<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='كسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/ث';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% ارتفاع/امتداد';
$ec_lang['u_grade']='ارتفاع/امتداد';
$ec_lang['u_in2']='بوصة مربعة';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='بوصة';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='ل/ث';
$ec_lang['u_m2']='م^2';
$ec_lang['u_m3ps']='م^3/ث';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='م ماء';
$ec_lang['u_mld']='ML/يوم';
$ec_lang['u_m']='م';
$ec_lang['u_mm2']='مم^2';
$ec_lang['u_mmh2o']='مم ماء';
$ec_lang['u_mm']='مم';
$ec_lang['u_mps']='م/ث';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='ثانية';
$ec_lang['u_lph']='ل/س';
$ec_lang['u_gph']='غال/س';
$ec_lang['u_mmph']='مم/س';
$ec_lang['u_inph']='بوصة/س';
$ec_lang['u_acft']='أكر-قدم';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='م^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/سنة';
$ec_lang['u_mwh_yr']='MWh/سنة';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='م^2/ث';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='حاسبات HawsEDC';
$ec_lang['menu_main_list']='قائمة الحاسبات';
$ec_lang['menu_main_hydraulics']='الهيدروليكا';
$ec_lang['menu_main_language']='اللغة';
$ec_lang['menu_more']='المزيد';
$ec_lang['template_welcome']='>> اتركوا مخاوفكم عند الباب؛ هنا نتحدث بالمحبة. أنتم لا تدمرون كل شيء. استمتعوا أيضاً بـ<a target="_blank" href="https://hawsedc.com/download.php">أدوات HawsEDC المجانية لـ AutoCAD.</a> <<';
$ec_lang['template_translation_help']='هل لديك رؤية رائعة لحاسبة تريد إضافتها هنا؟ هل يمكنك مساعدتي في تحسين الترجمات أو البرمجة أو استضافة هذه الحاسبات؟  ';
$ec_lang['template_feedback']='يرجى مشاركتنا ملاحظاتك القيّمة. هل فاقت هذه الحاسبة المجانية توقعاتك من كل جانب؟';
$ec_lang['template_printable_title']='عنوان للطباعة';
$ec_lang['template_printable_subtitle']='عنوان فرعي للطباعة';
$ec_lang['index_title']='حاسبات هندسية مجانية عبر الإنترنت';
$ec_lang['calc_set_units']='تحديد الوحدات:';
$ec_lang['calc_defaults']='القيم الافتراضية';
$ec_lang['calc_defaults_confirm']='إعادة تعيين الحاسبة إلى القيم الافتراضية؟';
$ec_lang['points_data_help']='(أو نسخ/لصق باستخدام منطقة البيانات)';
$ec_lang['points_data_title']='بيانات النقاط<br />(مفصولة بفاصلة أو مسافة جدولة)';
$ec_lang['points_data_copy']='نسخ';
$ec_lang['points_data_paste']='لصق';
$ec_lang['calc_inputs']='المدخلات';
$ec_lang['calc_results']='النتائج';
$ec_lang['view_hide_line']='[إخفاء هذا السطر]';
$ec_lang['view_printable']='نسخة قابلة للطباعة (أعد التحميل للاستعادة)';
$ec_lang['ec_name_label']='احفظ هذا الحساب:';
$ec_lang['ec_name_placeholder']='الاسم';
$ec_lang['ec_name_hint']='يحفظ المدخلات في عنوان URL للإشارات المرجعية واسترجاع السجل والمشاركة';
$ec_lang['calc_copy_link']='نسخ الرابط';
$ec_lang_intent['calc_copy_link']='';
$ec_lang['calc_copy_link_done']='تم النسخ!';
$ec_lang_intent['calc_copy_link_done']='';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='فاقد الضغط في الأنابيب — داركي-وايسباخ';
$ec_lang['dw_main_title']='حاسبة فاقد الضغط في الأنابيب داركي-وايسباخ المجانية عبر الإنترنت';
$ec_lang['dw_main_desc']='فاقد الضغط في الأنابيب بداركي-وايسباخ عند قطر وخشونة وتدفق معلومة';
$ec_lang['dw_roughness']='الخشونة، e';
$ec_lang['dw_roughness_tip']='<span title="ارتفاع خشونة داركي-وايسباخ" class="ec-tip">?</span>';
$ec_lang['dw_kinematic_viscosity']='اللزوجة الحركية، &nu; <span title="1×10⁻⁶ m²/s للماء النظيف عند 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='رقم رينولدز، Re';
$ec_lang['dw_flow_regime']='نظام الجريان';
$ec_lang['dw_regime_laminar']='صفحي';
$ec_lang['dw_regime_transitional']='انتقالي';
$ec_lang['dw_regime_turbulent']='مضطرب';
$ec_lang['dw_friction_factor_method']='طريقة معامل الاحتكاك';
$ec_lang['dw_friction_factor']='معامل الاحتكاك، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='فاقد الضغط في الأنابيب — هيزن-وليامز';
$ec_lang['hw_main_title']='حاسبة فاقد الضغط في الأنابيب هيزن-وليامز المجانية عبر الإنترنت';
$ec_lang['hw_main_desc']='فاقد الضغط في الأنابيب بهيزن-وليامز عند قطر وخشونة وتدفق معلومة';
$ec_lang['hw_hgl_1']='خط المتدرج الهيدروليكي المصبّ';
$ec_lang['hw_hgl_2']='خط المتدرج الهيدروليكي المنبع';
$ec_lang['hw_roughness']='معامل هيزن-وليامز، C';
// Manning Irregular
$ec_lang['mi_menu']='قناة غير منتظمة المقطع — مانينغ';
$ec_lang['mi_main_title']='الحاسبة المجانية عبر الإنترنت لقناة مانينغ غير المنتظمة المقطع';
$ec_lang['mi_main_desc']='حاسبة الجريان المنتظم بمعادلة مانينغ في قناة غير منتظمة المقطع';
$ec_lang['mi_waterSurfaceElevation']='منسوب سطح الماء';
$ec_lang['mi_q_617']='Q <span title="التدفق المركّب Q، باستخدام معامل خشونة مانينغ المركّب n لكل منطقة وفق معادلة تشاو 6-17، بافتراض تساوي السرعات" class="ec-tip">؟</span>';
$ec_lang['mi_xSecPoints']='نقاط المقطع العرضي';
$ec_lang['mi_groupPoint']='نقطة';
$ec_lang['mi_groupSegment']='قطعة';
$ec_lang['mi_groupRegion']='منطقة';
$ec_lang['mi_station']='محطة';
$ec_lang['mi_elevation']='منسوب';
$ec_lang['mi_d50in']='حجم<br />صخور<br />التبطين<br />الوسيط';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='حد منطقة R<sub>h</sub>، Q (ضفة)';
$ec_lang['mi_tau']='إجهاد القص القاعي &tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />مركّب';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='ملاحظات';
$ec_lang['mi_notes_1_term']='n المركّب';
$ec_lang['mi_notes_1_def']='تتبع هذه الحاسبة الدليل المرجعي لبرنامج HEC-RAS في حساب معامل الخشونة المركّب n للمنطقة، باستخدام تشاو (Chow) 1959، الصفحة 136، المعادلة 6-17 (وليست 6-18).';
$ec_lang['mi_notes_2_term']='تبطين الصخور';
$ec_lang['mi_notes_2_def']='استخدم حاسبة قناة مانينغ شبه المنحرفة لتصميم تبطين الصخور. هذه الحاسبة أنسب للمقاطع الطبيعية.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='جريان في الأنابيب — مانينغ';
$ec_lang['mpf_main_title']='حاسبة جريان الأنابيب بمانينغ المجانية عبر الإنترنت';
$ec_lang['mpf_main_desc']='جريان منتظم في الأنابيب بمعادلة مانينغ عند ميل وعمق معلومَين';
$ec_lang['mpf_spreadheet_notice']='راجع النسخة الجدولية من هذه الحاسبة';
$ec_lang['mpf_pipe_diameter']='قطر الأنبوب، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='معامل خشونة مانينغ، n';
$ec_lang['mpf_friction_slope']='ميل الاحتكاك (يساوي أحياناً <a target="_blank" href="../frictionslope.php">؟</a> ميل الأنبوب)، S<sub>f</sub>';
$ec_lang['mpf_depth_ratio']='نسبة عمق الجريان، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(انظر الملاحظات)';
$ec_lang['mpf_flow']='التدفق، Q';
$ec_lang['mpf_velocity']='السرعة، v';
$ec_lang['mpf_velocity_head']='الرأس الحركي، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='مساحة الجريان، A';
$ec_lang['mpf_pipe_area']='مساحة الأنبوب، A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='المساحة النسبية، A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='المحيط المبلل، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='نصف القطر الهيدروليكي، R<sub>h</sub>';
$ec_lang['mpf_top_width']='العرض العلوي، T';
$ec_lang['mpf_froude_number']='رقم فرود، Fr';
$ec_lang['mpf_shear_stress']='متوسط إجهاد القص (القوة الجارّة)، &tau;';
$ec_lang['mpf_full_flow']='الجريان الكامل، Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='النسبة إلى الجريان الكامل، Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>هذا هو الجريان والعمق داخل أنبوب <em>لانهائي الطول</em>.</dt><dd>قد يتطلب إدخال الجريان إلى الأنبوب منسوب مياه مرتفعاً بشكل كبير. أضف ما لا يقل عن 1.5 ضعف الرأس الحركي للحصول على منسوب المياه، أو <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">راجع درسي القصير مدته دقيقتان</a> لحسابات منسوب مياه الداخل للعبارات القياسية باستخدام HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='احسب y/d<sub>0</sub> لقيمة Q معطاة';
$ec_lang['mpf_solve_desc']='باستخدام d<sub>0</sub> وn وS<sub>f</sub> من نموذج الحاسبة، يجد أدنى y/d<sub>0</sub> لقيمة Q معطاة.';
$ec_lang['mpf_solve_button']='احسب';
$ec_lang['mpf_solver_enter_positive_q']='أدخل قيمة موجبة لـ Q المستهدف.';
$ec_lang_intent['mpf_solver_enter_positive_q']='';
$ec_lang['mpf_solver_no_solution']='لا يوجد حل: تتجاوز Q سعة الأنبوب عند y/d0 = 93.8% (Qmax = {qmax} بالوحدات المختارة).';
$ec_lang_intent['mpf_solver_no_solution']='';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='فاقد الضغط في الأنابيب — مانينغ';
$ec_lang['mphl_main_title']='حاسبة فاقد الضغط في الأنابيب بمانينغ المجانية عبر الإنترنت';
$ec_lang['mphl_main_desc']='فاقد الضغط بمعادلة مانينغ عند جريان كامل معلوم';
$ec_lang['mphl_pipe_length']='طول الأنبوب، L';
$ec_lang['mphl_area']='المساحة، A';
$ec_lang['mphl_total_junction_k']='معامل الفاقد الموضعي، k<sub>m</sub>';
$ec_lang['mphl_friction_slope']='ميل الاحتكاك';
$ec_lang['mphl_friction_loss']='فاقد الاحتكاك، h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='الفاقد الموضعي، h<sub>m</sub>';
$ec_lang['mphl_total_loss']='الفاقد الإجمالي، h<sub>L</sub>';
$ec_lang['mphl_egl_1']='خط الطاقة المصبّ';
$ec_lang['mphl_egl_2']='خط الطاقة المنبع';
$ec_lang['mphl_hgl_2']='خط المتدرج الهيدروليكي المنبع في الأنبوب ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>عند وجود مدخل مفتوح (عبّارة)، يجب التحقق من حالات التحكم عند المدخل.</dt><dd>1. لا يمكن أن يكون خط المتدرج الهيدروليكي المنبع أدنى من ارتفاع الجريان الطبيعي المنبع (ولا أدنى من الأنبوب!).</dd><dd>2. منسوب مياه الداخل للعبارة يُمثَّل بشكل أفضل بخط الطاقة المنبع بدلاً من خط المتدرج الهيدروليكي المنبع.</dd><dd>3. انظر <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">درسي القصير مدته دقيقتان</a> لحسابات منسوب مياه الداخل البسيطة للعبارات القياسية باستخدام HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='قناة شبه منحرفة — مانينغ';
$ec_lang['mtc_main_title']='الحاسبة المجانية عبر الإنترنت للقناة شبه المنحرفة بمعادلة مانينغ';
$ec_lang['mtc_main_desc']='الجريان المنتظم بمعادلة مانينغ في قناة شبه منحرفة عند انحدار وعمق معلومين';
$ec_lang['mtc_bottom_width']='عرض القاع، b';
$ec_lang['mtc_side_slope_1']='الميل الجانبي 1، z<sub>1</sub> (أفقي/رأسي)';
$ec_lang['mtc_side_slope_2']='الميل الجانبي 2، z<sub>2</sub> (أفقي/رأسي)';
$ec_lang['mtc_channel_slope']='انحدار القناة، S';
$ec_lang['mtc_flow_depth']='عمق الجريان، y';
$ec_lang['mtc_bend_angle']='زاوية الانحناء، β <a target="_blank" href="riprap-bend-angle.png" title="انقر لعرض الصورة">؟</a> (لتحديد حجم الريبراب)';
$ec_lang['mtc_sgrock']='الكثافة النوعية للصخور، sg <span title="القيمة النموذجية &asymp; 2.65 للصخور المكسّرة" class="ec-tip">؟</span>';
$ec_lang['mtc_d50_in']='حجم الصخور التصميمي، D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n لحجم الصخور التصميمي (طريقة Strickler)';
$ec_lang['mtc_n_blodgett']='n لحجم الصخور التصميمي (طريقة Blodgett)';
$ec_lang['mtc_n_bathurst']='n لحجم الصخور التصميمي (طريقة Bathurst)';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett مقابل Bathurst';
$ec_lang['mtc_d50_bottom']='حجم الصخور الزاوية المطلوب للقاع، D<sub>50</sub> (Isbash وMC) <span title="وفق Isbash (1936) ومقاطعة ماريكوبا (Maricopa County)، أريزونا، الولايات المتحدة." class="ec-tip">؟</span>';
$ec_lang['mtc_d50_z1']='حجم الصخور الزاوية المطلوب للميل الجانبي 1، D<sub>50</sub> (Isbash وMC) <span title="وفق Isbash (1936) ومقاطعة ماريكوبا (Maricopa County)، أريزونا، الولايات المتحدة." class="ec-tip">؟</span>';
$ec_lang['mtc_d50_z2']='حجم الصخور الزاوية المطلوب للميل الجانبي 2، D<sub>50</sub> (Isbash وMC) <span title="وفق Isbash (1936) ومقاطعة ماريكوبا (Maricopa County)، أريزونا، الولايات المتحدة." class="ec-tip">؟</span>';
$ec_lang['mtc_d50_mra']='حجم الصخور الزاوية المطلوب، D<sub>50</sub> (Maynord وRuff وAbt 1989)';
$ec_lang['mtc_d50_searcy']='حجم الصخور الزاوية المطلوب، D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_check']='فحص السرعة';
$ec_lang['mtc_vel_ok']='السرعة معقولة بالنسبة إلى افتراضات الجريان المنتظم.';
$ec_lang['mtc_vel_high']='السرعة عالية - تحقق من خسائر الانتقال، والطاقة المتاحة، وضربة المطرقة المائية.';
$ec_lang['mtc_vel_low']='السرعة منخفضة؛ خطر الترسّب.';
$ec_lang['mtc_vel_ok_short']='موافق';
$ec_lang['mtc_vel_high_short']='مرتفع';
$ec_lang['mtc_vel_low_short']='منخفض';
$ec_lang['mtc_note_1']='<dl><dt>التكرار التلقائي لتصميم حجم الصخور والخشونة</dt><dd>اختر خيار الخشونة (يُوصى بطريقة Blodgett–Bathurst) وخيار حجم الصخور التصميمي (يُوصى بطريقة Isbash). اضبط العمق ومعامل أمان حجم الصخور للوصول إلى التدفق المستهدف بحجم صخور موحّد. في كل مرة تُغيّر فيها أحد المدخلات، تكرر الحاسبة الخطوات التالية: 1. تُحسب الخشونة من حجم الصخور التصميمي. 2. تُنسخ قيمة الخشونة المحسوبة إلى حقل الخشونة المُدخلة. 3. يُحسب تدفق القناة وحجم الصخور المطلوب. 4. يُعدَّل حجم الصخور التصميمي. 5. تُكرَّر الخطوات حتى يصبح الخطأ في حجم الصخور التصميمي ضئيلاً جداً.</dd><dt>الحاسبة الأساسية (بدون تكرار)</dt><dd>أدخل قيمة الخشونة المطلوبة، وتجاهل منطقة إدخال حجم الصخور التصميمي.</dd></dl>';
$ec_lang['mtc_note_2_term']='فحص السرعة';
$ec_lang['mtc_note_2_def']='السرعة العالية تعني وجود هبوط كبير في المنسوب أدى إلى طاقة نوعية مرتفعة بهذا القدر. يمكن أن تُفقد هذه الطاقة بسرعة عند التوسعات أو الانحناءات أو العوائق. تحقق من أن ذلك معقول لموقع المشروع.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='جريان العتبة — البسيطة';
$ec_lang['ws_main_title']='حاسبة جريان العتبة عريضة العرف البسيطة المجانية عبر الإنترنت';
$ec_lang['ws_main_desc']='حاسبة جريان العتبة عريضة العرف البسيطة';
$ec_lang['ws_weirLength']='طول العتبة، L';
$ec_lang['ws_headWaterHeight']='الرأس، h';
$ec_lang['ws_weirCoefficient']='معامل العتبة، C<sub>w</sub>';
$ec_lang['ws_notes_heading']='ملاحظات';
$ec_lang['ws_notes_we_term']='معادلة العتبة';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='جريان العتبة — غير المنتظمة';
$ec_lang['wi_main_title']='حاسبة جريان العتبة غير المنتظمة، المجزأة ومتغيرة العمق، المجانية عبر الإنترنت';
$ec_lang['wi_main_desc']='حاسبة جريان العتبة غير المنتظمة';
$ec_lang['wi_headWaterelevation']='منسوب المياه العلوية';
$ec_lang['wi_weirPoints']='نقاط العتبة';
$ec_lang['wi_station']='محطة<br />(مسافة)';
$ec_lang['wi_elevation']='المنسوب';
$ec_lang['wi_pondingHeight']='ارتفاع التجميع';
$ec_lang['wi_incrementalFlow']='التدفق التدريجي';
$ec_lang['wi_cumulativeFlow']='التدفق التراكمي';
$ec_lang['wi_save_and_calculate']='حفظ وحساب';
$ec_lang['wi_notes_we_term']='معادلة العتبة';
$ec_lang['wi_notes_we_def']='q = إذا (الطول = 0) إذن 0؛ وإلا إذا (الميل=0) إذن cw*length*d<sub>0</sub><sup>1.5</sup>؛ وإلا cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) حيث d<sub>1</sub> وd<sub>0</sub> دائماً موجبتان أو صفر';
// Orifice Flow
$ec_lang['or_main_menu']='جريان الفتحة';
$ec_lang['or_main_title']='حاسبة جريان الفتحة المجانية عبر الإنترنت';
$ec_lang['or_main_desc']='جريان الفتحة — حر أو مغمور';
$ec_lang['or_shape']='شكل الفتحة';
$ec_lang['or_shape_circular']='دائري';
$ec_lang['or_shape_rectangular']='مستطيل';
$ec_lang['or_diameter']='القطر أو الارتفاع، D <span title="القطر للفتحة الدائرية؛ الارتفاع للفتحة المستطيلة" class="ec-tip">?</span>';
$ec_lang['or_width']='العرض، W <span title="للفتحات المستطيلة فقط" class="ec-tip">?</span>';
$ec_lang['or_invert']='منسوب القاع <span title="أسفل الفتحة" class="ec-tip">?</span>';
$ec_lang['or_hwe']='منسوب المياه العلوية';
$ec_lang['or_twe']='منسوب المياه السفلية';
$ec_lang['or_cd']='معامل التصريف، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='منسوب المركز الهندسي';
$ec_lang['or_head']='الرأس الفعّال، h';
$ec_lang['or_area']='مساحة الفتحة، A';
$ec_lang['or_flow']='التدفق، Q';
$ec_lang['or_velocity']='السرعة، v';
$ec_lang['or_regime']='فحص نظام الفتحة';
$ec_lang['or_regime_valid']='تصريف حر';
$ec_lang['or_regime_submerged']='فتحة مغمورة';
$ec_lang['or_regime_submerged_tip']='TWE فوق المركز الهندسي — نظام الفتحة لا يزال صالحاً';
$ec_lang['or_regime_warn']='خارج نظام الفتحة';
$ec_lang['or_regime_warn_tip']='المياه العلوية أدنى من تاج الفتحة';
$ec_lang['or_regime_twe_above_hwe']='تحقق من المدخلات';
$ec_lang['or_regime_twe_above_hwe_tip']='المياه السفلية (TWE) فوق المياه العلوية (HWE)';
$ec_lang['or_notes_1_term']='معادلة الفتحة';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). للتصريف الحر: h = HWE − المركز الهندسي. للجريان المغمور (TWE فوق قاع الفتحة): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='نظام الفتحة';
$ec_lang['or_notes_2_def']='تُطبَّق معادلات جريان الفتحة عندما يكون منسوب المياه العلوية فوق تاج (قمة) الفتحة. عندما تكون المياه العلوية أدنى من التاج، استخدم معادلة عتبة بدلاً من ذلك.';
$ec_lang['or_notes_3_term']='معامل التصريف';
$ec_lang['or_notes_3_def']='يتراوح C<sub>d</sub> من حوالي 0.60 إلى 0.65 للفتحات ذات الحافة الحادة. تستخدم المداخل المستديرة أو المعكوسة قيماً مختلفة. انظر <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> أو دليل مرجعية هيدروليكا HEC-RAS للإرشاد.';
$ec_lang['or_notes_4_term']='الغمر';
$ec_lang['or_notes_4_def']='عندما يكون TWE فوق قاع الفتحة، تُطبّق الحاسبة تلقائياً معادلة الفتحة المغمورة باستخدام h = HWE − TWE. عندما يكون TWE عند قاع الفتحة أو أدنى منه، يُفترض التصريف الحر وh = HWE − المركز الهندسي.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='الطاقة الكهرومائية الصغيرة';
$ec_lang['mhp_main_title']='حاسبة الطاقة الكهرومائية الصغيرة المجانية عبر الإنترنت';
$ec_lang['mhp_main_desc']='حاسبة إنتاج الطاقة الكهرومائية الصغيرة بنظام مجرى النهر';
$ec_lang['mhp_flow']='معدل التدفق، Q';
$ec_lang['mhp_gross_head']='الارتفاع الإجمالي، H<sub>gross</sub>';
$ec_lang['mhp_diameter']='قطر أنبوب الضغط، D';
$ec_lang['mhp_length']='الطول، L <span title="طول أنبوب أو قناة التوصيل من منشأة الرأس (headworks) إلى التوربين" class="ec-tip">?</span>';
$ec_lang['mhp_roughness']='خشونة الأنبوب، e';
$ec_lang['mhp_km']='معامل الخسارة الثانوية، k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='اللزوجة الحركية، ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='كفاءة المحطة، η (0–1)';
$ec_lang['mhp_velocity']='سرعة التدفق، v';
$ec_lang['mhp_vel_check']='فحص السرعة';
$ec_lang['mhp_f']='معامل الاحتكاك، f';
$ec_lang['mhp_hf']='فقد الضغط بالاحتكاك، h<sub>f</sub>';
$ec_lang['mhp_hm']='فقد الرأس الثانوي، h<sub>m</sub>';
$ec_lang['mhp_hl']='إجمالي فقد أنبوب الضغط، h<sub>L</sub>';
$ec_lang['mhp_hl_check']='فحص فقد الضغط';
$ec_lang['mhp_hnet']='الارتفاع الصافي، H<sub>net</sub>';
$ec_lang['mhp_power']='القدرة المنتجة، P';
$ec_lang['mhp_annual_kwh']='الطاقة السنوية عند سعة 100%';
$ec_lang['mhp_vel_low']='السرعة منخفضة؛ خطر الترسيب واحتباس الهواء.';
$ec_lang['mhp_vel_high']='السرعة مرتفعة؛ تحقق من فقد الانتقال، والطاقة المتاحة، والمطرقة المائية.';
$ec_lang['mhp_vel_ok_short']='جيد';
$ec_lang['mhp_vel_high_short']='مرتفع';
$ec_lang['mhp_vel_low_short']='منخفض';
$ec_lang['mhp_hl_ok']='ضمن هدف 10%';
$ec_lang['mhp_hl_warn']='يتجاوز هدف 10%';
$ec_lang['mhp_hl_warn_tip']='يُنصح باستخدام أنبوب أكبر';
$ec_lang['mhp_hl_bad']='يتجاوز 20%';
$ec_lang['mhp_hl_bad_tip']='أعد تحديد حجم الأنبوب';
$ec_lang['mhp_notes_1_term']='فقد الضغط';
$ec_lang['mhp_notes_1_def']='إجمالي فقد أنبوب الضغط h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، حيث h<sub>f</sub> = f(L/D)(v²/2g) هو فقد الاحتكاك وفق داركي-وايسباخ، وh<sub>m</sub> = k<sub>m</sub>·v²/2g يشمل المدخل والانحناءات والصمامات. الارتفاع الصافي H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='السرعة';
$ec_lang['mhp_notes_2_def']='تحقق من أن السرعة معقولة بالنسبة للانخفاض المتاح وتكلفة الأنبوب. السرعة المنخفضة جداً قد تدل على مبالغة في حجم الأنبوب؛ والسرعة المرتفعة جداً قد تزيد فقد الاحتكاك وخطر المطرقة المائية.';
$ec_lang['mhp_notes_3_term']='هدف فقد الضغط';
$ec_lang['mhp_notes_3_def']='يُعدّ فقد أنبوب الضغط أقل من 10% من الارتفاع الإجمالي اقتصادياً في الغالب. يقع التوازن الأمثل بين تكلفة الأنبوب والطاقة المفقودة عادة عند 4–6% حيث تكون الكهرباء أعلى قيمة.';
$ec_lang['mhp_notes_4_term']='الفواقد الموضعية، k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='تحدث هذه الفواقد عند وصلات الأنابيب والمداخل والانحناءات والصمامات — ووصف "ثانوية" اصطلاحي لكنه مضلل؛ ففي أنبوب ضغط قصير يمكن أن تساوي فواقد الاحتكاك أو تتجاوزها. قيم k النموذجية: مدخل حاد 0.5، كل انحناء 45° بين 0.2–0.3، بوابة مفتوحة بالكامل 0.1، صمام فراشة 0.2. اجمع جميع التجهيزات لقيمة k<sub>m</sub> الإجمالية. القيمة الافتراضية 1.5 تفترض مدخلاً واحداً وانحناءين.';
$ec_lang['mhp_notes_5_term']='خشونة الأنبوب e';
$ec_lang['mhp_notes_5_def']='الخشونة المطلقة النموذجية: فولاذ (جديد) 0.046 مم، فولاذ (مستعمل) 0.15 مم، HDPE 0.003 مم، PVC/uPVC 0.0015 مم، خرسانة 0.3–3 مم. HDPE شائع لأنابيب الضغط في محطات الطاقة المائية الصغيرة.';
$ec_lang['mhp_notes_6_term']='الكفاءة';
$ec_lang['mhp_notes_6_def']='تتراوح كفاءة المحطة النموذجية η من 0.70 إلى 0.85 لتوربينات Pelton والتوربينات العرضية الشائعة في محطات الطاقة المائية الصغيرة. استخدم 0.75 كتقدير أولي متحفظ.';
$ec_lang['mhp_notes_7_term']='الطاقة السنوية';
$ec_lang['mhp_notes_7_def']='تفترض الطاقة السنوية تشغيلاً متواصلاً بالتدفق الكامل (8760 ساعة/سنة). الإنتاج الفعلي سيكون أقل بسبب التباين الموسمي في التدفق وتوقف الصيانة ومعامل الحمل.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='وقت التصريف بالفتحة';
$ec_lang['odt_main_title']='حاسبة وقت التصريف بالفتحة — بركة أو حوض أو خزان — مجانية عبر الإنترنت';
$ec_lang['odt_main_desc']='وقت تصريف البركة أو الحوض بالفتحة — طريقة الحجم المخروطي';
$ec_lang['odt_h1_elev']='منسوب سطح الماء الابتدائي';
$ec_lang['odt_a1']='المساحة الابتدائية، A<sub>1</sub>';
$ec_lang['odt_h2_elev']='منسوب سطح الماء النهائي';
$ec_lang['odt_h_orifice']='منسوب المركز الهندسي للفتحة';
$ec_lang['odt_a0']='المساحة عند منسوب الفتحة، A<sub>0</sub>';
$ec_lang['odt_a_ending']='المساحة النهائية، A<sub>2</sub> <span title="مُستوفاة من النموذج المخروطي عند المنسوب النهائي" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='فحص المنسوب النهائي';
$ec_lang['odt_h2_ok']='المنسوب النهائي فوق قمة الفتحة';
$ec_lang['odt_h2_warn']='المنسوب النهائي عند قمة الفتحة أو أدناه';
$ec_lang['odt_h2_warn_tip']='قمة الفتحة = المركز الهندسي + D/2';
$ec_lang['odt_d']='فتحة D <span title="القطر (دائري) أو الارتفاع (مستطيل)" class="ec-tip">?</span>';
$ec_lang['odt_w']='عرض الفتحة، W <span title="للفتحات المستطيلة فقط" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='وقت التصريف (ثوانٍ)';
$ec_lang['odt_t_min']='وقت التصريف (دقائق)';
$ec_lang['odt_t_hr']='وقت التصريف (ساعات)';
$ec_lang['odt_t_day']='وقت التصريف (أيام)';
$ec_lang['odt_notes_1_term']='الصيغة';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) يعطي وقت التصريف من الرأس H إلى الفتحة. وقت التصريف = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، حيث H<sub>1</sub> = المنسوب الابتدائي − منسوب الفتحة، H<sub>2</sub> = المنسوب النهائي − منسوب الفتحة.';
$ec_lang['odt_notes_2_term']='الطريقة';
$ec_lang['odt_notes_2_def']='تُنمذج طريقة الحجم المخروطي البركة أو الحوض كمقطع مخروطي بين المساحة الابتدائية A<sub>1</sub> عند منسوب المياه الابتدائي والمساحة A<sub>0</sub> عند منسوب المركز الهندسي للفتحة. يُحسب A<sub>2</sub>، مساحة البركة عند المنسوب النهائي، بالاستيفاء من A<sub>1</sub> وA<sub>0</sub> باستخدام نموذج المقطع المخروطي. وقت التصريف من المنسوب الابتدائي إلى النهائي يساوي إجمالي وقت التصريف من H<sub>1</sub> إلى الفتحة ناقص وقت التصريف المتبقي من H<sub>2</sub> إلى الفتحة.';
$ec_lang['odt_h1']='الرأس الابتدائي، H<sub>1</sub> <span title="منسوب سطح الماء الابتدائي ناقص منسوب المركز الهندسي للفتحة" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='الحد الأقصى للتدفق، Q<sub>max</sub>';
$ec_lang['odt_vol']='الحجم المُصرَّف';
$ec_lang['odt_sketch_start']='البداية';
$ec_lang['odt_sketch_end']='النهاية';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='الري';
$ec_lang['irr_main_title']='حاسبات قياس تدفق الري المجانية عبر الإنترنت';
$ec_lang['irr_main_desc']='قياس تدفق الري — السدود والفتحات';
$ec_lang['irr_intro_html']='<p>السدود القياسية والفتحات هي الأدوات الميدانية المعيارية لقياس تدفق المياه في أنظمة الري. اختر الحاسبة التي تناسب منشأتك:</p>';
$ec_lang['irr_card_weir_uniform_head']='السد القياسي — ذو العتبة العريضة (عرض منتظم)';
$ec_lang['irr_card_weir_uniform_desc']='قِس التدفق فوق عتبة سد التحويل، أو منشأة تحكم، أو لوح سد. أدخل طول السد وعمق الماء فوق العتبة.';
$ec_lang['irr_card_weir_irregular_head']='السد القياسي — مقطع غير منتظم';
$ec_lang['irr_card_weir_irregular_desc']='استخدمه عندما يختلف ارتفاع عتبة السد أو مقطعها — كمفيض طبيعي، أو منشآت انحدار بعرض متغير، أو منشآت تحكم متعددة الأقسام.';
$ec_lang['irr_card_orifice_head']='الفتحة — بوابة الرأس أو مخرج الأنبوب';
$ec_lang['irr_card_orifice_desc']='قِس التدفق عبر بوابة انزلاقية أو مخرج أنبوب أو فتحة بردورة. يتعامل تلقائياً مع حالتَي التصريف الحر والغمر (ضغط المصب).';
$ec_lang['irr_card_canal_head']='تصميم القناة وتحليلها';
$ec_lang['irr_card_canal_desc']='صمّم قناة ري أو تحقق منها باستخدام معادلة مانينغ. استخدم حاسبة المقطع شبه المنحرف للقنوات الجديدة، وحاسبة المقطع غير المنتظم للمقاطع الطبيعية أو الإنشائية القائمة.';
$ec_lang['irr_card_seepage_head']='تسرب القنوات وكفاءة النقل';
$ec_lang['irr_card_seepage_desc']='قدِّر فقد التسرب من مقطع قناة باستخدام قياسات التدفق الوارد والصادر. احسب كفاءة النقل والفقد السنوي للمياه للمساعدة في تحديد أولويات استثمارات التبطين.';
$ec_lang['irr_quickref_html']='<h3>مرجع سريع</h3><dl><dt>سد تحويل أو منشأة تحكم</dt><dd>قِس عمق الماء فوق عتبة السد. استخدم <a href="Weir-Flow-Simple.php">السد القياسي البسيط</a> للعتبة المنتظمة، أو <a href="Weir-Flow-Irregular.php">السد القياسي غير المنتظم</a> للعتبة ذات المقطع المنحدر أو المتدرج.</dd><dt>بوابة رأس أو مخرج أنبوب</dt><dd>قِس منسوب الماء في المنبع والمصب (أو منسوب القاع عند التصريف الحر). استخدم <a href="Orifice.php">تدفق الفتحة</a>. للأنبوب الدائري، D = قطر الأنبوب؛ للبوابة المستطيلة، أدخل العرض W والارتفاع D.</dd><dt>وقت تفريغ خزان أو بركة</dt><dd>استخدم <a href="Orifice-Drain-Time.php">وقت تصريف الفتحة</a> لتقدير المدة اللازمة لخفض منسوب بركة أو خزان عبر فتحة في القاع — مفيد لتخطيط مخزون مياه الري.</dd><dt>المعايير الميدانية</dt><dd>معادلات تدفق السد والفتحة المستخدمة هنا تتوافق مع إجراءات <em>دليل قياس المياه</em> الصادر عن مكتب الاستصلاح الأمريكي (USBR) (الطبعة الثالثة)، وهي المطلوبة عادةً من قِبل مشرفي المياه وأقاليم الري.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='تباعد القطارات، S<sub>e</sub>';
$ec_lang['ip_sl']='تباعد الخطوط الجانبية، S<sub>l</sub>';
$ec_lang['ip_n_e']='عدد القطارات في الخط الجانبي، n<sub>e</sub>';
$ec_lang['ip_n_l']='عدد الخطوط الجانبية في المنطقة، n<sub>l</sub>';
$ec_lang['ip_d']='عمق التطبيق المستهدف، d';
$ec_lang['ip_a_e']='المساحة لكل قطارة، A<sub>e</sub>';
$ec_lang['ip_pr']='معدل التطبيق، PR';
$ec_lang['ip_q_lat']='التدفق لكل خط جانبي، Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='تدفق المنطقة، Q<sub>zone</sub>';
$ec_lang['ip_t_run']='وقت التشغيل (ساعات)';
// Irrigation Pressure
$ec_lang['ip_main_menu']='ضغط الري';
$ec_lang['ip_main_title']='حاسبة ضغط الري وانتظام التوزيع المجانية عبر الإنترنت';
$ec_lang['ip_main_desc']='اختبار ضغط الفرع وتقدير انتظام التوزيع';
$ec_lang['ip_h_supply']='ضغط الإمداد';
$ec_lang['ip_elev_supply']='منسوب الإمداد، z<sub>supply</sub>';
$ec_lang['ip_q_design']='تدفق القطارة التصميمي، q<sub>design</sub>';
$ec_lang['ip_h_design']='ضغط القطارة التصميمي';
$ec_lang['ip_x']='أس تصريف القطارة، x <span title="0.5 للقطارات القياسية غير المعوَّضة؛ قريب من 0 للقطارات المعوَّضة بالضغط" class="ec-tip">؟</span>';
$ec_lang['ip_reach_table_title']='مسار الاختبار';
$ec_lang['ip_group_reach']='قطاع';
$ec_lang['ip_group_upstream']='المنبع';
$ec_lang['ip_group_downstream']='المصب';
$ec_lang['ip_group_loss']='الفاقد';
$ec_lang['ip_is_lateral']='جانبي <span title="مفعّل: هذا القطاع جزء من الخط الجانبي للاختبار الذي تسحب منه القطارات الفردية الماء. معطّل: هذا القطاع خط رئيسي يمرر التدفق فقط إلى خطوط جانبية أخرى لا تقع على مسار الاختبار." class="ec-tip">؟</span>';
$ec_lang['ip_count']='قطارات <span title="صفوف الخطوط الجانبية: القطارات في هذا القطاع فقط. صفوف الخط الرئيسي: إجمالي القطارات في الخطوط الجانبية الأخرى غير هذا الخط، والمتفرعة من هذا القطاع. أما قطاع الخط الرئيسي المنتهي عند الخط الجانبي للاختبار، فيشمل أيضاً أي خطوط جانبية أبعد على طول الخط الرئيسي بعد تلك النقطة، أو التي تشارك الوصلة نفسها (كخط جانبي على الجانب المقابل) — إذ يتفرع تدفقها من هذا القطاع نفسه أيضاً." class="ec-tip">؟</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_e']='e <span title="ارتفاع الخشونة في معادلة داركي-وايسباخ" class="ec-tip">؟</span>';
$ec_lang['ip_km']='k<sub>m</sub> <span title="معامل فاقد ثانوي عام لتجهيزات هذا القطاع من وصلات وصمامات ومقرنات (الحد الأدنى المقترح ≥0.5)" class="ec-tip">؟</span>';
$ec_lang['ip_elev_ds']='منسوب المصب <span title="منسوب نهاية هذا القطاع من جهة المصب. اختياري في الصفوف الداخلية (الافتراضي: مستوٍ / نفس منسوب العقدة السابقة إذا تُرك فارغاً). مطلوب في الصف الأخير: هذه القيمة هي منسوب آخر قطارة، وهي التي تحدد ضغط الإمداد المطلوب مباشرة." class="ec-tip">؟</span>';
$ec_lang['ip_elev_ds_missing_warn']='منسوب آخر قطارة (الصف الأخير) تُرك فارغاً وافتُرض مستوياً — أدخله للحصول على نتيجة دقيقة';
$ec_lang['ip_flow']='التدفق';
$ec_lang['ip_press']='ضغط';
$ec_lang['ip_v']='V';
$ec_lang['ip_hv']='H<sub>v</sub>';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='h<sub>L</sub> <span title="إجمالي فاقد القطاع، h_f + h_m" class="ec-tip">؟</span>';
$ec_lang['ip_pressure_warn']='ضغط منخفض/سالب — تحقق من احتمال وجود حالات دون الضغط الجوي';
$ec_lang['ip_pressure_warn_short']='منخفض';
$ec_lang['ip_h_far']='ضغط آخر قطارة';
$ec_lang['ip_q_supply']='تدفق إمداد مسار الاختبار، Q<sub>supply</sub> <span title="التدفق الداخل إلى مسار الاختبار المنمذج فقط — للمنطقة/النظام كاملاً، انظر Q_zone في تصميم التطبيق أدناه." class="ec-tip">؟</span>';
$ec_lang['ip_q_critical']='تدفق آخر قطارة، q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='متوسط تدفق القطارة (الخط الجانبي للاختبار)، q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='فرق الضغط المقدَّر، المتوسط مقابل الخط الجانبي للاختبار <span title="مقدار ارتفاع (أو انخفاض) ضغط تشغيل الخط الجانبي المتوسط النموذجي مقارنةً بهذا الخط الجانبي للاختبار، حسب تقديرك. الخط الجانبي للاختبار مفترض عمداً ليكون أسوأ الحالات، لذا فإن متوسطه الخاص يقلل من تقدير متوسط الحقل الفعلي — إذا تُرك عند 0، فإن فحص الانتظام وأرقام تصميم التطبيق أدناه تستخدم متوسط الخط الجانبي للاختبار نفسه (وهو على الأرجح متفائل) كما هو." class="ec-tip">؟</span>';
$ec_lang['ip_q_avg_field']='تدفق القطارة المتوسط الحقلي المقدَّر، q<sub>avg,field</sub> <span title="يُعاد تقييم q_avg_lateral عند ضغط كل صف من الخطوط الجانبية مضافاً إليه فرق الضغط المُدخل أعلاه — في محاولة لتصحيح كون الخط الجانبي للاختبار هو الحالة الأسوأ المفترضة وليس الممثل الفعلي. يُغذّي كلاً من فحص الانتظام وقسم تصميم التطبيق أدناه." class="ec-tip">؟</span>';
$ec_lang['ip_du_estimate']='فحص الانتظام، q<sub>last</sub>/q<sub>avg,field</sub> <span title="تدفق آخر قطارة المحسوب مقسوماً على تدفق القطارة المتوسط الحقلي المقدَّر — هذا تقريب لانتظام التوزيع القياسي للربع الأدنى (متوسط المجموعة الدنيا ÷ متوسط المجتمع)؛ لكنه مأخوذ من عينة نموذجية صغيرة وتصحيح مقدَّر من المستخدم بدلاً من عينة إحصائية ميدانية كاملة. القيم المساوية لـ 1 أو أعلى ممكنة وصحيحة: فهي تعني فقط أن ضغط آخر قطارة يساوي أو يفوق متوسط الحقل المقدَّر، بحيث تكون قطارة أخرى هي نقطة الضغط الأدنى. قد يكون ذلك لأن آخر قطارة تقع في أرض منخفضة أو لأن تقدير فرق الضغط أصغر من اللازم." class="ec-tip">؟</span>';
$ec_lang['ip_worst_case_warn']='ضغط القطارة المختبرة أكبر من أو يساوي ضغط الإمداد. من المرجح أن هذه ليست قطارة أسوأ الحالات، أو يمكن استخدام أنابيب أصغر.';
$ec_lang['ip_q_ratio']='تدفق آخر قطارة ÷ التدفق التصميمي، q<sub>last</sub>/q<sub>design</sub> <span title="هذا مختلف عن تقريبنا لمقياس الانتظام القياسي." class="ec-tip">؟</span>';
$ec_lang['ip_no_solution']='لا يوجد حل: ضغط الإمداد المطلوب يتجاوز ضغط الإمداد المُدخل. زِد ضغط الإمداد، أو قلِّل الطلب، أو استخدم أنبوباً أكبر.';
$ec_lang['ip_notes_1_term']='الطريقة';
$ec_lang['ip_notes_1_def']='يُخمِّن الضغط عند آخر قطارة (الأبعد)، ثم يتراجع بخط تدرج الطاقة نحو الإمداد، قطاعاً تلو الآخر، مضيفاً فاقد الاحتكاك والفاقد الثانوي في الطريق. يُطرح الارتفاع ورأس السرعة عند كل عقدة للإبلاغ عن الضغط الفعلي هناك. يُعدَّل الضغط المخمَّن عند الطرف البعيد (بطريقة التنصيف) حتى يطابق ضغط الإمداد المطلوب المحسوب ضغط الإمداد المُدخل — وهي نفس مسألة الحلقة المغلقة التي يعالجها محلل تدفق الأنابيب في حاسبة جريان الأنابيب بمعادلة مانينغ، لكن ممتدة إلى شبكة متفرعة.';
$ec_lang['ip_notes_2_term']='قطاعات الخط الرئيسي مقابل الخط الجانبي';
$ec_lang['ip_notes_2_def']='كل صف هو قطاع واحد على طول المسار الهيدروليكي الأسوأ الوحيد (مسار الاختبار) من الإمداد إلى آخر قطارة. قطاع الخط الرئيسي يمرر التدفق فقط إلى الخطوط الجانبية التي لا تقع على مسار الاختبار، لذا فإن سحبه هو ضرب بسيط (التدفق التصميمي × إجمالي عدد القطارات في القطاع) — دون أي حساسية للضغط المحلي. الخط الرئيسي أنبوب جذعي مشترك، لذا يجب أن يشمل قطاع الخط الرئيسي المنتهي عند الخط الجانبي للاختبار ليس فقط الخطوط الجانبية الواقعة بين طرفيه، بل أيضاً أي خطوط جانبية أبعد على طول الخط الرئيسي بعد تلك النقطة، أو تشارك الوصلة نفسها (كخط جانبي على الجانب المقابل) — إذ يمر تدفقها عبر هذا القطاع نفسه قبل أن يتفرع، سواء ظهرت في مكان آخر بهذا الجدول أم لا. أما قطاع الخط الجانبي فهو جزء من الخط الجانبي للاختبار نفسه: يُحسب تصريف القطارة من الضغط المحلي الفعلي عبر المعادلة q = k&middot;H<sup>x</sup>، ويُخفَّض فاقد الاحتكاك بعامل Christiansen F(n) لمراعاة انخفاض التدفق مع سحب كل قطارة في القطاع للماء.';
$ec_lang['ip_notes_3_term']='القيود';
$ec_lang['ip_notes_3_def']='يُنمذج ضغط إمداد ثابتاً واحداً (بلا منحنى مضخة)، ومسار اختبار واحداً فقط (وليس الحقل بأكمله)، ومنحنى قطارة بمعاملين (اضبط الأس قريباً من 0 لتقريب قطارة معوَّضة بالضغط). يُبلَّغ عن نسبتي انتظام مختلفتين، أُبقيتا منفصلتين عمداً: q<sub>last</sub>/q<sub>avg,field</sub> تقريب لانتظام التوزيع القياسي للربع الأدنى (متوسط المجموعة الدنيا ÷ متوسط المجتمع)؛ لكنها مأخوذة من عينة نموذجية صغيرة وتصحيح مقدَّر من المستخدم بدلاً من العينة الإحصائية الميدانية الكاملة القياسية. كذلك، الخط الجانبي للاختبار مفترض عمداً ليكون أسوأ الحالات، لذا فإن متوسطه الخام غير المصحَّح كان سيقلل من تقدير متوسط الحقل الحقيقي ويجعل الانتظام يبدو أفضل مما هو عليه؛ وقد وُضع مُدخل فرق الضغط خصيصاً لموازنة هذا التحيز. تبقى القيم المساوية لـ 1 أو أعلى ممكنة: فهي تعني فقط أن ضغط آخر قطارة يساوي أو يفوق متوسط الحقل المقدَّر، بحيث تكون قطارة أخرى هي نقطة الضغط الأدنى. قد يكون ذلك لأن آخر قطارة تقع في أرض منخفضة أو لأن تقدير فرق الضغط أصغر من اللازم. أما q<sub>last</sub>/q<sub>design</sub> فهو فحص مختلف، غير متعلق بالانتظام، مقابل التدفق المقنَّن من المصنّع — مفيد لكشف نظام مرتفع أو منخفض الضغط عموماً، لكنه فحص منفصل يُقرأ إلى جانب رقم الانتظام، لأن التدفق التصميمي/المقنَّن مستقل عن متوسط ضغط تشغيل النظام الفعلي.';
$ec_lang['ip_notes_4_term']='المرجع';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. تستخدم معايير ASAE/ASABE لتصميم الري الدقيق نفس أسلوب حساب فاقد الاحتكاك متعدد المخارج.';
$ec_lang['ip_notes_5_term']='تصميم التطبيق';
$ec_lang['ip_notes_5_def']='يستخدم معدل التطبيق وتدفق النظام/المنطقة تدفق القطارة المتوسط الحقلي المقدَّر (q<sub>avg,field</sub> — متوسط الخط الجانبي للاختبار نفسه، مصحَّحاً بتقدير فرق الضغط المُدخل)، وليس معدلاً مخمَّناً: PR = q<sub>avg,field</sub> / A<sub>e</sub>، مُغذّى بالقيمة النموذجية المصحَّحة. التباعد وأعداد الخطوط الجانبية/القطارات على مستوى النظام مُدخلات منفصلة هنا لأن مسار الاختبار ينمذج فرعاً واحداً فقط هو أسوأ الحالات، وليس كل خط جانبي في الحقل.';
$ec_lang['irr_card_pressure_head']='ضغط الري والانتظام';
$ec_lang['irr_card_pressure_desc']='مثِّل مخطط الضغط والتدفق على طول فرع رئيسي-جانبي-قطارة لتقدير انتظام التوزيع من ضغط مسار الاختبار الفعلي، لا من معدل تدفق القطارة في الكتالوج فقط.';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='تسرب القنوات';
$ec_lang['cs_main_title']='حاسبة فقد تسرب القنوات وكفاءة النقل المجانية عبر الإنترنت';
$ec_lang['cs_main_desc']='فقد تسرب القناة وكفاءة النقل — طريقة التدفق الوارد والصادر';
$ec_lang['cs_Q_in']='التدفق الوارد، Q<sub>in</sub>';
$ec_lang['cs_Q_out']='التدفق الصادر، Q<sub>out</sub>';
$ec_lang['cs_L']='طول المقطع، L';
$ec_lang['cs_wp']='المحيط المبلل للمقطع العرضي للقناة، P<sub>w</sub>';
$ec_lang['cs_Q_loss']='معدل فقد التسرب، Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='فحص القياس';
$ec_lang['cs_pct_loss']='الكسر المفقود';
$ec_lang['cs_Ec']='كفاءة النقل، E<sub>c</sub>';
$ec_lang['cs_Ec_check']='تقييم الكفاءة';
$ec_lang['cs_Vol_day']='الحجم اليومي المفقود';
$ec_lang['cs_Vol_year']='الحجم السنوي المفقود';
$ec_lang['cs_Q_loss_per_L']='الفقد لكل وحدة طول، Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='قيمة المياه';
$ec_lang['cs_lining_cost']='تكلفة التبطين';
$ec_lang['cs_Ec_target']='هدف التبطين، E<sub>c,target</sub> <span title="كفاءة النقل المستهدفة بعد التبطين؛ كسر بين 0 و1" class="ec-tip">؟</span>';
$ec_lang['cs_lining_area']='مساحة التبطين، L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='القيمة السنوية المفقودة';
$ec_lang['cs_annual_value_recovered']='القيمة السنوية المستردة';
$ec_lang['cs_lining_total_cost']='إجمالي تكلفة التبطين';
$ec_lang['cs_payback_years']='فترة الاسترداد <span title="الاسترداد البسيط = إجمالي تكلفة التبطين ÷ القيمة السنوية المستردة" class="ec-tip">؟</span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — تسرب مكتشف';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — لا فقد قابل للقياس';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — تحقق من القياسات';
$ec_lang['cs_Ec_good']='جيد — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='مقبول — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='ضعيف — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_term']='الطريقة';
$ec_lang['cs_notes_1_def']='يُقدِّر أسلوب التدفق الوارد والصادر التسرب بقياس التدفق عند رأس مقطع القناة وذيله: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. كفاءة النقل E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. يفترض الحجم السنوي تشغيلاً مستمراً بالتدفق الكامل؛ والفقد الفعلي أقل في القنوات الموسمية أو ذات التدفق الجزئي.';
$ec_lang['cs_notes_2_term']='تقييمات الكفاءة';
$ec_lang['cs_notes_2_def']='القنوات الترابية غير المبطنة النموذجية: E<sub>c</sub> = 60&ndash;80%. القنوات الترابية جيدة الصيانة: 75&ndash;85%. القنوات المبطنة بالخرسانة: 90&ndash;98%. غالباً ما تبرر خسائر التسرب التي تتجاوز 30% من التدفق الوارد استثمار التبطين. (USBR، FAO)';
$ec_lang['cs_notes_3_term']='استرداد تكلفة التبطين';
$ec_lang['cs_notes_3_def']='أدخل قيمة المياه وتكلفة التبطين بأي عملة متسقة. مساحة التبطين = طول المقطع &times; المحيط المبلل — وهو المحيط المبلل لمقطع القناة العرضي عند عمق الجريان المقاس (عرض القاع مضافاً إليه الجانبان المبللان). تفترض القيمة السنوية المستردة أن القناة المبطنة تحقق E<sub>c</sub> المستهدفة باستمرار. سيكون الاسترداد الفعلي أطول للقنوات الموسمية أو إذا لم يبلغ التبطين الكفاءة المستهدفة.';
$ec_lang['cs_notes_4_term']='المرجع';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>، الطبعة الثالثة (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='حول';
$ec_lang['install_main_menu']='تثبيت';
$ec_lang['install_main_title']='تثبيت EngCalcs';
$ec_lang['install_main_desc']='أضفه إلى جهازك للاستخدام دون اتصال';
$ec_lang['contact_main_menu']='تواصل';
$ec_lang['about_main_title']='حول حاسبات HawsEDC الهندسية';
$ec_lang['about_main_desc']='الرسالة، المصدر المفتوح، والمساهمة';
$ec_lang['about_body_html']='<h3>الرسالة</h3><p>وُجدت حاسبات HawsEDC الهندسية لخدمة المهندسين والعاملين الميدانيين حول العالم — ولا سيما أولئك الذين يعملون في المناطق الشحيحة المياه أو المحدودة الموارد أو المحرومة. هذه الأدوات جزء من رسالة إنسانية أشمل: إخبار كل إنسان بأكثر الطرق عملية وفاعلية أنه محبوب وعزيز إلى الأبد، وأنه لا يخشى شيئاً، وأنه لن يدمّر كل شيء.</p><p>الحاسبات هي الوسيلة، والهدف عالم خالٍ من المعاناة.</p><h3>ترخيص المصدر المفتوح</h3><p>يُصدَر الكود كاملاً تحت <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">رخصة GNU العامة الشاملة الإصدار 3.0 أو أحدث</a> — حراً كما هو الحرية. يمكنك استخدام الكود ودراسته وتعديله وإعادة توزيعه وفق الشروط ذاتها.</p><p>حقوق النشر © 2009–2026 Thomas Gail Haws.</p><h3>الكود المصدري</h3><p>الكود المصدري الكامل متاح للعموم على Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>يمكنك تصفح الكود وتسجيل المشكلات أو تفريع المستودع هناك.</p><h3>المساهمة</h3><p>طلبات السحب مرحَّب بها. طرق المساهمة:</p><ul><li><strong>الترجمة</strong> — حسِّن أو أضف لغة. افتح طلب سحب بتغييرات على ملف <code>lib/lang.ec.??.php</code> المعني.</li><li><strong>تقارير الأخطاء</strong> — استخدم نموذج الملاحظات في أي صفحة حاسبة، أو سجّل مشكلة على Bitbucket.</li><li><strong>حاسبات جديدة</strong> — أفكار لأدوات هندسة هيدروليكية تخدم العاملين الميدانيين وممارسي الري مرحَّب بها بشكل خاص. راجع دليل المطور <code>CLAUDE.md</code> في المستودع.</li><li><strong>الاستضافة</strong> — إن كنت تستطيع استضافة مرآة لهذه الحاسبات في منطقة ذات اتصال محدود، يُرجى التواصل معنا.</li></ul><h3>الاستخدام دون اتصال</h3><p>تعمل هذه الآلات الحاسبة كتطبيق ويب تقدمي (PWA). قم بزيارة أي صفحة حاسبة أثناء اتصالك بالإنترنت، وسيقوم متصفحك تلقائياً بتخزين جميع الآلات الحاسبة في ذاكرة التخزين المؤقت. بعد ذلك، تعمل جميع الآلات الحاسبة دون اتصال — لا حاجة للإنترنت.</p><p>على Android أو iOS، استخدم خيار "إضافة إلى الشاشة الرئيسية" في متصفحك لتثبيت EngCalcs كتطبيق على جهازك. على سطح المكتب، ابحث عن أيقونة التثبيت في شريط العنوان.</p><p>يمكنك أيضاً حفظ أي حاسبة منفردة باستخدام قائمة "حفظ باسم…" في متصفحك للاستخدام غير المتصل لمرة واحدة.</p><h3>التواصل</h3><p>Tom Haws — مهندس هيدروليكي ومؤلف هذه الحاسبات.<br />استخدم نموذج الملاحظات في أي صفحة حاسبة، أو تصفح الكود المصدري على <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='التواصل مع HawsEDC';
$ec_lang['contactSendMessage']='أرسل رسالة إلى Tom Haws';
$ec_lang['contactYourName']='اسمك:';
$ec_lang['contactYourEmail']='عنوان بريدك الإلكتروني:';
$ec_lang['contactSubject']='الموضوع:';
$ec_lang['contact_message']='الرسالة:';
$ec_lang['contactSpamPrefix']='خمسة زائد واحد يساوي';
$ec_lang['contactSpamPostfix']='(يرجى كتابتها بالحروف. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='إرسال الرسالة';
$ec_lang['contact_success']='شكراً لك على تخصيص الوقت للكتابة.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='تصميم المزلق الصخري (Robinson)';
$ec_lang['rc_main_title']='حاسبة تصميم المزلق الصخري المجانية عبر الإنترنت — Robinson (1998)';
$ec_lang['rc_main_desc']='تحديد حجم الحجارة في المزلق الصخري — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='انحدار قاع المزلق، S<sub>0</sub>';
$ec_lang['rc_qt']='التصريف الوحدوي الإجمالي، q<sub>t</sub> <span title="التدفق لكل وحدة عرض عند مدخل المزلق. لقناة بعرض قاع B وتدفق إجمالي Q، استخدم q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='مسامية الحجارة، n<sub>p</sub>';
$ec_lang['rc_sg']='الكثافة النسبية للصخر، sg <span title="الجرانيت أو البازلت المكسور النموذجي ≈ 2.65. نطاق Robinson الصحيح: 2.54 إلى 2.82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='انحراف التدرج SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="الانحراف المعياري للتدرج. الصخر المنتظم ≈ 1.25. نطاق Robinson الصحيح: 1.15 إلى 1.47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='العمق الطبيعي في قناة المدخل، y<sub>n</sub> <span title="تجمّع المياه (Hp > yn) جيد — يقلل التآكل في أعلى المجرى. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='حجم الصخر الوسيط المطلوب، D<sub>50</sub> <span title="المعادلة 1 (S0 < 0.10) أو المعادلة 2 (0.10-0.40). الصحيح: D50 من 15 إلى 278 مم، S0 من 0.02 إلى 0.40. خارج النطاق: قيم خارج المعايرة." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='المعادلة المطبّقة';
$ec_lang['rc_sg_check']='فحص الكثافة النسبية';
$ec_lang['rc_SD_check']='فحص انحراف التدرج SD';
$ec_lang['rc_sg_ok']   ='sg ضمن النطاق الصحيح';
$ec_lang['rc_sg_ok_tip']='2.54–2.82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg أقل من نطاق Robinson';
$ec_lang['rc_sg_low_tip']='النطاق الصحيح: 2.54–2.82';
$ec_lang['rc_sg_high'] ='sg أعلى من نطاق Robinson';
$ec_lang['rc_sg_high_tip']='النطاق الصحيح: 2.54–2.82';
$ec_lang['rc_SD_ok']   ='SD ضمن النطاق الصحيح';
$ec_lang['rc_SD_ok_tip']='1.15–1.47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD أقل من نطاق Robinson';
$ec_lang['rc_SD_low_tip']='النطاق الصحيح: 1.15–1.47';
$ec_lang['rc_SD_high'] ='SD أعلى من نطاق Robinson';
$ec_lang['rc_SD_high_tip']='النطاق الصحيح: 1.15–1.47';
$ec_lang['rc_layer']='سماكة طبقة الحجارة (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='نصف قطر منحنى التاج العلوي (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='طول قوس منحنى التاج العلوي';
$ec_lang['rc_apron_length']='طول مصطبة المخرج (15 × D<sub>50</sub>) <span title="مطلوب للدعم الإنشائي لحجارة المزلق. “الحد الأدنى لعمق مياه الذيل الناتج عن قطاع المخرج ومقاومة قناة أسفل المجرى كافٍ لضمان استقرار حجارة الحماية في قطاع المخرج.” (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='معامل خشونة Manning في المزلق، n';
$ec_lang['rc_Vm']='السرعة عبر غطاء الصخر، V<sub>m</sub> <span title="نسبة من qt تتدفق عبر مسام الحجارة. الباقي qs يتدفق على السطح. الافتراضي np = 0.45 للصخر المكسور الزاوي." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='التدفق الوحدوي عبر الغطاء، q<sub>m</sub>';
$ec_lang['rc_qs']='التدفق الوحدوي السطحي، q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='عمق التدفق فوق سطح الحجارة، d';
$ec_lang['rc_Hp']='علو المياه فوق الهدار عند المدخل، H<sub>p</sub> <span title="تجمّع المياه (Hp > yn) جيد — يقلل التآكل في أعلى المجرى. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='فحص تجمّع المياه عند المدخل';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — تجمّع مياه في أعلى المجرى';
$ec_lang['rc_pond_ok_tip']='تجمّع المياه في أعلى مدخل المزلق أمر جيد؛ فهو يقلل التآكل في أعلى المجرى. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — لا يوجد تجمّع للمياه — احتمال تآكل عند المدخل';
$ec_lang['rc_pond_warn_tip']='لا يوجد تجمّع للمياه في أعلى مدخل المزلق؛ قد يحدث تآكل في أعلى المجرى. (USDA)';
$ec_lang['rc_eq1']='المعادلة 1 (S<sub>0</sub> < 0.10) — انحدار لطيف';
$ec_lang['rc_eq2']='المعادلة 2 (0.10 ≤ S<sub>0</sub> ≤ 0.40) — انحدار حاد';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0.02 — أقل من نطاق التحقق لدى Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0.40 — أعلى من نطاق التحقق لدى Robinson';
$ec_lang['rc_notes_1_term']='معادلات تحديد حجم الصخر';
$ec_lang['rc_notes_1_def']='طوّر Robinson, Rice & Kadavy (1998) معادلتين تجريبيتين لحجم الحجارة الوسيط D<sub>50</sub> بناءً على انحدار المزلق والتصريف الوحدوي. تُطبَّق المعادلة 1 للانحدارات اللطيفة (S<sub>0</sub> < 0.10)؛ وتُطبَّق المعادلة 2 للانحدارات الحادة (0.10 ≤ S<sub>0</sub> ≤ 0.40). كلتا المعادلتين تستلزمان q<sub>t</sub> بوحدة m²/s وتُعيدان D<sub>50</sub> بالمليمتر. النطاق المعتمد هو 0.02 ≤ S<sub>0</sub> ≤ 0.40.';
$ec_lang['rc_notes_2_term']='التصريف الوحدوي';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> هو التصريف الوحدوي الإجمالي عند تاج المزلق (إجمالي التدفق لكل وحدة عرض). لقناة بعرض قاع B تحمل تدفقاً إجمالياً Q، يُقدَّر q<sub>t</sub> ≈ Q / B، أو يُحسب من شرط العمق الحرج عند مدخل المزلق.';
$ec_lang['rc_notes_3_term']='التدفق عبر غطاء الصخر';
$ec_lang['rc_notes_3_def']='جزء من التدفق الكلي يمر عبر مسام الحجارة (تدفق الغطاء q<sub>m</sub>)؛ والباقي يتدفق فوق سطح الصخر (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). يُحسب عمق التدفق d بتطبيق معادلة Manning على التدفق السطحي q<sub>s</sub> باستخدام خشونة المزلق n. المسامية الافتراضية n<sub>p</sub> = 0.45 نموذجية للصخر المكسور الزاوي.';
$ec_lang['rc_notes_5_term']='نطاق حجم الصخر الصحيح';
$ec_lang['rc_notes_5_def']='طُوِّرت المعادلات باستخدام نطاق D<sub>50</sub> من 15 مم إلى 278 مم. النتائج خارج هذا النطاق تُعدّ استقراءً وينبغي استخدامها بحكم هندسي إضافي.';
$ec_lang['rc_notes_6_term']='منسوب مصطبة المخرج';
$ec_lang['rc_notes_6_def']='ينبغي أن يكون منسوب أعلى حجارة الحماية في قطاع المخرج مساوياً لمنسوب قاع القناة في أسفل المجرى أو أقل منه. إذا كان أعلى، فستكون حجارة المخرج غير مستقرة.';
$ec_lang['rc_notes_7_def']='عندما يكون العمق الطبيعي في قناة المدخل أقل من علو المياه فوق الهدار (H<sub>p</sub>) اللازم لتمرير q<sub>t</sub>، يحدث تدفق مقيّد أو تجمّع للمياه في أعلى مدخل المزلق. هذا مقبول عموماً — فتجمّع المياه يقلل السرعة ويمنع التآكل في أعلى المجرى. للتحقق: استخدم حاسبة تدفق الهدار لإيجاد H<sub>p</sub> لقيمة q<sub>t</sub> وعرض التاج المعطيين، وقارِن الناتج بالعمق الطبيعي لقناة المدخل. إذا تجاوز H<sub>p</sub> العمق الطبيعي، سيحدث تجمّع للمياه.';
$ec_lang['rc_notes_4_term']='المرجع';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. تنشر وزارة الزراعة الأمريكية (USDA ARS) أيضاً <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">جدول Excel</a> يعتمد على نفس الطريقة.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'مرشح';
$ec_lang['rc_sketch_top_crest_curve'] = 'منحنى القمة';
$ec_lang['rc_sketch_outlet_apron']    = 'مصطبة المخرج';
$ec_lang['rc_sketch_radius']          = 'نصف القطر';
