<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='كسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/ث';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% ارتفاع/امتداد';
$ec_lang['u_grade']='ارتفاع/امتداد';
$ec_lang['u_in2']='بوصة مربعة';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='بوصة';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='ل/ث';
$ec_lang['u_m2']='م^2';
$ec_lang['u_m3ps']='م^3/ث';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='م ماء';
$ec_lang['u_mld']='Ml/يوم';
$ec_lang['u_m']='م';
$ec_lang['u_mm2']='مم^2';
$ec_lang['u_mmh2o']='مم ماء';
$ec_lang['u_mm']='مم';
$ec_lang['u_mps']='م/ث';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='ثانية';
$ec_lang['u_acft']='أكر-قدم';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='م^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='حاسبات HawsEDC';
$ec_lang['menu_main_list']='قائمة الحاسبات';
$ec_lang['menu_main_hydraulics']='الهيدروليكا';
$ec_lang['menu_main_language']='اللغة';
$ec_lang['template_welcome']='&gt;&gt; اتركوا مخاوفكم عند الباب؛ هنا نتحدث بالمحبة. أنتم لا تدمرون كل شيء. استمتعوا أيضاً بـ<a target="_blank" href="https://hawsedc.com/download.php">أدوات HawsEDC المجانية لـ AutoCAD.</a> &lt;&lt;';
$ec_lang['template_translation_help']='هل لديك رؤية رائعة لحاسبة تريد إضافتها هنا؟ هل يمكنك مساعدتي في تحسين الترجمات أو البرمجة أو استضافة هذه الحاسبات؟  ';
$ec_lang['template_feedback']='يرجى مشاركتنا ملاحظاتك القيّمة. هل فاقت هذه الحاسبة المجانية توقعاتك من كل جانب؟';
$ec_lang['template_printable_title']='عنوان للطباعة';
$ec_lang['template_printable_subtitle']='عنوان فرعي للطباعة';
$ec_lang['index_title']='حاسبات هندسية مجانية عبر الإنترنت';
$ec_lang['calc_set_units']='تحديد الوحدات:';
$ec_lang['points_data_help']='(أو نسخ/لصق باستخدام منطقة البيانات)';
$ec_lang['points_data_title']='بيانات النقاط<br />(مفصولة بفاصلة أو مسافة جدولة)';
$ec_lang['points_data_copy']='نسخ';
$ec_lang['points_data_paste']='لصق';
$ec_lang['calc_inputs']='المدخلات';
$ec_lang['calc_results']='النتائج';
$ec_lang['view_hide_line']='[إخفاء هذا السطر]';
$ec_lang['view_printable']='نسخة قابلة للطباعة (أعد التحميل للاستعادة)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='فاقد الضغط في الأنابيب — داركي-وايسباخ';
$ec_lang['dw_main_title']='حاسبة فاقد الضغط في الأنابيب داركي-وايسباخ المجانية عبر الإنترنت';
$ec_lang['dw_main_desc']='فاقد الضغط في الأنابيب بداركي-وايسباخ عند قطر وخشونة وتدفق معلومة';
$ec_lang['dw_roughness']='الخشونة المطلقة داركي-وايسباخ، e';
$ec_lang['dw_kinematic_viscosity']='اللزوجة الحركية، v، بوحدة م<sup>2</sup>/ث (1E-6 للماء النقي في درجة حرارة الغرفة)';
$ec_lang['dw_reynolds_number']='رقم رينولدز، Re';
$ec_lang['dw_flow_regime']='نظام الجريان';
$ec_lang['dw_regime_laminar']='صفحي';
$ec_lang['dw_regime_transitional']='انتقالي';
$ec_lang['dw_regime_turbulent']='مضطرب';
$ec_lang['dw_friction_factor_method']='طريقة معامل الاحتكاك';
$ec_lang['dw_friction_factor']='معامل الاحتكاك، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='فاقد الضغط في الأنابيب — هيزن-وليامز';
$ec_lang['hw_main_title']='حاسبة فاقد الضغط في الأنابيب هيزن-وليامز المجانية عبر الإنترنت';
$ec_lang['hw_main_desc']='فاقد الضغط في الأنابيب بهيزن-وليامز عند قطر وخشونة وتدفق معلومة';
$ec_lang['hw_hgl_1']='خط المتدرج الهيدروليكي المصبّ';
$ec_lang['hw_hgl_2']='خط المتدرج الهيدروليكي المنبع';
$ec_lang['hw_roughness']='معامل هيزن-وليامز، C';
// Manning Irregular
$ec_lang['mi_menu']='قناة شاذة الشكل — مانينغ';
$ec_lang['mi_main_title']='حاسبة القناة شاذة الشكل بمانينغ المجانية عبر الإنترنت';
$ec_lang['mi_main_desc']='حاسبة الجريان المنتظم في القناة شاذة الشكل بمانينغ';
$ec_lang['mi_waterSurfaceElevation']='منسوب سطح الماء';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='نقاط المقطع العرضي';
$ec_lang['mi_groupPoint']='نقطة';
$ec_lang['mi_groupSegment']='قطعة';
$ec_lang['mi_groupRegion']='منطقة';
$ec_lang['mi_station']='محطة';
$ec_lang['mi_elevation']='منسوب';
$ec_lang['mi_d50in']='حجم<br />صخور<br />التبطين<br />الوسطي';
$ec_lang['mi_n']='n<br />للقطعة';
$ec_lang['mi_is_bank']='R<sub>h</sub>، Q<br />حدود<br />المنطقة<br />(ضفة)';
$ec_lang['mi_tau']='إجهاد<br />القاعدة<br />&tau;'; //no
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />مركّب';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='ملاحظات';
$ec_lang['mi_notes_1_term']='n المركّب';
$ec_lang['mi_notes_1_def']='تتبع هذه الحاسبة دليل مرجعية HEC-RAS في حساب n المركّب للمنطقة باستخدام Chow 1959، الصفحة 136، المعادلة 6-17 (وليس 6-18).';
$ec_lang['mi_notes_2_term']='تبطين الصخور';
$ec_lang['mi_notes_2_def']='استخدم حاسبة القناة الاحتجازية بمانينغ لتصميم تبطين الصخور. هذه الحاسبة أكثر ملاءمة للمقاطع الطبيعية.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='جريان في الأنابيب — مانينغ';
$ec_lang['mpf_main_title']='حاسبة جريان الأنابيب بمانينغ المجانية عبر الإنترنت';
$ec_lang['mpf_main_desc']='جريان منتظم في الأنابيب بمعادلة مانينغ عند ميل وعمق معلومَين';
$ec_lang['mpf_spreadheet_notice']='راجع النسخة الجدولية من هذه الحاسبة';
$ec_lang['mpf_pipe_diameter']='قطر الأنبوب، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='معامل خشونة مانينغ، n';
$ec_lang['mpf_friction_slope']='ميل الضغط (يمكن أن يساوي <a target="_blank" href="../pressureslope.php">؟</a> ميل الأنبوب)، S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='نسبة عمق الجريان، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(انظر الملاحظات)';
$ec_lang['mpf_flow']='التدفق، Q';
$ec_lang['mpf_velocity']='السرعة، v';
$ec_lang['mpf_velocity_head']='الرأس الحركي، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='مساحة الجريان، a';
$ec_lang['mpf_pipe_area']='مساحة الأنبوب، a0';
$ec_lang['mpf_area_ratio']='النسبة النسبية، a/a0';
$ec_lang['mpf_wetted_perimeter']='المحيط المبلل، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='نصف القطر الهيدروليكي، R<sub>h</sub>';
$ec_lang['mpf_top_width']='العرض العلوي، T';
$ec_lang['mpf_froude_number']='رقم فرود، F';
$ec_lang['mpf_shear_stress']='متوسط إجهاد القص (القوة الجارّة)، tau';
$ec_lang['mpf_full_flow']='الجريان الكامل، Q0';
$ec_lang['mpf_full_flow_ratio']='النسبة إلى الجريان الكامل، Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>هذا هو الجريان والعمق داخل أنبوب <em>لانهائي الطول</em>.</dt><dd>قد يتطلب إدخال الجريان إلى الأنبوب منسوب مياه مرتفعاً بشكل كبير. أضف ما لا يقل عن 1.5 ضعف الرأس الحركي للحصول على منسوب المياه، أو <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">راجع درسي القصير مدته دقيقتان</a> لحسابات منسوب مياه الداخل للعبارات القياسية باستخدام HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='احسب y/d<sub>0</sub> لقيمة Q معطاة';
$ec_lang['mpf_solve_desc']='باستخدام D<sub>0</sub> وn وS<sub>0</sub> من نموذج الحاسبة، يجد أدنى y/d<sub>0</sub> لقيمة Q معطاة.';
$ec_lang['mpf_solve_button']='احسب';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='فاقد الضغط في الأنابيب — مانينغ';
$ec_lang['mphl_main_title']='حاسبة فاقد الضغط في الأنابيب بمانينغ المجانية عبر الإنترنت';
$ec_lang['mphl_main_desc']='فاقد الضغط بمعادلة مانينغ عند جريان كامل معلوم';
$ec_lang['mphl_pipe_length']='طول الأنبوب، L';
$ec_lang['mphl_pipe_length']='طول الأنبوب، L';
$ec_lang['mphl_area']='المساحة، A';
$ec_lang['mphl_total_junction_k']='إجمالي معامل فاقد الوصلة المركّب، k';
$ec_lang['mphl_friction_slope']='ميل الاحتكاك';
$ec_lang['mphl_friction_loss']='فاقد الاحتكاك، H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='فاقد الوصلة، H<sub>m</sub>';
$ec_lang['mphl_total_loss']='الفاقد الإجمالي، H<sub>l</sub>';
$ec_lang['mphl_egl_1']='خط الطاقة المصبّ';
$ec_lang['mphl_egl_2']='خط الطاقة المنبع';
$ec_lang['mphl_hgl_2']='خط المتدرج الهيدروليكي المنبع في الأنبوب ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>عند وجود مدخل مفتوح (عبّارة)، يجب التحقق من حالات التحكم عند المدخل.</dt><dd>1. لا يمكن أن يكون خط المتدرج الهيدروليكي المنبع أدنى من ارتفاع الجريان الطبيعي المنبع (ولا أدنى من الأنبوب!).</dd><dd>2. منسوب مياه الداخل للعبارة يُمثَّل بشكل أفضل بخط الطاقة المنبع بدلاً من خط المتدرج الهيدروليكي المنبع.</dd><dd>3. انظر <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">درسي القصير مدته دقيقتان</a> لحسابات منسوب مياه الداخل البسيطة للعبارات القياسية باستخدام HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='قناة احتجازية — مانينغ';
$ec_lang['mtc_main_title']='حاسبة القناة الاحتجازية بمعادلة مانينغ المجانية عبر الإنترنت';
$ec_lang['mtc_main_desc']='جريان منتظم في قناة احتجازية بمعادلة مانينغ عند ميل وعمق معلومَين';
$ec_lang['mtc_bottom_width']='عرض القاع، b';
$ec_lang['mtc_side_slope_1']='الميل الجانبي 1 (أفقي/رأسي)';
$ec_lang['mtc_side_slope_2']='الميل الجانبي 2 (أفقي/رأسي)';
$ec_lang['mtc_channel_slope']='ميل القناة، S';
$ec_lang['mtc_flow_depth']='عمق الجريان، y';
$ec_lang['mtc_bend_angle']='زاوية الانحناء <a target="_blank" href="riprap-bend-angle.png" title="انقر للصورة">؟</a> (لتصميم حجم الريبراب)';
$ec_lang['mtc_sgrock']='الكثافة النسبية للصخور (2.65)';
$ec_lang['mtc_d50_in']='حجم الصخور التصميمي، D50';
$ec_lang['mtc_n_strickler']='n لحجم الصخور التصميمي بطريقة Strickler';
$ec_lang['mtc_n_blodgett']='n لحجم الصخور التصميمي بطريقة Blodgett';
$ec_lang['mtc_n_bathurst']='n لحجم الصخور التصميمي بطريقة Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett مقابل Bathurst';
$ec_lang['mtc_d50_bottom']='حجم الريبراب الزاوي المطلوب للقاع، D50 (Isbash ومقاطعة ماريكوبا) <a href="javascript:alert(\'بحسب Isbash (1936) ومقاطعة ماريكوبا، أريزونا، الولايات المتحدة.\')">؟</a>';
$ec_lang['mtc_d50_z1']='حجم الريبراب الزاوي المطلوب للميل الجانبي 1، D50 (Isbash ومقاطعة ماريكوبا) <a href="javascript:alert(\'بحسب Isbash (1936) ومقاطعة ماريكوبا، أريزونا، الولايات المتحدة.\')">؟</a>';
$ec_lang['mtc_d50_z2']='حجم الريبراب الزاوي المطلوب للميل الجانبي 2، D50 (Isbash ومقاطعة ماريكوبا) <a href="javascript:alert(\'بحسب Isbash (1936) ومقاطعة ماريكوبا، أريزونا، الولايات المتحدة.\')">؟</a>';
$ec_lang['mtc_d50_mra']='حجم الريبراب الزاوي المطلوب، D50 (Maynord وRuff وAbt 1989)';
$ec_lang['mtc_d50_searcy']='حجم الريبراب الزاوي المطلوب، D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>التكرار التلقائي لتصميم حجم الصخور والخشونة</dt><dd>اختر زر اختيار الخشونة (BB موصى به) وزر اختيار حجم الصخور التصميمي (Isbash موصى به). ضبّط العمق ومعامل أمان حجم الصخور للحصول على التدفق المطلوب بحجم صخور متساوٍ. في كل مرة تغير فيها أي قيمة مدخلة، تحدث دورة التكرار التالية: 1. تُحسب الخشونة من حجم الصخور التصميمي. 2. يُنسخ حساب الخشونة المطلوب إلى خشونة المدخل. 3. يُحسب جريان القناة وحجم الصخور المطلوب. 4. يُعدَّل حجم الصخور التصميمي. 5. كرر حتى يصبح الخطأ في حجم الصخور التصميمي صغيراً جداً.</dd><dt>الحاسبة الأساسية (بدون تكرار)</dt><dd>أدخل قيمة الخشونة المطلوبة. تجاهل منطقة إدخال حجم الصخور التصميمي.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='منحدر صخري Robinson';
$ec_lang['rrc_main_desc']='جدول تصميم منحدر صخري Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='جريان العتبة — بسيط';
$ec_lang['ws_main_title']='حاسبة جريان العتبة عريضة العرف البسيطة المجانية عبر الإنترنت';
$ec_lang['ws_main_desc']='حاسبة جريان العتبة عريضة العرف البسيطة';
$ec_lang['ws_weirLength']='طول العتبة، l';
$ec_lang['ws_headWaterHeight']='ارتفاع المياه العلوية، h';
$ec_lang['ws_weirCoefficient']='معامل العتبة، Cw';
$ec_lang['ws_notes_heading']='ملاحظات';
$ec_lang['ws_notes_we_term']='معادلة العتبة';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='جريان العتبة — غير منتظم';
$ec_lang['wi_main_title']='حاسبة جريان العتبة غير المنتظمة متغيرة العمق المجانية عبر الإنترنت';
$ec_lang['wi_main_desc']='حاسبة جريان العتبة غير المنتظمة';
$ec_lang['wi_headWaterelevation']='منسوب المياه العلوية';
$ec_lang['wi_weirPoints']='نقاط العتبة';
$ec_lang['wi_station']='محطة<br />(مسافة)';
$ec_lang['wi_elevation']='المنسوب';
$ec_lang['wi_pondingHeight']='ارتفاع التجميع';
$ec_lang['wi_incrementalFlow']='التدفق التدريجي';
$ec_lang['wi_cumulativeFlow']='التدفق التراكمي';
$ec_lang['wi_save_and_calculate']='حفظ وحساب';
$ec_lang['wi_notes_we_term']='معادلة العتبة';
$ec_lang['wi_notes_we_def']='q = إذا (الطول = 0) إذن 0؛ وإلا إذا (الميل=0) إذن cw*length*d<sub>0</sub><sup>1.5</sup>؛ وإلا cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) حيث d<sub>1</sub> وd<sub>0</sub> دائماً موجبتان أو صفر';
// Orifice Flow
$ec_lang['or_main_menu']='جريان الفتحة';
$ec_lang['or_main_title']='حاسبة جريان الفتحة المجانية عبر الإنترنت';
$ec_lang['or_main_desc']='جريان الفتحة — حر أو مغمور';
$ec_lang['or_shape']='شكل الفتحة';
$ec_lang['or_shape_circular']='دائري';
$ec_lang['or_shape_rectangular']='مستطيل';
$ec_lang['or_diameter']='القطر (دائري) أو الارتفاع (مستطيل)، D';
$ec_lang['or_width']='العرض، W (مستطيل فقط)';
$ec_lang['or_invert']='منسوب قاع الفتحة (أسفل الفتحة)';
$ec_lang['or_hwe']='منسوب المياه العلوية';
$ec_lang['or_twe']='منسوب المياه السفلية';
$ec_lang['or_cd']='معامل التصريف، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='منسوب المركز الهندسي';
$ec_lang['or_head']='الرأس الفعّال، h';
$ec_lang['or_area']='مساحة الفتحة، A';
$ec_lang['or_flow']='التدفق، Q';
$ec_lang['or_velocity']='السرعة عند الفتحة، v';
$ec_lang['or_regime']='فحص نظام الفتحة';
$ec_lang['or_regime_valid']='تصريف حر — نظام الفتحة صالح ✓';
$ec_lang['or_regime_submerged']='فتحة مغمورة (TWE فوق قاع الفتحة) — صالح ✓';
$ec_lang['or_regime_warn']='تحذير: المياه العلوية أدنى من تاج الفتحة — ليس نظام فتحة';
$ec_lang['or_regime_twe_above_hwe']='تحذير: المياه السفلية (TWE) فوق المياه العلوية (HWE) — تحقق من المدخلات';
$ec_lang['or_notes_1_term']='معادلة الفتحة';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). للتصريف الحر: h = HWE &minus; المركز الهندسي. للجريان المغمور (TWE فوق قاع الفتحة): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='نظام الفتحة';
$ec_lang['or_notes_2_def']='تُطبَّق معادلات جريان الفتحة عندما يكون منسوب المياه العلوية فوق تاج (قمة) الفتحة. عندما تكون المياه العلوية أدنى من التاج، استخدم معادلة عتبة بدلاً من ذلك.';
$ec_lang['or_notes_3_term']='معامل التصريف';
$ec_lang['or_notes_3_def']='يتراوح C<sub>d</sub> من حوالي 0.60 إلى 0.65 للفتحات ذات الحافة الحادة. تستخدم المداخل المستديرة أو المعكوسة قيماً مختلفة. انظر <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> أو دليل مرجعية هيدروليكا HEC-RAS للإرشاد.';
$ec_lang['or_notes_4_term']='الغمر';
$ec_lang['or_notes_4_def']='عندما يكون TWE فوق قاع الفتحة، تُطبّق الحاسبة تلقائياً معادلة الفتحة المغمورة باستخدام h = HWE &minus; TWE. عندما يكون TWE عند قاع الفتحة أو أدنى منه، يُفترض التصريف الحر وh = HWE &minus; المركز الهندسي.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='وقت التصريف بالفتحة';
$ec_lang['odt_main_title']='حاسبة وقت التصريف بالفتحة — بركة أو حوض أو خزان — مجانية عبر الإنترنت';
$ec_lang['odt_main_desc']='وقت تصريف البركة أو الحوض بالفتحة &mdash; طريقة الحجم المخروطي';
$ec_lang['odt_h1_elev']='منسوب سطح الماء الابتدائي';
$ec_lang['odt_a1']='مساحة البركة أو الحوض الابتدائية، A1';
$ec_lang['odt_h2_elev']='منسوب سطح الماء النهائي';
$ec_lang['odt_h_orifice']='منسوب المركز الهندسي للفتحة';
$ec_lang['odt_a0']='مساحة البركة أو الحوض عند منسوب الفتحة، A0';
$ec_lang['odt_a_ending']='المساحة النهائية للبركة، A2 (بالاستيفاء)';
$ec_lang['odt_h2_check']='فحص المنسوب النهائي';
$ec_lang['odt_h2_ok']='المنسوب النهائي فوق قمة الفتحة ✓';
$ec_lang['odt_h2_warn']='تحذير: المنسوب النهائي عند قمة الفتحة أو أدناه (المركز الهندسي + D/2)';
$ec_lang['odt_d']='قطر الفتحة (دائري) أو الارتفاع (مستطيل)، D';
$ec_lang['odt_w']='عرض الفتحة، W (مستطيل فقط)';
$ec_lang['odt_t_sec']='وقت التصريف (ثوانٍ)';
$ec_lang['odt_t_min']='وقت التصريف (دقائق)';
$ec_lang['odt_t_hr']='وقت التصريف (ساعات)';
$ec_lang['odt_t_day']='وقت التصريف (أيام)';
$ec_lang['odt_notes_1_term']='الصيغة';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) يعطي وقت التصريف من الرأس H إلى الفتحة. وقت التصريف = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، حيث H<sub>1</sub> = المنسوب الابتدائي &minus; منسوب الفتحة، H<sub>2</sub> = المنسوب النهائي &minus; منسوب الفتحة.';
$ec_lang['odt_notes_2_term']='الطريقة';
$ec_lang['odt_notes_2_def']='تُنمذج طريقة الحجم المخروطي البركة أو الحوض كمقطع مخروطي بين المساحة الابتدائية A<sub>1</sub> عند منسوب المياه الابتدائي والمساحة A<sub>0</sub> عند منسوب المركز الهندسي للفتحة. يُحسب A<sub>2</sub>، مساحة البركة عند المنسوب النهائي، بالاستيفاء من A<sub>1</sub> وA<sub>0</sub> باستخدام نموذج المقطع المخروطي. وقت التصريف من المنسوب الابتدائي إلى النهائي يساوي إجمالي وقت التصريف من H<sub>1</sub> إلى الفتحة ناقص وقت التصريف المتبقي من H<sub>2</sub> إلى الفتحة.';
$ec_lang['odt_h1']='الرأس الابتدائي، H<sub>1</sub> (WSE &minus; المركز الهندسي)';
$ec_lang['odt_q_max']='الحد الأقصى للتدفق (الابتدائي)، Q<sub>max</sub>';
$ec_lang['odt_vol']='الحجم المُصرَّف';
$ec_lang['odt_sketch_start']='البداية';
$ec_lang['odt_sketch_end']='النهاية';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='العرض من ضفة إلى ضفة';
$ec_lang['essc_mcr']='الحد الأدنى لنصف قطر الانحناء';
$ec_lang['essc_q']='التدفق، Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='قياس تدفق الري';
$ec_lang['irr_main_title']='حاسبات قياس تدفق الري المجانية عبر الإنترنت';
$ec_lang['irr_main_desc']='قياس تدفق الري — القناطر والفتحات';
$ec_lang['contact_title']='التواصل مع HawsEDC';
$ec_lang['contactSendMessage']='أرسل رسالة إلى Tom Haws';
$ec_lang['contactYourName']='اسمك:';
$ec_lang['contactYourEmail']='عنوان بريدك الإلكتروني:';
$ec_lang['contactSubject']='الموضوع:';
$ec_lang['contact_message']='الرسالة:';
$ec_lang['contactSpamPrefix']='خمسة زائد واحد يساوي';
$ec_lang['contactSpamPostfix']='(يرجى كتابتها بالحروف. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='إرسال الرسالة';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='طاقة المياه الصغيرة';
$ec_lang['mhp_main_title']='حاسبة طاقة المياه الصغيرة المجانية عبر الإنترنت';
$ec_lang['mhp_main_desc']='حاسبة إنتاج طاقة المياه الصغيرة المتدفقة في الأنهار';
$ec_lang['mhp_flow']='معدل التدفق، Q';
$ec_lang['mhp_gross_head']='الرأس الإجمالي (فارق المنسوب)، H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='فاقد الرأس في أنبوب الضغط، h<sub>L</sub>';
$ec_lang['mhp_efficiency']='كفاءة المنشأة، &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='الرأس الصافي، H<sub>net</sub>';
$ec_lang['mhp_power']='القدرة المنتجة، P';
$ec_lang['mhp_annual_kwh']='الطاقة السنوية عند طاقة 100%';
$ec_lang['mhp_notes_1_term']='معادلة القدرة';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>، حيث &rho; = 1000 كغ/م&sup3; (ماء عذب) و g = 9.806 م/ث&sup2;.';
$ec_lang['mhp_notes_2_term']='الرأس الصافي';
$ec_lang['mhp_notes_2_def']='الرأس الصافي = الرأس الإجمالي &minus; فاقد الرأس في أنبوب الضغط. تقدير أولي شائع هو h<sub>L</sub> &asymp; 5% من H<sub>gross</sub>. استخدم <a href="Darcy-Weisbach.php">حاسبة داركي-وايسباخ</a> للحصول على تقديرات أدق لفاقد أنبوب الضغط.';
$ec_lang['mhp_notes_3_term']='الكفاءة';
$ec_lang['mhp_notes_3_def']='تتراوح كفاءة المنشأة النموذجية &eta; بين 0.70 و0.85 لتوربينات بيلتون والتوربينات المتقاطعة الشائعة في طاقة المياه الصغيرة. استخدم 0.75 كتقدير أولي محافظ.';
$ec_lang['mhp_notes_4_term']='الطاقة السنوية';
$ec_lang['mhp_notes_4_def']='تفترض الطاقة السنوية تشغيلاً مستمراً بالتدفق الكامل (8760 ساعة/سنة). سيكون الإنتاج الفعلي أقل بسبب التغيرات الموسمية في التدفق وأوقات الصيانة ومعامل الحمل.';
// Penstock Design
$ec_lang['ps_main_menu']='تصميم أنبوب الضغط';
$ec_lang['ps_main_title']='حاسبة تصميم أنبوب الضغط المجانية عبر الإنترنت';
$ec_lang['ps_main_desc']='تحديد أبعاد أنبوب ضغط الطاقة المائية الصغيرة — فقدان الضغط والقدرة والسرعة';
$ec_lang['ps_flow']='معدل التدفق، Q';
$ec_lang['ps_gross_head']='الرأس الإجمالي، H<sub>gross</sub>';
$ec_lang['ps_diameter']='قطر أنبوب الضغط، D';
$ec_lang['ps_length']='طول أنبوب الضغط، L';
$ec_lang['ps_roughness']='خشونة الأنبوب، e';
$ec_lang['ps_km']='معامل الخسارة الثانوية، k<sub>m</sub>';
$ec_lang['ps_nu']='اللزوجة الحركية، &nu;، بوحدة م<sup>2</sup>/ث (1E-6 للماء بالقرب من 20&deg;م)';
$ec_lang['ps_efficiency']='كفاءة المحطة، &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='سرعة التدفق، v';
$ec_lang['ps_vel_check']='فحص السرعة';
$ec_lang['ps_f']='معامل الاحتكاك، f';
$ec_lang['ps_hf']='فقد الضغط بالاحتكاك، h<sub>f</sub>';
$ec_lang['ps_hm']='فقد الضغط الثانوي، h<sub>m</sub>';
$ec_lang['ps_hl']='إجمالي فقد أنبوب الضغط، h<sub>L</sub>';
$ec_lang['ps_hl_check']='فحص فقد الضغط';
$ec_lang['ps_hnet']='الرأس الصافي، H<sub>net</sub>';
$ec_lang['ps_power']='القدرة المنتجة، P';
$ec_lang['ps_annual_kwh']='الطاقة السنوية بالطاقة الكاملة';
$ec_lang['ps_vel_ok']='1–3 م/ث — ضمن الهدف ✓';
$ec_lang['ps_vel_low']='أقل من 1 م/ث — زيادة القطر ⚠';
$ec_lang['ps_vel_high']='أكثر من 3 م/ث — تقليل القطر ⚠';
$ec_lang['ps_hl_ok']='ضمن هدف 10% ✓';
$ec_lang['ps_hl_warn']='يتجاوز هدف 10% — يُنصح بأنبوب أكبر ⚠';
$ec_lang['ps_hl_bad']='يتجاوز 20% — يلزم إعادة التصميم';
$ec_lang['ps_notes_1_term']='فقد الضغط';
$ec_lang['ps_notes_1_def']='إجمالي فقد أنبوب الضغط h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، حيث h<sub>f</sub> = f(L/D)(v&sup2;/2g) هو فقد الاحتكاك وفق داركي-وايسباخ وh<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g يغطي مدخل الأنبوب والانحناءات والصمامات. الرأس الصافي H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='السرعة';
$ec_lang['ps_notes_2_def']='الهدف 1&ndash;3 م/ث. ما دون 1 م/ث يعني تكبير غير ضروري للأنبوب؛ وما فوق 3 م/ث يزيد فقد الاحتكاك وخطر ضربة المطرقة المائية.';
$ec_lang['ps_notes_3_term']='هدف فقد الضغط';
$ec_lang['ps_notes_3_def']='يُعدّ فقد أنبوب الضغط أقل من 10% من الرأس الإجمالي اقتصادياً في الغالب. يقع التوازن الأمثل بين تكلفة الأنبوب والطاقة المفقودة حول 4&ndash;6% للمواقع ذات الكهرباء عالية القيمة.';
$ec_lang['ps_notes_4_term']='الخسائر الثانوية k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='قيم نموذجية: مدخل حاد 0.5، كل انحناء 45&deg; بين 0.2&ndash;0.3، بوابة مفتوحة بالكامل 0.1، صمام فراشة 0.2. اجمع جميع التجهيزات لقيمة k<sub>m</sub> الإجمالية. القيمة الافتراضية 1.5 تفترض مدخلاً واحداً وانحناءين.';
$ec_lang['ps_notes_5_term']='خشونة الأنبوب e';
$ec_lang['ps_notes_5_def']='الخشونة المطلقة النموذجية: فولاذ (جديد) 0.046&nbsp;مم، فولاذ (مستعمل) 0.15&nbsp;مم، HDPE 0.003&nbsp;مم، PVC/uPVC 0.0015&nbsp;مم، خرسانة 0.3&ndash;3&nbsp;مم. HDPE شائع لأنابيب الضغط في محطات الطاقة المائية الصغيرة.';

// About
$ec_lang['about_main_menu']='حول';
$ec_lang['about_main_title']='حول حاسبات HawsEDC الهندسية';
$ec_lang['about_main_desc']='الرسالة، المصدر المفتوح، والمساهمة';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='معدل الري بالتنقيط / الرش';
$ec_lang['ds_main_title']='حاسبة معدل الري بالتنقيط والرش مجانية عبر الإنترنت';
$ec_lang['ds_main_desc']='الري بالتنقيط والرش &mdash; معدل الإيداع والانتظام';
$ec_lang['ds_q_avg']='معدل تدفق المُشَتِّت المتوسط، q';
$ec_lang['ds_q_min']='معدل تدفق المُشَتِّت الأدنى، q<sub>min</sub>';
$ec_lang['ds_se']='تباعد المُشَتِّتات على طول الخط الجانبي، S<sub>e</sub>';
$ec_lang['ds_sl']='تباعد الخطوط الجانبية (تباعد الصفوف)، S<sub>l</sub>';
$ec_lang['ds_n_e']='عدد المُشَتِّتات في الخط الجانبي، n<sub>e</sub>';
$ec_lang['ds_n_l']='عدد الخطوط الجانبية في المنطقة، n<sub>l</sub>';
$ec_lang['ds_d']='عمق الإيداع المستهدف، d';
$ec_lang['ds_a_e']='المساحة لكل مُشَتِّت، A<sub>e</sub>';
$ec_lang['ds_pr']='معدل الإيداع (معدل التساقط)، PR';
$ec_lang['ds_du']='انتظام التوزيع، DU';
$ec_lang['ds_du_check']='فحص جودة DU';
$ec_lang['ds_q_lat']='التدفق لكل خط جانبي، Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='تدفق المنطقة، Q<sub>zone</sub>';
$ec_lang['ds_t_run']='وقت التشغيل للعمق المستهدف (ساعات)';
$ec_lang['ds_du_excellent']='ممتاز — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='جيد — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='مقبول — DU ≥ 70%';
$ec_lang['ds_du_poor']='ضعيف — DU < 70% — مراجعة التصميم ⚠';
$ec_lang['ds_notes_1_term']='معدل الإيداع';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>، حيث A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> هي المساحة التي يخدمها كل مُشَتِّت. يتيح معدل الإيداع المنخفض وقتاً أطول للتسرب &mdash; مهم في التربة الثقيلة أو الحقول المنحدرة.';
$ec_lang['ds_notes_2_term']='انتظام التوزيع (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. يعني DU بقيمة 1.0 (100%) أن جميع المُشَتِّتات تتدفق بشكل متطابق. القيم دون 0.80 تهدر الماء في المناطق الجيدة الري مع ترك بقع أكثر جفافاً. ينخفض الانتظام مع التباين المفرط في الضغط على طول الخط الجانبي أو تآكل المُشَتِّتات أو الانسداد الجزئي.';
$ec_lang['ds_notes_3_term']='وقت التشغيل';
$ec_lang['ds_notes_3_def']='وقت التشغيل = العمق المستهدف &divide; معدل الإيداع. في التربة المنحدرة أو المضغوطة، قسِّم وقت التشغيل إلى دورتين أو ثلاث دورات أقصر مع فترات راحة بينها لتجنب الجريان السطحي.';
$ec_lang['irr_intro_html']='<p>السدود القياسية والفتحات هي الأدوات الميدانية المعيارية لقياس تدفق المياه في أنظمة الري. اختر الحاسبة التي تناسب منشأتك:</p>';
$ec_lang['irr_card_weir_uniform_head']='السد القياسي — ذو العتبة العريضة (عرض منتظم)';
$ec_lang['irr_card_weir_uniform_desc']='قِس التدفق فوق عتبة سد التحويل أو منشأة التحكم أو لوح السد. أدخل طول السد وعمق الماء فوق العتبة.';
$ec_lang['irr_card_weir_irregular_head']='السد القياسي — مقطع غير منتظم';
$ec_lang['irr_card_weir_irregular_desc']='استخدمه عندما لا تكون عتبة السد على ارتفاع موحّد — مفيض طبيعي، أو منشآت سقوط بعرض متغير، أو منشآت تحكم متعددة الأقسام.';
$ec_lang['irr_card_orifice_head']='الفتحة — بوابة الرأس أو مخرج الأنبوب';
$ec_lang['irr_card_orifice_desc']='قِس التدفق عبر بوابة انزلاقية أو مخرج أنبوب أو فتحة بردورة. يتعامل تلقائياً مع حالتَي التصريف الحر والغمر (ضغط المصب).';
$ec_lang['irr_card_canal_head']='تصميم القناة &amp; تحليلها';
$ec_lang['irr_card_canal_desc']='صمّم أو تحقق من قناة ري باستخدام معادلة Manning. استخدم حاسبة المقطع الشبه المنحرف للقنوات الجديدة، وحاسبة المقطع غير المنتظم للمقاطع الطبيعية أو الإنشائية القائمة.';
$ec_lang['irr_card_drip_head']='تصميم الري بالتنقيط &amp; الرش';
$ec_lang['irr_card_drip_desc']='احسب معدل التطبيق، وتوحيد التوزيع، والتدفق الجانبي، وتدفق المنطقة، ووقت التشغيل لنظام ري بالتنقيط أو الرش. أدخل تدفق المُرشّح والمسافة بين المرشحات والعمق المستهدف.';
$ec_lang['irr_quickref_html']='<h3>مرجع سريع</h3><dl><dt>سد تحويل أو منشأة تحكم</dt><dd>قِس عمق الماء فوق عتبة السد القياسي. استخدم <a href="Weir-Flow-Simple.php">السد القياسي البسيط</a> للعتبة المنتظمة، أو <a href="Weir-Flow-Irregular.php">السد القياسي غير المنتظم</a> للعتبة ذات المقطع المنحدر أو المتدرج.</dd><dt>بوابة الرأس أو مخرج الأنبوب</dt><dd>قِس منسوب الماء في المصب العلوي والسفلي (أو منسوب قاع الأنبوب عند التصريف الحر). استخدم <a href="Orifice.php">تدفق الفتحة</a>. للأنبوب الدائري D&nbsp;= قطر الأنبوب؛ للبوابة المستطيلة أدخل العرض W والارتفاع D.</dd><dt>وقت تفريغ الخزان أو البركة</dt><dd>استخدم <a href="Orifice-Drain-Time.php">وقت تصريف الفتحة</a> لتقدير المدة اللازمة لخفض منسوب بركة أو خزان عبر فتحة في القاع — مفيد لتخطيط مخزون مياه الري.</dd><dt>المعايير الميدانية</dt><dd>معادلات تدفق السد القياسي والفتحة المستخدمة هنا تتوافق مع إجراءات <em>دليل قياس المياه</em> الصادر عن مكتب الاستصلاح الأمريكي (USBR) (الطبعة الثالثة)، وهي المطلوبة عادةً من قِبل مشرفي المياه وأقاليم الري.</dd></dl>';
$ec_lang['about_body_html']='<h3>الرسالة</h3><p>وُجدت حاسبات HawsEDC الهندسية لخدمة المهندسين والعاملين الميدانيين حول العالم — ولا سيما أولئك الذين يعملون في المناطق الشحيحة المياه أو المحدودة الموارد أو المحرومة. هذه الأدوات جزء من رسالة إنسانية أشمل: إخبار كل إنسان بأكثر الطرق عملية وفاعلية أنه محبوب وعزيز إلى الأبد، وأنه لا يخشى شيئاً، وأنه لن يدمّر كل شيء.</p><p>الحاسبات هي الوسيلة، والهدف عالم خالٍ من المعاناة.</p><h3>ترخيص المصدر المفتوح</h3><p>يُصدَر الكود كاملاً تحت <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">رخصة GNU العامة الشاملة الإصدار 3.0 أو أحدث</a> — حراً كما هو الحرية. يمكنك استخدام الكود ودراسته وتعديله وإعادة توزيعه وفق الشروط ذاتها.</p><p>حقوق النشر &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>الكود المصدري</h3><p>الكود المصدري الكامل متاح للعموم على Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>يمكنك تصفح الكود وتسجيل المشكلات أو تفريع المستودع هناك.</p><h3>المساهمة</h3><p>طلبات السحب مرحَّب بها. طرق المساهمة:</p><ul><li><strong>الترجمة</strong> — حسِّن أو أضف لغة. افتح طلب سحب بتغييرات على ملف <code>lib/lang.ec.??.php</code> المعني.</li><li><strong>تقارير الأخطاء</strong> — استخدم نموذج الملاحظات في أي صفحة حاسبة، أو سجّل مشكلة على Bitbucket.</li><li><strong>حاسبات جديدة</strong> — أفكار لأدوات هندسة هيدروليكية تخدم العاملين الميدانيين وممارسي الري مرحَّب بها بشكل خاص. راجع دليل المطور <code>CLAUDE.md</code> في المستودع.</li><li><strong>الاستضافة</strong> — إن كنت تستطيع استضافة مرآة لهذه الحاسبات في منطقة ذات اتصال محدود، يُرجى التواصل معنا.</li></ul><h3>الاستخدام دون اتصال</h3><p>تعمل هذه الآلات الحاسبة كتطبيق ويب تقدمي (PWA). قم بزيارة أي صفحة حاسبة أثناء اتصالك بالإنترنت، وسيقوم متصفحك تلقائياً بتخزين جميع الآلات الحاسبة في ذاكرة التخزين المؤقت. بعد ذلك، تعمل جميع الآلات الحاسبة دون اتصال — لا حاجة للإنترنت.</p><p>على Android أو iOS، استخدم خيار "إضافة إلى الشاشة الرئيسية" في متصفحك لتثبيت EngCalcs كتطبيق على جهازك. على سطح المكتب، ابحث عن أيقونة التثبيت في شريط العنوان.</p><p>يمكنك أيضاً حفظ أي حاسبة منفردة باستخدام قائمة "حفظ باسم&hellip;" في متصفحك للاستخدام غير المتصل لمرة واحدة.</p><h3>التواصل</h3><p>Tom Haws — مهندس هيدروليكي ومؤلف هذه الحاسبات.<br />استخدم نموذج الملاحظات في أي صفحة حاسبة، أو تصفح الكود المصدري على <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='تصميم المزلق الصخري (Robinson)';
$ec_lang['rc_main_title']='حاسبة تصميم المزلق الصخري المجانية عبر الإنترنت — Robinson (1998)';
$ec_lang['rc_main_desc']='تحديد حجم الحجارة في المزلق الصخري &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='انحدار قاع المزلق، S<sub>0</sub>';
$ec_lang['rc_qt']='التصريف الوحدوي الإجمالي، q<sub>t</sub> <span title="التدفق لكل وحدة عرض عند مدخل المزلق. لقناة بعرض قاع B وتدفق إجمالي Q، استخدم q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='مسامية الحجارة، n<sub>p</sub>';
$ec_lang['rc_sg']='الكثافة النسبية للصخر، sg <span title="الجرانيت أو البازلت المكسور النموذجي ≈ 2.65. نطاق Robinson الصحيح: 2.54 إلى 2.82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='انحراف التدرج SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="الانحراف المعياري للتدرج. الصخر المنتظم ≈ 1.25. نطاق Robinson الصحيح: 1.15 إلى 1.47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='العمق الطبيعي في قناة المدخل، y<sub>n</sub> <span title="التحوض (Hp > yn) جيد — يقلل من التآكل المنبعي. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='حجم الصخر الوسيط المطلوب، D<sub>50</sub> <span title="المعادلة 1 (S0 &lt; 0.10) أو المعادلة 2 (0.10-0.40). الصحيح: D50 من 15 إلى 278 مم، S0 من 0.02 إلى 0.40. خارج النطاق: قيم خارج المعايرة." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='المعادلة المطبّقة';
$ec_lang['rc_sg_check']='فحص الكثافة النسبية';
$ec_lang['rc_SD_check']='فحص انحراف التدرج SD';
$ec_lang['rc_sg_ok']   ='sg ضمن النطاق الصحيح (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='تحذير: sg < 2.54 — أقل من نطاق Robinson';
$ec_lang['rc_sg_high'] ='تحذير: sg > 2.82 — أعلى من نطاق Robinson';
$ec_lang['rc_SD_ok']   ='SD ضمن النطاق الصحيح (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='تحذير: SD < 1.15 — أقل من نطاق Robinson';
$ec_lang['rc_SD_high'] ='تحذير: SD > 1.47 — أعلى من نطاق Robinson';
$ec_lang['rc_layer']='سماكة طبقة الحجارة (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='نصف قطر منحنى التاج العلوي (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='طول قوس منحنى التاج العلوي';
$ec_lang['rc_apron_length']='طول مصطبة المصب (15 &times; D<sub>50</sub>) <span title="مطلوب للدعم الإنشائي لحجارة المزلق. «الحد الأدنى من الماء الخلفي الناتج عن قناة المصب ومقاومة القناة المنبعية كافٍ لضمان استقرار الحجارة في مقطع المصب.» (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='معامل خشونة Manning في المزلق، n';
$ec_lang['rc_Vm']='السرعة عبر غطاء الصخر، V<sub>m</sub> <span title="نسبة من qt تتدفق عبر مسام الحجارة. الباقي qs يتدفق على السطح. الافتراضي np = 0.45 للصخر المكسور الزاوي." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='التدفق الوحدوي عبر الغطاء، q<sub>m</sub>';
$ec_lang['rc_qs']='التدفق الوحدوي السطحي، q<sub>s</sub> (q<sub>t</sub> &minus; q<sub>m</sub>)';
$ec_lang['rc_d']='عمق التدفق فوق سطح الحجارة، d';
$ec_lang['rc_Hp']='ارتفاع الماء عند بوابة المدخل، H<sub>p</sub> <span title="التحوض (Hp > yn) جيد — يقلل من التآكل المنبعي. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='فحص تجمّع المياه عند المدخل';
$ec_lang['rc_pond_ok']  ='Hp > yn — تجمّع مياه مصبّ ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — لا تجمّع للمياه — تحقق من المدخل لاحتمال التآكل';
$ec_lang['rc_eq1']='المعادلة 1 (S0 < 0.10) — انحدار لطيف';
$ec_lang['rc_eq2']='المعادلة 2 (0.10 ≤ S0 ≤ 0.40) — انحدار حاد';
$ec_lang['rc_eq_warn_low']='تحذير: S0 < 0.02 — أقل من نطاق التحقق لدى Robinson';
$ec_lang['rc_eq_warn_high']='تحذير: S0 > 0.40 — أعلى من نطاق التحقق لدى Robinson';
$ec_lang['rc_notes_1_term']='معادلات تحديد حجم الصخر';
$ec_lang['rc_notes_1_def']='طوّر Robinson, Rice &amp; Kadavy (1998) معادلتين تجريبيتين لحجم الحجارة الوسيط D<sub>50</sub> بناءً على انحدار المزلق والتصريف الوحدوي. تُطبَّق المعادلة 1 للانحدارات اللطيفة (S<sub>0</sub> &lt; 0.10)؛ وتُطبَّق المعادلة 2 للانحدارات الحادة (0.10 &le; S<sub>0</sub> &le; 0.40). كلتا المعادلتين تستلزمان q<sub>t</sub> بوحدة m&sup2;/s وتُعيدان D<sub>50</sub> بالمليمتر. النطاق المعتمد هو 0.02 &le; S<sub>0</sub> &le; 0.40.';
$ec_lang['rc_notes_2_term']='التصريف الوحدوي';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> هو التصريف الوحدوي الإجمالي عند تاج المزلق (إجمالي التدفق لكل وحدة عرض). لقناة بعرض قاع B تحمل تدفقاً إجمالياً Q، يُقدَّر q<sub>t</sub> &asymp; Q / B، أو يُحسب من شرط العمق الحرج عند مدخل المزلق.';
$ec_lang['rc_notes_3_term']='التدفق عبر غطاء الصخر';
$ec_lang['rc_notes_3_def']='جزء من التدفق الكلي يمر عبر مسام الحجارة (تدفق الغطاء q<sub>m</sub>)؛ والباقي يتدفق فوق سطح الصخر (q<sub>s</sub> = q<sub>t</sub> &minus; q<sub>m</sub>). يُحسب عمق التدفق d بتطبيق معادلة Manning على التدفق السطحي q<sub>s</sub> باستخدام خشونة المزلق n. المسامية الافتراضية n<sub>p</sub> = 0.45 نموذجية للصخر المكسور الزاوي.';
$ec_lang['rc_notes_5_term']='نطاق حجم الصخر الصحيح';
$ec_lang['rc_notes_5_def']='طُوِّرت المعادلات باستخدام نطاق D<sub>50</sub> من 15&nbsp;مم إلى 278&nbsp;مم. النتائج خارج هذا النطاق تُعدّ استقراءً وينبغي استخدامها بحكم هندسي إضافي.';
$ec_lang['rc_notes_6_term']='منسوب مصطبة المصب';
$ec_lang['rc_notes_6_def']='ينبغي أن يكون منسوب أعلى الحجارة في مقطع المصب مساوياً أو أقل من منسوب قاع القناة المنبعية. إذا كان أعلى، ستكون حجارة المصب غير مستقرة.';
$ec_lang['rc_notes_7_term']='فحص التحوض عند المدخل';
$ec_lang['rc_notes_7_def']='عندما يكون العمق الطبيعي في قناة المدخل أقل من ارتفاع رأس العتبة (H<sub>p</sub>) اللازم لتمرير q<sub>t</sub>، يحدث تدفق مقيّد أو تحوض أمام مصطبة المدخل. هذا مقبول عموماً — التحوض يقلل السرعة ويمنع التآكل المنبعي. للتحقق: استخدم حاسبة تدفق السد لإيجاد H<sub>p</sub> لقيمة q<sub>t</sub> وعرض التاج المعطيين، وقارن بالعمق الطبيعي لقناة المدخل. إذا تجاوز H<sub>p</sub> العمق الطبيعي، سيحدث تحوض.';
$ec_lang['rc_notes_4_term']='المرجع';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://doi.org/10.13031/2013.17230">Design of rock chutes</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. تنشر وزارة الزراعة الأمريكية (USDA ARS) أيضاً <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">جدول Excel</a> يعتمد على نفس الطريقة.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'مرشح';
$ec_lang['rc_sketch_top_crest_curve'] = 'منحنى القمة';
$ec_lang['rc_sketch_outlet_apron']    = 'بلاطة المخرج';
$ec_lang['rc_sketch_radius']          = 'نصف القطر';
