<?php

// اردو — All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='کسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/سے';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% بلندی/فاصلہ';
$ec_lang['u_grade']='بلندی/فاصلہ';
$ec_lang['u_in2']='مربع انچ';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='انچ';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='لی/سے';
$ec_lang['u_m2']='می^2';
$ec_lang['u_m3ps']='می^3/سے';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='می پانی';
$ec_lang['u_mld']='ML/دن';
$ec_lang['u_m']='می';
$ec_lang['u_mm2']='ملی^2';
$ec_lang['u_mmh2o']='ملی پانی';
$ec_lang['u_mm']='ملی';
$ec_lang['u_mps']='می/سے';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='سیکنڈ';
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']='ایکڑ-فٹ';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='می^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC حسابات';
$ec_lang['menu_main_list']='حسابات کی فہرست';
$ec_lang['menu_main_hydraulics']='ہائیڈرولکس';
$ec_lang['menu_main_language']='زبان';
$ec_lang['menu_more']='مزید';
$ec_lang['template_welcome']='>> اپنے خوف دروازے پر چھوڑ دیں؛ یہاں محبت ہماری زبان ہے۔ آپ سب کچھ برباد نہیں کر رہے۔ <a target="_blank" href="https://hawsedc.com/download.php">مفت HawsEDC AutoCAD اوزار</a> بھی آزمائیں۔ <<';
$ec_lang['template_translation_help']='کیا آپ کے ذہن میں یہاں شامل کرنے کے لیے کوئی شاندار حاسبے کا خیال ہے؟ کیا آپ ترجمے بہتر کرنے، پروگرامنگ، یا ان حاسبات کی میزبانی میں مدد کر سکتے ہیں؟  ';
$ec_lang['template_feedback']='براہ کرم اپنی قیمتی رائے یا تعریف شیئر کریں۔ کیا اس مفت حاسبے نے ہر لحاظ سے آپ کی توقعات سے بڑھ کر کام کیا؟';
$ec_lang['template_printable_title']='طباعت کے قابل عنوان';
$ec_lang['template_printable_subtitle']='طباعت کے قابل ذیلی عنوان';
$ec_lang['index_title']='مفت آنلائن انجینئرنگ حاسبات';
$ec_lang['calc_set_units']='اکائیاں مقرر کریں:';
$ec_lang['calc_defaults']='پہلے سے مقرر اقدار';
$ec_lang['calc_defaults_confirm']='Reset calculator to factory defaults?';
$ec_lang['points_data_help']='(یا ڈیٹا علاقے سے کاپی/پیسٹ کریں)';
$ec_lang['points_data_title']='نقطہ ڈیٹا<br />(کاما یا ٹیب سے علیحدہ)';
$ec_lang['points_data_copy']='کاپی';
$ec_lang['points_data_paste']='پیسٹ';
$ec_lang['calc_inputs']='ان پٹ';
$ec_lang['calc_results']='نتائج';
$ec_lang['view_hide_line']='[یہ سطر چھپائیں]';
$ec_lang['view_printable']='طباعت کے قابل ورژن (بحال کرنے کے لیے دوبارہ لوڈ کریں)';
$ec_lang['ec_name_label']='یہ حساب محفوظ کریں:';
$ec_lang['ec_name_placeholder']='نام';
$ec_lang['ec_name_hint']='ان درج کردہ قدریوں کو URL میں محفوظ کریں نشان زدگی، تاریخ سے بازیافت، اور شیئرنگ کے لیے';
$ec_lang['calc_copy_link']='Copy link';
$ec_lang['calc_copy_link_done']='Copied!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='ڈارسی-وائسباخ پائپ دباؤ نقصان';
$ec_lang['dw_main_title']='مفت آنلائن ڈارسی-وائسباخ پائپ دباؤ نقصان حاسبہ';
$ec_lang['dw_main_desc']='دیے گئے قطر، کھردرا پن اور بہاؤ پر ڈارسی-وائسباخ پائپ دباؤ نقصان';
$ec_lang['dw_roughness']='ڈارسی-وائسباخ مطلق کھردرا پن، e';
$ec_lang['dw_kinematic_viscosity']='حرکیاتی چپچپاہٹ، ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='رینولڈز عدد، Re';
$ec_lang['dw_flow_regime']='بہاؤ کی نوع';
$ec_lang['dw_regime_laminar']='ورقی';
$ec_lang['dw_regime_transitional']='انتقالی';
$ec_lang['dw_regime_turbulent']='مضطرب';
$ec_lang['dw_friction_factor_method']='رگڑ کے گنجینے کا طریقہ';
$ec_lang['dw_friction_factor']='رگڑ کا گنجینہ، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='ہیزن-ولیمز پائپ دباؤ نقصان';
$ec_lang['hw_main_title']='مفت آنلائن ہیزن-ولیمز پائپ دباؤ نقصان حاسبہ';
$ec_lang['hw_main_desc']='دیے گئے قطر، کھردرا پن اور بہاؤ پر ہیزن-ولیمز پائپ دباؤ نقصان';
$ec_lang['hw_hgl_1']='پست آب HGL';
$ec_lang['hw_hgl_2']='بالا آب HGL';
$ec_lang['hw_roughness']='ہیزن-ولیمز گنجینہ، C';
// Manning Irregular
$ec_lang['mi_menu']='مانینگ نامنظم نالہ';
$ec_lang['mi_main_title']='مفت آنلائن مانینگ نامنظم نالہ حاسبہ';
$ec_lang['mi_main_desc']='نامنظم نالہ مانینگ یکساں بہاؤ حاسبہ';
$ec_lang['mi_waterSurfaceElevation']='آبی سطح کی بلندی';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='عرضی مقطع کے نقاط';
$ec_lang['mi_groupPoint']='نقطہ';
$ec_lang['mi_groupSegment']='حصہ';
$ec_lang['mi_groupRegion']='علاقہ';
$ec_lang['mi_station']='اسٹیشن';
$ec_lang['mi_elevation']='بلندی';
$ec_lang['mi_d50in']='اسٹر<br />درمیانی<br />پتھر<br />حجم';
$ec_lang['mi_n']='n<br />حصے<br />کے لیے';
$ec_lang['mi_is_bank']='R<sub>h</sub>، Q<br />علاقہ<br />حدود<br />(کنارہ)';
$ec_lang['mi_tau']='تہ<br />قینچی<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='مرکب<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='نوٹ';
$ec_lang['mi_notes_1_term']='مرکب n';
$ec_lang['mi_notes_1_def']='یہ حاسبہ Chow 1959، صفحہ 136، مساوات 6-17 (6-18 نہیں) استعمال کرتے ہوئے علاقائی مرکب n کی گنتی میں HEC-RAS حوالہ دستی کی پیروی کرتا ہے۔';
$ec_lang['mi_notes_2_term']='پتھر اسٹر';
$ec_lang['mi_notes_2_def']='پتھر اسٹر ڈیزائن کے لیے مانینگ ذوزنقہ نالہ حاسبہ استعمال کریں۔ یہ حاسبہ قدرتی عرضی مقاطع کے لیے زیادہ موزوں ہے۔';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='مانینگ پائپ بہاؤ';
$ec_lang['mpf_main_title']='مفت آنلائن مانینگ پائپ بہاؤ حاسبہ';
$ec_lang['mpf_main_desc']='دیے گئے ڈھلان اور گہرائی پر مانینگ فارمولا یکساں پائپ بہاؤ';
$ec_lang['mpf_spreadheet_notice']='اس حاسبے کا اسپریڈشیٹ ورژن دیکھیں';
$ec_lang['mpf_pipe_diameter']='پائپ قطر، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='مانینگ کھردرا پن، n';
$ec_lang['mpf_friction_slope']='دباؤ ڈھلان (ممکنہ طور پر <a target="_blank" href="../pressureslope.php">؟</a> پائپ ڈھلان کے برابر)، S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='نسبی بہاؤ گہرائی، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(نوٹ دیکھیں)';
$ec_lang['mpf_flow']='بہاؤ، Q';
$ec_lang['mpf_velocity']='رفتار، v';
$ec_lang['mpf_velocity_head']='رفتار سر، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='بہاؤ رقبہ، a';
$ec_lang['mpf_pipe_area']='پائپ رقبہ، a0';
$ec_lang['mpf_area_ratio']='نسبی رقبہ، a/a0';
$ec_lang['mpf_wetted_perimeter']='تر محیط، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='آبی نصف قطر، R<sub>h</sub>';
$ec_lang['mpf_top_width']='اوپری چوڑائی، T';
$ec_lang['mpf_froude_number']='فرود عدد، F';
$ec_lang['mpf_shear_stress']='اوسط قینچی دباؤ (کشش قوت)، tau';
$ec_lang['mpf_full_flow']='مکمل بہاؤ، Q0';
$ec_lang['mpf_full_flow_ratio']='مکمل بہاؤ سے نسبت، Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>یہ ایک <em>لامحدود لمبے</em> پائپ کے اندر بہاؤ اور گہرائی ہے۔</dt><dd>پائپ میں بہاؤ داخل کرانے کے لیے کافی زیادہ بالادست گہرائی درکار ہو سکتی ہے۔ بالادست گہرائی پانے کے لیے رفتار سر کا کم از کم 1.5 گنا جوڑیں یا HY-8 استعمال کرتے ہوئے معیاری پائپنالی سر آب حساب کے لیے <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">میرا 2 منٹ کا ٹیوٹوریل</a> دیکھیں۔</dd>';
$ec_lang['mpf_solve_for_dd0']='دیے گئے Q کے لیے y/d<sub>0</sub> حل کریں';
$ec_lang['mpf_solve_desc']='حاسبہ فارم سے D<sub>0</sub>، n اور S<sub>0</sub> استعمال کرتے ہوئے دیے گئے Q کے لیے کم سے کم y/d<sub>0</sub> تلاش کرتا ہے۔';
$ec_lang['mpf_solve_button']='حل کریں';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='مانینگ پائپ دباؤ نقصان';
$ec_lang['mphl_main_title']='مفت آنلائن مانینگ پائپ دباؤ نقصان حاسبہ';
$ec_lang['mphl_main_desc']='دیے گئے مکمل بہاؤ پر مانینگ فارمولا دباؤ نقصان';
$ec_lang['mphl_pipe_length']='پائپ لمبائی، L';
$ec_lang['mphl_area']='رقبہ، A';
$ec_lang['mphl_total_junction_k']='کل مشترک جنکشن نقصان گنجینہ، k';
$ec_lang['mphl_friction_slope']='رگڑ ڈھلان';
$ec_lang['mphl_friction_loss']='رگڑ نقصان، H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='جنکشن نقصان، H<sub>m</sub>';
$ec_lang['mphl_total_loss']='کل نقصان، H<sub>l</sub>';
$ec_lang['mphl_egl_1']='پست آب EGL';
$ec_lang['mphl_egl_2']='بالا آب EGL';
$ec_lang['mphl_hgl_2']='پائپ میں بالا آب HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>کھلے ان لیٹ (پائپنالی) کے معاملے میں، ان لیٹ کنٹرول کی حالتوں کی جانچ ضروری ہے۔</dt><dd>1. بالادست HGL بالادست معمول گہرائی بہاؤ بلندی (یا پائپ!) سے کم نہیں ہو سکتی۔</dd><dd>2. پائپنالی کا سر آب بالادست HGL کے مقابلے میں بالادست EGL سے بہتر ظاہر ہوتا ہے۔</dd><dd>3. HY-8 استعمال کرتے ہوئے سادہ معیاری پائپنالی سر آب حساب کے لیے <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">میرا 2 منٹ کا ٹیوٹوریل</a> دیکھیں۔</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='مانینگ ذوزنقہ نالہ';
$ec_lang['mtc_main_title']='مفت آنلائن مانینگ فارمولا ذوزنقہ نالہ حاسبہ';
$ec_lang['mtc_main_desc']='دیے گئے ڈھلان اور گہرائی پر مانینگ فارمولا یکساں ذوزنقہ نالہ بہاؤ';
$ec_lang['mtc_bottom_width']='تہ چوڑائی، b';
$ec_lang['mtc_side_slope_1']='جانبی ڈھلان 1، z1 (افقی/عمودی)';
$ec_lang['mtc_side_slope_2']='جانبی ڈھلان 2، z2 (افقی/عمودی)';
$ec_lang['mtc_channel_slope']='نالہ ڈھلان، S';
$ec_lang['mtc_flow_depth']='بہاؤ گہرائی، y';
$ec_lang['mtc_bend_angle']='موڑ کا زاویہ، β <a target="_blank" href="riprap-bend-angle.png" title="تصویر کے لیے کلک کریں">؟</a> (ریپ ریپ حجم کے لیے)';
$ec_lang['mtc_sgrock']='پتھر کی مخصوص کثافت، SG (2.65)';
$ec_lang['mtc_d50_in']='ڈیزائن پتھر حجم، D50';
$ec_lang['mtc_n_strickler']='Strickler کے مطابق ڈیزائن پتھر حجم کے لیے n';
$ec_lang['mtc_n_blodgett']='Blodgett کے مطابق ڈیزائن پتھر حجم کے لیے n';
$ec_lang['mtc_n_bathurst']='Bathurst کے مطابق ڈیزائن پتھر حجم کے لیے n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett بمقابلہ Bathurst';
$ec_lang['mtc_d50_bottom']='تہ کے لیے ضروری زاویہ دار پتھر حجم، D50 (Isbash اور MC) <span title="Isbash (1936) اور Maricopa County، Arizona، US کے مطابق۔" style="cursor:help;color:#06c;font-size:0.9em">؟</span>';
$ec_lang['mtc_d50_z1']='جانبی ڈھلان 1 کے لیے ضروری زاویہ دار پتھر حجم، D50 (Isbash اور MC) <span title="Isbash (1936) اور Maricopa County، Arizona، US کے مطابق۔" style="cursor:help;color:#06c;font-size:0.9em">؟</span>';
$ec_lang['mtc_d50_z2']='جانبی ڈھلان 2 کے لیے ضروری زاویہ دار پتھر حجم، D50 (Isbash اور MC) <span title="Isbash (1936) اور Maricopa County، Arizona، US کے مطابق۔" style="cursor:help;color:#06c;font-size:0.9em">؟</span>';
$ec_lang['mtc_d50_mra']='ضروری زاویہ دار پتھر حجم، D50 (Maynord، Ruff اور Abt 1989)';
$ec_lang['mtc_d50_searcy']='ضروری زاویہ دار پتھر حجم، D50 (Searcy 1967)';
$ec_lang['mtc_vel_check']='رفتار کی جانچ';
$ec_lang['mtc_vel_ok']='یکساں بہاؤ مفروضات کے لیے رفتار مناسب ہے۔';
$ec_lang['mtc_vel_high']='رفتار زیادہ — منتقلی کے نقصانات، دستیاب توانائی اور پانی کے ہتھوڑے کا خطرہ جانچیں۔';
$ec_lang['mtc_vel_low']='رفتار کم — تلچھٹ جمع ہونے کا خطرہ۔';
$ec_lang['mtc_vel_ok_short']='ٹھیک';
$ec_lang['mtc_vel_high_short']='زیادہ';
$ec_lang['mtc_vel_low_short']='کم';
$ec_lang['mtc_note_1']='<dl><dt>خودکار پتھر حجم اور کھردرا پن ڈیزائن تکرار</dt><dd>ایک کھردرا پن ریڈیو بٹن (BB تجویز کردہ) اور ایک ڈیزائن پتھر حجم ریڈیو بٹن (Isbash تجویز کردہ) منتخب کریں۔ مساوی پتھر حجم کے ساتھ اپنا مطلوبہ بہاؤ حاصل کرنے کے لیے گہرائی اور پتھر حجم حفاظت عامل کو ایڈجسٹ کریں۔ ہر بار جب آپ کوئی ان پٹ قدر تبدیل کرتے ہیں، درج ذیل تکرار چکر ہوتا ہے: 1. ڈیزائن پتھر حجم سے کھردرا پن کا حساب کیا جاتا ہے۔ 2. درخواست کردہ کھردرا پن حساب ان پٹ کھردرا پن میں کاپی کیا جاتا ہے۔ 3. نالہ بہاؤ اور ضروری پتھر حجم کا حساب کیا جاتا ہے۔ 4. ڈیزائن پتھر حجم کو ایڈجسٹ کیا جاتا ہے۔ 5. ڈیزائن پتھر حجم میں غلطی بہت چھوٹی ہونے تک دہرائیں۔</dd><dt>بنیادی حاسبہ (تکرار کے بغیر)</dt><dd>اپنی مطلوبہ کھردرا پن قدر درج کریں۔ ڈیزائن پتھر حجم ان پٹ علاقہ نظرانداز کریں۔</dd></dl>';
$ec_lang['mtc_note_2_term']='رفتار کی جانچ';
$ec_lang['mtc_note_2_def']='زیادہ رفتار دستیاب ڈراپ سے زیادہ مخصوص توانائی ظاہر کرتی ہے۔ یہ توانائی پھیلاؤ، موڑ یا رکاوٹوں پر تیزی سے ضائع ہو سکتی ہے۔ تصدیق کریں کہ یہ مقام کے لیے مناسب ہے۔';
// Weir Flow Simple
$ec_lang['ws_main_menu']='سادہ ویر بہاؤ';
$ec_lang['ws_main_title']='مفت آنلائن سادہ چوڑی-شیخر ویر بہاؤ حاسبہ';
$ec_lang['ws_main_desc']='سادہ چوڑی-شیخر ویر بہاؤ حاسبہ';
$ec_lang['ws_weirLength']='ویر لمبائی، l';
$ec_lang['ws_headWaterHeight']='بالا آب بلندی، h';
$ec_lang['ws_weirCoefficient']='ویر گنجینہ، Cw';
$ec_lang['ws_notes_heading']='نوٹ';
$ec_lang['ws_notes_we_term']='ویر مساوات';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='نامنظم ویر بہاؤ';
$ec_lang['wi_main_title']='مفت آنلائن کھنڈی، متغیر گہرائی، نامنظم ویر بہاؤ حاسبہ';
$ec_lang['wi_main_desc']='نامنظم ویر بہاؤ حاسبہ';
$ec_lang['wi_headWaterelevation']='بالا آب بلندی';
$ec_lang['wi_weirPoints']='ویر نقاط';
$ec_lang['wi_station']='اسٹیشن<br />(فاصلہ)';
$ec_lang['wi_elevation']='بلندی';
$ec_lang['wi_pondingHeight']='تالاب بلندی';
$ec_lang['wi_incrementalFlow']='اضافی بہاؤ';
$ec_lang['wi_cumulativeFlow']='مجموعی بہاؤ';
$ec_lang['wi_save_and_calculate']='محفوظ کریں اور حساب کریں';
$ec_lang['wi_notes_we_term']='ویر مساوات';
$ec_lang['wi_notes_we_def']='q = اگر (لمبائی = 0) تو 0 ورنہ اگر (ڈھلان=0) تو cw*لمبائی*d<sub>0</sub><sup>1.5</sup> ورنہ cw/(2.5*ڈھلان) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) جہاں d<sub>1</sub> اور d<sub>0</sub> ہمیشہ صفر یا مثبت ہوتے ہیں';
// Orifice Flow
$ec_lang['or_main_menu']='سوراخ بہاؤ';
$ec_lang['or_main_title']='مفت آنلائن سوراخ بہاؤ حاسبہ';
$ec_lang['or_main_desc']='سوراخ بہاؤ — آزاد یا ڈوبا ہوا';
$ec_lang['or_shape']='کھلنے کی شکل';
$ec_lang['or_shape_circular']='گول';
$ec_lang['or_shape_rectangular']='مستطیل';
$ec_lang['or_diameter']='قطر یا اونچائی، D <span title="Diameter for circular; height for rectangular" class="ec-tip">?</span>';
$ec_lang['or_width']='چوڑائی، W <span title="Rectangular openings only" class="ec-tip">?</span>';
$ec_lang['or_invert']='انورٹ بلندی <span title="Bottom of opening" class="ec-tip">?</span>';
$ec_lang['or_hwe']='بالا آب بلندی';
$ec_lang['or_twe']='پست آب بلندی';
$ec_lang['or_cd']='اخراج گنجینہ، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='مرکز ثقل بلندی';
$ec_lang['or_head']='مؤثر سر، h';
$ec_lang['or_area']='کھلنے کا رقبہ، A';
$ec_lang['or_flow']='بہاؤ، Q';
$ec_lang['or_velocity']='رفتار، v';
$ec_lang['or_regime']='سوراخ نوع جانچ';
$ec_lang['or_regime_valid']='آزاد اخراج — سوراخ نوع درست ✓';
$ec_lang['or_regime_submerged']='ڈوبا ہوا سوراخ (TWE مرکز ثقل کے اوپر) — درست ✓';
$ec_lang['or_regime_warn']='انتباہ: بالا آب تاج سے نیچے — سوراخ نوع نہیں';
$ec_lang['or_regime_twe_above_hwe']='انتباہ: پست آب (TWE) بالا آب (HWE) سے اوپر — ان پٹ جانچیں';
$ec_lang['or_notes_1_term']='سوراخ مساوات';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh)۔ آزاد اخراج: h = HWE − مرکز ثقل۔ ڈوبا ہوا بہاؤ (انورٹ کے اوپر TWE): h = HWE − TWE۔';
$ec_lang['or_notes_2_term']='سوراخ نوع';
$ec_lang['or_notes_2_def']='سوراخ بہاؤ مساوات اس وقت لاگو ہوتی ہیں جب بالا آب سطح کھلنے کے تاج سے اوپر ہو۔ جب بالا آب تاج سے نیچے ہو، تو ویر مساوات استعمال کریں۔';
$ec_lang['or_notes_3_term']='اخراج گنجینہ';
$ec_lang['or_notes_3_def']='تیز کنارے والے سوراخوں کے لیے C<sub>d</sub> تقریباً 0.60–0.65 تک ہوتا ہے۔ گول یا دوبارہ داخل ہونے والے ان لیٹس مختلف اقدار استعمال کرتے ہیں۔ رہنمائی کے لیے <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> یا HEC-RAS ہائیڈرولک حوالہ دستی دیکھیں۔';
$ec_lang['or_notes_4_term']='ڈوبنا';
$ec_lang['or_notes_4_def']='جب TWE کھلنے کی انورٹ کے اوپر ہو، تو یہ حاسبہ خودکار طور پر h = HWE − TWE استعمال کرتے ہوئے ڈوبا ہوا سوراخ مساوات لاگو کرتا ہے۔ جب TWE انورٹ پر یا اس سے نیچے ہو، تو آزاد اخراج فرض کیا جاتا ہے اور h = HWE − مرکز ثقل۔';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='مائیکرو-ہائیڈرو بجلی';
$ec_lang['mhp_main_title']='مفت آن لائن مائیکرو-ہائیڈرو بجلی کیلکولیٹر';
$ec_lang['mhp_main_desc']='رن-آف-ریور مائیکرو-ہائیڈرو بجلی پیداوار کیلکولیٹر';
$ec_lang['mhp_flow']='بہاؤ کی شرح، Q';
$ec_lang['mhp_gross_head']='مجموعی سر، H<sub>gross</sub>';
$ec_lang['mhp_diameter']='پینسٹاک قطر، D';
$ec_lang['mhp_length']='پینسٹاک لمبائی، L';
$ec_lang['mhp_roughness']='پائپ کی کھردرت، e';
$ec_lang['mhp_km']='ثانوی نقصان عامل، k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='حرکیاتی چپچپاہٹ، ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='پلانٹ کارکردگی، η (0–1)';
$ec_lang['mhp_velocity']='بہاؤ کی رفتار، v';
$ec_lang['mhp_vel_check']='رفتار کی جانچ';
$ec_lang['mhp_f']='رگڑ گتانک، f';
$ec_lang['mhp_hf']='رگڑ سر نقصان، h<sub>f</sub>';
$ec_lang['mhp_hm']='ثانوی نقصان، h<sub>m</sub>';
$ec_lang['mhp_hl']='کل پینسٹاک نقصان، h<sub>L</sub>';
$ec_lang['mhp_hl_check']='سر نقصان کی جانچ';
$ec_lang['mhp_hnet']='خالص سر، H<sub>net</sub>';
$ec_lang['mhp_power']='طاقت پیداوار، P';
$ec_lang['mhp_annual_kwh']='100% صلاحیت پر سالانہ توانائی';
$ec_lang['mhp_vel_ok']='1–3 m/s — ہدف کے اندر ✓';
$ec_lang['mhp_vel_low']='رفتار کم — تلچھٹ اور ہوا داخل ہونے کا خطرہ۔';
$ec_lang['mhp_vel_high']='رفتار زیادہ — منتقلی کے نقصانات، دستیاب توانائی اور پانی کے ہتھوڑے کا خطرہ جانچیں۔';
$ec_lang['mhp_vel_ok_short']='ٹھیک';
$ec_lang['mhp_vel_high_short']='زیادہ';
$ec_lang['mhp_vel_low_short']='کم';
$ec_lang['mhp_hl_ok']='10% ہدف کے اندر ✓';
$ec_lang['mhp_hl_warn']='10% ہدف سے زیادہ — بڑے پائپ پر غور کریں ⚠';
$ec_lang['mhp_hl_bad']='20% سے زیادہ — پائپ کی سائزنگ دوبارہ کریں';
$ec_lang['mhp_notes_1_term']='سر نقصان';
$ec_lang['mhp_notes_1_def']='کل نقصان h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، جہاں h<sub>f</sub> = f(L/D)(v²/2g) ڈارسی-وائزباخ رگڑ نقصان ہے اور h<sub>m</sub> = k<sub>m</sub>·v²/2g داخلہ، موڑ اور والوز کا احاطہ کرتا ہے۔ خالص سر H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='رفتار';
$ec_lang['mhp_notes_2_def']='ہدف 1–3 m/s۔ 1 m/s سے کم پائپ ضرورت سے بڑا ہے؛ 3 m/s سے زیادہ رگڑ نقصان اور پانی کے ہتھوڑے کا خطرہ بڑھتا ہے۔';
$ec_lang['mhp_notes_3_term']='سر نقصان کا ہدف';
$ec_lang['mhp_notes_3_def']='مجموعی سر کے 10% سے کم پینسٹاک نقصان عموماً اقتصادی ہے۔ پائپ کی لاگت اور ضائع ہونے والی طاقت کے درمیان زیادہ سے زیادہ توازن اکثر اعلی قیمتی بجلی کے مقامات کے لیے 4–6% کے قریب ہوتا ہے۔';
$ec_lang['mhp_notes_4_term']='ثانوی نقصانات k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='مخصوص اقدار: تیز داخلہ 0.5، ہر 45° موڑ 0.2–0.3، گیٹ والو (مکمل کھلا) 0.1، بٹرفلائی والو 0.2۔ تمام فٹنگز کا مجموع کل k<sub>m</sub> ہے۔ ڈیفالٹ 1.5 ایک داخلہ اور دو موڑ فرض کرتا ہے۔';
$ec_lang['mhp_notes_5_term']='پائپ کی کھردرت e';
$ec_lang['mhp_notes_5_def']='مخصوص مطلق کھردرت: اسٹیل (نیا) 0.046 ملی میٹر، اسٹیل (پرانا) 0.15 ملی میٹر، HDPE 0.003 ملی میٹر، PVC/uPVC 0.0015 ملی میٹر، کنکریٹ 0.3–3 ملی میٹر۔ HDPE چھوٹے مائیکرو-ہائیڈرو پینسٹاک کے لیے عام ہے۔';
$ec_lang['mhp_notes_6_term']='کارکردگی';
$ec_lang['mhp_notes_6_def']='مائیکرو-ہائیڈرو میں عام Pelton اور کراس-فلو ٹربائن کے لیے مخصوص پلانٹ کارکردگی &eta; 0.70 سے 0.85 تک ہوتی ہے۔ ابتدائی قدامت پسند تخمینے کے طور پر 0.75 استعمال کریں۔';
$ec_lang['mhp_notes_7_term']='سالانہ توانائی';
$ec_lang['mhp_notes_7_def']='سالانہ توانائی مسلسل مکمل بہاؤ آپریشن (8760 گھنٹے/سال) فرض کرتی ہے۔ موسمی بہاؤ تغیر، دیکھ بھال بند وقت اور بار گتانک کی وجہ سے اصل پیداوار کم ہوگی۔';

// Orifice Drain Time
$ec_lang['odt_main_menu']='سوراخ نکاسی وقت';
$ec_lang['odt_main_title']='مفت آنلائن سوراخ نکاسی وقت حاسبہ — تالاب، حوض یا ٹینک';
$ec_lang['odt_main_desc']='تالاب یا حوض سوراخ نکاسی وقت — مخروطی حجم طریقہ';
$ec_lang['odt_h1_elev']='ابتدائی WSE <span title="Starting water surface elevation" class="ec-tip">?</span>';
$ec_lang['odt_a1']='ابتدائی رقبہ، A<sub>1</sub>';
$ec_lang['odt_h2_elev']='آخری WSE';
$ec_lang['odt_h_orifice']='سوراخ مرکز ثقل بلندی';
$ec_lang['odt_a0']='سوراخ سطح رقبہ، A<sub>0</sub>';
$ec_lang['odt_a_ending']='آخری رقبہ، A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='آخری بلندی جانچ';
$ec_lang['odt_h2_ok']='آخری بلندی سوراخ تاج کے اوپر ✓';
$ec_lang['odt_h2_warn']='انتباہ: آخری بلندی سوراخ تاج پر یا اس سے نیچے (مرکز ثقل + D/2)';
$ec_lang['odt_d']='سوراخ D <span title="Diameter (circular) or height (rectangular)" class="ec-tip">?</span>';
$ec_lang['odt_w']='سوراخ چوڑائی، W <span title="Rectangular only" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='وقت (s)';
$ec_lang['odt_t_min']='وقت (min)';
$ec_lang['odt_t_hr']='وقت (hr)';
$ec_lang['odt_t_day']='وقت (days)';
$ec_lang['odt_notes_1_term']='فارمولا';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) سر H سے سوراخ تک نکاسی وقت دیتا ہے۔ نکاسی وقت = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، جہاں H<sub>1</sub> = ابتدائی بلندی − سوراخ بلندی، H<sub>2</sub> = آخری بلندی − سوراخ بلندی۔';
$ec_lang['odt_notes_2_term']='طریقہ';
$ec_lang['odt_notes_2_def']='مخروطی حجم طریقہ تالاب یا حوض کو ابتدائی آبی سطح پر A<sub>1</sub> اور سوراخ مرکز ثقل بلندی پر A<sub>0</sub> کے درمیان ایک مخروطی حصے کے طور پر ماڈل کرتا ہے۔ A<sub>2</sub>، آخری بلندی پر تالاب کا رقبہ، مخروطی حصہ ماڈل استعمال کرتے ہوئے A<sub>1</sub> اور A<sub>0</sub> سے تخمینہ کیا جاتا ہے۔ ابتدائی سے آخری بلندی تک نکاسی وقت H<sub>1</sub> سے سوراخ تک کل نکاسی وقت سے H<sub>2</sub> سے سوراخ تک باقی نکاسی وقت گھٹانے کے برابر ہے۔';
$ec_lang['odt_h1']='ابتدائی سر، H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='زیادہ بہاؤ، Q<sub>max</sub>';
$ec_lang['odt_vol']='نکالا گیا حجم';
$ec_lang['odt_sketch_start']='آغاز';
$ec_lang['odt_sketch_end']='اختتام';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='کنارے سے کنارے چوڑائی';
$ec_lang['essc_mcr']='کم سے کم انحناء نصف قطر';
$ec_lang['essc_q']='بہاؤ، Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='آبپاشی';
$ec_lang['irr_main_title']='آبپاشی بہاؤ پیمائش کے مفت آن لائن حسابگر';
$ec_lang['irr_main_desc']='آبپاشی بہاؤ پیمائش — ویئر اور اوریفس';
$ec_lang['irr_intro_html']='<p>ویئر اور اوریفس آبپاشی نظاموں میں پانی کے بہاؤ کی پیمائش کے لیے معیاری میدانی اوزار ہیں۔ وہ کیلکولیٹر منتخب کریں جو آپ کے ڈھانچے سے مطابقت رکھتا ہو:</p>';
$ec_lang['irr_card_weir_uniform_head']='ویئر — چوڑی کرسٹ (یکساں چوڑائی)';
$ec_lang['irr_card_weir_uniform_desc']='ڈائیورژن ڈیم کرسٹ، کنٹرول ڈھانچے یا ویئر بورڈ پر بہاؤ ناپیں۔ ویئر کی لمبائی اور کرسٹ سے اوپر پانی کی گہرائی درج کریں۔';
$ec_lang['irr_card_weir_irregular_head']='ویئر — بے قاعدہ پروفائل';
$ec_lang['irr_card_weir_irregular_desc']='استعمال کریں جب ویئر کرسٹ ایک یکساں اونچائی پر نہ ہو — قدرتی اسپل وے، متغیر چوڑائی کے ڈراپ ڈھانچے، یا کثیر مقطع کنٹرول ڈھانچے۔';
$ec_lang['irr_card_orifice_head']='اوریفس — ہیڈ گیٹ یا پائپ آؤٹ لیٹ';
$ec_lang['irr_card_orifice_desc']='سلیوس گیٹ، پائپ آؤٹ لیٹ، یا کلورٹ کھلنے سے بہاؤ ناپیں۔ خودبخود آزاد بہاؤ اور ڈوبے ہوئے (ٹیل واٹر) دونوں حالات سنبھالتا ہے۔';
$ec_lang['irr_card_canal_head']='نہر ڈیزائن & تجزیہ';
$ec_lang['irr_card_canal_desc']='Manning\'s فارمولا استعمال کرتے ہوئے آبپاشی نہر ڈیزائن یا جانچیں۔ نئی نہروں کے لیے ٹریپیزائڈل کیلکولیٹر؛ موجودہ قدرتی یا بنائے گئے مقاطع کے لیے بے قاعدہ کیلکولیٹر۔';
$ec_lang['irr_card_seepage_head']='نہر رسائی & ترسیل کارکردگی';
$ec_lang['irr_card_seepage_desc']='آمد اور خروج پیمائشوں سے نہر پہنچ میں رسائی نقصان کا تخمینہ لگائیں۔ ترسیل کارکردگی اور سالانہ پانی ضیاع کا حساب کریں تاکہ استرکاری سرمایہ کاری کو ترجیح دینے میں مدد ملے۔';
$ec_lang['irr_quickref_html']='<h3>فوری حوالہ</h3><dl><dt>ڈائیورژن ڈیم یا کنٹرول ڈھانچہ</dt><dd>ویئر کرسٹ کے اوپر پانی کی گہرائی ناپیں۔ یکساں کرسٹ کے لیے <a href="Weir-Flow-Simple.php">سادہ ویئر فلو</a> اور پروفائل یا زینہ دار کرسٹ کے لیے <a href="Weir-Flow-Irregular.php">بے قاعدہ ویئر فلو</a> استعمال کریں۔</dd><dt>ہیڈ گیٹ یا پائپ آؤٹ لیٹ</dt><dd>اوپر اور نیچے سطح آب ناپیں (یا آزاد بہاؤ میں پائپ تہہ کی بلندی)۔ <a href="Orifice.php">اوریفس فلو</a> استعمال کریں۔ گول پائپ کے لیے D = پائپ قطر؛ مستطیل گیٹ کے لیے چوڑائی W اور اونچائی D درج کریں۔</dd><dt>ذخیرے یا تالاب کے خالی ہونے کا وقت</dt><dd>تالاب یا ذخیرے کی سطح تہہ کے اوریفس سے کم کرنے میں لگنے والا وقت تخمین لگانے کے لیے <a href="Orifice-Drain-Time.php">اوریفس نکاسی وقت</a> استعمال کریں — آبپاشی ذخیرہ منصوبہ بندی کے لیے مفید۔</dd><dt>میدانی معیارات</dt><dd>یہاں استعمال کردہ ویئر اور اوریفس بہاؤ مساوات USBR <em>Water Measurement Manual</em> (تیسرا ایڈیشن) طریقہ کار سے مطابقت رکھتی ہیں جو عموماً پانی کے نگرانوں اور آبپاشی اضلاع کے ذریعے ضروری ہوتی ہیں۔</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='ایمیٹر فاصلہ، S<sub>e</sub>';
$ec_lang['ip_sl']='لیٹرل فاصلہ، S<sub>l</sub>';
$ec_lang['ip_n_e']='لیٹرل فی ایمیٹر، n<sub>e</sub>';
$ec_lang['ip_n_l']='زون فی لیٹرل، n<sub>l</sub>';
$ec_lang['ip_d']='ہدف اطلاق گہرائی، d';
$ec_lang['ip_a_e']='ہر ایمیٹر فی رقبہ، A<sub>e</sub>';
$ec_lang['ip_pr']='اطلاق کی شرح، PR';
$ec_lang['ip_q_lat']='لیٹرل فی بہاؤ، Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='زون بہاؤ، Q<sub>zone</sub>';
$ec_lang['ip_t_run']='چلانے کا وقت (گھنٹے)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='نہر رسائی';
$ec_lang['cs_main_title']='مفت آن لائن نہر رسائی نقصان اور ترسیل کارکردگی حاسبہ';
$ec_lang['cs_main_desc']='نہر رسائی نقصان & ترسیل کارکردگی — آمد-خروج طریقہ';
$ec_lang['cs_Q_in']='آمد، Q<sub>in</sub>';
$ec_lang['cs_Q_out']='خروج، Q<sub>out</sub>';
$ec_lang['cs_L']='پہنچ کی لمبائی، L';
$ec_lang['cs_wp']='تر محیط، P<sub>w</sub>';
$ec_lang['cs_Q_loss']='رسائی نقصان شرح، Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='پیمائش جانچ';
$ec_lang['cs_pct_loss']='نقصان کا کسر';
$ec_lang['cs_Ec']='ترسیل کارکردگی، E<sub>c</sub>';
$ec_lang['cs_Ec_check']='کارکردگی درجہ بندی';
$ec_lang['cs_Vol_day']='روزانہ ضائع ہونے والا حجم';
$ec_lang['cs_Vol_year']='سالانہ ضائع ہونے والا حجم';
$ec_lang['cs_Q_loss_per_L']='نقصان فی لمبائی، Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='پانی کی قیمت';
$ec_lang['cs_lining_cost']='لائننگ کی لاگت';
$ec_lang['cs_Ec_target']='ہدف ترسیل کارکردگی، E<sub>c,target</sub> <span title="استرکاری کے بعد ترسیل کارکردگی کا ہدف؛ حصہ 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='لائننگ رقبہ، L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='سالانہ ضائع شدہ قیمت';
$ec_lang['cs_annual_value_recovered']='سالانہ بحال شدہ قیمت';
$ec_lang['cs_lining_total_cost']='کل لائننگ لاگت';
$ec_lang['cs_payback_years']='واپسی مدت <span title="Simple payback = total lining cost ÷ annual value recovered" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — رسائی پکڑی گئی ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — کوئی قابل پیمائش نقصان نہیں';
$ec_lang['cs_loss_negative']='انتباہ: Qout > Qin — پیمائشیں جانچیں ⚠';
$ec_lang['cs_Ec_good']='اچھا — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='قابل قبول — Ec 60–80%';
$ec_lang['cs_Ec_poor']='ناقص — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='طریقہ';
$ec_lang['cs_notes_1_def']='آمد-خروج طریقہ نہر کی پہنچ کے سر اور دم پر بہاؤ ناپ کر رسائی کا تخمینہ لگاتا ہے: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>۔ ترسیل کارکردگی E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>۔ سالانہ حجم مسلسل مکمل بہاؤ آپریشن فرض کرتا ہے؛ موسمی یا جزوی بہاؤ نہروں میں اصل نقصان کم ہوگا۔';
$ec_lang['cs_notes_2_term']='کارکردگی درجہ بندیاں';
$ec_lang['cs_notes_2_def']='عام غیر استرکاری مٹی نہریں: E<sub>c</sub> = 60–80%۔ اچھی طرح دیکھ بھال کی مٹی نہریں: 75–85%۔ کنکریٹ استرکاری نہریں: 90–98%۔ آمد کے 30% سے زیادہ رسائی نقصانات اکثر استرکاری سرمایہ کاری کو درست ثابت کرتے ہیں۔ (USBR، FAO)';
$ec_lang['cs_notes_3_term']='لائننگ واپسی';
$ec_lang['cs_notes_3_def']='کسی بھی مطابقت پذیر کرنسی میں پانی کی قیمت اور لائننگ کی لاگت درج کریں۔ لائننگ کا رقبہ = پہنچ کی لمبائی × تر محیط — ناپی گئی بہاؤ کی گہرائی پر نہر کے عرضی مقطع کا تر محیط (تہ کی چوڑائی اور دونوں تر ڈھلانیں)۔ سالانہ واپس حاصل کی گئی قیمت فرض کرتی ہے کہ لائن شدہ نہر مسلسل مطلوبہ E<sub>c</sub> تک پہنچتا ہے۔ موسمی نہروں یا اگر لائننگ مطلوبہ کارکردگی تک نہ پہنچے تو اصل واپسی طویل تر ہوگی۔';
$ec_lang['cs_notes_4_term']='حوالہ';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>، تیسرا ایڈیشن (2001)۔ FAO Irrigation and Drainage Paper 57 (1999)۔';
// About
$ec_lang['about_main_menu']='کے بارے میں';
$ec_lang['install_main_menu']='انسٹال کریں';
$ec_lang['install_main_title']='EngCalcs انسٹال کریں';
$ec_lang['install_main_desc']='آف لائن استعمال کے لیے اپنے آلے میں شامل کریں';
$ec_lang['contact_main_menu']='رابطہ';
$ec_lang['about_main_title']='HawsEDC انجینئرنگ کیلکولیٹرز کے بارے میں';
$ec_lang['about_main_desc']='مشن، اوپن سورس اور تعاون';
$ec_lang['about_body_html']='<h3>مشن</h3><p>HawsEDC انجینیئرنگ کیلکولیٹر دنیا بھر کے انجینیئروں اور میدانی کارکنوں کی خدمت کے لیے موجود ہیں — خاص طور پر ان لوگوں کے لیے جو پانی کی قلت، محدود وسائل، یا کم خدمت والے علاقوں میں کام کرتے ہیں۔ یہ اوزار ایک وسیع انسانی مشن کا حصہ ہیں: ہر انسان کو سب سے عملی اور مؤثر طریقے سے بتانا کہ وہ ہمیشہ کے لیے محبوب اور عزیز ہے، کہ اسے ڈرنے کی ضرورت نہیں، اور یہ کہ وہ سب کچھ تباہ نہیں کرے گا۔</p><p>کیلکولیٹر ذریعہ ہیں۔ منزل تکلیف سے پاک دنیا ہے۔</p><h3>اوپن سورس لائسنس</h3><p>تمام کوڈ <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 یا بعد کے ورژن</a> کے تحت جاری کیا گیا ہے — آزادی کے معنوں میں آزاد۔ آپ انہی شرائط کے تحت کوڈ استعمال، مطالعہ، ترمیم اور دوبارہ تقسیم کر سکتے ہیں۔</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>سورس کوڈ</h3><p>مکمل سورس کوڈ Bitbucket پر عوامی طور پر دستیاب ہے:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>آپ وہاں کوڈ دیکھ سکتے ہیں، مسائل درج کر سکتے ہیں، یا ریپوزیٹری فورک کر سکتے ہیں۔</p><h3>تعاون</h3><p>Pull requests کا خیرمقدم ہے۔ تعاون کے طریقے:</p><ul><li><strong>ترجمے</strong> — کوئی زبان بہتر کریں یا نئی شامل کریں۔ متعلقہ <code>lib/lang.ec.??.php</code> فائل میں تبدیلیوں کے ساتھ pull request کھولیں۔</li><li><strong>بگ رپورٹس</strong> — کسی بھی کیلکولیٹر صفحے پر فیڈ بیک فارم استعمال کریں، یا Bitbucket پر مسئلہ درج کریں۔</li><li><strong>نئے کیلکولیٹر</strong> — میدانی کارکنوں اور آبپاشی پیشہ وروں کی خدمت کرنے والے ہائیڈرولک انجینیئرنگ اوزار کے لیے خیالات خاص طور پر خوش آمدید ہیں۔ ریپوزیٹری میں <code>CLAUDE.md</code> ڈویلپر گائیڈ دیکھیں۔</li><li><strong>ہوسٹنگ</strong> — اگر آپ محدود رابطے والے علاقے کے لیے ان کیلکولیٹروں کا آئینہ بنا سکتے ہیں تو رابطہ کریں۔</li></ul><h3>آف لائن استعمال</h3><p>یہ حسابگر پروگریسو ویب ایپ (PWA) کے طور پر کام کرتے ہیں۔ انٹرنیٹ سے منسلک ہونے کے دوران کسی بھی حسابگر صفحے پر جائیں، اور آپ کا براؤزر تمام حسابگر خود بخود محفوظ کر لے گا۔ اس کے بعد، تمام حسابگر آف لائن کام کرتے ہیں — انٹرنیٹ کی ضرورت نہیں۔</p><p>Android یا iOS پر، EngCalcs کو اپنے آلے پر ایپ کے طور پر نصب کرنے کے لیے اپنے براؤزر کا "ہوم اسکرین پر شامل کریں" اختیار استعمال کریں۔ ڈیسک ٹاپ پر، اپنے براؤزر کی ایڈریس بار میں نصب آئیکن تلاش کریں۔</p><p>آپ اپنے براؤزر کے "بطور محفوظ کریں…" مینو کا استعمال کرتے ہوئے کوئی بھی انفرادی حسابگر ایک بار کے آف لائن استعمال کے لیے محفوظ کر سکتے ہیں۔</p><h3>رابطہ</h3><p>Tom Haws — ہائیڈرولک انجینیئر اور ان کیلکولیٹروں کے مصنف۔<br />کسی بھی کیلکولیٹر صفحے پر فیڈ بیک فارم استعمال کریں، یا <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> پر سورس کوڈ تک رسائی حاصل کریں۔</p>';
$ec_lang['contact_title']='HawsEDC سے رابطہ';
$ec_lang['contactSendMessage']='Tom Haws کو پیغام بھیجیں';
$ec_lang['contactYourName']='آپ کا نام:';
$ec_lang['contactYourEmail']='آپ کا ای-میل پتہ:';
$ec_lang['contactSubject']='موضوع:';
$ec_lang['contact_message']='پیغام:';
$ec_lang['contactSpamPrefix']='پانچ جمع ایک برابر';
$ec_lang['contactSpamPostfix']='(براہ کرم انگریزی میں لکھیں۔ 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='پیغام بھیجیں';
$ec_lang['contact_success']='آپ کا وقت لگا کر لکھنے کے لیے شکریہ۔';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='راک چوٹ ڈیزائن (Robinson)';
$ec_lang['rc_main_title']='مفت آن لائن راک چوٹ ڈیزائن کیلکولیٹر — Robinson (1998)';
$ec_lang['rc_main_desc']='راک چوٹ ریپ‌ریپ سائزنگ — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='چوٹ بیڈ ڈھلان، S<sub>0</sub>';
$ec_lang['rc_qt']='کل یونٹ ڈسچارج، q<sub>t</sub> <span title="چوٹ ان لیٹ پر فی یونٹ چوڑائی بہاؤ۔ نچلی چوڑائی B اور کل بہاؤ Q والی نہر کے لیے q_t = Q / B استعمال کریں۔" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='ریپ‌ریپ پوروسٹی، n<sub>p</sub>';
$ec_lang['rc_sg']='چٹان کی مخصوص کشش ثقل، sg <span title="عام کٹا ہوا گرینائٹ یا بیسالٹ ≈ 2.65۔ Robinson کی درست حد: 2.54 سے 2.82۔" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='گریڈیشن SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="گریڈیشن اسٹینڈرڈ ڈیویشن۔ یکساں چٹان ≈ 1.25۔ Robinson کی درست حد: 1.15 سے 1.47۔" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='ان لیٹ چینل میں نارمل گہرائی، y<sub>n</sub> <span title="پانی جمع ہونا (Hp > yn) اچھا ہے — اوپری جانب کٹاؤ کم کرتا ہے۔ (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='مطلوب درمیانہ چٹان سائز، D<sub>50</sub> <span title="مساوات 1 (S0 < 0.10) یا مساوات 2 (0.10-0.40)۔ درست: D50 بین 15 اور 278 ملی میٹر، S0 بین 0.02 اور 0.40۔ حد سے باہر: اضافی تخمینہ۔" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='لاگو مساوات';
$ec_lang['rc_sg_check']='مخصوص کشش ثقل کی جانچ';
$ec_lang['rc_SD_check']='گریڈیشن SD کی جانچ';
$ec_lang['rc_sg_ok']   ='sg درست حد میں (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='انتباہ: sg < 2.54 — Robinson حد سے کم';
$ec_lang['rc_sg_high'] ='انتباہ: sg > 2.82 — Robinson حد سے زیادہ';
$ec_lang['rc_SD_ok']   ='SD درست حد میں (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='انتباہ: SD < 1.15 — Robinson حد سے کم';
$ec_lang['rc_SD_high'] ='انتباہ: SD > 1.47 — Robinson حد سے زیادہ';
$ec_lang['rc_layer']='چٹان کی تہہ کی موٹائی (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='اوپری کرسٹ وکر کا نصف قطر (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='اوپری کرسٹ وکر آرک کی لمبائی';
$ec_lang['rc_apron_length']='آؤٹ لیٹ ایپرن لمبائی (15 × D<sub>50</sub>) <span title="چوٹ کی چٹانوں کی ساختی مدد کے لیے ضروری۔ «آؤٹ لیٹ ریچ اور نیچے کی جانب چینل کی مزاحمت سے پیدا ہونے والا کم سے کم ٹیل واٹر آؤٹ لیٹ ریچ میں ریپ‌ریپ کی استحکام یقینی بنانے کے لیے کافی ہے۔» (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='چوٹ میں Manning کی کھردرائی، n';
$ec_lang['rc_Vm']='چٹان مینٹل سے گزرنے کی رفتار، V<sub>m</sub> <span title="qt کا وہ حصہ جو چٹان کے سوراخوں سے گزرتا ہے۔ باقی qs سطح پر بہتا ہے۔ ڈیفالٹ np = 0.45 زاویہ دار کٹی ہوئی چٹان کے لیے۔" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='مینٹل سے یونٹ بہاؤ، q<sub>m</sub>';
$ec_lang['rc_qs']='سطحی یونٹ بہاؤ، q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='ریپ‌ریپ سطح کے اوپر بہاؤ کی گہرائی، d';
$ec_lang['rc_Hp']='ان لیٹ ویئر ہیڈ، H<sub>p</sub> <span title="پانی جمع ہونا (Hp > yn) اچھا ہے — اوپری جانب کٹاؤ کم کرتا ہے۔ (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='ان لیٹ پر پانی جمع ہونے کی جانچ';
$ec_lang['rc_pond_ok']  ='Hp > yn — بالائی جانب پانی جمع ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — پانی جمع نہیں — ان لیٹ کو کٹاؤ کے لیے جانچیں';
$ec_lang['rc_eq1']='مساوات 1 (S0 < 0.10) — ہلکی ڈھلان';
$ec_lang['rc_eq2']='مساوات 2 (0.10 ≤ S0 ≤ 0.40) — تیز ڈھلان';
$ec_lang['rc_eq_warn_low']='انتباہ: S0 < 0.02 — Robinson توثیقی حد سے کم';
$ec_lang['rc_eq_warn_high']='انتباہ: S0 > 0.40 — Robinson توثیقی حد سے زیادہ';
$ec_lang['rc_notes_1_term']='چٹان سائزنگ مساوات';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) نے چوٹ ڈھلان اور یونٹ ڈسچارج کی بنیاد پر درمیانے ریپ‌ریپ سائز D<sub>50</sub> کے لیے دو تجرباتی مساوات بنائیں۔ مساوات 1 ہلکی ڈھلانوں کے لیے ہے (S<sub>0</sub> < 0.10)؛ مساوات 2 تیز ڈھلانوں کے لیے ہے (0.10 ≤ S<sub>0</sub> ≤ 0.40)۔ دونوں مساوات کو q<sub>t</sub> m²/s میں درکار ہے اور D<sub>50</sub> ملی میٹر میں دیتی ہیں۔ توثیق شدہ حد 0.02 ≤ S<sub>0</sub> ≤ 0.40 ہے۔';
$ec_lang['rc_notes_2_term']='یونٹ ڈسچارج';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> چوٹ کرسٹ پر کل یونٹ ڈسچارج ہے (فی یونٹ چوڑائی کل بہاؤ)۔ نچلی چوڑائی B اور کل بہاؤ Q والی نہر کے لیے، q<sub>t</sub> ≈ Q / B تخمین لگائیں، یا چوٹ ان لیٹ پر کریٹیکل ڈیپتھ کنڈیشن سے حساب لگائیں۔';
$ec_lang['rc_notes_3_term']='چٹان مینٹل سے بہاؤ';
$ec_lang['rc_notes_3_def']='کل بہاؤ کا ایک حصہ چٹان ریپ‌ریپ کے سوراخوں سے گزرتا ہے (مینٹل بہاؤ q<sub>m</sub>)؛ باقی چٹان کی سطح پر بہتا ہے (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>)۔ بہاؤ گہرائی d کو Manning کی مساوات کے ذریعے سطحی بہاؤ q<sub>s</sub> پر چوٹ کھردرائی n استعمال کرتے ہوئے حساب کیا جاتا ہے۔ ڈیفالٹ پوروسٹی n<sub>p</sub> = 0.45 زاویہ دار کٹی ہوئی چٹان کے لیے عام ہے۔';
$ec_lang['rc_notes_5_term']='چٹان سائز کی درست حد';
$ec_lang['rc_notes_5_def']='مساوات D<sub>50</sub> کی 15 ملی میٹر سے 278 ملی میٹر کی حد استعمال کرتے ہوئے بنائی گئی تھیں۔ اس حد سے باہر کے نتائج اضافی تخمینے ہیں اور انہیں اضافی انجینیئرنگ فیصلے کے ساتھ استعمال کرنا چاہیے۔';
$ec_lang['rc_notes_6_term']='آؤٹ لیٹ ایپرن کی بلندی';
$ec_lang['rc_notes_6_def']='آؤٹ لیٹ ریچ میں ریپ‌ریپ کے اوپری حصے کی بلندی نیچے کی جانب چینل کے بیڈ کی بلندی کے برابر یا کم ہونی چاہیے۔ اگر زیادہ ہو تو آؤٹ لیٹ کی چٹانیں غیر مستحکم ہوں گی۔';
$ec_lang['rc_notes_7_term']='ان لیٹ پونڈنگ چیک';
$ec_lang['rc_notes_7_def']='جب ان لیٹ چینل میں نارمل گہرائی ویئر ہیڈ (H<sub>p</sub>) سے کم ہو جو q<sub>t</sub> گزارنے کے لیے درکار ہے، تو ان لیٹ ایپرن کے اوپری جانب محدود بہاؤ یا پانی جمع ہوتا ہے۔ یہ عموماً قابل قبول ہے — پانی جمع ہونے سے رفتار کم ہوتی ہے اور اوپری جانب کٹاؤ روکتا ہے۔ جانچ کے لیے: ویئر فلو کیلکولیٹر استعمال کریں تاکہ دیے گئے q<sub>t</sub> اور کرسٹ چوڑائی کے لیے H<sub>p</sub> معلوم ہو، اور ان لیٹ چینل کی نارمل گہرائی سے موازنہ کریں۔ اگر H<sub>p</sub> نارمل گہرائی سے زیادہ ہو تو پانی جمع ہوگا۔';
$ec_lang['rc_notes_4_term']='حوالہ';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS اسی طریقہ پر مبنی ایک <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel اسپریڈ شیٹ</a> بھی شائع کرتی ہے۔';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'فلٹر';
$ec_lang['rc_sketch_top_crest_curve'] = 'چوٹی کا منحنی';
$ec_lang['rc_sketch_outlet_apron']    = 'آؤٹ لیٹ ایپرن';
$ec_lang['rc_sketch_radius']          = 'نصف قطر';
