<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='частка';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% підйом/довжина';
$ec_lang['u_grade']='підйом/довжина';
$ec_lang['u_in2']='кв. дюйм';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='л/с';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='с';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Calculators';
$ec_lang['menu_main_list']='Список калькуляторів';
$ec_lang['menu_main_hydraulics']='Гідравліка';
$ec_lang['menu_main_language']='Мова';
$ec_lang['template_welcome']='&gt;&gt; Залиш свої страхи за дверима; тут розмовляють мовою любові. Ти не все руйнуєш. Насолоджуйся також <a target="_blank" href="https://hawsedc.com/download.php">безкоштовними інструментами HawsEDC AutoCAD</a>. &lt;&lt;';
$ec_lang['template_translation_help']='Чи маєте ви ідею для нового калькулятора? Чи можете допомогти з перекладом, програмуванням або розміщенням цих калькуляторів? ';
$ec_lang['template_feedback']='Будь ласка, поділіться своїми цінними порадами або словами подяки. Чи перевершив цей безкоштовний калькулятор ваші очікування?';
$ec_lang['template_printable_title']='Заголовок для друку';
$ec_lang['template_printable_subtitle']='Підзаголовок для друку';
$ec_lang['index_title']='Безкоштовні онлайн-калькулятори для інженерів';
$ec_lang['calc_set_units']='Встановити одиниці:';
$ec_lang['points_data_help']='(або Копіювати/Вставити через область даних)';
$ec_lang['points_data_title']='Дані точок<br />(розділені комою або табуляцією)';
$ec_lang['points_data_copy']='Копіювати';
$ec_lang['points_data_paste']='Вставити';
$ec_lang['calc_inputs']='Вхідні дані';
$ec_lang['calc_results']='Результати';
$ec_lang['view_hide_line']='[Сховати цей рядок]';
$ec_lang['view_printable']='Версія для друку (перезавантажте для відновлення)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Втрати напору в трубі за Darcy-Weisbach';
$ec_lang['dw_main_title']='Безкоштовний онлайн-калькулятор втрат напору в трубі за Darcy-Weisbach';
$ec_lang['dw_main_desc']='Втрати напору в трубі за Darcy-Weisbach при заданому діаметрі, шорсткості та витраті';
$ec_lang['dw_roughness']='Абсолютна шорсткість Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Кінематична в\'язкість, v, у m<sup>2</sup>/sec (1E-6 для чистої води при кімнатній температурі)';
$ec_lang['dw_reynolds_number']='Число Рейнольдса, Re';
$ec_lang['dw_flow_regime']='Режим течії';
$ec_lang['dw_regime_laminar']='ламінарний';
$ec_lang['dw_regime_transitional']='перехідний';
$ec_lang['dw_regime_turbulent']='турбулентний';
$ec_lang['dw_friction_factor_method']='Метод визначення коефіцієнта тертя';
$ec_lang['dw_friction_factor']='Коефіцієнт тертя, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Втрати напору в трубі за Hazen-Williams';
$ec_lang['hw_main_title']='Безкоштовний онлайн-калькулятор втрат напору в трубі за Hazen-Williams';
$ec_lang['hw_main_desc']='Втрати напору в трубі за Hazen-Williams при заданому діаметрі, шорсткості та витраті';
$ec_lang['hw_hgl_1']='П\'єзометрична лінія нижче за течією';
$ec_lang['hw_hgl_2']='П\'єзометрична лінія вище за течією';
$ec_lang['hw_roughness']='Коефіцієнт Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning — Нерегулярне русло';
$ec_lang['mi_main_title']='Безкоштовний онлайн-калькулятор нерегулярного русла за Manning';
$ec_lang['mi_main_desc']='Калькулятор рівномірної течії в нерегулярному руслі за Manning';
$ec_lang['mi_waterSurfaceElevation']='Відмітка поверхні води';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Точки поперечного перерізу';
$ec_lang['mi_groupPoint']='Точка';
$ec_lang['mi_groupSegment']='Ділянка';
$ec_lang['mi_groupRegion']='Зона';
$ec_lang['mi_station']='Пікет';
$ec_lang['mi_elevation']='Відмітка';
$ec_lang['mi_d50in']='Облицювання<br />медіанний<br />розмір<br />каменю';
$ec_lang['mi_n']='n<br />для<br />ділян-<br />ки';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />межа<br />зони<br />(Берег)';
$ec_lang['mi_tau']='Дон.<br />дотич.<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Композ.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Примітки';
$ec_lang['mi_notes_1_term']='Складений n';
$ec_lang['mi_notes_1_def']='Цей калькулятор дотримується довідкового посібника HEC-RAS у розрахунку складеного n зони за Chow 1959, стор. 136, рівняння 6-17 (не 6-18).';
$ec_lang['mi_notes_2_term']='Кам\'яне облицювання';
$ec_lang['mi_notes_2_def']='Для проектування кам\'яного облицювання використовуйте калькулятор трапецієвидного русла Manning. Цей калькулятор призначений більше для природних перерізів.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning — Течія в трубі';
$ec_lang['mpf_main_title']='Безкоштовний онлайн-калькулятор течії в трубі за Manning';
$ec_lang['mpf_main_desc']='Рівномірна течія в трубі за формулою Manning при заданому похилі та глибині';
$ec_lang['mpf_spreadheet_notice']='Ознайомтесь з табличною версією цього калькулятора';
$ec_lang['mpf_pipe_diameter']='Діаметр труби, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Коефіцієнт шорсткості Manning, n';
$ec_lang['mpf_friction_slope']='Похил п\'єзометричної лінії (можливо <a target="_blank" href="../pressureslope.php">?</a> дорівнює похилу труби), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Відносна глибина течії, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Дивіться примітки)';
$ec_lang['mpf_flow']='Витрата, Q';
$ec_lang['mpf_velocity']='Швидкість, v';
$ec_lang['mpf_velocity_head']='Швидкісний напір, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Площа живого перерізу, a';
$ec_lang['mpf_pipe_area']='Площа перерізу труби, a0';
$ec_lang['mpf_area_ratio']='Відносна площа, a/a0';
$ec_lang['mpf_wetted_perimeter']='Змочений периметр, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Гідравлічний радіус, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Ширина по поверхні, T';
$ec_lang['mpf_froude_number']='Число Фруда, F';
$ec_lang['mpf_shear_stress']='Середнє дотичне напруження (тягнуча сила), tau';
$ec_lang['mpf_full_flow']='Витрата при повному заповненні, Q0';
$ec_lang['mpf_full_flow_ratio']='Відношення до повної витрати, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Це витрата і глибина всередині <em>нескінченно довгої</em> труби.</dt><dd>Для забезпечення надходження потоку в трубу може знадобитися значно більша глибина підпору. Додайте не менше 1.5 швидкісного напору для визначення глибини підпору, або <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">дивіться мій 2-хвилинний посібник</a> зі стандартних розрахунків підпору водопропускних труб за HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Визначити y/d<sub>0</sub> при заданій Q';
$ec_lang['mpf_solve_desc']='Використовуючи D<sub>0</sub>, n та S<sub>0</sub> з форми калькулятора, знаходить найменше y/d<sub>0</sub> для заданої Q.';
$ec_lang['mpf_solve_button']='Розрахувати';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning — Втрати напору в трубі';
$ec_lang['mphl_main_title']='Безкоштовний онлайн-калькулятор втрат напору в трубі за Manning';
$ec_lang['mphl_main_desc']='Втрати напору за формулою Manning при заданій витраті повного перерізу';
$ec_lang['mphl_pipe_length']='Довжина труби, L';
$ec_lang['mphl_area']='Площа, A';
$ec_lang['mphl_total_junction_k']='Сумарний коефіцієнт місцевих втрат, k';
$ec_lang['mphl_friction_slope']='Похил тертя';
$ec_lang['mphl_friction_loss']='Втрати на тертя, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Місцеві втрати, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Сумарні втрати, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='Лінія питомої енергії нижче за течією';
$ec_lang['mphl_egl_2']='Лінія питомої енергії вище за течією';
$ec_lang['mphl_hgl_2']='П\'єзометрична лінія в трубі вище за течією ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>При відкритому вхідному (водопропускному) режимі необхідно перевірити умови управління на вході.</dt><dd>1. П\'єзометрична лінія вище за течією не може бути нижче відмітки рівномірної течії нормальної глибини вище за течією (і не може бути нижче труби!).</dd><dd>2. Підпір водопропускної труби краще характеризується лінією питомої енергії вище за течією, а не п\'єзометричною лінією.</dd><dd>3. Дивіться <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">мій 2-хвилинний посібник</a> зі стандартних розрахунків підпору водопропускних труб за HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning — Трапецієвидне русло';
$ec_lang['mtc_main_title']='Безкоштовний онлайн-калькулятор трапецієвидного русла за формулою Manning';
$ec_lang['mtc_main_desc']='Рівномірна течія в трапецієвидному руслі за формулою Manning при заданому похилі та глибині';
$ec_lang['mtc_bottom_width']='Ширина дна, b';
$ec_lang['mtc_side_slope_1']='Закладення укосу 1 (горизонт./верт.)';
$ec_lang['mtc_side_slope_2']='Закладення укосу 2 (горизонт./верт.)';
$ec_lang['mtc_channel_slope']='Похил русла, S';
$ec_lang['mtc_flow_depth']='Глибина течії, y';
$ec_lang['mtc_bend_angle']='Кут повороту <a target="_blank" href="riprap-bend-angle.png" title="Натисніть для перегляду зображення">?</a> (для підбору розміру каменю)';
$ec_lang['mtc_sgrock']='Питома вага каменю (2.65)';
$ec_lang['mtc_d50_in']='Розрахунковий розмір каменю, D50';
$ec_lang['mtc_n_strickler']='n для розрахункового розміру каменю за Strickler';
$ec_lang['mtc_n_blodgett']='n для розрахункового розміру каменю за Blodgett';
$ec_lang['mtc_n_bathurst']='n для розрахункового розміру каменю за Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett проти Bathurst';
$ec_lang['mtc_d50_bottom']='Необхідний розмір кутастого каменю для дна, D50 (Isbash & MC) <a href="javascript:alert(\'За Isbash (1936) та округом Маріколь, Арізона, США.\')">?</a>';
$ec_lang['mtc_d50_z1']='Необхідний розмір кутастого каменю для укосу 1, D50 (Isbash & MC) <a href="javascript:alert(\'За Isbash (1936) та округом Маріколь, Арізона, США.\')">?</a>';
$ec_lang['mtc_d50_z2']='Необхідний розмір кутастого каменю для укосу 2, D50 (Isbash & MC) <a href="javascript:alert(\'За Isbash (1936) та округом Маріколь, Арізона, США.\')">?</a>';
$ec_lang['mtc_d50_mra']='Необхідний розмір кутастого каменю, D50 (Maynord, Ruff та Abt 1989)';
$ec_lang['mtc_d50_searcy']='Необхідний розмір кутастого каменю, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Автоматична ітерація розміру каменю та шорсткості</dt><dd>Виберіть перемикач шорсткості (рекомендується BB) та перемикач розрахункового розміру каменю (рекомендується Isbash). Підберіть глибину та коефіцієнт запасу розміру каменю для досягнення бажаної витрати із зручним розміром каменю. Щоразу при зміні вхідного значення відбувається наступний цикл ітерації: 1. Шорсткість розраховується за розрахунковим розміром каменю. 2. Результат розрахунку шорсткості копіюється у вхідну шорсткість. 3. Розраховуються витрата русла та необхідний розмір каменю. 4. Розрахунковий розмір каменю коригується. 5. Повторювати до досягнення дуже малої похибки розміру каменю.</dd><dt>Базовий калькулятор (без ітерації)</dt><dd>Введіть бажане значення шорсткості. Поле розрахункового розміру каменю ігноруйте.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='Таблиця проектування Robinson Rock Chute';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Водозлив — Простий';
$ec_lang['ws_main_title']='Безкоштовний онлайн-калькулятор течії через простий широкогребінчастий водозлив';
$ec_lang['ws_main_desc']='Калькулятор течії через простий широкогребінчастий водозлив';
$ec_lang['ws_weirLength']='Довжина водозливу, l';
$ec_lang['ws_headWaterHeight']='Висота підпору, h';
$ec_lang['ws_weirCoefficient']='Коефіцієнт водозливу, Cw';
$ec_lang['ws_notes_heading']='Примітки';
$ec_lang['ws_notes_we_term']='Рівняння водозливу';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Водозлив — Нерегулярний';
$ec_lang['wi_main_title']='Безкоштовний онлайн-калькулятор течії через сегментований нерегулярний водозлив зі змінною глибиною';
$ec_lang['wi_main_desc']='Калькулятор течії через нерегулярний водозлив';
$ec_lang['wi_headWaterelevation']='Відмітка рівня підпору';
$ec_lang['wi_weirPoints']='Точки водозливу';
$ec_lang['wi_station']='Пікет<br />(відстань)';
$ec_lang['wi_elevation']='Відмітка';
$ec_lang['wi_pondingHeight']='Висота підтоплення';
$ec_lang['wi_incrementalFlow']='Часткова витрата';
$ec_lang['wi_cumulativeFlow']='Накопичена витрата';
$ec_lang['wi_save_and_calculate']='Зберегти та розрахувати';
$ec_lang['wi_notes_we_term']='Рівняння водозливу';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='Витікання через отвір';
$ec_lang['or_main_title']='Безкоштовний онлайн-калькулятор витікання через отвір';
$ec_lang['or_main_desc']='Витікання через отвір — вільне або підтоплене';
$ec_lang['or_shape']='Форма отвору';
$ec_lang['or_shape_circular']='Кругла';
$ec_lang['or_shape_rectangular']='Прямокутна';
$ec_lang['or_diameter']='Діаметр (круглий) або висота (прямокутний), D';
$ec_lang['or_width']='Ширина, W (тільки для прямокутного)';
$ec_lang['or_invert']='Відмітка лотка отвору (низ отвору)';
$ec_lang['or_hwe']='Відмітка рівня підпору';
$ec_lang['or_twe']='Відмітка рівня нижнього б\'єфу';
$ec_lang['or_cd']='Коефіцієнт витрати, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Відмітка центроїда';
$ec_lang['or_head']='Ефективний напір, h';
$ec_lang['or_area']='Площа отвору, A';
$ec_lang['or_flow']='Витрата, Q';
$ec_lang['or_velocity']='Швидкість в отворі, v';
$ec_lang['or_regime']='Перевірка режиму отвору';
$ec_lang['or_regime_valid']='Вільний злив — режим отвору діє ✓';
$ec_lang['or_regime_submerged']='Підтоплений отвір (TWE вище лотка) — діє ✓';
$ec_lang['or_regime_warn']='Попередження: підпір нижче гребеня — не режим отвору';
$ec_lang['or_regime_twe_above_hwe']='Попередження: нижній б\'єф (TWE) вище підпору (HWE) — перевірте вхідні дані';
$ec_lang['or_notes_1_term']='Рівняння отвору';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). При вільному зливі: h = HWE &minus; центроїд. При підтопленні (TWE вище лотка): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Режим отвору';
$ec_lang['or_notes_2_def']='Рівняння отвору застосовуються, коли поверхня підпору знаходиться вище гребеня (верху) отвору. Коли підпір нижче гребеня, використовуйте рівняння водозливу.';
$ec_lang['or_notes_3_term']='Коефіцієнт витрати';
$ec_lang['or_notes_3_def']='C<sub>d</sub> знаходиться в межах приблизно 0.60&ndash;0.65 для гостроокрайних отворів. Для заокруглених або втоплених входів використовуються інші значення. Дивіться <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> або гідравлічний довідковий посібник HEC-RAS.';
$ec_lang['or_notes_4_term']='Підтоплення';
$ec_lang['or_notes_4_def']='Коли TWE знаходиться вище лотка отвору, калькулятор автоматично застосовує рівняння підтопленого отвору з h = HWE &minus; TWE. Коли TWE на рівні або нижче лотка, приймається вільний злив і h = HWE &minus; центроїд.';
// Penstock Design
$ec_lang['ps_main_menu']='Проектування пеньківки';
$ec_lang['ps_main_title']='Безкоштовний онлайн-калькулятор проектування напірного трубопроводу';
$ec_lang['ps_main_desc']='Підбір напірного трубопроводу для мікро-ГЕС — втрати напору, потужність та швидкість';
$ec_lang['ps_flow']='Витрата, Q';
$ec_lang['ps_gross_head']='Повний напір, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Діаметр напірного трубопроводу, D';
$ec_lang['ps_length']='Довжина напірного трубопроводу, L';
$ec_lang['ps_roughness']='Шорсткість труби, e';
$ec_lang['ps_km']='Коефіцієнт місцевих (або &ldquo;малих&rdquo;) втрат, k<sub>m</sub>';
$ec_lang['ps_nu']='Кінематична в\'язкість, &nu;, у m<sup>2</sup>/s (1E-6 для води при температурі близько 20&deg;C)';
$ec_lang['ps_efficiency']='ККД установки, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Швидкість течії, v';
$ec_lang['ps_vel_check']='Перевірка швидкості';
$ec_lang['ps_f']='Коефіцієнт тертя, f';
$ec_lang['ps_hf']='Втрати напору на тертя, h<sub>f</sub>';
$ec_lang['ps_hm']='Місцеві втрати напору, h<sub>m</sub>';
$ec_lang['ps_hl']='Сумарні втрати в трубопроводі, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Перевірка втрат напору';
$ec_lang['ps_hnet']='Чистий напір, H<sub>net</sub>';
$ec_lang['ps_power']='Потужність, P';
$ec_lang['ps_annual_kwh']='Річна виробітка при 100% завантаженні';
$ec_lang['ps_vel_ok']='1–3 m/s — в межах норми ✓';
$ec_lang['ps_vel_low']='менше 1 m/s — збільшіть діаметр ⚠';
$ec_lang['ps_vel_high']='більше 3 m/s — зменшіть діаметр ⚠';
$ec_lang['ps_hl_ok']='в межах 10% норми ✓';
$ec_lang['ps_hl_warn']='перевищує норму 10% — розгляньте більшу трубу ⚠';
$ec_lang['ps_hl_bad']='перевищує 20% — підберіть іншу трубу';
$ec_lang['ps_notes_1_term']='Втрати напору';
$ec_lang['ps_notes_1_def']='Сумарні втрати в трубопроводі h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, де h<sub>f</sub> = f(L/D)(v&sup2;/2g) — втрати на тертя за Darcy-Weisbach, а h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g — втрати на вході, поворотах і засувках. Чистий напір H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Швидкість';
$ec_lang['ps_notes_2_def']='Цільовий діапазон 1&ndash;3 m/s. Нижче 1 m/s — труба завелика для даної витрати; вище 3 m/s — зростають втрати на тертя та ризик гідравлічного удару.';
$ec_lang['ps_notes_3_term']='Цільові втрати напору';
$ec_lang['ps_notes_3_def']='Втрати в напірному трубопроводі нижче 10% від повного напору, як правило, є економічно обґрунтованими. Оптимальний компроміс між вартістю труби та втраченою потужністю зазвичай становить 4&ndash;6% для об\'єктів з високою вартістю електроенергії.';
$ec_lang['ps_notes_4_term']='Місцеві втрати k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Ці втрати виникають у з\'єднаннях труб, на входах, поворотах та засувках &mdash; термін &ldquo;малі&rdquo; є умовним і оманливим; у короткому трубопроводі вони можуть дорівнювати або перевищувати втрати на тертя. Типові значення k: гострий вхідний отвір 0.5, кожен поворот на 45&deg; 0.2&ndash;0.3, шиберна засувка (повністю відкрита) 0.1, метеликова засувка 0.2. Сумуйте всі фітинги для отримання k<sub>m</sub>. За замовчуванням 1.5 передбачає один вхід та два поворота.';
$ec_lang['ps_notes_5_term']='Шорсткість труби e';
$ec_lang['ps_notes_5_def']='Типова абсолютна шорсткість: сталь (нова) 0.046&nbsp;mm, сталь (б/у) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, ПВХ/uPVC 0.0015&nbsp;mm, бетон 0.3&ndash;3&nbsp;mm. HDPE широко застосовується для малих напірних трубопроводів мікро-ГЕС.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Мікро-гідроелектростанція';
$ec_lang['mhp_main_title']='Безкоштовний онлайн-калькулятор потужності мікро-ГЕС';
$ec_lang['mhp_main_desc']='Калькулятор потужності русловій мікро-ГЕС';
$ec_lang['mhp_flow']='Витрата, Q';
$ec_lang['mhp_gross_head']='Повний напір (перепад висот), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Втрати напору в трубопроводі, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='ККД установки, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Чистий напір, H<sub>net</sub>';
$ec_lang['mhp_power']='Потужність, P';
$ec_lang['mhp_annual_kwh']='Річна виробітка при 100% завантаженні';
$ec_lang['mhp_notes_1_term']='Рівняння потужності';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, де &rho; = 1000 kg/m&sup3; (прісна вода) і g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Чистий напір';
$ec_lang['mhp_notes_2_def']='Чистий напір = повний напір &minus; втрати в напірному трубопроводі. Поширена перша оцінка: h<sub>L</sub> &asymp; 5% від H<sub>gross</sub>. Використовуйте <a href="Darcy-Weisbach.php">калькулятор Darcy-Weisbach</a> для точнішого розрахунку втрат у трубопроводі.';
$ec_lang['mhp_notes_3_term']='ККД';
$ec_lang['mhp_notes_3_def']='Типовий ККД установки &eta; становить від 0.70 до 0.85 для турбін Пелтона та cross-flow, поширених у мікро-ГЕС. Використовуйте 0.75 як консервативну першу оцінку.';
$ec_lang['mhp_notes_4_term']='Річна виробітка';
$ec_lang['mhp_notes_4_def']='Річна виробітка передбачає безперервну роботу на повній витраті (8760 годин/рік). Фактична виробітка буде нижчою через сезонні коливання витрат, простої на технічне обслуговування та коефіцієнт використання.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Час спорожнення через отвір';
$ec_lang['odt_main_title']='Безкоштовний онлайн-калькулятор часу спорожнення через отвір — ставок, басейн або резервуар';
$ec_lang['odt_main_desc']='Час спорожнення ставка або басейну через отвір &mdash; метод конічного об\'єму';
$ec_lang['odt_h1_elev']='Початкова відмітка поверхні води';
$ec_lang['odt_a1']='Початкова площа ставка або басейну, A1';
$ec_lang['odt_h2_elev']='Кінцева відмітка поверхні води';
$ec_lang['odt_h_orifice']='Відмітка центроїда отвору';
$ec_lang['odt_a0']='Площа ставка або басейну на відмітці отвору, A0';
$ec_lang['odt_a_ending']='Кінцева площа ставка, A2 (інтерпольована)';
$ec_lang['odt_h2_check']='Перевірка кінцевої відмітки';
$ec_lang['odt_h2_ok']='Кінцева відмітка вище верху отвору ✓';
$ec_lang['odt_h2_warn']='Попередження: кінцева відмітка на рівні або нижче верху отвору (центроїд + D/2)';
$ec_lang['odt_d']='Діаметр отвору (круглий) або висота (прямокутний), D';
$ec_lang['odt_w']='Ширина отвору, W (тільки для прямокутного)';
$ec_lang['odt_t_sec']='Час спорожнення (секунди)';
$ec_lang['odt_t_min']='Час спорожнення (хвилини)';
$ec_lang['odt_t_hr']='Час спорожнення (години)';
$ec_lang['odt_t_day']='Час спорожнення (дні)';
$ec_lang['odt_notes_1_term']='Формула';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) дає час спорожнення від напору H до отвору. Час спорожнення = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), де H<sub>1</sub> = початкова відмітка &minus; відмітка отвору, H<sub>2</sub> = кінцева відмітка &minus; відмітка отвору.';
$ec_lang['odt_notes_2_term']='Метод';
$ec_lang['odt_notes_2_def']='Метод конічного об\'єму моделює ставок або басейн як конічний перетин між початковою площею A<sub>1</sub> на початковій поверхні води та площею A<sub>0</sub> на відмітці центроїда отвору. A<sub>2</sub>, площа ставка на кінцевій відмітці, інтерполюється між A<sub>1</sub> та A<sub>0</sub> за моделлю конічного перетину. Час спорожнення від початкової до кінцевої відмітки дорівнює повному часу спорожнення від H<sub>1</sub> до отвору мінус час, що залишається від H<sub>2</sub> до отвору.';
$ec_lang['odt_h1']='Початковий напір, H<sub>1</sub> (WSE &minus; центроїд)';
$ec_lang['odt_q_max']='Максимальна (початкова) витрата, Q<sub>max</sub>';
$ec_lang['odt_vol']='Зливний об\'єм';
$ec_lang['odt_sketch_start']='Початок';
$ec_lang['odt_sketch_end']='Кінець';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Ширина від берега до берега';
$ec_lang['essc_mcr']='Мінімальний радіус кривизни';
$ec_lang['essc_q']='Витрата, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Вимірювання витрати зрошення';
$ec_lang['irr_main_title']='Безкоштовні онлайн-калькулятори вимірювання витрати зрошення';
$ec_lang['irr_main_desc']='Вимірювання витрати зрошення — водозливи та отвори';
$ec_lang['contact_title']='Зв\'язок з HawsEDC';
$ec_lang['contactSendMessage']='Надіслати повідомлення Тому Хоусу';
$ec_lang['contactYourName']='Ваше ім\'я:';
$ec_lang['contactYourEmail']='Ваша адреса електронної пошти:';
$ec_lang['contactSubject']='Тема:';
$ec_lang['contact_message']='Повідомлення:';
$ec_lang['contactSpamPrefix']='П\'ять плюс один дорівнює';
$ec_lang['contactSpamPostfix']='(Будь ласка, напишіть словами. 1=один 2=два 3=три 4=чотири 5=п\'ять 6=шість 7=сім +=плюс 5+1=6)';
$ec_lang['contactSubmitButton']='Надіслати повідомлення';
