<?php

// Bahasa Indonesia — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="fraksi";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']="% naik/datar";
$ec_lang['u_grade']="naik/datar";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="L/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="ML/h";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="dtk";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Kalkulator HawsEDC';
$ec_lang['menu_main_list']='Daftar Kalkulator';
$ec_lang['menu_main_hydraulics']='Hidraulika';
$ec_lang['menu_main_language']='Bahasa';
$ec_lang['menu_more']='Lainnya';
$ec_lang['template_welcome']='>> Buang rasa takutmu di pintu; di sini cinta adalah bahasa kami. Kamu tidak merusak segalanya. Nikmati juga <a target="_blank" href="https://hawsedc.com/download.php">alat AutoCAD HawsEDC gratis</a>. <<';
$ec_lang['template_translation_help']='Apakah Anda memiliki visi luar biasa untuk kalkulator yang ingin ditambahkan di sini?  Bisakah Anda membantu meningkatkan terjemahan, memprogram, atau meng-host kalkulator ini?  ';
$ec_lang['template_feedback']='Silakan berikan masukan atau pujian yang berharga. Apakah kalkulator gratis ini melebihi harapan Anda di segala hal?';
$ec_lang['template_printable_title']='Judul Cetak';
$ec_lang['template_printable_subtitle']='Subjudul Cetak';
$ec_lang['index_title']='Kalkulator Teknik Gratis Daring';
$ec_lang['calc_set_units']='Atur satuan:';
$ec_lang['calc_defaults']='Nilai Default';
$ec_lang['calc_defaults_confirm']='Setel ulang kalkulator ke nilai default asli?';
$ec_lang['points_data_help']='(atau Salin/Tempel menggunakan area data)';
$ec_lang['points_data_title']='Data titik<br />(dipisah koma atau tabulasi)';
$ec_lang['points_data_copy']='Salin';
$ec_lang['points_data_paste']='Tempel';
$ec_lang['calc_inputs']='Masukan';
$ec_lang['calc_results']='Hasil';
$ec_lang['view_hide_line']='[Sembunyikan baris ini]';
$ec_lang['view_printable']='Versi cetak (muat ulang untuk memulihkan)';
$ec_lang['ec_name_label']='Simpan perhitungan ini:';
$ec_lang['ec_name_placeholder']='Nama';
$ec_lang['ec_name_hint']='Menyimpan nilai masukan ini ke URL untuk penanda halaman, pengambilan riwayat, dan berbagi';
$ec_lang['calc_copy_link']='Salin tautan';
$ec_lang['calc_copy_link_done']='Tersalin!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Kehilangan Tinggi Tekan Pipa Darcy-Weisbach';
$ec_lang['dw_main_title']='Kalkulator Kehilangan Tinggi Tekan Pipa Darcy-Weisbach Gratis Daring';
$ec_lang['dw_main_desc']='Kehilangan Tinggi Tekan Pipa Darcy-Weisbach pada Diameter, Kekasaran, dan Debit Tertentu';
$ec_lang['dw_roughness']='Kekasaran, e';
$ec_lang['dw_roughness_tip']='<span title="Tinggi kekasaran Darcy-Weisbach" class="ec-tip">?</span>';
$ec_lang['dw_kinematic_viscosity']='Viskositas kinematik, &nu; <span title="1×10⁻⁶ m²/s untuk air bersih pada 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Bilangan Reynolds, Re';
$ec_lang['dw_flow_regime']='Rezim aliran';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='transisi';
$ec_lang['dw_regime_turbulent']='turbulen';
$ec_lang['dw_friction_factor_method']='Metode faktor gesekan';
$ec_lang['dw_friction_factor']='Faktor gesekan, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Kehilangan Tinggi Tekan Pipa Hazen-Williams';
$ec_lang['hw_main_title']='Kalkulator Kehilangan Tinggi Tekan Pipa Hazen-Williams Gratis Daring';
$ec_lang['hw_main_desc']='Kehilangan Tinggi Tekan Pipa Hazen-Williams pada Diameter, Kekasaran, dan Debit Tertentu';
$ec_lang['hw_hgl_1']='HGL Hilir';
$ec_lang['hw_hgl_2']='HGL Hulu';
$ec_lang['hw_roughness']='Koefisien Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Saluran Penampang Tidak Beraturan Manning';
$ec_lang['mi_main_title']='Kalkulator Saluran Penampang Tidak Beraturan Manning Gratis Daring';
$ec_lang['mi_main_desc']='Kalkulator Aliran Seragam Saluran Penampang Tidak Beraturan dengan Rumus Manning';
$ec_lang['mi_waterSurfaceElevation']='Elevasi permukaan air';
$ec_lang['mi_q_617']='Q <span title="Debit komposit, Q, menggunakan n komposit untuk setiap zona menurut Chow 6-17, kecepatan sama" class="ec-tip">?</span>';
$ec_lang['mi_xSecPoints']='Titik penampang melintang';
$ec_lang['mi_groupPoint']='Titik';
$ec_lang['mi_groupSegment']='Segmen';
$ec_lang['mi_groupRegion']='Zona';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Elev';
$ec_lang['mi_d50in']='Ukuran<br />median<br />batu<br />pelapis';
$ec_lang['mi_n']='n<br />untuk<br />seg-<br />men';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />batas<br />zona<br />(Tebing)';
$ec_lang['mi_tau']='Tegangan<br />geser<br />dasar<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />komposit';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Catatan';
$ec_lang['mi_notes_1_term']='n komposit';
$ec_lang['mi_notes_1_def']='Kalkulator ini mengikuti Manual Referensi HEC-RAS dalam menghitung n komposit zona menggunakan Chow 1959, halaman 136, persamaan 6-17 (bukan 6-18).';
$ec_lang['mi_notes_2_term']='Pelapis batu';
$ec_lang['mi_notes_2_def']='Gunakan Kalkulator Saluran Trapesium Manning untuk merancang pelapis batu. Kalkulator ini lebih sesuai untuk penampang alami.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Aliran Pipa Manning';
$ec_lang['mpf_main_title']='Kalkulator Aliran Pipa Manning Gratis Daring';
$ec_lang['mpf_main_desc']='Rumus Manning untuk Aliran Pipa Seragam pada Kemiringan dan Kedalaman Tertentu';
$ec_lang['mpf_spreadheet_notice']='Coba versi spreadsheet dari kalkulator ini';
$ec_lang['mpf_pipe_diameter']='Diameter pipa, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Koefisien kekasaran Manning, n';
$ec_lang['mpf_friction_slope']='Kemiringan gesekan (terkadang <a target="_blank" href="../frictionslope.php">?</a> sama dengan kemiringan pipa), S<sub>f</sub>';
$ec_lang['mpf_depth_ratio']='Kedalaman aliran relatif, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Lihat catatan)';
$ec_lang['mpf_flow']='Debit, Q';
$ec_lang['mpf_velocity']='Kecepatan, v';
$ec_lang['mpf_velocity_head']='Tinggi kecepatan, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Luas aliran, A';
$ec_lang['mpf_pipe_area']='Luas pipa, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Luas relatif, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Keliling basah, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Jari-jari hidrolik, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Lebar permukaan air, T';
$ec_lang['mpf_froude_number']='Bilangan Froude, Fr';
$ec_lang['mpf_shear_stress']='Tegangan geser rata-rata (gaya traksi), &tau;';
$ec_lang['mpf_full_flow']='Aliran penuh, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Rasio terhadap aliran penuh, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Ini adalah debit dan kedalaman di dalam pipa yang panjangnya <em>tak terhingga</em>.</dt><dd>Memasukkan aliran ke dalam pipa mungkin memerlukan kedalaman air hulu yang jauh lebih tinggi. Tambahkan setidaknya 1,5 kali tinggi kecepatan untuk memperkirakan kedalaman air hulu, atau <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">lihat tutorial 2 menit saya</a> untuk perhitungan standar air hulu gorong-gorong menggunakan HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Cari y/d<sub>0</sub> berdasarkan Q';
$ec_lang['mpf_solve_desc']='Menggunakan d<sub>0</sub>, n, dan S<sub>f</sub> dari formulir kalkulator, mencari nilai y/d<sub>0</sub> terendah untuk Q tertentu.';
$ec_lang['mpf_solve_button']='Hitung';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Kehilangan Tinggi Tekan Pipa Manning';
$ec_lang['mphl_main_title']='Kalkulator Kehilangan Tinggi Tekan Pipa Manning Gratis Daring';
$ec_lang['mphl_main_desc']='Rumus Manning untuk Kehilangan Tinggi Tekan pada Aliran Penuh Tertentu';
$ec_lang['mphl_pipe_length']='Panjang, L';
$ec_lang['mphl_area']='Luas, A';
$ec_lang['mphl_total_junction_k']='Koefisien kehilangan kecil (lokal), k<sub>m</sub>';
$ec_lang['mphl_friction_slope']='Kemiringan gesekan';
$ec_lang['mphl_friction_loss']='Kehilangan gesekan, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Kehilangan kecil (lokal), h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Kehilangan total, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='EGL Hilir';
$ec_lang['mphl_egl_2']='EGL Hulu';
$ec_lang['mphl_hgl_2']='HGL Hulu di pipa ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Untuk kondisi saluran masuk terbuka (gorong-gorong), perlu diperiksa kondisi kendali saluran masuk.</dt><dd>1. HGL hulu harus berada di atas elevasi aliran kedalaman normal hulu (dan lebih tinggi dari pipa!).</dd><dd>2. Air hulu gorong-gorong lebih baik diwakili oleh EGL hulu daripada HGL hulu.</dd><dd>3. Lihat <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">tutorial 2 menit saya</a> untuk perhitungan standar sederhana air hulu gorong-gorong menggunakan HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Saluran Trapesium Manning';
$ec_lang['mtc_main_title']='Kalkulator Rumus Manning Saluran Trapesium Gratis Daring';
$ec_lang['mtc_main_desc']='Rumus Manning untuk Aliran Seragam Saluran Trapesium pada Kemiringan dan Kedalaman Tertentu';
$ec_lang['mtc_bottom_width']='Lebar dasar, b';
$ec_lang['mtc_side_slope_1']='Kemiringan tebing 1, z<sub>1</sub> (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Kemiringan tebing 2, z<sub>2</sub> (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Kemiringan saluran, S';
$ec_lang['mtc_flow_depth']='Kedalaman aliran, y';
$ec_lang['mtc_bend_angle']='Sudut belokan, β <a target="_blank" href="riprap-bend-angle.png" title="Klik untuk gambar">?</a> (untuk ukuran riprap)';
$ec_lang['mtc_sgrock']='Berat jenis batu, sg <span title="Umumnya &asymp; 2,65 untuk batu pecah" class="ec-tip">?</span>';
$ec_lang['mtc_d50_in']='Ukuran batu rencana, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n untuk ukuran batu rencana menurut Strickler';
$ec_lang['mtc_n_blodgett']='n untuk ukuran batu rencana menurut Blodgett';
$ec_lang['mtc_n_bathurst']='n untuk ukuran batu rencana menurut Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Ukuran batu sudut yang dibutuhkan di dasar, D<sub>50</sub> (Isbash & MC) <span title="Menurut Isbash (1936) dan Maricopa County, Arizona, AS." class="ec-tip">?</span>';
$ec_lang['mtc_d50_z1']='Ukuran batu sudut yang dibutuhkan di tebing 1, D<sub>50</sub> (Isbash & MC) <span title="Menurut Isbash (1936) dan Maricopa County, Arizona, AS." class="ec-tip">?</span>';
$ec_lang['mtc_d50_z2']='Ukuran batu sudut yang dibutuhkan di tebing 2, D<sub>50</sub> (Isbash & MC) <span title="Menurut Isbash (1936) dan Maricopa County, Arizona, AS." class="ec-tip">?</span>';
$ec_lang['mtc_d50_mra']='Ukuran batu sudut yang dibutuhkan, D<sub>50</sub> (Maynord, Ruff, dan Abt 1989)';
$ec_lang['mtc_d50_searcy']='Ukuran batu sudut yang dibutuhkan, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_check']='Pemeriksaan kecepatan';
$ec_lang['mtc_vel_ok']='Kecepatan wajar untuk asumsi aliran seragam.';
$ec_lang['mtc_vel_high']='Kecepatan tinggi — periksa kehilangan transisi, energi yang tersedia, dan risiko pukulan air.';
$ec_lang['mtc_vel_low']='Kecepatan rendah — risiko sedimentasi.';
$ec_lang['mtc_vel_ok_short']='OK';
$ec_lang['mtc_vel_high_short']='Tinggi';
$ec_lang['mtc_vel_low_short']='Rendah';
$ec_lang['mtc_note_1']='<dl><dt>Iterasi otomatis ukuran batu dan kekasaran</dt><dd>Pilih opsi kekasaran (Blodgett–Bathurst direkomendasikan) dan opsi ukuran batu rencana (Isbash direkomendasikan). Sesuaikan kedalaman dan faktor keamanan ukuran batu untuk mendapatkan debit yang diinginkan dengan ukuran batu yang seragam. Setiap kali Anda mengubah nilai masukan, siklus iterasi berikut terjadi: 1. Kekasaran dihitung dari ukuran batu rencana. 2. Perhitungan kekasaran yang diminta disalin ke kekasaran masukan. 3. Debit saluran dan ukuran batu yang diperlukan dihitung. 4. Ukuran batu rencana disesuaikan. 5. Ulangi hingga galat pada ukuran batu rencana sangat kecil.</dd><dt>Kalkulator dasar (tanpa iterasi)</dt><dd>Masukkan nilai kekasaran yang Anda inginkan. Abaikan area masukan ukuran batu rencana.</dd></dl>';
$ec_lang['mtc_note_2_term']='Pemeriksaan kecepatan';
$ec_lang['mtc_note_2_def']='Kecepatan tinggi mengimplikasikan energi spesifik tinggi dari beda tinggi yang tersedia. Energi tersebut dapat hilang dengan cepat pada ekspansi, belokan, atau hambatan. Verifikasi bahwa ini wajar untuk kondisi lapangan.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Aliran Bendung Ukur Sederhana';
$ec_lang['ws_main_title']='Kalkulator Aliran Bendung Ukur Bermercu Lebar Sederhana Gratis Daring';
$ec_lang['ws_main_desc']='Kalkulator Aliran Bendung Ukur Bermercu Lebar Sederhana';
$ec_lang['ws_weirLength']='Panjang bendung ukur, L';
$ec_lang['ws_headWaterHeight']='Tinggi tekan, h';
$ec_lang['ws_weirCoefficient']='Koefisien bendung ukur, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Catatan';
$ec_lang['ws_notes_we_term']='Persamaan Bendung Ukur';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Aliran Bendung Ukur Tidak Beraturan';
$ec_lang['wi_main_title']='Kalkulator Aliran Bendung Ukur Tidak Beraturan, Bersegmen, dan Kedalaman Bervariasi, Gratis Daring';
$ec_lang['wi_main_desc']='Kalkulator Aliran Bendung Ukur Tidak Beraturan';
$ec_lang['wi_headWaterelevation']='Elevasi air hulu';
$ec_lang['wi_weirPoints']='Titik bendung ukur';
$ec_lang['wi_station']='Stasiun<br />(jarak)';
$ec_lang['wi_elevation']='Elevasi';
$ec_lang['wi_pondingHeight']='Tinggi Genangan';
$ec_lang['wi_incrementalFlow']='Debit Tambahan';
$ec_lang['wi_cumulativeFlow']='Debit Kumulatif';
$ec_lang['wi_save_and_calculate']='Simpan dan Hitung';
$ec_lang['wi_notes_we_term']='Persamaan Pelimpah';
$ec_lang['wi_notes_we_def']='q = jika (panjang = 0) maka 0, selainnya jika (kemiringan=0) maka cw*panjang*d<sub>0</sub><sup>1.5</sup>, selainnya cw/(2.5*kemiringan) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) dengan d<sub>1</sub> dan d<sub>0</sub> selalu positif atau nol';
// Orifice Flow
$ec_lang['or_main_menu']='Debit Lubang Aliran';
$ec_lang['or_main_title']='Kalkulator Debit Lubang Aliran Gratis Daring';
$ec_lang['or_main_desc']='Debit Lubang Aliran — Bebas atau Tenggelam';
$ec_lang['or_shape']='Bentuk bukaan';
$ec_lang['or_shape_circular']='Lingkaran';
$ec_lang['or_shape_rectangular']='Persegi panjang';
$ec_lang['or_diameter']='Diameter atau tinggi, D <span title="Diameter untuk bentuk lingkaran; tinggi untuk bentuk persegi panjang" class="ec-tip">?</span>';
$ec_lang['or_width']='Lebar, W <span title="Hanya untuk bukaan persegi panjang" class="ec-tip">?</span>';
$ec_lang['or_invert']='Elevasi dasar <span title="Bagian bawah bukaan" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Elevasi muka air hulu';
$ec_lang['or_twe']='Elevasi muka air hilir';
$ec_lang['or_cd']='Koefisien debit, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Elevasi sentroid';
$ec_lang['or_head']='Tinggi tekan efektif, h';
$ec_lang['or_area']='Luas bukaan, A';
$ec_lang['or_flow']='Debit, Q';
$ec_lang['or_velocity']='Kecepatan, v';
$ec_lang['or_regime']='Pemeriksaan rezim lubang aliran';
$ec_lang['or_regime_valid']='Aliran bebas';
$ec_lang['or_regime_submerged']='Lubang aliran tenggelam';
$ec_lang['or_regime_submerged_tip']='TWE di atas sentroid — masih dalam rezim lubang aliran';
$ec_lang['or_regime_warn']='Di luar rezim lubang aliran';
$ec_lang['or_regime_warn_tip']='Air hulu di bawah mahkota';
$ec_lang['or_regime_twe_above_hwe']='Periksa masukan';
$ec_lang['or_regime_twe_above_hwe_tip']='Air hilir (TWE) di atas air hulu (HWE)';
$ec_lang['or_notes_1_term']='Persamaan Lubang Aliran';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Untuk aliran bebas: h = HWE − sentroid. Untuk aliran tenggelam (TWE di atas dasar): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Rezim Lubang Aliran';
$ec_lang['or_notes_2_def']='Persamaan debit lubang aliran berlaku ketika permukaan air hulu berada di atas mahkota (bagian atas) bukaan. Ketika air hulu berada di bawah mahkota, gunakan persamaan bendung ukur.';
$ec_lang['or_notes_3_term']='Koefisien Debit';
$ec_lang['or_notes_3_def']='C<sub>d</sub> berkisar sekitar 0,60–0,65 untuk lubang aliran bersudut tajam. Saluran masuk berbentuk bulat atau re-entrant menggunakan nilai yang berbeda. Lihat <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> atau HEC-RAS Hydraulic Reference Manual untuk panduan.';
$ec_lang['or_notes_4_term']='Ketenggelaman';
$ec_lang['or_notes_4_def']='Ketika TWE berada di atas dasar bukaan, kalkulator ini secara otomatis menerapkan persamaan lubang aliran tenggelam menggunakan h = HWE − TWE. Ketika TWE sama dengan atau di bawah dasar, aliran bebas diasumsikan dan h = HWE − sentroid.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Tenaga Mikro-Hidro';
$ec_lang['mhp_main_title']='Kalkulator Tenaga Mikro-Hidro Online Gratis';
$ec_lang['mhp_main_desc']='Kalkulator Daya Keluaran Mikro-Hidro Aliran Langsung (Tanpa Bendungan)';
$ec_lang['mhp_flow']='Debit, Q';
$ec_lang['mhp_gross_head']='Tinggi jatuh bruto, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diameter pipa tekanan, D';
$ec_lang['mhp_length']='Panjang, L <span title="Panjang pipa atau saluran pembawa air dari bangunan pengambilan air (headworks) ke turbin" class="ec-tip">?</span>';
$ec_lang['mhp_roughness']='Kekasaran pipa, e';
$ec_lang['mhp_km']='Koefisien kehilangan minor, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Viskositas kinematik, ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='Efisiensi instalasi, η (0–1)';
$ec_lang['mhp_velocity']='Kecepatan aliran, v';
$ec_lang['mhp_vel_check']='Pemeriksaan kecepatan';
$ec_lang['mhp_f']='Faktor gesekan, f';
$ec_lang['mhp_hf']='Kehilangan tinggi akibat gesekan, h<sub>f</sub>';
$ec_lang['mhp_hm']='Kehilangan tinggi minor, h<sub>m</sub>';
$ec_lang['mhp_hl']='Total kehilangan tinggi penstock, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Pemeriksaan kehilangan tinggi tekan';
$ec_lang['mhp_hnet']='Tinggi jatuh neto, H<sub>net</sub>';
$ec_lang['mhp_power']='Daya keluaran, P';
$ec_lang['mhp_annual_kwh']='Energi tahunan pada kapasitas 100%';
$ec_lang['mhp_vel_low']='Kecepatan rendah — risiko sedimentasi dan masuknya udara.';
$ec_lang['mhp_vel_high']='Kecepatan tinggi — periksa kehilangan transisi, energi yang tersedia, dan risiko pukulan air.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Tinggi';
$ec_lang['mhp_vel_low_short']='Rendah';
$ec_lang['mhp_hl_ok']='dalam target 10%';
$ec_lang['mhp_hl_warn']='melebihi target 10%';
$ec_lang['mhp_hl_warn_tip']='Pertimbangkan pipa yang lebih besar';
$ec_lang['mhp_hl_bad']='melebihi 20%';
$ec_lang['mhp_hl_bad_tip']='Ubah ukuran pipa';
$ec_lang['mhp_notes_1_term']='Kehilangan Tinggi Tekan';
$ec_lang['mhp_notes_1_def']='Total kehilangan tinggi tekan pada pipa tekanan, h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, di mana h<sub>f</sub> = f(L/D)(v²/2g) adalah kehilangan gesekan Darcy-Weisbach dan h<sub>m</sub> = k<sub>m</sub>·v²/2g mencakup inlet, belokan, dan katup. Tinggi jatuh neto H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Kecepatan';
$ec_lang['mhp_notes_2_def']='Pastikan kecepatan wajar untuk tinggi jatuh yang tersedia dan biaya pipa. Kecepatan yang sangat rendah dapat mengindikasikan pipa terlalu besar; kecepatan yang sangat tinggi dapat meningkatkan kehilangan gesekan dan risiko pukulan air.';
$ec_lang['mhp_notes_3_term']='Target Kehilangan Tinggi Tekan';
$ec_lang['mhp_notes_3_def']='Kehilangan pada pipa tekanan di bawah 10% dari tinggi jatuh bruto umumnya ekonomis. Titik optimal antara biaya pipa dan daya yang hilang sering berada di sekitar 4–6% di lokasi yang nilai listriknya tinggi.';
$ec_lang['mhp_notes_4_term']='Kehilangan Lokal, k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Kehilangan ini terjadi pada sambungan pipa, inlet, belokan, dan katup — istilah "minor" (kecil) bersifat konvensional namun menyesatkan; pada pipa tekanan yang pendek, kehilangan ini dapat menyamai atau bahkan melebihi kehilangan gesekan. Nilai k tipikal: inlet tajam 0.5, setiap belokan 45° antara 0.2–0.3, katup gerbang (terbuka penuh) 0.1, katup kupu-kupu 0.2. Jumlahkan semua fitting untuk mendapatkan total k<sub>m</sub>. Nilai default 1.5 mengasumsikan satu inlet dan dua belokan.';
$ec_lang['mhp_notes_5_term']='Kekasaran Pipa e';
$ec_lang['mhp_notes_5_def']='Kekasaran absolut tipikal: baja (baru) 0.046 mm, baja (bekas) 0.15 mm, HDPE 0.003 mm, PVC/uPVC 0.0015 mm, beton 0.3–3 mm. HDPE umum digunakan untuk pipa tekanan mikro-hidro kecil.';
$ec_lang['mhp_notes_6_term']='Efisiensi';
$ec_lang['mhp_notes_6_def']='Efisiensi instalasi tipikal &eta; berkisar antara 0,70 hingga 0,85 untuk turbin Pelton dan turbin aliran silang yang umum digunakan dalam mikro-hidro. Gunakan 0,75 sebagai estimasi awal yang konservatif.';
$ec_lang['mhp_notes_7_term']='Energi Tahunan';
$ec_lang['mhp_notes_7_def']='Energi tahunan mengasumsikan operasi aliran penuh berkelanjutan (8.760 jam/tahun). Produksi aktual akan lebih rendah akibat variasi debit musiman, waktu henti pemeliharaan, dan faktor beban.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Waktu Pengosongan Lubang Aliran';
$ec_lang['odt_main_title']='Kalkulator Waktu Pengosongan Lubang Aliran Gratis Daring — Kolam, Cekungan, atau Tangki';
$ec_lang['odt_main_desc']='Waktu Pengosongan Kolam atau Cekungan melalui Lubang Aliran — Metode Volume Konik';
$ec_lang['odt_h1_elev']='Elevasi permukaan air awal';
$ec_lang['odt_a1']='Luas awal, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Elevasi permukaan air akhir';
$ec_lang['odt_h_orifice']='Elevasi sentroid orifis';
$ec_lang['odt_a0']='Luas pada elevasi lubang aliran, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Luas akhir, A<sub>2</sub> <span title="Diinterpolasi dari model konik pada elevasi akhir" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='Pemeriksaan elevasi akhir';
$ec_lang['odt_h2_ok']='Elevasi akhir di atas mahkota lubang aliran';
$ec_lang['odt_h2_warn']='Elevasi akhir sama dengan atau di bawah mahkota lubang aliran';
$ec_lang['odt_h2_warn_tip']='Mahkota lubang aliran = sentroid + D/2';
$ec_lang['odt_d']='D lubang aliran <span title="Diameter (bentuk lingkaran) atau tinggi (bentuk persegi panjang)" class="ec-tip">?</span>';
$ec_lang['odt_w']='Lebar lubang aliran, W <span title="Hanya bentuk persegi panjang" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='Waktu pengosongan (detik)';
$ec_lang['odt_t_min']='Waktu pengosongan (menit)';
$ec_lang['odt_t_hr']='Waktu pengosongan (jam)';
$ec_lang['odt_t_day']='Waktu pengosongan (hari)';
$ec_lang['odt_notes_1_term']='Rumus';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) memberikan waktu pengosongan dari tinggi tekan H ke lubang aliran. Waktu pengosongan = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), dengan H<sub>1</sub> = elevasi awal − elevasi lubang aliran, H<sub>2</sub> = elevasi akhir − elevasi lubang aliran.';
$ec_lang['odt_notes_2_term']='Metode';
$ec_lang['odt_notes_2_def']='Metode volume konik memodelkan kolam atau cekungan sebagai penampang konik antara luas awal A<sub>1</sub> pada permukaan air awal dan luas A<sub>0</sub> pada elevasi sentroid lubang aliran. A<sub>2</sub>, luas kolam pada elevasi akhir, diinterpolasi dari A<sub>1</sub> dan A<sub>0</sub> menggunakan model penampang konik. Waktu pengosongan dari elevasi awal ke elevasi akhir sama dengan waktu pengosongan total dari H<sub>1</sub> ke lubang aliran dikurangi sisa waktu pengosongan dari H<sub>2</sub> ke lubang aliran.';
$ec_lang['odt_h1']='Tinggi tekan awal, H<sub>1</sub> <span title="Elevasi permukaan air awal dikurangi elevasi sentroid lubang aliran" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='Debit maksimum, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume yang dikosongkan';
$ec_lang['odt_sketch_start']='Mulai';
$ec_lang['odt_sketch_end']='Akhir';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Irigasi';
$ec_lang['irr_main_title']='Kalkulator Pengukuran Debit Irigasi Gratis Daring';
$ec_lang['irr_main_desc']='Pengukuran Debit Irigasi — Bendung Ukur dan Lubang Aliran';
$ec_lang['irr_intro_html']='<p>Bendung ukur dan lubang aliran adalah alat lapangan standar untuk mengukur debit air dalam sistem irigasi. Pilih kalkulator yang sesuai dengan struktur Anda:</p>';
$ec_lang['irr_card_weir_uniform_head']='Bendung Ukur — Mercu Lebar (Lebar Seragam)';
$ec_lang['irr_card_weir_uniform_desc']='Ukur debit di atas mercu bendung pengalih, bangunan pengatur, atau papan bendung. Masukkan panjang bendung dan kedalaman air hulu di atas mercu.';
$ec_lang['irr_card_weir_irregular_head']='Bendung Ukur — Profil Tidak Beraturan';
$ec_lang['irr_card_weir_irregular_desc']='Gunakan saat mercu bendung bervariasi elevasi atau profilnya — pelimpah alami, bangunan terjun dengan lebar bervariasi, atau bangunan kendali multi-bagian.';
$ec_lang['irr_card_orifice_head']='Lubang Aliran — Pintu Air atau Sambungan Pipa';
$ec_lang['irr_card_orifice_desc']='Ukur debit melalui pintu sorong, sambungan pipa, atau bukaan gorong-gorong. Menangani kondisi aliran bebas maupun tenggelam (dipengaruhi air hilir) secara otomatis.';
$ec_lang['irr_card_canal_head']='Desain &amp; Analisis Saluran';
$ec_lang['irr_card_canal_desc']='Desain atau periksa saluran irigasi menggunakan rumus Manning. Gunakan kalkulator Trapesium untuk saluran baru; kalkulator Tidak Beraturan untuk penampang alami atau buatan yang sudah ada.';
$ec_lang['irr_card_seepage_head']='Rembesan Saluran &amp; Efisiensi Saluran';
$ec_lang['irr_card_seepage_desc']='Perkirakan kehilangan rembesan dari segmen saluran menggunakan pengukuran debit masuk dan keluar. Hitung efisiensi saluran dan kehilangan air tahunan untuk membantu memprioritaskan investasi pelapisan saluran.';
$ec_lang['irr_card_pressure_head']='Tekanan Irigasi & Keseragaman';
$ec_lang['irr_card_pressure_desc']='Modelkan profil tekanan dan debit di sepanjang cabang saluran utama-lateral-emiter untuk memperkirakan keseragaman distribusi dari tekanan jalur uji yang sebenarnya, bukan hanya laju debit emiter dari katalog.';
$ec_lang['irr_quickref_html']='<h3>Referensi Cepat</h3><dl><dt>Bendung pengalih atau bangunan pengatur</dt><dd>Ukur kedalaman air hulu di atas mercu bendung. Gunakan <a href="Weir-Flow-Simple.php">Aliran Bendung Ukur Sederhana</a> untuk mercu seragam, atau <a href="Weir-Flow-Irregular.php">Aliran Bendung Ukur Tidak Beraturan</a> untuk mercu berprofil atau bertangga.</dd><dt>Pintu air atau sambungan pipa</dt><dd>Ukur elevasi muka air hulu dan hilir (atau elevasi dasar pipa jika mengalir bebas). Gunakan <a href="Orifice.php">Debit Lubang Aliran</a>. Untuk pipa bulat, D = diameter pipa; untuk pintu persegi panjang, masukkan lebar W dan tinggi D.</dd><dt>Waktu pengosongan waduk atau kolam</dt><dd>Gunakan <a href="Orifice-Drain-Time.php">Waktu Pengosongan Lubang Aliran</a> untuk memperkirakan berapa lama waktu yang diperlukan untuk menurunkan kolam atau waduk melalui lubang aliran dasar — berguna untuk perencanaan tampungan irigasi.</dd><dt>Standar lapangan</dt><dd>Persamaan debit bendung ukur dan lubang aliran yang digunakan di sini sesuai dengan prosedur USBR <em>Water Measurement Manual</em> (edisi ke-3), yang umumnya disyaratkan oleh pengelola air dan distrik irigasi.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Jarak emiter, S<sub>e</sub>';
$ec_lang['ip_sl']='Jarak lateral, S<sub>l</sub>';
$ec_lang['ip_n_e']='Emiter per lateral, n<sub>e</sub>';
$ec_lang['ip_n_l']='Lateral per zona, n<sub>l</sub>';
$ec_lang['ip_d']='Kedalaman aplikasi target, d';
$ec_lang['ip_a_e']='Luas per emiter, A<sub>e</sub>';
$ec_lang['ip_pr']='Laju pemberian air, PR';
$ec_lang['ip_q_lat']='Debit per lateral, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Debit zona, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Waktu operasi (jam)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Rembesan Saluran';
$ec_lang['cs_main_title']='Kalkulator Kehilangan Rembesan Saluran dan Efisiensi Saluran Gratis Daring';
$ec_lang['cs_main_desc']='Kehilangan Rembesan Saluran &amp; Efisiensi Saluran &mdash; Metode Debit Masuk-Keluar';
$ec_lang['cs_Q_in']='Debit masuk, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Debit keluar, Q<sub>out</sub>';
$ec_lang['cs_L']='Panjang segmen, L';
$ec_lang['cs_wp']='Keliling basah, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='Laju kehilangan rembesan, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Pemeriksaan pengukuran';
$ec_lang['cs_pct_loss']='Fraksi hilang';
$ec_lang['cs_Ec']='Efisiensi saluran, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Peringkat efisiensi';
$ec_lang['cs_Vol_day']='Volume harian yang hilang';
$ec_lang['cs_Vol_year']='Volume tahunan yang hilang';
$ec_lang['cs_Q_loss_per_L']='Kehilangan per satuan panjang, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Nilai air';
$ec_lang['cs_lining_cost']='Biaya pelapisan';
$ec_lang['cs_Ec_target']='Target pelapisan, E<sub>c,target</sub> <span title="Sasaran efisiensi saluran setelah pelapisan; fraksi 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Luas pelapisan, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Nilai tahunan yang hilang';
$ec_lang['cs_annual_value_recovered']='Nilai tahunan yang dipulihkan';
$ec_lang['cs_lining_total_cost']='Biaya pelapisan total';
$ec_lang['cs_payback_years']='Periode pengembalian <span title="Pengembalian sederhana = total biaya pelapisan ÷ nilai tahunan yang dipulihkan" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — rembesan terdeteksi';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — tidak ada kehilangan terukur';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — periksa pengukuran';
$ec_lang['cs_Ec_good']='Baik — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Sedang — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Buruk — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_term']='Metode';
$ec_lang['cs_notes_1_def']='Metode debit masuk-keluar memperkirakan rembesan dengan mengukur debit di ujung hulu dan hilir segmen saluran: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. Efisiensi saluran E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Volume tahunan mengasumsikan operasi debit penuh terus-menerus; kehilangan aktual lebih rendah untuk saluran musiman atau aliran sebagian.';
$ec_lang['cs_notes_2_term']='Peringkat Efisiensi';
$ec_lang['cs_notes_2_def']='Saluran tanah tidak dilapisi yang umum: E<sub>c</sub> = 60–80%. Saluran tanah terawat baik: 75–85%. Saluran berlapis beton: 90–98%. Kehilangan rembesan di atas 30% debit masuk sering kali membenarkan investasi pelapisan saluran. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Pengembalian Pelapisan';
$ec_lang['cs_notes_3_def']='Masukkan nilai air dan biaya pelapisan dalam mata uang apa pun yang konsisten. Luas pelapisan = panjang segmen × keliling basah — keliling basah penampang saluran pada kedalaman debit terukur (lebar dasar ditambah kedua sisi tebing basah). Nilai tahunan yang dipulihkan mengasumsikan saluran yang dilapisi mencapai E<sub>c</sub> target secara berkelanjutan. Pengembalian aktual akan lebih lama untuk saluran musiman atau jika pelapisan tidak mencapai efisiensi target.';
$ec_lang['cs_notes_4_term']='Referensi';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, edisi ke-3 (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='Tentang';
$ec_lang['install_main_menu']='Instal';
$ec_lang['install_main_title']='Instal EngCalcs';
$ec_lang['install_main_desc']='Tambahkan ke perangkat Anda untuk penggunaan offline';
$ec_lang['contact_main_menu']='Kontak';
$ec_lang['about_main_title']='Tentang Kalkulator Teknik HawsEDC';
$ec_lang['about_main_desc']='Misi, Sumber Terbuka, dan Kontribusi';
$ec_lang['about_body_html']='<h3>Misi</h3><p>Kalkulator Teknik HawsEDC hadir untuk melayani insinyur dan pekerja lapangan di seluruh dunia — terutama mereka yang bekerja di wilayah dengan keterbatasan air, sumber daya terbatas, atau kurang terlayani. Alat-alat ini merupakan bagian dari misi kemanusiaan yang lebih luas: menyampaikan kepada setiap manusia dengan cara yang paling praktis dan efektif bahwa mereka dicintai dan disayangi selamanya, bahwa mereka tidak perlu takut, dan bahwa mereka tidak akan merusak segalanya.</p><p>Kalkulator adalah kendaraannya. Tujuannya adalah dunia yang bebas dari penderitaan.</p><h3>Lisensi Sumber Terbuka</h3><p>Semua kode dirilis di bawah <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 atau lebih baru</a> — bebas dalam arti kebebasan. Anda boleh menggunakan, mempelajari, memodifikasi, dan mendistribusikan ulang kode dengan syarat yang sama.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Kode Sumber</h3><p>Kode sumber lengkap tersedia secara publik di Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Anda dapat menjelajahi kode, mengajukan isu, atau mem-fork repositori di sana.</p><h3>Berkontribusi</h3><p>Pull request sangat disambut. Cara berkontribusi:</p><ul><li><strong>Terjemahan</strong> — tingkatkan atau tambahkan bahasa. Buka pull request dengan perubahan pada file <code>lib/lang.ec.??.php</code> yang relevan.</li><li><strong>Laporan bug</strong> — gunakan formulir umpan balik di halaman kalkulator mana pun, atau ajukan isu di Bitbucket.</li><li><strong>Kalkulator baru</strong> — ide untuk alat teknik hidrolik yang melayani pekerja lapangan dan praktisi irigasi sangat disambut. Lihat panduan pengembang <code>CLAUDE.md</code> di repositori.</li><li><strong>Hosting</strong> — jika Anda dapat mencerminkan kalkulator ini untuk wilayah dengan konektivitas terbatas, silakan hubungi kami.</li></ul><h3>Penggunaan Offline</h3><p>Kalkulator-kalkulator ini berfungsi sebagai Aplikasi Web Progresif (PWA). Kunjungi halaman kalkulator mana pun saat terhubung ke internet, dan browser Anda akan secara otomatis menyimpan semua kalkulator ke dalam cache. Setelah itu, semua kalkulator berfungsi secara offline — tidak perlu internet.</p><p>Di Android atau iOS, gunakan opsi "Tambahkan ke Layar Utama" di browser Anda untuk memasang EngCalcs sebagai aplikasi di perangkat Anda. Di desktop, cari ikon pasang di bilah alamat browser Anda.</p><p>Anda juga dapat menyimpan kalkulator individual menggunakan menu "Simpan sebagai…" di browser Anda untuk penggunaan offline sekali pakai.</p><h3>Kontak</h3><p>Tom Haws — insinyur hidrolik dan penulis kalkulator ini.<br />Gunakan formulir umpan balik di halaman kalkulator mana pun, atau akses kode sumber di <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Kontak HawsEDC';
$ec_lang['contactSendMessage']='Kirim pesan ke Tom Haws';
$ec_lang['contactYourName']='Nama Anda:';
$ec_lang['contactYourEmail']='Alamat e-mail Anda:';
$ec_lang['contactSubject']='Subjek:';
$ec_lang['contact_message']='Pesan:';
$ec_lang['contactSpamPrefix']='Lima ditambah satu sama dengan';
$ec_lang['contactSpamPostfix']='(Tulis dalam bahasa Inggris. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Kirim Pesan';
$ec_lang['contact_success']='Terima kasih telah meluangkan waktu untuk menulis.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Desain Saluran Curam Berbatu (Robinson)';
$ec_lang['rc_main_title']='Kalkulator Desain Saluran Curam Berbatu Gratis Online — Robinson (1998)';
$ec_lang['rc_main_desc']='Penentuan Ukuran Riprap untuk Saluran Curam Berbatu — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Kemiringan dasar saluran curam, S<sub>0</sub>';
$ec_lang['rc_qt']='Debit satuan total, q<sub>t</sub> <span title="Debit per satuan lebar di inlet saluran curam berbatu. Untuk saluran dengan lebar dasar B dan debit total Q, gunakan q_t = Q / B." class="ec-tip">?</span>';
$ec_lang['rc_np']='Porositas riprap, n<sub>p</sub>';
$ec_lang['rc_sg']='Berat jenis batu, sg <span title="Granit atau basalt pecah biasa ≈ 2.65. Rentang valid Robinson: 2.54 hingga 2.82." class="ec-tip">?</span>';
$ec_lang['rc_SD']='Gradasi SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Simpangan baku gradasi. Batu seragam ≈ 1.25. Rentang valid Robinson: 1.15 hingga 1.47." class="ec-tip">?</span>';
$ec_lang['rc_yn']='Kedalaman normal di saluran inlet, y<sub>n</sub> <span title="Genangan (Hp > yn) baik — mengurangi erosi di hulu. (USDA)" class="ec-tip">?</span>';
$ec_lang['rc_D50']='Ukuran median batu yang diperlukan, D<sub>50</sub> <span title="Pers. 1 (S0 < 0.10) atau Pers. 2 (0.10-0.40). Valid: D50 15-278 mm, S0 0.02-0.40. Di luar rentang: diekstrapolasi." class="ec-tip">?</span>';
$ec_lang['rc_eq_used']='Persamaan yang diterapkan';
$ec_lang['rc_sg_check']='Pemeriksaan berat jenis';
$ec_lang['rc_SD_check']='Pemeriksaan gradasi SD';
$ec_lang['rc_sg_ok']='sg dalam rentang valid';
$ec_lang['rc_sg_ok_tip']='2.54–2.82 (Robinson)';
$ec_lang['rc_sg_low']='sg di bawah rentang Robinson';
$ec_lang['rc_sg_low_tip']='Rentang valid: 2.54–2.82';
$ec_lang['rc_sg_high']='sg di atas rentang Robinson';
$ec_lang['rc_sg_high_tip']='Rentang valid: 2.54–2.82';
$ec_lang['rc_SD_ok']='SD dalam rentang valid';
$ec_lang['rc_SD_ok_tip']='1.15–1.47 (Robinson)';
$ec_lang['rc_SD_low']='SD di bawah rentang Robinson';
$ec_lang['rc_SD_low_tip']='Rentang valid: 1.15–1.47';
$ec_lang['rc_SD_high']='SD di atas rentang Robinson';
$ec_lang['rc_SD_high_tip']='Rentang valid: 1.15–1.47';
$ec_lang['rc_layer']='Ketebalan lapisan batu (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Jari-jari kurva mercu atas (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Panjang busur kurva mercu atas';
$ec_lang['rc_apron_length']='Panjang lantai hilir outlet (15 × D<sub>50</sub>) <span title="Diperlukan untuk dukungan struktural batu saluran curam. &quot;Tailwater minimum yang terjadi akibat saluran outlet dan resistansi saluran hilir cukup untuk memastikan stabilitas riprap pada saluran outlet.&quot; (Robinson)" class="ec-tip">?</span>';
$ec_lang['rc_n_chute']='Kekasaran Manning di saluran curam, n';
$ec_lang['rc_Vm']='Kecepatan melalui mantel batu, V<sub>m</sub> <span title="Fraksi q_t yang mengalir melalui pori batu. Sisanya q_s mengalir di atas permukaan. Porositas default n_p = 0.45 untuk batu pecah bersudut." class="ec-tip">?</span>';
$ec_lang['rc_qm']='Debit satuan melalui mantel, q<sub>m</sub>';
$ec_lang['rc_qs']='Debit satuan permukaan, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Kedalaman aliran di atas permukaan riprap, d';
$ec_lang['rc_Hp']='Tinggi muka air mercu inlet, H<sub>p</sub> <span title="Genangan (Hp > yn) baik — mengurangi erosi di hulu. (USDA)" class="ec-tip">?</span>';
$ec_lang['rc_ponding_check']='Pemeriksaan genangan di inlet';
$ec_lang['rc_pond_ok']='H<sub>p</sub> > y<sub>n</sub> — genangan di hulu';
$ec_lang['rc_pond_ok_tip']='Genangan di hulu inlet saluran curam baik; hal ini mengurangi erosi di hulu. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — tidak ada genangan — potensi erosi di inlet';
$ec_lang['rc_pond_warn_tip']='Tidak ada genangan di hulu inlet saluran curam; erosi dapat terjadi di hulu. (USDA)';
$ec_lang['rc_eq1']='Pers. 1 (S<sub>0</sub> < 0.10) — kemiringan landai';
$ec_lang['rc_eq2']='Pers. 2 (0.10 ≤ S<sub>0</sub> ≤ 0.40) — kemiringan curam';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0.02 — di bawah rentang validasi Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0.40 — di atas rentang validasi Robinson';
$ec_lang['rc_notes_1_term']='Persamaan Penentuan Ukuran Batu';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) mengembangkan dua persamaan empiris untuk ukuran median riprap D<sub>50</sub> berdasarkan kemiringan saluran curam dan debit satuan. Persamaan 1 berlaku untuk kemiringan landai (S<sub>0</sub> < 0.10); Persamaan 2 berlaku untuk kemiringan curam (0.10 ≤ S<sub>0</sub> ≤ 0.40). Kedua persamaan memerlukan q<sub>t</sub> dalam m²/s dan menghasilkan D<sub>50</sub> dalam mm. Rentang yang divalidasi adalah 0.02 ≤ S<sub>0</sub> ≤ 0.40.';
$ec_lang['rc_notes_2_term']='Debit Satuan';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> adalah debit satuan total di mercu saluran curam (total debit per satuan lebar). Untuk saluran dengan lebar dasar B yang membawa debit total Q, perkirakan q<sub>t</sub> ≈ Q / B, atau hitung dari kondisi kedalaman kritis di inlet saluran curam.';
$ec_lang['rc_notes_3_term']='Aliran Melalui Mantel Batu';
$ec_lang['rc_notes_3_def']='Sebagian dari total debit bergerak melalui pori-pori riprap batu (debit mantel q<sub>m</sub>); sisanya mengalir di atas permukaan batu (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Kedalaman aliran d dihitung dari persamaan Manning yang diterapkan pada debit permukaan q<sub>s</sub> menggunakan kekasaran saluran curam n. Porositas default n<sub>p</sub> = 0.45 adalah tipikal untuk batu pecah bersudut.';
$ec_lang['rc_notes_5_term']='Rentang Ukuran Batu yang Valid';
$ec_lang['rc_notes_5_def']='Persamaan dikembangkan menggunakan rentang D<sub>50</sub> dari 15 mm hingga 278 mm. Hasil di luar rentang ini diekstrapolasi dan harus digunakan dengan pertimbangan teknis tambahan.';
$ec_lang['rc_notes_6_term']='Elevasi Lantai Hilir Outlet';
$ec_lang['rc_notes_6_def']='Elevasi bagian atas riprap di saluran outlet harus berada pada atau di bawah elevasi dasar saluran hilir. Jika lebih tinggi, batu outlet akan tidak stabil.';
$ec_lang['rc_notes_7_def']='Ketika kedalaman normal di saluran inlet lebih kecil dari tinggi muka air mercu (H<sub>p</sub>) yang diperlukan untuk mengalirkan q<sub>t</sub>, terjadi aliran terbatas atau genangan di hulu inlet. Hal ini umumnya dapat diterima — genangan mengurangi kecepatan dan mencegah erosi di hulu. Untuk memeriksa: gunakan kalkulator aliran mercu untuk mencari H<sub>p</sub> bagi q<sub>t</sub> dan lebar mercu yang diberikan, lalu bandingkan dengan kedalaman normal saluran inlet. Jika H<sub>p</sub> melebihi kedalaman normal, genangan akan terjadi.';
$ec_lang['rc_notes_4_term']='Referensi';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Desain saluran curam berbatu</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS juga menerbitkan <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">lembar kerja Excel</a> berdasarkan metode yang sama.';
// Sketch labels
$ec_lang['rc_sketch_filter']='Filter';
$ec_lang['rc_sketch_top_crest_curve']='Kurva Mercu Atas';
$ec_lang['rc_sketch_outlet_apron']='Lantai Hilir';
$ec_lang['rc_sketch_radius']='jari-jari';
// Irrigation Pressure. Prefix ip_.
$ec_lang['ip_main_menu']='Tekanan Irigasi';
$ec_lang['ip_main_title']='Kalkulator Tekanan Irigasi &amp; Keseragaman Distribusi Gratis Daring';
$ec_lang['ip_main_desc']='Tekanan Cabang Pengujian dan Estimasi Keseragaman';
$ec_lang['ip_h_supply']='Tekanan pasokan';
$ec_lang['ip_elev_supply']='Elevasi pasokan, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Debit desain emiter, q<sub>design</sub>';
$ec_lang['ip_h_design']='Tekanan desain emiter';
$ec_lang['ip_x']='Eksponen debit emiter, x <span title="0.5 untuk emiter non-kompensasi standar; mendekati 0 untuk emiter kompensasi tekanan" class="ec-tip">?</span>';
$ec_lang['ip_reach_table_title']='Jalur pengujian';
$ec_lang['ip_group_reach']='Segmen';
$ec_lang['ip_group_upstream']='Hulu';
$ec_lang['ip_group_downstream']='Hilir';
$ec_lang['ip_group_loss']='Kehilangan';
$ec_lang['ip_is_lateral']='Lat. <span title="Dicentang: segmen ini adalah bagian dari lateral pengujian tempat emiter-emiter individual mengambil air. Tidak dicentang: segmen ini adalah pipa utama, hanya mengalirkan debit ke lateral yang tidak berada pada jalur pengujian." class="ec-tip">?</span>';
$ec_lang['ip_count']='Emiter <span title="Baris lateral: emiter pada segmen ini saja. Baris pipa utama: total emiter pada lateral SELAIN lateral ini yang bercabang dari segmen ini. Untuk segmen pipa utama yang berakhir pada lateral pengujian, ini juga mencakup lateral mana pun yang lebih jauh di sepanjang pipa utama melewati titik tersebut, atau yang berbagi persimpangan yang sama (misalnya lateral di sisi berlawanan) — debit lateral tersebut juga bercabang dari segmen yang sama ini." class="ec-tip">?</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_e']='e <span title="Tinggi kekasaran Darcy-Weisbach" class="ec-tip">?</span>';
$ec_lang['ip_km']='k<sub>m</sub> <span title="Koefisien kehilangan lokal umum untuk fiting/katup/kopler segmen ini (disarankan minimum ≥0.5)" class="ec-tip">?</span>';
$ec_lang['ip_elev_ds']='Elev. Hilir <span title="Elevasi ujung hilir segmen ini. Opsional pada baris tengah (default datar / sama dengan simpul di atasnya jika dikosongkan). Wajib pada baris terakhir: nilai tersebut adalah elevasi emiter terakhir, yang secara langsung menentukan tekanan pasokan yang diperlukan." class="ec-tip">?</span>';
$ec_lang['ip_elev_ds_missing_warn']='Elevasi emiter terakhir (baris terakhir) dibiarkan kosong dan menggunakan default datar — masukkan nilainya untuk hasil yang akurat';
$ec_lang['ip_flow']='Debit';
$ec_lang['ip_press']='Tek.';
$ec_lang['ip_v']='V';
$ec_lang['ip_hv']='H<sub>v</sub>';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='h<sub>L</sub> <span title="Total kehilangan segmen, h_f + h_m" class="ec-tip">?</span>';
$ec_lang['ip_pressure_warn']='Tekanan rendah/negatif — periksa kemungkinan kondisi di bawah tekanan atmosfer';
$ec_lang['ip_pressure_warn_short']='Rendah';
$ec_lang['ip_h_far']='Tekanan emiter terakhir';
$ec_lang['ip_q_supply']='Debit pasokan jalur pengujian, Q<sub>supply</sub> <span title="Debit yang masuk ke jalur pengujian model ini saja — untuk seluruh zona/sistem, lihat Q_zone pada Desain Aplikasi di bawah." class="ec-tip">?</span>';
$ec_lang['ip_q_critical']='Debit emiter terakhir, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Debit emiter rata-rata (lateral pengujian), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='Est. &Delta;tekanan, rata-rata vs. lateral pengujian <span title="Seberapa jauh lebih tinggi (atau lebih rendah) Anda memperkirakan lateral tipikal beroperasi dibandingkan lateral pengujian ini. Lateral pengujian sengaja dianggap sebagai kasus terburuk, sehingga rata-ratanya sendiri merupakan estimasi yang terlalu rendah untuk rata-rata lapangan — jika dibiarkan pada 0, pemeriksaan keseragaman dan angka desain aplikasi di bawah menggunakan rata-rata lateral pengujian itu sendiri (kemungkinan optimistis) apa adanya." class="ec-tip">?</span>';
$ec_lang['ip_q_avg_field']='Est. debit emiter rata-rata lapangan, q<sub>avg,field</sub> <span title="q_avg_lateral dievaluasi ulang pada tekanan setiap baris lateral ditambah selisih tekanan yang dimasukkan di atas — upaya untuk mengoreksi anggapan bahwa lateral pengujian adalah kasus terburuk, bukan kasus yang representatif. Menjadi input bagi pemeriksaan keseragaman dan bagian desain aplikasi di bawah." class="ec-tip">?</span>';
$ec_lang['ip_du_estimate']='Pemeriksaan keseragaman, q<sub>last</sub>/q<sub>avg,field</sub> <span title="Debit emiter terakhir yang dihitung dibagi dengan estimasi debit emiter rata-rata lapangan — ini adalah pendekatan dari Keseragaman Distribusi kuartal-bawah standar (rata-rata kelompok terendah ÷ rata-rata populasi); ini berasal dari sampel model kecil dan koreksi perkiraan pengguna, bukan sampel statistik lapangan penuh. Nilai pada atau di atas 1 mungkin dan valid: itu hanya berarti tekanan emiter terakhir berada pada atau di atas rata-rata lapangan yang diestimasi, sehingga emiter lain menjadi titik tekanan terendah. Ini bisa terjadi karena emiter terakhir berada di tanah rendah atau karena estimasi &Delta;tekanan terlalu kecil." class="ec-tip">?</span>';
$ec_lang['ip_worst_case_warn']='Tekanan pada emiter pengujian &ge; tekanan pasokan. Ini mungkin bukan emiter kasus terburuk, atau ukuran pipa bisa diperkecil.';
$ec_lang['ip_q_ratio']='Debit emiter terakhir &divide; debit desain, q<sub>last</sub>/q<sub>design</sub> <span title="Ini berbeda dari pendekatan kami terhadap ukuran keseragaman standar." class="ec-tip">?</span>';
$ec_lang['ip_no_solution']='Tidak ada solusi: tekanan pasokan yang diperlukan melebihi tekanan pasokan yang dimasukkan. Tingkatkan tekanan pasokan, kurangi permintaan, atau gunakan pipa yang lebih besar.';
$ec_lang['ip_notes_1_term']='Metode';
$ec_lang['ip_notes_1_def']='Menebak tekanan pada emiter terakhir (paling jauh), lalu menelusuri Garis Energi mundur menuju pasokan, segmen demi segmen, menambahkan kehilangan gesekan dan kehilangan lokal di sepanjang jalan. Elevasi dan tinggi kecepatan dikurangkan pada setiap simpul untuk melaporkan tekanan aktual di sana. Tekanan ujung jauh yang ditebak disesuaikan (biseksi) hingga tekanan pasokan yang diperlukan hasil hitungan cocok dengan tekanan pasokan yang dimasukkan — masalah loop tertutup yang sama yang ditangani oleh pemecah aliran pipa pada kalkulator Aliran Pipa Manning, diperluas ke jaringan bercabang.';
$ec_lang['ip_notes_2_term']='Segmen Pipa Utama vs. Lateral';
$ec_lang['ip_notes_2_def']='Setiap baris adalah satu segmen di sepanjang jalur tunggal yang secara hidraulis paling buruk (jalur pengujian) dari pasokan ke emiter terakhir. Segmen Pipa Utama hanya mengalirkan debit ke lateral yang tidak berada pada jalur pengujian, sehingga pengambilannya adalah perkalian sederhana (debit desain × jumlah total emiter segmen tersebut) — tanpa kepekaan terhadap tekanan lokal. Pipa utama adalah pipa batang bersama, sehingga segmen pipa utama yang berakhir pada lateral pengujian harus mencakup bukan hanya lateral di antara titik-titik ujungnya sendiri, tetapi juga lateral mana pun yang lebih jauh di sepanjang pipa utama melewati titik tersebut, atau yang berbagi persimpangan yang sama (misalnya lateral di sisi berlawanan) — debit lateral-lateral tersebut melewati segmen yang sama sebelum bercabang, baik lateral itu muncul di tempat lain dalam tabel ini maupun tidak. Segmen Lateral adalah segmen dari lateral pengujian itu sendiri: debit emiter dihitung dari tekanan lokal aktual melalui q = k·H<sup>x</sup>, dan kehilangan gesekan dikurangi oleh faktor F(n) Christiansen untuk memperhitungkan debit yang menurun seiring setiap emiter pada segmen tersebut mengambil air.';
$ec_lang['ip_notes_3_term']='Keterbatasan';
$ec_lang['ip_notes_3_def']='Memodelkan satu tekanan pasokan tetap (tanpa kurva pompa), satu jalur pengujian saja (bukan seluruh lapangan), dan kurva emiter 2-parameter (atur eksponen mendekati 0 untuk mendekati emiter kompensasi tekanan). Dua rasio keseragaman yang berbeda dilaporkan, sengaja dipisahkan: q<sub>last</sub>/q<sub>avg,field</sub> adalah pendekatan dari Keseragaman Distribusi kuartal-bawah standar (rata-rata kelompok terendah ÷ rata-rata populasi); tetapi ini berasal dari sampel model kecil dan koreksi perkiraan pengguna, bukan sampel statistik lapangan penuh standar. Selain itu, lateral pengujian sengaja dianggap sebagai kasus terburuk, sehingga rata-ratanya yang mentah dan tidak dikoreksi akan meremehkan rata-rata lapangan yang sebenarnya dan membuat keseragaman terlihat lebih baik daripada kenyataannya; input &Delta;tekanan ada khusus untuk mengatasi bias tersebut. Nilai keseragaman pada atau di atas 1 tetap dimungkinkan: itu hanya berarti tekanan emiter terakhir berada pada atau di atas rata-rata lapangan yang diestimasi, sehingga emiter lain menjadi titik tekanan terendah. Ini bisa terjadi karena emiter terakhir berada di tanah rendah atau karena estimasi &Delta;tekanan terlalu kecil. q<sub>last</sub>/q<sub>design</sub> adalah pemeriksaan non-keseragaman yang berbeda terhadap debit yang dinilai oleh pabrikan — berguna untuk mendeteksi sistem yang secara keseluruhan bertekanan terlalu tinggi atau terlalu rendah, tetapi merupakan pemeriksaan terpisah yang dibaca bersama angka keseragaman, karena debit desain/nilai pabrikan tidak bergantung pada tekanan operasi rata-rata sistem yang sebenarnya.';
$ec_lang['ip_notes_4_term']='Referensi';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irigasi dengan penyemprotan.&rdquo; California Agricultural Experiment Station Bulletin 670. Standar ASAE/ASABE untuk desain mikroirigasi menggunakan pendekatan kehilangan gesekan multi-outlet yang sama.';
$ec_lang['ip_notes_5_term']='Desain Aplikasi';
$ec_lang['ip_notes_5_def']='Laju pemberian air dan debit sistem/zona menggunakan estimasi debit emiter rata-rata lapangan (q<sub>avg,field</sub> — rata-rata lateral pengujian itu sendiri, dikoreksi oleh estimasi &Delta;tekanan yang dimasukkan), bukan laju yang ditebak: PR = q<sub>avg,field</sub> / A<sub>e</sub>, dipasok oleh nilai model yang telah dikoreksi. Jarak dan jumlah lateral/emiter seluruh sistem merupakan input terpisah di sini karena jalur pengujian hanya memodelkan satu cabang kasus terburuk, bukan setiap lateral di lapangan.';
