<?php

// äöüÄÖÜß — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']='Anteil';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft WS';
$ec_lang['u_ftps']='ft/s';
$ec_lang['u_gpm']='gal/min';
$ec_lang['u_gradePercent']='% Gefälle';
$ec_lang['u_grade']='Gefälle';
$ec_lang['u_in2']='in^2';
$ec_lang['u_inh2o']='in WS';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m WS';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm WS';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='lb/ft^2';
$ec_lang['u_psi']='psi';
$ec_lang['u_bar']='bar';
$ec_lang['u_kgfcm2']='kgf/cm^2';
$ec_lang['u_s']='s';
$ec_lang['u_lph']='L/h';
$ec_lang['u_gph']='gal/h';
$ec_lang['u_mmph']='mm/h';
$ec_lang['u_inph']='in/h';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Rechner';
$ec_lang['menu_main_list']='Rechnerliste';
$ec_lang['menu_main_hydraulics']='Hydraulik';
$ec_lang['menu_main_language']='Sprache';
$ec_lang['menu_more']='Mehr';
$ec_lang['menu_libre']='Freie Software';
$ec_lang['template_welcome']='Lasst Eure Ängste an der Tür; hier wird Liebe gesprochen. Ihr ruiniert nicht alles. Genießt auch die <a target="_blank" href="https://hawsedc.com/download.php">kostenlosen HawsEDC AutoCAD-Tools.</a>';
$ec_lang['template_feedback']='Fällt Ihnen eine bessere Formulierung für diese Seite auf, oder sonst etwas? Möchten Sie mitwirken oder lernen, wie man solche Werkzeuge entwickelt? Bitte kontaktieren Sie mich.';
$ec_lang['template_printable_title']='Druckbarer Titel';
$ec_lang['template_printable_subtitle']='Druckbarer Untertitel';
$ec_lang['index_title']='Kostenlose Ingenieurrechner online';
$ec_lang['index_meta_desc_plain']='Kostenlose Ingenieurrechner für Hydraulik: Rohre, Kanäle, Wehre und Bewässerung. Sie laufen im Browser, funktionieren offline und sind in 27 Sprachen verfügbar.';
$ec_lang['calc_set_units']='Einheiten festlegen:';
$ec_lang['calc_units_us']='US';
$ec_lang['calc_units_si']='SI';
$ec_lang['calc_defaults']='Standardwerte wiederherstellen';
$ec_lang['calc_defaults_confirm']='Rechner auf die ursprünglichen Standardwerte zurücksetzen?';
$ec_lang['points_data_help']='(oder Kopieren/Einfügen im Datenbereich)';
$ec_lang['points_data_title']='Punktdaten<br />(durch Komma oder Tabulator getrennt)';
$ec_lang['points_data_copy']='Kopieren';
$ec_lang['points_data_paste']='Einfügen';
$ec_lang['calc_inputs']='Eingaben';
$ec_lang['calc_results']='Ergebnisse';
$ec_lang['view_hide_line']='[Diese Zeile ausblenden]';
$ec_lang['view_printable']='Druckversion (Seite neu laden zum Zurücksetzen)';
$ec_lang['ec_name_label']='Diese Berechnung speichern:';
$ec_lang['ec_name_placeholder']='Name';
$ec_lang['ec_name_hint']='Speichert diese Eingaben in der URL zum Lesezeichen, zum Abrufen aus dem Verlauf und zum Teilen';
$ec_lang['calc_copy_link']='Link kopieren';
$ec_lang['ec_related_calcs']='Verwandte Rechner:';
$ec_lang['calc_copy_link_done']='Kopiert!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Rohrreibungsverlust Darcy-Weisbach';
$ec_lang['dw_main_title']='Kostenloser Online-Rechner Rohrreibungsverlust Darcy-Weisbach';
$ec_lang['dw_main_desc']='Rohrreibungsverlust nach Darcy-Weisbach bei gegebenem Durchmesser, Rauheit und Durchfluss';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Absolute Rauheitshöhe, e, der Rohrwand. Typische Werte: Stahl (neu) 0,046 mm, Stahl (gebraucht) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, Beton 0,3–3 mm.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s für sauberes Wasser bei 20°C">Kinematische Viskosität, ν <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Kinematische Viskosität, ν';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s für sauberes Wasser bei 20°C';
$ec_lang['dw_reynolds_number']='Reynolds-Zahl, Re';
$ec_lang['dw_flow_regime']='Strömungsregime';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='Übergangsbereich';
$ec_lang['dw_regime_turbulent']='turbulent';
$ec_lang['dw_friction_factor_method']='Methode des Reibungskoeffizienten';
$ec_lang['dw_friction_factor']='Reibungskoeffizient, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Rohrreibungsverlust Hazen-Williams';
$ec_lang['hw_main_title']='Kostenloser Online-Rechner Rohrreibungsverlust Hazen-Williams';
$ec_lang['hw_main_desc']='Rohrreibungsverlust nach Hazen-Williams bei gegebenem Durchmesser, Rauheit und Durchfluss';
$ec_lang['hw_hgl_1']='HGL flussabwärts';
$ec_lang['hw_hgl_2']='HGL flussaufwärts';
$ec_lang['hw_elev_up']='Höhe flussaufwärts';
$ec_lang['hw_pressure_up']='Druck flussaufwärts';
$ec_lang['hw_elev_down']='Höhe flussabwärts';
$ec_lang['hw_pressure_down']='Druck flussabwärts';
$ec_lang['hw_pressure_check']='Druckprüfung';
$ec_lang['hw_pressure_ok_short']='Positiver Druck';
$ec_lang['hw_pressure_neg_short']='Negativer Druck';
$ec_lang['hw_pressure_neg']='Der Druck flussabwärts liegt unter null. Die HGL fällt unter das Rohr, sodass das Rohr nicht vollständig durchströmt wäre und dieses Ergebnis möglicherweise nicht gültig ist.';
$ec_lang['hw_roughness']='Hazen-Williams-Koeffizient, C';
$ec_lang['hw_note_1']='<dl><dt>Dieser Rechner bildet den Rohrverlauf zwischen den beiden Enden nicht ab.</dt><dd>Er verwendet nur die von Ihnen eingegebenen Höhen flussaufwärts und flussabwärts. Steigt das Gelände irgendwo dazwischen höher an als beide Enden, ist der Druck an diesem Hochpunkt niedriger als jeder hier angezeigte Druck. Führen Sie den Rechner erneut für die Strecke vom flussaufwärtigen Ende bis zum Hochpunkt aus, um dies zu prüfen.</dd><dd>Fällt die HGL unter das Rohr, steht das Wasser unter negativem Druck. Luft tritt aus der Lösung aus, ein dünnwandiges Rohr kann einbrechen, und verunreinigtes Grundwasser kann durch die Rohrverbindungen eindringen. Halten Sie die Leitung überall unter positivem Druck, und ziehen Sie an jedem Hochpunkt ein Entlüftungsventil in Betracht.</dd><dt>Der Druck flussaufwärts ist eine von Ihnen vorgegebene Randbedingung.</dt><dd>Lesen Sie ihn von einem Manometer, vom Wasserstand eines Behälters (der Höhe des Wassers über dem Rohr) oder von einer Pumpenkennlinie ab. Eine Pumpe liefert bei steigendem Durchfluss weniger Druck; verwenden Sie daher den Punkt auf der Kennlinie, der dem oben eingegebenen Durchfluss entspricht.</dd><dt>Addieren Sie die örtlichen (Einzel-)Verlustbeiwerte selbst.</dt><dd>Addieren Sie die K-Werte für jeden Schieber, jede Krümmung, jedes T-Stück, jeden Zähler und jeden Einlauf auf der Leitung, und geben Sie diese Summe ein. Folgen Sie dem Link bei dieser Eingabe für typische Werte. Bei einer langen Transportleitung sind diese Verluste im Vergleich zur Reibung gering, in kurzer Stationsverrohrung können sie jedoch den Großteil des Verlusts ausmachen.</dd></dl>';
// Manning Irregular
$ec_lang['mi_menu']='Unregelmäßiges Profil Manning';
$ec_lang['mi_main_title']='Kostenloser Online-Rechner unregelmäßiges Profil Manning';
$ec_lang['mi_main_desc']='Gleichförmiger Abflussrechner für unregelmäßiges Profil nach Manning';
$ec_lang['mi_waterSurfaceElevation']='Wasserstand';
$ec_lang['mi_q_617']='<span class="ec-help" title="Der zusammengesetzte Durchfluss, Q, unter Verwendung eines zusammengesetzten n für jeden Bereich nach Chow 6-17, bei gleichen Geschwindigkeiten">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Querschnittspunkte';
$ec_lang['mi_groupPoint']='Punkt';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Bereich';
$ec_lang['mi_station']='Sta.';
$ec_lang['mi_elevation']='Höhe';
$ec_lang['mi_d50in']='Mediane<br />Korn-<br />größe<br />Deckwerk';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />Bereich-<br />grenze<br />(Ufer)';
$ec_lang['mi_tau']='Sohl-<br />schub-<br />spg. τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Zus.-<br />ges. n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='Zusammengesetztes n';
$ec_lang['mi_notes_1_def']='Dieser Rechner folgt dem HEC-RAS-Referenzhandbuch bei der Berechnung des zusammengesetzten n des Bereichs nach Chow 1959, Seite 136, Gleichung 6-17 (nicht 6-18).';
$ec_lang['mi_notes_2_term']='Steindeckwerk';
$ec_lang['mi_notes_2_def']='Verwenden Sie den Manning-Trapezkanal-Rechner für die Steindeckwerk-Bemessung. Dieser Rechner eignet sich besser für natürliche Querschnitte.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Rohrdurchfluss Manning';
$ec_lang['mpf_main_title']='Kostenloser Online-Rechner Rohrdurchfluss Manning';
$ec_lang['mpf_main_desc']='Manning-Formel für gleichförmigen Rohrdurchfluss bei gegebenem Gefälle und Füllhöhe';
$ec_lang['mpf_spreadheet_notice']='Manning-Rohrdurchfluss-Tabelle';
$ec_lang['mpf_pipe_diameter']='Rohrdurchmesser, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning-Rauheitskoeffizient, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Reibungsgefälle, S<sub>f</sub></a><span class="ec-help" title="Mitunter gleich dem Rohrgefälle. Dem Link für die Erklärung folgen (nur auf Englisch)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Relative Füllhöhe, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Durchfluss, Q';
$ec_lang['mpf_flow_tip']='Durchfluss und Tiefe werden für ein unendlich langes Rohr berechnet. Um diesen Durchfluss tatsächlich in das Rohr einzuleiten, kann eine größere Oberwassertiefe erforderlich sein. Einzelheiten und ein Lehrvideo finden Sie unten in den Hinweisen.';
$ec_lang['mpf_velocity']='Fließgeschwindigkeit, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="Kinetische Energie als Höhe der Wassersäule, v²/2g">Geschwindigkeitshöhe, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='Durchflossene Fläche, A';
$ec_lang['mpf_pipe_area']='Rohrquerschnitt, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Relative Fläche, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Benetzter Umfang, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Hydraulischer Radius, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Wasserspiegelbreite, T';
$ec_lang['mpf_froude_number']='Froude-Zahl, Fr';
$ec_lang['mpf_shear_stress']='Mittlere Sohlschubspannung, τ';
$ec_lang['mpf_full_flow']='Vollfüllung, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Füllungsverhältnis, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Dies ist der Durchfluss und die Tiefe innerhalb eines <em>unendlich langen</em> Rohres.</dt><dd>Um den Durchfluss in das Rohr zu leiten, kann eine erheblich höhere Oberwassertiefe erforderlich sein. Addieren Sie mindestens das 1,5-fache der Geschwindigkeitshöhe zur Oberwassertiefe oder <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">sehen Sie das 2-Minuten-Tutorial</a> für Standard-Durchlassberechnungen mit <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>, dem kostenlosen Durchlassprogramm der US-amerikanischen Bundesstraßenverwaltung (FHWA).</dd>';
$ec_lang['mpf_sewer_ref']='<dl><dt>Planen Sie einen Schmutzwasserkanal?</dt><dd>Siehe die <a target="_blank" href="/sewslope.php">Tabellen für das Mindestgefälle von Abwasserkanälen</a> für Rohre von 4 bis 96 Zoll (100 bis 2400 mm), angegeben in m/m, mm/m und Prozent, sowie die Studie <a target="_blank" href="/peakfact.php">Spitzenfaktoren für sehr geringe Durchflüsse</a>. Beide sind Referenzdokumente ausschließlich in englischer Sprache.</dd></dl>';
$ec_lang['mpf_solver_enter_positive_q']='Geben Sie ein positives Ziel-Q ein.';
$ec_lang['mpf_solver_no_solution']='Keine Lösung: Q übersteigt die Rohrkapazität bei y/d0 = 93.8% (Qmax = {qmax} in den gewählten Einheiten).';
$ec_lang['mpf_solve_button']='Berechnen';
$ec_lang['mpf_solve_for_flow']='für Durchfluss, Q =';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Rohrverlusthöhe Manning';
$ec_lang['mphl_main_title']='Kostenloser Online-Rechner Rohrverlusthöhe Manning';
$ec_lang['mphl_main_desc']='Manning-Formel Verlusthöhe bei gegebenem Vollfüllungsdurchfluss';
$ec_lang['mphl_pipe_length']='Rohrlänge, L';
$ec_lang['mphl_area']='Fläche, A';
$ec_lang['mphl_total_junction_k']='Örtlicher (Einzel-)Verlustbeiwert, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Verlustbeiwert, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Örtlicher (Einzel-)Verlustbeiwert, km. Diese Verluste treten an Rohrverzweigungen, Einläufen, Auslässen, Krümmern und Armaturen auf — die Bezeichnung „gering“ ist üblich, aber irreführend; auf einer kurzen Leitung können sie die Reibungsverluste erreichen oder übersteigen. Typische k-Werte: scharfkantiger Einlauf 0,5, je 45°-Krümmer 0,2–0,3, Schieber (vollständig geöffnet) 0,1, Klappenventil 0,2, Auslass (in Reservoir oder Atmosphäre) 1,0. Alle Formstücke zur Ermittlung des gesamten km addieren. Der Standardwert 2,0 geht von einem Einlauf, einem Auslass und zwei 45°-Krümmern aus.';
$ec_lang['mphl_friction_slope']='Reibungsgefälle';
$ec_lang['mphl_friction_loss']='Reibungsverlust, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Örtlicher (Einzel-)Verlust, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Gesamtverlust, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='EGL flussabwärts';
$ec_lang['mphl_egl_2']='EGL flussaufwärts';
$ec_lang['mphl_hgl_egl_tip']='Möglicherweise nicht gültig, wenn das Rohr hoch liegt. Siehe Hinweise.';
$ec_lang['mphl_note_1']='<dl><dt>Dieser Rechner bildet den Rohrverlauf zwischen den beiden Enden nicht ab.</dt><dd>Liegt die HGL an irgendeiner Stelle unter der Rohroberkante, ist diese Berechnung möglicherweise nicht gültig.</dd><dt>Für einen offenen Einlauf (Durchlass) müssen die Einlaufsteuerungsbedingungen geprüft werden.</dt><dd>1. Die HGL flussaufwärts muss über der normalen Fließtiefe flussaufwärts liegen (und höher als das Rohr!).</dd><dd>2. Der Oberwasserstand eines Durchlasses wird besser durch die EGL flussaufwärts als durch die HGL flussaufwärts dargestellt.</dd><dd>3. Sehen Sie <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">das 2-Minuten-Tutorial</a> für einfache Standard-Durchlassberechnungen mit <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>, dem kostenlosen Durchlassprogramm der US-amerikanischen Bundesstraßenverwaltung (FHWA).</dd><dd>4. Diese Seite löst nur den Fall der Auslasssteuerung: ein vollständig durchströmtes Rohr, bei dem die Bedingungen flussabwärts die Höhe (den Druck) vorgeben. Bei der Durchlassbemessung muss entschieden werden, ob Einlauf- oder Auslasssteuerung maßgebend ist; verwenden Sie daher HY-8, wann immer beides infrage kommen könnte.</dd></dl>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Trapezprofil-Kanal Manning';
$ec_lang['mtc_main_title']='Kostenloser Online-Rechner Trapezkanal Manning-Formel';
$ec_lang['mtc_main_desc']='Manning-Formel gleichförmiger Abfluss im Trapezkanal bei gegebenem Gefälle und Tiefe';
$ec_lang['mtc_bottom_width']='Sohlbreite, b';
$ec_lang['mtc_side_slope_1']='Böschung 1, z<sub>1</sub> (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Böschung 2, z<sub>2</sub> (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Kanalgefälle, S';
$ec_lang['mtc_flow_depth']='Fließtiefe, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Kurvenwinkel, β</a><span class="ec-help" title="Für Deckwerksbemessung. Dem Link für die Skizze folgen."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Dichte relativ zu Wasser. Typisch ≈ 2,65 für Schotter.">Relative Dichte des Steins, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Bemessungskorngröße, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n für Bemessungskorngröße nach Strickler';
$ec_lang['mtc_n_blodgett']='n für Bemessungskorngröße nach Blodgett';
$ec_lang['mtc_n_bathurst']='n für Bemessungskorngröße nach Bathurst';
$ec_lang['mtc_n_pi']='n für Bemessungskorngröße nach Phillips & Ingersoll';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett gegenüber Bathurst';
$ec_lang['mtc_pi_range_check']='P&I-Bereichsprüfung';
$ec_lang['mtc_pi_ok']='d50 im P&I-Bereich';
$ec_lang['mtc_pi_ok_tip']='0,28–0,36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='Außerhalb des Bereichs';
$ec_lang['mtc_pi_tip']='Extrapolation außerhalb des Datenbereichs von 0,28–0,36 ft, für den diese Gleichung entwickelt wurde — als grobe Kontrolle, nicht als Bemessungsgrundlage zu verstehen';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Nach Isbash (1936) und Maricopa County, Arizona, USA.">Erforderliche Körnung kantenreicher Steine Sohle, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Nach Isbash (1936) und Maricopa County, Arizona, USA.">Erforderliche Körnung kantenreicher Steine Böschung 1, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Nach Isbash (1936) und Maricopa County, Arizona, USA.">Erforderliche Körnung kantenreicher Steine Böschung 2, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Erforderliche Körnung kantenreicher Steine, D<sub>50</sub> (Maynord, Ruff und Abt 1989)';
$ec_lang['mtc_d50_searcy']='Erforderliche Körnung kantenreicher Steine, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='Geschwindigkeit plausibel für Gleichströmungsannahmen.';
$ec_lang['mtc_vel_low']='Geschwindigkeit niedrig – Sedimentationsrisiko.';
$ec_lang['mtc_vel_high']='Geschwindigkeit ist hoch und möglicherweise nicht realistisch – Erosion der Gerinneauskleidung, zusätzliche Tiefe in Bögen und Energieverlust an Aufweitungen oder Hindernissen prüfen.';
$ec_lang['mtc_iteration_tip']='Wählen Sie eine Rauheitsoption (Blodgett–Bathurst empfohlen) und eine Option für die Korngröße (Isbash empfohlen), um automatisch auf eine gleichmäßige Korngröße für Ihren Zieldurchfluss zu iterieren. Die vollständige Methode finden Sie unten in den Hinweisen, oder geben Sie Ihren eigenen Rauheitswert ein (dem Link für Hinweise folgen) und ignorieren Sie die Korngröße, um die Iteration zu überspringen.';
$ec_lang['mtc_note_1']='<dl><dt>Automatische Iteration Steinbemessung und Rauheit</dt><dd>Wählen Sie eine Rauheitsoption (Blodgett–Bathurst empfohlen) und eine Option für die Bemessungskorngröße (Isbash empfohlen). Stellen Sie Tiefe und Steinbemessungsfaktor ein, um den gewünschten Durchfluss mit einer gleichmäßigen Korngröße zu erzielen. Bei jeder Änderung eines Eingabewerts startet der Iterationszyklus: 1. Die Rauheit wird aus der Bemessungskorngröße berechnet. 2. Der berechnete Rauheitswert wird in die Eingaberauheit kopiert. 3. Kanaldurchfluss und erforderliche Korngröße werden berechnet. 4. Die Bemessungskorngröße wird angepasst. 5. Wiederholen bis der Fehler sehr klein ist.</dd><dt>Grundrechner (ohne Iteration)</dt><dd>Geben Sie den gewünschten Rauheitswert ein. Ignorieren Sie den Eingabebereich für die Bemessungskorngröße.</dd></dl>';
$ec_lang['mtc_note_2_term']='Geschwindigkeitsprüfung';
$ec_lang['mtc_note_2_def']='Hohe Geschwindigkeit impliziert hohe spezifische Energie aus einem verfügbaren Absturz. Diese Energie kann schnell an Aufweitungen, Bögen oder Hindernissen abgebaut werden. Prüfen Sie, ob dies für den Standort plausibel ist.';
$ec_lang['mtc_solver_no_solution']='Für das gegebene Q wurde bei diesen Kanaleingaben keine Lösung gefunden.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Einfaches Wehr';
$ec_lang['ws_main_title']='Kostenloser Online-Rechner für den Durchfluss über ein einfaches breitkroniges Wehr';
$ec_lang['ws_main_desc']='Rechner für den Durchfluss über ein einfaches breitkroniges Wehr';
$ec_lang['ws_weirLength']='Wehrlänge, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="Energie pro Gewichtseinheit des Wassers – eine Höhe der Wassersäule, kein Druck">Überfallhöhe, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='Wehrbeiwert, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Hinweise';
$ec_lang['ws_notes_we_term']='Wehrformel';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Unregelmäßiges Wehr';
$ec_lang['wi_main_title']='Kostenloser Online-Rechner für segmentierte, unregelmäßige Wehre mit veränderlicher Kronenhöhe';
$ec_lang['wi_main_desc']='Rechner für den Durchfluss über ein unregelmäßiges Wehr';
$ec_lang['wi_weirPoints']='Wehrpunkte';
$ec_lang['wi_pondingHeight']='Stauhöhe';
$ec_lang['wi_incrementalFlow']='Teildurchfluss';
$ec_lang['wi_cumulativeFlow']='Kumulierter Durchfluss';
$ec_lang['wi_save_and_calculate']='Speichern und berechnen';
$ec_lang['wi_notes_we_def']='q = wenn (Länge = 0) dann 0, sonst wenn (Gefälle=0) dann cw*Länge*d<sub>0</sub><sup>1.5</sup>, sonst cw/(2.5*Gefälle) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) wobei d<sub>1</sub> und d<sub>0</sub> immer positiv oder null sind';
// Orifice Flow
$ec_lang['or_main_menu']='Ausfluss durch Öffnung';
$ec_lang['or_main_title']='Kostenloser Online-Rechner für den Ausfluss durch Öffnungen';
$ec_lang['or_main_desc']='Ausfluss durch Öffnung — frei oder eingestaut';
$ec_lang['or_shape']='Form der Öffnung';
$ec_lang['or_shape_circular']='Kreisförmig';
$ec_lang['or_shape_rectangular']='Rechteckig';
$ec_lang['or_diameter']='<span class="ec-help" title="Durchmesser bei kreisförmig; Höhe bei rechteckig">Durchmesser oder Höhe, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Nur bei rechteckigen Öffnungen">Breite, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Unterkante der Öffnung">Sohlhöhe <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Oberwasserstand';
$ec_lang['or_twe']='Unterwasserstand';
$ec_lang['or_cd']='Ausflusskoeffizient, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Schwerpunkthöhe';
$ec_lang['or_head']='<span class="ec-help" title="Energie pro Gewichtseinheit des Wassers – eine Höhe der Wassersäule, kein Druck">Wirksame Druckhöhe, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='Öffnungsfläche, A';
$ec_lang['or_regime']='Prüfung des Öffnungsregimes';
$ec_lang['or_regime_valid']='Freier Ausfluss';
$ec_lang['or_regime_submerged']='Eingestaute Öffnung';
$ec_lang['or_regime_submerged_tip']='TWE über dem Schwerpunkt — Öffnungsregime weiterhin gültig';
$ec_lang['or_regime_warn']='Außerhalb des Öffnungsregimes';
$ec_lang['or_regime_warn_tip']='Oberwasser unter dem Scheitel der Öffnung';
$ec_lang['or_regime_twe_above_hwe']='Eingaben prüfen';
$ec_lang['or_regime_twe_above_hwe_tip']='Unterwasserstand (TWE) über Oberwasserstand (HWE)';
$ec_lang['or_notes_1_term']='Ausflussformel';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Bei freiem Ausfluss: h = HWE − Schwerpunkt. Bei eingestautem Ausfluss (TWE über Sohle): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Öffnungsregime';
$ec_lang['or_notes_2_def']='Die Ausflussformeln für Öffnungen gelten, wenn der Oberwasserspiegel über dem Scheitel (der Oberkante) der Öffnung liegt. Liegt der Oberwasserspiegel darunter, ist stattdessen eine Wehrformel zu verwenden.';
$ec_lang['or_notes_3_term']='Ausflusskoeffizient';
$ec_lang['or_notes_3_def']='C<sub>d</sub> liegt bei ca. 0,60–0,65 für scharfkantige Öffnungen. Abgerundete oder einspringende Einläufe haben andere Werte. Siehe <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venturi-d_590.html">Engineering Toolbox</a> oder das HEC-RAS Hydraulic Reference Manual.';
$ec_lang['or_notes_4_term']='Einstau';
$ec_lang['or_notes_4_def']='Wenn TWE über der Sohle der Öffnung liegt, verwendet der Rechner automatisch die Formel für eingestauten Ausfluss mit h = HWE − TWE. Liegt TWE auf oder unter der Sohle, wird freier Ausfluss angenommen und h = HWE − Schwerpunkt.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Mikro-Wasserkraft';
$ec_lang['mhp_main_title']='Kostenloser Online-Rechner für Mikro-Wasserkraft';
$ec_lang['mhp_main_desc']='Leistungsrechner für Laufwasser-Mikro-Wasserkraftanlagen';
$ec_lang['mhp_gross_head']='Bruttofallhöhe, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="Durchmesser der Druckrohrleitung (Zuleitung)">Rohrdurchmesser der Druckrohrleitung, D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='Länge, L';
$ec_lang['mhp_efficiency']='Anlagenwirkungsgrad, η (0–1)';
$ec_lang['mhp_vel_check']='Geschwindigkeitsprüfung';
$ec_lang['mhp_hl_check']='Druckverlustprüfung';
$ec_lang['mhp_hnet']='Nettofallhöhe, H<sub>net</sub>';
$ec_lang['mhp_power']='Leistungsabgabe, P';
$ec_lang['mhp_annual_kwh']='Jahresenergie bei 100 % Kapazität';
$ec_lang['mhp_vel_low']='Geschwindigkeit niedrig – Risiko von Sedimentation und Lufteintrag.';
$ec_lang['mhp_vel_high']='Geschwindigkeit hoch – Übergangsverluste, verfügbare Energie und Druckstoß prüfen.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Hoch';
$ec_lang['mhp_vel_low_short']='Niedrig';
$ec_lang['mhp_vel_ok_tip']='Geschwindigkeit liegt im effizienten Bereich für die Auslegung der Druckrohrleitung.';
$ec_lang['mhp_hl_ok_tip']='Innerhalb des 10-%-Ziels — wirtschaftlich.';
$ec_lang['mhp_hl_warn_tip']='Überschreitet das 10-%-Ziel. Größeres Rohr in Betracht ziehen.';
$ec_lang['mhp_hl_bad_tip']='Überschreitet das 20-%-Ziel. Rohrgröße anpassen.';
$ec_lang['mhp_notes_1_term']='Druckverlust';
$ec_lang['mhp_notes_1_def']='Gesamtverlust der Druckrohrleitung h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, wobei h<sub>f</sub> = f(L/D)(v²/2g) der Darcy-Weisbach-Reibungsverlust ist und h<sub>m</sub> = k<sub>m</sub>·v²/2g Einläufe, Krümmer und Armaturen berücksichtigt. Nettofallhöhe H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Fließgeschwindigkeit';
$ec_lang['mhp_notes_2_def']='Prüfen Sie, ob die Geschwindigkeit für das verfügbare Gefälle und die Rohrkosten angemessen ist. Sehr niedrige Geschwindigkeit kann auf Überdimensionierung hindeuten; sehr hohe Geschwindigkeit kann Reibungsverluste und das Risiko eines Wasserschlags erhöhen.';
$ec_lang['mhp_notes_3_term']='Druckverlustziel';
$ec_lang['mhp_notes_3_def']='Verluste in der Druckrohrleitung unter 10 % der Bruttofallhöhe sind in der Regel wirtschaftlich. Der optimale Kompromiss zwischen Rohrkosten und Leistungsverlust liegt für wertvolle Stromerzeugungs-Standorte oft bei 4–6 %.';
$ec_lang['mhp_notes_6_term']='Wirkungsgrad';
$ec_lang['mhp_notes_6_def']='Der typische Anlagenwirkungsgrad η liegt für Pelton- und Durchströmturbinen, die in der Mikro-Wasserkraft verbreitet sind, zwischen 0,70 und 0,85. Als konservativen Anfangswert 0,75 verwenden.';
$ec_lang['mhp_notes_7_term']='Jahresenergie';
$ec_lang['mhp_notes_7_def']='Die Jahresenergie setzt einen kontinuierlichen Vollbetrieb voraus (8760 Stunden/Jahr). Die tatsächliche Produktion ist aufgrund saisonaler Durchflussschwankungen, Wartungsausfallzeiten und des Lastfaktors geringer.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Teich- & Behälter-Entleerungszeit';
$ec_lang['odt_main_title']='Kostenloser Online-Rechner für die Entleerungszeit von Teich, Becken und Behälter (Öffnung)';
$ec_lang['odt_main_desc']='Entleerungszeit von Teich, Becken oder Behälter — Auslauf durch Öffnung, Kegelvolumenmethode';
$ec_lang['odt_h1_elev']='Anfangswasserspiegelhöhe';
$ec_lang['odt_a1']='Anfangsfläche, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Endwasserspiegelhöhe';
$ec_lang['odt_a0']='Fläche auf Öffnungshöhe, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Interpoliert aus dem Kegelmodell bei der Endhöhe">Endfläche, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Prüfung der Endhöhe';
$ec_lang['odt_h2_ok']='Endhöhe über dem Scheitel der Öffnung';
$ec_lang['odt_h2_warn']='Endhöhe auf oder unter dem Scheitel der Öffnung';
$ec_lang['odt_h2_warn_tip']='Scheitel der Öffnung = Schwerpunkt + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Durchmesser (kreisförmig) oder Höhe (rechteckig)">Öffnung D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Nur rechteckig">Öffnungsbreite, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Entleerungszeit (s)';
$ec_lang['odt_t_min']='Entleerungszeit (min)';
$ec_lang['odt_t_hr']='Entleerungszeit (h)';
$ec_lang['odt_t_day']='Entleerungszeit (Tage)';
$ec_lang['odt_notes_1_term']='Formel';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ergibt die Entleerungszeit von der Druckhöhe H bis zur Öffnung. Entleerungszeit = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), wobei H<sub>1</sub> = Anfangshöhe − Öffnungshöhe, H<sub>2</sub> = Endhöhe − Öffnungshöhe.';
$ec_lang['odt_notes_2_term']='Methode';
$ec_lang['odt_notes_2_def']='Die Kegelvolumenmethode modelliert den Teich oder das Becken als Kegelschnitt zwischen der Anfangsfläche A<sub>1</sub> beim Anfangswasserspiegel und der Fläche A<sub>0</sub> auf der Schwerpunkthöhe der Öffnung. A<sub>2</sub>, die Fläche bei der Endhöhe, wird aus A<sub>1</sub> und A<sub>0</sub> nach dem Kegelmodell interpoliert. Die Entleerungszeit von der Anfangs- bis zur Endhöhe entspricht der gesamten Entleerungszeit von H<sub>1</sub> bis zur Öffnung abzüglich der verbleibenden Entleerungszeit von H<sub>2</sub> bis zur Öffnung.';
$ec_lang['odt_h1']='<span class="ec-help" title="Anfangswasserspiegelhöhe minus Schwerpunkthöhe der Öffnung">Anfangsdruckhöhe, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Maximaler Ausfluss, Q<sub>max</sub>';
$ec_lang['odt_vol']='Entleertes Volumen';
$ec_lang['odt_sketch_start']='Anfang';
$ec_lang['odt_sketch_end']='Ende';
// Contact us.

// Irrigation
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Emitterabstand, S<sub>e</sub>';
$ec_lang['ip_sl']='Lateralabstand, S<sub>l</sub>';
$ec_lang['ip_n_e']='Emitter pro Lateral, n<sub>e</sub>';
$ec_lang['ip_n_l']='Laterale pro Zone, n<sub>l</sub>';
$ec_lang['ip_d']='Ziel-Ausbringungstiefe, d';
$ec_lang['ip_a_e']='Fläche pro Emitter, A<sub>e</sub>';
$ec_lang['ip_pr']='Beregnungsintensität, PR';
$ec_lang['ip_q_lat']='Durchfluss pro Lateral, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Zonendurchfluss, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Laufzeit (Stunden)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Kanalversickerung';
$ec_lang['cs_main_title']='Kostenloser Online-Rechner für Kanalversickerungsverlust und Transportwirkungsgrad';
$ec_lang['cs_main_desc']='Kanalversickerungsverlust & Transportwirkungsgrad — Zu-/Abfluss-Methode';
$ec_lang['cs_Q_in']='Zufluss, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Abfluss, Q<sub>out</sub>';
$ec_lang['cs_L']='Haltungslänge, L';
$ec_lang['cs_Q_loss']='Versickerungsverlustrate, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Messungskontrolle';
$ec_lang['cs_pct_loss']='Verlorener Anteil';
$ec_lang['cs_Ec']='Transportwirkungsgrad, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Wirkungsgradbewertung';
$ec_lang['cs_Vol_day']='Täglich verlorenes Volumen';
$ec_lang['cs_Vol_year']='Jährlich verlorenes Volumen';
$ec_lang['cs_Q_loss_per_L']='Verlust je Längeneinheit, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Wasserwert';
$ec_lang['cs_lining_cost']='Auskleidungskosten';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Ziel-Transportwirkungsgrad nach Auskleidung; Anteil 0–1">Auskleidungsziel, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Auskleidungsfläche, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Jährlich verlorener Wert';
$ec_lang['cs_annual_value_recovered']='Jährlich zurückgewonnener Wert';
$ec_lang['cs_lining_total_cost']='Gesamte Auskleidungskosten';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Einfache Amortisation = gesamte Auskleidungskosten ÷ jährlich zurückgewonnener Wert">Amortisationszeit <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — Versickerung festgestellt';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — kein messbarer Verlust';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — Messungen prüfen';
$ec_lang['cs_Ec_good']='Gut — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Mittel — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Schlecht — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='Die Zu-/Abfluss-Methode schätzt die Versickerung, indem der Durchfluss am Anfang und Ende einer Kanalhaltung gemessen wird: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Der Transportwirkungsgrad E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Das Jahresvolumen setzt einen durchgehenden Vollbetrieb voraus; der tatsächliche Verlust ist bei saisonalen oder teilweise betriebenen Kanälen geringer.';
$ec_lang['cs_notes_2_term']='Wirkungsgradbewertungen';
$ec_lang['cs_notes_2_def']='Typische unbefestigte Erdkanäle: E<sub>c</sub> = 60–80 %. Gut unterhaltene Erdkanäle: 75–85 %. Betonausgekleidete Kanäle: 90–98 %. Versickerungsverluste über 30 % des Zuflusses rechtfertigen häufig eine Investition in die Auskleidung. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Amortisation der Auskleidung';
$ec_lang['cs_notes_3_def']='Geben Sie Wasserwert und Auskleidungskosten in einer beliebigen, aber einheitlichen Währung ein. Auskleidungsfläche = Haltungslänge × benetzter Umfang — der benetzte Umfang des Kanalquerschnitts bei der gemessenen Fließtiefe (Sohlbreite plus beide benetzten Böschungen). Der jährlich zurückgewonnene Wert setzt voraus, dass der ausgekleidete Kanal den Ziel-E<sub>c</sub> dauerhaft erreicht. Die tatsächliche Amortisationszeit ist bei saisonalen Kanälen oder wenn die Auskleidung die Zieleffizienz nicht erreicht, länger.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3. Aufl. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='Über';
$ec_lang['install_main_menu']='Installieren';
$ec_lang['install_main_title']='EngCalcs installieren';
$ec_lang['install_main_desc']='Zum Gerät hinzufügen für Offline-Nutzung';
$ec_lang['install_intro']='EngCalcs ist eine Progressive Web App (PWA). Nach der Installation funktionieren alle Rechner vollständig offline — keine Internetverbindung nötig.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Öffnen Sie eine beliebige Rechnerseite in Chrome.</li><li>Tippen Sie oben in der Navigationsleiste auf die Schaltfläche <strong>⬇ Installieren</strong>, oder öffnen Sie das Browsermenü (⋮) und wählen Sie <strong>Zum Startbildschirm hinzufügen</strong>.</li><li>Tippen Sie in der angezeigten Aufforderung auf <strong>Installieren</strong>.</li><li>EngCalcs erscheint auf Ihrem Startbildschirm und funktioniert offline.</li>';
$ec_lang['install_now_btn']='⬇ Jetzt installieren';
$ec_lang['install_prompt_unavailable']='Installationsaufforderung nicht verfügbar — nutzen Sie stattdessen Ihr Browsermenü.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Öffnen Sie eine beliebige Rechnerseite in Safari.</li><li>Tippen Sie auf die Schaltfläche <strong>Teilen</strong> (Kästchen mit nach oben zeigendem Pfeil).</li><li>Scrollen Sie nach unten und tippen Sie auf <strong>Zum Home-Bildschirm</strong>.</li><li>Tippen Sie auf <strong>Hinzufügen</strong>. EngCalcs erscheint auf Ihrem Startbildschirm.</li>';
$ec_lang['install_ios_note']='Unter iOS erfolgt die Installation immer über das Teilen-Menü — es gibt keine automatische Installationsaufforderung.';
$ec_lang['install_desktop_heading']='Desktop (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Öffnen Sie eine beliebige Rechnerseite.</li><li>Klicken Sie auf das <strong>Installationssymbol</strong> (⊕ oder Computersymbol) in der Adressleiste des Browsers, oder öffnen Sie das Browsermenü und wählen Sie <strong>EngCalcs installieren…</strong></li><li>Klicken Sie auf <strong>Installieren</strong>. EngCalcs öffnet sich als eigenständiges App-Fenster.</li>';
$ec_lang['install_firefox_heading']='Firefox / Andere Browser';
$ec_lang['install_firefox_body']='Firefox unterstützt die Installation von PWAs auf dem Desktop nicht. Sie können weiterhin alle Rechner normal im Browser nutzen — nach Ihrem ersten Besuch werden die Seiten automatisch für die Offline-Nutzung zwischengespeichert.';
$ec_lang['install_cached_heading']='Was zwischengespeichert wird';
$ec_lang['install_cached_body']='Beim ersten Installieren von EngCalcs werden alle Rechnerseiten und ihre zugehörigen Dateien (Skripte, Stile) automatisch auf Ihrem Gerät gespeichert. Danach funktioniert alles ohne Internetverbindung. Ihre Sprachauswahl wird von Ihrem letzten Online-Besuch übernommen.';
$ec_lang['contact_main_menu']='Kontakt';
$ec_lang['about_main_title']='Über die HawsEDC-Ingenieurrechner';
$ec_lang['about_main_desc']='Mission, Freie Software und Mitwirken';
$ec_lang['about_body_html']='<h3>Mission</h3><p>Die HawsEDC-Ingenieurrechner dienen Ingenieuren und Feldarbeitern auf der ganzen Welt — insbesondere solchen, die in wasserarmen, ressourcenarmen oder unterversorgten Regionen arbeiten. Diese Werkzeuge sind Teil einer breiteren humanitären Mission: jedem Menschen auf die praktischste und wirkungsvollste Weise zu sagen, dass er für immer geliebt und geschätzt wird, dass er nichts zu befürchten hat und dass er nicht alles zunichte machen wird.</p><p>Die Rechner sind das Mittel. Das Ziel ist eine Welt frei von Leid.</p><h3>Freie-Libre-Open-Source-Lizenz</h3><p>Aller Code wird unter der <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 oder später</a> veröffentlicht — frei wie in Freiheit. Sie dürfen den Code unter denselben Bedingungen nutzen, studieren, ändern und weitergeben.</p><p>Dies ist eine Einladung, kein Preis. Es gibt keine kostenpflichtige Stufe, keine kostenlose Stufe, die widerrufen werden kann, und keine Wartezeit, bevor der Code Ihnen gehört. Die vollständige Version, die Sie heute sehen, ist für jeden, jetzt und für immer, frei nutzbar und veränderbar.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Quellcode</h3><p>Der vollständige Quellcode ist öffentlich auf GitHub verfügbar:</p><p><a target="_blank" href="https://github.com/hawstom/engcalcs">github.com/hawstom/engcalcs</a></p><p>Sie können dort den Code durchsuchen, Probleme melden oder das Repository forken.</p><h3>Mitwirken</h3><p>Jede Hilfe ist willkommen. <a href="contact.php">Tom Haws kontaktieren</a>.</p><ul><li><strong>Übersetzungen:</strong> Schlagen Sie eine bessere Formulierung vor. Verbessern oder ergänzen Sie eine Sprache.</li><li><strong>Fehlerberichte:</strong> Nutzen Sie das Feedback-Formular auf einer beliebigen Rechnerseite oder melden Sie ein Problem auf GitHub.</li><li><strong>Neue Rechner:</strong> Ideen für hydraulisch-ingenieurtechnische Werkzeuge, die Feldarbeitern und Bewässerungspraktikern dienen, sind besonders willkommen.</li><li><strong>Hosting:</strong> Wenn Sie diese Rechner für eine Region mit eingeschränkter Konnektivität spiegeln können, nehmen Sie bitte Kontakt auf.</li></ul><h3>Offline-Nutzung</h3><p>Diese Rechner funktionieren als <strong>Progressive Web App (PWA)</strong>. Besuchen Sie eine beliebige Rechnerseite bei bestehender Internetverbindung, und Ihr Browser speichert alle Rechner automatisch im Cache. Danach funktionieren alle Rechner offline — kein Internet erforderlich.</p><p>Verwenden Sie auf Android oder iOS die Option „Zum Startbildschirm hinzufügen" Ihres Browsers, um EngCalcs als App auf Ihrem Gerät zu installieren. Auf dem Desktop suchen Sie nach dem Installationssymbol in der Adressleiste Ihres Browsers.</p><p>Sie können auch jeden einzelnen Rechner über das Menü „Speichern unter…" Ihres Browsers für die einmalige Offline-Nutzung speichern.</p><h3>Kontakt</h3><p>Tom Haws, Wasserbauingenieur und Gründer dieser Rechner.<br />Nutzen Sie das Feedback-Formular auf einer beliebigen Rechnerseite oder greifen Sie auf den Quellcode unter <a target="_blank" href="https://github.com/hawstom/engcalcs">GitHub</a> zu.</p>';
$ec_lang['contact_title']='HawsEDC Kontakt';
$ec_lang['contactSendMessage']='Senden Sie Tom Haws eine Nachricht';
$ec_lang['contactYourName']='Ihr Name:';
$ec_lang['contactYourEmail']='Ihre E-Mail-Adresse:';
$ec_lang['contactSubject']='Betreff:';
$ec_lang['contact_message']='Nachricht:';
$ec_lang['contactSpamPrefix']='Fünf plus eins ergibt';
$ec_lang['contactSpamPostfix']='(Bitte auf Englisch ausschreiben. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Nachricht senden';
$ec_lang['contact_success']='Danke, dass Sie sich die Zeit genommen haben zu schreiben.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Steingerinne-Bemessung (Robinson)';
$ec_lang['rc_main_title']='Kostenloser Online-Rechner für Steingerinne-Bemessung — Robinson (1998)';
$ec_lang['rc_main_desc']='Steingerinne Bruchsteinbemessung — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Gerinnegefälle, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="Abfluss je Breiteneinheit am Gerinneeinlauf. Bei einem Gerinne mit Sohlbreite B und Gesamtabfluss Q gilt q_t = Q / B.">Gesamtspezifischer Abfluss, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='Bruchsteinporosität, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="Dichte relativ zu Wasser. Typisch für gebrochenen Granit oder Basalt ≈ 2,65. Gültiger Robinson-Bereich: 2,54 bis 2,82.">Relative Dichte des Gesteins, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="Standardabweichung der Kornverteilung. Gleichförmiges Gestein ≈ 1,25. Gültiger Robinson-Bereich: 1,15 bis 1,47.">Kornverteilung SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="Einstau (Hp > yn) ist günstig — vermindert Erosion oberstrom. (USDA)">Normaltiefe im Zulaufgerinne, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="Gl. 1 (S0 < 0,10) oder Gl. 2 (0,10–0,40). Gültig: D50 15–278 mm, S0 0,02–0,40. Außerhalb des Bereichs: extrapoliert.">Erforderlicher medianer Steindurchmesser, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='Angewandte Gleichung';
$ec_lang['rc_sg_check']='Prüfung relative Dichte';
$ec_lang['rc_SD_check']='Prüfung Kornverteilung SD';
$ec_lang['rc_sg_ok']   ='sg im gültigen Bereich (2,54–2,82)';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg < 2,54 — unterhalb des Robinson-Bereichs';
$ec_lang['rc_sg_low_tip']='Gültiger Bereich: 2,54–2,82';
$ec_lang['rc_sg_high'] ='sg > 2,82 — oberhalb des Robinson-Bereichs';
$ec_lang['rc_sg_high_tip']='Gültiger Bereich: 2,54–2,82';
$ec_lang['rc_SD_ok']   ='SD im gültigen Bereich (1,15–1,47)';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD < 1,15 — unterhalb des Robinson-Bereichs';
$ec_lang['rc_SD_low_tip']='Gültiger Bereich: 1,15–1,47';
$ec_lang['rc_SD_high'] ='SD > 1,47 — oberhalb des Robinson-Bereichs';
$ec_lang['rc_SD_high_tip']='Gültiger Bereich: 1,15–1,47';
$ec_lang['rc_layer']='Steinlagenstärke (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Krümmungsradius Oberkante (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Bogenlänge Oberkante';
$ec_lang['rc_apron_length']='<span class="ec-help" title="Erforderlich zur Lagestabilisierung des Bruchsteins. “Der minimale Unterwasserstand, der durch den Auslaufbereich und den Widerstand des Unterliegergerinnes entsteht, ist ausreichend, um die Stabilität des Bruchsteins im Auslaufbereich zu gewährleisten.” (Robinson)">Vorschüttstrecke Auslauf (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='Manning-Rauheit im Gerinne, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="Anteil von qt, der durch die Steinporen fließt. Der Rest qs fließt über die Oberfläche. Standard np = 0,45 für gebrochenes Kantgestein.">Fließgeschwindigkeit durch Steinmatte, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='Spezifischer Durchfluss durch Steinmatte, q<sub>m</sub>';
$ec_lang['rc_qs']='Oberflächenspezifischer Abfluss, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Fließtiefe über Bruchsteinoberfläche, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="Einstau (Hp > yn) ist günstig — vermindert Erosion oberstrom. (USDA)">Einlaufstauhöhe, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='Einstauprüfung am Einlauf';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — Einstau oberstrom';
$ec_lang['rc_pond_ok_tip']='Einstau oberstrom des Gerinneeinlaufs ist günstig; er vermindert die Erosion oberstrom. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — kein Einstau — Erosionspotenzial am Einlauf';
$ec_lang['rc_pond_warn_tip']='Kein Einstau oberstrom des Gerinneeinlaufs; es kann zu Erosion oberstrom kommen. (USDA)';
$ec_lang['rc_eq1']='Gl. 1 (S<sub>0</sub> < 0,10) — flaches Gefälle';
$ec_lang['rc_eq2']='Gl. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — steiles Gefälle';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — unterhalb des Robinson-Gültigkeitsbereichs';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — oberhalb des Robinson-Gültigkeitsbereichs';
$ec_lang['rc_notes_1_term']='Steinbemessungsgleichungen';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) entwickelten zwei empirische Gleichungen für den medianen Bruchsteindurchmesser D<sub>50</sub> in Abhängigkeit von Gefälle und spezifischem Abfluss. Gleichung 1 gilt für flache Gefälle (S<sub>0</sub> < 0,10); Gleichung 2 gilt für steile Gefälle (0,10 ≤ S<sub>0</sub> ≤ 0,40). Beide Gleichungen erfordern q<sub>t</sub> in m²/s und liefern D<sub>50</sub> in mm. Der validierte Bereich ist 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Spezifischer Abfluss';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> ist der gesamte spezifische Abfluss an der Gerinneoberkante (Gesamtabfluss je Breiteneinheit). Für ein Gerinne mit Sohlbreite B und Gesamtabfluss Q gilt näherungsweise q<sub>t</sub> ≈ Q / B, oder es wird aus der Grenztiefenbedingung am Gerinneeinlauf berechnet.';
$ec_lang['rc_notes_3_term']='Durchfluss durch die Steinmatte';
$ec_lang['rc_notes_3_def']='Ein Teil des Gesamtabflusses fließt durch die Poren des Bruchsteins (Mattendurchfluss q<sub>m</sub>); der Rest fließt über die Steinoberfläche (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Die Fließtiefe d wird aus der Manning-Gleichung für den Oberflächenabfluss q<sub>s</sub> mit der Gerinnerauheit n berechnet. Die Standardporosität n<sub>p</sub> = 0,45 ist typisch für gebrochenes Kantgestein.';
$ec_lang['rc_notes_5_term']='Gültiger Steindurchmesserbereich';
$ec_lang['rc_notes_5_def']='Die Gleichungen wurden für einen D<sub>50</sub>-Bereich von 15 mm bis 278 mm entwickelt. Ergebnisse außerhalb dieses Bereichs sind extrapoliert und sollten mit zusätzlichem ingenieurmäßigem Urteilsvermögen verwendet werden.';
$ec_lang['rc_notes_6_term']='Höhenlage Auslaufvorschüttung';
$ec_lang['rc_notes_6_def']='Die Oberkante des Bruchsteins im Auslaufbereich sollte auf oder unter der Sohlhöhe des Unterliegergerinnes liegen. Liegt sie höher, ist der Auslaufstein instabil.';
$ec_lang['rc_notes_7_def']='Wenn die Normaltiefe im Zulaufgerinne kleiner ist als die erforderliche Wehrstauhöhe (H<sub>p</sub>) für den Abfluss q<sub>t</sub>, kommt es oberstrom der Einlaufschüttung zu eingeschränktem Abfluss oder Einstau. Dies ist grundsätzlich akzeptabel — Einstau vermindert die Fließgeschwindigkeit und verhindert Erosion oberstrom. Zur Prüfung: mit einem Wehrrechner H<sub>p</sub> für das gegebene q<sub>t</sub> und die Breite berechnen und mit der Normaltiefe im Zulaufgerinne vergleichen. Übersteigt H<sub>p</sub> die Normaltiefe, tritt Einstau auf.';
$ec_lang['rc_notes_4_term']='Literatur';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., und Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. Der USDA ARS veröffentlicht auch ein <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel-Arbeitsblatt</a> auf Basis derselben Methode.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filter';
$ec_lang['rc_sketch_top_crest_curve'] = 'Oberkantenkurve';
$ec_lang['rc_sketch_outlet_apron']    = 'Auslaufvorschüttung';
$ec_lang['rc_sketch_radius']          = 'Radius';
// Irrigation Pressure Calculator (branch pipe-network pressure/DU estimate). Prefix ip_.
$ec_lang['ip_main_menu']='Bewässerungsdruck';
$ec_lang['ip_main_title']='Kostenloser Online-Rechner für Bewässerungsdruck und Verteilungsgleichmäßigkeit';
$ec_lang['ip_main_desc']='Testzweig-Druck und Gleichmäßigkeitsschätzung';
$ec_lang['ip_h_supply']='Versorgungsdruck';
$ec_lang['ip_elev_supply']='Versorgungshöhe, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Emitter-Bemessungsdurchfluss, q<sub>design</sub>';
$ec_lang['ip_h_design']='Emitter-Bemessungsdruck';
$ec_lang['ip_x']='<span class="ec-help" title="0,5 für Standard-Emitter ohne Druckausgleich; nahe 0 für druckkompensierte Emitter">Emitter-Abflussexponent, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Testpfad';
$ec_lang['ip_group_reach']='Strecke';
$ec_lang['ip_group_upstream']='Oberstrom';
$ec_lang['ip_group_downstream']='Unterstrom';
$ec_lang['ip_group_loss']='Verlust';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="Aktiviert: Diese Strecke ist ein Segment der Testleitung (Lateral), aus der einzelne Emitter Wasser entnehmen. Nicht aktiviert: Diese Strecke ist eine Hauptleitung, die den Durchfluss nur an Laterale weiterleitet, die nicht auf dem Testpfad liegen.">Lat. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Lateral-Zeilen: nur die Emitter in dieser Strecke. Hauptleitungs-Zeilen: Gesamtzahl der Emitter auf Lateralen AUSSER diesem, die von dieser Strecke abzweigen. Für die Strecke der Hauptleitung, die an der Testleitung endet, zählen zusätzlich alle Laterale, die weiter entlang der Hauptleitung liegen, oder die denselben Knotenpunkt teilen (z. B. ein gegenüberliegendes Lateral) — ihr Durchfluss zweigt ebenfalls von dieser Strecke ab.">Emitter <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Höhe am unterstromigen Ende dieser Strecke. Optional bei inneren Zeilen (Standard: eben / gleich wie der Knoten darüber, falls leer gelassen). Erforderlich in der letzten Zeile: dieser Wert ist die Höhe des letzten Emitters, der direkt den erforderlichen Versorgungsdruck bestimmt.">US Höhe <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='Höhe des letzten Emitters (letzte Zeile) wurde leer gelassen und standardmäßig auf eben gesetzt — für ein genaues Ergebnis bitte eingeben';
$ec_lang['ip_flow']='Durchfluss';
$ec_lang['ip_press']='Druck';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Gesamter Streckenverlust, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Niedriger/negativer Druck — auf subatmosphärische Bedingungen prüfen';
$ec_lang['ip_pressure_warn_short']='Niedrig';
$ec_lang['ip_pressure_high']='Hoher Druck — Druckminderung erforderlich';
$ec_lang['ip_pressure_high_short']='Hoch';
$ec_lang['ip_max_head']='Max. zul. Druck';
$ec_lang['ip_max_head_tip']='Leitungen, deren Druck diesen Wert überschreitet, werden markiert. Leer lassen, um die Prüfung auf zu hohen Druck zu überspringen.';
$ec_lang['ip_h_far']='Druck am letzten Emitter';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Durchfluss, der nur in den modellierten Testpfad eintritt — für die gesamte Zone/das System siehe Q_zone unter Anwendungsauslegung weiter unten.">Versorgungsdurchfluss des Testpfads, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Durchfluss des letzten Emitters, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Durchschnittlicher Emitter-Durchfluss (Testleitung), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Wie viel höher (oder niedriger) Sie schätzen, dass eine typische Leitung im Vergleich zu dieser Testleitung arbeitet. Die Testleitung ist bewusst der angenommene schlechteste Fall, daher unterschätzt ihr eigener Durchschnitt den Feld-Durchschnitt — bei 0 belassen, verwenden die Gleichmäßigkeitsprüfung und die Zahlen zur Anwendungsauslegung unten den eigenen (wahrscheinlich optimistischen) Durchschnitt der Testleitung unverändert.">Geschätzte Δ-Druckdifferenz, Durchschn. gegenüber Testleitung <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral neu bewertet bei jeder Lateral-Zeile mit deren Druck plus der oben eingegebenen Druckdifferenz — ein Versuch, dafür zu korrigieren, dass die Testleitung der angenommene schlechteste Fall ist und nicht repräsentativ. Fließt sowohl in die Gleichmäßigkeitsprüfung als auch in den Abschnitt Anwendungsauslegung weiter unten ein.">Geschätzter Feld-Durchschnitt Emitter-Durchfluss, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Der berechnete Durchfluss des letzten Emitters geteilt durch den geschätzten Feld-Durchschnitt des Emitter-Durchflusses — dies ist eine Annäherung an die standardmäßige Verteilungsgleichmäßigkeit des unteren Viertels (Durchschnitt der unteren Gruppe ÷ Populationsmittelwert); sie stammt jedoch aus einer klein modellierten Stichprobe und einer vom Benutzer geschätzten Korrektur statt aus einer vollständigen statistischen Feldstichprobe. Werte bei oder über 1 sind möglich und gültig: Sie bedeuten nur, dass der Druck des letzten Emitters bei oder über dem geschätzten Feld-Durchschnitt liegt, sodass ein anderer Emitter der Punkt mit dem niedrigsten Druck ist. Dies kann daran liegen, dass der letzte Emitter auf tiefer gelegenem Gelände liegt, oder daran, dass die Δ-Druck-Schätzung zu klein ist.">Gleichmäßigkeitsprüfung, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='Der Druck am Testemitter ist ≥ Versorgungsdruck. Dies ist wahrscheinlich nicht der Emitter mit dem schlechtesten Fall, oder die Rohre könnten kleiner dimensioniert werden.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Dies unterscheidet sich von unserer Annäherung an das standardmäßige Gleichmäßigkeitsmaß.">Durchfluss des letzten Emitters ÷ Bemessungsdurchfluss, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Keine Lösung: Der erforderliche Versorgungsdruck übersteigt den eingegebenen Versorgungsdruck. Erhöhen Sie den Versorgungsdruck, verringern Sie den Bedarf, oder verwenden Sie ein größeres Rohr.';
$ec_lang['ip_notes_1_def']='Schätzt den Druck am letzten (entferntesten) Emitter und führt dann die Energielinie Strecke für Strecke zurück zur Versorgung, wobei Reibungs- und örtliche (Einzel-)Verluste addiert werden. Höhe und Geschwindigkeitshöhe werden an jedem Knoten abgezogen, um dort den tatsächlichen Druck auszugeben. Der geschätzte Druck am Fernende wird (per Bisektion) so lange angepasst, bis der berechnete erforderliche Versorgungsdruck mit dem eingegebenen Versorgungsdruck übereinstimmt — dasselbe geschlossene Problem, das auch der Rohrdurchfluss-Löser im Rechner Manning-Rohrdurchfluss löst, hier erweitert auf ein verzweigtes Netz.';
$ec_lang['ip_notes_2_term']='Hauptleitungs- und Lateralstrecken';
$ec_lang['ip_notes_2_def']='Jede Zeile ist eine Strecke entlang des einzigen hydraulisch schlechtesten Pfades (des Testpfads) von der Versorgung zum letzten Emitter. Eine Hauptleitungsstrecke leitet den Durchfluss nur an Laterale weiter, die nicht auf dem Testpfad liegen, daher ist ihre Entnahme eine einfache Multiplikation (Bemessungsdurchfluss × Gesamtzahl der Emitter dieser Strecke) — ohne lokale Druckabhängigkeit. Die Hauptleitung ist ein gemeinsames Stammrohr, daher muss die Strecke der Hauptleitung, die an der Testleitung endet, nicht nur die Laterale zwischen ihren eigenen Endpunkten einschließen, sondern auch alle Laterale, die noch weiter unten an der Hauptleitung liegen, oder die denselben Knotenpunkt teilen (z. B. ein gegenüberliegendes Lateral) — deren Durchfluss verläuft durch dieselbe Strecke, bevor er abzweigt, unabhängig davon, ob sie sonst irgendwo in dieser Tabelle auftauchen. Eine Lateralstrecke ist ein Segment der Testleitung selbst: Die Emitterabgabe wird aus dem tatsächlichen lokalen Druck über q = k·H<sup>x</sup> berechnet, und der Reibungsverlust wird durch Christiansens F(n)-Faktor verringert, um die Abnahme des Durchflusses zu berücksichtigen, da jeder Emitter in der Strecke Wasser entnimmt.';
$ec_lang['ip_notes_3_term']='Einschränkungen';
$ec_lang['ip_notes_3_def']='Modelliert einen festen Versorgungsdruck (keine Pumpenkennlinie), nur einen Testpfad (nicht das gesamte Feld) und eine Emitterkurve mit 2 Parametern (setzen Sie den Exponenten nahe 0, um einen druckkompensierten Emitter anzunähern). Es werden zwei unterschiedliche Gleichmäßigkeitsverhältnisse ausgegeben, die bewusst getrennt gehalten werden: q<sub>last</sub>/q<sub>avg,field</sub> ist eine Annäherung an die standardmäßige Verteilungsgleichmäßigkeit des unteren Viertels (Durchschnitt der unteren Gruppe ÷ Populationsmittelwert); dies stammt jedoch aus einer klein modellierten Stichprobe und einer vom Benutzer geschätzten Korrektur anstelle der vollständigen statistischen Feldstichprobe. Außerdem ist die Testleitung bewusst der angenommene schlechteste Fall, sodass ihr roher, unkorrigierter Durchschnitt den wahren Feld-Durchschnitt unterschätzen und die Gleichmäßigkeit besser erscheinen lassen würde, als sie ist; die Δ-Druck-Eingabe existiert eigens, um diese Verzerrung auszugleichen. Werte für die Gleichmäßigkeit bei oder über 1 sind weiterhin möglich: Sie bedeuten nur, dass der Druck des letzten Emitters bei oder über dem geschätzten Feld-Durchschnitt liegt, sodass ein anderer Emitter der Punkt mit dem niedrigsten Druck ist. Dies kann daran liegen, dass der letzte Emitter auf tiefer gelegenem Gelände liegt, oder daran, dass die Δ-Druck-Schätzung zu klein ist. q<sub>last</sub>/q<sub>design</sub> ist eine andere, nicht auf Gleichmäßigkeit bezogene Prüfung gegen den vom Hersteller angegebenen Nenndurchfluss — nützlich, um ein insgesamt über- oder unterdruckbeaufschlagtes System zu erkennen, aber es ist eine separate Prüfung, die zusammen mit dem Gleichmäßigkeitswert zu lesen ist, da der Bemessungs-/Nenndurchfluss unabhängig vom tatsächlichen mittleren Betriebsdruck des Systems ist.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). „Irrigation by sprinkling." California Agricultural Experiment Station Bulletin 670. Die ASAE/ASABE-Normen für die Mikrobewässerungsauslegung verwenden denselben Mehrfachauslass-Reibungsverlust-Ansatz.';
$ec_lang['ip_notes_5_term']='Anwendungsauslegung';
$ec_lang['ip_notes_5_def']='Beregnungsintensität und System-/Zonendurchfluss verwenden den geschätzten Feld-Durchschnitt des Emitter-Durchflusses (q<sub>avg,field</sub> — der eigene Durchschnitt der Testleitung, korrigiert durch die eingegebene Δ-Druck-Schätzung), nicht eine geschätzte Rate: PR = q<sub>avg,field</sub> / A<sub>e</sub>, gespeist vom korrigierten modellierten Wert. Abstand sowie systemweite Lateral-/Emitterzahlen sind hier separate Eingaben, da der Testpfad nur einen Zweig mit dem schlechtesten Fall modelliert, nicht jedes Lateral im Feld.';



// --- Branched Pipe Network (bpn_) --- English source ---
$ec_lang['bpn_main_menu']='Verzweigtes Rohrnetz';
$ec_lang['bpn_main_title']='Kostenloser Online-Druckrechner für verzweigte Rohrnetze (ohne Ringschluss)';
$ec_lang['bpn_main_desc']='Durchfluss und Druck im verzweigten Rohrnetz (Baumstruktur)';
$ec_lang['lpn_main_menu']='Vermaschtes Rohrnetz (Kartenoberfläche)';
$ec_lang['lpn_main_title']='Kostenloser Online-Rechner für vermaschte Rohrnetze mit Kartenoberfläche';
$ec_lang['lpn_main_desc']='Druck und Durchfluss im vermaschten Rohrnetz, das Sie auf einer Karte zeichnen';
$ec_lang['bpn_h_source_tip']='Statische Versorgungshöhe: die Quellhöhe bei Durchfluss null. Ein Wasserspiegel in Reservoir oder Tank über der Versorgungshöhe, oder die Nullförderhöhe einer Pumpe. Punkte 2 und 3 hinzufügen, um eine Pumpen- oder veränderliche Versorgungskennlinie festzulegen; das Werkzeug liest die Höhe beim Bemessungsdurchfluss ab.';
$ec_lang['bpn_elev_source']='Versorgungshöhe';
$ec_lang['bpn_q_total']='Gesamtdurchfluss';
$ec_lang['bpn_q_total_tip']='Gesamtdurchfluss, der die Quelle verlässt (Summe aller Entnahmen im Netz).';
$ec_lang['bpn_p_min']='Niedrigster Druck';
$ec_lang['bpn_p_min_tip']='Der niedrigste unterstromige Druck im gesamten Netz; der kritische Übergabepunkt.';
$ec_lang['bpn_method']='Reibungsmethode';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='Rohrleitungen';
$ec_lang['bpn_id']='ID';
$ec_lang['bpn_id_tip']='Name dieser Rohrleitung. Andere Leitungen verweisen in der Spalte Oberstrom-ID darauf.';
$ec_lang['bpn_upstream']='Oberstrom-ID';
$ec_lang['bpn_upstream_tip']='ID der Leitung, die diese speist. Leer lassen, um der unmittelbar darüberliegenden Leitung zu folgen (einfache Reihenleitung). Hier eine ID eingeben, um von einer anderen Leitung abzuzweigen.';
$ec_lang['bpn_roughness_tip']='Rohrrauheit für die gewählte Reibungsmethode: Manning n, Hazen-Williams C oder Darcy-Weisbach-Rauheitshöhe e (eine Länge). Typisches glattes Kunststoffrohr: n etwa 0,009, C etwa 150, e etwa 0,0015 mm.';
$ec_lang['bpn_demand']='Entnahme';
$ec_lang['bpn_demand_tip']='Fester Durchfluss, der am unterstromigen Ende dieser Leitung entnommen wird. Leer lassen bei einer Leitung, die den Durchfluss nur weiterleitet.';
$ec_lang['bpn_demand_mult']='Entnahmefaktor';
$ec_lang['bpn_demand_mult_tip']='Skaliert die Entnahme aller Leitungen gleichzeitig — etwa für eine Spitzenstunden- oder Zukunftsprognose. Für die eingegebenen Entnahmewerte 1 verwenden.';
$ec_lang['bpn_elev_down']='US-Höhe';
$ec_lang['bpn_q_line']='Leitungsdurchfluss';
$ec_lang['bpn_q_line_tip']='Gesamtdurchfluss, den diese Leitung führt: ihre eigene Entnahme plus jede unterstromige Entnahme, die sie versorgt.';
$ec_lang['bpn_p_down']='US-Druck';
$ec_lang['bpn_p_down_tip']='Druckhöhe (Überdruck) am unterstromigen Knoten dieser Leitung. Ein negativer Wert (markiert) bedeutet Unterdruck (unter Atmosphärendruck); Bemessung prüfen.';
$ec_lang['bpn_sketch_title']='Netzdiagramm';
$ec_lang['bpn_show_length']='Länge';
$ec_lang['bpn_show_diameter']='Durchmesser';
$ec_lang['bpn_show_q']='Durchfluss';
$ec_lang['bpn_show_p']='Druck';
$ec_lang['bpn_source_label']='Quelle';
$ec_lang['bpn_topology_warn']='Spalte Oberstrom-ID prüfen: Eine Leitung verweist auf eine unbekannte ID, auf sich selbst, oder bildet einen Ringschluss, sodass ein Teil des Netzes nicht mit der Quelle verbunden ist. Diese Leitungen bleiben ungelöst.';
$ec_lang['bpn_topology_warn_short']='Netz';
$ec_lang['bpn_pressure_warn']='Niedriger/negativer Druck; auf Unterdruck (unter Atmosphärendruck) prüfen';
$ec_lang['bpn_pressure_warn_short']='Niedrig';
$ec_lang['bpn_notes_1_term']='Standardmäßig in Reihe, verzweigt nur bei Bedarf';
$ec_lang['bpn_notes_1_def']='Oberstrom-ID leer lassen, und eine Leitung folgt der darüberliegenden; eine einfache Reihenleitung. Die ID einer Oberstromleitung eingeben, um von ihr abzuzweigen. Also: standardmäßig in Reihe, ein Baum, wenn er gebraucht wird.';
$ec_lang['bpn_notes_2_term']='Nur verzweigte Netze, keine Ringschlüsse';
$ec_lang['bpn_notes_2_def']='Jede Leitung hat genau eine Oberstromleitung (ein Baum). Dieses Werkzeug löst keine vermaschten (Ring-)Netze; dafür sind iterative Methoden nötig (EPANET oder ähnlich). Der Verzicht auf Ringschlüsse hält es einfach und exakt.';
$ec_lang['bpn_notes_3_term']='Keine aktiven Druckregler';
$ec_lang['bpn_notes_3_def']='Ein fester Einzelverlust-Ventilbeiwert (ein k-Wert) kann hinzugefügt werden, aber keine Druckminder- oder Druckhalteventile (PRV/PSV). Deren Öffnungs-/Schließzustand hängt von Durchfluss und Druck ab, was Iteration erzwingen würde.';
$ec_lang['bpn_supply2_q']='Versorgungsdurchfluss 2';
$ec_lang['bpn_supply2_h']='Versorgungshöhe 2';
$ec_lang['bpn_supply3_q']='Versorgungsdurchfluss 3';
$ec_lang['bpn_supply3_h']='Versorgungshöhe 3';
$ec_lang['bpn_supply_pt_tip']='Optionale Punkte 2 und 3 der Versorgungskennlinie. Für jeden einen Durchfluss und eine Höhe eingeben, um eine Pumpe oder jede Quelle abzubilden, deren Höhe mit steigender Abgabe sinkt; das Werkzeug liest die Höhe beim Bemessungsdurchfluss ab. Punkt 1 oben ist die statische Höhe bei Durchfluss null. 2 und 3 für eine konstante Reservoirhöhe leer lassen.';
$ec_lang['bpn_h_supply']='Versorgungshöhe';
$ec_lang['bpn_h_supply_tip']='Quellhöhe beim Bemessungsdurchfluss, abgelesen von der Versorgungskennlinie. Entspricht der eingegebenen Quellhöhe, wenn die Kennlinie flach verläuft (ein Reservoir).';
$ec_lang['bpn_show_elevation']='Höhe';
$ec_lang['bpn_supply1_h']='Statische Versorgungshöhe';
