<?php

// All missing text declarations will fall back to English.

// Birimler (alphabetical order)
// Hesap makinası birim seçimi için gerekli
$ec_lang['u_depthFrac']='oran';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='ft^3/s';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/s';
$ec_lang['u_gpm']='g/d';
$ec_lang['u_gradePercent']='% Yükselme/Yatay Mesafe';
$ec_lang['u_grade']='Yükselme/Yatay Mesafe';
$ec_lang['u_in2']='inç^2';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='inç';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='g*10^6/gün';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_bar']='bar';
$ec_lang['u_kgfcm2']='kgf/cm^2';
$ec_lang['u_s']='sn';
$ec_lang['u_lph']='L/hr';
$ec_lang['u_gph']='gal/hr';
$ec_lang['u_mmph']='mm/hr';
$ec_lang['u_inph']='in/hr';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Hesap Makineleri';
$ec_lang['menu_main_list']='Hesap makinesi listesi';
$ec_lang['menu_main_hydraulics']='Hidrolik';
$ec_lang['menu_main_language']='Dil';
$ec_lang['menu_more']='Daha fazla';
$ec_lang['template_welcome']='Korkularını kapıda bırak; burada sevgi konuşulur. Her şeyi mahvetmiyorsun. <a target="_blank" href="https://hawsedc.com/download.php">Ücretsiz HawsEDC AutoCAD araçlarını</a> da deneyin.';
$ec_lang['template_feedback']='Bu sayfadaki ifadeler için daha iyi bir öneriniz mi var, yoksa başka bir şey mi? Yardımcı olmak ya da bunun gibi araçlar yapmayı öğrenmek ister misiniz? Lütfen benimle iletişime geçin.';
$ec_lang['template_printable_title']='Yazdırılabilir Başlık';
$ec_lang['template_printable_subtitle']='Yazdırılabilir Alt Başlık';
$ec_lang['index_title']='Bedava çevrimiçi mühendislik hesaplayıcıları';
$ec_lang['index_meta_desc_plain']='Boru, kanal, savak ve sulama için ücretsiz hidrolik mühendislik hesaplayıcıları. Tarayıcınızda çalışır, çevrimdışı kullanılabilir ve 27 dilde sunulur.';
$ec_lang['calc_set_units']='Birimleri ayarla:';
$ec_lang['calc_units_us']='US';
$ec_lang['calc_units_si']='SI';
$ec_lang['calc_defaults']='Varsayılanları geri yükle';
$ec_lang['calc_defaults_confirm']='Hesap makinesini varsayılan değerlere sıfırla?';
$ec_lang['points_data_help']='(veya veri alanını kullanarak Kopyala/Yapıştır)';
$ec_lang['points_data_title']='Nokta verileri<br />(virgül veya sekme ile ayrılmış)';
$ec_lang['points_data_copy']='Kopyala';
$ec_lang['points_data_paste']='Yapıştır';
$ec_lang['calc_inputs']='Girdiler';
$ec_lang['calc_results']='Sonuçlar:';
$ec_lang['view_hide_line']='[Bu satırı gizle]';
$ec_lang['view_printable']='Yazdırılabilir sürüm (geri yüklemek için yeniden yükleyin)';
$ec_lang['ec_name_label']='Bu hesaplamayı kaydet:';
$ec_lang['ec_name_placeholder']='Ad';
$ec_lang['ec_name_hint']='Bu girdileri URL\'ye kaydeder (yer işareti, geçmiş ve paylaşım için)';
$ec_lang['calc_copy_link']='Bağlantıyı kopyala';
$ec_lang['ec_related_calcs']='İlgili hesaplayıcılar:';
$ec_lang['calc_copy_link_done']='Kopyalandı!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach Boru Yük Kaybı';
$ec_lang['dw_main_title']='Ücretsiz Çevrimiçi Darcy-Weisbach Boru Yük Kaybı Hesaplayıcısı';
$ec_lang['dw_main_desc']='Verilen Çap, Pürüzlülük ve Akış için Darcy-Weisbach Boru Yük Kaybı';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Boru cidarının mutlak pürüzlülük yüksekliği, e. Tipik değerler: çelik (yeni) 0,046 mm, çelik (kullanılmış) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, beton 0,3–3 mm.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="Temiz su için 20°C\'de 1×10⁻⁶ m²/s">Kinematik viskozite, ν <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Kinematik viskozite, ν';
$ec_lang['dw_kinematic_viscosity_tip']='Temiz su için 20°C\'de 1×10⁻⁶ m²/s';
$ec_lang['dw_reynolds_number']='Reynolds sayısı, Re';
$ec_lang['dw_flow_regime']='Akış rejimi';
$ec_lang['dw_regime_laminar']='laminer';
$ec_lang['dw_regime_transitional']='geçişli';
$ec_lang['dw_regime_turbulent']='türbülanslı';
$ec_lang['dw_friction_factor_method']='Sürtünme faktörü yöntemi';
$ec_lang['dw_friction_factor']='Sürtünme faktörü, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams Boru Yük Kaybı';
$ec_lang['hw_main_title']='Ücretsiz Çevrimiçi Hazen-Williams Boru Yük Kaybı Hesaplayıcısı';
$ec_lang['hw_main_desc']='Verilen Çap, Pürüzlülük ve Akış için Hazen-Williams Boru Yük Kaybı';
$ec_lang['hw_hgl_1']='Mansap HGL';
$ec_lang['hw_hgl_2']='Memba HGL';
$ec_lang['hw_elev_up']='Memba kotu';
$ec_lang['hw_pressure_up']='Memba basıncı';
$ec_lang['hw_elev_down']='Mansap kotu';
$ec_lang['hw_pressure_down']='Mansap basıncı';
$ec_lang['hw_pressure_check']='Basınç kontrolü';
$ec_lang['hw_pressure_ok_short']='Pozitif basınç';
$ec_lang['hw_pressure_neg_short']='Negatif basınç';
$ec_lang['hw_pressure_neg']='Mansap basıncı sıfırın altında. HGL borunun altına düşüyor, bu nedenle boru tam dolu akmayabilir ve bu sonuç geçerli olmayabilir.';
$ec_lang['hw_roughness']='Hazen-Williams katsayısı, C';
$ec_lang['hw_note_1']='<dl><dt>Bu hesaplayıcı, iki uç arasındaki boru profilini modellemez.</dt><dd>Yalnızca girdiğiniz memba ve mansap kotlarını kullanır. Zemin, aradaki bir noktada her iki uçtan daha yükseğe çıkıyorsa, o yüksek noktadaki basınç burada bildirilen basınçlardan daha düşüktür. Bunu kontrol etmek için hesaplayıcıyı, memba ucundan yüksek noktaya kadar olan uzunluk için tekrar çalıştırın.</dd><dd>HGL\'nin borunun altına düştüğü yerlerde, su negatif basınç altındadır. Hava çözeltiden çıkar, ince cidarlı bir boru çökebilir ve kirli yeraltı suyu eklem yerlerinden içeri çekilebilir. Hattı her yerde pozitif basınç altında tutun ve her yüksek noktada bir hava vanası kullanmayı düşünün.</dd><dt>Memba basıncı, sizin sağladığınız bir sınır koşuludur.</dt><dd>Bunu bir manometreden, bir tank su seviyesinden (borunun üzerindeki su yüksekliği) veya bir pompa eğrisinden okuyun. Debi arttıkça pompa daha az basınç sağlar, bu yüzden yukarıda girilen debiye karşılık gelen eğri üzerindeki noktayı kullanın.</dd><dt>Yerel kayıp katsayılarını kendiniz toplayın.</dt><dd>Hat üzerindeki her vana, dirsek, T-parçası, sayaç ve giriş için K değerlerini toplayın ve bu toplamı girin. Tipik değerler için o girdinin yanındaki bağlantıyı izleyin. Uzun bir iletim hattında bu kayıplar sürtünmenin yanında küçüktür, ancak kısa istasyon borulamasında kayıpların çoğunu oluşturabilirler.</dd></dl>';
$ec_lang['hw_notes_epanet_term']='Hazen-Williams sabitleri artık EPANET ile aynı (Ağustos 2026)';
$ec_lang['hw_notes_epanet_def']='Ağustos 2026\'da Hazen-Williams katsayısı ve üssü, EPANET ile aynı olacak şekilde değiştirildi. Yük kaybı sonuçları bu sayfanın önceki sürümlerinden en fazla yüzde 0,1 farklıdır; bu, C değerinin kendi belirsizliğinden çok daha küçüktür.';
// Manning Irregular
$ec_lang['mi_menu']='Manning Düzensiz Kesitli Kanal';
$ec_lang['mi_main_title']='Ücretsiz Çevrimiçi Manning Düzensiz Kesitli Kanal Hesaplayıcısı';
$ec_lang['mi_main_desc']='Düzensiz Kesitli Kanal Manning Düzgün Akış Hesaplayıcısı';
$ec_lang['mi_waterSurfaceElevation']='Su yüzeyi kotu';
$ec_lang['mi_q_617']='<span class="ec-help" title="Chow 6-17\'ye göre her bölge için bileşik n kullanılarak hesaplanan bileşik akış, Q (eşit hızlar)">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Kesit noktaları';
$ec_lang['mi_groupPoint']='Nokta';
$ec_lang['mi_groupSegment']='Bölüm';
$ec_lang['mi_groupRegion']='Bölge';
$ec_lang['mi_station']='İst.';
$ec_lang['mi_elevation']='Kot';
$ec_lang['mi_d50in']='Kaplama<br />ortanca<br />taş<br />boyutu';
$ec_lang['mi_n']='n<br />böl.';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />bölge<br />sınırı<br />(Kıyı)';
$ec_lang['mi_tau']='Taban<br />kaym.<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Bileş.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='Bileşik n';
$ec_lang['mi_notes_1_def']='Bu hesaplayıcı, bölge bileşik n hesabı için HEC-RAS Referans Kılavuzunu takip eder: Chow 1959, sayfa 136, denklem 6-17 (6-18 değil).';
$ec_lang['mi_notes_2_term']='Taş kaplama';
$ec_lang['mi_notes_2_def']='Taş kaplama tasarımı için Manning Trapezoidal Kanal Hesaplayıcısını kullanın. Bu hesaplayıcı daha çok doğal kesitler içindir.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning Boru Akışı';
$ec_lang['mpf_main_title']='Ücretsiz Çevrimiçi Manning Boru Akışı Hesaplayıcısı';
$ec_lang['mpf_main_desc']='Belirli Eğim ve Derinlikte Manning Formülü ile Düzgün Boru Akışı';
$ec_lang['mpf_spreadheet_notice']='Manning Boru Akışı elektronik tablosu';
$ec_lang['mpf_pipe_diameter']='Boru çapı, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning pürüzlülük katsayısı, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Sürtünme eğimi, S<sub>f</sub></a><span class="ec-help" title="Bazen boru eğimine eşit. Açıklama için bağlantıyı izleyin (yalnızca İngilizce)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Göreli akış derinliği, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Debi, Q';
$ec_lang['mpf_flow_tip']='Akış ve derinlik, sonsuz uzunluktaki bir boru için hesaplanmıştır. Bu akışın boruya girebilmesi için daha yüksek bir memba derinliği gerekebilir. Ayrıntılar ve bir öğretici video için aşağıdaki Notlar bölümüne bakın.';
$ec_lang['mpf_velocity']='Hız, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="Su sütunu yüksekliği olarak kinetik enerji, v²/2g">Hız yükü, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='Akış alanı, A';
$ec_lang['mpf_pipe_area']='Boru alanı, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Göreli alan, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Islak çevre, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Hidrolik yarıçap, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Üst genişlik, T';
$ec_lang['mpf_froude_number']='Froude sayısı, Fr';
$ec_lang['mpf_shear_stress']='Ortalama kayma gerilmesi, τ';
$ec_lang['mpf_full_flow']='Tam akış, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Tam akışa oran, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Bu, <em>sonsuz uzunluktaki</em> bir borunun içindeki akış ve derinliktir.</dt><dd>Akışın boruya girmesi için önemli ölçüde daha yüksek memba derinliği gerekebilir. Memba derinliğini elde etmek için en az 1,5 hız yükü ekleyin ya da standart menfez memba hesaplamaları için <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">2 dakikalık öğreticime bakın</a>; bu hesaplamalarda ABD Federal Karayolları İdaresi\'nin (FHWA) ücretsiz menfez programı olan <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>\'i kullanır.</dd>';
$ec_lang['mpf_sewer_ref']='<dl><dt>Atıksu kanalizasyon hattı mı tasarlıyorsunuz?</dt><dd>4 ila 96 inç (100 ila 2400 mm) arası borular için m/m, mm/m ve yüzde cinsinden verilen <a target="_blank" href="/sewslope.php">minimum kanalizasyon eğim tablolarına</a> ve çok düşük debiler için <a target="_blank" href="/peakfact.php">tepe debi faktörleri</a> çalışmasına bakın. Her ikisi de yalnızca İngilizce referans belgeleridir.</dd></dl>';
$ec_lang['mpf_solver_enter_positive_q']='Pozitif bir hedef Q girin.';
$ec_lang['mpf_solver_no_solution']='Çözüm yok: Q, y/d0 = %93,8\'de boru kapasitesini aşıyor (Qmax = {qmax}, seçilen birimlerde).';
$ec_lang['mpf_solve_button']='Hesapla';
$ec_lang['mpf_solve_for_flow']='debi için, Q =';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning Boru Yük Kaybı';
$ec_lang['mphl_main_title']='Ücretsiz Çevrimiçi Manning Boru Yük Kaybı Hesaplayıcısı';
$ec_lang['mphl_main_desc']='Belirli Tam Akışta Manning Formülü Yük Kaybı';
$ec_lang['mphl_pipe_length']='Uzunluk, L';
$ec_lang['mphl_area']='Alan, A';
$ec_lang['mphl_total_junction_k']='Küçük (yerel) kayıp katsayısı, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Kayıp katsayısı, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Küçük (yerel) kayıp katsayısı, km. Bu kayıplar boru bağlantılarında, girişlerde, çıkışlarda, dirseklerde ve vanalarda oluşur — "küçük" terimi geleneksel bir adlandırmadır ancak yanıltıcıdır; kısa bir hatta bu kayıplar sürtünme kayıplarına eşit olabilir, hatta onları aşabilir. Tipik k değerleri: keskin kenarlı giriş 0,5, her 45° dirsek 0,2–0,3, sürgülü vana (tam açık) 0,1, kelebek vana 0,2, çıkış (rezervuara veya atmosfere) 1,0. Toplam km için tüm bağlantı elemanlarını toplayın. Varsayılan değer olan 2,0; bir giriş, bir çıkış ve iki adet 45° dirsek varsayımına dayanır.';
$ec_lang['mphl_friction_slope']='Sürtünme eğimi';
$ec_lang['mphl_friction_loss']='Sürtünme kaybı, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Küçük (yerel) kayıp, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Toplam kayıp, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='Mansap EGL';
$ec_lang['mphl_egl_2']='Memba EGL';
$ec_lang['mphl_hgl_egl_tip']='Boru yüksekteyse geçerli olmayabilir. Notlara bakın.';
$ec_lang['mphl_note_1']='<dl><dt>Bu hesaplayıcı, iki uç arasındaki boru profilini modellemez.</dt><dd>HGL herhangi bir noktada boru üstünün altına düşerse, bu hesaplama geçerli olmayabilir.</dd><dt>Açık giriş (menfez) koşulunda, giriş kontrolü koşullarının kontrol edilmesi gerekir.</dt><dd>1. Memba HGL\'si, memba normal derinlik akış kotundan (veya borudan) düşük olamaz.</dd><dd>2. Bir menfezin memba su yüzü, memba HGL\'sinden ziyade memba EGL\'si ile daha iyi temsil edilir.</dd><dd>3. Basit standart menfez memba hesaplamaları için <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">2 dakikalık öğreticime bakın</a>; bu hesaplamalarda ABD Federal Karayolları İdaresi\'nin (FHWA) ücretsiz menfez programı olan <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>\'i kullanır.</dd><dd>4. Bu sayfa yalnızca çıkış kontrolü durumunu çözer: mansap koşullarının yükü belirlediği, tam dolu akan bir boru. Menfez tasarımı, giriş kontrolünün mü yoksa çıkış kontrolünün mü geçerli olduğuna karar vermeyi gerektirir; bu yüzden ikisinden biri geçerli olabiliyorsa HY-8 kullanın.</dd></dl>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning Trapezoidal Kanal';
$ec_lang['mtc_main_title']='Ücretsiz Çevrimiçi Manning Formülü Trapezoidal Kanal Hesaplayıcısı';
$ec_lang['mtc_main_desc']='Belli Eğim ve Derinlikteki Düzgün Trapezoidal Kanallar için Manning Formülü';
$ec_lang['mtc_bottom_width']='Taban genişliği, b';
$ec_lang['mtc_side_slope_1']='Yan Eğim 1, z<sub>1</sub> (yatay / dikey)';
$ec_lang['mtc_side_slope_2']='Yan Eğim 2, z<sub>2</sub> (yatay / dikey)';
$ec_lang['mtc_channel_slope']='Kanal Eğimi, S';
$ec_lang['mtc_flow_depth']='Akış Derinliği, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Kurp Açısı, β</a><span class="ec-help" title="Taş dolgu boyutlandırması için. Şema için bağlantıyı izleyin."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Suya göre yoğunluk. Kırma taş için tipik ≈ 2,65.">Taşın özgül ağırlığı, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Tasarım taş boyutu, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='Tasarım taş boyutu için n (Strickler\'e göre)';
$ec_lang['mtc_n_blodgett']='Tasarım taş boyutu için n (Blodgett\'e göre)';
$ec_lang['mtc_n_bathurst']='Tasarım taş boyutu için n (Bathurst\'e göre)';
$ec_lang['mtc_n_pi']='Tasarım taş boyutu için n (Phillips & Ingersoll\'e göre)';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett ve Bathurst karşılaştırması';
$ec_lang['mtc_pi_range_check']='P&I aralık kontrolü';
$ec_lang['mtc_pi_ok']='d50, P&I aralığında';
$ec_lang['mtc_pi_ok_tip']='0,28–0,36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='Aralık dışı';
$ec_lang['mtc_pi_tip']='Bu denklemin türetildiği 0.28–0.36 ft veri seti aralığının dışına ekstrapolasyon yapılıyor — tasarım esası değil, kaba bir kontrol olarak değerlendirin';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Isbash (1936) ve Maricopa County, Arizona, US\'ye göre.">Taban için gerekli köşeli taş boyutu, D<sub>50</sub> (Isbash ve MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Isbash (1936) ve Maricopa County, Arizona, US\'ye göre.">Yan eğim 1 için gerekli köşeli taş boyutu, D<sub>50</sub> (Isbash ve MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Isbash (1936) ve Maricopa County, Arizona, US\'ye göre.">Yan eğim 2 için gerekli köşeli taş boyutu, D<sub>50</sub> (Isbash ve MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Gerekli köşeli taş boyutu, D<sub>50</sub> (Maynord, Ruff ve Abt 1989)';
$ec_lang['mtc_d50_searcy']='Gerekli köşeli taş boyutu, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='Hız, düzgün akış varsayımları için makul.';
$ec_lang['mtc_vel_low']='Hız düşük — çökelme riski.';
$ec_lang['mtc_vel_high']='Hız yüksek ve gerçekçi olmayabilir; kanal kaplamasının erozyonunu, dirseklerde gereken ek derinliği ve genişlemelerde veya engellerde oluşan enerji kaybını kontrol edin.';
$ec_lang['mtc_iteration_tip']='Hedef akışınız için düzgün bir taş boyutuna otomatik olarak yaklaşmak üzere bir pürüzlülük seçeneği (Blodgett–Bathurst önerilir) ve bir taş boyutu seçeneği (Isbash önerilir) seçin. Tam yöntem için aşağıdaki Notlar bölümüne bakın veya döngüyü atlamak için kendi pürüzlülük değerinizi (rehberlik için bağlantıyı izleyin) girip taş boyutunu yoksayın.';
$ec_lang['mtc_note_1']='<dl><dt>Otomatik taş boyutu ve pürüzlülük tasarım döngüsü</dt><dd>Bir pürüzlülük seçeneği (Blodgett–Bathurst önerilir) ve bir tasarım taş boyutu seçeneği (Isbash önerilir) seçin. İstenen akışı düzgün bir taş boyutuyla elde etmek için derinliği ve taş boyutu güvenlik faktörünü ince ayarlayın. Her giriş değeri değiştiğinde şu döngü gerçekleşir: 1. Pürüzlülük, tasarım taş boyutundan hesaplanır. 2. İstenen pürüzlülük hesabı giriş pürüzlülüğüne kopyalanır. 3. Kanal akışı ve gerekli taş boyutu hesaplanır. 4. Tasarım taş boyutu ayarlanır. 5. Tasarım taş boyutundaki hata çok küçük olana kadar tekrarlanır.</dd><dt>Temel hesaplayıcı (döngü yok)</dt><dd>İstediğiniz pürüzlülük değerini girin. Tasarım taş boyutu giriş alanını yoksayın.</dd></dl>';
$ec_lang['mtc_note_2_term']='Hız kontrolü';
$ec_lang['mtc_note_2_def']='Yüksek hız, bu denli yüksek özgül enerji yaratan büyük bir kot düşüşü olduğunu gösterir. Bu enerji, genişlemelerde, dirseklerde veya engellerde hızla kaybolabilir. Bunun saha için makul olduğunu doğrulayın.';
$ec_lang['mtc_solver_no_solution']='Bu kanal girdileriyle verilen Q için çözüm bulunamadı.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Basit Savak Debisi';
$ec_lang['ws_main_title']='Ücretsiz Çevrimiçi Basit Geniş Kretli Savak Debisi Hesaplayıcı';
$ec_lang['ws_main_desc']='Basit Geniş Kretli Savak Debisi Hesaplayıcı';
$ec_lang['ws_weirLength']='Savak uzunluğu, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="Suyun birim ağırlığı başına enerji — su sütununun yüksekliğidir, basınç değildir">Su yükü, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='Savak katsayısı, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Notlar';
$ec_lang['ws_notes_we_term']='Savak Denklemi';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Düzensiz Kretli Savak Debisi';
$ec_lang['wi_main_title']='Ücretsiz Çevrimiçi Parçalı, Değişken Derinlikli, Düzensiz Kretli Savak Debisi Hesaplayıcı';
$ec_lang['wi_main_desc']='Düzensiz Kretli Savak Debisi Hesaplayıcı';
$ec_lang['wi_weirPoints']='Savak noktaları';
$ec_lang['wi_pondingHeight']='Göllenme yüksekliği';
$ec_lang['wi_incrementalFlow']='Artımlı debi';
$ec_lang['wi_cumulativeFlow']='Kümülatif debi';
$ec_lang['wi_save_and_calculate']='Kaydet ve Hesapla';
$ec_lang['wi_notes_we_def']='q = eğer (uzunluk = 0) ise 0, değilse eğer (eğim=0) ise cw*uzunluk*d<sub>0</sub><sup>1.5</sup>, değilse cw/(2.5*eğim) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>), burada d<sub>1</sub> ve d<sub>0</sub> her zaman pozitif veya sıfırdır';
// Orifice Flow
$ec_lang['or_main_menu']='Orifis Debisi';
$ec_lang['or_main_title']='Ücretsiz Çevrimiçi Orifis Debisi Hesaplayıcı';
$ec_lang['or_main_desc']='Orifis Debisi — Serbest veya Batık';
$ec_lang['or_shape']='Açıklık şekli';
$ec_lang['or_shape_circular']='Dairesel';
$ec_lang['or_shape_rectangular']='Dikdörtgen';
$ec_lang['or_diameter']='<span class="ec-help" title="Dairesel için çap; dikdörtgen için yükseklik">Çap veya yükseklik, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Yalnızca dikdörtgen açıklıklar için">Genişlik, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Açıklığın alt noktası">Taban kotu <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Memba su yüzü kotu';
$ec_lang['or_twe']='Mansap su yüzü kotu';
$ec_lang['or_cd']='Debi katsayısı, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Ağırlık merkezi kotu';
$ec_lang['or_head']='<span class="ec-help" title="Suyun birim ağırlığı başına enerji — su sütununun yüksekliğidir, basınç değildir">Etkin su yükü, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='Açıklık alanı, A';
$ec_lang['or_regime']='Orifis rejimi kontrolü';
$ec_lang['or_regime_valid']='Serbest çıkış';
$ec_lang['or_regime_submerged']='Batık orifis';
$ec_lang['or_regime_submerged_tip']='TWE ağırlık merkezinin üzerinde — orifis rejimi hâlâ geçerli';
$ec_lang['or_regime_warn']='Orifis rejimi dışında';
$ec_lang['or_regime_warn_tip']='Memba su yüzü tavanın altında';
$ec_lang['or_regime_twe_above_hwe']='Girdileri kontrol edin';
$ec_lang['or_regime_twe_above_hwe_tip']='Mansap suyu (TWE), memba suyunun (HWE) üzerinde';
$ec_lang['or_notes_1_term']='Orifis Denklemi';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Serbest çıkış için: h = HWE − ağırlık merkezi kotu. Batık akış için (TWE taban kotunun üzerinde): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Orifis Rejimi';
$ec_lang['or_notes_2_def']='Orifis akış denklemleri, memba su yüzü açıklığın tavanının (üst noktasının) üzerinde olduğunda uygulanır. Memba su yüzü tavanın altındaysa, bunun yerine bir savak denklemi kullanın.';
$ec_lang['or_notes_3_term']='Debi Katsayısı';
$ec_lang['or_notes_3_def']='C<sub>d</sub>, keskin kenarlı orifisler için yaklaşık 0,60–0,65 aralığındadır. Yuvarlatılmış veya içe girik girişler farklı değerler alır. Bkz. <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venturi-d_590.html">Engineering Toolbox</a> veya HEC-RAS Hidrolik Referans Kılavuzu.';
$ec_lang['or_notes_4_term']='Batıklık';
$ec_lang['or_notes_4_def']='TWE, açıklığın taban kotunun üzerindeyken bu hesaplayıcı, h = HWE − TWE kullanarak batık orifis denklemini otomatik olarak uygular. TWE taban kotunda veya altındayken serbest çıkış varsayılır ve h = HWE − ağırlık merkezi kotu alınır.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Mikro-Hidroelektrik Güç';
$ec_lang['mhp_main_title']='Ücretsiz Çevrimiçi Mikro-Hidroelektrik Güç Hesaplayıcısı';
$ec_lang['mhp_main_desc']='Nehir Akışı Mikro-Hidroelektrik Güç Çıkışı Hesaplayıcısı';
$ec_lang['mhp_gross_head']='Brüt düşü, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="Cebri boru (besleme borusu) çapı">Cebri boru çapı, D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='Uzunluk, L';
$ec_lang['mhp_efficiency']='Tesis verimi, η (0–1)';
$ec_lang['mhp_vel_check']='Hız kontrolü';
$ec_lang['mhp_hl_check']='Yük kaybı kontrolü';
$ec_lang['mhp_hnet']='Net düşü, H<sub>net</sub>';
$ec_lang['mhp_power']='Çıkış gücü, P';
$ec_lang['mhp_annual_kwh']='%100 kapasitede yıllık enerji';
$ec_lang['mhp_vel_low']='Hız düşük — çökelme ve hava sürüklenmesi riski.';
$ec_lang['mhp_vel_high']='Hız yüksek — geçiş kayıplarını, mevcut enerjiyi ve su darbesi riskini kontrol edin.';
$ec_lang['mhp_vel_ok_short']='Tamam';
$ec_lang['mhp_vel_high_short']='Yüksek';
$ec_lang['mhp_vel_low_short']='Düşük';
$ec_lang['mhp_vel_ok_tip']='Hız, cebri boru tasarımı için verimli aralıktadır.';
$ec_lang['mhp_hl_ok_tip']='%10 hedefinin altında — ekonomik.';
$ec_lang['mhp_hl_warn_tip']='%10 hedefini aşıyor. Daha büyük bir boru düşünün.';
$ec_lang['mhp_hl_bad_tip']='%20 hedefini aşıyor. Boru boyutunu değiştirin.';
$ec_lang['mhp_notes_1_term']='Yük Kaybı';
$ec_lang['mhp_notes_1_def']='Toplam cebri boru kaybı h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>; burada h<sub>f</sub> = f(L/D)(v²/2g) Darcy-Weisbach sürtünme kaybıdır ve h<sub>m</sub> = k<sub>m</sub>·v²/2g giriş, dirsek ve vanaları kapsar. Net düşü H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Hız';
$ec_lang['mhp_notes_2_def']='Hızın mevcut düşü ve boru maliyeti için makul olup olmadığını kontrol edin. Çok düşük hız borunun gereğinden büyük seçildiğini gösterebilir; çok yüksek hız sürtünme kayıplarını ve su darbesi riskini artırabilir.';
$ec_lang['mhp_notes_3_term']='Yük Kaybı Hedefi';
$ec_lang['mhp_notes_3_def']='Brüt düşünün %10\'unun altındaki cebri boru kayıpları genellikle ekonomiktir. Boru maliyeti ile kaybedilen güç arasındaki en uygun denge, genellikle elektriğin en değerli olduğu durumlarda %4–6 civarındadır.';
$ec_lang['mhp_notes_6_term']='Verimlilik';
$ec_lang['mhp_notes_6_def']='Tipik tesis verimi η, mikro-hidro sistemlerinde yaygın olan Pelton ve çapraz akış türbinleri için 0,70 ile 0,85 arasında değişir. Muhafazakâr bir ilk tahmin olarak 0,75 kullanın.';
$ec_lang['mhp_notes_7_term']='Yıllık Enerji';
$ec_lang['mhp_notes_7_def']='Yıllık enerji, sürekli tam debi çalışmasını (yılda 8.760 saat) varsayar. Mevsimsel debi değişimi, bakım duruşları ve yük faktörü nedeniyle gerçek üretim daha düşük olacaktır.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Gölet & Depo Boşalma Süresi';
$ec_lang['odt_main_title']='Ücretsiz Çevrimiçi Gölet, Havuz ve Depo Boşalma Süresi Hesaplayıcısı (Orifis)';
$ec_lang['odt_main_desc']='Gölet, Havuz veya Depo Boşalma Süresi — Orifis Çıkışlı, Konik Hacim Yöntemi';
$ec_lang['odt_h1_elev']='Başlangıç su yüzeyi kotu';
$ec_lang['odt_a1']='Başlangıç alanı, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Bitiş su yüzeyi kotu';
$ec_lang['odt_a0']='Orifis seviyesindeki alan, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Bitiş kotunda konik modelden interpolasyonla elde edilir">Bitiş alanı, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Bitiş kotu kontrolü';
$ec_lang['odt_h2_ok']='Bitiş kotu orifis tavanının üzerinde';
$ec_lang['odt_h2_warn']='Bitiş kotu orifis tavanında veya altında';
$ec_lang['odt_h2_warn_tip']='Orifis tavanı = ağırlık merkezi kotu + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Çap (dairesel) veya yükseklik (dikdörtgen)">Orifis D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Yalnızca dikdörtgen için">Orifis genişliği, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Boşalma süresi (sn)';
$ec_lang['odt_t_min']='Boşalma süresi (dk)';
$ec_lang['odt_t_hr']='Boşalma süresi (sa)';
$ec_lang['odt_t_day']='Boşalma süresi (gün)';
$ec_lang['odt_notes_1_term']='Formül';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ifadesi, H yükünden orifise kadar geçen boşalma süresini verir. Boşalma süresi = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), burada H<sub>1</sub> = başlangıç kotu − orifis kotu, H<sub>2</sub> = bitiş kotu − orifis kotu.';
$ec_lang['odt_notes_2_term']='Yöntem';
$ec_lang['odt_notes_2_def']='Konik hacim yöntemi, göleti veya havuzu, başlangıç su yüzeyindeki A<sub>1</sub> alanı ile orifis ağırlık merkezi kotundaki A<sub>0</sub> alanı arasında konik bir kesit olarak modeller. Bitiş kotundaki gölet alanı A<sub>2</sub>, konik kesit modeli kullanılarak A<sub>1</sub> ve A<sub>0</sub>\'dan interpolasyonla hesaplanır. Başlangıçtan bitiş kotuna boşalma süresi, H<sub>1</sub>\'den orifise kadar olan toplam boşalma süresinden H<sub>2</sub>\'den orifise kalan boşalma süresinin çıkarılmasına eşittir.';
$ec_lang['odt_h1']='<span class="ec-help" title="Başlangıç su yüzeyi kotu eksi orifis ağırlık merkezi kotu">Başlangıç su yükü, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Maksimum debi, Q<sub>max</sub>';
$ec_lang['odt_vol']='Boşaltılan hacim';
$ec_lang['odt_sketch_start']='Başlangıç';
$ec_lang['odt_sketch_end']='Bitiş';
// Contact us.

// Irrigation
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Damlatıcı aralığı, S<sub>e</sub>';
$ec_lang['ip_sl']='Lateral aralığı, S<sub>l</sub>';
$ec_lang['ip_n_e']='Lateral başına damlatıcı sayısı, n<sub>e</sub>';
$ec_lang['ip_n_l']='Bölge başına lateral sayısı, n<sub>l</sub>';
$ec_lang['ip_d']='Hedef uygulama derinliği, d';
$ec_lang['ip_a_e']='Damlatıcı başına alan, A<sub>e</sub>';
$ec_lang['ip_pr']='Uygulama oranı, PR';
$ec_lang['ip_q_lat']='Lateral başına debi, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Bölge debisi, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Çalışma süresi (saat)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Kanal Sızıntısı';
$ec_lang['cs_main_title']='Ücretsiz Çevrimiçi Kanal Sızıntı Kaybı ve İletim Verimliliği Hesaplayıcısı';
$ec_lang['cs_main_desc']='Kanal Sızıntı Kaybı & İletim Verimliliği — Giriş-Çıkış Yöntemi';
$ec_lang['cs_Q_in']='Giriş debisi, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Çıkış debisi, Q<sub>out</sub>';
$ec_lang['cs_L']='Güzergah uzunluğu, L';
$ec_lang['cs_Q_loss']='Sızıntı kayıp debisi, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Ölçüm kontrolü';
$ec_lang['cs_pct_loss']='Kayıp oranı';
$ec_lang['cs_Ec']='İletim verimliliği, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Verimlilik değerlendirmesi';
$ec_lang['cs_Vol_day']='Günlük kaybedilen hacim';
$ec_lang['cs_Vol_year']='Yıllık kaybedilen hacim';
$ec_lang['cs_Q_loss_per_L']='Birim uzunluk başına kayıp, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Su değeri';
$ec_lang['cs_lining_cost']='Astar maliyeti';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Kaplamadan sonra iletim verimliliği hedefi; kesir 0–1">Astar hedefi, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Astar alanı, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Yıllık kaybedilen değer';
$ec_lang['cs_annual_value_recovered']='Yıllık kazanılan değer';
$ec_lang['cs_lining_total_cost']='Toplam astar maliyeti';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Basit geri ödeme = toplam astar maliyeti ÷ yıllık kazanılan değer">Geri ödeme süresi <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — sızıntı tespit edildi';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — ölçülebilir kayıp yok';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — ölçümleri kontrol edin';
$ec_lang['cs_Ec_good']='İyi — E<sub>c</sub> ≥ %80';
$ec_lang['cs_Ec_fair']='Orta — E<sub>c</sub> %60–80';
$ec_lang['cs_Ec_poor']='Zayıf — E<sub>c</sub> < %60';
$ec_lang['cs_notes_1_def']='Giriş-çıkış yöntemi, bir kanal güzergahının başındaki ve sonundaki akışı ölçerek sızıntıyı tahmin eder: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. İletim verimliliği E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Yıllık hacim, sürekli tam debi ile çalışma varsayımına dayanır; mevsimsel veya kısmi debi durumunda gerçek kayıp daha düşük olacaktır.';
$ec_lang['cs_notes_2_term']='Verimlilik Değerlendirmeleri';
$ec_lang['cs_notes_2_def']='Tipik astarlanmamış toprak kanallar: E<sub>c</sub> = %60–80. İyi bakımlı toprak kanallar: %75–85. Beton astarlı kanallar: %90–98. Girişin %30\'unu aşan sızıntı kayıpları çoğunlukla astar yatırımını haklı kılar. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Astar Geri Ödeme';
$ec_lang['cs_notes_3_def']='Su değerini ve astar maliyetini herhangi bir tutarlı para biriminde girin. Astar alanı = güzergah uzunluğu × ıslak çevre — ölçülen akış derinliğindeki kanal kesitinin ıslak çevresi (taban genişliği artı her iki ıslak yamaç). Kurtarılan yıllık değer, astarlı kanalın hedef E<sub>c</sub>\'yi sürekli olarak sağladığını varsayar. Mevsimsel kanallar için veya astar hedef verimliliğe ulaşmadığında gerçek geri ödeme süresi daha uzun olacaktır.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3. baskı (2001). FAO Sulama ve Drenaj Belgesi 57 (1999).';
// About
$ec_lang['about_main_menu']='Hakkında';
$ec_lang['install_main_menu']='Yükle';
$ec_lang['install_main_title']='EngCalcs\'i Yükle';
$ec_lang['install_main_desc']='Çevrimdışı kullanım için cihazınıza ekleyin';
$ec_lang['install_intro']='EngCalcs bir Progresif Web Uygulamasıdır (PWA). Kurulduktan sonra tüm hesaplayıcılar tamamen çevrimdışı çalışır — internet bağlantısına gerek kalmaz.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Chrome\'da herhangi bir hesaplayıcı sayfasını açın.</li><li>Üst gezinme çubuğundaki <strong>⬇ Yükle</strong> düğmesine dokunun veya tarayıcı menüsüne (⋮) dokunup <strong>Ana ekrana ekle</strong> seçeneğini seçin.</li><li>Görünen istemde <strong>Yükle</strong> seçeneğine dokunun.</li><li>EngCalcs ana ekranınızda görünür ve çevrimdışı çalışır.</li>';
$ec_lang['install_now_btn']='⬇ Şimdi Yükle';
$ec_lang['install_prompt_unavailable']='Yükleme istemi kullanılamıyor — bunun yerine tarayıcı menünüzü kullanın.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Safari\'de herhangi bir hesaplayıcı sayfasını açın.</li><li><strong>Paylaş</strong> düğmesine dokunun (yukarı ok işaretli kutu).</li><li>Aşağı kaydırıp <strong>Ana Ekrana Ekle</strong> seçeneğine dokunun.</li><li><strong>Ekle</strong> seçeneğine dokunun. EngCalcs ana ekranınızda görünür.</li>';
$ec_lang['install_ios_note']='iOS\'ta kurulum her zaman Paylaş menüsü üzerinden yapılır — otomatik bir yükleme istemi bulunmaz.';
$ec_lang['install_desktop_heading']='Masaüstü (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Herhangi bir hesaplayıcı sayfasını açın.</li><li>Tarayıcının adres çubuğundaki <strong>yükleme simgesine</strong> (⊕ veya bilgisayar simgesi) tıklayın ya da tarayıcı menüsünü açıp <strong>EngCalcs\'i Yükle…</strong> seçeneğini seçin.</li><li><strong>Yükle</strong> seçeneğine tıklayın. EngCalcs bağımsız bir uygulama penceresi olarak açılır.</li>';
$ec_lang['install_firefox_heading']='Firefox / Diğer Tarayıcılar';
$ec_lang['install_firefox_body']='Firefox, masaüstünde PWA kurulumunu desteklemez. Yine de tüm hesaplayıcıları tarayıcıda normal şekilde kullanabilirsiniz — ilk ziyaretinizden sonra sayfalar çevrimdışı kullanım için otomatik olarak önbelleğe alınır.';
$ec_lang['install_cached_heading']='Önbelleğe Alınanlar';
$ec_lang['install_cached_body']='EngCalcs\'i ilk kez yüklediğinizde, tüm hesaplayıcı sayfaları ve bunları destekleyen dosyalar (betikler, stiller) cihazınıza otomatik olarak kaydedilir. Bundan sonra her şey internet bağlantısı olmadan çalışır. Dil tercihiniz son çevrimiçi ziyaretinizden hatırlanır.';
$ec_lang['contact_main_menu']='İletişim';
$ec_lang['about_main_title']='HawsEDC Mühendislik Hesaplayıcıları Hakkında';
$ec_lang['about_main_desc']='Misyon, Açık Kaynak ve Katkı';
$ec_lang['about_body_html']='<h3>Misyon</h3><p>HawsEDC Mühendislik Hesap Makineleri, dünya genelindeki mühendislere ve saha çalışanlarına hizmet etmek için var — özellikle su kıtlığı olan, kaynak yetersizliği çeken veya ihmal edilmiş bölgelerde çalışanlara. Bu araçlar, daha geniş bir insani misyonun parçasıdır: her insana en pratik ve etkili şekilde, sonsuza dek sevildiğini ve değer gördüğünü, hiçbir şeyden korkmasına gerek olmadığını ve her şeyi mahvetmeyeceğini söylemek.</p><p>Hesap makineleri araçtır. Hedef, acısız bir dünyadır.</p><h3>Açık Kaynak Lisansı</h3><p>Tüm kod, <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU Genel Kamu Lisansı v3.0 veya üzeri</a> kapsamında yayınlanmıştır — özgürlük anlamında özgür. Kodu aynı koşullar altında kullanabilir, inceleyebilir, değiştirebilir ve yeniden dağıtabilirsiniz.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Kaynak Kodu</h3><p>Tam kaynak kodu Bitbucket\'ta herkese açık olarak mevcuttur:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Orada kodu inceleyebilir, sorun bildirebilir veya depoyu çatallandırabilirsiniz.</p><h3>Katkıda Bulunma</h3><p>Pull request\'ler memnuniyetle karşılanır. Katkıda bulunma yolları:</p><ul><li><strong>Çeviriler</strong> — bir dili geliştirin veya yeni dil ekleyin. İlgili <code>lib/lang.ec.??.php</code> dosyasındaki değişikliklerle pull request açın.</li><li><strong>Hata raporları</strong> — herhangi bir hesap makinesi sayfasındaki geri bildirim formunu kullanın veya Bitbucket\'ta sorun bildirin.</li><li><strong>Yeni hesap makineleri</strong> — saha çalışanlarına ve sulama uzmanlarına hizmet eden hidrolik mühendislik araçları için fikirler özellikle memnuniyetle karşılanır. Depodaki <code>CLAUDE.md</code> geliştirici kılavuzuna bakın.</li><li><strong>Barındırma</strong> — bu hesap makinelerini sınırlı bağlantısı olan bir bölge için yansıtabilirseniz lütfen iletişime geçin.</li></ul><h3>Çevrimdışı Kullanım</h3><p>Bu hesap makineleri bir Aşamalı Web Uygulaması (PWA) olarak çalışır. İnternete bağlıyken herhangi bir hesap makinesi sayfasını ziyaret edin; tarayıcınız tüm hesap makinelerini otomatik olarak önbelleğe alacaktır. Bundan sonra tüm hesap makineleri çevrimdışı çalışır — internet gerekmez.</p><p>Android veya iOS\'ta, EngCalcs\'ı cihazınıza uygulama olarak yüklemek için tarayıcınızın "Ana Ekrana Ekle" seçeneğini kullanın. Masaüstünde, tarayıcınızın adres çubuğundaki yükleme simgesini arayın.</p><p>Ayrıca herhangi bir hesap makinesini tek seferlik çevrimdışı kullanım için tarayıcınızın "Farklı kaydet…" menüsünü kullanarak kaydedebilirsiniz.</p><h3>İletişim</h3><p>Tom Haws — hidrolik mühendisi ve bu hesap makinelerinin yazarı.<br />Herhangi bir hesap makinesi sayfasındaki geri bildirim formunu kullanın veya <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>\'taki kaynak koda erişin.</p>';
$ec_lang['contact_title']='Haws EDC Iletisim';
$ec_lang['contactSendMessage']='Tom Haws\'a bir mesaj gönderin';
$ec_lang['contactYourName']='Isim:';
$ec_lang['contactYourEmail']='E-mail Adresi:';
$ec_lang['contactSubject']='Konu:';
$ec_lang['contact_message']='Mesaj:';
$ec_lang['contactSpamPrefix']='Bes arti bir';
$ec_lang['contactSpamPostfix']='(Lütfen yaziyla gösterin. 1= bir 2=iki 3=üç 4=dört 5=bes 6=alti 7=yedi +=arti 5+1=6)';
$ec_lang['contactSubmitButton']='Gönder';
$ec_lang['contact_success']='Yazmanız için zaman ayırdığınız için teşekkür ederiz.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Taş Düşü Tasarımı (Robinson)';
$ec_lang['rc_main_title']='Ücretsiz Çevrimiçi Taş Düşü Tasarım Hesaplayıcısı — Robinson (1998)';
$ec_lang['rc_main_desc']='Taş Düşü Taş Dolgu Boyutlandırması — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Düşü taban eğimi, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="Düşü girişinde birim genişlik başına debi. B taban genişliğinde ve Q toplam debili bir kanal için q_t = Q / B kullanın.">Toplam birim debi, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='Taş dolgu gözenekliliği, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="Suya göre yoğunluk. Kırma granit veya bazalt için tipik ≈ 2,65. Robinson geçerli aralığı: 2,54–2,82.">Kaya özgül ağırlığı, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="Granülometri standart sapması. Tekdüze kaya ≈ 1,25. Robinson geçerli aralığı: 1,15–1,47.">Granülometri SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="Göllenme (Hp > yn) olumludur — memba erozyonunu azaltır. (USDA)">Giriş kanalında normal derinlik, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="Denklem 1 (S0 < 0,10) veya Denklem 2 (0,10–0,40). Geçerli: D50 15–278 mm, S0 0,02–0,40. Aralık dışı: ekstrapolasyon.">Gerekli ortanca kaya boyutu, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='Uygulanan denklem';
$ec_lang['rc_sg_check']='Özgül ağırlık kontrolü';
$ec_lang['rc_SD_check']='Granülometri SD kontrolü';
$ec_lang['rc_sg_ok']   ='sg geçerli aralıkta';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg Robinson aralığının altında';
$ec_lang['rc_sg_low_tip']='Geçerli aralık: 2,54–2,82';
$ec_lang['rc_sg_high'] ='sg Robinson aralığının üzerinde';
$ec_lang['rc_sg_high_tip']='Geçerli aralık: 2,54–2,82';
$ec_lang['rc_SD_ok']   ='SD geçerli aralıkta';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD Robinson aralığının altında';
$ec_lang['rc_SD_low_tip']='Geçerli aralık: 1,15–1,47';
$ec_lang['rc_SD_high'] ='SD Robinson aralığının üzerinde';
$ec_lang['rc_SD_high_tip']='Geçerli aralık: 1,15–1,47';
$ec_lang['rc_layer']='Taş dolgu kalınlığı (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Üst eşik eğri yarıçapı (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Üst eşik eğri yay uzunluğu';
$ec_lang['rc_apron_length']='<span class="ec-help" title="Düşü taşının yapısal desteği için gereklidir. “Çıkış kesimi ve mansap kanal direncinden kaynaklanan minimum kuyruk suyu, çıkış kesimindeki taş dolgunun stabilitesini sağlamaya yeterlidir.” (Robinson)">Çıkış apronu uzunluğu (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='Düşüde Manning pürüzlülüğü, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="Kaya gözeneklerinden geçen qt fraksiyonu. Kalan qs yüzeyden akar. Varsayılan np = 0,45 köşeli kırma kaya için tipiktir.">Taş mantosu içindeki hız, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='Manto içinden birim debi, q<sub>m</sub>';
$ec_lang['rc_qs']='Yüzey birim debisi, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Taş dolgu yüzeyi üzerindeki akış derinliği, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="Göllenme (Hp > yn) olumludur — memba erozyonunu azaltır. (USDA)">Giriş savak yükü, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='Giriş göllenmesi kontrolü';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — memba göllenmesi';
$ec_lang['rc_pond_ok_tip']='Düşü girişinin membasında göllenme olumludur; membadaki erozyonu azaltır. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — göllenme yok — giriş erozyon potansiyeli';
$ec_lang['rc_pond_warn_tip']='Düşü girişinin membasında göllenme yok; membada erozyon oluşabilir. (USDA)';
$ec_lang['rc_eq1']='Denk. 1 (S<sub>0</sub> < 0,10) — hafif eğim';
$ec_lang['rc_eq2']='Denk. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — dik eğim';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — Robinson doğrulama aralığının altında';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — Robinson doğrulama aralığının üzerinde';
$ec_lang['rc_notes_1_term']='Taş Boyutlandırma Denklemleri';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998), düşü eğimi ve birim debi temelinde ortanca taş dolgu boyutu D<sub>50</sub> için iki ampirik denklem geliştirmiştir. Denklem 1 hafif eğimler için geçerlidir (S<sub>0</sub> < 0,10); Denklem 2 dik eğimler için geçerlidir (0,10 ≤ S<sub>0</sub> ≤ 0,40). Her iki denklem de q<sub>t</sub>\'yi m²/s cinsinden gerektirir ve D<sub>50</sub>\'yi mm cinsinden verir. Doğrulanmış aralık 0,02 ≤ S<sub>0</sub> ≤ 0,40\'tır.';
$ec_lang['rc_notes_2_term']='Birim Debi';
$ec_lang['rc_notes_2_def']='q<sub>t</sub>, düşü eşiğindeki toplam birim debidir (birim genişlik başına toplam debi). B taban genişliğinde ve Q toplam debili bir kanal için q<sub>t</sub> ≈ Q / B olarak yaklaşık alınabilir veya düşü girişindeki kritik derinlik koşulundan hesaplanabilir.';
$ec_lang['rc_notes_3_term']='Taş Mantosu İçinden Akış';
$ec_lang['rc_notes_3_def']='Toplam akışın bir kısmı taş dolgu gözeneklerinden geçer (manto akışı q<sub>m</sub>); geri kalanı taş yüzeyinden akar (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Akış derinliği d, düşü pürüzlülüğü n kullanılarak yüzey akışı q<sub>s</sub>\'ye uygulanan Manning denkleminden hesaplanır. Varsayılan gözeneklilik n<sub>p</sub> = 0,45, köşeli kırma kaya için tipiktir.';
$ec_lang['rc_notes_5_term']='Geçerli Kaya Boyutu Aralığı';
$ec_lang['rc_notes_5_def']='Denklemler 15 mm ile 278 mm arasındaki D<sub>50</sub> aralığı kullanılarak geliştirilmiştir. Bu aralık dışındaki sonuçlar ekstrapolasyon değeridir ve ek mühendislik değerlendirmesiyle kullanılmalıdır.';
$ec_lang['rc_notes_6_term']='Çıkış Apronu Kotu';
$ec_lang['rc_notes_6_def']='Çıkış kesimindeki taş dolgunun üst yüzey kotu, mansap kanal taban kotunda veya altında olmalıdır. Daha yüksekse çıkıştaki taş kararsız olacaktır.';
$ec_lang['rc_notes_7_def']='Giriş kanalındaki normal derinlik, q<sub>t</sub>\'yi iletmek için gerekli savak yükü (H<sub>p</sub>)\'ndan az olduğunda, düşü girişinin membasında kısıtlı akış veya göllenme oluşur. Bu genellikle kabul edilebilirdir — göllenme hızı düşürür ve memba erozyonunu önler. Kontrol için: verilen q<sub>t</sub> ve eşik genişliği için bir savak hesaplayıcısıyla H<sub>p</sub>\'yi bulun ve giriş kanalı normal derinliğiyle karşılaştırın. H<sub>p</sub> normal derinliği aşarsa göllenme oluşacaktır.';
$ec_lang['rc_notes_4_term']='Kaynak';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS aynı yönteme dayalı bir <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel tablosu</a> da yayınlamaktadır.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtre';
$ec_lang['rc_sketch_top_crest_curve'] = 'Üst Eşik Eğrisi';
$ec_lang['rc_sketch_outlet_apron']    = 'Çıkış Apronu';
$ec_lang['rc_sketch_radius']          = 'yarıçap';
// Irrigation Pressure Calculator (branch pipe-network pressure/DU estimate). Prefix ip_.
$ec_lang['ip_main_menu']='Sulama Basıncı';
$ec_lang['ip_main_title']='Ücretsiz Çevrimiçi Sulama Basıncı ve Dağılım Düzgünlüğü Hesaplayıcısı';
$ec_lang['ip_main_desc']='Test Dalı Basıncı ve Düzgünlük Tahmini';
$ec_lang['ip_h_supply']='Beslenme basıncı';
$ec_lang['ip_elev_supply']='Beslenme kotu, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Damlatıcı tasarım debisi, q<sub>design</sub>';
$ec_lang['ip_h_design']='Damlatıcı tasarım basıncı';
$ec_lang['ip_x']='<span class="ec-help" title="Standart kompanse etmeyen damlatıcılar için 0,5; kompanse edici damlatıcılar için 0\'a yakın">Damlatıcı deşarj üssü, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Test yolu';
$ec_lang['ip_group_reach']='Hat';
$ec_lang['ip_group_upstream']='Memba';
$ec_lang['ip_group_downstream']='Mansap';
$ec_lang['ip_group_loss']='Kayıp';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="İşaretli: bu hat test lateral\'inin bir parçasıdır, bireysel damlatıcılar tarafından çekilir. İşaretli değil: bu hat bir ana hattır, sadece test yolunda olmayan lateral\'lere akış iletir.">Lat. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Lateral satırları: bu hattaki damlatıcılar sadece. Ana satırları: bu hattan dallanan diğer lateral\'lerdeki toplam damlatıcılar. Test lateral\'inin kendi alındığı hat için, bu aynı zamanda o alındıktan sonra ana hat boyunca diğer lateral\'leri veya aynı kavşağı paylaşan (örneğin ters taraf lateral) damlatıcıları içerir — akışları bu aynı hattan dallanır, bu tabloda başka yerde göründükleri olsa da.">Damlatıcılar <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Bu hattın mansap uç kotu. İç satırlarda isteğe bağlı (boş bırakılırsa düz olarak varsayılır / yukarıdaki düğümle aynı). Son satırda gerekli: bu değer son damlatıcının kotudur, doğrudan gerekli beslenme basıncını belirler.">MS Kot. <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='Son damlatıcı kotu (son satır) boş bırakıldı ve düz olarak varsayıldı — doğru sonuç için girin';
$ec_lang['ip_flow']='Debi';
$ec_lang['ip_press']='Bas.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Toplam hat kaybı, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Düşük/negatif basınç — atmosfer altı koşulları kontrol edin';
$ec_lang['ip_pressure_warn_short']='Düşük';
$ec_lang['ip_pressure_high']='Yüksek basınçlı yerlerde basınç düşürme gerekir';
$ec_lang['ip_pressure_high_short']='Yüksek';
$ec_lang['ip_max_head']='İzin ver. maks. boru basıncı';
$ec_lang['ip_max_head_tip']='Basıncı bu değeri aşan hatlar işaretlenir. Yüksek basınç kontrolünü atlamak için boş bırakın.';
$ec_lang['ip_h_far']='Son damlatıcı basıncı';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Sadece modellenen test yoluna giren debi, tüm bölge/sistem değil — Uygulama Tasarımı aşağısında Q_zone için bkz.">Test yolu beslenme debisi, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Son damlatıcı debisi, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Ortalama damlatıcı debisi (test lateral), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Bu test lateral\'ine kıyasla tipik/ortalama lateral\'in ne kadar daha yüksek (veya daha düşük) çalıştığına inanıyorsunuz. Test lateral kasıtlı olarak en kötü durum varsayıldığından, kendi ortalaması saha ortalaması için taraflı-düşük bir yaklaşımdır — 0\'da bırakıldığında, aşağıdaki düzgünlük kontrolü ve uygulama tasarımı sayıları test lateral\'inin kendi (muhtemelen iyimser) ortalamasını olduğu gibi kullanır.">Tah. Δbasınç, ort. vs. test lateral <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral yeniden değerlendirilir her lateral satırındaki basınç artı yukarıda girilen basınç farkında — test lateral\'inin en kötü durum varsayıldığı değil temsilci olan için düzeltme denemesi. Aşağıdaki düzgünlük kontrolü ve uygulama tasarımı bölümünün her ikisini de besler.">Tah. saha-ortalama damlatıcı debisi, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Son damlatıcının hesaplanan debisi, tahmini saha-ortalama damlatıcı debisine bölünür — bu, standart düşük-çeyrek Dağılım Düzgünlüğü\'nün (düşük-grup ortalama ÷ nüfus ortalaması) bir yaklaşımıdır; ancak bu, tam saha istatistiksel örneği yerine küçük bir modellenen örnekten ve kullanıcı tarafından tahmin edilen bir düzeltmeden elde edilir. 1\'e eşit veya üzerindeki değerler mümkündür ve geçerlidir: bunlar yalnızca son damlatıcının basıncının tahmini saha ortalamasında veya üzerinde olduğu, dolayısıyla en düşük basınç noktasının başka bir damlatıcı olduğu anlamına gelir. Bunun nedeni son damlatıcının alçak zeminde olması veya Δbasınç tahmininin çok küçük olması olabilir.">Düzgünlük kontrolü, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='Test damlatıcısındaki basınç ≥ besleme basıncı. Bu muhtemelen en kötü durumdaki damlatıcı değildir, ya da borular daha küçük seçilebilir.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Bu, standart düzgünlük ölçüsüne ilişkin yaklaşımımızdan farklıdır.">Son damlatıcı debisi ÷ tasarım debisi, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Çözüm yok: gerekli beslenme basıncı girilen beslenme basıncını aşıyor. Beslenme basıncını artırın, talep azaltın, veya daha büyük boru kullanın.';
$ec_lang['ip_notes_1_def']='Son (en uzak) damlatıcıdaki basıncı tahmin eder, ardından Enerji Seviye Hattını beslenme doğrultusunda geri doğru, hat hat hareket ettirir, yol boyunca sürtünme ve ikincil kayıpları ekler. Yükseklik ve hız yükü her düğümde geri alınır ve orada gerçek basınç bildirilir. Tahmin edilen uzak uç basıncı, hesaplanan gerekli beslenme basıncı girilen beslenme basıncına eşleşene kadar ayarlanır (ikiye bölme yöntemi) — Manning Boru Akımı hesaplayıcısındaki boru akımı çözücüsü tarafından ele alınan aynı kapalı devre problemi, dallı bir ağa genişletilmiştir.';
$ec_lang['ip_notes_2_term']='Ana Hat vs. Lateral Hatlar';
$ec_lang['ip_notes_2_def']='Her satır beslenme kaynağından son damlatıcıya tekil hidrolik olarak en kötü yol (test yolu) boyunca bir hattır. Ana hat sadece test yolunda olmayan lateral\'lere akış iletir, bu nedenle kaynağı düz çarpım (tasarım debisi × hattın toplam damlatıcı sayısı) — yerel basınç hassasiyeti yok. Ana hat paylaşılan gövde borusudur, bu nedenle test lateral\'inin kendi alındığı hattın hemen sağında sadece kendi uç noktaları arasındaki lateral\'leri değil, aynı zamanda o alındıktan sonra ana hat boyunca diğer lateral\'leri veya aynı kavşağı paylaşan lateral\'leri (örneğin ters taraf lateral) dahil etmelidir — akışları bu aynı hattan dallanır, bu tabloda başka yerde göründükleri olsa da. Lateral hat test lateral\'inin kendisinin bir parçasıdır: damlatıcı deşarjı gerçek yerel basınç aracılığıyla q = k·H<sup>x</sup> hesaplanır, ve sürtünme kaybı her damlatıcının hattın dışını çekmesiyle akış adımını hesaplamak için Christiansen\'in F(n) faktörü tarafından azaltılır.';
$ec_lang['ip_notes_3_term']='Sınırlamalar';
$ec_lang['ip_notes_3_def']='Tek bir sabit besleme basıncı (pompa eğrisi yok), yalnızca tek bir test yolu (tüm saha değil) ve 2 parametreli bir damlatıcı eğrisi (basınç-telafili bir damlatıcıyı yaklaşık olarak modellemek için üssü 0\'a yakın ayarlayın) modellenir. İki farklı düzgünlük oranı raporlanır ve bunlar bilerek ayrı tutulur: q<sub>last</sub>/q<sub>avg,field</sub>, standart düşük-çeyrek Dağılım Düzgünlüğü\'nün (düşük-grup ortalama ÷ nüfus ortalaması) bir yaklaşımıdır; ancak bu, standart tam saha istatistiksel örneği yerine küçük bir modellenen örnekten ve kullanıcı tarafından tahmin edilen bir düzeltmeden elde edilir. Ayrıca, test laterali kasıtlı olarak varsayılan en kötü durum olduğundan, düzeltilmemiş ham ortalaması gerçek saha ortalamasını olduğundan düşük gösterir ve düzgünlüğü olduğundan daha iyi gösterir; Δbasınç girdisi tam olarak bu sapmayı gidermek için vardır. 1\'e eşit veya üzerindeki düzgünlük değerleri yine de mümkündür: bunlar yalnızca son damlatıcının basıncının tahmini saha ortalamasında veya üzerinde olduğu, dolayısıyla en düşük basınç noktasının başka bir damlatıcı olduğu anlamına gelir. Bunun nedeni son damlatıcının alçak zeminde olması veya Δbasınç tahmininin çok küçük olması olabilir. q<sub>last</sub>/q<sub>design</sub> ise üreticinin nominal debisine karşı yapılan farklı, düzgünlükle ilgili olmayan bir kontroldür — sistemin genel olarak aşırı veya yetersiz basınçlandırılmış olduğunu tespit etmek için yararlıdır, ancak düzgünlük sayısıyla birlikte okunması gereken ayrı bir kontroldür, çünkü tasarım/nominal debi, sistemin gerçek ortalama işletme basıncından bağımsızdır.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). “Irrigation by sprinkling.” California Tarımsal Deneme İstasyonu Bülteni 670. ASAE/ASABE mikrosulama tasarımı standartları aynı çok çıkışlı sürtünme-kayıp yaklaşımını kullanır.';
$ec_lang['ip_notes_5_term']='Uygulama Tasarımı';
$ec_lang['ip_notes_5_def']='Uygulama oranı ve sistem/bölge debi tahmini saha-ortalama damlatıcı debisini (q<sub>avg,field</sub> — test lateral\'inin kendi ortalaması, girilen Δbasınç tahmini tarafından düzeltilmiş), tahmin edilen oran değil kullanır: PR = q<sub>avg,field</sub> / A<sub>e</sub>, düzeltilmiş modellenen değer tarafından beslenmiş. Aralık ve sistem-geniş lateral/damlatıcı sayıları ayrı girdilerdir çünkü test yolu sadece bir en kötü durum dalı modeller, sahada her lateral değil.';



// --- Branched Pipe Network (bpn_) --- English source ---
$ec_lang['bpn_main_menu']='Dallı Boru Şebekesi';
$ec_lang['bpn_main_title']='Ücretsiz Çevrimiçi Dallı Boru Şebekesi Basınç Hesaplayıcısı (Döngüsüz)';
$ec_lang['bpn_main_desc']='Dallı (Ağaç) Boru Şebekesi Debi ve Basınç';
$ec_lang['lpn_main_menu']='Halkalı Boru Şebekesi (Harita Arayüzü)';
$ec_lang['lpn_main_title']='Harita Arayüzlü Ücretsiz Çevrimiçi Halkalı Boru Şebekesi Hesaplayıcısı';
$ec_lang['lpn_main_desc']='Harita Üzerinde Çizdiğiniz Halkalı Boru Şebekesinde Basınç ve Debi';
$ec_lang['lpn_tool_select']='Seç';
$ec_lang['lpn_tool_add_junction']='Düğüm';
$ec_lang['lpn_tool_add_reservoir']='Rezervuar';
$ec_lang['lpn_tool_add_pipe']='Boru';
$ec_lang['lpn_tool_add_pump']='Pompa';
$ec_lang['lpn_tool_add_text']='Metin';
$ec_lang['lpn_tool_delete']='Sil';
$ec_lang['lpn_tool_zoom_extent']='Tümünü göster';
$ec_lang['lpn_new_text']='Metin';
$ec_lang['lpn_tool_example']='Örnek şebeke çiz';
$ec_lang['lpn_field_elev']='Kot';
$ec_lang['lpn_field_elev_tip']='Bu düğümdeki zemin veya boru kotu. İstediğiniz herhangi bir sıfır noktasından ölçebilirsiniz, yeter ki tüm düğümler aynı sıfırı kullansın.';
$ec_lang['lpn_field_head']='Yük';
$ec_lang['lpn_field_head_tip']='Rezervuardaki su yüzü kotu, basınç olarak değil yükseklik olarak ölçülür. Su yüzünü rezervuar kotuna yerleştirmek için boş bırakın.';
$ec_lang['lpn_close']='Kapat';
$ec_lang['lpn_empty_hint']='Başlamak için araç çubuğunu kullanarak bir arka plan görüntüsü veya rezervuar ekleyin, ya da örnek bir şebeke çizin.';
$ec_lang['lpn_tool_undo']='Geri al';
$ec_lang['lpn_confirm_example']='Bu, örneği mevcut şebekenize ekler. Devam edilsin mi?';
$ec_lang['lpn_field_diameter']='Çap';
$ec_lang['lpn_demand_tip']='Bu düğümde şebekeden çekilen debi. Buradan şebekeye verilen debi için negatif bir sayı girin.';
$ec_lang['lpn_units_length']='Uzunluk ve harita koordinatları';
$ec_lang['lpn_units_elevhead']='Kot ve yük';
$ec_lang['lpn_units_pressure']='Basınç';
$ec_lang['lpn_units_flow']='Debi';
$ec_lang['lpn_units_velocity']='Hız';
$ec_lang['lpn_result_gradient']='Yük kaybı eğimi';
$ec_lang['lpn_result_gradient_tip']='Yük kaybının boru uzunluğuna bölünmesi. Farklı uzunluktaki boruları tek bir tasarım sınırına göre karşılaştırmak için kullanın.';
$ec_lang['lpn_result_head']='Yük';
$ec_lang['lpn_result_head_tip']='Bu düğümdeki suyun enerjisi, su sütunu yüksekliği olarak ifade edilir. Bu bir yükseklik olup basınç değildir.';
$ec_lang['lpn_result_pressure']='Basınç';
$ec_lang['lpn_result_flow']='Debi';
$ec_lang['lpn_result_velocity']='Hız';
$ec_lang['lpn_result_headloss']='Yük kaybı';
$ec_lang['lpn_settings_restore_tip']='Yalnızca bu projenin ayarlarını sıfırlar. Çiziminiz ve diğer projeleriniz değişmez.';
$ec_lang['lpn_reset_all_tip']='Her projeyi, her arka plan görüntüsünü, her ayarı ve birim seçimlerinizi siler, ardından sayfayı ilk kez ziyaret eden birinin gördüğü haliyle yeniden yükler. Her şeyi temizleyen tek sıfırlama budur.';
$ec_lang['lpn_storage_too_new']='Bu proje, sayfanın daha yeni bir sürümüyle kaydedilmiş, bu yüzden burada açılamaz.';
$ec_lang['lpn_tool_file']='Dosya';
$ec_lang['lpn_menu_edit']='Düzen';
$ec_lang['lpn_menu_insert']='Ekle';
$ec_lang['lpn_menu_view']='Görünüm';
$ec_lang['lpn_menu_settings']='Ayarlar';
$ec_lang['lpn_edit_delete_network']='Şebekeyi sil';
$ec_lang['lpn_confirm_delete_network']='Bu projedeki her düğüm, boru ve metin etiketi silinsin mi? Arka plan görüntüsü, proje adı ve ayarlarınız korunur. Bu işlem geri alınamaz.';
$ec_lang['lpn_view_units']='Birimler';
$ec_lang['lpn_file_saveall']='Tümünü kaydet';
$ec_lang['lpn_project_numbered']='Proje{n}';
$ec_lang['lpn_project_copy_suffix']='(kopya)';
$ec_lang['lpn_project_rename']='Yeniden adlandır';
$ec_lang['lpn_file_new']='Yeni proje';
$ec_lang['lpn_file_open']='Aç…';
$ec_lang['lpn_file_save']='Kaydet';
$ec_lang['lpn_file_saveas']='Farklı kaydet…';
$ec_lang['lpn_file_revert']='Eski haline getir';
$ec_lang['lpn_file_close']='Kapat';
$ec_lang['lpn_tab_new']='Yeni proje';
$ec_lang['lpn_tab_all']='Tüm projeler';
$ec_lang['lpn_tab_menu']='Proje menüsü';
$ec_lang['lpn_tab_duplicate']='Çoğalt';
$ec_lang['lpn_tab_unsaved']='Bir dosyaya kaydedilmedi';
$ec_lang['lpn_import_bad_file']='O dosya, bu sayfadan kaydedilmiş bir proje olarak okunamadı.';
$ec_lang['lpn_import_no_room']='Bu projeyi eklemek için tarayıcı depolama alanında yeterli yer kalmadı. İhtiyacınız olmayan bir projeyi silip tekrar deneyin.';
$ec_lang['lpn_status_imported']='{name} bir dosyadan açıldı ve bu tarayıcıya yeni bir proje olarak eklendi.';
$ec_lang['lpn_file_type_desc']='Proje dosyası';
$ec_lang['lpn_file_upload_explain']='Bu tarayıcı bir dosyaya bağlanamıyor, bu yüzden burada bir dosya açmak aslında bir yükleme işlemidir: proje bu tarayıcıya kopyalanır ve çalışmanızı dosyaya geri kaydetmenin tek yolu, Dosya, Farklı Kaydet ile dosyanın üzerine yazmaktır.';
$ec_lang['lpn_file_save_tip']='Bağlı dosyaya kaydeder.';
$ec_lang['lpn_file_saveas_tip']='Kaydedilecek bir dosya seçin. Bu proje o dosyaya bağlanır ve bundan sonra Kaydet o dosyaya yazar.';
$ec_lang['lpn_file_saveas_tip_download']='Tarayıcınızın İndirme ayarlarını kullanarak kaydeder. Bu tarayıcı bir dosyaya bağlanamadığından Kaydet devre dışıdır, yalnızca Farklı Kaydet kullanılabilir. Tarayıcınızın "Her dosyanın nereye kaydedileceğini sor" ayarını açarsanız, orijinal dosyayı seçip üzerine yazabilirsiniz.';
$ec_lang['lpn_status_uploaded']='Proje dosyası yüklendi. Buna bir bağlantı sürdürülemez, bu yüzden ona geri kaydetmenin tek yolu Dosya, Farklı Kaydet kullanmaktır.';
$ec_lang['lpn_status_downloaded']='{file} indirildi. Bu tarayıcı bir dosyaya bağlanamadığından, bu proje bir dosyaya kaydedilmemiş olarak işaretli kalır.';
$ec_lang['lpn_status_file_opened']='{file} açıldı.';
$ec_lang['lpn_status_already_open']='O dosya burada zaten {name} olarak açık, bu yüzden ikinci bir kopya açmak yerine ona geçildi.';
$ec_lang['lpn_status_already_open_dirty']='O dosya burada zaten {name} olarak açık ve henüz kaydetmediğiniz değişiklikler içeriyor. İkinci bir kopya açmak yerine ona geçildi. Bunun yerine diskteki sürümü istiyorsanız Dosya, Eski Haline Getir\'i kullanın.';
$ec_lang['lpn_status_saved']='{file} kaydedildi.';
$ec_lang['lpn_status_reverted']='{file} diskten yeniden yüklendi.';
$ec_lang['lpn_close_save_prompt']='Kapatmadan önce {name} üzerindeki değişiklikleriniz kaydedilsin mi?';
$ec_lang['lpn_close_browser_prompt']='{name} yalnızca bu tarayıcıda tutuluyor. Bir dosyaya kaydetmeden kapatırsanız, kalıcı olarak kaybolur.';
$ec_lang['lpn_close_discard']='Kaydetmeden kapat';
$ec_lang['lpn_cancel']='İptal';
$ec_lang['lpn_revert_confirm']='Yaptığınız değişiklikler atılsın ve {file} diskten yeniden yüklensin mi?';
$ec_lang['lpn_file_needs_reopen']='Bu proje {file} dosyasından geldi, ancak o dosyayla bağlantı kayboldu. Yeniden bağlanmak için dosyayı tekrar seçin.';
$ec_lang['lpn_file_write_failed']='Dosyaya yazılamadı. Dosya taşınmış veya yeniden adlandırılmış olabilir, ya da izin geri alınmış olabilir. Çalışmanız bu tarayıcıda hâlâ kayıtlıdır.';
$ec_lang['lpn_file_changed_elsewhere']='Siz açtıktan sonra başka biri bu dosyaya kaydetti, bu yüzden şimdi kaydetmek onun çalışmasının üzerine yazar. Değişikliklerinizi kendi dosyanızda tutmak için Dosya, Farklı Kaydet\'i, kendinizinkini atıp onunkini yüklemek için Dosya, Eski Haline Getir\'i kullanın.';
$ec_lang['lpn_lock_prompt_name']='Bu proje sizde açıkken meslektaşlarınız ne görmeli? İsminizin baş harfleri idealdir. Aynı dosyayı açan herkes bunu görebilir, bu yüzden özel bir şey kullanmayın.';
$ec_lang['lpn_lock_somebody']='Başka biri';
$ec_lang['lpn_lock_open_heading']='{name} bu dosyayı açık tutuyor.';
$ec_lang['lpn_lock_open_readonly']='Salt okunur aç';
$ec_lang['lpn_lock_open_copy']='Bir kopya oluştur';
$ec_lang['lpn_lock_break']='Kilidini kaldır';
$ec_lang['lpn_lock_open_heading_times']='{name} bu dosyayı açık tutuyor; son düzenleme {x} önceydi, son kayıttan {y} sonra.';
$ec_lang['lpn_lock_open_heading_unsaved']='{name} bu dosyayı açık tutuyor; son düzenleme {x} önceydi ve henüz hiçbiri bu dosyaya kaydedilmedi.';
$ec_lang['lpn_lock_open_heading_saved']='{name} bu dosyayı açık tutuyor; son düzenleme {x} önceydi ve çalışması dosyaya kaydedildi.';
$ec_lang['lpn_lock_open_heading_seen']='{name} bu dosyayı açık tutuyor ancak henüz düzenlemedi. Tarayıcısı son olarak {x} önce yoklama yaptı.';
$ec_lang['lpn_lock_open_choices']='Seçenekleriniz: (1) İptal edip gerekirse onlardan dosyayı açıp düzgünce kapatmalarını isteyin (tarayıcıyı kapatmak projeyi kapatmaz), (2) Salt okunur açın, ya da (3) hiçbiri işe yaramazsa kilidini kaldırabilirsiniz. Onların kaydedilmemiş çalışması kaybolmaz, ancak sizin değişikliklerinizin üzerine kaydedemezler ve birinin ikisini elle birleştirmesi gerekebilir.';
$ec_lang['lpn_ago_seconds']='{n} saniye';
$ec_lang['lpn_ago_minutes']='{n} dakika';
$ec_lang['lpn_ago_hours']='{n} saat';
$ec_lang['lpn_ago_days']='{n} gün';
$ec_lang['lpn_ago_unknown']='bilinmeyen bir süre';
$ec_lang['lpn_lock_readonly_banner']='Salt okunur: {name} bu dosyayı açık tutuyor. Burada istediğiniz her şeyi değiştirebilirsiniz, ancak kaydedemezsiniz. Farklı bir dosyaya kaydetmek için Dosya, Farklı Kaydet\'i kullanın.';
$ec_lang['lpn_lock_unavailable']='Dikkat: bu proje üzerinde bir kilidi kontrol etmek veya oluşturmak için sunucuya ulaşılamadı, bu yüzden bir meslektaşınızın aynı dosyayı aynı anda düzenlemesini hiçbir şey engellemiyor. Kilitleme yeniden çalışmaya başlarsa size bildirilecektir.';
$ec_lang['lpn_lock_storage_error']='Dikkat: bu site kilit kayıtlarını kaydedemiyor, bu yüzden bir meslektaşınızın aynı dosyayı aynı anda düzenlemesini hiçbir şey engellemiyor. Bu, sunucudaki bir kurulum hatasıdır, burada düzeltebileceğiniz bir şey değildir — kilit klasörü web sunucusu tarafından yazılabilir değil.';
$ec_lang['lpn_lock_full_error']='Dikkat: bu site kimin hangi projeyi açık tuttuğunu kaydedecek yerinin tükendi, bu yüzden bir meslektaşınızın aynı dosyayı aynı anda düzenlemesini hiçbir şey engellemiyor. Bu, sunucudaki bir kurulum hatasıdır, burada düzeltebileceğiniz bir şey değildir.';
$ec_lang['lpn_lock_not_asked']='Bu proje için kilitleme çalışmıyor, bu yüzden bir meslektaşınızın aynı dosyayı aynı anda düzenlemesini hiçbir şey engellemiyor. Bu tarayıcıda sizin için henüz kayıtlı bir isim yok veya projenin bir tanımlayıcısı yok — projeyi bir dosyaya kaydetmek ikisini de belirler.';
$ec_lang['lpn_lock_restored']='Kilitleme yeniden çalışıyor ve bu dosya artık sizin kaydedebileceğiniz bir dosya.';
$ec_lang['lpn_lock_dismiss']='Bu mesajı gizle';
$ec_lang['lpn_file_training_1']='Projeniz bu bilgisayardaki bir dosyaya kaydedilecek. Yalnızca siz istediğinizde kaydedilir, başka hiçbir zaman değil, bu yüzden o dosyaya haberiniz olmadan hiçbir şey yazılmaz.';
$ec_lang['lpn_file_training_2']='İki kişinin aynı dosyayı aynı anda düzenlememesi için bu site kimin dosyayı açık tuttuğunu takip eder. Biri zaten açmışsa, yine de açıp bakabilir veya kendi kopyanızı tutabilirsiniz.';
$ec_lang['lpn_file_training_permission']='İlk kaydettiğinizde, tarayıcınız bu sitenin dosyayı düzenleyip düzenleyemeyeceğini soracaktır. Bu soru bizden değil tarayıcınızdan gelir ve evet demeniz, Kaydet\'in çalışmanızı geri yazmasını sağlar. Genellikle dosya başına yalnızca bir kez sorulur.';
$ec_lang['lpn_file_training_3']='Meslektaşlarınızın sizi tanıyacağı kısa bir isim verin. İsminizin baş harfleri idealdir. Aynı dosyayı açan herkes bunu görebilir, bu yüzden özel bir şey kullanmayın.';
$ec_lang['lpn_file_training_name']='İsminizin baş harfleri';
$ec_lang['lpn_file_training_continue']='Devam et';
$ec_lang['lpn_file_relink']='Dosyayı tekrar seçin';
$ec_lang['lpn_file_reconnect']='Bu dosyayla yeniden bağlan';
$ec_lang['lpn_file_reconnect_prompt']='Bu proje {file} dosyasından geldi. Tarayıcınızın ona yazabilmesi için izninize yeniden ihtiyacı var. Aşağıdan yeniden bağlanın.';
$ec_lang['lpn_saveas_same_file']='Bu, başka birinin açık tuttuğu aynı dosya, bu yüzden üzerine kaydedilemez. Farklı bir dosya veya farklı bir isim seçin.';
$ec_lang['lpn_saveas_overwrites_project']='O dosya zaten farklı bir proje içeriyor, {name}. Buraya kaydetmek onu tamamen değiştirir. Devam edilsin mi?';
$ec_lang['lpn_saveas_overwrites_newer']='O dosya siz son gördüğünüzden beri değişti, bu yüzden neredeyse kesinlikle başka biri ona kaydetti. Buraya kaydetmek onun sürümünü sizinkiyle değiştirir. Devam edilsin mi?';
$ec_lang['lpn_prompt_project_name']='Bu proje için isim';
$ec_lang['lpn_status_closed_opened']='{closed} kapatıldı. Şimdi {opened} gösteriliyor.';
$ec_lang['lpn_status_closed_empty']='{closed} kapatıldı. Yeni boş bir proje başlatıldı.';
$ec_lang['lpn_storage_full']='Kaydedilmedi. Tarayıcı depolama alanı dolu veya kullanılamıyor, bu yüzden bu sekmeyi kapattığınızda son değişiklikleriniz kaybolacak.';
$ec_lang['lpn_notes_1_term']='Kararlı durum';
$ec_lang['lpn_notes_1_def']='EPANET\'in kullandığı aynı küresel gradyan algoritmasını kullanarak seferde bir talep kümesini çözer. Şebekenin zaman içinde nasıl değiştiğini modellemez.';
$ec_lang['lpn_notes_2_term']='Modellenmeyenler';
$ec_lang['lpn_notes_2_def']='Depolar, su kalitesi ve kendi kendine açılıp kapanan kontrol vanaları (PRV, PSV, FCV) modellenmez. Bir boru sabit bir yerel kayıp taşıyabilir, ancak açık veya kapalı durumu çözülmekte olan debiye bağlı bir vana taşıyamaz.';
$ec_lang['lpn_notes_3_term']='Projeleri kaydetme';
$ec_lang['lpn_notes_3_def']='Her proje bir sekmedir ve çalışırken her sekme bu tarayıcıya kaydedilir. Tarayıcı verilerinizi temizlemek hepsini siler, bu yüzden çalışmanızı bir dosyada tutun: Dosya, Farklı Kaydet. Bir sekmedeki yıldız işareti, bir dosyada olmayan değişiklikler taşıdığı anlamına gelir. Siz istemedikçe hiçbir şey bir dosyaya yazılmaz. Bazı tarayıcılarda bir proje, kaydettiğiniz dosyaya bağlanır ve Dosya, Kaydet bundan sonra o aynı dosyaya geri yazar; diğerlerinde bağlantı mümkün değildir, bu yüzden Kaydet devre dışıdır ve yalnızca Farklı Kaydet kullanılabilir. Bir proje dosyası paylaşılan bir sürücüde tutulduğunda, bu sayfa bir meslektaşınızın onu zaten açık tutup tutmadığını size söyler, böylece iki kişi birbirinin üzerine yazmaz.';
$ec_lang['lpn_notes_5_term']='Pompa eğrisi';
$ec_lang['lpn_notes_5_def']='Bir pompa H = H₀ − aQ^b denklemini izler; burada H pompanın eklediği yük, Q ise içinden geçen debidir. Üreticinin eğrisinden bir, iki veya üç nokta girin. Üç nokta — sıfır debideki yük, normal çalışma noktası ve en yüksek debi noktası — H₀, a ve b\'yi doğrudan belirler ve yayımlanan bir eğriyi en yakından izler. İki nokta, tepe noktası sıfır debide olan bir parabole (b = 2) oturtulur. Tek nokta yaygın bir kural kullanır: sıfır debideki yük, girdiğiniz yükün 1,33 katıdır ve en yüksek debi, girdiğiniz debinin 2 katıdır; bu da yine b = 2 verir. Hiç nokta girilmemiş bir pompa hiç yük eklemez. Eğri sıfırda durdurulmaz, bu yüzden bir pompadan eğrisinin sağlayabileceğinden daha fazla debi istemek negatif bir yük verir. Çözüm daha büyük bir pompa veya daha küçük bir taleptir, farklı bir eğri uydurması değil.';
$ec_lang['lpn_notes_4_term']='Planlanan';
$ec_lang['lpn_notes_4_def']='Bir projenin birden çok talep kümesini tutabilmesi için senaryolar. Düğüm ve boru sonuçlarının tabloları. Son kullandığınız bir dosyayı yeniden aramadan açmak. EPANET .inp dosyalarını okuma ve yazma. Yorum ve önerileriniz her zaman memnuniyetle karşılanır (yukarıdaki geri bildirim bağlantısına bakın).';
$ec_lang['lpn_notes_epanet_term']='Hazen-Williams sabitleri artık EPANET ile eşleşiyor';
$ec_lang['lpn_notes_epanet_def']='Ağustos 2026\'da Hazen-Williams katsayısı ve üssü, EPANET ile eşleşecek şekilde değiştirildi. Yük kaybı sonuçları bu sayfanın önceki sürümlerinden en fazla yüzde 0,1 farklıdır; bu, C değerinin kendisindeki belirsizlikten çok daha küçüktür.';
$ec_lang['lpn_id_invalid']='Boşluk ve tırnak işareti içermeyen bir kimlik girin.';
$ec_lang['lpn_id_taken']='Bu kimlik zaten kullanılıyor.';
$ec_lang['lpn_diag_no_fixed_head']='Bir rezervuar ekleyin. Şebekenin çözülebilmesi için en az bir bilinen su seviyesine ihtiyacı var.';
$ec_lang['lpn_diag_dangling_link']='Bir boru veya pompa, artık var olmayan bir düğüme bağlanıyor:';
$ec_lang['lpn_diag_unreachable']='Bu düğümlerin bir rezervuara giden yolu yok:';
$ec_lang['lpn_diag_not_converged']='Bir çözüm bulunamadı. Sıfır çap gibi gerçek olamayacak değerleri kontrol edin.';
$ec_lang['lpn_field_roughness']='Pürüzlülük';
$ec_lang['lpn_field_roughness_tip']='Hazen-Williams C. Daha yüksek bir sayı daha pürüzsüz bir boru anlamına gelir: yeni plastik için yaklaşık 150, yeni çelik veya demir için 130 ve eski boru için 100.';
$ec_lang['lpn_field_length']='Uzunluk';
$ec_lang['lpn_field_length_tip']='Borunun uzunluğu. Otomatik açıkken bu, çizdiğinizi izler. Çizimden farklı bir uzunluk yazmak için Otomatik\'i kapatın.';
$ec_lang['lpn_field_km']='Küçük (yerel) kayıp katsayısı, k';
$ec_lang['lpn_field_km_tip']='Bu borudaki dirsek, vana ve bağlantı parçalarından kaynaklanan kayıp, hız yükünün bir katı olarak sayılır. Düz bir boru için 0 kullanın.';
$ec_lang['lpn_field_km_short']='Küçük kayıp, k';
$ec_lang['lpn_pump_curve_source']='Eğri kaynağı';
$ec_lang['lpn_pump_curve_own']='Noktaları aşağıya girin';
$ec_lang['lpn_pump_curve_ref_note']='Pompa {id} için girilen eğri kullanılıyor.';
$ec_lang['lpn_pump_curve_note']='Bir, iki veya üç nokta — aşağıdaki Notlar\'da "Pompa eğrisi"ne bakın.';
$ec_lang['lpn_pump_point1']='Nokta 1 (zorunlu)';
$ec_lang['lpn_pump_point2']='Nokta 2 (isteğe bağlı)';
$ec_lang['lpn_pump_point3']='Nokta 3 (isteğe bağlı)';
$ec_lang['lpn_mode_select']='Mod: Seç. Görmek veya değiştirmek için bir öğeye veya etikete tıklayın. Bir düğümü, kırılma noktasını veya etiketi taşımak için sürükleyin. Bir kırılma noktası eklemek veya kaldırmak için bir boruya çift tıklayın.';
$ec_lang['lpn_mode_delete']='Mod: Sil. Kaldırmak için bir öğeye tıklayın.';
$ec_lang['lpn_mode_add_junction']='Mod: Düğüm Ekle. Bir düğüm yerleştirmek için haritaya tıklayın. Öğeleri ve etiketleri değiştirmek veya taşımak için Seç moduna geçin.';
$ec_lang['lpn_mode_add_reservoir']='Mod: Rezervuar Ekle. Bir rezervuar yerleştirmek için haritaya tıklayın. Öğeleri ve etiketleri değiştirmek veya taşımak için Seç moduna geçin.';
$ec_lang['lpn_mode_add_pipe']='Mod: Boru Ekle. Bağlamak için bir düğüme, ardından başka bir düğüme tıklayın. Öğeleri ve etiketleri değiştirmek veya taşımak için Seç moduna geçin.';
$ec_lang['lpn_mode_add_pump']='Mod: Pompa Ekle. Bağlamak için bir düğüme, ardından başka bir düğüme tıklayın. Öğeleri ve etiketleri değiştirmek veya taşımak için Seç moduna geçin.';
$ec_lang['lpn_mode_add_text']='Mod: Metin Ekle. Bir metin etiketi yerleştirmek için haritaya tıklayın. Metni bir düğüme bağlamak için ona yakın bir yere tıklayın. Öğeleri ve etiketleri değiştirmek veya taşımak için Seç moduna geçin.';
$ec_lang['lpn_tip_select']='Haritadaki şeyleri değiştirmek, taşımak ve sürüklemek için bu modu kullanın.';
$ec_lang['lpn_tip_labels_draggable']='Bir etiketi taşımak için sürükleyebilirsiniz. Bir etiketi yerine geri koymak için çift tıklayın.';
$ec_lang['lpn_field_auto']='Otomatik';
$ec_lang['lpn_field_x']='X';
$ec_lang['lpn_field_y']='Y';
$ec_lang['lpn_field_text_size']='Boyut çarpanı';
$ec_lang['lpn_tool_labels']='Etiketler';
$ec_lang['lpn_labels_heading_node']='Düğüm etiketleri';
$ec_lang['lpn_labels_heading_link']='Hat etiketleri';
$ec_lang['lpn_labels_decimals_tip']='Bu etiket için gösterilen ondalık basamak sayısı';
$ec_lang['lpn_labels_mark_extrema']='En yüksek ve en düşük değerleri işaretle';
$ec_lang['lpn_field_id']='ID';
$ec_lang['lpn_backdrop_menu']='Arka plan görüntüsü...';
$ec_lang['lpn_backdrop_add']='Görüntü ekle';
$ec_lang['lpn_backdrop_scale']='Görüntü ölçeğini ayarla';
$ec_lang['lpn_backdrop_position']='Görüntüyü taşı';
$ec_lang['lpn_backdrop_remove']='Görüntüyü kaldır';
$ec_lang['lpn_backdrop_remove_confirm']='Arka plan görüntüsü kaldırılsın mı?';
$ec_lang['lpn_backdrop_scale_prompt1']='Arka plan görüntüsü üzerinde iki nokta tıklayın, örneğin bir ölçek çubuğunun iki ucu. Ardından aralarındaki gerçek mesafeyi yazın.';
$ec_lang['lpn_backdrop_scale_prompt2']='İki nokta arasındaki gerçek mesafe';
$ec_lang['lpn_backdrop_position_prompt1']='Arka plan görüntüsü üzerinde herhangi bir noktaya tıklayın. Bu, taşıyacağınız nokta olacak.';
$ec_lang['lpn_backdrop_position_prompt2']='O noktanın nereye gitmesi gerektiğini seçin, ardından Devam Et\'e tıklayın.';
$ec_lang['lpn_backdrop_target_label']='Şuraya taşı:';
$ec_lang['lpn_backdrop_target_node']='Bir düğüm';
$ec_lang['lpn_backdrop_target_free']='Harita üzerinde herhangi bir nokta';
$ec_lang['lpn_backdrop_target_coords']='Yazılan koordinatlar';
$ec_lang['lpn_backdrop_coords_prompt']='O noktanın taşınacağı X,Y\'yi yazın';
$ec_lang['lpn_backdrop_continue']='Devam et';
$ec_lang['lpn_tool_settings']='Ayarlar';
$ec_lang['lpn_settings_id_prefixes']='Kimlik önekleri';
$ec_lang['lpn_settings_defaults']='Başlangıç değerleri';
$ec_lang['lpn_settings_defaults_note']='Bundan sonra oluşturacağınız öğeler için kullanılır. Mevcut öğeler değişmez.';
$ec_lang['lpn_settings_push_note']='Yalnızca şu anda etiketleri gösterilen özellikler uygulanır.';
$ec_lang['lpn_settings_push_btn']='Başlangıç değerlerini tüm öğelere uygula';
$ec_lang['lpn_push_confirm']='Bu özellikler mevcut her öğede geçerli başlangıç değerleriyle değiştirilsin mi? Yazdığınız değerlerin üzerine yazılır. Bunu geri alabilirsiniz.';
$ec_lang['lpn_push_properties']='Özellikler:';
$ec_lang['lpn_push_elements']='Düğümler ve borular:';
$ec_lang['lpn_push_none_displayed']='Şu anda etiket olarak gösterilen bir başlangıç değeri yok, bu yüzden uygulanacak bir şey yok. İstediğiniz özelliklerin etiketlerini Etiketler panelinde açın, ardından tekrar deneyin.';
$ec_lang['lpn_push_nothing']='Mevcut hiçbir öğe, uygulanan özelliklerden hiçbirine sahip değil.';
$ec_lang['lpn_push_no_change']='Her öğe bu değerlere zaten sahip, bu yüzden hiçbir şey değişmez.';
$ec_lang['lpn_settings_emitter_exponent']='Emiter üssü';
$ec_lang['lpn_settings_tolerance']='Yakınsama toleransı';
$ec_lang['lpn_settings_tolerance_tip']='Çözücünün durmadan önce ne kadar yaklaşması gerektiği. Daha küçük bir sayı daha kesindir ve daha uzun sürer.';
$ec_lang['lpn_settings_text_size']='Metin boyutu';
$ec_lang['lpn_settings_text_size_map']='Harita mesafesi';
$ec_lang['lpn_settings_text_size_screen']='Ekran pikseli';
$ec_lang['lpn_settings_symbol_size']='Sembol boyutu (metne göre)';
$ec_lang['lpn_settings_symbol_opacity']='Sembol opaklığı (0 ile 1 arası)';
$ec_lang['lpn_settings_backdrop_opacity']='Arka plan görüntüsü opaklığı (0 ile 1 arası)';
$ec_lang['lpn_settings_text_size_units']='Metin boyutu birimleri';
$ec_lang['lpn_settings_map_display']='Harita görünümü';
$ec_lang['lpn_settings_map_height_px']='Harita yüksekliği (ekran pikseli)';
$ec_lang['lpn_settings_map_height_tip']='Küçük bir ekranda harita bundan daha kısa çizilir, böylece sayfanın bir kısmı her zaman kaydırılabilir kalır.';
$ec_lang['lpn_settings_legend_position']='Lejant konumu';
$ec_lang['lpn_settings_legend_top_left']='Sol üst';
$ec_lang['lpn_settings_legend_top_right']='Sağ üst';
$ec_lang['lpn_settings_legend_middle_left']='Sol orta';
$ec_lang['lpn_settings_legend_middle_right']='Sağ orta';
$ec_lang['lpn_settings_legend_bottom_left']='Sol alt';
$ec_lang['lpn_settings_legend_bottom_right']='Sağ alt';
$ec_lang['lpn_confirm_restore_defaults']='Tüm ayarlar (kimlik önekleri, başlangıç değerleri, çözücü ayarları, harita görünümü, lejant konumu ve görünür etiketler) orijinal değerlerine sıfırlansın mı? Şebekeniz değişmez. Ayarlar açık projeye aittir, bu yüzden diğer projeleriniz kendi ayarlarını korur.';
$ec_lang['lpn_settings_wipe_btn']='Bu sayfadaki her şeyi sil';
$ec_lang['lpn_confirm_wipe']='Bu sayfa için kaydedilmiş HER ŞEY — her proje, her arka plan görüntüsü, tüm ayarlar ve birim seçimleriniz — silinsin ve sayfa yepyeni bir ziyaretçinin göreceği gibi yeniden yüklensin mi? Bu işlem geri alınamaz.';
$ec_lang['bpn_h_source_tip']='Statik besleme yükü: sıfır debideki kaynak yükü. Besleme kotunun üzerindeki bir rezervuar veya tank su yüzü kotu, ya da bir pompanın kapatma yükü. Bir pompa veya değişken besleme eğrisi tanımlamak için 2 ve 3 numaralı besleme noktalarını ekleyin; araç, tasarım debisindeki yükü okur.';
$ec_lang['bpn_elev_source']='Besleme kotu';
$ec_lang['bpn_q_total']='Toplam debi';
$ec_lang['bpn_q_total_tip']='Kaynaktan çıkan toplam debi (şebekedeki tüm talep debilerinin toplamı).';
$ec_lang['bpn_p_min']='En düşük basınç';
$ec_lang['bpn_p_min_tip']='Şebekede herhangi bir yerdeki en düşük mansap basıncı; kritik teslim noktası.';
$ec_lang['bpn_method']='Sürtünme yöntemi';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='Boru hatları';
$ec_lang['bpn_id']='ID';
$ec_lang['bpn_id_tip']='Bu boru hattının adı. Diğer hatlar, Memba sütununda bu hatta atıfta bulunur.';
$ec_lang['bpn_upstream']='Memba ID';
$ec_lang['bpn_upstream_tip']='Bu hattı besleyen hattın ID\'si. Doğrudan üstündeki hattı izlemesi için boş bırakın (düz bir seri boru hattı). Farklı bir hattan dallanmak için buraya bir ID girin.';
$ec_lang['bpn_roughness_tip']='Seçilen sürtünme yöntemi için boru pürüzlülüğü: Manning n, Hazen-Williams C veya Darcy-Weisbach pürüzlülük yüksekliği e (bir uzunluk). Tipik düz plastik boru: n yaklaşık 0,009, C yaklaşık 150, e yaklaşık 0,0015 mm.';
$ec_lang['bpn_demand']='Talep';
$ec_lang['bpn_demand_tip']='Bu hattın mansap ucunda teslim edilen sabit debi. Yalnızca akışı ileriye taşıyan bir hat için boş bırakın.';
$ec_lang['bpn_demand_mult']='Talep çarpanı';
$ec_lang['bpn_demand_mult_tip']='Tepe saat veya gelecekteki büyüme senaryosu için tüm hat taleplerini aynı anda ölçeklendirir. Girildiği gibi talepler için 1 kullanın.';
$ec_lang['bpn_elev_down']='MS kot.';
$ec_lang['bpn_q_line']='Hat debisi';
$ec_lang['bpn_q_line_tip']='Bu hattın taşıdığı toplam debi: kendi talebi artı beslediği tüm mansap taleplerinin toplamı.';
$ec_lang['bpn_p_down']='MS basınç';
$ec_lang['bpn_p_down_tip']='Bu hattın mansap düğümündeki manometrik basınç yükü. Negatif bir değer (işaretlenir), atmosfer altı basınç anlamına gelir; tasarımı kontrol edin.';
$ec_lang['bpn_sketch_title']='Şebeke Şeması';
$ec_lang['bpn_show_length']='Uzunluk';
$ec_lang['bpn_show_diameter']='Çap';
$ec_lang['bpn_show_q']='Debi';
$ec_lang['bpn_show_p']='Basınç';
$ec_lang['bpn_source_label']='Kaynak';
$ec_lang['bpn_topology_warn']='Memba sütununu kontrol edin: bir hat bilinmeyen bir ID\'ye işaret ediyor, kendine atıfta bulunuyor veya bir döngü oluşturuyor; bu nedenle şebekenin bir kısmı kaynağa bağlı değil. Bu hatlar çözülmeden bırakılır.';
$ec_lang['bpn_topology_warn_short']='Şebeke';
$ec_lang['bpn_pressure_warn']='Düşük/negatif basınç; atmosfer altı koşulları kontrol edin';
$ec_lang['bpn_pressure_warn_short']='Düşük';
$ec_lang['bpn_notes_1_term']='Varsayılan olarak seri, istisna olarak dallanma';
$ec_lang['bpn_notes_1_def']='Memba ID\'sini boş bırakırsanız, hat üstündeki hattı izler; düz bir seri boru hattı. Bir hattan dallanmak için o hattın ID\'sini girin. Yani: varsayılan olarak seri, gerektiğinde bir ağaç.';
$ec_lang['bpn_notes_2_term']='Yalnızca dallı şebekeler, döngü yok';
$ec_lang['bpn_notes_2_def']='Her hattın tam olarak bir memba hattı vardır (bir ağaç). Bu araç döngülü şebekeleri çözmez; bunlar yinelemeli yöntemler gerektirir (EPANET veya benzeri). Döngüleri dışarıda bırakmak, aracı basit ve kesin tutar.';
$ec_lang['bpn_notes_3_term']='Aktif basınç kontrolü yok';
$ec_lang['bpn_notes_3_def']='Sabit bir yerel kayıp vanası (bir k değeri) ekleyebilirsiniz, ancak basınç düşürücü veya basınç sürdürücü vanalar (PRV/PSV) ekleyemezsiniz. Bunların açık/kapalı durumu debiye ve basınca bağlıdır, bu da yinelemeyi zorunlu kılar.';
$ec_lang['bpn_notes_epanet_term']='Hazen-Williams sabitleri artık EPANET ile aynı (Ağustos 2026)';
$ec_lang['bpn_notes_epanet_def']='Ağustos 2026\'da Hazen-Williams katsayısı ve üssü, EPANET ile aynı olacak şekilde değiştirildi. Yük kaybı sonuçları bu sayfanın önceki sürümlerinden en fazla yüzde 0,1 farklıdır; bu, C değerinin kendi belirsizliğinden çok daha küçüktür.';
$ec_lang['bpn_supply2_q']='Besleme debisi 2';
$ec_lang['bpn_supply2_h']='Besleme yükü 2';
$ec_lang['bpn_supply3_q']='Besleme debisi 3';
$ec_lang['bpn_supply3_h']='Besleme yükü 3';
$ec_lang['bpn_supply_pt_tip']='İsteğe bağlı besleme eğrisi noktaları 2 ve 3. Bir pompayı veya daha fazla debi verdikçe yükü düşen herhangi bir kaynağı modellemek için her biri için bir debi ve yük girin; araç, tasarım debisindeki yükü okur. Yukarıdaki 1. nokta, sıfır debideki statik yüktür. Sabit bir rezervuar yükü için 2 ve 3\'ü boş bırakın.';
$ec_lang['bpn_h_supply']='Besleme yükü';
$ec_lang['bpn_h_supply_tip']='Besleme eğrisinden okunan, tasarım debisindeki kaynak yükü. Eğri düz olduğunda (bir rezervuar) girilen kaynak yüküne eşittir.';
$ec_lang['bpn_show_elevation']='Kot';
$ec_lang['bpn_supply1_h']='Statik besleme yükü';
