<?php

// All missing text declarations will fall back to English.

$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// Note: In the process of rearranging the language variables into page order for easier maintenance.
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Протицај у цевима по Manningu';
$ec_lang['mpf_main_title']='Бесплатни онлајн калкулатор протицаја у цевима по Manningu';
$ec_lang['mpf_main_desc']='Манингова формула равномерног тецања у цевима при задатом паду и дубини';
$ec_lang['mpf_pipe_diameter']='Prečnik cevi, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manningov koeficijent hrapavosti, n';
$ec_lang['mpf_friction_slope']='Linijski gubitak pritiska (moguće <a target="_blank" href="../pressureslope.php">?</a> jednak nagibu cijevi), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Udeo ispunjenosti cevi (u % visine prečnika)';
$ec_lang['mpf_flow']='Protoka, q';
$ec_lang['mpf_velocity']='Tečenja, v';
$ec_lang['mpf_velocity_head']='Energija tečenja, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Površina preseka';
$ec_lang['mpf_wetted_perimeter']='Okvašeni obim, O';
$ec_lang['mpf_hydraulic_radius']='Hidraulički radijus, R';
$ec_lang['mpf_top_width']='Najveća širina, T';
$ec_lang['mpf_froude_number']='Frudov broj, F';
$ec_lang['mpf_shear_stress']='Napon smicanja average (vučna sila), tau';
$ec_lang['mpf_solve_for_dd0']='Израчунај y/d<sub>0</sub> за дато Q';
$ec_lang['mpf_solve_desc']='Користећи D<sub>0</sub>, n и S<sub>0</sub> из формулара калкулатора, проналази најмањи y/d<sub>0</sub> за дато Q.';
$ec_lang['mpf_solve_button']='Израчунај';
// Orifice Flow
$ec_lang['or_main_menu']='Протицај кроз отвор';
$ec_lang['or_main_title']='Бесплатни онлајн калкулатор протицаја кроз отвор';
$ec_lang['or_main_desc']='Протицај кроз отвор — Слободан или потопљен';
$ec_lang['or_shape']='Облик отвора';
$ec_lang['or_shape_circular']='Кружни';
$ec_lang['or_shape_rectangular']='Правоугаони';
$ec_lang['or_diameter']='Пречник (кружни) или висина (правоугаони), D';
$ec_lang['or_width']='Ширина, W (само правоугаони)';
$ec_lang['or_invert']='Кота дна отвора';
$ec_lang['or_hwe']='Кота узводног нивоа воде';
$ec_lang['or_twe']='Кота низводног нивоа воде';
$ec_lang['or_cd']='Коефицијент протицаја, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Кота тежишта';
$ec_lang['or_head']='Ефективна висина, h';
$ec_lang['or_area']='Површина отвора, A';
$ec_lang['or_flow']='Протицај, Q';
$ec_lang['or_velocity']='Брзина на отвору, v';
$ec_lang['or_regime']='Провера режима отвора';
$ec_lang['or_regime_valid']='Слободно истицање — режим отвора валидан ✓';
$ec_lang['or_regime_submerged']='Потопљен отвор (TWE изнад дна) — валидно ✓';
$ec_lang['or_regime_warn']='Упозорење: узводни ниво испод темена — није режим отвора';
$ec_lang['or_regime_twe_above_hwe']='Упозорење: низводни ниво (TWE) изнад узводног нивоа (HWE) — проверите улазне вредности';
$ec_lang['or_notes_1_term']='Једначина отвора';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Слободно истицање: h = HWE &minus; тежиште. Потопљени (TWE изнад дна): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Режим отвора';
$ec_lang['or_notes_2_def']='Једначине протицаја кроз отвор примењују се када је узводни ниво изнад темена отвора. Када је испод темена, користите једначину прелива.';
$ec_lang['or_notes_3_term']='Коефицијент протицаја';
$ec_lang['or_notes_3_def']='C<sub>d</sub> је приближно 0,60&ndash;0,65 за оштроивичне отворе. Заобљени или увучени улази имају различите вредности. Погледајте <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> или HEC-RAS Хидраулички приручник.';
$ec_lang['or_notes_4_term']='Потапање';
$ec_lang['or_notes_4_def']='Када је TWE изнад дна отвора, калкулатор аутоматски примењује једначину потопљеног отвора са h = HWE &minus; TWE. Када је TWE на нивоу или испод дна, претпоставља се слободно истицање и h = HWE &minus; тежиште.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Време пражњења кроз отвор';
$ec_lang['odt_main_title']='Бесплатни онлајн калкулатор времена пражњења кроз отвор — Акумулација, базен или резервоар';
$ec_lang['odt_main_desc']='Време пражњења акумулације или базена кроз отвор &mdash; Метод конусне запремине';
$ec_lang['odt_h1_elev']='Почетна кота нивоа воде';
$ec_lang['odt_a1']='Почетна површина акумулације или базена, A1';
$ec_lang['odt_h2_elev']='Завршна кота нивоа воде';
$ec_lang['odt_h_orifice']='Кота тежишта отвора';
$ec_lang['odt_a0']='Површина акумулације или базена на коти отвора, A0';
$ec_lang['odt_a_ending']='Завршна површина акумулације, A2 (интерполовано)';
$ec_lang['odt_h2_check']='Провера завршне коте';
$ec_lang['odt_h2_ok']='Завршна кота изнад врха отвора ✓';
$ec_lang['odt_h2_warn']='Упозорење: завршна кота на нивоу или испод врха отвора (тежиште + D/2)';
$ec_lang['odt_d']='Пречник отвора (кружни) или висина (правоугаони), D';
$ec_lang['odt_w']='Ширина отвора, W (само правоугаони)';
$ec_lang['odt_t_sec']='Време пражњења (секунде)';
$ec_lang['odt_t_min']='Време пражњења (минути)';
$ec_lang['odt_t_hr']='Време пражњења (сати)';
$ec_lang['odt_t_day']='Време пражњења (дани)';
$ec_lang['odt_notes_1_term']='Формула';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) даје време пражњења од висине H до отвора. Време пражњења = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), где је H<sub>1</sub> = почетна кота &minus; кота отвора, H<sub>2</sub> = завршна кота &minus; кота отвора.';
$ec_lang['odt_notes_2_term']='Метод';
$ec_lang['odt_notes_2_def']='Метод конусне запремине моделује акумулацију или базен као конусни пресек између почетне површине A<sub>1</sub> на почетном нивоу воде и површине A<sub>0</sub> на коти тежишта отвора. A<sub>2</sub>, површина акумулације на завршној коти, интерполује се из A<sub>1</sub> и A<sub>0</sub> помоћу модела конусног пресека. Време пражњења од почетне до завршне коте једнако је укупном времену пражњења од H<sub>1</sub> до отвора умањеном за преостало време пражњења од H<sub>2</sub> до отвора.';
$ec_lang['odt_h1']='Почетни напор, H<sub>1</sub> (WSE &minus; тежиште)';
$ec_lang['odt_q_max']='Максимални (почетни) протицај, Q<sub>max</sub>';
$ec_lang['odt_vol']='Испражњена запремина';
$ec_lang['odt_sketch_start']='Почетак';
$ec_lang['odt_sketch_end']='Крај';

// Units
$ec_lang['u_depthFrac']='разломак';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% пад/хоризонтала';
$ec_lang['u_grade']='пад/хоризонтала';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
// Menu and General
$ec_lang['menu_brand']='HawsEDC Калкулатори';
$ec_lang['menu_main_list']='Листа калкулатора';
$ec_lang['menu_main_hydraulics']='Хидраулика';
$ec_lang['menu_main_language']='Језик';
$ec_lang['template_welcome']='&gt;&gt; Оставите страхове за вратима; овде је љубав наш језик. Не кварите све. Уживајте и у <a target="_blank" href="https://hawsedc.com/download.php">бесплатним HawsEDC AutoCAD алатима</a>. &lt;&lt;';
$ec_lang['template_translation_help']='Имате ли одличну идеју за калкулатор који би требало додати овде?  Можете ли помоћи у побољшању превода, програмирању или хостовању ових калкулатора?  ';
$ec_lang['template_feedback']='Молимо вас да нам дате своје вредне сугестије или похвале. Да ли је овај бесплатни калкулатор превазишао ваша очекивања у сваком погледу?';
$ec_lang['template_printable_title']='Наслов за штампу';
$ec_lang['template_printable_subtitle']='Поднаслов за штампу';
$ec_lang['index_title']='Бесплатни онлајн инжењерски калкулатори';
$ec_lang['calc_set_units']='Подеси јединице:';
$ec_lang['calc_inputs']='Улазне вредности';
$ec_lang['calc_results']='Резултати';
$ec_lang['view_hide_line']='[Сакриј овај ред]';
$ec_lang['view_printable']='Верзија за штампу (освежите страницу да бисте вратили)';
$ec_lang['points_data_help']='(или Копирај/Налепи помоћу поља за податке)';
$ec_lang['points_data_title']='Подаци тачака<br />(одвојени зарезом или табулатором)';
$ec_lang['points_data_copy']='Копирај';
$ec_lang['points_data_paste']='Налепи';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='Губитак напора у цевима по Darcy-Weisbachу';
$ec_lang['dw_main_title']='Бесплатни онлајн калкулатор губитка напора у цевима по Darcy-Weisbachу';
$ec_lang['dw_main_desc']='Губитак напора у цевима по Darcy-Weisbachу при задатом пречнику, храпавости и протицају';
$ec_lang['dw_roughness']='Апсолутна храпавост по Darcy-Weisbachу, e';
$ec_lang['dw_kinematic_viscosity']='Кинематичка вискозност, v, у m<sup>2</sup>/sec (1E-6 за чисту воду на собној температури)';
$ec_lang['dw_reynolds_number']='Рејнолдсов број, Re';
$ec_lang['dw_flow_regime']='Режим тецања';
$ec_lang['dw_regime_laminar']='ламинарно';
$ec_lang['dw_regime_transitional']='прелазно';
$ec_lang['dw_regime_turbulent']='турбулентно';
$ec_lang['dw_friction_factor_method']='Метод фактора трења';
$ec_lang['dw_friction_factor']='Фактор трења, f';
// Hazen-Williams
$ec_lang['hw_main_menu']='Губитак напора у цевима по Hazen-Williamsu';
$ec_lang['hw_main_title']='Бесплатни онлајн калкулатор губитка напора у цевима по Hazen-Williamsu';
$ec_lang['hw_main_desc']='Губитак напора у цевима по Hazen-Williamsu при задатом пречнику, храпавости и протицају';
$ec_lang['hw_hgl_1']='Низводна HGL';
$ec_lang['hw_hgl_2']='Узводна HGL';
$ec_lang['hw_roughness']='Hazen-Williams коефицијент, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning Неправилни канал';
$ec_lang['mi_main_title']='Бесплатни онлајн калкулатор неправилног канала по Manningu';
$ec_lang['mi_main_desc']='Калкулатор равномерног тецања у неправилном каналу по Manningu';
$ec_lang['mi_waterSurfaceElevation']='Кота нивоа воде';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Тачке попречног пресека';
$ec_lang['mi_groupPoint']='Тачка';
$ec_lang['mi_groupSegment']='Сегмент';
$ec_lang['mi_groupRegion']='Регија';
$ec_lang['mi_station']='Ст.';
$ec_lang['mi_elevation']='Кота';
$ec_lang['mi_d50in']='Облога<br />медијана<br />величина<br />камена';
$ec_lang['mi_n']='n<br />за сег-<br />мент';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />граница<br />регије<br />(Обала)';
$ec_lang['mi_tau']='Напон<br />дна<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Ком-<br />позитни n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Напомене';
$ec_lang['mi_notes_1_term']='Композитни n';
$ec_lang['mi_notes_1_def']='Овај калкулатор прати HEC-RAS Референтни приручник у израчунавању композитног n регије помоћу Chow 1959, страна 136, једначина 6-17 (не 6-18).';
$ec_lang['mi_notes_2_term']='Каменa облога';
$ec_lang['mi_notes_2_def']='Користите калкулатор трапезног канала по Manningu за пројектовање каменe облоге. Овај калкулатор је примереnији за природне пресеке.';
// Manning Pipe Flow extras
$ec_lang['mpf_see_notes']='(Погледај напомене)';
$ec_lang['mpf_pipe_area']='Површина цеви, a0';
$ec_lang['mpf_area_ratio']='Релативна површина, a/a0';
$ec_lang['mpf_full_flow']='Пуни протицај, Q0';
$ec_lang['mpf_full_flow_ratio']='Однос према пуном протицају, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Ово је протицај и дубина унутар <em>бесконачно дугачке</em> цеви.</dt><dd>За унос воде у цев може бити потребна знатно већа дубина нивоа воде. Додајте најмање 1,5 пута енергетску висину брзине да бисте добили дубину нивоа воде или <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">погледајте мој 2-минутни туторијал</a> за стандардна израчунавања нивоа воде на пропусту помоћу HY-8.</dd>';
$ec_lang['mpf_spreadheet_notice']='Погледајте верзију овог калкулатора у облику табеле';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='Губитак напора у цевима по Manningu';
$ec_lang['mphl_main_title']='Бесплатни онлајн калкулатор губитка напора у цевима по Manningu';
$ec_lang['mphl_main_desc']='Манингова формула губитка напора при пуном протицају';
$ec_lang['mphl_pipe_length']='Дужина цеви, L';
$ec_lang['mphl_area']='Површина, A';
$ec_lang['mphl_total_junction_k']='Укупни комбиновани коефицијент губитка на спојевима, k';
$ec_lang['mphl_friction_slope']='Пад трења';
$ec_lang['mphl_friction_loss']='Губитак услед трења, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Губитак на споју, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Укупни губитак, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='Низводна EGL';
$ec_lang['mphl_egl_2']='Узводна EGL';
$ec_lang['mphl_hgl_2']='Узводна HGL у цеви ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>За услов отвореног улаза (пропуст), неопходно је проверити услове контроле улаза.</dt><dd>1. Узводна HGL не може бити нижа од узводне коте нормалног тецања (нити нижа од цеви!).</dd><dd>2. Ниво воде на пропусту боље је представити узводном EGL него узводном HGL.</dd><dd>3. Погледајте <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">мој 2-минутни туторијал</a> заједноставна стандардна израчунавања нивоа воде на пропусту помоћу HY-8.</dd>';
// Manning Trapezoidal Channel
$ec_lang['mtc_menu']='Манингов трапезни канал';
$ec_lang['mtc_main_title']='Бесплатни онлајн калкулатор трапезног канала по Манинговој формули';
$ec_lang['mtc_main_desc']='Манингова формула равномерног тецања у трапезном каналу при задатом паду и дубини';
$ec_lang['mtc_bottom_width']='Ширина дна, b';
$ec_lang['mtc_side_slope_1']='Нагиб бочне стране 1 (хориз./верт.)';
$ec_lang['mtc_side_slope_2']='Нагиб бочне стране 2 (хориз./верт.)';
$ec_lang['mtc_channel_slope']='Нагиб канала, S';
$ec_lang['mtc_flow_depth']='Дубина тецања, y';
$ec_lang['mtc_bend_angle']='Угао скретања <a target="_blank" href="riprap-bend-angle.png" title="Кликни за слику">?</a> (за димензионисање рипрапа)';
$ec_lang['mtc_sgrock']='Специфична тежина камена (2,65)';
$ec_lang['mtc_d50_in']='Пројектована величина камена, D50';
$ec_lang['mtc_n_strickler']='n за пројектовану величину камена по Strickleru';
$ec_lang['mtc_n_blodgett']='n за пројектовану величину камена по Blodgettu';
$ec_lang['mtc_n_bathurst']='n за пројектовану величину камена по Bathhurstu';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett насупрот Bathurst';
$ec_lang['mtc_d50_bottom']='Потребна величина угаоног камена дна, D50 (Isbash & MC) <a href="javascript:alert(\'По Isbashu (1936) и округу Maricopa, Аризона, САД.\')">?</a>';
$ec_lang['mtc_d50_z1']='Потребна величина угаоног камена бочне стране 1, D50 (Isbash & MC) <a href="javascript:alert(\'По Isbashu (1936) и округу Maricopa, Аризона, САД.\')">?</a>';
$ec_lang['mtc_d50_z2']='Потребна величина угаоног камена бочне стране 2, D50 (Isbash & MC) <a href="javascript:alert(\'По Isbashu (1936) и округу Maricopa, Аризона, САД.\')">?</a>';
$ec_lang['mtc_d50_mra']='Потребна величина угаоног камена, D50 (Maynord, Ruff и Abt 1989)';
$ec_lang['mtc_d50_searcy']='Потребна величина угаоног камена, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Аутоматска итерација пројектовања величине камена и храпавости</dt><dd>Изаберите радио дугме за храпавост (препоручује се BB) и радио дугме за пројектовану величину камена (препоручује се Isbash). Финим подешавањем дубине и фактора сигурности величине камена добијте жељени протицај са заокруженом величином камена. Свако промену улазне вредности покреће следећи итерациони циклус: 1. Храпавост се израчунава из пројектоване величине камена. 2. Израчунавање тражене храпавости копира се у улазну храпавост. 3. Израчунавају се протицај у каналу и потребна величина камена. 4. Пројектована величина камена се подешава. 5. Понавља се до врло малe грешке у пројектованoj величини камена.</dd><dt>Основни калкулатор (без итерације)</dt><dd>Унесите жељену вредност храпавости. Занемарите поље за унос пројектоване величине камена.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson каменита брзица';
$ec_lang['rrc_main_desc']='Пројектна табела Robinson каменита брзица';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Протицај преко прелива (просто)';
$ec_lang['ws_main_title']='Бесплатни онлајн калкулатор протицаја преко ширококрунског прелива';
$ec_lang['ws_main_desc']='Калкулатор протицаја преко ширококрунског прелива';
$ec_lang['ws_weirLength']='Дужина прелива, l';
$ec_lang['ws_headWaterHeight']='Висина узводног нивоа воде, h';
$ec_lang['ws_weirCoefficient']='Коефицијент прелива, Cw';
$ec_lang['ws_notes_heading']='Напомене';
$ec_lang['ws_notes_we_term']='Једначина прелива';
// Weir Flow Irregular
$ec_lang['wi_menu']='Протицај преко неправилног прелива';
$ec_lang['wi_main_title']='Бесплатни онлајн калкулатор протицаја преко сегментираног неправилног прелива са променљивом дубином';
$ec_lang['wi_main_desc']='Калкулатор протицаја преко неправилног прелива';
$ec_lang['wi_headWaterelevation']='Кота узводног нивоа воде';
$ec_lang['wi_weirPoints']='Тачке прелива';
$ec_lang['wi_station']='Станица<br />(растојање)';
$ec_lang['wi_elevation']='Кота';
$ec_lang['wi_pondingHeight']='Висина поплавног таласа';
$ec_lang['wi_incrementalFlow']='Инкрементални протицај';
$ec_lang['wi_cumulativeFlow']='Кумулативни протицај';
$ec_lang['wi_save_and_calculate']='Сачувај и израчунај';
$ec_lang['wi_notes_we_term']='Једначина прелива';
$ec_lang['wi_notes_we_def']='q = ако (дужина = 0) онда 0 иначе ако (нагиб=0) онда cw*дужина*d<sub>0</sub><sup>1.5</sup> иначе cw/(2.5*нагиб) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) где су d<sub>1</sub> и d<sub>0</sub> увек позитивни или нула';
// Erosion Setback and Scour
$ec_lang['essc_btbw']='Ширина од обале до обале';
$ec_lang['essc_mcr']='Минимални полупречник кривине';
$ec_lang['essc_q']='Протицај, Q';
// Contact

// Irrigation
$ec_lang['irr_main_menu']='Mjerenje protoka navodnjavanja';
$ec_lang['irr_main_title']='Besplatni online kalkulatori za mjerenje protoka navodnjavanja';
$ec_lang['irr_main_desc']='Mjerenje protoka navodnjavanja — prelivi i otvori';
$ec_lang['contact_title']='HawsEDC Контакт';
$ec_lang['contactSendMessage']='Пошаљите поруку Тому Хоусу';
$ec_lang['contactYourName']='Ваше име:';
$ec_lang['contactYourEmail']='Ваша е-маил адреса:';
$ec_lang['contactSubject']='Предмет:';
$ec_lang['contact_message']='Порука:';
$ec_lang['contactSpamPrefix']='Пет плус један је';
$ec_lang['contactSpamPostfix']='(Молимо вас напишите речима. 1=jedan 2=dva 3=tri 4=četiri 5=pet 6=šest 7=sedam +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Пошаљи поруку';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Мала хидроелектрана';
$ec_lang['mhp_main_title']='Бесплатни онлајн калкулатор за малу хидроелектрану';
$ec_lang['mhp_main_desc']='Калкулатор излазне снаге мале хидроелектране проточног типа';
$ec_lang['mhp_flow']='Протицај, Q';
$ec_lang['mhp_gross_head']='Бруто пад (разлика нивоа), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Губици пада у доводном цевоводу, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Искористивост постројења, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Нето пад, H<sub>net</sub>';
$ec_lang['mhp_power']='Излазна снага, P';
$ec_lang['mhp_annual_kwh']='Годишња енергија при 100% капацитету';
$ec_lang['mhp_notes_1_term']='Jednadžba snage';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, где &rho; = 1000 kg/m&sup3; (слатка вода) и g = 9,806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Нето пад';
$ec_lang['mhp_notes_2_def']='Нето пад = бруто пад &minus; губици пада у доводном цевоводу. Уобичајена прва процена је h<sub>L</sub> &asymp; 5% од H<sub>gross</sub>. Користите <a href="Darcy-Weisbach.php">Darcy-Weisbach калкулатор</a> за прецизније процене губитака у цевоводу.';
$ec_lang['mhp_notes_3_term']='Искористивост';
$ec_lang['mhp_notes_3_def']='Типична искористивост постројења &eta; креће се од 0,70 до 0,85 за Пелтон и попречно-проточне турбине уобичајене у малој хидроенергетици. Користите 0,75 као конзервативну почетну процену.';
$ec_lang['mhp_notes_4_term']='Годишња енергија';
$ec_lang['mhp_notes_4_def']='Годишња енергија претпоставља непрекидни рад при пуном протицају (8760 сати/год). Стварна производња биће мања услед сезонских варијација протицаја, застоја ради одржавања и фактора оптерећења.';
// Penstock Design
$ec_lang['ps_main_menu']='Пројектовање доводног цевовода';
$ec_lang['ps_main_title']='Бесплатни онлајн калкулатор доводног цевовода';
$ec_lang['ps_main_desc']='Димензионисање доводног цевовода за мало-хидро — губитак притиска, снага и брзина';
$ec_lang['ps_flow']='Протицај, Q';
$ec_lang['ps_gross_head']='Бруто напор, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Пречник цевовода, D';
$ec_lang['ps_length']='Дужина цевовода, L';
$ec_lang['ps_roughness']='Храпавост цеви, e';
$ec_lang['ps_km']='Коефицијент локалних губитака, k<sub>m</sub>';
$ec_lang['ps_nu']='Кинематичка вискозност, &nu;, у м<sup>2</sup>/с (1E-6 за воду при 20&deg;C)';
$ec_lang['ps_efficiency']='Ефикасност постројења, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Брзина струјања, v';
$ec_lang['ps_vel_check']='Провера брзине';
$ec_lang['ps_f']='Коефицијент трења, f';
$ec_lang['ps_hf']='Губитак напора трењем, h<sub>f</sub>';
$ec_lang['ps_hm']='Локални губитак напора, h<sub>m</sub>';
$ec_lang['ps_hl']='Укупни губитак цевовода, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Провера губитка напора';
$ec_lang['ps_hnet']='Нето напор, H<sub>net</sub>';
$ec_lang['ps_power']='Излазна снага, P';
$ec_lang['ps_annual_kwh']='Годишња енергија при 100% капацитета';
$ec_lang['ps_vel_ok']='1–3 м/с — у циљном опсегу ✓';
$ec_lang['ps_vel_low']='испод 1 м/с — повећајте пречник ⚠';
$ec_lang['ps_vel_high']='изнад 3 м/с — смањите пречник ⚠';
$ec_lang['ps_hl_ok']='у оквиру циља 10% ✓';
$ec_lang['ps_hl_warn']='прелази циљ 10% — размотрите шири цевовод ⚠';
$ec_lang['ps_hl_bad']='прелази 20% — редимензионишите цевовод';
$ec_lang['ps_notes_1_term']='Губитак напора';
$ec_lang['ps_notes_1_def']='Укупни губитак h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, где је h<sub>f</sub> = f(L/D)(v&sup2;/2g) губитак трењем по Дарси-Вајсбаху, а h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g обухвата улаз, лукове и вентиле. Нето напор H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Брзина';
$ec_lang['ps_notes_2_def']='Циљна брзина 1&ndash;3 м/с. Испод 1 м/с цевовод је предимензионисан; изнад 3 м/с расту трибологички губици и ризик водног удара.';
$ec_lang['ps_notes_3_term']='Циљни губитак напора';
$ec_lang['ps_notes_3_def']='Губитак у цевоводу испод 10% бруто напора је уопштено економичан. Оптималан компромис између цене цевовода и изгубљене снаге обично је 4&ndash;6% за локалитете с високом вредношћу електричне енергије.';
$ec_lang['ps_notes_4_term']='Локални губици k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Типичне вредности: оштри улаз 0.5, свако колено 45&deg; између 0.2&ndash;0.3, засун (потпуно отворен) 0.1, лептирасти вентил 0.2. Збир свих фитинга даје укупни k<sub>m</sub>. Подразумевана вредност 1.5 претпоставља један улаз и два колена.';
$ec_lang['ps_notes_5_term']='Храпавост цеви e';
$ec_lang['ps_notes_5_def']='Типична апсолутна храпавост: челик (нов) 0.046&nbsp;мм, челик (половни) 0.15&nbsp;мм, HDPE 0.003&nbsp;мм, PVC/uPVC 0.0015&nbsp;мм, бетон 0.3&ndash;3&nbsp;мм. HDPE је уобичајен за мале доводне цевоводе мало-хидро система.';
