<?php

// አማርኛ — All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='ክፍልፋይ';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/s';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% ቁልቁለት/ርቀት';
$ec_lang['u_grade']='ቁልቁለት/ርቀት';
$ec_lang['u_in2']='in^2';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_bar']="bar";
$ec_lang['u_kgfcm2']="kgf/cm^2";
$ec_lang['u_s']='sec';
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC ካልኩሌተሮች';
$ec_lang['menu_main_list']='የካልኩሌተሮች ዝርዝር';
$ec_lang['menu_main_hydraulics']='ሃይድሮሊክስ';
$ec_lang['menu_main_language']='ቋንቋ';
$ec_lang['menu_more']='ተጨማሪ';
$ec_lang['template_welcome']='>> ፍርሃትህን በር ላይ ትተህ ግባ; ፍቅር እዚህ ይነገራል። ሁሉንም ነገር አታበላሽም። <a target="_blank" href="https://hawsedc.com/download.php">ነፃ HawsEDC AutoCAD መሣሪያዎችን</a> ደግሞ ተጠቀም። <<';
$ec_lang['template_translation_help']='የተሻለ አገላለጽ ወይም ሌላ ማንኛውንም ማሻሻያ ሊጠቁሙን ይችላሉ? እባክዎ ንገሩን።';
$ec_lang['template_feedback']='እባክህ ሃሳብህን ወይም ምስጋናህን ስጠን። ይህ ነፃ ካልኩሌተር በሁሉም ረገድ ከምትጠብቀው በላይ ሆኗል?';
$ec_lang['template_printable_title']='ሊታተም የሚችል ርዕስ';
$ec_lang['template_printable_subtitle']='ሊታተም የሚችል ንዑስ ርዕስ';
$ec_lang['index_title']='ነፃ የኦንላይን ምህንድስና ካልኩሌተሮች';
$ec_lang['calc_set_units']='አሃዶችን አዘጋጅ:';
$ec_lang['calc_defaults']='ነባር ዋጋዎች';
$ec_lang['calc_defaults_confirm']='ካልኩሌተሩን ወደ ነባር ዋጋዎች ማስጀምር?';
$ec_lang['points_data_help']='(ወይም የውሂብ ቦታ ተጠቅሞ ቅዳ/ለጥፍ)';
$ec_lang['points_data_title']='የነጥቦች ውሂብ<br />(በኮማ ወይም ታብ የተለዩ)';
$ec_lang['points_data_copy']='ቅዳ';
$ec_lang['points_data_paste']='ለጥፍ';
$ec_lang['calc_inputs']='ግቤቶች';
$ec_lang['calc_results']='ውጤቶች';
$ec_lang['view_hide_line']='[ይህን መስመር ደብቅ]';
$ec_lang['view_printable']='ሊታተም የሚችል እትም (ለመመለስ አደስ)';
$ec_lang['ec_name_label']='ይህን ስሌት አስቀምጥ:';
$ec_lang['ec_name_placeholder']='ስም';
$ec_lang['ec_name_hint']='እነዚህ ግቤቶች ወደ URL ያስቀምጣል በደንብ ምልክት ለመስጠት ታሪክ ማግኛ እና ማጋራት';
$ec_lang['calc_copy_link']='ቅዳ ሊንክ';
$ec_lang['calc_copy_link_done']='ተቀድቷል!';
$ec_lang['ec_related_calcs']='ተዛማጅ ማስያዎች፦';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach የቧንቧ ሄድ ኪሳራ';
$ec_lang['dw_main_title']='ነፃ ኦንላይን Darcy-Weisbach የቧንቧ ሄድ ኪሳራ ካልኩሌተር';
$ec_lang['dw_main_desc']='Darcy-Weisbach የቧንቧ ሄድ ኪሳራ በተሰጠ ዲያሜትር፣ ሻካሪነት እና ፍሰት';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='የቧንቧ ግድግዳ ፍጹም ሻካሪነት ቁመት፣ e። የተለመዱ ዋጋዎች፦ ብረት (አዲስ) 0.046 ሚሜ፣ ብረት (የተጠቀመ) 0.15 ሚሜ፣ HDPE 0.003 ሚሜ፣ PVC/uPVC 0.0015 ሚሜ፣ ኮንክሪት 0.3–3 ሚሜ።';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s ለንጹህ ውሃ በ20°C">ኪኔማቲክ ቪስኮሲቲ, &nu; <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='ኪኔማቲክ ቪስኮሲቲ, &nu;';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s ለንጹህ ውሃ በ20°C';
$ec_lang['dw_reynolds_number']='ሬይኖልዶስ ቁጥር, Re';
$ec_lang['dw_flow_regime']='የፍሰት አገዛዝ';
$ec_lang['dw_regime_laminar']='ላሚናር';
$ec_lang['dw_regime_transitional']='ሽግግር';
$ec_lang['dw_regime_turbulent']='ቱርቡሌንት';
$ec_lang['dw_friction_factor_method']='የግጭት ፋክተር ዘዴ';
$ec_lang['dw_friction_factor']='ግጭት ፋክተር, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams የቧንቧ ሄድ ኪሳራ';
$ec_lang['hw_main_title']='ነፃ ኦንላይን Hazen-Williams የቧንቧ ሄድ ኪሳራ ካልኩሌተር';
$ec_lang['hw_main_desc']='Hazen-Williams የቧንቧ ሄድ ኪሳራ በተሰጠ ዲያሜትር፣ ሻካሪነት እና ፍሰት';
$ec_lang['hw_hgl_1']='ዝቅ ባለ ፍሰት HGL';
$ec_lang['hw_hgl_2']='ወደ ላይ ባለ ፍሰት HGL';
$ec_lang['hw_roughness']='Hazen-Williams ቅንጅት, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning ያልተስተካከለ ቅርጽ ቦይ';
$ec_lang['mi_main_title']='ነፃ ኦንላይን Manning ያልተስተካከለ ቅርጽ ቦይ ካልኩሌተር';
$ec_lang['mi_main_desc']='ያልተስተካከለ ቅርጽ ቦይ Manning ወጥ ፍሰት ካልኩሌተር';
$ec_lang['mi_waterSurfaceElevation']='የውሃ ወለል ከፍታ';
$ec_lang['mi_q_617']='<span class="ec-help" title="ጥምር ፍሰት Q፣ ለእያንዳንዱ ክልል በChow 6-17 መሠረት ጥምር n በመጠቀም የተሰላ (እኩል ፍጥነቶች)">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='የተሻጋሪ ክፍል ነጥቦች';
$ec_lang['mi_groupPoint']='ነጥብ';
$ec_lang['mi_groupSegment']='ክፍል';
$ec_lang['mi_groupRegion']='ክልል';
$ec_lang['mi_station']='ርቀት ነጥብ';
$ec_lang['mi_elevation']='ከፍታ';
$ec_lang['mi_d50in']='የሽፋን<br />መካከለኛ<br />ድንጋይ<br />መጠን';
$ec_lang['mi_n']='n<br />ለክፍል';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />የክልል<br />ወሰን<br />(ዳርቻ)';
$ec_lang['mi_tau']='የታች<br />ሸርፍ<br />ጭንቀት<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='ጥምር<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='ጥምር n';
$ec_lang['mi_notes_1_def']='ይህ ካልኩሌተር HEC-RAS የማጣቀሻ ማኑዋልን ተከትሎ Chow 1959, ገጽ 136, እኩልታ 6-17 (6-18 ሳይሆን) ተጠቅሞ የክልል ጥምር n ያሰላል።';
$ec_lang['mi_notes_2_term']='የድንጋይ ሽፋን';
$ec_lang['mi_notes_2_def']='የድንጋይ ሽፋን ለመንደፍ Manning ትራፔዞይዳዊ ቦይ ካልኩሌተርን ይጠቀሙ። ይህ ካልኩሌተር ለተፈጥሯዊ ተሻጋሪ ክፍሎች ይበልጥ ተስማሚ ነው።';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning የቧንቧ ፍሰት';
$ec_lang['mpf_main_title']='ነፃ ኦንላይን Manning የቧንቧ ፍሰት ካልኩሌተር';
$ec_lang['mpf_main_desc']='Manning ቀመር ወጥ የቧንቧ ፍሰት በተሰጠ ቁልቁለት እና ጥልቀት';
$ec_lang['mpf_spreadheet_notice']='Manning የቧንቧ ፍሰት ሰንጠረዥ';
$ec_lang['mpf_pipe_diameter']='የቧንቧ ዲያሜትር, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='የማኒንግ ሻካሪነት, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">የግጭት ቁልቁለት, S<sub>f</sub></a><span class="ec-help" title="አንዳንዴ ከቧንቧ ቁልቁለት ጋር እኩል። ማብራሪያ ለማግኘት አገናኙን ይከተሉ (በእንግሊዝኛ ብቻ)።"><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='አንጻራዊ የፍሰት ጥልቀት, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='ፍሰት, Q';
$ec_lang['mpf_flow_tip']='ፍሰት እና ጥልቀት ላልተወሰነ ርዝመት ቧንቧ ተሰልተዋል። ይህን ፍሰት ወደ ቧንቧው ለማስገባት ከፍ ያለ የላይኛው ውሃ ጥልቀት ሊያስፈልግ ይችላል። ዝርዝር እና የማስተማሪያ ቪዲዮ ለማግኘት ከታች ያሉትን ማስታወሻዎች ይመልከቱ።';
$ec_lang['mpf_velocity']='ፍጥነት, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="የኪነቲክ ኃይል እንደ ውሃ አምድ ቁመት፣ v&sup2;/2g">የፍጥነት ሄድ, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='የፍሰት ስፋት, A';
$ec_lang['mpf_pipe_area']='የቧንቧ ስፋት, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='አንጻራዊ ስፋት, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='የረጠበ ዙሪያ, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='ሃይድሮሊካዊ ራዲዩስ, R<sub>h</sub>';
$ec_lang['mpf_top_width']='የላይ ስፋት, T';
$ec_lang['mpf_froude_number']='Froude ቁጥር, Fr';
$ec_lang['mpf_shear_stress']='አማካይ ሺር ስትሬስ, &tau;';
$ec_lang['mpf_full_flow']='ሙሉ ፍሰት, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='ከሙሉ ፍሰት ጋር ያለ ጥምርታ, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>ይህ <em>ወሰን የሌለው</em> ቧንቧ ውስጥ ያለ ፍሰት እና ጥልቀት ነው።</dt><dd>ፍሰቱን ወደ ቧንቧ ለማስገባት ከፍ ያለ የላይኛው ውሃ ጥልቀት ሊያስፈልግ ይችላል። የላይኛው ውሃ ጥልቀቱን ለማግኘት ቢያንስ 1.5 እጥፍ የፍጥነት ሄድ ጨምር ወይም <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">የ2 ደቂቃ ትምህርቴን ይመልከቱ</a> HY-8 ተጠቅሞ ለተለመደ culvert የላይኛው ውሃ ስሌቶች።</dd>';
$ec_lang['mpf_solve_for_dd0']='Q ሲሰጥ y/d<sub>0</sub> ፍታ';
$ec_lang['mpf_solve_desc']='ከካልኩሌተር ቅጹ ላይ d<sub>0</sub>, n እና S<sub>f</sub> ተጠቅሞ፣ ለተሰጠ Q ዝቅተኛ y/d<sub>0</sub> ያገኛል።';
$ec_lang['mpf_solve_button']='ፍታ';
$ec_lang['mpf_solver_enter_positive_q']='አዎንታዊ ዒላማ Q ያስገቡ።';
$ec_lang['mpf_solver_no_solution']='ውጤት የለም፦ Q ከቧንቧው አቅም ይበልጣል y/d0 = 93.8% ላይ (Qmax = {qmax} በተመረጡት አሃዶች)።';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning የቧንቧ ሄድ ኪሳራ';
$ec_lang['mphl_main_title']='ነፃ ኦንላይን Manning የቧንቧ ሄድ ኪሳራ ካልኩሌተር';
$ec_lang['mphl_main_desc']='Manning ቀመር ሄድ ኪሳራ ሙሉ ፍሰት ሲሰጥ';
$ec_lang['mphl_pipe_length']='የቧንቧ ርዝመት, L';
$ec_lang['mphl_area']='ስፋት, A';
$ec_lang['mphl_total_junction_k']='ጥቃቅን (አካባቢያዊ) ኪሳራ ቅንጅት, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='ኪሳራ ቅንጅት, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='ጥቃቅን (አካባቢያዊ) የኪሳራ ውሁድ ቁጥር፣ k<sub>m</sub>። እነዚህ ኪሳራዎች የሚከሰቱት በቧንቧ መገናኛዎች፣ በመግቢያዎች፣ በመውጫዎች፣ በጠመዝማዛዎች እና በቫልቮች ላይ ነው — "ጥቃቅን" የሚለው ቃል የተለመደ ቢሆንም አሳሳች ነው፤ በአጭር መስመር ውስጥ ከግጭት ኪሳራዎች ጋር እኩል ሊሆኑ ወይም ሊበልጡ ይችላሉ። የተለመዱ k እሴቶች፦ ስለታም መግቢያ 0.5፣ እያንዳንዱ 45° ጠመዝማዛ 0.2–0.3፣ በር ቫልቭ (ሙሉ በሙሉ ክፍት) 0.1፣ የቢራቢሮ ቫልቭ 0.2፣ መውጫ (ወደ ማጠራቀሚያ ወይም ወደ ከባቢ አየር) 1.0። ጠቅላላ k<sub>m</sub> ለማግኘት ሁሉንም ተያያዥ ዕቃዎች ደምር። ነባሪው 2.0 አንድ መግቢያ፣ አንድ መውጫ፣ እና ሁለት 45° ጠመዝማዛዎችን ይገምታል።';
$ec_lang['mphl_friction_slope']='የግጭት ቁልቁለት';
$ec_lang['mphl_friction_loss']='ግጭት ኪሳራ, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='ጥቃቅን (አካባቢያዊ) ኪሳራ, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='ጠቅላላ ኪሳራ, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='ዝቅ ባለ ፍሰት EGL';
$ec_lang['mphl_egl_2']='ወደ ላይ ባለ ፍሰት EGL';
$ec_lang['mphl_hgl_egl_tip']='ቧንቧው ከፍ ያለ ከሆነ ትክክለኛ ላይሆን ይችላል። ማስታወሻዎችን ይመልከቱ።';
$ec_lang['mphl_note_1']='<dl><dt>ይህ ማስያ የቧንቧውን ከፍታ ግምት ውስጥ አያስገባም።</dt><dd>HGL በማንኛውም ቦታ ከቧንቧው ጫፍ በታች ከሆነ፣ ይህ ስሌት ትክክለኛ ላይሆን ይችላል።</dd><dt>ለክፍት መግቢያ (culvert) ሁኔታ፣ የመግቢያ ቁጥጥር ሁኔታዎችን ማረጋገጥ ያስፈልጋል።</dt><dd>1. የወደ ላይ ባለ ፍሰት HGL ከወደ ላይ ባለ ፍሰት ተፈጥሯዊ ጥልቀት ፍሰት ከፍታ በላይ (እንዲሁም ከቧንቧው በላይ) መሆን አለበት።</dd><dd>2. የ culvert የላይኛው ውሃ ከወደ ላይ ባለ ፍሰት HGL ይልቅ በወደ ላይ ባለ ፍሰት EGL በተሻለ ይወከላል።</dd><dd>3. ቀለል ያለ የ culvert የላይኛው ውሃ ስሌቶች HY-8 ተጠቅሞ ለማደረግ <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">የ2 ደቂቃ ትምህርቴን</a> ይመልከቱ።</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning ትራፔዞይዳዊ ቦይ';
$ec_lang['mtc_main_title']='ነፃ ኦንላይን Manning ቀመር ትራፔዞይዳዊ ቦይ ካልኩሌተር';
$ec_lang['mtc_main_desc']='Manning ቀመር ወጥ ትራፔዞይዳዊ ቦይ ፍሰት በተሰጠ ቁልቁለት እና ጥልቀት';
$ec_lang['mtc_bottom_width']='የታች ስፋት, b';
$ec_lang['mtc_side_slope_1']='የጎን ቁልቁለት 1, z<sub>1</sub> (አግድም/ቁመት)';
$ec_lang['mtc_side_slope_2']='የጎን ቁልቁለት 2, z<sub>2</sub> (አግድም/ቁመት)';
$ec_lang['mtc_channel_slope']='የቦይ ቁልቁለት, S';
$ec_lang['mtc_flow_depth']='የፍሰት ጥልቀት, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">የጥምዝ ማዕዘን, β</a><span class="ec-help" title="ለ ድንጋይ ሽፋን ስሌት። ንድፍ ለማግኘት አገናኙን ይከተሉ።"><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="ከውሃ አንጻር ያለው ጥግግት። ለተፈጨ ድንጋይ በተለምዶ &asymp; 2.65።">የድንጋይ ልዩ ስበት, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='የንድፍ የድንጋይ መጠን, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n ለ Strickler ዘዴ ንድፍ የድንጋይ መጠን';
$ec_lang['mtc_n_blodgett']='n ለ Blodgett ዘዴ ንድፍ የድንጋይ መጠን';
$ec_lang['mtc_n_bathurst']='n ለ Bathurst ዘዴ ንድፍ የድንጋይ መጠን';
$ec_lang['mtc_n_pi']='n ለ Phillips & Ingersoll ዘዴ ንድፍ የድንጋይ መጠን';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett በተቃራኒ Bathurst';
$ec_lang['mtc_pi_range_check']='P&I ክልል ማረጋገጫ';
$ec_lang['mtc_pi_ok']='d50 በ P&I ክልል ውስጥ';
$ec_lang['mtc_pi_ok_tip']='0.28–0.36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='ከክልል ውጪ';
$ec_lang['mtc_pi_tip']='ይህ ቀመር ከተገኘበት 0.28–0.36 ft የመረጃ ክልል ውጪ ግምት እየተደረገ ነው — እንደ ግምታዊ ማጣሪያ እንጂ እንደ ንድፍ መሰረት አይያዝ';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="በIsbash (1936) እና Maricopa County, Arizona, US. መሠረት">የሚፈለግ የታች ማዕዘናዊ የድንጋይ መጠን, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="በIsbash (1936) እና Maricopa County, Arizona, US. መሠረት">የሚፈለግ የጎን ቁልቁለት 1 ማዕዘናዊ የድንጋይ መጠን, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="በIsbash (1936) እና Maricopa County, Arizona, US. መሠረት">የሚፈለግ የጎን ቁልቁለት 2 ማዕዘናዊ የድንጋይ መጠን, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='የሚፈለግ ማዕዘናዊ የድንጋይ መጠን, D<sub>50</sub> (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='የሚፈለግ ማዕዘናዊ የድንጋይ መጠን, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='ፍጥነቱ ለወጥ ፍሰት ግምቶች ምክንያታዊ ነው።';
$ec_lang['mtc_vel_low']='ፍጥነቱ ዝቅ ያለ ነው - የደለል አደጋ አለ።';
$ec_lang['mtc_iteration_tip']='የሻካሪነት አማራጭ (Blodgett–Bathurst ይመከራል) እና የድንጋይ መጠን አማራጭ (Isbash ይመከራል) ይምረጡ፣ ለታለመው ፍሰት ወጥ የድንጋይ መጠን በራስ-ሰር ለማስላት። ሙሉ ዘዴውን ለማየት ከታች ያሉትን ማስታወሻዎች ይመልከቱ፣ ወይም የራስዎን የሻካሪነት ዋጋ (መመሪያ ለማግኘት አገናኙን ይመልከቱ) በማስገባት የድንጋይ መጠንን ችላ ብለው ድግግሞሽን ይዝለሉ።';
$ec_lang['mtc_note_1']='<dl><dt>አውቶማቲክ የድንጋይ መጠን እና ሻካሪነት ንድፍ ድግግሞሽ</dt><dd>የሻካሪነት አማራጭ (Blodgett–Bathurst ይመከራል) እና የንድፍ የድንጋይ መጠን አማራጭ (Isbash ይመከራል) ይምረጡ። የሚፈለገውን ፍሰት በወጥ የድንጋይ መጠን ለማግኘት ጥልቀቱን እና የድንጋይ መጠን የደህንነት ሁኔታን ያስተካክሉ። ማንኛውንም ግቤት በቀየሩ ቁጥር ካልኩሌተሩ እነዚህን ደረጃዎች ይደግማል፦ 1. ሻካሪነት ከንድፍ የድንጋይ መጠን ይሰላል። 2. የተሰላው ሻካሪነት ወደ ግቤት ሻካሪነት ይገለበጣል። 3. የቦይ ፍሰት እና የሚፈለግ የድንጋይ መጠን ይሰላሉ። 4. የንድፍ የድንጋይ መጠን ይስተካከላል። 5. በንድፍ የድንጋይ መጠን ስህተት እጅግ አነስተኛ እስኪሆን ድረስ ይደገማል።</dd><dt>መሠረታዊ ካልኩሌተር (ያለ ድግግሞሽ)</dt><dd>የሚፈልጉትን የሻካሪነት ዋጋ ያስገቡ። የንድፍ የድንጋይ መጠን ግቤት ቦታን ችላ ይበሉ።</dd></dl>';
$ec_lang['mtc_note_2_term']='የፍጥነት ምርመራ';
$ec_lang['mtc_note_2_def']='ከፍተኛ ፍጥነት ከሚገኝ ቁልቁለት ከፍተኛ ልዩ ሃይልን ያሳያል። ያ ሃይል በስፋፊዎች፣ ጥምዞች ወይም እንቅፋቶች ላይ በፍጥነት ሊጠፋ ይችላል። ይህ ለቦታው ምክንያታዊ መሆኑን ያረጋግጡ።';
// Weir Flow Simple
$ec_lang['mtc_solve_for_y']='Q ከተሰጠ ጥልቀት y ፍታ';
$ec_lang['mtc_solve_desc']='ከማስያ ቅጹ b, z<sub>1</sub>, z<sub>2</sub>, S እና n ን በመጠቀም፣ ለተሰጠው Q ጥልቀቱን ያገኛል።';
$ec_lang['mtc_solver_no_solution']='በእነዚህ የቦዮ ግቤቶች ለተሰጠው Q መፍትሔ አልተገኘም።';
$ec_lang['ws_main_menu']='ቀላል ዊር ፍሰት';
$ec_lang['ws_main_title']='ነፃ ኦንላይን ቀላል ሰፊ-ጫፍ ዊር ፍሰት ካልኩሌተር';
$ec_lang['ws_main_desc']='ቀላል ሰፊ-ጫፍ ዊር ፍሰት ካልኩሌተር';
$ec_lang['ws_weirLength']='የዊር ርዝመት, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="በአንድ አሃድ የውሃ ክብደት የሚሰላ ኃይል — የውሃ አምድ ቁመት እንጂ ግፊት አይደለም">ሄድ, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='የዊር ቅንጅት, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='ማስታወሻዎች';
$ec_lang['ws_notes_we_term']='የዊር እኩልታ';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='መደበኛ ያልሆነ ዊር ፍሰት';
$ec_lang['wi_main_title']='ነፃ ኦንላይን ክፍልፋይ፣ ተለዋዋጭ ጥልቀት፣ መደበኛ ያልሆነ ዊር ፍሰት ካልኩሌተር';
$ec_lang['wi_main_desc']='መደበኛ ያልሆነ ዊር ፍሰት ካልኩሌተር';
$ec_lang['wi_weirPoints']='ዊር ነጥቦች';
$ec_lang['wi_pondingHeight']='የኩሬ ውሃ ከፍታ';
$ec_lang['wi_incrementalFlow']='ተጨማሪ ፍሰት';
$ec_lang['wi_cumulativeFlow']='ድምር ፍሰት';
$ec_lang['wi_save_and_calculate']='አስቀምጥ እና አሰላ';
$ec_lang['wi_notes_we_def']='q = ርዝመት = 0 ከሆነ 0፤ አለበለዚያ ቁልቁለት = 0 ከሆነ cw*ርዝመት*d<sub>0</sub><sup>1.5</sup>፤ አለበለዚያ cw/(2.5*ቁልቁለት) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>)፣ እዚህ ላይ d<sub>1</sub> እና d<sub>0</sub> ሁልጊዜ አዎንታዊ ወይም ዜሮ ናቸው';
// Orifice Flow
$ec_lang['or_main_menu']='ቀዳዳ ፍሰት';
$ec_lang['or_main_title']='ነፃ ኦንላይን ቀዳዳ ፍሰት ካልኩሌተር';
$ec_lang['or_main_desc']='ቀዳዳ ፍሰት — ነፃ ወይም የተጠለቀ';
$ec_lang['or_shape']='የክፍት ቦታ ቅርጽ';
$ec_lang['or_shape_circular']='ክብ';
$ec_lang['or_shape_rectangular']='አራት ማዕዘን';
$ec_lang['or_diameter']='<span class="ec-help" title="ክብ ከሆነ ዲያሜትር፤ አራት ማዕዘን ከሆነ ቁመት">ዲያሜትር ወይም ቁመት, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="ለአራት ማዕዘን ቅርጽ ክፍት ቦታዎች ብቻ">ስፋት, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="የክፍት ቦታው የግርጌ ወለል">የግርጌ ከፍታ <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='የላይ ዳርቻ ከፍታ';
$ec_lang['or_twe']='የወረድ ዳርቻ ከፍታ';
$ec_lang['or_cd']='የፍሰት ቅንጅት, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='የማዕከል ከፍታ';
$ec_lang['or_head']='<span class="ec-help" title="በአንድ አሃድ የውሃ ክብደት የሚሰላ ኃይል — የውሃ አምድ ቁመት እንጂ ግፊት አይደለም">ውጤታማ ሄድ, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='የክፍት ቦታ ስፋት, A';
$ec_lang['or_regime']='የቀዳዳ አገዛዝ ማረጋገጫ';
$ec_lang['or_regime_valid']='ነፃ ፍሰት';
$ec_lang['or_regime_submerged']='የተጠለቀ ቀዳዳ';
$ec_lang['or_regime_submerged_tip']='TWE ከማዕከል በላይ ነው — የቀዳዳ አገዛዝ አሁንም ትክክል ነው';
$ec_lang['or_regime_warn']='ከቀዳዳ አገዛዝ ውጪ';
$ec_lang['or_regime_warn_tip']='የላይ ዳርቻ ውሃ ከክፍት ቦታው ጫፍ (የላይኛው፣ ከፍተኛው ውስጠኛ ነጥብ) በታች ነው';
$ec_lang['or_regime_twe_above_hwe']='ግቤቶቹን ያረጋግጡ';
$ec_lang['or_regime_twe_above_hwe_tip']='የወረድ ዳርቻ ውሃ (TWE) ከላይ ዳርቻ ውሃ (HWE) በላይ ነው';
$ec_lang['or_notes_1_term']='የቀዳዳ እኩልታ';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh)። ለነፃ ፍሰት፦ h = HWE − ማዕከል። ለተጠለቀ ፍሰት (TWE ከግርጌ በላይ ሲሆን)፦ h = HWE − TWE።';
$ec_lang['or_notes_2_term']='የቀዳዳ አገዛዝ';
$ec_lang['or_notes_2_def']='የቀዳዳ ፍሰት እኩልታዎች የላይ ዳርቻ ውሃ ወለሉ ከክፍት ቦታው ጫፍ (ላይኛው ክፍል) በላይ ሲሆን ይሠራሉ። የላይ ዳርቻ ውሃ ከጫፉ በታች ሲሆን ግን የዊር እኩልታ ተጠቀም።';
$ec_lang['or_notes_3_term']='የፍሰት ቅንጅት';
$ec_lang['or_notes_3_def']='C<sub>d</sub> ለሹል-ጫፍ ቀዳዳዎች ከ0.60 እስከ 0.65 አካባቢ ይደርሳል። ክብ ወይም ወደ ውስጥ ዘልቀው የገቡ (re-entrant) መግቢያዎች ግን የተለያዩ ዋጋዎችን ይጠቀማሉ። ለተጨማሪ መመሪያ <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ወይም የHEC-RAS Hydraulic Reference Manual ይመልከቱ።';
$ec_lang['or_notes_4_term']='መጠለቅ';
$ec_lang['or_notes_4_def']='TWE ከክፍት ቦታው ግርጌ (invert) በላይ ሲሆን ይህ ካልኩሌተር በራስ-ሰር h = HWE − TWE የተጠለቀ ቀዳዳ እኩልታን ይጠቀማል። TWE ከግርጌው ጋር እኩል ወይም ከዚያ ዝቅ ሲል ግን ነፃ ፍሰት ተብሎ ተወስዶ h = HWE − ማዕከል ይሰላል።';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='ማይክሮ-ሃይድሮ ኃይል';
$ec_lang['mhp_main_title']='ነፃ የመስመር ላይ ማይክሮ-ሃይድሮ ኃይል ካልኩሌተር';
$ec_lang['mhp_main_desc']='የወንዝ-ፍሰት ማይክሮ-ሃይድሮ ኃይል ውፅዓት ካልኩሌተር';
$ec_lang['mhp_gross_head']='ጠቅላላ ሄድ፣ H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="የግፊት ቧንቧ (የአቅርቦት ቧንቧ) ዲያሜትር">የግፊት ቧንቧ ዲያሜትር፣ D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='ርዝመት፣ L';
$ec_lang['mhp_efficiency']='የሃይል ማመንጫ ብቃት፣ η (0–1)';
$ec_lang['mhp_vel_check']='የፍጥነት ምርመራ';
$ec_lang['mhp_hl_check']='ሄድ ኪሳራ ምርመራ';
$ec_lang['mhp_hnet']='ተጣራ ሄድ፣ H<sub>net</sub>';
$ec_lang['mhp_power']='የሃይል ውጤት፣ P';
$ec_lang['mhp_annual_kwh']='በ100% አቅም ያለ ዓመታዊ ሃይል';
$ec_lang['mhp_vel_low']='ፍጥነቱ ዝቅተኛ ነው፤ የደለል መከማቸት እና የአየር መግባት አደጋ አለ።';
$ec_lang['mhp_vel_high']='ፍጥነቱ ከፍተኛ ነው፤ የሽግግር ኪሳራዎችን፣ የሚገኘውን ኃይል እና የውሃ መዶሻን ያረጋግጡ።';
$ec_lang['mhp_vel_ok_short']='ጥሩ';
$ec_lang['mhp_vel_high_short']='ከፍተኛ';
$ec_lang['mhp_vel_low_short']='ዝቅተኛ';
$ec_lang['mhp_vel_ok_tip']='ፍጥነቱ ለግፊት ቧንቧ ንድፍ ውጤታማ ክልል ውስጥ ነው።';
$ec_lang['mhp_hl_ok_tip']='ከ10% ኢላማ በታች ነው — ኢኮኖሚያዊ።';
$ec_lang['mhp_hl_warn_tip']='ከ10% ኢላማ በላይ ነው። ትልቅ ቧንቧ ያስቡ።';
$ec_lang['mhp_hl_bad_tip']='ከ20% ኢላማ በላይ ነው። የቧንቧውን መጠን ይቀይሩ።';
$ec_lang['mhp_notes_1_term']='ሄድ ኪሳራ';
$ec_lang['mhp_notes_1_def']='ጠቅላላ የግፊት ቧንቧ (የአቅርቦት ቧንቧ) ኪሳራ h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub> ሲሆን፣ h<sub>f</sub> = f(L/D)(v²/2g) የዳርሲ-ዋይስባክ ግጭት ኪሳራ ነው፣ h<sub>m</sub> = k<sub>m</sub>·v²/2g ደግሞ መግቢያ፣ መታጠፊያ እና ቫልቮችን ይሸፍናል። ተጣራ ሄድ H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='ፍጥነት';
$ec_lang['mhp_notes_2_def']='ፍጥነቱ ካለው ውድቀት (ጠብታ) እና ከቧንቧ ዋጋ አንጻር ምክንያታዊ መሆኑን ያረጋግጡ። እጅግ ዝቅተኛ ፍጥነት ቧንቧው ከመጠን በላይ ትልቅ መሆኑን ሊያመለክት ይችላል፤ እጅግ ከፍተኛ ፍጥነት ደግሞ የግጭት ኪሳራን እና የውሃ መዶሻ (water hammer) አደጋን ይጨምራል።';
$ec_lang['mhp_notes_3_term']='የሄድ ኪሳራ ዒላማ';
$ec_lang['mhp_notes_3_def']='ከጠቅላላ ሄድ 10% በታች የሆነ የግፊት ቧንቧ (የአቅርቦት ቧንቧ) ኪሳራ በአጠቃላይ ኢኮኖሚያዊ ነው። በቧንቧ ዋጋና በጠፋ ኃይል መካከል ያለው ምርጥ ሚዛን ኤሌክትሪክ በጣም ውድ በሆነበት ሁኔታ ብዙ ጊዜ በ4–6% አካባቢ ይወድቃል።';
$ec_lang['mhp_notes_6_term']='ብቃት';
$ec_lang['mhp_notes_6_def']='ለማይክሮ-ሃይድሮ ስርዓቶች ተለምዷዊ ለሆኑ Pelton እና cross-flow ተርባይኖች፣ ዓይነተኛ የሃይል ማመንጫ ብቃት &eta; ከ0.70 እስከ 0.85 ይደርሳል። እንደ መጠንቀቅ የተሞላ የመጀመሪያ ግምት 0.75ን ይጠቀሙ።';
$ec_lang['mhp_notes_7_term']='ዓመታዊ ሃይል';
$ec_lang['mhp_notes_7_def']='ዓመታዊ ሃይል ያለማቋረጥ ሙሉ-ፍሰት ስራ (8760 ሰዓት/ዓመት) እንዳለ ይገምታል። ትክክለኛው ምርት በወቅታዊ የፍሰት ልዩነት፣ የጥገና ማቆሚያ ጊዜ እና የጭነት መጠን ምክንያት ያንሳል።';

// Orifice Drain Time
$ec_lang['odt_main_menu']='ኩሬና ታንክ ፍሳሽ ጊዜ';
$ec_lang['odt_main_title']='ነፃ ኦንላይን ኩሬ፣ ቤዝን እና ታንክ ፍሳሽ ጊዜ ካልኩሌተር (ቀዳዳ)';
$ec_lang['odt_main_desc']='ኩሬ፣ ቤዝን ወይም ታንክ ፍሳሽ ጊዜ &mdash; የቀዳዳ መውጫ፣ ኮኒካዊ መጠን ዘዴ';
$ec_lang['odt_h1_elev']='የጀምር የውሃ ወለል ከፍታ';
$ec_lang['odt_a1']='የጀምር ስፋት, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='የማብቂያ የውሃ ወለል ከፍታ';
$ec_lang['odt_a0']='በቀዳዳ ከፍታ ያለው ስፋት, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="ከኮኒካዊ ሞዴል በማብቂያ ከፍታ ተሰልቶ የተገኘ">የማብቂያ ስፋት, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='የማብቂያ ከፍታ ማረጋገጫ';
$ec_lang['odt_h2_ok']='የማብቂያ ከፍታ ከቀዳዳው ጫፍ በላይ';
$ec_lang['odt_h2_warn']='የማብቂያ ከፍታ ከቀዳዳው ጫፍ ወይም ከዚያ በታች';
$ec_lang['odt_h2_warn_tip']='የቀዳዳው ጫፍ = ማዕከል + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="ዲያሜትር (ክብ ከሆነ) ወይም ቁመት (አራት ማዕዘን ከሆነ)">የቀዳዳ D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="ለአራት ማዕዘን ቅርጽ ብቻ">የቀዳዳ ስፋት, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='ፍሳሽ ጊዜ (ሰከንዶች)';
$ec_lang['odt_t_min']='ፍሳሽ ጊዜ (ደቂቃዎች)';
$ec_lang['odt_t_hr']='ፍሳሽ ጊዜ (ሰዓታት)';
$ec_lang['odt_t_day']='ፍሳሽ ጊዜ (ቀናት)';
$ec_lang['odt_notes_1_term']='ቀመር';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ከሄድ H እስከ ቀዳዳ ድረስ ያለውን የፍሳሽ ጊዜ ይሰጣል። ፍሳሽ ጊዜ = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)፣ እዚህ ላይ H<sub>1</sub> = የጀምር ከፍታ − የቀዳዳ ከፍታ፣ H<sub>2</sub> = የማብቂያ ከፍታ − የቀዳዳ ከፍታ።';
$ec_lang['odt_notes_2_term']='ዘዴ';
$ec_lang['odt_notes_2_def']='ኮኒካዊ መጠን ዘዴ ኩሬውን ወይም ቤዝኑን ከጀምር ስፋት A<sub>1</sub> (በመጀመሪያው የውሃ ወለል) እስከ ስፋት A<sub>0</sub> (በቀዳዳው ማዕከል ከፍታ) ድረስ እንደ ኮኒካዊ ክፍል አድርጎ ያሞዳል። A<sub>2</sub>፣ ማለትም የኩሬው ስፋት በማብቂያ ከፍታ፣ ከ A<sub>1</sub> እና A<sub>0</sub> በኮኒካዊ ክፍል ሞዴል ተሰልቶ ይገኛል። ከጀምር እስከ ማብቂያ ከፍታ ያለው የፍሳሽ ጊዜ ከ H<sub>1</sub> እስከ ቀዳዳ ካለው ጠቅላላ የፍሳሽ ጊዜ ከ H<sub>2</sub> እስከ ቀዳዳ ከቀረው የፍሳሽ ጊዜ ሲቀነስ እኩል ይሆናል።';
$ec_lang['odt_h1']='<span class="ec-help" title="የጀምር የውሃ ወለል ከፍታ ሲቀነስ የቀዳዳው ማዕከል ከፍታ">የጀምር ሄድ, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='ከፍተኛ ፍሰት, Q<sub>max</sub>';
$ec_lang['odt_vol']='የፈሰሰ መጠን';
$ec_lang['odt_sketch_start']='ጅምር';
$ec_lang['odt_sketch_end']='ፍጻሜ';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='መስኖ';
$ec_lang['irr_main_title']='ነፃ ኦንላይን የመስኖ ፍሰት መለኪያ ካልኩሌተሮች';
$ec_lang['irr_main_desc']='የመስኖ ፍሰት መለኪያ — ዊር እና ቀዳዳ';
$ec_lang['irr_intro_html']='<p>ዊርና ቀዳዳ በመስኖ ስርዓቶች ውስጥ የውሃ ፍሰትን ለመለካት ደረጃዊ የመስክ መሳሪያዎች ናቸው። ከመዋቅርዎ ጋር የሚስማማውን ካልኩሌተር ይምረጡ፡</p>';
$ec_lang['irr_card_weir_uniform_head']='ዊር — ሰፊ ጫፍ (ወጥ ስፋት)';
$ec_lang['irr_card_weir_uniform_desc']='በዳይቨርሽን ግድብ ጫፍ፣ በመቆጣጠሪያ መዋቅር ወይም በዊር ሰሌዳ ላይ ያለውን ፍሰት ይለኩ። የዊሩን ርዝመትና ከጫፉ በላይ ያለውን የላይኛው ውሃ ጥልቀት ያስገቡ።';
$ec_lang['irr_card_weir_irregular_head']='ዊር — ያልተስተካከለ ገፅታ';
$ec_lang['irr_card_weir_irregular_desc']='የዊሩ ጫፍ ከፍታ ወይም ገፅታ ሲለያይ ይጠቀሙ — ተፈጥሯዊ መፍሰሻዎች፣ ስፋታቸው የሚለያይ የመውደቂያ መዋቅሮች፣ ወይም ብዙ ክፍሎች ያሉት የመቆጣጠሪያ መዋቅሮች።';
$ec_lang['irr_card_orifice_head']='ቀዳዳ — የራስጌ በር ወይም የቧንቧ መውጫ';
$ec_lang['irr_card_orifice_desc']='በመግቻ በር፣ በቧንቧ መውጫ ወይም በካልቨርት ክፍት ቦታ የሚያልፈውን ፍሰት ይለኩ። ነፃ ፍሳሽንም ተጥለቅልቆ (የታችኛ ውሃ) ሁኔታንም ራሱ ችሎ ይያዛል።';
$ec_lang['irr_card_canal_head']='የቦይ ዲዛይንና ትንተና';
$ec_lang['irr_card_canal_desc']='የማኒንግ ቀመር ተጠቅመው የመስኖ ቦይ ዲዛይን ያድርጉ ወይም ይፈትሹ። ለአዲስ ቦዮች ትራፔዞይዳዊ ካልኩሌተርን፤ ለነባር ተፈጥሯዊ ወይም ሰው ሠራሽ ክፍሎች ያልተስተካከለ ገፅታ ካልኩሌተርን ይጠቀሙ።';
$ec_lang['irr_card_seepage_head']='የቦይ ዘልቆ ማለፍና የቦይ ማጓጓዝ ብቃት';
$ec_lang['irr_card_seepage_desc']='በቦይ ክፍል ላይ የፍሰት መግቢያና መውጫ ልኬቶችን ተጠቅሞ የዘልቆ ማለፍ ኪሳራን ይገምቱ። የቦይ ማጓጓዝ ብቃትንና ዓመታዊ የውሃ ኪሳራን በማስላት የሽፋን ኢንቨስትመንት ቅድሚያ ለመስጠት ይረዳል።';
$ec_lang['irr_quickref_html']='<h3>ፈጣን ማጣቀሻ</h3><dl><dt>ዳይቨርሽን ግድብ ወይም መቆጣጠሪያ መዋቅር</dt><dd>ከዊሩ ጫፍ በላይ ያለውን የላይኛው ውሃ ጥልቀት ይለኩ። ለወጥ ጫፍ <a href="Weir-Flow-Simple.php">ቀላል ዊር ፍሰት</a>ን፣ ወይም ገፅታው ለተለያየ ወይም ደረጃ ላለው ጫፍ <a href="Weir-Flow-Irregular.php">ያልተስተካከለ ዊር ፍሰት</a>ን ይጠቀሙ።</dd><dt>የራስጌ በር ወይም የቧንቧ መውጫ</dt><dd>የላይኛውን ውሃ ከፍታና የታችኛውን ውሃ ከፍታ ይለኩ (ወይም ነፃ ፍሳሽ ከሆነ የቧንቧውን ወለል ከፍታ)። <a href="Orifice.php">ቀዳዳ ፍሰት</a>ን ይጠቀሙ። ለክብ ቧንቧ D = የቧንቧ ዲያሜትር፤ ለአራት ማዕዘን በር ስፋት W እና ቁመት D ያስገቡ።</dd><dt>የውሃ ማጠራቀሚያ ወይም የኩሬ ማፍሰሻ ጊዜ</dt><dd>ከስር ባለ ቀዳዳ በኩል ኩሬ ወይም ማጠራቀሚያ ዝቅ ለማድረግ የሚወስደውን ጊዜ ለመገመት <a href="Orifice-Drain-Time.php">የቀዳዳ ማፍሰሻ ጊዜ</a>ን ይጠቀሙ — ለመስኖ ማጠራቀሚያ እቅድ ጠቃሚ ነው።</dd><dt>የመስክ ደረጃዎች</dt><dd>እዚህ ጥቅም ላይ የዋሉት የዊርና የቀዳዳ ፍሰት እኩልታዎች በውሃ አስተዳዳሪዎችና በመስኖ ወረዳዎች ብዙ ጊዜ የሚፈለጉትን የ USBR <em>Water Measurement Manual</em> (3ኛ እትም) ሂደቶች ይከተላሉ።</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='የኤሚተር ክፍተት, S<sub>e</sub>';
$ec_lang['ip_sl']='የላተራል ክፍተት, S<sub>l</sub>';
$ec_lang['ip_n_e']='ኤሚተሮች በላተራል, n<sub>e</sub>';
$ec_lang['ip_n_l']='ላተራሎች በዞን, n<sub>l</sub>';
$ec_lang['ip_d']='ዒላማ የልፍፍ ጥልቀት, d';
$ec_lang['ip_a_e']='በአንድ ኤሚተር ስፋት, A<sub>e</sub>';
$ec_lang['ip_pr']='የልፍፍ መጠን, PR';
$ec_lang['ip_q_lat']='ፍሰት በላተራል, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='የዞን ፍሰት, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='የስራ ጊዜ (ሰዓታት)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='የቦይ ዘልቆ ማለፍ';
$ec_lang['cs_main_title']='ነፃ ኦንላይን የቦይ ዘልቆ ማለፍ ኪሳራና የቦይ ማጓጓዝ ብቃት ካልኩሌተር';
$ec_lang['cs_main_desc']='የቦይ ዘልቆ ማለፍ ኪሳራና የቦይ ማጓጓዝ ብቃት — የመግቢያ-መውጫ ዘዴ';
$ec_lang['cs_Q_in']='መግቢያ ፍሰት, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='መውጫ ፍሰት, Q<sub>out</sub>';
$ec_lang['cs_L']='የክፍል ርዝመት, L';
$ec_lang['cs_Q_loss']='የዘልቆ ማለፍ ኪሳራ መጠን, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='የልኬት ማረጋገጫ';
$ec_lang['cs_pct_loss']='የጠፋው ክፍልፋይ';
$ec_lang['cs_Ec']='የቦይ ማጓጓዝ ብቃት, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='የብቃት ደረጃ';
$ec_lang['cs_Vol_day']='በቀን የሚጠፋ መጠን';
$ec_lang['cs_Vol_year']='በዓመት የሚጠፋ መጠን';
$ec_lang['cs_Q_loss_per_L']='በአሃድ ርዝመት ኪሳራ, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='የውሃ ዋጋ';
$ec_lang['cs_lining_cost']='የሽፋን ወጪ';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="ከሽፋን በኋላ ያለው ዒላማ የቦይ ማጓጓዝ ብቃት፤ ክፍልፋይ 0&ndash;1">የሽፋን ዒላማ, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='የሽፋን ስፋት, L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='ዓመታዊ የጠፋ ዋጋ';
$ec_lang['cs_annual_value_recovered']='ዓመታዊ የተመለሰ ዋጋ';
$ec_lang['cs_lining_total_cost']='ጠቅላላ የሽፋን ወጪ';
$ec_lang['cs_payback_years']='<span class="ec-help" title="ቀላል የመመለሻ ጊዜ = ጠቅላላ የሽፋን ወጪ &divide; ዓመታዊ የተመለሰ ዋጋ">የመመለሻ ጊዜ <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — ዘልቆ ማለፍ ተገኝቷል';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — የሚለካ ኪሳራ የለም';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — ልኬቶቹን ያረጋግጡ';
$ec_lang['cs_Ec_good']='ጥሩ — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='መካከለኛ — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='ደካማ — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='የመግቢያ-መውጫ ዘዴ ዘልቆ ማለፍን የሚገምተው ፍሰትን በቦይ ክፍል ራስጌና ጫፍ ላይ በመለካት ነው: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>። የቦይ ማጓጓዝ ብቃት E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>። ዓመታዊው መጠን ያለማቋረጥ ሙሉ-ፍሰት ስራ እንደሚካሄድ ይገምታል፤ ትክክለኛው ኪሳራ ለወቅታዊ ወይም ከፊል-ፍሰት ቦዮች ያነሰ ይሆናል።';
$ec_lang['cs_notes_2_term']='የብቃት ደረጃዎች';
$ec_lang['cs_notes_2_def']='ዓይነተኛ ያልተሸፈኑ የምድር ቦዮች: E<sub>c</sub> = 60&ndash;80%። በደንብ የተጠበቁ የምድር ቦዮች: 75&ndash;85%። በኮንክሪት የተሸፈኑ ቦዮች: 90&ndash;98%። ከመግቢያ ፍሰቱ 30% በላይ የሆነ ዘልቆ ማለፍ ኪሳራ ብዙ ጊዜ የሽፋን ኢንቨስትመንትን ያጸድቃል። (USBR, FAO)';
$ec_lang['cs_notes_3_term']='የሽፋን መመለሻ';
$ec_lang['cs_notes_3_def']='የውሃ ዋጋንና የሽፋን ወጪን በማንኛውም ወጥ ምንዛሬ ያስገቡ። የሽፋን ስፋት = የክፍል ርዝመት &times; የተረጠቀ ዙሪያ &mdash; በተለካው የፍሰት ጥልቀት ላይ ያለው የቦይ መስቀለኛ ክፍል የተረጠቀ ዙሪያ (የታችኛው ስፋት ከሁለቱም የተረጠቁ ጎኖች ጋር)። የሚመለሰው ዓመታዊ ዋጋ የተሸፈነው ቦይ ዒላማ E<sub>c</sub>ን ያለማቋረጥ እንደሚያሳካ ይገምታል። ለወቅታዊ ቦዮች ወይም ሽፋኑ ዒላማ ብቃቱን ካላሳካ ትክክለኛው የመመለሻ ጊዜ ይረዝማል።';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3ኛ እትም (2001)። FAO Irrigation and Drainage Paper 57 (1999)።';
// About
$ec_lang['about_main_menu']='ስለ';
$ec_lang['install_main_menu']='ጫን';
$ec_lang['install_main_title']='EngCalcs ይጫኑ';
$ec_lang['install_main_desc']='ያለኢንተርኔት ለመጠቀም ወደ መሳሪያዎ ያክሉ';
$ec_lang['install_intro']='EngCalcs ፕሮግረሲቭ ዌብ አፕሊኬሽን (PWA) ነው። አንዴ ከተጫነ በኋላ፣ ሁሉም ማስያ መሳሪያዎች ያለ ኢንተርኔት ግንኙነት ሙሉ በሙሉ ይሠራሉ።';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>ማንኛውንም የማስያ ገጽ በChrome ይክፈቱ።</li><li>ከላይ ባለው የአሰሳ አሞሌ ላይ ያለውን <strong>⬇ ጫን</strong> የሚለውን ቁልፍ ይንኩ፣ ወይም የአሳሽ ምናሌውን (⋮) ይንኩና <strong>ወደ መነሻ ገጽ አክል</strong> የሚለውን ይምረጡ።</li><li>በሚታየው መልእክት ላይ <strong>ጫን</strong> የሚለውን ይንኩ።</li><li>EngCalcs በመነሻ ገጽዎ ላይ ይታያል እንዲሁም ያለ ኢንተርኔት ይሠራል።</li>';
$ec_lang['install_now_btn']='⬇ አሁን ጫን';
$ec_lang['install_prompt_unavailable']='የመጫኛ መልእክት አልተገኘም — በምትኩ የአሳሽዎን ምናሌ ይጠቀሙ።';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>ማንኛውንም የማስያ ገጽ በSafari ይክፈቱ።</li><li>የ<strong>አጋራ</strong> ቁልፍን ይንኩ (ወደ ላይ ቀስት ያለው ሳጥን)።</li><li>ወደ ታች ይሸብልሉና <strong>ወደ መነሻ ገጽ አክል</strong> የሚለውን ይንኩ።</li><li><strong>አክል</strong> የሚለውን ይንኩ። EngCalcs በመነሻ ገጽዎ ላይ ይታያል።</li>';
$ec_lang['install_ios_note']='በiOS ላይ፣ መጫን ሁልጊዜ የአጋራ ምናሌን ይጠቀማል — ራስ-ሰር የመጫኛ መልእክት የለም።';
$ec_lang['install_desktop_heading']='ዴስክቶፕ (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>ማንኛውንም የማስያ ገጽ ይክፈቱ።</li><li>በአሳሹ የአድራሻ አሞሌ ላይ ያለውን <strong>የመጫኛ ምልክት</strong>ን (⊕ ወይም የኮምፒዩተር ምልክት) ይጫኑ፣ ወይም የአሳሽ ምናሌውን ከፍተው <strong>EngCalcs ጫን…</strong> የሚለውን ይምረጡ።</li><li><strong>ጫን</strong> የሚለውን ይጫኑ። EngCalcs እንደ ራሱን የቻለ የመተግበሪያ መስኮት ይከፈታል።</li>';
$ec_lang['install_firefox_heading']='Firefox / ሌሎች አሳሾች';
$ec_lang['install_firefox_body']='Firefox በዴስክቶፕ ላይ PWA መጫንን አይደግፍም። ቢሆንም ሁሉንም ማስያ መሳሪያዎች በአሳሹ ውስጥ በመደበኛነት መጠቀም ይችላሉ — ከመጀመሪያ ጉብኝትዎ በኋላ፣ ገጾቹ ያለ ኢንተርኔት ጥቅም ላይ እንዲውሉ ራስ-ሰር ይቀመጣሉ።';
$ec_lang['install_cached_heading']='ምን ይቀመጣል';
$ec_lang['install_cached_body']='EngCalcs ን ለመጀመሪያ ጊዜ ሲጭኑ፣ ሁሉም የማስያ ገጾችና አጋዥ ፋይሎቻቸው (ስክሪፕቶች፣ ስታይሎች) በራስ-ሰር በመሳሪያዎ ላይ ይቀመጣሉ። ከዚያ በኋላ፣ ሁሉም ነገር ያለ ኢንተርኔት ግንኙነት ይሠራል። የቋንቋ ምርጫዎ ካለፈው የመስመር ላይ ጉብኝትዎ ይታወሳል።';
$ec_lang['contact_main_menu']='አግኙን';
$ec_lang['about_main_title']='ስለ HawsEDC የምህንድስና ካልኩሌተሮች';
$ec_lang['about_main_desc']='ተልዕኮ፣ ክፍት ምንጭ እና አስተዋጽዖ';
$ec_lang['about_body_html']='<h3>ተልዕኮ</h3><p>የ HawsEDC ምህንድስና ካልኩሌተሮች በዓለም ዙሪያ ላሉ መሐንዲሶችና የሜዳ ሠራተኞች ለማገልገል ናቸው — በተለይ ውሃ እጥረት፣ ሀብት ውስንነት ወይም ዝቅተኛ አገልግሎት ባለበት አካባቢ ለሚሰሩ። እነዚህ መሳሪያዎች ሰፊ ሰብዓዊ ተልዕኮ አካል ናቸው፡ ለእያንዳንዱ ሰው በጣም ተግባራዊ እና ውጤታማ በሆነ መንገድ መናገር — ለዘለዓለም የተወደዱ እና የሚቀሩ መሆናቸውን፣ ምንም ነገር ሊፈሩ አለመሆናቸውን፣ እና ሁሉንም ነገር ሊያበላሹ አለመሆናቸውን።</p><p>ካልኩሌተሮቹ መሳሪያ ናቸው። ዓላማው ስቃይ የሌለው ዓለም ነው።</p><h3>ክፍት ምንጭ ፍቃድ</h3><p>ሁሉም ኮድ በ<a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 ወይም ቆይቶ</a> ተለቋል — እንደ ነፃነቱ ነፃ። ተመሳሳይ ሁኔታዎች ስር ኮዱን መጠቀም፣ ማጥናት፣ ማሻሻል እና ማሰራጨት ይችላሉ።</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>ምንጭ ኮድ</h3><p>ሙሉ ምንጭ ኮድ በ Bitbucket ላይ ሕዝባዊ ሆኖ ይገኛል፡</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>ኮዱን መቃኘት፣ ጉዳዮችን ሪፖርት ማድረግ፣ ወይም ሪፖዚቶሪውን ፎርክ ማድረግ ይችላሉ።</p><h3>አስተዋፅኦ</h3><p>Pull Requests ተቀባይነት አላቸው። የአስተዋፅኦ ዘዴዎች:</p><ul><li><strong>ትርጉሞች</strong> — ቋንቋ ያሻሽሉ ወይም አዲስ ይጨምሩ። ተዛማጅ <code>lib/lang.ec.??.php</code> ፋይሉ ላይ ለውጦቹን ይዘው Pull Request ይክፈቱ።</li><li><strong>ስህተት ሪፖርቶች</strong> — በማንኛውም ካልኩሌተር ገጽ ላይ ያለውን የተጠቃሚ ሀሳብ ቅጽ ይጠቀሙ፣ ወይም ጉዳዩን ሪፖዚቶሪ ላይ ሪፖርት ያድርጉ።</li><li><strong>አዲስ ካልኩሌተሮች</strong> — ለሜዳ ሠራተኞችና ለመስኖ ባለሙያዎች የሚያገለግሉ የሃይድሮሊክ ምህንድስና ሃሳቦች በተለይ ተቀባይነት አላቸው። ሪፖዚቶሪ ውስጥ ያለውን <code>CLAUDE.md</code> የ ዲቨሎፐር መመሪያ ይዩ።</li><li><strong>ሆስቲንግ</strong> — ዝቅተኛ ኔትወርክ ባለው አካባቢ ካልኩሌተሮቹን ማሳያ ማድረግ ከቻሉ እባኮትን ያስፈልጋቸው ያነጋግሩን።</li></ul><h3>ያለ ኢንተርኔት አጠቃቀም</h3><p>እነዚህ ካልኩሌተሮች እንደ ፕሮግሬሲቭ ዌብ አፕ (PWA) ይሠራሉ። ከኢንተርኔት ጋር ሲገናኙ ማንኛውንም የካልኩሌተር ገጽ ይጎብኙ፣ እና አሳሽዎ ሁሉንም ካልኩሌተሮች በራስ-ሰር ያከማቻል። ከዚያ በኋላ ሁሉም ካልኩሌተሮች ያለ ኢንተርኔት ይሠራሉ — ኢንተርኔት አያስፈልግም።</p><p>ለ Android ወይም iOS፣ EngCalcs እንደ አፕ በመሣሪያዎ ላይ ለመጫን የአሳሽዎን "ወደ መነሻ ማያ ገጽ ጨምር" አማራጭ ይጠቀሙ። ለዴስክቶፕ፣ የጭነት አዶ በአሳሽዎ የአድራሻ አሞሌ ውስጥ ይፈልጉ።</p><p>እንዲሁም ማንኛውንም ካልኩሌተር ወደ አካባቢያዊ መሣሪያዎ ለማስቀመጥ የአሳሽዎን "እንደ… አስቀምጥ" ምናሌ መጠቀም ይችላሉ።</p><h3>ግንኙነት</h3><p>Tom Haws — ሃይድሮሊክ መሐንዲስ እና የእነዚህ ካልኩሌተሮች ደራሲ።<br />በማንኛውም ካልኩሌተር ገጽ ላይ ያለውን ተጠቃሚ ሀሳብ ቅጽ ይጠቀሙ፣ ወይም <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> ላይ ምንጭ ኮዱን ያስሱ።</p>';
$ec_lang['contact_title']='HawsEDC ያግኙን';
$ec_lang['contactSendMessage']='Tom Haws ላክ መልዕክት';
$ec_lang['contactYourName']='ስምህ:';
$ec_lang['contactYourEmail']='የኢሜይል አድራሻህ:';
$ec_lang['contactSubject']='ርዕሰ ጉዳይ:';
$ec_lang['contact_message']='መልዕክት:';
$ec_lang['contactSpamPrefix']='አምስት ሲደምር አንድ ይሆናል';
$ec_lang['contactSpamPostfix']='(እባክህ በቃላት ፃፍ። 1=አንድ 2=ሁለት 3=ሦስት 4=አራት 5=አምስት 6=ስድስት 7=ሰባት +=ሲደምር 5+1=6)';
$ec_lang['contactSubmitButton']='መልዕክት ላክ';
$ec_lang['contact_success']='ለመጻፍ ጊዜ ለወጣህ አመሰግናለሁ።';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='የድንጋይ-ምቀጫ ቦዩ ዲዛይን (Robinson)';
$ec_lang['rc_main_title']='ነፃ የመስመር ላይ የድንጋይ-ምቀጫ ቦዩ ዲዛይን ካልኩሌተር — Robinson (1998)';
$ec_lang['rc_main_desc']='የፈጣን ቦዩ ድንጋይ ሽፋን መጠን &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='የፈጣን ቦዩ ወለል ቁልቁለት, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="በፈጣን ቦዩ መግቢያ ላይ በአሃድ ስፋት ያለ ፍሰት። ጠቅላላ ፍሰት Q ላለው B የታች ስፋት ቦይ, q_t = Q / B ይጠቀሙ።">ጠቅላላ የአሃድ ፍሰት, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='የድንጋይ ሽፋን ቀዳዳማነት, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="ከውሃ አንጻር ያለው ጥግግት። ዓይነተኛ የተቀጠቀጠ ግራናይት ወይም ባዛልት ≈ 2.65። Robinson ትክክለኛ ወሰን፦ 2.54 እስከ 2.82።">የድንጋይ ልዩ ስበት, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="የቅንብር ስርጭት መደበኛ ልዩነት። ወጥ ድንጋይ ≈ 1.25። Robinson ትክክለኛ ወሰን፦ 1.15 እስከ 1.47።">የቅንብር ስርጭት SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="ኩሬ መያዝ (Hp > yn) ጥሩ ነው — ከላይ በኩል ያለውን ሸርሸራ ይቀንሳል። (USDA)">በመግቢያ ቦይ ውስጥ ያለ መደበኛ ጥልቀት, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="ቀ. 1 (S0 &lt; 0.10) ወይም ቀ. 2 (0.10-0.40)። ትክክለኛ ወሰን፦ D50 15-278 mm, S0 0.02-0.40። ከወሰን ውጭ፦ በግምት ተሰልቷል።">የሚፈለግ የድንጋይ መካከለኛ መጠን, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='የተተገበረ ቀመር';
$ec_lang['rc_sg_check']='የልዩ ስበት ምርመራ';
$ec_lang['rc_SD_check']='የቅንብር ስርጭት SD ምርመራ';
$ec_lang['rc_sg_ok']   ='sg በትክክለኛ ወሰን ውስጥ ነው';
$ec_lang['rc_sg_ok_tip']='2.54–2.82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg ከ Robinson ወሰን በታች';
$ec_lang['rc_sg_low_tip']='ትክክለኛ ወሰን፦ 2.54–2.82';
$ec_lang['rc_sg_high'] ='sg ከ Robinson ወሰን በላይ';
$ec_lang['rc_sg_high_tip']='ትክክለኛ ወሰን፦ 2.54–2.82';
$ec_lang['rc_SD_ok']   ='SD በትክክለኛ ወሰን ውስጥ ነው';
$ec_lang['rc_SD_ok_tip']='1.15–1.47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD ከ Robinson ወሰን በታች';
$ec_lang['rc_SD_low_tip']='ትክክለኛ ወሰን፦ 1.15–1.47';
$ec_lang['rc_SD_high'] ='SD ከ Robinson ወሰን በላይ';
$ec_lang['rc_SD_high_tip']='ትክክለኛ ወሰን፦ 1.15–1.47';
$ec_lang['rc_layer']='የድንጋይ ሽፋን ውፍረት (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='የላይኛው ጫፍ ኩርባ ራዲየስ (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='የላይኛው ጫፍ ኩርባ ቅስት ርዝመት';
$ec_lang['rc_apron_length']='<span class="ec-help" title="ለድንጋይ ሽፋን አወቃቀራዊ ድጋፍ ያስፈልጋል። &quot;በመውጫ ክፍልና በታችኛው ቦይ ተቃውሞ ምክንያት የሚፈጠረው ዝቅተኛ የጅራት ውሃ በመውጫ ክፍል ውስጥ ያለውን የድንጋይ ሽፋን መረጋጋት ለማረጋገጥ በቂ ነው።&quot; (Robinson)">የመውጫ ሰሌዳ ርዝመት (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='በፈጣን ቦዩ ውስጥ ያለ Manning ሻካራነት, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="የ q_t ክፍል በድንጋይ ቀዳዳዎች ውስጥ ያልፋል። ቀሪው q_s ከገጽ በላይ ይፈስሳል። ለማዕዘናዊ የተቀጠቀጠ ድንጋይ ነባሪ n_p = 0.45 ነው።">በድንጋይ ሽፋን ውስጥ ያለ ፍጥነት, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='በሽፋን ውስጥ የአሃድ ፍሰት, q<sub>m</sub>';
$ec_lang['rc_qs']='የገጽ አሃድ ፍሰት, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='ከድንጋይ ሽፋን ገጽ በላይ ያለ የፍሰት ጥልቀት, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="ኩሬ መያዝ (Hp > yn) ጥሩ ነው — ከላይ በኩል ያለውን ሸርሸራ ይቀንሳል። (USDA)">የመግቢያ ዌር ሄድ, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='የመግቢያ ኩሬ መያዝ ምርመራ';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — ከላይ በኩል ኩሬ ተይዟል';
$ec_lang['rc_pond_ok_tip']='ከፈጣን ቦዩ መግቢያ ከላይ በኩል ኩሬ መያዝ ጥሩ ነው፤ ከላይ በኩል ያለውን ሸርሸራ ይቀንሳል። (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — ኩሬ አልተያዘም — የመግቢያ ሸርሸራ ስጋት';
$ec_lang['rc_pond_warn_tip']='ከፈጣን ቦዩ መግቢያ ከላይ በኩል ኩሬ አልተያዘም፤ ከላይ በኩል ሸርሸራ ሊከሰት ይችላል። (USDA)';
$ec_lang['rc_eq1']='ቀመር 1 (S<sub>0</sub> < 0.10) — ቀስ ያለ ቁልቁለት';
$ec_lang['rc_eq2']='ቀመር 2 (0.10 ≤ S<sub>0</sub> ≤ 0.40) — ገደላማ ቁልቁለት';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0.02 — ከ Robinson ማረጋገጫ ወሰን በታች';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0.40 — ከ Robinson ማረጋገጫ ወሰን በላይ';
$ec_lang['rc_notes_1_term']='የድንጋይ መጠን ማቀናጀት ቀመሮች';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) በፈጣን ቦዩ ቁልቁለትና በአሃድ ፍሰት ላይ ተመስርተው ለመካከለኛ የድንጋይ ሽፋን መጠን D<sub>50</sub> ሁለት ተሞክሮአዊ ቀመሮችን አዘጋጅተዋል። ቀመር 1 ለልል ቁልቁለቶች (S<sub>0</sub> &lt; 0.10) ይሠራል፤ ቀመር 2 ለገደላማ ቁልቁለቶች (0.10 &le; S<sub>0</sub> &le; 0.40) ይሠራል። ሁለቱም ቀመሮች q<sub>t</sub>ን በ m&sup2;/s ይፈልጋሉ እና D<sub>50</sub>ን በሚሜ ይመልሳሉ። የተረጋገጠው ወሰን 0.02 &le; S<sub>0</sub> &le; 0.40 ነው።';
$ec_lang['rc_notes_2_term']='የአሃድ ፍሰት';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> በፈጣን ቦዩ ጫፍ ላይ ያለ ጠቅላላ የአሃድ ፍሰት ነው (በአሃድ ስፋት ጠቅላላ ፍሰት)። ጠቅላላ ፍሰት Q የያዘ B የታች ስፋት ላለው ቦይ፣ q<sub>t</sub> &asymp; Q / B ብለው ግምት ውሰዱ፣ ወይም በፈጣን ቦዩ መግቢያ ላይ ካለው ወሳኝ-ጥልቀት ሁኔታ ያሰሉት።';
$ec_lang['rc_notes_3_term']='በድንጋይ ሽፋን ውስጥ ፍሰት';
$ec_lang['rc_notes_3_def']='ከጠቅላላ ፍሰት ውስጥ ክፍል የሆነው በድንጋይ ሽፋን ቀዳዳዎች ውስጥ ያልፋል (የሽፋን ፍሰት q<sub>m</sub>)፤ ቀሪው ከድንጋይ ገጽ በላይ ይፈስሳል (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>)። የፍሰት ጥልቀት d የፈጣን ቦዩን ሻካራነት n ተጠቅሞ በገጽ ፍሰት q<sub>s</sub> ላይ ከ Manning&rsquo;s ቀመር ይሰላል። ለማዕዘናዊ የተቀጠቀጠ ድንጋይ ነባሪ ቀዳዳማነት n<sub>p</sub> = 0.45 ዓይነተኛ ነው።';
$ec_lang['rc_notes_5_term']='ትክክለኛ የድንጋይ መጠን ወሰን';
$ec_lang['rc_notes_5_def']='ቀመሮቹ ከ15&nbsp;ሚሜ እስከ 278&nbsp;ሚሜ የ D<sub>50</sub> ወሰን ተጠቅመው ተዘጋጅተዋል። ከዚህ ወሰን ውጭ ያሉ ውጤቶች በግምት የተሰሉ ሲሆኑ ተጨማሪ የምህንድስና ፍርድ ጋር ጥቅም ላይ መዋል አለባቸው።';
$ec_lang['rc_notes_6_term']='የመውጫ ሰሌዳ ከፍታ';
$ec_lang['rc_notes_6_def']='በመውጫ ክፍል ውስጥ ያለው የድንጋይ ሽፋን ጫፍ ከፍታ ከታችኛው ቦይ ወለል ከፍታ ጋር እኩል ወይም ከዚያ በታች መሆን አለበት። ከዚያ ከፍ ካለ፣ የመውጫ ድንጋይ አይረጋጋም።';
$ec_lang['rc_notes_7_def']='የመግቢያ ቦይ ውስጥ ያለው መደበኛ ጥልቀት q<sub>t</sub>ን ለማሳለፍ ከሚያስፈልገው ዌር ሄድ (H<sub>p</sub>) ያነሰ ሲሆን፣ ገደብ ያለው ፍሰት ወይም ኩሬ መያዝ ከፈጣን ቦዩ መግቢያ ከላይ በኩል ይከሰታል። ይህ በአጠቃላይ ተቀባይነት አለው &mdash; ኩሬ መያዝ ፍጥነትን ይቀንሳል እና ከላይ በኩል ያለውን ሸርሸራ ይከላከላል። ለማረጋገጥ፦ ለተሰጠው q<sub>t</sub> እና የጫፍ ስፋት H<sub>p</sub>ን ለማግኘት የዌር ፍሰት ካልኩሌተር ይጠቀሙ፣ ከመግቢያ ቦዩ መደበኛ ጥልቀት ጋርም ያወዳድሩት። H<sub>p</sub> ከመደበኛ ጥልቀት ቢበልጥ፣ ኩሬ መያዝ ይከሰታል።';
$ec_lang['rc_notes_4_term']='ማጣቀሻ';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">የድንጋይ-ምቀጫ ቦዮች ዲዛይን</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS ደግሞ በተመሳሳይ ዘዴ ላይ የተመሠረተ <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel ሰነድ</a> ያትማል።';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'ማጣሪያ';
$ec_lang['rc_sketch_top_crest_curve'] = 'የላይኛው ጫፍ ኩርባ';
$ec_lang['rc_sketch_outlet_apron']    = 'የመውጫ ሰሌዳ';
$ec_lang['rc_sketch_radius']          = 'ራዲየስ';
// Irrigation Pressure (Prefix ip_)
$ec_lang['ip_main_menu']='የመስኖ ግፊት';
$ec_lang['ip_main_title']='ነፃ ኦንላይን የመስኖ ግፊትና የስርጭት ወጥነት ካልኩሌተር';
$ec_lang['ip_main_desc']='የሙከራ ቅርንጫፍ ግፊትና የወጥነት ግምት';
$ec_lang['ip_h_supply']='የአቅርቦት ግፊት';
$ec_lang['ip_elev_supply']='የአቅርቦት ከፍታ, z<sub>supply</sub>';
$ec_lang['ip_q_design']='የኤሚተር ዲዛይን ፍሰት, q<sub>design</sub>';
$ec_lang['ip_h_design']='የኤሚተር ዲዛይን ግፊት';
$ec_lang['ip_x']='<span class="ec-help" title="ለመደበኛ ግፊት-ላልማይካካሱ ኤሚተሮች 0.5፤ ግፊት ለሚካክሱ ኤሚተሮች ወደ 0 ቅርብ">የኤሚተር ፍሰት ኤክስፖነንት, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='የሙከራ መንገድ';
$ec_lang['ip_group_reach']='ክፍል';
$ec_lang['ip_group_upstream']='የላይኛው ጎን';
$ec_lang['ip_group_downstream']='የታችኛው ጎን';
$ec_lang['ip_group_loss']='ኪሳራ';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="ምልክት ከተደረገ: ይህ ክፍል የሙከራው ላተራል አካል ነው፣ ውሃውም በእያንዳንዱ ኤሚተር ይወሰዳል። ምልክት ካልተደረገ: ይህ ክፍል ዋና መስመር ነው፣ ፍሰቱን በሙከራው መንገድ ላይ ወደሌሉ ላተራሎች ብቻ ያስተላልፋል።">ላተራል <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="የላተራል ረድፎች: በዚህ ክፍል ውስጥ ያሉ ኤሚተሮች ብቻ። የዋና መስመር ረድፎች: ከዚህ ክፍል በሚወጡ ሌሎች ላተራሎች ላይ ያሉ ጠቅላላ ኤሚተሮች። የሙከራው ላተራል በሚወጣበት ቦታ ላለው ክፍል፣ ከዚያ ነጥብ በኋላ በዋናው መስመር ላይ ያሉ ላተራሎች እና ያንኑ መገናኛ የሚጋሩ (ለምሳሌ በተቃራኒ በኩል ያለ ላተራል) ጭምር ይካተታሉ &mdash; ፍሰታቸው በዚሁ ክፍል በኩል ያልፋልና።">ኤሚተሮች <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="የዚህ ክፍል የታችኛው ጫፍ ከፍታ። ለውስጣዊ ረድፎች አማራጭ ነው (ባዶ ከተተወ ጠፍጣፋ / ከላይኛው ነጥብ ጋር እኩል ይወሰዳል)። ለመጨረሻው ረድፍ ግዴታ ነው: ያ እሴት የመጨረሻው ኤሚተር ከፍታ ነው፣ የሚያስፈልገውን የአቅርቦት ግፊት በቀጥታ ይወስናል።">የታች ከፍታ <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='የመጨረሻው ኤሚተር ከፍታ (የመጨረሻ ረድፍ) ባዶ ተትቶ ወደ ጠፍጣፋ ነባሪ ሆኗል &mdash; ትክክለኛ ውጤት ለማግኘት ያስገቡት';
$ec_lang['ip_flow']='ፍሰት';
$ec_lang['ip_press']='ግፊት.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="የክፍሉ ጠቅላላ ኪሳራ, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='ዝቅተኛ/አሉታዊ ግፊት &mdash; ከከባቢ አየር ግፊት በታች ያለ ሁኔታ መኖሩን ያረጋግጡ';
$ec_lang['ip_pressure_warn_short']='ዝቅተኛ';
$ec_lang['ip_h_far']='የመጨረሻው ኤሚተር ግፊት';
$ec_lang['ip_q_supply']='<span class="ec-help" title="ወደ ተቀረጸው የሙከራ መንገድ ብቻ የሚገባ ፍሰት እንጂ የመላው ዞን/ሲስተም አይደለም — ለመላው ሲስተም ድምር ከታች ባለው የዲዛይን ክፍል Q_zone ይመልከቱ።">የሙከራ መንገድ የአቅርቦት ፍሰት, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='የመጨረሻው ኤሚተር ፍሰት, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='አማካይ ኤሚተር ፍሰት (ሙከራ ላተራል), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="የተለመደ/አማካይ ላተራል ከዚህ የሙከራ ላተራል ጋር ሲነጻጸር በምን ያህል ከፍ (ወይም ዝቅ) ባለ ግፊት እንደሚሠራ የእርስዎ ግምት። የሙከራው ላተራል ሆን ተብሎ የተገመተው መጥፎው ሁኔታ ነው፣ ስለዚህ የራሱ አማካይ ለማሳ አማካይ ዝቅ ያለ ምትክ ነው &mdash; 0 ላይ ከተተወ፣ የወጥነት ማረጋገጫውና ከታች ያሉት የዲዛይን ቁጥሮች የሙከራውን ላተራል (ምናልባትም ተስፋ የሞላበት) አማካይ እንዳለ ይጠቀማሉ።">ግምታዊ &Delta;ግፊት, አማካይ ከሙከራው ላተራል ጋር <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral በእያንዳንዱ የላተራል ረድፍ ግፊት ላይ ከላይ የገባው የግፊት ልዩነት ተጨምሮ እንደገና ይሰላል &mdash; የሙከራው ላተራል የተገመተው መጥፎ ሁኔታ እንጂ ወካይ አለመሆኑን ለማስተካከል የሚደረግ ሙከራ። የወጥነት ማረጋገጫውንም ከታች ያለውን የዲዛይን ክፍልንም ይመግባል።">ግምታዊ የማሳ አማካይ የኤሚተር ፍሰት, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="የመጨረሻው ኤሚተር የተሰላ ፍሰት በግምታዊው የማሳ አማካይ የኤሚተር ፍሰት ሲካፈል &mdash; ይህ መደበኛው የታችኛው ሩብ የስርጭት ወጥነት (የታችኛው ቡድን አማካይ &divide; የጠቅላላው አማካይ) ግምታዊ ስሌት ነው፤ ነገር ግን ከትንሽ የተቀረጸ ናሙናና ተጠቃሚው ከገመተው እርማት እንጂ ከመላው ማሳ ስታቲስቲካዊ ናሙና አይደለም። 1 ወይም ከዚያ በላይ እሴቶች ይቻላሉ፤ ስህተትም አይደሉም: የመጨረሻው ኤሚተር ከግምታዊው የማሳ አማካይ አንጻር ዝቅተኛው ነጥብ አለመሆኑን ብቻ ያሳያል (ለምሳሌ ወደ ታች የሚወርድ ምቹ መስመር፣ ወይም ከላይ ያለው የ&Delta;ግፊት ግምት በጣም ትንሽ ነው)።">የወጥነት ማረጋገጫ, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='የሙከራው ኤሚተር ግፊት ከአቅርቦት ግፊት ጋር እኩል ወይም ከፍ ያለ ነው። ይህ ምናልባት እውነተኛው መጥፎ-ጫፍ ኤሚተር ላይሆን ይችላል፣ ወይም ቧንቧዎቹ ይበልጥ ትንሽ ሊደረጉ ይችላሉ።';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="ከመደበኛው የወጥነት መለኪያ ግምታችን የተለየ ነው።">የመጨረሻው ኤሚተር ፍሰት ከዲዛይን ፍሰት ጋር, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='ውጤት የለም፦ የሚያስፈልገው የአቅርቦት ግፊት ከገባው የአቅርቦት ግፊት ይበልጣል። የአቅርቦት ግፊት ይጨምሩ፣ ፍላጎትን ይቀንሱ፣ ወይም ትልቅ ቧንቧ ይጠቀሙ።';
$ec_lang['ip_notes_1_def']='በመጨረሻው (በጣም ሩቅ በሆነው) ኤሚተር ላይ ግፊቱን ይገምታል፣ ከዚያም የኃይል መስመሩን ወደ አቅርቦቱ በመመለስ፣ ክፍል በክፍል፣ የፍትጊያና የአካባቢ ኪሳራዎችን በመንገዱ ላይ ይጨምራል። በእያንዳንዱ ነጥብ ከፍታውና የፍጥነት ቁመቱ ተቀንሰው እዚያ ያለው ትክክለኛ ግፊት ይገለጻል። የተገመተው የሩቁ ጫፍ ግፊት (በሁለት መክፈል ዘዴ) እየተስተካከለ የተሰላው የሚያስፈልገው የአቅርቦት ግፊት ከገባው የአቅርቦት ግፊት ጋር እስኪመሳሰል ድረስ ይቀጥላል &mdash; በ Manning የቧንቧ ፍሰት ማስያ ላይ ያለው የቧንቧ ፍሰት መፍትሔ የሚፈታው ያው ዝግ ችግር ነው፣ ወደ ቅርንጫፍ አውታር የተስፋፋ።';
$ec_lang['ip_notes_2_term']='ዋና ክፍል vs. ላተራል ክፍል';
$ec_lang['ip_notes_2_def']='እያንዳንዱ ረድፍ ከአቅርቦቱ እስከ መጨረሻው ኤሚተር ባለው በአንዱ በሃይድሮሊክ በኩል መጥፎው መንገድ (የሙከራው መንገድ) ላይ ያለ አንድ ክፍል ነው። የዋና መስመር ክፍል ፍሰቱን በሙከራው መንገድ ላይ ወደሌሉ ላተራሎች ብቻ ያስተላልፋል፣ ስለዚህ የውሃ አወሳሰዱ ቀላል ማባዛት ነው (የዲዛይን ፍሰት &times; የክፍሉ ጠቅላላ የኤሚተር ብዛት) &mdash; የአካባቢ ግፊት ተጽዕኖ የለውም። ዋናው መስመር የጋራ ግንድ ቧንቧ ነው፣ ስለዚህ የሙከራው ላተራል በሚወጣበት ቦታ ያለው ክፍል በጫፎቹ መካከል ያሉትን ላተራሎች ብቻ ሳይሆን ከዚያ መውጫ በኋላ በዋናው መስመር ላይ ያሉትን ላተራሎች እና ያንኑ መገናኛ የሚጋሩትን (ለምሳሌ በተቃራኒ በኩል ያለ ላተራል) ጭምር ማካተት አለበት &mdash; ፍሰታቸው ከመለያየቱ በፊት በዚሁ ክፍል በኩል ያልፋል፣ በዚህ ሠንጠረዥ ሌላ ቦታ ቢታዩም ባይታዩም። የላተራል ክፍል የሙከራው ላተራል ራሱ አካል ነው: የኤሚተር ፍሰት ከትክክለኛው የአካባቢ ግፊት በ q = k&middot;H<sup>x</sup> ይሰላል፣ የፍትጊያ ኪሳራም እያንዳንዱ ኤሚተር ውሃ ሲወስድ ፍሰቱ ቀስ በቀስ መቀነሱን ለማካተት በ Christiansen F(n) መጠን ይቀነሳል።';
$ec_lang['ip_notes_3_term']='ገደብ';
$ec_lang['ip_notes_3_def']='አንድ ቋሚ የአቅርቦት ግፊት (የፓምፕ ኩርባ የለም)፣ አንድ የሙከራ መንገድ ብቻ (መላው ማሳ አይደለም)፣ እና ባለ ሁለት መለኪያ የኤሚተር ኩርባ ይቀርጻል (ግፊት የሚክስ ኤሚተርን ለመገመት ኤክስፖነንቱን ወደ 0 ቅርብ ያድርጉ)። ሁለት የተለያዩ ንጽጽሮች ሆን ተብለው ተለያይተው ይገለጻሉ: q<sub>last</sub>/q<sub>avg,field</sub> መደበኛው የታችኛው ሩብ የስርጭት ወጥነት (የታችኛው ቡድን አማካይ &divide; የጠቅላላው አማካይ) ግምታዊ ስሌት ነው፣ ነገር ግን ከሙከራው ላተራል ራሱ ከተቀረጹ ኤሚተሮች ተሰልቶ በገባው የ&Delta;ግፊት ግምት ይታረማል እንጂ ከመላው ማሳ ስታቲስቲካዊ ናሙና አይደለም &mdash; የሙከራው ላተራል ሆን ተብሎ የተገመተው መጥፎ ሁኔታ ነው፣ ስለዚህ ያልታረመው ጥሬ አማካዩ ትክክለኛውን የማሳ አማካይ አሳንሶ ወጥነቱን ከትክክለኛው በላይ ጥሩ አድርጎ ያሳይ ነበር፤ የ&Delta;ግፊት ግቤት ይህን አድልዎ ለመቋቋም በተለይ ነው ያለው። 1 ወይም ከዚያ በላይ እሴቶች አሁንም ይቻላሉ (ለምሳሌ የ&Delta;ግፊት ግምቱ በጣም ትንሽ ከሆነ፣ ወይም ወደ ታች የሚወርድ ምቹ መስመር ካለ)። q<sub>last</sub>/q<sub>design</sub> የተለየ፣ ከወጥነት ጋር ያልተያያዘ ማረጋገጫ ነው፣ ከአምራቹ የተሰጠው ፍሰት ጋር &mdash; በአጠቃላይ ግፊቱ የበዛበትን ወይም ያነሰበትን ሲስተም ለማወቅ ጠቃሚ ነው፣ ነገር ግን የወጥነቱን ቁጥር አይተካም፣ ምክንያቱም የዲዛይን/የተሰጠው ፍሰት ከሲስተሙ ትክክለኛ አማካይ የሥራ ግፊት ጋር ግዴታ ግንኙነት የለውም።';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. ASAE/ASABE ደረጃዎች ለጥቃቅን-መስኖ ንድፍ ተመሳሳይ የብዙ-መውጫ ፍትጊያ-ኪሳራ አካሄድ ይጠቀማሉ።';
$ec_lang['ip_notes_5_term']='የልፍፍ ዲዛይን';
$ec_lang['ip_notes_5_def']='የልፍፍ መጠንና የሲስተም/ዞን ፍሰት ግምታዊውን የማሳ አማካይ የኤሚተር ፍሰት ይጠቀማሉ (q<sub>avg,field</sub> &mdash; የሙከራው ላተራል ራሱ አማካይ፣ በገባው የ&Delta;ግፊት ግምት የታረመ) እንጂ የተገመተ መጠን አይደለም: PR = q<sub>avg,field</sub> / A<sub>e</sub>፣ ከታረመው የተቀረጸ እሴት ይመገባል። ርቀቶችና የመላው ሲስተም የላተራል/ኤሚተር ብዛቶች እዚህ የተለያዩ ግቤቶች ናቸው፣ ምክንያቱም የሙከራው መንገድ አንድ መጥፎ ቅርንጫፍ ብቻ ነው የሚቀርጸው እንጂ በማሳው ያለውን እያንዳንዱን ላተራል አይደለም።';
$ec_lang['irr_card_pressure_head']='የመስኖ ግፊትና ወጥነት';
$ec_lang['irr_card_pressure_desc']='የስርጭት ወጥነትን ከካታሎግ ኤሚተር ፍሰት መጠን ብቻ ሳይሆን ከትክክለኛው የሙከራ መንገድ ግፊት ለመገመት በዋና-ላተራል-ኤሚተር ቅርንጫፍ ላይ ያለውን የግፊትና ፍሰት መገለጫ ይቅረጹ።';


// --- Branched Pipe Network (bn_) --- English source / fallback (translation pending) ---
$ec_lang['bpn_main_menu']='Branched Pipe Network';
$ec_lang['bpn_main_title']='Free Online Branched Pipe Network Pressure Calculator (No Loops)';
$ec_lang['bpn_main_desc']='Branched (Tree) Pipe Network Flow and Pressure';
$ec_lang['bpn_h_source_tip']='Static supply head: the source head at zero flow. A reservoir or tank water level above the supply elevation, or a pump\'s shutoff head. Add supply points 2 and 3 to define a pump or varying-supply curve; the tool reads the head at the design flow.';
$ec_lang['bpn_elev_source']='Supply elevation';
$ec_lang['bpn_q_total']='Total flow';
$ec_lang['bpn_q_total_tip']='Total flow leaving the source (the sum of all demands in the network).';
$ec_lang['bpn_p_min']='Lowest pressure';
$ec_lang['bpn_p_min_tip']='The lowest downstream pressure anywhere in the network; the critical delivery point.';
$ec_lang['bpn_method']='Friction method';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='Pipe lines';
$ec_lang['bpn_id']='ID';
$ec_lang['bpn_id_tip']='Name of this pipe line. Other lines refer to it in the Upstream column.';
$ec_lang['bpn_upstream']='Upstream ID';
$ec_lang['bpn_upstream_tip']='ID of the line that feeds this one. Leave blank to follow the line directly above it (a plain series pipeline). Enter an ID here to branch off a different line.';
$ec_lang['bpn_roughness_tip']='Pipe roughness for the selected friction method: Manning n, Hazen-Williams C, or Darcy-Weisbach roughness height e (a length). Typical smooth plastic pipe: n about 0.009, C about 150, e about 0.0015 mm.';
$ec_lang['bpn_demand']='Demand';
$ec_lang['bpn_demand_tip']='Fixed flow delivered at this line\'s downstream end. Leave blank for a line that only carries flow onward.';
$ec_lang['bpn_elev_down']='DS elev.';
$ec_lang['bpn_q_line']='Line flow';
$ec_lang['bpn_q_line_tip']='Total flow carried by this line: its own demand plus every downstream demand it feeds.';
$ec_lang['bpn_p_down']='DS press.';
$ec_lang['bpn_p_down_tip']='Gauge pressure head at this line\'s downstream node. A negative value (flagged) means subatmospheric pressure; check the design.';
$ec_lang['bpn_sketch_title']='Network Diagram';
$ec_lang['bpn_show_length']='Length';
$ec_lang['bpn_show_diameter']='Diameter';
$ec_lang['bpn_show_q']='Flow';
$ec_lang['bpn_show_p']='Pressure';
$ec_lang['bpn_source_label']='Source';
$ec_lang['bpn_topology_warn']='Check the Upstream column: a line points to an unknown ID, references itself, or forms a loop, so part of the network is not connected to the source. Those lines are left unsolved.';
$ec_lang['bpn_topology_warn_short']='Network';
$ec_lang['bpn_pressure_warn']='Low/negative pressure; check for subatmospheric conditions';
$ec_lang['bpn_pressure_warn_short']='Low';
$ec_lang['bpn_notes_1_term']='Series by default, branch by exception';
$ec_lang['bpn_notes_1_def']='Leave Upstream ID blank and a line follows the one above it; a plain series pipeline. Enter an upstream line\'s ID to branch off it. So: series by default, a tree when you need it.';
$ec_lang['bpn_notes_2_term']='Branched networks only, no loops';
$ec_lang['bpn_notes_2_def']='Every line has exactly one upstream line (a tree). This tool does not solve looped networks; those need iterative methods (EPANET or similar). Leaving loops out is what keeps it simple and exact.';
$ec_lang['bpn_notes_3_term']='No active pressure controls';
$ec_lang['bpn_notes_3_def']='You can add a fixed minor-loss valve (a k-value), but not pressure-reducing or pressure-sustaining valves (PRV/PSV). Their open/closed state depends on flow and pressure, which would force iteration.';
$ec_lang['bpn_supply2_q']='Supply flow 2';
$ec_lang['bpn_supply2_h']='Supply head 2';
$ec_lang['bpn_supply3_q']='Supply flow 3';
$ec_lang['bpn_supply3_h']='Supply head 3';
$ec_lang['bpn_supply_pt_tip']='Optional supply-curve points 2 and 3. Enter a flow and head for each to model a pump, or any source whose head drops as it delivers more; the tool reads the head at the design flow. Point 1 above is the static head at zero flow. Leave 2 and 3 blank for a constant reservoir head.';
$ec_lang['bpn_h_supply']='Supply head';
$ec_lang['bpn_h_supply_tip']='Source head at the design flow, read from the supply curve. Equals the entered source head when the curve is flat (a reservoir).';
$ec_lang['bpn_show_elevation']='Elevation';
$ec_lang['bpn_supply1_h']='Static supply head';
