<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='کسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% میل';
$ec_lang['u_grade']='میل';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC محاسبې';
$ec_lang['menu_main_list']='د محاسبو لیست';
$ec_lang['menu_main_hydraulics']='هایدرولیک';
$ec_lang['menu_main_language']='ژبه';
$ec_lang['menu_more']='نور';
$ec_lang['template_welcome']='>> خپل ویرونه دروازې ته پرېږده؛ دلته مینه زموږ ژبه ده. ته هر څه خرابوي نه یې. د <a target="_blank" href="https://hawsedc.com/download.php">وړیا HawsEDC AutoCAD وسیلو</a> خوند هم واخله. <<';
$ec_lang['template_translation_help']='ایا ستاسو د دلته د زیاتولو لپاره د کومې محاسبې لویه لید لرئ؟ ایا تاسو کولی شئ چې ژباړه، پروګرامولو، یا دا محاسبې کوربه کولو کې مرسته وکړئ؟  ';
$ec_lang['template_feedback']='مهرباني وکړئ خپلې ارزښتناکې وړاندیزونه یا ستاینې موږ ته راولیږئ. ایا دې وړیا محاسبې ستاسو تمې له هر اړخه پوره کړل؟';
$ec_lang['template_printable_title']='د چاپ سرلیک';
$ec_lang['template_printable_subtitle']='د چاپ فرعي سرلیک';
$ec_lang['index_title']='وړیا آنلاین انجینري محاسبې';
$ec_lang['calc_set_units']='واحدونه تنظیم کړئ:';
$ec_lang['calc_defaults']='د ډيفالټ ارزښتونه';
$ec_lang['calc_defaults_confirm']='ایا محاسبه اصلي (لومړنیو) ډيفالټ ارزښتونو ته بیرته تنظیم شي؟';
$ec_lang['points_data_help']='(یا د معلوماتو ساحې له لارې کاپي/پیسټ وکړئ)';
$ec_lang['points_data_title']='د نقطو معلومات<br />(د کوما یا ټب لخوا جلا شوي)';
$ec_lang['points_data_copy']='کاپي';
$ec_lang['points_data_paste']='پیسټ';
$ec_lang['calc_inputs']='ننوتنې';
$ec_lang['calc_results']='پایلې';
$ec_lang['view_hide_line']='[دا کرښه پټه کړئ]';
$ec_lang['view_printable']='د چاپ وړ نسخه (د بیا ترلاسه کولو لپاره بیا پورته کړئ)';
$ec_lang['ec_name_label']='دا محاسبه خوندي کړئ:';
$ec_lang['ec_name_placeholder']='نوم';
$ec_lang['ec_name_hint']='دا ننوتنې URL ته خوندي کوي د نشان کتاب، تاریخ بیر کیدو، او شریکولو لپاره';
$ec_lang['calc_copy_link']='لینک کاپي کړئ';
$ec_lang['calc_copy_link_done']='کاپي شو!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach د پایپ سر ضیاع';
$ec_lang['dw_main_title']='وړیا آنلاین Darcy-Weisbach د پایپ سر ضیاع محاسبه';
$ec_lang['dw_main_desc']='Darcy-Weisbach د پایپ سر ضیاع د ورکړل شوي قطر، خشونت، او بهاو سره';
$ec_lang['dw_roughness']='خشونت، e';
$ec_lang['dw_roughness_tip']='<span title="د Darcy-Weisbach د خشونت لوړوالی" class="ec-tip">?</span>';
$ec_lang['dw_kinematic_viscosity']='د حرکتي ویسکوزیته، &nu; <span title="د پاکو اوبو لپاره 1×10⁻⁶ m²/s په 20°C کې" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='د Reynolds عدد، Re';
$ec_lang['dw_flow_regime']='د بهاو رژیم';
$ec_lang['dw_regime_laminar']='لامینار';
$ec_lang['dw_regime_transitional']='انتقالي';
$ec_lang['dw_regime_turbulent']='توربولنت';
$ec_lang['dw_friction_factor_method']='د اصطکاک فاکتور میتود';
$ec_lang['dw_friction_factor']='د اصطکاک فاکتور، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams د پایپ سر ضیاع';
$ec_lang['hw_main_title']='وړیا آنلاین Hazen-Williams د پایپ سر ضیاع محاسبه';
$ec_lang['hw_main_desc']='Hazen-Williams د پایپ سر ضیاع د ورکړل شوي قطر، خشونت، او بهاو سره';
$ec_lang['hw_hgl_1']='ښکته HGL';
$ec_lang['hw_hgl_2']='پورته HGL';
$ec_lang['hw_roughness']='Hazen-Williams ضریب، C';
// Manning Irregular
$ec_lang['mi_menu']='Manning د غیریکسانې مقطع چینل';
$ec_lang['mi_main_title']='وړیا آنلاین Manning د غیریکسانې مقطع چینل محاسبه';
$ec_lang['mi_main_desc']='د غیریکسانې مقطع چینل Manning یکسان بهاو محاسبه';
$ec_lang['mi_waterSurfaceElevation']='د اوبو سطحې لوړوالی';
$ec_lang['mi_q_617']='Q <span title="مرکب بهاو، Q، چې د Chow 6-17 له مخې د هرې سیمې لپاره د مرکب n او مساوي سرعتونو په کارولو سره ټاکل کیږي" class="ec-tip">?</span>';
$ec_lang['mi_xSecPoints']='د مقطع نقطې';
$ec_lang['mi_groupPoint']='نقطه';
$ec_lang['mi_groupSegment']='برخه';
$ec_lang['mi_groupRegion']='سیمه';
$ec_lang['mi_station']='چینج';
$ec_lang['mi_elevation']='لوړوالی';
$ec_lang['mi_d50in']='د پوښ<br />منځنۍ<br />کاڼو<br />اندازه';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />د سیمې<br />حد<br />(غاړه)';
$ec_lang['mi_tau']='لاندینۍ<br />قیچي<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='مرکب<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='یادداشتونه';
$ec_lang['mi_notes_1_term']='مرکب n';
$ec_lang['mi_notes_1_def']='دا محاسبه د HEC-RAS د حوالې لارښود پیروي کوي چې د Chow 1959، مخ 136، معادله 6-17 (نه 6-18) کارولو سره د سیمې مرکب n حساب کوي.';
$ec_lang['mi_notes_2_term']='د کاڼو پوښ';
$ec_lang['mi_notes_2_def']='د کاڼو پوښ ډیزاین کولو لپاره د Manning ذوزنقه چینل محاسبه وکاروئ. دا محاسبه د طبیعي مقطعونو لپاره ډیره مناسبه ده.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning د پایپ بهاو';
$ec_lang['mpf_main_title']='وړیا آنلاین Manning د پایپ بهاو محاسبه';
$ec_lang['mpf_main_desc']='د Manning فارمول یکسان د پایپ بهاو د ورکړل شوي میل او ژوروالي سره';
$ec_lang['mpf_spreadheet_notice']='د دې محاسبې د سپریډشیټ نسخه وګورئ';
$ec_lang['mpf_pipe_diameter']='د پایپ قطر، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='د مانینګ خشونت، n';
$ec_lang['mpf_friction_slope']='د اصطکاک میل (کله ناکله <a target="_blank" href="../frictionslope.php">?</a> د پایپ میل سره مساوي)، S<sub>f</sub>';
$ec_lang['mpf_depth_ratio']='د بهاو نسبي ژوروالی، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(یادداشتونه وګورئ)';
$ec_lang['mpf_flow']='بهاو، Q';
$ec_lang['mpf_velocity']='سرعت، v';
$ec_lang['mpf_velocity_head']='د سرعت سر، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='د بهاو مساحت، A';
$ec_lang['mpf_pipe_area']='د پایپ مساحت، A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='نسبي مساحت، A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='د لندوالي محیط، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='هایدرولیکي شعاع، R<sub>h</sub>';
$ec_lang['mpf_top_width']='پورتني پلنوالی، T';
$ec_lang['mpf_froude_number']='د Froude عدد، Fr';
$ec_lang['mpf_shear_stress']='منځنی برشي فشار (کششي ځواک)، &tau;';
$ec_lang['mpf_full_flow']='بشپړ بهاو، Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='د بشپړ بهاو نسبت، Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>دا د یوه <em>بې نهایته اوږد</em> پایپ دننه بهاو او ژوروالی دی.</dt><dd>د پایپ ته د بهاو داخلولو لپاره ممکن د پام وړ لوړ سرسر ژوروالی ته اړتیا وي. د سرسر ژوروالي ترلاسه کولو لپاره لږ تر لږه ۱.۵ ځله د سرعت سر زیات کړئ، یا د HY-8 کارولو سره د معیاري کلورټ سرسر محاسبو لپاره <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">زما دوه دقیقو ټیوټوریل وګورئ</a>.</dd>';
$ec_lang['mpf_solve_for_dd0']='د ورکړل شوي Q لپاره y/d<sub>0</sub> حل کول';
$ec_lang['mpf_solve_desc']='د محاسبې فورمه د d<sub>0</sub>، n، او S<sub>f</sub> کارولو سره، د ورکړل شوي Q لپاره ټیټ ترین y/d<sub>0</sub> پیدا کوي.';
$ec_lang['mpf_solve_button']='حل کړئ';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning د پایپ سر ضیاع';
$ec_lang['mphl_main_title']='وړیا آنلاین Manning د پایپ سر ضیاع محاسبه';
$ec_lang['mphl_main_desc']='د Manning فارمول سر ضیاع د ورکړل شوي بشپړ بهاو سره';
$ec_lang['mphl_pipe_length']='د پایپ اوږدوالی، L';
$ec_lang['mphl_area']='مساحت، A';
$ec_lang['mphl_total_junction_k']='د ځایی ضیاع ضریب، k<sub>m</sub>';
$ec_lang['mphl_friction_slope']='د اصطکاک میل';
$ec_lang['mphl_friction_loss']='د اصطکاک ضیاع، h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='ځایی ضیاع، h<sub>m</sub>';
$ec_lang['mphl_total_loss']='ټول ضیاع، h<sub>L</sub>';
$ec_lang['mphl_egl_1']='ښکته EGL';
$ec_lang['mphl_egl_2']='پورته EGL';
$ec_lang['mphl_hgl_2']='د پایپ پورته HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>د خلاص دننه ننوت (کلورټ) د حالت لپاره، د ننوت کنترول حالتونو چک کول اړین دي.</dt><dd>۱. پورتني HGL د پورتني نورمال ژوروالي د بهاو لوړوالي (یا د پایپ لاندې) کمیدلی نشي.</dd><dd>۲. د کلورټ سرسر د پورتني EGL له خوا د پورتني HGL پر ځای ښه استازولی کیږي.</dd><dd>۳. د HY-8 کارولو سره د ساده معیاري کلورټ سرسر محاسبو لپاره <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">زما دوه دقیقو ټیوټوریل وګورئ</a>.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning ذوزنقه چینل';
$ec_lang['mtc_main_title']='وړیا آنلاین Manning فارمول ذوزنقه چینل محاسبه';
$ec_lang['mtc_main_desc']='Manning فارمول یکسان ذوزنقه چینل بهاو د ورکړل شوي میل او ژوروالي سره';
$ec_lang['mtc_bottom_width']='لاندیني پلنوالی، b';
$ec_lang['mtc_side_slope_1']='د اړخ میل ۱، z<sub>1</sub> (افقي/عمودي)';
$ec_lang['mtc_side_slope_2']='د اړخ میل ۲، z<sub>2</sub> (افقي/عمودي)';
$ec_lang['mtc_channel_slope']='د چینل میل، S';
$ec_lang['mtc_flow_depth']='د بهاو ژوروالی، y';
$ec_lang['mtc_bend_angle']='د ګوډ زاویه، β <a target="_blank" href="riprap-bend-angle.png" title="د انځور لپاره کلیک وکړئ">?</a> (د ریپراپ اندازه کولو لپاره)';
$ec_lang['mtc_sgrock']='د کاڼو ځانګړی ثقل، sg <span title="د ماتو شویو کاڼو لپاره معمولا &asymp; 2.65" class="ec-tip">?</span>';
$ec_lang['mtc_d50_in']='د ډیزاین کاڼو اندازه، D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='د Strickler له مخې د ډیزاین کاڼو اندازې لپاره n';
$ec_lang['mtc_n_blodgett']='د Blodgett له مخې د ډیزاین کاڼو اندازې لپاره n';
$ec_lang['mtc_n_bathurst']='د Bathurst له مخې د ډیزاین کاڼو اندازې لپاره n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett مقابل Bathurst';
$ec_lang['mtc_d50_bottom']='اړین لاندیني زاویه لرونکي کاڼو اندازه، D<sub>50</sub> (Isbash او MC) <span title="د Isbash (1936) او Maricopa County, Arizona, US له مخې." class="ec-tip">?</span>';
$ec_lang['mtc_d50_z1']='اړین د اړخ میل ۱ زاویه لرونکي کاڼو اندازه، D<sub>50</sub> (Isbash او MC) <span title="د Isbash (1936) او Maricopa County, Arizona, US له مخې." class="ec-tip">?</span>';
$ec_lang['mtc_d50_z2']='اړین د اړخ میل ۲ زاویه لرونکي کاڼو اندازه، D<sub>50</sub> (Isbash او MC) <span title="د Isbash (1936) او Maricopa County, Arizona, US له مخې." class="ec-tip">?</span>';
$ec_lang['mtc_d50_mra']='اړین زاویه لرونکي کاڼو اندازه، D<sub>50</sub> (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='اړین زاویه لرونکي کاڼو اندازه، D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_check']='د سرعت کتنه';
$ec_lang['mtc_vel_ok']='سرعت د یکنواخت بهاو فرضیو لپاره معقول دی.';
$ec_lang['mtc_vel_high']='سرعت لوړ دی — د انتقالي ضیاعاتو، د دسترس وړ انرژۍ او د اوبو چکش کتنه وکړئ.';
$ec_lang['mtc_vel_low']='سرعت ټیټ دی — د رسوب خطر.';
$ec_lang['mtc_vel_ok_short']='ٹھیک';
$ec_lang['mtc_vel_high_short']='لوړ';
$ec_lang['mtc_vel_low_short']='ټیټ';
$ec_lang['mtc_note_1']='<dl><dt>د کاڼو اندازه او خشونت ډیزاین اتوماتیک تکرار</dt><dd>یو د خشونت اختیار (Blodgett–Bathurst وړاندیز کیږي) او د ډیزاین کاڼو اندازې اختیار (Isbash وړاندیز کیږي) غوره کړئ. ژوروالی او د کاڼو اندازې امنیتي فاکتور سم کړئ ترڅو خپل غوښتل شوي بهاو د مساوي کاڼو اندازې سره ترلاسه کړئ. هر ځل چې تاسو کوم داخلي ارزښت بدل کړئ، لاندینی تکرار دور پیښیږي: ۱. خشونت د ډیزاین کاڼو اندازې له مخې محاسبه کیږي. ۲. غوښتل شوي خشونت محاسبه د داخلي خشونت ته کاپي کیږي. ۳. د چینل بهاو او اړین کاڼو اندازه محاسبه کیږي. ۴. د ډیزاین کاڼو اندازه تنظیمیږي. ۵. د ډیزاین کاڼو اندازې کې تیروتنه ډیره کوچنۍ شي پورې تکرار کیږي.</dd><dt>اساسي محاسبه (بدون تکرار)</dt><dd>خپل غوښتل شوي خشونت ارزښت داخل کړئ. د ډیزاین کاڼو اندازې داخلي ساحه له پامه غورځوئ.</dd></dl>';
$ec_lang['mtc_note_2_term']='د سرعت کتنه';
$ec_lang['mtc_note_2_def']='لوړ سرعت د شتون لرونکي لوېدل څخه لوړ ځانګړی انرژي ښيي. هغه انرژي کولی شي د پراختیاوو، ګوډونو، یا خنډونو کې ژر له لاسه ورکړل شي. تصدیق وکړئ چې دا د سایټ لپاره معقول دی.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='ساده ویر بهاو';
$ec_lang['ws_main_title']='وړیا آنلاین ساده پراخ تاج لرونکي ویر بهاو محاسبه';
$ec_lang['ws_main_desc']='ساده پراخ تاج لرونکي ویر بهاو محاسبه';
$ec_lang['ws_weirLength']='د ویر اوږدوالی، L';
$ec_lang['ws_headWaterHeight']='سر، h';
$ec_lang['ws_weirCoefficient']='د ویر ضریب، C<sub>w</sub>';
$ec_lang['ws_notes_heading']='یادداشتونه';
$ec_lang['ws_notes_we_term']='د ویر معادله';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='غیریکسانه ویر بهاو';
$ec_lang['wi_main_title']='وړیا آنلاین برخوي، متغیر ژوروالي، غیریکسانه ویر بهاو محاسبه';
$ec_lang['wi_main_desc']='غیریکسانه ویر بهاو محاسبه';
$ec_lang['wi_headWaterelevation']='د سرسر لوړوالی';
$ec_lang['wi_weirPoints']='د ویر نقطې';
$ec_lang['wi_station']='سټیشن<br />(واټن)';
$ec_lang['wi_elevation']='لوړوالی';
$ec_lang['wi_pondingHeight']='د ډنډ لوړوالی';
$ec_lang['wi_incrementalFlow']='برخوي بهاو';
$ec_lang['wi_cumulativeFlow']='ټولیز بهاو';
$ec_lang['wi_save_and_calculate']='خوندي کړئ او محاسبه وکړئ';
$ec_lang['wi_notes_we_term']='د ویر معادله';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='د سوري بهاو';
$ec_lang['or_main_title']='وړیا آنلاین د سوري بهاو محاسبه';
$ec_lang['or_main_desc']='د سوري بهاو — آزاد یا لاندې اوبو';
$ec_lang['or_shape']='د خلاص شکل';
$ec_lang['or_shape_circular']='دایروي';
$ec_lang['or_shape_rectangular']='مستطیلي';
$ec_lang['or_diameter']='قطر یا لوړوالی، D <span title="د دایروي لپاره قطر؛ د مستطیلي لپاره لوړوالی" class="ec-tip">?</span>';
$ec_lang['or_width']='پلنوالی، W <span title="یوازې مستطیلي سوري" class="ec-tip">?</span>';
$ec_lang['or_invert']='انورټ لوړوالی <span title="د خلاص لاندنۍ برخه" class="ec-tip">?</span>';
$ec_lang['or_hwe']='د پورته اوبو سطح';
$ec_lang['or_twe']='د ښکته اوبو سطح';
$ec_lang['or_cd']='د بهاو ضریب، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='د مرکز لوړوالی';
$ec_lang['or_head']='مؤثر سر، h';
$ec_lang['or_area']='د خلاص مساحت، A';
$ec_lang['or_flow']='بهاو، Q';
$ec_lang['or_velocity']='سرعت، v';
$ec_lang['or_regime']='د سوري رژیم چک';
$ec_lang['or_regime_valid']='آزاد وتل';
$ec_lang['or_regime_submerged']='لاندې اوبو کې سوری';
$ec_lang['or_regime_submerged_tip']='TWE د مرکز نه پورته دی — د سوري رژیم لا هم معتبر دی';
$ec_lang['or_regime_warn']='د سوري له رژیم نه بهر';
$ec_lang['or_regime_warn_tip']='پورته اوبه د تاج (خلاص پورتنۍ برخه) نه لاندې دي';
$ec_lang['or_regime_twe_above_hwe']='ننوتنې وګورئ';
$ec_lang['or_regime_twe_above_hwe_tip']='د ښکته اوبو سطحه (TWE) د پورته اوبو سطحې (HWE) نه پورته ده';
$ec_lang['or_notes_1_term']='د سوري معادله';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). د آزاد وتلو لپاره: h = HWE − مرکز. د لاندې اوبو بهاو لپاره (TWE د انورټ پورته): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='د سوري رژیم';
$ec_lang['or_notes_2_def']='د سوري بهاو معادلې هغه وخت پلي کیږي کله چې د پورته اوبو سطحه د خلاص د تاج (پورتنۍ برخې) نه پورته وي. کله چې پورته اوبه د تاج نه لاندې وي، پر ځای یې د ویر معادله وکاروئ.';
$ec_lang['or_notes_3_term']='د بهاو ضریب';
$ec_lang['or_notes_3_def']='C<sub>d</sub> د تیزو غاړو لرونکو سوریو لپاره شاوخوا 0.60–0.65 پورې وي. ګرد شوي یا شاته ننوتلي ننوتونه بېل ارزښتونه کاروي. د لارښوونې لپاره <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> یا HEC-RAS هایدرولیک حوالې لارښود وګورئ.';
$ec_lang['or_notes_4_term']='لاندې اوبو حالت';
$ec_lang['or_notes_4_def']='کله چې TWE د خلاص انورټ پورته وي، دا محاسبه اتوماتیک د لاندې اوبو د سوري معادله h = HWE − TWE کاروي. کله چې TWE د انورټ پر سطحه یا لاندې وي، آزاد وتل فرض کیږي او h = HWE − مرکز.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='مایکرو هایدرو ځواک';
$ec_lang['mhp_main_title']='وړیا آنلاین مایکرو هایدرو ځواک محاسبه';
$ec_lang['mhp_main_desc']='د سیند د طبیعي بهاو (Run-of-River) پر بنسټ د مایکرو هایدرو ځواک محصول محاسبه';
$ec_lang['mhp_flow']='د بهاو مقدار، Q';
$ec_lang['mhp_gross_head']='ناخالص سر، H<sub>gross</sub>';
$ec_lang['mhp_diameter']='د فشار لولې قطر، D';
$ec_lang['mhp_length']='اوږدوالی، L <span title="د ننوتنځي (د اوبو د اخیستو ودانۍ) رسوونکی پایپ یا فلیوم اوږدوالی" class="ec-tip">?</span>';
$ec_lang['mhp_roughness']='د پایپ خشونت، e';
$ec_lang['mhp_km']='د جنکشن ضیاع ضریب، k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='د حرکت ویسکوزیته، ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='د پلانټ موثریت، η (0–1)';
$ec_lang['mhp_velocity']='د بهاو سرعت، v';
$ec_lang['mhp_vel_check']='د سرعت کتنه';
$ec_lang['mhp_f']='د اصطکاک فاکتور، f';
$ec_lang['mhp_hf']='د اصطکاک د سر ضیاع، h<sub>f</sub>';
$ec_lang['mhp_hm']='د سر ضیاع، h<sub>m</sub>';
$ec_lang['mhp_hl']='د Penstock ټول ضیاع، h<sub>L</sub>';
$ec_lang['mhp_hl_check']='د سر ضیاع کتنه';
$ec_lang['mhp_hnet']='خالص سر، H<sub>net</sub>';
$ec_lang['mhp_power']='د ځواک محصول، P';
$ec_lang['mhp_annual_kwh']='کلنۍ انرژي د ۱۰۰٪ ظرفیت پر مهال';
$ec_lang['mhp_vel_low']='سرعت ټیټ دی؛ د رسوب کیدو او هوا ننوتلو خطر شته.';
$ec_lang['mhp_vel_high']='سرعت لوړ دی؛ د لېږد ضیاعات، شته انرژي، او د اوبو چکش وکتل شي.';
$ec_lang['mhp_vel_ok_short']='ښه';
$ec_lang['mhp_vel_high_short']='لوړ';
$ec_lang['mhp_vel_low_short']='ټیټ';
$ec_lang['mhp_hl_ok']='د ۱۰٪ موخې دننه';
$ec_lang['mhp_hl_warn']='د ۱۰٪ موخې نه ډیر — د لوی پایپ کارول په پام کې ونیسئ';
$ec_lang['mhp_hl_warn_tip']='د لوی پایپ کارول په پام کې ونیسئ';
$ec_lang['mhp_hl_bad']='د ۲۰٪ نه ډیر — پایپ بیا اندازه کړئ';
$ec_lang['mhp_hl_bad_tip']='پایپ بیا اندازه کړئ';
$ec_lang['mhp_notes_1_term']='د سر ضیاع';
$ec_lang['mhp_notes_1_def']='د فشار لولې ټول ضیاع h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، چیرې چې h<sub>f</sub> = f(L/D)(v²/2g) د Darcy-Weisbach اصطکاک ضیاع دی او h<sub>m</sub> = k<sub>m</sub>·v²/2g ننوتنځی، ګوډونه، او والوونه پوښي. خالص سر H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub> دی.';
$ec_lang['mhp_notes_2_term']='سرعت';
$ec_lang['mhp_notes_2_def']='باور وکړئ چې سرعت د شته لوېدنې او د پایپ لګښت لپاره منطقي دی. ډیر ټیټ سرعت ښایي د اندازې زیاتوالي نښه وي؛ ډیر لوړ سرعت کولی شي د اصطکاک ضیاعات او د اوبو چکش خطر زیات کړي.';
$ec_lang['mhp_notes_3_term']='د سر ضیاع موخه';
$ec_lang['mhp_notes_3_def']='د ناخالص سر د ۱۰٪ نه کم د فشار لولې ضیاعات معمولاً اقتصادي دي. د پایپ لګښت او د ضایع شوي ځواک ترمنځ غوره تعادل ډیری وختونه شاوخوا ۴–۶٪ کې واقع کیږي، چیرې چې بریښنا خورا ارزښتناکه وي.';
$ec_lang['mhp_notes_4_term']='ځایی ضیاعات، k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='دا ضیاعات د پایپ نقطو (جنکشنونو)، ننوتنځیو، ګوډونو، او والوونو کې رامنځته کیږي — اصطلاح "کوچني" دودیزه ده خو ګمراه کوونکې، ځکه چې په لنډه فشار لوله کې دا ضیاعات ممکن د اصطکاک ضیاعاتو سره مساوي یا لا زیات هم شي. د k عمومي ارزښتونه: تیزه ننوتنځی دروازه 0.5، هر 45° ګوډ 0.2–0.3، د دروازې والو (بشپړ خلاص) 0.1، پروانه‌یی والو 0.2. ټول فیټینګونه سره جمع کړئ ترڅو ټول k<sub>m</sub> ترلاسه شي. تلواله (ډیفالټ) ارزښت 1.5 یوه ننوتنځی او دوه ګوډونه ګڼي.';
$ec_lang['mhp_notes_5_term']='د پایپ خشونت e';
$ec_lang['mhp_notes_5_def']='عادي مطلق خشونت: فولاد (نوی) 0.046 mm، فولاد (کارول شوی) 0.15 mm، HDPE 0.003 mm، PVC/uPVC 0.0015 mm، کانکریټ 0.3–3 mm. HDPE د کوچنیو مایکرو هایدرو فشار لولو لپاره عام دی.';
$ec_lang['mhp_notes_6_term']='موثریت';
$ec_lang['mhp_notes_6_def']='د مایکرو هایدرو کې عام د Pelton او کراس-فلو ټربینونو د پلانټ عادي موثریت η د 0.70 تر 0.85 پورې کیږي. د محافظه‌کارانه لومړني اټکل لپاره 0.75 وکاروئ.';
$ec_lang['mhp_notes_7_term']='کلنۍ انرژي';
$ec_lang['mhp_notes_7_def']='کلنۍ انرژي د دوامداره بشپړ بهاو فعالیت (۸۷۶۰ ساعته/کال) فرضوي. واقعي تولید به د موسمي بهاو بدلون، د ساتنې د ودریدو وخت، او د بار فاکتور له امله ټیټ وي.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='د سوري ایستلو وخت';
$ec_lang['odt_main_title']='وړیا آنلاین د سوري ایستلو وخت محاسبه — ډنډ، حوض، یا ټانک';
$ec_lang['odt_main_desc']='د ډنډ یا حوض د سوري ایستلو وخت — د کونیکي حجم میتود';
$ec_lang['odt_h1_elev']='پیلیزه د اوبو د سطحې کچه';
$ec_lang['odt_a1']='پیلیز مساحت، A<sub>1</sub>';
$ec_lang['odt_h2_elev']='پایلیزه د اوبو د سطحې کچه';
$ec_lang['odt_h_orifice']='د سوري د مرکز لوړوالی';
$ec_lang['odt_a0']='د سوري د کچې مساحت، A<sub>0</sub>';
$ec_lang['odt_a_ending']='پایلیز مساحت، A<sub>2</sub> <span title="د پای کچې لپاره د کونیکي ماډل څخه تخمین شوی" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='د پایلیز کچې چک';
$ec_lang['odt_h2_ok']='پایلیزه کچه د سوري تاج نه پورته';
$ec_lang['odt_h2_warn']='پایلیزه کچه د سوري تاج ته یا لاندې';
$ec_lang['odt_h2_warn_tip']='د سوري تاج = مرکز + D/2';
$ec_lang['odt_d']='د سوري D <span title="قطر (دایروي) یا لوړوالی (مستطیلي)" class="ec-tip">?</span>';
$ec_lang['odt_w']='د سوري پلنوالی، W <span title="یوازې مستطیلي" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='ایستلو وخت (s)';
$ec_lang['odt_t_min']='ایستلو وخت (min)';
$ec_lang['odt_t_hr']='ایستلو وخت (hr)';
$ec_lang['odt_t_day']='ایستلو وخت (ورځې)';
$ec_lang['odt_notes_1_term']='فارمول';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) د سر H څخه تر سوري پورې د ایستلو وخت ورکوي. ایستلو وخت = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، چیرې چې H<sub>1</sub> = پیلیزه کچه − د سوري کچه، H<sub>2</sub> = پایلیزه کچه − د سوري کچه.';
$ec_lang['odt_notes_2_term']='میتود';
$ec_lang['odt_notes_2_def']='د کونیکي حجم میتود ډنډ یا حوض د پیل مساحت A<sub>1</sub> (په لومړني د اوبو سطحه کې) او د سوري د مرکز کچې مساحت A<sub>0</sub> ترمنځ د یوې کونیکي برخې په توګه ماډلوي. A<sub>2</sub>، چې د پای کچې کې د ډنډ مساحت دی، د کونیکي برخې ماډل په کارولو سره د A<sub>1</sub> او A<sub>0</sub> له مخې تخمین کیږي. د پیل نه تر پای کچې پورې د ایستلو وخت د H<sub>1</sub> نه تر سوري پورې د ټول ایستلو وخت منفي د H<sub>2</sub> نه پاتې د ایستلو وخت سره مساوي دی.';
$ec_lang['odt_h1']='پیلیز سر، H<sub>1</sub> <span title="پیلیزه د اوبو د سطحې کچه منفي د سوري د مرکز کچه" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='اعظمي بهاو، Q<sub>max</sub>';
$ec_lang['odt_vol']='ایستل شوی حجم';
$ec_lang['odt_sketch_start']='پیل';
$ec_lang['odt_sketch_end']='پای';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='اوبه لګول';
$ec_lang['irr_main_title']='وړیا آنلاین د اوبولګولو بهاو اندازه کولو کالکولېټرونه';
$ec_lang['irr_main_desc']='د اوبولګولو بهاو اندازه کول — ویرونه او منفذونه';
$ec_lang['irr_intro_html']='<p>ویرونه او منفذونه د اوبولګولو سیستمونو کې د اوبو بهاو اندازه کولو لپاره معیاري میداني وسیلې دي. هغه کالکولېټر غوره کړئ چې ستاسو جوړښت سره سمون خوري:</p>';
$ec_lang['irr_card_weir_uniform_head']='ویر — پراخه-سره (یو شان پلنوالی)';
$ec_lang['irr_card_weir_uniform_desc']='د یو انحرافي بند سر، د کنترول جوړښت، یا د ویر تختې پر سر بهاو اندازه کړئ. د ویر اوږدوالی او د سر پورته د پورتنیو اوبو ژوروالی ولیکئ.';
$ec_lang['irr_card_weir_irregular_head']='ویر — غیرمنظم پروفایل';
$ec_lang['irr_card_weir_irregular_desc']='کله یې وکاروئ چې د ویر سر د لوړوالي یا پروفایل له مخې توپیر ولري — طبیعي سپیل‌ویز، د بدلېدونکي پلنوالي سره د راچاڼون جوړښتونه، یا څو-برخو کنترول جوړښتونه.';
$ec_lang['irr_card_orifice_head']='منفذ — سردروازه یا پایپ ایستنځی';
$ec_lang['irr_card_orifice_desc']='د سلوس دروازې، پایپ ایستنځي، یا کلورت خلاصوالي له لارې بهاو اندازه کړئ. دواړه آزاد وتون او ډوب شوي (ښکتنۍ اوبو) شرایط په اتومات ډول اداره کوي.';
$ec_lang['irr_card_canal_head']='د کانال ډیزاین &amp; تحلیل';
$ec_lang['irr_card_canal_desc']='د Manning فورمول په مرسته د اوبولګولو کانال ډیزاین یا وګورئ. د نویو نهرونو لپاره د ترپیزویډ کالکولېټر وکاروئ؛ د موجودو طبیعي یا جوړ شوو برخو لپاره غیرمنظم کالکولېټر.';
$ec_lang['irr_card_pressure_head']='د اوبو د لګولو فشار &amp; یو‌شانتیا';
$ec_lang['irr_card_pressure_desc']='د اصلي نل-جانبي نل-وریز یوې څانګې پر اوږدو فشار او بهاو پروفایل نمونه کړئ ترڅو د حقیقي ازموینې-لار فشار له مخې د ویش یو‌شانتیا اټکل کړئ، نه یوازې د کتالوګ وریز بهاو کچه.';
$ec_lang['irr_card_seepage_head']='د کانال چوړ &amp; د لیږدولو اغیزمنتیا';
$ec_lang['irr_card_seepage_desc']='د ننوت او وتون اندازو په کارولو سره د یوې کانال برخې څخه د چوړ ضیاع اټکل کړئ. د لیږدولو اغیزمنتیا او کلنی اوبو ضیاع محاسبه کړئ ترڅو د کښلو پانګونې ته لومړیتوب ورکولو کې مرسته وشي.';
$ec_lang['irr_quickref_html']='<h3>ګړندۍ لارښوونه</h3><dl><dt>انحرافي بند یا کنترول جوړښت</dt><dd>د ویر سر پورته د پورتنیو اوبو ژوروالی اندازه کړئ. د یو شان سر لپاره <a href="Weir-Flow-Simple.php">ساده ویر بهاو</a>، یا د پروفایل شوي یا زینه‌یز سر لپاره <a href="Weir-Flow-Irregular.php">غیرمنظم ویر بهاو</a> وکاروئ.</dd><dt>سردروازه یا پایپ ایستنځی</dt><dd>د پورتنیو اوبو لوړوالی او د ښکتنیو اوبو لوړوالی اندازه کړئ (یا که آزاده تخلیه کیږي نو د پایپ بېخ). <a href="Orifice.php">منفذ بهاو</a> وکاروئ. د دایروي پایپ لپاره D&nbsp;= د پایپ قطر؛ د مستطیل دروازې لپاره پلنوالی W او لوړوالی D ولیکئ.</dd><dt>د ذخیرې یا حوض د خالي کیدو وخت</dt><dd>د یو تالاب یا ذخیرې د سطحې د ښکته کولو لپاره د بېخ منفذ له لارې د اړین وخت اټکل لپاره <a href="Orifice-Drain-Time.php">منفذ نکاسي وخت</a> وکاروئ &mdash; د اوبولګولو ذخیرې پلان جوړولو لپاره ګټور.</dd><dt>د ساحې معیارونه</dt><dd>دلته کارول شوي د ویر او منفذ بهاو معادلې د USBR <em>Water Measurement Manual</em> (درېیم&nbsp;چاپ) طرزالعملونو سره سمون خوري چې معمولاً د اوبو مسؤلینو او اوبولګولو ولسوالیو لخوا اړین ګڼل کیږي.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='د وریزونو واټن، S<sub>e</sub>';
$ec_lang['ip_sl']='د جانبي نلونو واټن، S<sub>l</sub>';
$ec_lang['ip_n_e']='د یو جانبي نل لپاره وریزونه، n<sub>e</sub>';
$ec_lang['ip_n_l']='د یو زون لپاره جانبي نلونه، n<sub>l</sub>';
$ec_lang['ip_d']='د موخې د اوبو د لګولو ژوروالی، d';
$ec_lang['ip_a_e']='د هر وریز لپاره مساحت، A<sub>e</sub>';
$ec_lang['ip_pr']='د اوبو کارولو کچه، PR';
$ec_lang['ip_q_lat']='د یو جانبي نل بهاو، Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='د زون بهاو، Q<sub>zone</sub>';
$ec_lang['ip_t_run']='د چلولو وخت (ساعتونه)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='د کانال چوړ';
$ec_lang['cs_main_title']='وړیا آنلاین د کانال چوړ ضیاع او د لیږدولو اغیزمنتیا کالکولېټر';
$ec_lang['cs_main_desc']='د کانال د چوړ ضیاع &amp; د لیږدولو اغیزمنتیا &mdash; د ننوت-وتلو میتود';
$ec_lang['cs_Q_in']='ننوتلو بهاو، Q<sub>in</sub>';
$ec_lang['cs_Q_out']='وتلو بهاو، Q<sub>out</sub>';
$ec_lang['cs_L']='د برخې اوږدوالی، L';
$ec_lang['cs_wp']='د لندوالي محیط، P<sub>w</sub>';
$ec_lang['cs_Q_loss']='د چوړ ضیاع کچه، Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='د اندازه کولو کتنه';
$ec_lang['cs_pct_loss']='ضایع شوی کسر';
$ec_lang['cs_Ec']='د لیږدولو اغیزمنتیا، E<sub>c</sub>';
$ec_lang['cs_Ec_check']='د اغیزمنتیا درجه‌بندي';
$ec_lang['cs_Vol_day']='ورځنی ضایع شوی حجم';
$ec_lang['cs_Vol_year']='کلنی ضایع شوی حجم';
$ec_lang['cs_Q_loss_per_L']='د واحد اوږدوالي لپاره ضیاع، Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='د اوبو ارزښت';
$ec_lang['cs_lining_cost']='د کښلو لګښت';
$ec_lang['cs_Ec_target']='د کښلو موخه، E<sub>c,target</sub> <span title="د کښلو وروسته د لیږدولو اغیزمنتیا موخه؛ کسر 0&ndash;1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='د کښلو مساحت، L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='کلنی ضایع شوی ارزښت';
$ec_lang['cs_annual_value_recovered']='کلنی بیرته لاسته راغلی ارزښت';
$ec_lang['cs_lining_total_cost']='د کښلو ټول لګښت';
$ec_lang['cs_payback_years']='د بیرته-راکړنې موده <span title="ساده بیرته-راکړنه = د کښلو ټول لګښت &divide; کلنی بیرته لاسته راغلی ارزښت" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — چوړ وموندل شو';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — د اندازه کیدو وړ ضیاع نشته';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — اندازه کول وګورئ';
$ec_lang['cs_Ec_good']='ښه — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='منځنی — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='ضعیف — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_term']='میتود';
$ec_lang['cs_notes_1_def']='د ننوت-وتلو میتود د کانال د یوې برخې په سر او لمن کې د بهاو اندازه کولو له لارې چوړ اټکل کوي: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. د لیږدولو اغیزمنتیا E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. کلنی حجم د دوامداره بشپړ-بهاو چلند فرض کوي؛ د موسمي یا نیمه-بهاو کانالونو لپاره واقعي ضیاع لږ وي.';
$ec_lang['cs_notes_2_term']='د اغیزمنتیا درجه‌بندۍ';
$ec_lang['cs_notes_2_def']='معمولي بې کښلو خاورین کانالونه: E<sub>c</sub> = 60&ndash;80%. ښه ساتل شوي خاورین کانالونه: 75&ndash;85%. کانکریټ کښلي کانالونه: 90&ndash;98%. کله چې د چوړ ضیاع د ننوت له 30% څخه زیاته وي، معمولاً د کښلو پانګونه ورته اړوند وي. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='د کښلو بیرته-راکړنه';
$ec_lang['cs_notes_3_def']='د اوبو ارزښت او د کښلو لګښت په هر همغږي پیسو کې ولیکئ. د کښلو مساحت = د برخې اوږدوالی &times; لندې محیط &mdash; د اندازه شوي بهاو ژوروالي کچه د کانال د مقطع لندې محیط (لاندیني پلنوالی زیات دواړه لندي شیبونه). کلنی بیرته لاسته راغلی ارزښت فرض کوي چې کښل شوی کانال په دوامداره توګه موخه E<sub>c</sub> ته رسیږي. که کانالونه موسمي وي یا کښلول موخه اغیزمنتیا ته ونه رسیږي، واقعي بیرته-راکړنه به اوږده وي.';
$ec_lang['cs_notes_4_term']='سرچینه';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>، درېیم چاپ (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='د اړه';
$ec_lang['install_main_menu']='نصب';
$ec_lang['install_main_title']='د EngCalcs نصبول';
$ec_lang['install_main_desc']='آفلاین کارولو لپاره خپل وسیلې ته اضافه کړئ';
$ec_lang['contact_main_menu']='اړیکه';
$ec_lang['about_main_title']='د HawsEDC انجینري کالکولیټرونو د اړه';
$ec_lang['about_main_desc']='دنده، خلاص سرچینه، او همکاري';
$ec_lang['about_body_html']='<h3>مأموریت</h3><p>د HawsEDC انجینیري کلکولیټرونه د ټول نړۍ انجینیرانو او میدانی کارکونو خدمت لپاره شتون لري — خاصه هغه کسان چې د اوبو نشتوالي، محدودو سرچینو، یا کم خدماتو سیمو کې کار کوي. دا وسیلې د یو پراخ بشردوستانه مأموریت برخه دي: هر انسان ته د ترټولو عملي او مؤثره لارې سره ووایي چې هغه تل د مینې او عزت وړ دی، چې هغه له هیڅ شي نه وېریږي، او دا چې هغه به هر څه تباه نه کړي.</p><p>کلکولیټرونه وسیله ده. منزل د سختیو پرته نړۍ ده.</p><h3>د خلاص سرچینې جواز</h3><p>ټول کوډ د <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 یا وروستي نسخه</a> لاندې خپور شوی — د آزادۍ په مانا خلاص. تاسو کولی شئ کوډ د ورته شرایطو لاندې وکاروئ، مطالعه یې کړئ، بدلون یې راوړئ، او بیا خپور یې کړئ.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>د سرچینې کوډ</h3><p>د سرچینې بشپړ کوډ د Bitbucket پر عامه توګه شتون لري:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>تاسو هلته کوډ کتلی شئ، ستونزې ثبتولی شئ، یا ریپوزیټوري فورک کولی شئ.</p><h3>همکاري</h3><p>د Pull Requests ښه راغلاست دی. د همکارۍ لارې:</p><ul><li><strong>ژباړه</strong> — یوه ژبه ښه کړئ یا نوې اضافه کړئ. د اړونده <code>lib/lang.ec.??.php</code> فایل کې د بدلونونو سره Pull Request پرانیزئ.</li><li><strong>د بګ راپور</strong> — د کوم کلکولیټر پاڼه کې د فیډبیک فارم وکاروئ، یا Bitbucket کې ستونزه ثبت کړئ.</li><li><strong>نوي کلکولیټرونه</strong> — د هایدرولیک انجینیري وسیلو لپاره نظریات چې میدانی کارکونو او اوبلو مسلکیانو ته خدمت کوي، خاصه ښه راغلاست دي. د ریپوزیټوري کې د پراختیاکار لارښود <code>CLAUDE.md</code> وګورئ.</li><li><strong>هوسټینګ</strong> — که تاسو کولی شئ دا کلکولیټرونه د محدود اتصال سیمې لپاره انعکاس کړئ، مهرباني وکړئ اړیکه ونیسئ.</li></ul><h3>آفلاین کارول</h3><p>دا حسابونه د پرمختللي ویب اپلیکیشن (PWA) په توګه کار کوي. کله چې له انټرنیټ سره وصل یاست، د هر حسابونو پاڼه وګورئ، او ستاسو براوزر به ټول حسابونه په اوتومات ډول ذخیره کړي. له هغې وروسته، ټول حسابونه بې له انټرنیټه کار کوي — انټرنیټ ته اړتیا نشته.</p><p>په Android یا iOS کې، د EngCalcs د خپل وسیله کې د اپلیکیشن په توګه د نصب کولو لپاره د خپل براوزر "کور سکرین ته اضافه کړئ" اختیار وکاروئ. په ډیسکټاپ کې، د خپل براوزر د پتې بار کې د نصب آیکون وګورئ.</p><p>تاسو کولی شئ هر یو حساب د خپل براوزر د "د نوم سره خوندي کړئ…" مینو له لارې یو ځل آفلاین کارولو لپاره خوندي کړئ.</p><h3>اړیکه</h3><p>Tom Haws — هایدرولیک انجینیر او د دغو کلکولیټرونو لیکوال.<br />د کوم کلکولیټر پاڼه کې د فیډبیک فارم وکاروئ، یا <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> کې سرچینې کوډ ته لاسرسی ومومئ.</p>';
$ec_lang['contact_title']='HawsEDC اړیکه';
$ec_lang['contactSendMessage']='Tom Haws ته پیغام ولیږئ';
$ec_lang['contactYourName']='ستاسو نوم:';
$ec_lang['contactYourEmail']='ستاسو بریښنالیک پته:';
$ec_lang['contactSubject']='موضوع:';
$ec_lang['contact_message']='پیغام:';
$ec_lang['contactSpamPrefix']='پنځه زیات یو مساوي دي';
$ec_lang['contactSpamPostfix']='(مهرباني وکړئ هغه ولیکئ. 1=یو 2=دوه 3=درې 4=څلور 5=پنځه 6=شپږ 7=اوه +=زیات 5+1=6)';
$ec_lang['contactSubmitButton']='پیغام ولیږئ';
$ec_lang['contact_success']='تاسو د لیکلو لپاره وخت کاروت د هغې لپاره تشکر.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='د کاڼو تند اوبو لار ډیزاین (Robinson)';
$ec_lang['rc_main_title']='وړیا آنلاین د کاڼو تند اوبو لار ډیزاین کلکولیټر &mdash; Robinson (1998)';
$ec_lang['rc_main_desc']='د کاڼو تند اوبو لار د کاڼو اندازې ټاکل &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='د چوټ د بیخ شیب، S<sub>0</sub>';
$ec_lang['rc_qt']='ټول واحد بهاو، q<sub>t</sub> <span title="د کاڼو تند اوبو لار ننوتنځي کې د هر واحد پلنوالي لپاره بهاو. د B ښکتنی پلنوالی لرونکي کانال لپاره چې Q ټول بهاو لري، q_t = Q / B وکاروئ." class="ec-tip">?</span>';
$ec_lang['rc_np']='د کاڼو سوري والتیا، n<sub>p</sub>';
$ec_lang['rc_sg']='د کاڼو ځانګړی ثقل، sg <span title="د عادي مات شوي ګرانائټ یا بازالټ ≈ 2.65. د Robinson سمه لړۍ: 2.54 تر 2.82." class="ec-tip">?</span>';
$ec_lang['rc_SD']='درجه‌بندي SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="د درجه‌بندۍ معیاري انحراف. یو‌شان کاڼي ≈ 1.25. د Robinson سمه لړۍ: 1.15 تر 1.47." class="ec-tip">?</span>';
$ec_lang['rc_yn']='د ننوتنځي کانال کې نورمال ژوروالی، y<sub>n</sub> <span title="د اوبو راټولېدل (Hp &gt; yn) ښه دي — پورتنی فرسایش کموي. (USDA)" class="ec-tip">?</span>';
$ec_lang['rc_D50']='اړینه منځنۍ د کاڼو اندازه، D<sub>50</sub> <span title="معادله 1 (S0 &lt; 0.10) یا معادله 2 (0.10-0.40). سمه لړۍ: D50 15-278 mm، S0 0.02-0.40. د لړۍ نه بهر: اټکل شوي ارزښتونه." class="ec-tip">?</span>';
$ec_lang['rc_eq_used']='کارول شوې معادله';
$ec_lang['rc_sg_check']='د ځانګړي ثقل کتنه';
$ec_lang['rc_SD_check']='د درجه‌بندۍ SD کتنه';
$ec_lang['rc_sg_ok']='sg په سمه لړۍ کې دی (2.54–2.82)';
$ec_lang['rc_sg_ok_tip']='2.54–2.82 (Robinson)';
$ec_lang['rc_sg_low']='sg د Robinson لړۍ نه لاندې دی';
$ec_lang['rc_sg_low_tip']='سمه لړۍ: 2.54–2.82';
$ec_lang['rc_sg_high']='sg د Robinson لړۍ نه پورته دی';
$ec_lang['rc_sg_high_tip']='سمه لړۍ: 2.54–2.82';
$ec_lang['rc_SD_ok']='SD په سمه لړۍ کې دی (1.15–1.47)';
$ec_lang['rc_SD_ok_tip']='1.15–1.47 (Robinson)';
$ec_lang['rc_SD_low']='SD د Robinson لړۍ نه لاندې دی';
$ec_lang['rc_SD_low_tip']='سمه لړۍ: 1.15–1.47';
$ec_lang['rc_SD_high']='SD د Robinson لړۍ نه پورته دی';
$ec_lang['rc_SD_high_tip']='سمه لړۍ: 1.15–1.47';
$ec_lang['rc_layer']='د کاڼو پرت ضخامت (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='د پورتني کرسټ منحني شعاع (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='د پورتني کرسټ منحني د قوس اوږدوالی';
$ec_lang['rc_apron_length']='د وتنځي اپرون اوږدوالی (15 &times; D<sub>50</sub>) <span title="د چوټ کاڼو جوړښتي ملاتړ لپاره اړین دی. &quot;هغه لږترلږه لاندنۍ اوبه چې د وتنځي برخې او ښکته‌اړخ کانال مقاومت له امله رامنځته کیږي، د وتنځي برخې کې د کاڼو ثبات ډاډمنولو لپاره کافي ده.&quot; (Robinson)" class="ec-tip">?</span>';
$ec_lang['rc_n_chute']='په چوټ کې د Manning خشونت، n';
$ec_lang['rc_Vm']='د کاڼو د پوښ (مینټل) له لارې سرعت، V<sub>m</sub> <span title="د qt هغه برخه چې د کاڼو سوریو له لارې تیریږي. پاتې برخه qs د سطحې پر مخ بهیږي. تلواله (ډیفالټ) np = 0.45 د زاویه‌لرونکو مات شویو کاڼو لپاره ده." class="ec-tip">?</span>';
$ec_lang['rc_qm']='د پوښ (مینټل) له لارې واحد بهاو، q<sub>m</sub>';
$ec_lang['rc_qs']='د سطحې واحد بهاو، q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='د کاڼو سطحې پورته د بهاو ژوروالی، d';
$ec_lang['rc_Hp']='د ننوتنځي د ویر سر، H<sub>p</sub> <span title="د اوبو راټولېدل (Hp &gt; yn) ښه دي — پورتنی فرسایش کموي. (USDA)" class="ec-tip">?</span>';
$ec_lang['rc_ponding_check']='د ننوتنځي د اوبو راټولیدو کتنه';
$ec_lang['rc_pond_ok']='H<sub>p</sub> &gt; y<sub>n</sub> — پورته اوبه راټولېږي';
$ec_lang['rc_pond_ok_tip']='د چوټ ننوتنځي نه پورته د اوبو راټولېدل ښه دي؛ دا پورتنی فرسایش کموي. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — اوبه نه راټولېږي — د ننوتنځي د فرسایش امکان شته';
$ec_lang['rc_pond_warn_tip']='د چوټ ننوتنځي نه پورته اوبه نه راټولېږي؛ ممکن پورته فرسایش رامنځته شي. (USDA)';
$ec_lang['rc_eq1']='معادله 1 (S<sub>0</sub> &lt; 0.10) — لږ شیب';
$ec_lang['rc_eq2']='معادله 2 (0.10 ≤ S<sub>0</sub> ≤ 0.40) — تند شیب';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> &lt; 0.02 — د Robinson د تایید لړۍ نه لاندې دی';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> &gt; 0.40 — د Robinson د تایید لړۍ نه پورته دی';
$ec_lang['rc_notes_1_term']='د کاڼو اندازې ټاکلو معادلې';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) د چوټ شیب او د واحد بهاو پر بنسټ د کاڼو منځنۍ اندازې D<sub>50</sub> لپاره دوه تجربي معادلې جوړې کړې. معادله 1 د لږو شیبونو لپاره کارول کیږي (S<sub>0</sub> &lt; 0.10)؛ معادله 2 د تندو شیبونو لپاره کارول کیږي (0.10 ≤ S<sub>0</sub> ≤ 0.40). دواړه معادلې q<sub>t</sub> په م&sup2;/ثانیه کې غواړي او D<sub>50</sub> په ملی‌متر کې ورکوي. تاییدشوې لړۍ 0.02 ≤ S<sub>0</sub> ≤ 0.40 ده.';
$ec_lang['rc_notes_2_term']='واحد بهاو';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> د چوټ د سر (کرسټ) کې ټول واحد بهاو دی (د هر واحد پلنوالي لپاره ټول بهاو). د B ښکتنی پلنوالی لرونکي کانال لپاره چې Q ټول بهاو لري، q<sub>t</sub> ≈ Q / B اټکل کړئ، یا یې د چوټ ننوتنځي کې د بحراني ژوروالي شرط له مخې حساب کړئ.';
$ec_lang['rc_notes_3_term']='د کاڼو پوښ (مینټل) له لارې بهاو';
$ec_lang['rc_notes_3_def']='د ټول بهاو یوه برخه د کاڼو سوریو له لارې تیریږي (د پوښ بهاو q<sub>m</sub>)؛ پاتې برخه د کاڼو سطحې پر مخ بهیږي (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). د بهاو ژوروالی d د Manning معادلې له مخې حساب کیږي چې د سطحې بهاو q<sub>s</sub> ته د چوټ خشونت n په کارولو سره پلي کیږي. تلواله (ډیفالټ) سوري والتیا n<sub>p</sub> = 0.45 د زاویه‌لرونکو مات‌شویو کاڼو لپاره عادي ده.';
$ec_lang['rc_notes_5_term']='د کاڼو اندازې سمه لړۍ';
$ec_lang['rc_notes_5_def']='معادلې د D<sub>50</sub> د 15&nbsp;mm تر 278&nbsp;mm لړۍ په کارولو سره جوړې شوې دي. د دې لړۍ نه بهر پایلې اټکل شوي دي او باید د اضافي انجینیري قضاوت سره وکارول شي.';
$ec_lang['rc_notes_6_term']='د وتنځي اپرون لوړوالی';
$ec_lang['rc_notes_6_def']='د وتنځي برخې کې د کاڼو د پاسنۍ سطحې لوړوالی باید د ښکته‌اړخ کانال د تله لوړوالي په کچه یا ترې لاندې وي. که چیرې لوړ وي، د وتنځي کاڼي به بې‌ثباته وي.';
$ec_lang['rc_notes_7_def']='کله چې د ننوتنځي کانال کې نورمال ژوروالی د هغه ویر سر (H<sub>p</sub>) نه کم وي چې د q<sub>t</sub> تیرولو لپاره اړین دی، نو د چوټ ننوتنځي نه پورته محدود بهاو یا د اوبو راټولیدل رامنځته کیږي. دا په عمومي ډول د منلو وړ دي — د اوبو راټولیدل سرعت کموي او پورته فرسایش مخنیوی کوي. د کتنې لپاره: د ورکړل شوي q<sub>t</sub> او د سر پلنوالي لپاره H<sub>p</sub> موندلو ته د ویر بهاو محاسبګر وکاروئ، او دا د ننوتنځي کانال نورمال ژوروالي سره پرتله کړئ. که H<sub>p</sub> د نورمال ژوروالي نه ډیر شي، اوبه به راټولېږي.';
$ec_lang['rc_notes_4_term']='سرچینه';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. USDA ARS د ورته میتود پر بنسټ یو <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel سپریډشیټ</a> هم خپروي.';
// Sketch labels
$ec_lang['rc_sketch_filter']='فلتر';
$ec_lang['rc_sketch_top_crest_curve']='د پورتني کرسټ منحني';
$ec_lang['rc_sketch_outlet_apron']='د وتنځي اپرون';
$ec_lang['rc_sketch_radius']='شعاع';
// Irrigation Pressure. Prefix ip_.
$ec_lang['ip_main_menu']='د اوبو د لګولو فشار';
$ec_lang['ip_main_title']='وړیا آنلاین د اوبو د لګولو فشار &amp; د ویش یو‌شانتیا کالکولېټر';
$ec_lang['ip_main_desc']='د ازموینې څانګې فشار او یو‌شانتیا اټکل';
$ec_lang['ip_h_supply']='د تامین فشار';
$ec_lang['ip_elev_supply']='د تامین لوړوالی، z<sub>supply</sub>';
$ec_lang['ip_q_design']='د وریز ډیزاین بهاو، q<sub>design</sub>';
$ec_lang['ip_h_design']='د وریز ډیزاین فشار';
$ec_lang['ip_x']='د وریز خارجېدنې اکسپوننټ، x <span title="د معیاري غیر-جبرانوونکو وریزونو لپاره 0.5؛ د فشار-جبرانوونکو وریزونو لپاره نږدې 0" class="ec-tip">?</span>';
$ec_lang['ip_reach_table_title']='د ازموینې لار';
$ec_lang['ip_group_reach']='برخه';
$ec_lang['ip_group_upstream']='پورتنۍ خوا';
$ec_lang['ip_group_downstream']='ښکتنۍ خوا';
$ec_lang['ip_group_loss']='ضیاع';
$ec_lang['ip_is_lateral']='جانبي <span title="نښه شوی: دا برخه د ازموینې جانبي نل یوه برخه ده، چې تر څنګ یې انفرادي وریزونه اوبه اخلي. بې نښې: دا برخه اصلي نل دی، یوازې بهاو هغو جانبي نلونو ته رسوي چې د ازموینې لار برخه نه دي." class="ec-tip">?</span>';
$ec_lang['ip_count']='وریزونه <span title="د جانبي نل کرښې: یوازې په دې برخه کې وریزونه. د اصلي نل کرښې: پر هغو جانبي نلونو ټول وریزونه چې د دې برخې غیر له نورو څخه شاخه کیږي. د اصلي نل هغه برخې لپاره چې د ازموینې جانبي نل ته رسیږي، دا هم په اصلي نل کې تر دې ځای وروسته پاتې هر جانبي نل، یا په ورته جنکشن کې شریک (لکه مخالف اړخ جانبي نل) شاملوي &mdash; د دوی بهاو هم له همدې برخې څخه شاخه کیږي." class="ec-tip">?</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_km']='k<sub>m</sub> <span title="د دې برخې د فیټنګونو/والوونو/نښلوونکو لپاره عمومي ځایي-ضیاع ضریب (&ge;0.5 وړاندیز شوی کمترین)" class="ec-tip">?</span>';
$ec_lang['ip_elev_ds']='ښکتنی لوړوالی <span title="د دې برخې د ښکتني پای لوړوالی. د منځني کرښو لپاره اختیاري دی (که خالي پریښودل شي، هوار / د پورتني نوډ سره یو شان ګڼل کیږي). د وروستۍ کرښې لپاره لازمي دی: هغه ارزښت د آخري وریز لوړوالی دی، کوم چې مستقیماً اړین تامین فشار ټاکي." class="ec-tip">?</span>';
$ec_lang['ip_elev_ds_missing_warn']='د آخري وریز لوړوالی (وروستۍ کرښه) خالي پاتې شو او هوار ګڼل شو &mdash; د دقیقې پایلې لپاره یې ولیکئ';
$ec_lang['ip_flow']='بهاو';
$ec_lang['ip_press']='فشار';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='h<sub>L</sub> <span title="د برخې ټوله ضیاع، h_f + h_m" class="ec-tip">?</span>';
$ec_lang['ip_pressure_warn']='ټیټ/منفي فشار &mdash; د فضا لاندې شرایطو لپاره وګورئ';
$ec_lang['ip_pressure_warn_short']='ټیټ';
$ec_lang['ip_h_far']='د آخري وریز فشار';
$ec_lang['ip_q_supply']='د ازموینې لار تامین بهاو، Q<sub>supply</sub> <span title="یوازې هغه بهاو چې نمونه شوې ازموینې لار ته ننوځي — د بشپړ زون/سیستم لپاره لاندې د کارونې ډیزاین کې Q_zone وګورئ." class="ec-tip">?</span>';
$ec_lang['ip_q_critical']='د آخري وریز بهاو، q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='د وریز اوسط بهاو (ازموینې جانبي نل)، q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='اټکل شوی &Delta;فشار، اوسط د ازموینې جانبي نل په پرتله <span title="تاسو اټکل کوئ چې یو عادي جانبي نل د دې ازموینې جانبي نل په پرتله څومره لوړ (یا ټیټ) فشار لري. ازموینې جانبي نل په قصدي توګه د بدترین حالت په توګه ګڼل کیږي، نو د هغه خپل اوسط د ساحې اوسط لپاره ټیټ اټکل دی &mdash; که پر 0 پریښودل شي، لاندې د یو‌شانتیا کتنه او د کارونې-ډیزاین شمیرې د ازموینې جانبي نل خپل (ښایي زیات ښه‌بین) اوسط لکه څنګه چې دی کاروي." class="ec-tip">?</span>';
$ec_lang['ip_q_avg_field']='د ساحې اټکل شوی اوسط وریز بهاو، q<sub>avg,field</sub> <span title="q_avg_lateral د هرې جانبي نل کرښې فشار زیات د پورته لیکل شوي فشار توپیر سره بیا-ارزول شوی &mdash; دا هڅه ده چې د ازموینې جانبي نل د بدترین حالت ګڼلو لپاره سمون ورکړي، نه د یوه استازي کوونکي حالت لپاره. دا هم لاندې د یو‌شانتیا کتنه او د کارونې-ډیزاین برخه دواړو ته تغذیه کوي." class="ec-tip">?</span>';
$ec_lang['ip_du_estimate']='د یو‌شانتیا کتنه، q<sub>last</sub>/q<sub>avg,field</sub> <span title="د آخري وریز محاسبه شوی بهاو د ساحې اټکل شوي اوسط وریز بهاو باندې ویشل شوی &mdash; دا د معیاري ټیټه-ربعه د ویش یو‌شانتیا (ټیټه-ډلې اوسط &divide; د ټول ډلې منځنی) یو نږدې والی دی؛ دا د یوې کوچنۍ نمونه‌یي بڼې او د کارونکي اټکل شوي سمون له مخې دی، نه د بشپړې ساحې احصایوي نمونې. د 1 سره یا تر هغه پورته ارزښتونه ممکن او سم دي: دا یوازې دا معنا لري چې د آخري وریز فشار د اټکل شوي ساحوي اوسط سره برابر یا تر هغه پورته دی، نو کوم بل وریز د ټیټ فشار ځای دی. دا ممکن ځکه وي چې آخري وریز په ټیټه ځمکه کې دی یا ځکه چې د &Delta;فشار اټکل ډیر کوچنی دی." class="ec-tip">?</span>';
$ec_lang['ip_worst_case_warn']='د ازموینې وریز کې فشار &ge; د تامین فشار. دا ښایي بدترین حالت وریز نه وي، یا پایپونه کولی شي کوچني شي.';
$ec_lang['ip_q_ratio']='د آخري وریز بهاو &divide; ډیزاین بهاو، q<sub>last</sub>/q<sub>design</sub> <span title="دا زموږ د معیاري یو‌شانتیا اندازې نږدې والي څخه بېل دی." class="ec-tip">?</span>';
$ec_lang['ip_no_solution']='حل نشته: اړین تامین فشار د لیکل شوي تامین فشار څخه زیات دی. تامین فشار زیات کړئ، غوښتنه کمه کړئ، یا لوی پایپ وکاروئ.';
$ec_lang['ip_notes_1_term']='میتود';
$ec_lang['ip_notes_1_def']='د آخري (تر ټولو لرې) وریز کې فشار اټکلوي، بیا د انرژۍ کچې کرښه برخه‌پر-برخه تامین ته شاته وړي، په لاره کې د اصطکاک او ځایي ضیاعاتو زیاتولو سره. په هر نوډ کې لوړوالی او د سرعت لوړوالی کمول کیږي ترڅو هلته حقیقي فشار راپور شي. اټکل شوی لرې-پای فشار سمون کیږي (دوه‌ویشنې میتود) تر هغه چې محاسبه شوی اړین تامین فشار د لیکل شوي تامین فشار سره برابر شي &mdash; همغه تړلی-حلقې ستونزه چې د Manning پایپ بهاو کالکولېټر کې د پایپ-بهاو حلونکي لخوا حل کیږي، خو دلته یوې څانګه‌یزې شبکې ته پراخه شوې.';
$ec_lang['ip_notes_2_term']='اصلي نل پر وړاندې جانبي نل برخې';
$ec_lang['ip_notes_2_def']='هره کرښه د تامین څخه تر آخري وریز پورې د یوازینۍ هایدرولیکي بدترینې لارې (د ازموینې لار) پر اوږدو یوه برخه ده. د اصلي نل یوه برخه یوازې هغو جانبي نلونو ته بهاو رسوي چې د ازموینې لار برخه نه دي، نو د هغې اخیستنه یوه ساده ضرب ده (ډیزاین بهاو &times; د برخې ټول د وریزونو شمېر) &mdash; هیڅ ځایي فشار حساسیت نشته. اصلي نل یو شریک تنه پایپ دی، نو د اصلي نل هغه برخه چې تر ازموینې جانبي نل پورې رسیږي باید نه یوازې د خپلو دواړو انجامونو ترمنځ جانبي نلونه ولري، بلکې هغه جانبي نلونه هم چې اصلي نل کې تر دې ځای نه هاخوا دي، یا په ورته جنکشن کې شریک دي (لکه مخالف اړخ جانبي نل) &mdash; د دوی بهاو مخکې له بېلوالي له همدې برخې تیریږي، که دا جدول کې بل ځای هم راڅرګند شي یا نه. د جانبي نل برخه د ازموینې جانبي نل خپله یوه برخه ده: د وریز خارجېدنه د حقیقي ځایي فشار له مخې q = k&middot;H<sup>x</sup> په واسطه محاسبه کیږي، او د اصطکاک ضیاع د Christiansen د F(n) فکتور له مخې کمیږي ترڅو په برخه کې د هر وریز د اوبو اخیستلو سره د بهاو کمښت په پام کې ونیول شي.';
$ec_lang['ip_notes_3_term']='محدودیتونه';
$ec_lang['ip_notes_3_def']='یو ثابت تامین فشار (بې پمپ منحني)، یوازې یوه ازموینې لار (نه بشپړه ساحه)، او د 2-پارامیټره وریز منحني (د فشار-جبرانوونکي وریز نږدې کولو لپاره اکسپوننټ نږدې 0 ته ټاکئ) نمونه کوي. دوه بېلابېلې د یو‌شانتیا نسبتونه راپور کیږي، چې په قصدي توګه بېل ساتل شوي: q<sub>last</sub>/q<sub>avg,field</sub> د معیاري ټیټه-ربعه د ویش یو‌شانتیا (ټیټه-ډلې اوسط &divide; د ټول ډلې منځنی) یو نږدې والی دی؛ خو دا د یوې کوچنۍ نمونه‌یي بڼې او د کارونکي اټکل شوي سمون له مخې دی، نه د معیاري بشپړې ساحې احصایوي نمونې. همدارنګه، ازموینې جانبي نل په قصدي توګه د بدترین حالت په توګه ګڼل کیږي، نو د هغه خام، نه-سمون شوی اوسط به حقیقي ساحوي اوسط ټیټ وښیي او یو‌شانتیا به تر حقیقي څخه ښه ښکاره کړي؛ د &Delta;فشار ننوت په ځانګړي توګه د دې تعصب سره د مقابلې لپاره شتون لري. د 1 سره یا تر هغه پورته یو‌شانتیا ارزښتونه بیا هم ممکن دي: دا یوازې دا معنا لري چې د آخري وریز فشار د اټکل شوي ساحوي اوسط سره برابر یا تر هغه پورته دی، نو کوم بل وریز د ټیټ فشار ځای دی. دا ممکن ځکه وي چې آخري وریز په ټیټه ځمکه کې دی یا ځکه چې د &Delta;فشار اټکل ډیر کوچنی دی. q<sub>last</sub>/q<sub>design</sub> یوه بېله، غیر-یو‌شانتیا کتنه ده د تولیدوونکي درجه‌بندي شوي بهاو په وړاندې &mdash; د ټول سیستم ډیر- یا کم-فشار کتلو لپاره ګټوره، خو دا د یو‌شانتیا شمېرې سره یوځای لوستلو لپاره یوه بېله کتنه ده، ځکه چې ډیزاین/درجه‌بندي شوی بهاو د سیستم د حقیقي منځني چلونې فشار څخه خپلواک دی.';
$ec_lang['ip_notes_4_term']='حواله';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. د میکرو-اوبولګولو ډیزاین لپاره د ASAE/ASABE معیارونه ورته څو-خارجي اصطکاک-ضیاع طریقه کاروي.';
$ec_lang['ip_notes_5_term']='د کارونې ډیزاین';
$ec_lang['ip_notes_5_def']='د کارونې کچه او د سیستم/زون بهاو د ساحې اټکل شوي اوسط وریز بهاو (q<sub>avg,field</sub> &mdash; د ازموینې جانبي نل خپل اوسط، د لیکل شوي &Delta;فشار اټکل له مخې سم شوی) کاروي، نه یو اټکل شوی کچه: PR = q<sub>avg,field</sub> / A<sub>e</sub>، د سم شوي نمونه‌یي ارزښت لخوا تغذیه شوی. د واټن او د ټول سیستم جانبي/وریز شمېرونه دلته بېل ننوتونه دي ځکه چې د ازموینې لار یوازې یوه بدترینه-حالته څانګه نمونه کوي، نه د ساحې هر جانبي نل.';
