<?php

// हिन्दी — All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='भिन्न';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/से';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% चढ़ाव/दौड़';
$ec_lang['u_grade']='चढ़ाव/दौड़';
$ec_lang['u_in2']='वर्ग इंच';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='इंच';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='ली/से';
$ec_lang['u_m2']='मी^2';
$ec_lang['u_m3ps']='मी^3/से';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='मी जल';
$ec_lang['u_mld']='Ml/दिन';
$ec_lang['u_m']='मी';
$ec_lang['u_mm2']='मिमी^2';
$ec_lang['u_mmh2o']='मिमी जल';
$ec_lang['u_mm']='मिमी';
$ec_lang['u_mps']='मी/से';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='सेकंड';
$ec_lang['u_acft']='एकड़-फुट';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='मी^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC कैलकुलेटर';
$ec_lang['menu_main_list']='कैलकुलेटर सूची';
$ec_lang['menu_main_hydraulics']='जलगतिकी';
$ec_lang['menu_main_language']='भाषा';
$ec_lang['template_welcome']='&gt;&gt; दरवाज़े पर अपने डर छोड़ें; यहाँ प्यार की बात होती है। <a href="https://hawsedc.com/download.php">मुफ़्त HawsEDC AutoCAD टूल</a> भी आज़माएँ। &lt;&lt;';
$ec_lang['template_translation_help']='क्या आपके पास यहाँ जोड़ने के लिए किसी कैलकुलेटर का शानदार विचार है? क्या आप अनुवाद सुधारने, प्रोग्राम करने, या इन कैलकुलेटरों को होस्ट करने में मदद कर सकते हैं?  ';
$ec_lang['template_feedback']='कृपया अपने बहुमूल्य सुझाव या प्रशंसा दें। क्या इस मुफ़्त कैलकुलेटर ने हर तरह से आपकी उम्मीदों को पार किया?';
$ec_lang['template_printable_title']='प्रिंट करने योग्य शीर्षक';
$ec_lang['template_printable_subtitle']='प्रिंट करने योग्य उप-शीर्षक';
$ec_lang['index_title']='मुफ़्त ऑनलाइन इंजीनियरिंग कैलकुलेटर';
$ec_lang['calc_set_units']='इकाइयाँ निर्धारित करें:';
$ec_lang['points_data_help']='(या डेटा क्षेत्र से कॉपी/पेस्ट करें)';
$ec_lang['points_data_title']='बिंदु डेटा<br />(अल्पविराम या टैब से अलग)';
$ec_lang['points_data_copy']='कॉपी';
$ec_lang['points_data_paste']='पेस्ट';
$ec_lang['calc_inputs']='इनपुट';
$ec_lang['calc_results']='परिणाम';
$ec_lang['view_hide_line']='[यह पंक्ति छुपाएँ]';
$ec_lang['view_printable']='प्रिंट करने योग्य संस्करण (पुनर्स्थापित करने के लिए पुनः लोड करें)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='डार्सी-वाइसबाख पाइप शीर्ष हानि';
$ec_lang['dw_main_title']='मुफ़्त ऑनलाइन डार्सी-वाइसबाख पाइप शीर्ष हानि कैलकुलेटर';
$ec_lang['dw_main_desc']='दिए गए व्यास, खुरदरापन और प्रवाह पर डार्सी-वाइसबाख पाइप शीर्ष हानि';
$ec_lang['dw_roughness']='डार्सी-वाइसबाख निरपेक्ष खुरदरापन, e';
$ec_lang['dw_kinematic_viscosity']='गतिक श्यानता, v, मी<sup>2</sup>/से में (कमरे के तापमान पर स्वच्छ जल के लिए 1E-6)';
$ec_lang['dw_reynolds_number']='रेनॉल्ड्स संख्या, Re';
$ec_lang['dw_flow_regime']='प्रवाह व्यवस्था';
$ec_lang['dw_regime_laminar']='स्तरीय';
$ec_lang['dw_regime_transitional']='संक्रमणीय';
$ec_lang['dw_regime_turbulent']='अशांत';
$ec_lang['dw_friction_factor_method']='घर्षण गुणांक विधि';
$ec_lang['dw_friction_factor']='घर्षण गुणांक, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='हेज़न-विलियम्स पाइप शीर्ष हानि';
$ec_lang['hw_main_title']='मुफ़्त ऑनलाइन हेज़न-विलियम्स पाइप शीर्ष हानि कैलकुलेटर';
$ec_lang['hw_main_desc']='दिए गए व्यास, खुरदरापन और प्रवाह पर हेज़न-विलियम्स पाइप शीर्ष हानि';
$ec_lang['hw_hgl_1']='अनुप्रवाह HGL';
$ec_lang['hw_hgl_2']='उर्ध्वप्रवाह HGL';
$ec_lang['hw_roughness']='हेज़न-विलियम्स गुणांक, C';
// Manning Irregular
$ec_lang['mi_menu']='मैनिंग अनियमित नाली';
$ec_lang['mi_main_title']='मुफ़्त ऑनलाइन मैनिंग अनियमित नाली कैलकुलेटर';
$ec_lang['mi_main_desc']='अनियमित नाली मैनिंग एकसमान प्रवाह कैलकुलेटर';
$ec_lang['mi_waterSurfaceElevation']='जल सतह स्तर';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='अनुप्रस्थ काट बिंदु';
$ec_lang['mi_groupPoint']='बिंदु';
$ec_lang['mi_groupSegment']='खंड';
$ec_lang['mi_groupRegion']='क्षेत्र';
$ec_lang['mi_station']='स्टेशन';
$ec_lang['mi_elevation']='स्तर';
$ec_lang['mi_d50in']='अस्तर<br />मध्यक<br />चट्टान<br />आकार';
$ec_lang['mi_n']='n<br />खंड<br />के लिए';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />क्षेत्र<br />सीमा<br />(तट)';
$ec_lang['mi_tau']='तल<br />अपरूपण<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='मिश्रित<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='नोट';
$ec_lang['mi_notes_1_term']='मिश्रित n';
$ec_lang['mi_notes_1_def']='यह कैलकुलेटर Chow 1959, पृष्ठ 136, समीकरण 6-17 (6-18 नहीं) का उपयोग करके क्षेत्र मिश्रित n की गणना में HEC-RAS संदर्भ मैनुअल का अनुसरण करता है।';
$ec_lang['mi_notes_2_term']='चट्टान अस्तर';
$ec_lang['mi_notes_2_def']='चट्टान अस्तर डिज़ाइन करने के लिए मैनिंग समलम्बाकार नाली कैलकुलेटर का उपयोग करें। यह कैलकुलेटर प्राकृतिक अनुप्रस्थ काटों के लिए अधिक उपयुक्त है।';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='मैनिंग पाइप प्रवाह';
$ec_lang['mpf_main_title']='मुफ़्त ऑनलाइन मैनिंग पाइप प्रवाह कैलकुलेटर';
$ec_lang['mpf_main_desc']='दिए गए ढलान और गहराई पर मैनिंग सूत्र एकसमान पाइप प्रवाह';
$ec_lang['mpf_spreadheet_notice']='इस कैलकुलेटर का स्प्रेडशीट संस्करण देखें';
$ec_lang['mpf_pipe_diameter']='पाइप व्यास, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='मैनिंग खुरदरापन, n';
$ec_lang['mpf_friction_slope']='दाब ढलान (संभवतः <a target="_blank" href="../pressureslope.php">?</a> पाइप ढलान के बराबर), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='सापेक्ष प्रवाह गहराई, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(नोट देखें)';
$ec_lang['mpf_flow']='प्रवाह, Q';
$ec_lang['mpf_velocity']='वेग, v';
$ec_lang['mpf_velocity_head']='वेग शीर्ष, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='प्रवाह क्षेत्रफल, a';
$ec_lang['mpf_pipe_area']='पाइप क्षेत्रफल, a0';
$ec_lang['mpf_area_ratio']='सापेक्ष क्षेत्रफल, a/a0';
$ec_lang['mpf_wetted_perimeter']='भीगा परिधि, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='हाइड्रॉलिक त्रिज्या, R<sub>h</sub>';
$ec_lang['mpf_top_width']='शीर्ष चौड़ाई, T';
$ec_lang['mpf_froude_number']='फ्रूड संख्या, F';
$ec_lang['mpf_shear_stress']='औसत अपरूपण प्रतिबल (कर्षण बल), tau';
$ec_lang['mpf_full_flow']='पूर्ण प्रवाह, Q0';
$ec_lang['mpf_full_flow_ratio']='पूर्ण प्रवाह से अनुपात, Q/Q0';
$ec_lang['mpf_note_1']='<p>नोट:</p><dl><dt>यह एक <em>अनंत लंबे</em> पाइप के अंदर का प्रवाह और गहराई है।</dt><dd>पाइप में प्रवाह प्रवेश कराने के लिए काफी अधिक उर्ध्वप्रवाह गहराई की आवश्यकता हो सकती है। उर्ध्वप्रवाह गहराई पाने के लिए वेग शीर्ष का कम से कम 1.5 गुना जोड़ें या HY-8 का उपयोग करके मानक पाइपनाली शीर्ष जल गणना के लिए <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">मेरा 2-मिनट का ट्यूटोरियल</a> देखें।</dd>';
$ec_lang['mpf_solve_for_dd0']='दिए गए Q के लिए y/d<sub>0</sub> हल करें';
$ec_lang['mpf_solve_desc']='कैलकुलेटर फ़ॉर्म से D<sub>0</sub>, n और S<sub>0</sub> का उपयोग करके दिए गए Q के लिए न्यूनतम y/d<sub>0</sub> खोजता है।';
$ec_lang['mpf_solve_button']='हल करें';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='मैनिंग पाइप शीर्ष हानि';
$ec_lang['mphl_main_title']='मुफ़्त ऑनलाइन मैनिंग पाइप शीर्ष हानि कैलकुलेटर';
$ec_lang['mphl_main_desc']='दिए गए पूर्ण प्रवाह पर मैनिंग सूत्र शीर्ष हानि';
$ec_lang['mphl_pipe_length']='पाइप लंबाई, L';
$ec_lang['mphl_area']='क्षेत्रफल, A';
$ec_lang['mphl_total_junction_k']='कुल संयुक्त जंक्शन हानि गुणांक, k';
$ec_lang['mphl_friction_slope']='घर्षण ढलान';
$ec_lang['mphl_friction_loss']='घर्षण हानि, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='जंक्शन हानि, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='कुल हानि, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='अनुप्रवाह EGL';
$ec_lang['mphl_egl_2']='उर्ध्वप्रवाह EGL';
$ec_lang['mphl_hgl_2']='पाइप में उर्ध्वप्रवाह HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<p>नोट:</p><dl><dt>खुले इनलेट (पाइपनाली) की स्थिति के लिए, इनलेट नियंत्रण स्थितियों की जाँच आवश्यक है।</dt><dd>1. उर्ध्वप्रवाह HGL उर्ध्वप्रवाह सामान्य गहराई प्रवाह स्तर (या पाइप!) से कम नहीं हो सकती।</dd><dd>2. पाइपनाली का शीर्ष जल उर्ध्वप्रवाह HGL की तुलना में उर्ध्वप्रवाह EGL द्वारा बेहतर दर्शाया जाता है।</dd><dd>3. HY-8 का उपयोग करके सरल मानक पाइपनाली शीर्ष जल गणना के लिए <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">मेरा 2-मिनट का ट्यूटोरियल</a> देखें।</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='मैनिंग समलम्बाकार नाली';
$ec_lang['mtc_main_title']='मुफ़्त ऑनलाइन मैनिंग सूत्र समलम्बाकार नाली कैलकुलेटर';
$ec_lang['mtc_main_desc']='दिए गए ढलान और गहराई पर मैनिंग सूत्र एकसमान समलम्बाकार नाली प्रवाह';
$ec_lang['mtc_bottom_width']='तल चौड़ाई, b';
$ec_lang['mtc_side_slope_1']='पार्श्व ढलान 1 (क्षैतिज/ऊर्ध्वाधर)';
$ec_lang['mtc_side_slope_2']='पार्श्व ढलान 2 (क्षैतिज/ऊर्ध्वाधर)';
$ec_lang['mtc_channel_slope']='नाली ढलान, S';
$ec_lang['mtc_flow_depth']='प्रवाह गहराई, y';
$ec_lang['mtc_bend_angle']='मोड़ कोण <a target="_blank" href="riprap-bend-angle.png" title="चित्र के लिए क्लिक करें">?</a> (रिप्रैप आकार के लिए)';
$ec_lang['mtc_sgrock']='चट्टान का विशिष्ट गुरुत्व (2.65)';
$ec_lang['mtc_d50_in']='डिज़ाइन चट्टान आकार, D50';
$ec_lang['mtc_n_strickler']='Strickler के अनुसार डिज़ाइन चट्टान आकार के लिए n';
$ec_lang['mtc_n_blodgett']='Blodgett के अनुसार डिज़ाइन चट्टान आकार के लिए n';
$ec_lang['mtc_n_bathurst']='Bathurst के अनुसार डिज़ाइन चट्टान आकार के लिए n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett बनाम Bathurst';
$ec_lang['mtc_d50_bottom']='तल के लिए आवश्यक कोणीय चट्टान आकार, D50 (Isbash और MC) <a href="javascript:alert(\'Isbash (1936) और Maricopa County, Arizona, US के अनुसार।\')">?</a>';
$ec_lang['mtc_d50_z1']='पार्श्व ढलान 1 के लिए आवश्यक कोणीय चट्टान आकार, D50 (Isbash और MC) <a href="javascript:alert(\'Isbash (1936) और Maricopa County, Arizona, US के अनुसार।\')">?</a>';
$ec_lang['mtc_d50_z2']='पार्श्व ढलान 2 के लिए आवश्यक कोणीय चट्टान आकार, D50 (Isbash और MC) <a href="javascript:alert(\'Isbash (1936) और Maricopa County, Arizona, US के अनुसार।\')">?</a>';
$ec_lang['mtc_d50_mra']='आवश्यक कोणीय चट्टान आकार, D50 (Maynord, Ruff और Abt 1989)';
$ec_lang['mtc_d50_searcy']='आवश्यक कोणीय चट्टान आकार, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<p>नोट:</p><dl><dt>स्वचालित चट्टान आकार और खुरदरापन डिज़ाइन पुनरावृत्ति</dt><dd>एक खुरदरापन रेडियो बटन (BB अनुशंसित) और एक डिज़ाइन चट्टान आकार रेडियो बटन (Isbash अनुशंसित) चुनें। समान चट्टान आकार के साथ अपना वांछित प्रवाह पाने के लिए गहराई और चट्टान आकार सुरक्षा कारक को सूक्ष्म-समायोजित करें। हर बार जब आप कोई इनपुट मूल्य बदलते हैं, तो निम्नलिखित पुनरावृत्ति चक्र होता है: 1. डिज़ाइन चट्टान आकार से खुरदरापन की गणना की जाती है। 2. अनुरोधित खुरदरापन गणना इनपुट खुरदरापन में कॉपी की जाती है। 3. नाली प्रवाह और आवश्यक चट्टान आकार की गणना की जाती है। 4. डिज़ाइन चट्टान आकार समायोजित किया जाता है। 5. डिज़ाइन चट्टान आकार में त्रुटि बहुत छोटी होने तक दोहराएँ।</dd><dt>बुनियादी कैलकुलेटर (पुनरावृत्ति के बिना)</dt><dd>अपना वांछित खुरदरापन मूल्य दर्ज करें। डिज़ाइन चट्टान आकार इनपुट क्षेत्र को अनदेखा करें।</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='रॉबिन्सन रॉक चूट';
$ec_lang['rrc_main_desc']='रॉबिन्सन रॉक चूट डिज़ाइन स्प्रेडशीट';
// Weir Flow Simple
$ec_lang['ws_main_menu']='सरल वीयर प्रवाह';
$ec_lang['ws_main_title']='मुफ़्त ऑनलाइन सरल चौड़ी-शिखर वीयर प्रवाह कैलकुलेटर';
$ec_lang['ws_main_desc']='सरल चौड़ी-शिखर वीयर प्रवाह कैलकुलेटर';
$ec_lang['ws_weirLength']='वीयर लंबाई, l';
$ec_lang['ws_headWaterHeight']='शीर्ष जल ऊँचाई, h';
$ec_lang['ws_weirCoefficient']='वीयर गुणांक, Cw';
$ec_lang['ws_notes_heading']='नोट';
$ec_lang['ws_notes_we_term']='वीयर समीकरण';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='अनियमित वीयर प्रवाह';
$ec_lang['wi_main_title']='मुफ़्त ऑनलाइन खंडित, परिवर्तनशील गहराई, अनियमित वीयर प्रवाह कैलकुलेटर';
$ec_lang['wi_main_desc']='अनियमित वीयर प्रवाह कैलकुलेटर';
$ec_lang['wi_headWaterelevation']='शीर्ष जल स्तर';
$ec_lang['wi_weirPoints']='वीयर बिंदु';
$ec_lang['wi_station']='स्टेशन<br />(दूरी)';
$ec_lang['wi_elevation']='स्तर';
$ec_lang['wi_pondingHeight']='तालाब ऊँचाई';
$ec_lang['wi_incrementalFlow']='वृद्धिशील प्रवाह';
$ec_lang['wi_cumulativeFlow']='संचित प्रवाह';
$ec_lang['wi_save_and_calculate']='सहेजें और गणना करें';
$ec_lang['wi_notes_we_term']='वीयर समीकरण';
$ec_lang['wi_notes_we_def']='q = यदि (लंबाई = 0) तो 0 अन्यथा यदि (ढलान=0) तो cw*लंबाई*d<sub>0</sub><sup>1.5</sup> अन्यथा cw/(2.5*ढलान) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) जहाँ d<sub>1</sub> और d<sub>0</sub> सदा शून्य या धनात्मक हैं';
// Orifice Flow
$ec_lang['or_main_menu']='छिद्र प्रवाह';
$ec_lang['or_main_title']='मुफ़्त ऑनलाइन छिद्र प्रवाह कैलकुलेटर';
$ec_lang['or_main_desc']='छिद्र प्रवाह — स्वतंत्र या जलमग्न';
$ec_lang['or_shape']='उद्घाटन आकृति';
$ec_lang['or_shape_circular']='वृत्ताकार';
$ec_lang['or_shape_rectangular']='आयताकार';
$ec_lang['or_diameter']='व्यास (वृत्ताकार) या ऊँचाई (आयताकार), D';
$ec_lang['or_width']='चौड़ाई, W (केवल आयताकार)';
$ec_lang['or_invert']='उद्घाटन इनवर्ट स्तर (उद्घाटन का तल)';
$ec_lang['or_hwe']='शीर्ष जल स्तर';
$ec_lang['or_twe']='पुच्छ जल स्तर';
$ec_lang['or_cd']='निर्वहन गुणांक, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='केन्द्रक स्तर';
$ec_lang['or_head']='प्रभावी शीर्ष, h';
$ec_lang['or_area']='उद्घाटन क्षेत्रफल, A';
$ec_lang['or_flow']='प्रवाह, Q';
$ec_lang['or_velocity']='उद्घाटन पर वेग, v';
$ec_lang['or_regime']='छिद्र व्यवस्था जाँच';
$ec_lang['or_regime_valid']='स्वतंत्र निकास — छिद्र व्यवस्था वैध ✓';
$ec_lang['or_regime_submerged']='जलमग्न छिद्र (TWE इनवर्ट के ऊपर) — वैध ✓';
$ec_lang['or_regime_warn']='चेतावनी: शीर्ष जल शिखर से नीचे — छिद्र व्यवस्था नहीं';
$ec_lang['or_regime_twe_above_hwe']='चेतावनी: पुच्छ जल (TWE) शीर्ष जल (HWE) से ऊपर — इनपुट जाँचें';
$ec_lang['or_notes_1_term']='छिद्र समीकरण';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh)। स्वतंत्र निकास: h = HWE &minus; केन्द्रक। जलमग्न प्रवाह (इनवर्ट के ऊपर TWE): h = HWE &minus; TWE।';
$ec_lang['or_notes_2_term']='छिद्र व्यवस्था';
$ec_lang['or_notes_2_def']='छिद्र प्रवाह समीकरण तब लागू होते हैं जब शीर्ष जल सतह उद्घाटन के शिखर (ऊपर) से ऊपर हो। जब शीर्ष जल शिखर से नीचे हो, तो वीयर समीकरण का उपयोग करें।';
$ec_lang['or_notes_3_term']='निर्वहन गुणांक';
$ec_lang['or_notes_3_def']='तीखे-किनारे वाले छिद्रों के लिए C<sub>d</sub> लगभग 0.60&ndash;0.65 तक होता है। गोलाकार या पुनः-प्रवेशी इनलेट अलग मूल्य उपयोग करते हैं। मार्गदर्शन के लिए <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> या HEC-RAS हाइड्रॉलिक संदर्भ मैनुअल देखें।';
$ec_lang['or_notes_4_term']='जलमग्नता';
$ec_lang['or_notes_4_def']='जब TWE उद्घाटन इनवर्ट के ऊपर हो, तो यह कैलकुलेटर स्वचालित रूप से h = HWE &minus; TWE का उपयोग करके जलमग्न छिद्र समीकरण लागू करता है। जब TWE इनवर्ट पर या उससे नीचे हो, तो स्वतंत्र निकास माना जाता है और h = HWE &minus; केन्द्रक।';
// Orifice Drain Time
$ec_lang['odt_main_menu']='छिद्र निकासी समय';
$ec_lang['odt_main_title']='मुफ़्त ऑनलाइन छिद्र निकासी समय कैलकुलेटर — तालाब, बेसिन या टंकी';
$ec_lang['odt_main_desc']='तालाब या बेसिन छिद्र निकासी समय &mdash; शंक्वाकार आयतन विधि';
$ec_lang['odt_h1_elev']='प्रारंभिक जल सतह स्तर';
$ec_lang['odt_a1']='प्रारंभिक तालाब या बेसिन क्षेत्रफल, A1';
$ec_lang['odt_h2_elev']='अंतिम जल सतह स्तर';
$ec_lang['odt_h_orifice']='छिद्र केन्द्रक स्तर';
$ec_lang['odt_a0']='छिद्र स्तर पर तालाब या बेसिन क्षेत्रफल, A0';
$ec_lang['odt_a_ending']='अंतिम तालाब क्षेत्रफल, A2 (प्रक्षेपित)';
$ec_lang['odt_h2_check']='अंतिम स्तर जाँच';
$ec_lang['odt_h2_ok']='अंतिम स्तर छिद्र शिखर के ऊपर ✓';
$ec_lang['odt_h2_warn']='चेतावनी: अंतिम स्तर छिद्र शिखर पर या उससे नीचे (केन्द्रक + D/2)';
$ec_lang['odt_d']='छिद्र व्यास (वृत्ताकार) या ऊँचाई (आयताकार), D';
$ec_lang['odt_w']='छिद्र चौड़ाई, W (केवल आयताकार)';
$ec_lang['odt_t_sec']='निकासी समय (सेकंड)';
$ec_lang['odt_t_min']='निकासी समय (मिनट)';
$ec_lang['odt_t_hr']='निकासी समय (घंटे)';
$ec_lang['odt_t_day']='निकासी समय (दिन)';
$ec_lang['odt_notes_1_term']='सूत्र';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) शीर्ष H से छिद्र तक निकासी समय देता है। निकासी समय = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), जहाँ H<sub>1</sub> = प्रारंभिक स्तर &minus; छिद्र स्तर, H<sub>2</sub> = अंतिम स्तर &minus; छिद्र स्तर।';
$ec_lang['odt_notes_2_term']='विधि';
$ec_lang['odt_notes_2_def']='शंक्वाकार आयतन विधि तालाब या बेसिन को प्रारंभिक जल सतह पर A<sub>1</sub> और छिद्र केन्द्रक स्तर पर A<sub>0</sub> के बीच एक शंक्वाकार खंड के रूप में मॉडल करती है। A<sub>2</sub>, अंतिम स्तर पर तालाब का क्षेत्रफल, शंक्वाकार खंड मॉडल का उपयोग करके A<sub>1</sub> और A<sub>0</sub> से प्रक्षेपित किया जाता है। प्रारंभिक से अंतिम स्तर तक निकासी समय H<sub>1</sub> से छिद्र तक कुल निकासी समय से H<sub>2</sub> से छिद्र तक शेष निकासी समय घटाने के बराबर है।';
$ec_lang['odt_h1']='प्रारंभिक शीर्ष, H<sub>1</sub> (WSE &minus; केन्द्रक)';
$ec_lang['odt_q_max']='अधिकतम (प्रारंभिक) प्रवाह, Q<sub>max</sub>';
$ec_lang['odt_vol']='निकाला गया आयतन';
$ec_lang['odt_sketch_start']='प्रारंभ';
$ec_lang['odt_sketch_end']='अंत';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='तट से तट चौड़ाई';
$ec_lang['essc_mcr']='न्यूनतम वक्र त्रिज्या';
$ec_lang['essc_q']='प्रवाह, Q';
// Contact us.
$ec_lang['contact_title']='HawsEDC संपर्क';
$ec_lang['contactSendMessage']='Tom Haws को संदेश भेजें';
$ec_lang['contactYourName']='आपका नाम:';
$ec_lang['contactYourEmail']='आपका ई-मेल पता:';
$ec_lang['contactSubject']='विषय:';
$ec_lang['contact_message']='संदेश:';
$ec_lang['contactSpamPrefix']='पाँच जमा एक बराबर';
$ec_lang['contactSpamPostfix']='(कृपया अंग्रेज़ी में लिखें। 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='संदेश भेजें';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='माइक्रो-हाइड्रो पावर';
$ec_lang['mhp_main_title']='निःशुल्क ऑनलाइन माइक्रो-हाइड्रो पावर कैलकुलेटर';
$ec_lang['mhp_main_desc']='रन-ऑफ-रिवर माइक्रो-हाइड्रो पावर आउटपुट कैलकुलेटर';
$ec_lang['mhp_flow']='प्रवाह दर, Q';
$ec_lang['mhp_gross_head']='सकल शीर्ष (ऊँचाई अंतर), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='पेनस्टॉक शीर्ष हानियाँ, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='संयंत्र दक्षता, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='शुद्ध शीर्ष, H<sub>net</sub>';
$ec_lang['mhp_power']='शक्ति उत्पादन, P';
$ec_lang['mhp_annual_kwh']='100% क्षमता पर वार्षिक ऊर्जा (kWh/वर्ष)';
$ec_lang['mhp_notes_1_term']='शक्ति समीकरण';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, जहाँ &rho; = 1000 kg/m&sup3; (मीठा पानी) और g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='शुद्ध शीर्ष';
$ec_lang['mhp_notes_2_def']='शुद्ध शीर्ष = सकल शीर्ष &minus; पेनस्टॉक शीर्ष हानियाँ। एक सामान्य प्रारंभिक अनुमान h<sub>L</sub> &asymp; H<sub>gross</sub> का 5% है। अधिक सटीक पेनस्टॉक हानि अनुमान के लिए <a href="Darcy-Weisbach.php">डार्सी-वेइसबाख कैलकुलेटर</a> का उपयोग करें।';
$ec_lang['mhp_notes_3_term']='दक्षता';
$ec_lang['mhp_notes_3_def']='माइक्रो-हाइड्रो में सामान्य पेल्टन और क्रॉस-फ्लो टर्बाइनों के लिए संयंत्र दक्षता &eta; आमतौर पर 0.70 से 0.85 तक होती है। रूढ़िवादी प्रारंभिक अनुमान के रूप में 0.75 का उपयोग करें।';
$ec_lang['mhp_notes_4_term']='वार्षिक ऊर्जा';
$ec_lang['mhp_notes_4_def']='वार्षिक ऊर्जा निरंतर पूर्ण-प्रवाह संचालन (8760 घंटे/वर्ष) मानती है। मौसमी प्रवाह भिन्नता, रखरखाव के कारण बंद होने और भार कारक के कारण वास्तविक उत्पादन कम होगा।';
// Penstock Design
$ec_lang['ps_main_menu']='Penstock Design';
$ec_lang['ps_main_title']='Free Online Penstock Design Calculator';
$ec_lang['ps_main_desc']='Micro-Hydro Penstock Sizing — Head Loss, Power, and Velocity';
$ec_lang['ps_flow']='Flow rate, Q';
$ec_lang['ps_gross_head']='Gross head, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Penstock diameter, D';
$ec_lang['ps_length']='Penstock length, L';
$ec_lang['ps_roughness']='Pipe roughness, e';
$ec_lang['ps_km']='Minor loss coefficient, k<sub>m</sub>';
$ec_lang['ps_nu']='Kinematic viscosity, &nu;, in m<sup>2</sup>/s (1E-6 for water near 20&deg;C)';
$ec_lang['ps_efficiency']='Plant efficiency, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Flow velocity, v';
$ec_lang['ps_vel_check']='Velocity check';
$ec_lang['ps_f']='Friction factor, f';
$ec_lang['ps_hf']='Friction head loss, h<sub>f</sub>';
$ec_lang['ps_hm']='Minor head loss, h<sub>m</sub>';
$ec_lang['ps_hl']='Total penstock loss, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Head loss check';
$ec_lang['ps_hnet']='Net head, H<sub>net</sub>';
$ec_lang['ps_power']='Power output, P';
$ec_lang['ps_annual_kwh']='Annual energy at 100% capacity (kWh/yr)';
$ec_lang['ps_vel_ok']='1&ndash;3 m/s &mdash; within target &#x2713;';
$ec_lang['ps_vel_low']='below 1 m/s &mdash; increase diameter &#x26a0;';
$ec_lang['ps_vel_high']='above 3 m/s &mdash; decrease diameter &#x26a0;';
$ec_lang['ps_hl_ok']='within 10% target &#x2713;';
$ec_lang['ps_hl_warn']='exceeds 10% target &mdash; consider larger pipe &#x26a0;';
$ec_lang['ps_hl_bad']='exceeds 20% &mdash; resize pipe';
$ec_lang['ps_notes_1_term']='Head Loss';
$ec_lang['ps_notes_1_def']='Total penstock loss h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, where h<sub>f</sub> = f(L/D)(v&sup2;/2g) is Darcy-Weisbach friction loss and h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g covers entrance, bends, and valves. Net head H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Velocity';
$ec_lang['ps_notes_2_def']='Target 1&ndash;3 m/s. Below 1 m/s over-sizes the pipe for the flow; above 3 m/s increases friction losses and water hammer risk.';
$ec_lang['ps_notes_3_term']='Head Loss Target';
$ec_lang['ps_notes_3_def']='Penstock losses below 10% of gross head are generally economic. The optimal trade-off between pipe cost and lost power often falls around 4&ndash;6% for high-value electricity sites.';
$ec_lang['ps_notes_4_term']='Minor Losses k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Typical values: sharp intake entrance 0.5, each 45&deg; bend 0.2&ndash;0.3, gate valve (fully open) 0.1, butterfly valve 0.2. Sum all fittings for the total k<sub>m</sub>. Default 1.5 assumes one entrance and two bends.';
$ec_lang['ps_notes_5_term']='Pipe Roughness e';
$ec_lang['ps_notes_5_def']='Typical absolute roughness: steel (new) 0.046&nbsp;mm, steel (used) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, concrete 0.3&ndash;3&nbsp;mm. HDPE is common for small micro-hydro penstocks.';
