<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='အပိုင်းကိန်း';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']='rise/run';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC တွက်ချက်မှုကိရိယာများ';
$ec_lang['menu_main_list']='တွက်ချက်မှုကိရိယာများ စာရင်း';
$ec_lang['menu_main_hydraulics']='ဟိုက်ဒရောလစ်';
$ec_lang['menu_main_language']='ဘာသာစကား';
$ec_lang['template_welcome']='&gt;&gt; သင့်ကြောက်ရွံ့မှုများကို တံခါးဝတွင် ချန်ထားပါ; ချစ်ခြင်းမေတ္တာသည် ဤနေရာ၌ ကျွန်ုပ်တို့၏ဘာသာစကားဖြစ်သည်။ သင်သည် အရာခပ်သိမ်းကို ဖျက်ဆီးနေသည်မဟုတ်ပါ။ <a target="_blank" href="https://hawsedc.com/download.php">အခမဲ့ HawsEDC AutoCAD ကိရိယာများ</a>ကိုလည်း ခံစားပါ။ &lt;&lt;';
$ec_lang['template_translation_help']='ဤနေရာတွင် ထည့်သွင်းရန် တွက်ချက်မှုကိရိယာတစ်ခုအတွက် မြင်ကွင်းကောင်းတစ်ခု ရှိပါသလား။ ဘာသာပြန်ဆိုမှုများ တိုးတက်စေရန်၊ ပရိုဂရမ်ရေးရန် သို့မဟုတ် ဤတွက်ချက်မှုကိရိယာများကို လက်ခံဆောင်ရွက်ရန် ကူညီနိုင်ပါသလား။  ';
$ec_lang['template_feedback']='ကျေးဇူးပြု၍ သင်၏တန်ဖိုးရှိသောအကြံပြုချက် သို့မဟုတ် ချီးမွမ်းစကားများ ပေးပါ။ ဤအခမဲ့တွက်ချက်မှုကိရိယာသည် သင်၏မျှော်လင့်ချက်များကို အကုန်အလုံး ကျော်လွန်ဆောင်ရွက်နိုင်ခဲ့ပါသလား။';
$ec_lang['template_printable_title']='မှတ်တမ်းတင်ရာ ခေါင်းစဉ်';
$ec_lang['template_printable_subtitle']='မှတ်တမ်းတင်ရာ အမည်ငယ်';
$ec_lang['index_title']='အခမဲ့ အွန်လိုင်း အင်ဂျင်နီယာ တွက်ချက်မှုကိရိယာများ';
$ec_lang['calc_set_units']='ယူနစ်သတ်မှတ်ရန်:';
$ec_lang['points_data_help']='(သို့မဟုတ် ဒေတာနေရာကို အသုံးပြု၍ ကူးယူ/ကူးထည့်ပါ)';
$ec_lang['points_data_title']='အမှတ်ဒေတာ<br />(ကော်မာ သို့မဟုတ် tab ဖြင့် ခွဲ)';
$ec_lang['points_data_copy']='ကူးယူ';
$ec_lang['points_data_paste']='ကူးထည့်';
$ec_lang['calc_inputs']='ထည့်သွင်းချက်များ';
$ec_lang['calc_results']='ရလဒ်များ';
$ec_lang['view_hide_line']='[ဤစာကြောင်း ဝှက်ရန်]';
$ec_lang['view_printable']='မှတ်တမ်းတင်နိုင်သောဗားရှင်း (ပြန်ရယူရန် ပြန်လည်တင်/ရှင်းလင်းပါ)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['dw_main_title']='အခမဲ့ အွန်လိုင်း Darcy-Weisbach သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['dw_main_desc']='သတ်မှတ်အချင်း၊ ကြမ်းတမ်းမှုနှင့် စီးဆင်းမှုတွင် Darcy-Weisbach သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['dw_roughness']='Darcy-Weisbach ပကတိကြမ်းတမ်းမှု, e';
$ec_lang['dw_kinematic_viscosity']='ကိနမတစ်ပျစ်ပိုင်း, v, m<sup>2</sup>/sec ဖြင့် (အခန်းအပူချိန်ရှိ သန့်ရှင်းသောရေအတွက် 1E-6)';
$ec_lang['dw_reynolds_number']='Reynolds ကိန်း, Re';
$ec_lang['dw_flow_regime']='စီးဆင်းမှုပုံစံ';
$ec_lang['dw_regime_laminar']='ညင်သာသောစီးဆင်းမှု (laminar)';
$ec_lang['dw_regime_transitional']='အသွင်ကူးပြောင်းမှု (transitional)';
$ec_lang['dw_regime_turbulent']='လှုပ်ရှားသောစီးဆင်းမှု (turbulent)';
$ec_lang['dw_friction_factor_method']='ပွတ်တိုက်မှုဆေးနည်း';
$ec_lang['dw_friction_factor']='ပွတ်တိုက်မှုဆေး, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['hw_main_title']='အခမဲ့ အွန်လိုင်း Hazen-Williams သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['hw_main_desc']='သတ်မှတ်အချင်း၊ ကြမ်းတမ်းမှုနှင့် စီးဆင်းမှုတွင် Hazen-Williams သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['hw_hgl_1']='မြောက်ဘက် HGL';
$ec_lang['hw_hgl_2']='အပေါ်ဘက် HGL';
$ec_lang['hw_roughness']='Hazen-Williams ကိန်းဂဏန်း, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning မညီမညာ မြောင်းကြောင်း';
$ec_lang['mi_main_title']='အခမဲ့ အွန်လိုင်း Manning မညီမညာ မြောင်းကြောင်း တွက်ချက်မှုကိရိယာ';
$ec_lang['mi_main_desc']='မညီမညာ မြောင်းကြောင်း Manning တစ်သမတ်တည်း စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['mi_waterSurfaceElevation']='ရေမျက်နှာပြင် အမြင့်';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='အဖြတ်ပိုင်းအမှတ်များ';
$ec_lang['mi_groupPoint']='အမှတ်';
$ec_lang['mi_groupSegment']='အပိုင်း';
$ec_lang['mi_groupRegion']='ဇုန်';
$ec_lang['mi_station']='စခန်း';
$ec_lang['mi_elevation']='အမြင့်';
$ec_lang['mi_d50in']='အကာအရံ<br />အလယ်<br />ကျောက်<br />အရွယ်';
$ec_lang['mi_n']='n<br />အပိုင်း<br />အတွက်';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />ဇုန်<br />နယ်နိမိတ်<br />(둑)';
$ec_lang['mi_tau']='ပေါ်ပြင်<br />ညှပ်အား<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='ပေါင်းစပ်<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='မှတ်ချက်များ';
$ec_lang['mi_notes_1_term']='ပေါင်းစပ် n';
$ec_lang['mi_notes_1_def']='ဤတွက်ချက်မှုကိရိယာသည် Chow 1959၊ ၁၃၆ မျက်နှာ၊ ညီမျှခြင်း 6-17 (6-18 မဟုတ်) ကို အသုံးပြု၍ ဇုန်ပေါင်းစပ် n တွက်ချက်ရာတွင် HEC-RAS ကိုးကားစာအုပ်ကို လိုက်နာသည်။';
$ec_lang['mi_notes_2_term']='ကျောက်အကာ';
$ec_lang['mi_notes_2_def']='ကျောက်အကာ ဒီဇိုင်းဆွဲရန် Manning Trapezoidal Channel Calculator ကို အသုံးပြုပါ။ ဤတွက်ချက်မှုကိရိယာသည် သဘာဝအပိုင်းများအတွက် ပိုသင့်တော်သည်။';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning သွတ်ပိုက် စီးဆင်းမှု';
$ec_lang['mpf_main_title']='အခမဲ့ အွန်လိုင်း Manning သွတ်ပိုက် စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['mpf_main_desc']='သတ်မှတ်အစောက်နှင့် နက်ရှိုင်းမှုတွင် Manning ဖော်မြူလာ တစ်သမတ်တည်း သွတ်ပိုက် စီးဆင်းမှု';
$ec_lang['mpf_spreadheet_notice']='ဤတွက်ချက်မှုကိရိယာ၏ spreadsheet ဗားရှင်းကို ကြည့်ပါ';
$ec_lang['mpf_pipe_diameter']='သွတ်ပိုက် အချင်း, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning ကြမ်းတမ်းမှု, n';
$ec_lang['mpf_friction_slope']='ဖိအားအစောက် (ပိုက်အစောက်နှင့် <a target="_blank" href="../pressureslope.php">?</a> တူနိုင်), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='နှိုင်းယှဉ်စီးဆင်းမှုနက်, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(မှတ်ချက်များ ကြည့်ပါ)';
$ec_lang['mpf_flow']='စီးဆင်းမှု, Q';
$ec_lang['mpf_velocity']='အမြန်နှုန်း, v';
$ec_lang['mpf_velocity_head']='အမြန်နှုန်းခေါင်း, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='စီးဆင်းမှုနေရာ, a';
$ec_lang['mpf_pipe_area']='သွတ်ပိုက်နေရာ, a0';
$ec_lang['mpf_area_ratio']='နှိုင်းယှဉ်နေရာ, a/a0';
$ec_lang['mpf_wetted_perimeter']='စိုရွှဲသောပတ်လည်, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='ဟိုက်ဒရောလစ်အချင်းဝက်, R<sub>h</sub>';
$ec_lang['mpf_top_width']='အပေါ်ပိုင်းအကျယ်, T';
$ec_lang['mpf_froude_number']='Froude ကိန်း, F';
$ec_lang['mpf_shear_stress']='ပျမ်းမျှညှပ်အား (ဆွဲဆန့်အား), tau';
$ec_lang['mpf_full_flow']='အပြည့်စီးဆင်းမှု, Q0';
$ec_lang['mpf_full_flow_ratio']='အပြည့်စီးဆင်းမှုနှင့် အချိုး, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt><em>အဆုံးမဲ့ရှည်</em>သောသွတ်ပိုက်အတွင်းရှိ စီးဆင်းမှုနှင့် နက်ရှိုင်းမှုဖြစ်သည်။</dt><dd>သွတ်ပိုက်ထဲသို့ စီးဆင်းမှုသွင်းရန် သိသိသာသာ မြင့်မားသော ဦးရေနက်ရှိုင်းမှု လိုအပ်နိုင်သည်။ ဦးရေနက်ရှိုင်းမှုရရန် အမြန်နှုန်းခေါင်းအနည်းဆုံး 1.5 ဆကို ထည့်ပါ သို့မဟုတ် HY-8 ကို အသုံးပြုသည့် စံကြောင်းဖြတ် ဦးရေတွက်ချက်မှုများအတွက် <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ကျွန်ုပ်၏ ၂ မိနစ် သင်ခန်းစာကို ကြည့်ပါ</a>။</dd>';
$ec_lang['mpf_solve_for_dd0']='Q ပေးချက်မှ y/d<sub>0</sub> ဖြေရှင်းရန်';
$ec_lang['mpf_solve_desc']='တွက်ချက်မှုကိရိယာပုံစံမှ D<sub>0</sub>, n, နှင့် S<sub>0</sub> ကို အသုံးပြု၍ သတ်မှတ် Q အတွက် အနိမ့်ဆုံး y/d<sub>0</sub> ကို ရှာဖွေသည်။';
$ec_lang['mpf_solve_button']='ဖြေရှင်းရန်';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['mphl_main_title']='အခမဲ့ အွန်လိုင်း Manning သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['mphl_main_desc']='သတ်မှတ်အပြည့်စီးဆင်းမှုတွင် Manning ဖော်မြူလာ ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['mphl_pipe_length']='သွတ်ပိုက်အရှည်, L';
$ec_lang['mphl_area']='နေရာ, A';
$ec_lang['mphl_total_junction_k']='ပေါင်းစပ်ချိတ်ဆက်မှတ်ဆုံးရှုံးမှုကိန်း, k';
$ec_lang['mphl_friction_slope']='ပွတ်တိုက်မှုအစောက်';
$ec_lang['mphl_friction_loss']='ပွတ်တိုက်မှုဆုံးရှုံးမှု, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='ချိတ်ဆက်မှ ဆုံးရှုံးမှု, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='စုစုပေါင်းဆုံးရှုံးမှု, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='မြောက်ဘက် EGL';
$ec_lang['mphl_egl_2']='အပေါ်ဘက် EGL';
$ec_lang['mphl_hgl_2']='သွတ်ပိုက်အတွင်း အပေါ်ဘက် HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>ဖွင့်လှစ်ဝင်ပေါက် (ကြောင်းဖြတ်) အခြေအနေတွင် ဝင်ပေါက်ထိန်းချုပ်မှု အခြေအနေများကို စစ်ဆေးရန် လိုအပ်သည်။</dt><dd>1. အပေါ်ဘက် HGL သည် အပေါ်ဘက် ပုံမှန်နက်ရှိုင်းမှု စီးဆင်းမှုအမြင့် (သို့မဟုတ် သွတ်ပိုက်ထက် နိမ့်) ထက် နိမ့်၍မရပါ။</dd><dd>2. ကြောင်းဖြတ်တစ်ခု၏ ဦးရေသည် အပေါ်ဘက် HGL ထက် အပေါ်ဘက် EGL ဖြင့် ပိုကောင်းစွာ ကိုယ်စားပြုသည်။</dd><dd>3. HY-8 ကို အသုံးပြုသည့် ရိုးရှင်းသောစံကြောင်းဖြတ် ဦးရေတွက်ချက်မှုများအတွက် <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ကျွန်ုပ်၏ ၂ မိနစ် သင်ခန်းစာကို ကြည့်ပါ</a>။</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning Trapezoidal မြောင်းကြောင်း';
$ec_lang['mtc_main_title']='အခမဲ့ အွန်လိုင်း Manning ဖော်မြူလာ Trapezoidal မြောင်းကြောင်း တွက်ချက်မှုကိရိယာ';
$ec_lang['mtc_main_desc']='သတ်မှတ်အစောက်နှင့် နက်ရှိုင်းမှုတွင် Manning ဖော်မြူလာ တစ်သမတ်တည်း Trapezoidal မြောင်းကြောင်း စီးဆင်းမှု';
$ec_lang['mtc_bottom_width']='အောက်ပိုင်းအကျယ်, b';
$ec_lang['mtc_side_slope_1']='ဘေးစောက် ၁ (အလျားဆင့်/ဒေါင်လိုက်)';
$ec_lang['mtc_side_slope_2']='ဘေးစောက် ၂ (အလျားဆင့်/ဒေါင်လိုက်)';
$ec_lang['mtc_channel_slope']='မြောင်းကြောင်းအစောက်, S';
$ec_lang['mtc_flow_depth']='စီးဆင်းမှုနက်ရှိုင်းမှု, y';
$ec_lang['mtc_bend_angle']='ကောက်ကြောင်းထောင့် <a target="_blank" href="riprap-bend-angle.png" title="ပုံကြည့်ရန် နှိပ်ပါ">?</a> (riprap အရွယ်အတွက်)';
$ec_lang['mtc_sgrock']='ကျောက်တုံးအထူးဆွဲငင်အား (2.65)';
$ec_lang['mtc_d50_in']='ဒီဇိုင်းကျောက်တုံးအရွယ်, D50';
$ec_lang['mtc_n_strickler']='Strickler အရ ဒီဇိုင်းကျောက်တုံးအရွယ်အတွက် n';
$ec_lang['mtc_n_blodgett']='Blodgett အရ ဒီဇိုင်းကျောက်တုံးအရွယ်အတွက် n';
$ec_lang['mtc_n_bathurst']='Bathurst အရ ဒီဇိုင်းကျောက်တုံးအရွယ်အတွက် n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett နှင့် Bathurst နှိုင်းယှဉ်မှု';
$ec_lang['mtc_d50_bottom']='လိုအပ်သောအောက်ပိုင်းထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Isbash & MC) <a href="javascript:alert(\'Isbash (1936) နှင့် Maricopa County, Arizona, US အရ.\')">?</a>';
$ec_lang['mtc_d50_z1']='လိုအပ်သောဘေးစောက် ၁ ထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Isbash & MC) <a href="javascript:alert(\'Isbash (1936) နှင့် Maricopa County, Arizona, US အရ.\')">?</a>';
$ec_lang['mtc_d50_z2']='လိုအပ်သောဘေးစောက် ၂ ထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Isbash & MC) <a href="javascript:alert(\'Isbash (1936) နှင့် Maricopa County, Arizona, US အရ.\')">?</a>';
$ec_lang['mtc_d50_mra']='လိုအပ်သောထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='လိုအပ်သောထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>အလိုအလျောက် ကျောက်တုံးအရွယ်နှင့် ကြမ်းတမ်းမှုဒီဇိုင်း ထပ်ခါထပ်ခါတွက်ချက်မှု</dt><dd>ကြမ်းတမ်းမှု ရေဒီယိုခလုတ် (BB အကြံပြု) နှင့် ဒီဇိုင်းကျောက်တုံးအရွယ် ရေဒီယိုခလုတ် (Isbash အကြံပြု) ကိုရွေးချယ်ပါ။ တညီတညာတည်းကျောက်တုံးအရွယ်ဖြင့် သင်လိုချင်သောစီးဆင်းမှုရရန် နက်ရှိုင်းမှုနှင့် ကျောက်တုံးအရွယ်လုံခြုံရေးဆေးကို ချိန်ညှိပါ။ မည်သည့် ထည့်သွင်းချက်တန်ဖိုး ပြောင်းလဲသည့်အခါတိုင်း ောင်လာသောထပ်ခါတလဲလဲအကြိမ်မြောက်ကာလ ဖြစ်ပေါ်သည်: ၁. ဒီဇိုင်းကျောက်တုံးအရွယ်မှ ကြမ်းတမ်းမှုကို တွက်ချက်သည်။ ၂. တောင်းဆိုထားသောကြမ်းတမ်းမှုတွက်ချက်မှုကို ထည့်သွင်းကြမ်းတမ်းမှုသို့ ကူးယူသည်။ ၃. မြောင်းကြောင်းစီးဆင်းမှုနှင့် လိုအပ်သောကျောက်တုံးအရွယ်ကို တွက်ချက်သည်။ ၄. ဒီဇိုင်းကျောက်တုံးအရွယ်ကို ချိန်ညှိသည်။ ၅. ဒီဇိုင်းကျောက်တုံးအရွယ်အမှားငယ်မြဲဖြစ်သည့်အထိ ထပ်ခါတလဲလဲ ဆောင်ရွက်သည်။</dd><dt>အခြေခံတွက်ချက်မှုကိရိယာ (ထပ်ခါတလဲလဲမဟုတ်)</dt><dd>သင်လိုချင်သောကြမ်းတမ်းမှုတန်ဖိုးကို ထည့်ပါ။ ဒီဇိုင်းကျောက်တုံးအရွယ်ထည့်သွင်းနေရာကို လျစ်လျူရှုပါ။</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='Robinson Rock Chute ဒီဇိုင်း Spreadsheet';
// Weir Flow Simple
$ec_lang['ws_main_menu']='ရိုးရှင်းသော ဆည်တမံ စီးဆင်းမှု';
$ec_lang['ws_main_title']='အခမဲ့ အွန်လိုင်း ရိုးရှင်းသော ကျယ်ပြူးနှင်းစွပ် ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['ws_main_desc']='ရိုးရှင်းသော ကျယ်ပြူးနှင်းစွပ် ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['ws_weirLength']='ဆည်တမံအရှည်, l';
$ec_lang['ws_headWaterHeight']='ဦးရေအမြင့်, h';
$ec_lang['ws_weirCoefficient']='ဆည်တမံကိန်းဂဏန်း, Cw';
$ec_lang['ws_notes_heading']='မှတ်ချက်များ';
$ec_lang['ws_notes_we_term']='ဆည်တမံညီမျှခြင်း';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='မညီမညာ ဆည်တမံ စီးဆင်းမှု';
$ec_lang['wi_main_title']='အခမဲ့ အွန်လိုင်း အပိုင်းပိုင်း ပြောင်းလဲသောနက်ရှိုင်းမှုနှင့် မညီမညာ ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['wi_main_desc']='မညီမညာ ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['wi_headWaterelevation']='ဦးရေအမြင့်';
$ec_lang['wi_weirPoints']='ဆည်တမံအမှတ်များ';
$ec_lang['wi_station']='စခန်း<br />(အကွာအဝေး)';
$ec_lang['wi_elevation']='အမြင့်';
$ec_lang['wi_pondingHeight']='ရေဝပ်မှုအမြင့်';
$ec_lang['wi_incrementalFlow']='တိုးမြှင့်စီးဆင်းမှု';
$ec_lang['wi_cumulativeFlow']='စုစုပေါင်းစီးဆင်းမှု';
$ec_lang['wi_save_and_calculate']='သိမ်းဆည်းပြီး တွက်ချက်ရန်';
$ec_lang['wi_notes_we_term']='ဆည်တမံညီမျှခြင်း';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='အပေါက်မှ စီးဆင်းမှု';
$ec_lang['or_main_title']='အခမဲ့ အွန်လိုင်း အပေါက်မှ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['or_main_desc']='အပေါက်မှ စီးဆင်းမှု — လွတ်လပ်သော သို့မဟုတ် နစ်မွန်းသော';
$ec_lang['or_shape']='ဖွင့်လှစ်ပုံသဏ္ဌာန်';
$ec_lang['or_shape_circular']='စက်ဝိုင်းပုံ';
$ec_lang['or_shape_rectangular']='ထောင့်မှန်စတုဂံပုံ';
$ec_lang['or_diameter']='အချင်း (စက်ဝိုင်းပုံ) သို့မဟုတ် အမြင့် (ထောင့်မှန်စတုဂံပုံ), D';
$ec_lang['or_width']='အကျယ်, W (ထောင့်မှန်စတုဂံပုံသာ)';
$ec_lang['or_invert']='ဖွင့်လှစ်မှ invert အမြင့် (ဖွင့်လှစ်မှ အောက်ခြေ)';
$ec_lang['or_hwe']='ဦးရေအမြင့်';
$ec_lang['or_twe']='နောက်ရေအမြင့်';
$ec_lang['or_cd']='ထုတ်လွှတ်မှုကိန်းဂဏန်း, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='ဗဟိုချက်အမြင့်';
$ec_lang['or_head']='ထိရောက်သောခေါင်းဆုံး, h';
$ec_lang['or_area']='ဖွင့်လှစ်နေရာ, A';
$ec_lang['or_flow']='စီးဆင်းမှု, Q';
$ec_lang['or_velocity']='ဖွင့်လှစ်မှ အမြန်နှုန်း, v';
$ec_lang['or_regime']='အပေါက်ပုံစံစစ်ဆေးမှု';
$ec_lang['or_regime_valid']='လွတ်လပ်သောကျဆင်းမှု — အပေါက်ပုံစံ မှန်ကန် ✓';
$ec_lang['or_regime_submerged']='နစ်မွန်းသောအပေါက် (TWE သည် invert အပေါ်တွင်) — မှန်ကန် ✓';
$ec_lang['or_regime_warn']='သတိပေးချက်: ဦးရေသည် crown အောက်တွင် — အပေါက်ပုံစံမဟုတ်';
$ec_lang['or_regime_twe_above_hwe']='သတိပေးချက်: နောက်ရေ (TWE) သည် ဦးရေ (HWE) အပေါ်တွင် — ထည့်သွင်းချက်များ စစ်ဆေးပါ';
$ec_lang['or_notes_1_term']='အပေါက်ညီမျှခြင်း';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). လွတ်လပ်သောကျဆင်းမှုအတွက်: h = HWE &minus; ဗဟိုချက်. နစ်မွန်းသောစီးဆင်းမှု (invert အပေါ်တွင် TWE): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='အပေါက်ပုံစံ';
$ec_lang['or_notes_2_def']='ဦးရေမျက်နှာပြင်သည် ဖွင့်လှစ်မှ crown (အပေါ်) အပေါ်တွင်ရှိသောအခါ အပေါက်စီးဆင်းမှုညီမျှခြင်းများ သက်ဆိုင်သည်။ ဦးရေသည် crown အောက်တွင်ရှိသောအခါ ၎င်းအစား ဆည်တမံညီမျှခြင်းကို အသုံးပြုပါ။';
$ec_lang['or_notes_3_term']='ထုတ်လွှတ်မှုကိန်းဂဏန်း';
$ec_lang['or_notes_3_def']='C<sub>d</sub> သည် ချွန်ထက်သောဘောင်ပါ အပေါက်များအတွက် ၀.၆၀&ndash;၀.၆၅ ခန့်ဖြစ်သည်။ ဝိုင်းသော သို့မဟုတ် ပြန်ဝင်သောဝင်ပေါက်များသည် ကွဲပြားသောတန်ဖိုးများ အသုံးပြုသည်။ လမ်းညွှန်မှုအတွက် <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> သို့မဟုတ် HEC-RAS Hydraulic Reference Manual ကို ကြည့်ပါ။';
$ec_lang['or_notes_4_term']='နစ်မွန်းမှု';
$ec_lang['or_notes_4_def']='TWE သည် ဖွင့်လှစ်မှ invert အပေါ်တွင်ရှိသောအခါ ဤတွက်ချက်မှုကိရိယာသည် h = HWE &minus; TWE ကိုအသုံးပြု၍ နစ်မွန်းသောအပေါက်ညီမျှခြင်းကို အလိုအလျောက်သုံးသည်။ TWE သည် invert တွင်ရှိသော သို့မဟုတ် အောက်တွင်ရှိသောအခါ လွတ်လပ်သောကျဆင်းမှုဟု မှတ်ယူပြီး h = HWE &minus; ဗဟိုချက်ဖြစ်သည်။';
// Penstock Design
$ec_lang['ps_main_menu']='Penstock ဒီဇိုင်း';
$ec_lang['ps_main_title']='အခမဲ့ အွန်လိုင်း Penstock ဒီဇိုင်း တွက်ချက်မှုကိရိယာ';
$ec_lang['ps_main_desc']='Micro-Hydro Penstock အရွယ်တိုင်းတာမှု — ခေါင်းဆုံးဆုံးရှုံးမှု၊ ပါဝါနှင့် အမြန်နှုန်း';
$ec_lang['ps_flow']='စီးဆင်းနှုန်း, Q';
$ec_lang['ps_gross_head']='စုစုပေါင်းခေါင်းဆုံး, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Penstock အချင်း, D';
$ec_lang['ps_length']='Penstock အရှည်, L';
$ec_lang['ps_roughness']='သွတ်ပိုက်ကြမ်းတမ်းမှု, e';
$ec_lang['ps_km']='ချိတ်ဆက်မ (သို့မဟုတ် &ldquo;အသေး&rdquo;) ဆုံးရှုံးမှုကိန်း, k<sub>m</sub>';
$ec_lang['ps_nu']='ကိနမတစ်ပျစ်ပိုင်း, &nu;, m<sup>2</sup>/s ဖြင့် (20&deg;C နီးပါးရေအတွက် 1E-6)';
$ec_lang['ps_efficiency']='စက်ရုံထိရောက်မှု, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='စီးဆင်းမှုအမြန်နှုန်း, v';
$ec_lang['ps_vel_check']='အမြန်နှုန်းစစ်ဆေးမှု';
$ec_lang['ps_f']='ပွတ်တိုက်မှုဆေး, f';
$ec_lang['ps_hf']='ပွတ်တိုက်မှုခေါင်းဆုံးဆုံးရှုံးမှု, h<sub>f</sub>';
$ec_lang['ps_hm']='ချိတ်ဆက်မ (အမှတ်) ခေါင်းဆုံးဆုံးရှုံးမှု, h<sub>m</sub>';
$ec_lang['ps_hl']='Penstock စုစုပေါင်းဆုံးရှုံးမှု, h<sub>L</sub>';
$ec_lang['ps_hl_check']='ခေါင်းဆုံးဆုံးရှုံးမှုစစ်ဆေးမှု';
$ec_lang['ps_hnet']='အသားတင်ခေါင်းဆုံး, H<sub>net</sub>';
$ec_lang['ps_power']='ပါဝါထုတ်ပိုး, P';
$ec_lang['ps_annual_kwh']='၁၀၀% အလားအလာတွင် နှစ်စဉ်စွမ်းအင်';
$ec_lang['ps_vel_ok']='1–3 m/s — ပစ်မှတ်အတွင်း ✓';
$ec_lang['ps_vel_low']='1 m/s အောက် — အချင်းတိုးချဲ့ပါ ⚠';
$ec_lang['ps_vel_high']='3 m/s အပေါ် — အချင်းလျှော့ချပါ ⚠';
$ec_lang['ps_hl_ok']='၁၀% ပစ်မှတ်အတွင်း ✓';
$ec_lang['ps_hl_warn']='၁၀% ပစ်မှတ်ကျော်လွန် — ကြီးမားသောပိုက်ကို ထည့်သွင်းစဉ်းစားပါ ⚠';
$ec_lang['ps_hl_bad']='၂၀% ကျော်လွန် — သွတ်ပိုက် ပြန်လည်အရွယ်တိုင်းပါ';
$ec_lang['ps_notes_1_term']='ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['ps_notes_1_def']='Penstock စုစုပေါင်းဆုံးရှုံးမှု h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, h<sub>f</sub> = f(L/D)(v&sup2;/2g) သည် Darcy-Weisbach ပွတ်တိုက်မှုဆုံးရှုံးမှုဖြစ်ပြီး h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g သည် ဝင်ပေါက်၊ ကောက်ကြောင်းနှင့် ventil များကို ကျုံ့ဆုပ်သည်။ အသားတင်ခေါင်းဆုံး H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='အမြန်နှုန်း';
$ec_lang['ps_notes_2_def']='1&ndash;3 m/s ကို ပစ်မှတ်ထားပါ။ 1 m/s အောက်သည် စီးဆင်းမှုအတွက် သွတ်ပိုက်ကို အလွန်ကြီးစေသည်; 3 m/s အပေါ်သည် ပွတ်တိုက်မှုဆုံးရှုံးမှုနှင့် ရေပေါက်အချက်ပြ အန္တရာယ်ကို တိုးစေသည်။';
$ec_lang['ps_notes_3_term']='ခေါင်းဆုံးဆုံးရှုံးမှုပစ်မှတ်';
$ec_lang['ps_notes_3_def']='စုစုပေါင်းခေါင်းဆုံး၏ ၁၀% အောက်ရှိ Penstock ဆုံးရှုံးမှုများသည် ယေဘုယျ အဆင်ပြေသည်။ သွတ်ပိုက်ကုန်ကျစားရိတ်နှင့် ဆုံးရှုံးသောပါဝါအကြား အကောင်းဆုံးရွေးချယ်မှုသည် တန်ဖိုးမြင့်လျှပ်စစ်နေရာများအတွက် ၄&ndash;၆% ခန့်ကျဆင်းသည်။';
$ec_lang['ps_notes_4_term']='ချိတ်ဆက်မ (အမှတ်) ဆုံးရှုံးမှုများ k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='ဤဆုံးရှုံးမှုများသည် သွတ်ပိုက်ချိတ်ဆက်မများ၊ ဝင်ပေါက်များ၊ ကောက်ကြောင်းများနှင့် ventil များတွင် ဖြစ်ပေါ်သည် &mdash; &ldquo;အသေး&rdquo; ဟူသောဝေါဟာရသည် သမရိုးကျဖြစ်သော်လည်း လမ်းလွဲသည်; တိုသော penstock တစ်ခုတွင် ပွတ်တိုက်မှုဆုံးရှုံးမှုနှင့် ညီမျှ သို့မဟုတ် ကျော်လွန်နိုင်သည်။ ယေဘုယျ k တန်ဖိုးများ: ချွန်ထက်သောဝင်ပေါက် 0.5, 45&deg; ကောက်ကြောင်းတစ်ခုစီ 0.2&ndash;0.3, gate valve (အပြည့်ဖွင့်) 0.1, butterfly valve 0.2. စုစုပေါင်း k<sub>m</sub> ရရန် ချိတ်ဆက်မများကို ပေါင်းပါ။ ပုသေချက် 1.5 သည် ဝင်ပေါက်တစ်ခုနှင့် ကောက်ကြောင်းနှစ်ခုဟု မှတ်ယူသည်။';
$ec_lang['ps_notes_5_term']='သွတ်ပိုက်ကြမ်းတမ်းမှု e';
$ec_lang['ps_notes_5_def']='ယေဘုယျပကတိကြမ်းတမ်းမှု: သံမဏိ (အသစ်) 0.046&nbsp;mm, သံမဏိ (အသုံးပြုပြီး) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, ကွန်ကရစ် 0.3&ndash;3&nbsp;mm. HDPE သည် အသေးစားမိုက်ခရိုဟိုက်ဒရို penstock များအတွက် အများသုံးဖြစ်သည်။';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='မိုက်ခရိုဟိုက်ဒရို ပါဝါ';
$ec_lang['mhp_main_title']='အခမဲ့ အွန်လိုင်း မိုက်ခရိုဟိုက်ဒရို ပါဝါ တွက်ချက်မှုကိရိယာ';
$ec_lang['mhp_main_desc']='မြစ်ဘေးစီးမိုက်ခရိုဟိုက်ဒရို ပါဝါထုတ်ပိုးတွက်ချက်မှုကိရိယာ';
$ec_lang['mhp_flow']='စီးဆင်းနှုန်း, Q';
$ec_lang['mhp_gross_head']='စုစုပေါင်းခေါင်းဆုံး (အမြင့်ကျဆင်းမှု), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Penstock ခေါင်းဆုံးဆုံးရှုံးမှုများ, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='စက်ရုံထိရောက်မှု, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='အသားတင်ခေါင်းဆုံး, H<sub>net</sub>';
$ec_lang['mhp_power']='ပါဝါထုတ်ပိုး, P';
$ec_lang['mhp_annual_kwh']='၁၀၀% အလားအလာတွင် နှစ်စဉ်စွမ်းအင်';
$ec_lang['mhp_notes_1_term']='ပါဝါညီမျှခြင်း';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, &rho; = 1000 kg/m&sup3; (သာမန်ရေ) နှင့် g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='အသားတင်ခေါင်းဆုံး';
$ec_lang['mhp_notes_2_def']='အသားတင်ခေါင်းဆုံး = စုစုပေါင်းခေါင်းဆုံး &minus; penstock ခေါင်းဆုံးဆုံးရှုံးမှုများ။ ပုသေပထမခန့်မှန်းချက်မှာ h<sub>L</sub> &asymp; H<sub>gross</sub> ၏ ၅%။ ပိုတိကျသော penstock ဆုံးရှုံးမှုခန့်မှန်းချက်များအတွက် <a href="Darcy-Weisbach.php">Darcy-Weisbach တွက်ချက်မှုကိရိယာ</a>ကို အသုံးပြုပါ။';
$ec_lang['mhp_notes_3_term']='ထိရောက်မှု';
$ec_lang['mhp_notes_3_def']='မိုက်ခရိုဟိုက်ဒရိုတွင် အများသုံး Pelton နှင့် cross-flow turbines များအတွက် ယေဘုယျ စက်ရုံထိရောက်မှု &eta; သည် ၀.၇၀ မှ ၀.၈၅ ဖြစ်သည်။ သတိရှိသောပထမခန့်မှန်းချက်အဖြစ် ၀.၇၅ ကို အသုံးပြုပါ။';
$ec_lang['mhp_notes_4_term']='နှစ်စဉ်စွမ်းအင်';
$ec_lang['mhp_notes_4_def']='နှစ်စဉ်စွမ်းအင်သည် အဆက်မပြတ်အပြည့်စီးဆင်းမှု လုပ်ဆောင်မှု (နှစ်တစ်နှစ် ၈၇၆၀ နာရီ) ကိုမှတ်ယူသည်။ ရာသီဥတုစီးဆင်းမှုကွာဟချက်၊ ပြုပြင်ထိန်းသိမ်းမှုပိတ်ချိန်နှင့် ဝန်ဆောင်မှုဆေးကြောင့် တကယ့်ထုတ်လုပ်မှုသည် နိမ့်ပါလိမ့်မည်။';
// Orifice Drain Time
$ec_lang['odt_main_menu']='အပေါက်မှ ရေထုတ်ချိန်';
$ec_lang['odt_main_title']='အခမဲ့ အွန်လိုင်း အပေါက်မှ ရေထုတ်ချိန် တွက်ချက်မှုကိရိယာ — အင်တိုင်း၊ မြောင်းကြောင်း သို့မဟုတ် တိုင်ကီ';
$ec_lang['odt_main_desc']='အင်တိုင်း သို့မဟုတ် မြောင်းကြောင်း အပေါက်ရေထုတ်ချိန် &mdash; ကွာဖြတ်ပမာဏနည်းလမ်း';
$ec_lang['odt_h1_elev']='စတင်ရေမျက်နှာပြင်အမြင့်';
$ec_lang['odt_a1']='စတင်အင်တိုင်း သို့မဟုတ် မြောင်းကြောင်းနေရာ, A1';
$ec_lang['odt_h2_elev']='အဆုံးသတ်ရေမျက်နှာပြင်အမြင့်';
$ec_lang['odt_h_orifice']='အပေါက်ဗဟိုချက်အမြင့်';
$ec_lang['odt_a0']='အပေါက်အမြင့်တွင် အင်တိုင်း သို့မဟုတ် မြောင်းကြောင်းနေရာ, A0';
$ec_lang['odt_a_ending']='အဆုံးသတ်အင်တိုင်းနေရာ, A2 (ကြားထည့်တွက်ချက်)';
$ec_lang['odt_h2_check']='အဆုံးသတ်အမြင့်စစ်ဆေးမှု';
$ec_lang['odt_h2_ok']='အဆုံးသတ်အမြင့်သည် အပေါက်အထိပ်အပေါ်တွင် ✓';
$ec_lang['odt_h2_warn']='သတိပေးချက်: အဆုံးသတ်အမြင့်သည် အပေါက်အထိပ် (ဗဟိုချက် + D/2) တွင် သို့မဟုတ် အောက်တွင်';
$ec_lang['odt_d']='အပေါက်အချင်း (စက်ဝိုင်းပုံ) သို့မဟုတ် အမြင့် (ထောင့်မှန်စတုဂံပုံ), D';
$ec_lang['odt_w']='အပေါက်အကျယ်, W (ထောင့်မှန်စတုဂံပုံသာ)';
$ec_lang['odt_t_sec']='ရေထုတ်ချိန် (စက္ကန့်)';
$ec_lang['odt_t_min']='ရေထုတ်ချိန် (မိနစ်)';
$ec_lang['odt_t_hr']='ရေထုတ်ချိန် (နာရီ)';
$ec_lang['odt_t_day']='ရေထုတ်ချိန် (ရက်)';
$ec_lang['odt_notes_1_term']='ဖော်မြူလာ';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) သည် ခေါင်းဆုံး H မှ အပေါက်သို့ ရေထုတ်ချိန်ကို ပေးသည်။ ရေထုတ်ချိန် = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), H<sub>1</sub> = စတင်အမြင့် &minus; အပေါက်အမြင့်, H<sub>2</sub> = အဆုံးသတ်အမြင့် &minus; အပေါက်အမြင့်.';
$ec_lang['odt_notes_2_term']='နည်းလမ်း';
$ec_lang['odt_notes_2_def']='ကွာဖြတ်ပမာဏနည်းလမ်းသည် အင်တိုင်း သို့မဟုတ် မြောင်းကြောင်းကို ရေမျက်နှာပြင်တွင် စတင်နေရာ A<sub>1</sub> နှင့် အပေါက်ဗဟိုချက်အမြင့်တွင် နေရာ A<sub>0</sub> အကြား ကွာဖြတ်ပိုင်းဟု မော်ဒယ်ပြုသည်။ A<sub>2</sub>၊ အဆုံးသတ်အမြင့်တွင် အင်တိုင်းနေရာ၊ ကွာဖြတ်ပိုင်းမော်ဒယ်ကို အသုံးပြု၍ A<sub>1</sub> နှင့် A<sub>0</sub> မှ ကြားထည့်တွက်ချက်သည်။ စတင်မှ အဆုံးသတ်အမြင့်သို့ ရေထုတ်ချိန်သည် H<sub>1</sub> မှ အပေါက်သို့ စုစုပေါင်းရေထုတ်ချိန်နှင့် H<sub>2</sub> မှ အပေါက်သို့ ကျန်ရှိသောရေထုတ်ချိန် ခြားနားချက်နှင့် ညီသည်။';
$ec_lang['odt_h1']='စတင်ခေါင်းဆုံး, H<sub>1</sub> (WSE &minus; ဗဟိုချက်)';
$ec_lang['odt_q_max']='အမြင့်ဆုံး (စတင်) စီးဆင်းမှု, Q<sub>max</sub>';
$ec_lang['odt_vol']='ထုတ်လွှတ်ပမာဏ';
$ec_lang['odt_sketch_start']='စတင်';
$ec_lang['odt_sketch_end']='အဆုံးသတ်';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='ကမ်းနဖူးမှ ကမ်းနဖူးအကျယ်';
$ec_lang['essc_mcr']='အနည်းဆုံးကောက်ကြောင်းအချင်း';
$ec_lang['essc_q']='စီးဆင်းမှု, Q';
// Contact us.
$ec_lang['contact_title']='HawsEDC ဆက်သွယ်ရန်';
$ec_lang['contactSendMessage']='Tom Haws ထံ မက်ဆေ့ပေးပို့ပါ';
$ec_lang['contactYourName']='သင့်နာမည်:';
$ec_lang['contactYourEmail']='သင့်အီးမေးလ်လိပ်စာ:';
$ec_lang['contactSubject']='အကြောင်းအရာ:';
$ec_lang['contact_message']='မက်ဆေ့:';
$ec_lang['contactSpamPrefix']='ငါးပေါင်း တစ်ညီ';
$ec_lang['contactSpamPostfix']='(ကျေးဇူးပြု၍ စကားလုံးဖြင့် ရေးပါ။ 1=တစ် 2=နှစ် 3=သုံး 4=လေး 5=ငါး 6=ခြောက် 7=ခုနစ် +=ပေါင်း 5+1=6)';
$ec_lang['contactSubmitButton']='မက်ဆေ့တင်ပြရန်';
