<?php

// Bahasa Indonesia — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="fraksi";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']="% naik/datar";
$ec_lang['u_grade']="naik/datar";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/h";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="dtk";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='Kalkulator HawsEDC';
$ec_lang['menu_main_list']='Daftar Kalkulator';
$ec_lang['menu_main_hydraulics']='Hidraulika';
$ec_lang['menu_main_language']='Bahasa';
$ec_lang['menu_more']='Lainnya';
$ec_lang['template_welcome']='>> Buang rasa takutmu di pintu; di sini cinta adalah bahasa kami. Kamu tidak merusak segalanya. Nikmati juga <a target="_blank" href="https://hawsedc.com/download.php">alat AutoCAD HawsEDC gratis</a>. <<';
$ec_lang['template_translation_help']='Apakah Anda memiliki visi luar biasa untuk kalkulator yang ingin ditambahkan di sini?  Bisakah Anda membantu meningkatkan terjemahan, memprogram, atau meng-host kalkulator ini?  ';
$ec_lang['template_feedback']='Silakan berikan masukan atau pujian yang berharga. Apakah kalkulator gratis ini melebihi harapan Anda di segala hal?';
$ec_lang['template_printable_title']='Judul Cetak';
$ec_lang['template_printable_subtitle']='Subjudul Cetak';
$ec_lang['index_title']='Kalkulator Teknik Gratis Daring';
$ec_lang['calc_set_units']='Atur satuan:';
$ec_lang['points_data_help']='(atau Salin/Tempel menggunakan area data)';
$ec_lang['points_data_title']='Data titik<br />(dipisah koma atau tabulasi)';
$ec_lang['points_data_copy']='Salin';
$ec_lang['points_data_paste']='Tempel';
$ec_lang['calc_inputs']='Masukan';
$ec_lang['calc_results']='Hasil';
$ec_lang['view_hide_line']='[Sembunyikan baris ini]';
$ec_lang['view_printable']='Versi cetak (muat ulang untuk memulihkan)';
$ec_lang['ec_name_label']='Simpan perhitungan ini:';
$ec_lang['ec_name_placeholder']='Nama';
$ec_lang['ec_name_hint']='Menyimpan nilai masukan ini ke URL untuk penanda halaman, pengambilan riwayat, dan berbagi';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Kehilangan Tinggi Tekan Darcy-Weisbach';
$ec_lang['dw_main_title']='Kalkulator Kehilangan Tinggi Tekan Pipa Darcy-Weisbach Gratis Daring';
$ec_lang['dw_main_desc']='Kehilangan Tinggi Tekan Pipa Darcy-Weisbach pada Diameter, Kekasaran, dan Debit Tertentu';
$ec_lang['dw_roughness']='Kekasaran absolut Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Viskositas kinematik, ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Bilangan Reynolds, Re';
$ec_lang['dw_flow_regime']='Regime aliran';
$ec_lang['dw_regime_laminar']='aliran laminar';
$ec_lang['dw_regime_transitional']='transisi';
$ec_lang['dw_regime_turbulent']='turbulen';
$ec_lang['dw_friction_factor_method']='Metode faktor gesekan';
$ec_lang['dw_friction_factor']='Faktor gesekan, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Kehilangan Tinggi Tekan Hazen-Williams';
$ec_lang['hw_main_title']='Kalkulator Kehilangan Tinggi Tekan Pipa Hazen-Williams Gratis Daring';
$ec_lang['hw_main_desc']='Kehilangan Tinggi Tekan Pipa Hazen-Williams pada Diameter, Kekasaran, dan Debit Tertentu';
$ec_lang['hw_hgl_1']='HGL Hilir';
$ec_lang['hw_hgl_2']='HGL Hulu';
$ec_lang['hw_roughness']='Koefisien Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Saluran Tidak Beraturan Manning';
$ec_lang['mi_main_title']='Kalkulator Saluran Tidak Beraturan Manning Gratis Daring';
$ec_lang['mi_main_desc']='Kalkulator Aliran Seragam Saluran Tidak Beraturan dengan Rumus Manning';
$ec_lang['mi_waterSurfaceElevation']='Elevasi permukaan air';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Titik penampang melintang';
$ec_lang['mi_groupPoint']='Titik';
$ec_lang['mi_groupSegment']='Segmen';
$ec_lang['mi_groupRegion']='Zona';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Elev';
$ec_lang['mi_d50in']='Ukuran<br />median<br />batu<br />pelapis';
$ec_lang['mi_n']='n<br />untuk<br />seg-<br />men';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />batas<br />zona<br />(Tebing)';
$ec_lang['mi_tau']='Tegangan<br />geser<br />dasar<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />komposit';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Catatan';
$ec_lang['mi_notes_1_term']='n komposit';
$ec_lang['mi_notes_1_def']='Kalkulator ini mengikuti Manual Referensi HEC-RAS dalam menghitung n komposit zona menggunakan Chow 1959, halaman 136, persamaan 6-17 (bukan 6-18).';
$ec_lang['mi_notes_2_term']='Pelapis batu';
$ec_lang['mi_notes_2_def']='Gunakan Kalkulator Saluran Trapesium Manning untuk merancang pelapis batu. Kalkulator ini lebih sesuai untuk penampang alami.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Aliran Pipa Manning';
$ec_lang['mpf_main_title']='Kalkulator Aliran Pipa Manning Gratis Daring';
$ec_lang['mpf_main_desc']='Rumus Manning untuk Aliran Pipa Seragam pada Kemiringan dan Kedalaman Tertentu';
$ec_lang['mpf_spreadheet_notice']='Lihat versi spreadsheet dari kalkulator ini';
$ec_lang['mpf_pipe_diameter']='Diameter pipa, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Kekasaran Manning, n';
$ec_lang['mpf_friction_slope']='Kemiringan tekanan (mungkin <a target="_blank" href="../pressureslope.php">?</a> sama dengan kemiringan pipa), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Rasio kedalaman aliran, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Lihat catatan)';
$ec_lang['mpf_flow']='Debit, Q';
$ec_lang['mpf_velocity']='Kecepatan, v';
$ec_lang['mpf_velocity_head']='Tinggi kecepatan, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Luas penampang aliran, a';
$ec_lang['mpf_pipe_area']='Luas penampang pipa, a0';
$ec_lang['mpf_area_ratio']='Rasio luas, a/a0';
$ec_lang['mpf_wetted_perimeter']='Keliling basah, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Jari-jari hidraulik, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Lebar permukaan air, T';
$ec_lang['mpf_froude_number']='Bilangan Froude, F';
$ec_lang['mpf_shear_stress']='Tegangan geser rata-rata (gaya traksi), tau';
$ec_lang['mpf_full_flow']='Aliran penuh, Q0';
$ec_lang['mpf_full_flow_ratio']='Rasio terhadap aliran penuh, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Ini adalah debit dan kedalaman di dalam pipa yang <em>sangat panjang</em>.</dt><dd>Memasukkan aliran ke dalam pipa mungkin memerlukan kedalaman air hulu yang jauh lebih tinggi. Tambahkan setidaknya 1,5 kali tinggi kecepatan untuk mendapatkan kedalaman air hulu atau <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">lihat tutorial 2 menit saya</a> untuk perhitungan standar air hulu gorong-gorong menggunakan HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Cari y/d<sub>0</sub> berdasarkan Q';
$ec_lang['mpf_solve_desc']='Menggunakan D<sub>0</sub>, n, dan S<sub>0</sub> dari formulir kalkulator, mencari nilai y/d<sub>0</sub> terendah untuk Q tertentu.';
$ec_lang['mpf_solve_button']='Hitung';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Kehilangan Tinggi Tekan Pipa Manning';
$ec_lang['mphl_main_title']='Kalkulator Kehilangan Tinggi Tekan Pipa Manning Gratis Daring';
$ec_lang['mphl_main_desc']='Rumus Manning untuk Kehilangan Tinggi Tekan pada Aliran Penuh Tertentu';
$ec_lang['mphl_pipe_length']='Panjang pipa, L';
$ec_lang['mphl_area']='Luas, A';
$ec_lang['mphl_total_junction_k']='Koefisien kehilangan tinggi tekan pada sambungan total, k';
$ec_lang['mphl_friction_slope']='Kemiringan gesekan';
$ec_lang['mphl_friction_loss']='Kehilangan akibat gesekan, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Kehilangan pada sambungan, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Kehilangan total, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL Hilir';
$ec_lang['mphl_egl_2']='EGL Hulu';
$ec_lang['mphl_hgl_2']='HGL Hulu di pipa ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Untuk kondisi saluran masuk terbuka (gorong-gorong), perlu diperiksa kondisi kendali saluran masuk.</dt><dd>1. HGL hulu tidak boleh lebih rendah dari elevasi aliran kedalaman normal hulu (atau lebih rendah dari pipa!).</dd><dd>2. Air hulu gorong-gorong lebih baik diwakili oleh EGL hulu daripada HGL hulu.</dd><dd>3. Lihat <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">tutorial 2 menit saya</a> untuk perhitungan standar sederhana air hulu gorong-gorong menggunakan HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Saluran Trapesium Manning';
$ec_lang['mtc_main_title']='Kalkulator Rumus Manning Saluran Trapesium Gratis Daring';
$ec_lang['mtc_main_desc']='Rumus Manning untuk Aliran Seragam Saluran Trapesium pada Kemiringan dan Kedalaman Tertentu';
$ec_lang['mtc_bottom_width']='Lebar dasar, b';
$ec_lang['mtc_side_slope_1']='Kemiringan tebing 1 (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Kemiringan tebing 2 (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Kemiringan saluran, S';
$ec_lang['mtc_flow_depth']='Kedalaman aliran, y';
$ec_lang['mtc_bend_angle']='Sudut belokan <a target="_blank" href="riprap-bend-angle.png" title="Klik untuk gambar">?</a> (untuk ukuran riprap)';
$ec_lang['mtc_sgrock']='Berat jenis batu (2,65)';
$ec_lang['mtc_d50_in']='Ukuran batu rencana, D50';
$ec_lang['mtc_n_strickler']='n untuk ukuran batu rencana menurut Strickler';
$ec_lang['mtc_n_blodgett']='n untuk ukuran batu rencana menurut Blodgett';
$ec_lang['mtc_n_bathurst']='n untuk ukuran batu rencana menurut Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Ukuran batu sudut yang dibutuhkan di dasar, D50 (Isbash & MC) <span title="Menurut Isbash (1936) dan Maricopa County, Arizona, AS." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Ukuran batu sudut yang dibutuhkan di tebing 1, D50 (Isbash & MC) <span title="Menurut Isbash (1936) dan Maricopa County, Arizona, AS." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Ukuran batu sudut yang dibutuhkan di tebing 2, D50 (Isbash & MC) <span title="Menurut Isbash (1936) dan Maricopa County, Arizona, AS." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Ukuran batu sudut yang dibutuhkan, D50 (Maynord, Ruff, dan Abt 1989)';
$ec_lang['mtc_d50_searcy']='Ukuran batu sudut yang dibutuhkan, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Iterasi otomatis ukuran batu dan kekasaran</dt><dd>Pilih tombol radio kekasaran (BB direkomendasikan) dan tombol radio ukuran batu rencana (Isbash direkomendasikan). Sesuaikan kedalaman dan faktor keamanan ukuran batu untuk mendapatkan debit yang diinginkan dengan ukuran batu yang seragam. Setiap kali Anda mengubah nilai masukan, siklus iterasi berikut terjadi: 1. Kekasaran dihitung dari ukuran batu rencana. 2. Perhitungan kekasaran yang diminta disalin ke kekasaran masukan. 3. Debit saluran dan ukuran batu yang diperlukan dihitung. 4. Ukuran batu rencana disesuaikan. 5. Ulangi hingga galat pada ukuran batu rencana sangat kecil.</dd><dt>Kalkulator dasar (tanpa iterasi)</dt><dd>Masukkan nilai kekasaran yang Anda inginkan. Abaikan area masukan ukuran batu rencana.</dd></dl>';
// Robinson Rock Chute
// Weir Flow Simple
$ec_lang['ws_main_menu']='Aliran Pelimpah Sederhana';
$ec_lang['ws_main_title']='Kalkulator Pelimpah Bermercu Lebar Sederhana Gratis Daring';
$ec_lang['ws_main_desc']='Kalkulator Aliran Pelimpah Bermercu Lebar Sederhana';
$ec_lang['ws_weirLength']='Panjang pelimpah, l';
$ec_lang['ws_headWaterHeight']='Tinggi air hulu, h';
$ec_lang['ws_weirCoefficient']='Koefisien pelimpah, Cw';
$ec_lang['ws_notes_heading']='Catatan';
$ec_lang['ws_notes_we_term']='Persamaan Pelimpah';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Aliran Pelimpah Tidak Beraturan';
$ec_lang['wi_main_title']='Kalkulator Aliran Pelimpah Tidak Beraturan Bertingkat Gratis Daring';
$ec_lang['wi_main_desc']='Kalkulator Aliran Pelimpah Tidak Beraturan';
$ec_lang['wi_headWaterelevation']='Elevasi air hulu';
$ec_lang['wi_weirPoints']='Titik pelimpah';
$ec_lang['wi_station']='Stasiun<br />(jarak)';
$ec_lang['wi_elevation']='Elevasi';
$ec_lang['wi_pondingHeight']='Tinggi genangan';
$ec_lang['wi_incrementalFlow']='Debit parsial';
$ec_lang['wi_cumulativeFlow']='Debit kumulatif';
$ec_lang['wi_save_and_calculate']='Simpan dan Hitung';
$ec_lang['wi_notes_we_term']='Persamaan Pelimpah';
$ec_lang['wi_notes_we_def']='q = jika (panjang = 0) maka 0 selainnya jika (kemiringan=0) maka cw*panjang*d<sub>0</sub><sup>1.5</sup> selainnya cw/(2.5*kemiringan) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) di mana d<sub>1</sub> dan d<sub>0</sub> selalu positif atau nol';
// Orifice Flow
$ec_lang['or_main_menu']='Aliran Orifis';
$ec_lang['or_main_title']='Kalkulator Aliran Orifis atau Lubang Aliran Gratis Daring';
$ec_lang['or_main_desc']='Aliran Orifis atau Lubang Aliran — Bebas atau Tenggelam';
$ec_lang['or_shape']='Bentuk bukaan';
$ec_lang['or_shape_circular']='Lingkaran';
$ec_lang['or_shape_rectangular']='Persegi panjang';
$ec_lang['or_diameter']='Diameter atau tinggi, D <span title="Diameter for circular; height for rectangular" class="ec-tip">?</span>';
$ec_lang['or_width']='Lebar, W <span title="Rectangular openings only" class="ec-tip">?</span>';
$ec_lang['or_invert']='Elevasi dasar <span title="Bottom of opening" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Elevasi air hulu';
$ec_lang['or_twe']='Elevasi air hilir';
$ec_lang['or_cd']='Koefisien debit, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Elevasi sentroid';
$ec_lang['or_head']='Tinggi tekan efektif, h';
$ec_lang['or_area']='Luas bukaan, A';
$ec_lang['or_flow']='Debit, Q';
$ec_lang['or_velocity']='Kecepatan, v';
$ec_lang['or_regime']='Pemeriksaan regime orifis';
$ec_lang['or_regime_valid']='Aliran bebas — regime orifis valid ✓';
$ec_lang['or_regime_submerged']='Orifis tenggelam (TWE di atas sentroid) — valid ✓';
$ec_lang['or_regime_warn']='Peringatan: air hulu di bawah mahkota — bukan regime orifis';
$ec_lang['or_regime_twe_above_hwe']='Peringatan: air hilir (TWE) di atas air hulu (HWE) — periksa masukan';
$ec_lang['or_notes_1_term']='Persamaan Orifis';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Aliran bebas: h = HWE − sentroid. Aliran tenggelam (TWE di atas dasar): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Regime Orifis';
$ec_lang['or_notes_2_def']='Persamaan aliran orifis berlaku ketika permukaan air hulu berada di atas mahkota (bagian atas) bukaan. Ketika air hulu berada di bawah mahkota, gunakan persamaan pelimpah.';
$ec_lang['or_notes_3_term']='Koefisien Debit';
$ec_lang['or_notes_3_def']='C<sub>d</sub> berkisar sekitar 0,60–0,65 untuk orifis bersudut tajam. Saluran masuk bulat atau re-entrant menggunakan nilai yang berbeda. Lihat <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> atau Manual Referensi Hidraulik HEC-RAS untuk panduan.';
$ec_lang['or_notes_4_term']='Tenggelam';
$ec_lang['or_notes_4_def']='Ketika TWE berada di atas dasar bukaan, kalkulator ini secara otomatis menerapkan persamaan orifis tenggelam menggunakan h = HWE − TWE. Ketika TWE sama dengan atau di bawah dasar, aliran bebas diasumsikan dan h = HWE − sentroid.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Waktu Pengosongan Orifis';
$ec_lang['odt_main_title']='Kalkulator Waktu Pengosongan Orifis Gratis Daring — Kolam, Cekungan, atau Tangki';
$ec_lang['odt_main_desc']='Waktu Pengosongan Kolam atau Cekungan melalui Orifis — Metode Volume Konik';
$ec_lang['odt_h1_elev']='Elevasi permukaan air awal <span title="Starting water surface elevation" class="ec-tip">?</span>';
$ec_lang['odt_a1']='Luas awal, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Elevasi permukaan air akhir';
$ec_lang['odt_h_orifice']='Elevasi sentroid orifis';
$ec_lang['odt_a0']='Luas tingkat orifis, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Luas akhir, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='Pemeriksaan elevasi akhir';
$ec_lang['odt_h2_ok']='Elevasi akhir di atas mahkota orifis ✓';
$ec_lang['odt_h2_warn']='Peringatan: elevasi akhir sama dengan atau di bawah mahkota orifis (sentroid + D/2)';
$ec_lang['odt_d']='Orifis D <span title="Diameter (circular) or height (rectangular)" class="ec-tip">?</span>';
$ec_lang['odt_w']='Lebar orifis, W <span title="Rectangular only" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='Waktu pengosongan (s)';
$ec_lang['odt_t_min']='Waktu pengosongan (min)';
$ec_lang['odt_t_hr']='Waktu pengosongan (hr)';
$ec_lang['odt_t_day']='Waktu pengosongan (days)';
$ec_lang['odt_notes_1_term']='Rumus';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) memberikan waktu pengosongan dari tinggi tekan H ke orifis. Waktu pengosongan = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), di mana H<sub>1</sub> = elevasi awal − elevasi orifis, H<sub>2</sub> = elevasi akhir − elevasi orifis.';
$ec_lang['odt_notes_2_term']='Metode';
$ec_lang['odt_notes_2_def']='Metode volume konik memodelkan kolam atau cekungan sebagai penampang konik antara luas awal A<sub>1</sub> pada permukaan air awal dan luas A<sub>0</sub> pada elevasi sentroid orifis. A<sub>2</sub>, luas kolam pada elevasi akhir, diinterpolasi dari A<sub>1</sub> dan A<sub>0</sub> menggunakan model penampang konik. Waktu pengosongan dari elevasi awal ke akhir sama dengan waktu pengosongan total dari H<sub>1</sub> ke orifis dikurangi waktu pengosongan sisa dari H<sub>2</sub> ke orifis.';
$ec_lang['odt_h1']='Tinggi awal, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='Debit maksimum, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume yang dikosongkan';
$ec_lang['odt_sketch_start']='Mulai';
$ec_lang['odt_sketch_end']='Akhir';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Lebar tepi ke tepi';
$ec_lang['essc_mcr']='Radius kurva minimum';
$ec_lang['essc_q']='Debit, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Pengukuran Aliran Irigasi';
$ec_lang['irr_main_title']='Kalkulator Pengukuran Aliran Irigasi Online Gratis';
$ec_lang['irr_main_desc']='Pengukuran Aliran Irigasi — Pelimpah dan Orifis';
$ec_lang['contact_title']='Kontak HawsEDC';
$ec_lang['contactSendMessage']='Kirim pesan ke Tom Haws';
$ec_lang['contactYourName']='Nama Anda:';
$ec_lang['contactYourEmail']='Alamat e-mail Anda:';
$ec_lang['contactSubject']='Subjek:';
$ec_lang['contact_message']='Pesan:';
$ec_lang['contactSpamPrefix']='Lima ditambah satu sama dengan';
$ec_lang['contactSpamPostfix']='(Tulis dalam bahasa Inggris. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Kirim Pesan';
$ec_lang['contact_success']='Terima kasih telah meluangkan waktu untuk menulis.';


// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Tenaga Mikro-Hidro';
$ec_lang['mhp_main_title']='Kalkulator Tenaga Mikro-Hidro Online Gratis';
$ec_lang['mhp_main_desc']='Kalkulator Daya Keluaran Mikro-Hidro Aliran Sungai';
$ec_lang['mhp_flow']='Debit, Q';
$ec_lang['mhp_gross_head']='Tinggi bruto, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diameter pipa penstock, D';
$ec_lang['mhp_length']='Panjang pipa penstock, L';
$ec_lang['mhp_roughness']='Kekasaran pipa, e';
$ec_lang['mhp_km']='Koefisien kehilangan minor, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Viskositas kinematik, ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='Efisiensi instalasi, η (0–1)';
$ec_lang['mhp_velocity']='Kecepatan aliran, v';
$ec_lang['mhp_vel_check']='Pemeriksaan kecepatan';
$ec_lang['mhp_f']='Faktor gesekan, f';
$ec_lang['mhp_hf']='Kehilangan tinggi akibat gesekan, h<sub>f</sub>';
$ec_lang['mhp_hm']='Kehilangan tinggi minor, h<sub>m</sub>';
$ec_lang['mhp_hl']='Total kehilangan tinggi penstock, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Pemeriksaan kehilangan tinggi';
$ec_lang['mhp_hnet']='Tinggi neto, H<sub>net</sub>';
$ec_lang['mhp_power']='Daya keluaran, P';
$ec_lang['mhp_annual_kwh']='Energi tahunan pada kapasitas 100%';
$ec_lang['mhp_vel_ok']='1–3 m/s — dalam rentang target ✓';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_low']='Kecepatan rendah — risiko sedimentasi dan masuknya udara.';
$ec_lang['mhp_vel_low_short']='Rendah';
$ec_lang['mhp_vel_high']='Kecepatan tinggi — risiko pukulan air dan kehilangan titik (minor).';
$ec_lang['mhp_vel_high_short']='Tinggi';
$ec_lang['mhp_hl_ok']='dalam target 10% ✓';
$ec_lang['mhp_hl_warn']='melebihi target 10% — pertimbangkan pipa lebih besar ⚠';
$ec_lang['mhp_hl_bad']='melebihi 20% — ubah ukuran pipa';
$ec_lang['mhp_notes_1_term']='Kehilangan Tinggi';
$ec_lang['mhp_notes_1_def']='Total kehilangan h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, di mana h<sub>f</sub> = f(L/D)(v²/2g) adalah kehilangan gesekan Darcy-Weisbach dan h<sub>m</sub> = k<sub>m</sub>·v²/2g mencakup inlet, belokan, dan katup. Tinggi neto H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Kecepatan';
$ec_lang['mhp_notes_2_def']='Target 1–3 m/s. Di bawah 1 m/s pipa terlalu besar; di atas 3 m/s meningkatkan kehilangan gesekan dan risiko pukulan air.';
$ec_lang['mhp_notes_3_term']='Target Kehilangan Tinggi';
$ec_lang['mhp_notes_3_def']='Kehilangan penstock di bawah 10% dari tinggi bruto umumnya ekonomis. Titik optimal antara biaya pipa dan daya yang hilang sering berada di sekitar 4–6% untuk lokasi listrik bernilai tinggi.';
$ec_lang['mhp_notes_4_term']='Kehilangan Minor k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Nilai tipikal: inlet tajam 0.5, setiap belokan 45° antara 0.2–0.3, katup gerbang (terbuka penuh) 0.1, katup kupu-kupu 0.2. Jumlah semua fitting menghasilkan k<sub>m</sub> total. Default 1.5 mengasumsikan satu inlet dan dua belokan.';
$ec_lang['mhp_notes_5_term']='Kekasaran Pipa e';
$ec_lang['mhp_notes_5_def']='Kekasaran absolut tipikal: baja (baru) 0.046 mm, baja (bekas) 0.15 mm, HDPE 0.003 mm, PVC/uPVC 0.0015 mm, beton 0.3–3 mm. HDPE umum digunakan untuk pipa penstock mikro-hidro kecil.';

// About
$ec_lang['about_main_menu']='Tentang';
$ec_lang['install_main_menu']='Instal';
$ec_lang['install_main_title']='Instal EngCalcs';
$ec_lang['install_main_desc']='Tambahkan ke perangkat Anda untuk penggunaan offline';
$ec_lang['contact_main_menu']='Kontak';
$ec_lang['about_main_title']='Tentang Kalkulator Teknik HawsEDC';
$ec_lang['about_main_desc']='Misi, Sumber Terbuka, dan Kontribusi';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Laju Aplikasi Irigasi Tetes/Sprinkler';
$ec_lang['ds_main_title']='Kalkulator Laju Aplikasi Irigasi Tetes/Sprinkler Gratis Online';
$ec_lang['ds_main_desc']='Irigasi Tetes & Sprinkler — Laju Aplikasi';
$ec_lang['ds_q_avg']='Laju aliran emitter, q';
$ec_lang['ds_se']='Jarak emitter, S<sub>e</sub>';
$ec_lang['ds_sl']='Jarak lateral, S<sub>l</sub>';
$ec_lang['ds_n_e']='Emitter per lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Lateral per zona, n<sub>l</sub>';
$ec_lang['ds_d']='Kedalaman aplikasi target, d';
$ec_lang['ds_a_e']='Luas per emitter, A<sub>e</sub>';
$ec_lang['ds_pr']='Laju aplikasi, PR';
$ec_lang['ds_q_lat']='Aliran per lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Aliran zona, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Waktu operasi (jam)';
$ec_lang['ds_notes_1_term']='Laju Aplikasi';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, di mana A<sub>e</sub> = S<sub>e</sub> × S<sub>l</sub> adalah luas yang dilayani oleh setiap emitter. Laju aplikasi yang lebih rendah memberikan lebih banyak waktu untuk infiltrasi — penting pada tanah berat atau lahan miring.';
$ec_lang['ds_notes_2_term']='Waktu Operasi';
$ec_lang['ds_notes_2_def']='Waktu operasi = kedalaman target ÷ laju aplikasi. Pada tanah miring atau padat, bagi waktu operasi menjadi dua atau tiga siklus yang lebih pendek dengan periode istirahat di antaranya untuk menghindari limpasan permukaan.';

// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Rembesan Saluran';
$ec_lang['cs_main_title']='Kalkulator Kehilangan Rembesan Saluran dan Efisiensi Konveyans Gratis Online';
$ec_lang['cs_main_desc']='Kehilangan Rembesan Saluran & Efisiensi Konveyans — Metode Aliran Masuk-Keluar';
$ec_lang['cs_Q_in']='Aliran masuk, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Aliran keluar, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='Laju kehilangan rembesan, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Pemeriksaan pengukuran';
$ec_lang['cs_pct_loss']='Fraksi hilang';
$ec_lang['cs_Ec']='Efisiensi konveyans, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Peringkat efisiensi';
$ec_lang['cs_Vol_day']='Volume harian yang hilang';
$ec_lang['cs_Vol_year']='Volume tahunan yang hilang';
$ec_lang['cs_L']='Panjang ruas, L';
$ec_lang['cs_wp']='Keliling basah, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='Kehilangan per satuan panjang, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Nilai air';
$ec_lang['cs_lining_cost']='Biaya pelapisan';
$ec_lang['cs_Ec_target']='Target efisiensi konveyans, E<sub>c,target</sub> <span title="Target efisiensi konveyans setelah pelapisan; fraksi 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Luas pelapisan, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Nilai tahunan yang hilang';
$ec_lang['cs_annual_value_recovered']='Nilai tahunan yang dipulihkan';
$ec_lang['cs_lining_total_cost']='Biaya pelapisan total';
$ec_lang['cs_payback_years']='Periode pengembalian <span title="Simple payback = total lining cost ÷ annual value recovered" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — rembesan terdeteksi ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — tidak ada kehilangan terukur';
$ec_lang['cs_loss_negative']='Peringatan: Qout > Qin — periksa pengukuran ⚠';
$ec_lang['cs_Ec_good']='Baik — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Sedang — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Buruk — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Metode';
$ec_lang['cs_notes_1_def']='Metode aliran masuk-keluar memperkirakan rembesan dengan mengukur aliran di hulu dan hilir ruas saluran: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Efisiensi konveyans E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Volume tahunan mengasumsikan operasi aliran penuh terus-menerus; kehilangan aktual lebih rendah untuk saluran musiman atau aliran parsial.';
$ec_lang['cs_notes_2_term']='Peringkat Efisiensi';
$ec_lang['cs_notes_2_def']='Saluran tanah tidak dilapisi yang umum: E<sub>c</sub> = 60–80%. Saluran tanah terawat baik: 75–85%. Saluran berlapis beton: 90–98%. Kehilangan rembesan di atas 30% aliran masuk sering kali membenarkan investasi lapisan saluran. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Pengembalian Pelapisan';
$ec_lang['cs_notes_3_def']='Masukkan nilai air dan biaya pelapisan dalam mata uang yang konsisten apa pun. Luas pelapisan = panjang ruas × keliling basah — keliling basah penampang saluran di kedalaman aliran terukur (lebar dasar ditambah kedua tebing basah). Nilai tahunan yang dipulihkan mengasumsikan saluran berlapis mencapai E<sub>c</sub> target secara berkelanjutan. Pengembalian aktual akan lebih lama untuk saluran musiman atau jika pelapisan tidak mencapai efisiensi target.';
$ec_lang['cs_notes_4_term']='Referensi';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, edisi ke-3 (2001). FAO Irrigation and Drainage Paper 57 (1999).';

$ec_lang['irr_intro_html']='<p>Weir dan orifice adalah alat lapangan standar untuk mengukur aliran air dalam sistem irigasi. Pilih kalkulator yang sesuai dengan struktur Anda:</p>';
$ec_lang['irr_card_weir_uniform_head']='Weir — Mercu Lebar (Lebar Seragam)';
$ec_lang['irr_card_weir_uniform_desc']='Ukur aliran di atas mercu bendung pengalih, bangunan cek, atau papan weir. Masukkan panjang weir dan kedalaman air di atas mercu.';
$ec_lang['irr_card_weir_irregular_head']='Weir — Profil Tidak Beraturan';
$ec_lang['irr_card_weir_irregular_desc']='Gunakan saat mercu weir tidak berada pada elevasi seragam tunggal — pelimpah alami, bangunan terjun dengan lebar bervariasi, atau bangunan kendali multi-bagian.';
$ec_lang['irr_card_orifice_head']='Orifice — Pintu Air atau Sambungan Pipa';
$ec_lang['irr_card_orifice_desc']='Ukur aliran melalui pintu sorong, sambungan pipa, atau bukaan gorong-gorong. Menangani secara otomatis kondisi aliran bebas maupun tenggelam (tekanan balik hilir).';
$ec_lang['irr_card_canal_head']='Desain & Analisis Saluran';
$ec_lang['irr_card_canal_desc']='Desain atau periksa saluran irigasi menggunakan rumus Manning. Gunakan kalkulator Trapesium untuk saluran baru; kalkulator Tidak Beraturan untuk penampang alam atau buatan yang sudah ada.';
$ec_lang['irr_card_drip_head']='Desain Tetes & Sprinkler';
$ec_lang['irr_card_drip_desc']='Hitung laju aplikasi, keseragaman distribusi, debit lateral, debit zona, dan waktu operasi untuk sistem irigasi tetes atau sprinkler. Masukkan debit emitter, jarak emitter, dan kedalaman target.';
$ec_lang['irr_card_seepage_head']='Rembesan Saluran & Efisiensi Konveyans';
$ec_lang['irr_card_seepage_desc']='Perkirakan kehilangan rembesan dari ruas saluran menggunakan pengukuran aliran masuk dan keluar. Hitung efisiensi konveyans dan kehilangan air tahunan untuk membantu memprioritaskan investasi lapisan saluran.';
$ec_lang['irr_quickref_html']='<h3>Referensi Cepat</h3><dl><dt>Bendung pengalih atau bangunan cek</dt><dd>Ukur kedalaman air di atas mercu weir. Gunakan <a href="Weir-Flow-Simple.php">Weir Aliran Sederhana</a> untuk mercu seragam, atau <a href="Weir-Flow-Irregular.php">Weir Aliran Tidak Beraturan</a> untuk mercu berprofil atau bertangga.</dd><dt>Pintu air atau sambungan pipa</dt><dd>Ukur elevasi muka air hulu dan hilir (atau elevasi dasar pipa jika aliran bebas). Gunakan <a href="Orifice.php">Aliran Orifice</a>. Untuk pipa bulat, D = diameter pipa; untuk pintu persegi panjang, masukkan lebar W dan tinggi D.</dd><dt>Waktu pengosongan waduk atau kolam</dt><dd>Gunakan <a href="Orifice-Drain-Time.php">Waktu Pengosongan Orifice</a> untuk memperkirakan berapa lama menurunkan kolam atau waduk melalui orifice dasar — berguna untuk perencanaan tampungan irigasi.</dd><dt>Standar lapangan</dt><dd>Persamaan aliran weir dan orifice yang digunakan di sini sesuai dengan prosedur USBR <em>Water Measurement Manual</em> (edisi ke-3), yang umumnya dipersyaratkan oleh pengelola air dan distrik irigasi.</dd></dl>';
$ec_lang['about_body_html']='<h3>Misi</h3><p>Kalkulator Teknik HawsEDC hadir untuk melayani insinyur dan pekerja lapangan di seluruh dunia — terutama mereka yang bekerja di wilayah dengan keterbatasan air, sumber daya terbatas, atau kurang terlayani. Alat-alat ini merupakan bagian dari misi kemanusiaan yang lebih luas: menyampaikan kepada setiap manusia dengan cara yang paling praktis dan efektif bahwa mereka dicintai dan disayangi selamanya, bahwa mereka tidak perlu takut, dan bahwa mereka tidak akan merusak segalanya.</p><p>Kalkulator adalah kendaraannya. Tujuannya adalah dunia yang bebas dari penderitaan.</p><h3>Lisensi Sumber Terbuka</h3><p>Semua kode dirilis di bawah <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 atau lebih baru</a> — bebas dalam arti kebebasan. Anda boleh menggunakan, mempelajari, memodifikasi, dan mendistribusikan ulang kode dengan syarat yang sama.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Kode Sumber</h3><p>Kode sumber lengkap tersedia secara publik di Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Anda dapat menjelajahi kode, mengajukan isu, atau mem-fork repositori di sana.</p><h3>Berkontribusi</h3><p>Pull request sangat disambut. Cara berkontribusi:</p><ul><li><strong>Terjemahan</strong> — tingkatkan atau tambahkan bahasa. Buka pull request dengan perubahan pada file <code>lib/lang.ec.??.php</code> yang relevan.</li><li><strong>Laporan bug</strong> — gunakan formulir umpan balik di halaman kalkulator mana pun, atau ajukan isu di Bitbucket.</li><li><strong>Kalkulator baru</strong> — ide untuk alat teknik hidrolik yang melayani pekerja lapangan dan praktisi irigasi sangat disambut. Lihat panduan pengembang <code>CLAUDE.md</code> di repositori.</li><li><strong>Hosting</strong> — jika Anda dapat mencerminkan kalkulator ini untuk wilayah dengan konektivitas terbatas, silakan hubungi kami.</li></ul><h3>Penggunaan Offline</h3><p>Kalkulator-kalkulator ini berfungsi sebagai Aplikasi Web Progresif (PWA). Kunjungi halaman kalkulator mana pun saat terhubung ke internet, dan browser Anda akan secara otomatis menyimpan semua kalkulator ke dalam cache. Setelah itu, semua kalkulator berfungsi secara offline — tidak perlu internet.</p><p>Di Android atau iOS, gunakan opsi "Tambahkan ke Layar Utama" di browser Anda untuk memasang EngCalcs sebagai aplikasi di perangkat Anda. Di desktop, cari ikon pasang di bilah alamat browser Anda.</p><p>Anda juga dapat menyimpan kalkulator individual menggunakan menu "Simpan sebagai…" di browser Anda untuk penggunaan offline sekali pakai.</p><h3>Kontak</h3><p>Tom Haws — insinyur hidrolik dan penulis kalkulator ini.<br />Gunakan formulir umpan balik di halaman kalkulator mana pun, atau akses kode sumber di <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Desain Peluncur Batu (Robinson)';
$ec_lang['rc_main_title']='Kalkulator Desain Peluncur Batu Gratis Online — Robinson (1998)';
$ec_lang['rc_main_desc']='Penentuan Ukuran Riprap Peluncur Batu — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Kemiringan dasar peluncur, S<sub>0</sub>';
$ec_lang['rc_qt']='Debit satuan total, q<sub>t</sub> <span title="Debit per satuan lebar di inlet peluncur. Untuk saluran dengan lebar dasar B dan debit total Q, gunakan q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Porositas riprap, n<sub>p</sub>';
$ec_lang['rc_sg']='Berat jenis batu, sg <span title="Granit atau basalt pecah biasa ≈ 2.65. Rentang valid Robinson: 2.54 hingga 2.82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Gradasi SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Simpangan baku gradasi. Batu seragam ≈ 1.25. Rentang valid Robinson: 1.15 hingga 1.47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Kedalaman normal di saluran inlet, y<sub>n</sub> <span title="Genangan (Hp > yn) baik — mengurangi erosi di hulu. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Ukuran median batu yang diperlukan, D<sub>50</sub> <span title="Pers. 1 (S0 < 0.10) atau Pers. 2 (0.10-0.40). Valid: D50 15-278 mm, S0 0.02-0.40. Di luar rentang: diekstrapolasi." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Persamaan yang diterapkan';
$ec_lang['rc_sg_check']='Pemeriksaan berat jenis';
$ec_lang['rc_SD_check']='Pemeriksaan gradasi SD';
$ec_lang['rc_sg_ok']   ='sg dalam rentang valid (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='Peringatan: sg < 2.54 — di bawah rentang Robinson';
$ec_lang['rc_sg_high'] ='Peringatan: sg > 2.82 — di atas rentang Robinson';
$ec_lang['rc_SD_ok']   ='SD dalam rentang valid (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='Peringatan: SD < 1.15 — di bawah rentang Robinson';
$ec_lang['rc_SD_high'] ='Peringatan: SD > 1.47 — di atas rentang Robinson';
$ec_lang['rc_layer']='Ketebalan lapisan batu (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Jari-jari kurva mercu atas (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Panjang busur kurva mercu atas';
$ec_lang['rc_apron_length']='Panjang apron outlet (15 × D<sub>50</sub>) <span title="Diperlukan untuk dukungan struktural batu peluncur. "Tailwater minimum yang terjadi akibat saluran outlet dan resistansi saluran hilir cukup untuk memastikan stabilitas riprap di saluran outlet." (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Kekasaran Manning di peluncur, n';
$ec_lang['rc_Vm']='Kecepatan melalui mantel batu, V<sub>m</sub> <span title="Fraksi q_t yang mengalir melalui pori batu. Sisanya q_s mengalir di atas permukaan. Porositas default n_p = 0.45 untuk batu pecah bersudut." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Debit satuan melalui mantel, q<sub>m</sub>';
$ec_lang['rc_qs']='Debit satuan permukaan, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Kedalaman aliran di atas permukaan riprap, d';
$ec_lang['rc_Hp']='Tinggi muka air weir inlet, H<sub>p</sub> <span title="Genangan (Hp > yn) baik — mengurangi erosi di hulu. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Pemeriksaan genangan di inlet';
$ec_lang['rc_pond_ok']  ='Hp > yn — genangan di hulu ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — tidak ada genangan — periksa inlet terhadap erosi';
$ec_lang['rc_eq1']='Pers. 1 (S0 < 0.10) — kemiringan landai';
$ec_lang['rc_eq2']='Pers. 2 (0.10 ≤ S0 ≤ 0.40) — kemiringan curam';
$ec_lang['rc_eq_warn_low']='Peringatan: S0 < 0.02 — di bawah rentang validasi Robinson';
$ec_lang['rc_eq_warn_high']='Peringatan: S0 > 0.40 — di atas rentang validasi Robinson';
$ec_lang['rc_notes_1_term']='Persamaan Penentuan Ukuran Batu';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) mengembangkan dua persamaan empiris untuk ukuran median riprap D<sub>50</sub> berdasarkan kemiringan peluncur dan debit satuan. Persamaan 1 berlaku untuk kemiringan landai (S<sub>0</sub> < 0.10); Persamaan 2 berlaku untuk kemiringan curam (0.10 ≤ S<sub>0</sub> ≤ 0.40). Kedua persamaan memerlukan q<sub>t</sub> dalam m²/s dan menghasilkan D<sub>50</sub> dalam mm. Rentang yang divalidasi adalah 0.02 ≤ S<sub>0</sub> ≤ 0.40.';
$ec_lang['rc_notes_2_term']='Debit Satuan';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> adalah debit satuan total di mercu peluncur (total debit per satuan lebar). Untuk saluran dengan lebar dasar B yang membawa debit total Q, perkirakan q<sub>t</sub> ≈ Q / B, atau hitung dari kondisi kedalaman kritis di inlet peluncur.';
$ec_lang['rc_notes_3_term']='Aliran Melalui Mantel Batu';
$ec_lang['rc_notes_3_def']='Sebagian dari total debit bergerak melalui pori-pori riprap batu (debit mantel q<sub>m</sub>); sisanya mengalir di atas permukaan batu (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Kedalaman aliran d dihitung dari persamaan Manning yang diterapkan pada debit permukaan q<sub>s</sub> menggunakan kekasaran peluncur n. Porositas default n<sub>p</sub> = 0.45 adalah tipikal untuk batu pecah bersudut.';
$ec_lang['rc_notes_5_term']='Rentang Ukuran Batu yang Valid';
$ec_lang['rc_notes_5_def']='Persamaan dikembangkan menggunakan rentang D<sub>50</sub> dari 15 mm hingga 278 mm. Hasil di luar rentang ini diekstrapolasi dan harus digunakan dengan pertimbangan teknis tambahan.';
$ec_lang['rc_notes_6_term']='Elevasi Apron Outlet';
$ec_lang['rc_notes_6_def']='Elevasi bagian atas riprap di saluran outlet harus berada pada atau di bawah elevasi dasar saluran hilir. Jika lebih tinggi, batu outlet akan tidak stabil.';
$ec_lang['rc_notes_7_term']='Pemeriksaan Genangan Inlet';
$ec_lang['rc_notes_7_def']='Ketika kedalaman normal di saluran inlet lebih kecil dari tinggi muka air weir (H<sub>p</sub>) yang diperlukan untuk mengalirkan q<sub>t</sub>, terjadi aliran terbatas atau genangan di hulu apron inlet. Ini umumnya dapat diterima — genangan mengurangi kecepatan dan mencegah erosi di hulu. Untuk memeriksa: gunakan kalkulator aliran weir untuk mencari H<sub>p</sub> bagi q<sub>t</sub> dan lebar mercu yang diberikan, dan bandingkan dengan kedalaman normal saluran inlet. Jika H<sub>p</sub> melebihi kedalaman normal, genangan akan terjadi.';
$ec_lang['rc_notes_4_term']='Referensi';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Desain peluncur batu</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS juga menerbitkan <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">lembar kerja Excel</a> berdasarkan metode yang sama.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filter';
$ec_lang['rc_sketch_top_crest_curve'] = 'Lengkung Puncak';
$ec_lang['rc_sketch_outlet_apron']    = 'Lantai Hilir';
$ec_lang['rc_sketch_radius']          = 'jari-jari';

// Manning Trapezoid — velocity checks and note 2 (new)
$ec_lang['mtc_vel_check']='Pemeriksaan kecepatan';
$ec_lang['mtc_vel_ok']='Kecepatan wajar untuk asumsi aliran seragam.';
$ec_lang['mtc_vel_ok_short']='OK';
$ec_lang['mtc_vel_high']='Kecepatan tinggi — periksa kehilangan transisi dan energi yang tersedia.';
$ec_lang['mtc_vel_high_short']='Tinggi';
$ec_lang['mtc_vel_low']='Kecepatan rendah — risiko sedimentasi.';
$ec_lang['mtc_vel_low_short']='Rendah';
$ec_lang['mtc_note_2_term']='Pemeriksaan kecepatan';
$ec_lang['mtc_note_2_def']='Kecepatan tinggi mengimplikasikan energi spesifik tinggi dari beda tinggi yang tersedia. Energi tersebut dapat hilang dengan cepat pada ekspansi, belokan, atau hambatan. Verifikasi bahwa ini wajar untuk kondisi lapangan.';

// Micro-Hydro Power — notes 6 and 7 (new)
$ec_lang['mhp_notes_6_term']='Efisiensi';
$ec_lang['mhp_notes_6_def']='Efisiensi instalasi tipikal &eta; berkisar antara 0,70 hingga 0,85 untuk turbin Pelton dan turbin aliran silang yang umum digunakan dalam mikro-hidro. Gunakan 0,75 sebagai estimasi awal yang konservatif.';
$ec_lang['mhp_notes_7_term']='Energi Tahunan';
$ec_lang['mhp_notes_7_def']='Energi tahunan mengasumsikan operasi aliran penuh berkelanjutan (8.760 jam/tahun). Produksi aktual akan lebih rendah akibat variasi debit musiman, waktu henti pemeliharaan, dan faktor beban.';
