<?php

// ñáéíóú All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='fracción';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='pies^2';
$ec_lang['u_ft3ps']='pies^3/seg';
$ec_lang['u_ft']='pies';
$ec_lang['u_fth2o']='pies ca';
$ec_lang['u_ftps']='pies/seg.';
$ec_lang['u_gpm']='gal/min';
$ec_lang['u_gradePercent']='% vert./horiz.';
$ec_lang['u_grade']='vert./horiz.';
$ec_lang['u_in2']='pulg.^2';
$ec_lang['u_inh2o']='pulg. ca';
$ec_lang['u_in']='pulg.';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='Mgal/día';
$ec_lang['u_mh2o']='mca';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mmca';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='lb/pie^2';
$ec_lang['u_psi']='lb/pulg^2';
$ec_lang['u_bar']='bar';
$ec_lang['u_kgfcm2']='kgf/cm^2';
$ec_lang['u_s']='seg';
$ec_lang['u_lph']='L/hr';
$ec_lang['u_gph']='gal/hr';
$ec_lang['u_mmph']='mm/hr';
$ec_lang['u_inph']='pulg./hr';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='pies^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Calculadoras HawsEDC';
$ec_lang['menu_main_list']='Lista de calculadoras';
$ec_lang['menu_main_hydraulics']='Hidráulica';
$ec_lang['menu_main_language']='Idioma';
$ec_lang['menu_more']='Más';
$ec_lang['template_welcome']='Dejad vuestros miedos en la puerta; el amor se habla aquí. No estáis arruinando todo. Disfrutad también <a target="_blank" href="https://hawsedc.com/download.php">las herramientas libres HawsEDC para AutoCAD.</a>';
$ec_lang['template_feedback']='Envíenos sugerencias o elogios. ¿Le resultó útil esta calculadora gratuita?';
$ec_lang['template_printable_title']='Título Imprimible';
$ec_lang['template_printable_subtitle']='Subtítulo Imprimible';
$ec_lang['index_title']='Calculadoras para ingenieros gratis en línea';
$ec_lang['index_meta_desc_plain']='Calculadoras hidráulicas gratuitas para tuberías, canales, vertederos y riego. Funcionan en su navegador, sin conexión a internet, y están disponibles en 27 idiomas.';
$ec_lang['calc_set_units']='Cambiar sistema de medidas:';
$ec_lang['calc_units_us']='US';
$ec_lang['calc_units_si']='SI';
$ec_lang['calc_defaults']='Restaurar valores predeterminados';
$ec_lang['calc_defaults_confirm']='¿Restablecer la calculadora a los valores predeterminados originales?';
$ec_lang['points_data_help']='(o bien Copiar/Pegar usando el área de datos)';
$ec_lang['points_data_title']='Datos de los puntos<br />(separados por comas o tabulaciones)';
$ec_lang['points_data_copy']='Copiar';
$ec_lang['points_data_paste']='Pegar';
$ec_lang['calc_inputs']='Datos de entrada';
$ec_lang['calc_results']='Resultados: ';
$ec_lang['view_hide_line']='[Ocultar esta línea]';
$ec_lang['view_printable']='Versión Imprimible (recargar/renover para restaurar)';
$ec_lang['ec_name_label']='Guardar este cálculo:';
$ec_lang['ec_name_placeholder']='Nombre';
$ec_lang['ec_name_hint']='Guarda los datos de entrada en la URL para marcapáginas, recuperar del historial y compartir';
$ec_lang['calc_copy_link']='Copiar enlace';
$ec_lang['ec_related_calcs']='Calculadoras relacionadas:';
$ec_lang['calc_copy_link_done']='¡Copiado!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Pérdida de carga en tubería según Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculadora gratis en línea de pérdida de carga en tubería según Darcy-Weisbach';
$ec_lang['dw_main_desc']='Pérdida de carga en tubería a partir del diámetro, la rugosidad y el caudal, según Darcy-Weisbach';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Altura de rugosidad absoluta, e, de la pared de la tubería. Valores típicos: acero (nuevo) 0,046 mm, acero (usado) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, concreto 0,3–3 mm.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s para agua limpia a 20°C">Viscosidad cinemática, ν <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Viscosidad cinemática, ν';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s para agua limpia a 20°C';
$ec_lang['dw_reynolds_number']='Número de Reynolds, Re';
$ec_lang['dw_flow_regime']='Régimen de flujo';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='de transición';
$ec_lang['dw_regime_turbulent']='turbulento';
$ec_lang['dw_friction_factor_method']='Método del factor de fricción';
$ec_lang['dw_friction_factor']='Factor de fricción, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Pérdida de carga en tubería según Hazen-Williams';
$ec_lang['hw_main_title']='Calculadora gratis en línea de pérdida de carga en tubería según Hazen-Williams';
$ec_lang['hw_main_desc']='Pérdida de carga en tubería a partir del diámetro, el coeficiente C de Hazen-Williams y el caudal';
$ec_lang['hw_hgl_1']='HGL aguas abajo';
$ec_lang['hw_hgl_2']='HGL aguas arriba';
$ec_lang['hw_elev_up']='Elevación aguas arriba';
$ec_lang['hw_pressure_up']='Presión aguas arriba';
$ec_lang['hw_elev_down']='Elevación aguas abajo';
$ec_lang['hw_pressure_down']='Presión aguas abajo';
$ec_lang['hw_pressure_check']='Verificación de presión';
$ec_lang['hw_pressure_ok_short']='Presión positiva';
$ec_lang['hw_pressure_neg_short']='Presión negativa';
$ec_lang['hw_pressure_neg']='La presión aguas abajo es menor que cero. El HGL queda por debajo de la tubería, por lo que la tubería no fluiría llena y este resultado puede no ser válido.';
$ec_lang['hw_roughness']='Coeficiente de Hazen-Williams, C';
$ec_lang['hw_note_1']='<dl><dt>Esta calculadora no representa el perfil de la tubería entre los dos extremos.</dt><dd>Usa solo las elevaciones aguas arriba y aguas abajo que usted ingresa. Si el terreno se eleva por encima de cualquiera de los dos extremos en algún punto intermedio, la presión en ese punto alto es menor que cualquier presión indicada aquí. Vuelva a ejecutar la calculadora para el tramo desde el extremo aguas arriba hasta el punto alto para verificarlo.</dd><dd>Donde el HGL queda por debajo de la tubería, el agua está bajo presión negativa. El aire sale de la solución, una tubería de paredes delgadas puede colapsar, y puede ingresar agua subterránea contaminada a través de las juntas. Mantenga la línea bajo presión positiva en todo su recorrido, y considere una válvula de aire en cada punto alto.</dd><dt>La presión aguas arriba es una condición de frontera que usted proporciona.</dt><dd>Léala en un manómetro, en el nivel de agua de un tanque (la altura de agua sobre la tubería), o en la curva de un bombeo. Un bombeo entrega menos presión a medida que aumenta el caudal, así que use el punto de la curva que corresponda al caudal ingresado arriba.</dd><dt>Sume usted mismo los coeficientes de pérdida localizada.</dt><dd>Sume los valores de K de cada válvula, codo, tee, medidor y entrada en la línea, e ingrese ese total. Siga el enlace de ese campo para ver valores típicos. En una línea de conducción larga estas pérdidas son pequeñas frente a la fricción, pero en tuberías cortas dentro de una estación pueden ser la mayor parte de la pérdida.</dd></dl>';
$ec_lang['hw_notes_epanet_term']='Las constantes de Hazen-Williams ahora coinciden con EPANET (agosto de 2026)';
$ec_lang['hw_notes_epanet_def']='En agosto de 2026 se cambiaron el coeficiente y el exponente de Hazen-Williams para coincidir con EPANET. Los resultados de pérdida de carga difieren de los de las versiones anteriores de esta página hasta en un 0,1 por ciento, mucho menos que la incertidumbre del propio valor de C.';
// Manning Irregular
$ec_lang['mi_menu']='Canal de sección irregular según Manning';
$ec_lang['mi_main_title']='Calculadora gratis en línea de Manning para canal de sección irregular';
$ec_lang['mi_main_desc']='Calculadora de flujo uniforme según Manning para canal de sección irregular';
$ec_lang['mi_waterSurfaceElevation']='Altura de la lámina libre';
$ec_lang['mi_q_617']='<span class="ec-help" title="El caudal compuesto, Q, usando una n compuesta para cada región según Chow 6-17, velocidades iguales">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Puntos de la sección transversal';
$ec_lang['mi_groupPoint']='Punto';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_groupRegion']='Región';
$ec_lang['mi_station']='Est.';
$ec_lang['mi_elevation']='Alt.';
$ec_lang['mi_d50in']='Tamaño<br />mediano<br />de roca<br />de revestimiento';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='Div. de<br />regiones<br />R<sub>h</sub> y Q<br />(margen)';
$ec_lang['mi_tau']='Cortante<br />de fondo<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />compuesta';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='n compuesta';
$ec_lang['mi_notes_1_def']='Esta calculadora sigue el Manual de Referencia de HEC-RAS para calcular la n compuesta de la región usando Chow 1959, página 136, ecuación 6-17 (no 6-18).';
$ec_lang['mi_notes_2_term']='Revestimiento de roca';
$ec_lang['mi_notes_2_def']='Use la Calculadora de canal trapecial según Manning para diseñar el revestimiento de roca. Esta calculadora es más adecuada para secciones naturales.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Flujo según Manning en tuberías';
$ec_lang['mpf_main_title']='Calculadora gratis en línea de la fórmula de Manning para flujo uniforme en tuberías';
$ec_lang['mpf_main_desc']='Caudal y velocidad de flujo uniforme en tuberías según Manning, a partir de la pendiente y el calado';
$ec_lang['mpf_spreadheet_notice']='Hoja de cálculo: Flujo según Manning en tuberías';
$ec_lang['mpf_pipe_diameter']='Diámetro de la tubería, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Coeficiente de rugosidad de Manning, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Pendiente de fricción, S<sub>f</sub></a><span class="ec-help" title="A veces igual a la pendiente de la tubería. Siga el enlace para la explicación (solo en inglés)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Relación de calados, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Caudal, Q';
$ec_lang['mpf_flow_tip']='El caudal y la profundidad se calculan para una tubería de longitud infinita. Para lograr que este caudal entre en la tubería puede necesitarse una mayor profundidad de agua de entrada. Vea las Notas más abajo para más detalles y un video tutorial.';
$ec_lang['mpf_velocity']='Velocidad, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="Energía cinética expresada como una altura de columna de agua, v²/2g">Carga de velocidad, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='Área de flujo, A';
$ec_lang['mpf_pipe_area']='Área de la tubería, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Relación de áreas, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Perímetro mojado, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Radio hidráulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Ancho de lámina libre, T';
$ec_lang['mpf_froude_number']='Número de Froude, Fr';
$ec_lang['mpf_shear_stress']='Tensión tangencial promedio, τ';
$ec_lang['mpf_full_flow']='Caudal lleno, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Relación de caudales, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Este es el caudal (y la profundidad) dentro de una tubería <em>de longitud infinita</em>.</dt><dd>Lograr que el caudal entre en la tubería puede requerir una profundidad de agua de entrada (cabezal) bastante mayor. Agregue por lo menos 1,5 veces la carga de velocidad para estimar la profundidad de agua de entrada, o <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">vea mi tutorial de 2 minutos</a> sobre los cálculos estándar de cabezal de entrada en alcantarillas usando <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>, el programa gratuito de alcantarillas de la Administración Federal de Carreteras de los Estados Unidos.</dd>';
$ec_lang['mpf_sewer_ref']='<dl><dt>¿Está diseñando un alcantarillado sanitario?</dt><dd>Vea las <a target="_blank" href="/sewslope.php">tablas de pendiente mínima de alcantarillado</a> para tuberías de 4 a 96 pulgadas (100 a 2400 mm), expresadas en m/m, mm/m y porcentaje, y el estudio de <a target="_blank" href="/peakfact.php">factores pico para caudales muy bajos</a>. Ambos son documentos de referencia solo en inglés.</dd></dl>';
$ec_lang['mpf_solver_enter_positive_q']='Ingrese un Q objetivo positivo.';
$ec_lang['mpf_solver_no_solution']='Sin solución: Q excede la capacidad de la tubería en y/d0 = 93.8% (Qmax = {qmax} en las unidades seleccionadas).';
$ec_lang['mpf_solve_button']='Calcular';
$ec_lang['mpf_solve_for_flow']='para caudal, Q =';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Pérdida de carga en tubería según Manning';
$ec_lang['mphl_main_title']='Calculadora gratis en línea de pérdida de carga en tubería según Manning';
$ec_lang['mphl_main_desc']='Pérdida de carga en tubería llena a partir del caudal, según la fórmula de Manning';
$ec_lang['mphl_pipe_length']='Longitud, L';
$ec_lang['mphl_area']='Área, A';
$ec_lang['mphl_total_junction_k']='Coeficiente de pérdida localizada (menor), k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Coeficiente de pérdida, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Coeficiente de pérdida localizada (menor), km. Estas pérdidas ocurren en uniones de tubería, entradas, salidas, codos y válvulas — el término "menor" es convencional pero engañoso; en un tramo corto pueden igualar o superar las pérdidas por fricción. Valores típicos de k: entrada de borde vivo 0.5, cada codo de 45° 0.2–0.3, válvula de compuerta (totalmente abierta) 0.1, válvula mariposa 0.2, salida (a un depósito o a la atmósfera) 1.0. Sume todos los accesorios para obtener el km total. El valor predeterminado 2.0 supone una entrada, una salida y dos codos de 45°.';
$ec_lang['mphl_friction_slope']='Pendiente de fricción';
$ec_lang['mphl_friction_loss']='Pérdida por fricción, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Pérdida localizada (menor), h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Pérdida total, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='EGL aguas abajo';
$ec_lang['mphl_egl_2']='EGL aguas arriba';
$ec_lang['mphl_hgl_egl_tip']='Puede no ser válido si la tubería está elevada. Véanse las notas.';
$ec_lang['mphl_note_1']='<dl><dt>Esta calculadora no representa el perfil de la tubería entre los dos extremos.</dt><dd>Si el HGL desciende por debajo de la parte superior de la tubería en algún punto, este cálculo puede no ser válido.</dd><dt>Para una entrada abierta (alcantarilla), es necesario verificar las condiciones de control de entrada.</dt><dd>1. El HGL aguas arriba debe estar por encima de la cota de flujo a profundidad normal aguas arriba (¡y por encima de la tubería!).</dd><dd>2. El cabezal de una alcantarilla se representa mejor con el EGL aguas arriba que con el HGL aguas arriba.</dd><dd>3. Véase <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">mi tutorial de 2 minutos</a> para cálculos estándar sencillos de cabezal en alcantarillas usando <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>, el programa gratuito de alcantarillas de la Administración Federal de Carreteras de los Estados Unidos.</dd><dd>4. Esta página resuelve solo el caso de control de salida: una tubería que fluye llena, donde las condiciones aguas abajo determinan el cabezal. El diseño de alcantarillas consiste en decidir si predomina el control de entrada o el control de salida, así que use HY-8 siempre que cualquiera de los dos pueda predominar.</dd></dl>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapecial según Manning';
$ec_lang['mtc_main_title']='Calculadora gratis en línea de la fórmula de Manning para canal trapecial';
$ec_lang['mtc_main_desc']='Flujo uniforme Manning en un canal trapecial a partir de pendiente y profundidad';
$ec_lang['mtc_bottom_width']='Anchura de la base, b';
$ec_lang['mtc_side_slope_1']='Pendiente de lado 1, z<sub>1</sub> (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Pendiente de lado 2, z<sub>2</sub> (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Pendiente del canal, S';
$ec_lang['mtc_flow_depth']='Calado de la lámina de agua, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Ángulo de la curva, β</a><span class="ec-help" title="Para el tamaño de roca. Siga el enlace para ver el diagrama."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Densidad relativa al agua. Valor típico ≈ 2,65 para roca triturada">Gravedad específica de la roca, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Tamaño de roca de diseño, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n para el tamaño de roca de diseño según Strickler';
$ec_lang['mtc_n_blodgett']='n para el tamaño de roca de diseño según Blodgett';
$ec_lang['mtc_n_bathurst']='n para el tamaño de roca de diseño según Bathurst';
$ec_lang['mtc_n_pi']='n para el tamaño de roca de diseño según Phillips & Ingersoll';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett frente a Bathurst';
$ec_lang['mtc_pi_range_check']='Verificación de rango P&I';
$ec_lang['mtc_pi_ok']='d50 en rango P&I';
$ec_lang['mtc_pi_ok_tip']='0,28–0,36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='Fuera de rango';
$ec_lang['mtc_pi_tip']='Extrapolación fuera del rango de datos de 0,28–0,36 ft con el que se desarrolló esta ecuación — trátese como una verificación aproximada, no como base de diseño';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Según Isbash (1936) y el condado de Maricopa, Arizona, EE. UU.">Tamaño de roca angular requerido en el fondo, D<sub>50</sub> (Isbash y MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Según Isbash (1936) y el condado de Maricopa, Arizona, EE. UU.">Tamaño de roca angular requerido en el lado 1, D<sub>50</sub> (Isbash y MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Según Isbash (1936) y el condado de Maricopa, Arizona, EE. UU.">Tamaño de roca angular requerido en el lado 2, D<sub>50</sub> (Isbash y MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Tamaño de roca angular requerido, D<sub>50</sub>, según Maynord, Ruff, y Abt (1989)';
$ec_lang['mtc_d50_searcy']='Tamaño de roca angular requerido, D<sub>50</sub>, según Searcy (1967)';
$ec_lang['mtc_vel_ok']='Velocidad razonable para supuestos de flujo uniforme.';
$ec_lang['mtc_vel_low']='Velocidad baja — riesgo de sedimentación.';
$ec_lang['mtc_iteration_tip']='Elija una opción de rugosidad (se recomienda Blodgett–Bathurst) y una opción de tamaño de roca (se recomienda Isbash) para iterar automáticamente hacia un tamaño de roca uniforme para su caudal objetivo. Vea las Notas más abajo para el método completo, o ingrese su propio valor de rugosidad (siga el enlace para más orientación) e ignore el tamaño de roca para omitir la iteración.';
$ec_lang['mtc_note_1']='<dl><dt>Iteración automática para diseño de tamaño y rugosidad de roca</dt><dd>Elija una opción de rugosidad (se recomienda Blodgett–Bathurst) y una opción para el tamaño de roca de diseño (se recomienda Isbash). Ajuste la profundidad y el factor de seguridad del tamaño de roca para obtener el caudal deseado con un tamaño de roca uniforme. Cada vez que cambie cualquier valor de entrada, ocurre el siguiente ciclo de iteración: 1. Se calcula la rugosidad a partir del tamaño de roca de diseño. 2. El cálculo de rugosidad solicitado se copia al campo de rugosidad. 3. Se calculan el caudal del canal y el tamaño de roca requerido. 4. Se ajusta el tamaño de roca de diseño. 5. Se repite hasta que el error en el tamaño de roca de diseño sea muy pequeño.</dd><dt>Calculadora básica (sin iteración)</dt><dd>Ingrese el valor de rugosidad deseado. Ignore el área de entrada del tamaño de roca de diseño.</dd></dl>';
$ec_lang['mtc_note_2_term']='Verificación de velocidad';
$ec_lang['mtc_note_2_def']='La velocidad elevada implica que hubo una caída de elevación considerable que generó una energía específica tan alta. Esa energía puede disiparse rápidamente en expansiones, curvas u obstrucciones. Verifique que esto sea razonable para el sitio.';
$ec_lang['mtc_solver_no_solution']='No se encontró solución para el Q dado con estos datos del canal.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Flujo en Vertedero Simple';
$ec_lang['ws_main_title']='Calculadora gratuita en línea de flujo en vertedero simple de cresta ancha';
$ec_lang['ws_main_desc']='Calculadora de flujo en vertedero simple de cresta ancha';
$ec_lang['ws_weirLength']='Longitud del vertedero, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="Energía por unidad de peso del agua: una altura de columna de agua, no una presión">Carga, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='Coeficiente del vertedero, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Notas';
$ec_lang['ws_notes_we_term']='Ecuación del vertedero';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Flujo en Vertedero Irregular';
$ec_lang['wi_main_title']='Calculadora gratuita en línea de flujo en vertedero irregular, segmentado, de profundidad variable';
$ec_lang['wi_main_desc']='Calculadora de flujo en vertedero irregular';
$ec_lang['wi_weirPoints']='Puntos del vertedero';
$ec_lang['wi_pondingHeight']='Altura de remanso';
$ec_lang['wi_incrementalFlow']='Caudal incremental';
$ec_lang['wi_cumulativeFlow']='Caudal acumulado';
$ec_lang['wi_save_and_calculate']='Guardar y calcular';
$ec_lang['wi_notes_we_def']='q = si (length = 0) entonces 0 si no si (slope=0) entonces cw*length*d<sub>0</sub><sup>1.5</sup> si no cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) donde d<sub>1</sub> y d<sub>0</sub> son siempre positivos o cero';
// Orifice Flow
$ec_lang['or_main_menu']='Flujo por Orificio';
$ec_lang['or_main_title']='Calculadora gratuita en línea de flujo por orificio';
$ec_lang['or_main_desc']='Flujo por orificio — libre o sumergido';
$ec_lang['or_shape']='Forma de la apertura';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Rectangular';
$ec_lang['or_diameter']='<span class="ec-help" title="Diámetro para circular; altura para rectangular">Diámetro o altura, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Solo aperturas rectangulares">Ancho, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Fondo de la apertura">Cota de la solera <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Nivel de agua aguas arriba';
$ec_lang['or_twe']='Nivel de agua aguas abajo';
$ec_lang['or_cd']='Coeficiente de descarga, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Elevación del centroide';
$ec_lang['or_head']='<span class="ec-help" title="Energía por unidad de peso del agua: una altura de columna de agua, no una presión">Carga efectiva, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='Área de la apertura, A';
$ec_lang['or_regime']='Verificación del régimen de orificio';
$ec_lang['or_regime_valid']='Salida libre';
$ec_lang['or_regime_submerged']='Orificio sumergido';
$ec_lang['or_regime_submerged_tip']='TWE sobre el centroide — el régimen de orificio sigue siendo válido';
$ec_lang['or_regime_warn']='Fuera del régimen de orificio';
$ec_lang['or_regime_warn_tip']='Nivel de agua aguas arriba por debajo de la clave (parte superior) de la apertura';
$ec_lang['or_regime_twe_above_hwe']='Revise los datos';
$ec_lang['or_regime_twe_above_hwe_tip']='Nivel aguas abajo (TWE) sobre el nivel aguas arriba (HWE)';
$ec_lang['or_notes_1_term']='Ecuación de orificio';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Para salida libre: h = HWE − centroide. Para flujo sumergido (TWE sobre la solera): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Régimen de orificio';
$ec_lang['or_notes_2_def']='Las ecuaciones de flujo por orificio se aplican cuando la lámina de agua aguas arriba está sobre la clave (parte superior) de la apertura. Cuando está bajo la clave, use en su lugar una ecuación de vertedero.';
$ec_lang['or_notes_3_term']='Coeficiente de descarga';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varía entre aproximadamente 0,60–0,65 para orificios de borde agudo. Las entradas redondeadas o reentrantes usan valores diferentes. Consulte <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> o el Manual de Referencia Hidráulica de HEC-RAS para orientación.';
$ec_lang['or_notes_4_term']='Sumersión';
$ec_lang['or_notes_4_def']='Cuando TWE está sobre la solera de la apertura, esta calculadora aplica automáticamente la ecuación de orificio sumergido usando h = HWE − TWE. Cuando TWE está en o por debajo de la solera, se asume salida libre y h = HWE − centroide.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hidroeléctrica';
$ec_lang['mhp_main_title']='Calculadora Gratuita de Potencia Micro-Hidroeléctrica';
$ec_lang['mhp_main_desc']='Calculadora de Potencia de Micro-Hidroeléctrica de Pasada';
$ec_lang['mhp_gross_head']='Carga bruta, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="Diámetro de la tubería de presión (tubería de suministro)">Diámetro de la tubería de presión, D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='Longitud, L';
$ec_lang['mhp_efficiency']='Rendimiento de la instalación, η (0–1)';
$ec_lang['mhp_vel_check']='Verificación de velocidad';
$ec_lang['mhp_hl_check']='Verificación de pérdida de carga';
$ec_lang['mhp_hnet']='Carga neta, H<sub>net</sub>';
$ec_lang['mhp_power']='Potencia producida, P';
$ec_lang['mhp_annual_kwh']='Energía anual al 100% de capacidad';
$ec_lang['mhp_vel_low']='Velocidad baja — riesgo de sedimentación y entrada de aire.';
$ec_lang['mhp_vel_high']='Velocidad elevada — verificar pérdidas de transición, energía disponible y golpe de ariete.';
$ec_lang['mhp_vel_ok_short']='Bien';
$ec_lang['mhp_vel_high_short']='Alto';
$ec_lang['mhp_vel_low_short']='Bajo';
$ec_lang['mhp_vel_ok_tip']='La velocidad está en el rango eficiente para el diseño de la tubería de presión.';
$ec_lang['mhp_hl_ok_tip']='Dentro del objetivo del 10% — económico.';
$ec_lang['mhp_hl_warn_tip']='Supera el objetivo del 10%. Considere una tubería más grande.';
$ec_lang['mhp_hl_bad_tip']='Supera el objetivo del 20%. Cambie el tamaño de la tubería.';
$ec_lang['mhp_notes_1_term']='Pérdida de carga';
$ec_lang['mhp_notes_1_def']='La pérdida total en la tubería de presión h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, donde h<sub>f</sub> = f(L/D)(v²/2g) es la pérdida por fricción de Darcy-Weisbach y h<sub>m</sub> = k<sub>m</sub>·v²/2g cubre entradas, codos y válvulas. Carga neta H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Velocidad';
$ec_lang['mhp_notes_2_def']='Verifique que la velocidad sea razonable para el desnivel disponible y el costo de la tubería. Una velocidad muy baja puede indicar sobredimensionamiento; una velocidad muy alta puede aumentar las pérdidas por fricción y el riesgo de golpe de ariete.';
$ec_lang['mhp_notes_3_term']='Objetivo de pérdida de carga';
$ec_lang['mhp_notes_3_def']='Las pérdidas en la tubería de presión inferiores al 10% de la carga bruta son generalmente económicas. La compensación óptima entre el coste de la tubería y la potencia perdida suele situarse en torno al 4–6% para instalaciones de electricidad de alto valor.';
$ec_lang['mhp_notes_6_term']='Rendimiento';
$ec_lang['mhp_notes_6_def']='El rendimiento típico de la instalación η varía de 0,70 a 0,85 para turbinas Pelton y de flujo cruzado, comunes en microhidroeléctrica. Use 0,75 como estimación inicial conservadora.';
$ec_lang['mhp_notes_7_term']='Energía anual';
$ec_lang['mhp_notes_7_def']='La energía anual supone operación continua a caudal completo (8760 horas/año). La producción real será menor debido a la variación estacional del caudal, paradas por mantenimiento y factor de carga.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Tiempo de vaciado de estanque y tanque';
$ec_lang['odt_main_title']='Calculadora gratuita en línea de tiempo de vaciado de estanque, cuenca y tanque (orificio)';
$ec_lang['odt_main_desc']='Tiempo de vaciado de estanque, cuenca o tanque — salida por orificio, método del volumen cónico';
$ec_lang['odt_h1_elev']='Elevación inicial de la superficie del agua';
$ec_lang['odt_a1']='Área inicial, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Elevación final de la superficie del agua';
$ec_lang['odt_a0']='Área al nivel del orificio, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Interpolada del modelo cónico en la elevación final">Área final, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Verificación de la elevación final';
$ec_lang['odt_h2_ok']='Elevación final sobre la cima del orificio';
$ec_lang['odt_h2_warn']='Elevación final en o por debajo de la cima del orificio';
$ec_lang['odt_h2_warn_tip']='Cima del orificio = centroide + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Diámetro (circular) o altura (rectangular)">Orificio D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Solo rectangular">Ancho del orificio, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Tiempo de vaciado (s)';
$ec_lang['odt_t_min']='Tiempo de vaciado (min)';
$ec_lang['odt_t_hr']='Tiempo de vaciado (hr)';
$ec_lang['odt_t_day']='Tiempo de vaciado (días)';
$ec_lang['odt_notes_1_term']='Fórmula';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) da el tiempo de vaciado desde la carga H hasta el orificio. Tiempo de vaciado = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), donde H<sub>1</sub> = elevación inicial − elevación del orificio, H<sub>2</sub> = elevación final − elevación del orificio.';
$ec_lang['odt_notes_2_term']='Método';
$ec_lang['odt_notes_2_def']='El método del volumen cónico modela el estanque o laguna como una sección cónica entre el área inicial A<sub>1</sub> en la superficie de agua inicial y el área A<sub>0</sub> en la elevación del centroide del orificio. A<sub>2</sub>, el área del estanque en la elevación final, se interpola de A<sub>1</sub> y A<sub>0</sub> usando el modelo de sección cónica. El tiempo de vaciado desde la elevación inicial hasta la final es igual al tiempo total de vaciado desde H<sub>1</sub> hasta el orificio menos el tiempo de vaciado restante desde H<sub>2</sub> hasta el orificio.';
$ec_lang['odt_h1']='<span class="ec-help" title="Elevación inicial de la superficie del agua menos la elevación del centroide del orificio">Carga inicial, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Caudal máximo, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volumen vaciado';
$ec_lang['odt_sketch_start']='Inicio';
$ec_lang['odt_sketch_end']='Fin';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Riego';
$ec_lang['irr_main_title']='Calculadoras en línea gratuitas para la medición de caudal de riego';
$ec_lang['irr_main_desc']='Medición de Caudal de Riego — Vertederos y Orificios';
$ec_lang['irr_intro_html']='<p>Los vertederos y orificios son las herramientas de campo estándar para medir el caudal en los sistemas de riego. Seleccione la calculadora que corresponde a su estructura:</p>';
$ec_lang['irr_card_weir_uniform_head']='Vertedero — Cresta Ancha (Ancho Uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Mida el caudal sobre una cresta de presa de desvío, estructura de control o tablero vertedor. Ingrese la longitud del vertedero y la profundidad del agua sobre la cresta.';
$ec_lang['irr_card_weir_irregular_head']='Vertedero — Perfil Irregular';
$ec_lang['irr_card_weir_irregular_desc']='Úselo cuando la cresta del vertedero no tenga una elevación uniforme única: aliviaderos naturales, estructuras de caída con ancho variable o estructuras de control de múltiples secciones.';
$ec_lang['irr_card_orifice_head']='Orificio — Compuerta de Cabecera o Toma de Tubería';
$ec_lang['irr_card_orifice_desc']='Mida el caudal a través de una compuerta deslizante, toma de tubería o abertura de alcantarilla. Maneja automáticamente tanto la descarga libre como las condiciones sumergidas (aguas abajo).';
$ec_lang['irr_card_canal_head']='Diseño y Análisis de Canal';
$ec_lang['irr_card_canal_desc']='Diseñe o verifique un canal de riego usando la fórmula de Manning. Use la calculadora Trapezoidal para canales nuevos; la calculadora Irregular para secciones naturales o construidas existentes.';
$ec_lang['irr_card_seepage_head']='Infiltración en Canales y Eficiencia de Conducción';
$ec_lang['irr_card_seepage_desc']='Estime la pérdida por infiltración en un tramo de canal usando mediciones de caudal de entrada y salida. Calcule la eficiencia de conducción y la pérdida anual de agua para ayudar a priorizar inversiones en revestimiento.';
$ec_lang['irr_quickref_html']='<h3>Referencia Rápida</h3><dl><dt>Presa de desvío o estructura de control</dt><dd>Mida la profundidad del agua sobre la cresta del vertedero. Use <a href="Weir-Flow-Simple.php">Vertedero Simple</a> para una cresta uniforme, o <a href="Weir-Flow-Irregular.php">Vertedero Irregular</a> para una cresta perfilada o escalonada.</dd><dt>Compuerta de cabecera o toma de tubería</dt><dd>Mida la elevación del agua aguas arriba y aguas abajo (o la cota de solera si descarga libremente). Use <a href="Orifice.php">Caudal por Orificio</a>. Para una tubería circular, D = diámetro de la tubería; para una compuerta rectangular, ingrese el ancho W y la altura D.</dd><dt>Tiempo de vaciado de embalse o estanque</dt><dd>Use <a href="Orifice-Drain-Time.php">Tiempo de Vaciado por Orificio</a> para estimar cuánto tiempo tarda en bajar el nivel de un estanque o embalse a través de un orificio en el fondo — útil para la planificación del almacenamiento de riego.</dd><dt>Estándares de campo</dt><dd>Las ecuaciones de caudal por vertedero y orificio usadas aquí corresponden a los procedimientos del <em>Manual de Medición de Agua</em> (3.ª ed.) del USBR, comúnmente requeridos por administradores de agua y distritos de riego.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Espaciado de emisores, S<sub>e</sub>';
$ec_lang['ip_sl']='Espaciado de laterales, S<sub>l</sub>';
$ec_lang['ip_n_e']='Emisores por lateral, n<sub>e</sub>';
$ec_lang['ip_n_l']='Laterales por zona, n<sub>l</sub>';
$ec_lang['ip_d']='Lámina de riego objetivo, d';
$ec_lang['ip_a_e']='Área por emisor, A<sub>e</sub>';
$ec_lang['ip_pr']='Tasa de aplicación, PR';
$ec_lang['ip_q_lat']='Caudal por lateral, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Caudal de la zona, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Tiempo de riego (horas)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Pérdida por Infiltración en Canales';
$ec_lang['cs_main_title']='Calculadora gratuita en línea de pérdida por infiltración y eficiencia de conducción en canales';
$ec_lang['cs_main_desc']='Pérdida por Infiltración y Eficiencia de Conducción — Método de Entrada-Salida';
$ec_lang['cs_Q_in']='Caudal de entrada, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Caudal de salida, Q<sub>out</sub>';
$ec_lang['cs_L']='Longitud del tramo, L';
$ec_lang['cs_Q_loss']='Tasa de pérdida por infiltración, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verificación de medición';
$ec_lang['cs_pct_loss']='Fracción perdida';
$ec_lang['cs_Ec']='Eficiencia de conducción, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Clasificación de eficiencia';
$ec_lang['cs_Vol_day']='Volumen perdido diario';
$ec_lang['cs_Vol_year']='Volumen perdido anual';
$ec_lang['cs_Q_loss_per_L']='Pérdida por unidad de longitud, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valor del agua';
$ec_lang['cs_lining_cost']='Costo del revestimiento';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Meta de eficiencia de conducción después del revestimiento; fracción 0–1">Objetivo de revestimiento, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Área de revestimiento, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valor anual perdido';
$ec_lang['cs_annual_value_recovered']='Valor anual recuperado';
$ec_lang['cs_lining_total_cost']='Costo total del revestimiento';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Recuperación simple = costo total del revestimiento ÷ valor anual recuperado">Período de recuperación <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — infiltración detectada';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — sin pérdida medible';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — verifique las mediciones';
$ec_lang['cs_Ec_good']='Buena — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Regular — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Deficiente — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='El método de entrada-salida estima la infiltración midiendo el caudal en la cabecera y la cola de un tramo de canal: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. La eficiencia de conducción E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. El volumen anual supone una operación continua a caudal pleno; la pérdida real es menor en canales de operación estacional o parcial.';
$ec_lang['cs_notes_2_term']='Clasificaciones de Eficiencia';
$ec_lang['cs_notes_2_def']='Canales de tierra sin revestir típicos: E<sub>c</sub> = 60–80%. Canales de tierra bien mantenidos: 75–85%. Canales revestidos de concreto: 90–98%. Las pérdidas por infiltración superiores al 30% del caudal de entrada suelen justificar una inversión en revestimiento. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Recuperación por Revestimiento';
$ec_lang['cs_notes_3_def']='Ingrese el valor del agua y el costo del revestimiento en cualquier moneda consistente. Área de revestimiento = longitud del tramo × perímetro mojado — el perímetro mojado de la sección transversal del canal a la profundidad de flujo medida (ancho de la base más ambos taludes mojados). El valor anual recuperado supone que el canal revestido alcanza la E<sub>c</sub> objetivo de forma continua. La recuperación real será mayor en canales de uso estacional o si el revestimiento no alcanza la eficiencia objetivo.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3.ª ed. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='Acerca de';
$ec_lang['install_main_menu']='Instalar';
$ec_lang['install_main_title']='Instalar EngCalcs';
$ec_lang['install_main_desc']='Agregar al dispositivo para uso sin conexión';
$ec_lang['install_intro']='EngCalcs es una aplicación web progresiva (PWA). Una vez instalada, todas las calculadoras funcionan completamente sin conexión a internet.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Abra cualquier página de calculadora en Chrome.</li><li>Toque el botón <strong>⬇ Instalar</strong> en la barra de navegación superior, o toque el menú del navegador (⋮) y elija <strong>Añadir a pantalla de inicio</strong>.</li><li>Toque <strong>Instalar</strong> en el cuadro que aparece.</li><li>EngCalcs aparecerá en su pantalla de inicio y funcionará sin conexión.</li>';
$ec_lang['install_now_btn']='⬇ Instalar ahora';
$ec_lang['install_prompt_unavailable']='El cuadro de instalación no está disponible; use el menú de su navegador.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Abra cualquier página de calculadora en Safari.</li><li>Toque el botón <strong>Compartir</strong> (el cuadro con la flecha hacia arriba).</li><li>Desplácese hacia abajo y toque <strong>Añadir a pantalla de inicio</strong>.</li><li>Toque <strong>Añadir</strong>. EngCalcs aparecerá en su pantalla de inicio.</li>';
$ec_lang['install_ios_note']='En iOS, la instalación siempre se realiza desde el menú Compartir; no existe un cuadro de instalación automático.';
$ec_lang['install_desktop_heading']='Escritorio (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Abra cualquier página de calculadora.</li><li>Haga clic en el <strong>icono de instalación</strong> (⊕ o un icono de equipo) en la barra de direcciones del navegador, o abra el menú del navegador y elija <strong>Instalar EngCalcs…</strong></li><li>Haga clic en <strong>Instalar</strong>. EngCalcs se abrirá como una aplicación independiente.</li>';
$ec_lang['install_firefox_heading']='Firefox / Otros navegadores';
$ec_lang['install_firefox_body']='Firefox no permite instalar aplicaciones web progresivas (PWA) en el escritorio. Aun así, puede usar todas las calculadoras normalmente en el navegador; tras su primera visita, las páginas se guardan en caché automáticamente para uso sin conexión.';
$ec_lang['install_cached_heading']='Qué se guarda en caché';
$ec_lang['install_cached_body']='La primera vez que instala EngCalcs, todas las páginas de las calculadoras y sus archivos de apoyo (scripts, estilos) se guardan automáticamente en su dispositivo. Después de eso, todo funciona sin conexión a internet. Se recuerda el idioma elegido desde su última visita en línea.';
$ec_lang['contact_main_menu']='Contacto';
$ec_lang['about_main_title']='Acerca de las calculadoras de ingeniería HawsEDC';
$ec_lang['about_main_desc']='Misión, código abierto y contribuciones';
$ec_lang['about_body_html']='<h3>Misión</h3><p>Las Calculadoras de Ingeniería HawsEDC existen para servir a ingenieros y trabajadores de campo en todo el mundo — especialmente a quienes trabajan en regiones con escasez de agua, recursos limitados o poco atendidas. Estas herramientas forman parte de una misión humanitaria más amplia: decirle a cada ser humano de la manera más práctica y efectiva posible que es amado y apreciado para siempre, que no tiene nada que temer y que no va a arruinarlo todo.</p><p>Las calculadoras son el vehículo. El destino es un mundo libre de sufrimiento.</p><h3>Licencia de Código Abierto</h3><p>Todo el código se publica bajo la <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licencia Pública General GNU v3.0 o posterior</a> — libre como en libertad. Puede usar, estudiar, modificar y redistribuir el código bajo los mismos términos.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Código Fuente</h3><p>El código fuente completo está disponible públicamente en Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Puede explorar el código, registrar problemas o bifurcar el repositorio allí.</p><h3>Contribuir</h3><p>Se aceptan solicitudes de extracción. Formas de contribuir:</p><ul><li><strong>Traducciones</strong> — mejore o agregue un idioma. Abra una solicitud de extracción con cambios en el archivo <code>lib/lang.ec.??.php</code> correspondiente.</li><li><strong>Informes de errores</strong> — use el formulario de comentarios en cualquier página de calculadora, o registre un problema en Bitbucket.</li><li><strong>Nuevas calculadoras</strong> — las ideas para herramientas de ingeniería hidráulica que sirvan a trabajadores de campo y profesionales del riego son especialmente bienvenidas. Consulte la guía del desarrollador <code>CLAUDE.md</code> en el repositorio.</li><li><strong>Alojamiento</strong> — si puede alojar estas calculadoras en una región con conectividad limitada, comuníquese con nosotros.</li></ul><h3>Uso sin conexión</h3><p>Estas calculadoras funcionan como una Aplicación Web Progresiva (PWA). Visite cualquier página de calculadora con conexión a internet, y su navegador almacenará automáticamente todas las calculadoras en caché. Después de eso, todas las calculadoras funcionan sin conexión — no se requiere internet.</p><p>En Android o iOS, use la opción "Agregar a pantalla de inicio" de su navegador para instalar EngCalcs como una aplicación en su dispositivo. En el escritorio, busque el ícono de instalación en la barra de direcciones de su navegador.</p><p>También puede guardar cualquier calculadora individual usando el menú "Guardar como…" de su navegador para uso sin conexión puntual.</p><h3>Contacto</h3><p>Tom Haws — ingeniero hidráulico y autor de estas calculadoras.<br />Use el formulario de comentarios en cualquier página de calculadora, o acceda al código fuente en <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Contacto con HawsEDC';
$ec_lang['contactSendMessage']='Envíe un mensaje a Tom Haws';
$ec_lang['contactYourName']='Su nombre:';
$ec_lang['contactYourEmail']='Su dirección de correo electrónico:';
$ec_lang['contactSubject']='Asunto:';
$ec_lang['contact_message']='Mensaje:';
$ec_lang['contactSpamPrefix']='Five (cinco) plus (y) one (uno) equals (son) ';
$ec_lang['contactSpamPostfix']='(Favor de escribirla en inglés con letras. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Enviar Mensaje';
$ec_lang['contact_success']='Gracias por tomarse el tiempo para escribir.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Diseño de Bajante de Escollera (Robinson)';
$ec_lang['rc_main_title']='Calculadora Gratuita de Diseño de Bajante de Escollera — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionamiento de Escollera para Bajante — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Pendiente del fondo del canal, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="Caudal por unidad de ancho en la entrada del canal. Para un canal de ancho de plantilla B con caudal total Q, usar q_t = Q / B.">Caudal unitario total, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='Porosidad de la escollera, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="Densidad relativa al agua. Típico para granito o basalto triturado ≈ 2,65. Rango válido según Robinson: 2,54 a 2,82.">Gravedad específica de la roca, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="Desviación estándar de gradación. Roca uniforme ≈ 1,25. Rango válido Robinson: 1,15 a 1,47.">Gradación SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="El remanso (Hp > yn) es favorable — reduce la erosión aguas arriba. (USDA)">Tirante normal en el canal de entrada, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="Ec. 1 (S0 < 0,10) o Ec. 2 (0,10-0,40). Válido: D50 15-278 mm, S0 0,02-0,40. Fuera del rango: extrapolado.">Tamaño mediano de roca requerido, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='Ecuación aplicada';
$ec_lang['rc_sg_check']='Verificación de gravedad específica';
$ec_lang['rc_SD_check']='Verificación de gradación SD';
$ec_lang['rc_sg_ok']   ='sg en rango válido';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg por debajo del rango Robinson';
$ec_lang['rc_sg_low_tip']='Rango válido: 2,54–2,82';
$ec_lang['rc_sg_high'] ='sg por encima del rango Robinson';
$ec_lang['rc_sg_high_tip']='Rango válido: 2,54–2,82';
$ec_lang['rc_SD_ok']   ='SD en rango válido';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD por debajo del rango Robinson';
$ec_lang['rc_SD_low_tip']='Rango válido: 1,15–1,47';
$ec_lang['rc_SD_high'] ='SD por encima del rango Robinson';
$ec_lang['rc_SD_high_tip']='Rango válido: 1,15–1,47';
$ec_lang['rc_layer']='Espesor de la capa de roca (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Radio de curva en cresta superior (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Longitud de arco en cresta superior';
$ec_lang['rc_apron_length']='<span class="ec-help" title="Requerido para el soporte estructural de la roca del canal. “El tirante mínimo aguas abajo que resulta del tramo de salida y la resistencia del canal aguas abajo es suficiente para garantizar la estabilidad de la escollera en el tramo de salida.” (Robinson)">Longitud del zampeado de salida (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='Rugosidad de Manning en el canal, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="Fracción de qt que fluye por los poros de la roca. El resto qs fluye por la superficie. np por defecto = 0,45 para roca triturada angular.">Velocidad a través del manto de roca, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='Caudal unitario a través del manto, q<sub>m</sub>';
$ec_lang['rc_qs']='Caudal unitario superficial, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Tirante sobre la superficie de escollera, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="El remanso (Hp > yn) es favorable — reduce la erosión aguas arriba. (USDA)">Carga en el vertedor de entrada, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='Verificación de remanso en entrada';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — remanso aguas arriba';
$ec_lang['rc_pond_ok_tip']='El remanso aguas arriba de la entrada del canal es favorable; reduce la erosión aguas arriba. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — sin remanso — riesgo de erosión en la entrada';
$ec_lang['rc_pond_warn_tip']='No hay remanso aguas arriba de la entrada del canal; podría producirse erosión aguas arriba. (USDA)';
$ec_lang['rc_eq1']='Ec. 1 (S<sub>0</sub> < 0,10) — pendiente suave';
$ec_lang['rc_eq2']='Ec. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — pendiente pronunciada';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — por debajo del rango de validación Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — por encima del rango de validación Robinson';
$ec_lang['rc_notes_1_term']='Ecuaciones de dimensionamiento de roca';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) desarrollaron dos ecuaciones empíricas para el tamaño mediano de escollera D<sub>50</sub> en función de la pendiente del canal y el caudal unitario. La ecuación 1 se aplica a pendientes suaves (S<sub>0</sub> < 0,10); la ecuación 2 a pendientes pronunciadas (0,10 ≤ S<sub>0</sub> ≤ 0,40). Ambas ecuaciones requieren q<sub>t</sub> en m²/s y devuelven D<sub>50</sub> en mm. El rango validado es 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Caudal unitario';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> es el caudal unitario total en la cresta del canal (caudal total por unidad de ancho). Para un canal de ancho de plantilla B con caudal total Q, q<sub>t</sub> ≈ Q / B, o se calcula a partir de la condición de tirante crítico en la entrada del canal.';
$ec_lang['rc_notes_3_term']='Flujo a través del manto de roca';
$ec_lang['rc_notes_3_def']='Una fracción del caudal total fluye por los poros de la escollera (caudal de manto q<sub>m</sub>); el resto fluye por la superficie de la roca (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). El tirante d se calcula con la ecuación de Manning aplicada al caudal superficial q<sub>s</sub> usando la rugosidad n del canal. La porosidad por defecto n<sub>p</sub> = 0,45 es típica para roca triturada angular.';
$ec_lang['rc_notes_5_term']='Rango válido de tamaño de roca';
$ec_lang['rc_notes_5_def']='Las ecuaciones fueron desarrolladas usando un rango de D<sub>50</sub> de 15 mm a 278 mm. Los resultados fuera de este rango son extrapolados y deben usarse con juicio de ingeniería adicional.';
$ec_lang['rc_notes_6_term']='Cota del zampeado de salida';
$ec_lang['rc_notes_6_def']='La cota de la parte superior de la escollera en el tramo de salida debe estar a la misma cota o por debajo de la plantilla del canal aguas abajo. Si es más alta, la roca de salida será inestable.';
$ec_lang['rc_notes_7_def']='Cuando el tirante normal en el canal de entrada es menor que la carga en el vertedor (H<sub>p</sub>) requerida para pasar q<sub>t</sub>, ocurre flujo restringido o remanso aguas arriba de la entrada del canal. Esto es generalmente aceptable — el remanso reduce la velocidad y evita la erosión aguas arriba. Para verificarlo: use una calculadora de flujo de vertedor para hallar H<sub>p</sub> para el q<sub>t</sub> y ancho de cresta dados, y compárelo con el tirante normal del canal de entrada. Si H<sub>p</sub> supera el tirante normal, se producirá remanso.';
$ec_lang['rc_notes_4_term']='Referencia';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., y Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. El USDA ARS también publica una <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">hoja de cálculo Excel</a> basada en el mismo método.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtro';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curva de cresta';
$ec_lang['rc_sketch_outlet_apron']    = 'Zampeado de salida';
$ec_lang['rc_sketch_radius']          = 'radio';
// Irrigation Pressure Calculator (branch pipe-network pressure/DU estimate). Prefix ip_.
$ec_lang['ip_main_menu']='Presión en Riego';
$ec_lang['ip_main_title']='Calculadora Gratuita en Línea de Presión en Riego y Uniformidad de Distribución';
$ec_lang['ip_main_desc']='Presión de Rama de Prueba y Estimación de Uniformidad';
$ec_lang['ip_h_supply']='Presión de suministro';
$ec_lang['ip_elev_supply']='Elevación de suministro, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Caudal de diseño del emisor, q<sub>design</sub>';
$ec_lang['ip_h_design']='Presión de diseño del emisor';
$ec_lang['ip_x']='<span class="ec-help" title="0,5 para emisores estándar sin compensación; cercano a 0 para emisores con compensación de presión">Exponente de descarga del emisor, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Ruta de prueba';
$ec_lang['ip_group_reach']='Tramo';
$ec_lang['ip_group_upstream']='Aguas arriba';
$ec_lang['ip_group_downstream']='Aguas abajo';
$ec_lang['ip_group_loss']='Pérdida';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="Marcada: este tramo es un segmento de la lateral de prueba, extraído por emisores individuales. Sin marcar: este tramo es una tubería principal, solo pasando caudal a laterales no en la ruta de prueba.">Lat. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Filas de laterales: emisores en este tramo solo. Filas de tubería principal: total de emisores en laterales OTROS que este que se ramifican desde este tramo. Para el tramo justo en el punto de extracción de la lateral de prueba, esto también incluye cualquier lateral más abajo en la tubería principal más allá de ese punto, o compartiendo la misma unión (p. ej., una lateral del lado opuesto) — su caudal se ramifica desde este mismo tramo también.">Emisores <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Elevación aguas abajo del tramo. Opcional en filas interiores (por defecto plano / igual que el nodo anterior si se deja en blanco). Requerido en la última fila: ese valor es la elevación del último emisor, que directamente establece la presión de suministro requerida.">Elev. abajo <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='Elevación del último emisor (última fila) se dejó en blanco y se asumió como plana — ingrese su valor para un resultado preciso';
$ec_lang['ip_flow']='Caudal';
$ec_lang['ip_press']='Pres.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Pérdida total del tramo, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Presión baja/negativa — verificar condiciones subatmosféricas';
$ec_lang['ip_pressure_warn_short']='Baja';
$ec_lang['ip_pressure_high']='Los puntos de presión alta necesitan reducción de presión';
$ec_lang['ip_pressure_high_short']='Alta';
$ec_lang['ip_max_head']='Presión máx. adm. tubería';
$ec_lang['ip_max_head_tip']='Se marcan los tramos cuya presión supere este valor. Déjelo en blanco para omitir la verificación de alta presión.';
$ec_lang['ip_h_far']='Presión del último emisor';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Caudal que ingresa a la ruta de prueba modelada solo, no a toda la zona/sistema — ver Q_zone en Diseño de Aplicación abajo para el total del sistema.">Caudal de suministro de ruta de prueba, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Caudal del último emisor, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Caudal promedio del emisor (lateral de prueba), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Cuánto más alto (o más bajo) cree que funciona una lateral típica/promedio en comparación con esta lateral de prueba. La lateral de prueba es deliberadamente el caso presumido peor, por lo que su promedio es un sustituto sesgado a la baja para un promedio de campo — dejado en 0, la verificación de uniformidad y los números de diseño de aplicación abajo usan el de la lateral de prueba propio (probablemente optimista) tal cual.">Est. Diferencia de presión, prom. vs. lateral de prueba <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral reevaluado a la presión de cada fila lateral más la diferencia de presión ingresada arriba — un intento de corregir el hecho de que la lateral de prueba sea el caso presumido peor, no uno representativo. Alimenta tanto la verificación de uniformidad como la sección de diseño de aplicación abajo.">Caudal promedio de emisor estimado de campo, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Caudal calculado del último emisor dividido entre el caudal promedio estimado de emisor de campo — esto es una aproximación de la Uniformidad de Distribución del cuarto inferior estándar (promedio del grupo inferior ÷ media poblacional); proviene de una muestra pequeña modelada y una corrección estimada por el usuario, en lugar de una muestra estadística de campo completo. Los valores en o por encima de 1 son posibles y válidos: solo significan que la presión del último emisor está en o por encima del promedio de campo estimado, por lo que algún otro emisor es el punto de menor presión. Esto podría deberse a que el último emisor está en terreno bajo o a que la estimación de Δpresión es demasiado pequeña.">Verificación de uniformidad, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='Presión en el emisor de prueba ≥ presión de suministro. Es probable que este no sea el emisor de peor caso, o que las tuberías podrían ser de menor tamaño.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Esto es diferente de nuestra aproximación de la medida de uniformidad estándar.">Caudal del último emisor ÷ caudal de diseño, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Sin solución: la presión de suministro requerida excede la presión de suministro ingresada. Aumente la presión de suministro, reduzca la demanda, o use una tubería más grande.';
$ec_lang['ip_notes_1_def']='Adivina la presión en el último emisor (más remoto), luego recorre la Línea de Grado de Energía hacia el suministro, tramo a tramo, agregando pérdidas por fricción y pérdidas menores en el camino. La elevación y energía cinética se retiran en cada nodo para reportar la presión real ahí. La presión adivinada en el extremo lejano se ajusta (bisección) hasta que la presión de suministro requerida computada coincida con la presión de suministro ingresada — el mismo problema de lazo cerrado que soluciona el resolvedor de flujo de tuberías en la calculadora Manning Pipe Flow, extendido a una red ramificada.';
$ec_lang['ip_notes_2_term']='Tramos de Tubería Principal vs. Lateral';
$ec_lang['ip_notes_2_def']='Cada fila es un tramo en la única ruta hidráulicamente peor (la ruta de prueba) desde el suministro hasta el último emisor. Un tramo de tubería principal solo pasa caudal a laterales no en la ruta de prueba, por lo que su extracción es una multiplicación plana (caudal de diseño × el número total de emisores del tramo) — sin sensibilidad local de presión. La tubería principal es una tubería troncal compartida, por lo que el tramo justo en el punto de extracción de la propia lateral de prueba debe incluir no solo laterales entre sus propios puntos finales sino también cualquier lateral aún más abajo en la tubería principal más allá de ese punto, o compartiendo la misma unión (p. ej., una lateral del lado opuesto) — su caudal viaja a través de ese mismo tramo antes de dividirse, esté o no apareciendo en otro lugar en esta tabla. Un tramo de Lateral es un segmento de la propia lateral de prueba: la descarga del emisor se calcula a partir de la presión local real vía q = k·H<sup>x</sup>, y la pérdida por fricción se reduce por el factor F(n) de Christiansen para contabilizar el caudal disminuyendo conforme cada emisor en el tramo lo extrae.';
$ec_lang['ip_notes_3_term']='Limitaciones';
$ec_lang['ip_notes_3_def']='Modela una presión de suministro fija (sin curva de bomba), una sola ruta de prueba (no el campo completo), y una curva de emisor de 2 parámetros (establezca el exponente cerca de 0 para aproximar un emisor con compensación de presión). Se reportan dos ratios de uniformidad diferentes, mantenidos deliberadamente separados: q<sub>last</sub>/q<sub>avg,field</sub> es una aproximación de la Uniformidad de Distribución del cuarto inferior estándar (promedio del grupo inferior ÷ media poblacional); pero esto proviene de una muestra pequeña modelada y una corrección estimada por el usuario, en lugar de la muestra estadística de campo completo estándar. Además, la lateral de prueba es deliberadamente el caso peor presumido, por lo que su promedio crudo, sin corregir, subestimaría el verdadero promedio de campo y haría que la uniformidad pareciera mejor de lo que es; la entrada de Δpresión existe específicamente para contrarrestar ese sesgo. Los valores de uniformidad en o por encima de 1 aún son posibles: solo significan que la presión del último emisor está en o por encima del promedio de campo estimado, por lo que algún otro emisor es el punto de menor presión. Esto podría deberse a que el último emisor está en terreno bajo o a que la estimación de Δpresión es demasiado pequeña. q<sub>last</sub>/q<sub>design</sub> es una verificación diferente, no de uniformidad, contra el caudal nominal del fabricante — útil para detectar un sistema sobre- o subpresurizado en general, pero es una verificación separada que debe leerse junto con el número de uniformidad, ya que el caudal de diseño/nominal es independiente de la presión operativa media real del sistema.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). "Irrigation by sprinkling." California Agricultural Experiment Station Bulletin 670. Los estándares ASAE/ASABE para diseño de microrriego usan el mismo enfoque de pérdida de fricción multi-salida.';
$ec_lang['ip_notes_5_term']='Diseño de Aplicación';
$ec_lang['ip_notes_5_def']='Tasa de aplicación y caudal de sistema/zona usan el caudal promedio de emisor estimado de campo (q<sub>avg,field</sub> — el promedio de la propia lateral de prueba, corregido por la estimación de diferencia de presión ingresada), no un caudal adivinado: PR = q<sub>avg,field</sub> / A<sub>e</sub>, alimentado por el valor modelado corregido. El espaciado y los números de lateral/emisor de todo el sistema son entradas separadas aquí porque la ruta de prueba solo modela una rama peor caso, no cada lateral en el campo.';
$ec_lang['irr_card_pressure_head']='Presión en Riego y Uniformidad';
$ec_lang['irr_card_pressure_desc']='Modele el perfil de presión y caudal a lo largo de una rama tubería principal-lateral-emisor para estimar la uniformidad de distribución a partir de la presión real de la ruta de prueba, no solo una tasa de caudal del catálogo del emisor.';



// --- Branched Pipe Network (bpn_) --- English source ---
$ec_lang['bpn_main_menu']='Red de tuberías ramificada';
$ec_lang['bpn_main_title']='Calculadora gratuita en línea de presión para redes de tuberías ramificadas (sin bucles)';
$ec_lang['bpn_main_desc']='Caudal y presión en red de tuberías ramificada (en árbol)';
$ec_lang['lpn_main_menu']='Red de tuberías mallada (interfaz de mapa) — VERSIÓN PRELIMINAR';
$ec_lang['lpn_main_title']='VERSIÓN PRELIMINAR: Calculadora gratuita en línea de redes de tuberías malladas con interfaz de mapa';
$ec_lang['lpn_main_desc']='VERSIÓN PRELIMINAR — Presión y caudal en una red de tuberías mallada que usted dibuja en un mapa';
$ec_lang['bpn_h_source_tip']='Carga estática de suministro: la carga de la fuente con caudal cero. El nivel de agua de un embalse o tanque por encima de la elevación de suministro, o la carga a válvula cerrada de una bomba. Agregue los puntos de suministro 2 y 3 para definir una bomba o una curva de suministro variable; la herramienta lee la carga en el caudal de diseño.';
$ec_lang['bpn_elev_source']='Elevación de suministro';
$ec_lang['bpn_q_total']='Caudal total';
$ec_lang['bpn_q_total_tip']='Caudal total que sale de la fuente (la suma de todas las demandas de la red).';
$ec_lang['bpn_p_min']='Presión mínima';
$ec_lang['bpn_p_min_tip']='La presión aguas abajo más baja en cualquier punto de la red; el punto crítico de entrega.';
$ec_lang['bpn_method']='Método de fricción';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='Tramos de tubería';
$ec_lang['bpn_id']='ID';
$ec_lang['bpn_id_tip']='Nombre de este tramo de tubería. Otros tramos lo referencian en la columna Aguas arriba.';
$ec_lang['bpn_upstream']='ID aguas arriba';
$ec_lang['bpn_upstream_tip']='ID del tramo que alimenta a este. Déjelo en blanco para seguir el tramo directamente anterior (una tubería en serie simple). Ingrese un ID aquí para ramificarse desde otro tramo.';
$ec_lang['bpn_roughness_tip']='Rugosidad de la tubería para el método de fricción seleccionado: n de Manning, C de Hazen-Williams, o altura de rugosidad e de Darcy-Weisbach (una longitud). Tubería de plástico lisa típica: n alrededor de 0,009, C alrededor de 150, e alrededor de 0,0015 mm.';
$ec_lang['bpn_demand']='Demanda';
$ec_lang['bpn_demand_tip']='Caudal fijo entregado en el extremo aguas abajo de este tramo. Déjelo en blanco para un tramo que solo transporta caudal hacia adelante.';
$ec_lang['bpn_demand_mult']='Multiplicador de demanda';
$ec_lang['bpn_demand_mult_tip']='Escala todas las demandas de los tramos a la vez, para un caso de hora pico o de crecimiento futuro. Use 1 para las demandas tal como se ingresaron.';
$ec_lang['bpn_elev_down']='Elev. AA';
$ec_lang['bpn_q_line']='Caudal del tramo';
$ec_lang['bpn_q_line_tip']='Caudal total transportado por este tramo: su propia demanda más toda demanda aguas abajo que alimenta.';
$ec_lang['bpn_p_down']='Pres. AA';
$ec_lang['bpn_p_down_tip']='Carga de presión manométrica en el nodo aguas abajo de este tramo. Un valor negativo (marcado) indica presión subatmosférica; revise el diseño.';
$ec_lang['bpn_sketch_title']='Diagrama de la red';
$ec_lang['bpn_show_length']='Longitud';
$ec_lang['bpn_show_diameter']='Diámetro';
$ec_lang['bpn_show_q']='Caudal';
$ec_lang['bpn_show_p']='Presión';
$ec_lang['bpn_source_label']='Fuente';
$ec_lang['bpn_topology_warn']='Revise la columna Aguas arriba: un tramo apunta a un ID desconocido, se referencia a sí mismo, o forma un bucle, por lo que parte de la red no está conectada a la fuente. Esos tramos quedan sin resolver.';
$ec_lang['bpn_topology_warn_short']='Red';
$ec_lang['bpn_pressure_warn']='Presión baja o negativa; revise si hay condiciones subatmosféricas';
$ec_lang['bpn_pressure_warn_short']='Baja';
$ec_lang['bpn_notes_1_term']='En serie por defecto, ramificada por excepción';
$ec_lang['bpn_notes_1_def']='Deje el ID aguas arriba en blanco y un tramo sigue al de arriba; una tubería en serie simple. Ingrese el ID de un tramo aguas arriba para ramificarse desde él. Así: en serie por defecto, un árbol cuando lo necesite.';
$ec_lang['bpn_notes_2_term']='Solo redes ramificadas, sin bucles';
$ec_lang['bpn_notes_2_def']='Cada tramo tiene exactamente un tramo aguas arriba (un árbol). Esta herramienta no resuelve redes con bucles; esas necesitan métodos iterativos (EPANET o similar). Excluir los bucles es lo que la mantiene simple y exacta.';
$ec_lang['bpn_notes_3_term']='Sin controles de presión activos';
$ec_lang['bpn_notes_3_def']='Puede agregar una válvula de pérdida localizada fija (un valor k), pero no válvulas reductoras o sostenedoras de presión (PRV/PSV). Su estado abierto/cerrado depende del caudal y la presión, lo que forzaría la iteración.';
$ec_lang['bpn_notes_epanet_term']='Las constantes de Hazen-Williams ahora coinciden con EPANET (agosto de 2026)';
$ec_lang['bpn_notes_epanet_def']='En agosto de 2026 se cambiaron el coeficiente y el exponente de Hazen-Williams para coincidir con EPANET. Los resultados de pérdida de carga difieren de los de las versiones anteriores de esta página hasta en un 0,1 por ciento, mucho menos que la incertidumbre del propio valor de C.';
$ec_lang['bpn_supply2_q']='Caudal de suministro 2';
$ec_lang['bpn_supply2_h']='Carga de suministro 2';
$ec_lang['bpn_supply3_q']='Caudal de suministro 3';
$ec_lang['bpn_supply3_h']='Carga de suministro 3';
$ec_lang['bpn_supply_pt_tip']='Puntos opcionales 2 y 3 de la curva de suministro. Ingrese un caudal y una carga para cada uno para modelar una bomba, o cualquier fuente cuya carga disminuya al entregar más caudal; la herramienta lee la carga en el caudal de diseño. El punto 1 arriba es la carga estática con caudal cero. Deje 2 y 3 en blanco para una carga de embalse constante.';
$ec_lang['bpn_h_supply']='Carga de suministro';
$ec_lang['bpn_h_supply_tip']='Carga de la fuente en el caudal de diseño, leída de la curva de suministro. Es igual a la carga de fuente ingresada cuando la curva es plana (un embalse).';
$ec_lang['bpn_show_elevation']='Elevación';
$ec_lang['bpn_supply1_h']='Carga estática de suministro';
