<?php

// äöüÄÖÜß — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="Anteil";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft WS";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% Gefälle";
$ec_lang['u_grade']="Gefälle";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in WS";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m WS";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm WS";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/ft^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="s";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Rechner';
$ec_lang['menu_main_list']='Rechnerliste';
$ec_lang['menu_main_hydraulics']='Hydraulik';
$ec_lang['menu_main_language']='Sprache';
$ec_lang['menu_more']='Mehr';
$ec_lang['template_welcome']='>> Lasst Eure Ängste an der Tür; hier wird Liebe gesprochen. Ihr ruiniert nicht alles. Genießt auch die <a target="_blank" href="https://hawsedc.com/download.php">kostenlosen HawsEDC AutoCAD-Tools.</a> <<';
$ec_lang['template_translation_help']='Haben Sie eine großartige Idee für einen Rechner, der hier hinzugefügt werden soll?  Können Sie mir helfen, Übersetzungen zu verbessern, zu programmieren oder diese Rechner zu hosten?  ';
$ec_lang['template_feedback']='Bitte teilen Sie uns Ihre wertvollen Anmerkungen oder Ihr Lob mit. Hat dieser kostenlose Rechner Ihre Erwartungen übertroffen?';
$ec_lang['template_printable_title']='Druckbarer Titel';
$ec_lang['template_printable_subtitle']='Druckbarer Untertitel';
$ec_lang['index_title']='Kostenlose Ingenieurrechner online';
$ec_lang['calc_set_units']='Einheiten festlegen:';
$ec_lang['points_data_help']='(oder Kopieren/Einfügen im Datenbereich)';
$ec_lang['points_data_title']='Punktdaten<br />(durch Komma oder Tabulator getrennt)';
$ec_lang['points_data_copy']='Kopieren';
$ec_lang['points_data_paste']='Einfügen';
$ec_lang['calc_inputs']='Eingaben';
$ec_lang['calc_results']='Ergebnisse';
$ec_lang['view_hide_line']='[Diese Zeile ausblenden]';
$ec_lang['view_printable']='Druckversion (Seite neu laden zum Zurücksetzen)';
$ec_lang['ec_name_label']='Diese Berechnung speichern:';
$ec_lang['ec_name_placeholder']='Name';
$ec_lang['ec_name_hint']='Speichert diese Eingaben in der URL zum Lesezeichen, zum Abrufen aus dem Verlauf und zum Teilen';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Rohrreibungsverlust Darcy-Weisbach';
$ec_lang['dw_main_title']='Kostenloser Online-Rechner Rohrreibungsverlust Darcy-Weisbach';
$ec_lang['dw_main_desc']='Rohrreibungsverlust nach Darcy-Weisbach bei gegebenem Durchmesser, Rauheit und Durchfluss';
$ec_lang['dw_roughness']='Absolute Rauheit Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Kinematische Viskosität, ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Reynolds-Zahl, Re';
$ec_lang['dw_flow_regime']='Strömungsregime';
$ec_lang['dw_regime_laminar']='laminare Strömung';
$ec_lang['dw_regime_transitional']='Übergangsbereich';
$ec_lang['dw_regime_turbulent']='turbulente Strömung';
$ec_lang['dw_friction_factor_method']='Methode des Reibungsbeiwerts';
$ec_lang['dw_friction_factor']='Reibungsbeiwert, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Rohrreibungsverlust Hazen-Williams';
$ec_lang['hw_main_title']='Kostenloser Online-Rechner Rohrreibungsverlust Hazen-Williams';
$ec_lang['hw_main_desc']='Rohrreibungsverlust nach Hazen-Williams bei gegebenem Durchmesser, Rauheit und Durchfluss';
$ec_lang['hw_hgl_1']='HGL flussabwärts';
$ec_lang['hw_hgl_2']='HGL flussaufwärts';
$ec_lang['hw_roughness']='Hazen-Williams-Koeffizient, C';
// Manning Irregular
$ec_lang['mi_menu']='Unregelmäßiges Profil Manning';
$ec_lang['mi_main_title']='Kostenloser Online-Rechner unregelmäßiges Gerinne Manning';
$ec_lang['mi_main_desc']='Gleichförmiger Abflussrechner für unregelmäßige Gerinne nach Manning';
$ec_lang['mi_waterSurfaceElevation']='Wasserstand';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Querschnittpunkte';
$ec_lang['mi_groupPoint']='Punkt';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Bereich';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Höhe';
$ec_lang['mi_d50in']='Mittlere<br />Korn-<br />größe<br />Deckwerk';
$ec_lang['mi_n']='n<br />Seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />Bereich-<br />grenze<br />(Ufer)';
$ec_lang['mi_tau']='Sohl-<br />schub-<br />spg. τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Zus.-<br />ges. n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Hinweise';
$ec_lang['mi_notes_1_term']='Zusammengesetztes n';
$ec_lang['mi_notes_1_def']='Dieser Rechner folgt dem HEC-RAS-Referenzhandbuch bei der Berechnung des zusammengesetzten n des Bereichs nach Chow 1959, Seite 136, Gleichung 6-17 (nicht 6-18).';
$ec_lang['mi_notes_2_term']='Steindeckwerk';
$ec_lang['mi_notes_2_def']='Verwenden Sie den Manning-Trapezkanal-Rechner für das Steindeckwerk-Design. Dieser Rechner eignet sich besser für natürliche Querschnitte.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Rohrdurchfluss Manning';
$ec_lang['mpf_main_title']='Kostenloser Online-Rechner Rohrdurchfluss Manning';
$ec_lang['mpf_main_desc']='Manning-Formel für gleichförmigen Rohrdurchfluss bei gegebenem Gefälle und Füllhöhe';
$ec_lang['mpf_spreadheet_notice']='Entdecken Sie die Tabellenversion dieses Rechners';
$ec_lang['mpf_pipe_diameter']='Rohrdurchmesser, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning-Rauheitsbeiwert, n';
$ec_lang['mpf_friction_slope']='Druckliniengefälle (möglicherweise <a target="_blank" href="../pressureslope.php">?</a> gleich Rohrgefälle), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Relative Füllhöhe, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Siehe Hinweise)';
$ec_lang['mpf_flow']='Durchfluss, Q';
$ec_lang['mpf_velocity']='Fließgeschwindigkeit, v';
$ec_lang['mpf_velocity_head']='Geschwindigkeitshöhe, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Durchflossene Fläche, a';
$ec_lang['mpf_pipe_area']='Rohrquerschnitt, a0';
$ec_lang['mpf_area_ratio']='Relative Fläche, a/a0';
$ec_lang['mpf_wetted_perimeter']='Benetzter Umfang, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Hydraulischer Radius, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Wasserspiegelbreite, T';
$ec_lang['mpf_froude_number']='Froude-Zahl, F';
$ec_lang['mpf_shear_stress']='Mittlere Sohlschubspannung (Schleppkraft), tau';
$ec_lang['mpf_full_flow']='Vollfüllung, Q0';
$ec_lang['mpf_full_flow_ratio']='Füllungsverhältnis, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Dies ist der Durchfluss und die Tiefe innerhalb eines <em>unendlich langen</em> Rohres.</dt><dd>Um den Durchfluss in das Rohr zu leiten, kann eine erheblich höhere Einstauhöhe erforderlich sein. Addieren Sie mindestens das 1,5-fache der Geschwindigkeitshöhe zur Einstauhöhe oder <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">sehen Sie das 2-Minuten-Tutorial</a> für Standard-Durchlassberechnungen mit HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='y/d<sub>0</sub> für gegebenes Q berechnen';
$ec_lang['mpf_solve_desc']='Mit D<sub>0</sub>, n und S<sub>0</sub> aus dem Formular wird das kleinste y/d<sub>0</sub> für ein gegebenes Q gefunden.';
$ec_lang['mpf_solve_button']='Berechnen';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Rohrdruckverlust Manning';
$ec_lang['mphl_main_title']='Kostenloser Online-Rechner Rohrdruckverlust Manning';
$ec_lang['mphl_main_desc']='Manning-Formel Druckverlust bei gegebenem Vollfüllungsdurchfluss';
$ec_lang['mphl_pipe_length']='Rohrlänge, L';
$ec_lang['mphl_area']='Fläche, A';
$ec_lang['mphl_total_junction_k']='Gesamter kombinierter Verlustbeiwert an Einbauten, k';
$ec_lang['mphl_friction_slope']='Reibungsgefälle';
$ec_lang['mphl_friction_loss']='Reibungsverlust, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Einbauverlust, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Gesamtverlust, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL flussabwärts';
$ec_lang['mphl_egl_2']='EGL flussaufwärts';
$ec_lang['mphl_hgl_2']='HGL im Rohr flussaufwärts ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Für einen offenen Einlauf (Durchlass) müssen die Einlaufsteuerungsbedingungen geprüft werden.</dt><dd>1. Die HGL flussaufwärts kann nicht unter der normalen Fließtiefe flussaufwärts liegen (oder unter dem Rohr!).</dd><dd>2. Der Einstaupegel eines Durchlasses wird besser durch die EGL als durch die HGL flussaufwärts dargestellt.</dd><dd>3. Sehen Sie <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">das 2-Minuten-Tutorial</a> für einfache Standard-Durchlassberechnungen mit HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Trapezprofil-Kanal Manning';
$ec_lang['mtc_main_title']='Kostenloser Online-Rechner Trapezkanal Manning-Formel';
$ec_lang['mtc_main_desc']='Manning-Formel gleichförmiger Abfluss im Trapezkanal bei gegebenem Gefälle und Tiefe';
$ec_lang['mtc_bottom_width']='Sohlbreite, b';
$ec_lang['mtc_side_slope_1']='Böschung 1 (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Böschung 2 (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Kanalgefälle, S';
$ec_lang['mtc_flow_depth']='Fließtiefe, y';
$ec_lang['mtc_bend_angle']='Kurvenwinkel <a target="_blank" href="riprap-bend-angle.png" title="Klicken für Bild">?</a> (für Deckwerksbemessung)';
$ec_lang['mtc_sgrock']='Rohdichte des Steins (2,65)';
$ec_lang['mtc_d50_in']='Bemessungskorngröße, D50';
$ec_lang['mtc_n_strickler']='n für Bemessungskorngröße nach Strickler';
$ec_lang['mtc_n_blodgett']='n für Bemessungskorngröße nach Blodgett';
$ec_lang['mtc_n_bathurst']='n für Bemessungskorngröße nach Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Erforderliche Körnung kantenreicher Steine Sohle, D50 (Isbash & MC) <span title="Nach Isbash (1936) und Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Erforderliche Körnung kantenreicher Steine Böschung 1, D50 (Isbash & MC) <span title="Nach Isbash (1936) und Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Erforderliche Körnung kantenreicher Steine Böschung 2, D50 (Isbash & MC) <span title="Nach Isbash (1936) und Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Erforderliche Körnung kantenreicher Steine, D50 (Maynord, Ruff und Abt 1989)';
$ec_lang['mtc_d50_searcy']='Erforderliche Körnung kantenreicher Steine, D50 (Searcy 1967)';
$ec_lang['mtc_vel_check']='Geschwindigkeitsprüfung';
$ec_lang['mtc_vel_ok']='Geschwindigkeit plausibel für Gleichströmungsannahmen.';
$ec_lang['mtc_vel_high']='Geschwindigkeit hoch – Übergangsverluste und verfügbare Energie prüfen.';
$ec_lang['mtc_vel_low']='Geschwindigkeit niedrig – Sedimentationsrisiko.';
$ec_lang['mtc_vel_ok_short']='OK';
$ec_lang['mtc_vel_high_short']='Hoch';
$ec_lang['mtc_vel_low_short']='Niedrig';
$ec_lang['mtc_note_1']='<dl><dt>Automatische Iteration Steinbemessung und Rauheit</dt><dd>Wählen Sie einen Rauheits-Radioknopf (BB empfohlen) und einen Radioknopf für die Bemessungskorngröße (Isbash empfohlen). Stellen Sie Tiefe und Steinbemessungsfaktor ein, um den gewünschten Durchfluss mit einer gleichmäßigen Korngröße zu erzielen. Bei jeder Änderung eines Eingabewerts startet der Iterationszyklus: 1. Die Rauheit wird aus der Bemessungskorngröße berechnet. 2. Der berechnete Rauheitswert wird in die Eingaberauheit kopiert. 3. Kanaldurchfluss und erforderliche Korngröße werden berechnet. 4. Die Bemessungskorngröße wird angepasst. 5. Wiederholen bis der Fehler sehr klein ist.</dd><dt>Grundrechner (ohne Iteration)</dt><dd>Geben Sie den gewünschten Rauheitswert ein. Ignorieren Sie den Eingabebereich für die Bemessungskorngröße.</dd></dl>';
$ec_lang['mtc_note_2_term']='Geschwindigkeitsprüfung';
$ec_lang['mtc_note_2_def']='Hohe Geschwindigkeit impliziert hohe spezifische Energie aus einem verfügbaren Absturz. Diese Energie kann schnell an Aufweitungen, Bögen oder Hindernissen abgebaut werden. Prüfen Sie, ob dies für den Standort plausibel ist.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Einfaches Wehr';
$ec_lang['ws_main_title']='Kostenloser Online-Rechner breitkroniges Wehr';
$ec_lang['ws_main_desc']='Rechner für den Durchfluss über ein einfaches breitkroniges Wehr';
$ec_lang['ws_weirLength']='Wehrlänge, l';
$ec_lang['ws_headWaterHeight']='Oberwasserhöhe, h';
$ec_lang['ws_weirCoefficient']='Wehrbeiwert, Cw';
$ec_lang['ws_notes_heading']='Hinweise';
$ec_lang['ws_notes_we_term']='Wehrformel';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Unregelmäßiges Wehr';
$ec_lang['wi_main_title']='Kostenloser Online-Rechner segmentiertes Wehr mit variablem Querschnitt';
$ec_lang['wi_main_desc']='Rechner für den Durchfluss über ein unregelmäßiges Wehr';
$ec_lang['wi_headWaterelevation']='Oberwasserstand';
$ec_lang['wi_weirPoints']='Wehrpunkte';
$ec_lang['wi_station']='Station';
$ec_lang['wi_elevation']='Höhe';
$ec_lang['wi_pondingHeight']='Stautiefe';
$ec_lang['wi_incrementalFlow']='Teilabfluss';
$ec_lang['wi_cumulativeFlow']='Kumulierter Abfluss';
$ec_lang['wi_save_and_calculate']='Speichern und berechnen';
$ec_lang['wi_notes_we_term']='Wehrformel';
$ec_lang['wi_notes_we_def']='q = wenn (Länge = 0) dann 0, wenn (Gefälle=0) dann cw*Länge*d<sub>0</sub><sup>1.5</sup>, sonst cw/(2.5*Gefälle) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) wobei d<sub>1</sub> und d<sub>0</sub> immer positiv oder null sind';
// Orifice Flow
$ec_lang['or_main_menu']='Ausfluss durch Öffnung';
$ec_lang['or_main_title']='Kostenloser Online-Rechner Ausfluss durch Öffnung';
$ec_lang['or_main_desc']='Ausfluss durch Öffnung — frei oder eingestaut';
$ec_lang['or_shape']='Form der Öffnung';
$ec_lang['or_shape_circular']='Kreisförmig';
$ec_lang['or_shape_rectangular']='Rechteckig';
$ec_lang['or_diameter']='Durchmesser oder Höhe, D <span title="Durchmesser für kreisförmig; Höhe für rechteckig" class="ec-tip">?</span>';
$ec_lang['or_width']='Breite, W <span title="Nur für rechteckige Öffnungen" class="ec-tip">?</span>';
$ec_lang['or_invert']='Sohlhöhe <span title="Unterkante der Öffnung" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Oberwasserstand';
$ec_lang['or_twe']='Unterwasserstand';
$ec_lang['or_cd']='Abflussbeiwert, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Schwerpunkthöhe';
$ec_lang['or_head']='Wirksame Druckhöhe, h';
$ec_lang['or_area']='Querschnittsfläche der Öffnung, A';
$ec_lang['or_flow']='Durchfluss, Q';
$ec_lang['or_velocity']='Geschwindigkeit, v';
$ec_lang['or_regime']='Abflussregimeprüfung';
$ec_lang['or_regime_valid']='Freier Ausfluss — Öffnungsregime gültig ✓';
$ec_lang['or_regime_submerged']='Eingestaute Öffnung (TWE über Schwerpunkt) — gültig ✓';
$ec_lang['or_regime_warn']='Warnung: Oberwasser unter Scheitel — kein Öffnungsregime';
$ec_lang['or_regime_twe_above_hwe']='Warnung: Unterwasser (TWE) über Oberwasser (HWE) — Eingaben prüfen';
$ec_lang['or_notes_1_term']='Ausflusformel';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Freier Ausfluss: h = HWE − Schwerpunkt. Eingestaut (TWE über Sohle): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Abflussregime';
$ec_lang['or_notes_2_def']='Die Ausflusformeln gelten, wenn der Oberwasserspiegel über dem Scheitel der Öffnung liegt. Liegt er darunter, ist eine Wehrformel zu verwenden.';
$ec_lang['or_notes_3_term']='Abflussbeiwert';
$ec_lang['or_notes_3_def']='C<sub>d</sub> liegt bei ca. 0,60–0,65 für scharfkantige Öffnungen. Abgerundete oder einspringende Einläufe haben andere Werte. Siehe <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> oder das HEC-RAS Hydraulic Reference Manual.';
$ec_lang['or_notes_4_term']='Rückstau';
$ec_lang['or_notes_4_def']='Wenn TWE über der Sohle der Öffnung liegt, verwendet der Rechner automatisch die eingestaute Ausflusformel mit h = HWE − TWE. Liegt TWE auf oder unter der Sohle, wird freier Ausfluss angenommen und h = HWE − Schwerpunkt.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Mikro-Wasserkraft';
$ec_lang['mhp_main_title']='Kostenloser Online-Rechner für Mikro-Wasserkraft';
$ec_lang['mhp_main_desc']='Leistungsrechner für Laufwasser-Mikro-Wasserkraftanlagen';
$ec_lang['mhp_flow']='Durchfluss, Q';
$ec_lang['mhp_gross_head']='Bruttofallhöhe, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Rohrdurchmesser der Druckrohrleitung, D';
$ec_lang['mhp_length']='Rohrlänge der Druckrohrleitung, L';
$ec_lang['mhp_roughness']='Rohrrauheit, e';
$ec_lang['mhp_km']='Einzelwiderstandsbeiwert, k<sub>m</sub>';
$ec_lang['mhp_nu']='Kinematische Viskosität, ν, in m<sup>2</sup>/s (1E-6 für Wasser nahe 20°C)';
$ec_lang['mhp_efficiency']='Anlagenwirkungsgrad, η (0–1)';
$ec_lang['mhp_velocity']='Fließgeschwindigkeit, v';
$ec_lang['mhp_vel_check']='Geschwindigkeitsprüfung';
$ec_lang['mhp_f']='Reibungsbeiwert, f';
$ec_lang['mhp_hf']='Reibungsdruckverlust, h<sub>f</sub>';
$ec_lang['mhp_hm']='Einzeldruckverlust, h<sub>m</sub>';
$ec_lang['mhp_hl']='Gesamtverlust der Druckrohrleitung, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Druckverlustprüfung';
$ec_lang['mhp_hnet']='Nettofallhöhe, H<sub>net</sub>';
$ec_lang['mhp_power']='Leistungsabgabe, P';
$ec_lang['mhp_annual_kwh']='Jahresenergie bei 100 % Kapazität';
$ec_lang['mhp_vel_ok']='1–3 m/s — im Zielbereich ✓';
$ec_lang['mhp_vel_low']='Geschwindigkeit niedrig – Risiko von Sedimentation und Lufteintrag.';
$ec_lang['mhp_vel_high']='Geschwindigkeit hoch – Risiko von Druckstoß und Einzelverlusten.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Hoch';
$ec_lang['mhp_vel_low_short']='Niedrig';
$ec_lang['mhp_hl_ok']='innerhalb des 10-%-Ziels ✓';
$ec_lang['mhp_hl_warn']='überschreitet 10-%-Ziel — größeres Rohr erwägen ⚠';
$ec_lang['mhp_hl_bad']='überschreitet 20 % — Rohr neu dimensionieren';
$ec_lang['mhp_notes_1_term']='Druckverlust';
$ec_lang['mhp_notes_1_def']='Gesamtverlust der Druckrohrleitung h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, wobei h<sub>f</sub> = f(L/D)(v²/2g) der Darcy-Weisbach-Reibungsverlust ist und h<sub>m</sub> = k<sub>m</sub>·v²/2g Einläufe, Krümmer und Armaturen berücksichtigt. Nettofallhöhe H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Fließgeschwindigkeit';
$ec_lang['mhp_notes_2_def']='Zielbereich: 1–3 m/s. Unter 1 m/s ist das Rohr für den Durchfluss überdimensioniert; über 3 m/s steigen die Reibungsverluste und das Risiko eines Wasserschlags.';
$ec_lang['mhp_notes_3_term']='Druckverlustziel';
$ec_lang['mhp_notes_3_def']='Verluste in der Druckrohrleitung unter 10 % der Bruttofallhöhe sind in der Regel wirtschaftlich. Der optimale Kompromiss zwischen Rohrkosten und Leistungsverlust liegt für wertvolle Stromerzeugungs-Standorte oft bei 4–6 %.';
$ec_lang['mhp_notes_4_term']='Einzelwiderstände k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Typische Werte: scharfkantige Einlauföffnung 0,5, jeder 45°-Krümmer 0,2–0,3, Schieber (vollständig geöffnet) 0,1, Schmetterlingsklappe 0,2. Alle Einbauten summieren für den Gesamt-k<sub>m</sub>. Standardwert 1,5 geht von einem Einlauf und zwei Krümmern aus.';
$ec_lang['mhp_notes_5_term']='Rohrrauheit e';
$ec_lang['mhp_notes_5_def']='Typische absolute Rauheit: Stahl (neu) 0,046 mm, Stahl (gebraucht) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, Beton 0,3–3 mm. HDPE ist bei kleinen Mikro-Wasserkraft-Druckrohrleitungen weit verbreitet.';
$ec_lang['mhp_notes_6_term']='Wirkungsgrad';
$ec_lang['mhp_notes_6_def']='Der typische Anlagenwirkungsgrad &eta; liegt für Pelton- und Durchströmturbinen, die in der Mikro-Wasserkraft verbreitet sind, zwischen 0,70 und 0,85. Als konservativen Anfangswert 0,75 verwenden.';
$ec_lang['mhp_notes_7_term']='Jahresenergie';
$ec_lang['mhp_notes_7_def']='Die Jahresenergie setzt einen kontinuierlichen Vollbetrieb voraus (8760 Stunden/Jahr). Die tatsächliche Produktion ist aufgrund saisonaler Durchflussschwankungen, Wartungsausfallzeiten und des Lastfaktors geringer.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Entleerungszeit durch Öffnung';
$ec_lang['odt_main_title']='Kostenloser Online-Rechner Entleerungszeit durch Öffnung';
$ec_lang['odt_main_desc']='Entleerungszeit eines Teichs durch Öffnung — Kegelvolumenmethode';
$ec_lang['odt_h1_elev']='Anfangswasserspiegelhöhe';
$ec_lang['odt_a1']='Anfangsteichfläche, A1';
$ec_lang['odt_h2_elev']='Endwasserspiegelhöhe';
$ec_lang['odt_h_orifice']='Schwerpunkthöhe der Öffnung';
$ec_lang['odt_a0']='Teichfläche auf Öffnungshöhe, A0';
$ec_lang['odt_a_ending']='Endteichfläche, A2 (interpoliert)';
$ec_lang['odt_h2_check']='Prüfung der Endhöhe';
$ec_lang['odt_h2_ok']='Endhöhe über Öffnungsscheitel ✓';
$ec_lang['odt_h2_warn']='Warnung: Endhöhe auf oder unter Öffnungsscheitel (Schwerpunkt + D/2)';
$ec_lang['odt_d']='Öffnungsdurchmesser (kreisförmig) oder Höhe (rechteckig), D';
$ec_lang['odt_w']='Öffnungsbreite, W (nur rechteckig)';
$ec_lang['odt_t_sec']='Entleerungszeit (Sekunden)';
$ec_lang['odt_t_min']='Entleerungszeit (Minuten)';
$ec_lang['odt_t_hr']='Entleerungszeit (Stunden)';
$ec_lang['odt_t_day']='Entleerungszeit (Tage)';
$ec_lang['odt_notes_1_term']='Formel';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ergibt die Entleerungszeit von Druckhöhe H bis zur Öffnung. Entleerungszeit = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), wobei H<sub>1</sub> = Anfangshöhe − Öffnungshöhe, H<sub>2</sub> = Endhöhe − Öffnungshöhe.';
$ec_lang['odt_notes_2_term']='Methode';
$ec_lang['odt_notes_2_def']='Die Kegelvolumenmethode modelliert den Teich als Kegelschnitt zwischen der Anfangsfläche A<sub>1</sub> beim Anfangswasserspiegel und der Fläche A<sub>0</sub> auf der Schwerpunkthöhe der Öffnung. A<sub>2</sub> wird aus A<sub>1</sub> und A<sub>0</sub> nach dem Kegelmodell interpoliert. Die Entleerungszeit von Anfang bis Endhöhe ist die Gesamtzeit von H<sub>1</sub> bis zur Öffnung minus der verbleibenden Zeit von H<sub>2</sub> bis zur Öffnung.';
$ec_lang['odt_h1']='Anfangsdruckhöhe, H<sub>1</sub> (WSE − Schwerpunkt)';
$ec_lang['odt_q_max']='Maximaldurchfluss (Anfang), Q<sub>max</sub>';
$ec_lang['odt_vol']='Abgeführtes Volumen';
$ec_lang['odt_sketch_start']='Anfang';
$ec_lang['odt_sketch_end']='Ende';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Uferbandbreite';
$ec_lang['essc_mcr']='Minimaler Kurvenradius';
$ec_lang['essc_q']='Durchfluss, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Bewässerungsdurchflussmessung';
$ec_lang['irr_main_title']='Kostenlose Online-Rechner für Bewässerungsdurchflussmessung';
$ec_lang['irr_main_desc']='Bewässerungsdurchflussmessung — Wehre und Öffnungen';
$ec_lang['irr_intro_html']='<p>Wehre und Öffnungen sind die standardmäßigen Feldwerkzeuge zur Messung des Wasserdurchflusses in Bewässerungssystemen. Wählen Sie den Rechner aus, der zu Ihrer Anlage passt:</p>';
$ec_lang['irr_card_weir_uniform_head']='Wehr — Breite Krone (Einheitliche Breite)';
$ec_lang['irr_card_weir_uniform_desc']='Messen Sie den Durchfluss über eine Ableitungsdammkrone, ein Kontrollbauwerk oder ein Wehrboard. Geben Sie die Wehrlänge und die Wasserspiegeltiefe über der Krone ein.';
$ec_lang['irr_card_weir_irregular_head']='Wehr — Unregelmäßiges Profil';
$ec_lang['irr_card_weir_irregular_desc']='Verwenden Sie dies, wenn die Wehrkrone keine einheitliche Höhe hat — natürliche Überlaufbauwerke, Absturzbauwerke mit variabler Breite oder mehrteilige Kontrollbauwerke.';
$ec_lang['irr_card_orifice_head']='Öffnung — Schieber oder Rohrauslass';
$ec_lang['irr_card_orifice_desc']='Messen Sie den Durchfluss durch einen Schieber, einen Rohrauslass oder eine Durchlassöffnung. Behandelt automatisch sowohl freien Ausfluss als auch eingestauene Bedingungen (Unterwasser).';
$ec_lang['irr_card_canal_head']='Kanalplanung & -analyse';
$ec_lang['irr_card_canal_desc']='Planen oder überprüfen Sie einen Bewässerungskanal mit der Manning-Formel. Verwenden Sie den Trapezrechner für neue Kanäle; den Unregelmäßigen Rechner für bestehende natürliche oder gebaute Querschnitte.';
$ec_lang['irr_card_drip_head']='Tropf- & Sprinklerplanung';
$ec_lang['irr_card_drip_desc']='Berechnen Sie Auftragsrate, Verteilungsgleichmäßigkeit, Lateraldurchfluss, Zonendurchfluss und Laufzeit für ein Tropf- oder Sprinklerbewässerungssystem. Geben Sie Emitterdurchfluss, Emitterabstand und Zieltiefe ein.';
$ec_lang['irr_card_seepage_head']='Kanaldurchsickerung & Transportwirkungsgrad';
$ec_lang['irr_card_seepage_desc']='Schätzen Sie den Versickerungsverlust einer Kanalhaltung anhand von Zu- und Abflussmessungen. Berechnen Sie den Transportwirkungsgrad und den jährlichen Wasserverlust, um Auskleidungsinvestitionen zu priorisieren.';
$ec_lang['irr_quickref_html']='<h3>Kurzreferenz</h3><dl><dt>Ableitungsdamm oder Kontrollbauwerk</dt><dd>Messen Sie die Wasserspiegeltiefe über der Wehrkrone. Verwenden Sie <a href="Weir-Flow-Simple.php">Einfaches Wehr</a> für eine einheitliche Krone oder <a href="Weir-Flow-Irregular.php">Unregelmäßiges Wehr</a> für eine profilierte oder gestufte Krone.</dd><dt>Schieber oder Rohrauslass</dt><dd>Messen Sie den Oberwasserspiegel und Unterwasserspiegel (oder die Sohlenhöhe bei freiem Ausfluss). Verwenden Sie <a href="Orifice.php">Öffnungsdurchfluss</a>. Bei einem Kreisrohr ist D = Rohrdurchmesser; bei einem rechteckigen Schieber geben Sie Breite W und Höhe D ein.</dd><dt>Entleerungszeit von Stausee oder Teich</dt><dd>Verwenden Sie <a href="Orifice-Drain-Time.php">Öffnungs-Entleerungszeit</a>, um zu schätzen, wie lange es dauert, einen Teich oder Stausee durch eine Bodenöffnung zu senken — nützlich für die Planung der Bewässerungsspeicherung.</dd><dt>Feldstandards</dt><dd>Die hier verwendeten Wehr- und Öffnungsdurchflussgleichungen entsprechen den Verfahren des USBR <em>Water Measurement Manual</em> (3. Aufl.), die häufig von Wassermeistern und Bewässerungsbezirken gefordert werden.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ds_main_menu']='Tropf-/Sprinkler-Ausbringungsrate';
$ec_lang['ds_main_title']='Kostenloser Online-Rechner für Tropf-/Sprinkler-Bewässerungsausbringungsrate';
$ec_lang['ds_main_desc']='Tropf- & Sprinklerbewässerung — Ausbringungsrate';
$ec_lang['ds_q_avg']='Emitterdurchflussrate, q';
$ec_lang['ds_se']='Emitterabstand entlang der Lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateralabstand (Reihenabstand), S<sub>l</sub>';
$ec_lang['ds_n_e']='Emitter pro Lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Lateralen pro Zone, n<sub>l</sub>';
$ec_lang['ds_d']='Ziel-Ausbringungstiefe, d';
$ec_lang['ds_a_e']='Fläche pro Emitter, A<sub>e</sub>';
$ec_lang['ds_pr']='Ausbringungsrate (Niederschlagsrate), PR';
$ec_lang['ds_q_lat']='Durchfluss pro Lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Zonendurchfluss, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Laufzeit für Zieltiefe (Stunden)';
$ec_lang['ds_notes_1_term']='Ausbringungsrate';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, wobei A<sub>e</sub> = S<sub>e</sub> × S<sub>l</sub> die von jedem Emitter versorgte Fläche ist. Eine niedrigere Ausbringungsrate gibt mehr Zeit für die Infiltration — wichtig bei schweren Böden oder geneigten Feldern.';
$ec_lang['ds_notes_2_term']='Laufzeit';
$ec_lang['ds_notes_2_def']='Laufzeit = Zieltiefe ÷ Ausbringungsrate. Auf geneigtem oder verdichtetem Boden die Laufzeit in zwei oder drei kürzere Zyklen mit Ruhepausen aufteilen, um Oberflächenabfluss zu vermeiden.';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Kanaldurchsickerung';
$ec_lang['cs_main_title']='Kostenloser Online-Rechner für Kanaldurchsickerungsverlust und Transportwirkungsgrad';
$ec_lang['cs_main_desc']='Kanaldurchsickerungsverlust & Transportwirkungsgrad — Zu-/Abfluss-Methode';
$ec_lang['cs_Q_in']='Zufluss am Anfang der Haltung, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Abfluss am Ende der Haltung, Q<sub>out</sub>';
$ec_lang['cs_L']='Haltungslänge, L';
$ec_lang['cs_wp']='Benetzter Umfang des Kanalquerschnitts, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='Versickerungsrate, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Messpunktkontrolle';
$ec_lang['cs_pct_loss']='Verlust als Anteil des Zuflusses';
$ec_lang['cs_Ec']='Transportwirkungsgrad, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Wirkungsgradklasse';
$ec_lang['cs_Vol_day']='Täglich verlorenes Volumen';
$ec_lang['cs_Vol_year']='Jährlich verlorenes Volumen';
$ec_lang['cs_Q_loss_per_L']='Versickerungsverlust je Längeneinheit, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Wasserpreis (Währung / Volumeneinheit)';
$ec_lang['cs_lining_cost']='Auskleidungskosten (Währung / Flächeneinheit)';
$ec_lang['cs_Ec_target']='Angestrebter Transportwirkungsgrad nach Auskleidung, E<sub>c,target</sub> (Bruchteil, 0–1) — Ziel für den Wasserrückhalt des ausgekleideten Kanals';
$ec_lang['cs_lining_area']='Kanalauskleidungsfläche (L × P<sub>w</sub>)';
$ec_lang['cs_annual_value_lost']='Jährlicher Wert des verlorenen Wassers (Währung)';
$ec_lang['cs_annual_value_recovered']='Jährlich durch Auskleidung zurückgewonnener Wert (Währung)';
$ec_lang['cs_lining_total_cost']='Gesamte Auskleidungskosten (Währung)';
$ec_lang['cs_payback_years']='Einfache Amortisationszeit (Jahre)';
$ec_lang['cs_loss_positive']='Qin > Qout — Versickerung festgestellt ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — kein messbarer Verlust';
$ec_lang['cs_loss_negative']='Warnung: Qout > Qin — Messungen prüfen ⚠';
$ec_lang['cs_Ec_good']='Gut — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Mittel — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Schlecht — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Methode';
$ec_lang['cs_notes_1_def']='Die Zu-/Abfluss-Methode schätzt die Versickerung durch Messung des Durchflusses am Anfang und Ende einer Kanalhaltung: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Transportwirkungsgrad E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Das Jahresvolumen setzt einen kontinuierlichen Vollbetrieb voraus; tatsächliche Verluste sind bei saisonalem oder Teilbetrieb geringer.';
$ec_lang['cs_notes_2_term']='Wirkungsgradklassen';
$ec_lang['cs_notes_2_def']='Typische unbefestigte Erdkanäle: E<sub>c</sub> = 60–80%. Gut unterhaltene Erdkanäle: 75–85%. Betonausgekleidete Kanäle: 90–98%. Versickerungsverluste über 30 % des Zuflusses rechtfertigen häufig eine Auskleidungsinvestition. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Amortisation der Auskleidung';
$ec_lang['cs_notes_3_def']='Wasserpreis und Auskleidungskosten in einer einheitlichen Währung eingeben. Auskleidungsfläche = Haltungslänge × benetzter Umfang — der benetzte Umfang des Kanalquerschnitts bei der gemessenen Fließtiefe (Sohlbreite plus beide benetzten Böschungen). Der jährlich zurückgewonnene Wert setzt voraus, dass der ausgekleidete Kanal das Ziel-E<sub>c</sub> dauerhaft erreicht. Die tatsächliche Amortisationszeit ist bei saisonalen Kanälen oder bei Nichterreichen der Zieleffizienz länger.';
$ec_lang['cs_notes_4_term']='Literatur';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3. Aufl. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='Über';
$ec_lang['install_main_menu']='Installieren';
$ec_lang['install_main_title']='EngCalcs installieren';
$ec_lang['install_main_desc']='Zum Gerät hinzufügen für Offline-Nutzung';
$ec_lang['contact_main_menu']='Kontakt';
$ec_lang['about_main_title']='Über die HawsEDC-Ingenieurrechner';
$ec_lang['about_main_desc']='Mission, Open Source und Mitwirken';
$ec_lang['about_body_html']='<h3>Mission</h3><p>Die HawsEDC-Ingenieurrechner dienen Ingenieuren und Feldarbeitern auf der ganzen Welt — insbesondere solchen, die in wasserarmen, ressourcenarmen oder unterversorgten Regionen arbeiten. Diese Werkzeuge sind Teil einer breiteren humanitären Mission: jedem Menschen auf die praktischste und wirkungsvollste Weise zu sagen, dass er für immer geliebt und geschätzt wird, dass er nichts zu befürchten hat und dass er nicht alles zunichte machen wird.</p><p>Die Rechner sind das Mittel. Das Ziel ist eine Welt frei von Leid.</p><h3>Open-Source-Lizenz</h3><p>Aller Code wird unter der <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 oder später</a> veröffentlicht — frei wie in Freiheit. Sie dürfen den Code unter denselben Bedingungen nutzen, studieren, ändern und weitergeben.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Quellcode</h3><p>Der vollständige Quellcode ist öffentlich auf Bitbucket verfügbar:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Sie können dort den Code durchsuchen, Probleme melden oder das Repository forken.</p><h3>Mitwirken</h3><p>Pull-Requests sind willkommen. Möglichkeiten zur Mitwirkung:</p><ul><li><strong>Übersetzungen</strong> — verbessern oder ergänzen Sie eine Sprache. Öffnen Sie einen Pull-Request mit Änderungen an der entsprechenden <code>lib/lang.ec.??.php</code>-Datei.</li><li><strong>Fehlerberichte</strong> — nutzen Sie das Feedback-Formular auf einer beliebigen Rechnerseite oder melden Sie ein Problem auf Bitbucket.</li><li><strong>Neue Rechner</strong> — Ideen für hydraulisch-ingenieurtechnische Werkzeuge für Feldarbeiter und Bewässerungspraktiker sind besonders willkommen. Siehe die Entwickleranleitung <code>CLAUDE.md</code> im Repository.</li><li><strong>Hosting</strong> — wenn Sie diese Rechner für eine Region mit eingeschränkter Konnektivität spiegeln können, nehmen Sie bitte Kontakt auf.</li></ul><h3>Offline-Nutzung</h3><p>Diese Rechner funktionieren als Progressive Web App (PWA). Besuchen Sie eine beliebige Rechnerseite bei bestehender Internetverbindung, und Ihr Browser speichert alle Rechner automatisch im Cache. Danach funktionieren alle Rechner offline — kein Internet erforderlich.</p><p>Verwenden Sie auf Android oder iOS die Option „Zum Startbildschirm hinzufügen" in Ihrem Browser, um EngCalcs als App auf Ihrem Gerät zu installieren. Auf dem Desktop suchen Sie nach dem Installationssymbol in der Adressleiste Ihres Browsers.</p><p>Sie können auch jeden einzelnen Rechner über das Menü „Speichern unter…" Ihres Browsers für die einmalige Offline-Nutzung speichern.</p><h3>Kontakt</h3><p>Tom Haws — Wasserbauingenieur und Autor dieser Rechner.<br />Nutzen Sie das Feedback-Formular auf einer beliebigen Rechnerseite oder greifen Sie auf den Quellcode unter <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> zu.</p>';
$ec_lang['contact_title']='HawsEDC Kontakt';
$ec_lang['contactSendMessage']='Senden Sie Tom Haws eine Nachricht';
$ec_lang['contactYourName']='Ihr Name:';
$ec_lang['contactYourEmail']='Ihre E-Mail-Adresse:';
$ec_lang['contactSubject']='Betreff:';
$ec_lang['contact_message']='Nachricht:';
$ec_lang['contactSpamPrefix']='Fünf plus eins ergibt';
$ec_lang['contactSpamPostfix']='(Bitte auf Englisch ausschreiben. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Nachricht senden';
$ec_lang['contact_success']='Danke, dass Sie sich die Zeit genommen haben zu schreiben.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Steingerinne-Bemessung (Robinson)';
$ec_lang['rc_main_title']='Kostenloser Online-Rechner für Steingerinne-Bemessung — Robinson (1998)';
$ec_lang['rc_main_desc']='Steingerinne Bruchsteinbemessung — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Gerinnegefälle, S<sub>0</sub>';
$ec_lang['rc_qt']='Gesamtspezifischer Abfluss, q<sub>t</sub> <span title="Abfluss je Breiteneinheit am Gerinneeinlauf. Bei einem Gerinne mit Sohlbreite B und Gesamtabfluss Q gilt q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Bruchsteinporosität, n<sub>p</sub>';
$ec_lang['rc_sg']='Rohdichte Gestein, sg <span title="Typisch für gebrochenen Granit oder Basalt ≈ 2,65. Gültiger Robinson-Bereich: 2,54 bis 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Kornverteilung SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Standardabweichung der Kornverteilung. Gleichförmiges Gestein ≈ 1,25. Gültiger Robinson-Bereich: 1,15 bis 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Normaltiefe im Zulaufgerinne, y<sub>n</sub> <span title="Einstau (Hp > yn) ist günstig — vermindert Erosion oberstrom. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Erforderlicher mittlerer Steindurchmesser, D<sub>50</sub> <span title="Gl. 1 (S0 < 0,10) oder Gl. 2 (0,10–0,40). Gültig: D50 15–278 mm, S0 0,02–0,40. Außerhalb des Bereichs: extrapoliert." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Angewandte Gleichung';
$ec_lang['rc_sg_check']='Prüfung Rohdichte';
$ec_lang['rc_SD_check']='Prüfung Kornverteilung SD';
$ec_lang['rc_sg_ok']   ='sg im gültigen Bereich (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Warnung: sg < 2,54 — unterhalb des Robinson-Bereichs';
$ec_lang['rc_sg_high'] ='Warnung: sg > 2,82 — oberhalb des Robinson-Bereichs';
$ec_lang['rc_SD_ok']   ='SD im gültigen Bereich (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Warnung: SD < 1,15 — unterhalb des Robinson-Bereichs';
$ec_lang['rc_SD_high'] ='Warnung: SD > 1,47 — oberhalb des Robinson-Bereichs';
$ec_lang['rc_layer']='Steinlagenstärke (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Krümmungsradius Oberkante (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Bogenlänge Oberkante';
$ec_lang['rc_apron_length']='Vorschüttstrecke Auslauf (15 × D<sub>50</sub>) <span title="Erforderlich zur Lagestabilisierung des Gerinneschotters. "Der minimale Unterwasserstand, der durch den Auslaufbereich und den Widerstand des Unterliegergerinnes entsteht, ist ausreichend, um die Stabilität des Bruchsteins im Auslaufbereich zu gewährleisten." (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Manning-Rauheit im Gerinne, n';
$ec_lang['rc_Vm']='Fließgeschwindigkeit durch Steinmatte, V<sub>m</sub> <span title="Anteil von qt, der durch die Steinporen fließt. Der Rest qs fließt über die Oberfläche. Standard np = 0,45 für gebrochenes Kantgestein." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Spezifischer Durchfluss durch Steinmatte, q<sub>m</sub>';
$ec_lang['rc_qs']='Oberflächenspezifischer Abfluss, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Fließtiefe über Bruchsteinoberfläche, d';
$ec_lang['rc_Hp']='Einlaufstauhöhe, H<sub>p</sub> <span title="Einstau (Hp > yn) ist günstig — vermindert Erosion oberstrom. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Einstauprufe am Einlauf';
$ec_lang['rc_pond_ok']  ='Hp > yn — Einstau oberstrom ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — kein Einstau — Einlauf auf Erosion prüfen';
$ec_lang['rc_eq1']='Gl. 1 (S0 < 0,10) — flaches Gefälle';
$ec_lang['rc_eq2']='Gl. 2 (0,10 ≤ S0 ≤ 0,40) — steiles Gefälle';
$ec_lang['rc_eq_warn_low']='Warnung: S0 < 0,02 — unterhalb des Robinson-Gültigkeitsbereichs';
$ec_lang['rc_eq_warn_high']='Warnung: S0 > 0,40 — oberhalb des Robinson-Gültigkeitsbereichs';
$ec_lang['rc_notes_1_term']='Steinbemessungsgleichungen';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) entwickelten zwei empirische Gleichungen für den mittleren Bruchsteindurchmesser D<sub>50</sub> in Abhängigkeit von Gefälle und spezifischem Abfluss. Gleichung 1 gilt für flache Gefälle (S<sub>0</sub> < 0,10); Gleichung 2 gilt für steile Gefälle (0,10 ≤ S<sub>0</sub> ≤ 0,40). Beide Gleichungen erfordern q<sub>t</sub> in m²/s und liefern D<sub>50</sub> in mm. Der validierte Bereich ist 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Spezifischer Abfluss';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> ist der gesamte spezifische Abfluss an der Gerinneoberkante (Gesamtabfluss je Breiteneinheit). Für ein Gerinne mit Sohlbreite B und Gesamtabfluss Q gilt näherungsweise q<sub>t</sub> ≈ Q / B, oder es wird aus der Grenztiefenbedingung am Gerinneeinlauf berechnet.';
$ec_lang['rc_notes_3_term']='Durchfluss durch die Steinmatte';
$ec_lang['rc_notes_3_def']='Ein Teil des Gesamtabflusses fließt durch die Poren des Bruchsteins (Mattendurchfluss q<sub>m</sub>); der Rest fließt über die Steinoberfläche (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Die Fließtiefe d wird aus der Manning-Gleichung für den Oberflächenabfluss q<sub>s</sub> mit der Gerinnorauheit n berechnet. Die Standardporosität n<sub>p</sub> = 0,45 ist typisch für gebrochenes Kantgestein.';
$ec_lang['rc_notes_5_term']='Gültiger Steindurchmesserbereich';
$ec_lang['rc_notes_5_def']='Die Gleichungen wurden für einen D<sub>50</sub>-Bereich von 15 mm bis 278 mm entwickelt. Ergebnisse außerhalb dieses Bereichs sind extrapoliert und sollten mit zusätzlichem ingenieurmäßigem Urteilsvermögen verwendet werden.';
$ec_lang['rc_notes_6_term']='Höhenlage Auslaufvorschüttung';
$ec_lang['rc_notes_6_def']='Die Oberkante des Bruchsteins im Auslaufbereich sollte auf oder unter der Sohlhöhe des Unterliegergerinnes liegen. Liegt sie höher, ist der Auslaufstein instabil.';
$ec_lang['rc_notes_7_term']='Einlaufeinstauprüfung';
$ec_lang['rc_notes_7_def']='Wenn die Normaltiefe im Zulaufgerinne kleiner ist als die erforderliche Wehrstauhöhe (H<sub>p</sub>) für den Abfluss q<sub>t</sub>, kommt es oberstrom der Einlaufschüttung zu eingeschränktem Abfluss oder Einstau. Dies ist grundsätzlich akzeptabel — Einstau vermindert die Fließgeschwindigkeit und verhindert Erosion oberstrom. Zur Prüfung: mit einem Wehrrechner H<sub>p</sub> für das gegebene q<sub>t</sub> und die Breite berechnen und mit der Normaltiefe im Zulaufgerinne vergleichen. Übersteigt H<sub>p</sub> die Normaltiefe, tritt Einstau auf.';
$ec_lang['rc_notes_4_term']='Literatur';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., und Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. Der USDA ARS veröffentlicht auch ein <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel-Arbeitsblatt</a> auf Basis derselben Methode.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filter';
$ec_lang['rc_sketch_top_crest_curve'] = 'Einlaufkurve';
$ec_lang['rc_sketch_outlet_apron']    = 'Auslaufschürze';
$ec_lang['rc_sketch_radius']          = 'Radius';
