<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="съотношение";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']='% наклон';
$ec_lang['u_grade']="височина/дължина";
$ec_lang['u_in2']="sq. in.";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="L/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="ML/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="sec";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Калкулатори';
$ec_lang['menu_main_list']='Списък с калкулатори';
$ec_lang['menu_main_hydraulics']='Хидравлика';
$ec_lang['menu_main_language']='Език';
$ec_lang['menu_more']='Още';
$ec_lang['template_welcome']='>> Оставете страховете си на прага; тук любовта е нашият език. Не съсипвате всичко. Насладете се и на <a target="_blank" href="https://hawsedc.com/download.php">безплатните инструменти HawsEDC за AutoCAD.</a> <<';
$ec_lang['template_translation_help']='Имате ли страхотна идея за калкулатор, който да добавите тук?  Можете ли да ми помогнете с превода, програмирането или хостинга за тези калкулатори?';
$ec_lang['template_feedback']='Моля споделете мнението си под формата на предложение или похвала. Този безплатен калкулатор надмина ли всичките ви очаквания?';
$ec_lang['template_printable_title']='Заглавие за принтиране';
$ec_lang['template_printable_subtitle']='Подзаглавие за принтиране';
$ec_lang['index_title']='Безплатни Oнлайн Инженерни Калкулатори';
$ec_lang['calc_set_units']='Изберете мерни единици:';
$ec_lang['calc_defaults']='Стандартни стойности';
$ec_lang['calc_defaults_confirm']='Reset calculator to factory defaults?';
$ec_lang['points_data_help']='(или Копиране/Поставяне чрез областта с данни)';
$ec_lang['points_data_title']='Данни за точки<br />(разделени със запетая или табулация)';
$ec_lang['points_data_copy']='Копирай';
$ec_lang['points_data_paste']='Постави';
$ec_lang['calc_inputs']='Входни данни';
$ec_lang['calc_results']='Резултати';
$ec_lang['view_hide_line']='[Скрий този ред]';
$ec_lang['view_printable']='Версия за печат (презаредете за възстановяване)';
$ec_lang['ec_name_label']='Запазете това изчисление:';
$ec_lang['ec_name_placeholder']='Име';
$ec_lang['ec_name_hint']='Запазва тези входни стойности в URL адреса за добавяне в отметки, извличане от история и споделяне';
$ec_lang['calc_copy_link']='Copy link';
$ec_lang['calc_copy_link_done']='Copied!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Загуба на напор в тръбопровод по Дарси-Вайсбах';
$ec_lang['dw_main_title']='Безплатен онлайн калкулатор за загуба на напор по Дарси-Вайсбах';
$ec_lang['dw_main_desc']='Загуба на напор по Дарси-Вайсбах при зададени диаметър, грапавост и дебит';
$ec_lang['dw_roughness']='Грапавост, e';
$ec_lang['dw_roughness_tip']='<span title="Височина на грапавостта по метода на Дарси-Вайсбах" class="ec-tip">?</span>';
$ec_lang['dw_kinematic_viscosity']='Кинематична вискозност, &nu; <span title="1×10⁻⁶ m²/s за чиста вода при 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Число на Рейнолдс, Re';
$ec_lang['dw_flow_regime']='Режим на течението';
$ec_lang['dw_regime_laminar']='ламинарен';
$ec_lang['dw_regime_transitional']='преходен';
$ec_lang['dw_regime_turbulent']='турбулентен';
$ec_lang['dw_friction_factor_method']='Метод за коефициент на триене';
$ec_lang['dw_friction_factor']='Коефициент на триене, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Загуба на напор в тръбопровод по Хейзен-Уилямс';
$ec_lang['hw_main_title']='Безплатен онлайн калкулатор за загуба на напор по Хейзен-Уилямс';
$ec_lang['hw_main_desc']='Загуба на напор по Хейзен-Уилямс при зададени диаметър, грапавост и дебит';
$ec_lang['hw_hgl_1']='HGL надолу по течението';
$ec_lang['hw_hgl_2']='HGL нагоре по течението';
$ec_lang['hw_roughness']='Коефициент на Хейзен-Уилямс, C';
// Manning Irregular
$ec_lang['mi_menu']='Канал с неправилно сечение по Манинг';
$ec_lang['mi_main_title']='Безплатен онлайн калкулатор за канал с неправилно сечение по Манинг';
$ec_lang['mi_main_desc']='Калкулатор за равномерно течение в канал с неправилно сечение по Манинг';
$ec_lang['mi_waterSurfaceElevation']='Кота на водната повърхност';
$ec_lang['mi_q_617']='Q <span title="Съставен дебит Q, изчислен със съставно n за всеки регион съгласно Chow 6-17, при равни скорости" class="ec-tip">?</span>';
$ec_lang['mi_xSecPoints']='Точки на напречното сечение';
$ec_lang['mi_groupPoint']='Точка';
$ec_lang['mi_groupSegment']='Сегмент';
$ec_lang['mi_groupRegion']='Регион';
$ec_lang['mi_station']='Ст.';
$ec_lang['mi_elevation']='Кота';
$ec_lang['mi_d50in']='Облицовка<br />медианен<br />размер<br />камъни';
$ec_lang['mi_n']='n<br />за сег-<br />мент';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />граница<br />регион<br />(Бряг)';
$ec_lang['mi_tau']='Дъно<br />срязв.<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Съст.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Бележки';
$ec_lang['mi_notes_1_term']='Съставно n';
$ec_lang['mi_notes_1_def']='Калкулаторът следва наръчника HEC-RAS за изчисляване на съставното n по региони съгласно Chow 1959, стр. 136, уравнение 6-17 (а не 6-18).';
$ec_lang['mi_notes_2_term']='Каменна облицовка';
$ec_lang['mi_notes_2_def']='Използвайте калкулатора за трапецовиден канал на Манинг за проектиране на каменна облицовка. Този калкулатор е предназначен за естествени напречни сечения.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Дебит в тръбопровод по Манинг';
$ec_lang['mpf_main_title']='Безплатен онлайн калкулатор за дебит в тръбопровод по Манинг';
$ec_lang['mpf_main_desc']='Равномерен дебит в тръбопровод по формулата на Манинг при зададени наклон и дълбочина';
$ec_lang['mpf_spreadheet_notice']='Изпробвайте таблична (Excel) версия на този калкулатор';
$ec_lang['mpf_pipe_diameter']='Диаметър на тръбата, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Коефициент на грапавост на Манинг, n';
$ec_lang['mpf_friction_slope']='Хидравличен наклон (понякога <a target="_blank" href="../frictionslope.php">?</a> равен на наклона на тръбата), S<sub>f</sub>';
$ec_lang['mpf_depth_ratio']='Относителна дълбочина на потока, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Вижте бележките)';
$ec_lang['mpf_flow']='Дебит, Q';
$ec_lang['mpf_velocity']='Скорост, v';
$ec_lang['mpf_velocity_head']='Скоростен напор, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Площ на потока, A';
$ec_lang['mpf_pipe_area']='Площ на тръбата, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Относителна площ, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Навлажнен периметър, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Хидравличен радиус, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Горна ширина, T';
$ec_lang['mpf_froude_number']='Число на Фруд, Fr';
$ec_lang['mpf_shear_stress']='Средно срязващо напрежение (теглителна сила), &tau;';
$ec_lang['mpf_full_flow']='Пълен дебит, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Съотношение към пълен дебит, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Това е дебитът и дълбочината в <em>безкрайно дълга</em> тръба.</dt><dd>За вкарването на потока в тръбата може да е необходима значително по-голяма дълбочина на горната вода. Добавете поне 1,5 пъти скоростния напор за да получите дълбочината на горната вода или <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">вижте моя 2-минутен урок</a> за стандартни изчисления на горна вода за водостоци с HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Намерете y/d<sub>0</sub> при дадено Q';
$ec_lang['mpf_solve_desc']='Използвайки d<sub>0</sub>, n и S<sub>f</sub> от формуляра на калкулатора, намира най-ниското y/d<sub>0</sub> за даденото Q.';
$ec_lang['mpf_solve_button']='Изчисли';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Загуба на напор в тръбопровод по Манинг';
$ec_lang['mphl_main_title']='Безплатен онлайн калкулатор за загуба на напор в тръбопровод по Манинг';
$ec_lang['mphl_main_desc']='Загуба на напор по формулата на Манинг при зададен пълен дебит';
$ec_lang['mphl_pipe_length']='Дължина, L';
$ec_lang['mphl_area']='Площ, A';
$ec_lang['mphl_total_junction_k']='Коефициент на местни (локални) загуби, k<sub>m</sub>';
$ec_lang['mphl_friction_slope']='Хидравличен наклон';
$ec_lang['mphl_friction_loss']='Загуби от триене, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Местни (локални) загуби, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Общи загуби, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='EGL надолу по течението';
$ec_lang['mphl_egl_2']='EGL нагоре по течението';
$ec_lang['mphl_hgl_2']='HGL нагоре по течението в тръбата ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>При отворен вход (водосток) е необходима проверка за условия на контрол при входа.</dt><dd>1. HGL нагоре по течението трябва да бъде над котата на нормалната дълбочина на течението нагоре по течението (и по-високо от тръбата!).</dd><dd>2. Горната вода на водосток се представя по-добре чрез EGL нагоре по течението, отколкото чрез HGL нагоре по течението.</dd><dd>3. Вижте <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">моя 2-минутен урок</a> за прости стандартни изчисления на горна вода за водостоци с HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Изчисления на трапецовидни канали по Манинг';
$ec_lang['mtc_main_title']='Безплатен онлайн калкулатор за изчисления на трапецовидни канали по Манинг';
$ec_lang['mtc_main_desc']='Формула на Манинг за равномерно движение в трапецовиден канал при зададени наклон и воден стълб';
$ec_lang['mtc_bottom_width']='Ширина на дъното, b';
$ec_lang['mtc_side_slope_1']='Страничен откос 1, z<sub>1</sub> (хориз./верт.)';
$ec_lang['mtc_side_slope_2']='Страничен откос 2, z<sub>2</sub> (хориз./верт.)';
$ec_lang['mtc_channel_slope']='Наклон на канала, S';
$ec_lang['mtc_flow_depth']='Воден стълб, y';
$ec_lang['mtc_bend_angle']='Ъгъл на завоя, β <a target="_blank" href="riprap-bend-angle.png" title="Натиснете за изображение">?</a> (за оразмеряване на каменната облицовка)';
$ec_lang['mtc_sgrock']='Относителна плътност на камъка, sg <span title="Обикновено &asymp; 2.65 за трошен камък" class="ec-tip">?</span>';
$ec_lang['mtc_d50_in']='Проектен размер на камъните, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n за проектния размер на камъните по Strickler';
$ec_lang['mtc_n_blodgett']='n за проектния размер на камъните по Blodgett';
$ec_lang['mtc_n_bathurst']='n за проектния размер на камъните по Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett срещу Bathurst';
$ec_lang['mtc_d50_bottom']='Необходим размер на ъглести камъни за дъното, D<sub>50</sub> (Isbash & MC) <span title="Съгласно Isbash (1936) и Maricopa County, Аризона, САЩ." class="ec-tip">?</span>';
$ec_lang['mtc_d50_z1']='Необходим размер на ъглести камъни за страничен откос 1, D<sub>50</sub> (Isbash & MC) <span title="Съгласно Isbash (1936) и Maricopa County, Аризона, САЩ." class="ec-tip">?</span>';
$ec_lang['mtc_d50_z2']='Необходим размер на ъглести камъни за страничен откос 2, D<sub>50</sub> (Isbash & MC) <span title="Съгласно Isbash (1936) и Maricopa County, Аризона, САЩ." class="ec-tip">?</span>';
$ec_lang['mtc_d50_mra']='Необходим размер на ъглести камъни, D<sub>50</sub> (Maynord, Ruff и Abt 1989)';
$ec_lang['mtc_d50_searcy']='Необходим размер на ъглести камъни, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_check']='Проверка на скоростта';
$ec_lang['mtc_vel_ok']='Скоростта е разумна за предположения за равномерно течение.';
$ec_lang['mtc_vel_high']='Висока скорост — проверете загубите при преходи, наличната енергия и хидравличния удар.';
$ec_lang['mtc_vel_low']='Ниска скорост — риск от утаяване.';
$ec_lang['mtc_vel_ok_short']='ОК';
$ec_lang['mtc_vel_high_short']='Висока';
$ec_lang['mtc_vel_low_short']='Ниска';
$ec_lang['mtc_note_1']='<dl><dt>Автоматична итерация за проектиране на размера и грапавината на каменната облицовка</dt><dd>Изберете опция за грапавина (препоръчва се Blodgett–Bathurst) и опция за проектен размер на камъните (препоръчва се Isbash). Настройте дълбочината и коефициента на безопасност за размера на камъните, за да получите желания дебит с равен размер на камъните. При всяка промяна на входна стойност се изпълнява следният итерационен цикъл: 1. Грапавината се изчислява от проектния размер на камъните. 2. Избраното изчисление на грапавината се копира в входната грапавина. 3. Дебитът в канала и необходимият размер на камъните се изчисляват. 4. Проектният размер на камъните се коригира. 5. Повтаря се до много малка грешка в проектния размер.</dd><dt>Основен калкулатор (без итерация)</dt><dd>Въведете желаната стойност на грапавината. Игнорирайте полето за проектен размер на камъните.</dd></dl>';
$ec_lang['mtc_note_2_term']='Проверка на скоростта';
$ec_lang['mtc_note_2_def']='Високата скорост означава висока специфична енергия от наличния пад. Тази енергия може да се загуби бързо при разширения, завои или препятствия. Проверете дали това е разумно за конкретния обект.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Прост преливник';
$ec_lang['ws_main_title']='Безплатен онлайн калкулатор за дебит на прост преливник с широк праг';
$ec_lang['ws_main_desc']='Калкулатор за дебит на прост преливник с широк праг';
$ec_lang['ws_weirLength']='Дължина на преливника, L';
$ec_lang['ws_headWaterHeight']='Напор, h';
$ec_lang['ws_weirCoefficient']='Коефициент на преливника, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Забележки';
$ec_lang['ws_notes_we_term']='Уравнение на преливника';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Преливник с неправилно сечение';
$ec_lang['wi_main_title']='Безплатен онлайн калкулатор за сегментиран преливник с неправилно сечение и променлива дълбочина';
$ec_lang['wi_main_desc']='Калкулатор за преливник с неправилно сечение';
$ec_lang['wi_headWaterelevation']='Кота на горната вода';
$ec_lang['wi_weirPoints']='Точки на преливника';
$ec_lang['wi_station']='Станция';
$ec_lang['wi_elevation']='Кота';
$ec_lang['wi_pondingHeight']='Дълбочина на подпор';
$ec_lang['wi_incrementalFlow']='Частичен дебит';
$ec_lang['wi_cumulativeFlow']='Натрупан дебит';
$ec_lang['wi_save_and_calculate']='Запази и изчисли';
$ec_lang['wi_notes_we_term']='Уравнение на преливника';
$ec_lang['wi_notes_we_def']='q = ако (дължина = 0) тогава 0 иначе ако (наклон=0) тогава cw*дължина*d<sub>0</sub><sup>1,5</sup> иначе cw/(2,5*наклон) * (d<sub>0</sub><sup>2,5</sup> - d<sub>1</sub><sup>2,5</sup>) където d<sub>1</sub> и d<sub>0</sub> са винаги положителни или нула';
// Orifice Flow
$ec_lang['or_main_menu']='Дебит през отвор';
$ec_lang['or_main_title']='Безплатен онлайн калкулатор за дебит през отвор';
$ec_lang['or_main_desc']='Дебит през отвор — свободно или потопено изтичане';
$ec_lang['or_shape']='Форма на отвора';
$ec_lang['or_shape_circular']='Кръгъл';
$ec_lang['or_shape_rectangular']='Правоъгълен';
$ec_lang['or_diameter']='Диаметър или височина, D <span title="Диаметър за кръгъл отвор; височина за правоъгълен" class="ec-tip">?</span>';
$ec_lang['or_width']='Ширина, W <span title="Само за правоъгълни отвори" class="ec-tip">?</span>';
$ec_lang['or_invert']='Инвертна кота <span title="Дъно на отвора" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Кота на горната вода';
$ec_lang['or_twe']='Кота на долната вода';
$ec_lang['or_cd']='Коефициент на изтичане, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Кота на центроида';
$ec_lang['or_head']='Ефективен напор, h';
$ec_lang['or_area']='Площ на отвора, A';
$ec_lang['or_flow']='Дебит, Q';
$ec_lang['or_velocity']='Скорост, v';
$ec_lang['or_regime']='Проверка на режима на отвор';
$ec_lang['or_regime_valid']='Свободно изтичане';
$ec_lang['or_regime_submerged']='Потопен отвор';
$ec_lang['or_regime_submerged_tip']='TWE над центроида на отвора — режимът на отвор остава валиден';
$ec_lang['or_regime_warn']='Извън режима на отвор';
$ec_lang['or_regime_warn_tip']='Горната вода е под горния ръб на отвора';
$ec_lang['or_regime_twe_above_hwe']='Проверете входните данни';
$ec_lang['or_regime_twe_above_hwe_tip']='Долната вода (TWE) е над горната вода (HWE)';
$ec_lang['or_notes_1_term']='Уравнение за отвор';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). При свободно изтичане: h = HWE − центроид. При потопено (TWE над дъното): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Режим на отвор';
$ec_lang['or_notes_2_def']='Уравнението за отвор е приложимо, когато нивото на горната вода е над горния ръб (върха) на отвора. Когато горната вода е под горния ръб, използвайте уравнение за преливник.';
$ec_lang['or_notes_3_term']='Коефициент на изтичане';
$ec_lang['or_notes_3_def']='C<sub>d</sub> е приблизително 0,60–0,65 за отвори с остри ръбове. Заоблени или вдлъбнати (re-entrant) входове използват различни стойности. Вижте <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> или Наръчника по хидравлика на HEC-RAS за насоки.';
$ec_lang['or_notes_4_term']='Потопяване';
$ec_lang['or_notes_4_def']='Когато TWE е над дъното на отвора, калкулаторът автоматично прилага уравнението за потопен отвор с h = HWE − TWE. Когато TWE е на или под дъното, се приема свободно изтичане и h = HWE − центроид.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Микро-ВЕЦ';
$ec_lang['mhp_main_title']='Безплатен онлайн калкулатор за мощност на микро-ВЕЦ';
$ec_lang['mhp_main_desc']='Калкулатор за изходна мощност на микро-ВЕЦ с деривационна схема';
$ec_lang['mhp_flow']='Дебит, Q';
$ec_lang['mhp_gross_head']='Брутен напор, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Диаметър на тръбопровода, D';
$ec_lang['mhp_length']='Дължина на тръбопровода, L';
$ec_lang['mhp_roughness']='Грапавост на тръбата, e';
$ec_lang['mhp_km']='Коефициент на местните загуби, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Кинематична вискозност, ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='КПД на централата, η (0–1)';
$ec_lang['mhp_velocity']='Скорост на потока, v';
$ec_lang['mhp_vel_check']='Проверка на скоростта';
$ec_lang['mhp_f']='Коефициент на триене, f';
$ec_lang['mhp_hf']='Загуба на напор от триене, h<sub>f</sub>';
$ec_lang['mhp_hm']='Загуби на напор, h<sub>m</sub>';
$ec_lang['mhp_hl']='Обща загуба в тръбопровода, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Проверка на загубата на напор';
$ec_lang['mhp_hnet']='Нетен напор, H<sub>net</sub>';
$ec_lang['mhp_power']='Изходна мощност, P';
$ec_lang['mhp_annual_kwh']='Годишна енергия при 100% натоварване';
$ec_lang['mhp_vel_low']='Ниска скорост — риск от утаяване и попадане на въздух.';
$ec_lang['mhp_vel_high']='Висока скорост — проверете загубите при преходи, наличната енергия и хидравличния удар.';
$ec_lang['mhp_vel_ok_short']='ОК';
$ec_lang['mhp_vel_high_short']='Висока';
$ec_lang['mhp_vel_low_short']='Ниска';
$ec_lang['mhp_hl_ok']='в рамките на целевите 10% ✓';
$ec_lang['mhp_hl_warn']='надвишава целевите 10% — помислете за по-голяма тръба ⚠';
$ec_lang['mhp_hl_bad']='надвишава 20% — преоразмерете тръбата';
$ec_lang['mhp_notes_1_term']='Загуба на напор';
$ec_lang['mhp_notes_1_def']='Обща загуба h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, където h<sub>f</sub> = f(L/D)(v²/2g) е загубата от триене по Дарси-Вайсбах, а h<sub>m</sub> = k<sub>m</sub>·v²/2g включва вход, колена и спирателни органи. Нетен напор H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Скорост';
$ec_lang['mhp_notes_2_def']='Целева скорост 1–3 м/с. Под 1 м/с тръбата е свръхоразмерена; над 3 м/с нарастват загубите от триене и рискът от хидравличен удар.';
$ec_lang['mhp_notes_3_term']='Целева загуба на напор';
$ec_lang['mhp_notes_3_def']='Загуба под 10% от брутния напор е икономически оправдана. Оптималният компромис между цената на тръбата и изгубената мощност обикновено е около 4–6% за обекти с висока стойност на електроенергията.';
$ec_lang['mhp_notes_4_term']='Местни загуби k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Типични стойности: остър вход 0.5, всяко коляно 45° между 0.2–0.3, спирателен кран (напълно отворен) 0.1, пеперудна клапа 0.2. Сумирайте всички фитинги за общ k<sub>m</sub>. Стойността по подразбиране 1.5 приема един вход и две колена.';
$ec_lang['mhp_notes_5_term']='Грапавост на тръбата e';
$ec_lang['mhp_notes_5_def']='Типична абсолютна грапавост: стомана (нова) 0.046 мм, стомана (стара) 0.15 мм, HDPE 0.003 мм, PVC/uPVC 0.0015 мм, бетон 0.3–3 мм. HDPE е широко разпространен за малки микрохидро тръбопроводи.';
$ec_lang['mhp_notes_6_term']='Ефективност';
$ec_lang['mhp_notes_6_def']='Типичното КПД на централата η е в диапазона 0,70–0,85 за турбини Pelton и напречно-проточни турбини, характерни за микро-ВЕЦ. Използвайте 0,75 като консервативна първоначална оценка.';
$ec_lang['mhp_notes_7_term']='Годишна енергия';
$ec_lang['mhp_notes_7_def']='Годишната енергия предполага непрекъсната работа при пълен дебит (8760 часа/година). Действителното производство ще бъде по-ниско поради сезонни вариации на дебита, престои за поддръжка и коефициент на натоварване.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Време за изпразване на отвор';
$ec_lang['odt_main_title']='Безплатен онлайн калкулатор за времето за изпразване на отвор — Езерце, басейн или резервоар';
$ec_lang['odt_main_desc']='Време за изпразване на езерце или басейн през отвор — Метод на коничния обем';
$ec_lang['odt_h1_elev']='Начална кота';
$ec_lang['odt_a1']='Начална площ, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Крайна кота';
$ec_lang['odt_h_orifice']='Кота на центроида на отвора';
$ec_lang['odt_a0']='Площ при котата на отвора, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Крайна площ, A<sub>2</sub> <span title="Интерполирана от коничния модел при крайната кота" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='Проверка на крайната кота';
$ec_lang['odt_h2_ok']='Крайната кота е над горния ръб на отвора';
$ec_lang['odt_h2_warn']='Крайната кота е на или под горния ръб на отвора';
$ec_lang['odt_h2_warn_tip']='Горният ръб на отвора = центроид + D/2';
$ec_lang['odt_d']='Отвор D <span title="Диаметър (кръгъл) или височина (правоъгълен)" class="ec-tip">?</span>';
$ec_lang['odt_w']='Ширина на отвор, W <span title="Само за правоъгълен" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='Време за изпразване (s)';
$ec_lang['odt_t_min']='Време за изпразване (min)';
$ec_lang['odt_t_hr']='Време за изпразване (часове)';
$ec_lang['odt_t_day']='Време за изпразване (дни)';
$ec_lang['odt_notes_1_term']='Формула';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) дава времето за изпразване от напор H до отвора. Времето за изпразване = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), където H<sub>1</sub> = начална кота − кота на отвора, H<sub>2</sub> = крайна кота − кота на отвора.';
$ec_lang['odt_notes_2_term']='Метод';
$ec_lang['odt_notes_2_def']='Методът на коничния обем моделира езерцето или басейна като конично сечение между началната площ A<sub>1</sub> при началната водна повърхност и площта A<sub>0</sub> при кота на центроида на отвора. A<sub>2</sub>, площта на езерцето при крайната кота, се интерполира от A<sub>1</sub> и A<sub>0</sub> по модела на коничното сечение. Времето за изпразване от началната до крайната кота е равно на общото време за изпразване от H<sub>1</sub> до отвора минус оставащото времe за изпразване от H<sub>2</sub> до отвора.';
$ec_lang['odt_h1']='Начален напор, H<sub>1</sub> <span title="Начална кота на водната повърхност минус кота на центроида на отвора" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='Максимален дебит, Q<sub>max</sub>';
$ec_lang['odt_vol']='Изпразнен обем';
$ec_lang['odt_sketch_start']='Начало';
$ec_lang['odt_sketch_end']='Край';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Напояване';
$ec_lang['irr_main_title']='Безплатни онлайн калкулатори за измерване на дебит при напояване';
$ec_lang['irr_main_desc']='Измерване на дебит при напояване — преливници и отвори';
$ec_lang['irr_intro_html']='<p>Преливниците и отворите са стандартните полеви инструменти за измерване на дебита на водата в напоителни системи. Изберете калкулатора, който съответства на вашето съоръжение:</p>';
$ec_lang['irr_card_weir_uniform_head']='Преливник — широкогребенен (еднородна ширина)';
$ec_lang['irr_card_weir_uniform_desc']='Измерете дебита над гребена на отводнителна язовирна стена, контролно съоръжение или дъска на преливник. Въведете дължината на преливника и дълбочината на водата над гребена.';
$ec_lang['irr_card_weir_irregular_head']='Преливник — неправилен профил';
$ec_lang['irr_card_weir_irregular_desc']='Използвайте, когато гребенът на преливника варира по кота или профил — естествени преливи, стъпаловидни съоръжения с променлива ширина или многосекционни контролни съоръжения.';
$ec_lang['irr_card_orifice_head']='Отвор — входен затвор или тръбен изход';
$ec_lang['irr_card_orifice_desc']='Измерете дебита през шлюзов затвор, тръбен изход или отвор на водосток. Автоматично се обработват както свободно изтичане, така и потопени условия (с повишено ниво надолу по течението).';
$ec_lang['irr_card_canal_head']='Проектиране &amp; анализ на канал';
$ec_lang['irr_card_canal_desc']='Проектирайте или проверете напоителен канал по формулата на Manning. Използвайте трапецовидния калкулатор за нови канали и калкулатора за неправилно сечение за съществуващи естествени или изградени участъци.';
$ec_lang['irr_card_seepage_head']='Просмукване от канал &amp; ефективност на транспортиране';
$ec_lang['irr_card_seepage_desc']='Оценете загубите от просмукване в участък от канал по измервания на притока и изтока. Изчислете ефективността на транспортиране и годишните загуби на вода, за да приоритизирате инвестициите в облицовка.';
$ec_lang['irr_quickref_html']='<h3>Бърза справка</h3><dl><dt>Отводнителна язовирна стена или контролно съоръжение</dt><dd>Измерете дълбочината на водата над гребена на преливника. Използвайте <a href="Weir-Flow-Simple.php">Прост преливник</a> за еднороден гребен или <a href="Weir-Flow-Irregular.php">Преливник с неправилен профил</a> за профилиран или стъпаловиден гребен.</dd><dt>Входен затвор или тръбен изход</dt><dd>Измерете котата на нивото на водата нагоре по течението и котата надолу по течението (или котата на дъното при свободно изтичане). Използвайте <a href="Orifice.php">Дебит през отвор</a>. За кръгла тръба D&nbsp;= диаметър на тръбата; за правоъгълен затвор въведете ширина W и височина D.</dd><dt>Време за изпразване на водоем или яз</dt><dd>Използвайте <a href="Orifice-Drain-Time.php">Време за изпразване през отвор</a>, за да оцените колко време отнема понижаването на нивото на яз или водоем през донен отвор — полезно за планиране на напоителни водохранилища.</dd><dt>Полеви стандарти</dt><dd>Уравненията за дебит през преливник и отвор, използвани тук, съответстват на процедурите на USBR <em>Water Measurement Manual</em> (3-то&nbsp;изд.), които обикновено се изискват от водни управители и напоителни райони.</dd></dl>';
$ec_lang['irr_card_pressure_head']='Налягане и равномерност при напояване';
$ec_lang['irr_card_pressure_desc']='Моделирайте профила на налягане и дебит по клон главен тръбопровод–латерал–емитер, за да оцените равномерността на разпределение въз основа на реалното налягане по пробния път, а не само на каталожния дебит на емитера.';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Разстояние между емитерите, S<sub>e</sub>';
$ec_lang['ip_sl']='Разстояние между латералите, S<sub>l</sub>';
$ec_lang['ip_n_e']='Емитери на латерал, n<sub>e</sub>';
$ec_lang['ip_n_l']='Латерали на зона, n<sub>l</sub>';
$ec_lang['ip_d']='Целева дълбочина на поливане, d';
$ec_lang['ip_a_e']='Площ на емитер, A<sub>e</sub>';
$ec_lang['ip_pr']='Норма на поливане, PR';
$ec_lang['ip_q_lat']='Дебит на латерал, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Дебит на зоната, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Продължителност на работа (часове)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Просмукване от канал';
$ec_lang['cs_main_title']='Безплатен онлайн калкулатор за загуби от просмукване и ефективност на транспортиране на канал';
$ec_lang['cs_main_desc']='Загуби от просмукване и ефективност на транспортиране на канал &mdash; метод вход-изход';
$ec_lang['cs_Q_in']='Приток, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Изток, Q<sub>out</sub>';
$ec_lang['cs_L']='Дължина на участъка, L';
$ec_lang['cs_wp']='Мокър периметър на напречното сечение на канала, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='Дебит на загубата от просмукване, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Проверка на измерването';
$ec_lang['cs_pct_loss']='Дял на загубата';
$ec_lang['cs_Ec']='Ефективност на транспортиране, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Оценка на ефективността';
$ec_lang['cs_Vol_day']='Дневен загубен обем';
$ec_lang['cs_Vol_year']='Годишен загубен обем';
$ec_lang['cs_Q_loss_per_L']='Загуба на единица дължина, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Стойност на водата';
$ec_lang['cs_lining_cost']='Цена на облицовката';
$ec_lang['cs_Ec_target']='Целева стойност след облицоване, E<sub>c,target</sub> <span title="Целева ефективност на транспортиране след облицоване; дял 0&ndash;1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Площ на облицовката, L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Годишна изгубена стойност';
$ec_lang['cs_annual_value_recovered']='Годишна възстановена стойност';
$ec_lang['cs_lining_total_cost']='Обща цена на облицовката';
$ec_lang['cs_payback_years']='Срок на откупуване <span title="Прост срок на откупуване = обща цена на облицовката &divide; годишна възстановена стойност" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — установено просмукване';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — няма измерима загуба';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — проверете измерванията';
$ec_lang['cs_Ec_good']='Добра — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Задоволителна — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Лоша — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_term']='Метод';
$ec_lang['cs_notes_1_def']='Методът вход-изход оценява просмукването чрез измерване на дебита в началото и края на участъка от канала: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. Ефективността на транспортиране E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Годишният обем приема непрекъсната работа при пълен дебит; действителната загуба е по-малка при сезонни канали или канали с частичен дебит.';
$ec_lang['cs_notes_2_term']='Оценки на ефективността';
$ec_lang['cs_notes_2_def']='Типични земни канали без облицовка: E<sub>c</sub> = 60&ndash;80%. Добре поддържани земни канали: 75&ndash;85%. Бетонирани (облицовани) канали: 90&ndash;98%. Загуби от просмукване над 30% от притока често оправдават инвестиция в облицовка. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Откупуване на облицовката';
$ec_lang['cs_notes_3_def']='Въведете стойността на водата и цената на облицовката в произволна, но последователна валута. Площ на облицовката = дължина на участъка &times; мокър периметър &mdash; мокрият периметър на напречното сечение на канала при измерената дълбочина на потока (ширина на дъното плюс двата мокри откоса). Годишната възстановена стойност предполага, че облицованият канал постига целевата E<sub>c</sub> непрекъснато. Действителният срок на откупуване ще бъде по-дълъг при сезонни канали или ако облицовката не достигне целевата ефективност.';
$ec_lang['cs_notes_4_term']='Справка';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3-то изд. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='За';
$ec_lang['install_main_menu']='Инсталирай';
$ec_lang['install_main_title']='Инсталирай EngCalcs';
$ec_lang['install_main_desc']='Добави на устройството си за офлайн използване';
$ec_lang['contact_main_menu']='Контакт';
$ec_lang['about_main_title']='За инженерните калкулатори HawsEDC';
$ec_lang['about_main_desc']='Мисия, отворен код и принос';
$ec_lang['about_body_html']='<h3>Мисия</h3><p>Инженерните Калкулатори на HawsEDC съществуват, за да служат на инженери и полеви работници по целия свят — особено на работещите в региони с недостиг на вода, ограничени ресурси или недостатъчно обслужване. Тези инструменти са част от по-широка хуманитарна мисия: да каже на всеки човек по най-практичния и ефективен начин, че е обичан и ценен завинаги, че няма от какво да се страхува и че няма да провали всичко.</p><p>Калкулаторите са превозното средство. Дестинацията е свят без страдание.</p><h3>Лиценз с Отворен Код</h3><p>Целият код е публикуван под <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU Общ Публичен Лиценз v3.0 или по-нова версия</a> — свободен като в свобода. Можете да използвате, изучавате, модифицирате и преразпространявате кода при същите условия.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Изходен Код</h3><p>Пълният изходен код е публично достъпен в Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Можете да разглеждате кода, да подавате проблеми или да форкнете хранилището там.</p><h3>Принос</h3><p>Pull заявките са добре дошли. Начини за принос:</p><ul><li><strong>Преводи</strong> — подобрете или добавете език. Отворете pull заявка с промени в съответния файл <code>lib/lang.ec.??.php</code>.</li><li><strong>Доклади за грешки</strong> — използвайте формуляра за обратна връзка на всяка страница с калкулатор или подайте проблем в Bitbucket.</li><li><strong>Нови калкулатори</strong> — идеи за хидравлично инженерни инструменти, обслужващи полеви работници и специалисти по напояване, са особено добре дошли. Вижте ръководството за разработчици <code>CLAUDE.md</code> в хранилището.</li><li><strong>Хостинг</strong> — ако можете да огледалите тези калкулатори за регион с ограничена свързаност, моля, свържете се с нас.</li></ul><h3>Използване без интернет</h3><p>Тези калкулатори работят като прогресивно уеб приложение (PWA). Посетете която и да е страница с калкулатор, докато сте свързани с интернет, и браузърът ви автоматично ще кешира всички калкулатори. След това всички калкулатори работят офлайн — не е необходим интернет.</p><p>На Android или iOS използвайте опцията „Добавяне към началния екран" на браузъра си, за да инсталирате EngCalcs като приложение на устройството си. На настолен компютър потърсете иконата за инсталиране в адресната лента на браузъра си.</p><p>Можете също да запазите всеки отделен калкулатор чрез менюто „Запазване като…" на браузъра си за еднократна употреба офлайн.</p><h3>Контакт</h3><p>Tom Haws — хидравличен инженер и автор на тези калкулатори.<br />Използвайте формуляра за обратна връзка на всяка страница с калкулатор или получете достъп до изходния код на <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']="Контакт с HawsEDC";
$ec_lang['contactSendMessage']='Изпратете съобщение на Tom Haws';
$ec_lang['contactYourName']='Вашето име:';
$ec_lang['contactYourEmail']='Вашият e-mail адрес:';
$ec_lang['contactSubject']='Относно:';
$ec_lang['contact_message']='Съобщение:';
$ec_lang['contactSpamPrefix']='Пет плюс едно е равно на';
$ec_lang['contactSpamPostfix']="(Моля, изпишете с думи. 1=едно 2=две 3=три 4=четири 5=пет 6=шест 7=седем +=плюс 5+1=6)";
$ec_lang['contactSubmitButton']='Изпратете съобщението';
$ec_lang['contact_success']='Благодарим ви за времето, което си отделили да напишете.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Проектиране на каменен бързоток (Robinson)';
$ec_lang['rc_main_title']='Безплатен онлайн калкулатор за проектиране на каменен бързоток — Robinson (1998)';
$ec_lang['rc_main_desc']='Оразмеряване на каменна облицовка за бързоток — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Наклон на дъното на бързотока, S<sub>0</sub>';
$ec_lang['rc_qt']='Специфично водно количество, q<sub>t</sub> <span title="Водно количество на единица ширина при входа на бързотока. За канал с ширина на дъното B и общо водно количество Q използвайте q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Порьозност на каменната облицовка, n<sub>p</sub>';
$ec_lang['rc_sg']='Специфично тегло на камъка, sg <span title="Типичен натрошен гранит или базалт ≈ 2,65. Диапазон по Robinson: 2,54 до 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Коефициент на едрозърнестост SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Стандартно отклонение на гранулометричния състав. Еднороден камък ≈ 1,25. Диапазон по Robinson: 1,15 до 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Дълбочина на равномерно течение във входния канал, y<sub>n</sub> <span title="Подпор (Hp > yn) е добре — намалява ерозията нагоре по течението. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Необходим медианен размер на камъка, D<sub>50</sub> <span title="Ур. 1 (S0 < 0,10) или Ур. 2 (0,10–0,40). Валиден: D50 15–278 мм, S0 0,02–0,40. Извън диапазона: екстраполация." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Приложено уравнение';
$ec_lang['rc_sg_check']='Проверка на специфичното тегло';
$ec_lang['rc_SD_check']='Проверка на коефициента на едрозърнестост';
$ec_lang['rc_sg_ok']   ='sg в допустимия диапазон (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Предупреждение: sg < 2,54 — под диапазона на Robinson';
$ec_lang['rc_sg_high'] ='Предупреждение: sg > 2,82 — над диапазона на Robinson';
$ec_lang['rc_SD_ok']   ='SD в допустимия диапазон (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Предупреждение: SD < 1,15 — под диапазона на Robinson';
$ec_lang['rc_SD_high'] ='Предупреждение: SD > 1,47 — над диапазона на Robinson';
$ec_lang['rc_layer']='Дебелина на слоя облицовка (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Радиус на кривата на гребена (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Дължина на дъгата на кривата на гребена';
$ec_lang['rc_apron_length']='Дължина на изходния праг (15 × D<sub>50</sub>) <span title="Необходим за конструктивна опора на камъка на бързотока." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Коефициент на грапавост на Manning в бързотока, n';
$ec_lang['rc_Vm']='Скорост през каменната мантия, V<sub>m</sub> <span title="Дял от q_t, протичащ през порите на камъка. Остатъкът qs тече по повърхността. По подразбиране np = 0,45 за ъглест натрошен камък." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Специфично водно количество през мантията, q<sub>m</sub>';
$ec_lang['rc_qs']='Повърхностно специфично водно количество, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Дълбочина на потока над повърхността на облицовката, d';
$ec_lang['rc_Hp']='Напор на входния праг, H<sub>p</sub> <span title="Подпор (Hp > yn) е добре — намалява ерозията нагоре по течението. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Проверка за подпор при входа';
$ec_lang['rc_pond_ok']  ='Hp > yn — подпор нагоре по течението ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — няма подпор — проверете входа за ерозия';
$ec_lang['rc_eq1']='Ур. 1 (S0 < 0,10) — полегат наклон';
$ec_lang['rc_eq2']='Ур. 2 (0,10 ≤ S0 ≤ 0,40) — стръмен наклон';
$ec_lang['rc_eq_warn_low']='Предупреждение: S0 < 0,02 — под диапазона за валидиране на Robinson';
$ec_lang['rc_eq_warn_high']='Предупреждение: S0 > 0,40 — над диапазона за валидиране на Robinson';
$ec_lang['rc_notes_1_term']='Уравнения за оразмеряване на камъка';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) разработиха две емпирични уравнения за медианен размер на облицовката D<sub>50</sub> въз основа на наклона на бързотока и специфичното водно количество. Уравнение 1 се прилага за полегати наклони (S<sub>0</sub> < 0,10); Уравнение 2 — за стръмни наклони (0,10 ≤ S<sub>0</sub> ≤ 0,40). И двете уравнения изискват q<sub>t</sub> в м²/с и връщат D<sub>50</sub> в мм. Валидираният диапазон е 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Специфично водно количество';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> е общото специфично водно количество при гребена на бързотока (общо водно количество на единица ширина). За канал с ширина на дъното B и общо водно количество Q приближено q<sub>t</sub> ≈ Q / B, или го изчислете от условието за критична дълбочина при входа на бързотока.';
$ec_lang['rc_notes_3_term']='Поток през каменната мантия';
$ec_lang['rc_notes_3_def']='Част от общия дебит преминава през порите на каменната облицовка (дебит през мантията q<sub>m</sub>); остатъкът тече по повърхността на камъка (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Дълбочината на потока d се изчислява по уравнението на Manning за повърхностния дебит q<sub>s</sub> с коефициента на грапавост на бързотока n. Порьозността по подразбиране n<sub>p</sub> = 0,45 е типична за ъглест натрошен камък.';
$ec_lang['rc_notes_5_term']='Допустим диапазон на размера на камъка';
$ec_lang['rc_notes_5_def']='Уравненията са разработени за диапазон D<sub>50</sub> от 15 мм до 278 мм. Резултатите извън този диапазон са екстраполация и трябва да се използват с допълнително инженерно внимание.';
$ec_lang['rc_notes_6_term']='Кота на изходния праг';
$ec_lang['rc_notes_6_def']='Котата на горната повърхност на облицовката в изходния участък трябва да бъде на или под котата на дъното на низходящия канал. Ако е по-висока — изходният камък ще бъде нестабилен.';
$ec_lang['rc_notes_7_term']='Проверка за подпор при входа';
$ec_lang['rc_notes_7_def']='Когато дълбочината на равномерно течение във входния канал е по-малка от напора на прага (H<sub>p</sub>), необходим за пропускане на q<sub>t</sub>, над входния праг възниква стесняване на потока или подпор. Това като цяло е приемливо — подпорът намалява скоростта и предотвратява ерозията нагоре по течението. За проверка: използвайте калкулатор за преливник, намерете H<sub>p</sub> за дадените q<sub>t</sub> и ширина на гребена, след което го сравнете с дълбочината на равномерно течение на входния канал. Ако H<sub>p</sub> надвишава дълбочината на равномерно течение, ще се образува подпор.';
$ec_lang['rc_notes_4_term']='Извор';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS публикува и <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">таблица в Excel</a> по същия метод.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Филтър';
$ec_lang['rc_sketch_top_crest_curve'] = 'Горна крива';
$ec_lang['rc_sketch_outlet_apron']    = 'Изходна плоча';
$ec_lang['rc_sketch_radius']          = 'радиус';
$ec_lang['ip_main_menu']='Налягане при напояване';
$ec_lang['ip_main_title']='Безплатен онлайн калкулатор за налягане при напояване и равномерност на разпределението';
$ec_lang['ip_main_desc']='Оценка на налягането и равномерността на пробния клон';
$ec_lang['ip_h_supply']='Налягане на подаването';
$ec_lang['ip_elev_supply']='Кота на подаването, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Проектен дебит на емитера, q<sub>design</sub>';
$ec_lang['ip_h_design']='Проектно налягане на емитера';
$ec_lang['ip_x']='Показател на степента на дебита на емитера, x <span title="0,5 за стандартни некомпенсиращи емитери; близо до 0 за емитери с компенсация на налягането" class="ec-tip">?</span>';
$ec_lang['ip_reach_table_title']='Пробен път';
$ec_lang['ip_group_reach']='Участък';
$ec_lang['ip_group_upstream']='Нагоре по течението';
$ec_lang['ip_group_downstream']='Надолу по течението';
$ec_lang['ip_group_loss']='Загуба';
$ec_lang['ip_is_lateral']='Лат. <span title="Отметнато: този участък е сегмент от пробния латерал, от който отделните емитери черпят вода. Неотметнато: този участък е главен тръбопровод, който само пропуска дебита към латерали извън пробния път." class="ec-tip">?</span>';
$ec_lang['ip_count']='Емитери <span title="Редове за латерал: емитерите само в този участък. Редове за главен тръбопровод: общият брой емитери на латерали, РАЗЛИЧНИ от този, които се отклоняват от този участък. За участъка на главния тръбопровод, който завършва при пробния латерал, това включва и всички латерали по-нататък по главния тръбопровод след тази точка, както и споделящите същия възел (напр. латерал от срещуположната страна) &mdash; техният дебит също се отклонява от този участък." class="ec-tip">?</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_e']='e <span title="Височина на грапавостта по Дарси-Вайсбах" class="ec-tip">?</span>';
$ec_lang['ip_km']='k<sub>m</sub> <span title="Общ коефициент на местни загуби за фитингите/крановете/съединителите на този участък (&ge;0,5 препоръчителен минимум)" class="ec-tip">?</span>';
$ec_lang['ip_elev_ds']='Долна кота <span title="Кота на долния край на този участък (надолу по течението). Незадължителна за вътрешните редове (по подразбиране хоризонтално / както възела отгоре, ако е оставена празна). Задължителна за последния ред: тази стойност е котата на последния емитер, която пряко определя необходимото налягане на подаване." class="ec-tip">?</span>';
$ec_lang['ip_elev_ds_missing_warn']='Котата на последния емитер (последен ред) беше оставена празна и по подразбиране е зададена хоризонтално &mdash; въведете я за точен резултат';
$ec_lang['ip_flow']='Дебит';
$ec_lang['ip_press']='Наляг.';
$ec_lang['ip_v']='V';
$ec_lang['ip_hv']='H<sub>v</sub>';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='h<sub>L</sub> <span title="Обща загуба в участъка, h_f + h_m" class="ec-tip">?</span>';
$ec_lang['ip_pressure_warn']='Ниско/отрицателно налягане &mdash; проверете за подналягане спрямо атмосферното';
$ec_lang['ip_pressure_warn_short']='Ниско';
$ec_lang['ip_h_far']='Налягане на последния емитер';
$ec_lang['ip_q_supply']='Дебит на подаване по пробния път, Q<sub>supply</sub> <span title="Дебитът, който постъпва само в моделирания пробен път &mdash; за целия обхват на зоната/системата вижте Q_zone в раздела Проектиране на поливането по-долу." class="ec-tip">?</span>';
$ec_lang['ip_q_critical']='Дебит на последния емитер, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Среден дебит на емитер (пробен латерал), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='Оценка на &Delta;налягане, средно спрямо пробния латерал <span title="С колко по-високо (или по-ниско) налягане според вас работи типичен латерал в сравнение с този пробен латерал. Пробният латерал е нарочно предполагаемият най-неблагоприятен случай, затова собствената му средна стойност подценява средната за полето &mdash; ако се остави на 0, проверката за равномерност и числата за проектиране на поливането по-долу използват (вероятно оптимистичната) собствена средна стойност на пробния латерал без корекция." class="ec-tip">?</span>';
$ec_lang['ip_q_avg_field']='Оценен среден дебит на емитер за полето, q<sub>avg,field</sub> <span title="q_avg_lateral, преизчислен при налягането на всеки ред от латерала плюс въведената по-горе разлика в налягането &mdash; опит за корекция на факта, че пробният латерал е предполагаемият най-неблагоприятен случай, а не представителен. Захранва както проверката за равномерност, така и раздела за проектиране на поливането по-долу." class="ec-tip">?</span>';
$ec_lang['ip_du_estimate']='Проверка за равномерност, q<sub>last</sub>/q<sub>avg,field</sub> <span title="Изчисленият дебит на последния емитер, разделен на оценения среден дебит на емитер за полето &mdash; това е приближение на стандартната равномерност на разпределение по долната четвърт (средно на долната група &divide; средно за съвкупността); тук обаче става дума за малка моделирана извадка и оценена от потребителя корекция, а не за пълна статистическа извадка за полето. Стойности, равни на или над 1, са възможни и валидни: те просто означават, че налягането при последния емитер е равно на или над оценената средна стойност за полето, така че друг емитер е точката с най-ниско налягане. Това може да се дължи на това, че последният емитер е на по-ниска кота, или защото оценката на &Delta;налягане е твърде малка." class="ec-tip">?</span>';
$ec_lang['ip_worst_case_warn']='Налягането при пробния емитер е &ge; налягането на подаването. Вероятно това не е емитерът с най-неблагоприятен случай, или тръбите могат да бъдат намалени.';
$ec_lang['ip_q_ratio']='Дебит на последния емитер &divide; проектен дебит, q<sub>last</sub>/q<sub>design</sub> <span title="Това е различно от нашето приближение на стандартния показател за равномерност." class="ec-tip">?</span>';
$ec_lang['ip_no_solution']='Няма решение: необходимото налягане на подаването надвишава въведеното налягане на подаването. Увеличете налягането на подаването, намалете търсенето или използвайте по-голяма тръба.';
$ec_lang['ip_notes_1_term']='Метод';
$ec_lang['ip_notes_1_def']='Предполага се налягането при последния (най-отдалечения) емитер, след което енергийната линия се проследява стъпка по стъпка обратно към подаването, участък по участък, като по пътя се добавят загубите от триене и местните загуби. Котата и скоростният напор се изваждат във всеки възел, за да се получи действителното налягане там. Предположеното налягане в далечния край се коригира (чрез бисекция), докато изчисленото необходимо налягане на подаването съвпадне с въведеното налягане на подаването &mdash; същата затворена задача, която решава решателят за дебит в тръби в калкулатора за дебит в тръби по Manning, разширена до разклонена мрежа.';
$ec_lang['ip_notes_2_term']='Главни спрямо латерални участъци';
$ec_lang['ip_notes_2_def']='Всеки ред е един участък по единствения хидравлично най-неблагоприятен път (пробния път) от подаването до последния емитер. Главен участък само пропуска дебит към латерали извън пробния път, затова неговото водовземане е просто умножение (проектен дебит &times; общия брой емитери на участъка) &mdash; без чувствителност към местното налягане. Главният тръбопровод е споделен ствол, затова участъкът от главния тръбопровод, който завършва при пробния латерал, трябва да включва не само латералите между собствените си краища, но и всички латерали по-нататък по главния тръбопровод след тази точка, както и споделящите същия възел (напр. латерал от срещуположната страна) &mdash; техният дебит преминава през същия участък, преди да се отклони, независимо дали фигурират другаде в тази таблица. Латерален участък е сегмент от самия пробен латерал: дебитът на емитера се изчислява от действителното местно налягане чрез q = k&middot;H<sup>x</sup>, а загубата от триене се намалява с коефициента F(n) на Christiansen, за да се отчете намаляването на дебита с всеки емитер в участъка, който черпи вода.';
$ec_lang['ip_notes_3_term']='Ограничения';
$ec_lang['ip_notes_3_def']='Моделира се едно фиксирано налягане на подаването (без характеристика на помпа), само един пробен път (не цялото поле) и двупараметрова характеристика на емитера (задайте показателя близо до 0, за да приближите емитер с компенсация на налягането). Отчитат се две различни отношения на равномерност, нарочно разделени: q<sub>last</sub>/q<sub>avg,field</sub> е приближение на стандартната равномерност на разпределение по долната четвърт (средно на долната група &divide; средно за съвкупността); но това е от малка моделирана извадка и оценена от потребителя корекция, а не от стандартната пълна статистическа извадка за полето. Освен това пробният латерал е нарочно предполагаемият най-неблагоприятен случай, затова неговата сурова, некоригирана средна стойност би подценила истинската средна за полето и би направила равномерността да изглежда по-добра, отколкото е; входът за &Delta;налягане съществува именно за да противодейства на това отклонение. Стойности на равномерността, равни на или над 1, все пак са възможни: те просто означават, че налягането при последния емитер е равно на или над оценената средна стойност за полето, така че друг емитер е точката с най-ниско налягане. Това може да се дължи на това, че последният емитер е на по-ниска кота, или защото оценката на &Delta;налягане е твърде малка. q<sub>last</sub>/q<sub>design</sub> е различна проверка, несвързана с равномерността, спрямо номиналния дебит на производителя &mdash; полезна за откриване на система с като цяло повишено или понижено налягане, но е отделна проверка, която се чете заедно с показателя за равномерност, тъй като проектният/номиналният дебит е независим от действителното средно работно налягане на системата.';
$ec_lang['ip_notes_4_term']='Справка';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. Стандартите на ASAE/ASABE за проектиране на микронапояване използват същия многоизходен подход за загуба от триене.';
$ec_lang['ip_notes_5_term']='Проектиране на поливането';
$ec_lang['ip_notes_5_def']='Нормата на поливане и дебитът на системата/зоната използват оценения среден дебит на емитер за полето (q<sub>avg,field</sub> &mdash; собствената средна стойност на пробния латерал, коригирана с въведената оценка за &Delta;налягане), а не предполагаема норма: PR = q<sub>avg,field</sub> / A<sub>e</sub>, захранена от коригираната моделирана стойност. Разстоянията и общият брой латерали/емитери за системата са отделни входни данни тук, защото пробният път моделира само един клон с най-неблагоприятен случай, а не всеки латерал в полето.';
