<?php

// Alh missing text declarations wilh falh back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fração";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']='% incl./compr.';
$ec_lang['u_grade']="incl./compr.";
$ec_lang['u_in2']="sq. in.";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="L/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="ML/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="segundos (seg)";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Calculadoras HawsEDC';
$ec_lang['menu_main_list']='Lista de calculadoras';
$ec_lang['menu_main_hydraulics']='Hidráulica';
$ec_lang['menu_main_language']='Idioma';
$ec_lang['menu_more']='Mais';
$ec_lang['template_welcome']='>> Deixe seus medos na porta. O amor é falado aqui. Você não está arruinando tudo. Aproveite também <a target="_blank" href="https://hawsedc.com/download.php">as ferramentas livres HawsEDC para AutoCAD</a>.<<';
$ec_lang['template_translation_help']='Você tem uma ótima ideia para uma calculadora a ser adicionada aqui?  Você pode me ajudar a traduzir esta calculadora para sua língua ou hostear esta calculadora em seu site?';
$ec_lang['template_feedback']='Por favor, dê-nos suas valiosas palavras de sugestão ou elogio. Esta calculadora gratuita excedeu suas expectativas em todos os aspectos?';
$ec_lang['template_printable_title']='Título imprimível';
$ec_lang['template_printable_subtitle']='Subtítulo imprimível';
$ec_lang['index_title']='Calculadoras de Engenharia Gratuitas Online';
$ec_lang['calc_set_units']='Definir unidades:';
$ec_lang['calc_defaults']='Valores padrão';
$ec_lang['calc_defaults_confirm']='Restaurar calculadora aos valores padrão originais?';
$ec_lang['points_data_help']='(ou Copiar/Colar usando a área de dados)';
$ec_lang['points_data_title']='Dados dos pontos<br />(separados por vírgula ou tabulação)';
$ec_lang['points_data_copy']='Copiar';
$ec_lang['points_data_paste']='Colar';
$ec_lang['calc_inputs']='Entradas';
$ec_lang['calc_results']='Resultados';
$ec_lang['view_hide_line']='[Ocultar esta linha]';
$ec_lang['view_printable']='Versão Imprimível (recarregar/renovar para restaurar)';
$ec_lang['ec_name_label']='Salvar este cálculo:';
$ec_lang['ec_name_placeholder']='Nome';
$ec_lang['ec_name_hint']='Salva esses valores na URL para favoritos, recuperação do histórico e compartilhamento';
$ec_lang['calc_copy_link']='Copiar link';
$ec_lang['calc_copy_link_done']='Copiado!';
$ec_lang['ec_related_calcs']='Calculadoras relacionadas:';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Perda de carga em tubulação por Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculadora gratuita online de perda de carga em tubulação por Darcy-Weisbach';
$ec_lang['dw_main_desc']='Perda de carga em tubulação para diâmetro, rugosidade e vazão informados, por Darcy-Weisbach';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Altura de rugosidade absoluta, e, da parede da tubulação. Valores típicos: aço (novo) 0,046 mm, aço (usado) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, concreto 0,3–3 mm.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s para água limpa a 20°C">Viscosidade cinemática, &nu; <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Viscosidade cinemática, &nu;';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s para água limpa a 20°C';
$ec_lang['dw_reynolds_number']='Número de Reynolds, Re';
$ec_lang['dw_flow_regime']='Regime de escoamento';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='de transição';
$ec_lang['dw_regime_turbulent']='turbulento';
$ec_lang['dw_friction_factor_method']='Método do fator de atrito';
$ec_lang['dw_friction_factor']='Fator de atrito, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Perda de carga em tubulação por Hazen-Williams';
$ec_lang['hw_main_title']='Calculadora gratuita online de perda de carga em tubulação por Hazen-Williams';
$ec_lang['hw_main_desc']='Perda de carga em tubulação para diâmetro, coeficiente C e vazão informados, por Hazen-Williams';
$ec_lang['hw_hgl_1']='LP a jusante';
$ec_lang['hw_hgl_2']='LP a montante';
$ec_lang['hw_roughness']='Coeficiente de Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canal de seção irregular de acordo com Manning';
$ec_lang['mi_main_title']='Calculadora gratuita online de canal de seção irregular de acordo com Manning';
$ec_lang['mi_main_desc']='Calculadora de escoamento uniforme de Manning para canal de seção irregular';
$ec_lang['mi_waterSurfaceElevation']='Nível da superfície d\'água';
$ec_lang['mi_q_617']='<span class="ec-help" title="A vazão composta, Q, usando um n composto para cada região de acordo com Chow 6-17, velocidades iguais">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Pontos da seção transversal';
$ec_lang['mi_groupPoint']='Ponto';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_groupRegion']='Região';
$ec_lang['mi_station']='Est.';
$ec_lang['mi_elevation']='Alt.';
$ec_lang['mi_d50in']='Tamanho<br />mediano<br />de rocha<br />de revestimento';
$ec_lang['mi_n']='n<br />do seg-<br />mento';
$ec_lang['mi_is_bank']='Div. de<br />regiões<br />R<sub>h</sub>, Q<br />(Margem)';
$ec_lang['mi_tau']='Cisalh. de<br />fundo, τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Comp.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='n composto';
$ec_lang['mi_notes_1_def']='Esta calculadora segue o Manual de Referência do HEC-RAS ao calcular o n composto da região usando Chow (1959), página 136, equação 6-17 (não 6-18).';
$ec_lang['mi_notes_2_term']='Revestimento de rocha';
$ec_lang['mi_notes_2_def']='Use a Calculadora de Canal Trapecial de Manning para dimensionar o revestimento de rocha. Esta calculadora é mais adequada a seções naturais.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Vazão em tubulação por Manning';
$ec_lang['mpf_main_title']='Calculadora gratuita online da fórmula de Manning para vazão em tubulação';
$ec_lang['mpf_main_desc']='Escoamento uniforme pela Fórmula de Manning para declividade e profundidade informadas';
$ec_lang['mpf_spreadheet_notice']='Planilha de Escoamento em Tubulação (Manning)';
$ec_lang['mpf_pipe_diameter']='Diâmetro da tubulação, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Coeficiente de rugosidade de Manning, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Declividade de atrito, S<sub>f</sub></a><span class="ec-help" title="Às vezes igual à declividade da tubulação. Siga o link para a explicação (somente em inglês)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Profundidade relativa do escoamento, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Vazão, Q';
$ec_lang['mpf_flow_tip']='Vazão e profundidade calculadas para uma tubulação infinitamente longa. Para que essa vazão realmente entre na tubulação, pode ser necessária uma profundidade de montante maior. Veja as Notas abaixo para detalhes e um vídeo tutorial.';
$ec_lang['mpf_velocity']='Velocidade, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="Energia cinética como uma altura de coluna de água, v&sup2;/2g">Carga de velocidade, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='Área do escoamento, A';
$ec_lang['mpf_pipe_area']='Área da tubulação, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Área relativa, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Perímetro molhado, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Raio hidráulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Largura superior, T';
$ec_lang['mpf_froude_number']='Número de Froude, Fr';
$ec_lang['mpf_shear_stress']='Tensão de cisalhamento média, &tau;';
$ec_lang['mpf_full_flow']='Vazão a seção plena, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Razão em relação à seção plena, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Este é o escoamento e a profundidade no interior de uma tubulação <em>infinitamente longa</em>.</dt><dd>Fazer o escoamento entrar na tubulação pode exigir uma profundidade de água significativamente maior. Acrescente pelo menos 1,5 vezes a carga de velocidade para obter a profundidade de água a montante ou <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">veja meu tutorial de 2 minutos</a> sobre cálculos padrão de nível de água em bueiros usando HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Calcular y/d<sub>0</sub> para um Q dado';
$ec_lang['mpf_solve_desc']='Usando d<sub>0</sub>, n e S<sub>f</sub> do formulário da calculadora, encontra o menor y/d<sub>0</sub> para um Q dado.';
$ec_lang['mpf_solve_button']='Calcular';
$ec_lang['mpf_solver_enter_positive_q']='Informe um Q alvo positivo.';
$ec_lang['mpf_solver_no_solution']='Sem solução: Q excede a capacidade da tubulação em y/d0 = 93.8% (Qmax = {qmax} nas unidades selecionadas).';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Perda de carga em tubulação por Manning';
$ec_lang['mphl_main_title']='Calculadora gratuita online de perda de carga em tubulação por Manning';
$ec_lang['mphl_main_desc']='Perda de carga pela Fórmula de Manning para vazão a seção plena informada';
$ec_lang['mphl_pipe_length']='Comprimento, L';
$ec_lang['mphl_area']='Área, A';
$ec_lang['mphl_total_junction_k']='Coeficiente de perda localizada, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Coeficiente de perda, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Coeficiente de perda de carga localizada (menor), k<sub>m</sub>. Essas perdas ocorrem em junções de tubulação, entradas, saídas, curvas e válvulas — o termo "menor" é convencional, mas enganoso; em uma linha curta, elas podem igualar ou superar as perdas por atrito. Valores típicos de k: entrada de aresta viva 0,5, cada curva de 45° 0,2–0,3, válvula gaveta (totalmente aberta) 0,1, válvula borboleta 0,2, saída (para reservatório ou atmosfera) 1,0. Some todas as conexões para obter o k<sub>m</sub> total. O valor padrão 2,0 pressupõe uma entrada, uma saída e duas curvas de 45°.';
$ec_lang['mphl_friction_slope']='Declividade de atrito';
$ec_lang['mphl_friction_loss']='Perda de carga por atrito, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Perda de carga localizada, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Perda total, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='LE a jusante';
$ec_lang['mphl_egl_2']='LE a montante';
$ec_lang['mphl_hgl_egl_tip']='Pode não ser válido se a tubulação estiver elevada. Veja as notas.';
$ec_lang['mphl_note_1']='<dl><dt>Esta calculadora não considera a elevação da tubulação.</dt><dd>Se a LP ficar abaixo do topo da tubulação em algum ponto, este cálculo pode não ser válido.</dd><dt>Para uma condição de entrada aberta (bueiro), é necessário verificar as condições de controle de entrada.</dt><dd>1. A LP a montante deve estar acima da elevação do escoamento à profundidade normal a montante (e acima da tubulação!).</dd><dd>2. O nível de água a montante de um bueiro é melhor representado pela LE a montante do que pela LP a montante.</dd><dd>3. Veja <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">meu tutorial de 2 minutos</a> para cálculos simples de nível de água em bueiros usando HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapezoidal de acordo com Manning';
$ec_lang['mtc_main_title']='Calculadora gratuita online da fórmula de Manning para canal trapezoidal';
$ec_lang['mtc_main_desc']='Escoamento uniforme de Manning em canal trapezoidal à declividade e profundidade dadas';
$ec_lang['mtc_bottom_width']='Largura da base, b';
$ec_lang['mtc_side_slope_1']='Declividade do lado 1, z<sub>1</sub> (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Declividade do lado 2, z<sub>2</sub> (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Declividade do canal, S';
$ec_lang['mtc_flow_depth']='Profundidade do escoamento, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Ângulo da curva, β</a><span class="ec-help" title="Para o tamanho de rocha. Siga o link para o diagrama."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Densidade relativa à água. Tipicamente &asymp; 2,65 para rocha britada">Densidade relativa da rocha, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Tamanho de rocha de projeto, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n para o tamanho de rocha de projeto (método de Strickler)';
$ec_lang['mtc_n_blodgett']='n para o tamanho de rocha de projeto (método de Blodgett)';
$ec_lang['mtc_n_bathurst']='n para o tamanho de rocha de projeto (método de Bathurst)';
$ec_lang['mtc_n_pi']='n para o tamanho de rocha de projeto (método de Phillips & Ingersoll)';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett x Bathurst';
$ec_lang['mtc_pi_range_check']='Verificação da faixa P&I';
$ec_lang['mtc_pi_ok']='d50 dentro da faixa P&I';
$ec_lang['mtc_pi_ok_tip']='0.28–0.36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='Fora da faixa';
$ec_lang['mtc_pi_tip']='Extrapolação além da faixa de dados de 0.28–0.36 ft usada para desenvolver esta equação — considere como uma verificação aproximada, não uma base de projeto';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Segundo Isbash (1936) e o Condado de Maricopa, Arizona, EUA.">Tamanho de rocha angular requerido no fundo, D<sub>50</sub> (Isbash e MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Segundo Isbash (1936) e o Condado de Maricopa, Arizona, EUA.">Tamanho de rocha angular requerido no lado 1, D<sub>50</sub> (Isbash e MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Segundo Isbash (1936) e o Condado de Maricopa, Arizona, EUA.">Tamanho de rocha angular requerido no lado 2, D<sub>50</sub> (Isbash e MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Tamanho de rocha angular requerido, D<sub>50</sub> (Maynord, Ruff e Abt 1989)';
$ec_lang['mtc_d50_searcy']='Tamanho de rocha angular requerido, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='Velocidade razoável para as hipóteses de escoamento uniforme.';
$ec_lang['mtc_vel_low']='Velocidade baixa; risco de sedimentação.';
$ec_lang['mtc_iteration_tip']='Escolha uma opção de rugosidade (recomenda-se Blodgett–Bathurst) e uma opção de tamanho de rocha (recomenda-se Isbash) para que a calculadora itere automaticamente até um tamanho de rocha uniforme para a vazão desejada. Veja as Notas abaixo para o método completo, ou digite seu próprio valor de rugosidade (siga o link para orientação) e ignore o tamanho de rocha para pular a iteração.';
$ec_lang['mtc_note_1']='<dl><dt>Iteração automatizada de dimensionamento de rocha e rugosidade</dt><dd>Escolha uma opção de rugosidade (recomenda-se Blodgett–Bathurst) e uma opção de tamanho de rocha de projeto (recomenda-se Isbash). Ajuste a profundidade e o fator de segurança do tamanho de rocha para atingir a vazão desejada com um tamanho de rocha uniforme. A cada alteração de um valor de entrada, a calculadora repete estas etapas: 1. A rugosidade é calculada a partir do tamanho de rocha de projeto. 2. O cálculo de rugosidade solicitado é copiado para a rugosidade de entrada. 3. A vazão do canal e o tamanho de rocha requerido são calculados. 4. O tamanho de rocha de projeto é ajustado. 5. Repete-se até que o erro no tamanho de rocha de projeto seja muito pequeno.</dd><dt>Calculadora básica (sem iteração)</dt><dd>Digite o valor de rugosidade desejado. Ignore a área de entrada do tamanho de rocha de projeto.</dd></dl>';
$ec_lang['mtc_note_2_term']='Verificação de velocidade';
$ec_lang['mtc_note_2_def']='Velocidade alta implica que houve uma grande queda de elevação, que gerou essa energia específica elevada. Essa energia pode se dissipar rapidamente em expansões, curvas ou obstruções. Verifique se isso é razoável para o local.';
$ec_lang['mtc_solve_for_y']='Determinar a profundidade, y, dada Q';
$ec_lang['mtc_solve_desc']='Usando b, z<sub>1</sub>, z<sub>2</sub>, S e n do formulário da calculadora, encontra a profundidade para uma vazão Q dada.';
$ec_lang['mtc_solver_no_solution']='Nenhuma solução encontrada para a vazão Q dada com estas entradas do canal.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Vertedor Simples';
$ec_lang['ws_main_title']='Calculadora Gratuita Online de Vazão em Vertedor Simples de Soleira Larga';
$ec_lang['ws_main_desc']='Calculadora de Vazão em Vertedor Simples de Soleira Larga';
$ec_lang['ws_weirLength']='Comprimento do vertedor, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="Energia por unidade de peso de água — uma altura da coluna de água, não uma pressão">Carga, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='Coeficiente do vertedor, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Notas';
$ec_lang['ws_notes_we_term']='Equação do Vertedor';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Vertedor Irregular';
$ec_lang['wi_main_title']='Calculadora Gratuita Online de Vazão em Vertedor Irregular Segmentado de Profundidade Variável';
$ec_lang['wi_main_desc']='Calculadora de Vazão em Vertedor Irregular';
$ec_lang['wi_weirPoints']='Pontos do vertedor';
$ec_lang['wi_pondingHeight']='Altura de represamento';
$ec_lang['wi_incrementalFlow']='Vazão incremental';
$ec_lang['wi_cumulativeFlow']='Vazão acumulada';
$ec_lang['wi_save_and_calculate']='Gravar e calcular';
$ec_lang['wi_notes_we_def']='q = se (comprimento = 0) então 0 senão se (declividade=0) então cw*comprimento*d<sub>0</sub><sup>1.5</sup> senão cw/(2.5*declividade) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) onde d<sub>1</sub> e d<sub>0</sub> são sempre positivos ou zero';
// Orifice Flow
$ec_lang['or_main_menu']='Vazão por Orifício';
$ec_lang['or_main_title']='Calculadora Gratuita Online de Vazão por Orifício';
$ec_lang['or_main_desc']='Vazão por Orifício — Livre ou Submersa';
$ec_lang['or_shape']='Forma da abertura';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Retangular';
$ec_lang['or_diameter']='<span class="ec-help" title="Diâmetro para circular; altura para retangular">Diâmetro ou altura, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Apenas para aberturas retangulares">Largura, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Fundo da abertura">Cota da soleira <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Nível d\'água a montante';
$ec_lang['or_twe']='Nível d\'água a jusante';
$ec_lang['or_cd']='Coeficiente de descarga, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Cota do centroide';
$ec_lang['or_head']='<span class="ec-help" title="Energia por unidade de peso de água — uma altura da coluna de água, não uma pressão">Carga efetiva, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='Área da abertura, A';
$ec_lang['or_regime']='Verificação do regime de orifício';
$ec_lang['or_regime_valid']='Saída livre';
$ec_lang['or_regime_submerged']='Orifício submerso';
$ec_lang['or_regime_submerged_tip']='TWE acima do centroide — regime de orifício ainda válido';
$ec_lang['or_regime_warn']='Fora do regime de orifício';
$ec_lang['or_regime_warn_tip']='Nível a montante abaixo do topo da abertura';
$ec_lang['or_regime_twe_above_hwe']='Verifique as entradas';
$ec_lang['or_regime_twe_above_hwe_tip']='Nível de jusante (TWE) acima do nível de montante (HWE)';
$ec_lang['or_notes_1_term']='Equação do Orifício';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Para saída livre: h = HWE &minus; centroide. Para escoamento submerso (TWE acima da soleira): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regime de Orifício';
$ec_lang['or_notes_2_def']='As equações de vazão por orifício aplicam-se quando o nível a montante está acima do topo da abertura. Quando o nível a montante está abaixo do topo, utilize uma equação de vertedor.';
$ec_lang['or_notes_3_term']='Coeficiente de Descarga';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varia entre 0,60 e 0,65 para orifícios de borda viva. Entradas arredondadas ou reentrantes utilizam valores diferentes. Consulte o <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ou o Manual de Referência Hidráulica do HEC-RAS para orientação.';
$ec_lang['or_notes_4_term']='Submersão';
$ec_lang['or_notes_4_def']='Quando o TWE está acima da soleira da abertura, esta calculadora aplica automaticamente a equação de orifício submerso, usando h = HWE &minus; TWE. Quando o TWE é igual ou inferior à soleira, assume-se saída livre e h = HWE &minus; centroide.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hidroelétrica';
$ec_lang['mhp_main_title']='Calculadora Gratuita de Potência Micro-Hidroelétrica';
$ec_lang['mhp_main_desc']='Calculadora de Potência de Micro-Hidroelétrica a Fio d\'Água';
$ec_lang['mhp_gross_head']='Altura bruta, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diâmetro da conduta forçada, D';
$ec_lang['mhp_length']='Comprimento, L';
$ec_lang['mhp_efficiency']='Rendimento da instalação, η (0–1)';
$ec_lang['mhp_vel_check']='Verificação da velocidade';
$ec_lang['mhp_hl_check']='Verificação da perda de carga';
$ec_lang['mhp_hnet']='Altura líquida, H<sub>net</sub>';
$ec_lang['mhp_power']='Potência produzida, P';
$ec_lang['mhp_annual_kwh']='Energia anual a 100% de capacidade';
$ec_lang['mhp_vel_low']='Velocidade baixa — risco de sedimentação e arrastamento de ar.';
$ec_lang['mhp_vel_high']='Velocidade elevada — verificar perdas de transição, energia disponível e golpe de aríete.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Alto';
$ec_lang['mhp_vel_low_short']='Baixo';
$ec_lang['mhp_vel_ok_tip']='A velocidade está na faixa eficiente para o projeto da conduta forçada.';
$ec_lang['mhp_hl_ok_tip']='Dentro da meta de 10% — econômico.';
$ec_lang['mhp_hl_warn_tip']='Excede a meta de 10%. Considere uma tubulação maior.';
$ec_lang['mhp_hl_bad_tip']='Excede a meta de 20%. Redimensione a tubulação.';
$ec_lang['mhp_notes_1_term']='Perda de carga';
$ec_lang['mhp_notes_1_def']='Perda total na conduta forçada h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, onde h<sub>f</sub> = f(L/D)(v²/2g) é a perda por atrito de Darcy-Weisbach e h<sub>m</sub> = k<sub>m</sub>·v²/2g cobre entradas, curvas e válvulas. Altura líquida H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Velocidade';
$ec_lang['mhp_notes_2_def']='Verifique se a velocidade é razoável para o desnível disponível e o custo da tubulação. Velocidade muito baixa pode indicar tubulação sobredimensionada; velocidade muito alta pode aumentar as perdas por atrito e o risco de golpe de aríete.';
$ec_lang['mhp_notes_3_term']='Objetivo de perda de carga';
$ec_lang['mhp_notes_3_def']='Perdas na conduta forçada inferiores a 10% da altura bruta são geralmente econômicas. O equilíbrio ótimo entre o custo da tubulação e a potência perdida situa-se frequentemente entre 4–6% para locais com eletricidade de alto valor.';
$ec_lang['mhp_notes_6_term']='Rendimento';
$ec_lang['mhp_notes_6_def']='Rendimento típico da instalação η varia de 0,70 a 0,85 para turbinas Pelton e de fluxo cruzado comuns em micro-hidroelétricas. Use 0,75 como uma estimativa conservadora inicial.';
$ec_lang['mhp_notes_7_term']='Energia Anual';
$ec_lang['mhp_notes_7_def']='A energia anual pressupõe operação contínua a pleno escoamento (8760 horas/ano). A produção real será menor devido a variação sazonal de escoamento, tempo de paragem para manutenção e fator de carga.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Tempo de Esvaziamento por Orifício';
$ec_lang['odt_main_title']='Calculadora Gratuita Online de Tempo de Esvaziamento por Orifício — Lagoa, Bacia ou Tanque';
$ec_lang['odt_main_desc']='Tempo de Esvaziamento de Lagoa ou Bacia por Orifício &mdash; Método do Volume Cônico';
$ec_lang['odt_h1_elev']='Cota inicial da superfície d\'água';
$ec_lang['odt_a1']='Área inicial, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Cota final da superfície d\'água';
$ec_lang['odt_a0']='Área no nível do orifício, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Interpolada a partir do modelo cônico na cota final">Área final, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Verificação da cota final';
$ec_lang['odt_h2_ok']='Cota final acima do topo do orifício';
$ec_lang['odt_h2_warn']='Cota final igual ou abaixo do topo do orifício';
$ec_lang['odt_h2_warn_tip']='Topo do orifício = centroide + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Diâmetro (circular) ou altura (retangular)">Orifício D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Apenas retangular">Largura do orifício, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Tempo de esvaziamento (s)';
$ec_lang['odt_t_min']='Tempo de esvaziamento (min)';
$ec_lang['odt_t_hr']='Tempo de esvaziamento (h)';
$ec_lang['odt_t_day']='Tempo de esvaziamento (dias)';
$ec_lang['odt_notes_1_term']='Fórmula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) fornece o tempo de esvaziamento da carga H até o orifício. Tempo de esvaziamento = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), onde H<sub>1</sub> = cota inicial &minus; cota do orifício, H<sub>2</sub> = cota final &minus; cota do orifício.';
$ec_lang['odt_notes_2_term']='Método';
$ec_lang['odt_notes_2_def']='O método do volume cônico modela a lagoa ou bacia como uma seção cônica entre a área inicial A<sub>1</sub> na superfície inicial da água e a área A<sub>0</sub> na cota do centroide do orifício. A<sub>2</sub>, a área da lagoa na cota final, é interpolada a partir de A<sub>1</sub> e A<sub>0</sub> usando o modelo de seção cônica. O tempo de esvaziamento da cota inicial até a cota final é igual ao tempo total de esvaziamento de H<sub>1</sub> até o orifício menos o tempo restante de H<sub>2</sub> até o orifício.';
$ec_lang['odt_h1']='<span class="ec-help" title="Cota inicial da superfície d\'água menos a cota do centroide do orifício">Carga inicial, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Vazão máxima, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume esvaziado';
$ec_lang['odt_sketch_start']='Início';
$ec_lang['odt_sketch_end']='Fim';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Irrigação';
$ec_lang['irr_main_title']='Calculadoras Online Gratuitas de Medição de Vazão de Irrigação';
$ec_lang['irr_main_desc']='Medição de Vazão de Irrigação — Vertedouros e Orifícios';
$ec_lang['irr_intro_html']='<p>Vertedouros e orifícios são as ferramentas de campo padrão para medir o fluxo de água em sistemas de irrigação. Selecione a calculadora que corresponde à sua estrutura:</p>';
$ec_lang['irr_card_weir_uniform_head']='Vertedouro — Crista Larga (Largura Uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Meça o fluxo sobre a crista de uma barragem de desvio, estrutura de controle ou prancha vertedora. Insira o comprimento do vertedouro e a profundidade da água acima da crista.';
$ec_lang['irr_card_weir_irregular_head']='Vertedouro — Perfil Irregular';
$ec_lang['irr_card_weir_irregular_desc']='Use quando a crista do vertedouro não tiver uma elevação uniforme única — vertedouros naturais, estruturas de queda com largura variável ou estruturas de controle de múltiplas seções.';
$ec_lang['irr_card_orifice_head']='Orifício — Comporta de Cabeçal ou Saída de Tubulação';
$ec_lang['irr_card_orifice_desc']='Meça o fluxo através de uma comporta deslizante, saída de tubulação ou abertura de bueiro. Trata automaticamente tanto a descarga livre quanto as condições submersas (contrapressão de jusante).';
$ec_lang['irr_card_canal_head']='Projeto & Análise de Canal';
$ec_lang['irr_card_canal_desc']='Projete ou verifique um canal de irrigação usando a fórmula de Manning. Use a calculadora Trapezoidal para novos canais; a calculadora Irregular para seções naturais ou construídas existentes.';
$ec_lang['irr_card_seepage_head']='Infiltração em Canal & Eficiência de Condução';
$ec_lang['irr_card_seepage_desc']='Estime a perda por infiltração em um trecho de canal usando medições de entrada e saída. Calcule a eficiência de condução e a perda anual de água para ajudar a priorizar investimentos em revestimento.';
$ec_lang['irr_card_pressure_head']='Pressão de Irrigação & Uniformidade';
$ec_lang['irr_card_pressure_desc']='Modele o perfil de pressão e vazão ao longo de um ramal principal-lateral-emissor para estimar a uniformidade de distribuição a partir da pressão real do caminho de teste, não apenas uma vazão nominal de catálogo do emissor.';
$ec_lang['irr_quickref_html']='<h3>Referência Rápida</h3><dl><dt>Barragem de desvio ou estrutura de controle</dt><dd>Meça a profundidade da água acima da crista do vertedouro. Use <a href="Weir-Flow-Simple.php">Vertedouro Simples</a> para uma crista uniforme, ou <a href="Weir-Flow-Irregular.php">Vertedouro Irregular</a> para uma crista perfilada ou escalonada.</dd><dt>Comporta de cabeçal ou saída de tubulação</dt><dd>Meça a elevação da água a montante e a jusante (ou a cota de fundo se a descarga for livre). Use <a href="Orifice.php">Fluxo por Orifício</a>. Para uma tubulação circular, D = diâmetro da tubulação; para uma comporta retangular, insira a largura W e a altura D.</dd><dt>Tempo de esvaziamento de reservatório ou lagoa</dt><dd>Use <a href="Orifice-Drain-Time.php">Tempo de Drenagem por Orifício</a> para estimar quanto tempo leva para baixar o nível de uma lagoa ou reservatório através de um orifício no fundo — útil para o planejamento do armazenamento de irrigação.</dd><dt>Padrões de campo</dt><dd>As equações de fluxo por vertedouro e orifício usadas aqui correspondem aos procedimentos do <em>Manual de Medição de Água</em> (3.ª ed.) do USBR, comumente exigidos por administradores de água e distritos de irrigação.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Espaçamento de emissores, S<sub>e</sub>';
$ec_lang['ip_sl']='Espaçamento de laterais, S<sub>l</sub>';
$ec_lang['ip_n_e']='Emissores por lateral, n<sub>e</sub>';
$ec_lang['ip_n_l']='Laterais por setor, n<sub>l</sub>';
$ec_lang['ip_d']='Lâmina de aplicação desejada, d';
$ec_lang['ip_a_e']='Área por emissor, A<sub>e</sub>';
$ec_lang['ip_pr']='Taxa de aplicação, PR';
$ec_lang['ip_q_lat']='Vazão por lateral, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Vazão do setor, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Tempo de funcionamento (horas)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Infiltração em Canal';
$ec_lang['cs_main_title']='Calculadora Gratuita Online de Perda por Infiltração e Eficiência de Condução em Canal';
$ec_lang['cs_main_desc']='Perda por Infiltração em Canal & Eficiência de Condução — Método de Entrada-Saída';
$ec_lang['cs_Q_in']='Vazão entrada, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Vazão saída, Q<sub>out</sub>';
$ec_lang['cs_L']='Comprimento do trecho, L';
$ec_lang['cs_Q_loss']='Taxa de perda por infiltração, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verificação de medição';
$ec_lang['cs_pct_loss']='Fração perdida';
$ec_lang['cs_Ec']='Eficiência de condução, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Classificação de eficiência';
$ec_lang['cs_Vol_day']='Volume diário perdido';
$ec_lang['cs_Vol_year']='Volume anual perdido';
$ec_lang['cs_Q_loss_per_L']='Perda por unidade de comprimento, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valor da água';
$ec_lang['cs_lining_cost']='Custo de revestimento';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Objetivo de eficiência de condução após revestimento; fração 0–1">Objetivo de revestimento, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Área de revestimento, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valor anual perdido';
$ec_lang['cs_annual_value_recovered']='Valor anual recuperado';
$ec_lang['cs_lining_total_cost']='Custo total de revestimento';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Retorno simples = custo total de revestimento ÷ valor anual recuperado">Período de retorno <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — infiltração detectada';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — sem perda mensurável';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — verificar medições';
$ec_lang['cs_Ec_good']='Boa — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Regular — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Ruim — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='O método de entrada-saída estima a infiltração medindo a vazão na entrada e na saída de um trecho de canal: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Eficiência de condução E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. O volume anual pressupõe operação contínua a plena vazão; a perda real é menor em canais sazonais ou com vazão parcial.';
$ec_lang['cs_notes_2_term']='Classificações de Eficiência';
$ec_lang['cs_notes_2_def']='Canais de terra sem revestimento típicos: E<sub>c</sub> = 60–80%. Canais de terra bem mantidos: 75–85%. Canais revestidos em concreto: 90–98%. Perdas por infiltração acima de 30% da vazão de entrada frequentemente justificam o investimento em revestimento. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Retorno de Investimento em Revestimento';
$ec_lang['cs_notes_3_def']='Insira o valor da água e o custo de revestimento em qualquer moeda coerente. Área de revestimento = comprimento do trecho × perímetro molhado — o perímetro molhado da seção do canal na profundidade de escoamento medida (largura de fundo mais ambos os taludes molhados). Valor anual recuperado pressupõe que o canal revestido atinge continuamente o E<sub>c</sub> alvo. O retorno real será mais longo para canais sazonais ou se o revestimento não atingir a eficiência alvo.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3.ª ed. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='Sobre';
$ec_lang['install_main_menu']='Instalar';
$ec_lang['install_main_title']='Instalar EngCalcs';
$ec_lang['install_main_desc']='Adicionar ao dispositivo para uso offline';
$ec_lang['install_intro']='O EngCalcs é um Aplicativo Web Progressivo (PWA). Depois de instalado, todas as calculadoras funcionam totalmente offline — sem necessidade de conexão com a internet.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Abra qualquer página de calculadora no Chrome.</li><li>Toque no botão <strong>⬇ Instalar</strong> na barra de navegação superior, ou toque no menu do navegador (⋮) e escolha <strong>Adicionar à tela inicial</strong>.</li><li>Toque em <strong>Instalar</strong> na janela que aparecer.</li><li>O EngCalcs aparece na sua tela inicial e funciona offline.</li>';
$ec_lang['install_now_btn']='⬇ Instalar Agora';
$ec_lang['install_prompt_unavailable']='Solicitação de instalação indisponível — use o menu do seu navegador.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Abra qualquer página de calculadora no Safari.</li><li>Toque no botão <strong>Compartilhar</strong> (ícone de caixa com seta para cima).</li><li>Role para baixo e toque em <strong>Adicionar à Tela de Início</strong>.</li><li>Toque em <strong>Adicionar</strong>. O EngCalcs aparece na sua tela inicial.</li>';
$ec_lang['install_ios_note']='No iOS, a instalação sempre usa o menu Compartilhar — não há solicitação automática de instalação.';
$ec_lang['install_desktop_heading']='Computador (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Abra qualquer página de calculadora.</li><li>Clique no <strong>ícone de instalação</strong> (⊕ ou ícone de computador) na barra de endereço do navegador, ou abra o menu do navegador e escolha <strong>Instalar EngCalcs…</strong></li><li>Clique em <strong>Instalar</strong>. O EngCalcs abre como uma janela de aplicativo independente.</li>';
$ec_lang['install_firefox_heading']='Firefox / Outros Navegadores';
$ec_lang['install_firefox_body']='O Firefox não oferece suporte à instalação de PWAs em computadores. Você ainda pode usar todas as calculadoras normalmente no navegador — após sua primeira visita, as páginas são armazenadas em cache automaticamente para uso offline.';
$ec_lang['install_cached_heading']='O Que Fica Armazenado em Cache';
$ec_lang['install_cached_body']='Na primeira vez que você instala o EngCalcs, todas as páginas de calculadoras e seus arquivos de suporte (scripts, estilos) são salvos automaticamente no seu dispositivo. Depois disso, tudo funciona sem conexão com a internet. Sua escolha de idioma é lembrada desde sua última visita online.';
$ec_lang['contact_main_menu']='Contato';
$ec_lang['about_main_title']='Sobre as calculadoras de engenharia HawsEDC';
$ec_lang['about_main_desc']='Missão, código aberto e contribuições';
$ec_lang['about_body_html']='<h3>Missão</h3><p>As Calculadoras de Engenharia HawsEDC existem para servir engenheiros e trabalhadores de campo em todo o mundo — especialmente aqueles que trabalham em regiões com escassez de água, recursos limitados ou pouco atendidas. Essas ferramentas fazem parte de uma missão humanitária mais ampla: dizer a cada ser humano da maneira mais prática e eficaz possível que é amado e prezado para sempre, que não tem nada a temer e que não vai arruinar tudo.</p><p>As calculadoras são o veículo. O destino é um mundo livre de sofrimento.</p><h3>Licença de Código Aberto</h3><p>Todo o código é lançado sob a <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licença Pública Geral GNU v3.0 ou posterior</a> — livre como em liberdade. Você pode usar, estudar, modificar e redistribuir o código sob os mesmos termos.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Código Fonte</h3><p>O código fonte completo está disponível publicamente no Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Você pode navegar pelo código, registrar problemas ou fazer um fork do repositório lá.</p><h3>Contribuir</h3><p>Pull requests são bem-vindos. Formas de contribuir:</p><ul><li><strong>Traduções</strong> — melhore ou adicione um idioma. Abra um pull request com alterações no arquivo <code>lib/lang.ec.??.php</code> relevante.</li><li><strong>Relatórios de erros</strong> — use o formulário de feedback em qualquer página de calculadora, ou registre um problema no Bitbucket.</li><li><strong>Novas calculadoras</strong> — ideias para ferramentas de engenharia hidráulica que sirvam a trabalhadores de campo e profissionais de irrigação são especialmente bem-vindas. Consulte o guia do desenvolvedor <code>CLAUDE.md</code> no repositório.</li><li><strong>Hospedagem</strong> — se você pode espelhar essas calculadoras para uma região com conectividade limitada, entre em contato.</li></ul><h3>Uso offline</h3><p>Estas calculadoras funcionam como um Aplicativo Web Progressivo (PWA). Visite qualquer página de calculadora enquanto estiver conectado à internet, e seu navegador armazenará automaticamente todas as calculadoras em cache. Depois disso, todas as calculadoras funcionam offline — sem necessidade de internet.</p><p>No Android ou iOS, use a opção "Adicionar à tela inicial" do seu navegador para instalar o EngCalcs como um aplicativo no seu dispositivo. No desktop, procure o ícone de instalação na barra de endereços do seu navegador.</p><p>Você também pode salvar qualquer calculadora individualmente usando o menu "Salvar como…" do seu navegador para uso offline pontual.</p><h3>Contato</h3><p>Tom Haws — engenheiro hidráulico e autor dessas calculadoras.<br />Use o formulário de feedback em qualquer página de calculadora, ou acesse o código fonte em <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Contacto com HawsEDC';
$ec_lang['contactSendMessage']='Envie uma mensagem para Tom Haws';
$ec_lang['contactYourName']='Seu nome:';
$ec_lang['contactYourEmail']='Seu endereço de e-mail:';
$ec_lang['contactSubject']='Assunto:';
$ec_lang['contact_message']='Mensagem:';
$ec_lang['contactSpamPrefix']='Five (cinco) plus (e) one (um) equals (são) ';
$ec_lang['contactSpamPostfix']='(Por favor, escreva em inglês com letras. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Enviar Mensagem';
$ec_lang['contact_success']='Obrigado por dedicar seu tempo para escrever.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Projeto de Rampa em Enrocamento (Robinson)';
$ec_lang['rc_main_title']='Calculadora Gratuita de Projeto de Rampa em Enrocamento — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionamento de Rampa em Enrocamento — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Declividade do fundo da calha, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="Vazão por unidade de largura na entrada da calha. Para um canal de largura de base B com vazão total Q, usar q_t = Q / B.">Vazão específica total, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='Porosidade do enrocamento, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="Densidade relativa à água. Granito britado ou basalto típico &asymp; 2,65. Faixa válida de Robinson: 2,54 a 2,82.">Densidade relativa da rocha, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="Desvio padrão granulométrico. Rocha uniforme ≈ 1,25. Faixa válida Robinson: 1,15 a 1,47.">Graduação SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="O remanso (Hp > yn) é favorável — reduz erosão a montante. (USDA)">Tirante normal no canal de entrada, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="Eq. 1 (S0 < 0,10) ou Eq. 2 (0,10–0,40). Válido: D50 15–278 mm, S0 0,02–0,40. Fora da faixa: extrapolado.">Tamanho mediano necessário da rocha, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='Equação aplicada';
$ec_lang['rc_sg_check']='Verificação de densidade relativa';
$ec_lang['rc_SD_check']='Verificação de graduação SD';
$ec_lang['rc_sg_ok']   ='sg na faixa válida';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg abaixo da faixa Robinson';
$ec_lang['rc_sg_low_tip']='Faixa válida: 2,54–2,82';
$ec_lang['rc_sg_high'] ='sg acima da faixa Robinson';
$ec_lang['rc_sg_high_tip']='Faixa válida: 2,54–2,82';
$ec_lang['rc_SD_ok']   ='SD na faixa válida';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD abaixo da faixa Robinson';
$ec_lang['rc_SD_low_tip']='Faixa válida: 1,15–1,47';
$ec_lang['rc_SD_high'] ='SD acima da faixa Robinson';
$ec_lang['rc_SD_high_tip']='Faixa válida: 1,15–1,47';
$ec_lang['rc_layer']='Espessura da camada de rocha (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Raio de curva na crista superior (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Comprimento de arco na crista superior';
$ec_lang['rc_apron_length']='<span class="ec-help" title="Necessário para suporte estrutural da rocha da calha. &quot;O tirante mínimo a jusante resultante do trecho de saída e da resistência do canal a jusante é suficiente para garantir a estabilidade do enrocamento no trecho de saída.&quot; (Robinson)">Comprimento da laje de saída (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='Rugosidade de Manning na calha, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="Fração de qt que flui pelos poros da rocha. O restante qs flui pela superfície. np padrão = 0,45 para rocha britada angular.">Velocidade através do manto de pedra, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='Vazão específica no manto, q<sub>m</sub>';
$ec_lang['rc_qs']='Vazão específica superficial, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Lâmina d\'água acima da superfície do enrocamento, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="O remanso (Hp > yn) é favorável — reduz erosão a montante. (USDA)">Carga no vertedor de entrada, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='Verificação de remanso na entrada';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — remanso a montante';
$ec_lang['rc_pond_ok_tip']='O remanso a montante da entrada da calha é favorável; reduz a erosão a montante. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — sem remanso — potencial de erosão na entrada';
$ec_lang['rc_pond_warn_tip']='Sem remanso a montante da entrada da calha; pode ocorrer erosão a montante. (USDA)';
$ec_lang['rc_eq1']='Eq. 1 (S<sub>0</sub> < 0,10) — declividade suave';
$ec_lang['rc_eq2']='Eq. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — declividade acentuada';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — abaixo da faixa de validação Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — acima da faixa de validação Robinson';
$ec_lang['rc_notes_1_term']='Equações de dimensionamento de rocha';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) desenvolveram duas equações empíricas para o tamanho mediano de enrocamento D<sub>50</sub> em função da declividade da calha e da vazão específica. A equação 1 aplica-se a declividades suaves (S<sub>0</sub> < 0,10); a equação 2 a declividades acentuadas (0,10 ≤ S<sub>0</sub> ≤ 0,40). Ambas as equações requerem q<sub>t</sub> em m²/s e retornam D<sub>50</sub> em mm. A faixa validada é 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Vazão específica';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> é a vazão específica total na crista da calha (vazão total por unidade de largura). Para um canal de largura de base B com vazão total Q, q<sub>t</sub> ≈ Q / B, ou calculada a partir da condição de tirante crítico na entrada da calha.';
$ec_lang['rc_notes_3_term']='Fluxo através do manto de pedra';
$ec_lang['rc_notes_3_def']='Uma fração da vazão total flui pelos poros do enrocamento (vazão de manto q<sub>m</sub>); o restante flui pela superfície da rocha (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). A lâmina d\'água d é calculada pela equação de Manning aplicada à vazão superficial q<sub>s</sub> usando a rugosidade n da calha. A porosidade padrão n<sub>p</sub> = 0,45 é típica para rocha britada angular.';
$ec_lang['rc_notes_5_term']='Faixa válida de tamanho de rocha';
$ec_lang['rc_notes_5_def']='As equações foram desenvolvidas usando uma faixa de D<sub>50</sub> de 15 mm a 278 mm. Resultados fora desta faixa são extrapolados e devem ser usados com julgamento de engenharia adicional.';
$ec_lang['rc_notes_6_term']='Cota da superfície da laje de saída';
$ec_lang['rc_notes_6_def']='A cota do topo do enrocamento no trecho de saída deve estar na mesma cota ou abaixo da cota do fundo do canal a jusante. Se estiver mais alta, a rocha de saída será instável.';
$ec_lang['rc_notes_7_def']='Quando o tirante normal no canal de entrada é menor que a carga no vertedor (H<sub>p</sub>) necessária para escoar q<sub>t</sub>, ocorre fluxo restringido ou remanso a montante da entrada do canal. Isso é geralmente aceitável — o remanso reduz a velocidade e previne erosão a montante. Para verificar: usar uma calculadora de vertedor para encontrar H<sub>p</sub> para o q<sub>t</sub> e largura de crista dados, e comparar com o tirante normal do canal de entrada. Se H<sub>p</sub> exceder o tirante normal, ocorrerá remanso.';
$ec_lang['rc_notes_4_term']='Referência';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., e Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. O USDA ARS também publica uma <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">planilha Excel</a> baseada no mesmo método.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtro';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curva de crista superior';
$ec_lang['rc_sketch_outlet_apron']    = 'Laje de saída';
$ec_lang['rc_sketch_radius']          = 'raio';
$ec_lang['ip_main_menu']='Pressão em Irrigação';
$ec_lang['ip_main_title']='Calculadora Gratuita Online de Pressão em Irrigação e Uniformidade de Distribuição';
$ec_lang['ip_main_desc']='Pressão no Ramo de Teste e Uniformidade Estimada';
$ec_lang['ip_h_supply']='Pressão de abastecimento';
$ec_lang['ip_elev_supply']='Elevação de abastecimento, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Vazão de projeto do emissor, q<sub>design</sub>';
$ec_lang['ip_h_design']='Pressão de projeto do emissor';
$ec_lang['ip_x']='<span class="ec-help" title="0,5 para emissores não compensadores padrão; próximo a 0 para emissores com compensação de pressão">Expoente de descarga do emissor, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Caminho de teste';
$ec_lang['ip_group_reach']='Trecho';
$ec_lang['ip_group_upstream']='A montante';
$ec_lang['ip_group_downstream']='A jusante';
$ec_lang['ip_group_loss']='Perda';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="Marcado: este trecho é um segmento da lateral de teste, extraído por emissores individuais. Desmarcado: este trecho é uma principal, apenas passando fluxo para laterais não no caminho de teste.">Lat. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Linhas laterais: emissores neste trecho apenas. Linhas principais: emissores totais em laterais OUTRAS que ramificam deste trecho. Para o trecho exatamente na própria tomada da lateral de teste, isto também inclui quaisquer laterais ainda mais abaixo na principal, ou compartilhando a mesma junção (por ex., uma lateral no lado oposto) — seu fluxo ramifica deste mesmo trecho também.">Emissores <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Elevação da extremidade a jusante deste trecho. Opcional em linhas interiores (padroniza para plano / mesma do nó acima se deixado em branco). Obrigatório na última linha: esse valor é a elevação do último emissor, que define diretamente a pressão de abastecimento necessária.">Elev. JUS <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='Elevação do último emissor (última linha) foi deixada em branco e padronizou para plano — entre com ela para um resultado preciso';
$ec_lang['ip_flow']='Vazão';
$ec_lang['ip_press']='Press.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Perda total do trecho, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Pressão baixa/negativa — verificar condições subatmosféricas';
$ec_lang['ip_pressure_warn_short']='Baixa';
$ec_lang['ip_h_far']='Pressão do último emissor';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Fluxo entrando apenas no caminho de teste modelado, não a zona/sistema inteiro — ver Q_zone no Projeto de Aplicação abaixo para o total do sistema.">Vazão de abastecimento do caminho de teste, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Vazão do último emissor, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Vazão média do emissor (lateral de teste), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Quanto maior (ou menor) você acredita que uma lateral típica/média funciona comparada a esta lateral de teste. A lateral de teste é deliberadamente o pior caso presumido, portanto sua própria média é uma substituição enviesada para uma média de campo — deixado em 0, a verificação de uniformidade e os números de projeto-aplicação abaixo usam a própria média da lateral de teste (provavelmente otimista) como está.">Est. ΔPressão, média vs. lateral de teste <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral reavaliado em cada pressão de linha lateral mais a diferença de pressão inserida acima — uma tentativa de corrigir pela lateral de teste ser o pior caso presumido, não um representativo. Alimenta tanto a verificação de uniformidade quanto a seção de projeto-aplicação abaixo.">Est. vazão média do emissor em campo, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Vazão do último emissor dividida pela vazão média estimada do emissor em campo — mesma forma que a Uniformidade de Distribuição baixa-quarto padrão (média de grupo-baixo ÷ média populacional), mas computada a partir dos emissores modelados da própria lateral de teste, corrigida por uma estimativa ΔPressão inserida em vez de amostra estatística de campo completo. Valores em ou acima de 1 são possíveis e não um erro: apenas significa que o último emissor não é o ponto baixo em relação à média estimada em campo (por ex., uma corrida favorável em declive, ou a estimativa ΔPressão acima é muito pequena).">Verificação de uniformidade, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='Pressão do emissor de teste está em ou acima da pressão de abastecimento — este caminho provavelmente não é sua lateral de pior caso. Verificar uma lateral mais remota ou de maior fricção, ou um perfil de elevação que melhor represente o pior caso real.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Uma verificação separada, não uma figura de uniformidade: quão longe o último emissor funciona do ponto de vazão de projeto nominal do fabricante. Acima de 1: funcionando acima de seu ponto de projeto (por ex., de ganho de elevação em declive favorável). Abaixo de 1: funcionando sob projeto (caso típico dominado por fricção).">Vazão do último emissor vs. vazão de projeto, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Sem solução: pressão de abastecimento necessária excede a pressão de abastecimento inserida. Aumentar pressão de abastecimento, reduzir demanda, ou usar uma tubulação maior.';
$ec_lang['ip_notes_1_def']='Adivinha a pressão no último (mais remoto) emissor, depois marcha a Linha de Grau de Energia de volta para o abastecimento, trecho por trecho, adicionando fricção e perdas menores ao longo do caminho. Elevação e carga de velocidade são retiradas de cada nó para relatar a pressão real lá. A pressão de extremidade distante adivinhada é ajustada (bisseção) até que a pressão de abastecimento necessária computada corresponda à pressão de abastecimento inserida — o mesmo problema de circuito fechado endereçado pelo solucionador de fluxo em tubulação na calculadora de Vazão Manning em Tubulações, estendido a uma rede ramificada.';
$ec_lang['ip_notes_2_term']='Trechos Principais vs. Laterais';
$ec_lang['ip_notes_2_def']='Cada linha é um trecho ao longo do caminho hidraulicamente único pior presumido (o caminho de teste) do abastecimento ao último emissor. Um trecho Principal apenas passa fluxo para laterais não no caminho de teste, portanto sua extração é uma multiplicação plana (vazão de projeto × contagem de emissores total do trecho) — sem sensibilidade de pressão local. A principal é uma tubulação de tronco compartilhada, portanto o trecho exatamente na própria tomada da lateral de teste deve incluir não apenas laterais entre seus próprios extremos mas também quaisquer laterais ainda mais abaixo na principal além dessa tomada, ou compartilhando a mesma junção (por ex., uma lateral no lado oposto) — seu fluxo viaja através desse mesmo trecho antes de se ramificar, independentemente de aparecerem em qualquer outro lugar nesta tabela. Um trecho Lateral é um segmento da própria lateral de teste: descarga do emissor é computada a partir da pressão local real via q = k·H<sup>x</sup>, e perda de fricção é reduzida pelo fator F(n) de Christiansen para contabilizar fluxo diminuindo conforme cada emissor no trecho extrai.';
$ec_lang['ip_notes_3_term']='Limitações';
$ec_lang['ip_notes_3_def']='Modela uma pressão de entrada fixa (sem curva de bomba), um caminho de teste apenas (não o campo completo), e uma curva de emissor de 2 parâmetros (defina o expoente próximo a 0 para aproximar um emissor com compensação de pressão). Duas razões diferentes são relatadas, deliberadamente mantidas separadas: q<sub>last</sub>/q<sub>avg,field</sub> é uma verificação de uniformidade, em forma de Uniformidade de Distribuição baixa-quarto padrão (média de grupo-baixo ÷ média populacional) mas computada a partir dos emissores modelados da própria lateral de teste, corrigida por uma estimativa ΔPressão inserida em vez de amostra estatística de campo completo — a lateral de teste é deliberadamente o pior caso presumido, portanto sua média bruta não corrigida subestimaria a verdadeira média de campo e faria uniformidade parecer melhor do que é; a entrada ΔPressão existe especificamente para contrariar esse viés. Valores em ou acima de 1 ainda são possíveis (por ex., a estimativa ΔPressão é muito pequena, ou uma corrida em declive favorável). q<sub>last</sub>/q<sub>design</sub> é uma verificação diferente, não-uniformidade contra a vazão de projeto nominal do fabricante — útil para detectar um sistema sobre- ou sub-pressurizado em geral, mas não um substituto para o número de uniformidade, já que a vazão de projeto/nominal não tem relação necessária com a pressão de funcionamento médio real do sistema.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. Padrões ASAE/ASABE para projeto de microirrigação usam a mesma abordagem de perda de fricção de saída múltipla.';
$ec_lang['ip_notes_5_term']='Projeto de Aplicação';
$ec_lang['ip_notes_5_def']='Taxa de aplicação e fluxo de sistema/zona usam a vazão média estimada do emissor em campo (q<sub>avg,field</sub> — a média da própria lateral de teste, corrigida pela estimativa ΔPressão inserida), não uma taxa adivinhada: PR = q<sub>avg,field</sub> / A<sub>e</sub>, alimentada pelo valor modelado corrigido. Espaçamento e contagens de lateral/emissor do sistema amplo são entradas separadas aqui porque o caminho de teste modela apenas uma ramificação de pior caso, não cada lateral no campo.';
