<?php

// All missing text declarations will fall back to English.

$ec_lang['u_depthFrac']='разломак';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% пад/хоризонтала';
$ec_lang['u_grade']='пад/хоризонтала';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_bar']="bar";
$ec_lang['u_kgfcm2']="kgf/cm^2";
$ec_lang['u_s']='sec';
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Калкулатори';
$ec_lang['menu_main_list']='Листа калкулатора';
$ec_lang['menu_main_hydraulics']='Хидраулика';
$ec_lang['menu_main_language']='Језик';
$ec_lang['menu_more']='Више';
$ec_lang['template_welcome']='Оставите страхове за вратима; овде је љубав наш језик. Не кварите све. Уживајте и у <a target="_blank" href="https://hawsedc.com/download.php">бесплатним HawsEDC AutoCAD алатима</a>.';
$ec_lang['template_translation_help']='Можете ли да предложите бољу формулацију или било шта друго? Реците нам.';
$ec_lang['template_feedback']='Пошаљите нам предлоге или похвале. Да ли вам је овај бесплатни калкулатор добро послужио?';
$ec_lang['template_printable_title']='Наслов за штампу';
$ec_lang['template_printable_subtitle']='Поднаслов за штампу';
$ec_lang['index_title']='Бесплатни онлајн инжењерски калкулатори';
$ec_lang['index_meta_desc_plain']='Бесплатни хидротехнички калкулатори за цеви, канале, преливе и наводњавање. Раде директно у прегледачу, доступни су и без интернета, на 27 језика.';
$ec_lang['calc_set_units']='Подеси јединице:';
$ec_lang['calc_defaults']='Подразумеване вредности';
$ec_lang['calc_defaults_confirm']='Повратити калкулатор на подразумеване вредности?';
$ec_lang['points_data_help']='(или Копирај/Налепи помоћу поља за податке)';
$ec_lang['points_data_title']='Подаци тачака<br />(одвојени зарезом или табулатором)';
$ec_lang['points_data_copy']='Копирај';
$ec_lang['points_data_paste']='Налепи';
$ec_lang['calc_inputs']='Улазне вредности';
$ec_lang['calc_results']='Резултати';
$ec_lang['view_hide_line']='[Сакриј овај ред]';
$ec_lang['view_printable']='Верзија за штампу (освежите страницу да бисте вратили)';
$ec_lang['ec_name_label']='Сачувајте овај прорачун:';
$ec_lang['ec_name_placeholder']='Назив';
$ec_lang['ec_name_hint']='Чува унете вредности у URL адресу за обележавање, преузимање из историје и дељење';
$ec_lang['calc_copy_link']='Копирај линк';
$ec_lang['calc_copy_link_done']='Копирано!';
$ec_lang['ec_related_calcs']='Слични калкулатори:';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Губитак напора у цевима по Darcy-Weisbachу';
$ec_lang['dw_main_title']='Бесплатни онлајн калкулатор губитка напора у цевима по Darcy-Weisbachу';
$ec_lang['dw_main_desc']='Губитак напора у цевима по Darcy-Weisbachу при задатом пречнику, храпавости и протоку';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Апсолутна храпавост зида цеви, e. Типичне вредности: челик (нов) 0,046 мм, челик (коришћен) 0,15 мм, HDPE 0,003 мм, PVC/uPVC 0,0015 мм, бетон 0,3–3 мм.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s за чисту воду на 20°C">Кинематичка вискозност, ν <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Кинематичка вискозност, ν';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s за чисту воду на 20°C';
$ec_lang['dw_reynolds_number']='Рејнолдсов број, Re';
$ec_lang['dw_flow_regime']='Режим течења';
$ec_lang['dw_regime_laminar']='ламинарно';
$ec_lang['dw_regime_transitional']='прелазно';
$ec_lang['dw_regime_turbulent']='турбулентно';
$ec_lang['dw_friction_factor_method']='Метод фактора трења';
$ec_lang['dw_friction_factor']='Фактор трења, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Губитак напора у цевима по Hazen-Williamsу';
$ec_lang['hw_main_title']='Бесплатни онлајн калкулатор губитка напора у цевима по Hazen-Williamsу';
$ec_lang['hw_main_desc']='Губитак напора у цевима по Hazen-Williamsу при задатом пречнику, храпавости и протоку';
$ec_lang['hw_hgl_1']='Низводна HGL';
$ec_lang['hw_hgl_2']='Узводна HGL';
$ec_lang['hw_roughness']='Hazen-Williams коефицијент, C';
// Manning Irregular
$ec_lang['mi_menu']='Манингов канал неправилног пресека';
$ec_lang['mi_main_title']='Бесплатни онлајн калкулатор канала неправилног попречног пресека по Manningу';
$ec_lang['mi_main_desc']='Калкулатор равномерног тецања по Manningу за канал неправилног попречног пресека';
$ec_lang['mi_waterSurfaceElevation']='Кота нивоа воде';
$ec_lang['mi_q_617']='<span class="ec-help" title="Композитни проток Q, коришћењем композитног n за сваку регију према Chow 6-17, једнаке брзине">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Тачке попречног пресека';
$ec_lang['mi_groupPoint']='Тачка';
$ec_lang['mi_groupSegment']='Сегмент';
$ec_lang['mi_groupRegion']='Регија';
$ec_lang['mi_station']='Ст.';
$ec_lang['mi_elevation']='Кота';
$ec_lang['mi_d50in']='Медијана<br />величина<br />камена<br />облоге';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />граница<br />регије<br />(Обала)';
$ec_lang['mi_tau']='Смицајни<br />напон<br />дна τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Комп.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='Композитни n';
$ec_lang['mi_notes_1_def']='Овај калкулатор прати HEC-RAS Референтни приручник у израчунавању композитног n регије помоћу Chow 1959, страна 136, једначина 6-17 (не 6-18).';
$ec_lang['mi_notes_2_term']='Камена облога';
$ec_lang['mi_notes_2_def']='Користите калкулатор трапезног канала по Manningу за пројектовање камене облоге. Овај калкулатор је примеренији за природне пресеке.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Проток у цевима по Manningу';
$ec_lang['mpf_main_title']='Бесплатни онлајн калкулатор протока у цевима по Manningу';
$ec_lang['mpf_main_desc']='Манингова формула равномерног течења у цевима при задатом нагибу и дубини';
$ec_lang['mpf_spreadheet_notice']='Табела Manning протока у цевима';
$ec_lang['mpf_pipe_diameter']='Пречник цеви, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Манингов коефицијент храпавости, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Нагиб трења, S<sub>f</sub></a><span class="ec-help" title="Понекад једнак нагибу цеви. Пратите везу за објашњење (само на енглеском)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Релативна дубина течења, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Проток, Q';
$ec_lang['mpf_flow_tip']='Проток и дубина су израчунати за бесконачно дугачку цев. За унос овог протока у цев можда је потребна већа дубина нивоа воде. Погледајте напомене испод за детаље и туторијал видео.';
$ec_lang['mpf_velocity']='Брзина, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="Кинетичка енергија изражена као висина водног стуба, v²/2g">Брзинска висина, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='Површина протицајног пресека, A';
$ec_lang['mpf_pipe_area']='Површина цеви, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Релативна површина, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Квашени периметар, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Хидраулички полупречник, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Површинска ширина, T';
$ec_lang['mpf_froude_number']='Фрудов број, Fr';
$ec_lang['mpf_shear_stress']='Просечан напон смицања, τ';
$ec_lang['mpf_full_flow']='Пуни проток, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Однос према пуном протоку, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Ово је проток и дубина унутар <em>бесконачно дугачке</em> цеви.</dt><dd>За унос воде у цев може бити потребна знатно већа дубина нивоа воде. Додајте најмање 1,5 пута брзинску висину да бисте добили дубину нивоа воде или <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">погледајте мој 2-минутни туторијал</a> за стандардна израчунавања нивоа воде на пропусту помоћу <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>, бесплатног програма за пропусте Управе за аутопутеве САД (U.S. Federal Highway Administration).</dd>';
$ec_lang['mpf_sewer_ref']='<dl><dt>Пројектујете санитарну канализацију?</dt><dd>Погледајте <a target="_blank" href="/sewslope.php">табеле минималних падова канализације</a> за цеви од 4 до 96 инча (100 до 2400 mm), дате у m/m, mm/m и процентима, и студију <a target="_blank" href="/peakfact.php">фактора врха за веома мале протоке</a>. Оба су референтна документа само на енглеском језику.</dd></dl>';
$ec_lang['mpf_solve_button']='Израчунај';
$ec_lang['mpf_solve_for_flow']='за проток, Q =';
$ec_lang['mpf_solver_enter_positive_q']='Унесите позитиван циљани Q.';
$ec_lang['mpf_solver_no_solution']='Нема решења: Q премашује капацитет цеви при y/d0 = 93.8% (Qmax = {qmax} у изабраним јединицама).';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Губитак напора у цевима по Manningу';
$ec_lang['mphl_main_title']='Бесплатни онлајн калкулатор губитка напора у цевима по Manningу';
$ec_lang['mphl_main_desc']='Манингова формула губитка напора при пуном протоку';
$ec_lang['mphl_pipe_length']='Дужина цеви, L';
$ec_lang['mphl_area']='Површина, A';
$ec_lang['mphl_total_junction_k']='Коефицијент мањег (локалног) губитка, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Коефицијент губитка, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Коефицијент мањег (локалног) губитка, km. Ови губици настају на спојевима цеви, улазима, излазима, луковима и вентилима — израз „мањи” је уобичајен, али обмањујућ; на краткој деоници они могу бити једнаки или чак већи од губитака трењем. Типичне вредности k: оштар улаз (усисни) 0,5, сваки лук од 45° 0,2–0,3, затварач (потпуно отворен) 0,1, лептир вентил 0,2, излаз (у резервоар или атмосферу) 1,0. Саберите све фитинге за укупну вредност km. Подразумевана вредност 2,0 претпоставља један улаз, један излаз и два лука од 45°.';
$ec_lang['mphl_friction_slope']='Нагиб трења';
$ec_lang['mphl_friction_loss']='Губици услед трења, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Мањи (локални) губитак, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Укупни губитак, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='Низводна EGL';
$ec_lang['mphl_egl_2']='Узводна EGL';
$ec_lang['mphl_hgl_egl_tip']='Можда није валидно ако је цев високо постављена. Погледајте напомене.';
$ec_lang['mphl_note_1']='<dl><dt>Овај калкулатор не узима у обзир коту (елевацију) цеви.</dt><dd>Ако HGL падне испод горње ивице цеви у било којој тачки, овај прорачун можда није валидан.</dd><dt>За услов отвореног улаза (пропуст), неопходно је проверити услове контроле улаза.</dt><dd>1. Узводна HGL не може бити нижа од узводне коте нормалног течења (нити нижа од цеви!).</dd><dd>2. Ниво воде на пропусту боље је представити узводном EGL него узводном HGL.</dd><dd>3. Погледајте <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">мој 2-минутни туторијал</a> за једноставна стандардна израчунавања нивоа воде на пропусту помоћу <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>, бесплатног програма за пропусте Управе за аутопутеве САД (U.S. Federal Highway Administration).</dd><dd>4. Ова страница решава само случај контроле излаза: цев која тече пуна, где ниво воде одређују низводни услови. Пројектовање пропуста подразумева одлуку да ли доминира контрола улаза или контрола излаза, па користите HY-8 кад год је могуће било које од то двоје.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Манингов трапезни канал';
$ec_lang['mtc_main_title']='Бесплатни онлајн калкулатор трапезног канала по Манинговој формули';
$ec_lang['mtc_main_desc']='Манингова формула равномерног тецања у трапезном каналу при задатом паду и дубини';
$ec_lang['mtc_bottom_width']='Ширина дна, b';
$ec_lang['mtc_side_slope_1']='Нагиб бочне стране 1, z<sub>1</sub> (хориз./верт.)';
$ec_lang['mtc_side_slope_2']='Нагиб бочне стране 2, z<sub>2</sub> (хориз./верт.)';
$ec_lang['mtc_channel_slope']='Пад канала, S';
$ec_lang['mtc_flow_depth']='Дубина тецања, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Угао скретања, β</a><span class="ec-help" title="За димензионисање камените насуте конструкције. Пратите везу за шему."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Густина у односу на воду. Типично ≈ 2,65 за дробљени камен.">Релативна густина камена, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Пројектована величина камена, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n за пројектовану величину камена по Strickleru';
$ec_lang['mtc_n_blodgett']='n за пројектовану величину камена по Blodgettu';
$ec_lang['mtc_n_bathurst']='n за пројектовану величину камена по Bathurstu';
$ec_lang['mtc_n_pi']='n за пројектовану величину камена по методи Phillips & Ingersoll';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett насупрот Bathurst';
$ec_lang['mtc_pi_range_check']='P&I провера опсега';
$ec_lang['mtc_pi_ok']='d50 у P&I опсегу';
$ec_lang['mtc_pi_ok_tip']='0.28–0.36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='Ван опсега';
$ec_lang['mtc_pi_tip']='Екстраполација ван опсега скупа података 0.28–0.36 ft на основу којег је ова једначина изведена — сматрати оквирном провером, а не основом за пројектовање';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="По Isbashu (1936) и округу Maricopa, Аризона, САД.">Потребна величина угаоног камена дна, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="По Isbashu (1936) и округу Maricopa, Аризона, САД.">Потребна величина угаоног камена бочне стране 1, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="По Isbashu (1936) и округу Maricopa, Аризона, САД.">Потребна величина угаоног камена бочне стране 2, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Потребна величина угаоног камена, D<sub>50</sub> (Maynord, Ruff и Abt 1989)';
$ec_lang['mtc_d50_searcy']='Потребна величина угаоног камена, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='Брзина прихватљива за претпоставке равномерног тецања.';
$ec_lang['mtc_vel_low']='Брзина ниска — ризик таложења наноса.';
$ec_lang['mtc_iteration_tip']='Изаберите опцију храпавости (препоручује се Blodgett–Bathurst) и опцију величине камена (препоручује се Isbash) за аутоматску итерацију до уједначене величине камена за жељени проток. Погледајте напомене испод за пун опис методе, или унесите сопствену вредност храпавости (пратите везу за смернице) и занемарите величину камена да прескочите итерацију.';
$ec_lang['mtc_note_1']='<dl><dt>Аутоматска итерација пројектовања величине камена и храпавости</dt><dd>Изаберите радио дугме за храпавост (препоручује се Blodgett–Bathurst) и радио дугме за пројектовану величину камена (препоручује се Isbash). Финим подешавањем дубине и фактора сигурности величине камена добијте жељени проток са уједначеном величином камена. Свака промена улазне вредности покреће следећи итерациони циклус: 1. Храпавост се израчунава из пројектоване величине камена. 2. Израчунавање тражене храпавости копира се у улазну храпавост. 3. Израчунавају се проток у каналу и потребна величина камена. 4. Пројектована величина камена се подешава. 5. Понавља се до врло мале грешке у пројектованој величини камена.</dd><dt>Основни калкулатор (без итерације)</dt><dd>Унесите жељену вредност храпавости. Занемарите поље за унос пројектоване величине камена.</dd></dl>';
$ec_lang['mtc_note_2_term']='Провера брзине';
$ec_lang['mtc_note_2_def']='Висока брзина подразумева велику специфичну енергију услед расположивог пада. Та енергија може се брзо изгубити на ширењима, луковима или препрекама. Проверите да ли је то прихватљиво за дато место.';
$ec_lang['mtc_solver_no_solution']='Није пронађено решење за дато Q са овим улазним подацима канала.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Проток преко простог прелива';
$ec_lang['ws_main_title']='Бесплатни онлајн калкулатор протока преко простог ширококрунског прелива';
$ec_lang['ws_main_desc']='Калкулатор протока преко простог ширококрунског прелива';
$ec_lang['ws_weirLength']='Дужина прелива, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="Енергија по јединици тежине воде — висина водног стуба, а не притисак">Напор, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='Коефицијент прелива, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Напомене';
$ec_lang['ws_notes_we_term']='Једначина прелива';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Проток преко прелива неправилног облика круне';
$ec_lang['wi_main_title']='Бесплатни онлајн калкулатор протока преко сегментираног прелива променљиве дубине и неправилног облика круне';
$ec_lang['wi_main_desc']='Калкулатор протока преко прелива неправилног облика круне';
$ec_lang['wi_weirPoints']='Тачке прелива';
$ec_lang['wi_pondingHeight']='Висина успора';
$ec_lang['wi_incrementalFlow']='Прираштајни проток';
$ec_lang['wi_cumulativeFlow']='Кумулативни проток';
$ec_lang['wi_save_and_calculate']='Сачувај и израчунај';
$ec_lang['wi_notes_we_def']='q = ако (length = 0) онда 0 иначе ако (slope=0) онда cw*length*d<sub>0</sub><sup>1.5</sup> иначе cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) где су d<sub>1</sub> и d<sub>0</sub> увек позитивни или нула';
// Orifice Flow
$ec_lang['or_main_menu']='Проток кроз отвор';
$ec_lang['or_main_title']='Бесплатни онлајн калкулатор протока кроз отвор';
$ec_lang['or_main_desc']='Проток кроз отвор — слободан или потопљен';
$ec_lang['or_shape']='Облик отвора';
$ec_lang['or_shape_circular']='Кружни';
$ec_lang['or_shape_rectangular']='Правоугаони';
$ec_lang['or_diameter']='<span class="ec-help" title="Пречник за кружни; висина за правоугаони отвор">Пречник или висина, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Само за правоугаоне отворе">Ширина, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Дно отвора">Кота дна отвора <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Кота узводног нивоа воде';
$ec_lang['or_twe']='Кота низводног нивоа воде';
$ec_lang['or_cd']='Коефицијент протока, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Кота тежишта';
$ec_lang['or_head']='<span class="ec-help" title="Енергија по јединици тежине воде — висина водног стуба, а не притисак">Ефективни напор, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='Површина отвора, A';
$ec_lang['or_regime']='Провера режима отвора';
$ec_lang['or_regime_valid']='Слободно истицање';
$ec_lang['or_regime_submerged']='Потопљени отвор';
$ec_lang['or_regime_submerged_tip']='TWE изнад тежишта — режим отвора и даље важи';
$ec_lang['or_regime_warn']='Изван режима отвора';
$ec_lang['or_regime_warn_tip']='Узводни ниво воде испод темена отвора';
$ec_lang['or_regime_twe_above_hwe']='Проверите улазне вредности';
$ec_lang['or_regime_twe_above_hwe_tip']='Низводни ниво (TWE) изнад узводног нивоа (HWE)';
$ec_lang['or_notes_1_term']='Једначина отвора';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). За слободно истицање: h = HWE − тежиште. За потопљени проток (TWE изнад дна отвора): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Режим отвора';
$ec_lang['or_notes_2_def']='Једначине протока кроз отвор важе када је узводни ниво воде изнад темена (врха) отвора. Када је узводни ниво испод темена, користи се једначина прелива.';
$ec_lang['or_notes_3_term']='Коефицијент протока';
$ec_lang['or_notes_3_def']='C<sub>d</sub> се креће од приближно 0,60 до 0,65 за оштроивичне отворе. Заобљени или увучени улази имају друге вредности. Погледајте <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> или HEC-RAS Хидраулички приручник за смернице.';
$ec_lang['or_notes_4_term']='Потопљеност';
$ec_lang['or_notes_4_def']='Када је TWE изнад дна отвора, калкулатор аутоматски примењује једначину потопљеног отвора са h = HWE − TWE. Када је TWE на нивоу дна или испод њега, претпоставља се слободно истицање и h = HWE − тежиште.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Мала хидроелектрана';
$ec_lang['mhp_main_title']='Бесплатни онлајн калкулатор за малу хидроелектрану';
$ec_lang['mhp_main_desc']='Калкулатор излазне снаге мале хидроелектране проточног типа';
$ec_lang['mhp_gross_head']='Бруто пад, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="Пречник напорног цевовода (доводне цеви)">Пречник цевовода, D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='Дужина, L';
$ec_lang['mhp_efficiency']='Ефикасност постројења, η (0–1)';
$ec_lang['mhp_vel_check']='Провера брзине';
$ec_lang['mhp_hl_check']='Провера губитка напора';
$ec_lang['mhp_hnet']='Нето пад, H<sub>net</sub>';
$ec_lang['mhp_power']='Излазна снага, P';
$ec_lang['mhp_annual_kwh']='Годишња енергија при 100% капацитета';
$ec_lang['mhp_vel_low']='Брзина ниска — ризик од таложења наноса и увлачења ваздуха.';
$ec_lang['mhp_vel_high']='Брзина висока — проверите губитке при преласку, расположиву енергију и ризик од водног удара.';
$ec_lang['mhp_vel_ok_short']='У реду';
$ec_lang['mhp_vel_high_short']='Висока';
$ec_lang['mhp_vel_low_short']='Ниска';
$ec_lang['mhp_vel_ok_tip']='Брзина је у ефикасном опсегу за пројектовање цевовода.';
$ec_lang['mhp_hl_ok_tip']='У оквиру циља од 10% — економично.';
$ec_lang['mhp_hl_warn_tip']='Прекорачује циљ од 10%. Размотрите већи пречник цеви.';
$ec_lang['mhp_hl_bad_tip']='Прекорачује циљ од 20%. Промените пречник цеви.';
$ec_lang['mhp_notes_1_term']='Губитак напора';
$ec_lang['mhp_notes_1_def']='Укупни губитак h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, где је h<sub>f</sub> = f(L/D)(v²/2g) губитак трењем по Дарси-Вајсбаху, а h<sub>m</sub> = k<sub>m</sub>·v²/2g обухвата улаз, лукове и вентиле. Нето пад H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Брзина';
$ec_lang['mhp_notes_2_def']='Проверите да ли је брзина разумна с обзиром на расположиви пад и цену цевовода. Врло ниска брзина може указивати на предимензионисан пречник; врло висока брзина повећава губитке трењем и ризик од водног удара.';
$ec_lang['mhp_notes_3_term']='Циљни губитак напора';
$ec_lang['mhp_notes_3_def']='Губитак у цевоводу испод 10% бруто пада је уопштено економичан. Оптималан компромис између цене цевовода и изгубљене снаге обично је 4–6% за локалитете с високом вредношћу електричне енергије.';
$ec_lang['mhp_notes_6_term']='Ефикасност';
$ec_lang['mhp_notes_6_def']='Типична ефикасност постројења η износи 0.70 до 0.85 за Pelton и попречне турбине уобичајене у мало-хидро системима. Користите 0.75 као конзервативну прву процену.';
$ec_lang['mhp_notes_7_term']='Годишња енергија';
$ec_lang['mhp_notes_7_def']='Годишња енергија претпоставља непрекидан рад при пуном протоку (8760 сати/годишње). Стварна производња биће нижа услед сезонских варијација протока, застоја ради одржавања и фактора оптерећења.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Време пражњења базена и резервоара';
$ec_lang['odt_main_title']='Бесплатни онлајн калкулатор времена пражњења базена, акумулације и резервоара (кроз отвор)';
$ec_lang['odt_main_desc']='Време пражњења базена, акумулације или резервоара — излаз кроз отвор, метод конусне запремине';
$ec_lang['odt_h1_elev']='Почетна кота нивоа воде';
$ec_lang['odt_a1']='Почетна површина, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Завршна кота нивоа воде';
$ec_lang['odt_a0']='Површина на нивоу отвора, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Интерполисано из конусног модела на завршној коти">Завршна површина, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Провера завршне коте';
$ec_lang['odt_h2_ok']='Завршна кота изнад врха отвора';
$ec_lang['odt_h2_warn']='Завршна кота на нивоу или испод врха отвора';
$ec_lang['odt_h2_warn_tip']='Врх отвора = тежиште + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Пречник (кружни) или висина (правоугаони)">Пречник отвора, D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Само за правоугаоне">Ширина отвора, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Време пражњења (s)';
$ec_lang['odt_t_min']='Време пражњења (min)';
$ec_lang['odt_t_hr']='Време пражњења (hr)';
$ec_lang['odt_t_day']='Време пражњења (дана)';
$ec_lang['odt_notes_1_term']='Формула';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) даје време пражњења од напора H до отвора. Време пражњења = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), где је H<sub>1</sub> = почетна кота − кота отвора, H<sub>2</sub> = завршна кота − кота отвора.';
$ec_lang['odt_notes_2_term']='Метод';
$ec_lang['odt_notes_2_def']='Метод конусне запремине моделује акумулацију или базен као конусни пресек између почетне површине A<sub>1</sub> на почетном нивоу воде и површине A<sub>0</sub> на коти тежишта отвора. A<sub>2</sub>, површина акумулације на завршној коти, интерполише се из A<sub>1</sub> и A<sub>0</sub> помоћу модела конусног пресека. Време пражњења од почетне до завршне коте једнако је укупном времену пражњења од H<sub>1</sub> до отвора умањеном за преостало време пражњења од H<sub>2</sub> до отвора.';
$ec_lang['odt_h1']='<span class="ec-help" title="Почетна кота нивоа воде минус кота тежишта отвора">Почетни напор, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Максимални проток, Q<sub>max</sub>';
$ec_lang['odt_vol']='Испражњена запремина';
$ec_lang['odt_sketch_start']='Почетак';
$ec_lang['odt_sketch_end']='Крај';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Наводњавање';
$ec_lang['irr_main_title']='Бесплатни онлајн калкулатори за мерење протока у наводњавању';
$ec_lang['irr_main_desc']='Мерење протока у наводњавању — преливи и отвори';
$ec_lang['irr_intro_html']='<p>Преливи и отвори су стандардни теренски алати за мерење протока воде у системима за наводњавање. Изаберите калкулатор који одговара вашој грађевини:</p>';
$ec_lang['irr_card_weir_uniform_head']='Прелив — широка круна (равномерна ширина)';
$ec_lang['irr_card_weir_uniform_desc']='Измерите проток преко круне одводне бране, уставе или даске прелива. Унесите дужину прелива и дубину узводне воде изнад круне.';
$ec_lang['irr_card_weir_irregular_head']='Прелив — неуједначени профил';
$ec_lang['irr_card_weir_irregular_desc']='Користите када се кота или профил круне прелива мења — природни преливи, каскадне грађевине с променљивом ширином, или вишеделне регулационе грађевине.';
$ec_lang['irr_card_orifice_head']='Отвор — главна устава или цевни излаз';
$ec_lang['irr_card_orifice_desc']='Измерите проток кроз уставу, цевни излаз или отвор пропуста. Аутоматски обрађује и слободно истицање и потопљене услове (противпритисак низводне воде).';
$ec_lang['irr_card_canal_head']='Пројектовање и анализа канала';
$ec_lang['irr_card_canal_desc']='Пројектујте или проверите канал за наводњавање помоћу Manningove формуле. Користите трапезни калкулатор за нове канале, а калкулатор неуједначеног пресека за постојеће природне или изграђене пресеке.';
$ec_lang['irr_card_seepage_head']='Процеђивање из канала и ефикасност транспорта воде';
$ec_lang['irr_card_seepage_desc']='Процените губитак процеђивањем из деонице канала помоћу мерења притицаја и отицаја. Израчунајте ефикасност транспорта воде и годишњи губитак воде ради приоритизације улагања у облагање.';
$ec_lang['irr_quickref_html']='<h3>Брзи водич</h3><dl><dt>Одводна брана или устава</dt><dd>Измерите дубину узводне воде изнад круне прелива. Користите <a href="Weir-Flow-Simple.php">Прелив — равномерна круна</a> за равномерну круну, или <a href="Weir-Flow-Irregular.php">Прелив — неуједначени профил</a> за профилисану или степенасту круну.</dd><dt>Главна устава или цевни излаз</dt><dd>Измерите коту узводне и низводне воде (или коту дна ако слободно истиче). Користите <a href="Orifice.php">Проток кроз отвор</a>. За кружну цев D = пречник цеви; за правоугаону уставу унесите ширину W и висину D.</dd><dt>Време пражњења резервоара или рибњака</dt><dd>Користите <a href="Orifice-Drain-Time.php">Трајање пражњења кроз отвор</a> за процену колико је потребно да се ниво рибњака или резервоара спусти кроз донски отвор — корисно за планирање акумулације за наводњавање.</dd><dt>Теренски стандарди</dt><dd>Овде коришћене једначине протока кроз прелив и отвор одговарају поступцима из USBR <em>Water Measurement Manual</em> (3. изд.), које обично захтевају управници вода и наводњавачки окрузи.</dd></dl>';
$ec_lang['irr_card_pressure_head']='Притисак и уједначеност наводњавања';
$ec_lang['irr_card_pressure_desc']='Моделирајте профил притиска и протока дуж гране магистрала–латерала–емитер да бисте проценили уједначеност дистрибуције на основу стварног притиска путање теста, а не само каталошког протока емитера.';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Растојање емитера, S<sub>e</sub>';
$ec_lang['ip_sl']='Растојање латерала, S<sub>l</sub>';
$ec_lang['ip_n_e']='Емитери по латерали, n<sub>e</sub>';
$ec_lang['ip_n_l']='Латерале по зони, n<sub>l</sub>';
$ec_lang['ip_d']='Циљна дубина наводњавања, d';
$ec_lang['ip_a_e']='Површина по емитеру, A<sub>e</sub>';
$ec_lang['ip_pr']='Интензитет наводњавања, PR';
$ec_lang['ip_q_lat']='Проток по латерали, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Проток зоне, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Време наводњавања (сати)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Процеђивање из канала';
$ec_lang['cs_main_title']='Бесплатни онлајн калкулатор губитака процеђивањем из канала и ефикасности транспорта воде';
$ec_lang['cs_main_desc']='Губитак процеђивањем из канала и ефикасност транспорта воде — метода притицаја и отицаја';
$ec_lang['cs_Q_in']='Притицај, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Отицај, Q<sub>out</sub>';
$ec_lang['cs_L']='Дужина деонице, L';
$ec_lang['cs_Q_loss']='Стопа губитка процеђивањем, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Провера мерења';
$ec_lang['cs_pct_loss']='Удео губитка';
$ec_lang['cs_Ec']='Ефикасност транспорта воде, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Оцена ефикасности';
$ec_lang['cs_Vol_day']='Дневни изгубљени обим воде';
$ec_lang['cs_Vol_year']='Годишњи изгубљени обим воде';
$ec_lang['cs_Q_loss_per_L']='Губитак по јединици дужине, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Вредност воде';
$ec_lang['cs_lining_cost']='Трошак облагања';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Циљна ефикасност транспорта воде након облагања; удео 0–1">Циљ облагања, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Површина облоге, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Годишња изгубљена вредност';
$ec_lang['cs_annual_value_recovered']='Годишња опорављена вредност';
$ec_lang['cs_lining_total_cost']='Укупан трошак облагања';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Прост поврат = укупан трошак облагања ÷ годишња опорављена вредност">Период поврата инвестиције <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — процеђивање детектовано';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — нема мерљивог губитка';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — проверите мерења';
$ec_lang['cs_Ec_good']='Добро — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Прихватљиво — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Лоше — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='Метода мерења притицаја и отицаја процењује процеђивање мерењем протока на почетку и на крају деонице канала: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Ефикасност транспорта воде E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Годишњи обим претпоставља непрекидан рад са пуним протоком; стварни губитак је мањи за сезонске канале или канале с делимичним протоком.';
$ec_lang['cs_notes_2_term']='Оцене ефикасности';
$ec_lang['cs_notes_2_def']='Типични необложени земљани канали: E<sub>c</sub> = 60–80%. Добро одржавани земљани канали: 75–85%. Бетонски обложени канали: 90–98%. Губици процеђивањем изнад 30% притицаја често оправдавају улагање у облагање. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Поврат улагања у облагање';
$ec_lang['cs_notes_3_def']='Унесите вредност воде и трошак облагања у било којој доследно коришћеној валути. Површина облоге = дужина деонице × оквашени обим — оквашени обим попречног пресека канала на измереној дубини протока (ширина дна плус оба оквашена нагиба). Годишња опорављена вредност претпоставља да обложени канал непрекидно достиже циљну E<sub>c</sub>. Стварни период поврата биће дужи за сезонске канале или ако облагање не достигне циљну ефикасност.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3. изд. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='О нама';
$ec_lang['install_main_menu']='Инсталирај';
$ec_lang['install_main_title']='Инсталирај EngCalcs';
$ec_lang['install_main_desc']='Додај на уређај за коришћење без интернета';
$ec_lang['install_intro']='EngCalcs је прогресивна веб апликација (PWA). После инсталације, сви калкулатори раде потпуно без интернета — веза са интернетом није потребна.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Отворите било коју страницу калкулатора у Chrome-у.</li><li>Додирните дугме <strong>⬇ Инсталирај</strong> на горњој траци, или додирните мени прегледача (⋮) и изаберите <strong>Додај на почетни екран</strong>.</li><li>Додирните <strong>Инсталирај</strong> у прозору који се појави.</li><li>EngCalcs се појављује на почетном екрану и ради без интернета.</li>';
$ec_lang['install_now_btn']='⬇ Инсталирај сада';
$ec_lang['install_prompt_unavailable']='Прозор за инсталацију није доступан — уместо тога користите мени прегледача.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Отворите било коју страницу калкулатора у Safari-ју.</li><li>Додирните дугме <strong>Дели</strong> (квадрат са стрелицом нагоре).</li><li>Скролујте надоле и додирните <strong>Додај на почетни екран</strong>.</li><li>Додирните <strong>Додај</strong>. EngCalcs се појављује на почетном екрану.</li>';
$ec_lang['install_ios_note']='На iOS-у, инсталација увек иде преко менија Дели — не постоји аутоматски прозор за инсталацију.';
$ec_lang['install_desktop_heading']='Рачунар (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Отворите било коју страницу калкулатора.</li><li>Кликните на <strong>икону за инсталацију</strong> (⊕ или икона рачунара) у адресној траци прегледача, или отворите мени прегледача и изаберите <strong>Инсталирај EngCalcs…</strong></li><li>Кликните на <strong>Инсталирај</strong>. EngCalcs се отвара као самостални прозор апликације.</li>';
$ec_lang['install_firefox_heading']='Firefox / Остали прегледачи';
$ec_lang['install_firefox_body']='Firefox не подржава инсталацију PWA апликација на рачунару. И даље можете нормално користити све калкулаторе у прегледачу — после прве посете, странице се аутоматски чувају у меморији за коришћење без интернета.';
$ec_lang['install_cached_heading']='Шта се чува у меморији';
$ec_lang['install_cached_body']='Приликом прве инсталације EngCalcs-а, све странице калкулатора и пратећи фајлови (скрипте, стилови) аутоматски се чувају на вашем уређају. После тога, све ради без интернетске везе. Ваш избор језика се памти од последње посете уз интернет.';
$ec_lang['contact_main_menu']='Контакт';
$ec_lang['about_main_title']='О инжењерским калкулаторима HawsEDC';
$ec_lang['about_main_desc']='Мисија, отворени код и доприноси';
$ec_lang['about_body_html']='<h3>Мисија</h3><p>Инжењерски Калкулатори HawsEDC постоје да служе инжењерима и теренским радницима широм света — посебно онима који раде у регионима са недостатком воде, ограниченим ресурсима или недовољном покривеношћу. Ови алати су део шире хуманитарне мисије: рећи сваком човеку на најпрактичнији и најефикаснији могући начин да је вољен и цењен заувек, да нема ничег чега треба да се боји и да неће упропастити све.</p><p>Калкулатори су средство. Циљ је свет без патње.</p><h3>Лиценца са Отвореним Изворним Кодом</h3><p>Сав код је објављен под <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU Општом Јавном Лиценцом v3.0 или новијом</a> — слободан у смислу слободе. Код можете користити, проучавати, мењати и даље дистрибуирати под истим условима.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Изворни Код</h3><p>Пуни изворни код јавно је доступан на Bitbucket-у:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Тамо можете прегледати код, пријавити проблеме или направити fork репозиторијума.</p><h3>Допринос</h3><p>Pull захтеви су добродошли. Начини доприноса:</p><ul><li><strong>Преводи</strong> — побољшајте или додајте језик. Отворите pull захтев са изменама у одговарајућем фајлу <code>lib/lang.ec.??.php</code>.</li><li><strong>Пријаве грешака</strong> — користите формулар за повратне информације на bilo kojoj stranici калкулатора или пријавите проблем на Bitbucket-у.</li><li><strong>Нови калкулатори</strong> — идеје за хидрауличко-инжењерске алате који служе теренским радницима и стручњацима за наводњавање посебно су добродошле. Погледајте развојни водич <code>CLAUDE.md</code> у репозиторијуму.</li><li><strong>Хостинг</strong> — ако можете да поставите огледало ових калкулатора за регион са ограниченом повезаношћу, јавите се.</li></ul><h3>Коришћење без интернета</h3><p>Ови калкулатори раде као прогресивна веб апликација (PWA). Посетите било коју страницу калкулатора dok сте повезани на интернет и ваш прегледач ће аутоматски сачувати све калкулаторе у кеш. Након тога, сви калкулатори раде без интернета — интернет није потребан.</p><p>На Android-у или iOS-у користите опцију „Додај на почетни екран" у прегледачу да бисте инсталирали EngCalcs као апликацију на свом уређају. На рачунару потражите икону за инсталацију у адресној траци прегледача.</p><p>Такође можете сачувати сваки калкулатор појединачно помоћу менија „Сачувај као…" у прегледачу за повремену употребу без интернета.</p><h3>Контакт</h3><p>Tom Haws — хидраулички инжењер и аутор ових калкулатора.<br />Користите формулар за повратне информације на bilo kojoj stranici калкулатора или приступите изворном коду на <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket-у</a>.</p>';
$ec_lang['contact_title']='HawsEDC Контакт';
$ec_lang['contactSendMessage']='Пошаљите поруку Тому Хоусу';
$ec_lang['contactYourName']='Ваше име:';
$ec_lang['contactYourEmail']='Ваша е-маил адреса:';
$ec_lang['contactSubject']='Предмет:';
$ec_lang['contact_message']='Порука:';
$ec_lang['contactSpamPrefix']='Пет плус један је';
$ec_lang['contactSpamPostfix']='(Молимо вас напишите речима. 1=jedan 2=dva 3=tri 4=četiri 5=pet 6=šest 7=sedam +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Пошаљи поруку';
$ec_lang['contact_success']='Хвала вам што сте одвојили време да напишете.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Пројектовање Каменог Брзотока (Robinson)';
$ec_lang['rc_main_title']='Бесплатни Онлајн Калкулатор за Пројектовање Каменог Брзотока — Robinson (1998)';
$ec_lang['rc_main_desc']='Димензионисање Каменог Поплочавања за Брзоток — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Пад дна брзотока, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="Проток по јединици ширине при улазу у брзоток. За канал са ширином дна B и укупним протоком Q користите q_t = Q / B.">Јединични проток, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='Порозност каменог поплочавања, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="Густина у односу на воду. Типичан дробљени гранит или базалт ≈ 2,65. Опсег по Robinson: 2,54 до 2,82.">Релативна густина камена, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="Стандардна девијација гранулометријског састава. Уједначен камен ≈ 1,25. Опсег по Robinson: 1,15 до 1,47.">Гранулометрија SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="Успор (Hp > yn) је пожељан — смањује ерозију узводно. (USDA)">Нормална дубина у улазном каналу, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="Јед. 1 (S0 < 0,10) или Јед. 2 (0,10–0,40). Важи: D50 15–278 мм, S0 0,02–0,40. Ван опсега: екстраполација.">Потребна медијанска величина камена, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='Примењена једначина';
$ec_lang['rc_sg_check']='Провера релативне густине';
$ec_lang['rc_SD_check']='Провера гранулометрије SD';
$ec_lang['rc_sg_ok']   ='sg у важећем опсегу';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg испод опсега Robinson';
$ec_lang['rc_sg_low_tip']='Важећи опсег: 2,54–2,82';
$ec_lang['rc_sg_high'] ='sg изнад опсега Robinson';
$ec_lang['rc_sg_high_tip']='Важећи опсег: 2,54–2,82';
$ec_lang['rc_SD_ok']   ='SD у важећем опсегу';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD испод опсега Robinson';
$ec_lang['rc_SD_low_tip']='Важећи опсег: 1,15–1,47';
$ec_lang['rc_SD_high'] ='SD изнад опсега Robinson';
$ec_lang['rc_SD_high_tip']='Важећи опсег: 1,15–1,47';
$ec_lang['rc_layer']='Дебљина слоја поплочавања (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Радијус криве гребена (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Дужина лука криве гребена';
$ec_lang['rc_apron_length']='<span class="ec-help" title="Потребна за конструктивну подршку камена брзотока. „Минимална доња вода која настаје услед излазне деонице и отпора низводног канала довољна је да обезбеди стабилност поплочавања у излазној деоници.“ (Robinson)">Дужина излазне плоче (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='Манингов коефицијент храпавости у брзотоку, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="Део qt који тече кроз поре камена. Остатак qs тече по површини. Подразумевана вредност np = 0,45 за угласти дробљени камен.">Брзина кроз камену мантију, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='Јединични проток кроз мантију, q<sub>m</sub>';
$ec_lang['rc_qs']='Површински јединични проток, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Дубина тока изнад површине поплочавања, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="Успор (Hp > yn) је пожељан — смањује ерозију узводно. (USDA)">Преливна висина на улазу, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='Провера успора на улазу';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — успор узводно';
$ec_lang['rc_pond_ok_tip']='Успор узводно од улаза у брзоток је пожељан — смањује ерозију узводно. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — нема успора — могућа ерозија на улазу';
$ec_lang['rc_pond_warn_tip']='Нема успора узводно од улаза у брзоток; може доћи до ерозије узводно. (USDA)';
$ec_lang['rc_eq1']='Јед. 1 (S<sub>0</sub> < 0,10) — благи пад';
$ec_lang['rc_eq2']='Јед. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — стрми пад';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — испод опсега валидације Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — изнад опсега валидације Robinson';
$ec_lang['rc_notes_1_term']='Једначине за димензионисање камена';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) развили су две емпиријске једначине за медијанску величину поплочавања D<sub>50</sub> на основу пада брзотока и јединичног протока. Једначина 1 се примењује за благе падове (S<sub>0</sub> < 0,10); Једначина 2 — за стрме падове (0,10 ≤ S<sub>0</sub> ≤ 0,40). Обе једначине захтевају q<sub>t</sub> у м²/с и враћају D<sub>50</sub> у мм. Валидирани опсег је 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Јединични проток';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> је укупни јединични проток при гребену брзотока (укупни проток по јединици ширине). За канал са ширином дна B и укупним протоком Q приближно q<sub>t</sub> ≈ Q / B, или израчунајте из услова критичне дубине при улазу у брзоток.';
$ec_lang['rc_notes_3_term']='Проток кроз камену мантију';
$ec_lang['rc_notes_3_def']='Део укупног протока пролази кроз поре каменог поплочавања (проток кроз мантију q<sub>m</sub>); остатак тече по површини камена (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Дубина тока d рачуна се Манинговом једначином примењеном на површински проток q<sub>s</sub> са коефицијентом храпавости брзотока n. Подразумевана порозност n<sub>p</sub> = 0,45 типична је за угласти дробљени камен.';
$ec_lang['rc_notes_5_term']='Важећи опсег величине камена';
$ec_lang['rc_notes_5_def']='Једначине су развијене за опсег D<sub>50</sub> од 15 мм до 278 мм. Резултати ван овог опсега су екстраполација и треба их користити са додатном инжењерском пажњом.';
$ec_lang['rc_notes_6_term']='Кота излазне плоче';
$ec_lang['rc_notes_6_def']='Кота врха поплочавања у излазној деоници треба да буде на нивоу или испод коте дна низводног канала. Ако је виша, излазни камен ће бити нестабилан.';
$ec_lang['rc_notes_7_def']='Када је нормална дубина у улазном каналу мања од преливне висине (H<sub>p</sub>) потребне за пропуштање q<sub>t</sub>, узводно од улаза у брзоток долази до стешњавања тока или успора. То је генерално прихватљиво — успор смањује брзину и спречава ерозију узводно. Ради провере: користите калкулатор прелива да пронађете H<sub>p</sub> за дате q<sub>t</sub> и ширину гребена, па упоредите са нормалном дубином улазног канала. Ако H<sub>p</sub> премашује нормалну дубину, доћи ће до успора.';
$ec_lang['rc_notes_4_term']='Извор';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS такође објављује <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel табелу</a> засновану на истој методи.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Филтер';
$ec_lang['rc_sketch_top_crest_curve'] = 'Крива гребена';
$ec_lang['rc_sketch_outlet_apron']    = 'Излазна плоча';
$ec_lang['rc_sketch_radius']          = 'полупречник';
// Irrigation Pressure (Irrigation Pressure main menu and calculator)
$ec_lang['ip_main_menu']='Притисак наводњавања';
$ec_lang['ip_main_title']='Бесплатни онлајн калкулатор притиска и уједначености дистрибуције наводњавања';
$ec_lang['ip_main_desc']='Притисак тестне гране и процена уједначености';
$ec_lang['ip_h_supply']='Притисак напајања';
$ec_lang['ip_elev_supply']='Кота напајања, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Пројектни проток емитера, q<sub>design</sub>';
$ec_lang['ip_h_design']='Пројектни притисак емитера';
$ec_lang['ip_x']='<span class="ec-help" title="0,5 за стандардне емитере без компензације притиска; близу 0 за емитере са компензацијом притиска">Експонент протока емитера, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Путања теста';
$ec_lang['ip_group_reach']='Деоница';
$ec_lang['ip_group_upstream']='Узводно';
$ec_lang['ip_group_downstream']='Низводно';
$ec_lang['ip_group_loss']='Губитак';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="Означено: ова деоница је сегмент тестне латерале, из које појединачни емитери узимају воду. Неозначено: ова деоница је магистрала, која само преноси проток ка латералама ван путање теста.">Лат. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Редови латерале: емитери само у овој деоници. Редови магистрале: укупан број емитера на латералама ОСИМ ове, које се одвајају од ове деонице. За деоницу магистрале која се завршава код тестне латерале, ово укључује и све латерале даље низ магистралу иза те тачке, или које деле исти чвор (нпр. латерала на супротној страни) — и њихов проток се такође одваја од исте деонице.">Емитери <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Кота низводног краја ове деонице. Опционо код унутрашњих редова (подразумевано равно / исто као претходни чвор ако се остави празно). Обавезно у последњем реду: та вредност је кота последњег емитера, која директно одређује потребан притисак напајања.">Низв. кота <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='Кота последњег емитера (последњи ред) остављена је празна и подразумевана као равна — унесите је ради тачног резултата';
$ec_lang['ip_flow']='Проток';
$ec_lang['ip_press']='Прит.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Укупни губитак деонице, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Низак/негативан притисак — проверите услове испод атмосферског притиска';
$ec_lang['ip_pressure_warn_short']='Низак';
$ec_lang['ip_pressure_high']='Локације са високим притиском захтевају редукцију притиска';
$ec_lang['ip_pressure_high_short']='Висок';
$ec_lang['ip_max_head']='Макс. доз. притисак цеви';
$ec_lang['ip_max_head_tip']='Линије чији притисак прелази ову вредност се означавају. Оставите празно да прескочите проверу високог притиска.';
$ec_lang['ip_h_far']='Притисак последњег емитера';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Проток који улази само у моделирану путању теста — за целу зону/систем, погледајте Q_zone у делу Пројектовање примене испод.">Проток напајања путање теста, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Проток последњег емитера, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Просечан проток емитера (тестна латерала), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Колико виши (или нижи) процењујете да ради типична латерала у поређењу са овом тестном латералом. Тестна латерала је намерно претпостављени најнеповољнији случај, тако да њен сопствени просек потцењује просек на терену — ако се остави на 0, провера уједначености и бројеви пројектовања примене испод користе сопствени (вероватно оптимистички) просек тестне латерале какав јесте.">Проц. Δпритисак, просек наспрам тестне латерале <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral поново израчунат при притиску сваког реда латерале, увећан за унету разлику притиска изнад — покушај исправке за то што је тестна латерала претпостављени најнеповољнији случај, а не репрезентативан. Улази и у проверу уједначености и у одељак Пројектовање примене испод.">Проц. просечан проток емитера на терену, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Израчунати проток последњег емитера подељен процењеним просечним протоком емитера на терену — ово је приближна процена стандардне равномерности расподеле нижег квартила (просек најниже групе ÷ средња вредност популације); заснована је на малом моделираном узорку и корисничкој процени, а не на пуном статистичком узорку са терена. Вредности једнаке или веће од 1 су могуће и исправне: то само значи да је притисак последњег емитера једнак или виши од процењеног просека на терену, па је неки други емитер тачка најнижег притиска. Ово може бити зато што је последњи емитер на нижем терену, или зато што је процена Δпритиска премала.">Провера уједначености, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='Притисак код тестног емитера ≥ притисак напајања. Ово вероватно није најнеповољнији емитер, или би цеви могле бити мање.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Ово се разликује од наше приближне процене стандардне мере уједначености.">Проток последњег емитера ÷ пројектни проток, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Нема решења: потребан притисак напајања премашује унети притисак напајања. Повећајте притисак напајања, смањите потрошњу или користите већу цев.';
$ec_lang['ip_notes_1_def']='Претпоставља притисак код последњег (најудаљенијег) емитера, а затим враћа Енергетску линију уназад ка напајању, деоницу по деоницу, додајући губитке трењем и локалне губитке дуж пута. Кота и брзинска висина се одузимају на сваком чвору да би се пријавио стварни притисак тамо. Претпостављени притисак на далеком крају подешава се (бисекцијом) док се израчунати потребан притисак напајања не поклопи са унетим притиском напајања — исти затворени проблем који решава решавач протока на калкулатору Проток кроз цев по Manningovoj формули, проширен на разгранату мрежу.';
$ec_lang['ip_notes_2_term']='Магистралне наспрам латералних деоница';
$ec_lang['ip_notes_2_def']='Сваки ред представља једну деоницу дуж једне, хидраулички најнеповољније путање (путање теста) од напајања до последњег емитера. Магистрална деоница само преноси проток ка латералама које нису на путањи теста, тако да је њено одузимање проста множина (пројектни проток × укупан број емитера у деоници) — без локалне осетљивости на притисак. Магистрала је заједничка носећа цев, па деоница магистрале која се завршава код тестне латерале мора да укључи не само латерале између сопствених крајева, већ и све латерале даље низ магистралу иза те тачке, или које деле исти чвор (нпр. латерала на супротној страни) — њихов проток пролази кроз ту исту деоницу пре него што се одвоји, без обзира да ли се појављују негде другде у овој табели. Латерална деоница је сегмент саме тестне латерале: проток емитера рачуна се из стварног локалног притиска преко q = k·H<sup>x</sup>, а губитак трењем се умањује Christiansenовим фактором F(n) како би се узело у обзир смањење протока док сваки емитер у деоници узима воду.';
$ec_lang['ip_notes_3_term']='Ограничења';
$ec_lang['ip_notes_3_def']='Моделира један фиксни притисак напајања (без криве пумпе), само једну путању теста (не цело поље), и криву емитера са 2 параметра (поставите експонент близу 0 да бисте приближили емитер са компензацијом притиска). Извештавају се два различита односа уједначености, намерно одвојена: q<sub>last</sub>/q<sub>avg,field</sub> је приближна процена стандардне равномерности расподеле нижег квартила (просек најниже групе ÷ средња вредност популације); али је заснована на малом моделираном узорку и корисничкој процени, а не на стандардном пуном статистичком узорку са терена. Такође, тестна латерала је намерно претпостављени најнеповољнији случај, тако да би њен сирови, неисправљени просек потценио стварни просек на терену и учинио да уједначеност изгледа боље него што јесте; унос Δпритиска постоји управо да би се супротставио тој пристрасности. Вредности уједначености једнаке или веће од 1 су и даље могуће: то само значи да је притисак последњег емитера једнак или виши од процењеног просека на терену, па је неки други емитер тачка најнижег притиска. Ово може бити зато што је последњи емитер на нижем терену, или зато што је процена Δпритиска премала. q<sub>last</sub>/q<sub>design</sub> је другачија провера, која се не тиче уједначености, наспрам произвођачки декларисаног протока — корисна за откривање прекомерно или недовољно притиснутог система у целини, али је то одвојена провера коју треба читати уз број уједначености, пошто пројектни/декларисани проток не зависи од стварног средњег радног притиска система.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). “Irrigation by sprinkling.” California Agricultural Experiment Station Bulletin 670. ASAE/ASABE стандарди за пројектовање микронаводњавања користе исти приступ прорачуна губитака трењем за вишеструке изливне тачке.';
$ec_lang['ip_notes_5_term']='Пројектовање примене';
$ec_lang['ip_notes_5_def']='Интензитет наводњавања и проток система/зоне користе процењени просечан проток емитера на терену (q<sub>avg,field</sub> — сопствени просек тестне латерале, исправљен унетом проценом Δпритиска), а не претпостављену вредност: PR = q<sub>avg,field</sub> / A<sub>e</sub>, заснован на исправљеној моделираној вредности. Размак и укупан број латерала/емитера у систему су овде одвојени улази, јер путања теста моделира само једну најнеповољнију грану, а не сваку латералу на терену.';


// --- Branched Pipe Network (bn_) --- English source / fallback (translation pending) ---
$ec_lang['bpn_main_menu']='Разграната цевна мрежа';
$ec_lang['bpn_main_title']='Бесплатни онлајн калкулатор притиска у разгранатој цевној мрежи (без петљи)';
$ec_lang['bpn_main_desc']='Проток и притисак у разгранатој (стаблоликој) цевној мрежи';
$ec_lang['bpn_h_source_tip']='Статички напор напајања: напор извора при нултом протоку. Ниво воде у резервоару или цистерни изнад коте напајања, или напор пумпе при затвореном вентилу. Додајте тачке напајања 2 и 3 да бисте дефинисали криву пумпе или променљиву криву напајања; алат очитава напор при пројектном протоку.';
$ec_lang['bpn_elev_source']='Кота напајања';
$ec_lang['bpn_q_total']='Укупан проток';
$ec_lang['bpn_q_total_tip']='Укупан проток који напушта извор (збир свих потрошњи у мрежи).';
$ec_lang['bpn_p_min']='Најнижи притисак';
$ec_lang['bpn_p_min_tip']='Најнижи низводни притисак било где у мрежи; критична тачка испоруке.';
$ec_lang['bpn_method']='Метода трења';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='Цевне линије';
$ec_lang['bpn_id']='ID';
$ec_lang['bpn_id_tip']='Назив ове цевне линије. Друге линије је наводе у колони Узводни ID.';
$ec_lang['bpn_upstream']='Узводни ID';
$ec_lang['bpn_upstream_tip']='ID линије која напаја ову линију. Оставите празно да следи линију непосредно изнад (обичан серијски цевовод). Унесите ID овде да бисте се одвојили од друге линије.';
$ec_lang['bpn_roughness_tip']='Храпавост цеви за изабрану методу трења: Манингов коефицијент n, Hazen-Williams коефицијент C, или висина храпавости e по Darcy-Weisbachu (дужина). Типична глатка пластична цев: n око 0,009, C око 150, e око 0,0015 mm.';
$ec_lang['bpn_demand']='Потрошња';
$ec_lang['bpn_demand_tip']='Фиксни проток испоручен на низводном крају ове линије. Оставите празно за линију која само преноси проток даље.';
$ec_lang['bpn_demand_mult']='Множилац потрошње';
$ec_lang['bpn_demand_mult_tip']='Скалира потрошњу свих линија истовремено, за прорачун вршног часа или будућег раста. Користите 1 за потрошње унете као што јесу.';
$ec_lang['bpn_elev_down']='Низв. кота';
$ec_lang['bpn_q_line']='Проток линије';
$ec_lang['bpn_q_line_tip']='Укупан проток кроз ову линију: сопствена потрошња плус свака низводна потрошња коју напаја.';
$ec_lang['bpn_p_down']='Низв. прит.';
$ec_lang['bpn_p_down_tip']='Манометарски притисак (напор) на низводном чвору ове линије. Негативна вредност (означена) значи притисак испод атмосферског; проверите пројекат.';
$ec_lang['bpn_sketch_title']='Шема мреже';
$ec_lang['bpn_show_length']='Дужина';
$ec_lang['bpn_show_diameter']='Пречник';
$ec_lang['bpn_show_q']='Проток';
$ec_lang['bpn_show_p']='Притисак';
$ec_lang['bpn_source_label']='Извор';
$ec_lang['bpn_topology_warn']='Проверите колону Узводни ID: нека линија упућује на непознат ID, упућује на саму себе или формира петљу, па део мреже није повезан са извором. Те линије остају нерешене.';
$ec_lang['bpn_topology_warn_short']='Мрежа';
$ec_lang['bpn_pressure_warn']='Низак/негативан притисак; проверите услове испод атмосферског притиска';
$ec_lang['bpn_pressure_warn_short']='Низак';
$ec_lang['bpn_notes_1_term']='Серијски подразумевано, гранање по изузетку';
$ec_lang['bpn_notes_1_def']='Оставите Узводни ID празним и линија прати ону изнад ње; обичан серијски цевовод. Унесите ID узводне линије да бисте се одвојили од ње. Дакле: серијски подразумевано, стабло када вам затреба.';
$ec_lang['bpn_notes_2_term']='Само разгранате мреже, без петљи';
$ec_lang['bpn_notes_2_def']='Свака линија има тачно једну узводну линију (стабло). Овај алат не решава мреже са петљама; за то су потребне итеративне методе (EPANET или слично). Изостављање петљи је оно што овај алат чини једноставним и тачним.';
$ec_lang['bpn_notes_3_term']='Без активних регулатора притиска';
$ec_lang['bpn_notes_3_def']='Можете додати фиксни вентил локалног губитка (k-вредност), али не и вентиле за смањење или одржавање притиска (PRV/PSV). Њихово отворено/затворено стање зависи од протока и притиска, што би захтевало итерацију.';
$ec_lang['bpn_supply2_q']='Проток напајања 2';
$ec_lang['bpn_supply2_h']='Напор напајања 2';
$ec_lang['bpn_supply3_q']='Проток напајања 3';
$ec_lang['bpn_supply3_h']='Напор напајања 3';
$ec_lang['bpn_supply_pt_tip']='Опционе тачке 2 и 3 криве напајања. Унесите проток и напор за сваку да бисте моделирали пумпу, или било који извор чији напор опада како испоручује више; алат очитава напор при пројектном протоку. Тачка 1 изнад је статички напор при нултом протоку. Оставите 2 и 3 празним за константан напор резервоара.';
$ec_lang['bpn_h_supply']='Напор напајања';
$ec_lang['bpn_h_supply_tip']='Напор извора при пројектном протоку, очитан са криве напајања. Једнак унетом напору извора када је крива равна (резервоар).';
$ec_lang['bpn_show_elevation']='Кота';
$ec_lang['bpn_supply1_h']='Статички напор напајања';
