<?php

// ñáéíóú All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fracción";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="pies^2";
$ec_lang['u_ft3ps']="pies^3/seg";
$ec_lang['u_fth2o']="pies ca";
$ec_lang['u_ft']="pies";
$ec_lang['u_ftps']="pies/seg.";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_grade']="vert./horiz.";
$ec_lang['u_gradePercent']="% $ec_lang[u_grade]";
$ec_lang['u_in']="pulg.";
$ec_lang['u_in2']="$ec_lang[u_in]^2";
$ec_lang['u_inh2o']="pulg. ca";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="Mgal/día";
$ec_lang['u_mh2o']="mca";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mmca";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/pie^2";
$ec_lang['u_psi']="lb/pulg^2";
$ec_lang['u_s']="seg";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
$ec_lang['menu_brand']='Calculadoras HawsEDC';
$ec_lang['menu_main_list']='Lista de calculadoras';
$ec_lang['menu_main_hydraulics']='Hidráulica';
$ec_lang['menu_main_language']='Idioma';
$ec_lang['menu_more']='Más';
$ec_lang['template_welcome']='>> Dejad vuestros miedos en la puerta; el amor se habla aquí. No estáis arruinando todo. Disfrutad también <a target="_blank" href="https://hawsedc.com/download.php">las herramientas libres HawsEDC para AutoCAD.</a> <<';
$ec_lang['template_translation_help']='¿Tiene usted una gran visión para una calculadora que agregar aquí?  ¿Me puede ayudar a traducir esta calculadora a su idioma?  ¿Quisiera Ud. poner esta calculadora en su propio sitio web?';
$ec_lang['template_feedback']='Tenga la amabilidad de enviarnos sus comentarios. ¿Le fue útil esta calculadora?';
$ec_lang['template_printable_title']='Título Imprimible';
$ec_lang['template_printable_subtitle']='Subtítulo Imprimible';
$ec_lang['index_title']='Calculadoras para ingenieros gratis en línea';
$ec_lang['calc_set_units']='Cambiar sistema de medidas:';
$ec_lang['points_data_help']='(o bien Copiar/Pegar usando el área de datos)';
$ec_lang['points_data_title']='Datos de los puntos<br />(separados por comas o tabulaciones)';
$ec_lang['points_data_copy']='Copiar';
$ec_lang['points_data_paste']='Pegar';
$ec_lang['calc_inputs']='Ingresos';
$ec_lang['calc_results']='Resultados: ';
$ec_lang['view_hide_line']='[Ocultar esta línea]';
$ec_lang['view_printable']='Versión Imprimible (recargar/renover para restaurar)';
$ec_lang['ec_name_label']='Guardar este cálculo:';
$ec_lang['ec_name_placeholder']='Nombre';
$ec_lang['ec_name_hint']='Guarda los datos de entrada en la URL para marcapáginas, recuperar del historial y compartir';
$ec_lang['ec_name_invalid']='Use solo letras, dígitos, espacios, – _ .';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Pérdida de presión en una tubería según Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculadora gratis en línea de pérdida de presión en una tubería según Darcy-Weisbach';
$ec_lang['dw_main_desc']='Pérdida de presión en una tubería a partir de diámetro, rugosidad, y gasto según Darcy-Weisbach';
$ec_lang['dw_roughness']='Rugosidad absoluto, e';
$ec_lang['dw_kinematic_viscosity']='Viscosidad cinemática, ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['dw_reynolds_number']='Número de Reynolds, Re';
$ec_lang['dw_flow_regime']='Régimen del flujo';
$ec_lang['dw_regime_laminar']='flujo laminar';
$ec_lang['dw_regime_transitional']='transicional';
$ec_lang['dw_regime_turbulent']='turbulente';
$ec_lang['dw_friction_factor_method']='Método del factor de fricción';
$ec_lang['dw_friction_factor']='Factor de fricción, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Pérdida de presión en una tubería según Hazen-Williams';
$ec_lang['hw_main_title']='Calculadora gratis en línea de pérdida de presión en una tubería según Hazen-Williams';
$ec_lang['hw_main_desc']='Calculadora de pérdida de presión en una tubería a partir de diámetro, rugosidad, y gasto según Hazen-Williams';
$ec_lang['hw_roughness']='Coeficiente de Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canal irregular según Manning';
$ec_lang['mi_main_title']='Calculadora gratis en línea de un canal irregular según Manning';
$ec_lang['mi_main_desc']='Calculadora de un canal irregular con flujo uniforme según Manning';
$ec_lang['mi_waterSurfaceElevation']='Altura de la lámina libre';
$ec_lang['mi_q_617']='Q por sumación de regiones con n compuesto según Chow 6-17 velocidades iguales';
$ec_lang['mi_xSecPoints']='Puntos de la sección traversal';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Alt.';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='Div. de<br />regiónes<br />R<sub>h</sub>y Q<br />(Banco)';
$ec_lang['mi_t']='T';
$ec_lang['mi_tau']='Fza. tang.<br />τ';
$ec_lang['mi_a']='A';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_notes']='Notas';
$ec_lang['mi_notes_1_term']='Métodos de calcular Q';
$ec_lang['mi_notes_1_def']='Q por sumación de segmentos estima por bajo la contribución friccional de segmentos con alto pendiente traversal. Q por sumación de regiones con n compuesto estima por alto el efecto de la fricción en áreas anchas de poca profundidad en el flujo en áreas más profundas (canal primario).';
$ec_lang['mi_notes_2_term']='Tamaño mediano de roca';
$ec_lang['mi_notes_2_def']='El tamaño mediano D<sub>50</sub> según Strickler es el tamaño (por un canal derecho y limpio) implicado por la rugosidad dada. Los otros tamaños D<sub>50</sub> son los requeridos para resistir la erosión según 1) el condado de Maricopa County, Arizona, USA, y Robinson Rock Chutes, 2) Maynord, Ruff, y Abt (1989), y 3) Searcy (1967)';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Flujo según Manning en tuberías';
$ec_lang['mpf_main_title']='Calculadora gratis en línea de la fórmula de Manning para flujo uniforme en tuberías';
$ec_lang['mpf_main_desc']='Cálculo por Manning de caudal y velocidad de flujo en tuberías a partir de pendiente y sección';
$ec_lang['mpf_spreadheet_notice']='Estrene la versión de esta calculadora en una hoja de cálculo';
$ec_lang['mpf_pipe_diameter']='Diámetro de la tubería, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Rugosidad según Manning, n';
$ec_lang['mpf_friction_slope']='Pendiente hidráulica (o quizás <a target="_blank" href="/pressureslope.php">?</a> de la tubería), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Relación de calados, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Caudal, q';
$ec_lang['mpf_velocity']='Velocidad, v';
$ec_lang['mpf_velocity_head']='Energía cinética, hv';
$ec_lang['mpf_flow_area']='Sección mojada, a';
$ec_lang['mpf_pipe_area']='Sección llena, a<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Relación de secciones, a/a<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Perímetro mojado, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Radio hidráulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Ancho de lámina libre, T';
$ec_lang['mpf_froude_number']='Número de Froude, F';
$ec_lang['mpf_shear_stress']='Tensión tangencial promedio (fuerza de tracción), tau';
$ec_lang['mpf_full_flow']='Caudal lleno, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Relación de caudales, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Este es el caudal (también la profundidad) dentro de una tubería <em>de largo infinito</em>.</dt><dd>El alcanzar que el caudal entre a la tubería puede requerir un cabezal bastante más alto. Agregue por lo menos 1,5 veces la energía cinética al calado o <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">haga los cálculos de cabecera de alcantarilla de una manera estándar utilizando HY-8.</a> </dd>';
$ec_lang['mpf_solve_for_dd0']='Calcular y/d<sub>0</sub> para un Q dado';
$ec_lang['mpf_solve_desc']='Usando D<sub>0</sub>, n y S<sub>0</sub> del formulario de la calculadora, encuentra el menor y/d<sub>0</sub> para un Q dado.';
$ec_lang['mpf_solve_button']='Calcular';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Pérdida de presión en una tubería según Manning';
$ec_lang['mphl_main_title']='Calculadora gratis en línea de la pérdida de altura de presión en una tubería según Manning';
$ec_lang['mphl_main_desc']='La pérdida de presión en una tubería llena a partir de gasto';
$ec_lang['mphl_pipe_length']='Longitud de la tubería, l';
$ec_lang['mphl_area']='Área, A';
$ec_lang['mphl_total_junction_k']='Coeficiente total de pérdida en las juntas, k';
$ec_lang['mphl_friction_slope']='Pendiente de fricción, s<sub>f</sub>';
$ec_lang['mphl_friction_loss']='Pérdidas por fricción';
$ec_lang['mphl_junction_loss']='Pérdidas en las juntas';
$ec_lang['mphl_total_loss']='Pérdida total';
$ec_lang['mphl_egl_1']='EGL aguas abajo';
$ec_lang['mphl_egl_2']='EGL aguas arriba';
$ec_lang['mpf_see_notes']='(Véanse las notas)';
$ec_lang['mphl_hgl_2']='HGL aguas arriba en la tubería ' . $ec_lang['mpf_see_notes'];
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapecial según Manning';
$ec_lang['mtc_main_title']='Calculadora gratis en línea de la fórmula de Manning para canal trapecial';
$ec_lang['mtc_main_desc']='Flujo uniforme Manning en un canal trapecial a partir de pendiente y profundidad';
$ec_lang['mtc_bottom_width']='Anchura de la base';
$ec_lang['mtc_side_slope_1']='Pendiente de lado 1 (horizontal / vertical)';
$ec_lang['mtc_side_slope_2']='Pendiente de lado 2 (horizontal / vertical)';
$ec_lang['mtc_channel_slope']='Pendiente del canal (vertical / horizontal)';
$ec_lang['mtc_flow_depth']='Calado de la lámina de agua, y';
$ec_lang['mtc_bend_angle']='Ángulo de la curva<a href="riprap-bend-angle.png" title="Haz clic para ver imagen">?</a> (para el tamaño de roca)';
$ec_lang['mtc_sgrock']='Gravedad específica de la roca (2.65)';
$ec_lang['mtc_d50_in']='Tamaño de roca';
$ec_lang['mtc_d50_bottom']='Tamaño de roca requerido en el fondo, D<sub>50</sub>, Maricopa County <span title="Cuando S0 < 2% según Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% según Robinson Rock Chute " style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Tamaño de roca requerido en el lado 1, D<sub>50</sub>, Maricopa County <span title="Cuando S0 < 2% según Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% según Robinson Rock Chute " style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Tamaño de roca requerido en el lado 2, D<sub>50</sub>, Maricopa County <span title="Cuando S0 < 2% según Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% según Robinson Rock Chute " style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Tamaño de roca requerido, D<sub>50</sub>, según Maynord, Ruff, y Abt (1989)';
$ec_lang['mtc_d50_searcy']='Tamaño de roca requerido, D<sub>50</sub>, según Searcy (1967)';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Vertedero hidráulico sencillo';
$ec_lang['ws_main_title']='Calculadora de gasto en un vertedero hidráulico sencillo';
$ec_lang['ws_main_desc']='Calculadora de gasto en un vertedero hidráulico sencillo';
$ec_lang['ws_weirLength']='Longitud del vertedero, l';
$ec_lang['ws_headWaterHeight']='Altura de cabezal, h';
$ec_lang['ws_weirCoefficient']='Factor para el vertedero hidráulico, Cw';
$ec_lang['ws_notes_heading']='Notas';
$ec_lang['ws_notes_we_term']='Fórmula de un vertedero';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Vertedero hidráulico irregular';
$ec_lang['wi_main_title']='Calculadora gratis en línea para vertedero hidráulico irregular, de profundidad variable';
$ec_lang['wi_main_desc']='Calculadora de gasto para un vertedero irregular de profundidad variable';
$ec_lang['wi_headWaterelevation']='Nivel de cabezal';
$ec_lang['wi_weirPoints']='Puntos del vertedero hidráulico';
$ec_lang['wi_station']='Distancia';
$ec_lang['wi_elevation']='Nivel';
$ec_lang['wi_pondingHeight']='Altura de inundación';
$ec_lang['wi_incrementalFlow']='Gasto adicional';
$ec_lang['wi_cumulativeFlow']='Gasto total';
$ec_lang['wi_save_and_calculate']='Grabar y calcular';
$ec_lang['wi_notes_we_term']='Ecuación de Vertedero';
$ec_lang['wi_notes_we_def']='q = si (distancia = 0) entonces 0 o si (slope=0) entoces cw*distancia*d<sub>0</sub><sup>1.5</sup> o cw/(2.5*pendiente) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) donde d<sub>1</sub> y d<sub>0</sub> son siempre positivos o cero';
// Orifice Flow
$ec_lang['or_main_menu']='Flujo por Orificio';
$ec_lang['or_main_title']='Calculadora gratuita en línea de flujo por orificio';
$ec_lang['or_main_desc']='Flujo por Orificio — Libre o Sumergido';
$ec_lang['or_shape']='Forma de la apertura';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Rectangular';
$ec_lang['or_diameter']='Diámetro o altura, D <span title="Diameter for circular; height for rectangular" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_width']='Ancho, W <span title="Rectangular openings only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_invert']='Cota de la solera <span title="Bottom of opening" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_hwe']='Elevación de la lámina de agua aguas arriba';
$ec_lang['or_twe']='Elevación de la lámina de agua aguas abajo';
$ec_lang['or_cd']='Coeficiente de descarga, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Elevación del centroide';
$ec_lang['or_head']='Carga efectiva, h';
$ec_lang['or_area']='Área de la apertura, A';
$ec_lang['or_flow']='Caudal, Q';
$ec_lang['or_regime']='Verificación del régimen de orificio';
$ec_lang['or_regime_valid']='Salida libre — régimen de orificio válido ✓';
$ec_lang['or_regime_submerged']='Orificio sumergido (TWE sobre el centroide) — válido ✓';
$ec_lang['or_regime_warn']='Advertencia: lámina aguas arriba bajo la clave — no es régimen de orificio';
$ec_lang['or_regime_twe_above_hwe']='Advertencia: agua de cola (TWE) sobre agua de cabeza (HWE) — verifique las entradas';
$ec_lang['or_notes_1_term']='Ecuación de orificio';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Salida libre: h = HWE − centroide. Sumergido (TWE sobre la solera): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Régimen de orificio';
$ec_lang['or_notes_2_def']='Las ecuaciones de flujo por orificio aplican cuando la lámina aguas arriba está sobre la clave de la apertura. Cuando está bajo la clave, use una ecuación de vertedero.';
$ec_lang['or_notes_3_term']='Coeficiente de descarga';
$ec_lang['or_notes_3_def']='C<sub>d</sub> es aproximadamente 0,60–0,65 para orificios de borde agudo. Entradas redondeadas o reentrantes tienen valores diferentes. Consulte <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> o el Manual de Referencia Hidráulica de HEC-RAS.';
$ec_lang['or_notes_4_term']='Sumersión';
$ec_lang['or_notes_4_def']='Cuando TWE está sobre la solera de la apertura, la calculadora aplica automáticamente la ecuación de orificio sumergido con h = HWE − TWE. Cuando TWE es igual o inferior a la solera, se asume salida libre y h = HWE − centroide.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Tiempo de vaciado por orificio';
$ec_lang['odt_main_title']='Calculadora gratuita en línea de tiempo de vaciado por orificio — Estanque, laguna o depósito';
$ec_lang['odt_main_desc']='Tiempo de vaciado de estanque o laguna por orificio — Método del volumen cónico';
$ec_lang['odt_h1_elev']='Cota inicial WSE <span title="Starting water surface elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_a1']='Área inicial, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Cota final WSE';
$ec_lang['odt_h_orifice']='Cota del centroide del orificio';
$ec_lang['odt_a0']='Área a nivel orificio, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Área final, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_h2_check']='Verificación de cota final';
$ec_lang['odt_h2_ok']='Cota final sobre la cima del orificio ✓';
$ec_lang['odt_h2_warn']='Advertencia: cota final igual o inferior a la cima del orificio (centroide + D/2)';
$ec_lang['odt_d']='Orificio D <span title="Diameter (circular) or height (rectangular)" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_w']='Ancho orificio, W <span title="Rectangular only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_t_sec']='Tiempo drenaje (s)';
$ec_lang['odt_t_min']='Tiempo drenaje (min)';
$ec_lang['odt_t_hr']='Tiempo drenaje (hr)';
$ec_lang['odt_t_day']='Tiempo drenaje (days)';
$ec_lang['odt_notes_1_term']='Fórmula';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) da el tiempo de vaciado desde la carga H hasta el orificio. Tiempo de vaciado = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), donde H<sub>1</sub> = cota inicial − cota del orificio, H<sub>2</sub> = cota final − cota del orificio.';
$ec_lang['odt_notes_2_term']='Método';
$ec_lang['odt_notes_2_def']='El método del volumen cónico modela el estanque o laguna como una sección cónica entre el área inicial A<sub>1</sub> en la lámina de agua inicial y el área A<sub>0</sub> a la cota del centroide del orificio. A<sub>2</sub>, el área del estanque a la cota final, se interpola de A<sub>1</sub> y A<sub>0</sub> usando el modelo de sección cónica. El tiempo de vaciado desde la cota inicial hasta la final es igual al tiempo total de vaciado desde H<sub>1</sub> hasta el orificio menos el tiempo de vaciado restante desde H<sub>2</sub> hasta el orificio.';
$ec_lang['odt_h1']='Carga inicial, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_q_max']='Flujo máx, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volumen vaciado';
$ec_lang['odt_sketch_start']='Inicio';
$ec_lang['odt_sketch_end']='Fin';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Medición de Caudal de Riego';
$ec_lang['irr_main_title']='Calculadoras en línea gratuitas para la medición de caudal de riego';
$ec_lang['irr_main_desc']='Medición de Caudal de Riego — Vertederos y Orificios';
$ec_lang['contact_title']='Contacto con HawsEDC';
$ec_lang['contactSendMessage']='Envíe un mensaje a Tom Haws';
$ec_lang['contactYourName']='Su nombre:';
$ec_lang['contactYourEmail']='Su dirección de correo electrónico:';
$ec_lang['contactSubject']='Asunto:';
$ec_lang['contact_message']='Mensaje:';
$ec_lang['contactSpamPrefix']='Five (cinco) plus (y) one (uno) equals (son) ';
$ec_lang['contactSpamPostfix']='(Favor de escribirla en inglés con letras. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Enviar Mensaje';
$ec_lang['contact_success']='Gracias por tomarse el tiempo para escribir.';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Ancho de orilla a orilla';
$ec_lang['essc_mcr']='Radio mínimo de curvatura';
$ec_lang['essc_q']='Caudal, Q';
// Hazen-Williams HGL
$ec_lang['hw_hgl_1']='HGL aguas abajo';
$ec_lang['hw_hgl_2']='HGL aguas arriba';
// Manning Irregular additional keys
$ec_lang['mi_d50in']='Diam.<br />mediano<br />de la<br />roca';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_groupPoint']='Punto';
$ec_lang['mi_groupRegion']='Región';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_n617']='n<br />compuesto';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_v617']='v';
// Manning Pipe Head Loss note
$ec_lang['mphl_note_1']='<dl><dt>Para una entrada abierta (alcantarilla), es necesario verificar las condiciones de control de entrada.</dt><dd>1. El HGL aguas arriba no puede ser inferior a la cota de flujo a profundidad normal aguas arriba (ni inferior a la tubería).</dd><dd>2. El cabezal de una alcantarilla se representa mejor con el EGL aguas arriba que con el HGL aguas arriba.</dd><dd>3. Véase <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">mi tutorial de 2 minutos</a> para cálculos estándar de cabezal en alcantarillas usando HY-8.</dd>';
// Manning Trapezoidal Channel additional keys
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_n_bathurst']='n para el tamaño de roca de diseño según Bathurst';
$ec_lang['mtc_n_blodgett']='n para el tamaño de roca de diseño según Blodgett';
$ec_lang['mtc_n_strickler']='n para el tamaño de roca de diseño según Strickler';
$ec_lang['mtc_note_1']='<dl><dt>Iteración automática para diseño de tamaño y rugosidad de roca</dt><dd>Elija un botón de radio de rugosidad (se recomienda BB) y un botón de radio para el tamaño de roca de diseño (se recomienda Isbash). Ajuste la profundidad y el factor de seguridad del tamaño de roca para obtener el caudal deseado con un tamaño de roca uniforme. Cada vez que cambie cualquier valor de entrada, ocurre el siguiente ciclo de iteración: 1. Se calcula la rugosidad a partir del tamaño de roca de diseño. 2. El cálculo de rugosidad solicitado se copia al campo de rugosidad. 3. Se calculan el caudal del canal y el tamaño de roca requerido. 4. Se ajusta el tamaño de roca de diseño. 5. Se repite hasta que el error en el tamaño de roca de diseño sea muy pequeño.</dd><dt>Calculadora básica (sin iteración)</dt><dd>Ingrese el valor de rugosidad deseado. Ignore el área de entrada del tamaño de roca de diseño.</dd></dl>';
// Orifice Flow additional key
$ec_lang['or_velocity']='Velocidad, v';
// Robinson Rock Chute
$ec_lang['rrc_main_desc']='Hoja de cálculo para el diseño de bajantes de rocado según el método de Robinson';
$ec_lang['rrc_main_menu']='Diseño de Bajante de Rocado según Robinson';


// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hidroeléctrica';
$ec_lang['mhp_main_title']='Calculadora Gratuita de Potencia Micro-Hidroeléctrica';
$ec_lang['mhp_main_desc']='Calculadora de Potencia de Micro-Hidroeléctrica de Pasada';
$ec_lang['mhp_flow']='Caudal, Q';
$ec_lang['mhp_gross_head']='Altura bruta, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diámetro de la tubería de presión, D';
$ec_lang['mhp_length']='Longitud de la tubería de presión, L';
$ec_lang['mhp_roughness']='Rugosidad de la tubería, e';
$ec_lang['mhp_km']='Coef. pérdidas menores, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_nu']='Viscosidad cinemática, ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_efficiency']='Rendimiento de la instalación, η (0–1)';
$ec_lang['mhp_velocity']='Velocidad del flujo, v';
$ec_lang['mhp_vel_check']='Verificación de velocidad';
$ec_lang['mhp_f']='Factor de fricción, f';
$ec_lang['mhp_hf']='Pérdida de carga por fricción, h<sub>f</sub>';
$ec_lang['mhp_hm']='Pérdida menor, h<sub>m</sub>';
$ec_lang['mhp_hl']='Pérdida total en la tubería de presión, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Verificación de pérdida de carga';
$ec_lang['mhp_hnet']='Altura neta, H<sub>net</sub>';
$ec_lang['mhp_power']='Potencia producida, P';
$ec_lang['mhp_annual_kwh']='Energía anual al 100% de capacidad';
$ec_lang['mhp_vel_ok']='1–3 m/s — dentro del objetivo ✓';
$ec_lang['mhp_vel_low']='Velocidad baja — riesgo de sedimentación y entrada de aire.';
$ec_lang['mhp_vel_high']='Velocidad elevada — riesgo de golpe de ariete y pérdidas menores.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Alto';
$ec_lang['mhp_vel_low_short']='Bajo';
$ec_lang['mhp_hl_ok']='dentro del objetivo del 10% ✓';
$ec_lang['mhp_hl_warn']='supera el objetivo del 10% — considerar tubería más grande ⚠';
$ec_lang['mhp_hl_bad']='supera el 20% — redimensionar la tubería';
$ec_lang['mhp_notes_1_term']='Pérdida de carga';
$ec_lang['mhp_notes_1_def']='La pérdida total en la tubería de presión h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, donde h<sub>f</sub> = f(L/D)(v²/2g) es la pérdida por fricción de Darcy-Weisbach y h<sub>m</sub> = k<sub>m</sub>·v²/2g cubre entradas, codos y válvulas. Altura neta H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Velocidad';
$ec_lang['mhp_notes_2_def']='Objetivo: 1–3 m/s. Por debajo de 1 m/s la tubería queda sobredimensionada para el caudal; por encima de 3 m/s aumentan las pérdidas por fricción y el riesgo de golpe de ariete.';
$ec_lang['mhp_notes_3_term']='Objetivo de pérdida de carga';
$ec_lang['mhp_notes_3_def']='Las pérdidas en la tubería de presión inferiores al 10% de la altura bruta son generalmente económicas. La compensación óptima entre el coste de la tubería y la potencia perdida suele situarse en torno al 4–6% para instalaciones de electricidad de alto valor.';
$ec_lang['mhp_notes_4_term']='Pérdidas menores k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Valores típicos: entrada con borde vivo 0,5, cada codo de 45° 0,2–0,3, válvula compuerta (totalmente abierta) 0,1, válvula mariposa 0,2. Sume todos los accesorios para obtener el k<sub>m</sub> total. El valor por defecto 1,5 supone una entrada y dos codos.';
$ec_lang['mhp_notes_5_term']='Rugosidad de la tubería e';
$ec_lang['mhp_notes_5_def']='Rugosidad absoluta típica: acero (nuevo) 0,046 mm, acero (usado) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, hormigón 0,3–3 mm. El HDPE es común en tuberías de presión de pequeñas instalaciones micro-hidroeléctricas.';
$ec_lang['mhp_notes_6_term']='Rendimiento';
$ec_lang['mhp_notes_6_def']='El rendimiento típico de la instalación η varía de 0,70 a 0,85 para turbinas Pelton y turbinas de flujo cruzado comunes en micro-hidráulica. Use 0,75 como estimación inicial conservadora.';
$ec_lang['mhp_notes_7_term']='Energía Anual';
$ec_lang['mhp_notes_7_def']='La energía anual supone operación continua a caudal completo (8760 horas/año). La producción real será menor debido a la variación estacional del caudal, paradas por mantenimiento y factor de carga.';

// About
$ec_lang['about_main_menu']='Acerca de';
$ec_lang['install_main_menu']='Instalar';
$ec_lang['install_main_title']='Instalar EngCalcs';
$ec_lang['install_main_desc']='Agregar al dispositivo para uso sin conexión';
$ec_lang['contact_main_menu']='Contacto';
$ec_lang['about_main_title']='Acerca de las calculadoras de ingeniería HawsEDC';
$ec_lang['about_main_desc']='Misión, código abierto y contribuciones';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Tasa de aplicación de riego por goteo/aspersión';
$ec_lang['ds_main_title']='Calculadora gratuita en línea de tasa de aplicación de riego por goteo/aspersión';
$ec_lang['ds_main_desc']='Riego por Goteo & Aspersión — Tasa de Aplicación y Uniformidad';
$ec_lang['ds_q_avg']='Caudal promedio del emisor, q';
$ec_lang['ds_q_min']='Caudal mínimo del emisor, q<sub>min</sub>';
$ec_lang['ds_se']='Espaciado emisores, S<sub>e</sub>';
$ec_lang['ds_sl']='Espaciado laterales, S<sub>l</sub>';
$ec_lang['ds_n_e']='Emisores por lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Laterales por sector, n<sub>l</sub>';
$ec_lang['ds_d']='Lámina de riego objetivo, d';
$ec_lang['ds_a_e']='Área por emisor, A<sub>e</sub>';
$ec_lang['ds_pr']='Tasa aplicación, PR';
$ec_lang['ds_du']='Uniformidad de distribución, DU';
$ec_lang['ds_du_check']='Verificación de calidad DU';
$ec_lang['ds_q_lat']='Caudal por lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Caudal del sector, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Tiempo riego (hours)';
$ec_lang['ds_du_excellent']='Excelente — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='Bueno — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='Aceptable — DU ≥ 70%';
$ec_lang['ds_du_poor']='Deficiente — DU < 70% — revisar el diseño ⚠';
$ec_lang['ds_notes_1_term']='Tasa de Aplicación';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, donde A<sub>e</sub> = S<sub>e</sub> × S<sub>l</sub> es el área servida por cada emisor. Una tasa de aplicación menor da más tiempo para la infiltración — importante en suelos pesados o campos con pendiente.';
$ec_lang['ds_notes_2_term']='Uniformidad de Distribución (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. Un DU de 1,0 (100%) significa que todos los emisores emiten igual. Valores por debajo de 0,80 desperdician agua en zonas bien regadas dejando puntos más secos. La uniformidad disminuye con variaciones de presión excesivas a lo largo de la lateral, desgaste de emisores o atasco parcial.';
$ec_lang['ds_notes_3_term']='Tiempo de Riego';
$ec_lang['ds_notes_3_def']='Tiempo de riego = lámina objetivo ÷ tasa de aplicación. En suelos con pendiente o compactados, divida el tiempo de riego en dos o tres ciclos más cortos con períodos de descanso entre ellos para evitar escorrentía superficial.';

// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Pérdida por Infiltración en Canales';
$ec_lang['cs_main_title']='Calculadora gratuita en línea de pérdida por infiltración y eficiencia de conducción en canales';
$ec_lang['cs_main_desc']='Pérdida por Infiltración & Eficiencia de Conducción — Método Entrada-Salida';
$ec_lang['cs_Q_in']='Entrada, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Salida, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='Tasa de pérdida por infiltración, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verificación de medición';
$ec_lang['cs_pct_loss']='Fracción perdida';
$ec_lang['cs_Ec']='Eficiencia de conducción, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Clasificación de eficiencia';
$ec_lang['cs_Vol_day']='Volumen perdido diario';
$ec_lang['cs_Vol_year']='Volumen perdido anual';
$ec_lang['cs_L']='Longitud del tramo, L';
$ec_lang['cs_wp']='Perímetro mojado, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='Pérdida por longitud, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valor agua';
$ec_lang['cs_lining_cost']='Costo revestimiento';
$ec_lang['cs_Ec_target']='Objetivo Ec, E<sub>c,target</sub> <span title="Conveyance efficiency goal after lining; fraction 0–1" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_lining_area']='Área revestimiento, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valor anual perdido';
$ec_lang['cs_annual_value_recovered']='Valor anual recuperado';
$ec_lang['cs_lining_total_cost']='Costo total revestimiento';
$ec_lang['cs_payback_years']='Período recuperación <span title="Simple payback = total lining cost ÷ annual value recovered" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — infiltración detectada ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — sin pérdida medible';
$ec_lang['cs_loss_negative']='Advertencia: Qout > Qin — verifique las mediciones ⚠';
$ec_lang['cs_Ec_good']='Buena — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Regular — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Deficiente — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Método';
$ec_lang['cs_notes_1_def']='El método entrada-salida estima la infiltración midiendo el gasto al inicio y al final de un tramo del canal: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. La eficiencia de conducción E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. El volumen anual asume operación continua a plena carga; la pérdida real es menor en canales de funcionamiento estacional o parcial.';
$ec_lang['cs_notes_2_term']='Clasificaciones de Eficiencia';
$ec_lang['cs_notes_2_def']='Canales de tierra sin revestir típicos: E<sub>c</sub> = 60–80%. Canales de tierra bien mantenidos: 75–85%. Canales revestidos de concreto: 90–98%. Las pérdidas por infiltración superiores al 30% del gasto de entrada suelen justificar una inversión en revestimiento. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Recuperación por Revestimiento';
$ec_lang['cs_notes_3_def']='Ingrese el valor del agua y el costo del revestimiento en cualquier moneda consistente. Área de revestimiento = longitud del tramo × perímetro mojado — el perímetro mojado de la sección transversal del canal a la profundidad de flujo medida (ancho de plantilla más ambas orillas mojadas). El valor anual recuperado supone que el canal revestido alcanza la E<sub>c</sub> objetivo de forma continua. El período de recuperación real será mayor en canales de uso estacional o si el revestimiento no alcanza la eficiencia objetivo.';
$ec_lang['cs_notes_4_term']='Referencia';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3.ª ed. (2001). FAO Irrigation and Drainage Paper 57 (1999).';

$ec_lang['irr_intro_html']='<p>Los vertederos y orificios son las herramientas de campo estándar para medir el caudal en los sistemas de riego. Seleccione la calculadora que corresponde a su estructura:</p>';
$ec_lang['irr_card_weir_uniform_head']='Vertedero — Cresta Ancha (Ancho Uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Mida el caudal sobre una cresta de presa de desvío, estructura de control o tablero vertedor. Ingrese la longitud del vertedero y la profundidad del agua sobre la cresta.';
$ec_lang['irr_card_weir_irregular_head']='Vertedero — Perfil Irregular';
$ec_lang['irr_card_weir_irregular_desc']='Úselo cuando la cresta del vertedero no tenga una elevación uniforme única: aliviaderos naturales, estructuras de caída con ancho variable o estructuras de control de múltiples secciones.';
$ec_lang['irr_card_orifice_head']='Orificio — Compuerta de Cabecera o Toma de Tubería';
$ec_lang['irr_card_orifice_desc']='Mida el caudal a través de una compuerta deslizante, toma de tubería o abertura de alcantarilla. Maneja automáticamente tanto la descarga libre como las condiciones sumergidas (aguas abajo).';
$ec_lang['irr_card_canal_head']='Diseño y Análisis de Canal';
$ec_lang['irr_card_canal_desc']='Diseñe o verifique un canal de riego usando la fórmula de Manning. Use la calculadora Trapezoidal para canales nuevos; la calculadora Irregular para secciones naturales o construidas existentes.';
$ec_lang['irr_card_drip_head']='Diseño de Goteo & Aspersión';
$ec_lang['irr_card_drip_desc']='Calcule la tasa de aplicación, uniformidad de distribución, caudal lateral, caudal de zona y tiempo de funcionamiento para un sistema de riego por goteo o aspersión. Ingrese el caudal del emisor, el espaciado y la profundidad objetivo.';
$ec_lang['irr_card_seepage_head']='Infiltración en Canales & Eficiencia de Conducción';
$ec_lang['irr_card_seepage_desc']='Estime la pérdida por infiltración en un tramo de canal usando mediciones de gasto de entrada y salida. Calcule la eficiencia de conducción y la pérdida anual de agua para ayudar a priorizar inversiones en revestimiento.';
$ec_lang['irr_quickref_html']='<h3>Referencia Rápida</h3><dl><dt>Presa de desvío o estructura de control</dt><dd>Mida la profundidad del agua sobre la cresta del vertedero. Use <a href="Weir-Flow-Simple.php">Vertedero Simple</a> para una cresta uniforme, o <a href="Weir-Flow-Irregular.php">Vertedero Irregular</a> para una cresta perfilada o escalonada.</dd><dt>Compuerta de cabecera o toma de tubería</dt><dd>Mida la elevación del agua aguas arriba y aguas abajo (o la cota de solera si descarga libremente). Use <a href="Orifice.php">Caudal por Orificio</a>. Para una tubería circular, D = diámetro de la tubería; para una compuerta rectangular, ingrese el ancho W y la altura D.</dd><dt>Tiempo de vaciado de embalse o estanque</dt><dd>Use <a href="Orifice-Drain-Time.php">Tiempo de Vaciado por Orificio</a> para estimar cuánto tiempo tarda en bajar el nivel de un estanque o embalse a través de un orificio en el fondo — útil para la planificación del almacenamiento de riego.</dd><dt>Estándares de campo</dt><dd>Las ecuaciones de caudal por vertedero y orificio usadas aquí corresponden a los procedimientos del <em>Manual de Medición de Agua</em> (3.ª ed.) del USBR, comúnmente requeridos por administradores de agua y distritos de riego.</dd></dl>';
$ec_lang['about_body_html']='<h3>Misión</h3><p>Las Calculadoras de Ingeniería HawsEDC existen para servir a ingenieros y trabajadores de campo en todo el mundo — especialmente a quienes trabajan en regiones con escasez de agua, recursos limitados o poco atendidas. Estas herramientas forman parte de una misión humanitaria más amplia: decirle a cada ser humano de la manera más práctica y efectiva posible que es amado y apreciado para siempre, que no tiene nada que temer y que no va a arruinarlo todo.</p><p>Las calculadoras son el vehículo. El destino es un mundo libre de sufrimiento.</p><h3>Licencia de Código Abierto</h3><p>Todo el código se publica bajo la <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licencia Pública General GNU v3.0 o posterior</a> — libre como en libertad. Puede usar, estudiar, modificar y redistribuir el código bajo los mismos términos.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Código Fuente</h3><p>El código fuente completo está disponible públicamente en Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Puede explorar el código, registrar problemas o bifurcar el repositorio allí.</p><h3>Contribuir</h3><p>Se aceptan solicitudes de extracción. Formas de contribuir:</p><ul><li><strong>Traducciones</strong> — mejore o agregue un idioma. Abra una solicitud de extracción con cambios en el archivo <code>lib/lang.ec.??.php</code> correspondiente.</li><li><strong>Informes de errores</strong> — use el formulario de comentarios en cualquier página de calculadora, o registre un problema en Bitbucket.</li><li><strong>Nuevas calculadoras</strong> — las ideas para herramientas de ingeniería hidráulica que sirvan a trabajadores de campo y profesionales del riego son especialmente bienvenidas. Consulte la guía del desarrollador <code>CLAUDE.md</code> en el repositorio.</li><li><strong>Alojamiento</strong> — si puede alojar estas calculadoras en una región con conectividad limitada, comuníquese con nosotros.</li></ul><h3>Uso sin conexión</h3><p>Estas calculadoras funcionan como una Aplicación Web Progresiva (PWA). Visite cualquier página de calculadora con conexión a internet, y su navegador almacenará automáticamente todas las calculadoras en caché. Después de eso, todas las calculadoras funcionan sin conexión — no se requiere internet.</p><p>En Android o iOS, use la opción "Agregar a pantalla de inicio" de su navegador para instalar EngCalcs como una aplicación en su dispositivo. En el escritorio, busque el ícono de instalación en la barra de direcciones de su navegador.</p><p>También puede guardar cualquier calculadora individual usando el menú "Guardar como…" de su navegador para uso sin conexión puntual.</p><h3>Contacto</h3><p>Tom Haws — ingeniero hidráulico y autor de estas calculadoras.<br />Use el formulario de comentarios en cualquier página de calculadora, o acceda al código fuente en <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Diseño de Bajante de Rocado (Robinson)';
$ec_lang['rc_main_title']='Calculadora Gratuita de Diseño de Bajante de Rocado — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionamiento de Escollera para Bajante de Rocado — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Pendiente del fondo del canal, S<sub>0</sub>';
$ec_lang['rc_qt']='Gasto unitario total, q<sub>t</sub> <span title="Caudal por unidad de ancho en la entrada del canal. Para un canal de ancho de plantilla B con gasto total Q, usar q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Porosidad de la escollera, n<sub>p</sub>';
$ec_lang['rc_sg']='Gravedad específica del material, sg <span title="Granito triturado o basalto típico ≈ 2,65. Rango válido Robinson: 2,54 a 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Gradación SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Desviación estándar de gradación. Roca uniforme ≈ 1,25. Rango válido Robinson: 1,15 a 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Tirante normal en canal de entrada, y<sub>n</sub> <span title="El remanso (Hp > yn) es favorable — reduce erosión aguas arriba. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Tamaño mediano requerido de roca, D<sub>50</sub> <span title="Ec. 1 (S0 < 0,10) o Ec. 2 (0,10–0,40). Válido: D50 15–278 mm, S0 0,02–0,40. Fuera del rango: extrapolado." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Ecuación aplicada';
$ec_lang['rc_sg_check']='Verificación de gravedad específica';
$ec_lang['rc_SD_check']='Verificación de gradación SD';
$ec_lang['rc_sg_ok']   ='sg en rango válido (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Advertencia: sg < 2,54 — por debajo del rango Robinson';
$ec_lang['rc_sg_high'] ='Advertencia: sg > 2,82 — por encima del rango Robinson';
$ec_lang['rc_SD_ok']   ='SD en rango válido (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Advertencia: SD < 1,15 — por debajo del rango Robinson';
$ec_lang['rc_SD_high'] ='Advertencia: SD > 1,47 — por encima del rango Robinson';
$ec_lang['rc_layer']='Espesor de la capa de roca (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Radio de curva en cresta superior (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Longitud de arco en cresta superior';
$ec_lang['rc_apron_length']='Longitud del colchón de salida (15 × D<sub>50</sub>) <span title="Requerido para el soporte estructural de la roca del canal. "El tirante aguas abajo mínimo que resulta del tramo de salida y la resistencia del canal aguas abajo es suficiente para garantizar la estabilidad de la escollera en el tramo de salida." (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Rugosidad de Manning en el canal, n';
$ec_lang['rc_Vm']='Velocidad a través del manto de roca, V<sub>m</sub> <span title="Fracción de qt que fluye por los poros de la roca. El resto qs fluye por la superficie. np por defecto = 0,45 para roca triturada angular." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Gasto unitario a través del manto, q<sub>m</sub>';
$ec_lang['rc_qs']='Gasto unitario superficial, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Tirante sobre la superficie de escollera, d';
$ec_lang['rc_Hp']='Carga en vertedor de entrada, H<sub>p</sub> <span title="El remanso (Hp > yn) es favorable — reduce erosión aguas arriba. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Verificación de remanso en entrada';
$ec_lang['rc_pond_ok']  ='Hp > yn — remanso aguas arriba ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — sin remanso — verificar erosión en entrada';
$ec_lang['rc_eq1']='Ec. 1 (S0 < 0,10) — pendiente suave';
$ec_lang['rc_eq2']='Ec. 2 (0,10 ≤ S0 ≤ 0,40) — pendiente pronunciada';
$ec_lang['rc_eq_warn_low']='Advertencia: S0 < 0,02 — por debajo del rango de validación Robinson';
$ec_lang['rc_eq_warn_high']='Advertencia: S0 > 0,40 — por encima del rango de validación Robinson';
$ec_lang['rc_notes_1_term']='Ecuaciones de dimensionamiento de roca';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) desarrollaron dos ecuaciones empíricas para el tamaño mediano de escollera D<sub>50</sub> en función de la pendiente del canal y el gasto unitario. La ecuación 1 aplica para pendientes suaves (S<sub>0</sub> < 0,10); la ecuación 2 para pendientes pronunciadas (0,10 ≤ S<sub>0</sub> ≤ 0,40). Ambas ecuaciones requieren q<sub>t</sub> en m²/s y devuelven D<sub>50</sub> en mm. El rango validado es 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Gasto unitario';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> es el gasto unitario total en la cresta del canal (gasto total por unidad de ancho). Para un canal de ancho de plantilla B con gasto total Q, q<sub>t</sub> ≈ Q / B, o se calcula a partir de la condición de tirante crítico en la entrada del canal.';
$ec_lang['rc_notes_3_term']='Flujo a través del manto de roca';
$ec_lang['rc_notes_3_def']='Una fracción del gasto total fluye por los poros de la escollera (gasto de manto q<sub>m</sub>); el resto fluye por la superficie de la roca (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). El tirante d se calcula con la ecuación de Manning aplicada al gasto superficial q<sub>s</sub> usando la rugosidad n del canal. La porosidad por defecto n<sub>p</sub> = 0,45 es típica para roca triturada angular.';
$ec_lang['rc_notes_5_term']='Rango válido de tamaño de roca';
$ec_lang['rc_notes_5_def']='Las ecuaciones fueron desarrolladas usando un rango de D<sub>50</sub> de 15 mm a 278 mm. Los resultados fuera de este rango son extrapolados y deben usarse con juicio de ingeniería adicional.';
$ec_lang['rc_notes_6_term']='Cota de superficie del colchón de salida';
$ec_lang['rc_notes_6_def']='La cota de la parte superior de la escollera en el tramo de salida debe estar a la misma cota o por debajo de la plantilla del canal aguas abajo. Si es más alta, la roca de salida será inestable.';
$ec_lang['rc_notes_7_term']='Verificación de remanso en entrada';
$ec_lang['rc_notes_7_def']='Cuando el tirante normal en el canal de entrada es menor que la carga en el vertedor (H<sub>p</sub>) requerida para pasar q<sub>t</sub>, ocurre flujo restringido o remanso aguas arriba del colchón de entrada. Esto es generalmente aceptable — el remanso reduce la velocidad y previene erosión aguas arriba. Para verificar: usar una calculadora de vertedor para encontrar H<sub>p</sub> para el q<sub>t</sub> y ancho de cresta dados, y compararlo con el tirante normal del canal de entrada. Si H<sub>p</sub> supera el tirante normal, ocurrirá remanso.';
$ec_lang['rc_notes_4_term']='Referencia';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., y Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. El USDA ARS también publica una <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">hoja de cálculo Excel</a> basada en el mismo método.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtro';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curva de cresta';
$ec_lang['rc_sketch_outlet_apron']    = 'Zampeado';
$ec_lang['rc_sketch_radius']          = 'radio';
// Manning Trapezoidal Channel velocity check
$ec_lang['mtc_vel_check']='Verificación de velocidad';
$ec_lang['mtc_vel_ok']='Velocidad razonable para supuestos de flujo uniforme.';
$ec_lang['mtc_vel_high']='Velocidad elevada — verificar pérdidas de transición y energía disponible.';
$ec_lang['mtc_vel_low']='Velocidad baja — riesgo de sedimentación.';
$ec_lang['mtc_vel_ok_short']='OK';
$ec_lang['mtc_vel_high_short']='Alto';
$ec_lang['mtc_vel_low_short']='Bajo';
$ec_lang['mtc_note_2_term']='Verificación de velocidad';
$ec_lang['mtc_note_2_def']='La velocidad elevada implica alta energía específica a partir de una caída disponible. Esa energía puede disiparse rápidamente en expansiones, curvas u obstrucciones. Verifique que esto sea razonable para el sitio.';
