<?php

// اردو — All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='کسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/سے';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% بلندی/فاصلہ';
$ec_lang['u_grade']='بلندی/فاصلہ';
$ec_lang['u_in2']='مربع انچ';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='انچ';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='لی/سے';
$ec_lang['u_m2']='می^2';
$ec_lang['u_m3ps']='می^3/سے';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='می پانی';
$ec_lang['u_mld']='Ml/دن';
$ec_lang['u_m']='می';
$ec_lang['u_mm2']='ملی^2';
$ec_lang['u_mmh2o']='ملی پانی';
$ec_lang['u_mm']='ملی';
$ec_lang['u_mps']='می/سے';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='سیکنڈ';
$ec_lang['u_acft']='ایکڑ-فٹ';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='می^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC حسابات';
$ec_lang['menu_main_list']='حسابات کی فہرست';
$ec_lang['menu_main_hydraulics']='ہائیڈرولکس';
$ec_lang['menu_main_language']='زبان';
$ec_lang['template_welcome']='&gt;&gt; اپنے خوف دروازے پر چھوڑ دیں؛ یہاں محبت ہماری زبان ہے۔ آپ سب کچھ برباد نہیں کر رہے۔ <a target="_blank" href="https://hawsedc.com/download.php">مفت HawsEDC AutoCAD اوزار</a> بھی آزمائیں۔ &lt;&lt;';
$ec_lang['template_translation_help']='کیا آپ کے ذہن میں یہاں شامل کرنے کے لیے کوئی شاندار حاسبے کا خیال ہے؟ کیا آپ ترجمے بہتر کرنے، پروگرامنگ، یا ان حاسبات کی میزبانی میں مدد کر سکتے ہیں؟  ';
$ec_lang['template_feedback']='براہ کرم اپنی قیمتی رائے یا تعریف شیئر کریں۔ کیا اس مفت حاسبے نے ہر لحاظ سے آپ کی توقعات سے بڑھ کر کام کیا؟';
$ec_lang['template_printable_title']='طباعت کے قابل عنوان';
$ec_lang['template_printable_subtitle']='طباعت کے قابل ذیلی عنوان';
$ec_lang['index_title']='مفت آنلائن انجینئرنگ حاسبات';
$ec_lang['calc_set_units']='اکائیاں مقرر کریں:';
$ec_lang['points_data_help']='(یا ڈیٹا علاقے سے کاپی/پیسٹ کریں)';
$ec_lang['points_data_title']='نقطہ ڈیٹا<br />(کاما یا ٹیب سے علیحدہ)';
$ec_lang['points_data_copy']='کاپی';
$ec_lang['points_data_paste']='پیسٹ';
$ec_lang['calc_inputs']='ان پٹ';
$ec_lang['calc_results']='نتائج';
$ec_lang['view_hide_line']='[یہ سطر چھپائیں]';
$ec_lang['view_printable']='طباعت کے قابل ورژن (بحال کرنے کے لیے دوبارہ لوڈ کریں)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='ڈارسی-وائسباخ پائپ دباؤ نقصان';
$ec_lang['dw_main_title']='مفت آنلائن ڈارسی-وائسباخ پائپ دباؤ نقصان حاسبہ';
$ec_lang['dw_main_desc']='دیے گئے قطر، کھردرا پن اور بہاؤ پر ڈارسی-وائسباخ پائپ دباؤ نقصان';
$ec_lang['dw_roughness']='ڈارسی-وائسباخ مطلق کھردرا پن، e';
$ec_lang['dw_kinematic_viscosity']='حرکیاتی چپچپاہٹ، v، می<sup>2</sup>/سے میں (کمرے کے درجہ حرارت پر خالص پانی کے لیے 1E-6)';
$ec_lang['dw_reynolds_number']='رینولڈز عدد، Re';
$ec_lang['dw_flow_regime']='بہاؤ کی نوع';
$ec_lang['dw_regime_laminar']='ورقی';
$ec_lang['dw_regime_transitional']='انتقالی';
$ec_lang['dw_regime_turbulent']='مضطرب';
$ec_lang['dw_friction_factor_method']='رگڑ کے گنجینے کا طریقہ';
$ec_lang['dw_friction_factor']='رگڑ کا گنجینہ، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='ہیزن-ولیمز پائپ دباؤ نقصان';
$ec_lang['hw_main_title']='مفت آنلائن ہیزن-ولیمز پائپ دباؤ نقصان حاسبہ';
$ec_lang['hw_main_desc']='دیے گئے قطر، کھردرا پن اور بہاؤ پر ہیزن-ولیمز پائپ دباؤ نقصان';
$ec_lang['hw_hgl_1']='پست آب HGL';
$ec_lang['hw_hgl_2']='بالا آب HGL';
$ec_lang['hw_roughness']='ہیزن-ولیمز گنجینہ، C';
// Manning Irregular
$ec_lang['mi_menu']='مانینگ نامنظم نالہ';
$ec_lang['mi_main_title']='مفت آنلائن مانینگ نامنظم نالہ حاسبہ';
$ec_lang['mi_main_desc']='نامنظم نالہ مانینگ یکساں بہاؤ حاسبہ';
$ec_lang['mi_waterSurfaceElevation']='آبی سطح کی بلندی';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='عرضی مقطع کے نقاط';
$ec_lang['mi_groupPoint']='نقطہ';
$ec_lang['mi_groupSegment']='حصہ';
$ec_lang['mi_groupRegion']='علاقہ';
$ec_lang['mi_station']='اسٹیشن';
$ec_lang['mi_elevation']='بلندی';
$ec_lang['mi_d50in']='اسٹر<br />درمیانی<br />پتھر<br />حجم';
$ec_lang['mi_n']='n<br />حصے<br />کے لیے';
$ec_lang['mi_is_bank']='R<sub>h</sub>، Q<br />علاقہ<br />حدود<br />(کنارہ)';
$ec_lang['mi_tau']='تہ<br />قینچی<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='مرکب<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='نوٹ';
$ec_lang['mi_notes_1_term']='مرکب n';
$ec_lang['mi_notes_1_def']='یہ حاسبہ Chow 1959، صفحہ 136، مساوات 6-17 (6-18 نہیں) استعمال کرتے ہوئے علاقائی مرکب n کی گنتی میں HEC-RAS حوالہ دستی کی پیروی کرتا ہے۔';
$ec_lang['mi_notes_2_term']='پتھر اسٹر';
$ec_lang['mi_notes_2_def']='پتھر اسٹر ڈیزائن کے لیے مانینگ ذوزنقہ نالہ حاسبہ استعمال کریں۔ یہ حاسبہ قدرتی عرضی مقاطع کے لیے زیادہ موزوں ہے۔';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='مانینگ پائپ بہاؤ';
$ec_lang['mpf_main_title']='مفت آنلائن مانینگ پائپ بہاؤ حاسبہ';
$ec_lang['mpf_main_desc']='دیے گئے ڈھلان اور گہرائی پر مانینگ فارمولا یکساں پائپ بہاؤ';
$ec_lang['mpf_spreadheet_notice']='اس حاسبے کا اسپریڈشیٹ ورژن دیکھیں';
$ec_lang['mpf_pipe_diameter']='پائپ قطر، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='مانینگ کھردرا پن، n';
$ec_lang['mpf_friction_slope']='دباؤ ڈھلان (ممکنہ طور پر <a target="_blank" href="../pressureslope.php">؟</a> پائپ ڈھلان کے برابر)، S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='نسبی بہاؤ گہرائی، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(نوٹ دیکھیں)';
$ec_lang['mpf_flow']='بہاؤ، Q';
$ec_lang['mpf_velocity']='رفتار، v';
$ec_lang['mpf_velocity_head']='رفتار سر، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='بہاؤ رقبہ، a';
$ec_lang['mpf_pipe_area']='پائپ رقبہ، a0';
$ec_lang['mpf_area_ratio']='نسبی رقبہ، a/a0';
$ec_lang['mpf_wetted_perimeter']='تر محیط، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='آبی نصف قطر، R<sub>h</sub>';
$ec_lang['mpf_top_width']='اوپری چوڑائی، T';
$ec_lang['mpf_froude_number']='فرود عدد، F';
$ec_lang['mpf_shear_stress']='اوسط قینچی دباؤ (کشش قوت)، tau';
$ec_lang['mpf_full_flow']='مکمل بہاؤ، Q0';
$ec_lang['mpf_full_flow_ratio']='مکمل بہاؤ سے نسبت، Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>یہ ایک <em>لامحدود لمبے</em> پائپ کے اندر بہاؤ اور گہرائی ہے۔</dt><dd>پائپ میں بہاؤ داخل کرانے کے لیے کافی زیادہ بالادست گہرائی درکار ہو سکتی ہے۔ بالادست گہرائی پانے کے لیے رفتار سر کا کم از کم 1.5 گنا جوڑیں یا HY-8 استعمال کرتے ہوئے معیاری پائپنالی سر آب حساب کے لیے <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">میرا 2 منٹ کا ٹیوٹوریل</a> دیکھیں۔</dd>';
$ec_lang['mpf_solve_for_dd0']='دیے گئے Q کے لیے y/d<sub>0</sub> حل کریں';
$ec_lang['mpf_solve_desc']='حاسبہ فارم سے D<sub>0</sub>، n اور S<sub>0</sub> استعمال کرتے ہوئے دیے گئے Q کے لیے کم سے کم y/d<sub>0</sub> تلاش کرتا ہے۔';
$ec_lang['mpf_solve_button']='حل کریں';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='مانینگ پائپ دباؤ نقصان';
$ec_lang['mphl_main_title']='مفت آنلائن مانینگ پائپ دباؤ نقصان حاسبہ';
$ec_lang['mphl_main_desc']='دیے گئے مکمل بہاؤ پر مانینگ فارمولا دباؤ نقصان';
$ec_lang['mphl_pipe_length']='پائپ لمبائی، L';
$ec_lang['mphl_area']='رقبہ، A';
$ec_lang['mphl_total_junction_k']='کل مشترک جنکشن نقصان گنجینہ، k';
$ec_lang['mphl_friction_slope']='رگڑ ڈھلان';
$ec_lang['mphl_friction_loss']='رگڑ نقصان، H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='جنکشن نقصان، H<sub>m</sub>';
$ec_lang['mphl_total_loss']='کل نقصان، H<sub>l</sub>';
$ec_lang['mphl_egl_1']='پست آب EGL';
$ec_lang['mphl_egl_2']='بالا آب EGL';
$ec_lang['mphl_hgl_2']='پائپ میں بالا آب HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>کھلے ان لیٹ (پائپنالی) کے معاملے میں، ان لیٹ کنٹرول کی حالتوں کی جانچ ضروری ہے۔</dt><dd>1. بالادست HGL بالادست معمول گہرائی بہاؤ بلندی (یا پائپ!) سے کم نہیں ہو سکتی۔</dd><dd>2. پائپنالی کا سر آب بالادست HGL کے مقابلے میں بالادست EGL سے بہتر ظاہر ہوتا ہے۔</dd><dd>3. HY-8 استعمال کرتے ہوئے سادہ معیاری پائپنالی سر آب حساب کے لیے <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">میرا 2 منٹ کا ٹیوٹوریل</a> دیکھیں۔</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='مانینگ ذوزنقہ نالہ';
$ec_lang['mtc_main_title']='مفت آنلائن مانینگ فارمولا ذوزنقہ نالہ حاسبہ';
$ec_lang['mtc_main_desc']='دیے گئے ڈھلان اور گہرائی پر مانینگ فارمولا یکساں ذوزنقہ نالہ بہاؤ';
$ec_lang['mtc_bottom_width']='تہ چوڑائی، b';
$ec_lang['mtc_side_slope_1']='جانبی ڈھلان 1 (افقی/عمودی)';
$ec_lang['mtc_side_slope_2']='جانبی ڈھلان 2 (افقی/عمودی)';
$ec_lang['mtc_channel_slope']='نالہ ڈھلان، S';
$ec_lang['mtc_flow_depth']='بہاؤ گہرائی، y';
$ec_lang['mtc_bend_angle']='موڑ کا زاویہ <a target="_blank" href="riprap-bend-angle.png" title="تصویر کے لیے کلک کریں">؟</a> (ریپ ریپ حجم کے لیے)';
$ec_lang['mtc_sgrock']='پتھر کی مخصوص کثافت (2.65)';
$ec_lang['mtc_d50_in']='ڈیزائن پتھر حجم، D50';
$ec_lang['mtc_n_strickler']='Strickler کے مطابق ڈیزائن پتھر حجم کے لیے n';
$ec_lang['mtc_n_blodgett']='Blodgett کے مطابق ڈیزائن پتھر حجم کے لیے n';
$ec_lang['mtc_n_bathurst']='Bathurst کے مطابق ڈیزائن پتھر حجم کے لیے n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett بمقابلہ Bathurst';
$ec_lang['mtc_d50_bottom']='تہ کے لیے ضروری زاویہ دار پتھر حجم، D50 (Isbash اور MC) <a href="javascript:alert(\'Isbash (1936) اور Maricopa County، Arizona، US کے مطابق۔\')">؟</a>';
$ec_lang['mtc_d50_z1']='جانبی ڈھلان 1 کے لیے ضروری زاویہ دار پتھر حجم، D50 (Isbash اور MC) <a href="javascript:alert(\'Isbash (1936) اور Maricopa County، Arizona، US کے مطابق۔\')">؟</a>';
$ec_lang['mtc_d50_z2']='جانبی ڈھلان 2 کے لیے ضروری زاویہ دار پتھر حجم، D50 (Isbash اور MC) <a href="javascript:alert(\'Isbash (1936) اور Maricopa County، Arizona، US کے مطابق۔\')">؟</a>';
$ec_lang['mtc_d50_mra']='ضروری زاویہ دار پتھر حجم، D50 (Maynord، Ruff اور Abt 1989)';
$ec_lang['mtc_d50_searcy']='ضروری زاویہ دار پتھر حجم، D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>خودکار پتھر حجم اور کھردرا پن ڈیزائن تکرار</dt><dd>ایک کھردرا پن ریڈیو بٹن (BB تجویز کردہ) اور ایک ڈیزائن پتھر حجم ریڈیو بٹن (Isbash تجویز کردہ) منتخب کریں۔ مساوی پتھر حجم کے ساتھ اپنا مطلوبہ بہاؤ حاصل کرنے کے لیے گہرائی اور پتھر حجم حفاظت عامل کو ایڈجسٹ کریں۔ ہر بار جب آپ کوئی ان پٹ قدر تبدیل کرتے ہیں، درج ذیل تکرار چکر ہوتا ہے: 1. ڈیزائن پتھر حجم سے کھردرا پن کا حساب کیا جاتا ہے۔ 2. درخواست کردہ کھردرا پن حساب ان پٹ کھردرا پن میں کاپی کیا جاتا ہے۔ 3. نالہ بہاؤ اور ضروری پتھر حجم کا حساب کیا جاتا ہے۔ 4. ڈیزائن پتھر حجم کو ایڈجسٹ کیا جاتا ہے۔ 5. ڈیزائن پتھر حجم میں غلطی بہت چھوٹی ہونے تک دہرائیں۔</dd><dt>بنیادی حاسبہ (تکرار کے بغیر)</dt><dd>اپنی مطلوبہ کھردرا پن قدر درج کریں۔ ڈیزائن پتھر حجم ان پٹ علاقہ نظرانداز کریں۔</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='رابنسن راک چیوٹ';
$ec_lang['rrc_main_desc']='رابنسن راک چیوٹ ڈیزائن اسپریڈشیٹ';
// Weir Flow Simple
$ec_lang['ws_main_menu']='سادہ ویر بہاؤ';
$ec_lang['ws_main_title']='مفت آنلائن سادہ چوڑی-شیخر ویر بہاؤ حاسبہ';
$ec_lang['ws_main_desc']='سادہ چوڑی-شیخر ویر بہاؤ حاسبہ';
$ec_lang['ws_weirLength']='ویر لمبائی، l';
$ec_lang['ws_headWaterHeight']='بالا آب بلندی، h';
$ec_lang['ws_weirCoefficient']='ویر گنجینہ، Cw';
$ec_lang['ws_notes_heading']='نوٹ';
$ec_lang['ws_notes_we_term']='ویر مساوات';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='نامنظم ویر بہاؤ';
$ec_lang['wi_main_title']='مفت آنلائن کھنڈی، متغیر گہرائی، نامنظم ویر بہاؤ حاسبہ';
$ec_lang['wi_main_desc']='نامنظم ویر بہاؤ حاسبہ';
$ec_lang['wi_headWaterelevation']='بالا آب بلندی';
$ec_lang['wi_weirPoints']='ویر نقاط';
$ec_lang['wi_station']='اسٹیشن<br />(فاصلہ)';
$ec_lang['wi_elevation']='بلندی';
$ec_lang['wi_pondingHeight']='تالاب بلندی';
$ec_lang['wi_incrementalFlow']='اضافی بہاؤ';
$ec_lang['wi_cumulativeFlow']='مجموعی بہاؤ';
$ec_lang['wi_save_and_calculate']='محفوظ کریں اور حساب کریں';
$ec_lang['wi_notes_we_term']='ویر مساوات';
$ec_lang['wi_notes_we_def']='q = اگر (لمبائی = 0) تو 0 ورنہ اگر (ڈھلان=0) تو cw*لمبائی*d<sub>0</sub><sup>1.5</sup> ورنہ cw/(2.5*ڈھلان) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) جہاں d<sub>1</sub> اور d<sub>0</sub> ہمیشہ صفر یا مثبت ہوتے ہیں';
// Orifice Flow
$ec_lang['or_main_menu']='سوراخ بہاؤ';
$ec_lang['or_main_title']='مفت آنلائن سوراخ بہاؤ حاسبہ';
$ec_lang['or_main_desc']='سوراخ بہاؤ — آزاد یا ڈوبا ہوا';
$ec_lang['or_shape']='کھلنے کی شکل';
$ec_lang['or_shape_circular']='گول';
$ec_lang['or_shape_rectangular']='مستطیل';
$ec_lang['or_diameter']='قطر (گول) یا اونچائی (مستطیل)، D';
$ec_lang['or_width']='چوڑائی، W (صرف مستطیل)';
$ec_lang['or_invert']='کھلنے کی انورٹ بلندی (کھلنے کا تہ)';
$ec_lang['or_hwe']='بالا آب بلندی';
$ec_lang['or_twe']='پست آب بلندی';
$ec_lang['or_cd']='اخراج گنجینہ، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='مرکز ثقل بلندی';
$ec_lang['or_head']='مؤثر سر، h';
$ec_lang['or_area']='کھلنے کا رقبہ، A';
$ec_lang['or_flow']='بہاؤ، Q';
$ec_lang['or_velocity']='کھلنے پر رفتار، v';
$ec_lang['or_regime']='سوراخ نوع جانچ';
$ec_lang['or_regime_valid']='آزاد اخراج — سوراخ نوع درست ✓';
$ec_lang['or_regime_submerged']='ڈوبا ہوا سوراخ (TWE انورٹ کے اوپر) — درست ✓';
$ec_lang['or_regime_warn']='انتباہ: بالا آب تاج سے نیچے — سوراخ نوع نہیں';
$ec_lang['or_regime_twe_above_hwe']='انتباہ: پست آب (TWE) بالا آب (HWE) سے اوپر — ان پٹ جانچیں';
$ec_lang['or_notes_1_term']='سوراخ مساوات';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh)۔ آزاد اخراج: h = HWE &minus; مرکز ثقل۔ ڈوبا ہوا بہاؤ (انورٹ کے اوپر TWE): h = HWE &minus; TWE۔';
$ec_lang['or_notes_2_term']='سوراخ نوع';
$ec_lang['or_notes_2_def']='سوراخ بہاؤ مساوات اس وقت لاگو ہوتی ہیں جب بالا آب سطح کھلنے کے تاج سے اوپر ہو۔ جب بالا آب تاج سے نیچے ہو، تو ویر مساوات استعمال کریں۔';
$ec_lang['or_notes_3_term']='اخراج گنجینہ';
$ec_lang['or_notes_3_def']='تیز کنارے والے سوراخوں کے لیے C<sub>d</sub> تقریباً 0.60&ndash;0.65 تک ہوتا ہے۔ گول یا دوبارہ داخل ہونے والے ان لیٹس مختلف اقدار استعمال کرتے ہیں۔ رہنمائی کے لیے <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> یا HEC-RAS ہائیڈرولک حوالہ دستی دیکھیں۔';
$ec_lang['or_notes_4_term']='ڈوبنا';
$ec_lang['or_notes_4_def']='جب TWE کھلنے کی انورٹ کے اوپر ہو، تو یہ حاسبہ خودکار طور پر h = HWE &minus; TWE استعمال کرتے ہوئے ڈوبا ہوا سوراخ مساوات لاگو کرتا ہے۔ جب TWE انورٹ پر یا اس سے نیچے ہو، تو آزاد اخراج فرض کیا جاتا ہے اور h = HWE &minus; مرکز ثقل۔';
// Orifice Drain Time
$ec_lang['odt_main_menu']='سوراخ نکاسی وقت';
$ec_lang['odt_main_title']='مفت آنلائن سوراخ نکاسی وقت حاسبہ — تالاب، حوض یا ٹینک';
$ec_lang['odt_main_desc']='تالاب یا حوض سوراخ نکاسی وقت &mdash; مخروطی حجم طریقہ';
$ec_lang['odt_h1_elev']='ابتدائی آبی سطح بلندی';
$ec_lang['odt_a1']='ابتدائی تالاب یا حوض رقبہ، A1';
$ec_lang['odt_h2_elev']='آخری آبی سطح بلندی';
$ec_lang['odt_h_orifice']='سوراخ مرکز ثقل بلندی';
$ec_lang['odt_a0']='سوراخ بلندی پر تالاب یا حوض رقبہ، A0';
$ec_lang['odt_a_ending']='آخری تالاب رقبہ، A2 (تخمینی)';
$ec_lang['odt_h2_check']='آخری بلندی جانچ';
$ec_lang['odt_h2_ok']='آخری بلندی سوراخ تاج کے اوپر ✓';
$ec_lang['odt_h2_warn']='انتباہ: آخری بلندی سوراخ تاج پر یا اس سے نیچے (مرکز ثقل + D/2)';
$ec_lang['odt_d']='سوراخ قطر (گول) یا اونچائی (مستطیل)، D';
$ec_lang['odt_w']='سوراخ چوڑائی، W (صرف مستطیل)';
$ec_lang['odt_t_sec']='نکاسی وقت (سیکنڈ)';
$ec_lang['odt_t_min']='نکاسی وقت (منٹ)';
$ec_lang['odt_t_hr']='نکاسی وقت (گھنٹے)';
$ec_lang['odt_t_day']='نکاسی وقت (دن)';
$ec_lang['odt_notes_1_term']='فارمولا';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) سر H سے سوراخ تک نکاسی وقت دیتا ہے۔ نکاسی وقت = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، جہاں H<sub>1</sub> = ابتدائی بلندی &minus; سوراخ بلندی، H<sub>2</sub> = آخری بلندی &minus; سوراخ بلندی۔';
$ec_lang['odt_notes_2_term']='طریقہ';
$ec_lang['odt_notes_2_def']='مخروطی حجم طریقہ تالاب یا حوض کو ابتدائی آبی سطح پر A<sub>1</sub> اور سوراخ مرکز ثقل بلندی پر A<sub>0</sub> کے درمیان ایک مخروطی حصے کے طور پر ماڈل کرتا ہے۔ A<sub>2</sub>، آخری بلندی پر تالاب کا رقبہ، مخروطی حصہ ماڈل استعمال کرتے ہوئے A<sub>1</sub> اور A<sub>0</sub> سے تخمینہ کیا جاتا ہے۔ ابتدائی سے آخری بلندی تک نکاسی وقت H<sub>1</sub> سے سوراخ تک کل نکاسی وقت سے H<sub>2</sub> سے سوراخ تک باقی نکاسی وقت گھٹانے کے برابر ہے۔';
$ec_lang['odt_h1']='ابتدائی سر، H<sub>1</sub> (WSE &minus; مرکز ثقل)';
$ec_lang['odt_q_max']='زیادہ سے زیادہ (ابتدائی) بہاؤ، Q<sub>max</sub>';
$ec_lang['odt_vol']='نکالا گیا حجم';
$ec_lang['odt_sketch_start']='آغاز';
$ec_lang['odt_sketch_end']='اختتام';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='کنارے سے کنارے چوڑائی';
$ec_lang['essc_mcr']='کم سے کم انحناء نصف قطر';
$ec_lang['essc_q']='بہاؤ، Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='آبپاشی بہاؤ پیمائش';
$ec_lang['irr_main_title']='آبپاشی بہاؤ پیمائش کے مفت آن لائن حسابگر';
$ec_lang['irr_main_desc']='آبپاشی بہاؤ پیمائش — ویئر اور اوریفس';
$ec_lang['contact_title']='HawsEDC سے رابطہ';
$ec_lang['contactSendMessage']='Tom Haws کو پیغام بھیجیں';
$ec_lang['contactYourName']='آپ کا نام:';
$ec_lang['contactYourEmail']='آپ کا ای-میل پتہ:';
$ec_lang['contactSubject']='موضوع:';
$ec_lang['contact_message']='پیغام:';
$ec_lang['contactSpamPrefix']='پانچ جمع ایک برابر';
$ec_lang['contactSpamPostfix']='(براہ کرم انگریزی میں لکھیں۔ 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='پیغام بھیجیں';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='مائیکرو-ہائیڈرو بجلی';
$ec_lang['mhp_main_title']='مفت آن لائن مائیکرو-ہائیڈرو بجلی کیلکولیٹر';
$ec_lang['mhp_main_desc']='رن-آف-ریور مائیکرو-ہائیڈرو بجلی پیداوار کیلکولیٹر';
$ec_lang['mhp_flow']='بہاؤ کی شرح، Q';
$ec_lang['mhp_gross_head']='کل سر (بلندی فرق)، H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='پنسٹاک سر نقصانات، h<sub>L</sub>';
$ec_lang['mhp_efficiency']='پلانٹ کارکردگی، &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='خالص سر، H<sub>net</sub>';
$ec_lang['mhp_power']='بجلی پیداوار، P';
$ec_lang['mhp_annual_kwh']='100% صلاحیت پر سالانہ توانائی';
$ec_lang['mhp_notes_1_term']='بجلی کا معادلہ';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>، جہاں &rho; = 1000 kg/m&sup3; (میٹھا پانی) اور g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='خالص سر';
$ec_lang['mhp_notes_2_def']='خالص سر = کل سر &minus; پنسٹاک سر نقصانات۔ ایک عام پہلا تخمینہ h<sub>L</sub> &asymp; H<sub>gross</sub> کا 5% ہے۔ پنسٹاک نقصان کے زیادہ درست تخمینوں کے لیے <a href="Darcy-Weisbach.php">ڈارسی-ویسباخ کیلکولیٹر</a> استعمال کریں۔';
$ec_lang['mhp_notes_3_term']='کارکردگی';
$ec_lang['mhp_notes_3_def']='مائیکرو-ہائیڈرو میں عام پیلٹن اور کراس-فلو ٹربائنوں کے لیے پلانٹ کارکردگی &eta; عموماً 0.70 سے 0.85 تک ہوتی ہے۔ قدامت پسند پہلے تخمینے کے طور پر 0.75 استعمال کریں۔';
$ec_lang['mhp_notes_4_term']='سالانہ توانائی';
$ec_lang['mhp_notes_4_def']='سالانہ توانائی مسلسل پورے بہاؤ کے ساتھ آپریشن (8760 گھنٹے/سال) مانتی ہے۔ موسمی بہاؤ کے اتار چڑھاؤ، دیکھ بھال کی بندش، اور بوجھ عامل کی وجہ سے حقیقی پیداوار کم ہوگی۔';
// Penstock Design
$ec_lang['ps_main_menu']='پینسٹاک ڈیزائن';
$ec_lang['ps_main_title']='مفت آن لائن پینسٹاک ڈیزائن کیلکولیٹر';
$ec_lang['ps_main_desc']='مائیکرو-ہائیڈرو پینسٹاک سائزنگ — سر کا نقصان، طاقت اور رفتار';
$ec_lang['ps_flow']='بہاؤ کی شرح، Q';
$ec_lang['ps_gross_head']='مجموعی سر، H<sub>gross</sub>';
$ec_lang['ps_diameter']='پینسٹاک قطر، D';
$ec_lang['ps_length']='پینسٹاک لمبائی، L';
$ec_lang['ps_roughness']='پائپ کی کھردرت، e';
$ec_lang['ps_km']='ثانوی نقصان گتانک، k<sub>m</sub>';
$ec_lang['ps_nu']='حرکیاتی لزوجت، &nu;، m<sup>2</sup>/s میں (20&deg;C کے قریب پانی کے لیے 1E-6)';
$ec_lang['ps_efficiency']='پلانٹ کارکردگی، &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='بہاؤ کی رفتار، v';
$ec_lang['ps_vel_check']='رفتار کی جانچ';
$ec_lang['ps_f']='رگڑ گتانک، f';
$ec_lang['ps_hf']='رگڑ سر نقصان، h<sub>f</sub>';
$ec_lang['ps_hm']='ثانوی سر نقصان، h<sub>m</sub>';
$ec_lang['ps_hl']='کل پینسٹاک نقصان، h<sub>L</sub>';
$ec_lang['ps_hl_check']='سر نقصان کی جانچ';
$ec_lang['ps_hnet']='خالص سر، H<sub>net</sub>';
$ec_lang['ps_power']='طاقت پیداوار، P';
$ec_lang['ps_annual_kwh']='100% صلاحیت پر سالانہ توانائی';
$ec_lang['ps_vel_ok']='1–3 m/s — ہدف کے اندر ✓';
$ec_lang['ps_vel_low']='1 m/s سے کم — قطر بڑھائیں ⚠';
$ec_lang['ps_vel_high']='3 m/s سے زیادہ — قطر کم کریں ⚠';
$ec_lang['ps_hl_ok']='10% ہدف کے اندر ✓';
$ec_lang['ps_hl_warn']='10% ہدف سے زیادہ — بڑے پائپ پر غور کریں ⚠';
$ec_lang['ps_hl_bad']='20% سے زیادہ — پائپ کی سائزنگ دوبارہ کریں';
$ec_lang['ps_notes_1_term']='سر نقصان';
$ec_lang['ps_notes_1_def']='کل نقصان h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، جہاں h<sub>f</sub> = f(L/D)(v&sup2;/2g) ڈارسی-وائزباخ رگڑ نقصان ہے اور h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g داخلہ، موڑ اور والوز کا احاطہ کرتا ہے۔ خالص سر H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='رفتار';
$ec_lang['ps_notes_2_def']='ہدف 1&ndash;3 m/s۔ 1 m/s سے کم پائپ ضرورت سے بڑا ہے؛ 3 m/s سے زیادہ رگڑ نقصان اور پانی کے ہتھوڑے کا خطرہ بڑھتا ہے۔';
$ec_lang['ps_notes_3_term']='سر نقصان کا ہدف';
$ec_lang['ps_notes_3_def']='مجموعی سر کے 10% سے کم پینسٹاک نقصان عموماً اقتصادی ہے۔ پائپ کی لاگت اور ضائع ہونے والی طاقت کے درمیان زیادہ سے زیادہ توازن اکثر اعلی قیمتی بجلی کے مقامات کے لیے 4&ndash;6% کے قریب ہوتا ہے۔';
$ec_lang['ps_notes_4_term']='ثانوی نقصانات k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='مخصوص اقدار: تیز داخلہ 0.5، ہر 45&deg; موڑ 0.2&ndash;0.3، گیٹ والو (مکمل کھلا) 0.1، بٹرفلائی والو 0.2۔ تمام فٹنگز کا مجموع کل k<sub>m</sub> ہے۔ ڈیفالٹ 1.5 ایک داخلہ اور دو موڑ فرض کرتا ہے۔';
$ec_lang['ps_notes_5_term']='پائپ کی کھردرت e';
$ec_lang['ps_notes_5_def']='مخصوص مطلق کھردرت: اسٹیل (نیا) 0.046&nbsp;ملی میٹر، اسٹیل (پرانا) 0.15&nbsp;ملی میٹر، HDPE 0.003&nbsp;ملی میٹر، PVC/uPVC 0.0015&nbsp;ملی میٹر، کنکریٹ 0.3&ndash;3&nbsp;ملی میٹر۔ HDPE چھوٹے مائیکرو-ہائیڈرو پینسٹاک کے لیے عام ہے۔';

// About
$ec_lang['about_main_menu']='کے بارے میں';
$ec_lang['about_main_title']='HawsEDC انجینئرنگ کیلکولیٹرز کے بارے میں';
$ec_lang['about_main_desc']='مشن، اوپن سورس اور تعاون';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Drip/Sprinkler Application Rate';
$ec_lang['ds_main_title']='Free Online Drip/Sprinkler Irrigation Application Rate Calculator';
$ec_lang['ds_main_desc']='Drip &amp; Sprinkler Irrigation &mdash; Application Rate and Uniformity';
$ec_lang['ds_q_avg']='Average emitter flow rate, q';
$ec_lang['ds_q_min']='Minimum emitter flow rate, q<sub>min</sub>';
$ec_lang['ds_se']='Emitter spacing along lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateral spacing (row spacing), S<sub>l</sub>';
$ec_lang['ds_n_e']='Emitters per lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Laterals per zone, n<sub>l</sub>';
$ec_lang['ds_d']='Target application depth, d';
$ec_lang['ds_a_e']='Area per emitter, A<sub>e</sub>';
$ec_lang['ds_pr']='Application rate (precipitation rate), PR';
$ec_lang['ds_du']='Distribution uniformity, DU';
$ec_lang['ds_du_check']='DU quality check';
$ec_lang['ds_q_lat']='Flow per lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Zone flow, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Runtime for target depth (hours)';
$ec_lang['ds_du_excellent']='Excellent &mdash; DU &ge; 90% ✓';
$ec_lang['ds_du_good']='Good &mdash; DU &ge; 80% ✓';
$ec_lang['ds_du_acceptable']='Acceptable &mdash; DU &ge; 70%';
$ec_lang['ds_du_poor']='Poor &mdash; DU &lt; 70% &mdash; review design ⚠';
$ec_lang['ds_notes_1_term']='Application Rate';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, where A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> is the area served by each emitter. A lower application rate gives more time for infiltration &mdash; important on heavy soils or sloped fields.';
$ec_lang['ds_notes_2_term']='Distribution Uniformity (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. A DU of 1.0 (100%) means all emitters flow identically. Values below 0.80 waste water on well-watered areas while leaving drier spots. Uniformity drops with excessive pressure variation along the lateral, emitter wear, or partial clogging.';
$ec_lang['ds_notes_3_term']='Runtime';
$ec_lang['ds_notes_3_def']='Runtime = target depth &divide; application rate. On sloping or compacted soil, split the runtime into two or three shorter cycles with rest periods between them to avoid surface runoff.';
