<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='كسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/ث';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% ارتفاع/امتداد';
$ec_lang['u_grade']='ارتفاع/امتداد';
$ec_lang['u_in2']='بوصة مربعة';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='بوصة';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='ل/ث';
$ec_lang['u_m2']='م^2';
$ec_lang['u_m3ps']='م^3/ث';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='م ماء';
$ec_lang['u_mld']='ML/يوم';
$ec_lang['u_m']='م';
$ec_lang['u_mm2']='مم^2';
$ec_lang['u_mmh2o']='مم ماء';
$ec_lang['u_mm']='مم';
$ec_lang['u_mps']='م/ث';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_bar']='بار';
$ec_lang['u_kgfcm2']='كجم قوة/سم²';
$ec_lang['u_s']='ث';
$ec_lang['u_lph']='ل/س';
$ec_lang['u_gph']='غال/س';
$ec_lang['u_mmph']='مم/س';
$ec_lang['u_inph']='بوصة/س';
$ec_lang['u_acft']='أكر-قدم';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='م^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/سنة';
$ec_lang['u_mwh_yr']='MWh/سنة';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='م^2/ث';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='حاسبات HawsEDC';
$ec_lang['menu_main_list']='قائمة الحاسبات';
$ec_lang['menu_main_hydraulics']='الهيدروليكا';
$ec_lang['menu_main_language']='اللغة';
$ec_lang['menu_more']='المزيد';
$ec_lang['menu_libre']='برمجيات حرة';
$ec_lang['template_welcome']='اتركوا مخاوفكم عند الباب؛ هنا نتحدث بالمحبة. أنتم لا تدمرون كل شيء. استمتعوا أيضاً بـ<a target="_blank" href="https://hawsedc.com/download.php">أدوات HawsEDC المجانية لـ AutoCAD.</a>';
$ec_lang['template_feedback']='هل يمكنكم اقتراح صياغة أفضل لهذه الصفحة أو أي شيء آخر؟ هل ترغبون في المساعدة أو في تعلّم إنشاء أدوات مثل هذه؟ يرجى التواصل معي.';
$ec_lang['template_printable_title']='عنوان للطباعة';
$ec_lang['template_printable_subtitle']='عنوان فرعي للطباعة';
$ec_lang['index_title']='حاسبات هندسية مجانية عبر الإنترنت';
$ec_lang['index_meta_desc_plain']='حاسبات هندسة هيدروليكية مجانية للأنابيب والقنوات والسدود والري. تعمل في متصفحك، دون اتصال بالإنترنت، وهي متاحة بـ27 لغة.';
$ec_lang['calc_set_units']='تحديد الوحدات:';
$ec_lang['calc_units_us']='US';
$ec_lang['calc_units_si']='SI';
$ec_lang['calc_defaults']='استعادة الافتراضي';
$ec_lang['calc_defaults_confirm']='إعادة تعيين الحاسبة إلى القيم الافتراضية؟';
$ec_lang['points_data_help']='(أو نسخ/لصق باستخدام منطقة البيانات)';
$ec_lang['points_data_title']='بيانات النقاط<br />(مفصولة بفاصلة أو مسافة جدولة)';
$ec_lang['points_data_copy']='نسخ';
$ec_lang['points_data_paste']='لصق';
$ec_lang['calc_inputs']='المدخلات';
$ec_lang['calc_results']='النتائج';
$ec_lang['view_hide_line']='[إخفاء هذا السطر]';
$ec_lang['view_printable']='نسخة قابلة للطباعة (أعد التحميل للاستعادة)';
$ec_lang['ec_name_label']='احفظ هذا الحساب:';
$ec_lang['ec_name_placeholder']='الاسم';
$ec_lang['ec_name_hint']='يحفظ المدخلات في عنوان URL للإشارات المرجعية واسترجاع السجل والمشاركة';
$ec_lang['calc_copy_link']='نسخ الرابط';
$ec_lang['ec_related_calcs']='حاسبات ذات صلة:';
$ec_lang['calc_copy_link_done']='تم النسخ!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='فاقد الضغط في الأنابيب — داركي-وايسباخ';
$ec_lang['dw_main_title']='حاسبة فاقد الضغط في الأنابيب داركي-وايسباخ المجانية عبر الإنترنت';
$ec_lang['dw_main_desc']='فاقد الضغط في الأنابيب بداركي-وايسباخ عند قطر وخشونة وتدفق معلومة';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='ارتفاع الخشونة المطلقة، e، لجدار الأنبوب. قيم نموذجية: الفولاذ (جديد) 0.046 مم، الفولاذ (مستعمل) 0.15 مم، HDPE 0.003 مم، PVC/uPVC 0.0015 مم، الخرسانة 0.3–3 مم.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s للماء النظيف عند 20°C">اللزوجة الحركية، ν <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='اللزوجة الحركية، ν';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s للماء النظيف عند 20°C';
$ec_lang['dw_reynolds_number']='رقم رينولدز، Re';
$ec_lang['dw_flow_regime']='نظام الجريان';
$ec_lang['dw_regime_laminar']='صفحي';
$ec_lang['dw_regime_transitional']='انتقالي';
$ec_lang['dw_regime_turbulent']='مضطرب';
$ec_lang['dw_friction_factor_method']='طريقة معامل الاحتكاك';
$ec_lang['dw_friction_factor']='معامل الاحتكاك، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='فاقد الضغط في الأنابيب — هيزن-وليامز';
$ec_lang['hw_main_title']='حاسبة فاقد الضغط في الأنابيب هيزن-وليامز المجانية عبر الإنترنت';
$ec_lang['hw_main_desc']='فاقد الضغط في الأنابيب بهيزن-وليامز عند قطر وخشونة وتدفق معلومة';
$ec_lang['hw_hgl_1']='خط المتدرج الهيدروليكي المصبّ';
$ec_lang['hw_hgl_2']='خط المتدرج الهيدروليكي المنبع';
$ec_lang['hw_elev_up']='منسوب المنبع';
$ec_lang['hw_pressure_up']='ضغط المنبع';
$ec_lang['hw_elev_down']='منسوب المصب';
$ec_lang['hw_pressure_down']='ضغط المصب';
$ec_lang['hw_pressure_check']='فحص الضغط';
$ec_lang['hw_pressure_ok_short']='ضغط موجب';
$ec_lang['hw_pressure_neg_short']='ضغط سالب';
$ec_lang['hw_pressure_neg']='ضغط المصب أقل من الصفر. ينخفض خط المتدرج الهيدروليكي عن مستوى الأنبوب، لذا لن يجري الأنبوب ممتلئاً، وقد لا تكون هذه النتيجة صالحة.';
$ec_lang['hw_roughness']='معامل هيزن-وليامز، C';
$ec_lang['hw_note_1']='<dl><dt>لا تُمثِّل هذه الحاسبة مسار الأنبوب (البروفايل) بين الطرفين.</dt><dd>تستخدم فقط منسوبَي المنبع والمصب اللذين تُدخلهما. إذا ارتفع سطح الأرض عن أي من الطرفين في نقطة ما بينهما، فإن الضغط عند تلك النقطة المرتفعة يكون أقل من أي ضغط مذكور هنا. أعد تشغيل الحاسبة لطول القطعة من طرف المنبع حتى تلك النقطة المرتفعة للتحقق منها.</dd><dd>حيثما ينخفض خط المتدرج الهيدروليكي عن مستوى الأنبوب، يكون الماء تحت ضغط سالب. يخرج الهواء من المحلول، ويمكن أن ينهار الأنبوب رقيق الجدار، وقد تتسرب مياه جوفية ملوثة عبر الوصلات. حافظ على أن يبقى الخط تحت ضغط موجب في كل مكان، وفكّر في تركيب صمام هواء عند كل نقطة مرتفعة.</dd><dt>ضغط المنبع هو شرط حدّي (Boundary Condition) تُدخله أنت.</dt><dd>اقرأه من مقياس ضغط، أو من منسوب الماء في خزان (ارتفاع الماء فوق الأنبوب)، أو من منحنى المضخة. تُعطي المضخة ضغطاً أقل كلما ارتفع التدفق، لذا استخدم النقطة على المنحنى التي تطابق التدفق المُدخل أعلاه.</dd><dt>اجمع معاملات الفواقد الموضعية (Minor Losses) بنفسك.</dt><dd>اجمع قيم K لكل صمام وانحناء ووصلة تفرع (Tee) وعداد ومدخل على الخط، وأدخل المجموع. اتبع الرابط عند هذا الحقل للحصول على القيم النموذجية. في خط النقل الرئيسي الطويل تكون هذه الفواقد صغيرة مقارنة بفاقد الاحتكاك، لكن في أنابيب المحطة القصيرة قد تشكل معظم الفاقد.</dd></dl>';
// Manning Irregular
$ec_lang['mi_menu']='قناة غير منتظمة المقطع — مانينغ';
$ec_lang['mi_main_title']='الحاسبة المجانية عبر الإنترنت لقناة مانينغ غير المنتظمة المقطع';
$ec_lang['mi_main_desc']='حاسبة الجريان المنتظم بمعادلة مانينغ في قناة غير منتظمة المقطع';
$ec_lang['mi_waterSurfaceElevation']='منسوب سطح الماء';
$ec_lang['mi_q_617']='<span class="ec-help" title="التدفق المركّب Q، باستخدام معامل خشونة مانينغ المركّب n لكل منطقة وفق معادلة تشاو 6-17، بافتراض تساوي السرعات">Q <span class="ec-tip">؟</span></span>';
$ec_lang['mi_xSecPoints']='نقاط المقطع العرضي';
$ec_lang['mi_groupPoint']='نقطة';
$ec_lang['mi_groupSegment']='قطعة';
$ec_lang['mi_groupRegion']='منطقة';
$ec_lang['mi_station']='مسافة';
$ec_lang['mi_elevation']='منسوب';
$ec_lang['mi_d50in']='حجم<br />صخور<br />التبطين<br />الوسيط';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='حد منطقة R<sub>h</sub>، Q (ضفة)';
$ec_lang['mi_tau']='إجهاد القص القاعي τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />مركّب';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='n المركّب';
$ec_lang['mi_notes_1_def']='تتبع هذه الحاسبة الدليل المرجعي لبرنامج HEC-RAS في حساب معامل الخشونة المركّب n للمنطقة، باستخدام تشاو (Chow) 1959، الصفحة 136، المعادلة 6-17 (وليست 6-18).';
$ec_lang['mi_notes_2_term']='تبطين الصخور';
$ec_lang['mi_notes_2_def']='استخدم حاسبة قناة مانينغ شبه المنحرفة لتصميم تبطين الصخور. هذه الحاسبة أنسب للمقاطع الطبيعية.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='جريان في الأنابيب — مانينغ';
$ec_lang['mpf_main_title']='حاسبة جريان الأنابيب بمانينغ المجانية عبر الإنترنت';
$ec_lang['mpf_main_desc']='جريان منتظم في الأنابيب بمعادلة مانينغ عند ميل وعمق معلومَين';
$ec_lang['mpf_spreadheet_notice']='جدول بيانات جريان الأنابيب بمعادلة مانينغ';
$ec_lang['mpf_pipe_diameter']='قطر الأنبوب، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='معامل خشونة مانينغ، n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">ميل الاحتكاك، S<sub>f</sub></a><span class="ec-help" title="يساوي أحياناً ميل الأنبوب. اتبع الرابط للحصول على شرح (باللغة الإنجليزية فقط)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='نسبة عمق الجريان، y/d<sub>0</sub>';
$ec_lang['mpf_flow']='التدفق، Q';
$ec_lang['mpf_flow_tip']='يُحسب التدفق والعمق بافتراض أنبوب لانهائي الطول. للحصول على هذا التدفق داخل الأنبوب فعلياً، قد يلزم عمق مياه أعلى عند المدخل. راجع الملاحظات أدناه للتفاصيل ومقطع فيديو تعليمي.';
$ec_lang['mpf_velocity']='السرعة، v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="طاقة حركية معبَّر عنها كارتفاع لعمود الماء، v²/2g">الرأس الحركي، h<sub>v</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['mpf_flow_area']='مساحة الجريان، A';
$ec_lang['mpf_pipe_area']='مساحة الأنبوب، A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='المساحة النسبية، A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='المحيط المبلل، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='نصف القطر الهيدروليكي، R<sub>h</sub>';
$ec_lang['mpf_top_width']='العرض العلوي، T';
$ec_lang['mpf_froude_number']='رقم فرود، Fr';
$ec_lang['mpf_shear_stress']='متوسط إجهاد القص، τ';
$ec_lang['mpf_full_flow']='الجريان الكامل، Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='النسبة إلى الجريان الكامل، Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>هذا هو الجريان والعمق داخل أنبوب <em>لانهائي الطول</em>.</dt><dd>قد يتطلب إدخال الجريان إلى الأنبوب منسوب مياه مرتفعاً بشكل كبير. أضف ما لا يقل عن 1.5 ضعف الرأس الحركي للحصول على منسوب المياه، أو <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">راجع درسي القصير مدته دقيقتان</a> لحسابات منسوب مياه الداخل للعبارات القياسية باستخدام <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>، البرنامج المجاني لتصميم العبّارات من إدارة الطرق السريعة الفيدرالية الأمريكية.</dd>';
$ec_lang['mpf_sewer_ref']='<dl><dt>هل تُصمِّم شبكة صرف صحي؟</dt><dd>راجع <a target="_blank" href="/sewslope.php">جداول الحد الأدنى لانحدار مجاري الصرف الصحي</a> لأنابيب من 4 إلى 96 إنش (100 إلى 2400 مم)، معطاة بوحدات م/م ومم/م والنسبة المئوية، ودراسة <a target="_blank" href="/peakfact.php">معاملات الذروة للتدفقات المنخفضة جداً</a>. كلا المرجعين متاحان باللغة الإنجليزية فقط.</dd></dl>';
$ec_lang['mpf_solver_enter_positive_q']='أدخل قيمة موجبة لـ Q المستهدف.';
$ec_lang['mpf_solver_no_solution']='لا يوجد حل: تتجاوز Q سعة الأنبوب عند y/d0 = 93.8% (Qmax = {qmax} بالوحدات المختارة).';
$ec_lang['mpf_solve_btn']='احسب';
$ec_lang['mpf_solve_for_flow']='للتدفق، Q =';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='فاقد الضغط في الأنابيب — مانينغ';
$ec_lang['mphl_main_title']='حاسبة فاقد الضغط في الأنابيب بمانينغ المجانية عبر الإنترنت';
$ec_lang['mphl_main_desc']='فاقد الضغط بمعادلة مانينغ عند جريان كامل معلوم';
$ec_lang['mphl_pipe_length']='طول الأنبوب، L';
$ec_lang['mphl_area']='المساحة، A';
$ec_lang['mphl_total_junction_k']='معامل الفاقد الموضعي، k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='معامل الفاقد، k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='معامل الفواقد الموضعية، km. تحدث هذه الفواقد عند نقاط التقاء الأنابيب، والمداخل، والمخارج، والانحناءات، والصمامات — ويوصف هذا النوع من الفواقد اصطلاحاً بأنه "ثانوي"، وهو وصف مضلل؛ ففي الخط القصير قد تساوي هذه الفواقد فواقد الاحتكاك أو تتجاوزها. القيم النموذجية لمعامل k: مدخل حاد 0.5، كل انحناء بزاوية 45° 0.2–0.3، صمام بوابة (مفتوح بالكامل) 0.1، صمام فراشة 0.2، المخرج (إلى خزان أو إلى الجو) 1.0. اجمع معاملات جميع التجهيزات للحصول على مجموع km. القيمة الافتراضية 2.0 تفترض مدخلاً واحداً، ومخرجاً واحداً، وانحناءين بزاوية 45°.';
$ec_lang['mphl_friction_slope']='ميل الاحتكاك';
$ec_lang['mphl_friction_loss']='فاقد الاحتكاك، h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='الفاقد الموضعي، h<sub>m</sub>';
$ec_lang['mphl_total_loss']='الفاقد الإجمالي، h<sub>L</sub>';
$ec_lang['mphl_egl_1']='خط الطاقة المصبّ';
$ec_lang['mphl_egl_2']='خط الطاقة المنبع';
$ec_lang['mphl_hgl_egl_tip']='قد لا يكون صالحاً إذا كان الأنبوب مرتفعاً. انظر الملاحظات.';
$ec_lang['mphl_note_1']='<dl><dt>لا تُمثِّل هذه الحاسبة مسار الأنبوب (البروفايل) بين الطرفين.</dt><dd>إذا انخفض خط المتدرج الهيدروليكي عن قمة الأنبوب في أي نقطة، فقد لا يكون هذا الحساب صالحاً.</dd><dt>عند وجود مدخل مفتوح (عبّارة)، يجب التحقق من حالات التحكم عند المدخل.</dt><dd>1. لا يمكن أن يكون خط المتدرج الهيدروليكي المنبع أدنى من ارتفاع الجريان الطبيعي المنبع (ولا أدنى من الأنبوب!).</dd><dd>2. منسوب مياه الداخل للعبارة يُمثَّل بشكل أفضل بخط الطاقة المنبع بدلاً من خط المتدرج الهيدروليكي المنبع.</dd><dd>3. انظر <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">درسي القصير مدته دقيقتان</a> لحسابات منسوب مياه الداخل البسيطة للعبارات القياسية باستخدام <a target="_blank" href="https://www.fhwa.dot.gov/engineering/hydraulics/software/hy8/">HY-8</a>، البرنامج المجاني لتصميم العبّارات من إدارة الطرق السريعة الفيدرالية الأمريكية.</dd><dd>4. تحل هذه الصفحة حالة التحكم عند المصب (المخرج) فقط: أنبوب يجري ممتلئاً بالكامل، حيث تُحدِّد ظروف المصب منسوب المياه. يتطلب تصميم العبّارات تحديد ما إذا كان التحكم يحدث عند المدخل أو عند المخرج، لذا استخدم HY-8 كلما احتمل أن يكون أي منهما هو الحاكم.</dd></dl>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='قناة شبه منحرفة — مانينغ';
$ec_lang['mtc_main_title']='الحاسبة المجانية عبر الإنترنت للقناة شبه المنحرفة بمعادلة مانينغ';
$ec_lang['mtc_main_desc']='الجريان المنتظم بمعادلة مانينغ في قناة شبه منحرفة عند انحدار وعمق معلومين';
$ec_lang['mtc_bottom_width']='عرض القاع، b';
$ec_lang['mtc_side_slope_1']='الميل الجانبي 1، z<sub>1</sub> (أفقي/رأسي)';
$ec_lang['mtc_side_slope_2']='الميل الجانبي 2، z<sub>2</sub> (أفقي/رأسي)';
$ec_lang['mtc_channel_slope']='انحدار القناة، S';
$ec_lang['mtc_flow_depth']='عمق الجريان، y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">زاوية الانحناء، β</a><span class="ec-help" title="لتحديد حجم الصخور. اتبع الرابط لعرض المخطط."><span class="ec-tip">؟</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="الكثافة النسبية إلى الماء. القيمة النموذجية ≈ 2.65 للصخور المكسّرة.">الكثافة النسبية للصخور، sg <span class="ec-tip">؟</span></span>';
$ec_lang['mtc_d50_in']='حجم الصخور التصميمي، D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n لحجم الصخور التصميمي (طريقة Strickler)';
$ec_lang['mtc_n_blodgett']='n لحجم الصخور التصميمي (طريقة Blodgett)';
$ec_lang['mtc_n_bathurst']='n لحجم الصخور التصميمي (طريقة Bathurst)';
$ec_lang['mtc_n_pi']='n لحجم الصخور التصميمي (طريقة Phillips & Ingersoll)';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett مقابل Bathurst';
$ec_lang['mtc_pi_range_check']='فحص نطاق P&I';
$ec_lang['mtc_pi_ok']='D50 ضمن نطاق P&I';
$ec_lang['mtc_pi_ok_tip']='0.28–0.36 قدم (Phillips & Ingersoll، 1998)';
$ec_lang['mtc_pi_out_of_range']='خارج النطاق';
$ec_lang['mtc_pi_tip']='تجاوز نطاق بيانات 0.28–0.36 قدم الذي اشتُقت منه هذه المعادلة — يُعتمد كفحص تقريبي فقط، وليس كأساس للتصميم';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="وفق Isbash (1936) ومقاطعة ماريكوبا (Maricopa County)، أريزونا، الولايات المتحدة.">حجم الصخور الزاوية المطلوب للقاع، D<sub>50</sub> (Isbash وMC) <span class="ec-tip">؟</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="وفق Isbash (1936) ومقاطعة ماريكوبا (Maricopa County)، أريزونا، الولايات المتحدة.">حجم الصخور الزاوية المطلوب للميل الجانبي 1، D<sub>50</sub> (Isbash وMC) <span class="ec-tip">؟</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="وفق Isbash (1936) ومقاطعة ماريكوبا (Maricopa County)، أريزونا، الولايات المتحدة.">حجم الصخور الزاوية المطلوب للميل الجانبي 2، D<sub>50</sub> (Isbash وMC) <span class="ec-tip">؟</span></span>';
$ec_lang['mtc_d50_mra']='حجم الصخور الزاوية المطلوب، D<sub>50</sub> (Maynord وRuff وAbt 1989)';
$ec_lang['mtc_d50_searcy']='حجم الصخور الزاوية المطلوب، D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='السرعة معقولة بالنسبة إلى افتراضات الجريان المنتظم.';
$ec_lang['mtc_vel_low']='السرعة منخفضة؛ خطر الترسّب.';
$ec_lang['mtc_vel_high']='السرعة مرتفعة وقد لا تكون واقعية؛ تحقق من تآكل تبطين القناة، والعمق الإضافي عند الانحناءات، وفقد الطاقة عند التوسعات أو العوائق.';
$ec_lang['mtc_iteration_tip']='اختر خيار خشونة (يُوصى بطريقة Blodgett–Bathurst) وخيار حجم صخور تصميمي (يُوصى بطريقة Isbash) للتكرار التلقائي نحو حجم صخور موحّد يحقق التدفق المستهدف. راجع الملاحظات أدناه للاطلاع على الطريقة الكاملة، أو أدخل قيمة الخشونة الخاصة بك (اتبع الرابط للإرشاد) وتجاهل حجم الصخور لتخطي التكرار.';
$ec_lang['mtc_note_1']='<dl><dt>التكرار التلقائي لتصميم حجم الصخور والخشونة</dt><dd>اختر خيار الخشونة (يُوصى بطريقة Blodgett–Bathurst) وخيار حجم الصخور التصميمي (يُوصى بطريقة Isbash). اضبط العمق ومعامل أمان حجم الصخور للوصول إلى التدفق المستهدف بحجم صخور موحّد. في كل مرة تُغيّر فيها أحد المدخلات، تكرر الحاسبة الخطوات التالية: 1. تُحسب الخشونة من حجم الصخور التصميمي. 2. تُنسخ قيمة الخشونة المحسوبة إلى حقل الخشونة المُدخلة. 3. يُحسب تدفق القناة وحجم الصخور المطلوب. 4. يُعدَّل حجم الصخور التصميمي. 5. تُكرَّر الخطوات حتى يصبح الخطأ في حجم الصخور التصميمي ضئيلاً جداً.</dd><dt>الحاسبة الأساسية (بدون تكرار)</dt><dd>أدخل قيمة الخشونة المطلوبة، وتجاهل منطقة إدخال حجم الصخور التصميمي.</dd></dl>';
$ec_lang['mtc_note_2_term']='فحص السرعة';
$ec_lang['mtc_note_2_def']='السرعة العالية تعني وجود هبوط كبير في المنسوب أدى إلى طاقة نوعية مرتفعة بهذا القدر. يمكن أن تُفقد هذه الطاقة بسرعة عند التوسعات أو الانحناءات أو العوائق. تحقق من أن ذلك معقول لموقع المشروع.';
$ec_lang['mtc_solver_no_solution']='لم يتم العثور على حل للتدفق Q المعطى بهذه المدخلات الخاصة بالقناة.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='جريان العتبة — البسيطة';
$ec_lang['ws_main_title']='حاسبة جريان العتبة عريضة العرف البسيطة المجانية عبر الإنترنت';
$ec_lang['ws_main_desc']='حاسبة جريان العتبة عريضة العرف البسيطة';
$ec_lang['ws_weirLength']='طول العتبة، L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="طاقة لكل وحدة وزن من الماء — ارتفاع لعمود الماء، وليس ضغطاً">الرأس، h <span class="ec-tip">؟</span></span>';
$ec_lang['ws_weirCoefficient']='معامل العتبة، C<sub>w</sub>';
$ec_lang['ws_notes_heading']='ملاحظات';
$ec_lang['ws_notes_we_term']='معادلة العتبة';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='جريان العتبة — غير المنتظمة';
$ec_lang['wi_main_title']='حاسبة جريان العتبة غير المنتظمة، المجزأة ومتغيرة العمق، المجانية عبر الإنترنت';
$ec_lang['wi_main_desc']='حاسبة جريان العتبة غير المنتظمة';
$ec_lang['wi_weirPoints']='نقاط العتبة';
$ec_lang['wi_pondingHeight']='ارتفاع التجميع';
$ec_lang['wi_incrementalFlow']='التدفق التدريجي';
$ec_lang['wi_cumulativeFlow']='التدفق التراكمي';
$ec_lang['wi_save_and_calculate']='حفظ وحساب';
$ec_lang['wi_notes_we_def']='q = إذا (الطول = 0) إذن 0؛ وإلا إذا (الميل=0) إذن cw*length*d<sub>0</sub><sup>1.5</sup>؛ وإلا cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) حيث d<sub>1</sub> وd<sub>0</sub> دائماً موجبتان أو صفر';
// Orifice Flow
$ec_lang['or_main_menu']='جريان الفتحة';
$ec_lang['or_main_title']='حاسبة جريان الفتحة المجانية عبر الإنترنت';
$ec_lang['or_main_desc']='جريان الفتحة — حر أو مغمور';
$ec_lang['or_shape']='شكل الفتحة';
$ec_lang['or_shape_circular']='دائري';
$ec_lang['or_shape_rectangular']='مستطيل';
$ec_lang['or_diameter']='<span class="ec-help" title="القطر للفتحة الدائرية؛ الارتفاع للفتحة المستطيلة">القطر أو الارتفاع، D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="للفتحات المستطيلة فقط">العرض، W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="أسفل الفتحة">منسوب القاع <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='منسوب المياه العلوية';
$ec_lang['or_twe']='منسوب المياه السفلية';
$ec_lang['or_cd']='معامل التصريف، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='منسوب المركز الهندسي';
$ec_lang['or_head']='<span class="ec-help" title="طاقة لكل وحدة وزن من الماء — ارتفاع لعمود الماء، وليس ضغطاً">الرأس الفعّال، h <span class="ec-tip">؟</span></span>';
$ec_lang['or_area']='مساحة الفتحة، A';
$ec_lang['or_regime']='فحص نظام الفتحة';
$ec_lang['or_regime_valid']='تصريف حر';
$ec_lang['or_regime_submerged']='فتحة مغمورة';
$ec_lang['or_regime_submerged_tip']='TWE فوق المركز الهندسي — نظام الفتحة لا يزال صالحاً';
$ec_lang['or_regime_warn']='خارج نظام الفتحة';
$ec_lang['or_regime_warn_tip']='المياه العلوية أدنى من تاج الفتحة';
$ec_lang['or_regime_twe_above_hwe']='تحقق من المدخلات';
$ec_lang['or_regime_twe_above_hwe_tip']='المياه السفلية (TWE) فوق المياه العلوية (HWE)';
$ec_lang['or_notes_1_term']='معادلة الفتحة';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). للتصريف الحر: h = HWE − المركز الهندسي. للجريان المغمور (TWE فوق قاع الفتحة): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='نظام الفتحة';
$ec_lang['or_notes_2_def']='تُطبَّق معادلات جريان الفتحة عندما يكون منسوب المياه العلوية فوق تاج (قمة) الفتحة. عندما تكون المياه العلوية أدنى من التاج، استخدم معادلة عتبة بدلاً من ذلك.';
$ec_lang['or_notes_3_term']='معامل التصريف';
$ec_lang['or_notes_3_def']='يتراوح C<sub>d</sub> من حوالي 0.60 إلى 0.65 للفتحات ذات الحافة الحادة. تستخدم المداخل المستديرة أو المعكوسة قيماً مختلفة. انظر <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venturi-d_590.html">Engineering Toolbox</a> أو دليل مرجعية هيدروليكا HEC-RAS للإرشاد.';
$ec_lang['or_notes_4_term']='الغمر';
$ec_lang['or_notes_4_def']='عندما يكون TWE فوق قاع الفتحة، تُطبّق الحاسبة تلقائياً معادلة الفتحة المغمورة باستخدام h = HWE − TWE. عندما يكون TWE عند قاع الفتحة أو أدنى منه، يُفترض التصريف الحر وh = HWE − المركز الهندسي.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='الطاقة الكهرومائية الصغيرة';
$ec_lang['mhp_main_title']='حاسبة الطاقة الكهرومائية الصغيرة المجانية عبر الإنترنت';
$ec_lang['mhp_main_desc']='حاسبة إنتاج الطاقة الكهرومائية الصغيرة بنظام مجرى النهر';
$ec_lang['mhp_gross_head']='الارتفاع الإجمالي، H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="قطر أنبوب الضغط (أنبوب التغذية)">قطر أنبوب الضغط، D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='الطول، L';
$ec_lang['mhp_efficiency']='كفاءة المحطة، η (0–1)';
$ec_lang['mhp_vel_check']='فحص السرعة';
$ec_lang['mhp_hl_check']='فحص فقد الضغط';
$ec_lang['mhp_hnet']='الارتفاع الصافي، H<sub>net</sub>';
$ec_lang['mhp_power']='القدرة المنتجة، P';
$ec_lang['mhp_annual_kwh']='الطاقة السنوية عند سعة 100%';
$ec_lang['mhp_vel_low']='السرعة منخفضة؛ خطر الترسيب واحتباس الهواء.';
$ec_lang['mhp_vel_high']='السرعة مرتفعة؛ تحقق من فقد الانتقال، والطاقة المتاحة، والمطرقة المائية.';
$ec_lang['mhp_vel_ok_short']='جيد';
$ec_lang['mhp_vel_high_short']='مرتفع';
$ec_lang['mhp_vel_low_short']='منخفض';
$ec_lang['mhp_vel_ok_tip']='السرعة ضمن النطاق الفعّال لتصميم أنبوب الضغط.';
$ec_lang['mhp_hl_ok_tip']='ضمن الحد المستهدف 10% — اقتصادي.';
$ec_lang['mhp_hl_warn_tip']='يتجاوز الحد المستهدف 10%. يُفضَّل استخدام أنبوب أكبر.';
$ec_lang['mhp_hl_bad_tip']='يتجاوز الحد المستهدف 20%. يلزم تغيير حجم الأنبوب.';
$ec_lang['mhp_notes_1_term']='فقد الضغط';
$ec_lang['mhp_notes_1_def']='إجمالي فقد أنبوب الضغط h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، حيث h<sub>f</sub> = f(L/D)(v²/2g) هو فقد الاحتكاك وفق داركي-وايسباخ، وh<sub>m</sub> = k<sub>m</sub>·v²/2g يشمل المدخل والانحناءات والصمامات. الارتفاع الصافي H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='السرعة';
$ec_lang['mhp_notes_2_def']='تحقق من أن السرعة معقولة بالنسبة للانخفاض المتاح وتكلفة الأنبوب. السرعة المنخفضة جداً قد تدل على مبالغة في حجم الأنبوب؛ والسرعة المرتفعة جداً قد تزيد فقد الاحتكاك وخطر المطرقة المائية.';
$ec_lang['mhp_notes_3_term']='هدف فقد الضغط';
$ec_lang['mhp_notes_3_def']='يُعدّ فقد أنبوب الضغط أقل من 10% من الارتفاع الإجمالي اقتصادياً في الغالب. يقع التوازن الأمثل بين تكلفة الأنبوب والطاقة المفقودة عادة عند 4–6% حيث تكون الكهرباء أعلى قيمة.';
$ec_lang['mhp_notes_6_term']='الكفاءة';
$ec_lang['mhp_notes_6_def']='تتراوح كفاءة المحطة النموذجية η من 0.70 إلى 0.85 لتوربينات Pelton والتوربينات العرضية الشائعة في محطات الطاقة المائية الصغيرة. استخدم 0.75 كتقدير أولي متحفظ.';
$ec_lang['mhp_notes_7_term']='الطاقة السنوية';
$ec_lang['mhp_notes_7_def']='تفترض الطاقة السنوية تشغيلاً متواصلاً بالتدفق الكامل (8760 ساعة/سنة). الإنتاج الفعلي سيكون أقل بسبب التباين الموسمي في التدفق وتوقف الصيانة ومعامل الحمل.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='وقت تصريف البركة والخزان';
$ec_lang['odt_main_title']='حاسبة وقت تصريف البركة أو الحوض أو الخزان مجانًا عبر الإنترنت (بفتحة)';
$ec_lang['odt_main_desc']='وقت تصريف البركة أو الحوض أو الخزان — مخرج بفتحة، طريقة الحجم المخروطي';
$ec_lang['odt_h1_elev']='منسوب سطح الماء الابتدائي';
$ec_lang['odt_a1']='المساحة الابتدائية، A<sub>1</sub>';
$ec_lang['odt_h2_elev']='منسوب سطح الماء النهائي';
$ec_lang['odt_a0']='المساحة عند منسوب الفتحة، A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="مُستوفاة من النموذج المخروطي عند المنسوب النهائي">المساحة النهائية، A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='فحص المنسوب النهائي';
$ec_lang['odt_h2_ok']='المنسوب النهائي فوق قمة الفتحة';
$ec_lang['odt_h2_warn']='المنسوب النهائي عند قمة الفتحة أو أدناه';
$ec_lang['odt_h2_warn_tip']='قمة الفتحة = المركز الهندسي + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="القطر (دائري) أو الارتفاع (مستطيل)">فتحة D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="للفتحات المستطيلة فقط">عرض الفتحة، W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='وقت التصريف (ثوانٍ)';
$ec_lang['odt_t_min']='وقت التصريف (دقائق)';
$ec_lang['odt_t_hr']='وقت التصريف (ساعات)';
$ec_lang['odt_t_day']='وقت التصريف (أيام)';
$ec_lang['odt_notes_1_term']='الصيغة';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) يعطي وقت التصريف من الرأس H إلى الفتحة. وقت التصريف = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، حيث H<sub>1</sub> = المنسوب الابتدائي − منسوب الفتحة، H<sub>2</sub> = المنسوب النهائي − منسوب الفتحة.';
$ec_lang['odt_notes_2_term']='الطريقة';
$ec_lang['odt_notes_2_def']='تُنمذج طريقة الحجم المخروطي البركة أو الحوض كمقطع مخروطي بين المساحة الابتدائية A<sub>1</sub> عند منسوب المياه الابتدائي والمساحة A<sub>0</sub> عند منسوب المركز الهندسي للفتحة. يُحسب A<sub>2</sub>، مساحة البركة عند المنسوب النهائي، بالاستيفاء من A<sub>1</sub> وA<sub>0</sub> باستخدام نموذج المقطع المخروطي. وقت التصريف من المنسوب الابتدائي إلى النهائي يساوي إجمالي وقت التصريف من H<sub>1</sub> إلى الفتحة ناقص وقت التصريف المتبقي من H<sub>2</sub> إلى الفتحة.';
$ec_lang['odt_h1']='<span class="ec-help" title="منسوب سطح الماء الابتدائي ناقص منسوب المركز الهندسي للفتحة">الرأس الابتدائي، H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='الحد الأقصى للتدفق، Q<sub>max</sub>';
$ec_lang['odt_vol']='الحجم المُصرَّف';
$ec_lang['odt_sketch_start']='البداية';
$ec_lang['odt_sketch_end']='النهاية';
// Contact us.

// Irrigation
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='تباعد القطارات، S<sub>e</sub>';
$ec_lang['ip_sl']='تباعد الخطوط الجانبية، S<sub>l</sub>';
$ec_lang['ip_n_e']='عدد القطارات في الخط الجانبي، n<sub>e</sub>';
$ec_lang['ip_n_l']='عدد الخطوط الجانبية في المنطقة، n<sub>l</sub>';
$ec_lang['ip_d']='عمق التطبيق المستهدف، d';
$ec_lang['ip_a_e']='المساحة لكل قطارة، A<sub>e</sub>';
$ec_lang['ip_pr']='معدل التطبيق، PR';
$ec_lang['ip_q_lat']='التدفق لكل خط جانبي، Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='تدفق المنطقة، Q<sub>zone</sub>';
$ec_lang['ip_t_run']='وقت التشغيل (ساعات)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='تسرب القنوات';
$ec_lang['cs_main_title']='حاسبة فقد تسرب القنوات وكفاءة النقل المجانية عبر الإنترنت';
$ec_lang['cs_main_desc']='فقد تسرب القناة وكفاءة النقل — طريقة التدفق الوارد والصادر';
$ec_lang['cs_Q_in']='التدفق الوارد، Q<sub>in</sub>';
$ec_lang['cs_Q_out']='التدفق الصادر، Q<sub>out</sub>';
$ec_lang['cs_L']='طول القطاع، L';
$ec_lang['cs_Q_loss']='معدل فقد التسرب، Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='فحص القياس';
$ec_lang['cs_pct_loss']='الكسر المفقود';
$ec_lang['cs_Ec']='كفاءة النقل، E<sub>c</sub>';
$ec_lang['cs_Ec_check']='تقييم الكفاءة';
$ec_lang['cs_Vol_day']='الحجم اليومي المفقود';
$ec_lang['cs_Vol_year']='الحجم السنوي المفقود';
$ec_lang['cs_Q_loss_per_L']='الفقد لكل وحدة طول، Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='قيمة المياه';
$ec_lang['cs_lining_cost']='تكلفة التبطين';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="كفاءة النقل المستهدفة بعد التبطين؛ كسر بين 0 و1">هدف التبطين، E<sub>c,target</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['cs_lining_area']='مساحة التبطين، L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='القيمة السنوية المفقودة';
$ec_lang['cs_annual_value_recovered']='القيمة السنوية المستردة';
$ec_lang['cs_lining_total_cost']='إجمالي تكلفة التبطين';
$ec_lang['cs_payback_years']='<span class="ec-help" title="الاسترداد البسيط = إجمالي تكلفة التبطين ÷ القيمة السنوية المستردة">فترة الاسترداد <span class="ec-tip">؟</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — تسرب مكتشف';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — لا فقد قابل للقياس';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — تحقق من القياسات';
$ec_lang['cs_Ec_good']='جيد — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='مقبول — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='ضعيف — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='يُقدِّر أسلوب التدفق الوارد والصادر التسرب بقياس التدفق عند رأس قطاع القناة وذيله: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. كفاءة النقل E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. يفترض الحجم السنوي تشغيلاً مستمراً بالتدفق الكامل؛ والفقد الفعلي أقل في القنوات الموسمية أو ذات التدفق الجزئي.';
$ec_lang['cs_notes_2_term']='تقييمات الكفاءة';
$ec_lang['cs_notes_2_def']='القنوات الترابية غير المبطنة النموذجية: E<sub>c</sub> = 60–80%. القنوات الترابية جيدة الصيانة: 75–85%. القنوات المبطنة بالخرسانة: 90–98%. غالباً ما يبرر فقد التسرب الذي يتجاوز 30% من التدفق الوارد استثمار التبطين. (USBR، FAO)';
$ec_lang['cs_notes_3_term']='استرداد تكلفة التبطين';
$ec_lang['cs_notes_3_def']='أدخل قيمة المياه وتكلفة التبطين بأي عملة متسقة. مساحة التبطين = طول القطاع × المحيط المبلل — وهو المحيط المبلل لمقطع القناة العرضي عند عمق الجريان المقاس (عرض القاع مضافاً إليه الجانبان المبللان). تفترض القيمة السنوية المستردة أن القناة المبطنة تحقق E<sub>c</sub> المستهدفة باستمرار. سيكون الاسترداد الفعلي أطول للقنوات الموسمية أو إذا لم يبلغ التبطين الكفاءة المستهدفة.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>، الطبعة الثالثة (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='حول';
$ec_lang['install_main_menu']='تثبيت';
$ec_lang['install_main_title']='تثبيت EngCalcs';
$ec_lang['install_main_desc']='أضفه إلى جهازك للاستخدام دون اتصال';
$ec_lang['install_intro']='‏EngCalcs هو تطبيق ويب تقدمي (PWA). بعد تثبيته، تعمل جميع الحاسبات دون اتصال بالإنترنت بشكل كامل — لا حاجة لأي اتصال بالشبكة.';
$ec_lang['install_android_heading']='أندرويد (Chrome)';
$ec_lang['install_android_steps_html']='<li>افتح أي صفحة حاسبة في متصفح Chrome.</li><li>اضغط على زر <strong>⬇ تثبيت</strong> في شريط التنقل العلوي، أو اضغط على قائمة المتصفح (⋮) واختر <strong>إضافة إلى الشاشة الرئيسية</strong>.</li><li>اضغط على <strong>تثبيت</strong> في الرسالة التي تظهر.</li><li>يظهر EngCalcs على شاشتك الرئيسية ويعمل دون اتصال بالإنترنت.</li>';
$ec_lang['install_now_btn']='⬇ تثبيت الآن';
$ec_lang['install_prompt_unavailable']='رسالة التثبيت غير متاحة — استخدم قائمة المتصفح بدلاً من ذلك.';
$ec_lang['install_ios_heading']='آيفون (Safari)';
$ec_lang['install_ios_steps_html']='<li>افتح أي صفحة حاسبة في متصفح Safari.</li><li>اضغط على زر <strong>المشاركة</strong> (المربع الذي يحتوي على سهم يشير لأعلى).</li><li>مرّر لأسفل واضغط على <strong>إضافة إلى الشاشة الرئيسية</strong>.</li><li>اضغط على <strong>إضافة</strong>. يظهر EngCalcs على شاشتك الرئيسية.</li>';
$ec_lang['install_ios_note']='على أجهزة آيفون، يتم التثبيت دائماً عبر قائمة المشاركة — لا توجد رسالة تثبيت تلقائية.';
$ec_lang['install_desktop_heading']='سطح المكتب (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>افتح أي صفحة حاسبة.</li><li>انقر على <strong>أيقونة التثبيت</strong> (⊕ أو أيقونة الحاسوب) في شريط عنوان المتصفح، أو افتح قائمة المتصفح واختر <strong>تثبيت EngCalcs…</strong></li><li>انقر على <strong>تثبيت</strong>. يفتح EngCalcs في نافذة تطبيق مستقلة.</li>';
$ec_lang['install_firefox_heading']='فَيَرفُكس ومتصفحات أخرى';
$ec_lang['install_firefox_body']='لا يدعم Firefox تثبيت تطبيقات الويب التقدمية على سطح المكتب. يمكنك مع ذلك استخدام جميع الحاسبات بشكل طبيعي في المتصفح — بعد زيارتك الأولى، يتم حفظ الصفحات تلقائياً في الذاكرة المؤقتة لاستخدامها دون اتصال بالإنترنت.';
$ec_lang['install_cached_heading']='ما الذي يتم حفظه';
$ec_lang['install_cached_body']='في المرة الأولى التي تثبّت فيها EngCalcs، يتم حفظ جميع صفحات الحاسبات وملفاتها المساعدة (البرمجيات النصية وأنماط التنسيق) تلقائياً على جهازك. بعد ذلك، يعمل كل شيء دون الحاجة لاتصال بالإنترنت. يتم تذكّر اختيارك للغة من آخر زيارة لك وأنت متصل بالإنترنت.';
$ec_lang['contact_main_menu']='تواصل';
$ec_lang['about_main_title']='حول حاسبات HawsEDC الهندسية';
$ec_lang['about_main_desc']='الرسالة، والبرمجيات الحرة، والمساهمة';
$ec_lang['about_body_html']='<h3>الرسالة</h3><p>وُجدت حاسبات HawsEDC الهندسية لخدمة المهندسين والعاملين الميدانيين حول العالم — ولا سيما أولئك الذين يعملون في المناطق الشحيحة المياه أو المحدودة الموارد أو المحرومة. هذه الأدوات جزء من رسالة إنسانية أشمل: إخبار كل إنسان بأكثر الطرق عملية وفاعلية أنه محبوب وعزيز إلى الأبد، وأنه لا يخشى شيئاً، وأنه لن يدمّر كل شيء.</p><p>الحاسبات هي الوسيلة، والهدف عالم خالٍ من المعاناة.</p><h3>ترخيص البرمجيات الحرة ومفتوحة المصدر</h3><p>يُصدَر الكود بالكامل تحت <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">رخصة GNU العامة الشاملة الإصدار 3.0 أو أحدث</a> — حرة كما هي الحرية. يمكنك استخدام الكود ودراسته وتعديله وإعادة توزيعه وفق الشروط ذاتها.</p><p>هذه دعوة، لا سعر. لا توجد نسخة مدفوعة، ولا نسخة مجانية يمكن سحبها لاحقاً، ولا تأخير قبل أن يصبح الكود ملكك. النسخة الكاملة التي تراها اليوم متاحة مجاناً للجميع الآن وإلى الأبد للاستخدام والتعديل.</p><p>حقوق النشر © 2009–2026 Thomas Gail Haws.</p><h3>الكود المصدري</h3><p>الكود المصدري الكامل متاح للعموم على GitHub:</p><p><a target="_blank" href="https://github.com/hawstom/engcalcs">github.com/hawstom/engcalcs</a></p><p>يمكنك تصفح الكود وتسجيل المشكلات أو تفريع المستودع هناك.</p><h3>المساهمة</h3><p>كل مساعدة مرحَّب بها. <a href="contact.php">تواصل مع Tom Haws</a>.</p><ul><li><strong>الترجمة:</strong> اقترح صياغة أفضل. حسِّن لغة أو أضف لغة جديدة.</li><li><strong>تقارير الأخطاء:</strong> استخدم نموذج الملاحظات في أي صفحة حاسبة، أو سجّل مشكلة على GitHub.</li><li><strong>حاسبات جديدة:</strong> أفكار لأدوات هندسة هيدروليكية تخدم العاملين الميدانيين وممارسي الري مرحَّب بها بشكل خاص.</li><li><strong>الاستضافة:</strong> إن كنت تستطيع استضافة نسخة مطابقة من هذه الحاسبات لمنطقة ذات اتصال محدود، يُرجى التواصل معي.</li></ul><h3>الاستخدام دون اتصال</h3><p>تعمل هذه الحاسبات كـ<strong>تطبيق ويب تقدمي (PWA)</strong>. قم بزيارة أي صفحة حاسبة أثناء اتصالك بالإنترنت، وسيقوم متصفحك بتخزين جميع الحاسبات تلقائياً في ذاكرة التخزين المؤقت. بعد ذلك، تعمل جميع الحاسبات دون اتصال — لا حاجة للإنترنت.</p><p>على Android أو iOS، استخدم خيار "إضافة إلى الشاشة الرئيسية" في متصفحك لتثبيت EngCalcs كتطبيق على جهازك. على سطح المكتب، ابحث عن أيقونة التثبيت في شريط عنوان متصفحك.</p><p>يمكنك أيضاً حفظ أي حاسبة منفردة باستخدام قائمة "حفظ باسم…" في متصفحك للاستخدام غير المتصل لمرة واحدة.</p><h3>التواصل</h3><p>Tom Haws، مهندس هيدروليكي ومؤسس هذه الحاسبات.<br />استخدم نموذج الملاحظات في أي صفحة حاسبة، أو تصفح الكود المصدري على <a target="_blank" href="https://github.com/hawstom/engcalcs">GitHub</a>.</p>';
$ec_lang['contact_title']='التواصل مع HawsEDC';
$ec_lang['contactSendMessage']='أرسل رسالة إلى Tom Haws';
$ec_lang['contactYourName']='اسمك:';
$ec_lang['contactYourEmail']='عنوان بريدك الإلكتروني:';
$ec_lang['contactSubject']='الموضوع:';
$ec_lang['contact_message']='الرسالة:';
$ec_lang['contactSpamPrefix']='خمسة زائد واحد يساوي';
$ec_lang['contactSpamPostfix']='(يرجى كتابتها بالحروف. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='إرسال الرسالة';
$ec_lang['contact_success']='شكراً لك على تخصيص الوقت للكتابة.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='تصميم المزلق الصخري (Robinson)';
$ec_lang['rc_main_title']='حاسبة تصميم المزلق الصخري المجانية عبر الإنترنت — Robinson (1998)';
$ec_lang['rc_main_desc']='تحديد حجم الحجارة في المزلق الصخري — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='انحدار قاع المزلق، S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="التدفق لكل وحدة عرض عند مدخل المزلق. لقناة بعرض قاع B وتدفق إجمالي Q، استخدم q_t = Q / B.">التصريف الوحدوي الإجمالي، q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='مسامية الحجارة، n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="الكثافة النسبية إلى الماء. القيمة النموذجية للجرانيت أو البازلت المكسور ≈ 2.65. نطاق Robinson الصحيح: 2.54 إلى 2.82.">الكثافة النسبية للصخر، sg <span class="ec-tip">؟</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="الانحراف المعياري للتدرج. الصخر المنتظم ≈ 1.25. نطاق Robinson الصحيح: 1.15 إلى 1.47.">انحراف التدرج SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="تجمّع المياه (Hp > yn) جيد — يقلل التآكل في أعلى المجرى. (USDA)">العمق الطبيعي في قناة المدخل، y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="المعادلة 1 (S0 < 0.10) أو المعادلة 2 (0.10-0.40). الصحيح: D50 من 15 إلى 278 مم، S0 من 0.02 إلى 0.40. خارج النطاق: قيم خارج المعايرة.">حجم الصخر الوسيط المطلوب، D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='المعادلة المطبّقة';
$ec_lang['rc_sg_check']='فحص الكثافة النسبية';
$ec_lang['rc_SD_check']='فحص انحراف التدرج SD';
$ec_lang['rc_sg_ok']   ='sg ضمن النطاق الصحيح';
$ec_lang['rc_sg_ok_tip']='2.54–2.82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg أقل من نطاق Robinson';
$ec_lang['rc_sg_low_tip']='النطاق الصحيح: 2.54–2.82';
$ec_lang['rc_sg_high'] ='sg أعلى من نطاق Robinson';
$ec_lang['rc_sg_high_tip']='النطاق الصحيح: 2.54–2.82';
$ec_lang['rc_SD_ok']   ='SD ضمن النطاق الصحيح';
$ec_lang['rc_SD_ok_tip']='1.15–1.47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD أقل من نطاق Robinson';
$ec_lang['rc_SD_low_tip']='النطاق الصحيح: 1.15–1.47';
$ec_lang['rc_SD_high'] ='SD أعلى من نطاق Robinson';
$ec_lang['rc_SD_high_tip']='النطاق الصحيح: 1.15–1.47';
$ec_lang['rc_layer']='سماكة طبقة الحجارة (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='نصف قطر منحنى التاج العلوي (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='طول قوس منحنى التاج العلوي';
$ec_lang['rc_apron_length']='<span class="ec-help" title="مطلوب للدعم الإنشائي لحجارة المزلق. “الحد الأدنى لعمق مياه الذيل الناتج عن قطاع المخرج ومقاومة قناة أسفل المجرى كافٍ لضمان استقرار حجارة الحماية في قطاع المخرج.” (Robinson)">طول مصطبة المخرج (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='معامل خشونة Manning في المزلق، n';
$ec_lang['rc_Vm']='<span class="ec-help" title="نسبة من qt تتدفق عبر مسام الحجارة. الباقي qs يتدفق على السطح. الافتراضي np = 0.45 للصخر المكسور الزاوي.">السرعة عبر غطاء الصخر، V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='التدفق الوحدوي عبر الغطاء، q<sub>m</sub>';
$ec_lang['rc_qs']='التدفق الوحدوي السطحي، q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='عمق التدفق فوق سطح الحجارة، d';
$ec_lang['rc_Hp']='<span class="ec-help" title="تجمّع المياه (Hp > yn) جيد — يقلل التآكل في أعلى المجرى. (USDA)">علو المياه فوق الهدار عند المدخل، H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='فحص تجمّع المياه عند المدخل';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — تجمّع مياه في أعلى المجرى';
$ec_lang['rc_pond_ok_tip']='تجمّع المياه في أعلى مدخل المزلق أمر جيد؛ فهو يقلل التآكل في أعلى المجرى. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — لا يوجد تجمّع للمياه — احتمال تآكل عند المدخل';
$ec_lang['rc_pond_warn_tip']='لا يوجد تجمّع للمياه في أعلى مدخل المزلق؛ قد يحدث تآكل في أعلى المجرى. (USDA)';
$ec_lang['rc_eq1']='المعادلة 1 (S<sub>0</sub> < 0.10) — انحدار لطيف';
$ec_lang['rc_eq2']='المعادلة 2 (0.10 ≤ S<sub>0</sub> ≤ 0.40) — انحدار حاد';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0.02 — أقل من نطاق التحقق لدى Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0.40 — أعلى من نطاق التحقق لدى Robinson';
$ec_lang['rc_notes_1_term']='معادلات تحديد حجم الصخر';
$ec_lang['rc_notes_1_def']='طوّر Robinson, Rice & Kadavy (1998) معادلتين تجريبيتين لحجم الحجارة الوسيط D<sub>50</sub> بناءً على انحدار المزلق والتصريف الوحدوي. تُطبَّق المعادلة 1 للانحدارات اللطيفة (S<sub>0</sub> < 0.10)؛ وتُطبَّق المعادلة 2 للانحدارات الحادة (0.10 ≤ S<sub>0</sub> ≤ 0.40). كلتا المعادلتين تستلزمان q<sub>t</sub> بوحدة m²/s وتُعيدان D<sub>50</sub> بالمليمتر. النطاق المعتمد هو 0.02 ≤ S<sub>0</sub> ≤ 0.40.';
$ec_lang['rc_notes_2_term']='التصريف الوحدوي';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> هو التصريف الوحدوي الإجمالي عند تاج المزلق (إجمالي التدفق لكل وحدة عرض). لقناة بعرض قاع B تحمل تدفقاً إجمالياً Q، يُقدَّر q<sub>t</sub> ≈ Q / B، أو يُحسب من شرط العمق الحرج عند مدخل المزلق.';
$ec_lang['rc_notes_3_term']='التدفق عبر غطاء الصخر';
$ec_lang['rc_notes_3_def']='جزء من التدفق الكلي يمر عبر مسام الحجارة (تدفق الغطاء q<sub>m</sub>)؛ والباقي يتدفق فوق سطح الصخر (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). يُحسب عمق التدفق d بتطبيق معادلة Manning على التدفق السطحي q<sub>s</sub> باستخدام خشونة المزلق n. المسامية الافتراضية n<sub>p</sub> = 0.45 نموذجية للصخر المكسور الزاوي.';
$ec_lang['rc_notes_5_term']='نطاق حجم الصخر الصحيح';
$ec_lang['rc_notes_5_def']='طُوِّرت المعادلات باستخدام نطاق D<sub>50</sub> من 15 مم إلى 278 مم. النتائج خارج هذا النطاق تُعدّ استقراءً وينبغي استخدامها بحكم هندسي إضافي.';
$ec_lang['rc_notes_6_term']='منسوب مصطبة المخرج';
$ec_lang['rc_notes_6_def']='ينبغي أن يكون منسوب أعلى حجارة الحماية في قطاع المخرج مساوياً لمنسوب قاع القناة في أسفل المجرى أو أقل منه. إذا كان أعلى، فستكون حجارة المخرج غير مستقرة.';
$ec_lang['rc_notes_7_def']='عندما يكون العمق الطبيعي في قناة المدخل أقل من علو المياه فوق الهدار (H<sub>p</sub>) اللازم لتمرير q<sub>t</sub>، يحدث تدفق مقيّد أو تجمّع للمياه في أعلى مدخل المزلق. هذا مقبول عموماً — فتجمّع المياه يقلل السرعة ويمنع التآكل في أعلى المجرى. للتحقق: استخدم حاسبة تدفق الهدار لإيجاد H<sub>p</sub> لقيمة q<sub>t</sub> وعرض التاج المعطيين، وقارِن الناتج بالعمق الطبيعي لقناة المدخل. إذا تجاوز H<sub>p</sub> العمق الطبيعي، سيحدث تجمّع للمياه.';
$ec_lang['rc_notes_4_term']='المرجع';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. تنشر وزارة الزراعة الأمريكية (USDA ARS) أيضاً <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">جدول Excel</a> يعتمد على نفس الطريقة.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'مرشح';
$ec_lang['rc_sketch_top_crest_curve'] = 'منحنى القمة';
$ec_lang['rc_sketch_outlet_apron']    = 'مصطبة المخرج';
$ec_lang['rc_sketch_radius']          = 'نصف القطر';
// Irrigation Pressure Calculator (branch pipe-network pressure/DU estimate). Prefix ip_.
$ec_lang['ip_main_menu']='ضغط الري';
$ec_lang['ip_main_title']='حاسبة ضغط الري وانتظام التوزيع المجانية عبر الإنترنت';
$ec_lang['ip_main_desc']='اختبار ضغط الفرع وتقدير انتظام التوزيع';
$ec_lang['ip_h_supply']='ضغط الإمداد';
$ec_lang['ip_elev_supply']='منسوب الإمداد، z<sub>supply</sub>';
$ec_lang['ip_q_design']='تدفق القطارة التصميمي، q<sub>design</sub>';
$ec_lang['ip_h_design']='ضغط القطارة التصميمي';
$ec_lang['ip_x']='<span class="ec-help" title="0.5 للقطارات القياسية غير المعوَّضة؛ قريب من 0 للقطارات المعوَّضة بالضغط">أس تصريف القطارة، x <span class="ec-tip">؟</span></span>';
$ec_lang['ip_reach_table_title']='مسار الاختبار';
$ec_lang['ip_group_reach']='قطاع';
$ec_lang['ip_group_upstream']='المنبع';
$ec_lang['ip_group_downstream']='المصب';
$ec_lang['ip_group_loss']='الفاقد';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="مفعّل: هذا القطاع جزء من الخط الجانبي للاختبار الذي تسحب منه القطارات الفردية الماء. معطّل: هذا القطاع خط رئيسي يمرر التدفق فقط إلى خطوط جانبية أخرى لا تقع على مسار الاختبار.">جانبي <span class="ec-tip">؟</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="صفوف الخطوط الجانبية: القطارات في هذا القطاع فقط. صفوف الخط الرئيسي: إجمالي القطارات في الخطوط الجانبية الأخرى غير هذا الخط، والمتفرعة من هذا القطاع. أما قطاع الخط الرئيسي المنتهي عند الخط الجانبي للاختبار، فيشمل أيضاً أي خطوط جانبية أبعد على طول الخط الرئيسي بعد تلك النقطة، أو التي تشارك الوصلة نفسها (كخط جانبي على الجانب المقابل) — إذ يتفرع تدفقها من هذا القطاع نفسه أيضاً.">قطارات <span class="ec-tip">؟</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="منسوب نهاية هذا القطاع من جهة المصب. اختياري في الصفوف الداخلية (الافتراضي: مستوٍ / نفس منسوب العقدة السابقة إذا تُرك فارغاً). مطلوب في الصف الأخير: هذه القيمة هي منسوب آخر قطارة، وهي التي تحدد ضغط الإمداد المطلوب مباشرة.">منسوب المصب <span class="ec-tip">؟</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='منسوب آخر قطارة (الصف الأخير) تُرك فارغاً وافتُرض مستوياً — أدخله للحصول على نتيجة دقيقة';
$ec_lang['ip_flow']='التدفق';
$ec_lang['ip_press']='ضغط';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="إجمالي فاقد القطاع، h_f + h_m">h<sub>L</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['ip_pressure_warn']='ضغط منخفض/سالب — تحقق من احتمال وجود حالات دون الضغط الجوي';
$ec_lang['ip_pressure_warn_short']='منخفض';
$ec_lang['ip_pressure_high']='مواقع الضغط المرتفع تحتاج إلى تخفيض الضغط';
$ec_lang['ip_pressure_high_short']='مرتفع';
$ec_lang['ip_max_head']='أقصى ضغط مسموح للأنبوب';
$ec_lang['ip_max_head_tip']='يتم تمييز الخطوط التي يتجاوز ضغطها هذه القيمة. اتركه فارغاً لتخطي فحص الضغط المرتفع.';
$ec_lang['ip_h_far']='ضغط آخر قطارة';
$ec_lang['ip_q_supply']='<span class="ec-help" title="التدفق الداخل إلى مسار الاختبار المنمذج فقط — للمنطقة/النظام كاملاً، انظر Q_zone في تصميم التطبيق أدناه.">تدفق إمداد مسار الاختبار، Q<sub>supply</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['ip_q_critical']='تدفق آخر قطارة، q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='متوسط تدفق القطارة (الخط الجانبي للاختبار)، q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="مقدار ارتفاع (أو انخفاض) ضغط تشغيل الخط الجانبي المتوسط النموذجي مقارنةً بهذا الخط الجانبي للاختبار، حسب تقديرك. الخط الجانبي للاختبار مفترض عمداً ليكون أسوأ الحالات، لذا فإن متوسطه الخاص يقلل من تقدير متوسط الحقل الفعلي — إذا تُرك عند 0، فإن فحص الانتظام وأرقام تصميم التطبيق أدناه تستخدم متوسط الخط الجانبي للاختبار نفسه (وهو على الأرجح متفائل) كما هو.">فرق الضغط المقدَّر، المتوسط مقابل الخط الجانبي للاختبار <span class="ec-tip">؟</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="يُعاد تقييم q_avg_lateral عند ضغط كل صف من الخطوط الجانبية مضافاً إليه فرق الضغط المُدخل أعلاه — في محاولة لتصحيح كون الخط الجانبي للاختبار هو الحالة الأسوأ المفترضة وليس الممثل الفعلي. يُغذّي كلاً من فحص الانتظام وقسم تصميم التطبيق أدناه.">تدفق القطارة المتوسط الحقلي المقدَّر، q<sub>avg,field</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="تدفق آخر قطارة المحسوب مقسوماً على تدفق القطارة المتوسط الحقلي المقدَّر — هذا تقريب لانتظام التوزيع القياسي للربع الأدنى (متوسط المجموعة الدنيا ÷ متوسط المجتمع)؛ لكنه مأخوذ من عينة نموذجية صغيرة وتصحيح مقدَّر من المستخدم بدلاً من عينة إحصائية ميدانية كاملة. القيم المساوية لـ 1 أو أعلى ممكنة وصحيحة: فهي تعني فقط أن ضغط آخر قطارة يساوي أو يفوق متوسط الحقل المقدَّر، بحيث تكون قطارة أخرى هي نقطة الضغط الأدنى. قد يكون ذلك لأن آخر قطارة تقع في أرض منخفضة أو لأن تقدير فرق الضغط أصغر من اللازم.">فحص الانتظام، q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['ip_worst_case_warn']='ضغط القطارة المختبرة أكبر من أو يساوي ضغط الإمداد. من المرجح أن هذه ليست قطارة أسوأ الحالات، أو يمكن استخدام أنابيب أصغر.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="هذا مختلف عن تقريبنا لمقياس الانتظام القياسي.">تدفق آخر قطارة ÷ التدفق التصميمي، q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">؟</span></span>';
$ec_lang['ip_no_solution']='لا يوجد حل: ضغط الإمداد المطلوب يتجاوز ضغط الإمداد المُدخل. زِد ضغط الإمداد، أو قلِّل الطلب، أو استخدم أنبوباً أكبر.';
$ec_lang['ip_notes_1_def']='يُخمِّن الضغط عند آخر قطارة (الأبعد)، ثم يتراجع بخط تدرج الطاقة نحو الإمداد، قطاعاً تلو الآخر، مضيفاً فاقد الاحتكاك والفاقد الثانوي في الطريق. يُطرح الارتفاع ورأس السرعة عند كل عقدة للإبلاغ عن الضغط الفعلي هناك. يُعدَّل الضغط المخمَّن عند الطرف البعيد (بطريقة التنصيف) حتى يطابق ضغط الإمداد المطلوب المحسوب ضغط الإمداد المُدخل — وهي نفس مسألة الحلقة المغلقة التي يعالجها محلل تدفق الأنابيب في حاسبة جريان الأنابيب بمعادلة مانينغ، لكن ممتدة إلى شبكة متفرعة.';
$ec_lang['ip_notes_2_term']='قطاعات الخط الرئيسي مقابل الخط الجانبي';
$ec_lang['ip_notes_2_def']='كل صف هو قطاع واحد على طول المسار الهيدروليكي الأسوأ الوحيد (مسار الاختبار) من الإمداد إلى آخر قطارة. قطاع الخط الرئيسي يمرر التدفق فقط إلى الخطوط الجانبية التي لا تقع على مسار الاختبار، لذا فإن سحبه هو ضرب بسيط (التدفق التصميمي × إجمالي عدد القطارات في القطاع) — دون أي حساسية للضغط المحلي. الخط الرئيسي أنبوب جذعي مشترك، لذا يجب أن يشمل قطاع الخط الرئيسي المنتهي عند الخط الجانبي للاختبار ليس فقط الخطوط الجانبية الواقعة بين طرفيه، بل أيضاً أي خطوط جانبية أبعد على طول الخط الرئيسي بعد تلك النقطة، أو تشارك الوصلة نفسها (كخط جانبي على الجانب المقابل) — إذ يمر تدفقها عبر هذا القطاع نفسه قبل أن يتفرع، سواء ظهرت في مكان آخر بهذا الجدول أم لا. أما قطاع الخط الجانبي فهو جزء من الخط الجانبي للاختبار نفسه: يُحسب تصريف القطارة من الضغط المحلي الفعلي عبر المعادلة q = k·H<sup>x</sup>، ويُخفَّض فاقد الاحتكاك بعامل Christiansen F(n) لمراعاة انخفاض التدفق مع سحب كل قطارة في القطاع للماء.';
$ec_lang['ip_notes_3_term']='القيود';
$ec_lang['ip_notes_3_def']='يُنمذج ضغط إمداد ثابتاً واحداً (بلا منحنى مضخة)، ومسار اختبار واحداً فقط (وليس الحقل بأكمله)، ومنحنى قطارة بمعاملين (اضبط الأس قريباً من 0 لتقريب قطارة معوَّضة بالضغط). يُبلَّغ عن نسبتي انتظام مختلفتين، أُبقيتا منفصلتين عمداً: q<sub>last</sub>/q<sub>avg,field</sub> تقريب لانتظام التوزيع القياسي للربع الأدنى (متوسط المجموعة الدنيا ÷ متوسط المجتمع)؛ لكنها مأخوذة من عينة نموذجية صغيرة وتصحيح مقدَّر من المستخدم بدلاً من العينة الإحصائية الميدانية الكاملة القياسية. كذلك، الخط الجانبي للاختبار مفترض عمداً ليكون أسوأ الحالات، لذا فإن متوسطه الخام غير المصحَّح كان سيقلل من تقدير متوسط الحقل الحقيقي ويجعل الانتظام يبدو أفضل مما هو عليه؛ وقد وُضع مُدخل فرق الضغط خصيصاً لموازنة هذا التحيز. تبقى القيم المساوية لـ 1 أو أعلى ممكنة: فهي تعني فقط أن ضغط آخر قطارة يساوي أو يفوق متوسط الحقل المقدَّر، بحيث تكون قطارة أخرى هي نقطة الضغط الأدنى. قد يكون ذلك لأن آخر قطارة تقع في أرض منخفضة أو لأن تقدير فرق الضغط أصغر من اللازم. أما q<sub>last</sub>/q<sub>design</sub> فهو فحص مختلف، غير متعلق بالانتظام، مقابل التدفق المقنَّن من المصنّع — مفيد لكشف نظام مرتفع أو منخفض الضغط عموماً، لكنه فحص منفصل يُقرأ إلى جانب رقم الانتظام، لأن التدفق التصميمي/المقنَّن مستقل عن متوسط ضغط تشغيل النظام الفعلي.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). “Irrigation by sprinkling.” California Agricultural Experiment Station Bulletin 670. تستخدم معايير ASAE/ASABE لتصميم الري الدقيق نفس أسلوب حساب فاقد الاحتكاك متعدد المخارج.';
$ec_lang['ip_notes_5_term']='تصميم التطبيق';
$ec_lang['ip_notes_5_def']='يستخدم معدل التطبيق وتدفق النظام/المنطقة تدفق القطارة المتوسط الحقلي المقدَّر (q<sub>avg,field</sub> — متوسط الخط الجانبي للاختبار نفسه، مصحَّحاً بتقدير فرق الضغط المُدخل)، وليس معدلاً مخمَّناً: PR = q<sub>avg,field</sub> / A<sub>e</sub>، مُغذّى بالقيمة النموذجية المصحَّحة. التباعد وأعداد الخطوط الجانبية/القطارات على مستوى النظام مُدخلات منفصلة هنا لأن مسار الاختبار ينمذج فرعاً واحداً فقط هو أسوأ الحالات، وليس كل خط جانبي في الحقل.';



// --- Branched Pipe Network (bpn_) --- English source ---
$ec_lang['bpn_main_menu']='شبكة الأنابيب المتفرعة';
$ec_lang['bpn_main_title']='حاسبة ضغط شبكة الأنابيب المتفرعة المجانية عبر الإنترنت (بدون حلقات)';
$ec_lang['bpn_main_desc']='تدفق وضغط شبكة الأنابيب المتفرعة (الشجرية)';
$ec_lang['bpn_h_source_tip']='العلو الساكن للإمداد: علو المصدر عند تدفق صفري. مستوى الماء في خزان أو صهريج أعلى من منسوب الإمداد، أو علو الإغلاق لمضخة. أضف نقطتي الإمداد 2 و3 لتحديد منحنى مضخة أو إمداد متغير؛ تقرأ الأداة العلو عند التدفق التصميمي.';
$ec_lang['bpn_elev_source']='منسوب الإمداد';
$ec_lang['bpn_q_total']='إجمالي التدفق';
$ec_lang['bpn_q_total_tip']='إجمالي التدفق الخارج من المصدر (مجموع جميع الطلبات في الشبكة).';
$ec_lang['bpn_p_min']='أدنى ضغط';
$ec_lang['bpn_p_min_tip']='أدنى ضغط مصب في أي مكان بالشبكة؛ وهي نقطة التسليم الحرجة.';
$ec_lang['bpn_method']='طريقة الاحتكاك';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='خطوط الأنابيب';
$ec_lang['bpn_id']='المعرّف';
$ec_lang['bpn_id_tip']='اسم خط الأنبوب هذا. تشير إليه الخطوط الأخرى في عمود المنبع.';
$ec_lang['bpn_upstream']='معرّف المنبع';
$ec_lang['bpn_upstream_tip']='معرّف الخط الذي يغذي هذا الخط. اتركه فارغاً لمتابعة الخط الذي يعلوه مباشرة (خط أنابيب متسلسل بسيط). أدخل معرّفاً هنا للتفرع من خط آخر.';
$ec_lang['bpn_roughness_tip']='خشونة الأنبوب لطريقة الاحتكاك المختارة: معامل مانينغ n، أو معامل هيزن-وليامز C، أو ارتفاع خشونة دارسي-وايسباخ e (طول). الأنبوب البلاستيكي الأملس النموذجي: n نحو 0.009، وC نحو 150، وe نحو 0.0015 مم.';
$ec_lang['bpn_demand']='الطلب';
$ec_lang['bpn_demand_tip']='تدفق ثابت يُسلَّم عند طرف مصب هذا الخط. اتركه فارغاً لخط يكتفي بنقل التدفق إلى ما بعده.';
$ec_lang['bpn_demand_mult']='مضاعف الطلب';
$ec_lang['bpn_demand_mult_tip']='يُضاعف طلب جميع الخطوط دفعة واحدة، لتشغيل ذروة الساعة أو نمو مستقبلي. استخدم القيمة 1 للطلبات كما أُدخلت.';
$ec_lang['bpn_elev_down']='منسوب المصب';
$ec_lang['bpn_q_line']='تدفق الخط';
$ec_lang['bpn_q_line_tip']='إجمالي التدفق الذي يحمله هذا الخط: طلبه الخاص مضافاً إليه كل طلب مصبّي يغذّيه.';
$ec_lang['bpn_p_down']='ضغط المصب';
$ec_lang['bpn_p_down_tip']='علو الضغط المقيسي عند عقدة مصب هذا الخط. القيمة السالبة (المميَّزة) تعني ضغطاً دون الضغط الجوي؛ راجع التصميم.';
$ec_lang['bpn_sketch_title']='مخطط الشبكة';
$ec_lang['bpn_show_length']='الطول';
$ec_lang['bpn_show_diameter']='القطر';
$ec_lang['bpn_show_q']='التدفق';
$ec_lang['bpn_show_p']='الضغط';
$ec_lang['bpn_source_label']='المصدر';
$ec_lang['bpn_topology_warn']='تحقق من عمود المنبع: أحد الخطوط يشير إلى معرّف غير معروف، أو يشير إلى نفسه، أو يكوّن حلقة، مما يجعل جزءاً من الشبكة غير متصل بالمصدر. تُترك هذه الخطوط دون حل.';
$ec_lang['bpn_topology_warn_short']='الشبكة';
$ec_lang['bpn_pressure_warn']='ضغط منخفض/سالب؛ تحقق من احتمال وجود حالات دون الضغط الجوي';
$ec_lang['bpn_pressure_warn_short']='منخفض';
$ec_lang['bpn_notes_1_term']='التسلسل هو الافتراضي، والتفرع هو الاستثناء';
$ec_lang['bpn_notes_1_def']='اترك معرّف المنبع فارغاً ليتبع الخط الذي يعلوه؛ أي خط أنابيب متسلسل بسيط. أدخل معرّف خط علوي للتفرع منه. إذاً: تسلسل بشكل افتراضي، وشجرة متفرعة عند الحاجة إليها.';
$ec_lang['bpn_notes_2_term']='شبكات متفرعة فقط، بلا حلقات';
$ec_lang['bpn_notes_2_def']='لكل خط خط منبع واحد فقط بالضبط (شجرة). لا تحل هذه الأداة الشبكات الحلقية؛ فتلك تحتاج إلى طرائق تكرارية (مثل EPANET أو ما شابهها). استبعاد الحلقات هو ما يجعل الحل بسيطاً ودقيقاً.';
$ec_lang['bpn_notes_3_term']='بلا عناصر تحكم فعّالة بالضغط';
$ec_lang['bpn_notes_3_def']='يمكنك إضافة صمام ذي فاقد موضعي ثابت (قيمة k)، ولكن ليس صمامات تخفيض الضغط أو مواصلة الضغط (PRV/PSV). فحالة فتحها أو إغلاقها تعتمد على التدفق والضغط، مما يفرض الحل التكراري.';
$ec_lang['bpn_supply2_q']='تدفق الإمداد 2';
$ec_lang['bpn_supply2_h']='علو الإمداد 2';
$ec_lang['bpn_supply3_q']='تدفق الإمداد 3';
$ec_lang['bpn_supply3_h']='علو الإمداد 3';
$ec_lang['bpn_supply_pt_tip']='نقطتا منحنى الإمداد 2 و3 اختياريتان. أدخل تدفقاً وعلواً لكل منهما لتمثيل مضخة، أو أي مصدر ينخفض علوه كلما زاد ما يسلّمه؛ تقرأ الأداة العلو عند التدفق التصميمي. النقطة 1 أعلاه هي العلو الساكن عند تدفق صفري. اترك 2 و3 فارغتين لعلو خزان ثابت.';
$ec_lang['bpn_h_supply']='علو الإمداد';
$ec_lang['bpn_h_supply_tip']='علو المصدر عند التدفق التصميمي، مقروءاً من منحنى الإمداد. يساوي علو المصدر المُدخل عندما يكون المنحنى مستوياً (خزان).';
$ec_lang['bpn_show_elevation']='المنسوب';
$ec_lang['bpn_supply1_h']='العلو الساكن للإمداد';
$ec_lang['consent_body']='هل يمكننا الاحتفاظ برقم واحد لكل صفحة في تخزين ملف تعريف هذا المتصفح لمنع تسجيل زياراته بشكل متكرر؟';
$ec_lang['consent_accept']='الموافقة هذه المرة';
$ec_lang['consent_accept_all']='الموافقة دائماً';
$ec_lang['consent_decline']='رفض';
$ec_lang['consent_current_granted']='لقد وافقت على هذا. نحن نحدّ من التسجيل لملف تعريف هذا المتصفح.';
$ec_lang['consent_current_denied']='لقد رفضت هذا. لا نخزّن شيئاً للحد من التسجيل لملف تعريف هذا المتصفح.';
$ec_lang['consent_region_label']='اختيارك بشأن الحد من التسجيل.';
$ec_lang['consent_settings_link']='إعدادات ملفات تعريف الارتباط';
$ec_lang['privacy_link']='إشعار الخصوصية';
$ec_lang['terms_link']='شروط الاستخدام';
$ec_lang['lpn_main_menu']='شبكة إمداد المياه';
$ec_lang['lpn_main_title']='حاسبة مجانية عبر الإنترنت لشبكات توزيع المياه بمحرك EPANET';
$ec_lang['lpn_main_desc']='تحليل شبكة إمداد المياه: ارسم شبكة أنابيب حلقية أو استورد ملفات EPANET';
$ec_lang['lpn_title_units']='وحدات {units}';
$ec_lang['lpn_tool_select']='تحديد';
$ec_lang['lpn_tool_add_junction']='ملتقى';
$ec_lang['lpn_tool_add_reservoir']='خزان';
$ec_lang['lpn_tool_add_pipe']='أنبوب';
$ec_lang['lpn_tool_add_pump']='مضخة';
$ec_lang['lpn_tool_add_text']='نص';
$ec_lang['lpn_tool_delete']='حذف';
$ec_lang['lpn_tool_zoom_extent']='إظهار الكل';
$ec_lang['lpn_new_text']='نص';
$ec_lang['lpn_field_elev']='المنسوب';
$ec_lang['lpn_field_elev_tip']='منسوب الأرض أو الأنبوب عند هذه العقدة. قسه من أي نقطة صفر تختارها، طالما استخدمت جميع العقد النقطة نفسها.';
$ec_lang['lpn_field_head']='العلو';
$ec_lang['lpn_field_head_tip']='منسوب سطح الماء في الخزان، ويُقاس كارتفاع لا كضغط. اتركه فارغاً لجعل سطح الماء عند منسوب الخزان.';
$ec_lang['lpn_close']='إغلاق';
$ec_lang['lpn_empty_hint']='ابدأ بإضافة صورة خلفية أو خزان من شريط الأدوات، أو افتح ملف، مشروع جديد للبدء من مثال.';
$ec_lang['lpn_tool_undo']='تراجع';
$ec_lang['lpn_confirm_example']='سيؤدي هذا إلى إضافة المثال إلى الشبكة الموجودة لديك بالفعل. هل تريد المتابعة؟';
$ec_lang['lpn_field_diameter']='القطر';
$ec_lang['lpn_demand_tip']='التدفق المسحوب من الشبكة عند هذه العقدة. أدخل رقماً سالباً للتدفق المضاف إلى الشبكة هنا.';
$ec_lang['lpn_units_length']='الطول وإحداثيات الخريطة';
$ec_lang['lpn_units_elevhead']='المنسوب والعلو';
$ec_lang['lpn_units_pressure']='الضغط';
$ec_lang['lpn_units_flow']='التدفق';
$ec_lang['lpn_units_velocity']='السرعة';
$ec_lang['lpn_result_gradient']='تدرج فقدان الضغط';
$ec_lang['lpn_result_gradient_tip']='فقدان الضغط مقسوماً على طول الأنبوب. استخدمه لمقارنة الأنابيب ذات الأطوال المختلفة بحد تصميم واحد.';
$ec_lang['lpn_result_head']='العلو';
$ec_lang['lpn_result_head_tip']='طاقة الماء عند هذه العقدة، معبَّراً عنها كارتفاع عمود ماء. هي ارتفاع لا ضغط.';
$ec_lang['lpn_result_pressure']='الضغط';
$ec_lang['lpn_result_flow']='التدفق';
$ec_lang['lpn_result_velocity']='السرعة';
$ec_lang['lpn_result_headloss']='فقدان الضغط';
$ec_lang['lpn_settings_restore_tip']='يعيد ضبط إعدادات هذا المشروع فقط. لا يتغيّر رسمك ولا مشاريعك الأخرى. لحفظ إعداداتك المفضّلة لإعادة استخدامها، احفظ ملف مشروع لا يحتوي إلا على الإعدادات.';
$ec_lang['lpn_reset_all_tip']='يحذف كل مشروع، وكل صورة خلفية، وكل إعداد، واختياراتك للوحدات، ثم يعيد تحميل الصفحة تماماً كما يراها زائر لأول مرة. هذا هو إعادة الضبط الوحيدة التي تمسح كل شيء.';
$ec_lang['lpn_v2_restore_prompt']='تخزّن هذه الحاسبة وحدات المشروع ومدخلاته كما أُدخلت، لكنها كانت سابقاً تحوّل الأرقام إلى النظام الدولي للوحدات (SI) عند التخزين. حُفظ هذا المشروع قبل ذلك التغيير، لذا كانت أرقامه مخزَّنة بالنظام الدولي. هل تريد تحويلها مرة أخيرة إلى الوحدات الحالية؟ لتتمكّن من الحكم، إليك بعض الأقطار التي ستُحوَّل، بقيمها قبل التحويل وبعده:';
$ec_lang['lpn_v2_restore_yes']='تحويل';
$ec_lang['lpn_v2_restore_never']='لا. لا تسألني مرة أخرى.';
$ec_lang['lpn_v2_restore_no']='إغلاق لأتحقق أولاً من الوحدات الحالية';
$ec_lang['lpn_storage_too_new']='حُفظ هذا المشروع بإصدار أحدث من الصفحة، لذا لا يمكن فتحه هنا.';
$ec_lang['lpn_tool_file']='ملف';
$ec_lang['lpn_menu_edit']='تحرير';
$ec_lang['lpn_menu_insert']='إدراج';
$ec_lang['lpn_menu_view']='عرض';
$ec_lang['lpn_menu_settings']='الإعدادات';
$ec_lang['lpn_edit_delete_network']='حذف الشبكة';
$ec_lang['lpn_confirm_delete_network']='هل تريد حذف كل عقدة وأنبوب وتسمية نصية في هذا المشروع؟ تبقى الصورة الخلفية واسم المشروع وإعداداتك دون تغيير. لا يمكن التراجع عن هذا.';
$ec_lang['lpn_view_units']='الوحدات';
$ec_lang['lpn_file_saveall']='حفظ الكل';
$ec_lang['lpn_project_numbered']='مشروع{n}';
$ec_lang['lpn_project_copy_suffix']='(نسخة)';
$ec_lang['lpn_project_rename']='إعادة تسمية';
$ec_lang['lpn_file_new']='مشروع جديد…';
$ec_lang['lpn_new_blank_us']='مشروع فارغ، وحدات أمريكية (gpm)';
$ec_lang['lpn_new_blank_si']='مشروع فارغ، وحدات النظام الدولي (l/s)';
$ec_lang['lpn_new_from_examples']='من الأمثلة';
$ec_lang['lpn_new_example_us']='شبكة أساسية، وحدات أمريكية (gpm)';
$ec_lang['lpn_new_example_si']='شبكة أساسية، وحدات النظام الدولي (l/s)';
$ec_lang['lpn_file_open']='فتح…';
$ec_lang['lpn_file_save']='حفظ';
$ec_lang['lpn_file_saveas']='حفظ باسم…';
$ec_lang['lpn_file_revert']='استرجاع';
$ec_lang['lpn_file_close']='إغلاق';
$ec_lang['lpn_file_recent']='الملفات الأخيرة';
$ec_lang['lpn_recent_tip']='أعد فتح {file} دون الحاجة إلى البحث عنه في جهازك.';
$ec_lang['lpn_recent_denied']='لم يُمنح الإذن لفتح ذلك الملف، لذا لم يُفتح.';
$ec_lang['lpn_recent_gone']='تعذّر فتح {file}. ربما نُقل أو أُعيدت تسميته أو حُذف، لذا أُزيل من القائمة الأخيرة.';
$ec_lang['lpn_tab_new']='مشروع جديد';
$ec_lang['lpn_tab_all']='كل المشاريع';
$ec_lang['lpn_tab_menu']='قائمة المشروع';
$ec_lang['lpn_tab_duplicate']='نسخ';
$ec_lang['lpn_tab_move_left']='نقل إلى اليسار';
$ec_lang['lpn_tab_move_right']='نقل إلى اليمين';
$ec_lang['lpn_tab_unsaved']='غير محفوظ في ملف';
$ec_lang['lpn_import_bad_file']='تعذّرت قراءة ذلك الملف كمشروع محفوظ من هذه الصفحة.';
$ec_lang['lpn_import_no_room']='لا توجد مساحة تخزين كافية في المتصفح لإضافة هذا المشروع. احذف مشروعاً لم تعد بحاجة إليه وحاول مرة أخرى.';
$ec_lang['lpn_dialog_ok']='موافق';
$ec_lang['lpn_file_import_inp']='استيراد ملف EPANET…';
$ec_lang['lpn_file_import_inp_tip']='اقرأ شبكة من ملف EPANET، سواء الملف النصي .inp أو ملف .net الذي يحفظه EPANET، واحفظها في هذا المتصفح كمشروع جديد. لا يمكن لهذه الصفحة كتابة ملف EPANET مرة أخرى، فاستخدم ملف، حفظ باسم للحفاظ على عملك.';
$ec_lang['lpn_inp_bad_file']='تعذّرت قراءة ذلك الملف كملف شبكة EPANET.';
$ec_lang['lpn_net_bad_file']='يبدو هذا ملف .net من EPANET، لكن هذه الصفحة تعذّر عليها قراءته. افتحه في EPANET واستخدم أمر ملف، تصدير، شبكة هناك لحفظه كملف .inp، ثم استورد ذلك الملف.';
$ec_lang['lpn_inp_report_heading']='تم استيراد {file}';
$ec_lang['lpn_inp_report_counts']='{nodes} من الملتقيات والخزانات، و{links} من الأنابيب والمضخات، بوحدات {units}.';
$ec_lang['lpn_inp_report_clean']='انتقل كل شيء في الملف بنجاح. لم يُستبعد شيء.';
$ec_lang['lpn_inp_report_lead']='لا تحمل هذه الصفحة كل ما يحمله EPANET. وفيما يلي ما تغيّر أثناء الاستيراد:';
$ec_lang['lpn_inp_drop_headloss']='لا يستخدم هذا الملف معادلة هيزن-وليامز. تحسب هذه الصفحة هيزن-وليامز، لذا أُبقيت أرقام خشونة الأنابيب كما كُتبت تماماً، لكن النتائج هنا لن تطابق نتائج EPANET.';
$ec_lang['lpn_inp_drop_tanks']='استُبعدت صهاريج التخزين. تحتوي هذه الصفحة على خزانات ذات منسوب مائي ثابت واحد. لا يحافظ صهريج التخزين على منسوب ثابت، لذا فهو ليس خزاناً.';
$ec_lang['lpn_inp_drop_tank_links']='استُبعدت هذه الأنابيب لأنها تتصل بصهريج تم استبعاده.';
$ec_lang['lpn_inp_drop_tcv']='دخلت صمامات التحكم الخانقة هذه كأنابيب قصيرة جداً تحمل الفاقد الموضعي نفسه. يسلك الماء المسلك نفسه، لكن العنصر ليس نفسه.';
$ec_lang['lpn_inp_drop_valve']='تتحكم هذه الصمامات في الضغط أو التدفق، ولا تحتوي هذه الصفحة على عنصر مماثل. دخلت كأنابيب مفتوحة، فبقيت الشبكة متصلة، لكن لم يعد هناك ما يتحكم بها.';
$ec_lang['lpn_inp_drop_cv']='في EPANET، تسمح هذه الأنابيب بمرور الماء في اتجاه واحد فقط. دخلت كأنابيب عادية، فقد يتدفق الماء الآن في أي من الاتجاهين خلالها.';
$ec_lang['lpn_inp_drop_demands']='كان لهذه الملتقيات أكثر من طلب واحد. جُمعت الطلبات معاً في الطلب الواحد الذي تحمله هذه الصفحة.';
$ec_lang['lpn_inp_drop_patterns']='استُبعدت أنماط الطلب. تحل هذه الصفحة للحظة زمنية واحدة، لذا فإن كل طلب هو الرقم المكتوب في الملف.';
$ec_lang['lpn_inp_drop_emitters']='لهذه الملتقيات معامل رشاش أو تسرّب. أُبقي عليه ويُحسب ضمن الحل، لكن لا يوجد بعد مكان في هذه الصفحة لعرضه أو تغييره.';
$ec_lang['lpn_inp_drop_curve_long']='كان لمنحنى هذه المضخة أكثر من ثلاث نقاط. أُبقي على أدنى نقطة وأوسطها وأعلاها، لأن هذه الصفحة توائم منحنى بثلاث نقاط على الأكثر.';
$ec_lang['lpn_inp_drop_curve_missing']='تشير هذه المضخة إلى منحنى غير موجود في الملف. دخلت دون منحنى، فهي لا تضيف أي علو.';
$ec_lang['lpn_inp_drop_pump_other']='تُوصف هذه المضخة بالقدرة أو السرعة أو جدول زمني، لا بمنحنى. دخلت دون منحنى، فهي لا تضيف أي علو.';
$ec_lang['lpn_inp_drop_setting']='تحمل هذه الأنابيب والمضخات والصمامات إعداداً لا يمكن لهذه الصفحة الاحتفاظ به. دخلت مفتوحة.';
$ec_lang['lpn_inp_drop_controls']='استُبعدت عناصر التحكم والقواعد. دخل كل أنبوب ومضخة وصمام بالحالة المكتوبة في الملف، ولا يتغيّر.';
$ec_lang['lpn_inp_drop_eps']='يصف هذا الملف محاكاة تمتد على فترة زمنية. تحل هذه الصفحة للحظة واحدة، لذا دخلت الظروف الابتدائية فقط.';
$ec_lang['lpn_inp_drop_quality']='استُبعدت إعدادات جودة المياه والتفاعل الكيميائي وطاقة المضخة. تحل هذه الصفحة التدفق والضغط فقط.';
$ec_lang['lpn_inp_drop_backdrop']='يشير هذا الملف إلى صورة خلفية لكنه لا يحتوي على الصورة نفسها. أضفها بنفسك عبر ملف، صورة خلفية، إضافة صورة.';
$ec_lang['lpn_inp_drop_dangling']='تشير هذه الأنابيب إلى ملتقى غير موجود في الملف، لذا استُبعدت.';
$ec_lang['lpn_inp_drop_units']='لم تُعرَف وحدات التدفق في هذا الملف، فافتُرضت غالونات في الدقيقة. تحقق من كل رقم قبل استخدام النتائج.';
$ec_lang['lpn_status_imported']='فُتح {name} من ملف، وأُضيف إلى هذا المتصفح كمشروع جديد.';
$ec_lang['lpn_file_type_desc']='ملف مشروع';
$ec_lang['lpn_file_upload_explain']='لا يستطيع هذا المتصفح الاتصال بملف، فإن فتح ملف هنا هو في الواقع رفع: يُنسخ المشروع إلى هذا المتصفح، والطريقة الوحيدة لحفظ عملك في الملف مرة أخرى هي الكتابة فوقه عبر ملف، حفظ باسم.';
$ec_lang['lpn_file_save_tip']='يحفظ في الملف المتصل.';
$ec_lang['lpn_file_saveas_tip']='اختر ملفاً لتحفظ فيه. يتصل هذا المشروع بذلك الملف، ويكتب أمر الحفظ فيه من الآن فصاعداً.';
$ec_lang['lpn_file_saveas_tip_download']='يحفظ باستخدام إعدادات التنزيل في متصفحك. لا يستطيع هذا المتصفح الاتصال بملف، لذا فإن الحفظ معطّل ولا يتوفر إلا حفظ باسم. إذا فعّلت إعداد المتصفح “السؤال عن مكان حفظ كل ملف”، يمكنك اختيار الملف الأصلي والكتابة فوقه.';
$ec_lang['lpn_status_uploaded']='تم رفع ملف المشروع. لا يمكن الحفاظ على اتصال به، فالطريقة الوحيدة للحفظ فيه مرة أخرى هي استخدام ملف، حفظ باسم.';
$ec_lang['lpn_status_downloaded']='تم تنزيل {file}. لا يستطيع هذا المتصفح الاتصال بملف، لذا يبقى هذا المشروع معلَّماً بأنه غير محفوظ في ملف.';
$ec_lang['lpn_status_file_opened']='تم فتح {file}.';
$ec_lang['lpn_status_already_open']='ذلك الملف مفتوح هنا بالفعل باسم {name}، لذا تم التحويل إليه بدلاً من فتح نسخة ثانية.';
$ec_lang['lpn_status_already_open_dirty']='ذلك الملف مفتوح هنا بالفعل باسم {name}، وفيه تغييرات لم تُحفظ. تم التحويل إليه بدلاً من فتح نسخة ثانية. استخدم ملف، استرجاع إذا أردت النسخة الموجودة على القرص بدلاً من ذلك.';
$ec_lang['lpn_status_saved']='تم حفظ {file}.';
$ec_lang['lpn_status_reverted']='أُعيد تحميل {file} من القرص.';
$ec_lang['lpn_close_save_prompt']='هل تريد حفظ تغييراتك في {name} قبل إغلاقه؟';
$ec_lang['lpn_close_browser_prompt']='يُحفظ {name} في هذا المتصفح فقط. إذا أغلقته دون حفظه في ملف، فسيضيع نهائياً.';
$ec_lang['lpn_close_discard']='إغلاق دون حفظ';
$ec_lang['lpn_cancel']='إلغاء';
$ec_lang['lpn_revert_confirm']='هل تريد التخلص من التغييرات التي أجريتها وإعادة تحميل {file} من القرص؟';
$ec_lang['lpn_file_needs_reopen']='جاء هذا المشروع من {file}، لكن الاتصال بذلك الملف انقطع. اختر الملف مرة أخرى للاتصال به.';
$ec_lang['lpn_file_write_failed']='تعذّرت الكتابة في الملف. ربما نُقل أو أُعيدت تسميته، أو سُحب الإذن. لا يزال عملك محفوظاً في هذا المتصفح.';
$ec_lang['lpn_file_changed_elsewhere']='حفظ شخص آخر في هذا الملف منذ أن فتحته، فالحفظ الآن سيكتب فوق عمله. استخدم ملف، حفظ باسم للاحتفاظ بتغييراتك في ملف خاص بك، أو ملف، استرجاع للتخلص من تغييراتك وتحميل تغييراته.';
$ec_lang['lpn_lock_prompt_name']='ماذا يجب أن يرى زملاؤك عندما يكون هذا المشروع مفتوحاً لديك؟ الأحرف الأولى من اسمك مثالية. يمكن لأي شخص يفتح الملف نفسه أن يرى هذا، فلا تستخدم أي معلومة خاصة.';
$ec_lang['lpn_lock_somebody']='شخص آخر';
$ec_lang['lpn_lock_open_heading']='{name} فتح هذا الملف.';
$ec_lang['lpn_lock_open_readonly']='فتح للقراءة فقط';
$ec_lang['lpn_lock_open_copy']='إنشاء نسخة';
$ec_lang['lpn_lock_break']='كسر قفلهم';
$ec_lang['lpn_lock_open_heading_times']='{name} فتح هذا الملف؛ كان آخر تعديل قبل {x}، أي بعد {y} من آخر حفظ.';
$ec_lang['lpn_lock_open_heading_unsaved']='{name} فتح هذا الملف؛ كان آخر تعديل قبل {x}، ولم يُحفظ أي منه في هذا الملف بعد.';
$ec_lang['lpn_lock_open_heading_saved']='{name} فتح هذا الملف؛ كان آخر تعديل قبل {x}، وعمله محفوظ في الملف.';
$ec_lang['lpn_lock_open_heading_seen']='{name} فتح هذا الملف لكن لم يعدّله. تحقق متصفحه آخر مرة قبل {x}.';
$ec_lang['lpn_lock_open_choices']='خياراتك: (1) الإلغاء وطلب فتحه إذا لزم الأمر ثم إغلاقه بشكل صحيح (إغلاق المتصفح لا يغلق المشروع)، (2) الفتح للقراءة فقط، أو (3) إذا فشل كل شيء آخر، يمكنك كسر قفلهم. لا يضيع عملهم غير المحفوظ، لكنهم لن يتمكنوا من الحفظ فوق تغييراتك، وقد يحتاج أحد إلى دمج الاثنين يدوياً.';
$ec_lang['lpn_ago_seconds']='{n} ثانية';
$ec_lang['lpn_ago_minutes']='{n} دقيقة';
$ec_lang['lpn_ago_hours']='{n} ساعة';
$ec_lang['lpn_ago_days']='{n} يوم';
$ec_lang['lpn_ago_unknown']='وقت غير معروف';
$ec_lang['lpn_lock_readonly_banner']='للقراءة فقط: {name} فتح هذا الملف. يمكنك تغيير أي شيء تريده هنا، لكن لا يمكنك الحفظ. استخدم ملف، حفظ باسم للحفظ في ملف آخر.';
$ec_lang['lpn_lock_unavailable']='تنبيه: تعذّر الوصول إلى الخادم للتحقق من قفل هذا المشروع أو إنشائه، فلا شيء يمنع زميلاً من تعديل الملف نفسه في الوقت نفسه. ستُبلَّغ إذا عاد القفل للعمل.';
$ec_lang['lpn_lock_storage_error']='تنبيه: لا يستطيع هذا الموقع حفظ سجلات القفل، فلا شيء يمنع زميلاً من تعديل الملف نفسه في الوقت نفسه. هذا خلل في إعداد الخادم، وليس شيئاً يمكنك إصلاحه هنا — مجلد القفل غير قابل للكتابة من قبل خادم الويب.';
$ec_lang['lpn_lock_full_error']='تنبيه: نفدت مساحة هذا الموقع لتسجيل من فتح أي مشروع، فلا شيء يمنع زميلاً من تعديل الملف نفسه في الوقت نفسه. هذا خلل في إعداد الخادم، وليس شيئاً يمكنك إصلاحه هنا.';
$ec_lang['lpn_lock_not_asked']='لا يعمل القفل لهذا المشروع، فلا شيء يمنع زميلاً من تعديل الملف نفسه في الوقت نفسه. لم يُسجَّل بعد اسم لك في هذا المتصفح، أو ليس للمشروع معرّف — يحدّد حفظ المشروع في ملف كليهما.';
$ec_lang['lpn_lock_restored']='عاد القفل للعمل، وأصبح هذا الملف الآن لك لتحفظ فيه.';
$ec_lang['lpn_lock_dismiss']='إخفاء هذه الرسالة';
$ec_lang['lpn_file_training_1']='سيُحفظ مشروعك في ملف على هذا الجهاز. يُحفظ عندما تطلب ذلك، ولا يُحفظ في أي وقت آخر، فلا يُكتب في ذلك الملف شيء دون علمك.';
$ec_lang['lpn_file_training_2']='لكي لا يعدّل شخصان ملفاً واحداً في الوقت نفسه، يتتبّع هذا الموقع من فتحه. إذا كان شخص ما قد فتحه بالفعل، لا يزال بإمكانك فتحه ومشاهدته، أو الاحتفاظ بنسخة خاصة بك.';
$ec_lang['lpn_file_training_permission']='في أول مرة تحفظ فيها، سيسألك متصفحك عمّا إذا كان يجوز لهذا الموقع تعديل الملف. هذا السؤال يأتي من المتصفح لا منّا، والموافقة عليه هي ما يسمح لأمر الحفظ بكتابة عملك مرة أخرى في الملف. عادةً ما يُسأل مرة واحدة فقط لكل ملف.';
$ec_lang['lpn_file_training_3']='أعطِ اسماً قصيراً يعرفك به زملاؤك. الأحرف الأولى من اسمك مثالية. يمكن لأي شخص يفتح الملف نفسه أن يرى هذا، فلا تستخدم أي معلومة خاصة.';
$ec_lang['lpn_file_training_name']='الأحرف الأولى من اسمك';
$ec_lang['lpn_file_training_continue']='متابعة';
$ec_lang['lpn_file_relink']='اختيار الملف مرة أخرى';
$ec_lang['lpn_file_reconnect']='إعادة الاتصال بهذا الملف';
$ec_lang['lpn_file_reconnect_prompt']='جاء هذا المشروع من {file}. يحتاج متصفحك إلى إذنك مرة أخرى قبل أن يتمكن من الكتابة فيه. أعد الاتصال أدناه.';
$ec_lang['lpn_saveas_same_file']='هذا هو الملف نفسه الذي فتحه شخص آخر، فلا يمكن الكتابة فوقه. اختر ملفاً آخر أو اسماً آخر.';
$ec_lang['lpn_saveas_overwrites_project']='يحتوي ذلك الملف بالفعل على مشروع مختلف، {name}. سيؤدي الحفظ هنا إلى استبداله بالكامل. هل تريد المتابعة؟';
$ec_lang['lpn_saveas_overwrites_newer']='تغيّر ذلك الملف منذ آخر مرة رأيته فيها، فمن شبه المؤكد أن شخصاً آخر حفظ فيه. سيؤدي الحفظ هنا إلى استبدال نسخته بنسختك. هل تريد المتابعة؟';
$ec_lang['lpn_prompt_project_name']='اسم لهذا المشروع';
$ec_lang['lpn_status_closed_opened']='تم إغلاق {closed}. يُعرض الآن {opened}.';
$ec_lang['lpn_status_closed_empty']='تم إغلاق {closed}. بدأ مشروع فارغ جديد.';
$ec_lang['lpn_storage_full']='لم يُحفظ. تخزين المتصفح ممتلئ أو غير متاح، لذا ستُفقد تغييراتك الأخيرة عند إغلاق هذا التبويب.';
$ec_lang['lpn_notes_1_term']='الحالة المستقرة';
$ec_lang['lpn_notes_1_def']='تحل مجموعة واحدة من الطلبات في كل مرة، باستخدام خوارزمية التدرج الشامل نفسها التي يستخدمها EPANET. لا تُحاكي كيف تتغير الشبكة مع مرور الوقت.';
$ec_lang['lpn_notes_2_term']='غير مُحاكى';
$ec_lang['lpn_notes_2_def']='لا تُحاكى الصهاريج ولا جودة المياه ولا صمامات التحكم التي تفتح وتغلق من تلقاء نفسها (PRV وPSV وFCV). يمكن للأنبوب أن يحمل فاقداً موضعياً ثابتاً، لكن ليس صماماً تعتمد حالة فتحه أو إغلاقه على التدفق قيد الحل.';
$ec_lang['lpn_notes_3_term']='حفظ المشاريع';
$ec_lang['lpn_notes_3_def']='كل مشروع هو تبويب، وكل تبويب يُحفظ في هذا المتصفح أثناء عملك. يؤدي مسح بيانات متصفحك إلى حذفها جميعاً، فاحتفظ بعملك في ملف: ملف، حفظ باسم. تعني علامة النجمة على تبويب أنه يحمل تغييرات غير موجودة في ملف. لا يُكتب شيء في ملف أبداً ما لم تطلب ذلك. في بعض المتصفحات يتصل المشروع بالملف الذي تحفظه فيه، ويكتب أمر ملف، حفظ في ذلك الملف نفسه من حينها؛ وفي متصفحات أخرى لا يمكن الاتصال، فيكون الحفظ معطّلاً ولا يتوفر إلا حفظ باسم. عندما يُحفظ ملف مشروع على قرص مشترك، تخبرك هذه الصفحة إذا كان زميل قد فتحه بالفعل، حتى لا يكتب شخصان فوق عمل بعضهما.';
$ec_lang['lpn_notes_5_term']='منحنى المضخة';
$ec_lang['lpn_notes_5_def']='تتبع المضخة العلاقة H = H₀ − aQ^b، حيث H هو العلو الذي تضيفه المضخة وQ هو التدفق خلالها. أدخل نقطة واحدة أو نقطتين أو ثلاث نقاط من منحنى الشركة المصنعة. النقاط الثلاث — العلو عند تدفق صفري، ونقطة التشغيل العادية، ونقطة أعلى تدفق — توائم H₀ وa وb مباشرة، وتتبع المنحنى المنشور عن كثب. توائم النقطتان قطعاً مكافئاً (b = 2) قمته عند تدفق صفري. تستخدم النقطة الواحدة قاعدة شائعة: العلو عند تدفق صفري يساوي 1.33 × العلو الذي تُدخله، وأعلى تدفق يساوي 2 × التدفق الذي تُدخله، مما يعطي أيضاً b = 2. المضخة التي لا تُدخل لها أي نقاط لا تضيف أي علو على الإطلاق. لا يُقطع المنحنى عند وصول العلو إلى الصفر، لذا فإن طلب تدفق من مضخة أكبر مما يستطيع منحناها تقديمه يعطي علواً سالباً. الحل هو مضخة أكبر أو طلب أصغر، لا موائمة منحنى مختلفة.';
$ec_lang['lpn_notes_4_term']='إضافات مخطط لها';
$ec_lang['lpn_notes_4_def']='سيناريوهات، بحيث يحمل المشروع الواحد عدة مجموعات من الطلبات. جداول لنتائج العقد والأنابيب. كتابة ملفات EPANET .inp، بحيث يمكن للمشروع أن يعود إلى EPANET. التعليقات والاقتراحات مرحّب بها دائماً (انظر رابط الملاحظات أعلاه).';
$ec_lang['lpn_notes_epanet_term']='ثوابت هيزن-وليامز تطابق EPANET';
$ec_lang['lpn_notes_epanet_def']='في أغسطس 2026 غُيِّر معامل هيزن-وليامز وأسّه ليطابقا EPANET. تختلف نتائج فقدان الضغط عن الإصدارات السابقة من هذه الصفحة بنسبة تصل إلى 0.1 بالمئة، وهو أصغر بكثير من عدم اليقين في قيمة C نفسها.';
$ec_lang['lpn_id_invalid']='أدخل معرّفاً بلا مسافات وبلا علامات اقتباس.';
$ec_lang['lpn_id_taken']='ذلك المعرّف قيد الاستخدام بالفعل.';
$ec_lang['lpn_diag_no_fixed_head']='أضف خزاناً. تحتاج الشبكة إلى منسوب مائي معروف واحد على الأقل قبل أن يمكن حلها.';
$ec_lang['lpn_diag_dangling_link']='يتصل أنبوب أو مضخة بعقدة لم تعد موجودة:';
$ec_lang['lpn_diag_unreachable']='لا يوجد مسار من هذه العقد إلى أي خزان:';
$ec_lang['lpn_diag_not_converged']='لم يُعثر على حل. تحقق من وجود قيم مستحيلة في الواقع، مثل قطر يساوي صفراً.';
$ec_lang['lpn_field_roughness']='الخشونة';
$ec_lang['lpn_field_roughness_tip']='معامل هيزن-وليامز C. كلما زاد الرقم كان الأنبوب أملس: نحو 150 للبلاستيك الجديد، و130 للفولاذ أو الحديد الجديد، و100 للأنبوب القديم.';
$ec_lang['lpn_field_length']='الطول';
$ec_lang['lpn_field_length_tip']='طول الأنبوب. عند تفعيل تلقائي، يُقاس الطول مما رسمته. أوقف تلقائي لكتابة طول مختلف عن الرسم.';
$ec_lang['lpn_field_km']='معامل الفاقد الموضعي، k';
$ec_lang['lpn_field_km_tip']='الفاقد من الانحناءات والصمامات والوصلات على هذا الأنبوب، ويُحتسب كمضاعف لعلو السرعة. استخدم 0 لأنبوب مستقيم بسيط.';
$ec_lang['lpn_field_km_short']='الفاقد الموضعي، k';
$ec_lang['lpn_pump_curve_source']='مصدر المنحنى';
$ec_lang['lpn_pump_curve_own']='أدخل النقاط أدناه';
$ec_lang['lpn_pump_curve_ref_note']='يُستخدم المنحنى المُدخل للمضخة {id}.';
$ec_lang['lpn_pump_curve_note']='نقطة واحدة أو نقطتان أو ثلاث نقاط — انظر “منحنى المضخة” في الملاحظات أدناه.';
$ec_lang['lpn_pump_point1']='النقطة 1 (مطلوبة)';
$ec_lang['lpn_pump_point2']='النقطة 2 (اختيارية)';
$ec_lang['lpn_pump_point3']='النقطة 3 (اختيارية)';
$ec_lang['lpn_mode_select']='الوضع: تحديد. انقر عنصراً أو تسمية لعرضه أو تغييره. اسحب لتحريك عقدة أو نقطة انعطاف أو تسمية. انقر نقراً مزدوجاً على أنبوب لإضافة نقطة انعطاف أو إزالتها.';
$ec_lang['lpn_mode_delete']='الوضع: حذف. انقر عنصراً لإزالته.';
$ec_lang['lpn_mode_add_junction']='الوضع: إضافة ملتقى. انقر على الخريطة لوضع ملتقى. انتقل إلى وضع التحديد لتغيير العناصر والتسميات أو تحريكها.';
$ec_lang['lpn_mode_add_reservoir']='الوضع: إضافة خزان. انقر على الخريطة لوضع خزان. انتقل إلى وضع التحديد لتغيير العناصر والتسميات أو تحريكها.';
$ec_lang['lpn_mode_add_pipe']='الوضع: إضافة أنبوب. انقر عقدة، ثم عقدة أخرى، لتوصيلهما. انتقل إلى وضع التحديد لتغيير العناصر والتسميات أو تحريكها.';
$ec_lang['lpn_mode_add_pump']='الوضع: إضافة مضخة. انقر عقدة، ثم عقدة أخرى، لتوصيلهما. انتقل إلى وضع التحديد لتغيير العناصر والتسميات أو تحريكها.';
$ec_lang['lpn_mode_add_text']='الوضع: إضافة نص. انقر على الخريطة لوضع تسمية نصية. انقر بالقرب من عقدة لإلحاق النص بتلك العقدة. انتقل إلى وضع التحديد لتغيير العناصر والتسميات أو تحريكها.';
$ec_lang['lpn_tip_select']='استخدم هذا الوضع لتغيير الأشياء على الخريطة وتحريكها وسحبها.';
$ec_lang['lpn_tip_labels_draggable']='يمكنك سحب تسمية لتحريكها. انقر نقراً مزدوجاً على تسمية لإعادتها إلى موضعها التلقائي.';
$ec_lang['lpn_field_auto']='تلقائي';
$ec_lang['lpn_field_x']='X';
$ec_lang['lpn_field_y']='Y';
$ec_lang['lpn_field_text_size']='مضاعف الحجم';
$ec_lang['lpn_tool_labels']='التسميات';
$ec_lang['lpn_labels_heading_node']='تسميات العقد';
$ec_lang['lpn_labels_heading_link']='تسميات الوصلات';
$ec_lang['lpn_labels_decimals_tip']='عدد الخانات العشرية المعروضة لهذه التسمية';
$ec_lang['lpn_labels_mark_extrema']='تمييز أعلى القيم وأدناها';
$ec_lang['lpn_field_id']='المعرّف';
$ec_lang['lpn_backdrop_menu']='صورة خلفية…';
$ec_lang['lpn_backdrop_add']='إضافة صورة';
$ec_lang['lpn_backdrop_scale']='ضبط مقياس الصورة';
$ec_lang['lpn_backdrop_position']='تحريك الصورة';
$ec_lang['lpn_backdrop_remove']='إزالة الصورة';
$ec_lang['lpn_backdrop_remove_confirm']='هل تريد إزالة الصورة الخلفية؟';
$ec_lang['lpn_backdrop_scale_prompt1']='انقر نقطتين على الصورة الخلفية، مثل طرفي مقياس رسم. ثم اكتب المسافة الحقيقية بينهما.';
$ec_lang['lpn_backdrop_scale_prompt2']='المسافة الحقيقية بين النقطتين';
$ec_lang['lpn_backdrop_position_prompt1']='انقر أي نقطة على الصورة الخلفية. هذه هي النقطة التي ستحرّكها.';
$ec_lang['lpn_backdrop_position_prompt2']='اختر أين يجب أن تذهب تلك النقطة، ثم انقر متابعة.';
$ec_lang['lpn_backdrop_target_label']='حرّك تلك النقطة إلى:';
$ec_lang['lpn_backdrop_target_node']='عقدة';
$ec_lang['lpn_backdrop_target_free']='أي نقطة على الخريطة';
$ec_lang['lpn_backdrop_target_coords']='إحداثيات تكتبها';
$ec_lang['lpn_backdrop_coords_prompt']='اكتب الإحداثيات X,Y التي يجب أن تنتقل إليها تلك النقطة';
$ec_lang['lpn_backdrop_continue']='متابعة';
$ec_lang['lpn_tool_settings']='الإعدادات';
$ec_lang['lpn_settings_scope_project']='إعدادات المشروع';
$ec_lang['lpn_settings_scope_calculator']='إعدادات الحاسبة';
$ec_lang['lpn_settings_show_titles']='إظهار عناوين الصفحة';
$ec_lang['lpn_settings_show_titles_tip']='يخفي عنوان الصفحة وسطر الترحيب فوق الرسم، لتحصل الخريطة على مساحة أكبر. لا تتغيّر عملية الطباعة.';
$ec_lang['lpn_settings_id_prefixes']='بادئات المعرّفات';
$ec_lang['lpn_settings_defaults']='القيم الابتدائية';
$ec_lang['lpn_settings_defaults_note']='تُستخدم للعناصر التي تنشئها من الآن فصاعداً. لا تتغيّر العناصر الموجودة.';
$ec_lang['lpn_settings_push_note']='تُطبَّق فقط الخصائص التي تظهر تسمياتها الآن.';
$ec_lang['lpn_settings_push_btn']='تطبيق القيم الابتدائية على جميع العناصر';
$ec_lang['lpn_push_confirm']='هل تريد استبدال هذه الخصائص في كل عنصر موجود بالقيم الابتدائية الحالية؟ ستُكتب القيم التي أدخلتها فوقها. يمكنك التراجع عن هذا.';
$ec_lang['lpn_push_properties']='الخصائص:';
$ec_lang['lpn_push_elements']='العقد والأنابيب:';
$ec_lang['lpn_push_none_displayed']='لا تظهر أي قيمة ابتدائية كتسمية الآن، فلا يوجد ما يُطبَّق. فعّل تسميات الخصائص التي تريدها في لوحة التسميات، ثم حاول مرة أخرى.';
$ec_lang['lpn_push_nothing']='لا يحمل أي عنصر موجود أياً من الخصائص التي يجري تطبيقها.';
$ec_lang['lpn_push_no_change']='يحمل كل عنصر هذه القيم بالفعل، فلن يتغيّر شيء.';
$ec_lang['lpn_settings_emitter_exponent']='أسّ الرشاش';
$ec_lang['lpn_settings_computation']='الحساب';
$ec_lang['lpn_settings_tolerance']='سماحية التقارب';
$ec_lang['lpn_settings_tolerance_tip']='مدى القرب الذي يجب أن يصل إليه الحلّال قبل أن يتوقف. الرقم الأصغر أكثر دقة ويستغرق وقتاً أطول.';
$ec_lang['lpn_settings_engine_epanet']='الحل بمحرك EPANET';
$ec_lang['lpn_settings_engine_epanet_tip']='يشغّل محرك EPANET الأصلي من وكالة حماية البيئة الأمريكية، هنا في متصفحك. يعطي الحلّال المدمج النتائج نفسها وهو أسرع، فاترك هذا الخيار متوقفاً ما لم تحتج إلى EPANET نفسه.';
$ec_lang['lpn_engine_loading']='جارٍ تحميل محرك EPANET…';
$ec_lang['lpn_engine_failed']='تعذّر تحميل محرك EPANET. يُعرض الحلّال المدمج بدلاً منه.';
$ec_lang['lpn_engine_manning_note']='ملاحظة: مع خشونة مانينج، يحسب EPANET فقدان الضغط أقل بنحو 0.6٪ من الحلّال المدمج.';
$ec_lang['lpn_settings_text_size']='حجم النص';
$ec_lang['lpn_settings_text_size_map']='مسافة الخريطة';
$ec_lang['lpn_settings_text_size_screen']='بكسلات الشاشة';
$ec_lang['lpn_settings_symbol_size']='حجم الرمز (نسبةً إلى النص)';
$ec_lang['lpn_settings_symbol_opacity']='عتامة الرمز (0 إلى 1)';
$ec_lang['lpn_settings_backdrop_opacity']='عتامة الصورة الخلفية (0 إلى 1)';
$ec_lang['lpn_settings_text_size_units']='وحدات حجم النص';
$ec_lang['lpn_settings_map_display']='مظهر الخريطة';
$ec_lang['lpn_settings_map_height_px']='ارتفاع الخريطة (بكسلات الشاشة)';
$ec_lang['lpn_settings_map_height_tip']='على الشاشة الصغيرة تُرسم الخريطة أقصر من هذا، ليبقى دائماً جزء من الصفحة قابلاً للتمرير.';
$ec_lang['lpn_settings_legend_position']='موضع مفتاح الرموز';
$ec_lang['lpn_settings_legend_top_left']='أعلى اليسار';
$ec_lang['lpn_settings_legend_top_right']='أعلى اليمين';
$ec_lang['lpn_settings_legend_middle_left']='منتصف اليسار';
$ec_lang['lpn_settings_legend_middle_right']='منتصف اليمين';
$ec_lang['lpn_settings_legend_bottom_left']='أسفل اليسار';
$ec_lang['lpn_settings_legend_bottom_right']='أسفل اليمين';
$ec_lang['lpn_confirm_restore_defaults']='هل تريد إعادة ضبط كل الإعدادات (بادئات المعرّفات، والقيم الابتدائية، وإعدادات الحلّال، ومظهر الخريطة، وموضع مفتاح الرموز، والتسميات الظاهرة) إلى قيمها الأصلية؟ لا تتغيّر شبكتك. الإعدادات تخص المشروع المفتوح، فتحتفظ مشاريعك الأخرى بإعداداتها الخاصة.';
$ec_lang['lpn_settings_wipe_btn']='محو كل شيء في هذه الصفحة';
$ec_lang['lpn_confirm_wipe']='هل تريد حذف كل شيء محفوظ لهذه الصفحة — كل مشروع، وكل صورة خلفية، وكل الإعدادات، واختياراتك للوحدات — وإعادة تحميل الصفحة كما يراها زائر جديد تماماً؟ لا يمكن التراجع عن هذا.';
