<?php

// àáèéìíòóùú — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="frazione";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% pendenza";
$ec_lang['u_grade']="pendenza";
$ec_lang['u_in2']="poll^2";
$ec_lang['u_inh2o']="poll H2O";
$ec_lang['u_in']="poll";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="L/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="ML/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/ft^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="s";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="poll/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Calcolatori HawsEDC';
$ec_lang['menu_main_list']='Elenco calcolatori';
$ec_lang['menu_main_hydraulics']='Idraulica';
$ec_lang['menu_main_language']='Lingua';
$ec_lang['menu_more']='Altro';
$ec_lang['template_welcome']='>> Lasciate le paure alla porta; qui l\'amore è la nostra lingua. Non state rovinando tutto. Godetevi anche gli <a target="_blank" href="https://hawsedc.com/download.php">strumenti gratuiti HawsEDC per AutoCAD.</a> <<';
$ec_lang['template_translation_help']='Hai una grande visione per una calcolatrice da aggiungere qui?  Puoi aiutarmi a migliorare le traduzioni, programmare o ospitare questi calcolatori?  ';
$ec_lang['template_feedback']='Condividi le tue preziose opinioni o suggerimenti. Questo calcolatore gratuito ha superato le tue aspettative in ogni modo?';
$ec_lang['template_printable_title']='Titolo stampabile';
$ec_lang['template_printable_subtitle']='Sottotitolo stampabile';
$ec_lang['index_title']='Calcolatori ingegneristici gratuiti online';
$ec_lang['calc_set_units']='Imposta unità:';
$ec_lang['calc_defaults']='Valori predefiniti';
$ec_lang['calc_defaults_confirm']='Ripristinare il calcolatore ai valori predefiniti originali?';
$ec_lang['points_data_help']='(o Copia/Incolla usando l\'area dati)';
$ec_lang['points_data_title']='Dati punti<br />(separati da virgola o tabulazione)';
$ec_lang['points_data_copy']='Copia';
$ec_lang['points_data_paste']='Incolla';
$ec_lang['calc_inputs']='Dati di input';
$ec_lang['calc_results']='Risultati';
$ec_lang['view_hide_line']='[Nascondi questa riga]';
$ec_lang['view_printable']='Versione stampabile (ricaricare per ripristinare)';
$ec_lang['ec_name_label']='Salva questo calcolo:';
$ec_lang['ec_name_placeholder']='Nome';
$ec_lang['ec_name_hint']='Salva questi dati inseriti nell\'URL per segnalibri, recupero della cronologia e condivisione';
$ec_lang['calc_copy_link']='Copia collegamento';
$ec_lang['ec_related_calcs']='Calcolatori correlati:';
$ec_lang['calc_copy_link_done']='Copiato!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Perdita di carico Darcy-Weisbach';
$ec_lang['dw_main_title']='Calcolatore gratuito online perdita di carico Darcy-Weisbach';
$ec_lang['dw_main_desc']='Perdita di carico in tubazione con Darcy-Weisbach a diametro, scabrezza e portata dati';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Altezza di scabrezza assoluta, e, della parete della tubazione. Valori tipici: acciaio (nuovo) 0,046 mm, acciaio (usato) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, calcestruzzo 0,3–3 mm.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s per acqua pulita a 20°C">Viscosità cinematica, &nu; <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Viscosità cinematica, &nu;';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s per acqua pulita a 20°C';
$ec_lang['dw_reynolds_number']='Numero di Reynolds, Re';
$ec_lang['dw_flow_regime']='Regime di flusso';
$ec_lang['dw_regime_laminar']='laminare';
$ec_lang['dw_regime_transitional']='di transizione';
$ec_lang['dw_regime_turbulent']='turbolento';
$ec_lang['dw_friction_factor_method']='Metodo del fattore di attrito';
$ec_lang['dw_friction_factor']='Fattore di attrito, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Perdita di carico Hazen-Williams';
$ec_lang['hw_main_title']='Calcolatore gratuito online perdita di carico Hazen-Williams';
$ec_lang['hw_main_desc']='Perdita di carico in tubazione con Hazen-Williams a diametro, scabrezza e portata dati';
$ec_lang['hw_hgl_1']='HGL a valle';
$ec_lang['hw_hgl_2']='HGL a monte';
$ec_lang['hw_roughness']='Coefficiente Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canale irregolare Manning';
$ec_lang['mi_main_title']='Calcolatore gratuito online di Manning per canale a sezione irregolare';
$ec_lang['mi_main_desc']='Calcolatore flusso uniforme di Manning per canale a sezione irregolare';
$ec_lang['mi_waterSurfaceElevation']='Quota pelo libero';
$ec_lang['mi_q_617']='<span class="ec-help" title="La portata composita, Q, usando un n composto per ciascuna regione secondo Chow 6-17, velocità uguali">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Punti sezione trasversale';
$ec_lang['mi_groupPoint']='Punto';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_groupRegion']='Regione';
$ec_lang['mi_station']='Prog.';
$ec_lang['mi_elevation']='Quota';
$ec_lang['mi_d50in']='Diam.<br />mediano<br />rivestim.';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />confine<br />regione<br />(Sponda)';
$ec_lang['mi_tau']='Tensione<br />tang.<br />di fondo<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n com-<br />posto';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='n composto';
$ec_lang['mi_notes_1_def']='Questo calcolatore segue il manuale di riferimento HEC-RAS nel calcolo del n composto della regione usando Chow 1959, pagina 136, equazione 6-17 (non 6-18).';
$ec_lang['mi_notes_2_term']='Rivestimento in roccia';
$ec_lang['mi_notes_2_def']='Usare il Calcolatore Canale Trapezoidale Manning per progettare il rivestimento in roccia. Questo calcolatore è più adatto per sezioni naturali.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Portata in tubazione Manning';
$ec_lang['mpf_main_title']='Calcolatore gratuito online portata in tubazione Manning';
$ec_lang['mpf_main_desc']='Formula di Manning per flusso uniforme in tubazione a pendenza e profondità date';
$ec_lang['mpf_spreadheet_notice']='Foglio di calcolo Portata in tubazione Manning';
$ec_lang['mpf_pipe_diameter']='Diametro tubazione, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Scabrezza di Manning, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Pendenza di attrito, S<sub>f</sub></a><span class="ec-help" title="Talvolta uguale alla pendenza della tubazione. Segui il link per la spiegazione (solo in inglese)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Rapporto di riempimento, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Portata, Q';
$ec_lang['mpf_flow_tip']='Portata e profondità calcolate per una tubazione infinitamente lunga. Per immettere questa portata nella tubazione può essere necessaria un\'altezza idraulica a monte maggiore. Vedere le Note sotto per i dettagli e un video tutorial.';
$ec_lang['mpf_velocity']='Velocità, v';
$ec_lang['mpf_velocity_head']='Altezza cinetica, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Area bagnata, A';
$ec_lang['mpf_pipe_area']='Area tubazione, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Area relativa, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Perimetro bagnato, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Raggio idraulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Larghezza pelo libero, T';
$ec_lang['mpf_froude_number']='Numero di Froude, Fr';
$ec_lang['mpf_shear_stress']='Tensione tangenziale media, &tau;';
$ec_lang['mpf_full_flow']='Portata a sezione piena, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Rapporto alla portata piena, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Questa è la portata e la profondità all\'interno di una tubazione <em>infinitamente lunga</em>.</dt><dd>L\'immissione della portata nella tubazione può richiedere un\'altezza idraulica significativamente maggiore. Aggiungere almeno 1,5 volte l\'altezza cinetica per l\'altezza idraulica o <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">vedere il tutorial di 2 minuti</a> per i calcoli standard del livello idraulico nei tombini con HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Calcola y/d<sub>0</sub> dato Q';
$ec_lang['mpf_solve_desc']='Usando d<sub>0</sub>, n e S<sub>f</sub> dal modulo, trova il minimo y/d<sub>0</sub> per un dato Q.';
$ec_lang['mpf_solve_button']='Calcola';
$ec_lang['mpf_solver_enter_positive_q']='Inserire un valore positivo per Q.';
$ec_lang['mpf_solver_no_solution']='Nessuna soluzione: Q supera la capacità della tubazione a y/d0 = 93.8% (Qmax = {qmax} nelle unità selezionate).';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Perdita di carico in tubazione Manning';
$ec_lang['mphl_main_title']='Calcolatore gratuito online perdita di carico in tubazione Manning';
$ec_lang['mphl_main_desc']='Formula di Manning perdita di carico a portata piena data';
$ec_lang['mphl_pipe_length']='Lunghezza, L';
$ec_lang['mphl_area']='Area, A';
$ec_lang['mphl_total_junction_k']='Coefficiente di perdita di carico concentrata, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Coefficiente di perdita, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Perdita di carico (localizzata) concentrata, k<sub>m</sub>. Queste perdite si verificano in corrispondenza di giunti di tubazione, imbocchi, sbocchi, curve e valvole — il termine "concentrata" indica che la perdita è localizzata in un punto, non che sia piccola; in un tratto corto possono eguagliare o superare le perdite per attrito. Valori tipici di k: imbocco a spigolo vivo 0,5, ogni curva a 45° 0,2–0,3, valvola a saracinesca (tutta aperta) 0,1, valvola a farfalla 0,2, sbocco (verso serbatoio o atmosfera) 1,0. Sommare tutti i raccordi per ottenere il k<sub>m</sub> totale. Il valore predefinito 2,0 presuppone un imbocco, uno sbocco e due curve a 45°.';
$ec_lang['mphl_friction_slope']='Pendenza di attrito';
$ec_lang['mphl_friction_loss']='Perdita di carico distribuita, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Perdita di carico concentrata, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Perdita di carico totale, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='EGL a valle';
$ec_lang['mphl_egl_2']='EGL a monte';
$ec_lang['mphl_hgl_egl_tip']='Potrebbe non essere valido se la tubazione è in rilievo. Vedere le note.';
$ec_lang['mphl_note_1']='<dl><dt>Questo calcolatore non tiene conto della quota della tubazione.</dt><dd>Se l\'HGL scende sotto la sommità della tubazione in un qualsiasi punto, questo calcolo potrebbe non essere valido.</dd><dt>Per una condizione di imbocco aperto (tombino), è necessario verificare le condizioni di controllo all\'imbocco.</dt><dd>1. L\'HGL a monte non può essere inferiore alla quota di deflusso a profondità normale a monte (o inferiore alla tubazione!).</dd><dd>2. Il livello idraulico di un tombino è meglio rappresentato dall\'EGL a monte che dall\'HGL a monte.</dd><dd>3. <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">Vedere il tutorial di 2 minuti</a> per semplici calcoli standard del livello idraulico nei tombini con HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canale trapezoidale Manning';
$ec_lang['mtc_main_title']='Calcolatore gratuito online formula di Manning canale trapezoidale';
$ec_lang['mtc_main_desc']='Flusso uniforme Manning in canale trapezoidale a pendenza e profondità date';
$ec_lang['mtc_bottom_width']='Larghezza di fondo, b';
$ec_lang['mtc_side_slope_1']='Scarpata lato 1, z<sub>1</sub> (orizz./vert.)';
$ec_lang['mtc_side_slope_2']='Scarpata lato 2, z<sub>2</sub> (orizz./vert.)';
$ec_lang['mtc_channel_slope']='Pendenza canale, S';
$ec_lang['mtc_flow_depth']='Profondità di flusso, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Angolo di curva, β</a><span class="ec-help" title="Per dimensionamento massi. Segui il link per lo schema."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Tipicamente &asymp; 2,65 per roccia frantumata">Peso specifico relativo della roccia, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Dimensione roccia di progetto, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n per dimensione roccia di progetto secondo Strickler';
$ec_lang['mtc_n_blodgett']='n per dimensione roccia di progetto secondo Blodgett';
$ec_lang['mtc_n_bathurst']='n per dimensione roccia di progetto secondo Bathurst';
$ec_lang['mtc_n_pi']='n per dimensione roccia di progetto secondo Phillips & Ingersoll';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett contro Bathurst';
$ec_lang['mtc_pi_range_check']='Verifica intervallo P&I';
$ec_lang['mtc_pi_ok']='d50 nell\'intervallo P&I';
$ec_lang['mtc_pi_ok_tip']='0,28–0,36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='Fuori intervallo';
$ec_lang['mtc_pi_tip']='Estrapolazione oltre l\'intervallo di dati 0,28–0,36 ft su cui questa equazione è stata sviluppata: da considerare come verifica indicativa, non come base di progetto';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Secondo Isbash (1936) e Maricopa County, Arizona, US.">Dimensione roccia angolare richiesta sul fondo, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Secondo Isbash (1936) e Maricopa County, Arizona, US.">Dimensione roccia angolare richiesta scarpata 1, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Secondo Isbash (1936) e Maricopa County, Arizona, US.">Dimensione roccia angolare richiesta scarpata 2, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Dimensione roccia angolare richiesta, D<sub>50</sub> (Maynord, Ruff, e Abt 1989)';
$ec_lang['mtc_d50_searcy']='Dimensione roccia angolare richiesta, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='Velocità ragionevole per le ipotesi di flusso uniforme.';
$ec_lang['mtc_vel_low']='Velocità bassa — rischio di sedimentazione.';
$ec_lang['mtc_iteration_tip']='Scegliere un\'opzione di scabrezza (Blodgett-Bathurst raccomandato) e un\'opzione di dimensione roccia (Isbash raccomandato) per iterare automaticamente verso una dimensione roccia uniforme per la portata desiderata. Vedere le Note sotto per il metodo completo, oppure inserire un proprio valore di scabrezza (seguire il link per indicazioni) e ignorare la dimensione roccia per saltare l\'iterazione.';
$ec_lang['mtc_note_1']='<dl><dt>Iterazione automatica dimensionamento roccia e scabrezza</dt><dd>Scegliere un pulsante radio per la scabrezza (Blodgett-Bathurst raccomandato) e uno per la dimensione roccia di progetto (Isbash raccomandato). Regolare profondità e fattore di sicurezza della roccia per ottenere la portata desiderata con una dimensione roccia uniforme. Ogni modifica ai dati avvia il ciclo iterativo: 1. La scabrezza viene calcolata dalla dimensione roccia di progetto. 2. La scabrezza richiesta viene copiata nella scabrezza di input. 3. La portata nel canale e la dimensione roccia richiesta vengono calcolati. 4. La dimensione roccia di progetto viene aggiornata. 5. Si ripete fino a convergenza.</dd><dt>Calcolatore base (senza iterazione)</dt><dd>Inserire il valore di scabrezza desiderato. Ignorare l\'area di input della dimensione roccia di progetto.</dd></dl>';
$ec_lang['mtc_note_2_term']='Controllo della velocità';
$ec_lang['mtc_note_2_def']='Velocità elevata implica elevata energia specifica derivante da una caduta disponibile. Tale energia può dissiparsi rapidamente in corrispondenza di espansioni, curve o ostruzioni. Verificare che ciò sia ragionevole per il sito.';
$ec_lang['mtc_solve_for_y']='Calcola la profondità, y, dato Q';
$ec_lang['mtc_solve_desc']='Utilizzando b, z<sub>1</sub>, z<sub>2</sub>, S e n dal modulo del calcolatore, determina la profondità per un dato Q.';
$ec_lang['mtc_solver_no_solution']='Nessuna soluzione trovata per il Q indicato con questi dati del canale.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Stramazzo semplice';
$ec_lang['ws_main_title']='Calcolatore gratuito online del deflusso su stramazzo semplice a soglia larga';
$ec_lang['ws_main_desc']='Calcolatore del deflusso su stramazzo semplice a soglia larga';
$ec_lang['ws_weirLength']='Lunghezza dello stramazzo, L';
$ec_lang['ws_headWaterHeight']='Carico, h';
$ec_lang['ws_weirCoefficient']='Coefficiente dello stramazzo, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Note';
$ec_lang['ws_notes_we_term']='Equazione dello stramazzo';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Stramazzo irregolare';
$ec_lang['wi_main_title']='Calcolatore gratuito online del deflusso su stramazzo irregolare, segmentato, a profondità variabile';
$ec_lang['wi_main_desc']='Calcolatore del deflusso su stramazzo irregolare';
$ec_lang['wi_weirPoints']='Punti dello stramazzo';
$ec_lang['wi_pondingHeight']='Altezza di invaso';
$ec_lang['wi_incrementalFlow']='Portata incrementale';
$ec_lang['wi_cumulativeFlow']='Portata cumulativa';
$ec_lang['wi_save_and_calculate']='Salva e calcola';
$ec_lang['wi_notes_we_def']='q = se (length = 0) allora 0 altrimenti se (slope=0) allora cw*length*d<sub>0</sub><sup>1.5</sup> altrimenti cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) dove d<sub>1</sub> e d<sub>0</sub> sono sempre positivi o zero';
// Orifice Flow
$ec_lang['or_main_menu']='Deflusso a orifizio';
$ec_lang['or_main_title']='Calcolatore gratuito online del deflusso a orifizio';
$ec_lang['or_main_desc']='Deflusso a orifizio — libero o sommerso';
$ec_lang['or_shape']='Forma dell\'apertura';
$ec_lang['or_shape_circular']='Circolare';
$ec_lang['or_shape_rectangular']='Rettangolare';
$ec_lang['or_diameter']='<span class="ec-help" title="Diametro per forma circolare; altezza per forma rettangolare">Diametro o altezza, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Solo per aperture rettangolari">Larghezza, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Parte inferiore dell\'apertura">Quota di fondo <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Quota pelo libero a monte';
$ec_lang['or_twe']='Quota pelo libero a valle';
$ec_lang['or_cd']='Coefficiente di efflusso, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Quota del centroide';
$ec_lang['or_head']='Carico efficace, h';
$ec_lang['or_area']='Area dell\'apertura, A';
$ec_lang['or_regime']='Verifica del regime di orifizio';
$ec_lang['or_regime_valid']='Scarico libero';
$ec_lang['or_regime_submerged']='Orifizio sommerso';
$ec_lang['or_regime_submerged_tip']='TWE sopra il centroide — il regime di orifizio resta valido';
$ec_lang['or_regime_warn']='Fuori dal regime di orifizio';
$ec_lang['or_regime_warn_tip']='Pelo libero a monte sotto la sommità dell\'apertura';
$ec_lang['or_regime_twe_above_hwe']='Verificare i dati';
$ec_lang['or_regime_twe_above_hwe_tip']='Pelo libero a valle (TWE) sopra il pelo libero a monte (HWE)';
$ec_lang['or_notes_1_term']='Equazione dell\'orifizio';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Per scarico libero: h = HWE &minus; centroide. Per deflusso sommerso (TWE sopra la quota di fondo): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regime di orifizio';
$ec_lang['or_notes_2_def']='Le equazioni del deflusso a orifizio si applicano quando il pelo libero a monte è sopra la sommità (il punto più alto) dell\'apertura. Quando il pelo libero a monte è sotto la sommità, utilizzare invece un\'equazione di stramazzo.';
$ec_lang['or_notes_3_term']='Coefficiente di efflusso';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varia da circa 0,60 a 0,65 per orifizi a spigolo vivo. Imbocchi arrotondati o rientranti richiedono valori diversi. Vedere <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> o il Manuale di Riferimento Idraulico HEC-RAS per maggiori indicazioni.';
$ec_lang['or_notes_4_term']='Sommersione';
$ec_lang['or_notes_4_def']='Quando TWE è sopra la quota di fondo dell\'apertura, questo calcolatore applica automaticamente l\'equazione dell\'orifizio sommerso usando h = HWE &minus; TWE. Quando TWE è pari o inferiore alla quota di fondo, si assume lo scarico libero e h = HWE &minus; centroide.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Idroelettrico';
$ec_lang['mhp_main_title']='Calcolatore Gratuito di Potenza Micro-Idroelettrica';
$ec_lang['mhp_main_desc']='Calcolatore di Potenza Micro-Idroelettrica ad Acqua Fluente';
$ec_lang['mhp_gross_head']='Altezza lorda, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diametro della condotta forzata, D';
$ec_lang['mhp_length']='Lunghezza, L';
$ec_lang['mhp_efficiency']='Rendimento dell\'impianto, η (0–1)';
$ec_lang['mhp_vel_check']='Verifica della velocità';
$ec_lang['mhp_hl_check']='Verifica della perdita di carico';
$ec_lang['mhp_hnet']='Altezza netta, H<sub>net</sub>';
$ec_lang['mhp_power']='Potenza prodotta, P';
$ec_lang['mhp_annual_kwh']='Energia annua al 100% di capacità';
$ec_lang['mhp_vel_low']='Velocità bassa — rischio di sedimentazione e trascinamento d\'aria.';
$ec_lang['mhp_vel_high']='Velocità elevata — verificare le perdite di transizione, l\'energia disponibile e il colpo d\'ariete.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Alto';
$ec_lang['mhp_vel_low_short']='Basso';
$ec_lang['mhp_vel_ok_tip']='La velocità è nell\'intervallo efficiente per il dimensionamento della condotta forzata.';
$ec_lang['mhp_hl_ok_tip']='Entro l\'obiettivo del 10% — economico.';
$ec_lang['mhp_hl_warn_tip']='Supera l\'obiettivo del 10%. Considerare una condotta più grande.';
$ec_lang['mhp_hl_bad_tip']='Supera l\'obiettivo del 20%. Ridimensionare la condotta.';
$ec_lang['mhp_notes_1_term']='Perdita di carico';
$ec_lang['mhp_notes_1_def']='Perdita totale nella condotta forzata h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, dove h<sub>f</sub> = f(L/D)(v²/2g) è la perdita per attrito di Darcy-Weisbach e h<sub>m</sub> = k<sub>m</sub>·v²/2g comprende imbocchi, curve e valvole. Altezza netta H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Velocità';
$ec_lang['mhp_notes_2_def']='Verificare che la velocità sia ragionevole per il dislivello disponibile e il costo della tubazione. Una velocità molto bassa può indicare un sovradimensionamento; una velocità molto alta può aumentare le perdite per attrito e il rischio di colpo d\'ariete.';
$ec_lang['mhp_notes_3_term']='Obiettivo di perdita di carico';
$ec_lang['mhp_notes_3_def']='Perdite nella condotta forzata inferiori al 10% dell\'altezza lorda sono generalmente economiche. Il compromesso ottimale tra costo della tubazione e potenza persa si attesta spesso intorno al 4–6% per i siti ad alta valorizzazione dell\'energia elettrica.';
$ec_lang['mhp_notes_6_term']='Rendimento';
$ec_lang['mhp_notes_6_def']='Il rendimento tipico dell\'impianto η varia da 0,70 a 0,85 per le turbine Pelton e cross-flow comuni negli impianti micro-idroelettrici. Usare 0,75 come stima conservativa iniziale.';
$ec_lang['mhp_notes_7_term']='Energia annua';
$ec_lang['mhp_notes_7_def']='L\'energia annua presuppone un funzionamento continuativo a portata piena (8760 ore/anno). La produzione reale sarà inferiore a causa della variazione stagionale di portata, dei tempi di fermo per manutenzione e del fattore di carico.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Tempo di svuotamento a orifizio';
$ec_lang['odt_main_title']='Calcolatore gratuito online del tempo di svuotamento a orifizio — laghetto, vasca o serbatoio';
$ec_lang['odt_main_desc']='Tempo di svuotamento a orifizio di laghetto o vasca &mdash; Metodo del volume conico';
$ec_lang['odt_h1_elev']='Quota iniziale del pelo libero';
$ec_lang['odt_a1']='Area iniziale, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Quota finale del pelo libero';
$ec_lang['odt_a0']='Area alla quota dell\'orifizio, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Interpolata dal modello conico alla quota finale">Area finale, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Verifica della quota finale';
$ec_lang['odt_h2_ok']='Quota finale sopra la sommità dell\'orifizio';
$ec_lang['odt_h2_warn']='Quota finale pari o inferiore alla sommità dell\'orifizio';
$ec_lang['odt_h2_warn_tip']='Sommità dell\'orifizio = centroide + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Diametro (circolare) o altezza (rettangolare)">D dell\'orifizio <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Solo rettangolare">Larghezza dell\'orifizio, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Tempo di svuotamento (s)';
$ec_lang['odt_t_min']='Tempo di svuotamento (min)';
$ec_lang['odt_t_hr']='Tempo di svuotamento (h)';
$ec_lang['odt_t_day']='Tempo di svuotamento (giorni)';
$ec_lang['odt_notes_1_term']='Formula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) fornisce il tempo di svuotamento dal carico H all\'orifizio. Tempo di svuotamento = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), dove H<sub>1</sub> = quota iniziale &minus; quota orifizio, H<sub>2</sub> = quota finale &minus; quota orifizio.';
$ec_lang['odt_notes_2_term']='Metodo';
$ec_lang['odt_notes_2_def']='Il metodo del volume conico modella il laghetto o la vasca come una sezione conica tra l\'area iniziale A<sub>1</sub> al pelo libero iniziale e l\'area A<sub>0</sub> alla quota del centroide dell\'orifizio. A<sub>2</sub>, l\'area del laghetto alla quota finale, è interpolata da A<sub>1</sub> e A<sub>0</sub> usando il modello della sezione conica. Il tempo di svuotamento dalla quota iniziale alla finale equivale al tempo totale di svuotamento da H<sub>1</sub> all\'orifizio meno il tempo di svuotamento rimanente da H<sub>2</sub> all\'orifizio.';
$ec_lang['odt_h1']='<span class="ec-help" title="Quota iniziale del pelo libero meno quota del centroide dell\'orifizio">Carico iniziale, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Portata massima, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume svuotato';
$ec_lang['odt_sketch_start']='Inizio';
$ec_lang['odt_sketch_end']='Fine';
// Erosion Setback and Scour Calc.
// Contact us.

// About
$ec_lang['about_main_menu']='Informazioni';
$ec_lang['install_main_menu']='Installa';
$ec_lang['install_main_title']='Installa EngCalcs';
$ec_lang['install_main_desc']='Aggiungi al tuo dispositivo per l\'uso offline';
$ec_lang['install_intro']='EngCalcs è una Progressive Web App (PWA). Una volta installata, tutti i calcolatori funzionano completamente offline: non serve alcuna connessione a Internet.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Apri una qualsiasi pagina di calcolo in Chrome.</li><li>Tocca il pulsante <strong>⬇ Installa</strong> nella barra di navigazione superiore, oppure tocca il menu del browser (⋮) e scegli <strong>Aggiungi a schermata Home</strong>.</li><li>Tocca <strong>Installa</strong> nella richiesta che compare.</li><li>EngCalcs comparirà nella schermata Home e funzionerà offline.</li>';
$ec_lang['install_now_btn']='⬇ Installa ora';
$ec_lang['install_prompt_unavailable']='Richiesta di installazione non disponibile: usa invece il menu del browser.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Apri una qualsiasi pagina di calcolo in Safari.</li><li>Tocca il pulsante <strong>Condividi</strong> (il riquadro con la freccia verso l\'alto).</li><li>Scorri verso il basso e tocca <strong>Aggiungi a Home</strong>.</li><li>Tocca <strong>Aggiungi</strong>. EngCalcs comparirà nella schermata Home.</li>';
$ec_lang['install_ios_note']='Su iOS l\'installazione avviene sempre tramite il menu Condividi: non compare alcuna richiesta di installazione automatica.';
$ec_lang['install_desktop_heading']='Desktop (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Apri una qualsiasi pagina di calcolo.</li><li>Fai clic sull\'<strong>icona di installazione</strong> (⊕ o icona a forma di computer) nella barra degli indirizzi del browser, oppure apri il menu del browser e scegli <strong>Installa EngCalcs…</strong></li><li>Fai clic su <strong>Installa</strong>. EngCalcs si aprirà come app autonoma in una propria finestra.</li>';
$ec_lang['install_firefox_heading']='Firefox / Altri browser';
$ec_lang['install_firefox_body']='Firefox non supporta l\'installazione di PWA su desktop. Puoi comunque usare tutti i calcolatori normalmente nel browser: dopo la prima visita, le pagine vengono memorizzate automaticamente nella cache per l\'uso offline.';
$ec_lang['install_cached_heading']='Cosa viene memorizzato nella cache';
$ec_lang['install_cached_body']='La prima volta che installi EngCalcs, tutte le pagine dei calcolatori e i relativi file di supporto (script, stili) vengono salvati automaticamente sul tuo dispositivo. Da quel momento, tutto funziona senza connessione a Internet. La lingua scelta viene ricordata dall\'ultima visita online.';
$ec_lang['contact_main_menu']='Contatto';
$ec_lang['about_main_title']='Informazioni sui calcolatori HawsEDC';
$ec_lang['about_main_desc']='Missione, open source e contributi';
$ec_lang['about_body_html']='<h3>Missione</h3><p>Le Calcolatrici di Ingegneria HawsEDC esistono per servire ingegneri e operatori sul campo in tutto il mondo — in particolare coloro che lavorano in regioni con scarsità d\'acqua, risorse limitate o poco servite. Questi strumenti fanno parte di una missione umanitaria più ampia: dire a ogni essere umano nel modo più pratico ed efficace possibile che è amato e prezioso per sempre, che non ha nulla da temere e che non rovinerà tutto.</p><p>Le calcolatrici sono il mezzo. La destinazione è un mondo libero dalla sofferenza.</p><h3>Licenza Open Source</h3><p>Tutto il codice è rilasciato sotto la <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licenza Pubblica Generale GNU v3.0 o successiva</a> — libero come nella libertà. Puoi usare, studiare, modificare e ridistribuire il codice secondo gli stessi termini.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Codice Sorgente</h3><p>Il codice sorgente completo è disponibile pubblicamente su Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Puoi sfogliare il codice, segnalare problemi o fare un fork del repository lì.</p><h3>Contribuire</h3><p>Le pull request sono benvenute. Modi per contribuire:</p><ul><li><strong>Traduzioni</strong> — migliora o aggiungi una lingua. Apri una pull request con modifiche al file <code>lib/lang.ec.??.php</code> pertinente.</li><li><strong>Segnalazioni di bug</strong> — usa il modulo di feedback su qualsiasi pagina della calcolatrice, o segnala un problema su Bitbucket.</li><li><strong>Nuove calcolatrici</strong> — le idee per strumenti di ingegneria idraulica al servizio di operatori sul campo e professionisti dell\'irrigazione sono particolarmente benvenute. Consulta la guida per sviluppatori <code>CLAUDE.md</code> nel repository.</li><li><strong>Hosting</strong> — se puoi ospitare queste calcolatrici per una regione con connettività limitata, contattaci.</li></ul><h3>Uso offline</h3><p>Questi calcolatori funzionano come un\'App Web Progressiva (PWA). Visita qualsiasi pagina del calcolatore mentre sei connesso a internet e il tuo browser memorizzerà automaticamente tutti i calcolatori nella cache. Dopodiché, tutti i calcolatori funzionano offline — senza necessità di internet.</p><p>Su Android o iOS, usa l\'opzione "Aggiungi alla schermata iniziale" del tuo browser per installare EngCalcs come app sul tuo dispositivo. Su desktop, cerca l\'icona di installazione nella barra degli indirizzi del browser.</p><p>Puoi anche salvare qualsiasi calcolatore individuale usando il menu "Salva con nome…" del tuo browser per un utilizzo offline occasionale.</p><h3>Contatto</h3><p>Tom Haws — ingegnere idraulico e autore di queste calcolatrici.<br />Usa il modulo di feedback su qualsiasi pagina della calcolatrice, o accedi al codice sorgente su <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Contatti HawsEDC';
$ec_lang['contactSendMessage']='Invia un messaggio a Tom Haws';
$ec_lang['contactYourName']='Nome:';
$ec_lang['contactYourEmail']='Indirizzo e-mail:';
$ec_lang['contactSubject']='Oggetto:';
$ec_lang['contact_message']='Messaggio:';
$ec_lang['contactSpamPrefix']='Cinque più uno è';
$ec_lang['contactSpamPostfix']='(Scrivere in inglese. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Invia messaggio';
$ec_lang['contact_success']='Grazie per aver dedicato il tempo a scrivere.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Progetto di Scivolo in Pietrame (Robinson)';
$ec_lang['rc_main_title']='Calcolatore Gratuito per Progetto di Scivolo in Pietrame — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionamento del Pietrame per Scivolo — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Pendenza del fondo dello scivolo, S<sub>0</sub>';
$ec_lang['rc_qt']='Portata specifica totale, q<sub>t</sub> <span title="Portata per unità di larghezza all\'ingresso dello scivolo. Per un canale di larghezza di fondo B con portata totale Q, usare q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Porosità del pietrame, n<sub>p</sub>';
$ec_lang['rc_sg']='Densità relativa della roccia, sg <span title="Granito frantumato o basalto tipico ≈ 2,65. Intervallo valido Robinson: 2,54 a 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Gradazione SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Deviazione standard granulometrica. Roccia uniforme ≈ 1,25. Intervallo valido Robinson: 1,15 a 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Tirante normale nel canale di ingresso, y<sub>n</sub> <span title="Il rigurgito (Hp > yn) è favorevole — riduce l\'erosione a monte. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Dimensione mediana richiesta della roccia, D<sub>50</sub> <span title="Eq. 1 (S0 < 0,10) o Eq. 2 (0,10–0,40). Valido: D50 15–278 mm, S0 0,02–0,40. Fuori intervallo: estrapolato." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Equazione applicata';
$ec_lang['rc_sg_check']='Verifica della densità relativa';
$ec_lang['rc_SD_check']='Verifica della gradazione SD';
$ec_lang['rc_sg_ok']   ='sg nell\'intervallo valido';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']  ='sg al di sotto dell\'intervallo Robinson';
$ec_lang['rc_sg_low_tip']='Intervallo valido: 2,54–2,82';
$ec_lang['rc_sg_high'] ='sg al di sopra dell\'intervallo Robinson';
$ec_lang['rc_sg_high_tip']='Intervallo valido: 2,54–2,82';
$ec_lang['rc_SD_ok']   ='SD nell\'intervallo valido';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']  ='SD al di sotto dell\'intervallo Robinson';
$ec_lang['rc_SD_low_tip']='Intervallo valido: 1,15–1,47';
$ec_lang['rc_SD_high'] ='SD al di sopra dell\'intervallo Robinson';
$ec_lang['rc_SD_high_tip']='Intervallo valido: 1,15–1,47';
$ec_lang['rc_layer']='Spessore dello strato di pietrame (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Raggio di curvatura in sommità (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Lunghezza d\'arco in sommità';
$ec_lang['rc_apron_length']='Lunghezza della platea di uscita (15 × D<sub>50</sub>) <span title="Necessario per il supporto strutturale della roccia dello scivolo. &quot;Il tirante minimo di valle risultante dal tratto di uscita e dalla resistenza del canale a valle è sufficiente a garantire la stabilità del pietrame nel tratto di uscita.&quot; (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Scabrezza di Manning nello scivolo, n';
$ec_lang['rc_Vm']='Velocità attraverso il mantello di roccia, V<sub>m</sub> <span title="Frazione di qt che scorre attraverso i pori della roccia. Il resto qs scorre in superficie. np predefinito = 0,45 per roccia frantumata angolare." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Portata specifica nel mantello, q<sub>m</sub>';
$ec_lang['rc_qs']='Portata specifica superficiale, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Altezza idrica sopra la superficie del pietrame, d';
$ec_lang['rc_Hp']='Carico sulla soglia di ingresso, H<sub>p</sub> <span title="Il rigurgito (Hp > yn) è favorevole — riduce l\'erosione a monte. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Verifica del rigurgito all\'imbocco';
$ec_lang['rc_pond_ok']  ='H<sub>p</sub> > y<sub>n</sub> — rigurgito a monte';
$ec_lang['rc_pond_ok_tip']='Il rigurgito a monte dell\'imbocco dello scivolo è favorevole; riduce l\'erosione a monte. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — nessun rigurgito — rischio di erosione all\'imbocco';
$ec_lang['rc_pond_warn_tip']='Nessun rigurgito a monte dell\'imbocco dello scivolo; potrebbe verificarsi erosione a monte. (USDA)';
$ec_lang['rc_eq1']='Eq. 1 (S<sub>0</sub> < 0,10) — pendenza dolce';
$ec_lang['rc_eq2']='Eq. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — pendenza ripida';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — al di sotto dell\'intervallo di validazione Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — al di sopra dell\'intervallo di validazione Robinson';
$ec_lang['rc_notes_1_term']='Equazioni di dimensionamento della roccia';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) hanno sviluppato due equazioni empiriche per la dimensione mediana del pietrame D<sub>50</sub> in funzione della pendenza dello scivolo e della portata specifica. L\'equazione 1 si applica a pendenze dolci (S<sub>0</sub> < 0,10); l\'equazione 2 a pendenze ripide (0,10 ≤ S<sub>0</sub> ≤ 0,40). Entrambe le equazioni richiedono q<sub>t</sub> in m²/s e restituiscono D<sub>50</sub> in mm. L\'intervallo validato è 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Portata specifica';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> è la portata specifica totale alla sommità dello scivolo (portata totale per unità di larghezza). Per un canale di larghezza di fondo B con portata totale Q, q<sub>t</sub> ≈ Q / B, oppure si calcola dalla condizione di tirante critico all\'ingresso dello scivolo.';
$ec_lang['rc_notes_3_term']='Deflusso attraverso il mantello di roccia';
$ec_lang['rc_notes_3_def']='Una frazione della portata totale scorre attraverso i pori del pietrame (portata di mantello q<sub>m</sub>); il resto scorre sulla superficie della roccia (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). L\'altezza idrica d è calcolata con l\'equazione di Manning applicata alla portata superficiale q<sub>s</sub> usando la scabrezza n dello scivolo. La porosità predefinita n<sub>p</sub> = 0,45 è tipica per roccia frantumata angolare.';
$ec_lang['rc_notes_5_term']='Intervallo valido di dimensione della roccia';
$ec_lang['rc_notes_5_def']='Le equazioni sono state sviluppate per un intervallo D<sub>50</sub> da 15 mm a 278 mm. I risultati al di fuori di questo intervallo sono estrapolati e devono essere utilizzati con ulteriore giudizio ingegneristico.';
$ec_lang['rc_notes_6_term']='Quota della superficie della platea di uscita';
$ec_lang['rc_notes_6_def']='La quota della sommità del pietrame nel tratto di uscita deve essere pari o inferiore alla quota del fondo del canale a valle. Se è più alta, la roccia di uscita sarà instabile.';
$ec_lang['rc_notes_7_def']='Quando il tirante normale nel canale di ingresso è inferiore al carico sullo stramazzo (H<sub>p</sub>) necessario per transitare q<sub>t</sub>, si verifica un deflusso limitato o un rigurgito a monte dell\'imbocco dello scivolo. Ciò è generalmente accettabile — il rigurgito riduce la velocità e previene l\'erosione a monte. Per verificare: utilizzare un calcolatore di stramazzo per trovare H<sub>p</sub> per il q<sub>t</sub> e la larghezza di cresta dati, e confrontarlo con il tirante normale del canale di ingresso. Se H<sub>p</sub> supera il tirante normale, si verificherà rigurgito.';
$ec_lang['rc_notes_4_term']='Riferimento';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., e Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. L\'USDA ARS pubblica anche un <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">foglio di calcolo Excel</a> basato sullo stesso metodo.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtro';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curva di cresta';
$ec_lang['rc_sketch_outlet_apron']    = 'Platea di uscita';
$ec_lang['rc_sketch_radius']          = 'raggio';
// Category 4: Irrigation & Seepage (irr_/cs_/ip_) - complete re-translation
$ec_lang['irr_main_menu']='Irrigazione';
$ec_lang['irr_main_title']='Calcolatrici online gratuite per la misura della portata di irrigazione';
$ec_lang['irr_main_desc']='Misura della portata di irrigazione — stramazzi e orifizi';
$ec_lang['irr_intro_html']='<p>Gli stramazzi e gli orifizi sono gli strumenti standard da campo per misurare la portata d\'acqua nei sistemi di irrigazione. Selezionare la calcolatrice che corrisponde alla propria struttura:</p>';
$ec_lang['irr_card_weir_uniform_head']='Stramazzo — a soglia larga (larghezza uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Misurare la portata sopra la soglia di una diga di derivazione, una struttura di regolazione, o una paratoia di stramazzo. Inserire la lunghezza dello stramazzo e il tirante a monte sopra la soglia.';
$ec_lang['irr_card_weir_irregular_head']='Stramazzo — profilo irregolare';
$ec_lang['irr_card_weir_irregular_desc']='Utilizzare quando la soglia dello stramazzo varia in quota o profilo — sfioratori naturali, strutture di caduta con larghezza variabile, o strutture di controllo a più sezioni.';
$ec_lang['irr_card_orifice_head']='Orifizio — paratoia di testata o presa da tubazione';
$ec_lang['irr_card_orifice_desc']='Misurare la portata attraverso una paratoia a saracinesca, una presa da tubazione, o un\'apertura di tombino. Gestisce automaticamente sia le condizioni di scarico libero sia quelle sommerse (a valle).';
$ec_lang['irr_card_canal_head']='Progettazione e verifica di canali';
$ec_lang['irr_card_canal_desc']='Progettare o verificare un canale di irrigazione usando la formula di Manning. Utilizzare la calcolatrice Trapezoidale per nuovi canali; la calcolatrice Irregolare per sezioni naturali o costruite esistenti.';
$ec_lang['irr_card_seepage_head']='Infiltrazione del canale &amp; efficienza di trasporto';
$ec_lang['irr_card_seepage_desc']='Stimare la perdita per infiltrazione da un tratto di canale usando le misurazioni di portata in ingresso e in uscita. Calcolare l\'efficienza di trasporto e la perdita annua d\'acqua per aiutare a stabilire le priorità degli investimenti di rivestimento.';
$ec_lang['irr_quickref_html']='<h3>Riferimento rapido</h3><dl><dt>Diga di derivazione o struttura di regolazione</dt><dd>Misurare il tirante a monte sopra la soglia dello stramazzo. Utilizzare <a href="Weir-Flow-Simple.php">Stramazzo semplice</a> per una soglia uniforme, oppure <a href="Weir-Flow-Irregular.php">Stramazzo irregolare</a> per una soglia sagomata o a gradini.</dd><dt>Paratoia di testata o presa da tubazione</dt><dd>Misurare la quota a monte e la quota a valle (oppure la quota di fondo se lo scarico è libero). Utilizzare <a href="Orifice.php">Deflusso a orifizio</a>. Per una tubazione circolare, D&nbsp;= diametro della tubazione; per una paratoia rettangolare, inserire la larghezza W e l\'altezza D.</dd><dt>Tempo di svuotamento di serbatoio o invaso</dt><dd>Utilizzare <a href="Orifice-Drain-Time.php">Tempo di svuotamento da orifizio</a> per stimare quanto tempo serve per abbassare un invaso o serbatoio attraverso un orifizio di fondo — utile per la pianificazione degli invasi di irrigazione.</dd><dt>Standard di campo</dt><dd>Le equazioni di flusso per stramazzi e orifizi utilizzate qui corrispondono alle procedure USBR <em>Water Measurement Manual</em> (3&nbsp;ed.) comunemente richieste dai gestori idrici e dai consorzi di irrigazione.</dd></dl>';
$ec_lang['ip_se']='Spaziatura tra gli emettitori, S<sub>e</sub>';
$ec_lang['ip_sl']='Spaziatura delle ali laterali, S<sub>l</sub>';
$ec_lang['ip_n_e']='Emettitori per ala laterale, n<sub>e</sub>';
$ec_lang['ip_n_l']='Ali laterali per zona, n<sub>l</sub>';
$ec_lang['ip_d']='Profondità di applicazione obiettivo, d';
$ec_lang['ip_a_e']='Area per emettitore, A<sub>e</sub>';
$ec_lang['ip_pr']='Tasso di applicazione, PR';
$ec_lang['ip_q_lat']='Portata per ala laterale, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Portata di zona, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Durata di funzionamento (ore)';
$ec_lang['cs_main_menu']='Infiltrazione del canale';
$ec_lang['cs_main_title']='Calcolatrice online gratuita per la perdita per infiltrazione del canale e l\'efficienza di trasporto';
$ec_lang['cs_main_desc']='Perdita per infiltrazione del canale &amp; efficienza di trasporto &mdash; metodo ingresso-uscita';
$ec_lang['cs_Q_in']='Portata in ingresso, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Portata in uscita, Q<sub>out</sub>';
$ec_lang['cs_L']='Lunghezza del tratto, L';
$ec_lang['cs_Q_loss']='Tasso di perdita per infiltrazione, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verifica della misurazione';
$ec_lang['cs_pct_loss']='Frazione persa';
$ec_lang['cs_Ec']='Efficienza di trasporto, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Valutazione dell\'efficienza';
$ec_lang['cs_Vol_day']='Volume perso giornaliero';
$ec_lang['cs_Vol_year']='Volume perso annuo';
$ec_lang['cs_Q_loss_per_L']='Perdita per unità di lunghezza, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valore dell\'acqua';
$ec_lang['cs_lining_cost']='Costo del rivestimento';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Obiettivo di efficienza di trasporto dopo il rivestimento; frazione 0&ndash;1">Obiettivo di rivestimento, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Area di rivestimento, L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valore annuo perso';
$ec_lang['cs_annual_value_recovered']='Valore annuo recuperato';
$ec_lang['cs_lining_total_cost']='Costo totale del rivestimento';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Ammortamento semplice = costo totale del rivestimento &divide; valore annuo recuperato">Periodo di ammortamento <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — infiltrazione rilevata';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — nessuna perdita misurabile';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — verificare le misurazioni';
$ec_lang['cs_Ec_good']='Buona — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Discreta — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Scarsa — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='Il metodo ingresso-uscita stima l\'infiltrazione misurando la portata a monte e a valle di un tratto di canale: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. L\'efficienza di trasporto E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Il volume annuo presuppone un funzionamento continuo a piena portata; la perdita effettiva è inferiore per i canali stagionali o a portata parziale.';
$ec_lang['cs_notes_2_term']='Valutazioni dell\'efficienza';
$ec_lang['cs_notes_2_def']='Canali in terra tipici non rivestiti: E<sub>c</sub> = 60&ndash;80%. Canali in terra ben mantenuti: 75&ndash;85%. Canali rivestiti in calcestruzzo: 90&ndash;98%. Perdite per infiltrazione superiori al 30% della portata in ingresso spesso giustificano un investimento nel rivestimento. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Ammortamento del rivestimento';
$ec_lang['cs_notes_3_def']='Inserire il valore dell\'acqua e il costo del rivestimento in qualsiasi valuta coerente. L\'area di rivestimento = lunghezza del tratto &times; perimetro bagnato &mdash; il perimetro bagnato della sezione trasversale del canale alla profondità di flusso misurata (larghezza di fondo più entrambe le sponde bagnate). Il valore annuo recuperato presuppone che il canale rivestito raggiunga l\'efficienza obiettivo E<sub>c</sub> in modo continuo. L\'ammortamento effettivo sarà più lungo per i canali stagionali o se il rivestimento non raggiunge l\'efficienza obiettivo.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3ª ed. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
$ec_lang['ip_main_menu']='Pressione di irrigazione';
$ec_lang['ip_main_title']='Calcolatrice online gratuita per la pressione di irrigazione e l\'uniformità di distribuzione';
$ec_lang['ip_main_desc']='Verifica della pressione nel ramo di prova e stima dell\'uniformità';
$ec_lang['ip_h_supply']='Pressione di alimentazione';
$ec_lang['ip_elev_supply']='Quota di alimentazione, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Portata di progetto dell\'emettitore, q<sub>design</sub>';
$ec_lang['ip_h_design']='Pressione di progetto dell\'emettitore';
$ec_lang['ip_x']='<span class="ec-help" title="0,5 per emettitori standard non compensati; vicino a 0 per emettitori autocompensanti">Esponente di scarico dell\'emettitore, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Percorso di prova';
$ec_lang['ip_group_reach']='Tratto';
$ec_lang['ip_group_upstream']='A monte';
$ec_lang['ip_group_downstream']='A valle';
$ec_lang['ip_group_loss']='Perdita';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="Selezionato: questo tratto è un segmento dell\'ala laterale di prova, dalla quale i singoli emettitori prelevano acqua. Non selezionato: questo tratto è una condotta principale, che si limita a trasmettere la portata alle ali laterali non presenti nel percorso di prova.">Lat. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Righe ala laterale: emettitori solo in questo tratto. Righe condotta principale: numero totale di emettitori sulle ali laterali DIVERSE da questa che si diramano da questo tratto. Per il tratto della condotta principale che termina all\'ala laterale di prova, questo include anche tutte le ali laterali oltre quel punto lungo la condotta principale, o che condividono lo stesso nodo (ad esempio un\'ala laterale sul lato opposto) &mdash; anche la loro portata si dirama da questo stesso tratto.">Emettitori <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Quota all\'estremità di valle di questo tratto. Facoltativa nelle righe interne (predefinita: piatta, cioè uguale al nodo superiore, se lasciata vuota). Obbligatoria nell\'ultima riga: quel valore è la quota dell\'ultimo emettitore, che determina direttamente la pressione di alimentazione richiesta.">Elev. V. <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='La quota dell\'ultimo emettitore (ultima riga) è stata lasciata vuota ed è stata impostata come piatta per impostazione predefinita &mdash; inserirla per un risultato accurato';
$ec_lang['ip_flow']='Portata';
$ec_lang['ip_press']='Press.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Perdita totale del tratto, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Pressione bassa/negativa &mdash; verificare eventuali condizioni subatmosferiche';
$ec_lang['ip_pressure_warn_short']='Bassa';
$ec_lang['ip_h_far']='Pressione all\'ultimo emettitore';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Portata in ingresso al solo percorso di prova modellato — per l\'intera zona/sistema, vedere Q_zone in Progettazione dell\'applicazione qui sotto.">Portata di alimentazione del percorso di prova, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Portata dell\'ultimo emettitore, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Portata media dell\'emettitore (ala laterale di prova), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Quanto più alta (o più bassa) si stima che un\'ala laterale tipica operi rispetto a questa ala laterale di prova. L\'ala laterale di prova è deliberatamente il caso peggiore presunto, quindi la sua stessa media è una sottostima della media di campo &mdash; se lasciato a 0, la verifica di uniformità e i valori di progettazione dell\'applicazione qui sotto usano la media dell\'ala laterale di prova stessa (probabilmente ottimistica) così com\'è.">Stima &Delta;pressione, media rispetto all\'ala laterale di prova <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral rivalutata alla pressione di ciascuna riga dell\'ala laterale più la differenza di pressione inserita sopra &mdash; un tentativo di correggere il fatto che l\'ala laterale di prova sia il caso peggiore presunto, non uno rappresentativo. Alimenta sia la verifica di uniformità sia la sezione di progettazione dell\'applicazione qui sotto.">Stima della portata media di campo dell\'emettitore, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Portata calcolata dell\'ultimo emettitore divisa per la portata media di campo stimata dell\'emettitore &mdash; questa è un\'approssimazione della uniformità di distribuzione del quarto inferiore standard (media del gruppo inferiore &divide; media della popolazione); questa deriva da un piccolo campione modellato e da una correzione stimata dall\'utente anziché da un campione statistico completo sul campo. Valori pari o superiori a 1 sono possibili e validi: significano solo che la pressione dell\'ultimo emettitore è pari o superiore alla media di campo stimata, quindi qualche altro emettitore è il punto di pressione più bassa. Ciò potrebbe essere dovuto al fatto che l\'ultimo emettitore si trova su un terreno più basso oppure che la stima di &Delta;pressione è troppo piccola.">Verifica di uniformità, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='La pressione all\'emettitore di prova è &ge; alla pressione di alimentazione. Probabilmente questo non è l\'emettitore nel caso peggiore, oppure le tubazioni potrebbero essere ridotte.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Questo è diverso dalla nostra approssimazione della misura di uniformità standard.">Portata dell\'ultimo emettitore &divide; portata di progetto, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Nessuna soluzione: la pressione di alimentazione richiesta supera la pressione di alimentazione inserita. Aumentare la pressione di alimentazione, ridurre la domanda, oppure utilizzare una tubazione più grande.';
$ec_lang['ip_notes_1_def']='Ipotizza la pressione all\'ultimo emettitore (il più remoto), poi retrocede la linea dei carichi totali verso l\'alimentazione, tratto per tratto, aggiungendo le perdite per attrito e le perdite concentrate lungo il percorso. La quota e l\'altezza cinetica vengono sottratte a ogni nodo per calcolare la pressione effettiva in quel punto. La pressione ipotizzata all\'estremità remota viene regolata (bisezione) finché la pressione di alimentazione richiesta calcolata non corrisponde alla pressione di alimentazione inserita &mdash; lo stesso problema a circuito chiuso affrontato dal risolutore di flusso in tubazione della calcolatrice Manning Pipe Flow, esteso a una rete ramificata.';
$ec_lang['ip_notes_2_term']='Tratti di condotta principale e ala laterale';
$ec_lang['ip_notes_2_def']='Ogni riga è un tratto lungo l\'unico percorso idraulicamente peggiore (il percorso di prova) dall\'alimentazione all\'ultimo emettitore. Un tratto di condotta principale trasmette solamente la portata alle ali laterali non presenti nel percorso di prova, quindi il suo prelievo è una semplice moltiplicazione (portata di progetto &times; il numero totale di emettitori del tratto) &mdash; nessuna sensibilità di pressione locale. La condotta principale è una tubazione tronco condivisa, quindi il tratto della condotta principale che termina all\'ala laterale di prova deve includere non solo le ali laterali comprese tra i propri estremi, ma anche qualsiasi ala laterale ulteriore lungo la condotta principale oltre quel punto, o che condivide lo stesso nodo (ad esempio un\'ala laterale sul lato opposto) &mdash; la loro portata attraversa quello stesso tratto prima di diramarsi, che appaiano o meno altrove in questa tabella. Un tratto di ala laterale è un segmento dell\'ala laterale di prova stessa: la portata dell\'emettitore viene calcolata dalla pressione locale effettiva tramite q = k&middot;H<sup>x</sup>, e la perdita per attrito viene ridotta dal fattore F(n) di Christiansen per tenere conto della diminuzione della portata man mano che ciascun emettitore nel tratto preleva acqua.';
$ec_lang['ip_notes_3_term']='Limitazioni';
$ec_lang['ip_notes_3_def']='Modella una pressione di alimentazione fissa (nessuna curva di pompa), un solo percorso di prova (non l\'intero campo), e una curva dell\'emettitore a 2 parametri (impostare l\'esponente vicino a 0 per approssimare un emettitore autocompensante). Vengono riportati due diversi rapporti di uniformità, tenuti deliberatamente separati: q<sub>last</sub>/q<sub>avg,field</sub> è un\'approssimazione della uniformità di distribuzione del quarto inferiore standard (media del gruppo inferiore &divide; media della popolazione); ma questa deriva da un piccolo campione modellato e da una correzione stimata dall\'utente anziché dal campione statistico completo standard sul campo. Inoltre, l\'ala laterale di prova è deliberatamente il caso peggiore presunto, quindi la sua media grezza, non corretta, sottostimerebbe la vera media di campo e farebbe apparire l\'uniformità migliore di quanto sia in realtà; l\'input di &Delta;pressione esiste specificamente per contrastare questo effetto. Valori di uniformità pari o superiori a 1 restano possibili: significano solo che la pressione dell\'ultimo emettitore è pari o superiore alla media di campo stimata, quindi qualche altro emettitore è il punto di pressione più bassa. Ciò potrebbe essere dovuto al fatto che l\'ultimo emettitore si trova su un terreno più basso oppure che la stima di &Delta;pressione è troppo piccola. q<sub>last</sub>/q<sub>design</sub> è una verifica diversa, non di uniformità, rispetto alla portata nominale del produttore &mdash; utile per rilevare un sistema complessivamente sovra- o sottopressurizzato, ma è una verifica separata da leggere insieme al valore di uniformità, poiché la portata di progetto/nominale è indipendente dalla pressione media di esercizio effettiva del sistema.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. Gli standard ASAE/ASABE per la progettazione della microirrigazione utilizzano lo stesso approccio alla perdita per attrito multi-uscita.';
$ec_lang['ip_notes_5_term']='Progettazione dell\'applicazione';
$ec_lang['ip_notes_5_def']='Il tasso di applicazione e la portata di sistema/zona utilizzano la portata media di campo stimata dell\'emettitore (q<sub>avg,field</sub> &mdash; la media dell\'ala laterale di prova stessa, corretta dalla stima di &Delta;pressione inserita), non un tasso ipotizzato: PR = q<sub>avg,field</sub> / A<sub>e</sub>, alimentato dal valore modellato corretto. La spaziatura e il numero di ali laterali/emettitori dell\'intero sistema sono input separati qui, poiché il percorso di prova modella solo un ramo nel caso peggiore, non ogni ala laterale del campo.';
$ec_lang['irr_card_pressure_head']='Pressione di irrigazione &amp; uniformità';
$ec_lang['irr_card_pressure_desc']='Modellare il profilo di pressione e portata lungo un ramo condotta principale-ala laterale-emettitore per stimare l\'uniformità di distribuzione dalla pressione reale del percorso di prova, non solo da una portata nominale da catalogo dell\'emettitore.';
