<?php

// Units
// Necessary for calculator units selectors
$ec_lang['u_ft']="ft";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_in']="inches";
$ec_lang['u_in2']="sq. in.";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m']="m";
$ec_lang['u_m2']="m^2";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mps']="m/s";
$ec_lang['u_m3ph']="m^3/hr";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mm']="mm";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mph']="miles/hr";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_s']="sec";
$ec_lang['u_grade']="rise/run";
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_depthFrac']="fraction";
$ec_lang['u_depthPercent']="%";

// Page text
// Note: In the process of rearranging the language variables into page order for easier maintenance.
$ec_lang['menu_main_list']='List of Calculators';
$ec_lang['menu_main_hydraulics']='Hydraulics';
$ec_lang['menu_main_language']='Language';
$ec_lang['menu_sub1_manning']='Manning Formula';
$ec_lang['template_translation_help']="Can you help me translate this calculator to your language or host this calculator at your web site?  ";
$ec_lang['template_feedback']="Please give us your valued words of suggestion or praise.  Did this free calculator exceed your expectations in every way?";
$ec_lang['template_printable_title']="Printable Title";
$ec_lang['template_printable_subtitle']="Printable Subtitle";
$ec_lang['index_title']='Free Online Engineering Calculators';
$ec_lang['mpf_main_menu']='Manning Pipe Flow';
$ec_lang['mpf_main_title']='Free Online Manning Pipe Flow Calculator';
$ec_lang['mpf_main_desc']='Manning Formula Uniform Pipe Flow at Given Slope and Depth';
$ec_lang['calc_set_units']='Set units:';
$ec_lang['calc_results']='Results';
$ec_lang['mpf_pipe_diameter']='Promjer cijevi, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manningov koeficijent hrapavosti, n';
$ec_lang['mpf_friction_slope']='Linijski gubitak pritiska (moguće <a target="_blank" href="../pressureslope.php">?</a> jednak nagibu cijevi), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Udio ispunjenosti cijevi (u % visine promjera)';
$ec_lang['mpf_flow']='Protok, q';
$ec_lang['mpf_velocity']='Tečenja, v';
$ec_lang['mpf_velocity_head']='Energija tečenja, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Površina presjeka';
$ec_lang['mpf_wetted_perimeter']='Omočeni opseg, O';
$ec_lang['mpf_hydraulic_radius']='Hidraulički radijus, R';
$ec_lang['mpf_top_width']='Najveća širina, T';
$ec_lang['mpf_froude_number']='Froudeov broj, F';
$ec_lang['mpf_shear_stress']='Posmično naprezanje (vučna sila), tau';
$ec_lang['mphl_main_menu']='Manning Pipe Head Loss';
$ec_lang['mphl_main_title']='Free Online Manning Pipe Head Loaa Calculator';
$ec_lang['mphl_main_desc']='Manning Formula Head Loss at Given Full Flow';
$ec_lang['mphl_pipe_length']='Pipe length, L';
$ec_lang['mphl_total_junction_k']='Total combined junction loss coefficient, k';
$ec_lang['mphl_friction_loss']='Friction loss';
$ec_lang['mphl_junction_loss']='Junction loss';
$ec_lang['mphl_total_loss']='Total loss';
$ec_lang['mtc_menu']='Manning Formula Trapezoidal Channel';
$ec_lang['mtc_main_title']='Free Online Manning Formula Trapezoidal Channel Calculator';
$ec_lang['mtc_main_desc']='Manning Formula Uniform Trapezoidal Channel Flow at Given Slope and Depth';
$ec_lang['mtc_bottom_width']='Bottom width';
$ec_lang['mtc_side_slope_1']='Side slope 1 (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Side slope 2 (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Channel slope';
$ec_lang['mtc_flow_depth']='Flow depth';
$ec_lang['mtc_d50_bottom']='<span title="per Isbash (1936), Robinson, and Maricopa County, Arizona, US">Required bottom angular riprap size, D50, Maricopa County</span>';
$ec_lang['mtc_d50_mra']='Required angular riprap size, D50, per Maynord, Ruff, and Abt (1989)';
$ec_lang['mtc_d50_searcy']='Required angular riprap size, D50, per Searcy (1967)';
$ec_lang['mtc_d50_strickler']='<span title="per Strickler (Adjust n so this equals your design lining size)">Implied riprap size based on n</span>';
$ec_lang['mtc_d50_z1']='<span title="per Isbash (1936), Robinson, and Maricopa County, Arizona, US">Required side slope 1 angular riprap size, D50, Maricopa County</span>';
$ec_lang['mtc_d50_z2']='<span title="per Isbash (1936), Robinson, and Maricopa County, Arizona, US">Required side slope 2 angular riprap size, D50, Maricopa County</span>';
$ec_lang['rrc_main_menu']="Robinson Rock Chute";
$ec_lang['rrc_main_desc']="Robinson Rock Chute Design Spreadsheet";
$ec_lang['ws_main_menu']='Weir Flow Simple';
$ec_lang['ws_main_title']='Simple Broad-crested Weir Flow Calculator';
$ec_lang['ws_main_desc']='Simple Broad-crested Weir Flow Calculator';
$ec_lang['ws_weirLength']='Weir length, l';
$ec_lang['ws_headWaterHeight']='Headwater height, h';
$ec_lang['ws_weirCoefficient']='Weir coefficient, Cw';
$ec_lang['ws_notes_heading']='Notes';
$ec_lang['ws_notes_we_term']='Weir Equation';
$ec_lang['wi_menu']='Weir Flow Irregular';
$ec_lang['wi_main_title']='Free Online Segmented, Variable Depth, Irregular Broad-crested Weir Flow Calculator';
$ec_lang['wi_main_desc']='Irregular Broad-crested Weir Flow Calculator';
$ec_lang['wi_headWaterelevation']='Headwater elevation';
$ec_lang['wi_weirPoints']='Weir points';
$ec_lang['wi_station']='Station';
$ec_lang['wi_elevation']='Elevation';
$ec_lang['wi_pondingHeight']='Ponding Height';
$ec_lang['wi_incrementalFlow']='Incremental Flow';
$ec_lang['wi_cumulativeFlow']='Cumulative Flow';
$ec_lang['wi_save_and_calculate']='Save and Calculate';
$ec_lang['wi_or_adjust']="or";
$ec_lang['wi_n_rows']="the number of rows";
$ec_lang['wi_notes']='Notes';
$ec_lang['wi_notes_we_term']='Weir Equation';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d0<sup>1.5</sup> else cw/(2.5*slope) * (d0<sup>2.5</sup> - d1<sup>2.5</sup>) where d1 and d0 are always positive or zero';
$ec_lang['contact_title']="HawsEDC Contact";
$ec_lang['contactSendMessage']='Send Tom Haws a message';
$ec_lang['contactYourName']='Your name:';
$ec_lang['contactYourEmail']='Your e-mail address:';
$ec_lang['contactSubject']='Subject:';
$ec_lang['contact_message']='Message:';
$ec_lang['contactSpamPrefix']='Five plus one equals';
$ec_lang['contactSpamPostfix']='(Please spell it out. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Submit Message';
?>
