<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='ប្រភាគ';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']='rise/run';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Calculators';
$ec_lang['menu_main_list']='បញ្ជីម៉ាស៊ីនគណនា';
$ec_lang['menu_main_hydraulics']='វិស្វកម្មហ៊ីដ្រូលីក';
$ec_lang['menu_main_language']='ភាសា';
$ec_lang['template_welcome']='&gt;&gt; ទម្លាក់ការភ័យខ្លាចរបស់អ្នកនៅក្រៅទ្វារ; ក្ដីស្រឡាញ់ត្រូវបានប្រើសម្រាប់ភាសាទីនេះ។ អ្នកមិនបំផ្លាញអ្វីទាំងអស់ឡើយ។ រីករាយជាមួយ <a target="_blank" href="https://hawsedc.com/download.php">ឧបករណ៍ HawsEDC AutoCAD ឥតគិតថ្លៃ</a> ផងដែរ។ &lt;&lt;';
$ec_lang['template_translation_help']='តើអ្នកមានគំនិតល្អសម្រាប់ម៉ាស៊ីនគណនាដែលចង់បន្ថែមនៅទីនេះទេ? តើអ្នកអាចជួយខ្ញុំកែលម្អការបកប្រែ ការសរសេរកម្មវិធី ឬការបង្ហោះម៉ាស៊ីនគណនាទាំងនេះបានទេ?  ';
$ec_lang['template_feedback']='សូមផ្ញើមតិយោបល់ ឬការសរសើររបស់អ្នកដ៏មានតម្លៃមកយើង។ តើម៉ាស៊ីនគណនាឥតគិតថ្លៃនេះបានលើសពីការរំពឹងទុករបស់អ្នកគ្រប់ទិសទិសទេ?';
$ec_lang['template_printable_title']='ចំណងជើងដែលអាចបោះពុម្ព';
$ec_lang['template_printable_subtitle']='ចំណងជើងរងដែលអាចបោះពុម្ព';
$ec_lang['index_title']='ម៉ាស៊ីនគណនាវិស្វកម្មតាមអ៊ីនធឺណិតឥតគិតថ្លៃ';
$ec_lang['calc_set_units']='កំណត់ឯកតា:';
$ec_lang['points_data_help']='(ឬ ចម្លង/បិទភ្ជាប់ ដោយប្រើផ្ទៃទិន្នន័យ)';
$ec_lang['points_data_title']='ទិន្នន័យចំណុច<br />(បំបែកដោយក្បៀស ឬ tab)';
$ec_lang['points_data_copy']='ចម្លង';
$ec_lang['points_data_paste']='បិទភ្ជាប់';
$ec_lang['calc_inputs']='ទិន្នន័យបញ្ចូល';
$ec_lang['calc_results']='លទ្ធផល';
$ec_lang['view_hide_line']='[លាក់បន្ទាត់នេះ]';
$ec_lang['view_printable']='កំណែដែលអាចបោះពុម្ព (ផ្ទុកឡើងវិញ/ធ្វើឱ្យស្រស់ ដើម្បីស្ដារ)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់';
$ec_lang['dw_main_title']='ម៉ាស៊ីនគណនា Darcy-Weisbach ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['dw_main_desc']='ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ Darcy-Weisbach ប្រឡោះ ភាពរញ៉េរញ៉ៃ និងល្បឿនហូរទឹកដែលបានកំណត់';
$ec_lang['dw_roughness']='ភាពរញ៉េរញ៉ៃដាច់ខាត Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='លំហូរ kinematic viscosity, v, ជា m<sup>2</sup>/sec (1E-6 សម្រាប់ទឹកស្អាតនៅសីតុណ្ហភាពបន្ទប់)';
$ec_lang['dw_reynolds_number']='លេខ Reynolds, Re';
$ec_lang['dw_flow_regime']='របៀបហូរ';
$ec_lang['dw_regime_laminar']='លំហូរស្រួល';
$ec_lang['dw_regime_transitional']='លំហូរផ្លាស់ប្ដូរ';
$ec_lang['dw_regime_turbulent']='លំហូររំខាន';
$ec_lang['dw_friction_factor_method']='វិធីសាស្ត្រគ្រាប់ friction factor';
$ec_lang['dw_friction_factor']='Friction factor, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់';
$ec_lang['hw_main_title']='ម៉ាស៊ីនគណនា Hazen-Williams ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['hw_main_desc']='ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ Hazen-Williams ប្រឡោះ ភាពរញ៉េរញ៉ៃ និងល្បឿនហូរទឹកដែលបានកំណត់';
$ec_lang['hw_hgl_1']='HGL ចំហៀងក្រោម';
$ec_lang['hw_hgl_2']='HGL ចំហៀងលើ';
$ec_lang['hw_roughness']='សម្ប្រាក Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning មានប្រឡាយមិនទៀងទាត់';
$ec_lang['mi_main_title']='ម៉ាស៊ីនគណនា Manning ប្រឡាយមិនទៀងទាត់ ឥតគិតថ្លៃ';
$ec_lang['mi_main_desc']='ម៉ាស៊ីនគណនាលំហូរឯកសណ្ឋាន Manning ប្រឡាយមិនទៀងទាត់';
$ec_lang['mi_waterSurfaceElevation']='កម្ពស់ផ្ទៃទឹក';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='ចំណុចខណ្ឌកាត់';
$ec_lang['mi_groupPoint']='ចំណុច';
$ec_lang['mi_groupSegment']='ផ្នែក';
$ec_lang['mi_groupRegion']='តំបន់';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Elev';
$ec_lang['mi_d50in']='Lining<br />median<br />rock<br />size';
$ec_lang['mi_n']='n<br />for seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />region<br />boundary<br />(Bank)';
$ec_lang['mi_tau']='Bot.<br />shear<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Comp.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='កំណត់ចំណាំ';
$ec_lang['mi_notes_1_term']='Composite n';
$ec_lang['mi_notes_1_def']='ម៉ាស៊ីនគណនានេះធ្វើតាម HEC-RAS Reference Manual ក្នុងការគណនា composite n ក្នុងតំបន់ ដោយប្រើ Chow 1959, ទំព័រ 136, សមីការ 6-17 (មិនមែន 6-18)។';
$ec_lang['mi_notes_2_term']='ស្រទាប់ថ្ម';
$ec_lang['mi_notes_2_def']='ប្រើម៉ាស៊ីនគណនា Manning Trapezoidal Channel ដើម្បីរចនាស្រទាប់ថ្ម។ ម៉ាស៊ីនគណនានេះសម្រាប់ខណ្ឌធម្មជាតិជាង។';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning ការហូរទឹកក្នុងបំពង់';
$ec_lang['mpf_main_title']='ម៉ាស៊ីនគណនា Manning ការហូរទឹកក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['mpf_main_desc']='រូបមន្ត Manning ការហូរទឹកបំពង់ឯកសណ្ឋានជាមួយ ជម្រាល និងជម្រៅដែលបានកំណត់';
$ec_lang['mpf_spreadheet_notice']='ពិនិត្យកំណែសៀវភៅបញ្ជីរបស់ម៉ាស៊ីនគណនានេះ';
$ec_lang['mpf_pipe_diameter']='ប្រឡោះបំពង់, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='ភាពរញ៉េរញ៉ៃ Manning, n';
$ec_lang['mpf_friction_slope']='ជម្រាលសម្ពាធ (ប្រហែល <a target="_blank" href="../pressureslope.php">?</a> ស្មើជម្រាលបំពង់), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='សមាមាត្រជម្រៅហូរ, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(មើលកំណត់ចំណាំ)';
$ec_lang['mpf_flow']='ល្បឿនហូរ, Q';
$ec_lang['mpf_velocity']='ល្បឿន, v';
$ec_lang['mpf_velocity_head']='ទំនាប់ល្បឿន, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='ផ្ទៃហូរ, a';
$ec_lang['mpf_pipe_area']='ផ្ទៃបំពង់, a0';
$ec_lang['mpf_area_ratio']='សមាមាត្រផ្ទៃ, a/a0';
$ec_lang['mpf_wetted_perimeter']='គ្រែទឹក, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='កាំ hydraulic, R<sub>h</sub>';
$ec_lang['mpf_top_width']='ទទឹងខាងលើ, T';
$ec_lang['mpf_froude_number']='លេខ Froude, F';
$ec_lang['mpf_shear_stress']='ការពន្លូតលើស​មធ្យម (កម្លាំងទាញ), tau';
$ec_lang['mpf_full_flow']='ហូរពេញ, Q0';
$ec_lang['mpf_full_flow_ratio']='សមាមាត្រទៅនឹងហូរពេញ, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>នេះជាការហូរ និងជម្រៅនៅខាងក្នុងបំពង់ <em>វែងឥតកំណត់</em>។</dt><dd>ការទទួលទឹកចូលបំពង់អាចត្រូវការជម្រៅទឹកខាងលើខ្ពស់ជាងច្រើន។ បន្ថែមយ៉ាងហោចណាស់ 1.5 ដងទំនាប់ល្បឿន ដើម្បីទទួលបានជម្រៅទឹកខាងលើ ឬ <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">មើលការណែនាំ 2 នាទីរបស់ខ្ញុំ</a> សម្រាប់ការគណនាទំនាប់ទឹក culvert ស្ដង់ដារ ដោយប្រើ HY-8។</dd>';
$ec_lang['mpf_solve_for_dd0']='រកដំណោះស្រាយ y/d<sub>0</sub> ពី Q';
$ec_lang['mpf_solve_desc']='ដោយប្រើ D<sub>0</sub>, n, និង S<sub>0</sub> ពីទម្រង់ម៉ាស៊ីនគណនា រក y/d<sub>0</sub> ទាបបំផុត សម្រាប់ Q ដែលបានកំណត់។';
$ec_lang['mpf_solve_button']='ដោះស្រាយ';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning ការបាត់បង់ទំនាប់ក្នុងបំពង់';
$ec_lang['mphl_main_title']='ម៉ាស៊ីនគណនា Manning ការបាត់បង់ទំនាប់ក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['mphl_main_desc']='រូបមន្ត Manning ការបាត់បង់ទំនាប់ ជាមួយការហូរពេញ';
$ec_lang['mphl_pipe_length']='ប្រវែងបំពង់, L';
$ec_lang['mphl_area']='ផ្ទៃ, A';
$ec_lang['mphl_total_junction_k']='សម្ប្រាក k សរុបរួមបញ្ចូលគ្នានៃការបាត់បង់ junction';
$ec_lang['mphl_friction_slope']='ជម្រាលស្ទះ';
$ec_lang['mphl_friction_loss']='ការបាត់បង់ស្ទះ, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='ការបាត់បង់ junction, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='ការបាត់បង់សរុប, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL ចំហៀងក្រោម';
$ec_lang['mphl_egl_2']='EGL ចំហៀងលើ';
$ec_lang['mphl_hgl_2']='HGL ចំហៀងលើ ក្នុងបំពង់ ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>សម្រាប់លក្ខខណ្ឌចំហ (culvert) ចាំបាច់ត្រូវពិនិត្យលក្ខខណ្ឌត្រួតពិនិត្យធាតុចូល។</dt><dd>1. HGL ខាងលើ មិនអាចទាបជាងកម្ពស់ហូរជម្រៅធម្មតា ខាងលើ (ឬទាបជាងបំពង់!)។</dd><dd>2. ទំនាប់ទឹក culvert ត្រូវបានតំណាងប្រសើរជាងដោយ EGL ខាងលើ ជាជាង HGL ខាងលើ។</dd><dd>3. មើល <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ការណែនាំ 2 នាទីរបស់ខ្ញុំ</a> សម្រាប់ការគណនាទំនាប់ទឹក culvert ស្ដង់ដារ ដោយប្រើ HY-8។</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning ប្រឡាយជ្រូងចតុកោណ';
$ec_lang['mtc_main_title']='ម៉ាស៊ីនគណនា Manning ប្រឡាយជ្រូងចតុកោណ ឥតគិតថ្លៃ';
$ec_lang['mtc_main_desc']='រូបមន្ត Manning ការហូរប្រឡាយជ្រូងចតុកោណឯកសណ្ឋាន ជម្រាល និងជម្រៅដែលបានកំណត់';
$ec_lang['mtc_bottom_width']='ទទឹងខាងក្រោម, b';
$ec_lang['mtc_side_slope_1']='ជម្រាលចំហៀង 1 (ផ្ដេក/បញ្ឈរ)';
$ec_lang['mtc_side_slope_2']='ជម្រាលចំហៀង 2 (ផ្ដេក/បញ្ឈរ)';
$ec_lang['mtc_channel_slope']='ជម្រាលប្រឡាយ, S';
$ec_lang['mtc_flow_depth']='ជម្រៅហូរ, y';
$ec_lang['mtc_bend_angle']='មុំបត់ <a target="_blank" href="riprap-bend-angle.png" title="ចុចសម្រាប់រូបភាព">?</a> (សម្រាប់ការកំណត់ទំហំ riprap)';
$ec_lang['mtc_sgrock']='ទំនាក់ទំនងទម្ងន់ជាក់លាក់ថ្ម (2.65)';
$ec_lang['mtc_d50_in']='ទំហំថ្មរចនា, D50';
$ec_lang['mtc_n_strickler']='n សម្រាប់ទំហំថ្មរចនា តាម Strickler';
$ec_lang['mtc_n_blodgett']='n សម្រាប់ទំហំថ្មរចនា តាម Blodgett';
$ec_lang['mtc_n_bathurst']='n សម្រាប់ទំហំថ្មរចនា តាម Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett ទល់នឹង Bathurst';
$ec_lang['mtc_d50_bottom']='ទំហំថ្មខ្ចាញ់ខាងក្រោមដែលត្រូវការ, D50 (Isbash & MC) <a href="javascript:alert(\'Per Isbash (1936) and Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z1']='ទំហំថ្មខ្ចាញ់ជម្រាលចំហៀង 1 ដែលត្រូវការ, D50 (Isbash & MC) <a href="javascript:alert(\'Per Isbash (1936) and Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z2']='ទំហំថ្មខ្ចាញ់ជម្រាលចំហៀង 2 ដែលត្រូវការ, D50 (Isbash & MC) <a href="javascript:alert(\'Per Isbash (1936) and Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_mra']='ទំហំថ្មខ្ចាញ់ដែលត្រូវការ, D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='ទំហំថ្មខ្ចាញ់ដែលត្រូវការ, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>ការធ្វើម្ដងទៀតដោយស្វ័យប្រវត្តិនៃទំហំថ្ម និងការរចនាភាពរញ៉េរញ៉ៃ</dt><dd>ជ្រើសប៊ូតុងភាពរញ៉េរញ៉ៃ (ណែនាំ BB) និងប៊ូតុងទំហំថ្មរចនា (ណែនាំ Isbash)។ កែតម្រូវជម្រៅ និងកត្តាសុវត្ថិភាពទំហំថ្ម ដើម្បីទទួលបានការហូរចង់បានជាមួយទំហំថ្មស្ថិតស្ថេរ។ រាល់ពេលអ្នកផ្លាស់ប្ដូរតម្លៃបញ្ចូលណាមួយ ដំណើរការម្ដងទៀតខាងក្រោមនឹងកើតឡើង: 1. ភាពរញ៉េរញ៉ៃត្រូវបានគណនាពីទំហំថ្មរចនា។ 2. ការគណនាភាពរញ៉េរញ៉ៃដែលបានស្នើត្រូវបានចម្លងទៅភាពរញ៉េរញ៉ៃបញ្ចូល។ 3. ការហូរក្នុងប្រឡាយ និងទំហំថ្មដែលត្រូវការ ត្រូវបានគណនា។ 4. ទំហំថ្មរចនាត្រូវបានកែតម្រូវ។ 5. ធ្វើម្ដងទៀតរហូតដល់កំហុសក្នុងទំហំថ្មរចនាតូចណាស់។</dd><dt>ម៉ាស៊ីនគណនាមូលដ្ឋាន (គ្មានការធ្វើម្ដងទៀត)</dt><dd>បញ្ចូលតម្លៃភាពរញ៉េរញ៉ៃចង់បាន។ មិនយកចិត្តទុកដាក់ផ្ទៃបញ្ចូលទំហំថ្មរចនា។</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='សៀវភៅបញ្ជីរចនា Robinson Rock Chute';
// Weir Flow Simple
$ec_lang['ws_main_menu']='ការហូរ Weir សាមញ្ញ';
$ec_lang['ws_main_title']='ម៉ាស៊ីនគណនា Weir ព្រំដែនទទឹងសាមញ្ញ ឥតគិតថ្លៃ';
$ec_lang['ws_main_desc']='ម៉ាស៊ីនគណនាការហូរ Weir ព្រំដែនទទឹងសាមញ្ញ';
$ec_lang['ws_weirLength']='ប្រវែង weir, l';
$ec_lang['ws_headWaterHeight']='កម្ពស់ទំនាប់ទឹក, h';
$ec_lang['ws_weirCoefficient']='សម្ប្រាក weir, Cw';
$ec_lang['ws_notes_heading']='កំណត់ចំណាំ';
$ec_lang['ws_notes_we_term']='សមីការ Weir';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='ការហូរ Weir មិនទៀងទាត់';
$ec_lang['wi_main_title']='ម៉ាស៊ីនគណនាការហូរ Weir ស្ថិតិ ជម្រៅប្រែប្រួល មិនទៀងទាត់ ឥតគិតថ្លៃ';
$ec_lang['wi_main_desc']='ម៉ាស៊ីនគណនាការហូរ Weir មិនទៀងទាត់';
$ec_lang['wi_headWaterelevation']='កម្ពស់ទំនាប់ទឹក';
$ec_lang['wi_weirPoints']='ចំណុច weir';
$ec_lang['wi_station']='ស្ថានីយ<br />(ចម្ងាយ)';
$ec_lang['wi_elevation']='កម្ពស់';
$ec_lang['wi_pondingHeight']='កម្ពស់ស្ទើ';
$ec_lang['wi_incrementalFlow']='ការហូរបន្ថែម';
$ec_lang['wi_cumulativeFlow']='ការហូរសរុប';
$ec_lang['wi_save_and_calculate']='រក្សាទុក និងគណនា';
$ec_lang['wi_notes_we_term']='សមីការ Weir';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='ការហូរ Orifice';
$ec_lang['or_main_title']='ម៉ាស៊ីនគណនាការហូរ Orifice ឥតគិតថ្លៃ';
$ec_lang['or_main_desc']='ការហូរ Orifice — សេរី ឬ ជ្រុក';
$ec_lang['or_shape']='រូបរាងរន្ធ';
$ec_lang['or_shape_circular']='មូល';
$ec_lang['or_shape_rectangular']='ចតុកោណ';
$ec_lang['or_diameter']='ប្រឡោះ (មូល) ឬ កម្ពស់ (ចតុកោណ), D';
$ec_lang['or_width']='ទទឹង, W (ចតុកោណប៉ុណ្ណោះ)';
$ec_lang['or_invert']='កម្ពស់ invert រន្ធ (ខាងក្រោមរន្ធ)';
$ec_lang['or_hwe']='កម្ពស់ទំនាប់ទឹក';
$ec_lang['or_twe']='កម្ពស់ទឹកខាងក្រោម';
$ec_lang['or_cd']='សម្ប្រាកការហូរចេញ, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='កម្ពស់ centroid';
$ec_lang['or_head']='ទំនាប់ប្រសិទ្ធិ, h';
$ec_lang['or_area']='ផ្ទៃរន្ធ, A';
$ec_lang['or_flow']='ការហូរ, Q';
$ec_lang['or_velocity']='ល្បឿននៅរន្ធ, v';
$ec_lang['or_regime']='ការពិនិត្យ orifice regime';
$ec_lang['or_regime_valid']='ហូរចេញសេរី — orifice regime ត្រឹមត្រូវ ✓';
$ec_lang['or_regime_submerged']='Orifice ជ្រុក (TWE លើ invert) — ត្រឹមត្រូវ ✓';
$ec_lang['or_regime_warn']='ព្រមាន: ទំនាប់ទឹកខាងក្រោមកំពូល — មិនមែន orifice regime';
$ec_lang['or_regime_twe_above_hwe']='ព្រមាន: ទឹកខ្ទង់ (TWE) លើ ទំនាប់ទឹក (HWE) — ពិនិត្យទិន្នន័យបញ្ចូល';
$ec_lang['or_notes_1_term']='សមីការ Orifice';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh)។ សម្រាប់ហូរចេញសេរី: h = HWE &minus; centroid។ សម្រាប់ការហូរជ្រុក (TWE លើ invert): h = HWE &minus; TWE។';
$ec_lang['or_notes_2_term']='Orifice Regime';
$ec_lang['or_notes_2_def']='សមីការការហូរ orifice ត្រូវបានអនុវត្ត នៅពេលផ្ទៃទំនាប់ទឹកស្ថិតនៅលើកំពូល (ខាងលើ) នៃរន្ធ។ នៅពេលទំនាប់ទឹកនៅក្រោមកំពូល ប្រើសមីការ weir ជំនួស។';
$ec_lang['or_notes_3_term']='សម្ប្រាកការហូរចេញ';
$ec_lang['or_notes_3_def']='C<sub>d</sub> ស្ថិតក្នុងចន្លោះប្រហែល 0.60&ndash;0.65 សម្រាប់ orifice ប្រភេទដែមមុតស្រួច។ ធាតុចូលមូល ឬ re-entrant ប្រើតម្លៃផ្សេងៗ។ មើល <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ឬ HEC-RAS Hydraulic Reference Manual ដើម្បីទទួលការណែនាំ។';
$ec_lang['or_notes_4_term']='ការជ្រុក';
$ec_lang['or_notes_4_def']='នៅពេល TWE ស្ថិតនៅលើ invert រន្ធ ម៉ាស៊ីនគណនានេះអនុវត្ត orifice ជ្រុកដោយស្វ័យប្រវត្តិ ដោយប្រើ h = HWE &minus; TWE។ នៅពេល TWE ស្ថិតនៅ invert ឬក្រោម ហូរចេញសេរីត្រូវបានសន្មតថា h = HWE &minus; centroid។';
// Penstock Design
$ec_lang['ps_main_menu']='ការរចនា Penstock';
$ec_lang['ps_main_title']='ម៉ាស៊ីនគណនារចនា Penstock ឥតគិតថ្លៃ';
$ec_lang['ps_main_desc']='ការកំណត់ទំហំ Penstock Micro-Hydro — ការបាត់បង់ទំនាប់ ថាមពល និងល្បឿន';
$ec_lang['ps_flow']='អត្រាហូរ, Q';
$ec_lang['ps_gross_head']='ទំនាប់ brut, H<sub>gross</sub>';
$ec_lang['ps_diameter']='ប្រឡោះ penstock, D';
$ec_lang['ps_length']='ប្រវែង penstock, L';
$ec_lang['ps_roughness']='ភាពរញ៉េរញ៉ៃបំពង់, e';
$ec_lang['ps_km']='សម្ប្រាក k នៃការបាត់បង់ junction (ឬ &ldquo;minor&rdquo;), k<sub>m</sub>';
$ec_lang['ps_nu']='Kinematic viscosity, &nu;, ជា m<sup>2</sup>/s (1E-6 សម្រាប់ទឹកជិត 20&deg;C)';
$ec_lang['ps_efficiency']='ប្រសិទ្ធភាពរោងចក្រ, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='ល្បឿនហូរ, v';
$ec_lang['ps_vel_check']='ការពិនិត្យល្បឿន';
$ec_lang['ps_f']='Friction factor, f';
$ec_lang['ps_hf']='ការបាត់បង់ទំនាប់ស្ទះ, h<sub>f</sub>';
$ec_lang['ps_hm']='ការបាត់បង់ទំនាប់ junction (ចំណុច), h<sub>m</sub>';
$ec_lang['ps_hl']='ការបាត់បង់ penstock សរុប, h<sub>L</sub>';
$ec_lang['ps_hl_check']='ការពិនិត្យការបាត់បង់ទំនាប់';
$ec_lang['ps_hnet']='ទំនាប់ net, H<sub>net</sub>';
$ec_lang['ps_power']='ថាមពលផ្តល់ចេញ, P';
$ec_lang['ps_annual_kwh']='ថាមពលប្រចាំឆ្នាំ ក្នុងសមត្ថភាព 100%';
$ec_lang['ps_vel_ok']='1–3 m/s — ស្ថិតក្នុងគោលដៅ ✓';
$ec_lang['ps_vel_low']='ក្រោម 1 m/s — បង្កើនប្រឡោះ ⚠';
$ec_lang['ps_vel_high']='លើស 3 m/s — បន្ថយប្រឡោះ ⚠';
$ec_lang['ps_hl_ok']='ស្ថិតក្នុងគោលដៅ 10% ✓';
$ec_lang['ps_hl_warn']='លើស 10% — ពិចារណាបំពង់ធំជាង ⚠';
$ec_lang['ps_hl_bad']='លើស 20% — ផ្លាស់ប្ដូរទំហំបំពង់';
$ec_lang['ps_notes_1_term']='ការបាត់បង់ទំនាប់';
$ec_lang['ps_notes_1_def']='ការបាត់បង់ penstock សរុប h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, ដែល h<sub>f</sub> = f(L/D)(v&sup2;/2g) ជាការបាត់បង់ Darcy-Weisbach friction និង h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g គ្របដណ្ដប់ធាតុចូល ការបត់ និងបំពង់ valve។ ទំនាប់ net H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>។';
$ec_lang['ps_notes_2_term']='ល្បឿន';
$ec_lang['ps_notes_2_def']='គោលដៅ 1&ndash;3 m/s។ ក្រោម 1 m/s ធ្វើឱ្យបំពង់ធំជ្រុលសម្រាប់ការហូរ; លើស 3 m/s បង្កើនការបាត់បង់ friction និងហានិភ័យ water hammer។';
$ec_lang['ps_notes_3_term']='គោលដៅការបាត់បង់ទំនាប់';
$ec_lang['ps_notes_3_def']='ការបាត់បង់ penstock ក្រោម 10% នៃទំនាប់ brut ជាទូទៅប្រកបដោយសេដ្ឋកិច្ច។ ការផ្លាស់ប្ដូរប្រសើរបំផុតរវាងតម្លៃបំពង់ និងថាមពលបាត់ ជារឿយៗស្ថិតប្រហែល 4&ndash;6% សម្រាប់តំបន់ไฟฟ้าដែលមានតម្លៃខ្ពស់។';
$ec_lang['ps_notes_4_term']='ការបាត់បង់ Junction (ចំណុច) k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='ការបាត់បង់ទាំងនេះកើតឡើងនៅ junction បំពង់ ធាតុចូល ការបត់ និងបំពង់ valve &mdash; ពាក្យ &ldquo;minor&rdquo; គឺជាទំនៀមប៉ុន្តែបំភាន់; ក្នុង penstock ខ្លី ពួកគេអាចស្មើ ឬលើសសារ friction។ តម្លៃ k ធម្មតា: ធាតុចូលមុតស្រួច 0.5, ការបត់ 45&deg; មួយ 0.2&ndash;0.3, gate valve (បើកពេញ) 0.1, butterfly valve 0.2។ សរុបគ្រប់ fitting សម្រាប់ k<sub>m</sub> សរុប។ លំនាំដើម 1.5 សន្មតធាតុចូលមួយ និងការបត់ពីរ។';
$ec_lang['ps_notes_5_term']='ភាពរញ៉េរញ៉ៃបំពង់ e';
$ec_lang['ps_notes_5_def']='ភាពរញ៉េរញ៉ៃដាច់ខាតធម្មតា: ដែក (ថ្មី) 0.046&nbsp;mm, ដែក (ប្រើហើយ) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, ស៊ីម៉ង់ 0.3&ndash;3&nbsp;mm។ HDPE គឺជារឿងធម្មតាសម្រាប់ penstock micro-hydro តូច។';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='ថាមពល Micro-Hydro';
$ec_lang['mhp_main_title']='ម៉ាស៊ីនគណនាថាមពល Micro-Hydro ឥតគិតថ្លៃ';
$ec_lang['mhp_main_desc']='ម៉ាស៊ីនគណនាផលិតថាមពល Micro-Hydro Run-of-River';
$ec_lang['mhp_flow']='អត្រាហូរ, Q';
$ec_lang['mhp_gross_head']='ទំនាប់ brut (ដំណើរចុះ), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='ការបាត់បង់ penstock, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='ប្រសិទ្ធភាពរោងចក្រ, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='ទំនាប់ net, H<sub>net</sub>';
$ec_lang['mhp_power']='ថាមពលផ្តល់ចេញ, P';
$ec_lang['mhp_annual_kwh']='ថាមពលប្រចាំឆ្នាំ ក្នុងសមត្ថភាព 100%';
$ec_lang['mhp_notes_1_term']='សមីការថាមពល';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, ដែល &rho; = 1000 kg/m&sup3; (ទឹកស្រស់) និង g = 9.806 m/s&sup2;។';
$ec_lang['mhp_notes_2_term']='ទំនាប់ Net';
$ec_lang['mhp_notes_2_def']='ទំនាប់ net = ទំនាប់ brut &minus; ការបាត់បង់ penstock។ ការប៉ាន់ស្មានដំបូងទូទៅ h<sub>L</sub> &asymp; 5% នៃ H<sub>gross</sub>។ ប្រើ <a href="Darcy-Weisbach.php">ម៉ាស៊ីនគណនា Darcy-Weisbach</a> ដើម្បីប៉ាន់ការបាត់បង់ penstock យ៉ាងត្រឹមត្រូវជាង។';
$ec_lang['mhp_notes_3_term']='ប្រសិទ្ធភាព';
$ec_lang['mhp_notes_3_def']='ប្រសិទ្ធភាពរោងចក្រធម្មតា &eta; ស្ថិតក្នុងចន្លោះ 0.70 ដល់ 0.85 សម្រាប់ turbine Pelton និង cross-flow ដែលជារឿងធម្មតា​ក្នុង micro-hydro។ ប្រើ 0.75 ជាការប៉ាន់ស្មានដំបូងប្រកបដោយការប្រុងប្រយ័ត្ន។';
$ec_lang['mhp_notes_4_term']='ថាមពលប្រចាំឆ្នាំ';
$ec_lang['mhp_notes_4_def']='ថាមពលប្រចាំឆ្នាំ សន្មតការប្រតិបត្តិការហូរពេញ​ជាបន្តបន្ទាប់ (8760 ម៉ោង/ឆ្នាំ)។ ការផលិតពិតប្រាកដ​នឹងទាបជាង ដោយសារតែភាពប្រែប្រួលនៃការហូរតាមរដូវ ការឈប់ជួសជុល និងប្រព័ន្ធ load factor។';
// Orifice Drain Time
$ec_lang['odt_main_menu']='ពេលបង្ហូរ Orifice';
$ec_lang['odt_main_title']='ម៉ាស៊ីនគណនាពេលបង្ហូរ Orifice ឥតគិតថ្លៃ — សាលា អាងស្ដុក ឬ ធុង';
$ec_lang['odt_main_desc']='ពេលបង្ហូរ Orifice ចេញពីសាលា ឬ អាង &mdash; វិធីសាស្ត្រ Conic Volume';
$ec_lang['odt_h1_elev']='កម្ពស់ផ្ទៃទឹកដំបូង';
$ec_lang['odt_a1']='ផ្ទៃសាលា ឬ អាងដំបូង, A1';
$ec_lang['odt_h2_elev']='កម្ពស់ផ្ទៃទឹកចុងក្រោយ';
$ec_lang['odt_h_orifice']='កម្ពស់ centroid orifice';
$ec_lang['odt_a0']='ផ្ទៃសាលា ឬ អាង នៅកម្ពស់ orifice, A0';
$ec_lang['odt_a_ending']='ផ្ទៃសាលាចុងក្រោយ, A2 (បូករំលាយ)';
$ec_lang['odt_h2_check']='ការពិនិត្យកម្ពស់ចុងក្រោយ';
$ec_lang['odt_h2_ok']='កម្ពស់ចុងក្រោយ​ស្ថិតនៅលើ orifice ខាងលើ ✓';
$ec_lang['odt_h2_warn']='ព្រមាន: កម្ពស់ចុងក្រោយ​ស្ថិតនៅ ឬ ក្រោមកំពូល orifice (centroid + D/2)';
$ec_lang['odt_d']='ប្រឡោះ orifice (មូល) ឬ កម្ពស់ (ចតុកោណ), D';
$ec_lang['odt_w']='ទទឹង orifice, W (ចតុកោណប៉ុណ្ណោះ)';
$ec_lang['odt_t_sec']='ពេលបង្ហូរ (វិនាទី)';
$ec_lang['odt_t_min']='ពេលបង្ហូរ (នាទី)';
$ec_lang['odt_t_hr']='ពេលបង្ហូរ (ម៉ោង)';
$ec_lang['odt_t_day']='ពេលបង្ហូរ (ថ្ងៃ)';
$ec_lang['odt_notes_1_term']='រូបមន្ត';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ផ្តល់ពេលបង្ហូរពី head H ទៅ orifice។ ពេលបង្ហូរ = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), ដែល H<sub>1</sub> = កម្ពស់ដំបូង &minus; កម្ពស់ orifice, H<sub>2</sub> = កម្ពស់ចុងក្រោយ &minus; កម្ពស់ orifice។';
$ec_lang['odt_notes_2_term']='វិធីសាស្ត្រ';
$ec_lang['odt_notes_2_def']='វិធីសាស្ត្រ conic volume គំរូ​ សាលា ឬ អាង​ ជាផ្នែក conic រវាងផ្ទៃដំបូង A<sub>1</sub> នៅ​ ផ្ទៃទឹកដំបូង​ និងផ្ទៃ A<sub>0</sub> នៅ​ កម្ពស់ centroid orifice។ A<sub>2</sub>, ផ្ទៃ​ សាលា​ នៅ​ កម្ពស់​ ចុងក្រោយ ត្រូវ​ បូករំលាយ​ ពី A<sub>1</sub> និង A<sub>0</sub> ដោយ​ ប្រើ​ គំរូ​ conic section។ ពេលបង្ហូរ​ ពី​ ដំបូង​ ដល់​ ចុង​ ស្មើ​ ពេល​ បង្ហូរ​ សរុប​ ពី H<sub>1</sub> ដល់ orifice ដកពេលបង្ហូរ​ នៅ​ សល់​ ពី H<sub>2</sub> ដល់ orifice។';
$ec_lang['odt_h1']='Head ដំបូង, H<sub>1</sub> (WSE &minus; centroid)';
$ec_lang['odt_q_max']='ការហូរ​ ច្រើន​ បំផុត​ (ដំបូង), Q<sub>max</sub>';
$ec_lang['odt_vol']='បរិមាណ​ ដែល​ បាន​ បង្ហូរ';
$ec_lang['odt_sketch_start']='ចាប់ផ្ដើម';
$ec_lang['odt_sketch_end']='ចប់';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='ទទឹង Bank ទៅ Bank';
$ec_lang['essc_mcr']='កាំ​ong​ curve តូចបំផុត';
$ec_lang['essc_q']='ការហូរ, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='ការវាស់ស្ទង់លំហូរប្រព័ន្ធស្រោចស្រព';
$ec_lang['irr_main_title']='ម៉ាស៊ីនគណនាឥតគិតថ្លៃតាមអ៊ីនធឺណិតសម្រាប់ការវាស់ស្ទង់លំហូរប្រព័ន្ធស្រោចស្រព';
$ec_lang['irr_main_desc']='ការវាស់ស្ទង់លំហូរប្រព័ន្ធស្រោចស្រព — ទ្រនាប់ទឹក និងរន្ធ';
$ec_lang['contact_title']='ទំនាក់ទំនង HawsEDC';
$ec_lang['contactSendMessage']='ផ្ញើសារទៅ Tom Haws';
$ec_lang['contactYourName']='ឈ្មោះ​ របស់​ អ្នក:';
$ec_lang['contactYourEmail']='អាសយ​ ដ្ឋាន​ អ៊ីម៉ែល​ របស់​ អ្នក:';
$ec_lang['contactSubject']='ប្រធានបទ:';
$ec_lang['contact_message']='សារ:';
$ec_lang['contactSpamPrefix']='ប្រាំ​ បូក​ មួយ​ ស្មើ​ នឹង';
$ec_lang['contactSpamPostfix']='(សូម​ សរសេរ​ ជា​ ពាក្យ​។ 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='ផ្ញើ​ សារ';
