<?php

// 简体中文 — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="比例";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="英尺水柱";
$ec_lang['u_ftps']="英尺/秒";
$ec_lang['u_ft']="英尺";
$ec_lang['u_gpm']="加仑/分钟";
$ec_lang['u_gradePercent']="% 坡度";
$ec_lang['u_grade']="坡度";
$ec_lang['u_in2']="平方英寸";
$ec_lang['u_inh2o']="英寸水柱";
$ec_lang['u_in']="英寸";
$ec_lang['u_knpcm2']="千牛/厘米^2";
$ec_lang['u_knpm2']="千牛/米^2";
$ec_lang['u_kpa']="千帕";
$ec_lang['u_lps']="升/秒";
$ec_lang['u_m2']="米^2";
$ec_lang['u_m3ps']="米^3/秒";
$ec_lang['u_mgd']="百万加仑/天";
$ec_lang['u_mh2o']="米水柱";
$ec_lang['u_mld']="百万升/天";
$ec_lang['u_m']="米";
$ec_lang['u_mm2']="毫米^2";
$ec_lang['u_mmh2o']="毫米水柱";
$ec_lang['u_mm']="毫米";
$ec_lang['u_mps']="米/秒";
$ec_lang['u_npm2']="牛/米^2";
$ec_lang['u_pa']="帕";
$ec_lang['u_psf']="磅/英尺^2";
$ec_lang['u_psi']="磅/英寸^2";
$ec_lang['u_s']="秒";
$ec_lang['u_acft']="英亩-英尺";
$ec_lang['u_ft3']="英尺^3";
$ec_lang['u_m3']="米^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='HawsEDC 计算器';
$ec_lang['menu_main_list']='计算器列表';
$ec_lang['menu_main_hydraulics']='水力学';
$ec_lang['menu_main_language']='语言';
$ec_lang['template_welcome']='&gt;&gt; 把恐惧留在门外；这里说爱的语言。同时享用免费的 <a href="https://hawsedc.com/download.php">HawsEDC AutoCAD 工具。</a> &lt;&lt;';
$ec_lang['template_translation_help']='您是否有关于在此处添加计算器的绝妙构想？  您能帮助我改进翻译、编程或托管这些计算器吗？  ';
$ec_lang['template_feedback']='请给我们有价值的建议或嘉许的话。此免费计算器是否在每个方面都超出您的预期？';
$ec_lang['template_printable_title']='可打印标题';
$ec_lang['template_printable_subtitle']='可打印副标题';
$ec_lang['index_title']='免费在线工程计算器';
$ec_lang['calc_set_units']='单位设置：';
$ec_lang['points_data_help']='（或使用数据区域复制/粘贴）';
$ec_lang['points_data_title']='测点数据<br />（逗号或制表符分隔）';
$ec_lang['points_data_copy']='复制';
$ec_lang['points_data_paste']='粘贴';
$ec_lang['calc_inputs']='输入';
$ec_lang['calc_results']='结果';
$ec_lang['view_hide_line']='[隐藏此行]';
$ec_lang['view_printable']='打印版本（刷新页面可恢复）';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='达西-韦斯巴赫管道水头损失';
$ec_lang['dw_main_title']='免费在线达西-韦斯巴赫管道水头损失计算器';
$ec_lang['dw_main_desc']='在给定管径、粗糙度和流量条件下的达西-韦斯巴赫管道水头损失';
$ec_lang['dw_roughness']='达西-韦斯巴赫绝对粗糙度，e';
$ec_lang['dw_kinematic_viscosity']='运动粘度，v，单位 m<sup>2</sup>/秒（常温清水取 1E-6）';
$ec_lang['dw_reynolds_number']='雷诺数，Re';
$ec_lang['dw_flow_regime']='流态';
$ec_lang['dw_regime_laminar']='层流';
$ec_lang['dw_regime_transitional']='过渡流';
$ec_lang['dw_regime_turbulent']='紊流';
$ec_lang['dw_friction_factor_method']='摩阻系数计算方法';
$ec_lang['dw_friction_factor']='摩阻系数，f';
// Hazen-Williams
$ec_lang['hw_main_menu']='哈森-威廉管道水头损失';
$ec_lang['hw_main_title']='免费在线哈森-威廉管道水头损失计算器';
$ec_lang['hw_main_desc']='在给定管径、粗糙度和流量条件下的哈森-威廉管道水头损失';
$ec_lang['hw_hgl_1']='下游测压管水头线';
$ec_lang['hw_hgl_2']='上游测压管水头线';
$ec_lang['hw_roughness']='哈森-威廉系数，C';
// Manning Irregular
$ec_lang['mi_menu']='曼宁不规则明渠';
$ec_lang['mi_main_title']='免费在线曼宁不规则明渠计算器';
$ec_lang['mi_main_desc']='不规则断面明渠曼宁均匀流计算器';
$ec_lang['mi_waterSurfaceElevation']='水面高程';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='横断面测点';
$ec_lang['mi_groupPoint']='测点';
$ec_lang['mi_groupSegment']='分段';
$ec_lang['mi_groupRegion']='分区';
$ec_lang['mi_station']='桩号';
$ec_lang['mi_elevation']='高程';
$ec_lang['mi_d50in']='护坡石<br />材中值<br />粒径';
$ec_lang['mi_n']='分段<br />曼宁<br />n 值';
$ec_lang['mi_is_bank']='R<sub>h</sub>、Q<br />分区边<br />界（岸坡）';
$ec_lang['mi_tau']='底部剪<br />切力<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='综合<br />n 值';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='注释';
$ec_lang['mi_notes_1_term']='综合 n 值';
$ec_lang['mi_notes_1_def']='本计算器依据 HEC-RAS 参考手册，采用 Chow 1959 第 136 页公式 6-17（非 6-18）计算各分区综合 n 值。';
$ec_lang['mi_notes_2_term']='石材护坡';
$ec_lang['mi_notes_2_def']='请使用曼宁梯形渠道计算器进行石材护坡设计。本计算器更适用于天然断面。';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='曼宁管流';
$ec_lang['mpf_main_title']='免费在线曼宁管流计算器';
$ec_lang['mpf_main_desc']='在给定坡度和水深条件下的曼宁公式均匀管流';
$ec_lang['mpf_spreadheet_notice']='查看本计算器的电子表格版本';
$ec_lang['mpf_pipe_diameter']='管径，d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='曼宁粗糙系数，n';
$ec_lang['mpf_friction_slope']='压力坡度线坡度（可能 <a target="_blank" href="../pressureslope.php">?</a> 等于管道坡度），S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='相对水深，y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='（参见注释）';
$ec_lang['mpf_flow']='流量，Q';
$ec_lang['mpf_velocity']='流速，v';
$ec_lang['mpf_velocity_head']='流速水头，h<sub>v</sub>';
$ec_lang['mpf_flow_area']='过水面积，a';
$ec_lang['mpf_pipe_area']='管道断面面积，a0';
$ec_lang['mpf_area_ratio']='面积比，a/a0';
$ec_lang['mpf_wetted_perimeter']='湿周，P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='水力半径，R<sub>h</sub>';
$ec_lang['mpf_top_width']='水面宽，T';
$ec_lang['mpf_froude_number']='弗劳德数，F';
$ec_lang['mpf_shear_stress']='平均剪切力（拖拽力），tau';
$ec_lang['mpf_full_flow']='满流流量，Q0';
$ec_lang['mpf_full_flow_ratio']='流量比，Q/Q0';
$ec_lang['mpf_note_1']='<p>注释：</p><dl><dt>这是<em>无限长</em>管道内部的流量和水深。</dt><dd>使水流进入管道可能需要显著更高的水位。请在水深基础上至少加 1.5 倍流速水头，或 <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">参见 2 分钟教程</a>，了解使用 HY-8 进行标准涵洞水位计算的方法。</dd>';
$ec_lang['mpf_solve_for_dd0']='已知 Q 求 y/d<sub>0</sub>';
$ec_lang['mpf_solve_desc']='使用计算器表单中的 D<sub>0</sub>、n 和 S<sub>0</sub>，求给定 Q 对应的最小 y/d<sub>0</sub>。';
$ec_lang['mpf_solve_button']='求解';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='曼宁管道水头损失';
$ec_lang['mphl_main_title']='免费在线曼宁管道水头损失计算器';
$ec_lang['mphl_main_desc']='在给定满流流量条件下的曼宁公式水头损失';
$ec_lang['mphl_pipe_length']='管道长度，L';
$ec_lang['mphl_area']='面积，A';
$ec_lang['mphl_total_junction_k']='局部损失系数总和，k';
$ec_lang['mphl_friction_slope']='摩擦坡度';
$ec_lang['mphl_friction_loss']='摩擦损失，H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='局部损失，H<sub>m</sub>';
$ec_lang['mphl_total_loss']='总损失，H<sub>l</sub>';
$ec_lang['mphl_egl_1']='下游能量坡降线';
$ec_lang['mphl_egl_2']='上游能量坡降线';
$ec_lang['mphl_hgl_2']='管内上游测压管水头线 ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<p>注释：</p><dl><dt>对于开口进水口（涵洞）情况，需检验进口控制条件。</dt><dd>1. 上游测压管水头线不得低于上游正常水深处高程（也不得低于管顶！）。</dd><dd>2. 涵洞水位更宜用上游能量坡降线而非测压管水头线表示。</dd><dd>3. <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">参见 2 分钟教程</a>，了解使用 HY-8 进行简单标准涵洞水位计算的方法。</dd>';
// Manning Trapezoid
$ec_lang['mtc_menu']='曼宁梯形渠道';
$ec_lang['mtc_main_title']='免费在线曼宁公式梯形渠道计算器';
$ec_lang['mtc_main_desc']='在给定坡度和水深条件下的曼宁公式均匀梯形渠道流';
$ec_lang['mtc_bottom_width']='渠底宽度，b';
$ec_lang['mtc_side_slope_1']='边坡 1（水平/垂直）';
$ec_lang['mtc_side_slope_2']='边坡 2（水平/垂直）';
$ec_lang['mtc_channel_slope']='渠道坡度，S';
$ec_lang['mtc_flow_depth']='水深，y';
$ec_lang['mtc_bend_angle']='弯道角度 <a target="_blank" href="riprap-bend-angle.png" title="点击查看图片">?</a>（用于石材护坡设计）';
$ec_lang['mtc_sgrock']='石材比重（2.65）';
$ec_lang['mtc_d50_in']='设计石材粒径，D50';
$ec_lang['mtc_n_strickler']='设计石材粒径对应 Strickler 公式 n 值';
$ec_lang['mtc_n_blodgett']='设计石材粒径对应 Blodgett 公式 n 值';
$ec_lang['mtc_n_bathurst']='设计石材粒径对应 Bathurst 公式 n 值';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett 与 Bathurst 比较';
$ec_lang['mtc_d50_bottom']='渠底所需棱角石材粒径，D50（Isbash 与 MC）<a href="javascript:alert(\'依据 Isbash (1936) 及 Maricopa County, Arizona, US。\')">?</a>';
$ec_lang['mtc_d50_z1']='边坡 1 所需棱角石材粒径，D50（Isbash 与 MC）<a href="javascript:alert(\'依据 Isbash (1936) 及 Maricopa County, Arizona, US。\')">?</a>';
$ec_lang['mtc_d50_z2']='边坡 2 所需棱角石材粒径，D50（Isbash 与 MC）<a href="javascript:alert(\'依据 Isbash (1936) 及 Maricopa County, Arizona, US。\')">?</a>';
$ec_lang['mtc_d50_mra']='所需棱角石材粒径，D50（Maynord、Ruff 和 Abt 1989）';
$ec_lang['mtc_d50_searcy']='所需棱角石材粒径，D50（Searcy 1967）';
$ec_lang['mtc_note_1']='<p>注释：</p><dl><dt>石材粒径与糙率自动迭代</dt><dd>选择糙率单选按钮（推荐 BB）和设计石材粒径单选按钮（推荐 Isbash）。调整水深和石材安全系数，以获得所需流量和均一石材粒径。每次修改输入值时，将触发以下迭代循环：1. 由设计石材粒径计算糙率。2. 所求糙率复制至输入糙率。3. 计算渠道流量和所需石材粒径。4. 调整设计石材粒径。5. 重复直至设计石材粒径误差极小。</dd><dt>基础计算器（无迭代）</dt><dd>直接输入所需糙率值，忽略设计石材粒径输入区域。</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson 石材跌水';
$ec_lang['rrc_main_desc']='Robinson 石材跌水设计电子表格';
// Weir Flow Simple
$ec_lang['ws_main_menu']='简单堰流';
$ec_lang['ws_main_title']='免费在线简单宽顶堰流计算器';
$ec_lang['ws_main_desc']='简单宽顶堰流计算器';
$ec_lang['ws_weirLength']='堰长，l';
$ec_lang['ws_headWaterHeight']='上游水头，h';
$ec_lang['ws_weirCoefficient']='堰流系数，Cw';
$ec_lang['ws_notes_heading']='注释';
$ec_lang['ws_notes_we_term']='堰流方程';
// Weir Flow Irregular
$ec_lang['wi_menu']='不规则堰流';
$ec_lang['wi_main_title']='免费在线分段变深不规则堰流计算器';
$ec_lang['wi_main_desc']='不规则堰流计算器';
$ec_lang['wi_headWaterelevation']='上游水位高程';
$ec_lang['wi_weirPoints']='堰体测点';
$ec_lang['wi_station']='位置';
$ec_lang['wi_elevation']='高程';
$ec_lang['wi_pondingHeight']='蓄水高度';
$ec_lang['wi_incrementalFlow']='分段流量';
$ec_lang['wi_cumulativeFlow']='累计流量';
$ec_lang['wi_save_and_calculate']='保存并计算';
$ec_lang['wi_notes_we_term']='堰流方程';
$ec_lang['wi_notes_we_def']='q = 若（堰长 = 0）则 0，若（坡度=0）则 cw*堰长*d<sub>0</sub><sup>1.5</sup>，否则 cw/(2.5*坡度) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>)，其中 d<sub>1</sub> 和 d<sub>0</sub> 始终为正值或零';
// Orifice Flow
$ec_lang['or_main_menu']='孔口流量';
$ec_lang['or_main_title']='免费在线孔口流量计算器';
$ec_lang['or_main_desc']='孔口流量 — 自由出流或淹没出流';
$ec_lang['or_shape']='孔口形状';
$ec_lang['or_shape_circular']='圆形';
$ec_lang['or_shape_rectangular']='矩形';
$ec_lang['or_diameter']='直径（圆形）或高度（矩形），D';
$ec_lang['or_width']='宽度，W（仅限矩形）';
$ec_lang['or_invert']='孔口底部高程';
$ec_lang['or_hwe']='上游水位高程';
$ec_lang['or_twe']='下游水位高程';
$ec_lang['or_cd']='流量系数，C<sub>d</sub>';
$ec_lang['or_centroid_elev']='形心高程';
$ec_lang['or_head']='有效水头，h';
$ec_lang['or_area']='孔口面积，A';
$ec_lang['or_flow']='流量，Q';
$ec_lang['or_velocity']='孔口处流速，v';
$ec_lang['or_regime']='孔口流态检验';
$ec_lang['or_regime_valid']='自由出流 — 孔口流态有效 ✓';
$ec_lang['or_regime_submerged']='淹没孔口（下游水位高于孔底）— 有效 ✓';
$ec_lang['or_regime_warn']='警告：上游水位低于孔顶 — 非孔口流态';
$ec_lang['or_regime_twe_above_hwe']='警告：下游水位（TWE）高于上游水位（HWE）— 请检查输入';
$ec_lang['or_notes_1_term']='孔口方程';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh)。自由出流：h = HWE &minus; 形心高程。淹没出流（下游水位高于孔底）：h = HWE &minus; TWE。';
$ec_lang['or_notes_2_term']='孔口流态';
$ec_lang['or_notes_2_def']='当上游水位高于孔口顶部时，适用孔口流量方程。当上游水位低于孔顶时，请改用堰流方程。';
$ec_lang['or_notes_3_term']='流量系数';
$ec_lang['or_notes_3_def']='锐缘孔口的 C<sub>d</sub> 约为 0.60&ndash;0.65。圆角或内缩入口的值不同。请参考 <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> 或 HEC-RAS 水力学参考手册。';
$ec_lang['or_notes_4_term']='淹没';
$ec_lang['or_notes_4_def']='当下游水位高于孔口底部时，计算器自动采用淹没孔口方程，h = HWE &minus; TWE。当下游水位等于或低于孔底时，采用自由出流假定，h = HWE &minus; 形心高程。';
// Orifice Drain Time
$ec_lang['odt_main_menu']='孔口排水时间';
$ec_lang['odt_main_title']='免费在线孔口排水时间计算器——池塘、调蓄池或水箱';
$ec_lang['odt_main_desc']='池塘或调蓄池孔口排水时间 &mdash; 锥体体积法';
$ec_lang['odt_h1_elev']='初始水面高程';
$ec_lang['odt_a1']='初始池塘或调蓄池面积，A1';
$ec_lang['odt_h2_elev']='终止水面高程';
$ec_lang['odt_h_orifice']='孔口形心高程';
$ec_lang['odt_a0']='孔口高程处池塘或调蓄池面积，A0';
$ec_lang['odt_a_ending']='终止池塘面积，A2（插值）';
$ec_lang['odt_h2_check']='终止高程校验';
$ec_lang['odt_h2_ok']='终止高程高于孔口顶部 ✓';
$ec_lang['odt_h2_warn']='警告：终止高程等于或低于孔口顶部（形心 + D/2）';
$ec_lang['odt_d']='孔口直径（圆形）或高度（矩形），D';
$ec_lang['odt_w']='孔口宽度，W（仅限矩形）';
$ec_lang['odt_t_sec']='排水时间（秒）';
$ec_lang['odt_t_min']='排水时间（分钟）';
$ec_lang['odt_t_hr']='排水时间（小时）';
$ec_lang['odt_t_day']='排水时间（天）';
$ec_lang['odt_notes_1_term']='公式';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) 给出从水头 H 至孔口的排水时间。排水时间 = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)，其中 H<sub>1</sub> = 初始高程 &minus; 孔口高程，H<sub>2</sub> = 终止高程 &minus; 孔口高程。';
$ec_lang['odt_notes_2_term']='方法';
$ec_lang['odt_notes_2_def']='锥体体积法将池塘或调蓄池模型化为初始水面面积 A<sub>1</sub> 与孔口形心高程处面积 A<sub>0</sub> 之间的锥形截面。终止高程处的池塘面积 A<sub>2</sub> 由 A<sub>1</sub> 和 A<sub>0</sub> 按锥形截面模型插值得出。从初始到终止高程的排水时间等于从 H<sub>1</sub> 到孔口的总排水时间减去从 H<sub>2</sub> 到孔口的剩余排水时间。';
$ec_lang['odt_h1']='初始水头，H<sub>1</sub>（水面高程 &minus; 形心高程）';
$ec_lang['odt_q_max']='最大（初始）流量，Q<sub>max</sub>';
$ec_lang['odt_vol']='排出水量';
$ec_lang['odt_sketch_start']='开始';
$ec_lang['odt_sketch_end']='结束';
// Erosion Setback
$ec_lang['essc_btbw']='岸对岸宽度';
$ec_lang['essc_mcr']='最小弯道半径';
$ec_lang['essc_q']='流量，Q';
// Contact
$ec_lang['contact_title']='HawsEDC 联系';
$ec_lang['contactSendMessage']='给 Tom Haws 发送消息';
$ec_lang['contactYourName']='您的姓名：';
$ec_lang['contactYourEmail']='您的电子邮件地址：';
$ec_lang['contactSubject']='主题：';
$ec_lang['contact_message']='留言：';
$ec_lang['contactSpamPrefix']='五加一等于';
$ec_lang['contactSpamPostfix']='（请用英文拼写。1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6）';
$ec_lang['contactSubmitButton']='发送消息';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='微型水力发电';
$ec_lang['mhp_main_title']='免费在线微型水力发电计算器';
$ec_lang['mhp_main_desc']='径流式微型水力发电功率计算器';
$ec_lang['mhp_flow']='流量，Q';
$ec_lang['mhp_gross_head']='总水头（落差），H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='压力管道水头损失，h<sub>L</sub>';
$ec_lang['mhp_efficiency']='电站效率，&eta;（0&ndash;1）';
$ec_lang['mhp_net_head']='净水头，H<sub>net</sub>';
$ec_lang['mhp_power']='输出功率，P';
$ec_lang['mhp_annual_kwh']='100%容量时的年发电量（kWh/年）';
$ec_lang['mhp_notes_1_term']='功率公式';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>，其中 &rho; = 1000 kg/m&sup3;（淡水），g = 9.806 m/s&sup2;。';
$ec_lang['mhp_notes_2_term']='净水头';
$ec_lang['mhp_notes_2_def']='净水头 = 总水头 &minus; 压力管道水头损失。常用初步估算为 h<sub>L</sub> &asymp; H<sub>gross</sub> 的 5%。如需更精确的管道损失估算，请使用 <a href="Darcy-Weisbach.php">达西–韦斯巴赫计算器</a>。';
$ec_lang['mhp_notes_3_term']='效率';
$ec_lang['mhp_notes_3_def']='微型水力发电中常用的冲击式（Pelton）和贯流式水轮机的典型电站效率 &eta; 为 0.70 至 0.85。保守初步估算可取 0.75。';
$ec_lang['mhp_notes_4_term']='年发电量';
$ec_lang['mhp_notes_4_def']='年发电量假设全年满流量连续运行（8760 小时/年）。由于流量季节性变化、维护停机及负荷因数影响，实际发电量将低于此值。';
// Penstock Design
$ec_lang['ps_main_menu']='压力管道设计';
$ec_lang['ps_main_title']='免费在线压力管道设计计算器';
$ec_lang['ps_main_desc']='微型水电压力管道尺寸计算——水头损失、功率与流速';
$ec_lang['ps_flow']='流量，Q';
$ec_lang['ps_gross_head']='毛水头，H<sub>gross</sub>';
$ec_lang['ps_diameter']='压力管道直径，D';
$ec_lang['ps_length']='压力管道长度，L';
$ec_lang['ps_roughness']='管道粗糙度，e';
$ec_lang['ps_km']='局部损失系数，k<sub>m</sub>';
$ec_lang['ps_nu']='运动黏度，&nu;，单位 m<sup>2</sup>/s（20&deg;C 附近水的值为 1E-6）';
$ec_lang['ps_efficiency']='水电站效率，&eta;（0&ndash;1）';
$ec_lang['ps_velocity']='流速，v';
$ec_lang['ps_vel_check']='流速校核';
$ec_lang['ps_f']='摩擦系数，f';
$ec_lang['ps_hf']='沿程水头损失，h<sub>f</sub>';
$ec_lang['ps_hm']='局部水头损失，h<sub>m</sub>';
$ec_lang['ps_hl']='压力管道总损失，h<sub>L</sub>';
$ec_lang['ps_hl_check']='水头损失校核';
$ec_lang['ps_hnet']='净水头，H<sub>net</sub>';
$ec_lang['ps_power']='输出功率，P';
$ec_lang['ps_annual_kwh']='100% 装机容量下的年发电量（kWh/年）';
$ec_lang['ps_vel_ok']='1&ndash;3 m/s &mdash; 在目标范围内 &#x2713;';
$ec_lang['ps_vel_low']='低于 1 m/s &mdash; 增大管径 &#x26a0;';
$ec_lang['ps_vel_high']='高于 3 m/s &mdash; 减小管径 &#x26a0;';
$ec_lang['ps_hl_ok']='在 10% 目标内 &#x2713;';
$ec_lang['ps_hl_warn']='超过 10% 目标 &mdash; 考虑更大管径 &#x26a0;';
$ec_lang['ps_hl_bad']='超过 20% &mdash; 重新核算管道尺寸';
$ec_lang['ps_notes_1_term']='水头损失';
$ec_lang['ps_notes_1_def']='总损失 h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>，其中 h<sub>f</sub> = f(L/D)(v&sup2;/2g) 为达西-魏斯巴赫沿程摩擦损失，h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g 包含进口、弯管与阀门损失。净水头 H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>。';
$ec_lang['ps_notes_2_term']='流速';
$ec_lang['ps_notes_2_def']='目标 1&ndash;3 m/s。低于 1 m/s 表明管道过大；高于 3 m/s 将增大摩擦损失和水锤风险。';
$ec_lang['ps_notes_3_term']='水头损失目标';
$ec_lang['ps_notes_3_def']='压力管道损失低于毛水头的 10% 一般是经济的。管道费用与损失电量之间的最优权衡通常在高价值发电站约 4&ndash;6% 处。';
$ec_lang['ps_notes_4_term']='局部损失 k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='典型参考值：锐边进口 0.5，每个 45&deg; 弯头 0.2&ndash;0.3，闸阀（全开）0.1，蝶阀 0.2。累加所有管件得到总 k<sub>m</sub>。默认值 1.5 假设一个进口和两个弯头。';
$ec_lang['ps_notes_5_term']='管道粗糙度 e';
$ec_lang['ps_notes_5_def']='典型绝对粗糙度：钢管（新）0.046&nbsp;mm，钢管（旧）0.15&nbsp;mm，HDPE 0.003&nbsp;mm，PVC/uPVC 0.0015&nbsp;mm，混凝土 0.3&ndash;3&nbsp;mm。HDPE 常用于小型微水电压力管道。';
