<?php

// Alh missing text declarations wilh falh back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fração";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="pés^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ft']="pés";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_grade']="incl./compr.";
$ec_lang['u_gradePercent']='% incl./compr.';
$ec_lang['u_in2']="pol. quad.";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="pol.";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="segundos (seg)";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
$ec_lang['menu_main_list']='Lista de calculadoras';
$ec_lang['menu_main_hydraulics']='Hidráulica';
$ec_lang['menu_main_language']='Idioma';
$ec_lang['template_welcome']='>> Deixe seus medos na porta. O amor é falado aqui. Você não está arruinando tudo. Aproveite também <a target="_blank" href="https://hawsedc.com/download.php">as ferramentas livres HawsEDC para AutoCAD</a>.<<';
$ec_lang['template_translation_help']='Você tem uma ótima ideia para uma calculadora a ser adicionada aqui?  Você pode me ajudar a traduzir esta calculadora para sua língua ou hostear esta calculadora em seu site?';
$ec_lang['template_feedback']='Por favor, dê-nos suas valiosas palavras de sugestão ou elogio. Esta calculadora gratuita excedeu suas expectativas em todos os aspectos?';
$ec_lang['template_printable_title']='Título imprimível';
$ec_lang['template_printable_subtitle']='Subtítulo imprimível';
$ec_lang['index_title']='Calculadoras de Engenharia Gratuitas Online';
$ec_lang['calc_set_units']='Definir unidades:';
$ec_lang['points_data_help']='(ou Copiar/Colar usando a área de dados)';
$ec_lang['points_data_title']='Dados dos pontos (separados por vírgula ou tabulação)';
$ec_lang['points_data_copy']='Copiar';
$ec_lang['points_data_paste']='Colar';
$ec_lang['calc_inputs']='Entradas';
$ec_lang['calc_results']='Resultados';
$ec_lang['view_hide_line']='[Ocultar esta linha]';
$ec_lang['view_printable']='Versão Imprimível (recarregar/renovar para restaurar)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Perda de pressão em uma tubulação de acordo com Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculadora gratuita online de perda de pressão em uma tubulação de acordo com Darcy-Weisbach';
$ec_lang['dw_main_desc']='Perda de pressão em uma tubulação a dado diâmetro, rugosidade, e vazão de acordo com Darcy-Weisbach';
$ec_lang['dw_roughness']='Rugosidade absoluta, e';
$ec_lang['dw_kinematic_viscosity']='<span title="1E-6 m^2/seg para água limpa à temperatura ambiente">Viscosidade cinemática, v (1E-6)</span>';
$ec_lang['dw_reynolds_number']='Número de Reynolds, Re';
$ec_lang['dw_flow_regime']='Regime do escoamento';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='transicional';
$ec_lang['dw_regime_turbulent']='turbulento';
$ec_lang['dw_friction_factor_method']='Método do fator de fricção';
$ec_lang['dw_friction_factor']='Fator de fricção, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Perda de pressão em uma tubulação de acordo com Hazen-Williams';
$ec_lang['hw_main_title']='Calculadora gratuita online de perda de pressão em uma tubulação de acordo com Hazen-Williams';
$ec_lang['hw_main_desc']='Calculadora de perda de pressão em uma tubulação a dado diâmetro, rugosidade, e vazão de acordo com Hazen-Williams';
$ec_lang['hw_roughness']='Coeficiente de Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canal irregular de acordo com Manning';
$ec_lang['mi_main_title']='Calculadora gratuita online de canal irregular de acordo com Manning';
$ec_lang['mi_main_desc']='Calculadora de canal irregular com escoamento uniforme de acordo com Manning';
$ec_lang['mi_waterSurfaceElevation']='Nível da superfície d\'água';
$ec_lang['mi_q_617']='Q por somação de regiões com n composto de acordo com Chow 6-17 velocidades iguais';
$ec_lang['mi_xSecPoints']='Pontos da seção transversal';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Alt.';
$ec_lang['mi_n']='n<br />do seg-<br />mento';
$ec_lang['mi_is_bank']='Div. de<br />regiões<br />R<sub>h</sub> e Q<br />(Margem)';
$ec_lang['mi_t']='T';
$ec_lang['mi_tau']='Força tang.<br />&tau;';
$ec_lang['mi_a']='A';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_notes']='Notas';
$ec_lang['mi_notes_1_term']='Métodos de calcular Q';
$ec_lang['mi_notes_1_def']='Q por somação de segmentos subestima a contribuição friccional de segmentos com alta declividade transversal. Q por somação de regiões com n composto superestima o efeito da fricção em áreas largas de pouca profundidade no escoamento em áreas mais profundas (canal principal).';
$ec_lang['mi_notes_2_term']='Tamanho mediano de rocha';
$ec_lang['mi_notes_2_def']='O tamanho mediano D<sub>50</sub> de acordo com Strickler é o tamanho (para um canal reto e limpo) implicado pela rugosidade dada. Os outros tamanhos D<sub>50</sub> são os requeridos para resistir à erosão de acordo com 1) o condado de Maricopa County, Arizona, EUA, e Robinson Rock Chutes, 2) Maynord, Ruff, e Abt (1989), e 3) Searcy (1967)';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Vazão Manning em tubulações';
$ec_lang['mpf_main_title']='Calculadora gratuita online da fórmula de Manning para vazão em tubulações';
$ec_lang['mpf_main_desc']='Escoamento uniforme em canais a uma específica declividade e profundidade, utilizando a Fórmula de Manning.';
$ec_lang['mpf_spreadheet_notice']='Confira a versão desta calculadora em planilha';
$ec_lang['mpf_pipe_diameter']='Diâmetro da tubulação, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Coeficiente de Manning (rugosidade), n';
$ec_lang['mpf_friction_slope']='Declividade de pressão (possivelmente <a target="_blank" href="../pressureslope.php">?</a> igual à declividade do tubo), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Percentual da seção utilizado (100% ou 1 se for seção plena)';
$ec_lang['mpf_flow']='Vazão, q';
$ec_lang['mpf_velocity']='Velocidade, v';
$ec_lang['mpf_velocity_head']='Pressão exercida pela velocidade, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Área molhada';
$ec_lang['mpf_wetted_perimeter']='Perímetro molhado';
$ec_lang['mpf_hydraulic_radius']='Raio hidráulico';
$ec_lang['mpf_top_width']='Largura, L';
$ec_lang['mpf_froude_number']='Número de Froude, F';
$ec_lang['mpf_shear_stress']='Tensão cisalhante média (força de tração), tau';
$ec_lang['mpf_solve_for_dd0']='Calcular y/d<sub>0</sub> para um Q dado';
$ec_lang['mpf_solve_desc']='Usando D<sub>0</sub>, n e S<sub>0</sub> do formulário da calculadora, encontra o menor y/d<sub>0</sub> para um Q dado.';
$ec_lang['mpf_solve_button']='Calcular';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Perda de pressão em uma tubulação de acordo com Manning';
$ec_lang['mphl_main_title']='Calculadora gratuita online de perda de carga em uma tubulação de acordo com Manning';
$ec_lang['mphl_main_desc']='A perda de pressão em uma tubulação cheia a dada vazão';
$ec_lang['mphl_pipe_length']='Comprimento da tubulação, l';
$ec_lang['mphl_area']='Área, A';
$ec_lang['mphl_total_junction_k']='Coeficiente total de perda nas juntas, k';
$ec_lang['mphl_friction_slope']='Declividade de fricção, s<sub>f</sub>';
$ec_lang['mphl_friction_loss']='Perdas por fricção';
$ec_lang['mphl_junction_loss']='Perdas nas juntas';
$ec_lang['mphl_total_loss']='Perda total';
$ec_lang['mphl_egl_1']='EGL a jusante';
$ec_lang['mphl_egl_2']='EGL a montante';
$ec_lang['mphl_hgl_2']='HGL a montante no tubo (Ver notas)';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapecial de acordo com Manning';
$ec_lang['mtc_main_title']='Calculadora gratuita online da fórmula de Manning para canal trapecial';
$ec_lang['mtc_main_desc']='Escoamento uniforme Manning em um canal trapecial a dada declividade e profundidade';
$ec_lang['mtc_bottom_width']='Largura da base';
$ec_lang['mtc_side_slope_1']='Declividade do lado 1 (horizontal / vertical)';
$ec_lang['mtc_side_slope_2']='Declividade do lado 2 (horizontal / vertical)';
$ec_lang['mtc_channel_slope']='Declividade do canal (vertical / horizontal)';
$ec_lang['mtc_flow_depth']='Profundidade do escoamento';
$ec_lang['mtc_bend_angle']='Ângulo da curva<a target="_blank" href="riprap-bend-angle.png" title="Clique para ver imagem">?</a> (para o tamanho de rocha)';
$ec_lang['mtc_sgrock']='Gravidade específica da rocha (2.65)';
$ec_lang['mtc_d50_in']='Tamanho de rocha';
$ec_lang['mtc_d50_bottom']='Tamanho de rocha requerido no fundo, D50, Maricopa County <a href="javascript:alert(\'Quando S0 < 2% segundo Isbash (1936) e Maricopa County, Arizona, EUA. Quando S >= 2% segundo Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_z1']='Tamanho de rocha requerido no lado 1, D50, Maricopa County <a href="javascript:alert(\'Quando S0 < 2% segundo Isbash (1936) e Maricopa County, Arizona, EUA. Quando S >= 2% segundo Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_z2']='Tamanho de rocha requerido no lado 2, D50, Maricopa County <a href="javascript:alert(\'Quando S0 < 2% segundo Isbash (1936) e Maricopa County, Arizona, EUA. Quando S >= 2% segundo Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_mra']='Tamanho de rocha requerido, D50, de acordo com Maynord, Ruff, e Abt (1989)';
$ec_lang['mtc_d50_searcy']='Tamanho de rocha requerido, D50, de acordo com Searcy (1967)';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute Design';
$ec_lang['rrc_main_desc']='Planilha de dimensionamento de rampa de pedras Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Vertedor hidráulico simples';
$ec_lang['ws_main_title']='Calculadora de vazão em um vertedor hidráulico simples';
$ec_lang['ws_main_desc']='Calculadora de vazão em um vertedor hidráulico simples';
$ec_lang['ws_weirLength']='Comprimento do vertedor, l';
$ec_lang['ws_headWaterHeight']='Altura da lâmina d\'água a montante, h';
$ec_lang['ws_weirCoefficient']='Coeficiente do vertedor hidráulico, Cw';
$ec_lang['ws_notes_heading']='Notas';
$ec_lang['ws_notes_we_term']='Fórmula de um vertedor';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Vertedor hidráulico irregular';
$ec_lang['wi_main_title']='Calculadora gratuita online de vertedor hidráulico irregular de profundidade variável';
$ec_lang['wi_main_desc']='Calculadora de vazão em um vertedor irregular de profundidade variável';
$ec_lang['wi_headWaterelevation']='Nível da lâmina d\'água a montante';
$ec_lang['wi_weirPoints']='Pontos do vertedor hidráulico';
$ec_lang['wi_station']='Distância';
$ec_lang['wi_elevation']='Nível';
$ec_lang['wi_pondingHeight']='Altura de inundação';
$ec_lang['wi_incrementalFlow']='Vazão incremental';
$ec_lang['wi_cumulativeFlow']='Vazão acumulada';
$ec_lang['wi_save_and_calculate']='Gravar e calcular';
$ec_lang['wi_notes_we_term']='Equação do Vertedor';
$ec_lang['wi_notes_we_def']='q = se (comprimento = 0) então 0 ou se (slope=0) então cw*comprimento*d0<sup>1.5</sup> ou cw/(2.5*pendente) * (d0<sup>2.5</sup> - d1<sup>2.5</sup>) onde d1 e d0 são sempre positivos ou zero';
// Orifice Flow
$ec_lang['or_main_menu']='Vazão por Orifício';
$ec_lang['or_main_title']='Calculadora gratuita de vazão por orifício';
$ec_lang['or_main_desc']='Vazão por Orifício — Livre ou Submersa';
$ec_lang['or_shape']='Forma da abertura';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Retangular';
$ec_lang['or_diameter']='Diâmetro (circular) ou altura (retangular), D';
$ec_lang['or_width']='Largura, W (somente retangular)';
$ec_lang['or_invert']='Cota da soleira da abertura';
$ec_lang['or_hwe']='Nível d\'água a montante';
$ec_lang['or_twe']='Nível d\'água a jusante';
$ec_lang['or_cd']='Coeficiente de descarga, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Cota do centroide';
$ec_lang['or_head']='Carga efetiva, h';
$ec_lang['or_area']='Área da abertura, A';
$ec_lang['or_flow']='Vazão, Q';
$ec_lang['or_regime']='Verificação do regime de orifício';
$ec_lang['or_regime_valid']='Saída livre — regime de orifício válido ✓';
$ec_lang['or_regime_submerged']='Orifício submerso (TWE acima da soleira) — válido ✓';
$ec_lang['or_regime_warn']='Aviso: nível a montante abaixo da crista — não é regime de orifício';
$ec_lang['or_regime_twe_above_hwe']='Aviso: nível de jusante (TWE) acima do nível de montante (HWE) — verifique as entradas';
$ec_lang['or_notes_1_term']='Equação do orifício';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Saída livre: h = HWE &minus; centroide. Escoamento submerso (TWE acima da soleira): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regime de orifício';
$ec_lang['or_notes_2_def']='As equações de orifício aplicam-se quando o nível a montante está acima da crista da abertura. Quando está abaixo, use uma equação de vertedor.';
$ec_lang['or_notes_3_term']='Coeficiente de descarga';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varia de 0,60 a 0,65 para orifícios de borda viva. Entradas arredondadas ou reentrantes têm valores diferentes. Consulte o <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ou o Manual de Referência Hidráulica do HEC-RAS.';
$ec_lang['or_notes_4_term']='Submersão';
$ec_lang['or_notes_4_def']='Quando TWE está acima da soleira da abertura, a calculadora aplica automaticamente a equação de orifício submerso com h = HWE &minus; TWE. Quando TWE é igual ou inferior à soleira, assume-se saída livre e h = HWE &minus; centroide.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Tempo de Esvaziamento por Orifício';
$ec_lang['odt_main_title']='Calculadora Gratuita Online de Tempo de Esvaziamento por Orifício — Lagoa, Bacia ou Tanque';
$ec_lang['odt_main_desc']='Tempo de Esvaziamento de Lagoa ou Bacia por Orifício &mdash; Método do Volume Cônico';
$ec_lang['odt_h1_elev']='Cota inicial da superfície da água';
$ec_lang['odt_a1']='Área inicial da lagoa ou bacia, A1';
$ec_lang['odt_h2_elev']='Cota final da superfície da água';
$ec_lang['odt_h_orifice']='Cota do centroide do orifício';
$ec_lang['odt_a0']='Área da lagoa ou bacia na cota do orifício, A0';
$ec_lang['odt_a_ending']='Área final da lagoa, A2 (interpolada)';
$ec_lang['odt_h2_check']='Verificação da cota final';
$ec_lang['odt_h2_ok']='Cota final acima do topo do orifício ✓';
$ec_lang['odt_h2_warn']='Aviso: cota final igual ou abaixo do topo do orifício (centroide + D/2)';
$ec_lang['odt_d']='Diâmetro do orifício (circular) ou altura (retangular), D';
$ec_lang['odt_w']='Largura do orifício, W (somente retangular)';
$ec_lang['odt_t_sec']='Tempo de esvaziamento (segundos)';
$ec_lang['odt_t_min']='Tempo de esvaziamento (minutos)';
$ec_lang['odt_t_hr']='Tempo de esvaziamento (horas)';
$ec_lang['odt_t_day']='Tempo de esvaziamento (dias)';
$ec_lang['odt_notes_1_term']='Fórmula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) fornece o tempo de esvaziamento da carga H até o orifício. Tempo de esvaziamento = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), onde H<sub>1</sub> = cota inicial &minus; cota do orifício, H<sub>2</sub> = cota final &minus; cota do orifício.';
$ec_lang['odt_notes_2_term']='Método';
$ec_lang['odt_notes_2_def']='O método do volume cônico modela a lagoa ou bacia como uma secção cônica entre a área inicial A<sub>1</sub> na superfície inicial da água e a área A<sub>0</sub> na cota do centroide do orifício. A<sub>2</sub>, a área da lagoa na cota final, é interpolada a partir de A<sub>1</sub> e A<sub>0</sub> usando o modelo de secção cônica. O tempo de esvaziamento da cota inicial até a cota final é igual ao tempo total de esvaziamento de H<sub>1</sub> até o orifício menos o tempo restante de H<sub>2</sub> até o orifício.';
$ec_lang['odt_h1']='Carga inicial, H<sub>1</sub> (WSE &minus; centroide)';
$ec_lang['odt_q_max']='Vazão máxima (inicial), Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume esvaziado';
$ec_lang['odt_sketch_start']='Início';
$ec_lang['odt_sketch_end']='Fim';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Medição de Vazão de Irrigação';
$ec_lang['irr_main_title']='Calculadoras Online Gratuitas de Medição de Vazão de Irrigação';
$ec_lang['irr_main_desc']='Medição de Vazão de Irrigação — Vertedores e Orifícios';
$ec_lang['contact_title']='Contacto com HawsEDC';
$ec_lang['contactSendMessage']='Envie uma mensagem para Tom Haws';
$ec_lang['contactYourName']='Seu nome:';
$ec_lang['contactYourEmail']='Seu endereço de e-mail:';
$ec_lang['contactSubject']='Assunto:';
$ec_lang['contact_message']='Mensagem:';
$ec_lang['contactSpamPrefix']='Five (cinco) plus (e) one (um) equals (são) ';
$ec_lang['contactSpamPostfix']='(Por favor, escreva em inglês com letras. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Enviar Mensagem';
$ec_lang['menu_brand']='Calculadoras HawsEDC';
$ec_lang['essc_btbw']='Largura de margem a margem';
$ec_lang['essc_mcr']='Raio mínimo de curvatura';
$ec_lang['essc_q']='Vazão, Q';
$ec_lang['hw_hgl_1']='HGL a jusante';
$ec_lang['hw_hgl_2']='HGL a montante';
$ec_lang['mi_d50in']='Tamanho<br />mediano<br />de rocha<br />de revestimento';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_groupPoint']='Ponto';
$ec_lang['mi_groupRegion']='Região';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_n617']='n<br />comp.';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_v617']='v';
$ec_lang['mpf_area_ratio']='Área relativa, a/a0';
$ec_lang['mpf_full_flow']='Vazão a seção plena, Q0';
$ec_lang['mpf_full_flow_ratio']='Razão em relação à seção plena, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Este é o escoamento e a profundidade no interior de um tubo <em>infinitamente longo</em>.</dt><dd>Fazer o escoamento entrar no tubo pode exigir uma profundidade de água significativamente maior. Acrescente pelo menos 1,5 vezes a carga de velocidade para obter a profundidade de água a montante ou <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">veja meu tutorial de 2 minutos</a> sobre cálculos padrão de nível de água em bueiros usando HY-8.</dd>';
$ec_lang['mpf_pipe_area']='Área da tubulação, a0';
$ec_lang['mpf_see_notes']='(Ver notas)';
$ec_lang['mphl_note_1']='<dl><dt>Para uma condição de entrada aberta (bueiro), é necessário verificar condições de controle de entrada.</dt><dd>1. O HGL a montante não pode ser inferior à cota de profundidade normal de escoamento a montante (nem inferior ao tubo!).</dd><dd>2. O nível de água a montante de um bueiro é mais bem representado pelo EGL a montante do que pelo HGL a montante.</dd><dd>3. Veja <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">meu tutorial de 2 minutos</a> para cálculos simples de nível de água em bueiros usando HY-8.</dd>';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_n_bathurst']='n para o tamanho de rocha de projeto segundo Bathurst';
$ec_lang['mtc_n_blodgett']='n para o tamanho de rocha de projeto segundo Blodgett';
$ec_lang['mtc_n_strickler']='n para o tamanho de rocha de projeto segundo Strickler';
$ec_lang['mtc_note_1']='<dl><dt>Iteração automatizada de dimensionamento de rocha e rugosidade</dt><dd>Escolha um botão de opção de rugosidade (BB recomendado) e um botão de opção de tamanho de rocha de projeto (Isbash recomendado). Ajuste a profundidade e o fator de segurança do tamanho de rocha para obter o escoamento desejado com um tamanho de rocha inteiro. Toda vez que qualquer valor de entrada é alterado, o seguinte ciclo de iteração ocorre: 1. A rugosidade é calculada a partir do tamanho de rocha de projeto. 2. O cálculo de rugosidade solicitado é copiado para a rugosidade de entrada. 3. O escoamento do canal e o tamanho de rocha requerido são calculados. 4. O tamanho de rocha de projeto é ajustado. 5. Repete até que o erro no tamanho de rocha de projeto seja muito pequeno.</dd><dt>Calculadora básica (sem iteração)</dt><dd>Digite o valor de rugosidade desejado. Ignore a área de entrada do tamanho de rocha de projeto.</dd></dl>';
$ec_lang['or_velocity']='Velocidade na abertura, v';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hidroelétrica';
$ec_lang['mhp_main_title']='Calculadora Gratuita de Potência Micro-Hidroelétrica';
$ec_lang['mhp_main_desc']='Calculadora de Potência de Micro-Hidroelétrica a Fio d\'Água';
$ec_lang['mhp_flow']='Vazão, Q';
$ec_lang['mhp_gross_head']='Altura bruta (desnível), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Perdas de carga na conduta forçada, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Eficiência da instalação, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Altura líquida, H<sub>net</sub>';
$ec_lang['mhp_power']='Potência gerada, P';
$ec_lang['mhp_annual_kwh']='Energia anual a 100% da capacidade';
$ec_lang['mhp_notes_1_term']='Equação de Potência';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, onde &rho; = 1000 kg/m&sup3; (água doce) e g = 9,806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Altura Líquida';
$ec_lang['mhp_notes_2_def']='Altura líquida = altura bruta &minus; perdas de carga na conduta forçada. Uma primeira estimativa comum é h<sub>L</sub> &asymp; 5% de H<sub>gross</sub>. Utilize a <a href="Darcy-Weisbach.php">calculadora de Darcy-Weisbach</a> para estimativas mais precisas das perdas na conduta forçada.';
$ec_lang['mhp_notes_3_term']='Eficiência';
$ec_lang['mhp_notes_3_def']='A eficiência típica da instalação &eta; varia de 0,70 a 0,85 para turbinas Pelton e de fluxo cruzado, comuns em micro-hidroelétricas. Use 0,75 como primeira estimativa conservadora.';
$ec_lang['mhp_notes_4_term']='Energia Anual';
$ec_lang['mhp_notes_4_def']='A energia anual pressupõe operação contínua a plena vazão (8760 horas/ano). A produção real será menor devido à variação sazonal da vazão, paragens para manutenção e fator de carga.';
// Penstock Design
$ec_lang['ps_main_menu']='Dimensionamento de conduta forçada';
$ec_lang['ps_main_title']='Calculadora gratuita online de conduta forçada';
$ec_lang['ps_main_desc']='Dimensionamento de conduta forçada micro-hidráulica — Perda de carga, potência e velocidade';
$ec_lang['ps_flow']='Vazão, Q';
$ec_lang['ps_gross_head']='Altura bruta, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Diâmetro da conduta forçada, D';
$ec_lang['ps_length']='Comprimento da conduta forçada, L';
$ec_lang['ps_roughness']='Rugosidade da tubagem, e';
$ec_lang['ps_km']='Coeficiente de perdas menores, k<sub>m</sub>';
$ec_lang['ps_nu']='Viscosidade cinemática, &nu;, em m<sup>2</sup>/s (1E-6 para água perto de 20&deg;C)';
$ec_lang['ps_efficiency']='Rendimento da instalação, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Velocidade de escoamento, v';
$ec_lang['ps_vel_check']='Verificação da velocidade';
$ec_lang['ps_f']='Fator de atrito, f';
$ec_lang['ps_hf']='Perda de carga por atrito, h<sub>f</sub>';
$ec_lang['ps_hm']='Perda de carga menor, h<sub>m</sub>';
$ec_lang['ps_hl']='Perda total na conduta forçada, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Verificação da perda de carga';
$ec_lang['ps_hnet']='Altura líquida, H<sub>net</sub>';
$ec_lang['ps_power']='Potência produzida, P';
$ec_lang['ps_annual_kwh']='Energia anual a 100% de capacidade';
$ec_lang['ps_vel_ok']='1–3 m/s — dentro do objetivo ✓';
$ec_lang['ps_vel_low']='abaixo de 1 m/s — aumentar o diâmetro ⚠';
$ec_lang['ps_vel_high']='acima de 3 m/s — reduzir o diâmetro ⚠';
$ec_lang['ps_hl_ok']='dentro do objetivo de 10% ✓';
$ec_lang['ps_hl_warn']='supera o objetivo de 10% — considerar tubagem mais larga ⚠';
$ec_lang['ps_hl_bad']='supera 20% — redimensionar a tubagem';
$ec_lang['ps_notes_1_term']='Perda de carga';
$ec_lang['ps_notes_1_def']='Perda total na conduta forçada h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, onde h<sub>f</sub> = f(L/D)(v&sup2;/2g) é a perda por atrito de Darcy-Weisbach e h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g cobre entradas, curvas e válvulas. Altura líquida H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Velocidade';
$ec_lang['ps_notes_2_def']='Objetivo: 1&ndash;3 m/s. Abaixo de 1 m/s a tubagem fica sobredimensionada para a vazão; acima de 3 m/s aumentam as perdas por atrito e o risco de golpe de aríete.';
$ec_lang['ps_notes_3_term']='Objetivo de perda de carga';
$ec_lang['ps_notes_3_def']='Perdas na conduta forçada inferiores a 10% da altura bruta são geralmente económicas. O equilíbrio ótimo entre o custo da tubagem e a potência perdida situa-se frequentemente entre 4&ndash;6% para locais com eletricidade de alto valor.';
$ec_lang['ps_notes_4_term']='Perdas menores k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Valores típicos: entrada com aresta viva 0,5, cada curva a 45&deg; 0,2&ndash;0,3, válvula de gaveta (totalmente aberta) 0,1, válvula borboleta 0,2. Somar todos os acessórios para obter o k<sub>m</sub> total. O valor por defeito 1,5 assume uma entrada e duas curvas.';
$ec_lang['ps_notes_5_term']='Rugosidade da tubagem e';
$ec_lang['ps_notes_5_def']='Rugosidade absoluta típica: aço (novo) 0,046&nbsp;mm, aço (usado) 0,15&nbsp;mm, HDPE 0,003&nbsp;mm, PVC/uPVC 0,0015&nbsp;mm, betão 0,3&ndash;3&nbsp;mm. O HDPE é comum em condutas forçadas de pequenas instalações micro-hidráulicas.';

// About
$ec_lang['about_main_menu']='Sobre';
$ec_lang['about_main_title']='Sobre as calculadoras de engenharia HawsEDC';
$ec_lang['about_main_desc']='Missão, código aberto e contribuições';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Taxa de aplicação — gotejamento/aspersão';
$ec_lang['ds_main_title']='Calculadora gratuita online de taxa de aplicação em irrigação por gotejamento/aspersão';
$ec_lang['ds_main_desc']='Irrigação por gotejamento e aspersão &mdash; taxa de aplicação e uniformidade';
$ec_lang['ds_q_avg']='Vazão média do emissor, q';
$ec_lang['ds_q_min']='Vazão mínima do emissor, q<sub>min</sub>';
$ec_lang['ds_se']='Espaçamento de emissores ao longo do lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='Espaçamento de laterais (espaçamento entre linhas), S<sub>l</sub>';
$ec_lang['ds_n_e']='Emissores por lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Laterais por setor, n<sub>l</sub>';
$ec_lang['ds_d']='Lâmina de aplicação desejada, d';
$ec_lang['ds_a_e']='Área por emissor, A<sub>e</sub>';
$ec_lang['ds_pr']='Taxa de aplicação (intensidade pluviométrica), PR';
$ec_lang['ds_du']='Uniformidade de distribuição, DU';
$ec_lang['ds_du_check']='Verificação de qualidade DU';
$ec_lang['ds_q_lat']='Vazão por lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Vazão do setor, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Tempo de funcionamento para lâmina desejada (horas)';
$ec_lang['ds_du_excellent']='Excelente — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='Bom — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='Aceitável — DU ≥ 70%';
$ec_lang['ds_du_poor']='Ruim — DU < 70% — revisar o projeto ⚠';
$ec_lang['ds_notes_1_term']='Taxa de aplicação';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, onde A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> é a área atendida por cada emissor. Uma taxa de aplicação menor dá mais tempo para infiltração &mdash; importante em solos pesados ou campos inclinados.';
$ec_lang['ds_notes_2_term']='Uniformidade de distribuição (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. DU de 1,0 (100%) significa que todos os emissores têm a mesma vazão. Valores abaixo de 0,80 desperdiçam água nas áreas bem irrigadas deixando pontos mais secos. A uniformidade cai com variação excessiva de pressão ao longo do lateral, desgaste dos emissores ou obstrução parcial.';
$ec_lang['ds_notes_3_term']='Tempo de funcionamento';
$ec_lang['ds_notes_3_def']='Tempo de funcionamento = lâmina desejada &divide; taxa de aplicação. Em solo com declividade ou compactado, divida o tempo em dois ou três ciclos mais curtos com intervalos entre eles para evitar escoamento superficial.';
$ec_lang['irr_intro_html']='<p>Vertedouros e orifícios são as ferramentas de campo padrão para medir o fluxo de água em sistemas de irrigação. Selecione a calculadora que corresponde à sua estrutura:</p>';
$ec_lang['irr_card_weir_uniform_head']='Vertedouro — Crista Larga (Largura Uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Meça o fluxo sobre a crista de uma barragem de desvio, estrutura de controle ou prancha vertedora. Insira o comprimento do vertedouro e a profundidade da água acima da crista.';
$ec_lang['irr_card_weir_irregular_head']='Vertedouro — Perfil Irregular';
$ec_lang['irr_card_weir_irregular_desc']='Use quando a crista do vertedouro não tiver uma elevação uniforme única — vertedouros naturais, estruturas de queda com largura variável ou estruturas de controle de múltiplas seções.';
$ec_lang['irr_card_orifice_head']='Orifício — Comporta de Cabeçal ou Saída de Tubulação';
$ec_lang['irr_card_orifice_desc']='Meça o fluxo através de uma comporta deslizante, saída de tubulação ou abertura de bueiro. Trata automaticamente tanto a descarga livre quanto as condições submersas (contrapressão de jusante).';
$ec_lang['irr_card_canal_head']='Projeto &amp; Análise de Canal';
$ec_lang['irr_card_canal_desc']='Projete ou verifique um canal de irrigação usando a fórmula de Manning. Use a calculadora Trapezoidal para novos canais; a calculadora Irregular para seções naturais ou construídas existentes.';
$ec_lang['irr_card_drip_head']='Projeto de Gotejamento &amp; Aspersão';
$ec_lang['irr_card_drip_desc']='Calcule a taxa de aplicação, uniformidade de distribuição, fluxo lateral, fluxo de zona e tempo de funcionamento para um sistema de irrigação por gotejamento ou aspersão. Insira o fluxo do emissor, o espaçamento e a profundidade alvo.';
$ec_lang['irr_quickref_html']='<h3>Referência Rápida</h3><dl><dt>Barragem de desvio ou estrutura de controle</dt><dd>Meça a profundidade da água acima da crista do vertedouro. Use <a href="Weir-Flow-Simple.php">Vertedouro Simples</a> para uma crista uniforme, ou <a href="Weir-Flow-Irregular.php">Vertedouro Irregular</a> para uma crista perfilada ou escalonada.</dd><dt>Comporta de cabeçal ou saída de tubulação</dt><dd>Meça a elevação da água a montante e a jusante (ou a cota de fundo se a descarga for livre). Use <a href="Orifice.php">Fluxo por Orifício</a>. Para uma tubulação circular, D&nbsp;= diâmetro da tubulação; para uma comporta retangular, insira a largura W e a altura D.</dd><dt>Tempo de esvaziamento de reservatório ou lagoa</dt><dd>Use <a href="Orifice-Drain-Time.php">Tempo de Drenagem por Orifício</a> para estimar quanto tempo leva para baixar o nível de uma lagoa ou reservatório através de um orifício no fundo — útil para o planejamento do armazenamento de irrigação.</dd><dt>Padrões de campo</dt><dd>As equações de fluxo por vertedouro e orifício usadas aqui correspondem aos procedimentos do <em>Manual de Medição de Água</em> (3.ª&nbsp;ed.) do USBR, comumente exigidos por administradores de água e distritos de irrigação.</dd></dl>';
$ec_lang['about_body_html']='<h3>Missão</h3><p>As Calculadoras de Engenharia HawsEDC existem para servir engenheiros e trabalhadores de campo em todo o mundo — especialmente aqueles que trabalham em regiões com escassez de água, recursos limitados ou pouco atendidas. Essas ferramentas fazem parte de uma missão humanitária mais ampla: dizer a cada ser humano da maneira mais prática e eficaz possível que é amado e prezado para sempre, que não tem nada a temer e que não vai arruinar tudo.</p><p>As calculadoras são o veículo. O destino é um mundo livre de sofrimento.</p><h3>Licença de Código Aberto</h3><p>Todo o código é lançado sob a <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licença Pública Geral GNU v3.0 ou posterior</a> — livre como em liberdade. Você pode usar, estudar, modificar e redistribuir o código sob os mesmos termos.</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>Código Fonte</h3><p>O código fonte completo está disponível publicamente no Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Você pode navegar pelo código, registrar problemas ou fazer um fork do repositório lá.</p><h3>Contribuir</h3><p>Pull requests são bem-vindos. Formas de contribuir:</p><ul><li><strong>Traduções</strong> — melhore ou adicione um idioma. Abra um pull request com alterações no arquivo <code>lib/lang.ec.??.php</code> relevante.</li><li><strong>Relatórios de erros</strong> — use o formulário de feedback em qualquer página de calculadora, ou registre um problema no Bitbucket.</li><li><strong>Novas calculadoras</strong> — ideias para ferramentas de engenharia hidráulica que sirvam a trabalhadores de campo e profissionais de irrigação são especialmente bem-vindas. Consulte o guia do desenvolvedor <code>CLAUDE.md</code> no repositório.</li><li><strong>Hospedagem</strong> — se você pode espelhar essas calculadoras para uma região com conectividade limitada, entre em contato.</li></ul><h3>Uso offline</h3><p>Estas calculadoras funcionam como um Aplicativo Web Progressivo (PWA). Visite qualquer página de calculadora enquanto estiver conectado à internet, e seu navegador armazenará automaticamente todas as calculadoras em cache. Depois disso, todas as calculadoras funcionam offline — sem necessidade de internet.</p><p>No Android ou iOS, use a opção "Adicionar à tela inicial" do seu navegador para instalar o EngCalcs como um aplicativo no seu dispositivo. No desktop, procure o ícone de instalação na barra de endereços do seu navegador.</p><p>Você também pode salvar qualquer calculadora individualmente usando o menu "Salvar como&hellip;" do seu navegador para uso offline pontual.</p><h3>Contato</h3><p>Tom Haws — engenheiro hidráulico e autor dessas calculadoras.<br />Use o formulário de feedback em qualquer página de calculadora, ou acesse o código fonte em <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
