<?php

// 简体中文 — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="比例";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="英尺水柱";
$ec_lang['u_ftps']="英尺/秒";
$ec_lang['u_ft']="英尺";
$ec_lang['u_gpm']="加仑/分钟";
$ec_lang['u_gradePercent']="% 坡度";
$ec_lang['u_grade']="坡度";
$ec_lang['u_in2']="平方英寸";
$ec_lang['u_inh2o']="英寸水柱";
$ec_lang['u_in']="英寸";
$ec_lang['u_knpcm2']="千牛/厘米^2";
$ec_lang['u_knpm2']="千牛/米^2";
$ec_lang['u_kpa']="千帕";
$ec_lang['u_lps']="升/秒";
$ec_lang['u_m2']="米^2";
$ec_lang['u_m3ps']="米^3/秒";
$ec_lang['u_mgd']="百万加仑/天";
$ec_lang['u_mh2o']="米水柱";
$ec_lang['u_mld']="百万升/天";
$ec_lang['u_m']="米";
$ec_lang['u_mm2']="毫米^2";
$ec_lang['u_mmh2o']="毫米水柱";
$ec_lang['u_mm']="毫米";
$ec_lang['u_mps']="米/秒";
$ec_lang['u_npm2']="牛/米^2";
$ec_lang['u_pa']="帕";
$ec_lang['u_psf']="磅/英尺^2";
$ec_lang['u_psi']="磅/英寸^2";
$ec_lang['u_s']="秒";
$ec_lang['u_acft']="英亩-英尺";
$ec_lang['u_ft3']="英尺^3";
$ec_lang['u_m3']="米^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='HawsEDC 计算器';
$ec_lang['menu_main_list']='计算器列表';
$ec_lang['menu_main_hydraulics']='水力学';
$ec_lang['menu_main_language']='语言';
$ec_lang['menu_more']='更多';
$ec_lang['template_welcome']='>> 把恐惧留在门外；这里说爱的语言。你没有毁掉一切。同时享用免费的 <a target="_blank" href="https://hawsedc.com/download.php">HawsEDC AutoCAD 工具。</a> <<';
$ec_lang['template_translation_help']='您是否有关于在此处添加计算器的绝妙构想？  您能帮助我改进翻译、编程或托管这些计算器吗？  ';
$ec_lang['template_feedback']='请给我们有价值的建议或嘉许的话。此免费计算器是否在每个方面都超出您的预期？';
$ec_lang['template_printable_title']='可打印标题';
$ec_lang['template_printable_subtitle']='可打印副标题';
$ec_lang['index_title']='免费在线工程计算器';
$ec_lang['calc_set_units']='单位设置：';
$ec_lang['points_data_help']='（或使用数据区域复制/粘贴）';
$ec_lang['points_data_title']='测点数据<br />（逗号或制表符分隔）';
$ec_lang['points_data_copy']='复制';
$ec_lang['points_data_paste']='粘贴';
$ec_lang['calc_inputs']='输入';
$ec_lang['calc_results']='结果';
$ec_lang['view_hide_line']='[隐藏此行]';
$ec_lang['view_printable']='打印版本（刷新页面可恢复）';
$ec_lang['ec_name_label']='保存此计算：';
$ec_lang['ec_name_placeholder']='名称';
$ec_lang['ec_name_hint']='将这些输入值保存到网址中以便书签、历史记录和分享';
$ec_lang['ec_name_invalid']='仅允许字母、数字、空格、– _ .';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='达西-韦斯巴赫管道水头损失';
$ec_lang['dw_main_title']='免费在线达西-韦斯巴赫管道水头损失计算器';
$ec_lang['dw_main_desc']='在给定管径、粗糙度和流量条件下的达西-韦斯巴赫管道水头损失';
$ec_lang['dw_roughness']='达西-韦斯巴赫绝对粗糙度，e';
$ec_lang['dw_kinematic_viscosity']='运动粘度，ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['dw_reynolds_number']='雷诺数，Re';
$ec_lang['dw_flow_regime']='流态';
$ec_lang['dw_regime_laminar']='层流';
$ec_lang['dw_regime_transitional']='过渡流';
$ec_lang['dw_regime_turbulent']='紊流';
$ec_lang['dw_friction_factor_method']='摩阻系数计算方法';
$ec_lang['dw_friction_factor']='摩阻系数，f';
// Hazen-Williams
$ec_lang['hw_main_menu']='哈森-威廉管道水头损失';
$ec_lang['hw_main_title']='免费在线哈森-威廉管道水头损失计算器';
$ec_lang['hw_main_desc']='在给定管径、粗糙度和流量条件下的哈森-威廉管道水头损失';
$ec_lang['hw_hgl_1']='下游测压管水头线';
$ec_lang['hw_hgl_2']='上游测压管水头线';
$ec_lang['hw_roughness']='哈森-威廉系数，C';
// Manning Irregular
$ec_lang['mi_menu']='曼宁不规则明渠';
$ec_lang['mi_main_title']='免费在线曼宁不规则明渠计算器';
$ec_lang['mi_main_desc']='不规则断面明渠曼宁均匀流计算器';
$ec_lang['mi_waterSurfaceElevation']='水面高程';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='横断面测点';
$ec_lang['mi_groupPoint']='测点';
$ec_lang['mi_groupSegment']='分段';
$ec_lang['mi_groupRegion']='分区';
$ec_lang['mi_station']='桩号';
$ec_lang['mi_elevation']='高程';
$ec_lang['mi_d50in']='护坡石<br />材中值<br />粒径';
$ec_lang['mi_n']='分段<br />曼宁<br />n 值';
$ec_lang['mi_is_bank']='R<sub>h</sub>、Q<br />分区边<br />界（岸坡）';
$ec_lang['mi_tau']='底部剪<br />切力<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='综合<br />n 值';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='注释';
$ec_lang['mi_notes_1_term']='综合 n 值';
$ec_lang['mi_notes_1_def']='本计算器依据 HEC-RAS 参考手册，采用 Chow 1959 第 136 页公式 6-17（非 6-18）计算各分区综合 n 值。';
$ec_lang['mi_notes_2_term']='石材护坡';
$ec_lang['mi_notes_2_def']='请使用曼宁梯形渠道计算器进行石材护坡设计。本计算器更适用于天然断面。';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='曼宁管流';
$ec_lang['mpf_main_title']='免费在线曼宁管流计算器';
$ec_lang['mpf_main_desc']='在给定坡度和水深条件下的曼宁公式均匀管流';
$ec_lang['mpf_spreadheet_notice']='查看本计算器的电子表格版本';
$ec_lang['mpf_pipe_diameter']='管径，d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='曼宁粗糙系数，n';
$ec_lang['mpf_friction_slope']='压力坡度线坡度（可能 <a target="_blank" href="../pressureslope.php">?</a> 等于管道坡度），S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='相对水深，y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='（参见注释）';
$ec_lang['mpf_flow']='流量，Q';
$ec_lang['mpf_velocity']='流速，v';
$ec_lang['mpf_velocity_head']='流速水头，h<sub>v</sub>';
$ec_lang['mpf_flow_area']='过水面积，a';
$ec_lang['mpf_pipe_area']='管道断面面积，a0';
$ec_lang['mpf_area_ratio']='面积比，a/a0';
$ec_lang['mpf_wetted_perimeter']='湿周，P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='水力半径，R<sub>h</sub>';
$ec_lang['mpf_top_width']='水面宽，T';
$ec_lang['mpf_froude_number']='弗劳德数，F';
$ec_lang['mpf_shear_stress']='平均剪切力（拖拽力），tau';
$ec_lang['mpf_full_flow']='满流流量，Q0';
$ec_lang['mpf_full_flow_ratio']='流量比，Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>这是<em>无限长</em>管道内部的流量和水深。</dt><dd>使水流进入管道可能需要显著更高的水位。请在水深基础上至少加 1.5 倍流速水头，或 <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">参见 2 分钟教程</a>，了解使用 HY-8 进行标准涵洞水位计算的方法。</dd>';
$ec_lang['mpf_solve_for_dd0']='已知 Q 求 y/d<sub>0</sub>';
$ec_lang['mpf_solve_desc']='使用计算器表单中的 D<sub>0</sub>、n 和 S<sub>0</sub>，求给定 Q 对应的最小 y/d<sub>0</sub>。';
$ec_lang['mpf_solve_button']='求解';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='曼宁管道水头损失';
$ec_lang['mphl_main_title']='免费在线曼宁管道水头损失计算器';
$ec_lang['mphl_main_desc']='在给定满流流量条件下的曼宁公式水头损失';
$ec_lang['mphl_pipe_length']='管道长度，L';
$ec_lang['mphl_area']='面积，A';
$ec_lang['mphl_total_junction_k']='局部损失系数总和，k';
$ec_lang['mphl_friction_slope']='摩擦坡度';
$ec_lang['mphl_friction_loss']='摩擦损失，H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='局部损失，H<sub>m</sub>';
$ec_lang['mphl_total_loss']='总损失，H<sub>l</sub>';
$ec_lang['mphl_egl_1']='下游能量坡降线';
$ec_lang['mphl_egl_2']='上游能量坡降线';
$ec_lang['mphl_hgl_2']='管内上游测压管水头线 ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>对于开口进水口（涵洞）情况，需检验进口控制条件。</dt><dd>1. 上游测压管水头线不得低于上游正常水深处高程（也不得低于管顶！）。</dd><dd>2. 涵洞水位更宜用上游能量坡降线而非测压管水头线表示。</dd><dd>3. <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">参见 2 分钟教程</a>，了解使用 HY-8 进行简单标准涵洞水位计算的方法。</dd>';
// Manning Trapezoid
$ec_lang['mtc_menu']='曼宁梯形渠道';
$ec_lang['mtc_main_title']='免费在线曼宁公式梯形渠道计算器';
$ec_lang['mtc_main_desc']='在给定坡度和水深条件下的曼宁公式均匀梯形渠道流';
$ec_lang['mtc_bottom_width']='渠底宽度，b';
$ec_lang['mtc_side_slope_1']='边坡 1（水平/垂直）';
$ec_lang['mtc_side_slope_2']='边坡 2（水平/垂直）';
$ec_lang['mtc_channel_slope']='渠道坡度，S';
$ec_lang['mtc_flow_depth']='水深，y';
$ec_lang['mtc_bend_angle']='弯道角度 <a target="_blank" href="riprap-bend-angle.png" title="点击查看图片">?</a>（用于石材护坡设计）';
$ec_lang['mtc_sgrock']='石材比重（2.65）';
$ec_lang['mtc_d50_in']='设计石材粒径，D50';
$ec_lang['mtc_n_strickler']='设计石材粒径对应 Strickler 公式 n 值';
$ec_lang['mtc_n_blodgett']='设计石材粒径对应 Blodgett 公式 n 值';
$ec_lang['mtc_n_bathurst']='设计石材粒径对应 Bathurst 公式 n 值';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett 与 Bathurst 比较';
$ec_lang['mtc_d50_bottom']='渠底所需棱角石材粒径，D50（Isbash 与 MC）<span title="依据 Isbash (1936) 及 Maricopa County, Arizona, US。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='边坡 1 所需棱角石材粒径，D50（Isbash 与 MC）<span title="依据 Isbash (1936) 及 Maricopa County, Arizona, US。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='边坡 2 所需棱角石材粒径，D50（Isbash 与 MC）<span title="依据 Isbash (1936) 及 Maricopa County, Arizona, US。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='所需棱角石材粒径，D50（Maynord、Ruff 和 Abt 1989）';
$ec_lang['mtc_d50_searcy']='所需棱角石材粒径，D50（Searcy 1967）';
$ec_lang['mtc_note_1']='<dl><dt>石材粒径与糙率自动迭代</dt><dd>选择糙率单选按钮（推荐 BB）和设计石材粒径单选按钮（推荐 Isbash）。调整水深和石材安全系数，以获得所需流量和均一石材粒径。每次修改输入值时，将触发以下迭代循环：1. 由设计石材粒径计算糙率。2. 所求糙率复制至输入糙率。3. 计算渠道流量和所需石材粒径。4. 调整设计石材粒径。5. 重复直至设计石材粒径误差极小。</dd><dt>基础计算器（无迭代）</dt><dd>直接输入所需糙率值，忽略设计石材粒径输入区域。</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson 石材跌水';
$ec_lang['rrc_main_desc']='Robinson 石材跌水设计电子表格';
// Weir Flow Simple
$ec_lang['ws_main_menu']='简单堰流';
$ec_lang['ws_main_title']='免费在线简单宽顶堰流计算器';
$ec_lang['ws_main_desc']='简单宽顶堰流计算器';
$ec_lang['ws_weirLength']='堰长，l';
$ec_lang['ws_headWaterHeight']='上游水头，h';
$ec_lang['ws_weirCoefficient']='堰流系数，Cw';
$ec_lang['ws_notes_heading']='注释';
$ec_lang['ws_notes_we_term']='堰流方程';
// Weir Flow Irregular
$ec_lang['wi_menu']='不规则堰流';
$ec_lang['wi_main_title']='免费在线分段变深不规则堰流计算器';
$ec_lang['wi_main_desc']='不规则堰流计算器';
$ec_lang['wi_headWaterelevation']='上游水位高程';
$ec_lang['wi_weirPoints']='堰体测点';
$ec_lang['wi_station']='位置';
$ec_lang['wi_elevation']='高程';
$ec_lang['wi_pondingHeight']='蓄水高度';
$ec_lang['wi_incrementalFlow']='分段流量';
$ec_lang['wi_cumulativeFlow']='累计流量';
$ec_lang['wi_save_and_calculate']='保存并计算';
$ec_lang['wi_notes_we_term']='堰流方程';
$ec_lang['wi_notes_we_def']='q = 若（堰长 = 0）则 0，若（坡度=0）则 cw*堰长*d<sub>0</sub><sup>1.5</sup>，否则 cw/(2.5*坡度) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>)，其中 d<sub>1</sub> 和 d<sub>0</sub> 始终为正值或零';
// Orifice Flow
$ec_lang['or_main_menu']='孔口流量';
$ec_lang['or_main_title']='免费在线孔口流量计算器';
$ec_lang['or_main_desc']='孔口流量 — 自由出流或淹没出流';
$ec_lang['or_shape']='孔口形状';
$ec_lang['or_shape_circular']='圆形';
$ec_lang['or_shape_rectangular']='矩形';
$ec_lang['or_diameter']='直径或高度，D <span title="Diameter for circular; height for rectangular" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_width']='宽度，W <span title="Rectangular openings only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_invert']='底部高程 <span title="Bottom of opening" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_hwe']='上游水位高程';
$ec_lang['or_twe']='下游水位高程';
$ec_lang['or_cd']='流量系数，C<sub>d</sub>';
$ec_lang['or_centroid_elev']='形心高程';
$ec_lang['or_head']='有效水头，h';
$ec_lang['or_area']='孔口面积，A';
$ec_lang['or_flow']='流量，Q';
$ec_lang['or_velocity']='流速，v';
$ec_lang['or_regime']='孔口流态检验';
$ec_lang['or_regime_valid']='自由出流 — 孔口流态有效 ✓';
$ec_lang['or_regime_submerged']='淹没孔口（下游水位高于形心）— 有效 ✓';
$ec_lang['or_regime_warn']='警告：上游水位低于孔顶 — 非孔口流态';
$ec_lang['or_regime_twe_above_hwe']='警告：下游水位（TWE）高于上游水位（HWE）— 请检查输入';
$ec_lang['or_notes_1_term']='孔口方程';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh)。自由出流：h = HWE − 形心高程。淹没出流（下游水位高于孔底）：h = HWE − TWE。';
$ec_lang['or_notes_2_term']='孔口流态';
$ec_lang['or_notes_2_def']='当上游水位高于孔口顶部时，适用孔口流量方程。当上游水位低于孔顶时，请改用堰流方程。';
$ec_lang['or_notes_3_term']='流量系数';
$ec_lang['or_notes_3_def']='锐缘孔口的 C<sub>d</sub> 约为 0.60–0.65。圆角或内缩入口的值不同。请参考 <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> 或 HEC-RAS 水力学参考手册。';
$ec_lang['or_notes_4_term']='淹没';
$ec_lang['or_notes_4_def']='当下游水位高于孔口底部时，计算器自动采用淹没孔口方程，h = HWE − TWE。当下游水位等于或低于孔底时，采用自由出流假定，h = HWE − 形心高程。';
// Orifice Drain Time
$ec_lang['odt_main_menu']='孔口排水时间';
$ec_lang['odt_main_title']='免费在线孔口排水时间计算器——池塘、调蓄池或水箱';
$ec_lang['odt_main_desc']='池塘或调蓄池孔口排水时间 — 锥体体积法';
$ec_lang['odt_h1_elev']='初始水面高程 <span title="Starting water surface elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_a1']='初始面积，A<sub>1</sub>';
$ec_lang['odt_h2_elev']='终止水面高程';
$ec_lang['odt_h_orifice']='孔口形心高程';
$ec_lang['odt_a0']='孔口高程处面积，A<sub>0</sub>';
$ec_lang['odt_a_ending']='终止面积，A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_h2_check']='终止高程校验';
$ec_lang['odt_h2_ok']='终止高程高于孔口顶部 ✓';
$ec_lang['odt_h2_warn']='警告：终止高程等于或低于孔口顶部（形心 + D/2）';
$ec_lang['odt_d']='孔口直径 D <span title="Diameter (circular) or height (rectangular)" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_w']='孔口宽度，W <span title="Rectangular only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_t_sec']='排水时间（秒）';
$ec_lang['odt_t_min']='排水时间（分钟）';
$ec_lang['odt_t_hr']='排水时间（小时）';
$ec_lang['odt_t_day']='排水时间（天）';
$ec_lang['odt_notes_1_term']='公式';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) 给出从水头 H 至孔口的排水时间。排水时间 = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)，其中 H<sub>1</sub> = 初始高程 − 孔口高程，H<sub>2</sub> = 终止高程 − 孔口高程。';
$ec_lang['odt_notes_2_term']='方法';
$ec_lang['odt_notes_2_def']='锥体体积法将池塘或调蓄池模型化为初始水面面积 A<sub>1</sub> 与孔口形心高程处面积 A<sub>0</sub> 之间的锥形截面。终止高程处的池塘面积 A<sub>2</sub> 由 A<sub>1</sub> 和 A<sub>0</sub> 按锥形截面模型插值得出。从初始到终止高程的排水时间等于从 H<sub>1</sub> 到孔口的总排水时间减去从 H<sub>2</sub> 到孔口的剩余排水时间。';
$ec_lang['odt_h1']='初始水头，H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_q_max']='最大流量，Q<sub>max</sub>';
$ec_lang['odt_vol']='排出水量';
$ec_lang['odt_sketch_start']='开始';
$ec_lang['odt_sketch_end']='结束';
// Erosion Setback
$ec_lang['essc_btbw']='岸对岸宽度';
$ec_lang['essc_mcr']='最小弯道半径';
$ec_lang['essc_q']='流量，Q';
// Contact

// Irrigation
$ec_lang['irr_main_menu']='灌溉流量测量';
$ec_lang['irr_main_title']='免费在线灌溉流量测量计算器';
$ec_lang['irr_main_desc']='灌溉流量测量 — 堰和孔口';
$ec_lang['contact_title']='HawsEDC 联系';
$ec_lang['contactSendMessage']='给 Tom Haws 发送消息';
$ec_lang['contactYourName']='您的姓名：';
$ec_lang['contactYourEmail']='您的电子邮件地址：';
$ec_lang['contactSubject']='主题：';
$ec_lang['contact_message']='留言：';
$ec_lang['contactSpamPrefix']='五加一等于';
$ec_lang['contactSpamPostfix']='（请用英文拼写。1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6）';
$ec_lang['contactSubmitButton']='发送消息';
$ec_lang['contact_success']='感谢您抽出宝贵的时间来写信。';


// Micro-Hydro Power
$ec_lang['mhp_main_menu']='微型水力发电';
$ec_lang['mhp_main_title']='免费在线微型水力发电计算器';
$ec_lang['mhp_main_desc']='径流式微型水力发电功率计算器';
$ec_lang['mhp_flow']='流量，Q';
$ec_lang['mhp_gross_head']='毛水头，H<sub>gross</sub>';
$ec_lang['mhp_diameter']='压力管道直径，D';
$ec_lang['mhp_length']='压力管道长度，L';
$ec_lang['mhp_roughness']='管道粗糙度，e';
$ec_lang['mhp_km']='局部损失系数，k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_nu']='运动粘度，ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_efficiency']='水电站效率，η（0–1）';
$ec_lang['mhp_velocity']='流速，v';
$ec_lang['mhp_vel_check']='流速校核';
$ec_lang['mhp_f']='摩擦系数，f';
$ec_lang['mhp_hf']='沿程水头损失，h<sub>f</sub>';
$ec_lang['mhp_hm']='局部水头损失，h<sub>m</sub>';
$ec_lang['mhp_hl']='压力管道总损失，h<sub>L</sub>';
$ec_lang['mhp_hl_check']='水头损失校核';
$ec_lang['mhp_hnet']='净水头，H<sub>net</sub>';
$ec_lang['mhp_power']='输出功率，P';
$ec_lang['mhp_annual_kwh']='100% 装机容量下的年发电量';
$ec_lang['mhp_vel_ok']='1–3 m/s — 在目标范围内 ✓';
$ec_lang['mhp_vel_ok_short']='正常';
$ec_lang['mhp_vel_low']='流速过低 — 有泥沙淤积和吸气的风险。';
$ec_lang['mhp_vel_low_short']='低';
$ec_lang['mhp_vel_high']='流速过高 — 有水锤风险和较大的局部损失。';
$ec_lang['mhp_vel_high_short']='高';
$ec_lang['mhp_hl_ok']='在 10% 目标内 ✓';
$ec_lang['mhp_hl_warn']='超过 10% 目标 — 考虑更大管径 ⚠';
$ec_lang['mhp_hl_bad']='超过 20% — 重新核算管道尺寸';
$ec_lang['mhp_notes_1_term']='水头损失';
$ec_lang['mhp_notes_1_def']='总损失 h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>，其中 h<sub>f</sub> = f(L/D)(v²/2g) 为达西-魏斯巴赫沿程摩擦损失，h<sub>m</sub> = k<sub>m</sub>·v²/2g 包含进口、弯管与阀门损失。净水头 H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>。';
$ec_lang['mhp_notes_2_term']='流速';
$ec_lang['mhp_notes_2_def']='目标 1–3 m/s。低于 1 m/s 表明管道过大；高于 3 m/s 将增大摩擦损失和水锤风险。';
$ec_lang['mhp_notes_3_term']='水头损失目标';
$ec_lang['mhp_notes_3_def']='压力管道损失低于毛水头的 10% 一般是经济的。管道费用与损失电量之间的最优权衡通常在高价值发电站约 4–6% 处。';
$ec_lang['mhp_notes_4_term']='局部损失 k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='典型参考值：锐边进口 0.5，每个 45° 弯头 0.2–0.3，闸阀（全开）0.1，蝶阀 0.2。累加所有管件得到总 k<sub>m</sub>。默认值 1.5 假设一个进口和两个弯头。';
$ec_lang['mhp_notes_5_term']='管道粗糙度 e';
$ec_lang['mhp_notes_5_def']='典型绝对粗糙度：钢管（新）0.046 mm，钢管（旧）0.15 mm，HDPE 0.003 mm，PVC/uPVC 0.0015 mm，混凝土 0.3–3 mm。HDPE 常用于小型微水电压力管道。';

// About
$ec_lang['about_main_menu']='关于';
$ec_lang['install_main_menu']='安装';
$ec_lang['install_main_title']='安装 EngCalcs';
$ec_lang['install_main_desc']='添加到您的设备以供离线使用';
$ec_lang['contact_main_menu']='联系';
$ec_lang['about_main_title']='关于 HawsEDC 工程计算器';
$ec_lang['about_main_desc']='使命、开源与贡献';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='滴灌/喷灌灌水强度';
$ec_lang['ds_main_title']='免费在线滴灌/喷灌灌水强度计算器';
$ec_lang['ds_main_desc']='滴灌和喷灌 — 灌水强度与灌水均匀度';
$ec_lang['ds_q_avg']='灌水器平均流量, q';
$ec_lang['ds_q_min']='灌水器最小流量, q<sub>min</sub>';
$ec_lang['ds_se']='灌水器间距，S<sub>e</sub>';
$ec_lang['ds_sl']='支管间距，S<sub>l</sub>';
$ec_lang['ds_n_e']='每条支管灌水器数, n<sub>e</sub>';
$ec_lang['ds_n_l']='每个灌区支管数, n<sub>l</sub>';
$ec_lang['ds_d']='目标灌水深度, d';
$ec_lang['ds_a_e']='每个灌水器控制面积, A<sub>e</sub>';
$ec_lang['ds_pr']='灌水强度，PR';
$ec_lang['ds_du']='灌水均匀度, DU';
$ec_lang['ds_du_check']='DU 质量评估';
$ec_lang['ds_q_lat']='每条支管流量, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='灌区流量, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='运行时间（小时）';
$ec_lang['ds_du_excellent']='优秀 — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='良好 — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='可接受 — DU ≥ 70%';
$ec_lang['ds_du_poor']='差 — DU < 70% — 请检查设计 ⚠';
$ec_lang['ds_notes_1_term']='灌水强度';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>，其中 A<sub>e</sub> = S<sub>e</sub> × S<sub>l</sub> 为每个灌水器控制的面积。较低的灌水强度可为水分入渗提供更多时间 — 在黏重土壤或坡地上尤为重要。';
$ec_lang['ds_notes_2_term']='灌水均匀度（DU）';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>。DU 为 1.0（100%）表示所有灌水器出流完全一致。低于 0.80 的值会在灌水充足区浪费水，同时留下较干燥的区域。均匀度随支管沿线压力变化过大、灌水器磨损或局部堵塞而下降。';
$ec_lang['ds_notes_3_term']='运行时间';
$ec_lang['ds_notes_3_def']='运行时间 = 目标深度 ÷ 灌水强度。在坡地或板结土壤上，将运行时间分成两到三个较短的周期，中间安排休息，以避免地表径流。';

// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='渠道渗漏';
$ec_lang['cs_main_title']='免费在线渠道渗漏损失与输水效率计算器';
$ec_lang['cs_main_desc']='渠道渗漏损失 & 输水效率 — 进出水量差值法';
$ec_lang['cs_Q_in']='入流，Q<sub>in</sub>';
$ec_lang['cs_Q_out']='出流，Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='渗漏损失流量, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='量测检验';
$ec_lang['cs_pct_loss']='损失比例';
$ec_lang['cs_Ec']='输水效率, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='效率等级';
$ec_lang['cs_Vol_day']='日渗漏水量';
$ec_lang['cs_Vol_year']='年渗漏水量';
$ec_lang['cs_L']='渠段长度，L';
$ec_lang['cs_wp']='湿周，P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='单位长度损失，Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='水价值';
$ec_lang['cs_lining_cost']='衬砌成本';
$ec_lang['cs_Ec_target']='衬砌目标，E<sub>c,target</sub> <span title="Conveyance efficiency goal after lining; fraction 0–1" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_lining_area']='衬砌面积，L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='年损失价值';
$ec_lang['cs_annual_value_recovered']='年回收价值';
$ec_lang['cs_lining_total_cost']='衬砌总成本';
$ec_lang['cs_payback_years']='投资回收期 <span title="Simple payback = total lining cost ÷ annual value recovered" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — 检测到渗漏 ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — 无可测损失';
$ec_lang['cs_loss_negative']='警告：Qout > Qin — 请检查量测数据 ⚠';
$ec_lang['cs_Ec_good']='良好 — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='一般 — Ec 60–80%';
$ec_lang['cs_Ec_poor']='差 — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='方法';
$ec_lang['cs_notes_1_def']='进出水量差值法通过测量渠段首尾流量来估算渗漏量：Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>。输水效率 E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>。年渗漏量按全年满流连续运行计算；季节性或非满流渠道的实际损失将低于此值。';
$ec_lang['cs_notes_2_term']='效率等级';
$ec_lang['cs_notes_2_def']='典型土渠（无衬砌）：E<sub>c</sub> = 60–80%。维护良好的土渠：75–85%。混凝土衬砌渠道：90–98%。渗漏损失超过入流量 30% 时，通常值得投资进行渠道衬砌。（美国垦务局、联合国粮农组织）';
$ec_lang['cs_notes_3_term']='衬砌投资回收';
$ec_lang['cs_notes_3_def']='输入任意统一货币单位的水价值和衬砌成本。衬砌面积 = 渠段长度 × 湿周 — 渠道横截面在量测流量水深处的湿周（底宽加两侧湿润坡面）。年回收价值按衬砌渠道持续达到目标 E<sub>c</sub> 计算。季节性渠道或衬砌未达目标效率的实际投资回收期将更长。';
$ec_lang['cs_notes_4_term']='参考文献';
$ec_lang['cs_notes_4_def']='美国垦务局《量水手册》第3版（2001年）。联合国粮农组织灌溉与排水文件第57号（1999年）。';

$ec_lang['irr_intro_html']='<p>量水堰和孔口是测量灌溉系统水流量的标准现场工具。请选择与您的水工建筑物相匹配的计算器：</p>';
$ec_lang['irr_card_weir_uniform_head']='量水堰 — 宽顶堰（均匀宽度）';
$ec_lang['irr_card_weir_uniform_desc']='测量引水坝堰顶、控制建筑物或堰板的过流量。输入堰长和堰顶以上水深。';
$ec_lang['irr_card_weir_irregular_head']='量水堰 — 不规则断面';
$ec_lang['irr_card_weir_irregular_desc']='当堰顶高程不统一时使用——天然溢洪道、宽度变化的跌水建筑物或多段控制建筑物。';
$ec_lang['irr_card_orifice_head']='孔口 — 闸门或管道出水口';
$ec_lang['irr_card_orifice_desc']='测量通过闸门、管道出水口或涵洞开口的流量。自动处理自由出流和淹没（下游顶托）两种情况。';
$ec_lang['irr_card_canal_head']='渠道设计 & 分析';
$ec_lang['irr_card_canal_desc']='使用曼宁公式设计或核算灌溉渠道。新建渠道使用梯形断面计算器；已有天然或人工断面使用不规则断面计算器。';
$ec_lang['irr_card_drip_head']='滴灌 & 喷灌设计';
$ec_lang['irr_card_drip_desc']='计算滴灌或喷灌系统的灌水强度、分布均匀度、支管流量、轮灌区流量和灌水时间。输入灌水器流量、间距和设计灌水深度。';
$ec_lang['irr_card_seepage_head']='渠道渗漏 & 输水效率';
$ec_lang['irr_card_seepage_desc']='利用渠段进出水量测量数据估算渠道渗漏损失。计算输水效率和年渗漏水量，为渠道衬砌投资决策提供依据。';
$ec_lang['irr_quickref_html']='<h3>快速参考</h3><dl><dt>引水坝或控制建筑物</dt><dd>测量堰顶以上水深。均匀堰顶使用 <a href="Weir-Flow-Simple.php">简单量水堰</a>，异形或阶梯型堰顶使用 <a href="Weir-Flow-Irregular.php">不规则量水堰</a>。</dd><dt>闸门或管道出水口</dt><dd>测量上游水位和下游水位（自由出流时测管道底部高程）。使用 <a href="Orifice.php">孔口流量</a>。圆形管道 D = 管径；矩形闸门输入宽度 W 和高度 D。</dd><dt>水库或池塘排空时间</dt><dd>使用 <a href="Orifice-Drain-Time.php">孔口排空时间</a> 估算池塘或水库通过底部孔口降低水位所需时间——适用于灌溉调蓄规划。</dd><dt>现场标准</dt><dd>本站量水堰和孔口流量方程符合美国垦务局（USBR）<em>量水手册</em>（第3版）规程，通常为水资源管理机构和灌区所要求。</dd></dl>';
$ec_lang['about_body_html']='<h3>使命</h3><p>HawsEDC 工程计算器旨在为全球工程师和现场工作者服务——尤其是在缺水、资源匮乏或服务不足地区工作的人。这些工具是更广泛人道主义使命的一部分：以最实际、最有效的方式告诉每一个人，他们永远是被爱和珍视的，他们不必害怕，也不会毁掉一切。</p><p>计算器是载体，目标是一个没有苦难的世界。</p><h3>开源许可证</h3><p>所有代码均在 <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU 通用公共许可证 v3.0 或更高版本</a>下发布——自由如自由本身。您可以在相同条款下使用、研究、修改和再分发代码。</p><p>版权所有 © 2009–2026 Thomas Gail Haws。</p><h3>源代码</h3><p>完整源代码在 Bitbucket 上公开提供：</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>您可以在那里浏览代码、提交问题或 fork 仓库。</p><h3>参与贡献</h3><p>欢迎提交 Pull Request。贡献方式：</p><ul><li><strong>翻译</strong> — 改进或新增语言。提交包含相关 <code>lib/lang.ec.??.php</code> 文件修改的 Pull Request。</li><li><strong>错误报告</strong> — 使用任意计算器页面上的反馈表单，或在 Bitbucket 上提交问题。</li><li><strong>新计算器</strong> — 特别欢迎为现场工作者和灌溉从业者服务的水力工程工具创意。请参阅仓库中的开发者指南 <code>CLAUDE.md</code>。</li><li><strong>托管镜像</strong> — 如果您能为连接受限地区提供镜像服务，欢迎联系我们。</li></ul><h3>离线使用</h3><p>这些计算器可作为渐进式网络应用（PWA）运行。在联网状态下访问任意计算器页面，您的浏览器将自动缓存所有计算器。此后，所有计算器均可离线使用——无需网络连接。</p><p>在 Android 或 iOS 上，使用浏览器的"添加到主屏幕"功能，将 EngCalcs 作为应用安装到您的设备上。在桌面端，请在浏览器地址栏中找到安装图标。</p><p>您也可以使用浏览器的"另存为…"菜单保存任意单个计算器，以便临时离线使用。</p><h3>联系方式</h3><p>Tom Haws——水力工程师，这些计算器的作者。<br />请使用任意计算器页面上的反馈表单，或访问 <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> 上的源代码。</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='块石陡槽设计（Robinson）';
$ec_lang['rc_main_title']='免费在线块石陡槽设计计算器 — Robinson (1998)';
$ec_lang['rc_main_desc']='块石陡槽护坡块石尺寸设计 — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='陡槽底坡, S<sub>0</sub>';
$ec_lang['rc_qt']='总单宽流量, q<sub>t</sub> <span title="陡槽进口处单宽流量。对于底宽为 B、总流量为 Q 的渠道，取 q_t = Q / B。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='护坡孔隙率, n<sub>p</sub>';
$ec_lang['rc_sg']='岩石比重, sg <span title="典型碎花岗岩或玄武岩 ≈ 2.65。Robinson 有效范围：2.54 至 2.82。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='级配标准差 SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="级配标准差。均匀块石 ≈ 1.25。Robinson 有效范围：1.15 至 1.47。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='进口渠道正常水深, y<sub>n</sub> <span title="积水（Hp > yn）有利——减少上游冲刷。（USDA）" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='所需中值块石粒径, D<sub>50</sub> <span title="公式 1（S0 < 0.10）或公式 2（0.10–0.40）。适用范围：D50 15–278 mm，S0 0.02–0.40。超出范围时为外推值。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='所用公式';
$ec_lang['rc_sg_check']='比重检验';
$ec_lang['rc_SD_check']='级配标准差检验';
$ec_lang['rc_sg_ok']   ='sg 在有效范围内（2.54–2.82）✓';
$ec_lang['rc_sg_low']  ='警告：sg < 2.54 — 低于 Robinson 有效范围';
$ec_lang['rc_sg_high'] ='警告：sg > 2.82 — 高于 Robinson 有效范围';
$ec_lang['rc_SD_ok']   ='SD 在有效范围内（1.15–1.47）✓';
$ec_lang['rc_SD_low']  ='警告：SD < 1.15 — 低于 Robinson 有效范围';
$ec_lang['rc_SD_high'] ='警告：SD > 1.47 — 高于 Robinson 有效范围';
$ec_lang['rc_layer']='块石层厚度（2 × D<sub>50</sub>）';
$ec_lang['rc_crest_radius']='顶部堰顶曲线半径（40 × D<sub>50</sub>）';
$ec_lang['rc_crest_length']='顶部堰顶曲线弧长';
$ec_lang['rc_apron_length']='出口护坦长度（15 × D<sub>50</sub>）<span title="为确保陡槽块石的结构稳定性所必须的护坦长度。"出口段和下游渠道阻力所产生的最小尾水足以确保出口段护坡的稳定性。"（Robinson）" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='陡槽曼宁糙率, n';
$ec_lang['rc_Vm']='通过块石层的流速, V<sub>m</sub> <span title="流经岩石孔隙的 qt 比例。其余 qs 在表面流动。默认 np = 0.45（适用于棱角形碎石）。" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='通过块石层的单宽流量, q<sub>m</sub>';
$ec_lang['rc_qs']='表面单宽流量, q<sub>s</sub>（q<sub>t</sub> − q<sub>m</sub>）';
$ec_lang['rc_d']='护坡表面以上水深, d';
$ec_lang['rc_Hp']='进口堰顶水头, H<sub>p</sub> <span title="积水（Hp > yn）有利——减少上游冲刷。（USDA）" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='进口积水检验';
$ec_lang['rc_pond_ok']  ='Hp > yn — 上游积水 ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — 无积水 — 检查进口是否发生冲刷';
$ec_lang['rc_eq1']='公式 1（S0 < 0.10）— 缓坡';
$ec_lang['rc_eq2']='公式 2（0.10 ≤ S0 ≤ 0.40）— 陡坡';
$ec_lang['rc_eq_warn_low']='警告：S0 < 0.02 — 低于 Robinson 验证范围';
$ec_lang['rc_eq_warn_high']='警告：S0 > 0.40 — 高于 Robinson 验证范围';
$ec_lang['rc_notes_1_term']='块石尺寸公式';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) 根据陡槽坡度和单宽流量，建立了两个计算护坡中值粒径 D<sub>50</sub> 的经验公式。公式 1 适用于缓坡（S<sub>0</sub> < 0.10）；公式 2 适用于陡坡（0.10 ≤ S<sub>0</sub> ≤ 0.40）。两个公式均要求 q<sub>t</sub> 的单位为 m²/s，输出 D<sub>50</sub> 单位为 mm。经验证范围为 0.02 ≤ S<sub>0</sub> ≤ 0.40。';
$ec_lang['rc_notes_2_term']='单宽流量';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> 为陡槽堰顶处的总单宽流量（单位宽度上的总流量）。对于底宽为 B、总流量为 Q 的渠道，可近似取 q<sub>t</sub> ≈ Q / B，或由陡槽进口的临界水深条件计算得出。';
$ec_lang['rc_notes_3_term']='通过块石层的水流';
$ec_lang['rc_notes_3_def']='总流量的一部分流经护坡岩石孔隙（层内流 q<sub>m</sub>）；其余部分在岩石表面流动（q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>）。表面水深 d 由曼宁方程根据陡槽糙率 n 对表面流量 q<sub>s</sub> 求解得出。默认孔隙率 n<sub>p</sub> = 0.45，适用于棱角形碎石。';
$ec_lang['rc_notes_5_term']='有效块石粒径范围';
$ec_lang['rc_notes_5_def']='该公式的开发数据中 D<sub>50</sub> 范围为 15 mm 至 278 mm。超出此范围的计算结果为外推值，使用时应结合额外的工程判断。';
$ec_lang['rc_notes_6_term']='出口护坦高程';
$ec_lang['rc_notes_6_def']='出口段护坡顶面高程应不高于下游渠道底高程。若高于下游河床，出口块石将不稳定。';
$ec_lang['rc_notes_7_term']='进口积水检验';
$ec_lang['rc_notes_7_def']='当进口渠道正常水深小于通过 q<sub>t</sub> 所需的堰顶水头（H<sub>p</sub>）时，进口护坦上游将出现壅水或积水。这通常是可接受的——积水可降低流速，防止上游冲刷。检验方法：使用量水堰计算器，根据给定的 q<sub>t</sub> 和堰顶宽度求 H<sub>p</sub>，并与进口渠道正常水深比较。若 H<sub>p</sub> 超过正常水深，则将发生积水。';
$ec_lang['rc_notes_4_term']='参考文献';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS 亦发布了基于同一方法的 <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel 计算表</a>。';
// Sketch labels
$ec_lang['rc_sketch_filter']          = '过滤层';
$ec_lang['rc_sketch_top_crest_curve'] = '顶部曲线';
$ec_lang['rc_sketch_outlet_apron']    = '出口护坦';
$ec_lang['rc_sketch_radius']          = '半径';

// Manning Trapezoid — velocity checks and note 2 (added)
$ec_lang['mtc_vel_check']='流速校核';
$ec_lang['mtc_vel_ok']='流速在均匀流假设范围内合理。';
$ec_lang['mtc_vel_ok_short']='正常';
$ec_lang['mtc_vel_high']='流速偏高 — 检查过渡段损失和可用能量。';
$ec_lang['mtc_vel_high_short']='偏高';
$ec_lang['mtc_vel_low']='流速偏低 — 有泥沙淤积风险。';
$ec_lang['mtc_vel_low_short']='偏低';
$ec_lang['mtc_note_2_term']='流速校核';
$ec_lang['mtc_note_2_def']='高流速意味着来自可用落差的高比能。该能量可在扩大段、弯道或障碍处迅速耗散。请验证这对于该场地是否合理。';

// Micro-Hydro Power — notes 6 and 7 (added)
$ec_lang['mhp_notes_6_term']='效率';
$ec_lang['mhp_notes_6_def']='微水电中常用的 Pelton 和贯流式水轮机典型机组效率 &eta; 为 0.70 至 0.85。保守起见，初步估算可取 0.75。';
$ec_lang['mhp_notes_7_term']='年发电量';
$ec_lang['mhp_notes_7_def']='年发电量假设全年满负荷连续运行（8760 小时/年）。实际发电量将因季节性流量变化、维护停机和负荷因子而偏低。';
