<?php

// Kiswahili — All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='sehemu';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sek';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% kupanda/kutembea';
$ec_lang['u_grade']='kupanda/kutembea';
$ec_lang['u_in2']='in^2';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/sek';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/sek';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/siku';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/sek';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sek';
$ec_lang['u_acft']='ekari-futi';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Vikokotoo vya HawsEDC';
$ec_lang['menu_main_list']='Orodha ya Vikokotoo';
$ec_lang['menu_main_hydraulics']='Majimajii';
$ec_lang['menu_main_language']='Lugha';
$ec_lang['template_welcome']='&gt;&gt; Acha wasiwasi wako mlangoni; hapa upendo unasemwa. Furahia <a href="https://hawsedc.com/download.php">zana za bure za HawsEDC AutoCAD</a> pia. &lt;&lt;';
$ec_lang['template_translation_help']='Je, una wazo zuri la kikokotoo cha kuongeza hapa? Je, unaweza kunisaidia kuboresha tafsiri, kupanga programu, au kuweka vikokotoo hivi?  ';
$ec_lang['template_feedback']='Tafadhali tupe maoni yako ya thamani au sifa. Je, kikokotoo hiki cha bure kilivuka matarajio yako kwa kila njia?';
$ec_lang['template_printable_title']='Kichwa cha Kuchapishwa';
$ec_lang['template_printable_subtitle']='Kichwa Kidogo cha Kuchapishwa';
$ec_lang['index_title']='Vikokotoo vya Uhandisi Bure Mtandaoni';
$ec_lang['calc_set_units']='Weka vitengo:';
$ec_lang['points_data_help']='(au Nakili/Bandika ukitumia eneo la data)';
$ec_lang['points_data_title']='Data za vituo<br />(kwa mkato au kichupo)';
$ec_lang['points_data_copy']='Nakili';
$ec_lang['points_data_paste']='Bandika';
$ec_lang['calc_inputs']='Maingizo';
$ec_lang['calc_results']='Matokeo';
$ec_lang['view_hide_line']='[Ficha mstari huu]';
$ec_lang['view_printable']='Toleo la kuchapishwa (pakia upya ili kurejesha)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Upotevu wa Kichwa cha Bomba la Darcy-Weisbach';
$ec_lang['dw_main_title']='Kikokotoo cha Bure Mtandaoni cha Upotevu wa Kichwa cha Bomba la Darcy-Weisbach';
$ec_lang['dw_main_desc']='Upotevu wa Kichwa cha Bomba la Darcy-Weisbach kwa Kipenyo, Ukakamavu, na Mtiririko Uliowekwa';
$ec_lang['dw_roughness']='Ukakamavu kamili wa Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Mnato wa kinematik, v, katika m<sup>2</sup>/sek (1E-6 kwa maji safi kwenye joto la chumba)';
$ec_lang['dw_reynolds_number']='Nambari ya Reynolds, Re';
$ec_lang['dw_flow_regime']='Utaratibu wa mtiririko';
$ec_lang['dw_regime_laminar']='lamlam';
$ec_lang['dw_regime_transitional']='mpito';
$ec_lang['dw_regime_turbulent']='msukosuko';
$ec_lang['dw_friction_factor_method']='Njia ya kipengele cha msuguano';
$ec_lang['dw_friction_factor']='Kipengele cha msuguano, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Upotevu wa Kichwa cha Bomba la Hazen-Williams';
$ec_lang['hw_main_title']='Kikokotoo cha Bure Mtandaoni cha Upotevu wa Kichwa cha Bomba la Hazen-Williams';
$ec_lang['hw_main_desc']='Upotevu wa Kichwa cha Bomba la Hazen-Williams kwa Kipenyo, Ukakamavu, na Mtiririko Uliowekwa';
$ec_lang['hw_hgl_1']='HGL ya Chini ya Mkondo';
$ec_lang['hw_hgl_2']='HGL ya Juu ya Mkondo';
$ec_lang['hw_roughness']='Mgawo wa Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Mfereji Usio wa Kawaida wa Manning';
$ec_lang['mi_main_title']='Kikokotoo cha Bure Mtandaoni cha Mfereji Usio wa Kawaida wa Manning';
$ec_lang['mi_main_desc']='Kikokotoo cha Mtiririko Sawia wa Mfereji Usio wa Kawaida wa Manning';
$ec_lang['mi_waterSurfaceElevation']='Kiwango cha uso wa maji';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Vituo vya mkato mtambazi';
$ec_lang['mi_groupPoint']='Kituo';
$ec_lang['mi_groupSegment']='Sehemu';
$ec_lang['mi_groupRegion']='Eneo';
$ec_lang['mi_station']='Stn';
$ec_lang['mi_elevation']='Urefu';
$ec_lang['mi_d50in']='Ukingo<br />ukubwa<br />wa jiwe<br />wastani';
$ec_lang['mi_n']='n kwa<br />sehemu';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />mpaka wa<br />eneo<br />(Ukingo)';
$ec_lang['mi_tau']='Msongo<br />wa chini<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />mchanganyiko';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Maelezo';
$ec_lang['mi_notes_1_term']='n mchanganyiko';
$ec_lang['mi_notes_1_def']='Kikokotoo hiki kinafuata Mwongozo wa Marejeleo wa HEC-RAS katika kuhesabu n mchanganyiko wa eneo ukitumia Chow 1959, ukurasa 136, mlinganyo 6-17 (si 6-18).';
$ec_lang['mi_notes_2_term']='Ukingo wa jiwe';
$ec_lang['mi_notes_2_def']='Tumia Kikokotoo cha Mfereji wa Trapezoidi wa Manning kubuni ukingo wa jiwe. Kikokotoo hiki kinafaa zaidi kwa sehemu za asili.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Mtiririko wa Bomba la Manning';
$ec_lang['mpf_main_title']='Kikokotoo cha Bure Mtandaoni cha Mtiririko wa Bomba la Manning';
$ec_lang['mpf_main_desc']='Mtiririko Sawia wa Bomba la Fomula ya Manning kwa Mteremko na Kina Kilichowekwa';
$ec_lang['mpf_spreadheet_notice']='Angalia toleo la lahajedwali la kikokotoo hiki';
$ec_lang['mpf_pipe_diameter']='Kipenyo cha bomba, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Ukakamavu wa Manning, n';
$ec_lang['mpf_friction_slope']='Mteremko wa shinikizo (labda <a target="_blank" href="../pressureslope.php">?</a> sawa na mteremko wa bomba), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Uwiano wa kina cha mtiririko, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Angalia maelezo)';
$ec_lang['mpf_flow']='Mtiririko, Q';
$ec_lang['mpf_velocity']='Kasi, v';
$ec_lang['mpf_velocity_head']='Kichwa cha kasi, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Eneo la mtiririko, a';
$ec_lang['mpf_pipe_area']='Eneo la bomba, a0';
$ec_lang['mpf_area_ratio']='Uwiano wa eneo, a/a0';
$ec_lang['mpf_wetted_perimeter']='Mzingo ulioloweshwa, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Radi ya majimajii, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Upana wa juu, T';
$ec_lang['mpf_froude_number']='Nambari ya Froude, F';
$ec_lang['mpf_shear_stress']='Msongo wastani wa kukata (nguvu ya kukokota), tau';
$ec_lang['mpf_full_flow']='Mtiririko kamili, Q0';
$ec_lang['mpf_full_flow_ratio']='Uwiano wa mtiririko kamili, Q/Q0';
$ec_lang['mpf_note_1']='<p>Maelezo:</p><dl><dt>Huu ni mtiririko na kina ndani ya bomba la <em>urefu usio na kikomo</em>.</dt><dd>Kuingiza mtiririko kwenye bomba kunaweza kuhitaji kina cha maji juu ya mlango kinachozidi zaidi. Ongeza angalau mara 1.5 ya kichwa cha kasi ili kupata kina hicho, au <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">tazama mafunzo yangu ya dakika 2</a> kwa mahesabu ya kawaida ya kichwa cha maji ya bomba la kupita ukitumia HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Suluhisha y/d<sub>0</sub> ikitolewa Q';
$ec_lang['mpf_solve_desc']='Ukitumia D<sub>0</sub>, n, na S<sub>0</sub> kutoka kwa fomu ya kikokotoo, inapata y/d<sub>0</sub> ya chini kabisa kwa Q iliyopewa.';
$ec_lang['mpf_solve_button']='Suluhisha';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Upotevu wa Kichwa cha Bomba la Manning';
$ec_lang['mphl_main_title']='Kikokotoo cha Bure Mtandaoni cha Upotevu wa Kichwa cha Bomba la Manning';
$ec_lang['mphl_main_desc']='Upotevu wa Kichwa wa Fomula ya Manning kwa Mtiririko Kamili Uliowekwa';
$ec_lang['mphl_pipe_length']='Urefu wa bomba, L';
$ec_lang['mphl_area']='Eneo, A';
$ec_lang['mphl_total_junction_k']='Jumla ya mgawo wa hasara ya makutano, k';
$ec_lang['mphl_friction_slope']='Mteremko wa msuguano';
$ec_lang['mphl_friction_loss']='Hasara ya msuguano, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Hasara ya makutano, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Hasara jumla, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL ya Chini ya Mkondo';
$ec_lang['mphl_egl_2']='EGL ya Juu ya Mkondo';
$ec_lang['mphl_hgl_2']='HGL ya Juu ya Mkondo katika bomba ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<p>Maelezo:</p><dl><dt>Kwa hali ya mlango wazi (bomba la kupita), ni lazima kukagua hali za udhibiti wa mlango.</dt><dd>1. HGL ya juu ya mkondo haiwezi kuwa chini ya kiwango cha mtiririko wa kina cha kawaida cha juu ya mkondo (wala chini ya bomba!).</dd><dd>2. Kichwa cha maji ya bomba la kupita kinawakilishwa vizuri zaidi na EGL ya juu ya mkondo kuliko HGL ya juu ya mkondo.</dd><dd>3. Tazama <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">mafunzo yangu ya dakika 2</a> kwa mahesabu rahisi ya kawaida ya kichwa cha maji ya bomba la kupita ukitumia HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Mfereji wa Trapezoidi wa Manning';
$ec_lang['mtc_main_title']='Kikokotoo cha Bure Mtandaoni cha Mfereji wa Trapezoidi wa Fomula ya Manning';
$ec_lang['mtc_main_desc']='Mtiririko Sawia wa Mfereji wa Trapezoidi wa Fomula ya Manning kwa Mteremko na Kina Vilivyowekwa';
$ec_lang['mtc_bottom_width']='Upana wa chini, b';
$ec_lang['mtc_side_slope_1']='Mteremko wa upande 1 (usawa/wima)';
$ec_lang['mtc_side_slope_2']='Mteremko wa upande 2 (usawa/wima)';
$ec_lang['mtc_channel_slope']='Mteremko wa mfereji, S';
$ec_lang['mtc_flow_depth']='Kina cha mtiririko, y';
$ec_lang['mtc_bend_angle']='Pembe ya Kona <a target="_blank" href="riprap-bend-angle.png" title="Bonyeza kwa picha">?</a> (kwa upangaji wa riprap)';
$ec_lang['mtc_sgrock']='Uzito maalum wa jiwe (2.65)';
$ec_lang['mtc_d50_in']='Ukubwa wa jiwe la kubuni, D50';
$ec_lang['mtc_n_strickler']='n kwa ukubwa wa jiwe la kubuni kulingana na Strickler';
$ec_lang['mtc_n_blodgett']='n kwa ukubwa wa jiwe la kubuni kulingana na Blodgett';
$ec_lang['mtc_n_bathurst']='n kwa ukubwa wa jiwe la kubuni kulingana na Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett dhidi ya Bathurst';
$ec_lang['mtc_d50_bottom']='Ukubwa wa jiwe la pembe unaohitajika chini, D50 (Isbash na MC) <a href="javascript:alert(\'Kulingana na Isbash (1936) na Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z1']='Ukubwa wa jiwe la pembe unaohitajika kwa mteremko wa upande 1, D50 (Isbash na MC) <a href="javascript:alert(\'Kulingana na Isbash (1936) na Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z2']='Ukubwa wa jiwe la pembe unaohitajika kwa mteremko wa upande 2, D50 (Isbash na MC) <a href="javascript:alert(\'Kulingana na Isbash (1936) na Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_mra']='Ukubwa wa jiwe la pembe unaohitajika, D50 (Maynord, Ruff, na Abt 1989)';
$ec_lang['mtc_d50_searcy']='Ukubwa wa jiwe la pembe unaohitajika, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<p>Maelezo:</p><dl><dt>Upangaji wa kiotomatiki wa ukubwa wa jiwe na ukakamavu</dt><dd>Chagua kitufe cha redio cha ukakamavu (BB inapendekezwa) na kitufe cha redio cha ukubwa wa jiwe la kubuni (Isbash inapendekezwa). Rekebisha kina na kipengele cha usalama wa ukubwa wa jiwe ili kupata mtiririko unaotakiwa kwa ukubwa sawa wa jiwe. Kila wakati unabadilisha thamani yoyote ya ingizo, mzunguko ufuatao wa upangaji hutokea: 1. Ukakamavu huhesabiwa kutoka kwa ukubwa wa jiwe la kubuni. 2. Hesabu ya ukakamavu ulioombwa hucopiwa kwenye ukakamavu wa ingizo. 3. Mtiririko wa mfereji na ukubwa wa jiwe unaohitajika huhesabiwa. 4. Ukubwa wa jiwe la kubuni hurekebishwa. 5. Rudia hadi hitilafu ya ukubwa wa jiwe la kubuni iwe ndogo sana.</dd><dt>Kikokotoo cha msingi (bila upangaji)</dt><dd>Ingiza thamani yako ya ukakamavu inayotakiwa. Puuza eneo la ingizo la ukubwa wa jiwe la kubuni.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Teremko la Mawe la Robinson';
$ec_lang['rrc_main_desc']='Lahajedwali la Kubuni Teremko la Mawe la Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Mtiririko wa Bwawa Rahisi';
$ec_lang['ws_main_title']='Kikokotoo cha Bure Mtandaoni cha Mtiririko wa Bwawa la Matawi-pana Rahisi';
$ec_lang['ws_main_desc']='Kikokotoo cha Mtiririko wa Bwawa la Matawi-pana Rahisi';
$ec_lang['ws_weirLength']='Urefu wa bwawa, l';
$ec_lang['ws_headWaterHeight']='Urefu wa maji juu ya mlango, h';
$ec_lang['ws_weirCoefficient']='Mgawo wa bwawa, Cw';
$ec_lang['ws_notes_heading']='Maelezo';
$ec_lang['ws_notes_we_term']='Mlinganyo wa Bwawa';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Mtiririko wa Bwawa Usio wa Kawaida';
$ec_lang['wi_main_title']='Kikokotoo cha Bure Mtandaoni cha Mtiririko wa Bwawa Usio wa Kawaida wa Sehemu, Kina Kinachobadilika';
$ec_lang['wi_main_desc']='Kikokotoo cha Mtiririko wa Bwawa Usio wa Kawaida';
$ec_lang['wi_headWaterelevation']='Kiwango cha maji juu ya mlango';
$ec_lang['wi_weirPoints']='Vituo vya bwawa';
$ec_lang['wi_station']='Kituo<br />(umbali)';
$ec_lang['wi_elevation']='Urefu';
$ec_lang['wi_pondingHeight']='Urefu wa Bwawa Dogo';
$ec_lang['wi_incrementalFlow']='Mtiririko wa Ziada';
$ec_lang['wi_cumulativeFlow']='Mtiririko Jumla';
$ec_lang['wi_save_and_calculate']='Hifadhi na Hesabu';
$ec_lang['wi_notes_we_term']='Mlinganyo wa Bwawa';
$ec_lang['wi_notes_we_def']='q = kama (urefu = 0) basi 0 vinginevyo kama (mteremko=0) basi cw*urefu*d<sub>0</sub><sup>1.5</sup> vinginevyo cw/(2.5*mteremko) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) ambapo d<sub>1</sub> na d<sub>0</sub> daima ni chanya au sifuri';
// Orifice Flow
$ec_lang['or_main_menu']='Mtiririko wa Tundu';
$ec_lang['or_main_title']='Kikokotoo cha Bure Mtandaoni cha Mtiririko wa Tundu';
$ec_lang['or_main_desc']='Mtiririko wa Tundu — Huru au Ulizozwa';
$ec_lang['or_shape']='Umbo la ufunguzi';
$ec_lang['or_shape_circular']='Duara';
$ec_lang['or_shape_rectangular']='Mstatili';
$ec_lang['or_diameter']='Kipenyo (duara) au urefu (mstatili), D';
$ec_lang['or_width']='Upana, W (mstatili peke yake)';
$ec_lang['or_invert']='Kiwango cha chini cha ufunguzi (chini ya ufunguzi)';
$ec_lang['or_hwe']='Kiwango cha maji juu ya mlango';
$ec_lang['or_twe']='Kiwango cha maji ya mkia';
$ec_lang['or_cd']='Mgawo wa kutoka, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Kiwango cha katikati';
$ec_lang['or_head']='Kichwa cha ufanisi, h';
$ec_lang['or_area']='Eneo la ufunguzi, A';
$ec_lang['or_flow']='Mtiririko, Q';
$ec_lang['or_velocity']='Kasi kwenye ufunguzi, v';
$ec_lang['or_regime']='Ukaguzi wa utaratibu wa tundu';
$ec_lang['or_regime_valid']='Kutoka huru — utaratibu wa tundu ni halali ✓';
$ec_lang['or_regime_submerged']='Tundu lililozozwa (TWE juu ya invert) — halali ✓';
$ec_lang['or_regime_warn']='Onyo: maji ya juu ya mlango chini ya taji — si utaratibu wa tundu';
$ec_lang['or_regime_twe_above_hwe']='Onyo: maji ya mkia (TWE) juu ya maji ya juu ya mlango (HWE) — angalia maingizo';
$ec_lang['or_notes_1_term']='Mlinganyo wa Tundu';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Kwa kutoka huru: h = HWE &minus; katikati. Kwa mtiririko ulizozwa (TWE juu ya invert): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Utaratibu wa Tundu';
$ec_lang['or_notes_2_def']='Mlinganyo wa mtiririko wa tundu unatumika wakati uso wa maji ya juu ya mlango uko juu ya taji (juu) ya ufunguzi. Wakati maji ya juu ya mlango yako chini ya taji, tumia mlinganyo wa bwawa badala yake.';
$ec_lang['or_notes_3_term']='Mgawo wa Kutoka';
$ec_lang['or_notes_3_def']='C<sub>d</sub> inaanzia takriban 0.60&ndash;0.65 kwa matundu yenye makingo makali. Matundu yenye makingo ya mviringo au yanayoingia hutumia thamani tofauti. Tazama <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> au Mwongozo wa Marejeleo wa HEC-RAS Hydraulic kwa mwongozo.';
$ec_lang['or_notes_4_term']='Kuzozwa';
$ec_lang['or_notes_4_def']='Wakati TWE iko juu ya invert ya ufunguzi, kikokotoo hiki kinatumia kiotomatiki mlinganyo wa tundu lililozozwa ukitumia h = HWE &minus; TWE. Wakati TWE iko kwenye au chini ya invert, kutoka huru kunakadiriwa na h = HWE &minus; katikati.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Muda wa Kumwagika kwa Tundu';
$ec_lang['odt_main_title']='Kikokotoo cha Bure Mtandaoni cha Muda wa Kumwagika kwa Tundu — Bwawa, Bonde, au Tanki';
$ec_lang['odt_main_desc']='Muda wa Kumwagika kwa Bwawa au Bonde kwa Tundu &mdash; Njia ya Kiasi cha Koni';
$ec_lang['odt_h1_elev']='Kiwango cha awali cha uso wa maji';
$ec_lang['odt_a1']='Eneo la awali la bwawa au bonde, A1';
$ec_lang['odt_h2_elev']='Kiwango cha mwisho cha uso wa maji';
$ec_lang['odt_h_orifice']='Kiwango cha katikati cha tundu';
$ec_lang['odt_a0']='Eneo la bwawa au bonde kwenye kiwango cha tundu, A0';
$ec_lang['odt_a_ending']='Eneo la mwisho la bwawa, A2 (iliyokadiriwa)';
$ec_lang['odt_h2_check']='Ukaguzi wa kiwango cha mwisho';
$ec_lang['odt_h2_ok']='Kiwango cha mwisho juu ya juu ya tundu ✓';
$ec_lang['odt_h2_warn']='Onyo: kiwango cha mwisho kwenye au chini ya juu ya tundu (katikati + D/2)';
$ec_lang['odt_d']='Kipenyo cha tundu (duara) au urefu (mstatili), D';
$ec_lang['odt_w']='Upana wa tundu, W (mstatili peke yake)';
$ec_lang['odt_t_sec']='Muda wa kumwagika (sekunde)';
$ec_lang['odt_t_min']='Muda wa kumwagika (dakika)';
$ec_lang['odt_t_hr']='Muda wa kumwagika (masaa)';
$ec_lang['odt_t_day']='Muda wa kumwagika (siku)';
$ec_lang['odt_notes_1_term']='Fomula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) inatoa muda wa kumwagika kutoka kwa kichwa H hadi kwenye tundu. Muda wa kumwagika = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), ambapo H<sub>1</sub> = kiwango cha awali &minus; kiwango cha tundu, H<sub>2</sub> = kiwango cha mwisho &minus; kiwango cha tundu.';
$ec_lang['odt_notes_2_term']='Njia';
$ec_lang['odt_notes_2_def']='Njia ya kiasi cha koni inamodelisha bwawa au bonde kama sehemu ya koni kati ya eneo la awali A<sub>1</sub> kwenye uso wa maji wa awali na eneo A<sub>0</sub> kwenye kiwango cha katikati cha tundu. A<sub>2</sub>, eneo la bwawa kwenye kiwango cha mwisho, hukadiriwa kutoka A<sub>1</sub> na A<sub>0</sub> ukitumia mfano wa sehemu ya koni. Muda wa kumwagika kutoka kiwango cha awali hadi mwisho ni sawa na jumla ya muda wa kumwagika kutoka H<sub>1</sub> hadi kwenye tundu ukitoa muda wa kumwagika uliobaki kutoka H<sub>2</sub> hadi kwenye tundu.';
$ec_lang['odt_h1']='Kichwa cha awali, H<sub>1</sub> (WSE &minus; katikati)';
$ec_lang['odt_q_max']='Mtiririko wa juu zaidi (wa awali), Q<sub>max</sub>';
$ec_lang['odt_vol']='Kiasi kilichomwagwa';
$ec_lang['odt_sketch_start']='Mwanzo';
$ec_lang['odt_sketch_end']='Mwisho';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Upana kutoka ukingo hadi ukingo';
$ec_lang['essc_mcr']='Radi ndogo kabisa ya mviringo';
$ec_lang['essc_q']='Mtiririko, Q';
// Contact us.
$ec_lang['contact_title']='Mawasiliano ya HawsEDC';
$ec_lang['contactSendMessage']='Tuma Tom Haws ujumbe';
$ec_lang['contactYourName']='Jina lako:';
$ec_lang['contactYourEmail']='Anwani yako ya barua pepe:';
$ec_lang['contactSubject']='Mada:';
$ec_lang['contact_message']='Ujumbe:';
$ec_lang['contactSpamPrefix']='Tano pamoja na moja ni sawa na';
$ec_lang['contactSpamPostfix']='(Tafadhali andika kwa maneno. 1=moja 2=mbili 3=tatu 4=nne 5=tano 6=sita 7=saba +=pamoja 5+1=6)';
$ec_lang['contactSubmitButton']='Tuma Ujumbe';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hydro Power';
$ec_lang['mhp_main_title']='Free Online Micro-Hydro Power Calculator';
$ec_lang['mhp_main_desc']='Run-of-River Micro-Hydro Power Output Calculator';
$ec_lang['mhp_flow']='Flow rate, Q';
$ec_lang['mhp_gross_head']='Gross head (elevation drop), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Penstock head losses, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Plant efficiency, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Net head, H<sub>net</sub>';
$ec_lang['mhp_power']='Power output, P';
$ec_lang['mhp_annual_kwh']='Annual energy at 100% capacity (kWh/yr)';
$ec_lang['mhp_notes_1_term']='Power Equation';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, where &rho; = 1000 kg/m&sup3; (fresh water) and g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Net Head';
$ec_lang['mhp_notes_2_def']='Net head = gross head &minus; penstock head losses. A common first estimate is h<sub>L</sub> &asymp; 5% of H<sub>gross</sub>. Use the <a href="Darcy-Weisbach.php">Darcy-Weisbach calculator</a> for more accurate penstock loss estimates.';
$ec_lang['mhp_notes_3_term']='Efficiency';
$ec_lang['mhp_notes_3_def']='Typical plant efficiency &eta; ranges from 0.70 to 0.85 for Pelton and cross-flow turbines common in micro-hydro. Use 0.75 as a conservative first estimate.';
$ec_lang['mhp_notes_4_term']='Annual Energy';
$ec_lang['mhp_notes_4_def']='Annual energy assumes continuous full-flow operation (8760 hours/year). Actual production will be lower due to seasonal flow variation, maintenance downtime, and load factor.';
