<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='ប្រភាគ';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']='rise/run';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Calculators';
$ec_lang['menu_main_list']='បញ្ជីម៉ាស៊ីនគណនា';
$ec_lang['menu_main_hydraulics']='វិស្វកម្មហ៊ីដ្រូលីក';
$ec_lang['menu_main_language']='ភាសា';
$ec_lang['template_welcome']='&gt;&gt; ទម្លាក់ការភ័យខ្លាចរបស់អ្នកនៅក្រៅទ្វារ; ក្ដីស្រឡាញ់ត្រូវបានប្រើសម្រាប់ភាសាទីនេះ។ អ្នកមិនបំផ្លាញអ្វីទាំងអស់ឡើយ។ រីករាយជាមួយ <a target="_blank" href="https://hawsedc.com/download.php">ឧបករណ៍ HawsEDC AutoCAD ឥតគិតថ្លៃ</a> ផងដែរ។ &lt;&lt;';
$ec_lang['template_translation_help']='តើអ្នកមានគំនិតល្អសម្រាប់ម៉ាស៊ីនគណនាដែលចង់បន្ថែមនៅទីនេះទេ? តើអ្នកអាចជួយខ្ញុំកែលម្អការបកប្រែ ការសរសេរកម្មវិធី ឬការបង្ហោះម៉ាស៊ីនគណនាទាំងនេះបានទេ?  ';
$ec_lang['template_feedback']='សូមផ្ញើមតិយោបល់ ឬការសរសើររបស់អ្នកដ៏មានតម្លៃមកយើង។ តើម៉ាស៊ីនគណនាឥតគិតថ្លៃនេះបានលើសពីការរំពឹងទុករបស់អ្នកគ្រប់ទិសទិសទេ?';
$ec_lang['template_printable_title']='ចំណងជើងដែលអាចបោះពុម្ព';
$ec_lang['template_printable_subtitle']='ចំណងជើងរងដែលអាចបោះពុម្ព';
$ec_lang['index_title']='ម៉ាស៊ីនគណនាវិស្វកម្មតាមអ៊ីនធឺណិតឥតគិតថ្លៃ';
$ec_lang['calc_set_units']='កំណត់ឯកតា:';
$ec_lang['points_data_help']='(ឬ ចម្លង/បិទភ្ជាប់ ដោយប្រើផ្ទៃទិន្នន័យ)';
$ec_lang['points_data_title']='ទិន្នន័យចំណុច<br />(បំបែកដោយក្បៀស ឬ tab)';
$ec_lang['points_data_copy']='ចម្លង';
$ec_lang['points_data_paste']='បិទភ្ជាប់';
$ec_lang['calc_inputs']='ទិន្នន័យបញ្ចូល';
$ec_lang['calc_results']='លទ្ធផល';
$ec_lang['view_hide_line']='[លាក់បន្ទាត់នេះ]';
$ec_lang['view_printable']='កំណែដែលអាចបោះពុម្ព (ផ្ទុកឡើងវិញ/ធ្វើឱ្យស្រស់ ដើម្បីស្ដារ)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់';
$ec_lang['dw_main_title']='ម៉ាស៊ីនគណនា Darcy-Weisbach ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['dw_main_desc']='ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ Darcy-Weisbach ប្រឡោះ ភាពរញ៉េរញ៉ៃ និងល្បឿនហូរទឹកដែលបានកំណត់';
$ec_lang['dw_roughness']='ភាពរញ៉េរញ៉ៃដាច់ខាត Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='លំហូរ kinematic viscosity, v, ជា m<sup>2</sup>/sec (1E-6 សម្រាប់ទឹកស្អាតនៅសីតុណ្ហភាពបន្ទប់)';
$ec_lang['dw_reynolds_number']='លេខ Reynolds, Re';
$ec_lang['dw_flow_regime']='របៀបហូរ';
$ec_lang['dw_regime_laminar']='លំហូរស្រួល';
$ec_lang['dw_regime_transitional']='លំហូរផ្លាស់ប្ដូរ';
$ec_lang['dw_regime_turbulent']='លំហូររំខាន';
$ec_lang['dw_friction_factor_method']='វិធីសាស្ត្រគ្រាប់ friction factor';
$ec_lang['dw_friction_factor']='Friction factor, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់';
$ec_lang['hw_main_title']='ម៉ាស៊ីនគណនា Hazen-Williams ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['hw_main_desc']='ការបាត់បង់ទំនាប់ទឹកក្នុងបំពង់ Hazen-Williams ប្រឡោះ ភាពរញ៉េរញ៉ៃ និងល្បឿនហូរទឹកដែលបានកំណត់';
$ec_lang['hw_hgl_1']='HGL ចំហៀងក្រោម';
$ec_lang['hw_hgl_2']='HGL ចំហៀងលើ';
$ec_lang['hw_roughness']='សម្ប្រាក Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning មានប្រឡាយមិនទៀងទាត់';
$ec_lang['mi_main_title']='ម៉ាស៊ីនគណនា Manning ប្រឡាយមិនទៀងទាត់ ឥតគិតថ្លៃ';
$ec_lang['mi_main_desc']='ម៉ាស៊ីនគណនាលំហូរឯកសណ្ឋាន Manning ប្រឡាយមិនទៀងទាត់';
$ec_lang['mi_waterSurfaceElevation']='កម្ពស់ផ្ទៃទឹក';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='ចំណុចខណ្ឌកាត់';
$ec_lang['mi_groupPoint']='ចំណុច';
$ec_lang['mi_groupSegment']='ផ្នែក';
$ec_lang['mi_groupRegion']='តំបន់';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Elev';
$ec_lang['mi_d50in']='Lining<br />median<br />rock<br />size';
$ec_lang['mi_n']='n<br />for seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />region<br />boundary<br />(Bank)';
$ec_lang['mi_tau']='Bot.<br />shear<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Comp.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='កំណត់ចំណាំ';
$ec_lang['mi_notes_1_term']='Composite n';
$ec_lang['mi_notes_1_def']='ម៉ាស៊ីនគណនានេះធ្វើតាម HEC-RAS Reference Manual ក្នុងការគណនា composite n ក្នុងតំបន់ ដោយប្រើ Chow 1959, ទំព័រ 136, សមីការ 6-17 (មិនមែន 6-18)។';
$ec_lang['mi_notes_2_term']='ស្រទាប់ថ្ម';
$ec_lang['mi_notes_2_def']='ប្រើម៉ាស៊ីនគណនា Manning Trapezoidal Channel ដើម្បីរចនាស្រទាប់ថ្ម។ ម៉ាស៊ីនគណនានេះសម្រាប់ខណ្ឌធម្មជាតិជាង។';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning ការហូរទឹកក្នុងបំពង់';
$ec_lang['mpf_main_title']='ម៉ាស៊ីនគណនា Manning ការហូរទឹកក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['mpf_main_desc']='រូបមន្ត Manning ការហូរទឹកបំពង់ឯកសណ្ឋានជាមួយ ជម្រាល និងជម្រៅដែលបានកំណត់';
$ec_lang['mpf_spreadheet_notice']='ពិនិត្យកំណែសៀវភៅបញ្ជីរបស់ម៉ាស៊ីនគណនានេះ';
$ec_lang['mpf_pipe_diameter']='ប្រឡោះបំពង់, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='ភាពរញ៉េរញ៉ៃ Manning, n';
$ec_lang['mpf_friction_slope']='ជម្រាលសម្ពាធ (ប្រហែល <a target="_blank" href="../pressureslope.php">?</a> ស្មើជម្រាលបំពង់), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='សមាមាត្រជម្រៅហូរ, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(មើលកំណត់ចំណាំ)';
$ec_lang['mpf_flow']='ល្បឿនហូរ, Q';
$ec_lang['mpf_velocity']='ល្បឿន, v';
$ec_lang['mpf_velocity_head']='ទំនាប់ល្បឿន, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='ផ្ទៃហូរ, a';
$ec_lang['mpf_pipe_area']='ផ្ទៃបំពង់, a0';
$ec_lang['mpf_area_ratio']='សមាមាត្រផ្ទៃ, a/a0';
$ec_lang['mpf_wetted_perimeter']='គ្រែទឹក, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='កាំ hydraulic, R<sub>h</sub>';
$ec_lang['mpf_top_width']='ទទឹងខាងលើ, T';
$ec_lang['mpf_froude_number']='លេខ Froude, F';
$ec_lang['mpf_shear_stress']='ការពន្លូតលើស​មធ្យម (កម្លាំងទាញ), tau';
$ec_lang['mpf_full_flow']='ហូរពេញ, Q0';
$ec_lang['mpf_full_flow_ratio']='សមាមាត្រទៅនឹងហូរពេញ, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>នេះជាការហូរ និងជម្រៅនៅខាងក្នុងបំពង់ <em>វែងឥតកំណត់</em>។</dt><dd>ការទទួលទឹកចូលបំពង់អាចត្រូវការជម្រៅទឹកខាងលើខ្ពស់ជាងច្រើន។ បន្ថែមយ៉ាងហោចណាស់ 1.5 ដងទំនាប់ល្បឿន ដើម្បីទទួលបានជម្រៅទឹកខាងលើ ឬ <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">មើលការណែនាំ 2 នាទីរបស់ខ្ញុំ</a> សម្រាប់ការគណនាទំនាប់ទឹក culvert ស្ដង់ដារ ដោយប្រើ HY-8។</dd>';
$ec_lang['mpf_solve_for_dd0']='រកដំណោះស្រាយ y/d<sub>0</sub> ពី Q';
$ec_lang['mpf_solve_desc']='ដោយប្រើ D<sub>0</sub>, n, និង S<sub>0</sub> ពីទម្រង់ម៉ាស៊ីនគណនា រក y/d<sub>0</sub> ទាបបំផុត សម្រាប់ Q ដែលបានកំណត់។';
$ec_lang['mpf_solve_button']='ដោះស្រាយ';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning ការបាត់បង់ទំនាប់ក្នុងបំពង់';
$ec_lang['mphl_main_title']='ម៉ាស៊ីនគណនា Manning ការបាត់បង់ទំនាប់ក្នុងបំពង់ ឥតគិតថ្លៃ';
$ec_lang['mphl_main_desc']='រូបមន្ត Manning ការបាត់បង់ទំនាប់ ជាមួយការហូរពេញ';
$ec_lang['mphl_pipe_length']='ប្រវែងបំពង់, L';
$ec_lang['mphl_area']='ផ្ទៃ, A';
$ec_lang['mphl_total_junction_k']='សម្ប្រាក k សរុបរួមបញ្ចូលគ្នានៃការបាត់បង់ junction';
$ec_lang['mphl_friction_slope']='ជម្រាលស្ទះ';
$ec_lang['mphl_friction_loss']='ការបាត់បង់ស្ទះ, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='ការបាត់បង់ junction, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='ការបាត់បង់សរុប, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL ចំហៀងក្រោម';
$ec_lang['mphl_egl_2']='EGL ចំហៀងលើ';
$ec_lang['mphl_hgl_2']='HGL ចំហៀងលើ ក្នុងបំពង់ ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>សម្រាប់លក្ខខណ្ឌចំហ (culvert) ចាំបាច់ត្រូវពិនិត្យលក្ខខណ្ឌត្រួតពិនិត្យធាតុចូល។</dt><dd>1. HGL ខាងលើ មិនអាចទាបជាងកម្ពស់ហូរជម្រៅធម្មតា ខាងលើ (ឬទាបជាងបំពង់!)។</dd><dd>2. ទំនាប់ទឹក culvert ត្រូវបានតំណាងប្រសើរជាងដោយ EGL ខាងលើ ជាជាង HGL ខាងលើ។</dd><dd>3. មើល <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ការណែនាំ 2 នាទីរបស់ខ្ញុំ</a> សម្រាប់ការគណនាទំនាប់ទឹក culvert ស្ដង់ដារ ដោយប្រើ HY-8។</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning ប្រឡាយជ្រូងចតុកោណ';
$ec_lang['mtc_main_title']='ម៉ាស៊ីនគណនា Manning ប្រឡាយជ្រូងចតុកោណ ឥតគិតថ្លៃ';
$ec_lang['mtc_main_desc']='រូបមន្ត Manning ការហូរប្រឡាយជ្រូងចតុកោណឯកសណ្ឋាន ជម្រាល និងជម្រៅដែលបានកំណត់';
$ec_lang['mtc_bottom_width']='ទទឹងខាងក្រោម, b';
$ec_lang['mtc_side_slope_1']='ជម្រាលចំហៀង 1 (ផ្ដេក/បញ្ឈរ)';
$ec_lang['mtc_side_slope_2']='ជម្រាលចំហៀង 2 (ផ្ដេក/បញ្ឈរ)';
$ec_lang['mtc_channel_slope']='ជម្រាលប្រឡាយ, S';
$ec_lang['mtc_flow_depth']='ជម្រៅហូរ, y';
$ec_lang['mtc_bend_angle']='មុំបត់ <a target="_blank" href="riprap-bend-angle.png" title="ចុចសម្រាប់រូបភាព">?</a> (សម្រាប់ការកំណត់ទំហំ riprap)';
$ec_lang['mtc_sgrock']='ទំនាក់ទំនងទម្ងន់ជាក់លាក់ថ្ម (2.65)';
$ec_lang['mtc_d50_in']='ទំហំថ្មរចនា, D50';
$ec_lang['mtc_n_strickler']='n សម្រាប់ទំហំថ្មរចនា តាម Strickler';
$ec_lang['mtc_n_blodgett']='n សម្រាប់ទំហំថ្មរចនា តាម Blodgett';
$ec_lang['mtc_n_bathurst']='n សម្រាប់ទំហំថ្មរចនា តាម Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett ទល់នឹង Bathurst';
$ec_lang['mtc_d50_bottom']='ទំហំថ្មខ្ចាញ់ខាងក្រោមដែលត្រូវការ, D50 (Isbash & MC) <span title="Per Isbash (1936) and Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='ទំហំថ្មខ្ចាញ់ជម្រាលចំហៀង 1 ដែលត្រូវការ, D50 (Isbash & MC) <span title="Per Isbash (1936) and Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='ទំហំថ្មខ្ចាញ់ជម្រាលចំហៀង 2 ដែលត្រូវការ, D50 (Isbash & MC) <span title="Per Isbash (1936) and Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='ទំហំថ្មខ្ចាញ់ដែលត្រូវការ, D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='ទំហំថ្មខ្ចាញ់ដែលត្រូវការ, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>ការធ្វើម្ដងទៀតដោយស្វ័យប្រវត្តិនៃទំហំថ្ម និងការរចនាភាពរញ៉េរញ៉ៃ</dt><dd>ជ្រើសប៊ូតុងភាពរញ៉េរញ៉ៃ (ណែនាំ BB) និងប៊ូតុងទំហំថ្មរចនា (ណែនាំ Isbash)។ កែតម្រូវជម្រៅ និងកត្តាសុវត្ថិភាពទំហំថ្ម ដើម្បីទទួលបានការហូរចង់បានជាមួយទំហំថ្មស្ថិតស្ថេរ។ រាល់ពេលអ្នកផ្លាស់ប្ដូរតម្លៃបញ្ចូលណាមួយ ដំណើរការម្ដងទៀតខាងក្រោមនឹងកើតឡើង: 1. ភាពរញ៉េរញ៉ៃត្រូវបានគណនាពីទំហំថ្មរចនា។ 2. ការគណនាភាពរញ៉េរញ៉ៃដែលបានស្នើត្រូវបានចម្លងទៅភាពរញ៉េរញ៉ៃបញ្ចូល។ 3. ការហូរក្នុងប្រឡាយ និងទំហំថ្មដែលត្រូវការ ត្រូវបានគណនា។ 4. ទំហំថ្មរចនាត្រូវបានកែតម្រូវ។ 5. ធ្វើម្ដងទៀតរហូតដល់កំហុសក្នុងទំហំថ្មរចនាតូចណាស់។</dd><dt>ម៉ាស៊ីនគណនាមូលដ្ឋាន (គ្មានការធ្វើម្ដងទៀត)</dt><dd>បញ្ចូលតម្លៃភាពរញ៉េរញ៉ៃចង់បាន។ មិនយកចិត្តទុកដាក់ផ្ទៃបញ្ចូលទំហំថ្មរចនា។</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='សៀវភៅបញ្ជីរចនា Robinson Rock Chute';
// Weir Flow Simple
$ec_lang['ws_main_menu']='ការហូរ Weir សាមញ្ញ';
$ec_lang['ws_main_title']='ម៉ាស៊ីនគណនា Weir ព្រំដែនទទឹងសាមញ្ញ ឥតគិតថ្លៃ';
$ec_lang['ws_main_desc']='ម៉ាស៊ីនគណនាការហូរ Weir ព្រំដែនទទឹងសាមញ្ញ';
$ec_lang['ws_weirLength']='ប្រវែង weir, l';
$ec_lang['ws_headWaterHeight']='កម្ពស់ទំនាប់ទឹក, h';
$ec_lang['ws_weirCoefficient']='សម្ប្រាក weir, Cw';
$ec_lang['ws_notes_heading']='កំណត់ចំណាំ';
$ec_lang['ws_notes_we_term']='សមីការ Weir';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='ការហូរ Weir មិនទៀងទាត់';
$ec_lang['wi_main_title']='ម៉ាស៊ីនគណនាការហូរ Weir ស្ថិតិ ជម្រៅប្រែប្រួល មិនទៀងទាត់ ឥតគិតថ្លៃ';
$ec_lang['wi_main_desc']='ម៉ាស៊ីនគណនាការហូរ Weir មិនទៀងទាត់';
$ec_lang['wi_headWaterelevation']='កម្ពស់ទំនាប់ទឹក';
$ec_lang['wi_weirPoints']='ចំណុច weir';
$ec_lang['wi_station']='ស្ថានីយ<br />(ចម្ងាយ)';
$ec_lang['wi_elevation']='កម្ពស់';
$ec_lang['wi_pondingHeight']='កម្ពស់ស្ទើ';
$ec_lang['wi_incrementalFlow']='ការហូរបន្ថែម';
$ec_lang['wi_cumulativeFlow']='ការហូរសរុប';
$ec_lang['wi_save_and_calculate']='រក្សាទុក និងគណនា';
$ec_lang['wi_notes_we_term']='សមីការ Weir';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='ការហូរ Orifice';
$ec_lang['or_main_title']='ម៉ាស៊ីនគណនាការហូរ Orifice ឥតគិតថ្លៃ';
$ec_lang['or_main_desc']='ការហូរ Orifice — សេរី ឬ ជ្រុក';
$ec_lang['or_shape']='រូបរាងរន្ធ';
$ec_lang['or_shape_circular']='មូល';
$ec_lang['or_shape_rectangular']='ចតុកោណ';
$ec_lang['or_diameter']='ប្រឡោះ (មូល) ឬ កម្ពស់ (ចតុកោណ), D';
$ec_lang['or_width']='ទទឹង, W (ចតុកោណប៉ុណ្ណោះ)';
$ec_lang['or_invert']='កម្ពស់ invert រន្ធ (ខាងក្រោមរន្ធ)';
$ec_lang['or_hwe']='កម្ពស់ទំនាប់ទឹក';
$ec_lang['or_twe']='កម្ពស់ទឹកខាងក្រោម';
$ec_lang['or_cd']='សម្ប្រាកការហូរចេញ, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='កម្ពស់ centroid';
$ec_lang['or_head']='ទំនាប់ប្រសិទ្ធិ, h';
$ec_lang['or_area']='ផ្ទៃរន្ធ, A';
$ec_lang['or_flow']='ការហូរ, Q';
$ec_lang['or_velocity']='ល្បឿននៅរន្ធ, v';
$ec_lang['or_regime']='ការពិនិត្យ orifice regime';
$ec_lang['or_regime_valid']='ហូរចេញសេរី — orifice regime ត្រឹមត្រូវ ✓';
$ec_lang['or_regime_submerged']='Orifice ជ្រុក (TWE លើ invert) — ត្រឹមត្រូវ ✓';
$ec_lang['or_regime_warn']='ព្រមាន: ទំនាប់ទឹកខាងក្រោមកំពូល — មិនមែន orifice regime';
$ec_lang['or_regime_twe_above_hwe']='ព្រមាន: ទឹកខ្ទង់ (TWE) លើ ទំនាប់ទឹក (HWE) — ពិនិត្យទិន្នន័យបញ្ចូល';
$ec_lang['or_notes_1_term']='សមីការ Orifice';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh)។ សម្រាប់ហូរចេញសេរី: h = HWE &minus; centroid។ សម្រាប់ការហូរជ្រុក (TWE លើ invert): h = HWE &minus; TWE។';
$ec_lang['or_notes_2_term']='Orifice Regime';
$ec_lang['or_notes_2_def']='សមីការការហូរ orifice ត្រូវបានអនុវត្ត នៅពេលផ្ទៃទំនាប់ទឹកស្ថិតនៅលើកំពូល (ខាងលើ) នៃរន្ធ។ នៅពេលទំនាប់ទឹកនៅក្រោមកំពូល ប្រើសមីការ weir ជំនួស។';
$ec_lang['or_notes_3_term']='សម្ប្រាកការហូរចេញ';
$ec_lang['or_notes_3_def']='C<sub>d</sub> ស្ថិតក្នុងចន្លោះប្រហែល 0.60&ndash;0.65 សម្រាប់ orifice ប្រភេទដែមមុតស្រួច។ ធាតុចូលមូល ឬ re-entrant ប្រើតម្លៃផ្សេងៗ។ មើល <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ឬ HEC-RAS Hydraulic Reference Manual ដើម្បីទទួលការណែនាំ។';
$ec_lang['or_notes_4_term']='ការជ្រុក';
$ec_lang['or_notes_4_def']='នៅពេល TWE ស្ថិតនៅលើ invert រន្ធ ម៉ាស៊ីនគណនានេះអនុវត្ត orifice ជ្រុកដោយស្វ័យប្រវត្តិ ដោយប្រើ h = HWE &minus; TWE។ នៅពេល TWE ស្ថិតនៅ invert ឬក្រោម ហូរចេញសេរីត្រូវបានសន្មតថា h = HWE &minus; centroid។';
// Penstock Design
$ec_lang['ps_main_menu']='ការរចនា Penstock';
$ec_lang['ps_main_title']='ម៉ាស៊ីនគណនារចនា Penstock ឥតគិតថ្លៃ';
$ec_lang['ps_main_desc']='ការកំណត់ទំហំ Penstock Micro-Hydro — ការបាត់បង់ទំនាប់ ថាមពល និងល្បឿន';
$ec_lang['ps_flow']='អត្រាហូរ, Q';
$ec_lang['ps_gross_head']='ទំនាប់ brut, H<sub>gross</sub>';
$ec_lang['ps_diameter']='ប្រឡោះ penstock, D';
$ec_lang['ps_length']='ប្រវែង penstock, L';
$ec_lang['ps_roughness']='ភាពរញ៉េរញ៉ៃបំពង់, e';
$ec_lang['ps_km']='សម្ប្រាក k នៃការបាត់បង់ junction (ឬ &ldquo;minor&rdquo;), k<sub>m</sub>';
$ec_lang['ps_nu']='Kinematic viscosity, &nu;, ជា m<sup>2</sup>/s (1E-6 សម្រាប់ទឹកជិត 20&deg;C)';
$ec_lang['ps_efficiency']='ប្រសិទ្ធភាពរោងចក្រ, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='ល្បឿនហូរ, v';
$ec_lang['ps_vel_check']='ការពិនិត្យល្បឿន';
$ec_lang['ps_f']='Friction factor, f';
$ec_lang['ps_hf']='ការបាត់បង់ទំនាប់ស្ទះ, h<sub>f</sub>';
$ec_lang['ps_hm']='ការបាត់បង់ទំនាប់ junction (ចំណុច), h<sub>m</sub>';
$ec_lang['ps_hl']='ការបាត់បង់ penstock សរុប, h<sub>L</sub>';
$ec_lang['ps_hl_check']='ការពិនិត្យការបាត់បង់ទំនាប់';
$ec_lang['ps_hnet']='ទំនាប់ net, H<sub>net</sub>';
$ec_lang['ps_power']='ថាមពលផ្តល់ចេញ, P';
$ec_lang['ps_annual_kwh']='ថាមពលប្រចាំឆ្នាំ ក្នុងសមត្ថភាព 100%';
$ec_lang['ps_vel_ok']='1–3 m/s — ស្ថិតក្នុងគោលដៅ ✓';
$ec_lang['ps_vel_low']='ក្រោម 1 m/s — បង្កើនប្រឡោះ ⚠';
$ec_lang['ps_vel_high']='លើស 3 m/s — បន្ថយប្រឡោះ ⚠';
$ec_lang['ps_hl_ok']='ស្ថិតក្នុងគោលដៅ 10% ✓';
$ec_lang['ps_hl_warn']='លើស 10% — ពិចារណាបំពង់ធំជាង ⚠';
$ec_lang['ps_hl_bad']='លើស 20% — ផ្លាស់ប្ដូរទំហំបំពង់';
$ec_lang['ps_notes_1_term']='ការបាត់បង់ទំនាប់';
$ec_lang['ps_notes_1_def']='ការបាត់បង់ penstock សរុប h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, ដែល h<sub>f</sub> = f(L/D)(v&sup2;/2g) ជាការបាត់បង់ Darcy-Weisbach friction និង h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g គ្របដណ្ដប់ធាតុចូល ការបត់ និងបំពង់ valve។ ទំនាប់ net H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>។';
$ec_lang['ps_notes_2_term']='ល្បឿន';
$ec_lang['ps_notes_2_def']='គោលដៅ 1&ndash;3 m/s។ ក្រោម 1 m/s ធ្វើឱ្យបំពង់ធំជ្រុលសម្រាប់ការហូរ; លើស 3 m/s បង្កើនការបាត់បង់ friction និងហានិភ័យ water hammer។';
$ec_lang['ps_notes_3_term']='គោលដៅការបាត់បង់ទំនាប់';
$ec_lang['ps_notes_3_def']='ការបាត់បង់ penstock ក្រោម 10% នៃទំនាប់ brut ជាទូទៅប្រកបដោយសេដ្ឋកិច្ច។ ការផ្លាស់ប្ដូរប្រសើរបំផុតរវាងតម្លៃបំពង់ និងថាមពលបាត់ ជារឿយៗស្ថិតប្រហែល 4&ndash;6% សម្រាប់តំបន់ไฟฟ้าដែលមានតម្លៃខ្ពស់។';
$ec_lang['ps_notes_4_term']='ការបាត់បង់ Junction (ចំណុច) k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='ការបាត់បង់ទាំងនេះកើតឡើងនៅ junction បំពង់ ធាតុចូល ការបត់ និងបំពង់ valve &mdash; ពាក្យ &ldquo;minor&rdquo; គឺជាទំនៀមប៉ុន្តែបំភាន់; ក្នុង penstock ខ្លី ពួកគេអាចស្មើ ឬលើសសារ friction។ តម្លៃ k ធម្មតា: ធាតុចូលមុតស្រួច 0.5, ការបត់ 45&deg; មួយ 0.2&ndash;0.3, gate valve (បើកពេញ) 0.1, butterfly valve 0.2។ សរុបគ្រប់ fitting សម្រាប់ k<sub>m</sub> សរុប។ លំនាំដើម 1.5 សន្មតធាតុចូលមួយ និងការបត់ពីរ។';
$ec_lang['ps_notes_5_term']='ភាពរញ៉េរញ៉ៃបំពង់ e';
$ec_lang['ps_notes_5_def']='ភាពរញ៉េរញ៉ៃដាច់ខាតធម្មតា: ដែក (ថ្មី) 0.046&nbsp;mm, ដែក (ប្រើហើយ) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, ស៊ីម៉ង់ 0.3&ndash;3&nbsp;mm។ HDPE គឺជារឿងធម្មតាសម្រាប់ penstock micro-hydro តូច។';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='ថាមពល Micro-Hydro';
$ec_lang['mhp_main_title']='ម៉ាស៊ីនគណនាថាមពល Micro-Hydro ឥតគិតថ្លៃ';
$ec_lang['mhp_main_desc']='ម៉ាស៊ីនគណនាផលិតថាមពល Micro-Hydro Run-of-River';
$ec_lang['mhp_flow']='អត្រាហូរ, Q';
$ec_lang['mhp_gross_head']='ទំនាប់ brut (ដំណើរចុះ), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='ការបាត់បង់ penstock, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='ប្រសិទ្ធភាពរោងចក្រ, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='ទំនាប់ net, H<sub>net</sub>';
$ec_lang['mhp_power']='ថាមពលផ្តល់ចេញ, P';
$ec_lang['mhp_annual_kwh']='ថាមពលប្រចាំឆ្នាំ ក្នុងសមត្ថភាព 100%';
$ec_lang['mhp_notes_1_term']='សមីការថាមពល';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, ដែល &rho; = 1000 kg/m&sup3; (ទឹកស្រស់) និង g = 9.806 m/s&sup2;។';
$ec_lang['mhp_notes_2_term']='ទំនាប់ Net';
$ec_lang['mhp_notes_2_def']='ទំនាប់ net = ទំនាប់ brut &minus; ការបាត់បង់ penstock។ ការប៉ាន់ស្មានដំបូងទូទៅ h<sub>L</sub> &asymp; 5% នៃ H<sub>gross</sub>។ ប្រើ <a href="Darcy-Weisbach.php">ម៉ាស៊ីនគណនា Darcy-Weisbach</a> ដើម្បីប៉ាន់ការបាត់បង់ penstock យ៉ាងត្រឹមត្រូវជាង។';
$ec_lang['mhp_notes_3_term']='ប្រសិទ្ធភាព';
$ec_lang['mhp_notes_3_def']='ប្រសិទ្ធភាពរោងចក្រធម្មតា &eta; ស្ថិតក្នុងចន្លោះ 0.70 ដល់ 0.85 សម្រាប់ turbine Pelton និង cross-flow ដែលជារឿងធម្មតា​ក្នុង micro-hydro។ ប្រើ 0.75 ជាការប៉ាន់ស្មានដំបូងប្រកបដោយការប្រុងប្រយ័ត្ន។';
$ec_lang['mhp_notes_4_term']='ថាមពលប្រចាំឆ្នាំ';
$ec_lang['mhp_notes_4_def']='ថាមពលប្រចាំឆ្នាំ សន្មតការប្រតិបត្តិការហូរពេញ​ជាបន្តបន្ទាប់ (8760 ម៉ោង/ឆ្នាំ)។ ការផលិតពិតប្រាកដ​នឹងទាបជាង ដោយសារតែភាពប្រែប្រួលនៃការហូរតាមរដូវ ការឈប់ជួសជុល និងប្រព័ន្ធ load factor។';
// Orifice Drain Time
$ec_lang['odt_main_menu']='ពេលបង្ហូរ Orifice';
$ec_lang['odt_main_title']='ម៉ាស៊ីនគណនាពេលបង្ហូរ Orifice ឥតគិតថ្លៃ — សាលា អាងស្ដុក ឬ ធុង';
$ec_lang['odt_main_desc']='ពេលបង្ហូរ Orifice ចេញពីសាលា ឬ អាង &mdash; វិធីសាស្ត្រ Conic Volume';
$ec_lang['odt_h1_elev']='កម្ពស់ផ្ទៃទឹកដំបូង';
$ec_lang['odt_a1']='ផ្ទៃសាលា ឬ អាងដំបូង, A1';
$ec_lang['odt_h2_elev']='កម្ពស់ផ្ទៃទឹកចុងក្រោយ';
$ec_lang['odt_h_orifice']='កម្ពស់ centroid orifice';
$ec_lang['odt_a0']='ផ្ទៃសាលា ឬ អាង នៅកម្ពស់ orifice, A0';
$ec_lang['odt_a_ending']='ផ្ទៃសាលាចុងក្រោយ, A2 (បូករំលាយ)';
$ec_lang['odt_h2_check']='ការពិនិត្យកម្ពស់ចុងក្រោយ';
$ec_lang['odt_h2_ok']='កម្ពស់ចុងក្រោយ​ស្ថិតនៅលើ orifice ខាងលើ ✓';
$ec_lang['odt_h2_warn']='ព្រមាន: កម្ពស់ចុងក្រោយ​ស្ថិតនៅ ឬ ក្រោមកំពូល orifice (centroid + D/2)';
$ec_lang['odt_d']='ប្រឡោះ orifice (មូល) ឬ កម្ពស់ (ចតុកោណ), D';
$ec_lang['odt_w']='ទទឹង orifice, W (ចតុកោណប៉ុណ្ណោះ)';
$ec_lang['odt_t_sec']='ពេលបង្ហូរ (វិនាទី)';
$ec_lang['odt_t_min']='ពេលបង្ហូរ (នាទី)';
$ec_lang['odt_t_hr']='ពេលបង្ហូរ (ម៉ោង)';
$ec_lang['odt_t_day']='ពេលបង្ហូរ (ថ្ងៃ)';
$ec_lang['odt_notes_1_term']='រូបមន្ត';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ផ្តល់ពេលបង្ហូរពី head H ទៅ orifice។ ពេលបង្ហូរ = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), ដែល H<sub>1</sub> = កម្ពស់ដំបូង &minus; កម្ពស់ orifice, H<sub>2</sub> = កម្ពស់ចុងក្រោយ &minus; កម្ពស់ orifice។';
$ec_lang['odt_notes_2_term']='វិធីសាស្ត្រ';
$ec_lang['odt_notes_2_def']='វិធីសាស្ត្រ conic volume គំរូ​ សាលា ឬ អាង​ ជាផ្នែក conic រវាងផ្ទៃដំបូង A<sub>1</sub> នៅ​ ផ្ទៃទឹកដំបូង​ និងផ្ទៃ A<sub>0</sub> នៅ​ កម្ពស់ centroid orifice។ A<sub>2</sub>, ផ្ទៃ​ សាលា​ នៅ​ កម្ពស់​ ចុងក្រោយ ត្រូវ​ បូករំលាយ​ ពី A<sub>1</sub> និង A<sub>0</sub> ដោយ​ ប្រើ​ គំរូ​ conic section។ ពេលបង្ហូរ​ ពី​ ដំបូង​ ដល់​ ចុង​ ស្មើ​ ពេល​ បង្ហូរ​ សរុប​ ពី H<sub>1</sub> ដល់ orifice ដកពេលបង្ហូរ​ នៅ​ សល់​ ពី H<sub>2</sub> ដល់ orifice។';
$ec_lang['odt_h1']='Head ដំបូង, H<sub>1</sub> (WSE &minus; centroid)';
$ec_lang['odt_q_max']='ការហូរ​ ច្រើន​ បំផុត​ (ដំបូង), Q<sub>max</sub>';
$ec_lang['odt_vol']='បរិមាណ​ ដែល​ បាន​ បង្ហូរ';
$ec_lang['odt_sketch_start']='ចាប់ផ្ដើម';
$ec_lang['odt_sketch_end']='ចប់';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='ទទឹង Bank ទៅ Bank';
$ec_lang['essc_mcr']='កាំ​ong​ curve តូចបំផុត';
$ec_lang['essc_q']='ការហូរ, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='ការវាស់ស្ទង់លំហូរប្រព័ន្ធស្រោចស្រព';
$ec_lang['irr_main_title']='ម៉ាស៊ីនគណនាឥតគិតថ្លៃតាមអ៊ីនធឺណិតសម្រាប់ការវាស់ស្ទង់លំហូរប្រព័ន្ធស្រោចស្រព';
$ec_lang['irr_main_desc']='ការវាស់ស្ទង់លំហូរប្រព័ន្ធស្រោចស្រព — ទ្រនាប់ទឹក និងរន្ធ';
$ec_lang['contact_title']='ទំនាក់ទំនង HawsEDC';
$ec_lang['contactSendMessage']='ផ្ញើសារទៅ Tom Haws';
$ec_lang['contactYourName']='ឈ្មោះ​ របស់​ អ្នក:';
$ec_lang['contactYourEmail']='អាសយ​ ដ្ឋាន​ អ៊ីម៉ែល​ របស់​ អ្នក:';
$ec_lang['contactSubject']='ប្រធានបទ:';
$ec_lang['contact_message']='សារ:';
$ec_lang['contactSpamPrefix']='ប្រាំ​ បូក​ មួយ​ ស្មើ​ នឹង';
$ec_lang['contactSpamPostfix']='(សូម​ សរសេរ​ ជា​ ពាក្យ​។ 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='ផ្ញើ​ សារ';

// About
$ec_lang['about_main_menu']='អំពី';
$ec_lang['about_main_title']='អំពី HawsEDC ម៉ាស៊ីនគណនាវិស្វកម្ម';
$ec_lang['about_main_desc']='បេសកកម្ម, ប្រភពបើកចំហ, និងការចូលរួម';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='អត្រាប្រើប្រាស់ទឹក — ការប្រព្រឹត្ត/ការបាញ់ទឹក';
$ec_lang['ds_main_title']='គណនាអត្រាប្រើប្រាស់ទឹកស្រោចស្រព់ (ប្រព្រឹត្ត/បាញ់ទឹក) ដោយឥតគិតថ្លៃ';
$ec_lang['ds_main_desc']='ការស្រោចស្រព់ប្រព្រឹត្ត &amp; បាញ់ទឹក &mdash; អត្រាប្រើប្រាស់ទឹក និងឯកសណ្ឋានភាព';
$ec_lang['ds_q_avg']='អត្រាលំហូរជាមធ្យម, q';
$ec_lang['ds_q_min']='អត្រាលំហូរអប្បបរមា, q<sub>min</sub>';
$ec_lang['ds_se']='ចម្ងាយក្បាលប្រព្រឹត្តតាមបំពង់ lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='ចម្ងាយរវាង lateral (ចម្ងាយជួរដេក), S<sub>l</sub>';
$ec_lang['ds_n_e']='ក្បាលប្រព្រឹត្តក្នុង lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='lateral ក្នុងតំបន់, n<sub>l</sub>';
$ec_lang['ds_d']='ជម្រៅប្រើប្រាស់ទឹកគោលដៅ, d';
$ec_lang['ds_a_e']='ផ្ទៃដីក្នុង lateral, A<sub>e</sub>';
$ec_lang['ds_pr']='អត្រាប្រើប្រាស់ទឹក, PR';
$ec_lang['ds_du']='ឯកសណ្ឋានភាពចែកចាយ, DU';
$ec_lang['ds_du_check']='ការត្រួតពិនិត្យគុណភាព DU';
$ec_lang['ds_q_lat']='លំហូរក្នុង lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='លំហូរតំបន់, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='ពេលវេលាដំណើរការសម្រាប់ជម្រៅគោលដៅ (ម៉ោង)';
$ec_lang['ds_du_excellent']='ល្អប្រសើរ — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='ល្អ — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='អាចទទួលយកបាន — DU ≥ 70%';
$ec_lang['ds_du_poor']='ខ្សោយ — DU < 70% — ពិនិត្យផែនការ ⚠';
$ec_lang['ds_notes_1_term']='អត្រាប្រើប្រាស់ទឹក';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub> ដែល A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> គឺផ្ទៃដីដែលក្បាលប្រព្រឹត្តម្នាក់ម្នាងទំនុកបម្រុង។ អត្រាប្រើប្រាស់ទឹកទាបជាងផ្ដល់ពេលវេលាបន្ថែមសម្រាប់ការជ្រៀតចូល &mdash; សំខាន់សម្រាប់ដីធ្ងន់ ឬទីជម្រៅ។';
$ec_lang['ds_notes_2_term']='ឯកសណ្ឋានភាពចែកចាយ (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>។ DU 1.0 (100%) មានន័យថាក្បាលប្រព្រឹត្តទាំងអស់លំហូរដូចគ្នា។ តម្លៃក្រោម 0.80 បង្ខាំងទឹកនៅតំបន់ស្រោចស្រព់ល្អ ខណៈដែលទុកតំបន់ស្ងួតជាង។';
$ec_lang['ds_notes_3_term']='ពេលវេលាដំណើរការ';
$ec_lang['ds_notes_3_def']='ពេលវេលា = ជម្រៅគោលដៅ &divide; អត្រាប្រើប្រាស់ទឹក។ នៅលើដីទម្រ ឬដីរឹង សូមបំបែកពេលវេលាជាពីរ ឬបីជុំខ្លីៗ។';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='ការបំពេះ ប្រឡាយ';
$ec_lang['cs_main_title']='ម៉ាស៊ីនគណនាការបំពេះប្រឡាយ និងប្រសិទ្ធភាពដឹកជញ្ជូន ឥតគិតថ្លៃ';
$ec_lang['cs_main_desc']='ការបំពេះប្រឡាយ &amp; ប្រសិទ្ធភាពដឹកជញ្ជូន &mdash; វិធីសាស្ត្រ ចូល-ចេញ';
$ec_lang['cs_Q_in']='ការហូរចូលនៅក្បាលខ្សែ, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='ការហូរចេញនៅចុងខ្សែ, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='អត្រាការបំពេះ, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='ការពិនិត្យការវាស់';
$ec_lang['cs_pct_loss']='ការបាត់បង់ជាប្រភាគនៃការហូរចូល';
$ec_lang['cs_Ec']='ប្រសិទ្ធភាពដឹកជញ្ជូន, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='ការវាយតម្លៃប្រសិទ្ធភាព';
$ec_lang['cs_Vol_day']='បរិមាណប្រចាំថ្ងៃដែលបានបំពេះ';
$ec_lang['cs_Vol_year']='បរិមាណប្រចាំឆ្នាំដែលបានបំពេះ';
$ec_lang['cs_L']='ប្រវែងឈានដល់, L';
$ec_lang['cs_wp']='គ្រែទឹកនៃផ្នែកឆ្លងកាត់ប្រឡាយ, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='ការបំពេះក្នុងមួយឯកតាប្រវែង, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='តម្លៃទឹក (រង្វាន់ / ឯកតាបរិមាណ)';
$ec_lang['cs_lining_cost']='ថ្លៃរង្វាន់ស្រទាប់ (រង្វាន់ / ឯកតាផ្ទៃដី)';
$ec_lang['cs_Ec_target']='គោលដៅប្រសិទ្ធភាពដឹកជញ្ជូនបន្ទាប់ពីស្រទាប់, E<sub>c,target</sub> (ប្រភាគ, 0&ndash;1) &mdash; គោលដៅដែលស្រទាប់នឹងរក្សាទឹក';
$ec_lang['cs_lining_area']='ផ្ទៃស្រទាប់ប្រឡាយ (L &times; P<sub>w</sub>)';
$ec_lang['cs_annual_value_lost']='តម្លៃប្រចាំឆ្នាំនៃទឹកដែលបាត់បង់ (រង្វាន់)';
$ec_lang['cs_annual_value_recovered']='តម្លៃដែលរួងរាប់ដោយស្រទាប់ (រង្វាន់)';
$ec_lang['cs_lining_total_cost']='ថ្លៃរង្វាន់ស្រទាប់សរុប (រង្វាន់)';
$ec_lang['cs_payback_years']='រយៈពេលវិនិយោគឡើងវិញសាមញ្ញ (ឆ្នាំ)';
$ec_lang['cs_loss_positive']='Qin > Qout — រកឃើញការបំពេះ ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — គ្មានការបំពេះអាចវាស់បាន';
$ec_lang['cs_loss_negative']='ការព្រមាន: Qout > Qin — ពិនិត្យការវាស់ ⚠';
$ec_lang['cs_Ec_good']='ល្អ — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='មធ្យម — Ec 60–80%';
$ec_lang['cs_Ec_poor']='ខ្សោយ — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='វិធីសាស្ត្រ';
$ec_lang['cs_notes_1_def']='វិធីសាស្ត្រ ចូល-ចេញ ប៉ាន់ស្មានការបំពេះដោយការវាស់ការហូរនៅក្បាល និងចុងខ្សែប្រឡាយ: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>។ ប្រសិទ្ធភាពដឹកជញ្ជូន E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>។ បរិមាណប្រចាំឆ្នាំសន្មតការប្រតិបត្តិការហូរពេញជានិច្ច; ការបំពេះពិតប្រាកដទាបជាងសម្រាប់ប្រឡាយតាមរដូវ ឬហូរខ្លះ។';
$ec_lang['cs_notes_2_term']='ការវាយតម្លៃប្រសិទ្ធភាព';
$ec_lang['cs_notes_2_def']='ប្រឡាយដីធម្មតាគ្មានស្រទាប់: E<sub>c</sub> = 60&ndash;80%។ ប្រឡាយដីថែទាំល្អ: 75&ndash;85%។ ប្រឡាយស្រទាប់ concrete: 90&ndash;98%។ ការបំពេះលើស 30% នៃការហូរចូល ជួនកាលសមស្របក្នុងការវិនិយោគស្រទាប់ប្រឡាយ។ (USBR, FAO)';
$ec_lang['cs_notes_3_term']='ការត្រឡប់វិនិយោគស្រទាប់';
$ec_lang['cs_notes_3_def']='បញ្ចូលតម្លៃទឹក និងថ្លៃរង្វាន់ស្រទាប់ក្នុងរង្វាន់ដែលស្របគ្នា។ ផ្ទៃស្រទាប់ = ប្រវែងឈានដល់ &times; គ្រែទឹក &mdash; គ្រែទឹកនៃផ្នែកឆ្លងកាត់ប្រឡាយនៅប្រវែងហូរដែលបានវាស់ (ទទឹងបាត បូកលាក់ទឹកផ្នែកចំហៀងទាំងពីរ)។ តម្លៃដែលរួងរាប់ដោយឌ្វារ៉ាង់ធានាថាប្រឡាយស្រទាប់ឈានដល់គោលដៅ E<sub>c</sub> ដោយបង្រួបបង្រួមអស់រយៈពេល។ វិនិយោគឡើងវិញតាមពិតប្រាកដនឹងវែងជាងសម្រាប់ប្រឡាយតាមរដូវ ឬប្រសិនបើស្រទាប់មិនឈានដល់ប្រសិទ្ធភាពគោលដៅ។';
$ec_lang['cs_notes_4_term']='ឯកសារយោង';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3rd ed. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
$ec_lang['irr_intro_html']='<p>ទំនប់ស្ទឹង និងរន្ធ គឺជាឧបករណ៍វាស់ស្ទង់ស្តង់ដារនៅក្នុងវាលស្រែសម្រាប់វាស់ប្រាក់ទឹកក្នុងប្រព័ន្ធស្រោចស្រព។ ជ្រើសរើសម៉ាស៊ីនគណនាដែលសមស្របទៅនឹងរចនាសម្ព័ន្ធរបស់អ្នក:</p>';
$ec_lang['irr_card_weir_uniform_head']='ទំនប់ស្ទឹង — ក្បាលទូលាយ (ទទឹងស្មើ)';
$ec_lang['irr_card_weir_uniform_desc']='វាស់ប្រាក់ទឹកដែលហូរឆ្លងក្បាលទំនប់បែងចែក រចនាសម្ព័ន្ធពិនិត្យ ឬក្ដារទំនប់។ បញ្ចូលប្រវែងទំនប់ស្ទឹង និងជម្រៅទឹកពីលើក្បាល។';
$ec_lang['irr_card_weir_irregular_head']='ទំនប់ស្ទឹង — ទម្រង់មិនទៀងទាត់';
$ec_lang['irr_card_weir_irregular_desc']='ប្រើប្រាស់នៅពេលដែលក្បាលទំនប់មិននៅក្នុងកម្ពស់ស្មើគ្នា — ច្រោះទឹកធម្មជាតិ រចនាសម្ព័ន្ធធ្លាក់ទឹកមានទទឹងប្រែប្រួល ឬរចនាសម្ព័ន្ធគ្រប់គ្រងច្រើនផ្នែក។';
$ec_lang['irr_card_orifice_head']='រន្ធ — ទ្វារទឹក ឬចុងបំពង់';
$ec_lang['irr_card_orifice_desc']='វាស់ប្រាក់ទឹកដែលហូរឆ្លងទ្វារទឹករអិល ចុងបំពង់ ឬបំពង់ culvert។ ដោះស្រាយជាប្រព័ន្ធទាំងការហូរទឹកសេរី និងលក្ខខណ្ឌលង់ទឹក (សម្ពាធខាងក្រោម)។';
$ec_lang['irr_card_canal_head']='រចនា &amp; វិភាគប្រឡាយ';
$ec_lang['irr_card_canal_desc']='រចនា ឬពិនិត្យប្រឡាយស្រោចស្រពដោយប្រើរូបមន្ត Manning\'s។ ប្រើម៉ាស៊ីនគណនា Trapezoidal សម្រាប់ប្រឡាយថ្មី; ម៉ាស៊ីនគណនា Irregular សម្រាប់ប្រឡាយធម្មជាតិ ឬសំណង់ដែលមានស្រាប់។';
$ec_lang['irr_card_drip_head']='រចនាការស្រោចទឹក &amp; Sprinkler';
$ec_lang['irr_card_drip_desc']='គណនាអត្រាស្រោចទឹក ភាពស្មើគ្នានៃការចែកចាយ ប្រាក់ទឹកខ្សែ ប្រាក់ទឹកតំបន់ និងម៉ោងដំណើរការ សម្រាប់ប្រព័ន្ធស្រោចទឹកដំណក់ ឬ Sprinkler។ បញ្ចូលប្រាក់ទឹក Emitter ចម្ងាយ Emitter និងជម្រៅគោលដៅ។';
$ec_lang['irr_card_seepage_head']='ការបំពេះប្រឡាយ &amp; ប្រសិទ្ធភាពដឹកជញ្ជូន';
$ec_lang['irr_card_seepage_desc']='ប៉ាន់ស្មានការបំពេះដោយប្រើការវាស់ការហូរចូល និងចេញនៃខ្សែប្រឡាយ។ គណនាប្រសិទ្ធភាពដឹកជញ្ជូន និងការបំពេះទឹកប្រចាំឆ្នាំ ដើម្បីជួយកំណត់អទិភាពវិនិយោគស្រទាប់ប្រឡាយ។';
$ec_lang['irr_quickref_html']='<h3>ឯកសារយោងរហ័ស</h3><dl><dt>ទំនប់បែងចែក ឬរចនាសម្ព័ន្ធគ្រប់គ្រង</dt><dd>វាស់ជម្រៅទឹកពីលើក្បាលទំនប់ស្ទឹង។ ប្រើ <a href="Weir-Flow-Simple.php">ទំនប់ស្ទឹងសាមញ្ញ</a> សម្រាប់ក្បាលស្មើ ឬ <a href="Weir-Flow-Irregular.php">ទំនប់ស្ទឹងមិនទៀងទាត់</a> សម្រាប់ក្បាលមានទម្រង់ ឬជណ្ដើរ។</dd><dt>ទ្វារទឹក ឬចុងបំពង់</dt><dd>វាស់ជម្រៅទឹកខាងលើ និងខាងក្រោម (ឬកម្ពស់បាតបំពង់ប្រសិនបើហូរទឹកសេរី)។ ប្រើ <a href="Orifice.php">ប្រាក់ទឹករន្ធ</a>។ សម្រាប់បំពង់មូល D&nbsp;= ចន្លោះបំពង់; សម្រាប់ទ្វារចតុកោណ បញ្ចូលទទឹង W និងកម្ពស់ D។</dd><dt>ពេលវេលាបង្ហូរទឹករណ្ដប ឬស្រះ</dt><dd>ប្រើ <a href="Orifice-Drain-Time.php">ពេលវេលាបង្ហូរទឹករន្ធ</a> ដើម្បីប៉ាន់ស្មានពេលវេលាដើម្បីបញ្ចុះកម្រិតទឹកស្រះ ឬទំនប់ តាមរន្ធបាត — មានប្រយោជន៍សម្រាប់ការគ្រោងផែនការស្តុកទឹក។</dd><dt>ស្តង់ដារវាលស្រែ</dt><dd>សមីការប្រាក់ទឹក weir និង orifice ដែលប្រើនៅទីនេះ ស្របនឹងនីតិវិធី USBR <em>Water Measurement Manual</em> (ការបោះពុម្ពលើក ៣) ដែលជាធម្មតាតម្រូវដោយអ្នកគ្រប់គ្រងទឹក និងស្រុកស្រោចស្រព។</dd></dl>';
$ec_lang['about_body_html']='<h3>បេសកកម្ម</h3><p>ម៉ាស៊ីនគណនាវិស្វកម្ម HawsEDC មានឡើងដើម្បីបម្រើដល់វិស្វករ និងកម្មករវាលស្រែទូទាំងពិភពលោក — ជាពិសេសសម្រាប់អ្នកដែលធ្វើការនៅក្នុងតំបន់ខ្វះខាតទឹក ធនធានមានកំណត់ ឬតំបន់ដែលខ្វះការបម្រើ។ ឧបករណ៍ទាំងនេះជាផ្នែកមួយនៃបេសកកម្មមនុស្សធម៌ទូលំទូលាយ: ប្រាប់មនុស្សគ្រប់រូបតាមវិធីដ៏ជាក់ស្ដែង និងមានប្រសិទ្ធភាពបំផុតថា ពួកគេជាទីស្រឡាញ់ និងដ៏ចំណាន់ជារៀងរហូត ថាពួកគេមិនមានអ្វីត្រូវខ្លាចទេ ហើយថាពួកគេនឹងមិនបំផ្លាញអ្វីទាំងអស់ទេ។</p><p>ម៉ាស៊ីនគណនាជានូវវាហនៈ។ ទិសដៅគឺពិភពលោកដែលគ្មានទុក្ខ។</p><h3>អាជ្ញាប័ណ្ណ Open Source</h3><p>កូដទាំងអស់ត្រូវបានបញ្ចេញក្រោម <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 ឬក្រោយ</a> — សេរីក្នុងន័យនៃសេរីភាព។ អ្នកអាចប្រើប្រាស់ ស្វែងយល់ កែប្រែ និងចែករំលែកកូដក្រោមលក្ខខណ្ឌដូចគ្នា។</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>កូដប្រភព</h3><p>កូដប្រភពពេញលេញដែលអាចរកបានជាសាធារណៈនៅ Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>អ្នកអាចរុករកកូដ ការរាយការណ៍បញ្ហា ឬ fork repository នៅទីនោះ។</p><h3>ការចូលរួម</h3><p>Pull requests ត្រូវបានស្វាគមន៍។ វិធីចូលរួម:</p><ul><li><strong>ការបកប្រែ</strong> — កែលម្អ ឬបន្ថែមភាសា។ បើក pull request ជាមួយការផ្លាស់ប្ដូរទៅ <code>lib/lang.ec.??.php</code> ឯកសារពាក់ព័ន្ធ។</li><li><strong>របាយការណ៍ Bug</strong> — ប្រើទម្រង់មតិកែលម្អនៅក្នុងទំព័រម៉ាស៊ីនគណនាណាមួយ ឬដាក់ស្នើបញ្ហានៅ Bitbucket។</li><li><strong>ម៉ាស៊ីនគណនាថ្មី</strong> — គំនិតសម្រាប់ឧបករណ៍វិស្វកម្មអ៊ីដ្រូលីកដែលបម្រើដល់កម្មករវាល និងអ្នកជំនាញស្រោចស្រព ជាពិសេសសំណើររ។ សូមមើលសៀវភៅណែនាំ <code>CLAUDE.md</code> developer នៅ repository។</li><li><strong>ការបង្ហោះ</strong> — ប្រសិនបើអ្នកអាចដាក់ mirror ម៉ាស៊ីនគណនាទាំងនេះសម្រាប់តំបន់ដែលមានការតភ្ជាប់ មានកំណត់ សូមទាក់ទង។</li></ul><h3>ការប្រើប្រាស់ក្រៅបណ្តាញ</h3><p>ម៉ាស៊ីនគណនាទាំងនេះដំណើរការជា Progressive Web App (PWA)។ ចូលទៅកាន់ទំព័រម៉ាស៊ីនគណនាណាមួយពេលមានការតភ្ជាប់អ៊ីនធឺណិត ហើយកម្មវិធីរុករករបស់អ្នកនឹងរក្សាទុកម៉ាស៊ីនគណនាទាំងអស់ដោយស្វ័យប្រវត្តិ។ បន្ទាប់ពីនោះ ម៉ាស៊ីនគណនាទាំងអស់ដំណើរការក្រៅបណ្តាញ — មិនចាំបាច់ប្រើអ៊ីនធឺណិត។</p><p>នៅលើ Android ឬ iOS ប្រើជម្រើស "បន្ថែមទៅអេក្រង់ដើម" ក្នុងកម្មវិធីរុករករបស់អ្នក ដើម្បីដំឡើង EngCalcs ជាកម្មវិធីនៅលើឧបករណ៍របស់អ្នក។ នៅលើកុំព្យូទ័រ ស្វែងរករូបតំណាងដំឡើងនៅក្នុងរបារអាសយដ្ឋានកម្មវិធីរុករករបស់អ្នក។</p><p>អ្នកក៏អាចរក្សាទុកម៉ាស៊ីនគណនាណាមួយដោយប្រើម៉ឺនុយ "រក្សាទុកជា&hellip;" ក្នុងកម្មវិធីរុករករបស់អ្នកសម្រាប់ការប្រើប្រាស់ក្រៅបណ្តាញម្តងម្កាល។</p><h3>ទំនាក់ទំនង</h3><p>Tom Haws — វិស្វករ Hydraulic និងអ្នកនិពន្ធម៉ាស៊ីនគណនាទាំងនេះ។<br />ប្រើទម្រង់មតិនៅក្នុងទំព័រម៉ាស៊ីនគណនាណាមួយ ឬចូលទៅកាន់ source code នៅ <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>។</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='រចនា Rock Chute (Robinson)';
$ec_lang['rc_main_title']='ម៉ាស៊ីនគណនារចនា Rock Chute តាមអ៊ីនធឺណិតដោយឥតគិតថ្លៃ — Robinson (1998)';
$ec_lang['rc_main_desc']='ការជ្រើសរើសថ្មសម្រាប់ Rock Chute &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='ជម្រាលបាតច្រក, S<sub>0</sub>';
$ec_lang['rc_qt']='ចំណុះប្រតិបត្តិការក្នុងមួយអង្គង, q<sub>t</sub> <span title="ការហូរក្នុងមួយអង្គង​នៅច្រករបៀងបញ្ចូល។ សម្រាប់ប្រឡាយទទឹងបាត B ដែលមានការហូរសរុប Q ប្រើ q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='ប្រហោង Riprap, n<sub>p</sub>';
$ec_lang['rc_sg']='ទំងន់ប្រភេទថ្ម, sg <span title="ថ្មកិនឬបាសាល់ធម្មតា ≈ 2.65។ ជួរ Robinson ត្រឹមត្រូវ: 2.54 ដល់ 2.82។" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='ការចែកថ្ម SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="គម្លាតស្ដង់ដារការចែកថ្ម។ ថ្មស្មើ ≈ 1.25។ ជួរ Robinson ត្រឹមត្រូវ: 1.15 ដល់ 1.47។" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='ជម្រៅធម្មតានៅក្នុងប្រឡាយបញ្ចូល, y<sub>n</sub> <span title="ទឹកដាំង (Hp > yn) ល្អ — កាត់បន្ថយការ​침ខ្ទេចនៅខ្ពស់ (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='ទំហំថ្មមធ្យោបាយដែលត្រូវការ, D<sub>50</sub> <span title="សមីការ 1 (S0 &lt; 0.10) ឬ សមីការ 2 (0.10-0.40)។ ត្រឹមត្រូវ: D50 15-278 mm, S0 0.02-0.40។ ក្រៅពីជួរ: ដកស្រង់ពីក្រៅ។" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='សមីការដែលបានប្រើ';
$ec_lang['rc_sg_check']='ការត្រួតពិនិត្យទំងន់ប្រភេទ';
$ec_lang['rc_SD_check']='ការត្រួតពិនិត្យការចែកថ្ម SD';
$ec_lang['rc_sg_ok']   ='sg ស្ថិតក្នុងជួរត្រឹមត្រូវ (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='ការព្រមាន: sg < 2.54 — ក្រោមជួរ Robinson';
$ec_lang['rc_sg_high'] ='ការព្រមាន: sg > 2.82 — លើសជួរ Robinson';
$ec_lang['rc_SD_ok']   ='SD ស្ថិតក្នុងជួរត្រឹមត្រូវ (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='ការព្រមាន: SD < 1.15 — ក្រោមជួរ Robinson';
$ec_lang['rc_SD_high'] ='ការព្រមាន: SD > 1.47 — លើសជួរ Robinson';
$ec_lang['rc_layer']='កំណាស់ស្រទាប់ថ្ម (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='កាំខ្សែកោងខ្ពស់បំផុត (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='ប្រវែងខ្សែកោងខ្ពស់បំផុត';
$ec_lang['rc_apron_length']='ប្រវែងក្រណាត់ខ្សែចេញ (15 &times; D<sub>50</sub>) <span title="ត្រូវការសម្រាប់គ្រោងរចនាសម្ព័ន្ធរបស់ ch ute ។ &quot;ទឹកខ្ពស់ទាបបំផុតដែលកើតឡើងជាលទ្ធផលនៃចំហៀងខ្សែចេញ និងភាពទប់ស្កាត់ប្រឡាយខ្ពស់ទាបគ្រប់គ្រាន់ដើម្បីធានាស្ថិរភាពនៃ riprap នៅច្រកចេញ។&quot; (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='ភាពរដុបរបស់ Manning នៅក្នុងច្រក, n';
$ec_lang['rc_Vm']='ល្បឿននៅក្នុងស្រទាប់ថ្ម, V<sub>m</sub> <span title="ផ្នែកនៃ qt ហូរតាមរន្ធថ្ម។ សំណល់ qs ហូរលើផ្ទៃ។ np លំនាំដើម = 0.45 សម្រាប់ថ្មកិនជ្រួញ។" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='ចំណុះប្រតិបត្តិការក្នុងមួយអង្គងតាមស្រទាប់, q<sub>m</sub>';
$ec_lang['rc_qs']='ចំណុះប្រតិបត្តិការក្នុងមួយអង្គងលើផ្ទៃ, q<sub>s</sub> (q<sub>t</sub> &minus; q<sub>m</sub>)';
$ec_lang['rc_d']='ជម្រៅទឹកលើផ្ទៃ riprap, d';
$ec_lang['rc_Hp']='ជម្រៅទឹកនៅច្រករបៀងបញ្ចូល, H<sub>p</sub> <span title="ទឹកដាំង (Hp > yn) ល្អ — កាត់បន្ថយការ침ខ្ទេចនៅខ្ពស់ (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='ការត្រួតពិនិត្យទឹកដាំងនៅច្រករបៀង';
$ec_lang['rc_pond_ok']   ='Hp > yn — ទឹកដាំងខ្ពស់ ✓';
$ec_lang['rc_pond_warn'] ='⚠ Hp ≤ yn — គ្មានទឹកដាំង — ត្រួតពិនិត្យច្រករបៀងសម្រាប់ការ침ខ្ទេច';
$ec_lang['rc_eq1']='Eq. 1 (S0 < 0.10) — ជម្រាលស្រាល';
$ec_lang['rc_eq2']='Eq. 2 (0.10 ≤ S0 ≤ 0.40) — ជម្រាលចោត';
$ec_lang['rc_eq_warn_low']='ការព្រមាន: S0 < 0.02 — ក្រោមជួរផ្ទៀងផ្ទាត់ Robinson';
$ec_lang['rc_eq_warn_high']='ការព្រមាន: S0 > 0.40 — លើសជួរផ្ទៀងផ្ទាត់ Robinson';
$ec_lang['rc_notes_1_term']='សមីការជ្រើសរើសថ្ម';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) បានបង្កើតសមីការ​ប្រព័ន្ធពីររូបមន្តសម្រាប់ D<sub>50</sub> ដោយផ្អែកលើជម្រាលច្រក និងចំណុះប្រតិបត្តិការ។ សមីការ 1 ប្រើសម្រាប់ជម្រាលស្រាល (S<sub>0</sub> &lt; 0.10); សមីការ 2 ប្រើសម្រាប់ជម្រាលចោត (0.10 &le; S<sub>0</sub> &le; 0.40)។ សមីការទាំងពីរត្រូវការ q<sub>t</sub> ជា m&sup2;/s ហើយបញ្ជូន D<sub>50</sub> ជា mm។ ជួរផ្ទៀងផ្ទាត់គឺ 0.02 &le; S<sub>0</sub> &le; 0.40។';
$ec_lang['rc_notes_2_term']='ចំណុះប្រតិបត្តិការក្នុងមួយអង្គង';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> គឺជាចំណុះប្រតិបត្តិការក្នុងមួយអង្គងសរុបនៅខ្ពស់ច្រក (ការហូរសរុបក្នុងមួយអង្គងទទឹង)។ សម្រាប់ប្រឡាយទទឹងបាត B ដែលមានការហូរសរុប Q ប៉ាន់ q<sub>t</sub> &asymp; Q / B ឬគណនាពីលក្ខខណ្ឌជម្រៅ​វិកលណ្ឌ​នៅច្រករបៀងបញ្ចូល។';
$ec_lang['rc_notes_3_term']='ការហូរតាមស្រទាប់ថ្ម';
$ec_lang['rc_notes_3_def']='ផ្នែកនៃការហូរសរុបហូរតាមរន្ធ riprap (ការហូរស្រទាប់ q<sub>m</sub>); សំណល់ហូរលើផ្ទៃថ្ម (q<sub>s</sub> = q<sub>t</sub> &minus; q<sub>m</sub>)។ ជម្រៅទឹក d គណនាពីសមីការ Manning&rsquo;s ដែលប្រើចំពោះការហូរផ្ទៃ q<sub>s</sub> ដោយប្រើភាពរដុបរបស់ ch ute n។ ប្រហោងលំនាំដើម n<sub>p</sub> = 0.45 ជារឿងធម្មតាសម្រាប់ថ្មកិន​ជ្រួញ។';
$ec_lang['rc_notes_5_term']='ជួរទំហំថ្មត្រឹមត្រូវ';
$ec_lang['rc_notes_5_def']='សមីការត្រូវបានបង្កើតដោយប្រើជួរ D<sub>50</sub> ពី 15&nbsp;mm ដល់ 278&nbsp;mm។ លទ្ធផលក្រៅជួរនេះត្រូវបានដកស្រង់ពីក្រៅ ហើយត្រូវប្រើដោយមានការវិនិច្ឆ័យបន្ថែមពីអ្នកវិស្វករ។';
$ec_lang['rc_notes_6_term']='កម្រិតក្រណាត់ចេញ';
$ec_lang['rc_notes_6_def']='កម្រិតកំពូលនៃ riprap នៅក្នុងជួរចេញគួរស្ថិតនៅលើ ឬក្រោមកម្រិតបាតប្រឡាយទឹកខ្ពស់ទាបខ្ពស់ទាប។ ប្រសិនបើខ្ពស់ជាងនេះ ថ្ម​ចេញនឹងមិនស្ថិរ។';
$ec_lang['rc_notes_7_term']='ការត្រួតពិនិត្យទឹកដាំងនៅច្រករបៀង';
$ec_lang['rc_notes_7_def']='នៅពេលជម្រៅធម្មតានៅក្នុងប្រឡាយបញ្ចូលតិចជាងជម្រៅទឹក weir (H<sub>p</sub>) ដែលចាំបាច់ដើម្បីឆ្លងកាត់ q<sub>t</sub> ការហូររួមចង្អៀត ឬទឹកដាំងកើតឡើងខ្ពស់ទឹក​​នៃ​ apron បញ្ចូល។ នេះជាទូទៅអាចទទួលយកបាន — ទឹកដាំងកាត់បន្ថយល្បឿន និងការពារការ침ខ្ទេចខ្ពស់ទឹក។ ដើម្បីត្រួតពិនិត្យ: ប្រើម៉ាស៊ីនគណនា weir flow ដើម្បីស្វែងរក H<sub>p</sub> សម្រាប់ q<sub>t</sub> និងទទឹង crest ដែលបានផ្ដល់ ហើយប្រៀបធៀបជាមួយជម្រៅធម្មតានៅក្នុងប្រឡាយបញ្ចូល។ ប្រសិនបើ H<sub>p</sub> លើសជម្រៅធម្មតា ទឹកដាំងនឹងកើតឡើង។';
$ec_lang['rc_notes_4_term']='ឯកសារយោង';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://doi.org/10.13031/2013.17230">រចនា rock chutes</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. USDA ARS ក៏បោះពុម្ពផ្សាយ <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">សន្លឹក Excel</a> ដោយផ្អែកលើវិធីដូចគ្នា។';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'តម្រង';
$ec_lang['rc_sketch_top_crest_curve'] = 'កោងកំពូល';
$ec_lang['rc_sketch_outlet_apron']    = 'ធុងទឹកចេញ';
$ec_lang['rc_sketch_radius']          = 'កាំ';
