<?php

// àáèéìíòóùú — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="frazione";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ft']="ft";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% pendenza";
$ec_lang['u_grade']="pendenza";
$ec_lang['u_in2']="poll^2";
$ec_lang['u_inh2o']="poll H2O";
$ec_lang['u_in']="poll";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/ft^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="s";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='Calcolatori HawsEDC';
$ec_lang['menu_main_list']='Elenco calcolatori';
$ec_lang['menu_main_hydraulics']='Idraulica';
$ec_lang['menu_main_language']='Lingua';
$ec_lang['template_welcome']='&gt;&gt; Lasciate le paure alla porta; qui l\'amore è la nostra lingua. Non state rovinando tutto. Godetevi anche gli <a target="_blank" href="https://hawsedc.com/download.php">strumenti gratuiti HawsEDC per AutoCAD.</a> &lt;&lt;';
$ec_lang['template_translation_help']='Hai una grande visione per una calcolatrice da aggiungere qui?  Puoi aiutarmi a migliorare le traduzioni, programmare o ospitare questi calcolatori?  ';
$ec_lang['template_feedback']='Condividi le tue preziose opinioni o suggerimenti. Questo calcolatore gratuito ha superato le tue aspettative in ogni modo?';
$ec_lang['template_printable_title']='Titolo stampabile';
$ec_lang['template_printable_subtitle']='Sottotitolo stampabile';
$ec_lang['index_title']='Calcolatori ingegneristici gratuiti online';
$ec_lang['calc_set_units']='Imposta unità:';
$ec_lang['points_data_help']='(o Copia/Incolla usando l\'area dati)';
$ec_lang['points_data_title']='Dati punti<br />(separati da virgola o tabulazione)';
$ec_lang['points_data_copy']='Copia';
$ec_lang['points_data_paste']='Incolla';
$ec_lang['calc_inputs']='Dati di input';
$ec_lang['calc_results']='Risultati';
$ec_lang['view_hide_line']='[Nascondi questa riga]';
$ec_lang['view_printable']='Versione stampabile (ricaricare per ripristinare)';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='Perdita di carico Darcy-Weisbach';
$ec_lang['dw_main_title']='Calcolatore gratuito online perdita di carico Darcy-Weisbach';
$ec_lang['dw_main_desc']='Perdita di carico in tubazione con Darcy-Weisbach a diametro, scabrezza e portata dati';
$ec_lang['dw_roughness']='Scabrezza assoluta Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Viscosità cinematica, v, in m<sup>2</sup>/s (1E-6 per acqua pulita a temperatura ambiente)';
$ec_lang['dw_reynolds_number']='Numero di Reynolds, Re';
$ec_lang['dw_flow_regime']='Regime di flusso';
$ec_lang['dw_regime_laminar']='laminare';
$ec_lang['dw_regime_transitional']='di transizione';
$ec_lang['dw_regime_turbulent']='turbolento';
$ec_lang['dw_friction_factor_method']='Metodo del coefficiente di attrito';
$ec_lang['dw_friction_factor']='Coefficiente di attrito, f';
// Hazen-Williams
$ec_lang['hw_main_menu']='Perdita di carico Hazen-Williams';
$ec_lang['hw_main_title']='Calcolatore gratuito online perdita di carico Hazen-Williams';
$ec_lang['hw_main_desc']='Perdita di carico in tubazione con Hazen-Williams a diametro, scabrezza e portata dati';
$ec_lang['hw_hgl_1']='HGL a valle';
$ec_lang['hw_hgl_2']='HGL a monte';
$ec_lang['hw_roughness']='Coefficiente Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canale irregolare Manning';
$ec_lang['mi_main_title']='Calcolatore gratuito online canale irregolare Manning';
$ec_lang['mi_main_desc']='Calcolatore flusso uniforme canale irregolare con formula di Manning';
$ec_lang['mi_waterSurfaceElevation']='Quota pelo libero';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Punti sezione trasversale';
$ec_lang['mi_groupPoint']='Punto';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_groupRegion']='Regione';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Quota';
$ec_lang['mi_d50in']='Dim.<br />med.<br />roccia<br />rivestim.';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />boundary<br />regione<br />(Sponda)';
$ec_lang['mi_tau']='Tensione<br />di fondo<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n com-<br />posto';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Note';
$ec_lang['mi_notes_1_term']='n composto';
$ec_lang['mi_notes_1_def']='Questo calcolatore segue il manuale di riferimento HEC-RAS nel calcolo del n composto della regione usando Chow 1959, pagina 136, equazione 6-17 (non 6-18).';
$ec_lang['mi_notes_2_term']='Rivestimento in roccia';
$ec_lang['mi_notes_2_def']='Usare il Calcolatore Canale Trapezoidale Manning per progettare il rivestimento in roccia. Questo calcolatore è più adatto per sezioni naturali.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Portata in tubazione Manning';
$ec_lang['mpf_main_title']='Calcolatore gratuito online portata in tubazione Manning';
$ec_lang['mpf_main_desc']='Formula di Manning per flusso uniforme in tubazione a pendenza e profondità date';
$ec_lang['mpf_spreadheet_notice']='Scopri la versione foglio di calcolo di questo calcolatore';
$ec_lang['mpf_pipe_diameter']='Diametro tubazione, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Scabrezza Manning, n';
$ec_lang['mpf_friction_slope']='Pendente idraulica (possibilmente <a target="_blank" href="../pressureslope.php">?</a> uguale alla pendenza della tubazione), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Rapporto di riempimento, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Vedi note)';
$ec_lang['mpf_flow']='Portata, Q';
$ec_lang['mpf_velocity']='Velocità, v';
$ec_lang['mpf_velocity_head']='Altezza cinetica, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Area bagnata, a';
$ec_lang['mpf_pipe_area']='Area totale tubazione, a0';
$ec_lang['mpf_area_ratio']='Rapporto di riempimento area, a/a0';
$ec_lang['mpf_wetted_perimeter']='Perimetro bagnato, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Raggio idraulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Larghezza pelo libero, T';
$ec_lang['mpf_froude_number']='Numero di Froude, F';
$ec_lang['mpf_shear_stress']='Tensione tangenziale media (forza trattiva), tau';
$ec_lang['mpf_full_flow']='Portata a sezione piena, Q0';
$ec_lang['mpf_full_flow_ratio']='Rapporto alla portata piena, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Questo è il flusso e la profondità all\'interno di una tubazione <em>infinitamente lunga</em>.</dt><dd>L\'immissione del flusso nella tubazione può richiedere un\'altezza idraulica significativamente maggiore. Aggiungere almeno 1,5 volte l\'altezza cinetica per l\'altezza idraulica o <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">vedere il tutorial di 2 minuti</a> per i calcoli standard del livello idraulico nei tombini con HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Calcola y/d<sub>0</sub> dato Q';
$ec_lang['mpf_solve_desc']='Usando D<sub>0</sub>, n, e S<sub>0</sub> dal modulo, trova il minimo y/d<sub>0</sub> per un dato Q.';
$ec_lang['mpf_solve_button']='Calcola';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='Perdita di carico in tubazione Manning';
$ec_lang['mphl_main_title']='Calcolatore gratuito online perdita di carico in tubazione Manning';
$ec_lang['mphl_main_desc']='Formula di Manning perdita di carico a portata piena data';
$ec_lang['mphl_pipe_length']='Lunghezza tubazione, L';
$ec_lang['mphl_area']='Area, A';
$ec_lang['mphl_total_junction_k']='Coefficiente totale perdita di carico ai giunti, k';
$ec_lang['mphl_friction_slope']='Pendente di attrito';
$ec_lang['mphl_friction_loss']='Perdita per attrito, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Perdita ai giunti, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Perdita totale, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL a valle';
$ec_lang['mphl_egl_2']='EGL a monte';
$ec_lang['mphl_hgl_2']='HGL a monte in tubazione ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Per una condizione di imbocco aperto (tombino), è necessario verificare le condizioni di controllo all\'imbocco.</dt><dd>1. L\'HGL a monte non può essere inferiore alla quota di deflusso a profondità normale a monte (o inferiore alla tubazione!).</dd><dd>2. Il livello idraulico di un tombino è meglio rappresentato dall\'EGL a monte che dall\'HGL a monte.</dd><dd>3. <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">Vedere il tutorial di 2 minuti</a> per semplici calcoli standard del livello idraulico nei tombini con HY-8.</dd>';
// Manning Trapezoid
$ec_lang['mtc_menu']='Canale trapezoidale Manning';
$ec_lang['mtc_main_title']='Calcolatore gratuito online formula di Manning canale trapezoidale';
$ec_lang['mtc_main_desc']='Flusso uniforme Manning in canale trapezoidale a pendenza e profondità date';
$ec_lang['mtc_bottom_width']='Larghezza di fondo, b';
$ec_lang['mtc_side_slope_1']='Scarpata lato 1 (orizz./vert.)';
$ec_lang['mtc_side_slope_2']='Scarpata lato 2 (orizz./vert.)';
$ec_lang['mtc_channel_slope']='Pendenza canale, S';
$ec_lang['mtc_flow_depth']='Profondità di flusso, y';
$ec_lang['mtc_bend_angle']='Angolo di curva <a target="_blank" href="riprap-bend-angle.png" title="Clicca per immagine">?</a> (per dimensionamento massi)';
$ec_lang['mtc_sgrock']='Peso specifico della roccia (2,65)';
$ec_lang['mtc_d50_in']='Dimensione roccia di progetto, D50';
$ec_lang['mtc_n_strickler']='n per dimensione roccia di progetto secondo Strickler';
$ec_lang['mtc_n_blodgett']='n per dimensione roccia di progetto secondo Blodgett';
$ec_lang['mtc_n_bathurst']='n per dimensione roccia di progetto secondo Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Dimensione roccia angolare richiesta sul fondo, D50 (Isbash &amp; MC) <a href="javascript:alert(\'Secondo Isbash (1936) e Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z1']='Dimensione roccia angolare richiesta scarpata 1, D50 (Isbash &amp; MC) <a href="javascript:alert(\'Secondo Isbash (1936) e Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z2']='Dimensione roccia angolare richiesta scarpata 2, D50 (Isbash &amp; MC) <a href="javascript:alert(\'Secondo Isbash (1936) e Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_mra']='Dimensione roccia angolare richiesta, D50 (Maynord, Ruff, e Abt 1989)';
$ec_lang['mtc_d50_searcy']='Dimensione roccia angolare richiesta, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Iterazione automatica dimensionamento roccia e scabrezza</dt><dd>Scegliere un pulsante radio per la scabrezza (BB raccomandato) e uno per la dimensione roccia di progetto (Isbash raccomandato). Regolare profondità e fattore di sicurezza della roccia per ottenere il flusso desiderato con una dimensione roccia uniforme. Ogni modifica ai dati avvia il ciclo iterativo: 1. La scabrezza viene calcolata dalla dimensione roccia di progetto. 2. La scabrezza richiesta viene copiata nella scabrezza di input. 3. Il flusso nel canale e la dimensione roccia richiesta vengono calcolati. 4. La dimensione roccia di progetto viene aggiornata. 5. Si ripete fino a convergenza.</dd><dt>Calcolatore base (senza iterazione)</dt><dd>Inserire il valore di scabrezza desiderato. Ignorare l\'area di input della dimensione roccia di progetto.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Rampa in massi Robinson';
$ec_lang['rrc_main_desc']='Foglio di calcolo progettazione rampa in massi Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Sfioratore semplice';
$ec_lang['ws_main_title']='Calcolatore gratuito online sfioratore largo a cresta semplice';
$ec_lang['ws_main_desc']='Calcolatore portata sfioratore largo a cresta semplice';
$ec_lang['ws_weirLength']='Lunghezza sfioratore, l';
$ec_lang['ws_headWaterHeight']='Altezza pelo libero a monte, h';
$ec_lang['ws_weirCoefficient']='Coefficiente sfioratore, Cw';
$ec_lang['ws_notes_heading']='Note';
$ec_lang['ws_notes_we_term']='Equazione sfioratore';
// Weir Flow Irregular
$ec_lang['wi_menu']='Sfioratore irregolare';
$ec_lang['wi_main_title']='Calcolatore gratuito online sfioratore irregolare a profondità variabile';
$ec_lang['wi_main_desc']='Calcolatore portata sfioratore irregolare';
$ec_lang['wi_headWaterelevation']='Quota pelo libero a monte';
$ec_lang['wi_weirPoints']='Punti sfioratore';
$ec_lang['wi_station']='Distanza';
$ec_lang['wi_elevation']='Quota';
$ec_lang['wi_pondingHeight']='Altezza di invaso';
$ec_lang['wi_incrementalFlow']='Portata incrementale';
$ec_lang['wi_cumulativeFlow']='Portata cumulativa';
$ec_lang['wi_save_and_calculate']='Salva e calcola';
$ec_lang['wi_notes_we_term']='Equazione sfioratore';
$ec_lang['wi_notes_we_def']='q = se (lunghezza = 0) allora 0 altrimenti se (slope=0) allora cw*lunghezza*d<sub>0</sub><sup>1.5</sup> altrimenti cw/(2.5*pendenza) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) dove d<sub>1</sub> e d<sub>0</sub> sono sempre positivi o zero';
// Orifice Flow
$ec_lang['or_main_menu']='Deflusso a orifizio';
$ec_lang['or_main_title']='Calcolatore gratuito online deflusso a orifizio';
$ec_lang['or_main_desc']='Deflusso a orifizio — libero o sommerso';
$ec_lang['or_shape']='Forma dell\'apertura';
$ec_lang['or_shape_circular']='Circolare';
$ec_lang['or_shape_rectangular']='Rettangolare';
$ec_lang['or_diameter']='Diametro (circolare) o altezza (rettangolare), D';
$ec_lang['or_width']='Larghezza, W (solo rettangolare)';
$ec_lang['or_invert']='Quota soletta apertura (fondo apertura)';
$ec_lang['or_hwe']='Quota pelo libero a monte';
$ec_lang['or_twe']='Quota pelo libero a valle';
$ec_lang['or_cd']='Coefficiente di deflusso, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Quota centroide';
$ec_lang['or_head']='Carico efficace, h';
$ec_lang['or_area']='Area apertura, A';
$ec_lang['or_flow']='Portata, Q';
$ec_lang['or_velocity']='Velocità all\'apertura, v';
$ec_lang['or_regime']='Verifica regime orifizio';
$ec_lang['or_regime_valid']='Uscita libera — regime orifizio valido ✓';
$ec_lang['or_regime_submerged']='Orifizio sommerso (TWE sopra la soletta) — valido ✓';
$ec_lang['or_regime_warn']='Attenzione: pelo libero a monte sotto la chiave — non è regime orifizio';
$ec_lang['or_regime_twe_above_hwe']='Attenzione: acqua a valle (TWE) sopra acqua a monte (HWE) — verificare i dati';
$ec_lang['or_notes_1_term']='Equazione orifizio';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Uscita libera: h = HWE &minus; centroide. Sommerso (TWE sopra la soletta): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regime orifizio';
$ec_lang['or_notes_2_def']='Le equazioni del deflusso a orifizio si applicano quando il pelo libero a monte è sopra la chiave (sommità) dell\'apertura. Quando è sotto la chiave, utilizzare un\'equazione di sfioratore.';
$ec_lang['or_notes_3_term']='Coefficiente di deflusso';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varia da circa 0,60 a 0,65 per orifizi a spigolo vivo. Imbocchi arrotondati o rientranti hanno valori diversi. Vedere <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> o il Manuale di Riferimento Idraulico HEC-RAS.';
$ec_lang['or_notes_4_term']='Sommersione';
$ec_lang['or_notes_4_def']='Quando TWE è sopra la soletta dell\'apertura, la calcolatrice applica automaticamente l\'equazione dell\'orifizio sommerso usando h = HWE &minus; TWE. Quando TWE è pari o inferiore alla soletta, si assume uscita libera e h = HWE &minus; centroide.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Tempo di svuotamento a orifizio';
$ec_lang['odt_main_title']='Calcolatore gratuito online tempo di svuotamento a orifizio';
$ec_lang['odt_main_desc']='Tempo di svuotamento vasca tramite orifizio &mdash; Metodo volume conico';
$ec_lang['odt_h1_elev']='Quota pelo libero iniziale';
$ec_lang['odt_a1']='Area vasca iniziale, A1';
$ec_lang['odt_h2_elev']='Quota pelo libero finale';
$ec_lang['odt_h_orifice']='Quota centroide orifizio';
$ec_lang['odt_a0']='Area vasca alla quota orifizio, A0';
$ec_lang['odt_a_ending']='Area vasca finale, A2 (interpolata)';
$ec_lang['odt_h2_check']='Verifica quota finale';
$ec_lang['odt_h2_ok']='Quota finale sopra la sommità dell\'orifizio ✓';
$ec_lang['odt_h2_warn']='Attenzione: quota finale pari o inferiore alla sommità orifizio (centroide + D/2)';
$ec_lang['odt_d']='Diametro orifizio (circolare) o altezza (rettangolare), D';
$ec_lang['odt_w']='Larghezza orifizio, W (solo rettangolare)';
$ec_lang['odt_t_sec']='Tempo di svuotamento (secondi)';
$ec_lang['odt_t_min']='Tempo di svuotamento (minuti)';
$ec_lang['odt_t_hr']='Tempo di svuotamento (ore)';
$ec_lang['odt_t_day']='Tempo di svuotamento (giorni)';
$ec_lang['odt_notes_1_term']='Formula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) fornisce il tempo di svuotamento dal carico H all\'orifizio. Tempo di svuotamento = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), dove H<sub>1</sub> = quota iniziale &minus; quota orifizio, H<sub>2</sub> = quota finale &minus; quota orifizio.';
$ec_lang['odt_notes_2_term']='Metodo';
$ec_lang['odt_notes_2_def']='Il metodo del volume conico modella la vasca come sezione conica tra l\'area iniziale A<sub>1</sub> al pelo libero iniziale e l\'area A<sub>0</sub> alla quota del centroide dell\'orifizio. A<sub>2</sub>, l\'area della vasca alla quota finale, è interpolata da A<sub>1</sub> e A<sub>0</sub> usando il modello conico. Il tempo di svuotamento dalla quota iniziale alla finale equivale al tempo totale da H<sub>1</sub> all\'orifizio meno il tempo rimanente da H<sub>2</sub> all\'orifizio.';
$ec_lang['odt_h1']='Carico iniziale, H<sub>1</sub> (WSE &minus; centroide)';
$ec_lang['odt_q_max']='Portata massima (iniziale), Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume svuotato';
$ec_lang['odt_sketch_start']='Inizio';
$ec_lang['odt_sketch_end']='Fine';
// Erosion Setback
$ec_lang['essc_btbw']='Larghezza di sponda a sponda';
$ec_lang['essc_mcr']='Raggio minimo di curvatura';
$ec_lang['essc_q']='Portata, Q';
// Contact

// Irrigation
$ec_lang['irr_main_menu']='Misurazione del Flusso di Irrigazione';
$ec_lang['irr_main_title']='Calcolatrici Online Gratuite per la Misurazione del Flusso di Irrigazione';
$ec_lang['irr_main_desc']='Misurazione del Flusso di Irrigazione — Stramazzi e Orifizi';
$ec_lang['contact_title']='Contatti HawsEDC';
$ec_lang['contactSendMessage']='Invia un messaggio a Tom Haws';
$ec_lang['contactYourName']='Nome:';
$ec_lang['contactYourEmail']='Indirizzo e-mail:';
$ec_lang['contactSubject']='Oggetto:';
$ec_lang['contact_message']='Messaggio:';
$ec_lang['contactSpamPrefix']='Cinque più uno è';
$ec_lang['contactSpamPostfix']='(Scrivere in inglese. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Invia messaggio';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Idroelettrico';
$ec_lang['mhp_main_title']='Calcolatore Gratuito di Potenza Micro-Idroelettrica';
$ec_lang['mhp_main_desc']='Calcolatore di Potenza Micro-Idroelettrica ad Acqua Fluente';
$ec_lang['mhp_flow']='Portata, Q';
$ec_lang['mhp_gross_head']='Salto lordo (dislivello), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Perdite di carico nella condotta forzata, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Rendimento dell\'impianto, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Salto netto, H<sub>net</sub>';
$ec_lang['mhp_power']='Potenza prodotta, P';
$ec_lang['mhp_annual_kwh']='Energia annua al 100% di capacità';
$ec_lang['mhp_notes_1_term']='Equazione di Potenza';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, dove &rho; = 1000 kg/m&sup3; (acqua dolce) e g = 9,806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Salto Netto';
$ec_lang['mhp_notes_2_def']='Salto netto = salto lordo &minus; perdite di carico nella condotta forzata. Una prima stima comune è h<sub>L</sub> &asymp; 5% di H<sub>gross</sub>. Utilizzare il <a href="Darcy-Weisbach.php">calcolatore Darcy-Weisbach</a> per stime più accurate delle perdite nella condotta forzata.';
$ec_lang['mhp_notes_3_term']='Rendimento';
$ec_lang['mhp_notes_3_def']='Il rendimento tipico dell\'impianto &eta; varia da 0,70 a 0,85 per le turbine Pelton e a flusso incrociato, comuni nel micro-idroelettrico. Usare 0,75 come prima stima conservativa.';
$ec_lang['mhp_notes_4_term']='Energia Annua';
$ec_lang['mhp_notes_4_def']='L\'energia annua presuppone un funzionamento continuo a piena portata (8760 ore/anno). La produzione effettiva sarà inferiore a causa della variazione stagionale della portata, dei fermi per manutenzione e del fattore di carico.';
// Penstock Design
$ec_lang['ps_main_menu']='Progetto condotta forzata';
$ec_lang['ps_main_title']='Calcolatore gratuito online per condotte forzate';
$ec_lang['ps_main_desc']='Dimensionamento della condotta forzata micro-idroelettrica — Perdita di carico, potenza e velocità';
$ec_lang['ps_flow']='Portata, Q';
$ec_lang['ps_gross_head']='Altezza lorda, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Diametro della condotta forzata, D';
$ec_lang['ps_length']='Lunghezza della condotta forzata, L';
$ec_lang['ps_roughness']='Rugosità della tubazione, e';
$ec_lang['ps_km']='Coefficiente di perdita minore, k<sub>m</sub>';
$ec_lang['ps_nu']='Viscosità cinematica, &nu;, in m<sup>2</sup>/s (1E-6 per acqua vicino a 20&deg;C)';
$ec_lang['ps_efficiency']='Rendimento dell\'impianto, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Velocità di flusso, v';
$ec_lang['ps_vel_check']='Verifica della velocità';
$ec_lang['ps_f']='Fattore di attrito, f';
$ec_lang['ps_hf']='Perdita di carico per attrito, h<sub>f</sub>';
$ec_lang['ps_hm']='Perdita di carico minore, h<sub>m</sub>';
$ec_lang['ps_hl']='Perdita totale nella condotta forzata, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Verifica della perdita di carico';
$ec_lang['ps_hnet']='Altezza netta, H<sub>net</sub>';
$ec_lang['ps_power']='Potenza prodotta, P';
$ec_lang['ps_annual_kwh']='Energia annua al 100% di capacità';
$ec_lang['ps_vel_ok']='1–3 m/s — nell\'intervallo target ✓';
$ec_lang['ps_vel_low']='inferiore a 1 m/s — aumentare il diametro ⚠';
$ec_lang['ps_vel_high']='superiore a 3 m/s — ridurre il diametro ⚠';
$ec_lang['ps_hl_ok']='entro il target del 10% ✓';
$ec_lang['ps_hl_warn']='supera il target del 10% — considerare una tubazione più grande ⚠';
$ec_lang['ps_hl_bad']='supera il 20% — ridimensionare la tubazione';
$ec_lang['ps_notes_1_term']='Perdita di carico';
$ec_lang['ps_notes_1_def']='Perdita totale nella condotta forzata h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, dove h<sub>f</sub> = f(L/D)(v&sup2;/2g) è la perdita per attrito di Darcy-Weisbach e h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g comprende imbocchi, curve e valvole. Altezza netta H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Velocità';
$ec_lang['ps_notes_2_def']='Obiettivo: 1&ndash;3 m/s. Al di sotto di 1 m/s la tubazione risulta sovradimensionata per la portata; al di sopra di 3 m/s aumentano le perdite per attrito e il rischio di colpo d\'ariete.';
$ec_lang['ps_notes_3_term']='Obiettivo di perdita di carico';
$ec_lang['ps_notes_3_def']='Perdite nella condotta forzata inferiori al 10% dell\'altezza lorda sono generalmente economiche. Il compromesso ottimale tra costo della tubazione e potenza persa si attesta spesso intorno al 4&ndash;6% per i siti ad alta valorizzazione dell\'energia elettrica.';
$ec_lang['ps_notes_4_term']='Perdite minori k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Valori tipici: imbocco con spigolo vivo 0,5, ogni curva a 45&deg; 0,2&ndash;0,3, saracinesca (completamente aperta) 0,1, valvola a farfalla 0,2. Sommare tutti i raccordi per ottenere il k<sub>m</sub> totale. Il valore predefinito 1,5 presuppone un imbocco e due curve.';
$ec_lang['ps_notes_5_term']='Rugosità della tubazione e';
$ec_lang['ps_notes_5_def']='Rugosità assoluta tipica: acciaio (nuovo) 0,046&nbsp;mm, acciaio (usato) 0,15&nbsp;mm, HDPE 0,003&nbsp;mm, PVC/uPVC 0,0015&nbsp;mm, calcestruzzo 0,3&ndash;3&nbsp;mm. L\'HDPE è comune nelle condotte forzate di piccoli impianti micro-idroelettrici.';

// About
$ec_lang['about_main_menu']='Informazioni';
$ec_lang['about_main_title']='Informazioni sui calcolatori HawsEDC';
$ec_lang['about_main_desc']='Missione, open source e contributi';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Drip/Sprinkler Application Rate';
$ec_lang['ds_main_title']='Free Online Drip/Sprinkler Irrigation Application Rate Calculator';
$ec_lang['ds_main_desc']='Drip &amp; Sprinkler Irrigation &mdash; Application Rate and Uniformity';
$ec_lang['ds_q_avg']='Average emitter flow rate, q';
$ec_lang['ds_q_min']='Minimum emitter flow rate, q<sub>min</sub>';
$ec_lang['ds_se']='Emitter spacing along lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateral spacing (row spacing), S<sub>l</sub>';
$ec_lang['ds_n_e']='Emitters per lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Laterals per zone, n<sub>l</sub>';
$ec_lang['ds_d']='Target application depth, d';
$ec_lang['ds_a_e']='Area per emitter, A<sub>e</sub>';
$ec_lang['ds_pr']='Application rate (precipitation rate), PR';
$ec_lang['ds_du']='Distribution uniformity, DU';
$ec_lang['ds_du_check']='DU quality check';
$ec_lang['ds_q_lat']='Flow per lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Zone flow, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Runtime for target depth (hours)';
$ec_lang['ds_du_excellent']='Excellent &mdash; DU &ge; 90% ✓';
$ec_lang['ds_du_good']='Good &mdash; DU &ge; 80% ✓';
$ec_lang['ds_du_acceptable']='Acceptable &mdash; DU &ge; 70%';
$ec_lang['ds_du_poor']='Poor &mdash; DU &lt; 70% &mdash; review design ⚠';
$ec_lang['ds_notes_1_term']='Application Rate';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, where A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> is the area served by each emitter. A lower application rate gives more time for infiltration &mdash; important on heavy soils or sloped fields.';
$ec_lang['ds_notes_2_term']='Distribution Uniformity (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. A DU of 1.0 (100%) means all emitters flow identically. Values below 0.80 waste water on well-watered areas while leaving drier spots. Uniformity drops with excessive pressure variation along the lateral, emitter wear, or partial clogging.';
$ec_lang['ds_notes_3_term']='Runtime';
$ec_lang['ds_notes_3_def']='Runtime = target depth &divide; application rate. On sloping or compacted soil, split the runtime into two or three shorter cycles with rest periods between them to avoid surface runoff.';
