<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='частка';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% підйом/довжина';
$ec_lang['u_grade']='підйом/довжина';
$ec_lang['u_in2']='кв. дюйм';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='л/с';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='с';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Calculators';
$ec_lang['menu_main_list']='Список калькуляторів';
$ec_lang['menu_main_hydraulics']='Гідравліка';
$ec_lang['menu_main_language']='Мова';
$ec_lang['menu_more']='Ще';
$ec_lang['template_welcome']='>> Залиш свої страхи за дверима; тут розмовляють мовою любові. Ти не все руйнуєш. Насолоджуйся також <a target="_blank" href="https://hawsedc.com/download.php">безкоштовними інструментами HawsEDC AutoCAD</a>. <<';
$ec_lang['template_translation_help']='Чи маєте ви ідею для нового калькулятора? Чи можете допомогти з перекладом, програмуванням або розміщенням цих калькуляторів? ';
$ec_lang['template_feedback']='Будь ласка, поділіться своїми цінними порадами або словами подяки. Чи перевершив цей безкоштовний калькулятор ваші очікування?';
$ec_lang['template_printable_title']='Заголовок для друку';
$ec_lang['template_printable_subtitle']='Підзаголовок для друку';
$ec_lang['index_title']='Безкоштовні онлайн-калькулятори для інженерів';
$ec_lang['calc_set_units']='Встановити одиниці:';
$ec_lang['points_data_help']='(або Копіювати/Вставити через область даних)';
$ec_lang['points_data_title']='Дані точок<br />(розділені комою або табуляцією)';
$ec_lang['points_data_copy']='Копіювати';
$ec_lang['points_data_paste']='Вставити';
$ec_lang['calc_inputs']='Вхідні дані';
$ec_lang['calc_results']='Результати';
$ec_lang['view_hide_line']='[Сховати цей рядок]';
$ec_lang['view_printable']='Версія для друку (перезавантажте для відновлення)';
$ec_lang['ec_name_label']='Збережіть цей розрахунок:';
$ec_lang['ec_name_placeholder']='Назва';
$ec_lang['ec_name_hint']='Зберігає ці вхідні дані у URL для створення закладки, отримання історії та спільного доступу';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Втрати напору в трубі за Darcy-Weisbach';
$ec_lang['dw_main_title']='Безкоштовний онлайн-калькулятор втрат напору в трубі за Darcy-Weisbach';
$ec_lang['dw_main_desc']='Втрати напору в трубі за Darcy-Weisbach при заданому діаметрі, шорсткості та витраті';
$ec_lang['dw_roughness']='Абсолютна шорсткість Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Кінематична в’язкість, ν <span title="1×10⁻⁶ m²/s для чистої води при 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Число Рейнольдса, Re';
$ec_lang['dw_flow_regime']='Режим течії';
$ec_lang['dw_regime_laminar']='ламінарний';
$ec_lang['dw_regime_transitional']='перехідний';
$ec_lang['dw_regime_turbulent']='турбулентний';
$ec_lang['dw_friction_factor_method']='Метод визначення коефіцієнта тертя';
$ec_lang['dw_friction_factor']='Коефіцієнт тертя, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Втрати напору в трубі за Hazen-Williams';
$ec_lang['hw_main_title']='Безкоштовний онлайн-калькулятор втрат напору в трубі за Hazen-Williams';
$ec_lang['hw_main_desc']='Втрати напору в трубі за Hazen-Williams при заданому діаметрі, шорсткості та витраті';
$ec_lang['hw_hgl_1']='П\'єзометрична лінія нижче за течією';
$ec_lang['hw_hgl_2']='П\'єзометрична лінія вище за течією';
$ec_lang['hw_roughness']='Коефіцієнт Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning — Нерегулярне русло';
$ec_lang['mi_main_title']='Безкоштовний онлайн-калькулятор нерегулярного русла за Manning';
$ec_lang['mi_main_desc']='Калькулятор рівномірної течії в нерегулярному руслі за Manning';
$ec_lang['mi_waterSurfaceElevation']='Відмітка поверхні води';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Точки поперечного перерізу';
$ec_lang['mi_groupPoint']='Точка';
$ec_lang['mi_groupSegment']='Ділянка';
$ec_lang['mi_groupRegion']='Зона';
$ec_lang['mi_station']='Пікет';
$ec_lang['mi_elevation']='Відмітка';
$ec_lang['mi_d50in']='Облицювання<br />медіанний<br />розмір<br />каменю';
$ec_lang['mi_n']='n<br />для<br />ділян-<br />ки';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />межа<br />зони<br />(Берег)';
$ec_lang['mi_tau']='Дон.<br />дотич.<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Композ.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Примітки';
$ec_lang['mi_notes_1_term']='Складений n';
$ec_lang['mi_notes_1_def']='Цей калькулятор дотримується довідкового посібника HEC-RAS у розрахунку складеного n зони за Chow 1959, стор. 136, рівняння 6-17 (не 6-18).';
$ec_lang['mi_notes_2_term']='Кам\'яне облицювання';
$ec_lang['mi_notes_2_def']='Для проектування кам\'яного облицювання використовуйте калькулятор трапецієвидного русла Manning. Цей калькулятор призначений більше для природних перерізів.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning — Течія в трубі';
$ec_lang['mpf_main_title']='Безкоштовний онлайн-калькулятор течії в трубі за Manning';
$ec_lang['mpf_main_desc']='Рівномірна течія в трубі за формулою Manning при заданому похилі та глибині';
$ec_lang['mpf_spreadheet_notice']='Ознайомтесь з табличною версією цього калькулятора';
$ec_lang['mpf_pipe_diameter']='Діаметр труби, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Коефіцієнт шорсткості Manning, n';
$ec_lang['mpf_friction_slope']='Похил п\'єзометричної лінії (можливо <a target="_blank" href="../pressureslope.php">?</a> дорівнює похилу труби), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Відносна глибина течії, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Дивіться примітки)';
$ec_lang['mpf_flow']='Витрата, Q';
$ec_lang['mpf_velocity']='Швидкість, v';
$ec_lang['mpf_velocity_head']='Швидкісний напір, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Площа живого перерізу, a';
$ec_lang['mpf_pipe_area']='Площа перерізу труби, a0';
$ec_lang['mpf_area_ratio']='Відносна площа, a/a0';
$ec_lang['mpf_wetted_perimeter']='Змочений периметр, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Гідравлічний радіус, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Ширина по поверхні, T';
$ec_lang['mpf_froude_number']='Число Фруда, F';
$ec_lang['mpf_shear_stress']='Середнє дотичне напруження (тягнуча сила), tau';
$ec_lang['mpf_full_flow']='Витрата при повному заповненні, Q0';
$ec_lang['mpf_full_flow_ratio']='Відношення до повної витрати, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Це витрата і глибина всередині <em>нескінченно довгої</em> труби.</dt><dd>Для забезпечення надходження потоку в трубу може знадобитися значно більша глибина підпору. Додайте не менше 1.5 швидкісного напору для визначення глибини підпору, або <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">дивіться мій 2-хвилинний посібник</a> зі стандартних розрахунків підпору водопропускних труб за HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Визначити y/d<sub>0</sub> при заданій Q';
$ec_lang['mpf_solve_desc']='Використовуючи D<sub>0</sub>, n та S<sub>0</sub> з форми калькулятора, знаходить найменше y/d<sub>0</sub> для заданої Q.';
$ec_lang['mpf_solve_button']='Розрахувати';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning — Втрати напору в трубі';
$ec_lang['mphl_main_title']='Безкоштовний онлайн-калькулятор втрат напору в трубі за Manning';
$ec_lang['mphl_main_desc']='Втрати напору за формулою Manning при заданій витраті повного перерізу';
$ec_lang['mphl_pipe_length']='Довжина труби, L';
$ec_lang['mphl_area']='Площа, A';
$ec_lang['mphl_total_junction_k']='Сумарний коефіцієнт місцевих втрат, k';
$ec_lang['mphl_friction_slope']='Похил тертя';
$ec_lang['mphl_friction_loss']='Втрати на тертя, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Місцеві втрати, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Сумарні втрати, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='Лінія питомої енергії нижче за течією';
$ec_lang['mphl_egl_2']='Лінія питомої енергії вище за течією';
$ec_lang['mphl_hgl_2']='П\'єзометрична лінія в трубі вище за течією ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>При відкритому вхідному (водопропускному) режимі необхідно перевірити умови управління на вході.</dt><dd>1. П\'єзометрична лінія вище за течією не може бути нижче відмітки рівномірної течії нормальної глибини вище за течією (і не може бути нижче труби!).</dd><dd>2. Підпір водопропускної труби краще характеризується лінією питомої енергії вище за течією, а не п\'єзометричною лінією.</dd><dd>3. Дивіться <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">мій 2-хвилинний посібник</a> зі стандартних розрахунків підпору водопропускних труб за HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning — Трапецієвидне русло';
$ec_lang['mtc_main_title']='Безкоштовний онлайн-калькулятор трапецієвидного русла за формулою Manning';
$ec_lang['mtc_main_desc']='Рівномірна течія в трапецієвидному руслі за формулою Manning при заданому похилі та глибині';
$ec_lang['mtc_bottom_width']='Ширина дна, b';
$ec_lang['mtc_side_slope_1']='Закладення укосу 1 (горизонт./верт.)';
$ec_lang['mtc_side_slope_2']='Закладення укосу 2 (горизонт./верт.)';
$ec_lang['mtc_channel_slope']='Похил русла, S';
$ec_lang['mtc_flow_depth']='Глибина течії, y';
$ec_lang['mtc_bend_angle']='Кут повороту <a target="_blank" href="riprap-bend-angle.png" title="Натисніть для перегляду зображення">?</a> (для підбору розміру каменю)';
$ec_lang['mtc_sgrock']='Питома вага каменю (2.65)';
$ec_lang['mtc_d50_in']='Розрахунковий розмір каменю, D50';
$ec_lang['mtc_n_strickler']='n для розрахункового розміру каменю за Strickler';
$ec_lang['mtc_n_blodgett']='n для розрахункового розміру каменю за Blodgett';
$ec_lang['mtc_n_bathurst']='n для розрахункового розміру каменю за Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett проти Bathurst';
$ec_lang['mtc_d50_bottom']='Необхідний розмір кутастого каменю для дна, D50 (Isbash & MC) <span title="За Isbash (1936) та округом Маріколь, Арізона, США." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Необхідний розмір кутастого каменю для укосу 1, D50 (Isbash & MC) <span title="За Isbash (1936) та округом Маріколь, Арізона, США." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Необхідний розмір кутастого каменю для укосу 2, D50 (Isbash & MC) <span title="За Isbash (1936) та округом Маріколь, Арізона, США." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Необхідний розмір кутастого каменю, D50 (Maynord, Ruff та Abt 1989)';
$ec_lang['mtc_d50_searcy']='Необхідний розмір кутастого каменю, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Автоматична ітерація розміру каменю та шорсткості</dt><dd>Виберіть перемикач шорсткості (рекомендується BB) та перемикач розрахункового розміру каменю (рекомендується Isbash). Підберіть глибину та коефіцієнт запасу розміру каменю для досягнення бажаної витрати із зручним розміром каменю. Щоразу при зміні вхідного значення відбувається наступний цикл ітерації: 1. Шорсткість розраховується за розрахунковим розміром каменю. 2. Результат розрахунку шорсткості копіюється у вхідну шорсткість. 3. Розраховуються витрата русла та необхідний розмір каменю. 4. Розрахунковий розмір каменю коригується. 5. Повторювати до досягнення дуже малої похибки розміру каменю.</dd><dt>Базовий калькулятор (без ітерації)</dt><dd>Введіть бажане значення шорсткості. Поле розрахункового розміру каменю ігноруйте.</dd></dl>';
// Robinson Rock Chute
// Weir Flow Simple
$ec_lang['ws_main_menu']='Водозлив — Простий';
$ec_lang['ws_main_title']='Безкоштовний онлайн-калькулятор течії через простий широкогребінчастий водозлив';
$ec_lang['ws_main_desc']='Калькулятор течії через простий широкогребінчастий водозлив';
$ec_lang['ws_weirLength']='Довжина водозливу, l';
$ec_lang['ws_headWaterHeight']='Висота підпору, h';
$ec_lang['ws_weirCoefficient']='Коефіцієнт водозливу, Cw';
$ec_lang['ws_notes_heading']='Примітки';
$ec_lang['ws_notes_we_term']='Рівняння водозливу';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Водозлив — Нерегулярний';
$ec_lang['wi_main_title']='Безкоштовний онлайн-калькулятор течії через сегментований нерегулярний водозлив зі змінною глибиною';
$ec_lang['wi_main_desc']='Калькулятор течії через нерегулярний водозлив';
$ec_lang['wi_headWaterelevation']='Відмітка рівня підпору';
$ec_lang['wi_weirPoints']='Точки водозливу';
$ec_lang['wi_station']='Пікет<br />(відстань)';
$ec_lang['wi_elevation']='Відмітка';
$ec_lang['wi_pondingHeight']='Висота підтоплення';
$ec_lang['wi_incrementalFlow']='Часткова витрата';
$ec_lang['wi_cumulativeFlow']='Накопичена витрата';
$ec_lang['wi_save_and_calculate']='Зберегти та розрахувати';
$ec_lang['wi_notes_we_term']='Рівняння водозливу';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='Витікання через отвір';
$ec_lang['or_main_title']='Безкоштовний онлайн-калькулятор витікання через отвір';
$ec_lang['or_main_desc']='Витікання через отвір — вільне або підтоплене';
$ec_lang['or_shape']='Форма отвору';
$ec_lang['or_shape_circular']='Кругла';
$ec_lang['or_shape_rectangular']='Прямокутна';
$ec_lang['or_diameter']='Діаметр або висота, D <span title="Діаметр для круглого; висота для прямокутного" class="ec-tip">?</span>';
$ec_lang['or_width']='Ширина, W <span title="Прямокутні отвори тільки" class="ec-tip">?</span>';
$ec_lang['or_invert']='Відмітка лотка <span title="Низ отвору" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Відмітка рівня підпору';
$ec_lang['or_twe']='Відмітка рівня нижнього б\'єфу';
$ec_lang['or_cd']='Коефіцієнт витрати, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Відмітка центроїда';
$ec_lang['or_head']='Ефективний напір, h';
$ec_lang['or_area']='Площа отвору, A';
$ec_lang['or_flow']='Витрата, Q';
$ec_lang['or_velocity']='Швидкість, v';
$ec_lang['or_regime']='Перевірка режиму отвору';
$ec_lang['or_regime_valid']='Вільний злив — режим отвору діє ✓';
$ec_lang['or_regime_submerged']='Підтоплений отвір (TWE вище центроїда) — діє ✓';
$ec_lang['or_regime_warn']='Попередження: підпір нижче гребеня — не режим отвору';
$ec_lang['or_regime_twe_above_hwe']='Попередження: нижній б\'єф (TWE) вище підпору (HWE) — перевірте вхідні дані';
$ec_lang['or_notes_1_term']='Рівняння отвору';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). При вільному зливі: h = HWE − центроїд. При підтопленні (TWE вище лотка): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Режим отвору';
$ec_lang['or_notes_2_def']='Рівняння отвору застосовуються, коли поверхня підпору знаходиться вище гребеня (верху) отвору. Коли підпір нижче гребеня, використовуйте рівняння водозливу.';
$ec_lang['or_notes_3_term']='Коефіцієнт витрати';
$ec_lang['or_notes_3_def']='C<sub>d</sub> знаходиться в межах приблизно 0.60–0.65 для гостроокрайних отворів. Для заокруглених або втоплених входів використовуються інші значення. Дивіться <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> або гідравлічний довідковий посібник HEC-RAS.';
$ec_lang['or_notes_4_term']='Підтоплення';
$ec_lang['or_notes_4_def']='Коли TWE знаходиться вище лотка отвору, калькулятор автоматично застосовує рівняння підтопленого отвору з h = HWE − TWE. Коли TWE на рівні або нижче лотка, приймається вільний злив і h = HWE − центроїд.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Мікро-гідроелектростанція';
$ec_lang['mhp_main_title']='Безкоштовний онлайн-калькулятор потужності мікро-ГЕС';
$ec_lang['mhp_main_desc']='Калькулятор потужності русловій мікро-ГЕС';
$ec_lang['mhp_flow']='Витрата, Q';
$ec_lang['mhp_gross_head']='Повний напір, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Діаметр напірного трубопроводу, D';
$ec_lang['mhp_length']='Довжина напірного трубопроводу, L';
$ec_lang['mhp_roughness']='Шорсткість труби, e';
$ec_lang['mhp_km']='Коефіцієнт місцевих втрат, k<sub>m</sub> <span title="Сума всіх коефіцієнтів місцевих втрат вздовж пеньківки" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Кінематична в\'язкість, ν <span title="1×10⁻⁶ m²/s для чистої води близько 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='ККД установки, η (0–1)';
$ec_lang['mhp_velocity']='Швидкість течії, v';
$ec_lang['mhp_vel_check']='Перевірка швидкості';
$ec_lang['mhp_f']='Коефіцієнт тертя, f';
$ec_lang['mhp_hf']='Втрати напору на тертя, h<sub>f</sub>';
$ec_lang['mhp_hm']='Втрати напору, h<sub>m</sub>';
$ec_lang['mhp_hl']='Сумарні втрати в трубопроводі, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Перевірка втрат напору';
$ec_lang['mhp_hnet']='Чистий напір, H<sub>net</sub>';
$ec_lang['mhp_power']='Потужність, P';
$ec_lang['mhp_annual_kwh']='Річна виробітка при 100% завантаженні';
$ec_lang['mhp_vel_ok']='1–3 m/s — в межах норми ✓';
$ec_lang['mhp_vel_low']='Швидкість низька — ризик замулення та захоплення повітря.';
$ec_lang['mhp_vel_high']='Швидкість висока — ризик гідравлічного удару та місцевих втрат.';
$ec_lang['mhp_vel_ok_short']='ОК';
$ec_lang['mhp_vel_high_short']='Висока';
$ec_lang['mhp_vel_low_short']='Низька';
$ec_lang['mhp_hl_ok']='в межах 10% норми ✓';
$ec_lang['mhp_hl_warn']='перевищує норму 10% — розгляньте більшу трубу ⚠';
$ec_lang['mhp_hl_bad']='перевищує 20% — підберіть іншу трубу';
$ec_lang['mhp_notes_1_term']='Втрати напору';
$ec_lang['mhp_notes_1_def']='Сумарні втрати в трубопроводі h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, де h<sub>f</sub> = f(L/D)(v²/2g) — втрати на тертя за Darcy-Weisbach, а h<sub>m</sub> = k<sub>m</sub>·v²/2g — втрати на вході, поворотах і засувках. Чистий напір H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Швидкість';
$ec_lang['mhp_notes_2_def']='Цільовий діапазон 1–3 m/s. Нижче 1 m/s — труба завелика для даної витрати; вище 3 m/s — зростають втрати на тертя та ризик гідравлічного удару.';
$ec_lang['mhp_notes_3_term']='Цільові втрати напору';
$ec_lang['mhp_notes_3_def']='Втрати в напірному трубопроводі нижче 10% від повного напору, як правило, є економічно обґрунтованими. Оптимальний компроміс між вартістю труби та втраченою потужністю зазвичай становить 4–6% для об\'єктів з високою вартістю електроенергії.';
$ec_lang['mhp_notes_4_term']='Місцеві втрати k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Ці втрати виникають у з\'єднаннях труб, на входах, поворотах та засувках — термін "малі" є умовним і оманливим; у короткому трубопроводі вони можуть дорівнювати або перевищувати втрати на тертя. Типові значення k: гострий вхідний отвір 0.5, кожен поворот на 45° 0.2–0.3, шиберна засувка (повністю відкрита) 0.1, метеликова засувка 0.2. Сумуйте всі фітинги для отримання k<sub>m</sub>. За замовчуванням 1.5 передбачає один вхід та два поворота.';
$ec_lang['mhp_notes_5_term']='Шорсткість труби e';
$ec_lang['mhp_notes_5_def']='Типова абсолютна шорсткість: сталь (нова) 0.046 mm, сталь (б/у) 0.15 mm, HDPE 0.003 mm, ПВХ/uPVC 0.0015 mm, бетон 0.3–3 mm. HDPE широко застосовується для малих напірних трубопроводів мікро-ГЕС.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Час спорожнення через отвір';
$ec_lang['odt_main_title']='Безкоштовний онлайн-калькулятор часу спорожнення через отвір — ставок, басейн або резервуар';
$ec_lang['odt_main_desc']='Час спорожнення ставка або басейну через отвір — метод конічного об\'єму';
$ec_lang['odt_h1_elev']='Початкова відмітка поверхні <span title="Початкова висота поверхні води" class="ec-tip">?</span>';
$ec_lang['odt_a1']='Початкова площа, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Кінцева відмітка поверхні';
$ec_lang['odt_h_orifice']='Відмітка центроїда отвору';
$ec_lang['odt_a0']='Площа на рівні отвору, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Кінцева площа, A<sub>2</sub> <span title="Інтерпольована з конічної моделі на кінцевій відмітці" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='Перевірка кінцевої відмітки';
$ec_lang['odt_h2_ok']='Кінцева відмітка вище верху отвору ✓';
$ec_lang['odt_h2_warn']='Попередження: кінцева відмітка на рівні або нижче верху отвору (центроїд + D/2)';
$ec_lang['odt_d']='Діаметр отвору D <span title="Діаметр (круглий) або висота (прямокутний)" class="ec-tip">?</span>';
$ec_lang['odt_w']='Ширина отвору, W <span title="Прямокутні отвори тільки" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='Час спорожнення (s)';
$ec_lang['odt_t_min']='Час спорожнення (min)';
$ec_lang['odt_t_hr']='Час спорожнення (hr)';
$ec_lang['odt_t_day']='Час спорожнення (days)';
$ec_lang['odt_notes_1_term']='Формула';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) дає час спорожнення від напору H до отвору. Час спорожнення = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), де H<sub>1</sub> = початкова відмітка − відмітка отвору, H<sub>2</sub> = кінцева відмітка − відмітка отвору.';
$ec_lang['odt_notes_2_term']='Метод';
$ec_lang['odt_notes_2_def']='Метод конічного об\'єму моделює ставок або басейн як конічний перетин між початковою площею A<sub>1</sub> на початковій поверхні води та площею A<sub>0</sub> на відмітці центроїда отвору. A<sub>2</sub>, площа ставка на кінцевій відмітці, інтерполюється між A<sub>1</sub> та A<sub>0</sub> за моделлю конічного перетину. Час спорожнення від початкової до кінцевої відмітки дорівнює повному часу спорожнення від H<sub>1</sub> до отвору мінус час, що залишається від H<sub>2</sub> до отвору.';
$ec_lang['odt_h1']='Початковий напір, H<sub>1</sub> <span title="Початкова висота поверхні мінус відмітка центроїда отвору" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='Макс. витрата, Q<sub>max</sub>';
$ec_lang['odt_vol']='Зливний об\'єм';
$ec_lang['odt_sketch_start']='Початок';
$ec_lang['odt_sketch_end']='Кінець';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Ширина від берега до берега';
$ec_lang['essc_mcr']='Мінімальний радіус кривизни';
$ec_lang['essc_q']='Витрата, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Вимірювання витрати зрошення';
$ec_lang['irr_main_title']='Безкоштовні онлайн-калькулятори вимірювання витрати зрошення';
$ec_lang['irr_main_desc']='Вимірювання витрати зрошення — водозливи та отвори';
$ec_lang['contact_title']='Зв\'язок з HawsEDC';
$ec_lang['contactSendMessage']='Надіслати повідомлення Тому Хоусу';
$ec_lang['contactYourName']='Ваше ім\'я:';
$ec_lang['contactYourEmail']='Ваша адреса електронної пошти:';
$ec_lang['contactSubject']='Тема:';
$ec_lang['contact_message']='Повідомлення:';
$ec_lang['contactSpamPrefix']='П\'ять плюс один дорівнює';
$ec_lang['contactSpamPostfix']='(Будь ласка, напишіть словами. 1=один 2=два 3=три 4=чотири 5=п\'ять 6=шість 7=сім +=плюс 5+1=6)';
$ec_lang['contactSubmitButton']='Надіслати повідомлення';
$ec_lang['contact_success']='Дякуємо за ваш час та увагу.';

// About
$ec_lang['about_main_menu']='Про';
$ec_lang['install_main_menu']='Встановити';
$ec_lang['install_main_title']='Встановити EngCalcs';
$ec_lang['install_main_desc']='Додайте на пристрій для використання офлайн';
$ec_lang['contact_main_menu']='Контакт';
$ec_lang['about_main_title']='Про інженерні калькулятори HawsEDC';
$ec_lang['about_main_desc']='Місія, відкритий код і внесок';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Норма поливу — крапельне/дощування';
$ec_lang['ds_main_title']='Безкоштовний онлайн-калькулятор норми поливу крапельним/дощувальним зрошенням';
$ec_lang['ds_main_desc']='Крапельне та дощувальне зрошення — норма поливу';
$ec_lang['ds_q_avg']='Витрата емітера, q';
$ec_lang['ds_se']='Розстав емітерів, S<sub>e</sub>';
$ec_lang['ds_sl']='Розстав ліній, S<sub>l</sub>';
$ec_lang['ds_n_e']='Емітери на бічний трубопровід, n<sub>e</sub>';
$ec_lang['ds_n_l']='Бічні трубопроводи на зону, n<sub>l</sub>';
$ec_lang['ds_d']='Цільова глибина поливу, d';
$ec_lang['ds_a_e']='Площа на один емітер, A<sub>e</sub>';
$ec_lang['ds_pr']='Норма поливу, PR';
$ec_lang['ds_q_lat']='Витрата на бічний трубопровід, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Витрата зони, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Час роботи (години)';
$ec_lang['ds_notes_1_term']='Норма поливу';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, де A<sub>e</sub> = S<sub>e</sub> × S<sub>l</sub> — площа, яку обслуговує кожен емітер. Нижча норма поливу дає більше часу для вбирання — важливо на важких ґрунтах або похилих полях.';
$ec_lang['ds_notes_2_term']='Час поливу';
$ec_lang['ds_notes_2_def']='Час поливу = цільова глибина ÷ норма поливу. На похилих або ущільнених ґрунтах розділіть час поливу на два або три коротких цикли з перервами між ними, щоб уникнути поверхневого стоку.';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Фільтрація з каналу';
$ec_lang['cs_main_title']='Безкоштовний онлайн-калькулятор фільтраційних втрат і коефіцієнта корисної дії каналу';
$ec_lang['cs_main_desc']='Фільтраційні втрати каналу & коефіцієнт корисної дії транспортування — метод витрата на вході − витрата на виході';
$ec_lang['cs_Q_in']='Витрата на входу, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Витрата на виході, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='Інтенсивність фільтраційних втрат, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Перевірка вимірювань';
$ec_lang['cs_pct_loss']='Частка втрат';
$ec_lang['cs_Ec']='Коефіцієнт корисної дії транспортування, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Оцінка ефективності';
$ec_lang['cs_Vol_day']='Добовий об\'єм втрат';
$ec_lang['cs_Vol_year']='Річний об\'єм втрат';
$ec_lang['cs_L']='Довжина ділянки, L';
$ec_lang['cs_wp']='Змочений периметр, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='Втрата на одиницю довжини, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Вартість води';
$ec_lang['cs_lining_cost']='Вартість облицювання';
$ec_lang['cs_Ec_target']='Цільовий ККД облицювання, E<sub>c,target</sub> <span title="Коефіцієнт корисної дії мета після облицювання; дріб 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Площа облицювання, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Річна вартість втрат';
$ec_lang['cs_annual_value_recovered']='Річна вартість розбіжностей';
$ec_lang['cs_lining_total_cost']='Вартість облицювання всього';
$ec_lang['cs_payback_years']='Період окупності <span title="Простий період окупності = загальна вартість облицювання ÷ річна вартість розбіжностей" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — фільтрація виявлена ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — вимірних втрат немає';
$ec_lang['cs_loss_negative']='Попередження: Qout > Qin — перевірте вимірювання ⚠';
$ec_lang['cs_Ec_good']='Добре — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Задовільно — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Незадовільно — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Метод';
$ec_lang['cs_notes_1_def']='Метод витрата на вході — витрата на виході визначає фільтрацію вимірюванням витрати на початку та в кінці ділянки каналу: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Коефіцієнт корисної дії транспортування E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Річний об\'єм розраховується за умови безперервної роботи на повній витраті; фактичні втрати нижчі для сезонних або частково завантажених каналів.';
$ec_lang['cs_notes_2_term']='Оцінки ефективності';
$ec_lang['cs_notes_2_def']='Типові незакріплені земляні канали: E<sub>c</sub> = 60–80%. Добре утримувані земляні канали: 75–85%. Канали з бетонним облицюванням: 90–98%. Фільтраційні втрати понад 30% від витрати на вході часто обґрунтовують вкладення в облицювання. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Окупність облицювання';
$ec_lang['cs_notes_3_def']='Введіть вартість води та вартість облицювання у будь-якій послідовній грошовій одиниці. Площа облицювання = довжина ділянки × змочений периметр — змочений периметр перерізу каналу на відмітці вимірюваної глибини (ширина дна плюс обидва змочені укоси). Річна вартість розбіжностей передбачає, що облицьований канал безперервно досягає цільового E<sub>c</sub>. Фактична окупність буде довшою для сезонних каналів або якщо облицювання не досягає цільової ефективності.';
$ec_lang['cs_notes_4_term']='Джерело';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3-тє вид. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
$ec_lang['irr_intro_html']='<p>Водозливи та отвори — стандартні польові інструменти для вимірювання витрати води в зрошувальних системах. Оберіть калькулятор, що відповідає вашій споруді:</p>';
$ec_lang['irr_card_weir_uniform_head']='Водозлив — Широкий Поріг (Рівномірна Ширина)';
$ec_lang['irr_card_weir_uniform_desc']='Виміряйте витрату над гребенем водовідводної греблі, контрольної споруди або дошки водозливу. Введіть довжину водозливу та глибину води над порогом.';
$ec_lang['irr_card_weir_irregular_head']='Водозлив — Нерегулярний Профіль';
$ec_lang['irr_card_weir_irregular_desc']='Використовуйте, коли гребінь водозливу не знаходиться на єдиній рівномірній відмітці — природні водоскиди, перепадні споруди зі змінною шириною або багатосекційні регулювальні споруди.';
$ec_lang['irr_card_orifice_head']='Отвір — Головний Затвор або Трубний Випуск';
$ec_lang['irr_card_orifice_desc']='Виміряйте витрату через шандорний затвор, трубний випуск або отвір водопропуску. Автоматично обробляє як вільне витікання, так і підтоплені умови (підпір з нижнього б\'єфу).';
$ec_lang['irr_card_canal_head']='Проектування & Аналіз Каналу';
$ec_lang['irr_card_canal_desc']='Проектуйте або перевіряйте зрошувальний канал за формулою Маннінга. Використовуйте трапецієподібний калькулятор для нових каналів; калькулятор для нерегулярних перерізів — для існуючих природних або штучних.';
$ec_lang['irr_card_drip_head']='Проектування Краплинного & Дощувального Зрошення';
$ec_lang['irr_card_drip_desc']='Розрахуйте норму поливу, рівномірність розподілу, витрату бокового водоводу, витрату зони та час роботи для краплинної або дощувальної зрошувальної системи. Введіть витрату емітера, крок розстановки та цільову глибину зволоження.';
$ec_lang['irr_card_seepage_head']='Фільтрація з каналу & коефіцієнт корисної дії транспортування';
$ec_lang['irr_card_seepage_desc']='Оцінте фільтраційні втрати ділянки каналу за вимірюваннями витрати на вході та виході. Розрахуйте коефіцієнт корисної дії транспортування та річні втрати води для обґрунтування інвестицій в облицювання.';
$ec_lang['irr_quickref_html']='<h3>Швидкий Довідник</h3><dl><dt>Водовідводна гребля або контрольна споруда</dt><dd>Виміряйте глибину води над гребенем водозливу. Використовуйте <a href="Weir-Flow-Simple.php">Простий Водозлив</a> для рівномірного гребеня або <a href="Weir-Flow-Irregular.php">Нерегулярний Водозлив</a> для профільованого або ступінчастого гребеня.</dd><dt>Головний затвор або трубний випуск</dt><dd>Виміряйте відмітку рівня води у верхньому та нижньому б\'єфі (або відмітку лотка при вільному витіканні). Використовуйте <a href="Orifice.php">Витрату через Отвір</a>. Для круглої труби D = діаметр труби; для прямокутного затвора введіть ширину W і висоту D.</dd><dt>Час спорожнення водосховища або ставка</dt><dd>Використовуйте <a href="Orifice-Drain-Time.php">Час Спорожнення через Отвір</a>, щоб оцінити, скільки часу знадобиться на зниження рівня ставка або водосховища через донний отвір — корисно для планування зрошувального накопичення.</dd><dt>Польові стандарти</dt><dd>Рівняння витрати водозливу та отвору, використані тут, відповідають процедурам USBR <em>Water Measurement Manual</em> (3-те вид.), які зазвичай вимагаються водогосподарськими службами та зрошувальними округами.</dd></dl>';
$ec_lang['about_body_html']='<h3>Місія</h3><p>Інженерні Калькулятори HawsEDC існують для обслуговування інженерів і польових працівників по всьому світу — особливо тих, хто працює в регіонах з дефіцитом води, обмеженими ресурсами або недостатнім забезпеченням. Ці інструменти є частиною ширшої гуманітарної місії: сказати кожній людині найбільш практичним і дієвим способом, що вона кохана і дорога назавжди, що їй нема чого боятися і що вона не зруйнує все.</p><p>Калькулятори — це засіб. Мета — світ без страждань.</p><h3>Ліцензія з Відкритим Кодом</h3><p>Весь код опублікований під <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Стандартною Громадською Ліцензією GNU v3.0 або пізнішою</a> — вільний у значенні свободи. Ви можете використовувати, вивчати, змінювати і поширювати код на тих самих умовах.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Вихідний Код</h3><p>Повний вихідний код публічно доступний на Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Там можна переглядати код, повідомляти про проблеми або зробити форк репозиторію.</p><h3>Внесок</h3><p>Pull-запити вітаються. Способи участі:</p><ul><li><strong>Переклади</strong> — покращіть або додайте мову. Відкрийте pull-запит зі змінами у відповідному файлі <code>lib/lang.ec.??.php</code>.</li><li><strong>Звіти про помилки</strong> — скористайтеся формою зворотного зв\'язку на будь-якій сторінці калькулятора або повідомте про проблему на Bitbucket.</li><li><strong>Нові калькулятори</strong> — ідеї для гідравлічно-інженерних інструментів для польових працівників і фахівців із зрошення особливо вітаються. Дивіться посібник розробника <code>CLAUDE.md</code> у репозиторії.</li><li><strong>Хостинг</strong> — якщо ви можете розмістити дзеркало цих калькуляторів для регіону з обмеженим підключенням, зв\'яжіться з нами.</li></ul><h3>Використання без інтернету</h3><p>Ці калькулятори працюють як прогресивний веб-додаток (PWA). Відвідайте будь-яку сторінку калькулятора, коли є підключення до інтернету, і ваш браузер автоматично збереже всі калькулятори в кеш. Після цього всі калькулятори працюють без інтернету — підключення не потрібне.</p><p>На Android або iOS скористайтеся функцією «Додати на головний екран» у браузері, щоб встановити EngCalcs як додаток на своєму пристрої. На комп\'ютері шукайте значок встановлення в адресному рядку браузера.</p><p>Ви також можете зберегти будь-який окремий калькулятор за допомогою меню «Зберегти як…» у браузері для разового використання без інтернету.</p><h3>Контакт</h3><p>Tom Haws — гідравлічний інженер і автор цих калькуляторів.<br />Скористайтеся формою зворотного зв\'язку на будь-якій сторінці калькулятора або перейдіть до вихідного коду на <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Проектування Кам\'яного Лотка (Robinson)';
$ec_lang['rc_main_title']='Безкоштовний Онлайн-Калькулятор Проектування Кам\'яного Лотка — Robinson (1998)';
$ec_lang['rc_main_desc']='Підбір Розміру Кам\'яної Накидки для Лотка — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Ухил дна лотка, S<sub>0</sub>';
$ec_lang['rc_qt']='Питомий розрахунковий витрата, q<sub>t</sub> <span title="Витрата на одиницю ширини у вхідному перерізі лотка. Для каналу з шириною дна B і повним витратом Q використовуйте q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Пористість кам\'яної накидки, n<sub>p</sub>';
$ec_lang['rc_sg']='Питома вага каменю, sg <span title="Типовий дроблений граніт або базальт ≈ 2,65. Діапазон за Robinson: 2,54 до 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Градаційне СВ SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Стандартне відхилення гранулометричного складу. Однорідний камінь ≈ 1,25. Діапазон за Robinson: 1,15 до 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Нормальна глибина у вхідному каналі, y<sub>n</sub> <span title="Підпір (Hp > yn) — це добре: знижує ерозію вище за течією. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Необхідний медіанний розмір каменю, D<sub>50</sub> <span title="Рівн. 1 (S0 < 0,10) або Рівн. 2 (0,10–0,40). Дійсний: D50 15–278 мм, S0 0,02–0,40. За межами діапазону: екстраполяція." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Застосоване рівняння';
$ec_lang['rc_sg_check']='Перевірка питомої ваги';
$ec_lang['rc_SD_check']='Перевірка градаційного СВ';
$ec_lang['rc_sg_ok']   ='sg у допустимому діапазоні (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Попередження: sg < 2,54 — нижче діапазону Robinson';
$ec_lang['rc_sg_high'] ='Попередження: sg > 2,82 — вище діапазону Robinson';
$ec_lang['rc_SD_ok']   ='SD у допустимому діапазоні (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Попередження: SD < 1,15 — нижче діапазону Robinson';
$ec_lang['rc_SD_high'] ='Попередження: SD > 1,47 — вище діапазону Robinson';
$ec_lang['rc_layer']='Товщина шару накидки (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Радіус кривої гребеня (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Довжина дуги кривої гребеня';
$ec_lang['rc_apron_length']='Довжина вихідного фартуха (15 × D<sub>50</sub>) <span title="Необхідна для конструктивної підтримки каменю лотка. «Мінімальний підпір на виході, що виникає внаслідок опору вихідного та нижнього каналів, достатній для забезпечення стійкості накидки на вихідній ділянці.» (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Коефіцієнт шорсткості Маннінга в лотку, n';
$ec_lang['rc_Vm']='Швидкість через кам\'яну мантію, V<sub>m</sub> <span title="Частка q_t, що протікає через пори каменю. Залишок qs тече по поверхні. За замовчуванням np = 0,45 для кутастого дробленого каменю." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Питомий витрата через мантію, q<sub>m</sub>';
$ec_lang['rc_qs']='Поверхневий питомий витрата, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Глибина потоку над поверхнею накидки, d';
$ec_lang['rc_Hp']='Напір на вхідному порозі, H<sub>p</sub> <span title="Підпір (Hp > yn) — це добре: знижує ерозію вище за течією. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Перевірка підпору на вході';
$ec_lang['rc_pond_ok']  ='Hp > yn — підпір вище за течією ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — підпору немає — перевірте вхід на ерозію';
$ec_lang['rc_eq1']='Рівн. 1 (S0 < 0,10) — пологий ухил';
$ec_lang['rc_eq2']='Рівн. 2 (0,10 ≤ S0 ≤ 0,40) — крутий ухил';
$ec_lang['rc_eq_warn_low']='Попередження: S0 < 0,02 — нижче діапазону валідації Robinson';
$ec_lang['rc_eq_warn_high']='Попередження: S0 > 0,40 — вище діапазону валідації Robinson';
$ec_lang['rc_notes_1_term']='Рівняння підбору розміру каменю';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) розробили два емпіричних рівняння для медіанного розміру накидки D<sub>50</sub> на основі ухилу лотка та питомого витрату. Рівняння 1 застосовується для пологих ухилів (S<sub>0</sub> < 0,10); Рівняння 2 — для крутих ухилів (0,10 ≤ S<sub>0</sub> ≤ 0,40). Обидва рівняння вимагають q<sub>t</sub> у м²/с та повертають D<sub>50</sub> у мм. Перевірений діапазон: 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Питомий витрата';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> — сумарний питомий витрата у гребені лотка (повний витрата на одиницю ширини). Для каналу з шириною дна B і повним витратом Q наближено q<sub>t</sub> ≈ Q / B, або обчисліть його з умови критичної глибини у вхідному перерізі лотка.';
$ec_lang['rc_notes_3_term']='Фільтраційний потік через кам\'яну мантію';
$ec_lang['rc_notes_3_def']='Частина повного витрату проходить через пори кам\'яної накидки (витрата через мантію q<sub>m</sub>); залишок тече по поверхні каменю (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Глибина потоку d обчислюється за рівнянням Маннінга для поверхневого витрату q<sub>s</sub> з використанням шорсткості лотка n. Пористість за замовчуванням n<sub>p</sub> = 0,45 типова для кутастого дробленого каменю.';
$ec_lang['rc_notes_5_term']='Допустимий діапазон розміру каменю';
$ec_lang['rc_notes_5_def']='Рівняння розроблені для діапазону D<sub>50</sub> від 15 мм до 278 мм. Результати за межами цього діапазону є екстраполяцією і мають застосовуватись з додатковою інженерною обережністю.';
$ec_lang['rc_notes_6_term']='Відмітка вихідного фартуха';
$ec_lang['rc_notes_6_def']='Відмітка верху накидки на вихідній ділянці повинна бути на рівні або нижче відмітки дна нижнього каналу. Якщо вона вища — вихідний камінь буде нестійким.';
$ec_lang['rc_notes_7_term']='Перевірка підпору на вході';
$ec_lang['rc_notes_7_def']='Якщо нормальна глибина у вхідному каналі менша за напір на порозі (H<sub>p</sub>), необхідний для пропуску q<sub>t</sub>, вище вхідного фартуха виникає стиснення потоку або підпір. Це, як правило, допустимо — підпір знижує швидкість і запобігає ерозії вище за течією. Для перевірки: скористайтесь калькулятором водозливу, знайдіть H<sub>p</sub> для заданих q<sub>t</sub> і ширини гребеня, потім порівняйте з нормальною глибиною вхідного каналу. Якщо H<sub>p</sub> перевищує нормальну глибину, підпір виникне.';
$ec_lang['rc_notes_4_term']='Джерело';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS також публікує <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">таблицю Excel</a> на основі того ж методу.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Фільтр';
$ec_lang['rc_sketch_top_crest_curve'] = 'Вхідна крива';
$ec_lang['rc_sketch_outlet_apron']    = 'Вихідна плита';
$ec_lang['rc_sketch_radius']          = 'радіус';
// Manning Trapezoid — velocity check messages
$ec_lang['mtc_vel_check']='Перевірка швидкості';
$ec_lang['mtc_vel_ok']='Швидкість прийнятна для умов рівномірної течії.';
$ec_lang['mtc_vel_high']='Швидкість висока — перевірте втрати на переходах та доступну енергію.';
$ec_lang['mtc_vel_low']='Швидкість низька — ризик замулення.';
$ec_lang['mtc_vel_ok_short']='ОК';
$ec_lang['mtc_vel_high_short']='Висока';
$ec_lang['mtc_vel_low_short']='Низька';
$ec_lang['mtc_note_2_term']='Перевірка швидкості';
$ec_lang['mtc_note_2_def']='Висока швидкість означає значну питому енергію від наявного перепаду. Ця енергія може швидко розсіюватися на розширеннях, поворотах або перешкодах. Переконайтеся, що це значення є прийнятним для даної ділянки.';
// Micro-Hydro Power — notes 6 and 7
$ec_lang['mhp_notes_6_term']='ККД установки';
$ec_lang['mhp_notes_6_def']='Типовий ККД установки η становить від 0.70 до 0.85 для турбін Пелтона та поперечно-потокових турбін, що застосовуються в мікро-ГЕС. Значення 0.75 є консервативною первинною оцінкою.';
$ec_lang['mhp_notes_7_term']='Річна енергія';
$ec_lang['mhp_notes_7_def']='Річна енергія розраховується за умови безперервної роботи при повній витраті (8760 годин/рік). Фактичне виробництво буде нижчим через сезонні коливання витрати, простої на технічне обслуговування та коефіцієнт завантаження.';
