<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fraction";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="ft^3/s";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']='% pente';
$ec_lang['u_grade']="pente";
$ec_lang['u_in2']="po^2";
$ec_lang['u_inh2o']="po H2O";
$ec_lang['u_in']="po";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="Mgal/j";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/j";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lbs/ft^2";
$ec_lang['u_psi']="lbs/po^2";
$ec_lang['u_s']="s";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Calculateurs HawsEDC';
$ec_lang['menu_main_list']='Liste des calculateurs';
$ec_lang['menu_main_hydraulics']='Hydraulique';
$ec_lang['menu_main_language']='Langue';
$ec_lang['menu_more']='Plus';
$ec_lang['template_welcome']='&gt;&gt; Laissez vos peurs à la porte; l\'amour est parlé ici. Vous ne ruinez pas tout. Profitez également des <a target="_blank" href="https://hawsedc.com/download.php">outils AutoCAD gratuits HawsEDC</a>. &lt;&lt;';
$ec_lang['template_translation_help']="Avez-vous une grande vision pour une calculatrice à ajouter ici ?  Pouvez-vous m'aider à traduire ce calculateur dans votre langue ou l'héberger sur votre site web?";
$ec_lang['template_feedback']="Donnez-nous vos précieux commentaires ou éloges. Ce calculateur gratuit a-t-il dépassé toutes vos attentes?";
$ec_lang['template_printable_title']='Titre imprimable';
$ec_lang['template_printable_subtitle']='Sous-titre imprimable';
$ec_lang['index_title']='Calculateurs d\'ingénierie gratuits en ligne';
$ec_lang['calc_set_units']='Définir les unités:';
$ec_lang['points_data_help']='(ou Copier/Coller via la zone de données)';
$ec_lang['points_data_title']='Données des points<br />(séparés par virgule ou tabulation)';
$ec_lang['points_data_copy']='Copier';
$ec_lang['points_data_paste']='Coller';
$ec_lang['calc_inputs']='Données';
$ec_lang['calc_results']='Résultats:';
$ec_lang['view_hide_line']='[Masquer cette ligne]';
$ec_lang['view_printable']='Version imprimable (recharger pour restaurer)';
$ec_lang['ec_name_label']='Enregistrer ce calcul :';
$ec_lang['ec_name_placeholder']='Nom';
$ec_lang['ec_name_hint']='Enregistre les données saisies dans l\'URL pour les signets, la récupération de l\'historique et le partage';
$ec_lang['ec_name_invalid']='Utilisez uniquement lettres, chiffres, espaces, – _ .';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Perte de charge Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculateur gratuit en ligne de perte de charge Darcy-Weisbach';
$ec_lang['dw_main_desc']='Perte de charge Darcy-Weisbach pour un diamètre, une rugosité et un débit donnés';
$ec_lang['dw_roughness']='Rugosité absolue Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Viscosité cinématique, &nu; <span title="1×10⁻⁶ m²/s for clean water at 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['dw_reynolds_number']='Nombre de Reynolds, Re';
$ec_lang['dw_flow_regime']='Régime d’écoulement';
$ec_lang['dw_regime_laminar']='laminaire';
$ec_lang['dw_regime_transitional']='transitoire';
$ec_lang['dw_regime_turbulent']='écoulement turbulent';
$ec_lang['dw_friction_factor_method']='Méthode du facteur de frottement';
$ec_lang['dw_friction_factor']='Facteur de frottement, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Perte de charge Hazen-Williams';
$ec_lang['hw_main_title']='Calculateur gratuit en ligne de perte de charge Hazen-Williams';
$ec_lang['hw_main_desc']='Perte de charge Hazen-Williams pour un diamètre, une rugosité et un débit donnés';
$ec_lang['hw_hgl_1']='LHP aval';
$ec_lang['hw_hgl_2']='LHP amont';
$ec_lang['hw_roughness']='Coefficient Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canal irrégulier Manning';
$ec_lang['mi_main_title']='Calculateur gratuit en ligne de canal irrégulier Manning';
$ec_lang['mi_main_desc']='Calculateur d\'écoulement uniforme en canal irrégulier Manning';
$ec_lang['mi_waterSurfaceElevation']='Cote de la surface libre';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Points de la section en travers';
$ec_lang['mi_groupPoint']='Point';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Région';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Cote';
$ec_lang['mi_d50in']='Granul.<br />médiane<br />revêtement<br />rocheux';
$ec_lang['mi_n']='n<br />du seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />limite de<br />région<br />(Berge)';
$ec_lang['mi_tau']='Cisaill.<br />fond<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />composé';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Notes';
$ec_lang['mi_notes_1_term']='n composé';
$ec_lang['mi_notes_1_def']='Ce calculateur suit le manuel de référence HEC-RAS pour calculer le n composé par région selon Chow 1959, page 136, équation 6-17 (et non 6-18).';
$ec_lang['mi_notes_2_term']='Revêtement rocheux';
$ec_lang['mi_notes_2_def']='Utilisez le calculateur de canal trapézoïdal Manning pour dimensionner le revêtement rocheux. Ce calculateur est destiné aux sections naturelles.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Écoulement Manning en conduite';
$ec_lang['mpf_main_title']='Calculateur gratuit en ligne de la formule Manning pour l\'écoulement en conduite';
$ec_lang['mpf_main_desc']='Écoulement uniforme Manning en conduite à pente et taux de remplissage donnés';
$ec_lang['mpf_spreadheet_notice']='Découvrez la version tableur de ce calculateur';
$ec_lang['mpf_pipe_diameter']='Diamètre de la conduite, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Rugosité Manning, n';
$ec_lang['mpf_friction_slope']='Pente de pression (possiblement <a target="_blank" href="../pressureslope.php">?</a> égale à la pente de la conduite), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Taux de remplissage, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(voir notes)';
$ec_lang['mpf_flow']='Débit, Q';
$ec_lang['mpf_velocity']='Vitesse, v';
$ec_lang['mpf_velocity_head']='Charge cinétique, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Section mouillée, a';
$ec_lang['mpf_pipe_area']='Section de la conduite, a0';
$ec_lang['mpf_area_ratio']='Rapport des sections, a/a0';
$ec_lang['mpf_wetted_perimeter']='Périmètre mouillé, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Rayon hydraulique, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Largeur au miroir, T';
$ec_lang['mpf_froude_number']='Nombre de Froude, F';
$ec_lang['mpf_shear_stress']='Contrainte de cisaillement moyenne (force tractrice), tau';
$ec_lang['mpf_full_flow']='Débit à section pleine, Q0';
$ec_lang['mpf_full_flow_ratio']='Rapport au débit plein, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Il s\'agit du débit (et de la profondeur) à l\'intérieur d\'une conduite de <em>longueur infinie</em>.</dt><dd>Faire entrer le débit dans la conduite peut nécessiter une charge amont nettement plus élevée. Ajoutez au moins 1,5 fois la charge cinétique pour obtenir la charge amont, ou <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">consultez mon tutoriel de 2 minutes</a> pour les calculs standard de charge amont de buse avec HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Calculer y/d<sub>0</sub> pour un Q donné';
$ec_lang['mpf_solve_desc']='En utilisant D<sub>0</sub>, n et S<sub>0</sub> du formulaire, trouve le plus petit y/d<sub>0</sub> pour un Q donné.';
$ec_lang['mpf_solve_button']='Calculer';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Perte de charge Manning en conduite';
$ec_lang['mphl_main_title']='Calculateur gratuit en ligne de perte de charge Manning en conduite';
$ec_lang['mphl_main_desc']='Formule Manning — perte de charge à débit en charge donné';
$ec_lang['mphl_pipe_length']='Longueur de conduite, L';
$ec_lang['mphl_area']='Section, A';
$ec_lang['mphl_total_junction_k']='Coefficient total de perte aux raccords, k';
$ec_lang['mphl_friction_slope']='Pente de frottement';
$ec_lang['mphl_friction_loss']='Perte par frottement, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Perte aux raccords, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Perte totale, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='LHE aval';
$ec_lang['mphl_egl_2']='LHE amont';
$ec_lang['mphl_hgl_2']='LHP amont en conduite ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Pour une entrée libre (buse), il est nécessaire de vérifier les conditions de contrôle à l\'entrée.</dt><dd>1. La LHP amont ne peut pas être inférieure à la cote de profondeur normal amont (ni inférieure au fil d\'eau!).</dd><dd>2. La charge amont d\'une buse est mieux représentée par la LHE amont que par la LHP amont.</dd><dd>3. Voir <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">mon tutoriel de 2 minutes</a> pour les calculs simples de charge amont de buse avec HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapézoïdal Manning';
$ec_lang['mtc_main_title']='Calculateur gratuit en ligne de la formule Manning pour canal trapézoïdal';
$ec_lang['mtc_main_desc']='Écoulement uniforme Manning en canal trapézoïdal à pente et profondeur données';
$ec_lang['mtc_bottom_width']='Largeur du fond, b';
$ec_lang['mtc_side_slope_1']='Talus 1 (horizontal/vertical)';
$ec_lang['mtc_side_slope_2']='Talus 2 (horizontal/vertical)';
$ec_lang['mtc_channel_slope']='Pente du canal, S';
$ec_lang['mtc_flow_depth']='Profondeur d\'écoulement, y';
$ec_lang['mtc_bend_angle']='Angle de courbure <a target="_blank" href="riprap-bend-angle.png" title="Cliquer pour image">?</a> (pour le dimensionnement des enrochements)';
$ec_lang['mtc_sgrock']='Masse volumique relative de la roche (2,65)';
$ec_lang['mtc_d50_in']='Granulométrie de conception, D50';
$ec_lang['mtc_n_strickler']='n pour la granulométrie de conception selon Strickler';
$ec_lang['mtc_n_blodgett']='n pour la granulométrie de conception selon Blodgett';
$ec_lang['mtc_n_bathurst']='n pour la granulométrie de conception selon Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Granulométrie d\'enrochement anguleux requise au fond, D50 (Isbash & MC) <span title="Selon Isbash (1936) et Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Granulométrie d\'enrochement anguleux requise sur talus 1, D50 (Isbash & MC) <span title="Selon Isbash (1936) et Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Granulométrie d\'enrochement anguleux requise sur talus 2, D50 (Isbash & MC) <span title="Selon Isbash (1936) et Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Granulométrie d\'enrochement anguleux requise, D50 (Maynord, Ruff et Abt 1989)';
$ec_lang['mtc_d50_searcy']='Granulométrie d\'enrochement anguleux requise, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Dimensionnement itératif automatique des enrochements</dt><dd>Choisissez un bouton de rugosité (BB recommandé) et un bouton de granulométrie de conception (Isbash recommandé). Affinez la profondeur et le coefficient de sécurité pour obtenir le débit souhaité avec une granulométrie ronde. À chaque modification: 1. La rugosité est calculée à partir de la granulométrie. 2. La rugosité calculée est copiée en entrée. 3. L\'écoulement et la granulométrie requise sont calculés. 4. La granulométrie est ajustée. 5. Répéter jusqu\'à convergence.</dd><dt>Calculateur de base (sans itération)</dt><dd>Entrez votre valeur de rugosité. Ignorez la zone de granulométrie de conception.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Chute en enrochement Robinson';
$ec_lang['rrc_main_desc']='Tableur de dimensionnement de chute en enrochement Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Déversoir simple';
$ec_lang['ws_main_title']='Calculateur gratuit en ligne de déversoir à seuil large';
$ec_lang['ws_main_desc']='Calculateur de débit sur déversoir à seuil large';
$ec_lang['ws_weirLength']='Longueur du déversoir, l';
$ec_lang['ws_headWaterHeight']='Charge amont, h';
$ec_lang['ws_weirCoefficient']='Coefficient de déversoir, Cw';
$ec_lang['ws_notes_heading']='Notes';
$ec_lang['ws_notes_we_term']='Équation du déversoir';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Déversoir irrégulier';
$ec_lang['wi_main_title']='Calculateur gratuit en ligne de débit sur déversoir irrégulier à profondeur variable';
$ec_lang['wi_main_desc']='Calculateur de débit sur déversoir irrégulier';
$ec_lang['wi_headWaterelevation']='Cote de la surface amont';
$ec_lang['wi_weirPoints']='Points du déversoir';
$ec_lang['wi_station']='Distance';
$ec_lang['wi_elevation']='Cote';
$ec_lang['wi_pondingHeight']='Hauteur de mise en charge';
$ec_lang['wi_incrementalFlow']='Débit élémentaire';
$ec_lang['wi_cumulativeFlow']='Débit cumulé';
$ec_lang['wi_save_and_calculate']='Enregistrer et calculer';
$ec_lang['wi_notes_we_term']='Équation du déversoir';
$ec_lang['wi_notes_we_def']='q = si (longueur = 0) alors 0 sinon si (pente=0) alors cw*longueur*d<sub>0</sub><sup>1,5</sup> sinon cw/(2,5*pente) * (d<sub>0</sub><sup>2,5</sup> - d<sub>1</sub><sup>2,5</sup>) où d<sub>1</sub> et d<sub>0</sub> sont toujours positifs ou nuls';
// Orifice Flow
$ec_lang['or_main_menu']='Débit par Orifice';
$ec_lang['or_main_title']='Calculateur gratuit en ligne de débit par orifice';
$ec_lang['or_main_desc']='Débit par Orifice — Libre ou Noyé';
$ec_lang['or_shape']='Forme de l\'ouverture';
$ec_lang['or_shape_circular']='Circulaire';
$ec_lang['or_shape_rectangular']='Rectangulaire';
$ec_lang['or_diameter']='Diamètre ou hauteur, D <span title="Diameter for circular; height for rectangular" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_width']='Largeur, W <span title="Rectangular openings only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_invert']='Cote du radier <span title="Bottom of opening" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_hwe']='Cote de la surface d\'eau amont';
$ec_lang['or_twe']='Cote de la surface d\'eau aval';
$ec_lang['or_cd']='Coefficient de débit, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Cote du centroïde';
$ec_lang['or_head']='Charge effective, h';
$ec_lang['or_area']='Aire de l\'ouverture, A';
$ec_lang['or_flow']='Débit, Q';
$ec_lang['or_regime']='Vérification du régime d\'orifice';
$ec_lang['or_regime_valid']='Déversement libre — régime d\'orifice valide ✓';
$ec_lang['or_regime_submerged']='Orifice noyé (TWE au-dessus du radier) — valide ✓';
$ec_lang['or_regime_warn']='Avertissement : surface amont sous la clé — pas en régime d\'orifice';
$ec_lang['or_regime_twe_above_hwe']='Avertissement : niveau aval (TWE) au-dessus du niveau amont (HWE) — vérifier les données';
$ec_lang['or_notes_1_term']='Équation d\'orifice';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Déversement libre : h = HWE &minus; centroïde. Écoulement noyé (TWE au-dessus du radier) : h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Régime d\'orifice';
$ec_lang['or_notes_2_def']='Les équations de débit par orifice s\'appliquent lorsque la surface amont est au-dessus de la clé de l\'ouverture. Lorsqu\'elle est en dessous, utilisez une équation de déversoir.';
$ec_lang['or_notes_3_term']='Coefficient de débit';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varie entre 0,60 et 0,65 pour les orifices à arête vive. Les entrées arrondies ou en retrait ont des valeurs différentes. Voir <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ou le Manuel de Référence Hydraulique HEC-RAS.';
$ec_lang['or_notes_4_term']='Submersion';
$ec_lang['or_notes_4_def']='Lorsque TWE est au-dessus du radier de l\'ouverture, la calculatrice applique automatiquement l\'équation d\'orifice noyé avec h = HWE &minus; TWE. Lorsque TWE est au niveau ou en dessous du radier, un déversement libre est supposé et h = HWE &minus; centroïde.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Temps de vidange par orifice';
$ec_lang['odt_main_title']='Calculateur gratuit en ligne du temps de vidange par orifice — Bassin, étang ou réservoir';
$ec_lang['odt_main_desc']='Temps de vidange d\'un bassin ou étang par orifice &mdash; Méthode du volume conique';
$ec_lang['odt_h1_elev']='Cote de départ, WSE <span title="Starting water surface elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_a1']='Superficie initiale, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Cote finale, WSE';
$ec_lang['odt_h_orifice']='Cote du centroïde de l\'orifice';
$ec_lang['odt_a0']='Superficie au radier, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Superficie finale, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_h2_check']='Vérification de la cote finale';
$ec_lang['odt_h2_ok']='Cote finale au-dessus du sommet de l\'orifice ✓';
$ec_lang['odt_h2_warn']='Avertissement : cote finale au niveau ou en dessous du sommet de l\'orifice (centroïde + D/2)';
$ec_lang['odt_d']='Orifice D <span title="Diameter (circular) or height (rectangular)" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_w']='Largeur, W <span title="Rectangular only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_t_sec']='Temps de vidange (s)';
$ec_lang['odt_t_min']='Temps de vidange (min)';
$ec_lang['odt_t_hr']='Temps de vidange (hr)';
$ec_lang['odt_t_day']='Temps de vidange (days)';
$ec_lang['odt_notes_1_term']='Formule';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) donne le temps de vidange depuis la charge H jusqu\'à l\'orifice. Temps de vidange = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), où H<sub>1</sub> = cote de départ &minus; cote de l\'orifice, H<sub>2</sub> = cote finale &minus; cote de l\'orifice.';
$ec_lang['odt_notes_2_term']='Méthode';
$ec_lang['odt_notes_2_def']='La méthode du volume conique modélise le bassin ou l\'étang comme une section conique entre la superficie initiale A<sub>1</sub> à la surface libre de départ et la superficie A<sub>0</sub> à la cote du centroïde de l\'orifice. A<sub>2</sub>, la superficie du bassin à la cote finale, est interpolée à partir de A<sub>1</sub> et A<sub>0</sub> selon le modèle conique. Le temps de vidange de la cote de départ à la cote finale est égal au temps de vidange total de H<sub>1</sub> à l\'orifice moins le temps de vidange restant de H<sub>2</sub> à l\'orifice.';
$ec_lang['odt_h1']='Starting head, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_q_max']='Débit max, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume vidangé';
$ec_lang['odt_sketch_start']='Début';
$ec_lang['odt_sketch_end']='Fin';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Mesure du débit d\'irrigation';
$ec_lang['irr_main_title']='Calculateurs en ligne gratuits de mesure du débit d\'irrigation';
$ec_lang['irr_main_desc']='Mesure du débit d\'irrigation — déversoirs et orifices';
$ec_lang['contact_title']='Contact HawsEDC';
$ec_lang['contactSendMessage']='Envoyer un message à Tom Haws';
$ec_lang['contactYourName']='Votre nom:';
$ec_lang['contactYourEmail']='Votre adresse e-mail:';
$ec_lang['contactSubject']='Sujet:';
$ec_lang['contact_message']='Message :';
$ec_lang['contactSpamPrefix']='Cinq plus un égale';
$ec_lang['contactSpamPostfix']="(Veuillez l'écrire en lettres. 1=un 2=deux 3=trois 4=quatre 5=cinq 6=six 7=sept +=plus 5+1=6)";
$ec_lang['contactSubmitButton']='Envoyer le message';
$ec_lang['contact_success']='Merci d\'avoir pris le temps d\'écrire.';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Largeur de berge à berge';
$ec_lang['essc_mcr']='Rayon de courbure minimal';
$ec_lang['essc_q']='Débit, Q';
// Orifice Flow
$ec_lang['or_velocity']='Vitesse, v';


// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hydroélectricité';
$ec_lang['mhp_main_title']='Calculateur Gratuit de Puissance Micro-Hydroélectrique';
$ec_lang['mhp_main_desc']='Calculateur de Puissance Micro-Hydroélectrique au Fil de l\'Eau';
$ec_lang['mhp_flow']='Débit, Q';
$ec_lang['mhp_gross_head']='Hauteur brute, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diamètre de la conduite forcée, D';
$ec_lang['mhp_length']='Longueur de la conduite forcée, L';
$ec_lang['mhp_roughness']='Rugosité de la conduite, e';
$ec_lang['mhp_km']='Coefficient de perte, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_nu']='Viscosité cinématique, &nu; <span title="1×10⁻⁶ m²/s for clean water near 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_efficiency']='Rendement de l\'installation, &eta; (0&ndash;1)';
$ec_lang['mhp_velocity']='Vitesse d\'écoulement, v';
$ec_lang['mhp_vel_check']='Vérification de la vitesse';
$ec_lang['mhp_f']='Facteur de frottement, f';
$ec_lang['mhp_hf']='Perte de charge par frottement, h<sub>f</sub>';
$ec_lang['mhp_hm']='Perte mineure, h<sub>m</sub>';
$ec_lang['mhp_hl']='Perte totale dans la conduite forcée, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Vérification de la perte de charge';
$ec_lang['mhp_hnet']='Hauteur nette, H<sub>net</sub>';
$ec_lang['mhp_power']='Puissance produite, P';
$ec_lang['mhp_annual_kwh']='Énergie annuelle à 100 % de capacité';
$ec_lang['mhp_vel_ok']='1–3 m/s — dans la plage cible ✓';
$ec_lang['mhp_vel_low']='inférieur à 1 m/s — réduire le diamètre ⚠';
$ec_lang['mhp_vel_high']='supérieur à 3 m/s — augmenter le diamètre ⚠';
$ec_lang['mhp_hl_ok']='dans la cible de 10 % ✓';
$ec_lang['mhp_hl_warn']='dépasse la cible de 10 % — envisager une conduite plus grande ⚠';
$ec_lang['mhp_hl_bad']='dépasse 20 % — redimensionner la conduite';
$ec_lang['mhp_notes_1_term']='Perte de charge';
$ec_lang['mhp_notes_1_def']='La perte totale dans la conduite forcée h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, où h<sub>f</sub> = f(L/D)(v&sup2;/2g) est la perte par frottement de Darcy-Weisbach et h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g couvre les entrées, coudes et vannes. Hauteur nette H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Vitesse';
$ec_lang['mhp_notes_2_def']='Objectif : 1&ndash;3 m/s. En dessous de 1 m/s, la conduite est surdimensionnée pour le débit ; au-dessus de 3 m/s, les pertes par frottement et le risque de coup de bélier augmentent.';
$ec_lang['mhp_notes_3_term']='Objectif de perte de charge';
$ec_lang['mhp_notes_3_def']='Des pertes dans la conduite forcée inférieures à 10 % de la hauteur brute sont généralement économiques. Le compromis optimal entre le coût de la conduite et la puissance perdue se situe souvent autour de 4&ndash;6 % pour les sites à électricité de haute valeur.';
$ec_lang['mhp_notes_4_term']='Pertes singulières k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Valeurs typiques : entrée à arête vive 0,5, chaque coude à 45&deg; 0,2&ndash;0,3, vanne-guillotine (pleinement ouverte) 0,1, vanne papillon 0,2. Additionner tous les accessoires pour obtenir le k<sub>m</sub> total. La valeur par défaut 1,5 suppose une entrée et deux coudes.';
$ec_lang['mhp_notes_5_term']='Rugosité de la conduite e';
$ec_lang['mhp_notes_5_def']='Rugosité absolue typique : acier (neuf) 0,046&nbsp;mm, acier (usagé) 0,15&nbsp;mm, PEHD 0,003&nbsp;mm, PVC/uPVC 0,0015&nbsp;mm, béton 0,3&ndash;3&nbsp;mm. Le PEHD est courant pour les conduites forcées des petites installations micro-hydrauliques.';
$ec_lang['mhp_notes_6_term']='Rendement';
$ec_lang['mhp_notes_6_def']='Le rendement typique de l\'installation &eta; varie de 0,70 à 0,85 pour les turbines Pelton et à flux croisé courantes en micro-hydroélectricité. Utilisez 0,75 comme première estimation prudente.';
$ec_lang['mhp_notes_7_term']='Énergie annuelle';
$ec_lang['mhp_notes_7_def']='L\'énergie annuelle suppose un fonctionnement continu à débit plein (8760 heures/an). La production réelle sera plus faible en raison de la variation saisonnière du débit, des temps d\'arrêt pour maintenance et du facteur de charge.';

// About
$ec_lang['about_main_menu']='À propos';
$ec_lang['install_main_menu']='Installer';
$ec_lang['install_main_title']='Installer EngCalcs';
$ec_lang['install_main_desc']='Ajouter à votre appareil pour une utilisation hors ligne';
$ec_lang['contact_main_menu']='Contact';
$ec_lang['about_main_title']='À propos des calculateurs HawsEDC';
$ec_lang['about_main_desc']='Mission, open source et contribution';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Taux d\'application — goutte-à-goutte/aspersion';
$ec_lang['ds_main_title']='Calculateur gratuit en ligne du taux d\'application pour l\'irrigation goutte-à-goutte/aspersion';
$ec_lang['ds_main_desc']='Irrigation goutte-à-goutte &amp; aspersion &mdash; taux d\'application et uniformité';
$ec_lang['ds_q_avg']='Débit moyen de l\'émetteur, q';
$ec_lang['ds_q_min']='Débit minimal de l\'émetteur, q<sub>min</sub>';
$ec_lang['ds_se']='Espacement émetteur, S<sub>e</sub>';
$ec_lang['ds_sl']='Espacement latéral, S<sub>l</sub>';
$ec_lang['ds_n_e']='Émetteurs par rampe, n<sub>e</sub>';
$ec_lang['ds_n_l']='Rampes par zone, n<sub>l</sub>';
$ec_lang['ds_d']='Profondeur d\'application cible, d';
$ec_lang['ds_a_e']='Surface par émetteur, A<sub>e</sub>';
$ec_lang['ds_pr']='Taux d\'application, PR';
$ec_lang['ds_du']='Uniformité de distribution, DU';
$ec_lang['ds_du_check']='Contrôle qualité DU';
$ec_lang['ds_q_lat']='Débit par rampe, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Débit de la zone, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Durée (heures)';
$ec_lang['ds_du_excellent']='Excellent — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='Bon — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='Acceptable — DU ≥ 70%';
$ec_lang['ds_du_poor']='Médiocre — DU < 70% — revoir la conception ⚠';
$ec_lang['ds_notes_1_term']='Taux d\'application';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, où A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> est la surface desservie par chaque émetteur. Un taux d\'application plus faible laisse plus de temps à l\'infiltration &mdash; important sur les sols lourds ou les champs en pente.';
$ec_lang['ds_notes_2_term']='Uniformité de distribution (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. Un DU de 1,0 (100 %) signifie que tous les émetteurs débitent de façon identique. Les valeurs inférieures à 0,80 gaspillent l\'eau dans les zones bien irriguées tout en laissant des zones plus sèches. L\'uniformité diminue avec une variation de pression excessive le long de la rampe, l\'usure des émetteurs ou un colmatage partiel.';
$ec_lang['ds_notes_3_term']='Durée d\'arrosage';
$ec_lang['ds_notes_3_def']='Durée d\'arrosage = profondeur cible &divide; taux d\'application. Sur un sol en pente ou compacté, fractionnez la durée en deux ou trois cycles plus courts avec des temps de repos entre eux pour éviter le ruissellement de surface.';

// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Pertes par infiltration — canal';
$ec_lang['cs_main_title']='Calculateur gratuit en ligne des pertes par infiltration et de l\'efficience de transport en canal';
$ec_lang['cs_main_desc']='Pertes par infiltration &amp; efficience de transport en canal &mdash; Méthode entrée-sortie';
$ec_lang['cs_Q_in']='Débit entrant, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Débit sortant, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='Taux de perte par infiltration, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Vérification de la mesure';
$ec_lang['cs_pct_loss']='Fraction perdue';
$ec_lang['cs_Ec']='Efficience de transport, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Classe d\'efficience';
$ec_lang['cs_Vol_day']='Volume perdu quotidiennement';
$ec_lang['cs_Vol_year']='Volume perdu annuellement';
$ec_lang['cs_L']='Longueur du bief, L';
$ec_lang['cs_wp']='Périmètre mouillé, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='Perte unitaire, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valeur de l\'eau';
$ec_lang['cs_lining_cost']='Coût revêtement';
$ec_lang['cs_Ec_target']='Lining target, E<sub>c,target</sub> <span title="Conveyance efficiency goal after lining; fraction 0&ndash;1" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_lining_area']='Surface, L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valeur annuelle perdue';
$ec_lang['cs_annual_value_recovered']='Valeur annuelle récupérée';
$ec_lang['cs_lining_total_cost']='Coût total revêtement';
$ec_lang['cs_payback_years']='Payback period <span title="Simple payback = total lining cost &divide; annual value recovered" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — infiltration détectée ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — aucune perte mesurable';
$ec_lang['cs_loss_negative']='Avertissement : Qout > Qin — vérifier les mesures ⚠';
$ec_lang['cs_Ec_good']='Bonne — Ec ≥ 80 % ✓';
$ec_lang['cs_Ec_fair']='Moyenne — Ec 60–80 %';
$ec_lang['cs_Ec_poor']='Mauvaise — Ec < 60 % ⚠';
$ec_lang['cs_notes_1_term']='Méthode';
$ec_lang['cs_notes_1_def']='La méthode entrée-sortie estime l\'infiltration en mesurant le débit en tête et en queue d\'un bief de canal : Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. Efficience de transport E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Le volume annuel suppose un fonctionnement continu à plein débit ; la perte réelle est plus faible pour les canaux saisonniers ou à débit partiel.';
$ec_lang['cs_notes_2_term']='Classes d\'efficience';
$ec_lang['cs_notes_2_def']='Canaux en terre non revêtus typiques : E<sub>c</sub> = 60&ndash;80&nbsp;%. Canaux en terre bien entretenus : 75&ndash;85&nbsp;%. Canaux en béton : 90&ndash;98&nbsp;%. Des pertes supérieures à 30&nbsp;% du débit entrant justifient souvent un investissement de revêtement. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Délai de récupération du revêtement';
$ec_lang['cs_notes_3_def']='Saisissez la valeur de l\'eau et le coût du revêtement dans une devise cohérente quelconque. Surface de revêtement = longueur du bief &times; périmètre mouillé — le périmètre mouillé de la section transversale du canal à la profondeur d\'écoulement mesurée (largeur du fond plus les deux talus mouillés). La valeur annuelle récupérée suppose que le canal revêtu atteint l\'E<sub>c</sub> cible en continu. Le délai de récupération réel sera plus long pour les canaux saisonniers ou si le revêtement n\'atteint pas l\'efficience cible.';
$ec_lang['cs_notes_4_term']='Référence';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3e éd. (2001). FAO Irrigation and Drainage Paper 57 (1999).';

$ec_lang['irr_intro_html']='<p>Les déversoirs et les orifices sont les outils de terrain standard pour mesurer le débit d\'eau dans les systèmes d\'irrigation. Sélectionnez la calculatrice correspondant à votre structure :</p>';
$ec_lang['irr_card_weir_uniform_head']='Déversoir — Seuil Large (Largeur Uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Mesurez le débit sur la crête d\'un barrage de dérivation, d\'une structure de contrôle ou d\'un seuil. Saisissez la longueur du déversoir et la hauteur d\'eau au-dessus de la crête.';
$ec_lang['irr_card_weir_irregular_head']='Déversoir — Profil Irrégulier';
$ec_lang['irr_card_weir_irregular_desc']='À utiliser lorsque la crête du déversoir n\'est pas à une élévation uniforme unique — déversoirs naturels, structures de chute à largeur variable ou structures de contrôle à sections multiples.';
$ec_lang['irr_card_orifice_head']='Orifice — Vanne de Prise ou Sortie de Canalisation';
$ec_lang['irr_card_orifice_desc']='Mesurez le débit à travers une vanne de type batardeau, une sortie de canalisation ou une ouverture de buse. Gère automatiquement les conditions de déversement libre et noyé (contrecharge aval).';
$ec_lang['irr_card_canal_head']='Conception &amp; Analyse de Canal';
$ec_lang['irr_card_canal_desc']='Concevez ou vérifiez un canal d\'irrigation à l\'aide de la formule de Manning. Utilisez la calculatrice Trapézoïdale pour les nouveaux canaux ; la calculatrice Irrégulière pour les sections naturelles ou construites existantes.';
$ec_lang['irr_card_drip_head']='Conception Goutte-à-Goutte &amp; Aspersion';
$ec_lang['irr_card_drip_desc']='Calculez le taux d\'application, l\'uniformité de distribution, le débit latéral, le débit de zone et la durée de fonctionnement pour un système d\'irrigation goutte-à-goutte ou par aspersion. Saisissez le débit de l\'émetteur, l\'espacement et la profondeur cible.';
$ec_lang['irr_card_seepage_head']='Infiltration &amp; Efficience de Transport en Canal';
$ec_lang['irr_card_seepage_desc']='Estimez les pertes par infiltration d\'un bief de canal à partir des mesures de débit entrant et sortant. Calculez l\'efficience de transport et le volume d\'eau perdu annuellement pour aider à prioriser les investissements de revêtement.';
$ec_lang['irr_quickref_html']='<h3>Référence Rapide</h3><dl><dt>Barrage de dérivation ou structure de contrôle</dt><dd>Mesurez la hauteur d\'eau au-dessus de la crête du déversoir. Utilisez <a href="Weir-Flow-Simple.php">Déversoir Simple</a> pour une crête uniforme, ou <a href="Weir-Flow-Irregular.php">Déversoir Irrégulier</a> pour une crête profilée ou à gradins.</dd><dt>Vanne de prise ou sortie de canalisation</dt><dd>Mesurez la cote de l\'eau en amont et en aval (ou la cote du radier si le déversement est libre). Utilisez <a href="Orifice.php">Débit par Orifice</a>. Pour une canalisation circulaire, D&nbsp;= diamètre de la canalisation ; pour une vanne rectangulaire, saisissez la largeur W et la hauteur D.</dd><dt>Temps de vidange de réservoir ou d\'étang</dt><dd>Utilisez <a href="Orifice-Drain-Time.php">Temps de Vidange par Orifice</a> pour estimer le temps nécessaire pour abaisser le niveau d\'un étang ou réservoir par un orifice de fond — utile pour la planification du stockage irrigant.</dd><dt>Normes de terrain</dt><dd>Les équations de débit par déversoir et orifice utilisées ici correspondent aux procédures du <em>Manuel de Mesure de l\'Eau</em> (3e&nbsp;éd.) de l\'USBR, couramment exigées par les gestionnaires de l\'eau et les districts d\'irrigation.</dd></dl>';
$ec_lang['about_body_html']='<h3>Mission</h3><p>Les Calculatrices d\'Ingénierie HawsEDC existent pour servir les ingénieurs et les travailleurs de terrain du monde entier — en particulier ceux qui travaillent dans des régions à faibles ressources en eau, à ressources limitées ou peu desservies. Ces outils font partie d\'une mission humanitaire plus large : dire à chaque être humain de la manière la plus pratique et la plus efficace possible qu\'il est aimé et chéri pour toujours, qu\'il n\'a rien à craindre, et qu\'il ne va pas tout gâcher.</p><p>Les calculatrices sont le véhicule. La destination est un monde libre de souffrance.</p><h3>Licence Open Source</h3><p>Tout le code est publié sous la <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licence Publique Générale GNU v3.0 ou ultérieure</a> — libre comme dans liberté. Vous pouvez utiliser, étudier, modifier et redistribuer le code selon les mêmes termes.</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>Code Source</h3><p>Le code source complet est disponible publiquement sur Bitbucket :</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Vous pouvez parcourir le code, signaler des problèmes ou bifurquer le dépôt là-bas.</p><h3>Contribuer</h3><p>Les demandes de tirage sont les bienvenues. Façons de contribuer :</p><ul><li><strong>Traductions</strong> — améliorez ou ajoutez une langue. Ouvrez une demande de tirage avec les modifications apportées au fichier <code>lib/lang.ec.??.php</code> correspondant.</li><li><strong>Rapports de bogues</strong> — utilisez le formulaire de commentaires sur n\'importe quelle page de calculatrice, ou signalez un problème sur Bitbucket.</li><li><strong>Nouvelles calculatrices</strong> — les idées d\'outils de génie hydraulique au service des travailleurs de terrain et des praticiens de l\'irrigation sont particulièrement bienvenues. Consultez le guide du développeur <code>CLAUDE.md</code> dans le dépôt.</li><li><strong>Hébergement</strong> — si vous pouvez héberger ces calculatrices pour une région à connectivité limitée, veuillez nous contacter.</li></ul><h3>Utilisation hors ligne</h3><p>Ces calculatrices fonctionnent comme une Application Web Progressive (PWA). Visitez n\'importe quelle page de calculatrice en étant connecté à internet, et votre navigateur mettra automatiquement en cache toutes les calculatrices. Ensuite, toutes les calculatrices fonctionnent hors ligne — sans connexion internet requise.</p><p>Sur Android ou iOS, utilisez l\'option « Ajouter à l\'écran d\'accueil » de votre navigateur pour installer EngCalcs comme application sur votre appareil. Sur ordinateur, recherchez l\'icône d\'installation dans la barre d\'adresse de votre navigateur.</p><p>Vous pouvez également enregistrer n\'importe quelle calculatrice individuelle en utilisant le menu « Enregistrer sous&hellip; » de votre navigateur pour une utilisation hors ligne ponctuelle.</p><h3>Contact</h3><p>Tom Haws — ingénieur hydraulique et auteur de ces calculatrices.<br />Utilisez le formulaire de commentaires sur n\'importe quelle page de calculatrice, ou accédez au code source sur <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Conception de Chute en Enrochement (Robinson)';
$ec_lang['rc_main_title']='Calculatrice Gratuite de Conception de Chute en Enrochement — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionnement de l\'Enrochement de Chute &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='Pente du radier de la chute, S<sub>0</sub>';
$ec_lang['rc_qt']='Débit unitaire total, q<sub>t</sub> <span title="Débit par unité de largeur à l\'entrée de la chute. Pour un canal de largeur de fond B avec débit total Q, utiliser q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Porosité de l\'enrochement, n<sub>p</sub>';
$ec_lang['rc_sg']='Densité relative du matériau, sg <span title="Granit concassé ou basalte typique ≈ 2,65. Plage valide Robinson : 2,54 à 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Granulométrie SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Écart-type granulométrique. Enrochement uniforme ≈ 1,25. Plage valide Robinson : 1,15 à 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Tirant d\'eau normal dans le canal amont, y<sub>n</sub> <span title="La mise en charge (Hp > yn) est favorable — réduit l\'érosion en amont. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Taille médiane requise des blocs, D<sub>50</sub> <span title="Éq. 1 (S0 &lt; 0,10) ou Éq. 2 (0,10–0,40). Valide : D50 15–278 mm, S0 0,02–0,40. Hors plage : extrapolé." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Équation appliquée';
$ec_lang['rc_sg_check']='Vérification de la densité relative';
$ec_lang['rc_SD_check']='Vérification de la granulométrie SD';
$ec_lang['rc_sg_ok']   ='sg dans la plage valide (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Avertissement : sg < 2,54 — en dessous de la plage Robinson';
$ec_lang['rc_sg_high'] ='Avertissement : sg > 2,82 — au-dessus de la plage Robinson';
$ec_lang['rc_SD_ok']   ='SD dans la plage valide (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Avertissement : SD < 1,15 — en dessous de la plage Robinson';
$ec_lang['rc_SD_high'] ='Avertissement : SD > 1,47 — au-dessus de la plage Robinson';
$ec_lang['rc_layer']='Épaisseur de la couche de blocs (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Rayon de courbure en crête (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Longueur d\'arc en crête';
$ec_lang['rc_apron_length']='Longueur du tablier de sortie (15 &times; D<sub>50</sub>) <span title="Requis pour le support structurel de l\'enrochement de la chute. &quot;La hauteur d\'eau minimale à l\'aval résultant du tronçon de sortie et de la résistance du canal aval est suffisante pour assurer la stabilité de l\'enrochement dans le tronçon de sortie.&quot; (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Rugosité de Manning dans la chute, n';
$ec_lang['rc_Vm']='Vitesse à travers le manteau rocheux, V<sub>m</sub> <span title="Fraction de qt s\'écoulant à travers les pores des blocs. Le reste qs s\'écoule en surface. np par défaut = 0,45 pour roche concassée anguleuse." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Débit unitaire dans le manteau, q<sub>m</sub>';
$ec_lang['rc_qs']='Débit unitaire de surface, q<sub>s</sub> (q<sub>t</sub> &minus; q<sub>m</sub>)';
$ec_lang['rc_d']='Profondeur d\'écoulement au-dessus de la surface d\'enrochement, d';
$ec_lang['rc_Hp']='Charge au déversoir d\'entrée, H<sub>p</sub> <span title="La mise en charge (Hp > yn) est favorable — réduit l\'érosion en amont. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Vérification de la mise en charge à l\'entrée';
$ec_lang['rc_pond_ok']  ='Hp > yn — mise en charge amont ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — pas de mise en charge — vérifier l\'érosion à l\'entrée';
$ec_lang['rc_eq1']='Éq. 1 (S0 < 0,10) — pente douce';
$ec_lang['rc_eq2']='Éq. 2 (0,10 ≤ S0 ≤ 0,40) — pente forte';
$ec_lang['rc_eq_warn_low']='Avertissement : S0 < 0,02 — en dessous de la plage de validation Robinson';
$ec_lang['rc_eq_warn_high']='Avertissement : S0 > 0,40 — au-dessus de la plage de validation Robinson';
$ec_lang['rc_notes_1_term']='Équations de dimensionnement des blocs';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) ont développé deux équations empiriques pour la taille médiane d\'enrochement D<sub>50</sub> en fonction de la pente de la chute et du débit unitaire. L\'équation 1 s\'applique aux pentes douces (S<sub>0</sub> &lt; 0,10) ; l\'équation 2 aux pentes fortes (0,10 &le; S<sub>0</sub> &le; 0,40). Les deux équations nécessitent q<sub>t</sub> en m&sup2;/s et restituent D<sub>50</sub> en mm. La plage validée est 0,02 &le; S<sub>0</sub> &le; 0,40.';
$ec_lang['rc_notes_2_term']='Débit unitaire';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> est le débit unitaire total à la crête de la chute (débit total par unité de largeur). Pour un canal de largeur de fond B transportant un débit total Q, q<sub>t</sub> &asymp; Q / B, ou calculé à partir de la condition de tirant critique à l\'entrée de la chute.';
$ec_lang['rc_notes_3_term']='Écoulement à travers le manteau rocheux';
$ec_lang['rc_notes_3_def']='Une fraction du débit total s\'écoule à travers les pores de l\'enrochement (débit de manteau q<sub>m</sub>) ; le reste s\'écoule en surface (q<sub>s</sub> = q<sub>t</sub> &minus; q<sub>m</sub>). La profondeur d\'écoulement d est calculée par l\'équation de Manning appliquée au débit de surface q<sub>s</sub> avec la rugosité n de la chute. La porosité par défaut n<sub>p</sub> = 0,45 est typique pour la roche concassée anguleuse.';
$ec_lang['rc_notes_5_term']='Plage valide de taille de blocs';
$ec_lang['rc_notes_5_def']='Les équations ont été développées pour une plage D<sub>50</sub> de 15&nbsp;mm à 278&nbsp;mm. Les résultats hors de cette plage sont extrapolés et doivent être utilisés avec un jugement d\'ingénierie complémentaire.';
$ec_lang['rc_notes_6_term']='Cote de la surface du tablier de sortie';
$ec_lang['rc_notes_6_def']='La cote du dessus de l\'enrochement dans le tronçon de sortie doit être égale ou inférieure à la cote du fond du canal aval. Si elle est plus haute, l\'enrochement de sortie sera instable.';
$ec_lang['rc_notes_7_term']='Vérification de la mise en charge à l\'entrée';
$ec_lang['rc_notes_7_def']='Lorsque le tirant d\'eau normal dans le canal d\'entrée est inférieur à la charge de déversoir (H<sub>p</sub>) nécessaire pour transiter q<sub>t</sub>, un écoulement limité ou une mise en charge se produit en amont du tablier d\'entrée. Ceci est généralement acceptable — la mise en charge réduit la vitesse et prévient l\'érosion en amont. Pour vérifier : utiliser une calculatrice de déversoir pour trouver H<sub>p</sub> pour le q<sub>t</sub> et la largeur de crête donnés, puis comparer au tirant d\'eau normal du canal d\'entrée. Si H<sub>p</sub> dépasse le tirant d\'eau normal, une mise en charge se produira.';
$ec_lang['rc_notes_4_term']='Référence';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., et Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://doi.org/10.13031/2013.17230">Design of rock chutes</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. L\'USDA ARS publie également un <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">tableur Excel</a> basé sur la même méthode.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtre';
$ec_lang['rc_sketch_top_crest_curve'] = 'Courbe de crête';
$ec_lang['rc_sketch_outlet_apron']    = 'Radier de sortie';
$ec_lang['rc_sketch_radius']          = 'rayon';
