<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fraction";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']="rise/run";
$ec_lang['u_in2']="sq. in.";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="sec";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']="kW";
$ec_lang['u_mw']="MW";
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']="hp";

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC Calculators';
$ec_lang['menu_main_list']='List of Calculators';
$ec_lang['menu_main_hydraulics']='Hydraulics';
$ec_lang['menu_main_language']='Language';
$ec_lang['template_welcome']='&gt;&gt; Drop your fears at the door; love is spoken here. You are not ruining everything. Enjoy the <a target="_blank" href="https://hawsedc.com/download.php">free libre HawsEDC AutoCAD tools</a> too. &lt;&lt;';
$ec_lang['template_translation_help']='Do you have a great vision for a calculator to add here?  Can you help me improve translations, program, or host these calculators?  ';
$ec_lang['template_feedback']='Please give us your valued words of suggestion or praise.  Did this free calculator exceed your expectations in every way?';
$ec_lang['template_printable_title']='Printable Title';
$ec_lang['template_printable_subtitle']='Printable Subtitle';
$ec_lang['index_title']='Free Online Engineering Calculators';
$ec_lang['calc_set_units']='Set units:';
$ec_lang['points_data_help']='(or Copy/Paste using data area)';
$ec_lang['points_data_title']='Points data<br />(comma or tab separated)';
$ec_lang['points_data_copy']='Copy';
$ec_lang['points_data_paste']='Paste';
$ec_lang['calc_inputs']='Inputs';
$ec_lang['calc_results']='Results';
$ec_lang['view_hide_line']='[Hide this line]';
$ec_lang['view_printable']='Printable version (reload/refresh to restore)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach Pipe Head Loss';
$ec_lang['dw_main_title']='Free Online Darcy-Weisbach Pipe Head Loss Calculator';
$ec_lang['dw_main_desc']='Darcy-Weisbach Pipe Head Loss at Given Diameter, Roughness, and Flow';
$ec_lang['dw_roughness']='Darcy-Weisbach absolute roughness, e';
$ec_lang['dw_kinematic_viscosity']='Kinematic viscosity, v, in m<sup>2</sup>/sec (1E-6 for clean water at room temperature)';
$ec_lang['dw_reynolds_number']='Reynolds number, Re';
$ec_lang['dw_flow_regime']='Flow regime';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='transitional';
$ec_lang['dw_regime_turbulent']='turbulent';
$ec_lang['dw_friction_factor_method']='Friction factor method';
$ec_lang['dw_friction_factor']='Friction factor, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams Pipe Head Loss';
$ec_lang['hw_main_title']='Free Online Hazen-Williams Pipe Head Loss Calculator';
$ec_lang['hw_main_desc']='Hazen-Williams Pipe Head Loss at Given Diameter, Roughness, and Flow';
$ec_lang['hw_hgl_1']='Downstream HGL';
$ec_lang['hw_hgl_2']='Upstream HGL';
$ec_lang['hw_roughness']='Hazen-Williams coefficient, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning Irregular Channel';
$ec_lang['mi_main_title']='Free Online Manning Irregular Channel Calculator';
$ec_lang['mi_main_desc']='Irregular Channel Manning Uniform Flow Calculator';
$ec_lang['mi_waterSurfaceElevation']='Water surface elevation';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Cross section points';
$ec_lang['mi_groupPoint']='Point';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Region';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Elev';
$ec_lang['mi_d50in']='Lining<br />median<br />rock<br />size';
$ec_lang['mi_n']='n<br />for seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />region<br />boundary<br />(Bank)';
$ec_lang['mi_tau']='Bot.<br />shear<br />&tau;'; //no
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Comp.<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Notes';
$ec_lang['mi_notes_1_term']='Composite n';
$ec_lang['mi_notes_1_def']='This calculator follows HEC-RAS Reference Manual in calculating region composite n using Chow 1959, page 136, equation 6-17 (not 6-18).';
$ec_lang['mi_notes_2_term']='Rock lining';
$ec_lang['mi_notes_2_def']='Use the Manning Trapezoidal Channel Calculator to design rock lining. This calculator is more for natural sections.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning Pipe Flow';
$ec_lang['mpf_main_title']='Free Online Manning Pipe Flow Calculator';
$ec_lang['mpf_main_desc']='Manning Formula Uniform Pipe Flow at Given Slope and Depth';
$ec_lang['mpf_spreadheet_notice']='Check out the spreadsheet version of this calculator';
$ec_lang['mpf_pipe_diameter']='Pipe diameter, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning roughness, n';
$ec_lang['mpf_friction_slope']='Pressure slope (possibly <a target="_blank" href="../pressureslope.php">?</a> equal to pipe slope), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Relative flow depth, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(See notes)';
$ec_lang['mpf_flow']='Flow, Q';
$ec_lang['mpf_velocity']='Velocity, v';
$ec_lang['mpf_velocity_head']='Velocity head, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Flow area, a';
$ec_lang['mpf_pipe_area']='Pipe area, a0';
$ec_lang['mpf_area_ratio']='Relative area, a/a0';
$ec_lang['mpf_wetted_perimeter']='Wetted perimeter, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Hydraulic radius, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Top width, T';
$ec_lang['mpf_froude_number']='Froude number, F';
$ec_lang['mpf_shear_stress']='Average shear stress (tractive force), tau';
$ec_lang['mpf_full_flow']='Full flow, Q0';
$ec_lang['mpf_full_flow_ratio']='Ratio to full flow, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>This is the flow and depth inside an <em>infinitely long</em> pipe.</dt><dd>Getting the flow into the pipe may require significantly higher headwater depth. Add at least 1.5 times the velocity head to get the headwater depth or <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">see my 2-minute tutorial</a> for standard culvert headwater calculations using HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Solve for y/d<sub>0</sub> given Q';
$ec_lang['mpf_solve_desc']='Using D<sub>0</sub>, n, and S<sub>0</sub> from the calculator form, finds the lowest y/d<sub>0</sub> for a given Q.';
$ec_lang['mpf_solve_button']='Solve';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning Pipe Head Loss';
$ec_lang['mphl_main_title']='Free Online Manning Pipe Head Loss Calculator';
$ec_lang['mphl_main_desc']='Manning Formula Head Loss at Given Full Flow';
$ec_lang['mphl_pipe_length']='Pipe length, L';
$ec_lang['mphl_pipe_length']='Pipe length, L';
$ec_lang['mphl_area']='Area, A';
$ec_lang['mphl_total_junction_k']='Total combined junction loss coefficient, k';
$ec_lang['mphl_friction_slope']='Friction slope';
$ec_lang['mphl_friction_loss']='Friction loss, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Junction loss, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Total loss, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='Downstream EGL';
$ec_lang['mphl_egl_2']='Upstream EGL';
$ec_lang['mphl_hgl_2']='Upstream HGL in pipe ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>For an open inlet (culvert) condition, it is necessary to check for inlet control conditions.</dt><dd>1. The upstream HGL cannot be lower than the upstream normal depth flow elevation (or lower than the pipe!).</dd><dd>2. The headwater of a culvert is better represented by the upstream EGL than the upstream HGL.</dd><dd>3. See <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">my 2-minute tutorial</a> for simple standard culvert headwater calculations using HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning Trapezoidal Channel';
$ec_lang['mtc_main_title']='Free Online Manning Formula Trapezoidal Channel Calculator';
$ec_lang['mtc_main_desc']='Manning Formula Uniform Trapezoidal Channel Flow at Given Slope and Depth';
$ec_lang['mtc_bottom_width']='Bottom width, b';
$ec_lang['mtc_side_slope_1']='Side slope 1 (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Side slope 2 (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Channel slope, S';
$ec_lang['mtc_flow_depth']='Flow depth, y';
$ec_lang['mtc_bend_angle']='Bend Angle <a target="_blank" href="riprap-bend-angle.png" title="Click for image">?</a> (for riprap sizing)';
$ec_lang['mtc_sgrock']='Rock specific gravity (2.65)';
$ec_lang['mtc_d50_in']='Design rock size, D50';
$ec_lang['mtc_n_strickler']='n for design rock size per Strickler';
$ec_lang['mtc_n_blodgett']='n for design rock size per Blodgett';
$ec_lang['mtc_n_bathurst']='n for design rock size per Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Required bottom angular rock size, D50 (Isbash & MC) <a href="javascript:alert(\'Per Isbash (1936) and Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z1']='Required side slope 1 angular rock size, D50 (Isbash & MC) <a href="javascript:alert(\'Per Isbash (1936) and Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_z2']='Required side slope 2 angular rock size, D50 (Isbash & MC) <a href="javascript:alert(\'Per Isbash (1936) and Maricopa County, Arizona, US.\')">?</a>';
$ec_lang['mtc_d50_mra']='Required angular rock size, D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='Required angular rock size, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Automated rock size and roughness design iteration</dt><dd>Choose a roughness radio button (BB recommended) and a design rock size radio button (Isbash recommended). Fine-tune depth and rock size safety factor to get your desired flow with an even rock size. Every time you change any input value, the following iteration cycle happens: 1. Roughness is calculated from design rock size. 2. The requested roughness calculation is copied to input roughness. 3. Channel flow and required rock size are calculated. 4. Design rock size is adjusted. 5. Repeat until error in the design rock size is very small.</dd><dt>Basic calculator (no iteration)</dt><dd>Enter your desired roughness value. Ignore the design rock size input area.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='Robinson Rock Chute Design Spreadsheet';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Weir Flow Simple';
$ec_lang['ws_main_title']='Free  Online Simple Broad-crested Weir Flow Calculator';
$ec_lang['ws_main_desc']='Simple Broad-crested Weir Flow Calculator';
$ec_lang['ws_weirLength']='Weir length, l';
$ec_lang['ws_headWaterHeight']='Headwater height, h';
$ec_lang['ws_weirCoefficient']='Weir coefficient, Cw';
$ec_lang['ws_notes_heading']='Notes';
$ec_lang['ws_notes_we_term']='Weir Equation';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Weir Flow Irregular';
$ec_lang['wi_main_title']='Free Online Segmented, Variable Depth, Irregular Weir Flow Calculator';
$ec_lang['wi_main_desc']='Irregular Weir Flow Calculator';
$ec_lang['wi_headWaterelevation']='Headwater elevation';
$ec_lang['wi_weirPoints']='Weir points';
$ec_lang['wi_station']='Station<br />(distance)';
$ec_lang['wi_elevation']='Elevation';
$ec_lang['wi_pondingHeight']='Ponding Height';
$ec_lang['wi_incrementalFlow']='Incremental Flow';
$ec_lang['wi_cumulativeFlow']='Cumulative Flow';
$ec_lang['wi_save_and_calculate']='Save and Calculate';
$ec_lang['wi_notes_we_term']='Weir Equation';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='Orifice Flow';
$ec_lang['or_main_title']='Free Online Orifice Flow Calculator';
$ec_lang['or_main_desc']='Orifice Flow — Free or Submerged';
$ec_lang['or_shape']='Opening shape';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Rectangular';
$ec_lang['or_diameter']='Diameter (circular) or height (rectangular), D';
$ec_lang['or_width']='Width, W (rectangular only)';
$ec_lang['or_invert']='Opening invert elevation (bottom of opening)';
$ec_lang['or_hwe']='Headwater elevation';
$ec_lang['or_twe']='Tailwater elevation';
$ec_lang['or_cd']='Discharge coefficient, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Centroid elevation';
$ec_lang['or_head']='Effective head, h';
$ec_lang['or_area']='Opening area, A';
$ec_lang['or_flow']='Flow, Q';
$ec_lang['or_velocity']='Velocity at opening, v';
$ec_lang['or_regime']='Orifice regime check';
$ec_lang['or_regime_valid']='Free outfall — orifice regime valid ✓';
$ec_lang['or_regime_submerged']='Submerged orifice (TWE above invert) — valid ✓';
$ec_lang['or_regime_warn']='Warning: headwater below crown — not orifice regime';
$ec_lang['or_regime_twe_above_hwe']='Warning: tailwater (TWE) above headwater (HWE) — check inputs';
$ec_lang['or_notes_1_term']='Orifice Equation';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). For free outfall: h = HWE &minus; centroid. For submerged flow (TWE above invert): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Orifice Regime';
$ec_lang['or_notes_2_def']='Orifice flow equations apply when the headwater surface is above the crown (top) of the opening. When headwater is below the crown, use a weir equation instead.';
$ec_lang['or_notes_3_term']='Discharge Coefficient';
$ec_lang['or_notes_3_def']='C<sub>d</sub> ranges from about 0.60&ndash;0.65 for sharp-edged orifices. Rounded or re-entrant inlets use different values. See the <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> or the HEC-RAS Hydraulic Reference Manual for guidance.';
$ec_lang['or_notes_4_term']='Submergence';
$ec_lang['or_notes_4_def']='When TWE is above the opening invert, this calculator automatically applies the submerged orifice equation using h = HWE &minus; TWE. When TWE is at or below the invert, free outfall is assumed and h = HWE &minus; centroid.';
// Penstock Design
$ec_lang['ps_main_menu']='Penstock Design';
$ec_lang['ps_main_title']='Free Online Penstock Design Calculator';
$ec_lang['ps_main_desc']='Micro-Hydro Penstock Sizing — Head Loss, Power, and Velocity';
$ec_lang['ps_flow']='Flow rate, Q';
$ec_lang['ps_gross_head']='Gross head, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Penstock diameter, D';
$ec_lang['ps_length']='Penstock length, L';
$ec_lang['ps_roughness']='Pipe roughness, e';
$ec_lang['ps_km']='Junction (or &ldquo;minor&rdquo;) loss coefficient, k<sub>m</sub>';
$ec_lang['ps_nu']='Kinematic viscosity, &nu;, in m<sup>2</sup>/s (1E-6 for water near 20&deg;C)';
$ec_lang['ps_efficiency']='Plant efficiency, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Flow velocity, v';
$ec_lang['ps_vel_check']='Velocity check';
$ec_lang['ps_f']='Friction factor, f';
$ec_lang['ps_hf']='Friction head loss, h<sub>f</sub>';
$ec_lang['ps_hm']='Junction (point) head loss, h<sub>m</sub>';
$ec_lang['ps_hl']='Total penstock loss, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Head loss check';
$ec_lang['ps_hnet']='Net head, H<sub>net</sub>';
$ec_lang['ps_power']='Power output, P';
$ec_lang['ps_annual_kwh']='Annual energy at 100% capacity';
$ec_lang['ps_vel_ok']='1–3 m/s — within target ✓';
$ec_lang['ps_vel_low']='below 1 m/s — increase diameter ⚠';
$ec_lang['ps_vel_high']='above 3 m/s — decrease diameter ⚠';
$ec_lang['ps_hl_ok']='within 10% target ✓';
$ec_lang['ps_hl_warn']='exceeds 10% target — consider larger pipe ⚠';
$ec_lang['ps_hl_bad']='exceeds 20% — resize pipe';
$ec_lang['ps_notes_1_term']='Head Loss';
$ec_lang['ps_notes_1_def']='Total penstock loss h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, where h<sub>f</sub> = f(L/D)(v&sup2;/2g) is Darcy-Weisbach friction loss and h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g covers entrance, bends, and valves. Net head H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Velocity';
$ec_lang['ps_notes_2_def']='Target 1&ndash;3 m/s. Below 1 m/s over-sizes the pipe for the flow; above 3 m/s increases friction losses and water hammer risk.';
$ec_lang['ps_notes_3_term']='Head Loss Target';
$ec_lang['ps_notes_3_def']='Penstock losses below 10% of gross head are generally economic. The optimal trade-off between pipe cost and lost power often falls around 4&ndash;6% for high-value electricity sites.';
$ec_lang['ps_notes_4_term']='Junction (Point) Losses k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='These losses occur at pipe junctions, entrances, bends, and valves &mdash; the term &ldquo;minor&rdquo; is conventional but misleading; in a short penstock they can equal or exceed friction losses. Typical k values: sharp intake entrance 0.5, each 45&deg; bend 0.2&ndash;0.3, gate valve (fully open) 0.1, butterfly valve 0.2. Sum all fittings for the total k<sub>m</sub>. Default 1.5 assumes one entrance and two bends.';
$ec_lang['ps_notes_5_term']='Pipe Roughness e';
$ec_lang['ps_notes_5_def']='Typical absolute roughness: steel (new) 0.046&nbsp;mm, steel (used) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, concrete 0.3&ndash;3&nbsp;mm. HDPE is common for small micro-hydro penstocks.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hydro Power';
$ec_lang['mhp_main_title']='Free Online Micro-Hydro Power Calculator';
$ec_lang['mhp_main_desc']='Run-of-River Micro-Hydro Power Output Calculator';
$ec_lang['mhp_flow']='Flow rate, Q';
$ec_lang['mhp_gross_head']='Gross head (elevation drop), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Penstock head losses, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Plant efficiency, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Net head, H<sub>net</sub>';
$ec_lang['mhp_power']='Power output, P';
$ec_lang['mhp_annual_kwh']='Annual energy at 100% capacity';
$ec_lang['mhp_notes_1_term']='Power Equation';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, where &rho; = 1000 kg/m&sup3; (fresh water) and g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Net Head';
$ec_lang['mhp_notes_2_def']='Net head = gross head &minus; penstock head losses. A common first estimate is h<sub>L</sub> &asymp; 5% of H<sub>gross</sub>. Use the <a href="Darcy-Weisbach.php">Darcy-Weisbach calculator</a> for more accurate penstock loss estimates.';
$ec_lang['mhp_notes_3_term']='Efficiency';
$ec_lang['mhp_notes_3_def']='Typical plant efficiency &eta; ranges from 0.70 to 0.85 for Pelton and cross-flow turbines common in micro-hydro. Use 0.75 as a conservative first estimate.';
$ec_lang['mhp_notes_4_term']='Annual Energy';
$ec_lang['mhp_notes_4_def']='Annual energy assumes continuous full-flow operation (8760 hours/year). Actual production will be lower due to seasonal flow variation, maintenance downtime, and load factor.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Orifice Drain Time';
$ec_lang['odt_main_title']='Free Online Orifice Drain Time Calculator — Pond, Basin, or Tank';
$ec_lang['odt_main_desc']='Pond or Basin Orifice Drain Time &mdash; Conic Volume Method';
$ec_lang['odt_h1_elev']='Starting water surface elevation';
$ec_lang['odt_a1']='Starting pond or basin area, A1';
$ec_lang['odt_h2_elev']='Ending water surface elevation';
$ec_lang['odt_h_orifice']='Orifice centroid elevation';
$ec_lang['odt_a0']='Pond or basin area at orifice elevation, A0';
$ec_lang['odt_a_ending']='Ending pond area, A2 (interpolated)';
$ec_lang['odt_h2_check']='Ending elevation check';
$ec_lang['odt_h2_ok']='Ending elevation above orifice top ✓';
$ec_lang['odt_h2_warn']='Warning: ending elevation at or below orifice top (centroid + D/2)';
$ec_lang['odt_d']='Orifice diameter (circular) or height (rectangular), D';
$ec_lang['odt_w']='Orifice width, W (rectangular only)';
$ec_lang['odt_t_sec']='Drain time (seconds)';
$ec_lang['odt_t_min']='Drain time (minutes)';
$ec_lang['odt_t_hr']='Drain time (hours)';
$ec_lang['odt_t_day']='Drain time (days)';
$ec_lang['odt_notes_1_term']='Formula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) gives drain time from head H to the orifice. Drain time = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), where H<sub>1</sub> = starting elevation &minus; orifice elevation, H<sub>2</sub> = ending elevation &minus; orifice elevation.';
$ec_lang['odt_notes_2_term']='Method';
$ec_lang['odt_notes_2_def']='The conic volume method models the pond or basin as a conic section between the starting area A<sub>1</sub> at the initial water surface and the area A<sub>0</sub> at the orifice centroid elevation. A<sub>2</sub>, the pond area at the ending elevation, is interpolated from A<sub>1</sub> and A<sub>0</sub> using the conic section model. Drain time from starting to ending elevation equals total drain time from H<sub>1</sub> to orifice minus remaining drain time from H<sub>2</sub> to orifice.';
$ec_lang['odt_h1']='Starting head, H<sub>1</sub> (WSE &minus; centroid)';
$ec_lang['odt_q_max']='Max (starting) flow, Q<sub>max</sub>';
$ec_lang['odt_vol']='Drained volume';
$ec_lang['odt_sketch_start']='Start';
$ec_lang['odt_sketch_end']='End';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Bank to bank width';
$ec_lang['essc_mcr']='Minimum curve radius';
$ec_lang['essc_q']='Flow, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Irrigation Flow Measurement';
$ec_lang['irr_main_title']='Free Online Irrigation Flow Measurement Calculators';
$ec_lang['irr_main_desc']='Irrigation Flow Measurement — Weirs and Orifices';
$ec_lang['irr_intro_html']='<p>Weirs and orifices are the standard field tools for measuring water flow in irrigation systems. Select the calculator that matches your structure:</p>';
$ec_lang['irr_card_weir_uniform_head']='Weir — Broad-Crested (Uniform Width)';
$ec_lang['irr_card_weir_uniform_desc']='Measure flow over a diversion dam crest, check structure, or weir board. Enter weir length and headwater depth above the crest.';
$ec_lang['irr_card_weir_irregular_head']='Weir — Irregular Profile';
$ec_lang['irr_card_weir_irregular_desc']='Use when the weir crest is not a single uniform elevation — natural spillways, drop structures with varying width, or multi-section control structures.';
$ec_lang['irr_card_orifice_head']='Orifice — Headgate or Pipe Turnout';
$ec_lang['irr_card_orifice_desc']='Measure flow through a sluice gate, pipe turnout, or culvert opening. Handles both free outfall and submerged (tailwater) conditions automatically.';
$ec_lang['irr_card_canal_head']='Canal Design &amp; Analysis';
$ec_lang['irr_card_canal_desc']='Design or check an irrigation canal using Manning\'s formula. Use the Trapezoidal calculator for new channels; the Irregular calculator for existing natural or constructed sections.';
$ec_lang['irr_card_drip_head']='Drip &amp; Sprinkler Design';
$ec_lang['irr_card_drip_desc']='Calculate application rate, distribution uniformity, lateral flow, zone flow, and runtime for a drip or sprinkler irrigation system. Enter emitter flow, emitter spacing, and target depth.';
$ec_lang['irr_quickref_html']='<h3>Quick Reference</h3><dl><dt>Diversion dam or check structure</dt><dd>Measure headwater depth above the weir crest. Use <a href="Weir-Flow-Simple.php">Weir Flow Simple</a> for a uniform crest, or <a href="Weir-Flow-Irregular.php">Weir Flow Irregular</a> for a profiled or stepped crest.</dd><dt>Headgate or pipe turnout</dt><dd>Measure headwater elevation and tailwater elevation (or invert if freely discharging). Use <a href="Orifice.php">Orifice Flow</a>. For a circular pipe, D&nbsp;= pipe diameter; for a rectangular gate, enter width W and height D.</dd><dt>Reservoir or pond drain time</dt><dd>Use <a href="Orifice-Drain-Time.php">Orifice Drain Time</a> to estimate how long it takes to lower a pond or reservoir through a bottom orifice — useful for irrigation storage planning.</dd><dt>Field standards</dt><dd>Weir and orifice flow equations used here match USBR <em>Water Measurement Manual</em> (3rd&nbsp;ed.) procedures commonly required by water masters and irrigation districts.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ds_main_menu']='Drip/Sprinkler Application Rate';
$ec_lang['ds_main_title']='Free Online Drip/Sprinkler Irrigation Application Rate Calculator';
$ec_lang['ds_main_desc']='Drip &amp; Sprinkler Irrigation &mdash; Application Rate and Uniformity';
$ec_lang['ds_q_avg']='Average emitter flow rate, q';
$ec_lang['ds_q_min']='Minimum emitter flow rate, q<sub>min</sub>';
$ec_lang['ds_se']='Emitter spacing along lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateral spacing (row spacing), S<sub>l</sub>';
$ec_lang['ds_n_e']='Emitters per lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Laterals per zone, n<sub>l</sub>';
$ec_lang['ds_d']='Target application depth, d';
$ec_lang['ds_a_e']='Area per emitter, A<sub>e</sub>';
$ec_lang['ds_pr']='Application rate (precipitation rate), PR';
$ec_lang['ds_du']='Distribution uniformity, DU';
$ec_lang['ds_du_check']='DU quality check';
$ec_lang['ds_q_lat']='Flow per lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Zone flow, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Runtime for target depth (hours)';
$ec_lang['ds_du_excellent']='Excellent — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='Good — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='Acceptable — DU ≥ 70%';
$ec_lang['ds_du_poor']='Poor — DU < 70% — review design ⚠';
$ec_lang['ds_notes_1_term']='Application Rate';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, where A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> is the area served by each emitter. A lower application rate gives more time for infiltration &mdash; important on heavy soils or sloped fields.';
$ec_lang['ds_notes_2_term']='Distribution Uniformity (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. A DU of 1.0 (100%) means all emitters flow identically. Values below 0.80 waste water on well-watered areas while leaving drier spots. Uniformity drops with excessive pressure variation along the lateral, emitter wear, or partial clogging.';
$ec_lang['ds_notes_3_term']='Runtime';
$ec_lang['ds_notes_3_def']='Runtime = target depth &divide; application rate. On sloping or compacted soil, split the runtime into two or three shorter cycles with rest periods between them to avoid surface runoff.';
// About
$ec_lang['about_main_menu']='About';
$ec_lang['about_main_title']='About HawsEDC Engineering Calculators';
$ec_lang['about_main_desc']='Mission, Open Source, and Contributing';
$ec_lang['about_body_html']='<h3>Mission</h3><p>HawsEDC Engineering Calculators exist to serve engineers and field workers around the world — especially those working in water-scarce, low-resource, or underserved regions. These tools are part of a broader humanitarian mission: to tell every human being in the most practical and effective way possible that they are loved and cherished forever, that they have nothing to fear, and that they are not going to ruin everything.</p><p>The calculators are the vehicle. The destination is a world free of suffering.</p><h3>Open Source License</h3><p>All code is released under the <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 or later</a> — free as in freedom. You may use, study, modify, and redistribute the code under the same terms.</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>Source Code</h3><p>The full source code is publicly available on Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>You can browse the code, file issues, or fork the repository there.</p><h3>Contributing</h3><p>Pull requests are welcome. Ways to contribute:</p><ul><li><strong>Translations</strong> — improve or add a language. Open a pull request with changes to the relevant <code>lib/lang.ec.??.php</code> file.</li><li><strong>Bug reports</strong> — use the feedback form on any calculator page, or file an issue on Bitbucket.</li><li><strong>New calculators</strong> — ideas for hydraulic engineering tools that serve field workers and irrigation practitioners are especially welcome. See the <code>CLAUDE.md</code> developer guide in the repository.</li><li><strong>Hosting</strong> — if you can mirror these calculators for a region with limited connectivity, please get in touch.</li></ul><h3>Offline Downloads</h3><p>You can save any calculator to your local device using your browser\'s "Save as&hellip;" menu.</p><p>An offline ZIP download is not yet available, but is planned — intended for engineers and field workers in areas with limited or expensive internet access. The goal is a self-contained bundle that runs from a local drive or USB stick with no server required.</p><p>If you have ideas or can help implement this, please contribute via the repository or the feedback form.</p><h3>Progressive Web App (PWA)</h3><p>These calculators are not yet a Progressive Web App, but PWA support is on the roadmap. The goal is to allow engineers to install the calculators on a phone or tablet and use them offline in the field — particularly valuable in low-connectivity regions.</p><h3>Contact</h3><p>Tom Haws — hydraulic engineer and author of these calculators.<br />Use the feedback form on any calculator page, or reach the source code at <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='HawsEDC Contact';
$ec_lang['contactSendMessage']='Send Tom Haws a message';
$ec_lang['contactYourName']='Your name:';
$ec_lang['contactYourEmail']='Your e-mail address:';
$ec_lang['contactSubject']='Subject:';
$ec_lang['contact_message']='Message:';
$ec_lang['contactSpamPrefix']='Five plus one equals';
$ec_lang['contactSpamPostfix']='(Please spell it out. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Submit Message';
