<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='חלק';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% עלייה/ריצה';
$ec_lang['u_grade']='עלייה/ריצה';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='inches';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='ML/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='מחשבוני HawsEDC';
$ec_lang['menu_main_list']='רשימת המחשבונים';
$ec_lang['menu_main_hydraulics']='הידרוליקה';
$ec_lang['menu_main_language']='שפה';
$ec_lang['menu_more']='עוד';
$ec_lang['template_welcome']='>> השאירו את פחדיכם בדלת; כאן מדברים אהבה. אתם לא הורסים הכול. נהנו גם מ<a target="_blank" href="https://hawsedc.com/download.php">כלי ה-AutoCAD החינמיים של HawsEDC.</a> <<';
$ec_lang['template_translation_help']='האם יש לך חזון נהדר למחשבון שיתווסף כאן?  האם אתה יכול לעזור לי לתרגם את המחשבון לשפה שלך או להטמיע את המחשבון באתר שלך?  ';
$ec_lang['template_feedback']='בבקשה תן לנו את חוות דעתך. האם המחשבון החינמי עלה על כל ציפיותיך?';
$ec_lang['template_printable_title']='אזור כותרת להדפסה';
$ec_lang['template_printable_subtitle']='אזור כותרת משנה להדפסה';
$ec_lang['index_title']='מחשבוני הנדסה חינמיים מקוונים';
$ec_lang['calc_set_units']='הגדרת יחידות';
$ec_lang['calc_defaults']='ערכים ברירת מחדל';
$ec_lang['calc_defaults_confirm']='Reset calculator to factory defaults?';
$ec_lang['points_data_help']='(או העתק/הדבק באמצעות אזור הנתונים)';
$ec_lang['points_data_title']='נתוני נקודות<br />(מופרדות בפסיקים או טאבים)';
$ec_lang['points_data_copy']='העתק';
$ec_lang['points_data_paste']='הדבק';
$ec_lang['calc_inputs']='נתוני קלט';
$ec_lang['calc_results']='תוצאות:';
$ec_lang['view_hide_line']='[הסתר שורה זו]';
$ec_lang['view_printable']='גרסה להדפסה (טען מחדש לשחזור)';
$ec_lang['ec_name_label']='שמור חישוב זה:';
$ec_lang['ec_name_placeholder']='שם';
$ec_lang['ec_name_hint']='שמירת הערכים האלה בכתובת עם סימניה, אחזור מהיסטוריה, ושיתוף';
$ec_lang['calc_copy_link']='Copy link';
$ec_lang['calc_copy_link_done']='Copied!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='אובדן גובה בצינור — Darcy-Weisbach';
$ec_lang['dw_main_title']='מחשבון אובדן גובה בצינור Darcy-Weisbach — חינם מקוון';
$ec_lang['dw_main_desc']='אובדן גובה בצינור Darcy-Weisbach בקוטר, גסות וספיקה נתונים';
$ec_lang['dw_roughness']='גסות מוחלטת Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='צמיגות קינמטית, ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='מספר Reynolds, Re';
$ec_lang['dw_flow_regime']='משטר זרימה';
$ec_lang['dw_regime_laminar']='למינרי';
$ec_lang['dw_regime_transitional']='מעברי';
$ec_lang['dw_regime_turbulent']='טורבולנטי';
$ec_lang['dw_friction_factor_method']='שיטת מקדם החיכוך';
$ec_lang['dw_friction_factor']='מקדם חיכוך, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='אובדן גובה בצינור — Hazen-Williams';
$ec_lang['hw_main_title']='מחשבון אובדן גובה בצינור Hazen-Williams — חינם מקוון';
$ec_lang['hw_main_desc']='אובדן גובה בצינור Hazen-Williams בקוטר, גסות וספיקה נתונים';
$ec_lang['hw_hgl_1']='HGL מורד';
$ec_lang['hw_hgl_2']='HGL מעלה';
$ec_lang['hw_roughness']='מקדם Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='תעלה לא סדירה — Manning';
$ec_lang['mi_main_title']='מחשבון תעלה לא סדירה לפי Manning — חינם מקוון';
$ec_lang['mi_main_desc']='מחשבון זרימה אחידה בתעלה לא סדירה לפי Manning';
$ec_lang['mi_waterSurfaceElevation']='גובה מפלס המים';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='נקודות חתך רוחב';
$ec_lang['mi_groupPoint']='נקודה';
$ec_lang['mi_groupSegment']='קטע';
$ec_lang['mi_groupRegion']='אזור';
$ec_lang['mi_station']='תחנה';
$ec_lang['mi_elevation']='גובה';
$ec_lang['mi_d50in']='גודל<br />סלע<br />חיפוי<br />חציוני';
$ec_lang['mi_n']='n<br />לקטע';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />גבול<br />אזור<br />(גדה)';
$ec_lang['mi_tau']='מתח<br />גזירה<br />תחתון<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />מורכב';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='הערות';
$ec_lang['mi_notes_1_term']='n מורכב';
$ec_lang['mi_notes_1_def']='מחשבון זה עוקב אחר המדריך ההתייחסות של HEC-RAS בחישוב n מורכב של אזור לפי Chow 1959, עמוד 136, משוואה 6-17 (לא 6-18).';
$ec_lang['mi_notes_2_term']='חיפוי סלע';
$ec_lang['mi_notes_2_def']='השתמש במחשבון תעלה טרפזואידית לפי Manning לתכנון חיפוי סלע. מחשבון זה מתאים יותר לחתכים טבעיים.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='זרימה בצינור — Manning';
$ec_lang['mpf_main_title']='מחשבון זרימה בצינור לפי Manning — חינם מקוון';
$ec_lang['mpf_main_desc']='זרימה אחידה בצינור לפי נוסחת Manning בשיפוע ועומק נתונים';
$ec_lang['mpf_spreadheet_notice']='עיין בגרסת הגיליון האלקטרוני של מחשבון זה';
$ec_lang['mpf_pipe_diameter']='קוטר הצינור';
$ec_lang['mpf_manningRoughness']='מקדם מאנינג';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../pressureslope.php">שיפוע התעלה (יתכן כי שווה לשיפוע הצינור)</a>';
$ec_lang['mpf_depth_ratio']='אחוז של (או היחס) עומק מלא (100% או 1 אם זרימה מלאה)';
$ec_lang['mpf_see_notes']='(ראה הערות)';
$ec_lang['mpf_flow']='ספיקה';
$ec_lang['mpf_velocity']='מהירות';
$ec_lang['mpf_velocity_head']='עומד הידראולי';
$ec_lang['mpf_flow_area']='חתך הזרימה';
$ec_lang['mpf_pipe_area']='שטח צינור, a0';
$ec_lang['mpf_area_ratio']='שטח יחסי, a/a0';
$ec_lang['mpf_wetted_perimeter']='ההיקף הרטוב';
$ec_lang['mpf_hydraulic_radius']='רדיוס הידראולי';
$ec_lang['mpf_top_width']='רוחב פני הנוזל';
$ec_lang['mpf_froude_number']='מספר פראוד';
$ec_lang['mpf_shear_stress']='מאמץ גזירה ממוצע (כוח גרר), tau';
$ec_lang['mpf_full_flow']='זרימה מלאה, Q0';
$ec_lang['mpf_full_flow_ratio']='יחס לזרימה מלאה, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>זהו הזרימה והעומק בתוך צינור <em>ארוך אינסופית</em>.</dt><dd>כדי לקבל את הזרימה לתוך הצינור ייתכן שיידרש גובה מים עליון גבוה הרבה יותר. הוסף לפחות 1.5 פעמים ראש המהירות כדי לקבל את גובה המים העליון, או <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ראה את המדריך הקצר שלי</a> לחישובי גובה מים עליון לתעלות ניקוז סטנדרטיות באמצעות HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='חשב y/d<sub>0</sub> עבור Q נתון';
$ec_lang['mpf_solve_desc']='תוך שימוש ב-D<sub>0</sub>, n ו-S<sub>0</sub> מטופס המחשבון, מוצא את ה-y/d<sub>0</sub> הנמוך ביותר עבור Q נתון.';
$ec_lang['mpf_solve_button']='חשב';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='אובדן גובה בצינור — Manning';
$ec_lang['mphl_main_title']='מחשבון אובדן גובה בצינור לפי Manning — חינם מקוון';
$ec_lang['mphl_main_desc']='אובדן גובה לפי נוסחת Manning בזרימה מלאה נתונה';
$ec_lang['mphl_pipe_length']='אורך הצינור,l';
$ec_lang['mphl_area']='שטח, A';
$ec_lang['mphl_total_junction_k']='חישוב סך כל מקדמי ההפסדים בצומת, k';
$ec_lang['mphl_friction_slope']='שיפוע חיכוך';
$ec_lang['mphl_friction_loss']='הפסד חיכוך';
$ec_lang['mphl_junction_loss']='הפסד בצומת';
$ec_lang['mphl_total_loss'] = 'סהכ הפסד';
$ec_lang['mphl_egl_1']='EGL מורד';
$ec_lang['mphl_egl_2']='EGL מעלה';
$ec_lang['mphl_hgl_2']='HGL מעלה בצינור (ראה הערות)';
$ec_lang['mphl_note_1']='<dl><dt>עבור כניסה פתוחה (תעלת ניקוז), יש לבדוק תנאי שליטה בכניסה.</dt><dd>1. HGL המעלה אינו יכול להיות נמוך מגובה זרימה נורמלית במעלה (ולא נמוך מהצינור!).</dd><dd>2. גובה המים העליון של תעלת ניקוז מיוצג טוב יותר על ידי EGL המעלה מאשר HGL המעלה.</dd><dd>3. ראה <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">את המדריך הקצר שלי</a> לחישובי גובה מים עליון פשוטים לתעלות ניקוז סטנדרטיות באמצעות HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='תעלה טרפזואידית — Manning';
$ec_lang['mtc_main_title']='מחשבון תעלה טרפזואידית לפי נוסחת Manning — חינם מקוון';
$ec_lang['mtc_main_desc']='זרימה אחידה בתעלה טרפזואידית לפי נוסחת Manning בשיפוע ועומק נתונים';
$ec_lang['mtc_bottom_width']='רוחב קרקעית, b';
$ec_lang['mtc_side_slope_1']='צד השיפוע 1, z1 (אופקי\אנכי)';
$ec_lang['mtc_side_slope_2']= 'צד השיפוע 2, z2 (אופקי\אנכי)';
$ec_lang['mtc_channel_slope']='שיפוע התעלה';
$ec_lang['mtc_flow_depth']='עומק הספיקה';
$ec_lang['mtc_bend_angle']='זווית כיפוף, β <a target="_blank" href="riprap-bend-angle.png" title="לחץ לתמונה">?</a> (לממדי ריפ-ראפ)';
$ec_lang['mtc_sgrock']='משקל סגולי של סלע, SG (2.65)';
$ec_lang['mtc_d50_in']='גודל סלע עיצוב, D50';
$ec_lang['mtc_n_strickler']='n לגודל סלע עיצוב לפי Strickler';
$ec_lang['mtc_n_blodgett']='n לגודל סלע עיצוב לפי Blodgett';
$ec_lang['mtc_n_bathurst']='n לגודל סלע עיצוב לפי Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett לעומת Bathurst';
$ec_lang['mtc_d50_bottom']='גודל אבן זוויתית נדרש לקרקעית, D50 (Isbash ו-MC) <span title="לפי Isbash (1936) ו-Maricopa County, אריזונה, ארה"ב." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='גודל אבן זוויתית נדרש לצד 1, D50 (Isbash ו-MC) <span title="לפי Isbash (1936) ו-Maricopa County, אריזונה, ארה"ב." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='גודל אבן זוויתית נדרש לצד 2, D50 (Isbash ו-MC) <span title="לפי Isbash (1936) ו-Maricopa County, אריזונה, ארה"ב." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='גודל אבן זוויתית נדרש, D50 (Maynord, Ruff ו-Abt 1989)';
$ec_lang['mtc_d50_searcy']='גודל אבן זוויתית נדרש, D50 (Searcy 1967)';
$ec_lang['mtc_vel_check']='בדיקת מהירות';
$ec_lang['mtc_vel_ok']='המהירות סבירה להנחות זרימה אחידה.';
$ec_lang['mtc_vel_high']='מהירות גבוהה — בדוק הפסדי מעברים, אנרגיה זמינה ופטיש מים.';
$ec_lang['mtc_vel_low']='מהירות נמוכה — סיכון להשתקעות.';
$ec_lang['mtc_vel_ok_short']='בסדר';
$ec_lang['mtc_vel_high_short']='גבוה';
$ec_lang['mtc_vel_low_short']='נמוך';
$ec_lang['mtc_note_1']='<dl><dt>איטרציה אוטומטית לתכנון גודל סלע וגסות</dt><dd>בחר לחצן בחירת גסות (BB מומלץ) ולחצן בחירת גודל סלע עיצוב (Isbash מומלץ). כוונן את העומק ומקדם הביטחון של גודל הסלע כדי לקבל את הזרימה הרצויה עם גודל סלע שלם. בכל שינוי ערך קלט מתרחשת מחזור איטרציה: 1. הגסות מחושבת מגודל סלע העיצוב. 2. חישוב הגסות המבוקש מועתק לגסות הקלט. 3. זרימת התעלה וגודל הסלע הנדרש מחושבים. 4. גודל סלע העיצוב מותאם. 5. חזרה עד שהשגיאה בגודל סלע העיצוב קטנה מאד.</dd><dt>מחשבון בסיסי (ללא איטרציה)</dt><dd>הכנס את ערך הגסות הרצוי. התעלם מאזור קלט גודל סלע העיצוב.</dd></dl>';
$ec_lang['mtc_note_2_term']='בדיקת מהירות';
$ec_lang['mtc_note_2_def']='מהירות גבוהה משמעה אנרגיה סגולית גבוהה הנובעת מנפילה זמינה. אנרגיה זו עשויה ללכת לאיבוד במהירות באזורי התרחבות, בעקומות או בחסמים. יש לוודא שהדבר סביר עבור האתר.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='זרימת מפל — פשוטה';
$ec_lang['ws_main_title']='מחשבון זרימת מפל עם כתר רחב פשוט — חינם מקוון';
$ec_lang['ws_main_desc']='מחשבון זרימת מפל עם כתר רחב פשוט';
$ec_lang['ws_weirLength']='אורך המפל, l';
$ec_lang['ws_headWaterHeight']='גובה מים עליונים, h';
$ec_lang['ws_weirCoefficient']='מקדם מפל, Cw';
$ec_lang['ws_notes_heading']='הערות';
$ec_lang['ws_notes_we_term']='משוואת המפל';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='זרימת מפל — לא סדיר';
$ec_lang['wi_main_title']='מחשבון זרימת מפל לא סדיר עם עומק משתנה — חינם מקוון';
$ec_lang['wi_main_desc']='מחשבון זרימת מפל לא סדיר';
$ec_lang['wi_headWaterelevation']='גובה מפלס מים עליונים';
$ec_lang['wi_weirPoints']='נקודות מפל';
$ec_lang['wi_station']='תחנה<br />(מרחק)';
$ec_lang['wi_elevation']='גובה';
$ec_lang['wi_pondingHeight']='גובה הצטברות מים';
$ec_lang['wi_incrementalFlow']='ספיקה מצטברת חלקית';
$ec_lang['wi_cumulativeFlow']='ספיקה מצטברת כוללת';
$ec_lang['wi_save_and_calculate']='שמור וחשב';
$ec_lang['wi_notes_we_term']='משוואת המפל';
$ec_lang['wi_notes_we_def']='q = אם (אורך = 0) אז 0; אחרת אם (שיפוע=0) אז cw*length*d<sub>0</sub><sup>1.5</sup>; אחרת cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) כאשר d<sub>1</sub> ו-d<sub>0</sub> תמיד חיוביים או אפס';
// Orifice Flow
$ec_lang['or_main_menu']='זרימה דרך פתח';
$ec_lang['or_main_title']='מחשבון זרימה דרך פתח - חינם';
$ec_lang['or_main_desc']='זרימה דרך פתח — חופשית או טבועה';
$ec_lang['or_shape']='צורת הפתח';
$ec_lang['or_shape_circular']='עגול';
$ec_lang['or_shape_rectangular']='מלבני';
$ec_lang['or_diameter']='קוטר או גובה, D <span title="Diameter for circular; height for rectangular" class="ec-tip">?</span>';
$ec_lang['or_width']='רוחב, W <span title="Rectangular openings only" class="ec-tip">?</span>';
$ec_lang['or_invert']='גובה היסוד <span title="Bottom of opening" class="ec-tip">?</span>';
$ec_lang['or_hwe']='גובה מפלס מים עליון';
$ec_lang['or_twe']='גובה מפלס מים תחתון';
$ec_lang['or_cd']='מקדם הספיקה, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='גובה הצנטרואיד';
$ec_lang['or_head']='עומק יעיל, h';
$ec_lang['or_area']='שטח הפתח, A';
$ec_lang['or_flow']='ספיקה, Q';
$ec_lang['or_velocity']='מהירות, v';
$ec_lang['or_regime']='בדיקת משטר הזרימה';
$ec_lang['or_regime_valid']='זרימה חופשית — משטר פתח תקין ✓';
$ec_lang['or_regime_submerged']='פתח טבוע (TWE מעל לצנטרואיד) — תקין ✓';
$ec_lang['or_regime_warn']='אזהרה: מפלס עליון מתחת לגג הפתח — לא משטר פתח';
$ec_lang['or_regime_twe_above_hwe']='אזהרה: מפלס מים תחתון (TWE) גבוה ממפלס מים עליון (HWE) — בדוק קלטים';
$ec_lang['or_notes_1_term']='משוואת הפתח';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). זרימה חופשית: h = HWE − צנטרואיד. זרימה טבועה (TWE מעל לתחתית): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='משטר הפתח';
$ec_lang['or_notes_2_def']='משוואות זרימה דרך פתח חלות כאשר המפלס העליון גבוה מגג הפתח. כאשר המפלס נמוך מהגג, יש להשתמש במשוואת מפל.';
$ec_lang['or_notes_3_term']='מקדם הספיקה';
$ec_lang['or_notes_3_def']='C<sub>d</sub> נע בין 0.60 ל-0.65 לפתחים עם קצה חד. כניסות מעוגלות או שקועות מקבלות ערכים שונים. ראה <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> או מדריך הידרולוגיית HEC-RAS.';
$ec_lang['or_notes_4_term']='טביעה';
$ec_lang['or_notes_4_def']='כאשר TWE גבוה מתחתית הפתח, המחשבון מיישם אוטומטית את משוואת הפתח הטבוע עם h = HWE − TWE. כאשר TWE שווה לתחתית הפתח או נמוך ממנה, מניחים זרימה חופשית ו-h = HWE − צנטרואיד.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='הידרו-כוח זעיר';
$ec_lang['mhp_main_title']='מחשבון הידרו-כוח זעיר חינמי מקוון';
$ec_lang['mhp_main_desc']='מחשבון הספק הידרו-כוח זעיר עם זרימה טבעית בנהר';
$ec_lang['mhp_flow']='ספיקה, Q';
$ec_lang['mhp_gross_head']='גובה ברוטו, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='קוטר צינור הלחץ, D';
$ec_lang['mhp_length']='אורך צינור הלחץ, L';
$ec_lang['mhp_roughness']='גסות הצינור, e';
$ec_lang['mhp_km']='מקדם אובדן משני, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='צמיגות קינמטית, ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='יעילות מתקן, η (0–1)';
$ec_lang['mhp_velocity']='מהירות זרימה, v';
$ec_lang['mhp_vel_check']='בדיקת מהירות';
$ec_lang['mhp_f']='מקדם חיכוך, f';
$ec_lang['mhp_hf']='אובדן לחץ בחיכוך, h<sub>f</sub>';
$ec_lang['mhp_hm']='אובדן משני, h<sub>m</sub>';
$ec_lang['mhp_hl']='סך אובדן צינור הלחץ, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='בדיקת אובדן לחץ';
$ec_lang['mhp_hnet']='גובה נטו, H<sub>net</sub>';
$ec_lang['mhp_power']='הספק יציאה, P';
$ec_lang['mhp_annual_kwh']='אנרגיה שנתית בקיבולת 100%';
$ec_lang['mhp_vel_ok']='1–3 מ/ש — בטווח היעד ✓';
$ec_lang['mhp_vel_low']='מהירות נמוכה — סיכון של שקוע משקעים וסחיפת אוויר.';
$ec_lang['mhp_vel_high']='מהירות גבוהה — בדוק הפסדי מעברים, אנרגיה זמינה ופטיש מים.';
$ec_lang['mhp_vel_ok_short']='בסדר';
$ec_lang['mhp_vel_high_short']='גבוה';
$ec_lang['mhp_vel_low_short']='נמוך';
$ec_lang['mhp_hl_ok']='בתוך יעד 10% ✓';
$ec_lang['mhp_hl_warn']='חורג מיעד 10% — שקול צינור גדול יותר ⚠';
$ec_lang['mhp_hl_bad']='חורג מ-20% — ממד מחדש את הצינור';
$ec_lang['mhp_notes_1_term']='אובדן לחץ';
$ec_lang['mhp_notes_1_def']='סך אובדן צינור הלחץ h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, כאשר h<sub>f</sub> = f(L/D)(v²/2g) הוא אובדן חיכוך לפי דארסי-ויסבאך ו-h<sub>m</sub> = k<sub>m</sub>·v²/2g מכסה כניסה, עקומות ושסתומים. גובה נטו H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='מהירות';
$ec_lang['mhp_notes_2_def']='יעד 1–3 מ/ש. מתחת ל-1 מ/ש מגדיל את הצינור מעל הצורך; מעל 3 מ/ש מגביר אובדן חיכוך וסיכון לפגיעת פטיש המים.';
$ec_lang['mhp_notes_3_term']='יעד אובדן לחץ';
$ec_lang['mhp_notes_3_def']='אובדן צינור הלחץ מתחת ל-10% מהגובה הברוטו הוא בדרך כלל כלכלי. האיזון האופטימלי בין עלות הצינור לאנרגיה שאבדה נמצא לרוב סביב 4–6% באתרי חשמל בעלי ערך גבוה.';
$ec_lang['mhp_notes_4_term']='אובדן משני k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='ערכים אופייניים: כניסה חדה 0.5, כל עיקול 45° בין 0.2–0.3, ברז שער (פתוח לחלוטין) 0.1, שסתום פרפר 0.2. סכום כל האבזרים הוא k<sub>m</sub> הכולל. ברירת המחדל 1.5 מניחה כניסה אחת ושני עיקולים.';
$ec_lang['mhp_notes_5_term']='גסות הצינור e';
$ec_lang['mhp_notes_5_def']='גסות מוחלטת אופיינית: פלדה (חדשה) 0.046 מ"מ, פלדה (משומשת) 0.15 מ"מ, HDPE 0.003 מ"מ, PVC/uPVC 0.0015 מ"מ, בטון 0.3–3 מ"מ. HDPE נפוץ בצינורות לחץ קטנים למיקרו-הידרו.';
$ec_lang['mhp_notes_6_term']='יעילות';
$ec_lang['mhp_notes_6_def']='יעילות המתקן האופיינית &eta; נעה בין 0.70 ל-0.85 לטורבינות Pelton ורוחב-זרימה הנפוצות במיקרו-הידרו. השתמש ב-0.75 כאומדן ראשוני שמרני.';
$ec_lang['mhp_notes_7_term']='אנרגיה שנתית';
$ec_lang['mhp_notes_7_def']='האנרגיה השנתית מניחה פעולה מתמשכת בזרימה מלאה (8760 שעות לשנה). התפוקה בפועל תהיה נמוכה יותר בשל שינויי זרימה עונתיים, זמן השבתה לתחזוקה ומקדם עומס.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='זמן ריקון פתח';
$ec_lang['odt_main_title']='מחשבון זמן ריקון פתח — בריכה, אגן או מיכל — חינם מקוון';
$ec_lang['odt_main_desc']='זמן ריקון פתח בריכת איגום או אגן — שיטת נפח קוני';
$ec_lang['odt_h1_elev']='WSE התחלתי <span title="Starting water surface elevation" class="ec-tip">?</span>';
$ec_lang['odt_a1']='שטח התחלתי, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='WSE סופי';
$ec_lang['odt_h_orifice']='גובה צנטרואיד הפתח';
$ec_lang['odt_a0']='שטח בגובה הפתח, A<sub>0</sub>';
$ec_lang['odt_a_ending']='שטח סופי, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='בדיקת גובה סופי';
$ec_lang['odt_h2_ok']='הגובה הסופי מעל לחלק העליון של הפתח ✓';
$ec_lang['odt_h2_warn']='אזהרה: הגובה הסופי שווה או נמוך מחלק עליון של הפתח (צנטרואיד + D/2)';
$ec_lang['odt_d']='קוטר פתח D <span title="Diameter (circular) or height (rectangular)" class="ec-tip">?</span>';
$ec_lang['odt_w']='רוחב פתח, W <span title="Rectangular only" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='זמן ריקון (s)';
$ec_lang['odt_t_min']='זמן ריקון (min)';
$ec_lang['odt_t_hr']='זמן ריקון (hr)';
$ec_lang['odt_t_day']='זמן ריקון (days)';
$ec_lang['odt_notes_1_term']='נוסחה';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) נותן את זמן הריקון מגובה ראש H עד לפתח. זמן ריקון = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), כאשר H<sub>1</sub> = גובה התחלתי − גובה הפתח, H<sub>2</sub> = גובה סופי − גובה הפתח.';
$ec_lang['odt_notes_2_term']='שיטה';
$ec_lang['odt_notes_2_def']='שיטת הנפח הקוני מדמה את הבריכה או האגן כחתך קוני בין שטח התחלתי A<sub>1</sub> במפלס המים הראשוני לבין שטח A<sub>0</sub> בגובה צנטרואיד הפתח. A<sub>2</sub>, שטח הבריכה בגובה הסופי, מחושב באינטרפולציה מ-A<sub>1</sub> ו-A<sub>0</sub> לפי מודל החתך הקוני. זמן הריקון מגובה התחלתי לסופי שווה לזמן הריקון הכולל מ-H<sub>1</sub> לפתח פחות זמן הריקון הנותר מ-H<sub>2</sub> לפתח.';
$ec_lang['odt_h1']='ראש התחלתי, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='זרימה מקסימלית, Q<sub>max</sub>';
$ec_lang['odt_vol']='נפח מרוקן';
$ec_lang['odt_sketch_start']='התחלה';
$ec_lang['odt_sketch_end']='סיום';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='רוחב מגדה לגדה';
$ec_lang['essc_mcr']='רדיוס עיקול מינימלי';
$ec_lang['essc_q']='ספיקה, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='השקיה';
$ec_lang['irr_main_title']='מחשבוני מדידת ספיקת השקיה חינמיים באינטרנט';
$ec_lang['irr_main_desc']='מדידת ספיקת השקיה — מפלי מים ופתחים';
$ec_lang['irr_intro_html']='<p>מעביר מים ופתחים הם הכלים השטחיים הסטנדרטיים למדידת זרימת מים במערכות השקיה. בחרו את המחשבון המתאים למבנה שלכם:</p>';
$ec_lang['irr_card_weir_uniform_head']='מעביר מים — סף רחב (רוחב אחיד)';
$ec_lang['irr_card_weir_uniform_desc']='מדדו את הזרימה מעל לכתר סכר הסטייה, מבנה הבקרה או לוח המעביר. הזינו את אורך המעביר ועומק המים מעל הסף.';
$ec_lang['irr_card_weir_irregular_head']='מעביר מים — פרופיל לא סדיר';
$ec_lang['irr_card_weir_irregular_desc']='השתמשו כאשר כתר המעביר אינו בגובה אחיד — שפכי חירום טבעיים, מבני נפילה ברוחב משתנה, או מבני בקרה רב-מקטעיים.';
$ec_lang['irr_card_orifice_head']='פתח — שער ראשי או חיבור צינור';
$ec_lang['irr_card_orifice_desc']='מדדו את הזרימה דרך שער הזזה, חיבור צינור, או פתח תעלת ניקוז. מטפל אוטומטית הן בשפיכה חופשית והן בתנאים מוצפים (לחץ נגדי מהזרם התחתון).';
$ec_lang['irr_card_canal_head']='תכנון & ניתוח תעלה';
$ec_lang['irr_card_canal_desc']='תכננו או בדקו תעלת השקיה בעזרת נוסחת Manning. השתמשו במחשבון הטרפזי לתעלות חדשות; במחשבון הלא סדיר לחתכים טבעיים או מבנויים קיימים.';
$ec_lang['irr_card_seepage_head']='דליפת תעלה & יעילות הולכה';
$ec_lang['irr_card_seepage_desc']='אמדו את אובדן הדליפה ממקטע תעלה באמצעות מדידות ספיקת כניסה ויציאה. חשבו יעילות הולכה ואובדן מים שנתי כדי לסייע בתעדוף השקעות בריפוד.';
$ec_lang['irr_quickref_html']='<h3>מדריך מהיר</h3><dl><dt>סכר הסטייה או מבנה בקרה</dt><dd>מדדו את עומק המים מעל לכתר המעביר. השתמשו ב<a href="Weir-Flow-Simple.php">מעביר פשוט</a> עבור כתר אחיד, או ב<a href="Weir-Flow-Irregular.php">מעביר לא סדיר</a> עבור כתר בעל פרופיל או ממדרגות.</dd><dt>שער ראשי או חיבור צינור</dt><dd>מדדו את מפלס המים בזרם העליון והתחתון (או גובה תחתית הצינור בשפיכה חופשית). השתמשו ב<a href="Orifice.php">זרימת פתח</a>. לצינור עגול D = קוטר הצינור; לשער מלבני הזינו רוחב W וגובה D.</dd><dt>זמן ריקון מאגר או בריכה</dt><dd>השתמשו ב<a href="Orifice-Drain-Time.php">זמן ניקוז דרך פתח</a> להערכת הזמן הדרוש להורדת מפלס בריכה או מאגר דרך פתח תחתי — שימושי לתכנון אחסון מי השקיה.</dd><dt>תקני שטח</dt><dd>משוואות הזרימה של מעביר ופתח המשמשות כאן תואמות את הנהלים של USBR <em>Water Measurement Manual</em> (מהדורה 3), הנדרשים בדרך כלל על ידי מנהלי מים ומחוזות השקיה.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='רווח פולטים, S<sub>e</sub>';
$ec_lang['ip_sl']='רווח צדדי, S<sub>l</sub>';
$ec_lang['ip_n_e']='פולטים לצינור צדדי, n<sub>e</sub>';
$ec_lang['ip_n_l']='צינורות צדדיים לגוש, n<sub>l</sub>';
$ec_lang['ip_d']='עומק יישום יעד, d';
$ec_lang['ip_a_e']='שטח לפולט, A<sub>e</sub>';
$ec_lang['ip_pr']='קצב יישום, PR';
$ec_lang['ip_q_lat']='ספיקה לצינור צדדי, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='ספיקת גוש, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='זמן הפעלה (שעות)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='דליפת תעלה';
$ec_lang['cs_main_title']='מחשבון חינמי מקוון לאובדן דליפה בתעלה ויעילות הולכה';
$ec_lang['cs_main_desc']='אובדן דליפה בתעלה & יעילות הולכה — שיטת מדידת יניקה-פליטה';
$ec_lang['cs_Q_in']='זרימת כניסה, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='זרימת יציאה, Q<sub>out</sub>';
$ec_lang['cs_L']='אורך המקטע, L';
$ec_lang['cs_wp']='היקף רטוב, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='קצב אובדן הדליפה, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='בדיקת מדידה';
$ec_lang['cs_pct_loss']='שבר שאבד';
$ec_lang['cs_Ec']='יעילות הולכה, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='דירוג יעילות';
$ec_lang['cs_Vol_day']='נפח יומי שאבד';
$ec_lang['cs_Vol_year']='נפח שנתי שאבד';
$ec_lang['cs_Q_loss_per_L']='אובדן ליחידת אורך, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='ערך מים';
$ec_lang['cs_lining_cost']='עלות ריפוד';
$ec_lang['cs_Ec_target']='יעילות יעד, E<sub>c,target</sub> <span title="יעד יעילות הולכה לאחר ריפוד; שבר 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='שטח ריפוד, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='ערך שנתי שאבד';
$ec_lang['cs_annual_value_recovered']='ערך שנתי מוחזר';
$ec_lang['cs_lining_total_cost']='סך עלות ריפוד';
$ec_lang['cs_payback_years']='תקופת החזר <span title="Simple payback = total lining cost ÷ annual value recovered" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — דליפה זוהתה ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — אין אובדן מדיד';
$ec_lang['cs_loss_negative']='אזהרה: Qout > Qin — בדוק את המדידות ⚠';
$ec_lang['cs_Ec_good']='טוב — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='סביר — Ec 60–80%';
$ec_lang['cs_Ec_poor']='גרוע — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='שיטה';
$ec_lang['cs_notes_1_def']='שיטת מדידת יניקה-פליטה מאמדת דליפה על ידי מדידת ספיקה בראש ובזנב מקטע התעלה: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. יעילות הולכה E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. הנפח השנתי מניח הפעלה רצופה בזרימה מלאה; האובדן בפועל נמוך יותר בתעלות עונתיות או בזרימה חלקית.';
$ec_lang['cs_notes_2_term']='דירוגי יעילות';
$ec_lang['cs_notes_2_def']='תעלות עפר לא מרופדות אופייניות: E<sub>c</sub> = 60–80%. תעלות עפר מתוחזקות היטב: 75–85%. תעלות מרופדות בבטון: 90–98%. אובדן דליפה מעל 30% מהספיקה הנכנסת מצדיק לרוב השקעה בריפוד. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='ריפוד החזרה';
$ec_lang['cs_notes_3_def']='הזינו ערך המים ועלות ריפוד בכל מטבע עקבי. שטח ריפוד = אורך מקטע × היקף רטוב — היקף הרטוב של חתך התעלה בעומק הזרימה הנמדד (רוחב תחתון ועל שתי המדרונות הרטובים). הערך השנתי שנשמר מניח שתעלה מרופדת משיגה את יעילות הולכה המטרה ברציפות. תקופת החזרה בפועל תהיה ארוכה יותר לתעלות עונתיות או אם הריפוד אינו מגיע ליעילות המטרה.';
$ec_lang['cs_notes_4_term']='מקור';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, מהדורה 3 (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='אודות';
$ec_lang['install_main_menu']='התקן';
$ec_lang['install_main_title']='התקן את EngCalcs';
$ec_lang['install_main_desc']='הוסף למכשיר שלך לשימוש לא מקוון';
$ec_lang['contact_main_menu']='צור קשר';
$ec_lang['about_main_title']='אודות מחשבוני ההנדסה HawsEDC';
$ec_lang['about_main_desc']='מטרה, קוד פתוח ותרומה';
$ec_lang['about_body_html']='<h3>שליחות</h3><p>מחשבוני ההנדסה של HawsEDC קיימים לשרת מהנדסים ועובדי שטח ברחבי העולם — ובמיוחד אלה הפועלים באזורים הסובלים מחוסר מים, מחסור במשאבים, או חסרי שירות מספק. כלים אלה הם חלק משליחות הומניטרית רחבה יותר: לומר לכל אדם בדרך המעשית והאפקטיבית ביותר שהוא אהוב ויקיר לנצח, שאין לו מה לפחד, ושהוא לא ישחית הכל.</p><p>המחשבונים הם הכלי. היעד הוא עולם נטול סבל.</p><h3>רישיון קוד פתוח</h3><p>כל הקוד מופץ תחת <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">רישיון GNU הציבורי הכללי גרסה 3.0 ומעלה</a> — חופשי כמשמעות החופש. תוכלו להשתמש, ללמוד, לשנות ולהפיץ את הקוד תחת אותם תנאים.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>קוד מקור</h3><p>קוד המקור המלא זמין לציבור ב-Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>תוכלו לעיין בקוד, לדווח על בעיות, או לפצל את המאגר שם.</p><h3>תרומה</h3><p>בקשות משיכה מתקבלות בברכה. דרכים לתרום:</p><ul><li><strong>תרגומים</strong> — שפרו או הוסיפו שפה. פתחו בקשת משיכה עם שינויים בקובץ <code>lib/lang.ec.??.php</code> הרלוונטי.</li><li><strong>דיווח על באגים</strong> — השתמשו בטופס המשוב בכל עמוד מחשבון, או דווחו על בעיה ב-Bitbucket.</li><li><strong>מחשבונים חדשים</strong> — רעיונות לכלי הנדסה הידראולית המשרתים עובדי שטח ואנשי מקצוע בהשקיה מתקבלים בברכה מיוחדת. ראו את מדריך המפתחים <code>CLAUDE.md</code> במאגר.</li><li><strong>אירוח</strong> — אם תוכלו לשקף מחשבונים אלה לאזור בעל קישוריות מוגבלת, אנא צרו קשר.</li></ul><h3>שימוש ללא חיבור לאינטרנט</h3><p>המחשבונים האלה פועלים כאפליקציית ווב מתקדמת (PWA). בקרו בכל עמוד מחשבון כאשר אתם מחוברים לאינטרנט, והדפדפן שלכם יאחסן אוטומטית את כל המחשבונים. לאחר מכן כל המחשבונים יפעלו ללא אינטרנט — אין צורך בחיבור.</p><p>ב-Android או iOS, השתמשו באפשרות "הוסף למסך הבית" בדפדפן שלכם כדי להתקין את EngCalcs כאפליקציה במכשירכם. במחשב שולחני, חפשו את סמל ההתקנה בשורת הכתובת של הדפדפן.</p><p>תוכלו גם לשמור כל מחשבון בנפרד באמצעות תפריט "שמור בשם…" בדפדפן שלכם לשימוש חד-פעמי ללא חיבור לאינטרנט.</p><h3>יצירת קשר</h3><p>Tom Haws — מהנדס הידראולי ומחבר מחשבונים אלה.<br />השתמשו בטופס המשוב בכל עמוד מחשבון, או גשו לקוד המקור ב<a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='צור קשר עם HawsEDC';
$ec_lang['contactSendMessage']='שלח הודעה ל-Tom Haws';
$ec_lang['contactYourName']='שמך:';
$ec_lang['contactYourEmail']='כתובת הדוא"ל שלך:';
$ec_lang['contactSubject']='נושא:';
$ec_lang['contact_message']='הודעה:';
$ec_lang['contactSpamPrefix']='חמש ועוד אחת שווה';
$ec_lang['contactSpamPostfix']='(אנא כתוב במילים. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='שלח הודעה';
$ec_lang['contact_success']='תודה שלקחת את הזמן לכתוב.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='תכנון מגלשת סלעים (Robinson)';
$ec_lang['rc_main_title']='מחשבון חינמי לתכנון מגלשת סלעים — Robinson (1998)';
$ec_lang['rc_main_desc']='קביעת גודל ריפרפ במגלשת סלעים — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='שיפוע קרקעית המגלשה, S<sub>0</sub>';
$ec_lang['rc_qt']='ספיקה יחידתית כוללת, q<sub>t</sub> <span title="זרימה ליחידת רוחב בכניסת המגלשה. לתעלה ברוחב תחתון B עם ספיקה כוללת Q, השתמשו ב-q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='תכולת נקבים בריפרפ, n<sub>p</sub>';
$ec_lang['rc_sg']='משקל סגולי של הסלע, sg <span title="גרניט או בזלט כתוש טיפוסי ≈ 2.65. טווח תקף לפי Robinson: 2.54 עד 2.82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='סטיית הדרגות SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="סטיית תקן של הדרגות. סלע אחיד ≈ 1.25. טווח תקף לפי Robinson: 1.15 עד 1.47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='עומק נורמלי בתעלת הכניסה, y<sub>n</sub> <span title="הצטברות מים (Hp > yn) רצויה — מפחיתה סחיפה מעלה. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='גודל סלע חציוני נדרש, D<sub>50</sub> <span title="מש׳ 1 (S0 < 0.10) או מש׳ 2 (0.10-0.40). תקף: D50 בין 15 ל-278 מ״מ, S0 בין 0.02 ל-0.40. מחוץ לטווח: ערכים מוחצנים." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='משוואה שיושמה';
$ec_lang['rc_sg_check']='בדיקת משקל סגולי';
$ec_lang['rc_SD_check']='בדיקת סטיית דרגות SD';
$ec_lang['rc_sg_ok']   ='sg בטווח התקף (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='אזהרה: sg < 2.54 — מתחת לטווח Robinson';
$ec_lang['rc_sg_high'] ='אזהרה: sg > 2.82 — מעל טווח Robinson';
$ec_lang['rc_SD_ok']   ='SD בטווח התקף (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='אזהרה: SD < 1.15 — מתחת לטווח Robinson';
$ec_lang['rc_SD_high'] ='אזהרה: SD > 1.47 — מעל טווח Robinson';
$ec_lang['rc_layer']='עובי שכבת הסלע (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='רדיוס עקמת הכתר העליון (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='אורך קשת עקמת הכתר העליון';
$ec_lang['rc_apron_length']='אורך מצוע יציאת המים (15 × D<sub>50</sub>) <span title="נדרש לתמיכה מבנית בסלעי המגלשה. «הגובה המינימלי של המים הנגדיים הנוצר כתוצאה מהתעלה היוצאת ותנגודת הערוץ המורד מספיק להבטחת יציבות הריפרפ במקטע המוצא.» (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='מקדם גסות Manning במגלשה, n';
$ec_lang['rc_Vm']='מהירות דרך מעטפת הסלע, V<sub>m</sub> <span title="חלק מ-qt הזורם דרך נקבוביות הסלע. השאר qs זורם על פני השטח. ברירת מחדל np = 0.45 לסלע כתוש זוויתי." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='ספיקה יחידתית דרך המעטפת, q<sub>m</sub>';
$ec_lang['rc_qs']='ספיקה יחידתית עילית, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='עומק הזרימה מעל פני הריפרפ, d';
$ec_lang['rc_Hp']='גובה עמוד מים בכניסה, H<sub>p</sub> <span title="הצטברות מים (Hp > yn) רצויה — מפחיתה סחיפה מעלה. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='בדיקת עמידת מים בכניסה';
$ec_lang['rc_pond_ok']  ='Hp > yn — עמידת מים במעלה הזרם ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — אין עמידת מים — בדוק את הכניסה לסחיפה';
$ec_lang['rc_eq1']='מש׳ 1 (S0 < 0.10) — שיפוע מתון';
$ec_lang['rc_eq2']='מש׳ 2 (0.10 ≤ S0 ≤ 0.40) — שיפוע תלול';
$ec_lang['rc_eq_warn_low']='אזהרה: S0 < 0.02 — מתחת לטווח אימות Robinson';
$ec_lang['rc_eq_warn_high']='אזהרה: S0 > 0.40 — מעל טווח אימות Robinson';
$ec_lang['rc_notes_1_term']='משוואות לקביעת גודל הסלע';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) פיתחו שתי משוואות אמפיריות לגודל ריפרפ החציוני D<sub>50</sub> על בסיס שיפוע המגלשה והספיקה היחידתית. משוואה 1 חלה לשיפועים מתונים (S<sub>0</sub> < 0.10); משוואה 2 חלה לשיפועים תלולים (0.10 ≤ S<sub>0</sub> ≤ 0.40). שתי המשוואות דורשות q<sub>t</sub> ביחידות m²/s ומחזירות D<sub>50</sub> במ״מ. הטווח המאומת הוא 0.02 ≤ S<sub>0</sub> ≤ 0.40.';
$ec_lang['rc_notes_2_term']='ספיקה יחידתית';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> היא הספיקה היחידתית הכוללת בכתר המגלשה (ספיקה כוללת ליחידת רוחב). לתעלה ברוחב תחתון B הנושאת ספיקה כוללת Q, יש לאמוד q<sub>t</sub> ≈ Q / B, או לחשב זאת מתנאי העומק הקריטי בכניסת המגלשה.';
$ec_lang['rc_notes_3_term']='זרימה דרך מעטפת הסלע';
$ec_lang['rc_notes_3_def']='חלק מהזרימה הכוללת עובר דרך נקבוביות ריפרפ הסלע (ספיקת מעטפת q<sub>m</sub>); השאר זורם על פני הסלע (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). עומק הזרימה d מחושב ממשוואת Manning המוחלת על ספיקת פני השטח q<sub>s</sub> תוך שימוש בגסות המגלשה n. נקבוביות ברירת מחדל n<sub>p</sub> = 0.45 אופיינית לסלע כתוש זוויתי.';
$ec_lang['rc_notes_5_term']='טווח גודל סלע תקף';
$ec_lang['rc_notes_5_def']='המשוואות פותחו בטווח D<sub>50</sub> שבין 15 מ״מ ל-278 מ״מ. תוצאות מחוץ לטווח זה הן החצנה ויש להשתמש בהן בשיקול דעת הנדסי נוסף.';
$ec_lang['rc_notes_6_term']='גובה מצוע המוצא';
$ec_lang['rc_notes_6_def']='גובה ראש הסלעים במקטע המוצא צריך להיות שווה או נמוך מגובה קרקעית הערוץ המורד. אם הוא גבוה יותר, סלעי המוצא יהיו בלתי יציבים.';
$ec_lang['rc_notes_7_term']='בדיקת הצטברות מים בכניסה';
$ec_lang['rc_notes_7_def']='כאשר העומק הנורמלי בתעלת הכניסה קטן מגובה עמוד המים (H<sub>p</sub>) הנדרש להעברת q<sub>t</sub>, נוצרת זרימה מוגבלת או הצטברות מים מעלה לפני מצוע הכניסה. זה בדרך כלל מקובל — הצטברות מים מפחיתה מהירות ומונעת סחיפה מעלה. לבדיקה: השתמשו במחשבון ספיקת מעביר כדי למצוא H<sub>p</sub> עבור q<sub>t</sub> ורוחב הכתר הנתונים, והשוו לעומק הנורמלי של תעלת הכניסה. אם H<sub>p</sub> עולה על העומק הנורמלי, תהיה הצטברות מים.';
$ec_lang['rc_notes_4_term']='מקור';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS מפרסמת גם <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">גיליון Excel</a> המבוסס על אותה שיטה.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'מסנן';
$ec_lang['rc_sketch_top_crest_curve'] = 'עקומת הרכס';
$ec_lang['rc_sketch_outlet_apron']    = 'סינר יציאה';
$ec_lang['rc_sketch_radius']          = 'רדיוס';
// Irrigation Pressure (ip_)
$ec_lang['ip_main_menu']='לחץ השקיה';
$ec_lang['ip_main_title']='מחשבון חינמי מקוונת לחץ השקיה & הוודות חלוקה';
$ec_lang['ip_main_desc']='בדיקת לחץ ענף וניתוח הוודות';
$ec_lang['ip_h_supply']='לחץ אספקה';
$ec_lang['ip_elev_supply']='גובה אספקה, z<sub>אספקה</sub>';
$ec_lang['ip_q_design']='ספיקת תכנון פולט, q<sub>תכנון</sub>';
$ec_lang['ip_h_design']='לחץ תכנון פולט';
$ec_lang['ip_x']='מעריך פריקת פולט, x <span title="0.5 לפולטים רגילים שלא מתקזזים; קרוב ל-0 לפולטים המתקזזים ללחץ" class="ec-tip">?</span>';
$ec_lang['ip_reach_table_title']='נתיב בדיקה';
$ec_lang['ip_group_reach']='קטע';
$ec_lang['ip_group_upstream']='זרם מעלה';
$ec_lang['ip_group_downstream']='זרם מורד';
$ec_lang['ip_group_loss']='הפסד';
$ec_lang['ip_is_lateral']='צדדי <span title="סימן: קטע זה הוא חלק של הצדדית בדיקה, שנשחררה על ידי פולטים בודדים. לא סימן: קטע זה הוא ראשית, העוברת רק ספיקה לצדדיות שאינן בנתיב הבדיקה." class="ec-tip">?</span>';
$ec_lang['ip_count']='פולטים <span title="שורות צדדיות: פולטים בקטע זה בלבד. שורות ראשיות: סך הפולטים בצדדיות שאינן בנתיב הבדיקה המתחנכות מקטע זה. עבור הקטע ממש בנקודת ההסתעפות של הצדדית בעצמה, זה גם כולל צדדיות כלשהן עדיין הלאה על הראשית, או חולקות את אותה צומת (למשל צדדית מצד הפוך) — זרימתן מתחנכת מקטע זה גם כן." class="ec-tip">?</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_e']='e <span title="גובה חספוס Darcy-Weisbach" class="ec-tip">?</span>';
$ec_lang['ip_km']='K<sub>m</sub> <span title="מקדם הפסד משני כללי עבור יציאות/שסתומים/צימודים של קטע זה (מוצע מינימום &ge;0.5)" class="ec-tip">?</span>';
$ec_lang['ip_elev_ds']='גובה מורד <span title="גובה סיום קטע זה בזרם מורד. אופציונלי בשורות פנימיות (חדש = שטוח / זהה לצומת למעלה אם השדה ריק). נדרש בשורה אחרונה: ערך זה הוא גובה הפולט האחרון, הקובע ישירות את לחץ האספקה הנדרש." class="ec-tip">?</span>';
$ec_lang['ip_elev_ds_missing_warn']='גובה פולט אחרון (שורה אחרונה) הוסר ונגדר חדש = שטוח — הזן אותו לתוצאה מדויקת ⚠';
$ec_lang['ip_flow']='ספיקה';
$ec_lang['ip_press']='לחץ';
$ec_lang['ip_v']='V';
$ec_lang['ip_hv']='H<sub>v</sub>';
$ec_lang['ip_hf']='H<sub>f</sub>';
$ec_lang['ip_hm']='H<sub>m</sub>';
$ec_lang['ip_hl']='H<sub>l</sub> <span title="סך הפסד קטע, H_f + H_m" class="ec-tip">?</span>';
$ec_lang['ip_pressure_warn']='לחץ נמוך/שלילי — בדוק תנאים תת-אטמוספריים';
$ec_lang['ip_pressure_warn_short']='נמוך ⚠';
$ec_lang['ip_h_far']='לחץ פולט אחרון';
$ec_lang['ip_q_supply']='ספיקת אספקה נתיב בדיקה, Q<sub>אספקה</sub> <span title="ספיקה הנכנסת לנתיב בדיקה המעוצב בלבד, לא הגוש/מערכת כולה — ראה Q_zone בתכנון יישום למטה עבור סך הכל המערכת." class="ec-tip">?</span>';
$ec_lang['ip_q_critical']='ספיקת פולט אחרון, q<sub>אחרון</sub>';
$ec_lang['ip_q_avg_lateral']='ספיקת פולט ממוצעת (צדדית בדיקה), q<sub>ממוצע</sub>';
$ec_lang['ip_dp_avg']='est. &Delta;לחץ, ממוצע לעומת צדדית בדיקה <span title="כמה גבוה יותר (או נמוך יותר) אתה משוער שצדדית טיפוסית/ממוצעת פועלת בהשוואה לצדדית בדיקה זו. צדדית הבדיקה היא בעמדה הרעה הנחוצה, ולכן הממוצע שלה הוא תחליף מוטה-נמוך עבור ממוצע שדה — כשהערך הוא 0, בדיקת ההוודות וגם מספרי תכנון היישום למטה משתמשים בממוצע של הצדדית בדיקה כמו-זה (בטוח אופטימי)." class="ec-tip">?</span>';
$ec_lang['ip_q_avg_field']='est. ספיקת פולט ממוצעת שדה, q<sub>ממוצע,שדה</sub> <span title="q_ממוצע_צדדי מעריך מחדש בלחץ כל שורה צדדית בתוספת הפרש הלחץ הנכנס למעלה — ניסיון לתקן עבור הצדדית בדיקה להיות המקרה הנחוץ, לא אחד מייצג. הזנו לשני בדיקת ההוודות וחלק תכנון היישום למטה." class="ec-tip">?</span>';
$ec_lang['ip_du_estimate']='בדיקת הוודות, q<sub>אחרון</sub>/q<sub>ממוצע,שדה</sub> <span title="זרימת פולט המחושבת האחרונה מחולקת בספיקת פולט הממוצעת השדה המעריכה — אותה צורה כמו ספר הלימוד Distribution Uniformity נמוך-רבע (ממוצע קבוצה נמוכה ÷ ממוצע אוכלוסייה), אך מדגם קטן מעוצב ותיקון משתמש-משוער, לא מדגם סטטיסטי שדה מלא. ערכים באו מעל 1 אפשריים וזה לא באג: זה פשוט משמעותו שפולט אחרון אינו הנקודה הנמוכה ביחס לממוצע שדה משוער (למשל ריצה תחתונה נוחה, או ה-&Delta;לחץ משוער למעלה הוא קטן מדי)." class="ec-tip">?</span>';
$ec_lang['ip_worst_case_warn']='לחץ פולט בדיקה הוא בו או מעל לחץ אספקה — נתיב זה לא סביר להיות צדדית הנחוצה שלך. בדוק עבור צדדית רחוקה יותר או גבוה-חיכוך, או פרופיל גובה המייצג טוב יותר את המקרה הנחוץ בפועל.';
$ec_lang['ip_q_ratio']='ספיקת פולט אחרון לעומת ספיקת תכנון, q<sub>אחרון</sub>/q<sub>תכנון</sub> <span title="בדיקה נפרדת, לא נתון הוודות: כמה רחוק פולט אחרון פועל מנקודת התכנון מדויק של היצרן. מעל 1: פועל מעל נקודת תכנונו (למשל מרווח גובה תחתונה נוח). מתחת 1: פועל תחת תכנון (מקרה אופייני של דומיננטיות חיכוך)." class="ec-tip">?</span>';
$ec_lang['ip_no_solution']='אין פתרון: לחץ אספקה הנדרש חורג מלחץ האספקה שהזנת. הגדל לחץ אספקה, הוריד דרישה, או השתמש בצינור גדול יותר.';
$ec_lang['ip_notes_1_term']='שיטה';
$ec_lang['ip_notes_1_def']='מעריך את הלחץ בפולט האחרון (הרחוק ביותר), ואחר כך צועד את Energy Grade Line בחזרה לכיוון האספקה, קטע לקטע, הוסף חיכוך והפסדים משניים בדרך. גובה וראש מהירות מותכנסים לאחור בכל צומת לדיווח הלחץ בפועל שם. לחץ הקצה הרחוק המשוער מותאם (bisection) עד שלחץ האספקה הנדרש המחושב תואם את לחץ האספקה הנכנס — אותה בעיה לולאה סגורה בעיתון על ידי פתרון צינור-זרימה על מחשבון Manning Pipe Flow, הורחק לרשת מתחנכת.';
$ec_lang['ip_notes_2_term']='ראשיות לעומת קטעים צדדיים';
$ec_lang['ip_notes_2_def']='כל שורה היא קטע אחד לאורך נתיב הידראולי אחד גרוע ביותר (נתיב הבדיקה) מהאספקה לפולט האחרון. קטע ראשי רק עביר ספיקה לצדדיות שאינן בנתיב הבדיקה, ולכן הנמשך שלו הוא הכפלה שטוחה (ספיקת תכנון × ספירת פולט כוללת של הקטע) — אין רגישות לחץ מקומית. הראשי הוא צינור גזע משותף, ולכן הקטע ממש בנקודת ההסתעפות של הצדדית בדיקה שלו כשלעצמו חייב לכלול לא רק צדדיות בין נקודות קצה שלו אלא גם צדדיות כלשהן עדיין הלאה על הראשי מעבר להסתעפות זו, או חולקות את אותה צומת (למשל צדדית מצד הפוך) — זרימתן נסעה דרך אותו קטע לפני פיצול, בין אם הן מופיעות בכל מקום בטבלה או לא. קטע צדדי הוא חלק של הצדדית בדיקה עצמה: פריקת פולט מחושבת מלחץ מקומי בפועל דרך q = k·H<sup>x</sup>, והפסד חיכוך מופחת לפי גורם F(n) של Christiansen כדי להסביר זרימה צעדה כל פולט בקטע שמושך כל.';
$ec_lang['ip_notes_3_term']='הגבלות';
$ec_lang['ip_notes_3_def']='דוגמא אחת של לחץ כניסה קבוע (לא עקומת משאבה), נתיב בדיקה אחד בלבד (לא שדה מלא), ועקומת פולט של 2-פרמטר (קבע את המעריך קרוב ל-0 כדי בקירוב פולט מתקזז לחץ). שני יחסים שונים מדווחים, בכוונה שמור נפרד: q<sub>אחרון</sub>/q<sub>ממוצע,שדה</sub> הוא בדיקת הוודות, צורה כמו ספר הלימוד Distribution Uniformity נמוך-רבע (ממוצע קבוצה נמוכה ÷ ממוצע אוכלוסייה) אך מחושבת מפולטים מעוצבים של צדדית הבדיקה, מתוקן על ידי משוער הנכנס &Delta;לחץ ולא מדגם סטטיסטי שדה מלא — הצדדית בדיקה היא בעמדה הרעה הנדרשת, לכן ממוצע גולמי שלה תיקון היה יוביל אנדרסטייט את השדה אמיתי הממוצע ולהפוך הוודות לראות טוב יותר מאשר הוא; הקלט &Delta;לחץ קיים בעיקר כדי נגד הטיה זו. ערכים בו או מעל 1 עדיין אפשרי (למשל משוער &Delta;לחץ קטן מדי, או ריצה תחתונה נוחה). q<sub>אחרון</sub>/q<sub>תכנון</sub> הוא בדיקה שונה, לא-הוודות נגד זרימת מדויק מדויק של היצרן — שימושי לזהות מערכת על- או תת-לחץ כלל, אך לא תחליף למספר הוודות, מכיוון שזרימת תכנון/מדויק אין יחס הכרחי לממוצע לחץ הפעלה בפועל של המערכת.';
$ec_lang['ip_notes_4_term']='התייחסות';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;השקיה על ידי זריקה.&rdquo; California Agricultural Experiment Station Bulletin 670. תקני ASAE/ASABE לתכנון ריסוס זעיר משתמשים בגישת הפסד חיכוך רב-יציאה אותה.';
$ec_lang['ip_notes_5_term']='תכנון יישום';
$ec_lang['ip_notes_5_def']='קצב יישום וזרימת מערכת/גוש משתמש בספיקת פולט ממוצעת שדה משוער (q<sub>ממוצע,שדה</sub> — הממוצע של צדדית הבדיקה, מתוקן על ידי משוער &Delta;לחץ), לא קצב ניחוש: PR = q<sub>ממוצע,שדה</sub> / A<sub>e</sub>, הזנות על ידי הערך המעוצב תוקן. רווח ומספר צדדית מערכת/פולט כולל הם קלטים נפרדים כאן משום נתיב הבדיקה דוגמא ענף רע אחד בלבד, לא כל צדדי בשדה.';
