<?php

// äöüÄÖÜß — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="Anteil";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ft']="ft";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% Gefälle";
$ec_lang['u_grade']="Gefälle";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m WS";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm WS";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/ft^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="s";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='HawsEDC Rechner';
$ec_lang['menu_main_list']='Rechnerliste';
$ec_lang['menu_main_hydraulics']='Hydraulik';
$ec_lang['menu_main_language']='Sprache';
$ec_lang['template_welcome']='&gt;&gt; Lasst Eure Ängste an der Tür; hier wird Liebe gesprochen. Ihr ruiniert nicht alles. Genießt auch die <a target="_blank" href="https://hawsedc.com/download.php">kostenlosen HawsEDC AutoCAD-Tools.</a> &lt;&lt;';
$ec_lang['template_translation_help']='Haben Sie eine großartige Idee für einen Rechner, der hier hinzugefügt werden soll?  Können Sie mir helfen, Übersetzungen zu verbessern, zu programmieren oder diese Rechner zu hosten?  ';
$ec_lang['template_feedback']='Bitte teilen Sie uns Ihre wertvollen Anmerkungen oder Ihr Lob mit. Hat dieser kostenlose Rechner Ihre Erwartungen übertroffen?';
$ec_lang['template_printable_title']='Druckbarer Titel';
$ec_lang['template_printable_subtitle']='Druckbarer Untertitel';
$ec_lang['index_title']='Kostenlose Ingenieurrechner online';
$ec_lang['calc_set_units']='Einheiten festlegen:';
$ec_lang['points_data_help']='(oder Kopieren/Einfügen im Datenbereich)';
$ec_lang['points_data_title']='Punktdaten<br />(durch Komma oder Tabulator getrennt)';
$ec_lang['points_data_copy']='Kopieren';
$ec_lang['points_data_paste']='Einfügen';
$ec_lang['calc_inputs']='Eingaben';
$ec_lang['calc_results']='Ergebnisse';
$ec_lang['view_hide_line']='[Diese Zeile ausblenden]';
$ec_lang['view_printable']='Druckversion (Seite neu laden zum Zurücksetzen)';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='Rohrreibungsverlust Darcy-Weisbach';
$ec_lang['dw_main_title']='Kostenloser Online-Rechner Rohrreibungsverlust Darcy-Weisbach';
$ec_lang['dw_main_desc']='Rohrreibungsverlust nach Darcy-Weisbach bei gegebenem Durchmesser, Rauheit und Durchfluss';
$ec_lang['dw_roughness']='Absolute Rauheit Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Kinematische Viskosität, v, in m<sup>2</sup>/s (1E-6 für reines Wasser bei Raumtemperatur)';
$ec_lang['dw_reynolds_number']='Reynolds-Zahl, Re';
$ec_lang['dw_flow_regime']='Strömungsregime';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='Übergangsbereich';
$ec_lang['dw_regime_turbulent']='turbulent';
$ec_lang['dw_friction_factor_method']='Methode des Reibungsbeiwerts';
$ec_lang['dw_friction_factor']='Reibungsbeiwert, f';
// Hazen-Williams
$ec_lang['hw_main_menu']='Rohrreibungsverlust Hazen-Williams';
$ec_lang['hw_main_title']='Kostenloser Online-Rechner Rohrreibungsverlust Hazen-Williams';
$ec_lang['hw_main_desc']='Rohrreibungsverlust nach Hazen-Williams bei gegebenem Durchmesser, Rauheit und Durchfluss';
$ec_lang['hw_hgl_1']='HGL flussabwärts';
$ec_lang['hw_hgl_2']='HGL flussaufwärts';
$ec_lang['hw_roughness']='Hazen-Williams-Koeffizient, C';
// Manning Irregular
$ec_lang['mi_menu']='Unregelmäßiges Profil Manning';
$ec_lang['mi_main_title']='Kostenloser Online-Rechner unregelmäßiges Gerinne Manning';
$ec_lang['mi_main_desc']='Gleichförmiger Abflussrechner für unregelmäßige Gerinne nach Manning';
$ec_lang['mi_waterSurfaceElevation']='Wasserstand';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Querschnittpunkte';
$ec_lang['mi_groupPoint']='Punkt';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Bereich';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Höhe';
$ec_lang['mi_d50in']='Mittlere<br />Korn-<br />größe<br />Deckwerk';
$ec_lang['mi_n']='n<br />Seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />Bereich-<br />grenze<br />(Ufer)';
$ec_lang['mi_tau']='Sohl-<br />schub-<br />spg. &tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Zus.-<br />ges. n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Hinweise';
$ec_lang['mi_notes_1_term']='Zusammengesetztes n';
$ec_lang['mi_notes_1_def']='Dieser Rechner folgt dem HEC-RAS-Referenzhandbuch bei der Berechnung des zusammengesetzten n des Bereichs nach Chow 1959, Seite 136, Gleichung 6-17 (nicht 6-18).';
$ec_lang['mi_notes_2_term']='Steindeckwerk';
$ec_lang['mi_notes_2_def']='Verwenden Sie den Manning-Trapezkanal-Rechner für das Steindeckwerk-Design. Dieser Rechner eignet sich besser für natürliche Querschnitte.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Rohrdurchfluss Manning';
$ec_lang['mpf_main_title']='Kostenloser Online-Rechner Rohrdurchfluss Manning';
$ec_lang['mpf_main_desc']='Manning-Formel für gleichförmigen Rohrdurchfluss bei gegebenem Gefälle und Füllhöhe';
$ec_lang['mpf_spreadheet_notice']='Entdecken Sie die Tabellenversion dieses Rechners';
$ec_lang['mpf_pipe_diameter']='Rohrdurchmesser, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning-Rauheitsbeiwert, n';
$ec_lang['mpf_friction_slope']='Druckliniengefälle (möglicherweise <a target="_blank" href="../pressureslope.php">?</a> gleich Rohrgefälle), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Relative Füllhöhe, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Siehe Hinweise)';
$ec_lang['mpf_flow']='Durchfluss, Q';
$ec_lang['mpf_velocity']='Fließgeschwindigkeit, v';
$ec_lang['mpf_velocity_head']='Geschwindigkeitshöhe, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Durchflossene Fläche, a';
$ec_lang['mpf_pipe_area']='Rohrquerschnitt, a0';
$ec_lang['mpf_area_ratio']='Relative Fläche, a/a0';
$ec_lang['mpf_wetted_perimeter']='Benetzter Umfang, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Hydraulischer Radius, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Wasserspiegelbreite, T';
$ec_lang['mpf_froude_number']='Froude-Zahl, F';
$ec_lang['mpf_shear_stress']='Mittlere Sohlschubspannung (Schleppkraft), tau';
$ec_lang['mpf_full_flow']='Vollfüllung, Q0';
$ec_lang['mpf_full_flow_ratio']='Füllungsverhältnis, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Dies ist der Durchfluss und die Tiefe innerhalb eines <em>unendlich langen</em> Rohres.</dt><dd>Um den Durchfluss in das Rohr zu leiten, kann eine erheblich höhere Einstauhöhe erforderlich sein. Addieren Sie mindestens das 1,5-fache der Geschwindigkeitshöhe zur Einstauhöhe oder <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">sehen Sie das 2-Minuten-Tutorial</a> für Standard-Durchlassberechnungen mit HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='y/d<sub>0</sub> für gegebenes Q berechnen';
$ec_lang['mpf_solve_desc']='Mit D<sub>0</sub>, n und S<sub>0</sub> aus dem Formular wird das kleinste y/d<sub>0</sub> für ein gegebenes Q gefunden.';
$ec_lang['mpf_solve_button']='Berechnen';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='Rohrdruckverlust Manning';
$ec_lang['mphl_main_title']='Kostenloser Online-Rechner Rohrdruckverlust Manning';
$ec_lang['mphl_main_desc']='Manning-Formel Druckverlust bei gegebenem Vollfüllungsdurchfluss';
$ec_lang['mphl_pipe_length']='Rohrlänge, L';
$ec_lang['mphl_area']='Fläche, A';
$ec_lang['mphl_total_junction_k']='Gesamter kombinierter Verlustbeiwert an Einbauten, k';
$ec_lang['mphl_friction_slope']='Reibungsgefälle';
$ec_lang['mphl_friction_loss']='Reibungsverlust, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Einbauverlust, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Gesamtverlust, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL flussabwärts';
$ec_lang['mphl_egl_2']='EGL flussaufwärts';
$ec_lang['mphl_hgl_2']='HGL im Rohr flussaufwärts ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Für einen offenen Einlauf (Durchlass) müssen die Einlaufsteuerungsbedingungen geprüft werden.</dt><dd>1. Die HGL flussaufwärts kann nicht unter der normalen Fließtiefe flussaufwärts liegen (oder unter dem Rohr!).</dd><dd>2. Der Einstaupegel eines Durchlasses wird besser durch die EGL als durch die HGL flussaufwärts dargestellt.</dd><dd>3. Sehen Sie <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">das 2-Minuten-Tutorial</a> für einfache Standard-Durchlassberechnungen mit HY-8.</dd>';
// Manning Trapezoid
$ec_lang['mtc_menu']='Trapezprofil-Kanal Manning';
$ec_lang['mtc_main_title']='Kostenloser Online-Rechner Trapezkanal Manning-Formel';
$ec_lang['mtc_main_desc']='Manning-Formel gleichförmiger Abfluss im Trapezkanal bei gegebenem Gefälle und Tiefe';
$ec_lang['mtc_bottom_width']='Sohlbreite, b';
$ec_lang['mtc_side_slope_1']='Böschung 1 (horiz./vert.)';
$ec_lang['mtc_side_slope_2']='Böschung 2 (horiz./vert.)';
$ec_lang['mtc_channel_slope']='Kanalgefälle, S';
$ec_lang['mtc_flow_depth']='Fließtiefe, y';
$ec_lang['mtc_bend_angle']='Kurvenwinkel <a target="_blank" href="riprap-bend-angle.png" title="Klicken für Bild">?</a> (für Deckwerksbemessung)';
$ec_lang['mtc_sgrock']='Rohdichte des Steins (2,65)';
$ec_lang['mtc_d50_in']='Bemessungskorngröße, D50';
$ec_lang['mtc_n_strickler']='n für Bemessungskorngröße nach Strickler';
$ec_lang['mtc_n_blodgett']='n für Bemessungskorngröße nach Blodgett';
$ec_lang['mtc_n_bathurst']='n für Bemessungskorngröße nach Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Erforderliche Körnung kantenreicher Steine Sohle, D50 (Isbash &amp; MC) <a href="javascript:alert(\'Nach Isbash (1936) und Maricopa County, Arizona, USA.\')">?</a>';
$ec_lang['mtc_d50_z1']='Erforderliche Körnung kantenreicher Steine Böschung 1, D50 (Isbash &amp; MC) <a href="javascript:alert(\'Nach Isbash (1936) und Maricopa County, Arizona, USA.\')">?</a>';
$ec_lang['mtc_d50_z2']='Erforderliche Körnung kantenreicher Steine Böschung 2, D50 (Isbash &amp; MC) <a href="javascript:alert(\'Nach Isbash (1936) und Maricopa County, Arizona, USA.\')">?</a>';
$ec_lang['mtc_d50_mra']='Erforderliche Körnung kantenreicher Steine, D50 (Maynord, Ruff und Abt 1989)';
$ec_lang['mtc_d50_searcy']='Erforderliche Körnung kantenreicher Steine, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Automatische Iteration Steinbemessung und Rauheit</dt><dd>Wählen Sie einen Rauheits-Radioknopf (BB empfohlen) und einen Radioknopf für die Bemessungskorngröße (Isbash empfohlen). Stellen Sie Tiefe und Steinbemessungsfaktor ein, um den gewünschten Durchfluss mit einer gleichmäßigen Korngröße zu erzielen. Bei jeder Änderung eines Eingabewerts startet der Iterationszyklus: 1. Die Rauheit wird aus der Bemessungskorngröße berechnet. 2. Der berechnete Rauheitswert wird in die Eingaberauheit kopiert. 3. Kanaldurchfluss und erforderliche Korngröße werden berechnet. 4. Die Bemessungskorngröße wird angepasst. 5. Wiederholen bis der Fehler sehr klein ist.</dd><dt>Grundrechner (ohne Iteration)</dt><dd>Geben Sie den gewünschten Rauheitswert ein. Ignorieren Sie den Eingabebereich für die Bemessungskorngröße.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson-Steinrampe';
$ec_lang['rrc_main_desc']='Bemessungstabelle Robinson-Steinrampe';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Einfaches Wehr';
$ec_lang['ws_main_title']='Kostenloser Online-Rechner breitkroniges Wehr';
$ec_lang['ws_main_desc']='Rechner für den Durchfluss über ein einfaches breitkroniges Wehr';
$ec_lang['ws_weirLength']='Wehrlänge, l';
$ec_lang['ws_headWaterHeight']='Oberwasserhöhe, h';
$ec_lang['ws_weirCoefficient']='Wehrbeiwert, Cw';
$ec_lang['ws_notes_heading']='Hinweise';
$ec_lang['ws_notes_we_term']='Wehrformel';
// Weir Flow Irregular
$ec_lang['wi_menu']='Unregelmäßiges Wehr';
$ec_lang['wi_main_title']='Kostenloser Online-Rechner segmentiertes Wehr mit variablem Querschnitt';
$ec_lang['wi_main_desc']='Rechner für den Durchfluss über ein unregelmäßiges Wehr';
$ec_lang['wi_headWaterelevation']='Oberwasserstand';
$ec_lang['wi_weirPoints']='Wehrpunkte';
$ec_lang['wi_station']='Station';
$ec_lang['wi_elevation']='Höhe';
$ec_lang['wi_pondingHeight']='Stautiefe';
$ec_lang['wi_incrementalFlow']='Teilabfluss';
$ec_lang['wi_cumulativeFlow']='Kumulierter Abfluss';
$ec_lang['wi_save_and_calculate']='Speichern und berechnen';
$ec_lang['wi_notes_we_term']='Wehrformel';
$ec_lang['wi_notes_we_def']='q = wenn (Länge = 0) dann 0, wenn (Gefälle=0) dann cw*Länge*d<sub>0</sub><sup>1.5</sup>, sonst cw/(2.5*Gefälle) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) wobei d<sub>1</sub> und d<sub>0</sub> immer positiv oder null sind';
// Orifice Flow
$ec_lang['or_main_menu']='Ausfluss durch Öffnung';
$ec_lang['or_main_title']='Kostenloser Online-Rechner Ausfluss durch Öffnung';
$ec_lang['or_main_desc']='Ausfluss durch Öffnung — frei oder eingestaut';
$ec_lang['or_shape']='Form der Öffnung';
$ec_lang['or_shape_circular']='Kreisförmig';
$ec_lang['or_shape_rectangular']='Rechteckig';
$ec_lang['or_diameter']='Durchmesser (kreisförmig) oder Höhe (rechteckig), D';
$ec_lang['or_width']='Breite, W (nur rechteckig)';
$ec_lang['or_invert']='Sohlhöhe der Öffnung (Unterkante)';
$ec_lang['or_hwe']='Oberwasserstand';
$ec_lang['or_twe']='Unterwasserstand';
$ec_lang['or_cd']='Abflussbeiwert, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Schwerpunkthöhe';
$ec_lang['or_head']='Wirksame Druckhöhe, h';
$ec_lang['or_area']='Querschnittsfläche der Öffnung, A';
$ec_lang['or_flow']='Durchfluss, Q';
$ec_lang['or_velocity']='Geschwindigkeit an der Öffnung, v';
$ec_lang['or_regime']='Abflussregimeprüfung';
$ec_lang['or_regime_valid']='Freier Ausfluss — Öffnungsregime gültig ✓';
$ec_lang['or_regime_submerged']='Eingestaute Öffnung (TWE über Sohle) — gültig ✓';
$ec_lang['or_regime_warn']='Warnung: Oberwasser unter Scheitel — kein Öffnungsregime';
$ec_lang['or_regime_twe_above_hwe']='Warnung: Unterwasser (TWE) über Oberwasser (HWE) — Eingaben prüfen';
$ec_lang['or_notes_1_term']='Ausflusformel';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Freier Ausfluss: h = HWE &minus; Schwerpunkt. Eingestaut (TWE über Sohle): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Abflussregime';
$ec_lang['or_notes_2_def']='Die Ausflusformeln gelten, wenn der Oberwasserspiegel über dem Scheitel der Öffnung liegt. Liegt er darunter, ist eine Wehrformel zu verwenden.';
$ec_lang['or_notes_3_term']='Abflussbeiwert';
$ec_lang['or_notes_3_def']='C<sub>d</sub> liegt bei ca. 0,60–0,65 für scharfkantige Öffnungen. Abgerundete oder einspringende Einläufe haben andere Werte. Siehe <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> oder das HEC-RAS Hydraulic Reference Manual.';
$ec_lang['or_notes_4_term']='Rückstau';
$ec_lang['or_notes_4_def']='Wenn TWE über der Sohle der Öffnung liegt, verwendet der Rechner automatisch die eingestaute Ausflusformel mit h = HWE &minus; TWE. Liegt TWE auf oder unter der Sohle, wird freier Ausfluss angenommen und h = HWE &minus; Schwerpunkt.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Entleerungszeit durch Öffnung';
$ec_lang['odt_main_title']='Kostenloser Online-Rechner Entleerungszeit durch Öffnung';
$ec_lang['odt_main_desc']='Entleerungszeit eines Teichs durch Öffnung &mdash; Kegelvolumenmethode';
$ec_lang['odt_h1_elev']='Anfangswasserspiegelhöhe';
$ec_lang['odt_a1']='Anfangsteichfläche, A1';
$ec_lang['odt_h2_elev']='Endwasserspiegelhöhe';
$ec_lang['odt_h_orifice']='Schwerpunkthöhe der Öffnung';
$ec_lang['odt_a0']='Teichfläche auf Öffnungshöhe, A0';
$ec_lang['odt_a_ending']='Endteichfläche, A2 (interpoliert)';
$ec_lang['odt_h2_check']='Prüfung der Endhöhe';
$ec_lang['odt_h2_ok']='Endhöhe über Öffnungsscheitel ✓';
$ec_lang['odt_h2_warn']='Warnung: Endhöhe auf oder unter Öffnungsscheitel (Schwerpunkt + D/2)';
$ec_lang['odt_d']='Öffnungsdurchmesser (kreisförmig) oder Höhe (rechteckig), D';
$ec_lang['odt_w']='Öffnungsbreite, W (nur rechteckig)';
$ec_lang['odt_t_sec']='Entleerungszeit (Sekunden)';
$ec_lang['odt_t_min']='Entleerungszeit (Minuten)';
$ec_lang['odt_t_hr']='Entleerungszeit (Stunden)';
$ec_lang['odt_t_day']='Entleerungszeit (Tage)';
$ec_lang['odt_notes_1_term']='Formel';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) ergibt die Entleerungszeit von Druckhöhe H bis zur Öffnung. Entleerungszeit = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), wobei H<sub>1</sub> = Anfangshöhe &minus; Öffnungshöhe, H<sub>2</sub> = Endhöhe &minus; Öffnungshöhe.';
$ec_lang['odt_notes_2_term']='Methode';
$ec_lang['odt_notes_2_def']='Die Kegelvolumenmethode modelliert den Teich als Kegelschnitt zwischen der Anfangsfläche A<sub>1</sub> beim Anfangswasserspiegel und der Fläche A<sub>0</sub> auf der Schwerpunkthöhe der Öffnung. A<sub>2</sub> wird aus A<sub>1</sub> und A<sub>0</sub> nach dem Kegelmodell interpoliert. Die Entleerungszeit von Anfang bis Endhöhe ist die Gesamtzeit von H<sub>1</sub> bis zur Öffnung minus der verbleibenden Zeit von H<sub>2</sub> bis zur Öffnung.';
$ec_lang['odt_h1']='Anfangsdruckhöhe, H<sub>1</sub> (WSE &minus; Schwerpunkt)';
$ec_lang['odt_q_max']='Maximaldurchfluss (Anfang), Q<sub>max</sub>';
$ec_lang['odt_vol']='Abgeführtes Volumen';
$ec_lang['odt_sketch_start']='Anfang';
$ec_lang['odt_sketch_end']='Ende';
// Erosion Setback
$ec_lang['essc_btbw']='Uferbandbreite';
$ec_lang['essc_mcr']='Minimaler Kurvenradius';
$ec_lang['essc_q']='Durchfluss, Q';
// Contact

// Irrigation
$ec_lang['irr_main_menu']='Bewässerungsdurchflussmessung';
$ec_lang['irr_main_title']='Kostenlose Online-Rechner für Bewässerungsdurchflussmessung';
$ec_lang['irr_main_desc']='Bewässerungsdurchflussmessung — Wehre und Öffnungen';
$ec_lang['contact_title']='HawsEDC Kontakt';
$ec_lang['contactSendMessage']='Senden Sie Tom Haws eine Nachricht';
$ec_lang['contactYourName']='Ihr Name:';
$ec_lang['contactYourEmail']='Ihre E-Mail-Adresse:';
$ec_lang['contactSubject']='Betreff:';
$ec_lang['contact_message']='Nachricht:';
$ec_lang['contactSpamPrefix']='Fünf plus eins ergibt';
$ec_lang['contactSpamPostfix']='(Bitte auf Englisch ausschreiben. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Nachricht senden';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Mikro-Wasserkraft';
$ec_lang['mhp_main_title']='Kostenloser Online-Rechner für Mikro-Wasserkraft';
$ec_lang['mhp_main_desc']='Leistungsrechner für Laufwasser-Mikro-Wasserkraftanlagen';
$ec_lang['mhp_flow']='Durchfluss, Q';
$ec_lang['mhp_gross_head']='Bruttofallhöhe (Höhenunterschied), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Druckverluste in der Druckrohrleitung, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Anlagenwirkungsgrad, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Nettofallhöhe, H<sub>net</sub>';
$ec_lang['mhp_power']='Abgegebene Leistung, P';
$ec_lang['mhp_annual_kwh']='Jahresenergie bei 100 % Kapazität';
$ec_lang['mhp_notes_1_term']='Leistungsgleichung';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, wobei &rho; = 1000 kg/m&sup3; (Süßwasser) und g = 9,806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Nettofallhöhe';
$ec_lang['mhp_notes_2_def']='Nettofallhöhe = Bruttofallhöhe &minus; Druckverluste in der Druckrohrleitung. Eine übliche erste Schätzung ist h<sub>L</sub> &asymp; 5 % von H<sub>gross</sub>. Verwenden Sie den <a href="Darcy-Weisbach.php">Darcy-Weisbach-Rechner</a> für genauere Schätzungen der Druckverluste in der Druckrohrleitung.';
$ec_lang['mhp_notes_3_term']='Wirkungsgrad';
$ec_lang['mhp_notes_3_def']='Der typische Anlagenwirkungsgrad &eta; liegt zwischen 0,70 und 0,85 für Pelton- und Querstromturbinen, die in Mikro-Wasserkraftanlagen verbreitet sind. Verwenden Sie 0,75 als konservative erste Schätzung.';
$ec_lang['mhp_notes_4_term']='Jahresenergie';
$ec_lang['mhp_notes_4_def']='Die Jahresenergie setzt einen kontinuierlichen Betrieb bei Volldurchfluss (8.760 Stunden/Jahr) voraus. Die tatsächliche Erzeugung wird aufgrund saisonaler Durchflussschwankungen, Wartungsausfallzeiten und des Lastfaktors geringer sein.';
// Penstock Design
$ec_lang['ps_main_menu']='Druckrohrleitung dimensionieren';
$ec_lang['ps_main_title']='Kostenloser Online-Rechner für Druckrohrleitungen';
$ec_lang['ps_main_desc']='Dimensionierung der Druckrohrleitung für Mikro-Wasserkraft — Druckverlust, Leistung und Fließgeschwindigkeit';
$ec_lang['ps_flow']='Durchfluss, Q';
$ec_lang['ps_gross_head']='Bruttofallhöhe, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Rohrdurchmesser der Druckrohrleitung, D';
$ec_lang['ps_length']='Rohrlänge der Druckrohrleitung, L';
$ec_lang['ps_roughness']='Rohrrauheit, e';
$ec_lang['ps_km']='Einzelwiderstandsbeiwert, k<sub>m</sub>';
$ec_lang['ps_nu']='Kinematische Viskosität, &nu;, in m<sup>2</sup>/s (1E-6 für Wasser nahe 20&deg;C)';
$ec_lang['ps_efficiency']='Anlagenwirkungsgrad, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Fließgeschwindigkeit, v';
$ec_lang['ps_vel_check']='Geschwindigkeitsprüfung';
$ec_lang['ps_f']='Reibungsbeiwert, f';
$ec_lang['ps_hf']='Reibungsdruckverlust, h<sub>f</sub>';
$ec_lang['ps_hm']='Einzeldruckverlust, h<sub>m</sub>';
$ec_lang['ps_hl']='Gesamtverlust der Druckrohrleitung, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Druckverlustprüfung';
$ec_lang['ps_hnet']='Nettofallhöhe, H<sub>net</sub>';
$ec_lang['ps_power']='Leistungsabgabe, P';
$ec_lang['ps_annual_kwh']='Jahresenergie bei 100 % Kapazität';
$ec_lang['ps_vel_ok']='1–3 m/s — im Zielbereich ✓';
$ec_lang['ps_vel_low']='unter 1 m/s — Durchmesser vergrößern ⚠';
$ec_lang['ps_vel_high']='über 3 m/s — Durchmesser verkleinern ⚠';
$ec_lang['ps_hl_ok']='innerhalb des 10-%-Ziels ✓';
$ec_lang['ps_hl_warn']='überschreitet 10-%-Ziel — größeres Rohr erwägen ⚠';
$ec_lang['ps_hl_bad']='überschreitet 20 % — Rohr neu dimensionieren';
$ec_lang['ps_notes_1_term']='Druckverlust';
$ec_lang['ps_notes_1_def']='Gesamtverlust der Druckrohrleitung h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, wobei h<sub>f</sub> = f(L/D)(v&sup2;/2g) der Darcy-Weisbach-Reibungsverlust ist und h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g Einläufe, Krümmer und Armaturen berücksichtigt. Nettofallhöhe H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Fließgeschwindigkeit';
$ec_lang['ps_notes_2_def']='Zielbereich: 1&ndash;3 m/s. Unter 1 m/s ist das Rohr für den Durchfluss überdimensioniert; über 3 m/s steigen die Reibungsverluste und das Risiko eines Wasserschlags.';
$ec_lang['ps_notes_3_term']='Druckverlustziel';
$ec_lang['ps_notes_3_def']='Verluste in der Druckrohrleitung unter 10 % der Bruttofallhöhe sind in der Regel wirtschaftlich. Der optimale Kompromiss zwischen Rohrkosten und Leistungsverlust liegt für wertvolle Stromerzeugungs-Standorte oft bei 4&ndash;6 %.';
$ec_lang['ps_notes_4_term']='Einzelwiderstände k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Typische Werte: scharfkantige Einlauföffnung 0,5, jeder 45&deg;-Krümmer 0,2&ndash;0,3, Schieber (vollständig geöffnet) 0,1, Schmetterlingsklappe 0,2. Alle Einbauten summieren für den Gesamt-k<sub>m</sub>. Standardwert 1,5 geht von einem Einlauf und zwei Krümmern aus.';
$ec_lang['ps_notes_5_term']='Rohrrauheit e';
$ec_lang['ps_notes_5_def']='Typische absolute Rauheit: Stahl (neu) 0,046&nbsp;mm, Stahl (gebraucht) 0,15&nbsp;mm, HDPE 0,003&nbsp;mm, PVC/uPVC 0,0015&nbsp;mm, Beton 0,3&ndash;3&nbsp;mm. HDPE ist bei kleinen Mikro-Wasserkraft-Druckrohrleitungen weit verbreitet.';
