<?php

// All missing text declarations will fall back to English.

$ec_lang['u_depthFrac']='fracție';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% ridicare/drum';
$ec_lang['u_grade']='ridicare/drum';
$ec_lang['u_in2']='in^2';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='L/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='ML/zi';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_bar']="bar";
$ec_lang['u_kgfcm2']="kgf/cm^2";
$ec_lang['u_s']='sec';
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Calculatoare HawsEDC';
$ec_lang['menu_main_list']='Listă de calculatoare';
$ec_lang['menu_main_hydraulics']='Hidraulică';
$ec_lang['menu_main_language']='Limbă';
$ec_lang['menu_more']='Mai mult';
$ec_lang['template_welcome']='>> Lasă temerile la ușă; dragostea se vorbește aici. Nu stricați totul. Bucurați-vă și de <a target="_blank" href="https://hawsedc.com/download.php">instrumentele gratuite HawsEDC AutoCAD</a>. <<';
$ec_lang['template_translation_help']='Puteți sugera o formulare mai bună sau orice altceva? Vă rugăm să ne spuneți.';
$ec_lang['template_feedback']='Vă rugăm să ne transmiteți sugestiile sau aprecierile dumneavoastră valoroase. Acest calculator gratuit v-a depășit așteptările în orice privință?';
$ec_lang['template_printable_title']='Titlu tipărit';
$ec_lang['template_printable_subtitle']='Subtitlu tipărit';
$ec_lang['index_title']='Calculatoare Inginerești Gratuite Online';
$ec_lang['calc_set_units']='Alegeți unitatea de măsură:';
$ec_lang['calc_defaults']='Valori implicite';
$ec_lang['calc_defaults_confirm']='Resetează calculatorul la valorile implicite inițiale?';
$ec_lang['points_data_help']='(sau Copiați/Lipiți folosind zona de date)';
$ec_lang['points_data_title']='Date puncte<br />(separate prin virgulă sau tabulație)';
$ec_lang['points_data_copy']='Copiați';
$ec_lang['points_data_paste']='Lipiți';
$ec_lang['calc_inputs']='Date de intrare';
$ec_lang['calc_results']='Rezultate';
$ec_lang['view_hide_line']='[Ascunde această linie]';
$ec_lang['view_printable']='Versiune tipăribilă (reîncărcați/actualizați pentru a restaura)';
$ec_lang['ec_name_label']='Salvați acest calcul:';
$ec_lang['ec_name_placeholder']='Nume';
$ec_lang['ec_name_hint']='Salvează valorile introduse în URL pentru marcaj, recuperare istoric și partajare';
$ec_lang['calc_copy_link']='Copiați linkul';
$ec_lang['ec_related_calcs']='Calculatoare conexe:';
$ec_lang['calc_copy_link_done']='Copiat!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Pierdere de Sarcină Conductă Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculator Gratuit Online Pierdere de Sarcină Conductă Darcy-Weisbach';
$ec_lang['dw_main_desc']='Pierdere de Sarcină Conductă Darcy-Weisbach la Diametru, Rugozitate și Debit Date';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='Înălțimea de rugozitate absolută, e, a peretelui conductei. Valori tipice: oțel (nou) 0,046 mm, oțel (uzat) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, beton 0,3–3 mm.';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="1×10⁻⁶ m²/s pentru apă curată la 20°C">Vâscozitate cinematică, &nu; <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='Vâscozitate cinematică, &nu;';
$ec_lang['dw_kinematic_viscosity_tip']='1×10⁻⁶ m²/s pentru apă curată la 20°C';
$ec_lang['dw_reynolds_number']='Numărul Reynolds, Re';
$ec_lang['dw_flow_regime']='Regimul de curgere';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='tranzitoriu';
$ec_lang['dw_regime_turbulent']='turbulent';
$ec_lang['dw_friction_factor_method']='Metoda factorului de frecare';
$ec_lang['dw_friction_factor']='Factorul de frecare, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Pierdere de Sarcină Conductă Hazen-Williams';
$ec_lang['hw_main_title']='Calculator Gratuit Online Pierdere de Sarcină Conductă Hazen-Williams';
$ec_lang['hw_main_desc']='Pierdere de Sarcină Conductă Hazen-Williams la Diametru, Rugozitate și Debit Date';
$ec_lang['hw_hgl_1']='HGL aval';
$ec_lang['hw_hgl_2']='HGL amonte';
$ec_lang['hw_roughness']='Coeficientul Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning Canal cu Secțiune Neregulată';
$ec_lang['mi_main_title']='Calculator Gratuit Online Manning pentru Canal cu Secțiune Neregulată';
$ec_lang['mi_main_desc']='Calculator Manning de Curgere Uniformă în Canal cu Secțiune Neregulată';
$ec_lang['mi_waterSurfaceElevation']='Cota suprafeței apei';
$ec_lang['mi_q_617']='<span class="ec-help" title="Debitul compozit, Q, folosind un n compozit pentru fiecare regiune conform Chow 6-17, viteze egale">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='Puncte de secțiune transversală';
$ec_lang['mi_groupPoint']='Punct';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Regiune';
$ec_lang['mi_station']='Sta.';
$ec_lang['mi_elevation']='Cotă';
$ec_lang['mi_d50in']='Dimensiune<br />mediană<br />rocă<br />placare';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />limita<br />regiunii<br />(Mal)';
$ec_lang['mi_tau']='Efort<br />tangenț.<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />comp.';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='n compozit';
$ec_lang['mi_notes_1_def']='Acest calculator urmează Manualul de Referință HEC-RAS în calculul n compozit de regiune folosind Chow 1959, pagina 136, ecuația 6-17 (nu 6-18).';
$ec_lang['mi_notes_2_term']='Placare cu rocă';
$ec_lang['mi_notes_2_def']='Folosiți Calculatorul Manning pentru Canal Trapezoidal pentru a proiecta placarea cu rocă. Acest calculator este mai potrivit pentru secțiuni naturale.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning Curgere Conductă';
$ec_lang['mpf_main_title']='Calculator Gratuit Online Manning Curgere Conductă';
$ec_lang['mpf_main_desc']='Formula Manning Curgere Uniformă în Conductă la Pantă și Adâncime Date';
$ec_lang['mpf_spreadheet_notice']='Foaie de calcul Curgere în Conductă Manning';
$ec_lang['mpf_pipe_diameter']='Diametrul conductei, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Coeficientul de rugozitate Manning, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">Panta de frecare, S<sub>f</sub></a><span class="ec-help" title="Uneori egală cu panta conductei. Urmați linkul pentru explicație (doar în engleză)."><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='Adâncime relativă de curgere, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Debit, Q';
$ec_lang['mpf_flow_tip']='Debitul și adâncimea sunt calculate pentru o conductă infinit de lungă. Pentru a introduce acest debit în conductă poate fi necesară o adâncime mai mare a apei din amonte. Vedeți Notele de mai jos pentru detalii și un videoclip tutorial.';
$ec_lang['mpf_velocity']='Viteză, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="Energie cinetică exprimată ca înălțime a coloanei de apă, v&sup2;/2g">Sarcina de viteză, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='Aria de curgere, A';
$ec_lang['mpf_pipe_area']='Aria conductei, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Arie relativă, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Perimetrul udat, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Raza hidraulică, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Lățimea suprafeței libere, T';
$ec_lang['mpf_froude_number']='Numărul Froude, Fr';
$ec_lang['mpf_shear_stress']='Efortul tangențial mediu, &tau;';
$ec_lang['mpf_full_flow']='Debit la plin, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Raport față de debitul la plin, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>Acesta este debitul și adâncimea în interiorul unei conducte <em>infinit lungi</em>.</dt><dd>Introducerea debitului în conductă poate necesita o adâncime a apei din amonte semnificativ mai mare. Adăugați cel puțin de 1,5 ori sarcina de viteză pentru a obține adâncimea din amonte sau <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">consultați tutorialul meu de 2 minute</a> pentru calculele standard ale nivelului din amonte ale podețelor folosind HY-8.</dd>';
$ec_lang['mpf_solve_button']='Calculează';
$ec_lang['mpf_solve_for_flow']='pentru debit, Q =';
$ec_lang['mpf_solver_enter_positive_q']='Introduceți un Q țintă pozitiv.';
$ec_lang['mpf_solver_no_solution']='Fără soluție: Q depășește capacitatea conductei la y/d0 = 93.8% (Qmax = {qmax} în unitățile selectate).';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning Pierdere de Sarcină Conductă';
$ec_lang['mphl_main_title']='Calculator Gratuit Online Manning Pierdere de Sarcină Conductă';
$ec_lang['mphl_main_desc']='Formula Manning Pierdere de Sarcină la Curgere Plină Dată';
$ec_lang['mphl_pipe_length']='Lungimea conductei, L';
$ec_lang['mphl_area']='Arie, A';
$ec_lang['mphl_total_junction_k']='Coeficient de pierdere minoră (locală), k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='Coeficient de pierdere, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='Coeficient de pierdere minoră (locală), k<sub>m</sub>. Aceste pierderi apar la joncțiuni de conducte, intrări, ieșiri, coturi și vane — termenul „minoră” este convențional, dar înșelător; pe o conductă scurtă pot egala sau depăși pierderile prin frecare. Valori tipice k: intrare cu muchie ascuțită 0,5, fiecare cot de 45° 0,2–0,3, vană cu sertar (complet deschisă) 0,1, vană fluture 0,2, ieșire (spre rezervor sau atmosferă) 1,0. Însumați toate fitingurile pentru k<sub>m</sub> total. Valoarea implicită 2,0 presupune o intrare, o ieșire și două coturi de 45°.';
$ec_lang['mphl_friction_slope']='Panta de frecare';
$ec_lang['mphl_friction_loss']='Pierdere prin frecare, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Pierdere minoră (locală), h<sub>m</sub>';
$ec_lang['mphl_total_loss']='Pierdere totală, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='EGL aval';
$ec_lang['mphl_egl_2']='EGL amonte';
$ec_lang['mphl_hgl_egl_tip']='Poate să nu fie valid dacă conducta este ridicată. Vedeți notele.';
$ec_lang['mphl_note_1']='<dl><dt>Acest calculator nu ia în calcul cota conductei.</dt><dd>Dacă HGL coboară sub partea superioară a conductei în orice punct, acest calcul poate să nu fie valid.</dd><dt>Pentru o condiție de intrare deschisă (podeț), este necesar să se verifice condițiile de control la intrare.</dt><dd>1. HGL amonte trebuie să fie deasupra cotei de adâncime normală amonte a curgerii (și mai sus decât conducta!).</dd><dd>2. Nivelul apei din amonte al unui podeț este mai bine reprezentat de EGL amonte decât de HGL amonte.</dd><dd>3. Consultați <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">tutorialul meu de 2 minute</a> pentru calculele simple standard ale nivelului din amonte ale podețelor folosind HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning Canal Trapezoidal';
$ec_lang['mtc_main_title']='Calculator Gratuit Online Formula Manning Canal Trapezoidal';
$ec_lang['mtc_main_desc']='Formula Manning Curgere Uniformă în Canal Trapezoidal la Pantă și Adâncime Date';
$ec_lang['mtc_bottom_width']='Lățimea fundului, b';
$ec_lang['mtc_side_slope_1']='Taluz 1, z<sub>1</sub> (orizontal/vertical)';
$ec_lang['mtc_side_slope_2']='Taluz 2, z<sub>2</sub> (orizontal/vertical)';
$ec_lang['mtc_channel_slope']='Panta canalului, S';
$ec_lang['mtc_flow_depth']='Adâncimea de curgere, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">Unghi de curbă, β</a><span class="ec-help" title="Pentru dimensionarea anrocamentului. Urmați linkul pentru schemă."><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="Densitate relativă la apă. Valoare tipică &asymp; 2,65 pentru rocă concasată">Densitatea relativă a rocii, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='Dimensiunea de proiectare a rocii, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='n pentru dimensiunea de proiectare a rocii conform Strickler';
$ec_lang['mtc_n_blodgett']='n pentru dimensiunea de proiectare a rocii conform Blodgett';
$ec_lang['mtc_n_bathurst']='n pentru dimensiunea de proiectare a rocii conform Bathurst';
$ec_lang['mtc_n_pi']='n pentru dimensiunea de proiectare a rocii conform Phillips & Ingersoll';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_pi_range_check']='Verificare interval P&I';
$ec_lang['mtc_pi_ok']='d50 în intervalul P&I';
$ec_lang['mtc_pi_ok_tip']='0,28–0,36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='În afara intervalului';
$ec_lang['mtc_pi_tip']='Extrapolare în afara intervalului de date de 0,28–0,36 ft pe baza căruia a fost dezvoltată această ecuație — a se trata ca o verificare aproximativă, nu ca bază de proiectare';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Conform Isbash (1936) și Comitatul Maricopa, Arizona, SUA.">Dimensiunea necesară a rocii unghiulare de fund, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Conform Isbash (1936) și Comitatul Maricopa, Arizona, SUA.">Dimensiunea necesară a rocii unghiulare pentru taluzul 1, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Conform Isbash (1936) și Comitatul Maricopa, Arizona, SUA.">Dimensiunea necesară a rocii unghiulare pentru taluzul 2, D<sub>50</sub> (Isbash & MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='Dimensiunea necesară a rocii unghiulare, D<sub>50</sub> (Maynord, Ruff și Abt 1989)';
$ec_lang['mtc_d50_searcy']='Dimensiunea necesară a rocii unghiulare, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='Viteză rezonabilă pentru ipotezele de curgere uniformă.';
$ec_lang['mtc_vel_low']='Viteză mică — risc de sedimentare.';
$ec_lang['mtc_iteration_tip']='Alegeți o opțiune de rugozitate (Blodgett–Bathurst recomandat) și o opțiune de dimensiune a rocii (Isbash recomandat) pentru a itera automat către o dimensiune uniformă a rocii pentru debitul dorit. Vedeți Notele de mai jos pentru metoda completă, sau introduceți propria valoare de rugozitate (urmați linkul pentru îndrumări) și ignorați dimensiunea rocii pentru a evita iterația.';
$ec_lang['mtc_note_1']='<dl><dt>Iterație automată de dimensionare a rocii și rugozității</dt><dd>Alegeți o opțiune de rugozitate (Blodgett–Bathurst recomandat) și o opțiune de dimensiune de proiectare a rocii (Isbash recomandat). Ajustați adâncimea și factorul de siguranță al dimensiunii rocii pentru a atinge debitul dorit cu o dimensiune uniformă a rocii. De fiecare dată când modificați o valoare de intrare, calculatorul repetă acești pași: 1. Rugozitatea este calculată din dimensiunea de proiectare a rocii. 2. Calculul rugozității solicitate este copiat în rugozitatea de intrare. 3. Debitul canalului și dimensiunea necesară a rocii sunt calculate. 4. Dimensiunea de proiectare a rocii este ajustată. 5. Repetați până când eroarea din dimensiunea de proiectare a rocii este foarte mică.</dd><dt>Calculator de bază (fără iterație)</dt><dd>Introduceți valoarea dorită de rugozitate. Ignorați zona de intrare a dimensiunii de proiectare a rocii.</dd></dl>';
$ec_lang['mtc_note_2_term']='Verificare viteză';
$ec_lang['mtc_note_2_def']='Viteza mare indică faptul că a existat o cădere de nivel mare, care a generat o energie specifică atât de ridicată. Acea energie se poate pierde rapid la lărgiri, curbe sau obstacole. Verificați dacă acest lucru este rezonabil pentru amplasament.';
$ec_lang['mtc_solver_no_solution']='Nu s-a găsit nicio soluție pentru Q dat cu aceste date de intrare ale canalului.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Deversor Simplu';
$ec_lang['ws_main_title']='Calculator Gratuit Online pentru Deversor Simplu cu Creastă Lată';
$ec_lang['ws_main_desc']='Calculator pentru Deversor Simplu cu Creastă Lată';
$ec_lang['ws_weirLength']='Lungimea deversorului, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="Energie pe unitatea de greutate a apei — o înălțime a coloanei de apă, nu o presiune">Sarcină, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='Coeficientul deversorului, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='Note';
$ec_lang['ws_notes_we_term']='Ecuația deversorului';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Deversor Neregulat';
$ec_lang['wi_main_title']='Calculator Gratuit Online pentru Deversor Neregulat, Segmentat, cu Adâncime Variabilă';
$ec_lang['wi_main_desc']='Calculator pentru Deversor Neregulat';
$ec_lang['wi_weirPoints']='Puncte ale deversorului';
$ec_lang['wi_pondingHeight']='Înălțimea acumulării';
$ec_lang['wi_incrementalFlow']='Debit incremental';
$ec_lang['wi_cumulativeFlow']='Debit cumulat';
$ec_lang['wi_save_and_calculate']='Salvați și Calculați';
$ec_lang['wi_notes_we_def']='q = dacă (length = 0) atunci 0 altfel dacă (slope=0) atunci cw*length*d<sub>0</sub><sup>1.5</sup> altfel cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) unde d<sub>1</sub> și d<sub>0</sub> sunt întotdeauna pozitive sau zero';
// Orifice Flow
$ec_lang['or_main_menu']='Debit prin Orificiu';
$ec_lang['or_main_title']='Calculator Gratuit Online pentru Debitul prin Orificiu';
$ec_lang['or_main_desc']='Debit prin Orificiu — Liber sau Înecat';
$ec_lang['or_shape']='Forma deschiderii';
$ec_lang['or_shape_circular']='Circulară';
$ec_lang['or_shape_rectangular']='Dreptunghiulară';
$ec_lang['or_diameter']='<span class="ec-help" title="Diametru pentru circular; înălțime pentru dreptunghiular">Diametru sau înălțime, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="Numai deschideri dreptunghiulare">Lățime, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="Fundul deschiderii">Cota radierului <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='Nivelul apei amonte';
$ec_lang['or_twe']='Nivelul apei aval';
$ec_lang['or_cd']='Coeficient de debit, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Cota centroidului';
$ec_lang['or_head']='<span class="ec-help" title="Energie pe unitatea de greutate a apei — o înălțime a coloanei de apă, nu o presiune">Sarcină efectivă, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='Aria deschiderii, A';
$ec_lang['or_regime']='Verificarea regimului de orificiu';
$ec_lang['or_regime_valid']='Curgere liberă';
$ec_lang['or_regime_submerged']='Orificiu înecat';
$ec_lang['or_regime_submerged_tip']='TWE deasupra centroidului — regimul de orificiu rămâne valid';
$ec_lang['or_regime_warn']='În afara regimului de orificiu';
$ec_lang['or_regime_warn_tip']='Nivelul apei amonte este sub coronamentul (partea superioară a) deschiderii';
$ec_lang['or_regime_twe_above_hwe']='Verificați datele de intrare';
$ec_lang['or_regime_twe_above_hwe_tip']='Nivelul apei aval (TWE) depășește nivelul apei amonte (HWE)';
$ec_lang['or_notes_1_term']='Ecuația orificiului';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Pentru curgere liberă: h = HWE &minus; centroid. Pentru curgere înecată (TWE deasupra radierului): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regimul orificiului';
$ec_lang['or_notes_2_def']='Ecuațiile de debit prin orificiu se aplică atunci când suprafața apei din amonte este deasupra coronamentului (partea superioară) deschiderii. Când nivelul din amonte este sub coronament, utilizați în schimb o ecuație de deversor.';
$ec_lang['or_notes_3_term']='Coeficient de debit';
$ec_lang['or_notes_3_def']='C<sub>d</sub> variază de la aproximativ 0,60&ndash;0,65 pentru orificii cu muchii ascuțite. Intrările rotunjite sau reintrante folosesc valori diferite. Consultați <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> sau Manualul de Referință Hidraulică HEC-RAS pentru îndrumări.';
$ec_lang['or_notes_4_term']='Înecare';
$ec_lang['or_notes_4_def']='Când TWE este deasupra radierului deschiderii, acest calculator aplică automat ecuația orificiului înecat folosind h = HWE &minus; TWE. Când TWE este la nivelul radierului sau sub acesta, se presupune curgere liberă și h = HWE &minus; centroid.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hidroenergie';
$ec_lang['mhp_main_title']='Calculator gratuit online de micro-hidroenergie';
$ec_lang['mhp_main_desc']='Calculator de putere pentru micro-hidrocentrale la cursul apei (fără baraj)';
$ec_lang['mhp_gross_head']='Cădere brută, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="Diametrul conductei sub presiune (conducta de alimentare)">Diametrul conductei sub presiune, D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='Lungimea, L';
$ec_lang['mhp_efficiency']='Randamentul centralei, η (0–1)';
$ec_lang['mhp_vel_check']='Verificarea vitezei';
$ec_lang['mhp_hl_check']='Verificarea pierderii de sarcină';
$ec_lang['mhp_hnet']='Cădere netă, H<sub>net</sub>';
$ec_lang['mhp_power']='Putere produsă, P';
$ec_lang['mhp_annual_kwh']='Energie anuală la 100% capacitate';
$ec_lang['mhp_vel_low']='Viteză mică — risc de sedimentare și antrenare de aer.';
$ec_lang['mhp_vel_high']='Viteză ridicată — verificați pierderile la tranziții, energia disponibilă și lovitura de berbec.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Ridicată';
$ec_lang['mhp_vel_low_short']='Mică';
$ec_lang['mhp_vel_ok_tip']='Viteza se află în intervalul eficient pentru proiectarea conductei sub presiune.';
$ec_lang['mhp_hl_ok_tip']='În limita țintei de 10% — economic.';
$ec_lang['mhp_hl_warn_tip']='Depășește ținta de 10%. Luați în considerare o conductă mai mare.';
$ec_lang['mhp_hl_bad_tip']='Depășește ținta de 20%. Redimensionați conducta.';
$ec_lang['mhp_notes_1_term']='Pierdere de sarcină';
$ec_lang['mhp_notes_1_def']='Pierderea totală h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, unde h<sub>f</sub> = f(L/D)(v²/2g) este pierderea prin frecare Darcy-Weisbach, iar h<sub>m</sub> = k<sub>m</sub>·v²/2g acoperă intrarea, coturile și armăturile. Căderea netă H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Viteză';
$ec_lang['mhp_notes_2_def']='Verificați dacă viteza este rezonabilă pentru căderea disponibilă și costul conductei. O viteză foarte mică poate indica o conductă supradimensionată; o viteză foarte mare poate crește pierderile prin frecare și riscul de lovitură de berbec.';
$ec_lang['mhp_notes_3_term']='Ținta pierderilor de sarcină';
$ec_lang['mhp_notes_3_def']='Pierderile din conducta sub presiune, sub 10% din căderea brută, sunt în general economice. Compromisul optim între costul conductei și puterea pierdută se situează adesea în jurul a 4–6% pentru siturile cu electricitate de mare valoare.';
$ec_lang['mhp_notes_6_term']='Randament';
$ec_lang['mhp_notes_6_def']='Randamentul tipic al centralei η variază între 0,70 și 0,85 pentru turbinele Pelton și cu flux încrucișat comune în micro-hidroenergie. Utilizați 0,75 ca primă estimare conservatoare.';
$ec_lang['mhp_notes_7_term']='Energie anuală';
$ec_lang['mhp_notes_7_def']='Energia anuală presupune funcționare continuă la debit maxim (8.760 de ore/an). Producția reală va fi mai mică din cauza variației sezoniere a debitului, întreruperii pentru întreținere și factorului de sarcină.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Timp de Golire a Iazului și Rezervorului';
$ec_lang['odt_main_title']='Calculator Gratuit Online Timp de Golire a Iazului, Bazinului și Rezervorului (Orificiu)';
$ec_lang['odt_main_desc']='Timp de Golire a Iazului, Bazinului sau Rezervorului &mdash; Evacuare prin Orificiu, Metoda Volumului Conic';
$ec_lang['odt_h1_elev']='Cota inițială a suprafeței apei';
$ec_lang['odt_a1']='Aria inițială, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Cota finală a suprafeței apei';
$ec_lang['odt_a0']='Aria la nivelul orificiului, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="Interpolată din modelul conic la cota finală">Aria finală, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='Verificarea cotei finale';
$ec_lang['odt_h2_ok']='Cota finală deasupra vârfului orificiului';
$ec_lang['odt_h2_warn']='Cota finală la nivelul sau sub vârful orificiului';
$ec_lang['odt_h2_warn_tip']='Vârful orificiului = centroid + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="Diametru (circular) sau înălțime (dreptunghiular)">D orificiu <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="Numai dreptunghiular">Lățimea orificiului, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='Timp de golire (s)';
$ec_lang['odt_t_min']='Timp de golire (min)';
$ec_lang['odt_t_hr']='Timp de golire (ore)';
$ec_lang['odt_t_day']='Timp de golire (zile)';
$ec_lang['odt_notes_1_term']='Formulă';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) dă timpul de golire de la sarcina H până la orificiu. Timp de golire = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), unde H<sub>1</sub> = cota inițială &minus; cota orificiului, H<sub>2</sub> = cota finală &minus; cota orificiului.';
$ec_lang['odt_notes_2_term']='Metodă';
$ec_lang['odt_notes_2_def']='Metoda volumului conic modelează iazul sau bazinul ca o secțiune conică între aria inițială A<sub>1</sub> la suprafața inițială a apei și aria A<sub>0</sub> la cota centroidului orificiului. A<sub>2</sub>, aria iazului la cota finală, este interpolată din A<sub>1</sub> și A<sub>0</sub> folosind modelul secțiunii conice. Timpul de golire de la cota inițială la cea finală este egal cu timpul total de golire de la H<sub>1</sub> la orificiu minus timpul rămas de golire de la H<sub>2</sub> la orificiu.';
$ec_lang['odt_h1']='<span class="ec-help" title="Cota inițială a suprafeței apei minus cota centroidului orificiului">Sarcina inițială, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='Debit maxim, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volum golit';
$ec_lang['odt_sketch_start']='Început';
$ec_lang['odt_sketch_end']='Sfârșit';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Irigare';
$ec_lang['irr_main_title']='Calculatoare Online Gratuite pentru Măsurarea Debitului de Irigare';
$ec_lang['irr_main_desc']='Măsurarea Debitului de Irigare — Deversoare și Orificii';
$ec_lang['irr_intro_html']='<p>Deversorele și orificiile sunt instrumentele standard de teren pentru măsurarea debitului de apă în sistemele de irigații. Selectați calculatorul care corespunde structurii dvs.:</p>';
$ec_lang['irr_card_weir_uniform_head']='Deversor — Prag Lat (Lățime Uniformă)';
$ec_lang['irr_card_weir_uniform_desc']='Măsurați debitul peste creasta unui baraj de derivație, a unui stăvilar de control, sau a unei plăci deversoare. Introduceți lungimea deversorului și adâncimea apei în amonte deasupra crestei.';
$ec_lang['irr_card_weir_irregular_head']='Deversor — Profil Neregulat';
$ec_lang['irr_card_weir_irregular_desc']='Utilizați atunci când creasta deversorului variază ca elevație sau profil — preaplinuri naturale, structuri de cădere cu lățime variabilă sau structuri de control cu mai multe secțiuni.';
$ec_lang['irr_card_orifice_head']='Orificiu — Vană de Cap sau Branșament de Conductă';
$ec_lang['irr_card_orifice_desc']='Măsurați debitul printr-o vană glisantă, un branșament de conductă sau orificiul unui podeț. Gestionează automat atât descărcarea liberă, cât și condițiile înecate (apă din aval).';
$ec_lang['irr_card_canal_head']='Proiectarea &amp; Analiza Canalului';
$ec_lang['irr_card_canal_desc']='Proiectați sau verificați un canal de irigații utilizând formula Manning. Folosiți calculatorul Trapezoidal pentru canale noi; calculatorul Neregulat pentru secțiuni naturale sau construite existente.';
$ec_lang['irr_card_seepage_head']='Infiltrația Canalului &amp; Eficiența de Transport';
$ec_lang['irr_card_seepage_desc']='Estimați pierderile prin infiltrație dintr-un tronson de canal folosind măsurătorile de influx și eflux. Calculați eficiența de transport și volumul anual de apă pierdut pentru a ajuta la prioritizarea investițiilor în căptușire.';
$ec_lang['irr_quickref_html']='<h3>Referință Rapidă</h3><dl><dt>Baraj de derivație sau stăvilar de control</dt><dd>Măsurați adâncimea apei în amonte deasupra crestei deversorului. Utilizați <a href="Weir-Flow-Simple.php">Deversor Simplu</a> pentru o creastă uniformă, sau <a href="Weir-Flow-Irregular.php">Deversor Neregulat</a> pentru o creastă profilată sau în trepte.</dd><dt>Vană de cap sau branșament de conductă</dt><dd>Măsurați cota apei în amonte și cota apei în aval (sau cota radierului dacă descărcarea este liberă). Utilizați <a href="Orifice.php">Debit prin Orificiu</a>. Pentru o conductă circulară, D&nbsp;= diametrul conductei; pentru o vană dreptunghiulară, introduceți lățimea W și înălțimea D.</dd><dt>Timpul de golire a unui rezervor sau iaz</dt><dd>Utilizați <a href="Orifice-Drain-Time.php">Timp de Golire prin Orificiu</a> pentru a estima cât timp durează coborârea nivelului unui iaz sau rezervor printr-un orificiu de fund — util pentru planificarea stocării apei de irigație.</dd><dt>Standarde de teren</dt><dd>Ecuațiile de debit pentru deversor și orificiu utilizate aici corespund procedurilor din USBR <em>Water Measurement Manual</em> (ediția a 3-a), solicitate frecvent de administratorii de apă și districtele de irigații.</dd></dl>';
$ec_lang['irr_card_pressure_head']='Presiune de Irigație &amp; Uniformitate';
$ec_lang['irr_card_pressure_desc']='Modelați profilul de presiune și debit de-a lungul unei ramuri principal-lateral-emițător pentru a estima uniformitatea distribuției din presiunea reală a căii test, nu doar dintr-un debit de catalog al emițătorului.';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Distanța dintre emițătoare, S<sub>e</sub>';
$ec_lang['ip_sl']='Distanța dintre laterale, S<sub>l</sub>';
$ec_lang['ip_n_e']='Emițătoare per lateral, n<sub>e</sub>';
$ec_lang['ip_n_l']='Laterale per zonă, n<sub>l</sub>';
$ec_lang['ip_d']='Adâncimea țintă de aplicare, d';
$ec_lang['ip_a_e']='Suprafața per emițător, A<sub>e</sub>';
$ec_lang['ip_pr']='Rata de aplicare, PR';
$ec_lang['ip_q_lat']='Debit pe lateral, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Debitul zonei, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Timp de funcționare (ore)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Infiltrația Canalului';
$ec_lang['cs_main_title']='Calculator Online Gratuit pentru Pierderi prin Infiltrație și Eficiența de Transport a Canalului';
$ec_lang['cs_main_desc']='Pierderi prin Infiltrație &amp; Eficiența de Transport a Canalului — Metoda Influx-Eflux';
$ec_lang['cs_Q_in']='Influx, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Eflux, Q<sub>out</sub>';
$ec_lang['cs_L']='Lungimea tronsonului, L';
$ec_lang['cs_Q_loss']='Rata de pierderi prin infiltrație, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verificare măsurători';
$ec_lang['cs_pct_loss']='Fracție pierdută';
$ec_lang['cs_Ec']='Eficiența de transport, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Clasificare eficiență';
$ec_lang['cs_Vol_day']='Volum pierdut zilnic';
$ec_lang['cs_Vol_year']='Volum pierdut anual';
$ec_lang['cs_Q_loss_per_L']='Pierdere pe unitate de lungime, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valoarea apei';
$ec_lang['cs_lining_cost']='Costul căptușelii';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="Obiectiv de eficiență a transportului după căptușire; fracție 0–1">Obiectiv de căptușeală, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='Suprafață căptușeală, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valoare anuală pierdută';
$ec_lang['cs_annual_value_recovered']='Valoare anuală recuperată';
$ec_lang['cs_lining_total_cost']='Costul total al căptușelii';
$ec_lang['cs_payback_years']='<span class="ec-help" title="Amortizare simplă = costul total al căptușelii ÷ valoarea anuală recuperată">Perioadă de amortizare <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — infiltrație detectată';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — fără pierdere măsurabilă';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — verificați măsurătorile';
$ec_lang['cs_Ec_good']='Bun — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='Satisfăcător — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='Slab — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='Metoda influx-eflux estimează infiltrația prin măsurarea debitului la intrarea și ieșirea unui tronson de canal: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Eficiența de transport E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Volumul anual presupune funcționare continuă la debit maxim; pierderea reală este mai mică pentru canale sezoniere sau cu debit parțial.';
$ec_lang['cs_notes_2_term']='Clasificarea eficienței';
$ec_lang['cs_notes_2_def']='Canale de pământ necăptușite tipice: E<sub>c</sub> = 60–80%. Canale de pământ bine întreținute: 75–85%. Canale cu căptușeală din beton: 90–98%. Pierderi prin infiltrație peste 30% din debitul de intrare justifică adesea o investiție în căptușire. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Amortizarea Căptușelii';
$ec_lang['cs_notes_3_def']='Introduceți valoarea apei și costul căptușelii în orice monedă consistentă. Suprafață căptușeală = lungimea tronsonului × perimetrul udat — perimetrul udat al secțiunii transversale a canalului la adâncimea de curgere măsurată (lățimea fundului plus ambii taluzi udați). Valoarea anuală recuperată presupune că canalul căptușit atinge în mod continuu E<sub>c</sub> țintă. Amortizarea reală va fi mai lungă pentru canale sezoniere sau dacă căptușeala nu atinge eficiența țintă.';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, ediția a 3-a (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='Despre';
$ec_lang['install_main_menu']='Instalare';
$ec_lang['install_main_title']='Instalează EngCalcs';
$ec_lang['install_main_desc']='Adaugă pe dispozitiv pentru utilizare offline';
$ec_lang['install_intro']='EngCalcs este o aplicație web progresivă (PWA). Odată instalată, toate calculatoarele funcționează complet offline — nu este nevoie de conexiune la internet.';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Deschideți orice pagină de calculator în Chrome.</li><li>Atingeți butonul <strong>⬇ Instalare</strong> din bara de navigare de sus sau atingeți meniul browserului (⋮) și alegeți <strong>Adăugare pe ecranul de start</strong>.</li><li>Atingeți <strong>Instalare</strong> în fereastra care apare.</li><li>EngCalcs apare pe ecranul de start și funcționează offline.</li>';
$ec_lang['install_now_btn']='⬇ Instalează acum';
$ec_lang['install_prompt_unavailable']='Fereastra de instalare nu este disponibilă — folosiți meniul browserului.';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Deschideți orice pagină de calculator în Safari.</li><li>Atingeți butonul <strong>Distribuire</strong> (pătrat cu săgeată în sus).</li><li>Derulați în jos și atingeți <strong>Adăugare pe ecranul de pornire</strong>.</li><li>Atingeți <strong>Adaugă</strong>. EngCalcs apare pe ecranul de start.</li>';
$ec_lang['install_ios_note']='Pe iOS, instalarea se face întotdeauna prin meniul Distribuire — nu există o fereastră automată de instalare.';
$ec_lang['install_desktop_heading']='Computer (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>Deschideți orice pagină de calculator.</li><li>Faceți clic pe <strong>pictograma de instalare</strong> (⊕ sau pictograma unui computer) din bara de adrese a browserului sau deschideți meniul browserului și alegeți <strong>Instalare EngCalcs…</strong></li><li>Faceți clic pe <strong>Instalare</strong>. EngCalcs se deschide ca o aplicație independentă.</li>';
$ec_lang['install_firefox_heading']='Firefox / Alte browsere';
$ec_lang['install_firefox_body']='Firefox nu permite instalarea aplicațiilor PWA pe desktop. Puteți folosi în continuare toate calculatoarele normal în browser — după prima vizită, paginile sunt salvate automat în memoria cache pentru utilizare offline.';
$ec_lang['install_cached_heading']='Ce este salvat în memoria cache';
$ec_lang['install_cached_body']='La prima instalare a EngCalcs, toate paginile calculatoarelor și fișierele lor suport (scripturi, stiluri) sunt salvate automat pe dispozitivul dvs. După aceea, totul funcționează fără conexiune la internet. Limba aleasă este reținută de la ultima vizită online.';
$ec_lang['contact_main_menu']='Contacteaza';
$ec_lang['about_main_title']='Despre calculatoarele de inginerie HawsEDC';
$ec_lang['about_main_desc']='Misiune, sursă deschisă și contribuții';
$ec_lang['about_body_html']='<h3>Misiune</h3><p>Calculatoarele de Inginerie HawsEDC există pentru a servi ingineri și muncitori de teren din întreaga lume — în special cei care lucrează în regiuni cu deficit de apă, resurse limitate sau insuficient deservite. Aceste instrumente fac parte dintr-o misiune umanitară mai amplă: să spună fiecărui om în cel mai practic și eficient mod posibil că este iubit și prețuit pentru totdeauna, că nu are nimic de care să se teamă și că nu va ruina totul.</p><p>Calculatoarele sunt vehiculul. Destinația este o lume fără suferință.</p><h3>Licență Open Source</h3><p>Tot codul este publicat sub <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 sau mai nou</a> — liber ca în libertate. Puteți utiliza, studia, modifica și redistribui codul în aceleași condiții.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Cod Sursă</h3><p>Codul sursă complet este disponibil public pe Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Puteți răsfoi codul, semnala probleme sau face fork la depozit acolo.</p><h3>Contribuție</h3><p>Pull request-urile sunt binevenite. Modalități de contribuție:</p><ul><li><strong>Traduceri</strong> — îmbunătățiți sau adăugați o limbă. Deschideți un pull request cu modificări în fișierul <code>lib/lang.ec.??.php</code> relevant.</li><li><strong>Rapoarte de erori</strong> — utilizați formularul de feedback pe orice pagină de calculator sau semnalați o problemă pe Bitbucket.</li><li><strong>Calculatoare noi</strong> — ideile pentru instrumente de inginerie hidraulică care servesc lucrătorilor de teren și practicienilor în irigații sunt deosebit de binevenite. Consultați ghidul pentru dezvoltatori <code>CLAUDE.md</code> din depozit.</li><li><strong>Găzduire</strong> — dacă puteți oglindi aceste calculatoare pentru o regiune cu conectivitate limitată, vă rugăm să ne contactați.</li></ul><h3>Utilizare offline</h3><p>Aceste calculatoare funcționează ca o Aplicație Web Progresivă (PWA). Vizitați orice pagină de calculator în timp ce sunteți conectat la internet, iar browserul dvs. va stoca automat toate calculatoarele în cache. După aceea, toate calculatoarele funcționează offline — nu este necesar internetul.</p><p>Pe Android sau iOS, folosiți opțiunea „Adaugă pe ecranul principal" din browserul dvs. pentru a instala EngCalcs ca aplicație pe dispozitivul dvs. Pe desktop, căutați pictograma de instalare în bara de adrese a browserului.</p><p>Puteți, de asemenea, să salvați orice calculator individual folosind meniul „Salvare ca…" din browser pentru utilizare offline ocazională.</p><h3>Contact</h3><p>Tom Haws — inginer hidraulic și autorul acestor calculatoare.<br />Folosiți formularul de feedback pe orice pagină de calculator sau accesați codul sursă pe <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Contact HawsEDC';
$ec_lang['contactSendMessage']='Trimiteți un mesaj lui Tom Haws';
$ec_lang['contactYourName']='Numele dumneavoastră:';
$ec_lang['contactYourEmail']='Adresa dumneavoastră de e-mail:';
$ec_lang['contactSubject']='Subiect:';
$ec_lang['contact_message']='Mesaj:';
$ec_lang['contactSpamPrefix']='Cinci plus unu este egal cu';
$ec_lang['contactSpamPostfix']='(Vă rugăm să scrieți cu litere. 1=unu 2=doi 3=trei 4=patru 5=cinci 6=șase 7=șapte +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Trimiteți Mesajul';
$ec_lang['contact_success']='Mulțumesc că ați luat timp pentru a scrie.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Proiectarea Canalului Rapid de Anrocament (Robinson)';
$ec_lang['rc_main_title']='Calculator Online Gratuit pentru Proiectarea Canalului Rapid de Anrocament — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionarea Pietrei de Protecție a Canalului Rapid — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Panta fundului canalului rapid, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="Debitul pe unitate de lățime la intrarea în canalul rapid. Pentru un canal cu lățimea fundului B și debitul total Q, utilizați q_t = Q / B.">Debit unitar total, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='Porozitatea pietrei de protecție, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="Densitate relativă la apă. Granit sau bazalt concasat tipic ≈ 2,65. Interval valid Robinson: 2,54–2,82.">Densitatea relativă a rocii, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="Abaterea standard a granulozității. Piatră uniformă ≈ 1,25. Interval valid Robinson: 1,15–1,47.">Granulozitate SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="Înălțarea (Hp > yn) este benefică — reduce eroziunea în amonte. (USDA)">Adâncimea normală în canalul de intrare, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="Ec. 1 (S0 < 0.10) sau Ec. 2 (0,10–0,40). Valid: D50 15–278 mm, S0 0,02–0,40. În afara intervalului: extrapolat.">Dimensiunea mediană necesară a pietrei, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='Ecuație aplicată';
$ec_lang['rc_sg_check']='Verificare densitate relativă';
$ec_lang['rc_SD_check']='Verificare granulozitate SD';
$ec_lang['rc_sg_ok']='sg în intervalul valid';
$ec_lang['rc_sg_ok_tip']='2,54–2,82 (Robinson)';
$ec_lang['rc_sg_low']='sg sub intervalul Robinson';
$ec_lang['rc_sg_low_tip']='Interval valid: 2,54–2,82';
$ec_lang['rc_sg_high']='sg peste intervalul Robinson';
$ec_lang['rc_sg_high_tip']='Interval valid: 2,54–2,82';
$ec_lang['rc_SD_ok']='SD în intervalul valid';
$ec_lang['rc_SD_ok_tip']='1,15–1,47 (Robinson)';
$ec_lang['rc_SD_low']='SD sub intervalul Robinson';
$ec_lang['rc_SD_low_tip']='Interval valid: 1,15–1,47';
$ec_lang['rc_SD_high']='SD peste intervalul Robinson';
$ec_lang['rc_SD_high_tip']='Interval valid: 1,15–1,47';
$ec_lang['rc_layer']='Grosimea stratului de piatră (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Raza curbei la coronamentul superior (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Lungimea arcului curbei la coronament';
$ec_lang['rc_apron_length']='<span class="ec-help" title="Necesară pentru susținerea structurală a pietrei canalului rapid. &quot;Nivelul minim de apă din aval, rezultat din tronsonul de ieșire și din rezistența canalului din aval, este suficient pentru a asigura stabilitatea pietrei de protecție în tronsonul de ieșire.&quot; (Robinson)">Lungimea radierului de ieșire (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='Rugozitatea Manning în canalul rapid, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="Fracțiunea din qt care curge prin porii pietrei de protecție. Restul qs curge la suprafață. Implicit np = 0,45 pentru piatră concasată cu muchii ascuțite.">Viteza prin mantaua de piatră, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='Debit unitar prin mantaua de piatră, q<sub>m</sub>';
$ec_lang['rc_qs']='Debit unitar la suprafață, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Adâncimea curgerii deasupra suprafeței pietrei, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="Înălțarea (Hp > yn) este benefică — reduce eroziunea în amonte. (USDA)">Sarcina hidraulică la intrare, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='Verificare înălțare la intrare';
$ec_lang['rc_pond_ok']='H<sub>p</sub> > y<sub>n</sub> — înălțare în amonte';
$ec_lang['rc_pond_ok_tip']='Înălțarea în amonte de intrarea canalului rapid este benefică; reduce eroziunea în amonte. (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — fără înălțare — risc de eroziune la intrare';
$ec_lang['rc_pond_warn_tip']='Nu există înălțare în amonte de intrarea canalului rapid; poate apărea eroziune în amonte. (USDA)';
$ec_lang['rc_eq1']='Ec. 1 (S<sub>0</sub> < 0,10) — pantă lină';
$ec_lang['rc_eq2']='Ec. 2 (0,10 ≤ S<sub>0</sub> ≤ 0,40) — pantă abruptă';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0,02 — sub intervalul de validare Robinson';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0,40 — peste intervalul de validare Robinson';
$ec_lang['rc_notes_1_term']='Ecuații de dimensionare a pietrei';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) au elaborat două ecuații empirice pentru dimensiunea mediană a pietrei de protecție D<sub>50</sub> pe baza pantei canalului rapid și a debitului unitar. Ecuația 1 se aplică pentru pante line (S<sub>0</sub> < 0,10); Ecuația 2 se aplică pentru pante abrupte (0,10 ≤ S<sub>0</sub> ≤ 0,40). Ambele ecuații necesită q<sub>t</sub> în m²/s și returnează D<sub>50</sub> în mm. Intervalul validat este 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Debitul unitar';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> este debitul unitar total la coronamentul canalului rapid (debit total pe unitate de lățime). Pentru un canal cu lățimea fundului B și debitul total Q, se poate aproxima q<sub>t</sub> ≈ Q / B, sau se poate calcula din condiția adâncimii critice la intrarea în canalul rapid.';
$ec_lang['rc_notes_3_term']='Curgerea prin mantaua de piatră';
$ec_lang['rc_notes_3_def']='O fracțiune din debitul total se deplasează prin porii pietrei de protecție (debitul prin mantaua q<sub>m</sub>); restul curge la suprafața pietrei (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Adâncimea de curgere d se calculează din ecuația lui Manning aplicată debitului de suprafață q<sub>s</sub> cu rugozitatea canalului rapid n. Porozitatea implicită n<sub>p</sub> = 0,45 este tipică pentru piatra concasată cu muchii ascuțite.';
$ec_lang['rc_notes_5_term']='Intervalul valid al dimensiunii pietrei';
$ec_lang['rc_notes_5_def']='Ecuațiile au fost elaborate pentru un interval D<sub>50</sub> de 15 mm până la 278 mm. Rezultatele în afara acestui interval sunt extrapolate și trebuie utilizate cu judecată inginerească suplimentară.';
$ec_lang['rc_notes_6_term']='Cota radierului de ieșire';
$ec_lang['rc_notes_6_def']='Cota suprafeței superioare a pietrei de protecție în zona de ieșire trebuie să fie la sau sub cota fundului canalului aval. Dacă este mai ridicată, piatra de protecție de la ieșire va fi instabilă.';
$ec_lang['rc_notes_7_def']='Când adâncimea normală în canalul de intrare este mai mică decât sarcina hidraulică (H<sub>p</sub>) necesară pentru a evacua q<sub>t</sub>, apare restricție de debit sau înălțare în amonte de intrarea în canal. Aceasta este în general acceptabilă — înălțarea reduce viteza și previne eroziunea în amonte. Verificare: utilizați un calculator de deversor pentru a determina H<sub>p</sub> pentru q<sub>t</sub> și lățimea crestei date, și comparați cu adâncimea normală a canalului de intrare. Dacă H<sub>p</sub> depășește adâncimea normală, va apărea înălțare.';
$ec_lang['rc_notes_4_term']='Referință';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS publică, de asemenea, un <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">tabel Excel</a> bazat pe aceeași metodă.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtru';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curbă de coronament';
$ec_lang['rc_sketch_outlet_apron']    = 'Radier de ieșire';
$ec_lang['rc_sketch_radius']          = 'rază';
// Irrigation Pressure (ip_ prefix)
$ec_lang['ip_main_menu']='Presiune Irigație';
$ec_lang['ip_main_title']='Calculator Online Gratuit pentru Presiunea de Irigație &amp; Uniformitatea Distribuției';
$ec_lang['ip_main_desc']='Presiunea Ramurii Test și Estimarea Uniformității';
$ec_lang['ip_h_supply']='Presiune de alimentare';
$ec_lang['ip_elev_supply']='Cota de alimentare, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Debit de proiectare al emițătorului, q<sub>design</sub>';
$ec_lang['ip_h_design']='Presiune de proiectare a emițătorului';
$ec_lang['ip_x']='<span class="ec-help" title="0,5 pentru emițători standard necompensați; aproape de 0 pentru emițători cu compensare de presiune">Exponentul de debit al emițătorului, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='Calea test';
$ec_lang['ip_group_reach']='Tronson';
$ec_lang['ip_group_upstream']='Amonte';
$ec_lang['ip_group_downstream']='Aval';
$ec_lang['ip_group_loss']='Pierdere';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="Bifat: acest tronson este un segment al lateralului test, din care emițătorii individuali preiau apă. Nebifat: acest tronson este o conductă principală, transmițând doar debit către laterale care nu sunt pe calea test.">Lat. <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="Rânduri laterale: emițători doar în acest tronson. Rânduri principale: total emițători pe laterale ALTELE decât acesta, care se ramifică din acest tronson. Pentru tronsonul liniei principale care se termină la linia lateralului test, aceasta include și orice laterale dincolo de acel punct de-a lungul principalului, sau care împart aceeași joncțiune (de ex. un lateral de partea opusă) &mdash; debitul lor se ramifică tot din acest tronson.">Emițători <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="Cota capătului aval al acestui tronson. Opțional pe rândurile interioare (implicit plat / la fel ca nodul de deasupra dacă se lasă gol). Necesară pe rândul final: acea valoare este cota ultimului emițător, care stabilește direct presiunea de alimentare necesară.">Cota Aval <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='Cota ultimului emițător (rândul final) a fost lăsată goală și s-a setat implicit la plat &mdash; introduceți-o pentru un rezultat exact';
$ec_lang['ip_flow']='Debit';
$ec_lang['ip_press']='Pres.';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="Pierderea totală a tronsonului, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='Presiune scăzută/negativă — verificați condițiile subatmosferice';
$ec_lang['ip_pressure_warn_short']='Scăzută';
$ec_lang['ip_pressure_high']='Presiune ridicată — necesită reducerea presiunii';
$ec_lang['ip_pressure_high_short']='Ridicată';
$ec_lang['ip_max_head']='Sarcină max. adm. conductă';
$ec_lang['ip_max_head_tip']='Tronsoanele a căror presiune depășește această valoare sunt semnalate. Lăsați necompletat pentru a omite verificarea presiunii ridicate.';
$ec_lang['ip_h_far']='Presiunea ultimului emițător';
$ec_lang['ip_q_supply']='<span class="ec-help" title="Debitul care intră doar în calea test modelată &mdash; pentru întreaga zonă/sistem, vezi Q_zone în Proiectarea Aplicației de mai jos.">Debitul de alimentare al căii test, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='Debitul ultimului emițător, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Debitul mediu al emițătorului (lateralul test), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="Cât de mult mai mare (sau mai mic) estimați că funcționează un lateral tipic în comparație cu acest lateral test. Lateralul test este presupus în mod deliberat cazul cel mai defavorabil, deci media sa proprie subestimează media de teren &mdash; lăsat la 0, verificarea uniformității și cifrele de proiectare a aplicației de mai jos folosesc media proprie a lateralului test (probabil optimistă) ca atare.">Est. &Delta;presiune, medie vs. lateralul test <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral reevaluat la presiunea fiecărui rând lateral, plus diferența de presiune introdusă mai sus &mdash; o încercare de a corecta faptul că lateralul test este presupus a fi cazul cel mai defavorabil, nu unul reprezentativ. Alimentează atât verificarea uniformității, cât și secțiunea de proiectare a aplicației de mai jos.">Est. debitul mediu al emițătorului pe teren, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="Debitul calculat al ultimului emițător împărțit la debitul mediu estimat al emițătorului pe teren &mdash; aceasta este o aproximare a Uniformității Distribuției de sfert inferior standard (media grupului inferior ÷ media populației); provine dintr-un eșantion modelat mic și o corecție estimată de utilizator, nu dintr-un eșantion statistic complet de teren. Valorile la sau peste 1 sunt posibile și valide: înseamnă doar că presiunea ultimului emițător este la sau peste media estimată de teren, deci un alt emițător este punctul de presiune minimă. Aceasta se poate datora faptului că ultimul emițător se află pe teren jos sau că estimarea &Delta;presiune este prea mică.">Verificarea uniformității, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='Presiunea la emițătorul test ≥ presiunea de alimentare. Acesta probabil nu este emițătorul de caz cel mai defavorabil, sau conductele ar putea fi micșorate.';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="Aceasta este diferită de aproximarea noastră a măsurii standard de uniformitate.">Debitul ultimului emițător ÷ debitul de proiectare, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='Fără soluție: presiunea de alimentare necesară depășește presiunea de alimentare introdusă. Măriți presiunea de alimentare, reduceți cererea sau utilizați o conductă mai mare.';
$ec_lang['ip_notes_1_def']='Estimează presiunea la ultimul (cel mai îndepărtat) emițător, apoi retrasează Linia Energetică înapoi către alimentare, tronson cu tronson, adăugând pierderi prin frecare și pierderi locale pe parcurs. Elevația și sarcina de viteză sunt scăzute la fiecare nod pentru a raporta presiunea reală acolo. Presiunea estimată la capătul îndepărtat este ajustată (prin bisecție) până când presiunea de alimentare calculată necesară corespunde cu presiunea de alimentare introdusă &mdash; aceeași problemă cu buclă închisă abordată de rezolvatorul curgerii în conductă din calculatorul Manning Pipe Flow, extinsă la o rețea ramificată.';
$ec_lang['ip_notes_2_term']='Tronsoane Principale vs. Laterale';
$ec_lang['ip_notes_2_def']='Fiecare rând este un tronson de-a lungul singurei căi hidraulic celei mai defavorabile (calea test) de la alimentare până la ultimul emițător. Un tronson Principal transmite debit doar către laterale care nu sunt pe calea test, deci extragerea sa este o simplă multiplicare (debitul de proiectare &times; numărul total de emițători ai tronsonului) &mdash; fără sensibilitate la presiunea locală. Conducta principală este o conductă trunchi partajată, deci tronsonul liniei principale care se termină la linia lateralului test trebuie să includă nu doar laterale între propriile sale capete, ci și orice laterale aflate mai departe de-a lungul principalului dincolo de acel punct, sau care împart aceeași joncțiune (de ex. un lateral de partea opusă) &mdash; debitul lor trece prin acest tronson înainte de a se ramifica, indiferent dacă apar sau nu în altă parte a acestui tabel. Un tronson Lateral este un segment al lateralului test propriu-zis: debitul emițătorului se calculează din presiunea locală reală via q = k·H<sup>x</sup>, iar pierderea prin frecare este redusă cu factorul F(n) al lui Christiansen pentru a ține cont de scăderea debitului pe măsură ce fiecare emițător din tronson preia apă.';
$ec_lang['ip_notes_3_term']='Limitări';
$ec_lang['ip_notes_3_def']='Modelează o singură presiune de alimentare fixă (fără curbă de pompă), o singură cale test (nu întregul teren), și o curbă a emițătorului cu 2 parametri (setați exponentul aproape de 0 pentru a aproxima un emițător cu compensare de presiune). Sunt raportate două rapoarte de uniformitate diferite, păstrate deliberat separate: q<sub>last</sub>/q<sub>avg,field</sub> este o aproximare a Uniformității Distribuției de sfert inferior standard (media grupului inferior ÷ media populației); dar aceasta provine dintr-un eșantion modelat mic și o corecție estimată de utilizator, în loc de eșantionul statistic complet de teren standard. De asemenea, lateralul test este presupus în mod deliberat a fi cazul cel mai defavorabil, deci media sa brută, necorectată, ar subestima media reală de teren și ar face uniformitatea să pară mai bună decât este; intrarea &Delta;presiune există special pentru a contracara această denaturare. Valorile de uniformitate la sau peste 1 sunt totuși posibile: ele înseamnă doar că presiunea ultimului emițător este la sau peste media estimată de teren, deci un alt emițător este punctul de presiune minimă. Aceasta se poate datora faptului că ultimul emițător se află pe teren jos sau că estimarea &Delta;presiune este prea mică. q<sub>last</sub>/q<sub>design</sub> este o verificare diferită, non-uniformitate, față de debitul nominal al fabricantului &mdash; utilă pentru detectarea unui sistem supra- sau subpresurizat în ansamblu, dar este o verificare separată, de citit alături de cifra de uniformitate, deoarece debitul de proiectare/nominal este independent de presiunea medie reală de funcționare a sistemului.';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; Buletin 670 al Stației de Experiment Agricol California. Standardele ASAE/ASABE pentru proiectarea microirigației folosesc aceeași abordare a pierderii prin frecare cu ieșiri multiple.';
$ec_lang['ip_notes_5_term']='Proiectarea Aplicației';
$ec_lang['ip_notes_5_def']='Rata de aplicare și debitul sistemului/zonei folosesc debitul mediu estimat al emițătorului pe teren (q<sub>avg,field</sub> &mdash; media proprie a lateralului test, corectată prin estimarea &Delta;presiune introdusă), nu o rată ghicită: PR = q<sub>avg,field</sub> / A<sub>e</sub>, alimentată de valoarea modelată corectată. Distanța și numărul de laterale/emițători la nivelul întregului sistem sunt intrări separate aici, deoarece calea test modelează doar o singură ramură de caz cel mai defavorabil, nu fiecare lateral din teren.';


// --- Branched Pipe Network (bn_) --- English source / fallback (translation pending) ---
$ec_lang['bpn_main_menu']='Rețea de conducte ramificată';
$ec_lang['bpn_main_title']='Calculator online gratuit de presiune pentru rețele de conducte ramificate (fără bucle)';
$ec_lang['bpn_main_desc']='Debit și presiune în rețea de conducte ramificată (arborescentă)';
$ec_lang['bpn_h_source_tip']='Sarcina statică de alimentare: sarcina sursei la debit zero. Nivelul apei într-un rezervor sau bazin deasupra cotei de alimentare, sau sarcina la vană închisă a unei pompe. Adăugați punctele de alimentare 2 și 3 pentru a defini o pompă sau o curbă de alimentare variabilă; instrumentul citește sarcina la debitul de proiectare.';
$ec_lang['bpn_elev_source']='Cota de alimentare';
$ec_lang['bpn_q_total']='Debit total';
$ec_lang['bpn_q_total_tip']='Debitul total care iese din sursă (suma tuturor cerințelor din rețea).';
$ec_lang['bpn_p_min']='Presiunea minimă';
$ec_lang['bpn_p_min_tip']='Cea mai mică presiune aval din întreaga rețea; punctul critic de livrare.';
$ec_lang['bpn_method']='Metoda de frecare';
$ec_lang['bpn_method_hw']='Hazen-Williams';
$ec_lang['bpn_method_dw']='Darcy-Weisbach';
$ec_lang['bpn_method_manning']='Manning';
$ec_lang['bpn_line_table_title']='Tronsoane de conductă';
$ec_lang['bpn_id']='ID';
$ec_lang['bpn_id_tip']='Numele acestui tronson de conductă. Alte tronsoane îl referențiază în coloana ID amonte.';
$ec_lang['bpn_upstream']='ID amonte';
$ec_lang['bpn_upstream_tip']='ID-ul tronsonului care alimentează acest tronson. Lăsați necompletat pentru a urma tronsonul direct de deasupra (o conductă simplă în serie). Introduceți un ID aici pentru a ramifica dintr-un alt tronson.';
$ec_lang['bpn_roughness_tip']='Rugozitatea conductei pentru metoda de frecare selectată: n Manning, C Hazen-Williams, sau înălțimea de rugozitate e Darcy-Weisbach (o lungime). Conductă din plastic neted, valori tipice: n circa 0,009, C circa 150, e circa 0,0015 mm.';
$ec_lang['bpn_demand']='Cerință';
$ec_lang['bpn_demand_tip']='Debit fix livrat la capătul aval al acestui tronson. Lăsați necompletat pentru un tronson care doar transportă debitul mai departe.';
$ec_lang['bpn_demand_mult']='Multiplicator de debit';
$ec_lang['bpn_demand_mult_tip']='Scalează simultan debitul tuturor tronsoanelor, pentru un calcul de oră de vârf sau de creștere viitoare. Utilizați 1 pentru debitele introduse ca atare.';
$ec_lang['bpn_elev_down']='Cotă av.';
$ec_lang['bpn_q_line']='Debit tronson';
$ec_lang['bpn_q_line_tip']='Debitul total transportat de acest tronson: cerința sa proprie plus fiecare cerință aval pe care o alimentează.';
$ec_lang['bpn_p_down']='Pres. av.';
$ec_lang['bpn_p_down_tip']='Sarcina de presiune manometrică la nodul aval al acestui tronson. O valoare negativă (semnalată) înseamnă presiune subatmosferică; verificați proiectul.';
$ec_lang['bpn_sketch_title']='Schema rețelei';
$ec_lang['bpn_show_length']='Lungime';
$ec_lang['bpn_show_diameter']='Diametru';
$ec_lang['bpn_show_q']='Debit';
$ec_lang['bpn_show_p']='Presiune';
$ec_lang['bpn_source_label']='Sursă';
$ec_lang['bpn_topology_warn']='Verificați coloana ID amonte: un tronson indică un ID necunoscut, se referențiază pe sine, sau formează o buclă, astfel încât o parte din rețea nu este conectată la sursă. Acele tronsoane rămân nerezolvate.';
$ec_lang['bpn_topology_warn_short']='Rețea';
$ec_lang['bpn_pressure_warn']='Presiune scăzută/negativă; verificați condițiile subatmosferice';
$ec_lang['bpn_pressure_warn_short']='Scăzută';
$ec_lang['bpn_notes_1_term']='În serie implicit, ramificare prin excepție';
$ec_lang['bpn_notes_1_def']='Lăsați ID amonte necompletat și un tronson îl urmează pe cel de deasupra; o conductă simplă în serie. Introduceți ID-ul unui tronson amonte pentru a ramifica din el. Deci: în serie implicit, un arbore când aveți nevoie.';
$ec_lang['bpn_notes_2_term']='Doar rețele ramificate, fără bucle';
$ec_lang['bpn_notes_2_def']='Fiecare tronson are exact un tronson amonte (un arbore). Acest instrument nu rezolvă rețele cu bucle; acestea necesită metode iterative (EPANET sau similar). Excluderea buclelor este ceea ce menține instrumentul simplu și exact.';
$ec_lang['bpn_notes_3_term']='Fără controale active de presiune';
$ec_lang['bpn_notes_3_def']='Puteți adăuga o vană cu pierdere locală fixă (o valoare k), dar nu vane reductoare sau susținătoare de presiune (PRV/PSV). Starea lor deschis/închis depinde de debit și presiune, ceea ce ar forța iterația.';
$ec_lang['bpn_supply2_q']='Debit de alimentare 2';
$ec_lang['bpn_supply2_h']='Sarcină de alimentare 2';
$ec_lang['bpn_supply3_q']='Debit de alimentare 3';
$ec_lang['bpn_supply3_h']='Sarcină de alimentare 3';
$ec_lang['bpn_supply_pt_tip']='Puncte opționale 2 și 3 ale curbei de alimentare. Introduceți un debit și o sarcină pentru fiecare pentru a modela o pompă, sau orice sursă a cărei sarcină scade pe măsură ce livrează mai mult debit; instrumentul citește sarcina la debitul de proiectare. Punctul 1 de mai sus este sarcina statică la debit zero. Lăsați 2 și 3 necompletate pentru o sarcină de rezervor constantă.';
$ec_lang['bpn_h_supply']='Sarcină de alimentare';
$ec_lang['bpn_h_supply_tip']='Sarcina sursei la debitul de proiectare, citită din curba de alimentare. Este egală cu sarcina sursei introdusă atunci când curba este plată (un rezervor).';
$ec_lang['bpn_show_elevation']='Cotă';
$ec_lang['bpn_supply1_h']='Sarcină statică de alimentare';
