<?php

// ěščžřýáíúůéó — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="podíl";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% sklonu";
$ec_lang['u_grade']="sklon";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="L/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="ML/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/ft^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="s";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Kalkulačky HawsEDC';
$ec_lang['menu_main_list']='Seznam kalkulaček';
$ec_lang['menu_main_hydraulics']='Hydraulika';
$ec_lang['menu_main_language']='Jazyk';
$ec_lang['menu_more']='Více';
$ec_lang['template_welcome']='>> Nechejte strachy za dveřmi; zde je láska naším jazykem. Nekazíte vše. Užijte si také <a target="_blank" href="https://hawsedc.com/download.php">zdarma nástroje HawsEDC pro AutoCAD.</a> <<';
$ec_lang['template_translation_help']='Máte skvělou vizi pro kalkulačku, která by mohla být přidána zde?  Můžete mi pomoci zlepšit překlady, programovat nebo hostovat tyto kalkulačky?  ';
$ec_lang['template_feedback']='Prosíme, podělte se o vaše cenné připomínky nebo pochvaly. Překonala tato bezplatná kalkulačka vaše očekávání?';
$ec_lang['template_printable_title']='Tisknutelný název';
$ec_lang['template_printable_subtitle']='Tisknutelný podtitul';
$ec_lang['index_title']='Bezplatné inženýrské kalkulačky online';
$ec_lang['calc_set_units']='Nastavit jednotky:';
$ec_lang['calc_defaults']='Výchozí hodnoty';
$ec_lang['calc_defaults_confirm']='Reset calculator to factory defaults?';
$ec_lang['points_data_help']='(nebo Kopírovat/Vložit pomocí datové oblasti)';
$ec_lang['points_data_title']='Data bodů<br />(oddělena čárkou nebo tabulátorem)';
$ec_lang['points_data_copy']='Kopírovat';
$ec_lang['points_data_paste']='Vložit';
$ec_lang['calc_inputs']='Vstupy';
$ec_lang['calc_results']='Výsledky';
$ec_lang['view_hide_line']='[Skrýt tento řádek]';
$ec_lang['view_printable']='Verze pro tisk (obnovit pro vrácení)';
$ec_lang['ec_name_label']='Uložit tento výpočet:';
$ec_lang['ec_name_placeholder']='Název';
$ec_lang['ec_name_hint']='Uloží tyto zadané hodnoty do adresy URL pro přidání do záložek, načtení z historie a sdílení';
$ec_lang['calc_copy_link']='Copy link';
$ec_lang['calc_copy_link_done']='Copied!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Ztráta tlaku v potrubí Darcy-Weisbach';
$ec_lang['dw_main_title']='Bezplatný online kalkulátor ztrát tlaku v potrubí Darcy-Weisbach';
$ec_lang['dw_main_desc']='Ztráta tlaku v potrubí dle Darcy-Weisbach při daném průměru, drsnosti a průtoku';
$ec_lang['dw_roughness']='Absolutní drsnost Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Kinematická viskozita, ν <span title="1×10⁻⁶ m²/s pro čistou vodu při 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Reynoldsovo číslo, Re';
$ec_lang['dw_flow_regime']='Režim proudění';
$ec_lang['dw_regime_laminar']='laminární';
$ec_lang['dw_regime_transitional']='přechodný';
$ec_lang['dw_regime_turbulent']='turbulentní';
$ec_lang['dw_friction_factor_method']='Metoda součinitele tření';
$ec_lang['dw_friction_factor']='Součinitel tření, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Ztráta tlaku v potrubí Hazen-Williams';
$ec_lang['hw_main_title']='Bezplatný online kalkulátor ztrát tlaku Hazen-Williams';
$ec_lang['hw_main_desc']='Ztráta tlaku v potrubí dle Hazen-Williams při daném průměru, drsnosti a průtoku';
$ec_lang['hw_hgl_1']='HGL po proudu';
$ec_lang['hw_hgl_2']='HGL proti proudu';
$ec_lang['hw_roughness']='Koeficient Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Nepravidelný průřez Manning';
$ec_lang['mi_main_title']='Bezplatný online kalkulátor nepravidelného koryta Manning';
$ec_lang['mi_main_desc']='Kalkulátor rovnoměrného proudění v nepravidelném korytě dle Manninga';
$ec_lang['mi_waterSurfaceElevation']='Kóta hladiny vody';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Body příčného řezu';
$ec_lang['mi_groupPoint']='Bod';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Oblast';
$ec_lang['mi_station']='Sta';
$ec_lang['mi_elevation']='Kóta';
$ec_lang['mi_d50in']='Střední<br />velikost<br />kamene<br />opevnění';
$ec_lang['mi_n']='n<br />seg-<br />mentu';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />hranice<br />oblasti<br />(Břeh)';
$ec_lang['mi_tau']='Tečné<br />nap. dna<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Složený<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Poznámky';
$ec_lang['mi_notes_1_term']='Složený n';
$ec_lang['mi_notes_1_def']='Tento kalkulátor sleduje referenční příručku HEC-RAS při výpočtu složeného n oblasti pomocí Chow 1959, strana 136, rovnice 6-17 (ne 6-18).';
$ec_lang['mi_notes_2_term']='Kamenné opevnění';
$ec_lang['mi_notes_2_def']='Pro návrh kamenného opevnění použijte kalkulátor lichoběžníkového koryta Manning. Tento kalkulátor je vhodnější pro přirozené průřezy.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Průtok v potrubí Manning';
$ec_lang['mpf_main_title']='Bezplatný online kalkulátor průtoku v potrubí Manning';
$ec_lang['mpf_main_desc']='Manningova rovnice pro rovnoměrný průtok v potrubí při daném sklonu a hloubce';
$ec_lang['mpf_spreadheet_notice']='Vyzkoušejte tabulkovou verzi tohoto kalkulátoru';
$ec_lang['mpf_pipe_diameter']='Průměr potrubí, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manningova drsnost, n';
$ec_lang['mpf_friction_slope']='Tlaková linie sklonu (případně <a target="_blank" href="../pressureslope.php">?</a> rovna sklonu potrubí), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Poměrná hloubka plnění, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Viz poznámky)';
$ec_lang['mpf_flow']='Průtok, Q';
$ec_lang['mpf_velocity']='Rychlost, v';
$ec_lang['mpf_velocity_head']='Rychlostní výška, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Průtočná plocha, a';
$ec_lang['mpf_pipe_area']='Plocha potrubí, a0';
$ec_lang['mpf_area_ratio']='Poměrná plocha, a/a0';
$ec_lang['mpf_wetted_perimeter']='Smočený obvod, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Hydraulický poloměr, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Šířka hladiny, T';
$ec_lang['mpf_froude_number']='Froudovo číslo, F';
$ec_lang['mpf_shear_stress']='Průměrné smykové napětí (trakční síla), tau';
$ec_lang['mpf_full_flow']='Průtok při plném plnění, Q0';
$ec_lang['mpf_full_flow_ratio']='Poměr k plnému průtoku, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Toto je průtok a hloubka uvnitř <em>nekonečně dlouhého</em> potrubí.</dt><dd>Přivést průtok do potrubí může vyžadovat výrazně vyšší výšku hladiny. Přidejte alespoň 1,5násobek rychlostní výšky pro výšku hladiny nebo <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">viz 2minutový výukový program</a> pro standardní výpočty propustků pomocí HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Vypočítat y/d<sub>0</sub> pro dané Q';
$ec_lang['mpf_solve_desc']='Pomocí D<sub>0</sub>, n a S<sub>0</sub> z formuláře najde nejnižší y/d<sub>0</sub> pro dané Q.';
$ec_lang['mpf_solve_button']='Vypočítat';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Ztráta výšky v potrubí Manning';
$ec_lang['mphl_main_title']='Bezplatný online kalkulátor ztrát výšky v potrubí Manning';
$ec_lang['mphl_main_desc']='Manningova rovnice ztráty výšky při plném průtoku';
$ec_lang['mphl_pipe_length']='Délka potrubí, L';
$ec_lang['mphl_area']='Plocha, A';
$ec_lang['mphl_total_junction_k']='Celkový kombinovaný koeficient ztrát na armaturách, k';
$ec_lang['mphl_friction_slope']='Třecí sklon';
$ec_lang['mphl_friction_loss']='Třecí ztráta, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Ztráta na armaturách, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Celková ztráta, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL po proudu';
$ec_lang['mphl_egl_2']='EGL proti proudu';
$ec_lang['mphl_hgl_2']='HGL proti proudu v potrubí ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Pro podmínku otevřeného vtoku (propustek) je nutné zkontrolovat podmínky vtokového ovládání.</dt><dd>1. HGL proti proudu nemůže být nižší než kóta normální hloubky proudění (ani nižší než potrubí!).</dd><dd>2. Hladina propustku je lépe reprezentována EGL než HGL proti proudu.</dd><dd>3. Viz <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">2minutový výukový program</a> pro jednoduchý standardní výpočet propustků pomocí HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Lichoběžníkový průřez Manning';
$ec_lang['mtc_main_title']='Bezplatný online kalkulátor lichoběžníkového koryta Manning';
$ec_lang['mtc_main_desc']='Manningova rovnice rovnoměrného proudění v lichoběžníkovém korytě při daném sklonu a hloubce';
$ec_lang['mtc_bottom_width']='Šířka dna, b';
$ec_lang['mtc_side_slope_1']='Sklon svahu 1, z1 (vodorovně/svisle)';
$ec_lang['mtc_side_slope_2']='Sklon svahu 2, z2 (vodorovně/svisle)';
$ec_lang['mtc_channel_slope']='Sklon koryta, S';
$ec_lang['mtc_flow_depth']='Hloubka proudění, y';
$ec_lang['mtc_bend_angle']='Úhel oblouku, β <a target="_blank" href="riprap-bend-angle.png" title="Klikněte pro obrázek">?</a> (pro velikost záhozu)';
$ec_lang['mtc_sgrock']='Měrná hmotnost kamene, SG (2,65)';
$ec_lang['mtc_d50_in']='Návrhová velikost kamene, D50';
$ec_lang['mtc_n_strickler']='n pro návrhovou velikost kamene dle Stricklera';
$ec_lang['mtc_n_blodgett']='n pro návrhovou velikost kamene dle Blodgetta';
$ec_lang['mtc_n_bathurst']='n pro návrhovou velikost kamene dle Bathursta';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Požadovaná velikost lomového kamene na dně, D50 (Isbash & MC) <span title="Dle Isbash (1936) a Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Požadovaná velikost lomového kamene svahu 1, D50 (Isbash & MC) <span title="Dle Isbash (1936) a Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Požadovaná velikost lomového kamene svahu 2, D50 (Isbash & MC) <span title="Dle Isbash (1936) a Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Požadovaná velikost lomového kamene, D50 (Maynord, Ruff a Abt 1989)';
$ec_lang['mtc_d50_searcy']='Požadovaná velikost lomového kamene, D50 (Searcy 1967)';
$ec_lang['mtc_vel_check']='Kontrola rychlosti';
$ec_lang['mtc_vel_ok']='Rychlost přiměřená pro předpoklady rovnoměrného proudění.';
$ec_lang['mtc_vel_high']='Rychlost vysoká — zkontrolujte ztráty na přechodech, dostupnou energii a riziko vodního rázu.';
$ec_lang['mtc_vel_low']='Rychlost nízká — riziko sedimentace.';
$ec_lang['mtc_vel_ok_short']='OK';
$ec_lang['mtc_vel_high_short']='Vysoká';
$ec_lang['mtc_vel_low_short']='Nízká';
$ec_lang['mtc_note_1']='<dl><dt>Automatická iterace návrhu kamene a drsnosti</dt><dd>Zvolte přepínač pro drsnost (doporučeno BB) a přepínač pro návrhovou velikost kamene (doporučeno Isbash). Dolaďte hloubku a bezpečnostní faktor kamene pro dosažení požadovaného průtoku s rovnoměrnou velikostí kamene. Každá změna vstupní hodnoty spustí iterační cyklus: 1. Drsnost je vypočtena z návrhové velikosti kamene. 2. Požadovaný výpočet drsnosti je zkopírován do vstupní drsnosti. 3. Průtok v korytě a požadovaná velikost kamene jsou vypočteny. 4. Návrhová velikost kamene je upravena. 5. Opakovat dokud chyba v návrhové velikosti kamene není velmi malá.</dd><dt>Základní kalkulátor (bez iterace)</dt><dd>Zadejte požadovanou hodnotu drsnosti. Ignorujte oblast zadávání návrhové velikosti kamene.</dd></dl>';
$ec_lang['mtc_note_2_term']='Kontrola rychlosti';
$ec_lang['mtc_note_2_def']='Vysoká rychlost znamená vysokou specifickou energii z dostupného spádu. Tato energie může být rychle ztracena na rozšířeních, obloucích nebo překážkách. Ověřte, zda je to pro danou lokalitu přiměřené.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Jednoduchý přepad';
$ec_lang['ws_main_title']='Bezplatný online kalkulátor jednoduchého širokokorunového přepadu';
$ec_lang['ws_main_desc']='Kalkulátor průtoku jednoduchým širokokorunovým přepadem';
$ec_lang['ws_weirLength']='Délka přepadu, l';
$ec_lang['ws_headWaterHeight']='Výška vzdutí, h';
$ec_lang['ws_weirCoefficient']='Koeficient přepadu, Cw';
$ec_lang['ws_notes_heading']='Poznámky';
$ec_lang['ws_notes_we_term']='Rovnice přepadu';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Nepravidelný přepad';
$ec_lang['wi_main_title']='Bezplatný online kalkulátor nepravidelného přepadu s proměnnou hloubkou';
$ec_lang['wi_main_desc']='Kalkulátor průtoku nepravidelným přepadem';
$ec_lang['wi_headWaterelevation']='Kóta vzdutí';
$ec_lang['wi_weirPoints']='Body přepadu';
$ec_lang['wi_station']='Staničení';
$ec_lang['wi_elevation']='Kóta';
$ec_lang['wi_pondingHeight']='Výška vzdutí';
$ec_lang['wi_incrementalFlow']='Přírůstkový průtok';
$ec_lang['wi_cumulativeFlow']='Kumulativní průtok';
$ec_lang['wi_save_and_calculate']='Uložit a vypočítat';
$ec_lang['wi_notes_we_term']='Rovnice přepadu';
$ec_lang['wi_notes_we_def']='q = pokud (délka = 0) pak 0, pokud (sklon=0) pak cw*délka*d<sub>0</sub><sup>1.5</sup>, jinak cw/(2.5*sklon) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) kde d<sub>1</sub> a d<sub>0</sub> jsou vždy kladné nebo nula';
// Orifice Flow
$ec_lang['or_main_menu']='Průtok otvorem';
$ec_lang['or_main_title']='Bezplatný online kalkulátor průtoku otvorem';
$ec_lang['or_main_desc']='Průtok otvorem — volný nebo zatopený';
$ec_lang['or_shape']='Tvar otvoru';
$ec_lang['or_shape_circular']='Kruhový';
$ec_lang['or_shape_rectangular']='Obdélníkový';
$ec_lang['or_diameter']='Průměr nebo výška, D <span title="Průměr pro kruhový; výška pro obdélníkový" class="ec-tip">?</span>';
$ec_lang['or_width']='Šířka, W <span title="Jen obdélníkový otvor" class="ec-tip">?</span>';
$ec_lang['or_invert']='Kóta dna otvoru <span title="Spodní hrana otvoru" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Kóta hladiny na přítoku';
$ec_lang['or_twe']='Kóta hladiny na odtoku';
$ec_lang['or_cd']='Součinitel průtoku, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Kóta těžiště';
$ec_lang['or_head']='Účinná výška, h';
$ec_lang['or_area']='Plocha otvoru, A';
$ec_lang['or_flow']='Průtok, Q';
$ec_lang['or_velocity']='Rychlost, v';
$ec_lang['or_regime']='Kontrola režimu průtoku otvorem';
$ec_lang['or_regime_valid']='Volný výtok — režim otvoru platný ✓';
$ec_lang['or_regime_submerged']='Zatopený otvor (TWE nad těžištěm otvoru) — platný ✓';
$ec_lang['or_regime_warn']='Varování: hladina přítoku pod korunou — není režim otvoru';
$ec_lang['or_regime_twe_above_hwe']='Varování: hladina odtoku (TWE) nad hladinou přítoku (HWE) — zkontrolujte vstupy';
$ec_lang['or_notes_1_term']='Rovnice otvoru';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Volný výtok: h = HWE − těžiště. Zatopený (TWE nad dnem): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Režim průtoku otvorem';
$ec_lang['or_notes_2_def']='Rovnice průtoku otvorem platí, když je hladina přítoku nad korunou otvoru. Když je pod korunou, použijte rovnici přepadu.';
$ec_lang['or_notes_3_term']='Součinitel průtoku';
$ec_lang['or_notes_3_def']='C<sub>d</sub> se pohybuje přibližně 0,60–0,65 pro ostrohrané otvory. Zaoblené nebo zúžené vstupy mají jiné hodnoty. Viz <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> nebo Hydraulický referenční manuál HEC-RAS.';
$ec_lang['or_notes_4_term']='Zatopení';
$ec_lang['or_notes_4_def']='Pokud je TWE nad dnem otvoru, kalkulačka automaticky použije rovnici zatopeného otvoru s h = HWE − TWE. Pokud je TWE na dně nebo níže, předpokládá se volný výtok a h = HWE − těžiště.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Mikro-vodní elektrárna';
$ec_lang['mhp_main_title']='Bezplatná online kalkulačka výkonu mikro-vodní elektrárny';
$ec_lang['mhp_main_desc']='Kalkulačka výkonu průtočné mikro-vodní elektrárny';
$ec_lang['mhp_flow']='Průtok, Q';
$ec_lang['mhp_gross_head']='Hrubá tlaková výška, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Průměr přiváděcího potrubí, D';
$ec_lang['mhp_length']='Délka přiváděcího potrubí, L';
$ec_lang['mhp_roughness']='Drsnost potrubí, e';
$ec_lang['mhp_km']='Součinitel místní ztráty, k<sub>m</sub> <span title="Součet všech součinitelů ztrát na armaturách a conectích v přiváděcím potrubí" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Kinematická viskozita, ν <span title="1×10⁻⁶ m²/s pro čistou vodu poblíž 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='Účinnost elektrárny, η (0–1)';
$ec_lang['mhp_velocity']='Rychlost proudění, v';
$ec_lang['mhp_vel_check']='Kontrola rychlosti';
$ec_lang['mhp_f']='Součinitel tření, f';
$ec_lang['mhp_hf']='Třecí ztráta tlakové výšky, h<sub>f</sub>';
$ec_lang['mhp_hm']='Ztráta místní výšky, h<sub>m</sub>';
$ec_lang['mhp_hl']='Celková ztráta přiváděcího potrubí, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Kontrola ztráty tlakové výšky';
$ec_lang['mhp_hnet']='Čistá tlaková výška, H<sub>net</sub>';
$ec_lang['mhp_power']='Výstupní výkon, P';
$ec_lang['mhp_annual_kwh']='Roční výroba při 100% výkonu';
$ec_lang['mhp_vel_ok']='1–3 m/s — v cílovém rozsahu ✓';
$ec_lang['mhp_vel_low']='Rychlost nízká — riziko sedimentace a usazování vzduchu.';
$ec_lang['mhp_vel_high']='Rychlost vysoká — zkontrolujte ztráty na přechodech, dostupnou energii a riziko vodního rázu.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Vysoká';
$ec_lang['mhp_vel_low_short']='Nízká';
$ec_lang['mhp_hl_ok']='v rámci cíle 10% ✓';
$ec_lang['mhp_hl_warn']='překračuje cíl 10% — zvažte větší potrubí ⚠';
$ec_lang['mhp_hl_bad']='překračuje 20% — přehodnoťte rozměry potrubí';
$ec_lang['mhp_notes_1_term']='Ztráta tlakové výšky';
$ec_lang['mhp_notes_1_def']='Celková ztráta h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, kde h<sub>f</sub> = f(L/D)(v²/2g) je třecí ztráta podle Darcy-Weisbacha a h<sub>m</sub> = k<sub>m</sub>·v²/2g zahrnuje vtok, kolena a armatury. Čistá výška H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Rychlost';
$ec_lang['mhp_notes_2_def']='Cíl 1–3 m/s. Pod 1 m/s je potrubí předimenzované; nad 3 m/s narůstají třecí ztráty a riziko vodního rázu.';
$ec_lang['mhp_notes_3_term']='Cílová ztráta tlakové výšky';
$ec_lang['mhp_notes_3_def']='Ztráty v přiváděcím potrubí pod 10% hrubé výšky jsou zpravidla hospodárné. Optimální kompromis mezi náklady na potrubí a ztrátou výkonu se obvykle pohybuje kolem 4–6% pro lokality s vysokou hodnotou elektřiny.';
$ec_lang['mhp_notes_4_term']='Místní ztráty k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Typické hodnoty: ostrý vtok 0.5, každé koleno 45° 0.2–0.3, šoupě (plně otevřené) 0.1, klapka 0.2. Součet všech armatur tvoří celkový k<sub>m</sub>. Výchozí hodnota 1.5 předpokládá jeden vtok a dvě kolena.';
$ec_lang['mhp_notes_5_term']='Drsnost potrubí e';
$ec_lang['mhp_notes_5_def']='Typická absolutní drsnost: ocel (nová) 0.046 mm, ocel (použitá) 0.15 mm, HDPE 0.003 mm, PVC/uPVC 0.0015 mm, beton 0.3–3 mm. HDPE je běžný materiál pro malá přiváděcí potrubí mikro-vodních elektráren.';
$ec_lang['mhp_notes_6_term']='Účinnost';
$ec_lang['mhp_notes_6_def']='Typická účinnost elektrárny &eta; se pohybuje od 0,70 do 0,85 pro Peltonovy a příčné turbíny běžné v mikro-vodní energetice. Jako konzervativní první odhad použijte hodnotu 0,75.';
$ec_lang['mhp_notes_7_term']='Roční výroba energie';
$ec_lang['mhp_notes_7_def']='Roční výroba energie předpokládá nepřetržitý provoz při plném průtoku (8760 hodin/rok). Skutečná výroba bude nižší z důvodu sezónní variability průtoku, prostojů při údržbě a faktoru zatížení.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Doba prázdnění otvorem';
$ec_lang['odt_main_title']='Bezplatný online kalkulátor doby prázdnění otvorem';
$ec_lang['odt_main_desc']='Doba prázdnění nádrže otvorem — Metoda kónického objemu';
$ec_lang['odt_h1_elev']='Počáteční kóta hladiny vody';
$ec_lang['odt_a1']='Počáteční plocha nádrže, A1';
$ec_lang['odt_h2_elev']='Koncová kóta hladiny vody';
$ec_lang['odt_h_orifice']='Kóta těžiště otvoru';
$ec_lang['odt_a0']='Plocha nádrže na kótě otvoru, A0';
$ec_lang['odt_a_ending']='Koncová plocha nádrže, A2 (interpolováno)';
$ec_lang['odt_h2_check']='Kontrola koncové kóty';
$ec_lang['odt_h2_ok']='Koncová kóta nad vrcholem otvoru ✓';
$ec_lang['odt_h2_warn']='Varování: koncová kóta na úrovni nebo pod vrcholem otvoru (těžiště + D/2)';
$ec_lang['odt_d']='Průměr otvoru (kruhový) nebo výška (obdélníkový), D';
$ec_lang['odt_w']='Šířka otvoru, W (jen obdélníkový)';
$ec_lang['odt_t_sec']='Doba prázdnění (sekundy)';
$ec_lang['odt_t_min']='Doba prázdnění (minuty)';
$ec_lang['odt_t_hr']='Doba prázdnění (hodiny)';
$ec_lang['odt_t_day']='Doba prázdnění (dny)';
$ec_lang['odt_notes_1_term']='Vzorec';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) udává dobu prázdnění od výšky H k otvoru. Doba prázdnění = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), kde H<sub>1</sub> = počáteční kóta − kóta otvoru, H<sub>2</sub> = koncová kóta − kóta otvoru.';
$ec_lang['odt_notes_2_term']='Metoda';
$ec_lang['odt_notes_2_def']='Metoda kónického objemu modeluje nádrž jako kónický řez mezi počáteční plochou A<sub>1</sub> u počáteční hladiny a plochou A<sub>0</sub> na kótě těžiště otvoru. A<sub>2</sub>, plocha nádrže na koncové kótě, je interpolována z A<sub>1</sub> a A<sub>0</sub> pomocí modelu kónického řezu. Doba prázdnění od počáteční do koncové kóty se rovná celkové době od H<sub>1</sub> k otvoru minus zbývající doba od H<sub>2</sub> k otvoru.';
$ec_lang['odt_h1']='Počáteční výška, H<sub>1</sub> (WSE − těžiště)';
$ec_lang['odt_q_max']='Maximální (počáteční) průtok, Q<sub>max</sub>';
$ec_lang['odt_vol']='Vyčerpaný objem';
$ec_lang['odt_sketch_start']='Začátek';
$ec_lang['odt_sketch_end']='Konec';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Šířka od břehu k břehu';
$ec_lang['essc_mcr']='Minimální poloměr oblouku';
$ec_lang['essc_q']='Průtok, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Závlaha';
$ec_lang['irr_main_title']='Bezplatné online kalkulačky pro měření průtoku závlahy';
$ec_lang['irr_main_desc']='Měření průtoku závlahy — přelivy a otvory';
$ec_lang['irr_intro_html']='<p>Přelivy a otvory jsou standardní terénní nástroje pro měření průtoku vody v závlahových systémech. Vyberte kalkulačku odpovídající vaší konstrukci:</p>';
$ec_lang['irr_card_weir_uniform_head']='Přeliv — Široká Koruna (Rovnoměrná Šířka)';
$ec_lang['irr_card_weir_uniform_desc']='Měřte průtok přes korunu odvodňovacího jezu, kontrolního objektu nebo přelivné desky. Zadejte délku přelivu a hloubku vody nad korunou.';
$ec_lang['irr_card_weir_irregular_head']='Přeliv — Nepravidelný Profil';
$ec_lang['irr_card_weir_irregular_desc']='Použijte, když koruna přelivu není v jediné rovnoměrné výšce — přirozené bezpečnostní přelivy, stupně s proměnnou šířkou nebo vícesekční regulační objekty.';
$ec_lang['irr_card_orifice_head']='Otvor — Hlavní Šoupě nebo Trubní Výpust';
$ec_lang['irr_card_orifice_desc']='Měřte průtok skrze stavidlové šoupě, trubní výpust nebo otvor propustku. Automaticky zpracovává jak volný výtok, tak podmínky vzdutí (protitlak z dolní vody).';
$ec_lang['irr_card_canal_head']='Návrh & Analýza Kanálu';
$ec_lang['irr_card_canal_desc']='Navrhněte nebo ověřte závlahový kanál pomocí Manningova vzorce. Používejte lichoběžníkovou kalkulačku pro nové kanály; nepravidelnou kalkulačku pro stávající přirozené nebo vybudované průřezy.';
$ec_lang['irr_card_seepage_head']='Průsak kanálu & Dopravní účinnost';
$ec_lang['irr_card_seepage_desc']='Odhadněte průsakové ztráty z úseku kanálu pomocí měření přítoku a odtoku. Vypočítejte dopravní účinnost a roční ztrátu vody pro stanovení priorit investic do zpevnění kanálu.';
$ec_lang['irr_quickref_html']='<h3>Rychlá Referenční Příručka</h3><dl><dt>Odvodňovací jez nebo kontrolní objekt</dt><dd>Změřte hloubku vody nad korunou přelivu. Používejte <a href="Weir-Flow-Simple.php">Jednoduchý Přeliv</a> pro rovnoměrnou korunu nebo <a href="Weir-Flow-Irregular.php">Nepravidelný Přeliv</a> pro profilovanou nebo stupňovitou korunu.</dd><dt>Hlavní šoupě nebo trubní výpust</dt><dd>Změřte nadmořskou výšku hladiny v horní a dolní vodě (nebo výšku dna při volném výtoku). Používejte <a href="Orifice.php">Průtok Otvorem</a>. Pro kruhovou trubku D = průměr trubky; pro obdélníkové šoupě zadejte šířku W a výšku D.</dd><dt>Doba vyprázdnění nádrže nebo rybníka</dt><dd>Použijte <a href="Orifice-Drain-Time.php">Dobu Vyprázdnění Otvorem</a> pro odhad doby potřebné ke snížení hladiny rybníka nebo nádrže přes spodní otvor — užitečné pro plánování závlahového zásobníku.</dd><dt>Terénní standardy</dt><dd>Rovnice průtoku přelivem a otvorem použité zde odpovídají postupům USBR <em>Water Measurement Manual</em> (3. vydání), které běžně vyžadují správci vod a závlahové obvody.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Rozteč emiterů podél postranní větve, S<sub>e</sub>';
$ec_lang['ip_sl']='Rozteč postranních větví (vzdálenost řad), S<sub>l</sub>';
$ec_lang['ip_n_e']='Emitory na postranní větev, n<sub>e</sub>';
$ec_lang['ip_n_l']='Postranní větve na zónu, n<sub>l</sub>';
$ec_lang['ip_d']='Cílová hloubka závlahy, d';
$ec_lang['ip_a_e']='Plocha na jeden emitor, A<sub>e</sub>';
$ec_lang['ip_pr']='Dávka vody (intenzita závlahy), PR';
$ec_lang['ip_q_lat']='Průtok postranní větví, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Průtok zónou, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Doba závlahy pro cílovou hloubku (hodiny)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Ztráty průsakem v kanálu';
$ec_lang['cs_main_title']='Bezplatná online kalkulačka ztrát průsakem v kanálu a dopravní účinnosti';
$ec_lang['cs_main_desc']='Ztráty průsakem v kanálu & Dopravní účinnost — Metoda přítok–odtok';
$ec_lang['cs_Q_in']='Průtok na vtoku úseku, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Průtok na výtoku úseku, Q<sub>out</sub>';
$ec_lang['cs_L']='Délka úseku, L';
$ec_lang['cs_wp']='Smočený obvod průřezu kanálu, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='Rychlost průsakové ztráty, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Kontrola měření';
$ec_lang['cs_pct_loss']='Ztráta jako podíl přítoku';
$ec_lang['cs_Ec']='Dopravní účinnost, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Hodnocení účinnosti';
$ec_lang['cs_Vol_day']='Denní objem ztracený průsakem';
$ec_lang['cs_Vol_year']='Roční objem ztracený průsakem';
$ec_lang['cs_Q_loss_per_L']='Průsaková ztráta na jednotku délky, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Hodnota vody (měna / jednotku objemu)';
$ec_lang['cs_lining_cost']='Náklady na zpevnění (měna / jednotku plochy)';
$ec_lang['cs_Ec_target']='Cílová účinnost, E<sub>c,target</sub> <span title="Cílová dopravní účinnost po zpevnění; podíl 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Plocha zpevnění kanálu (L × P<sub>w</sub>)';
$ec_lang['cs_annual_value_lost']='Roční hodnota ztracené vody (měna)';
$ec_lang['cs_annual_value_recovered']='Roční hodnota získaná zpevněním (měna)';
$ec_lang['cs_lining_total_cost']='Celkové náklady na zpevnění (měna)';
$ec_lang['cs_payback_years']='Prostá doba návratnosti (roky)';
$ec_lang['cs_loss_positive']='Qin > Qout — průsak zjištěn ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — žádná měřitelná ztráta';
$ec_lang['cs_loss_negative']='Varování: Qout > Qin — zkontrolujte měření ⚠';
$ec_lang['cs_Ec_good']='Dobrá — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Přijatelná — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Špatná — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Metoda';
$ec_lang['cs_notes_1_def']='Metoda přítok–odtok odhaduje průsak měřením průtoku na vtoku a výtoku úseku kanálu: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. Dopravní účinnost E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Roční objem předpokládá nepřetržitý provoz s plným průtokem; skutečná ztráta je nižší pro sezónní nebo částečně průtočné kanály.';
$ec_lang['cs_notes_2_term']='Hodnocení účinnosti';
$ec_lang['cs_notes_2_def']='Typické nezpevněné zemní kanály: E<sub>c</sub> = 60–80%. Dobře udržované zemní kanály: 75–85%. Betonové kanály: 90–98%. Průsakové ztráty nad 30 % přítoku často odůvodňují investici do zpevnění. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Návratnost zpevnění';
$ec_lang['cs_notes_3_def']='Zadejte hodnotu vody a náklady na zpevnění v jakékoli konzistentní měně. Plocha zpevnění = délka úseku × smočený obvod — smočený obvod průřezu kanálu při měřené hloubce proudění (šířka dna plus oba smočené svahy). Roční získaná hodnota předpokládá, že zpevněný kanál trvale dosahuje cílové E<sub>c</sub>. Skutečná doba návratnosti bude delší pro sezónní kanály nebo pokud zpevnění nedosáhne cílové účinnosti.';
$ec_lang['cs_notes_4_term']='Literatura';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3. vyd. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='O nás';
$ec_lang['install_main_menu']='Nainstalovat';
$ec_lang['install_main_title']='Nainstalovat EngCalcs';
$ec_lang['install_main_desc']='Přidejte si na zařízení pro offline použití';
$ec_lang['contact_main_menu']='Kontakt';
$ec_lang['about_main_title']='O kalkulátorech HawsEDC';
$ec_lang['about_main_desc']='Poslání, open source a přispívání';
$ec_lang['about_body_html']='<h3>Poslání</h3><p>Inženýrské Kalkulačky HawsEDC existují, aby sloužily inženýrům a terénním pracovníkům po celém světě — zejména těm, kteří pracují v oblastech s nedostatkem vody, omezenými zdroji nebo nedostatečným zásobením. Tyto nástroje jsou součástí širšího humanitárního poslání: říci každému člověku co nejpraktičtějším a nejúčinnějším způsobem, že je navždy milován a ceněn, že se nemá čeho bát a že nezkazí všechno.</p><p>Kalkulačky jsou prostředkem. Cílem je svět bez utrpení.</p><h3>Licence s Otevřeným Zdrojovým Kódem</h3><p>Veškerý kód je vydán pod <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 nebo novější</a> — svobodný ve smyslu svobody. Kód můžete za stejných podmínek používat, studovat, upravovat a šířit dál.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Zdrojový Kód</h3><p>Úplný zdrojový kód je veřejně dostupný na Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Tam si můžete prohlédnout kód, nahlásit problémy nebo forknout repozitář.</p><h3>Příspěvky</h3><p>Pull requesty jsou vítány. Způsoby přispění:</p><ul><li><strong>Překlady</strong> — vylepšete nebo přidejte jazyk. Otevřete pull request se změnami v příslušném souboru <code>lib/lang.ec.??.php</code>.</li><li><strong>Hlášení chyb</strong> — použijte formulář zpětné vazby na libovolné stránce kalkulačky nebo nahlaste problém na Bitbucket.</li><li><strong>Nové kalkulačky</strong> — nápady na hydraulicko-inženýrské nástroje sloužící terénním pracovníkům a odborníkům na závlahy jsou zvláště vítány. Viz příručka pro vývojáře <code>CLAUDE.md</code> v repozitáři.</li><li><strong>Hosting</strong> — pokud můžete tuto kalkulačku zrcadlit pro oblast s omezeným připojením, obraťte se na nás.</li></ul><h3>Offline použití</h3><p>Tyto kalkulačky fungují jako progresivní webová aplikace (PWA). Navštivte jakoukoli stránku kalkulačky při připojeném internetu a váš prohlížeč automaticky uloží všechny kalkulačky do mezipaměti. Poté všechny kalkulačky fungují offline — bez potřeby internetu.</p><p>Na Androidu nebo iOS použijte možnost „Přidat na domovskou obrazovku" v prohlížeči a nainstalujte EngCalcs jako aplikaci do svého zařízení. Na počítači hledejte ikonu instalace v adresním řádku prohlížeče.</p><p>Libovolnou kalkulačku můžete také uložit pomocí nabídky „Uložit jako…" ve svém prohlížeči pro jednorázové offline použití.</p><h3>Kontakt</h3><p>Tom Haws — hydraulický inženýr a autor těchto kalkulaček.<br />Použijte formulář zpětné vazby na libovolné stránce kalkulačky nebo přistupte ke zdrojovému kódu na <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Kontakt HawsEDC';
$ec_lang['contactSendMessage']='Pošlete zprávu Tomu Hawsovi';
$ec_lang['contactYourName']='Vaše jméno:';
$ec_lang['contactYourEmail']='Vaše e-mailová adresa:';
$ec_lang['contactSubject']='Předmět:';
$ec_lang['contact_message']='Zpráva:';
$ec_lang['contactSpamPrefix']='Pět plus jedna se rovná';
$ec_lang['contactSpamPostfix']='(Prosím napište anglicky slovy. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Odeslat zprávu';
$ec_lang['contact_success']='Děkujeme za váš čas věnovaný napsání.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Návrh Kamenného Skluzu (Robinson)';
$ec_lang['rc_main_title']='Bezplatná Online Kalkulačka Návrhu Kamenného Skluzu — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimenzování Záhozu Kamenného Skluzu — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Sklon dna skluzu, S<sub>0</sub>';
$ec_lang['rc_qt']='Celkový jednotkový průtok, q<sub>t</sub> <span title="Průtok na jednotku šířky na vtoku skluzu. Pro koryto s šířkou dna B a celkovým průtokem Q použijte q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Pórovitost záhozu, n<sub>p</sub>';
$ec_lang['rc_sg']='Měrná hmotnost horniny, sg <span title="Typický drcený granit nebo čedič ≈ 2,65. Platný rozsah Robinson: 2,54 až 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Zrnitostní SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Směrodatná odchylka zrnitosti. Rovnoměrné kamení ≈ 1,25. Platný rozsah Robinson: 1,15 až 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Normální hloubka ve vtokové stoce, y<sub>n</sub> <span title="Vzdutí (Hp > yn) je žádoucí — snižuje erozi na vtoku. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Požadovaná střední velikost kamene, D<sub>50</sub> <span title="Rovnice 1 (S0 < 0.10) nebo rovnice 2 (0,10–0,40). Platné rozmezí: D50 15–278 mm, S0 0,02–0,40. Mimo rozsah: extrapolováno." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Použitá rovnice';
$ec_lang['rc_sg_check']='Kontrola měrné hmotnosti';
$ec_lang['rc_SD_check']='Kontrola zrnitostního SD';
$ec_lang['rc_sg_ok']   ='sg v platném rozsahu (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Varování: sg < 2,54 — pod platným rozsahem Robinson';
$ec_lang['rc_sg_high'] ='Varování: sg > 2,82 — nad platným rozsahem Robinson';
$ec_lang['rc_SD_ok']   ='SD v platném rozsahu (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Varování: SD < 1,15 — pod platným rozsahem Robinson';
$ec_lang['rc_SD_high'] ='Varování: SD > 1,47 — nad platným rozsahem Robinson';
$ec_lang['rc_layer']='Tloušťka kamenné vrstvy (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Poloměr oblouku na koruně (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Délka oblouku na koruně';
$ec_lang['rc_apron_length']='Délka vývarové desky na výtoku (15 × D<sub>50</sub>) <span title="Nezbytné pro konstrukční stabilitu kamene skluzu." (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Manningova drsnost skluzu, n';
$ec_lang['rc_Vm']='Rychlost proudění kamennou vrstvou, V<sub>m</sub> <span title="Část qt protékající póry kamenného záhozu. Zbytek qs teče po povrchu. Výchozí np = 0,45 pro ostrohranný drcený kámen." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Jednotkový průtok kamennou vrstvou, q<sub>m</sub>';
$ec_lang['rc_qs']='Povrchový jednotkový průtok, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Hloubka proudu nad povrchem záhozu, d';
$ec_lang['rc_Hp']='Vzdutí na vtoku, H<sub>p</sub> <span title="Vzdutí (Hp > yn) je žádoucí — snižuje erozi na vtoku. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Kontrola vzdutí na vtoku';
$ec_lang['rc_pond_ok']  ='Hp > yn — vzdutí nad vtokem ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — žádné vzdutí — zkontrolujte vtok kvůli erozi';
$ec_lang['rc_eq1']='Rovn. 1 (S0 < 0,10) — mírný sklon';
$ec_lang['rc_eq2']='Rovn. 2 (0,10 ≤ S0 ≤ 0,40) — strmý sklon';
$ec_lang['rc_eq_warn_low']='Varování: S0 < 0,02 — pod ověřeným rozsahem Robinson';
$ec_lang['rc_eq_warn_high']='Varování: S0 > 0,40 — nad ověřeným rozsahem Robinson';
$ec_lang['rc_notes_1_term']='Rovnice pro dimenzování kamene';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) vyvinuli dvě empirické rovnice pro střední velikost záhozu D<sub>50</sub> na základě sklonu skluzu a jednotkového průtoku. Rovnice 1 platí pro mírné svahy (S<sub>0</sub> < 0,10); rovnice 2 platí pro strmé svahy (0,10 ≤ S<sub>0</sub> ≤ 0,40). Obě rovnice vyžadují q<sub>t</sub> v m²/s a vracejí D<sub>50</sub> v mm. Ověřený rozsah je 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Jednotkový průtok';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> je celkový jednotkový průtok na koruně skluzu (celkový průtok na jednotku šířky). Pro koryto s šířkou dna B a celkovým průtokem Q lze přibližně uvažovat q<sub>t</sub> ≈ Q / B, nebo jej vypočítat z podmínky kritické hloubky na vtoku skluzu.';
$ec_lang['rc_notes_3_term']='Proudění kamennou vrstvou';
$ec_lang['rc_notes_3_def']='Část celkového průtoku protéká póry kamenného záhozu (průtok vrstvou q<sub>m</sub>); zbývající část teče po povrchu kamene (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Hloubka proudu d se vypočítá z Manningovy rovnice aplikované na povrchový průtok q<sub>s</sub> s drsností skluzu n. Výchozí pórovitost n<sub>p</sub> = 0,45 je typická pro ostrohranný drcený kámen.';
$ec_lang['rc_notes_5_term']='Platný rozsah velikosti kamene';
$ec_lang['rc_notes_5_def']='Rovnice byly vyvinuty pro rozsah D<sub>50</sub> od 15 mm do 278 mm. Výsledky mimo tento rozsah jsou extrapolované a měly by být použity s dodatečným inženýrským posouzením.';
$ec_lang['rc_notes_6_term']='Výška vývarové desky na výtoku';
$ec_lang['rc_notes_6_def']='Výška horní plochy záhozu ve výtokovém úseku by měla být na úrovni nebo pod úrovní dna dolního koryta. Pokud je výše, zához na výtoku bude nestabilní.';
$ec_lang['rc_notes_7_term']='Kontrola vzdutí na vtoku';
$ec_lang['rc_notes_7_def']='Pokud je normální hloubka ve vtokové stoce menší než přepadová výška (H<sub>p</sub>) potřebná k převedení q<sub>t</sub>, dochází k omezení průtoku nebo vzdutí nad vtokovou deskou. To je obecně přijatelné — vzdutí snižuje rychlost a zabraňuje erozi na vtoku. Kontrola: pomocí kalkulačky přelivu zjistěte H<sub>p</sub> pro dané q<sub>t</sub> a šířku koruny a porovnejte s normální hloubkou vtokové stoky. Pokud H<sub>p</sub> překračuje normální hloubku, dojde ke vzdutí.';
$ec_lang['rc_notes_4_term']='Literatura';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS také zveřejňuje <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">tabulku Excel</a> založenou na stejné metodě.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtr';
$ec_lang['rc_sketch_top_crest_curve'] = 'Vrcholový oblouk';
$ec_lang['rc_sketch_outlet_apron']    = 'Výtokový práh';
$ec_lang['rc_sketch_radius']          = 'poloměr';

// Irrigation Pressure
$ec_lang['ip_main_menu']='Závlahový tlak';
$ec_lang['ip_main_title']='Bezplatný online kalkulátor tlaku závlahy a uniformity distribuce';
$ec_lang['ip_main_desc']='Odhad tlaku a uniformity testovací cesty';
$ec_lang['ip_h_supply']='Tlak na vstupu';
$ec_lang['ip_elev_supply']='Nadmořská výška vstupu, z<sub>supply</sub>';
$ec_lang['ip_q_design']='Návrhový průtok emitoru, q<sub>design</sub>';
$ec_lang['ip_h_design']='Návrhový tlak emitoru';
$ec_lang['ip_x']='Exponent výstupního průtoku emitoru, x <span title="0,5 pro standardní nekompenzované emitory; blízko 0 pro tlakově kompenzované emitory" class="ec-tip">?</span>';
$ec_lang['ip_reach_table_title']='Testovací cesta';
$ec_lang['ip_group_reach']='Úsek';
$ec_lang['ip_group_upstream']='Proti proudu';
$ec_lang['ip_group_downstream']='Po proudu';
$ec_lang['ip_group_loss']='Ztráta';
$ec_lang['ip_is_lateral']='Postranní <span title="Zaškrtnuto: tento úsek je segment testovací postranní větve, připojen jednotlivými emitory. Nezaškrtnuto: tento úsek je hlavní potrubí, pouze předávající průtok postranním větvím mimo testovací cestu." class="ec-tip">?</span>';
$ec_lang['ip_count']='Emitory <span title="Postranní řady: emitory v tomto úseku pouze. Hlavní řady: celkový počet emitorů na postranních větvích JINÉ než zde větvící se z tohoto úseku. V úseku přímo v místě odebírání testovací postranní větve se zahrnou také všechny postranní větve dále po hlavním potrubí za tímto odběrem, nebo sdílející stejný spoj (např. postranní větev na opačné straně) &mdash; jejich průtok také prochází tímto úsekem." class="ec-tip">?</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_e']='e <span title="Darcyho-Weisbachova výška drsnosti" class="ec-tip">?</span>';
$ec_lang['ip_km']='K<sub>m</sub> <span title="Obecný součinitel místní ztráty pro armatury/ventily/spojky v tomto úseku (&ge;0,5 doporučené minimum)" class="ec-tip">?</span>';
$ec_lang['ip_elev_ds']='DS Nadm. výška <span title="Nadmořská výška dolního konce úseku. Volitelná v interních řadách (pokud ponecháno prázdné, defaultuje na vodorovně / stejně jako uzel výše). Povinná v poslední řadě: tato hodnota je nadmořská výška posledního emitoru, která přímo určuje požadovaný vstupní tlak." class="ec-tip">?</span>';
$ec_lang['ip_elev_ds_missing_warn']='Nadmořská výška posledního emitoru (poslední řada) byla ponechána prázdná a defaultovala na vodorovně &mdash; zadejte ji pro přesný výsledek ⚠';
$ec_lang['ip_flow']='Průtok';
$ec_lang['ip_press']='Tlak';
$ec_lang['ip_v']='V';
$ec_lang['ip_hv']='H<sub>v</sub>';
$ec_lang['ip_hf']='H<sub>f</sub>';
$ec_lang['ip_hm']='H<sub>m</sub>';
$ec_lang['ip_hl']='H<sub>l</sub> <span title="Celková ztráta v úseku, H_f + H_m" class="ec-tip">?</span>';
$ec_lang['ip_pressure_warn']='Nízký/záporný tlak &mdash; kontrolujte podmínky pod atmosférickým tlakem';
$ec_lang['ip_pressure_warn_short']='Nízký ⚠';
$ec_lang['ip_h_far']='Tlak posledního emitoru';
$ec_lang['ip_q_supply']='Průtok vstupu testovací cesty, Q<sub>supply</sub> <span title="Průtok vstupující modelovanou testovací cestu pouze, ne celou zónu/systém &mdash; viz Q_zone v Návrhu aplikace níže pro systémový celkem." class="ec-tip">?</span>';
$ec_lang['ip_q_critical']='Průtok posledního emitoru, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='Průtok průměrného emitoru (testovací postranní větev), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='Odh. &Delta;tlak, průměr vs. testovací postranní větev <span title="Jak moc vyšší (nebo nižší) si myslíte, že běží typická/průměrná postranní větev ve srovnání s touto testovací postranní větví. Testovací postranní větev je úmyslně nejhorší případ, takže její vlastní průměr je zkreslený dolní odhad pro skutečný průměr &mdash; ponecháno na 0, kontrola uniformity a čísla návrhu aplikace níže používají vlastní průměr testovací postranní větve jako je." class="ec-tip">?</span>';
$ec_lang['ip_q_avg_field']='Odh. průtok průměrného emitoru v poli, q<sub>avg,field</sub> <span title="q_avg_lateral přehodnocený při tlaku každé řady postranní větve plus zadaný rozdíl tlaku výše &mdash; pokus opravit, že testovací postranní větev je nejhorší případ, ne reprezentativní. Podává jak kontrolu uniformity, tak čísla návrhu aplikace níže." class="ec-tip">?</span>';
$ec_lang['ip_du_estimate']='Kontrola uniformity, q<sub>last</sub>/q<sub>avg,field</sub> <span title="Vypočítaný průtok posledního emitoru dělený odhadovaným průtokem průměrného emitoru v poli &mdash; stejný tvar jako učebnicová Uniformita distribuce nízké čtvrtiny (průměr nízké skupiny ÷ průměr populace), ale vypočítaná z malého modelovaného vzorku a uživatelsky odhadnuté opravy, ne ze statistického vzorku celého pole. Hodnoty na 1 nebo výše jsou možné a nejsou chybou: znamená to, že poslední emitor není nejnižší bod relativně k odhadovanému průměru v poli (např. příznivý svah dolů, nebo odhadnutý rozdíl tlaku výše je příliš malý)." class="ec-tip">?</span>';
$ec_lang['ip_worst_case_warn']='Tlak testovacího emitoru je roven nebo vyšší než tlak na vstupu &mdash; tato cesta pravděpodobně není vaše nejhorší postranní větev. Zkontrolujte vzdálenější nebo vysoce trecí postranní větev, nebo profil nadmořských výšek, který lépe reprezentuje skutečný nejhorší případ.';
$ec_lang['ip_q_ratio']='Průtok posledního emitoru vs. návrhový průtok, q<sub>last</sub>/q<sub>design</sub> <span title="Odlišná kontrola, ne číslo uniformity: jak daleko běží poslední emitor od navrženého návrhu výrobce. Výše 1: běží výše svého návrhového bodu (např. z příznivého zisku nadmořské výšky dolů). Níže 1: běží pod návrhem (typický případ dominovaný třením)." class="ec-tip">?</span>';
$ec_lang['ip_no_solution']='Žádné řešení: požadovaný vstupní tlak překračuje zadaný vstupní tlak. Zvyšte vstupní tlak, snižte poptávku, nebo použijte větší potrubí.';
$ec_lang['ip_notes_1_term']='Metoda';
$ec_lang['ip_notes_1_def']='Odhadne tlak na posledním (nejdálejším) emitoru, poté postupuje Energetickou vrstvou zpět k vstupu, úsek po úseku, přidávaje tření a místní ztráty po cestě. Nadmořská výška a rychlostní hlava jsou extrahování na každém uzlu tak aby hlásily skutečný tlak tam. Odhadnutý tlak na konci je korigován (bisekce) až do té doby, než vypočítaný požadovaný vstupní tlak odpovídá zadaému vstupnímu tlaku &mdash; stejný problém uzavřené smyčky řešený řešičem průtoku potrubí na kalkulátoru Průtoku v Manningovém Potrubí, rozšířený na větvící se síť.';
$ec_lang['ip_notes_2_term']='Hlavní vs. Postranní Úseky';
$ec_lang['ip_notes_2_def']='Každý řádek je jeden úsek podél jedné hydraulicky nejhorší cesty (testovací cesty) od vstupu k poslednímu emitoru. Hlavní úsek pouze předává průtok postranním větvím mimo testovací cestu, takže jeho odběr je jednoduché násobení (návrhový průtok × celkový počet emitorů v úseku) &mdash; žádná citlivost na místní tlak. Hlavní potrubí je sdílený kmenový svod, takže úsek přímo v místě odebírání testovací postranní větve musí zahrnout nejen postranní větve mezi svými koncovými body, ale také všechny postranní větve stále dále po hlavním potrubí za tímto odebíráním, nebo sdílející stejný spoj (např. postranní větev na opačné straně) &mdash; jejich průtok cestuje stejným úsekem před rozštěpením, ať se v této tabulce objevují nebo ne. Postranní úsek je segment testovací postranní větve: výtok emitoru je vypočítán ze skutečného místního tlaku přes q = k·H<sup>x</sup>, a ztráta třením je snížena Christiansenův faktor F(n) aby se zohlednil pokles průtoku jak každý emitor v úseku odvádí vodu.';
$ec_lang['ip_notes_3_term']='Omezení';
$ec_lang['ip_notes_3_def']='Modeluje jeden pevný vstupní tlak (žádná křivka čerpadla), jednu testovací cestu pouze (ne celé pole), a dvouparametrickou křivku emitoru (nastavte exponent blízko 0 aby aproximoval emitor s kompenzací tlaku). Hlášeny jsou dva různé poměry, úmyslně odděleny: q<sub>last</sub>/q<sub>avg,field</sub> je kontrola uniformity, tvaru jako učebnicová Uniformita distribuce nízké čtvrtiny (průměr nízké skupiny ÷ průměr populace), ale vypočítaná z vlastních modelovaných emitorů testovací postranní větve, opravená zadaným odhadem &Delta;tlaku spíše než úplným statistickým vzorkem pole &mdash; testovací postranní větev je úmyslně nejhorší předpokládaný případ, takže její nezákonitý neispravený průměr by podceňoval skutečný průměr pole a dělal uniformitu lépe vypadající než je; vstup &Delta;tlaku existuje právě aby vzdoroval tomu zkreslení. Hodnoty na 1 nebo výše jsou stále možné (např. odhad &Delta;tlaku je příliš malý, nebo příznivý svah dolů). q<sub>last</sub>/q<sub>design</sub> je odlišná, ne-uniformitní kontrola proti navrženému průtoku výrobce &mdash; užitečná pro zachycení celkově přetlakovaného nebo nedotlakovaného systému, ale ne náhrada za číslo uniformity, od kdy návrhový/jmenovitý průtok nemá nutný vztah k aktuálnímu průměrnému pracovnímu tlaku systému.';
$ec_lang['ip_notes_4_term']='Odkaz';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. Standardy ASAE/ASABE pro návrh mikroirrigace používají stejný přístup ztráty třením vícečetného výstupu.';
$ec_lang['ip_notes_5_term']='Návrh aplikace';
$ec_lang['ip_notes_5_def']='Dávka aplikace a průtok systému/zóny používá odhadovaný průtok průměrného emitoru v poli (q<sub>avg,field</sub> &mdash; vlastní průměr testovací postranní větve, korigovaný zadaným odhadem &Delta;tlaku), ne odhadovanou sazbu: PR = q<sub>avg,field</sub> / A<sub>e</sub>, podávaný korigovanou modelovanou hodnotou. Rozteče a počty postranních větví/emitorů v systému jsou oddělené vstupy zde, protože testovací cesta modeluje pouze jednu nejhorší větev, ne každou postranní větev v poli.';
$ec_lang['irr_card_pressure_head']='Závlahový tlak & Uniformita';
$ec_lang['irr_card_pressure_desc']='Modelujte profil tlaku a průtoku podél větve hlavní-postranní-emitor pro odhad distribuční uniformity ze skutečného tlaku testovací cesty, ne jen z katalogového průtoku emitoru.';
