<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='کسر';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']='rise/run';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC محاسبې';
$ec_lang['menu_main_list']='د محاسبو لیست';
$ec_lang['menu_main_hydraulics']='هایدرولیک';
$ec_lang['menu_main_language']='ژبه';
$ec_lang['template_welcome']='&gt;&gt; خپل ویرونه دروازې ته پرېږده؛ دلته مینه زموږ ژبه ده. ته هر څه خرابوي نه یې. د <a target="_blank" href="https://hawsedc.com/download.php">وړیا HawsEDC AutoCAD وسیلو</a> خوند هم واخله. &lt;&lt;';
$ec_lang['template_translation_help']='ایا ستاسو د دلته د زیاتولو لپاره د کومې محاسبې لویه لید لرئ؟ ایا تاسو کولی شئ چې ژباړه، پروګرامولو، یا دا محاسبې کوربه کولو کې مرسته وکړئ؟  ';
$ec_lang['template_feedback']='مهرباني وکړئ خپلې ارزښتناکې وړاندیزونه یا ستاینې موږ ته راولیږئ. ایا دې وړیا محاسبې ستاسو تمې له هر اړخه پوره کړل؟';
$ec_lang['template_printable_title']='د چاپ سرلیک';
$ec_lang['template_printable_subtitle']='د چاپ فرعي سرلیک';
$ec_lang['index_title']='وړیا آنلاین انجینري محاسبې';
$ec_lang['calc_set_units']='واحدونه تنظیم کړئ:';
$ec_lang['points_data_help']='(یا د معلوماتو ساحې له لارې کاپي/پیسټ وکړئ)';
$ec_lang['points_data_title']='د نقطو معلومات<br />(د کوما یا ټب لخوا جلا شوي)';
$ec_lang['points_data_copy']='کاپي';
$ec_lang['points_data_paste']='پیسټ';
$ec_lang['calc_inputs']='ننوتنې';
$ec_lang['calc_results']='پایلې';
$ec_lang['view_hide_line']='[دا کرښه پټه کړئ]';
$ec_lang['view_printable']='د چاپ وړ نسخه (د بیا ترلاسه کولو لپاره بیا پورته کړئ)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach د پایپ سر ضیاع';
$ec_lang['dw_main_title']='وړیا آنلاین Darcy-Weisbach د پایپ سر ضیاع محاسبه';
$ec_lang['dw_main_desc']='Darcy-Weisbach د پایپ سر ضیاع د ورکړل شوي قطر، خشونت، او بهاو سره';
$ec_lang['dw_roughness']='Darcy-Weisbach مطلق خشونت، e';
$ec_lang['dw_kinematic_viscosity']='د حرکت ویسکوزیته، v، د m<sup>2</sup>/sec په واحد (د کوټې د تودوخې پر مهال د صاف اوبو لپاره 1E-6)';
$ec_lang['dw_reynolds_number']='د Reynolds عدد، Re';
$ec_lang['dw_flow_regime']='د بهاو رژیم';
$ec_lang['dw_regime_laminar']='لامینار';
$ec_lang['dw_regime_transitional']='انتقالي';
$ec_lang['dw_regime_turbulent']='توربولنت';
$ec_lang['dw_friction_factor_method']='د اصطکاک فاکتور میتود';
$ec_lang['dw_friction_factor']='د اصطکاک فاکتور، f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams د پایپ سر ضیاع';
$ec_lang['hw_main_title']='وړیا آنلاین Hazen-Williams د پایپ سر ضیاع محاسبه';
$ec_lang['hw_main_desc']='Hazen-Williams د پایپ سر ضیاع د ورکړل شوي قطر، خشونت، او بهاو سره';
$ec_lang['hw_hgl_1']='ښکته HGL';
$ec_lang['hw_hgl_2']='پورته HGL';
$ec_lang['hw_roughness']='Hazen-Williams ضریب، C';
// Manning Irregular
$ec_lang['mi_menu']='Manning نامنظم چینل';
$ec_lang['mi_main_title']='وړیا آنلاین Manning نامنظم چینل محاسبه';
$ec_lang['mi_main_desc']='د نامنظم چینل Manning یکسان بهاو محاسبه';
$ec_lang['mi_waterSurfaceElevation']='د اوبو سطحې لوړوالی';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='د مقطع نقطې';
$ec_lang['mi_groupPoint']='نقطه';
$ec_lang['mi_groupSegment']='برخه';
$ec_lang['mi_groupRegion']='سیمه';
$ec_lang['mi_station']='سټیشن';
$ec_lang['mi_elevation']='لوړوالی';
$ec_lang['mi_d50in']='پوښ<br />منځنۍ<br />کاڼي<br />اندازه';
$ec_lang['mi_n']='n<br />د برخې<br />لپاره';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />سیمه<br />حد<br />(غاړه)';
$ec_lang['mi_tau']='لاندینۍ<br />قیچي<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='مرکب<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='یادداشتونه';
$ec_lang['mi_notes_1_term']='مرکب n';
$ec_lang['mi_notes_1_def']='دا محاسبه د HEC-RAS د حوالې لارښود پیروي کوي چې د Chow 1959، مخ 136، معادله 6-17 (نه 6-18) کارولو سره د سیمې مرکب n حساب کوي.';
$ec_lang['mi_notes_2_term']='د کاڼو پوښ';
$ec_lang['mi_notes_2_def']='د کاڼو پوښ ډیزاین کولو لپاره د Manning ذوزنقه چینل محاسبه وکاروئ. دا محاسبه د طبیعي مقطعونو لپاره ډیره مناسبه ده.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning د پایپ بهاو';
$ec_lang['mpf_main_title']='وړیا آنلاین Manning د پایپ بهاو محاسبه';
$ec_lang['mpf_main_desc']='د Manning فارمول یکسان د پایپ بهاو د ورکړل شوي میل او ژوروالي سره';
$ec_lang['mpf_spreadheet_notice']='د دې محاسبې د سپریډشیټ نسخه وګورئ';
$ec_lang['mpf_pipe_diameter']='د پایپ قطر، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning خشونت، n';
$ec_lang['mpf_friction_slope']='د فشار میل (احتمالاً <a target="_blank" href="../pressureslope.php">?</a> د پایپ میل سره مساوي)، S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='د بهاو نسبي ژوروالی، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(یادداشتونه وګورئ)';
$ec_lang['mpf_flow']='بهاو، Q';
$ec_lang['mpf_velocity']='سرعت، v';
$ec_lang['mpf_velocity_head']='د سرعت سر، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='د بهاو مساحت، a';
$ec_lang['mpf_pipe_area']='د پایپ مساحت، a0';
$ec_lang['mpf_area_ratio']='نسبي مساحت، a/a0';
$ec_lang['mpf_wetted_perimeter']='د لندوالي محیط، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='هایدرولیکي رادیوس، R<sub>h</sub>';
$ec_lang['mpf_top_width']='پورتني پلنوالی، T';
$ec_lang['mpf_froude_number']='د Froude عدد، F';
$ec_lang['mpf_shear_stress']='منځني قیچي فشار (کشنه قوه)، tau';
$ec_lang['mpf_full_flow']='بشپړ بهاو، Q0';
$ec_lang['mpf_full_flow_ratio']='د بشپړ بهاو نسبت، Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>دا د یوه <em>بې نهایته اوږد</em> پایپ دننه بهاو او ژوروالی دی.</dt><dd>د پایپ ته د بهاو داخلولو لپاره ممکن د پام وړ لوړ سرسر ژوروالی ته اړتیا وي. د سرسر ژوروالي ترلاسه کولو لپاره لږ تر لږه ۱.۵ ځله د سرعت سر زیات کړئ، یا د HY-8 کارولو سره د معیاري کلورټ سرسر محاسبو لپاره <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">زما دوه دقیقو ټیوټوریل وګورئ</a>.</dd>';
$ec_lang['mpf_solve_for_dd0']='د ورکړل شوي Q لپاره y/d<sub>0</sub> حل کول';
$ec_lang['mpf_solve_desc']='د محاسبې فورمه د D<sub>0</sub>، n، او S<sub>0</sub> کارولو سره، د ورکړل شوي Q لپاره ټیټ ترین y/d<sub>0</sub> پیدا کوي.';
$ec_lang['mpf_solve_button']='حل کړئ';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning د پایپ سر ضیاع';
$ec_lang['mphl_main_title']='وړیا آنلاین Manning د پایپ سر ضیاع محاسبه';
$ec_lang['mphl_main_desc']='د Manning فارمول سر ضیاع د ورکړل شوي بشپړ بهاو سره';
$ec_lang['mphl_pipe_length']='د پایپ اوږدوالی، L';
$ec_lang['mphl_area']='مساحت، A';
$ec_lang['mphl_total_junction_k']='د ټولو مشترک جنکشن ضیاع ضریب، k';
$ec_lang['mphl_friction_slope']='د اصطکاک میل';
$ec_lang['mphl_friction_loss']='د اصطکاک ضیاع، H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='د جنکشن ضیاع، H<sub>m</sub>';
$ec_lang['mphl_total_loss']='ټول ضیاع، H<sub>l</sub>';
$ec_lang['mphl_egl_1']='ښکته EGL';
$ec_lang['mphl_egl_2']='پورته EGL';
$ec_lang['mphl_hgl_2']='د پایپ پورته HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>د خلاص دننه ننوت (کلورټ) د حالت لپاره، د ننوت کنترول حالتونو چک کول اړین دي.</dt><dd>۱. پورتني HGL د پورتني نورمال ژوروالي د بهاو لوړوالي (یا د پایپ لاندې) کمیدلی نشي.</dd><dd>۲. د کلورټ سرسر د پورتني EGL له خوا د پورتني HGL پر ځای ښه استازولی کیږي.</dd><dd>۳. د HY-8 کارولو سره د ساده معیاري کلورټ سرسر محاسبو لپاره <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">زما دوه دقیقو ټیوټوریل وګورئ</a>.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning ذوزنقه چینل';
$ec_lang['mtc_main_title']='وړیا آنلاین Manning فارمول ذوزنقه چینل محاسبه';
$ec_lang['mtc_main_desc']='Manning فارمول یکسان ذوزنقه چینل بهاو د ورکړل شوي میل او ژوروالي سره';
$ec_lang['mtc_bottom_width']='لاندیني پلنوالی، b';
$ec_lang['mtc_side_slope_1']='د اړخ میل ۱ (افقي/عمودي)';
$ec_lang['mtc_side_slope_2']='د اړخ میل ۲ (افقي/عمودي)';
$ec_lang['mtc_channel_slope']='د چینل میل، S';
$ec_lang['mtc_flow_depth']='د بهاو ژوروالی، y';
$ec_lang['mtc_bend_angle']='د ګوډ زاویه <a target="_blank" href="riprap-bend-angle.png" title="Click for image">?</a> (د ریپراپ اندازه کولو لپاره)';
$ec_lang['mtc_sgrock']='د کاڼو ځانګړی ثقل (2.65)';
$ec_lang['mtc_d50_in']='د ډیزاین کاڼو اندازه، D50';
$ec_lang['mtc_n_strickler']='د Strickler له مخې د ډیزاین کاڼو اندازې لپاره n';
$ec_lang['mtc_n_blodgett']='د Blodgett له مخې د ډیزاین کاڼو اندازې لپاره n';
$ec_lang['mtc_n_bathurst']='د Bathurst له مخې د ډیزاین کاڼو اندازې لپاره n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett مقابل Bathurst';
$ec_lang['mtc_d50_bottom']='اړین لاندیني زاویه لرونکي کاڼو اندازه، D50 (Isbash او MC) <a href="javascript:alert(\'د Isbash (1936) او Maricopa County, Arizona, US له مخې.\')">?</a>';
$ec_lang['mtc_d50_z1']='اړین د اړخ میل ۱ زاویه لرونکي کاڼو اندازه، D50 (Isbash او MC) <a href="javascript:alert(\'د Isbash (1936) او Maricopa County, Arizona, US له مخې.\')">?</a>';
$ec_lang['mtc_d50_z2']='اړین د اړخ میل ۲ زاویه لرونکي کاڼو اندازه، D50 (Isbash او MC) <a href="javascript:alert(\'د Isbash (1936) او Maricopa County, Arizona, US له مخې.\')">?</a>';
$ec_lang['mtc_d50_mra']='اړین زاویه لرونکي کاڼو اندازه، D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='اړین زاویه لرونکي کاڼو اندازه، D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>د کاڼو اندازه او خشونت ډیزاین اتوماتیک تکرار</dt><dd>یو خشونت ریډیو تڼۍ (BB وړاندیز کیږي) او د ډیزاین کاڼو اندازې ریډیو تڼۍ (Isbash وړاندیز کیږي) غوره کړئ. ژوروالی او د کاڼو اندازې امنیتي فاکتور سم کړئ ترڅو خپل غوښتل شوي بهاو د مساوي کاڼو اندازې سره ترلاسه کړئ. هر ځل چې تاسو کوم داخلي ارزښت بدل کړئ، لاندینی تکرار دور پیښیږي: ۱. خشونت د ډیزاین کاڼو اندازې له مخې محاسبه کیږي. ۲. غوښتل شوي خشونت محاسبه د داخلي خشونت ته کاپي کیږي. ۳. د چینل بهاو او اړین کاڼو اندازه محاسبه کیږي. ۴. د ډیزاین کاڼو اندازه تنظیمیږي. ۵. د ډیزاین کاڼو اندازې کې تیروتنه ډیره کوچنۍ شي پورې تکرار کیږي.</dd><dt>اساسي محاسبه (بدون تکرار)</dt><dd>خپل غوښتل شوي خشونت ارزښت داخل کړئ. د ډیزاین کاڼو اندازې داخلي ساحه له پامه غورځوئ.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='Robinson Rock Chute د ډیزاین سپریډشیټ';
// Weir Flow Simple
$ec_lang['ws_main_menu']='ساده د ویر بهاو';
$ec_lang['ws_main_title']='وړیا آنلاین ساده پراخ تاج لرونکي ویر بهاو محاسبه';
$ec_lang['ws_main_desc']='ساده پراخ تاج لرونکي ویر بهاو محاسبه';
$ec_lang['ws_weirLength']='د ویر اوږدوالی، l';
$ec_lang['ws_headWaterHeight']='د سرسر لوړوالی، h';
$ec_lang['ws_weirCoefficient']='د ویر ضریب، Cw';
$ec_lang['ws_notes_heading']='یادداشتونه';
$ec_lang['ws_notes_we_term']='د ویر معادله';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='نامنظم د ویر بهاو';
$ec_lang['wi_main_title']='وړیا آنلاین برخه شوي، متغیر ژوروالي، نامنظم ویر بهاو محاسبه';
$ec_lang['wi_main_desc']='نامنظم ویر بهاو محاسبه';
$ec_lang['wi_headWaterelevation']='د سرسر لوړوالی';
$ec_lang['wi_weirPoints']='د ویر نقطې';
$ec_lang['wi_station']='سټیشن<br />(واټن)';
$ec_lang['wi_elevation']='لوړوالی';
$ec_lang['wi_pondingHeight']='د ډنډ لوړوالی';
$ec_lang['wi_incrementalFlow']='زیاتیدونکی بهاو';
$ec_lang['wi_cumulativeFlow']='ټولیز انباشتي بهاو';
$ec_lang['wi_save_and_calculate']='خوندي کړئ او محاسبه وکړئ';
$ec_lang['wi_notes_we_term']='د ویر معادله';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='د سوري بهاو';
$ec_lang['or_main_title']='وړیا آنلاین د سوري بهاو محاسبه';
$ec_lang['or_main_desc']='د سوري بهاو — آزاد یا لاندې اوبو';
$ec_lang['or_shape']='د خلاص شکل';
$ec_lang['or_shape_circular']='دایروي';
$ec_lang['or_shape_rectangular']='مستطیلي';
$ec_lang['or_diameter']='قطر (دایروي) یا لوړوالی (مستطیلي)، D';
$ec_lang['or_width']='پلنوالی، W (یوازې مستطیلي)';
$ec_lang['or_invert']='د خلاص انورټ لوړوالی (د خلاص لاندینی برخه)';
$ec_lang['or_hwe']='د سرسر لوړوالی';
$ec_lang['or_twe']='د غوپه اوبو لوړوالی';
$ec_lang['or_cd']='د خارجولو ضریب، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='د مرکز لوړوالی';
$ec_lang['or_head']='مؤثره سر، h';
$ec_lang['or_area']='د خلاص مساحت، A';
$ec_lang['or_flow']='بهاو، Q';
$ec_lang['or_velocity']='د خلاص سرعت، v';
$ec_lang['or_regime']='د سوري رژیم چک';
$ec_lang['or_regime_valid']='آزاد وتل — د سوري رژیم معتبر ✓';
$ec_lang['or_regime_submerged']='لاندې اوبو کې سوری (TWE د انورټ پورته) — معتبر ✓';
$ec_lang['or_regime_warn']='خبرداری: سرسر د تاج لاندې — د سوري رژیم نه دی';
$ec_lang['or_regime_twe_above_hwe']='خبرداری: غوپه اوبه (TWE) د سرسر (HWE) پورته — داخلونه چک کړئ';
$ec_lang['or_notes_1_term']='د سوري معادله';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). د آزاد وتلو لپاره: h = HWE &minus; مرکز. د لاندې اوبو بهاو لپاره (TWE د انورټ پورته): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='د سوري رژیم';
$ec_lang['or_notes_2_def']='د سوري بهاو معادلې هغه وخت اعمالیږي کله چې د سرسر سطحه د خلاص د تاج (پورتني) پورته وي. کله چې سرسر د تاج لاندې وي، پر ځای یې د ویر معادله وکاروئ.';
$ec_lang['or_notes_3_term']='د خارجولو ضریب';
$ec_lang['or_notes_3_def']='C<sub>d</sub> د تیز غاړو سوریو لپاره د شاوخوا 0.60&ndash;0.65 پورې وي. ګرد شوي یا بیرته ننوتلي ننوتونه مختلف ارزښتونه کاروي. د لارښوونې لپاره <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> یا HEC-RAS هایدرولیک حوالې لارښود وګورئ.';
$ec_lang['or_notes_4_term']='لاندې اوبو حالت';
$ec_lang['or_notes_4_def']='کله چې TWE د خلاص انورټ پورته وي، دا محاسبه اتوماتیک د لاندې اوبو د سوري معادله h = HWE &minus; TWE کاروي. کله چې TWE د انورټ پر سطحه یا لاندې وي، آزاد وتل فرض کیږي او h = HWE &minus; مرکز.';
// Penstock Design
$ec_lang['ps_main_menu']='د Penstock ډیزاین';
$ec_lang['ps_main_title']='وړیا آنلاین د Penstock ډیزاین محاسبه';
$ec_lang['ps_main_desc']='د مایکرو هایدرو Penstock اندازه کول — د سر ضیاع، ځواک، او سرعت';
$ec_lang['ps_flow']='د بهاو مقدار، Q';
$ec_lang['ps_gross_head']='ناخالص سر، H<sub>gross</sub>';
$ec_lang['ps_diameter']='د Penstock قطر، D';
$ec_lang['ps_length']='د Penstock اوږدوالی، L';
$ec_lang['ps_roughness']='د پایپ خشونت، e';
$ec_lang['ps_km']='د جنکشن (یا &ldquo;کوچني&rdquo;) ضیاع ضریب، k<sub>m</sub>';
$ec_lang['ps_nu']='د حرکت ویسکوزیته، &nu;، د m<sup>2</sup>/s په واحد (د 20&deg;C نږدې اوبو لپاره 1E-6)';
$ec_lang['ps_efficiency']='د پلانټ اغیزمنتیا، &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='د بهاو سرعت، v';
$ec_lang['ps_vel_check']='د سرعت چک';
$ec_lang['ps_f']='د اصطکاک فاکتور، f';
$ec_lang['ps_hf']='د اصطکاک د سر ضیاع، h<sub>f</sub>';
$ec_lang['ps_hm']='د جنکشن (نقطوي) د سر ضیاع، h<sub>m</sub>';
$ec_lang['ps_hl']='د Penstock ټول ضیاع، h<sub>L</sub>';
$ec_lang['ps_hl_check']='د سر ضیاع چک';
$ec_lang['ps_hnet']='خالص سر، H<sub>net</sub>';
$ec_lang['ps_power']='د ځواک محصول، P';
$ec_lang['ps_annual_kwh']='کلنۍ انرژي د ۱۰۰٪ ظرفیت پر مهال';
$ec_lang['ps_vel_ok']='1–3 m/s — د هدف دننه ✓';
$ec_lang['ps_vel_low']='د 1 m/s لاندې — قطر لوی کړئ ⚠';
$ec_lang['ps_vel_high']='د 3 m/s پورته — قطر کوچنی کړئ ⚠';
$ec_lang['ps_hl_ok']='د ۱۰٪ هدف دننه ✓';
$ec_lang['ps_hl_warn']='د ۱۰٪ هدف تجاوزوي — لوی پایپ پر غور وکړئ ⚠';
$ec_lang['ps_hl_bad']='د ۲۰٪ تجاوزوي — پایپ بیا اندازه کړئ';
$ec_lang['ps_notes_1_term']='د سر ضیاع';
$ec_lang['ps_notes_1_def']='د Penstock ټول ضیاع h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، چیرې چې h<sub>f</sub> = f(L/D)(v&sup2;/2g) د Darcy-Weisbach اصطکاک ضیاع دی او h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g ننوت، ګوډونه، او والوونه پوښي. خالص سر H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='سرعت';
$ec_lang['ps_notes_2_def']='هدف 1&ndash;3 m/s. د 1 m/s لاندې پایپ د بهاو لپاره ډیر لوی اندازه کوي؛ د 3 m/s پورته د اصطکاک ضیاعات او د اوبو چکش خطر زیاتوي.';
$ec_lang['ps_notes_3_term']='د سر ضیاع هدف';
$ec_lang['ps_notes_3_def']='د ناخالص سر د ۱۰٪ لاندې د Penstock ضیاعات عموماً اقتصادي دي. د پایپ لګښت او د ضایع شوي ځواک ترمنځ مثالي مبادله اکثراً د لوړ ارزښت د برق ځایونو لپاره شاوخوا 4&ndash;6٪ کې راځي.';
$ec_lang['ps_notes_4_term']='د جنکشن (نقطوي) ضیاعات k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='دا ضیاعات د پایپ جنکشنونو، ننوتونو، ګوډونو، او والوونو کې پیښیږي &mdash; &ldquo;کوچني&rdquo; اصطلاح دودیزه خو ګمراه کوونکې ده؛ د لنډ Penstock کې ممکن د اصطکاک ضیاعاتو سره مساوي یا ترې ډیر وي. د k عادي ارزښتونه: تیز د ننوت دروازه 0.5، هر 45&deg; ګوډ 0.2&ndash;0.3، د دروازې والو (بشپړ خلاص) 0.1، پروانه والو 0.2. د ټول k<sub>m</sub> لپاره ټول فیټینګونه جمع کړئ. ډیفالټ 1.5 یو ننوت او دوه ګوډونه فرض کوي.';
$ec_lang['ps_notes_5_term']='د پایپ خشونت e';
$ec_lang['ps_notes_5_def']='عادي مطلق خشونت: فولاد (نوی) 0.046&nbsp;mm، فولاد (کارول شوی) 0.15&nbsp;mm، HDPE 0.003&nbsp;mm، PVC/uPVC 0.0015&nbsp;mm، کانکریټ 0.3&ndash;3&nbsp;mm. HDPE د کوچنیو مایکرو هایدرو Penstock لپاره عام دی.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='مایکرو هایدرو ځواک';
$ec_lang['mhp_main_title']='وړیا آنلاین مایکرو هایدرو ځواک محاسبه';
$ec_lang['mhp_main_desc']='د سیند بهاو مایکرو هایدرو ځواک محصول محاسبه';
$ec_lang['mhp_flow']='د بهاو مقدار، Q';
$ec_lang['mhp_gross_head']='ناخالص سر (د لوړوالي کمښت)، H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='د Penstock سر ضیاعات، h<sub>L</sub>';
$ec_lang['mhp_efficiency']='د پلانټ اغیزمنتیا، &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='خالص سر، H<sub>net</sub>';
$ec_lang['mhp_power']='د ځواک محصول، P';
$ec_lang['mhp_annual_kwh']='کلنۍ انرژي د ۱۰۰٪ ظرفیت پر مهال';
$ec_lang['mhp_notes_1_term']='د ځواک معادله';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>، چیرې چې &rho; = 1000 kg/m&sup3; (خوږې اوبه) او g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='خالص سر';
$ec_lang['mhp_notes_2_def']='خالص سر = ناخالص سر &minus; د Penstock سر ضیاعات. د لومړي اټکل لپاره عام تخمین h<sub>L</sub> &asymp; د H<sub>gross</sub> ۵٪ دی. د ډیر دقیق د Penstock ضیاع اټکل لپاره <a href="Darcy-Weisbach.php">Darcy-Weisbach محاسبه</a> وکاروئ.';
$ec_lang['mhp_notes_3_term']='اغیزمنتیا';
$ec_lang['mhp_notes_3_def']='د مایکرو هایدرو کې عام د Pelton او Cross-flow توربینونو لپاره عادي پلانټ اغیزمنتیا &eta; د 0.70 تر 0.85 پورې وي. د محافظه کارانه لومړي اټکل لپاره 0.75 وکاروئ.';
$ec_lang['mhp_notes_4_term']='کلنۍ انرژي';
$ec_lang['mhp_notes_4_def']='کلنۍ انرژي د دوامداره بشپړ بهاو عملیات (8760 ساعته/کال) فرض کوي. د موسمي بهاو توپیر، د ساتنې د ودرولو، او د بار فاکتور له امله واقعي تولید به لږ وي.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='د سوري ایستلو وخت';
$ec_lang['odt_main_title']='وړیا آنلاین د سوري ایستلو وخت محاسبه — ډنډ، حوض، یا ټانک';
$ec_lang['odt_main_desc']='د ډنډ یا حوض د سوري ایستلو وخت &mdash; د کونیکي حجم میتود';
$ec_lang['odt_h1_elev']='د اوبو د سطحې پیلیز لوړوالی';
$ec_lang['odt_a1']='د ډنډ یا حوض پیلیز مساحت، A1';
$ec_lang['odt_h2_elev']='د اوبو د سطحې پایلیز لوړوالی';
$ec_lang['odt_h_orifice']='د سوري د مرکز لوړوالی';
$ec_lang['odt_a0']='د سوري د لوړوالي پر کچه د ډنډ یا حوض مساحت، A0';
$ec_lang['odt_a_ending']='د ډنډ پایلیز مساحت، A2 (تخمین شوی)';
$ec_lang['odt_h2_check']='د پایلیز لوړوالي چک';
$ec_lang['odt_h2_ok']='پایلیز لوړوالی د سوري تاج پورته ✓';
$ec_lang['odt_h2_warn']='خبرداری: پایلیز لوړوالی د سوري تاج پر سطحه یا لاندې (مرکز + D/2)';
$ec_lang['odt_d']='د سوري قطر (دایروي) یا لوړوالی (مستطیلي)، D';
$ec_lang['odt_w']='د سوري پلنوالی، W (یوازې مستطیلي)';
$ec_lang['odt_t_sec']='د ایستلو وخت (ثانیې)';
$ec_lang['odt_t_min']='د ایستلو وخت (دقیقې)';
$ec_lang['odt_t_hr']='د ایستلو وخت (ساعتونه)';
$ec_lang['odt_t_day']='د ایستلو وخت (ورځې)';
$ec_lang['odt_notes_1_term']='فارمول';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) د سر H څخه تر سوري پورې د ایستلو وخت ورکوي. ایستلو وخت = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، چیرې چې H<sub>1</sub> = پیلیز لوړوالی &minus; د سوري لوړوالی، H<sub>2</sub> = پایلیز لوړوالی &minus; د سوري لوړوالی.';
$ec_lang['odt_notes_2_term']='میتود';
$ec_lang['odt_notes_2_def']='د کونیکي حجم میتود ډنډ یا حوض د پیلیز مساحت A<sub>1</sub> د لومړني اوبو سطحې کچه او د سوري د مرکز د لوړوالي کچه کې د مساحت A<sub>0</sub> ترمنځ د کونیکي برخې په توګه ماډل کوي. A<sub>2</sub>، د پایلیز لوړوالي کچه کې د ډنډ مساحت، د کونیکي برخې ماډل کارولو سره د A<sub>1</sub> او A<sub>0</sub> لخوا تخمین کیږي. د پیلیز لوړوالي څخه تر پایلیز لوړوالي پورې ایستلو وخت د H<sub>1</sub> لخوا د ټول ایستلو وخت سره د H<sub>2</sub> لخوا د پاتې ایستلو وخت منفي مساوي دی.';
$ec_lang['odt_h1']='پیلیز سر، H<sub>1</sub> (WSE &minus; مرکز)';
$ec_lang['odt_q_max']='اعظمي (پیلیز) بهاو، Q<sub>max</sub>';
$ec_lang['odt_vol']='ایستل شوی حجم';
$ec_lang['odt_sketch_start']='پیل';
$ec_lang['odt_sketch_end']='پای';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='د غاړه تر غاړه پلنوالی';
$ec_lang['essc_mcr']='لږترلږه د منحني رادیوس';
$ec_lang['essc_q']='بهاو، Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='د اوبه اچولو بهیر اندازه کول';
$ec_lang['irr_main_title']='د اوبه اچولو بهیر اندازه کولو وړیا آنلاین حسابونه';
$ec_lang['irr_main_desc']='د اوبه اچولو بهیر اندازه کول — د اوبو وزي او سوري';
$ec_lang['contact_title']='HawsEDC اړیکه';
$ec_lang['contactSendMessage']='Tom Haws ته پیغام ولیږئ';
$ec_lang['contactYourName']='ستاسو نوم:';
$ec_lang['contactYourEmail']='ستاسو بریښنالیک پته:';
$ec_lang['contactSubject']='موضوع:';
$ec_lang['contact_message']='پیغام:';
$ec_lang['contactSpamPrefix']='پنځه زیات یو مساوي دي';
$ec_lang['contactSpamPostfix']='(مهرباني وکړئ هغه ولیکئ. 1=یو 2=دوه 3=درې 4=څلور 5=پنځه 6=شپږ 7=اوه +=زیات 5+1=6)';
$ec_lang['contactSubmitButton']='پیغام ولیږئ';

// About
$ec_lang['about_main_menu']='د اړه';
$ec_lang['about_main_title']='د HawsEDC انجینري کالکولیټرونو د اړه';
$ec_lang['about_main_desc']='دنده، خلاص سرچینه، او همکاري';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Drip/Sprinkler Application Rate';
$ec_lang['ds_main_title']='Free Online Drip/Sprinkler Irrigation Application Rate Calculator';
$ec_lang['ds_main_desc']='Drip &amp; Sprinkler Irrigation &mdash; Application Rate and Uniformity';
$ec_lang['ds_q_avg']='Average emitter flow rate, q';
$ec_lang['ds_q_min']='Minimum emitter flow rate, q<sub>min</sub>';
$ec_lang['ds_se']='Emitter spacing along lateral, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateral spacing (row spacing), S<sub>l</sub>';
$ec_lang['ds_n_e']='Emitters per lateral, n<sub>e</sub>';
$ec_lang['ds_n_l']='Laterals per zone, n<sub>l</sub>';
$ec_lang['ds_d']='Target application depth, d';
$ec_lang['ds_a_e']='Area per emitter, A<sub>e</sub>';
$ec_lang['ds_pr']='Application rate (precipitation rate), PR';
$ec_lang['ds_du']='Distribution uniformity, DU';
$ec_lang['ds_du_check']='DU quality check';
$ec_lang['ds_q_lat']='Flow per lateral, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Zone flow, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Runtime for target depth (hours)';
$ec_lang['ds_du_excellent']='Excellent — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='Good — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='Acceptable — DU ≥ 70%';
$ec_lang['ds_du_poor']='Poor — DU < 70% — review design ⚠';
$ec_lang['ds_notes_1_term']='Application Rate';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, where A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> is the area served by each emitter. A lower application rate gives more time for infiltration &mdash; important on heavy soils or sloped fields.';
$ec_lang['ds_notes_2_term']='Distribution Uniformity (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. A DU of 1.0 (100%) means all emitters flow identically. Values below 0.80 waste water on well-watered areas while leaving drier spots. Uniformity drops with excessive pressure variation along the lateral, emitter wear, or partial clogging.';
$ec_lang['ds_notes_3_term']='Runtime';
$ec_lang['ds_notes_3_def']='Runtime = target depth &divide; application rate. On sloping or compacted soil, split the runtime into two or three shorter cycles with rest periods between them to avoid surface runoff.';
