<?php

// Alh missing text declarations wilh falh back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fração";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="pés^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ft']="pés";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_grade']="incl./compr.";
$ec_lang['u_gradePercent']='% incl./compr.';
$ec_lang['u_in2']="pol. quad.";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="pol.";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="segundos (seg)";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";

// Page text
// In page order for easiest maintenance.
$ec_lang['menu_main_list']='Lista de calculadoras';
$ec_lang['menu_main_hydraulics']='Hydraulica';
$ec_lang['menu_main_language']='Idioma';
$ec_lang['template_welcome']='>> Deixe seus medos na porta. O amor é falado aqui. Aproveite também <a href="https://hawsedc.com/download.php">as ferramentas livres HawsEDC para AutoCAD</a>.<<';
$ec_lang['template_translation_help']='Você pode me ajudar a traduzir esta calculadora para sua língua ou hostear esta calculadora em seu site?';
$ec_lang['template_feedback']='Por favor, dê-nos suas valiosas palavras de sugestão ou elogio. Esta calculadora gratuita excedeu suas expectativas em todos os aspectos?';
$ec_lang['template_printable_title']='Título imprimível';
$ec_lang['template_printable_subtitle']='Subtítulo imprimível';
$ec_lang['index_title']='Calculadoras de Engenharia Gratuitas Online';
$ec_lang['calc_set_units']='Definir unidades:';
$ec_lang['points_data_help']='(ou Copiar/Colar usando a área de dados)';
$ec_lang['points_data_title']='Dados dos pontos (separados por vírgula ou tabulação)';
$ec_lang['points_data_copy']='Copiar';
$ec_lang['points_data_paste']='Colar';
$ec_lang['calc_inputs']='Ingresos';
$ec_lang['calc_results']='Resultados';
$ec_lang['view_hide_line']='[Ocultar esta linha]';
$ec_lang['view_printable']='Versão Imprimible (recargar/renover para restaurar)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Pérdida de pressão em uma tubería de acordo com Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculadora gratis em linha de pérdida de pressão em uma tubería de acordo com Darcy-Weisbach';
$ec_lang['dw_main_desc']='Pérdida de pressão em uma tubería a dado diámetro, rugosidade, e caudal de acordo com Darcy-Weisbach';
$ec_lang['dw_roughness']='Rugosidade absoluto, e';
$ec_lang['dw_kinematic_viscosity']='<span title="1E-6 m^2/sec por agua limpia a la temperatura ambiente">Viscosidade kinemática, v (1E-6)</span>';
$ec_lang['dw_reynolds_number']='Número de Reynolds, Re';
$ec_lang['dw_flow_regime']='Régimen do flujo';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='transicional';
$ec_lang['dw_regime_turbulent']='turbulente';
$ec_lang['dw_friction_factor_method']='Método do factor de friccão';
$ec_lang['dw_friction_factor']='Factor de friccão, f';
// Hazen-Wilhiams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Pérdida de pressão em uma tubería de acordo com Hazen-Wilhiams';
$ec_lang['hw_main_title']='Calculadora gratis em linha de pérdida de pressão em uma tubería de acordo com Hazen-Wilhiams';
$ec_lang['hw_main_desc']='Calculadora de pérdida de pressão em uma tubería a dado diámetro, rugosidade, e caudal de acordo com Hazen-Wilhiams';
$ec_lang['hw_roughness']='Coeficiente de Hazen-Wilhiams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canal irregular de acordo com Manning';
$ec_lang['mi_main_title']='Calculadora gratis em linha de um canal irregular de acordo com Manning';
$ec_lang['mi_main_desc']='Calculadora de um canal irregular com flujo uniforme de acordo com Manning';
$ec_lang['mi_waterSurfaceElevation']='Altura de lámina de agua';
$ec_lang['mi_q_sum']='Q por sumacão de segmentos';
$ec_lang['mi_q_617']='Q por sumacão de regiones com n composto de acordo com Chow 6-17 velocidades iguales';
$ec_lang['mi_q_618']='Q por sumacão de regiones com n composto de acordo com Chow 6-18 equilibrio de forzas';
$ec_lang['mi_xSecPoints']='Puntos da seccão traversal';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Alt.';
$ec_lang['mi_q']='Q';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='Div. de<br />regãoes<br />R<sub>h</sub>y Q<br />(Banco)';
$ec_lang['mi_v']='v';
$ec_lang['mi_t']='T';
$ec_lang['mi_f']='f';
$ec_lang['mi_d50_strickler']='Diam. med.<br />de roca<br />impl. por<br />Strickler';
$ec_lang['mi_d50_mc']='Diam. med<br />requdo<br />seg. MC';
$ec_lang['mi_d50_mra']='Diam. med<br />requdo<br />seg. MRA';
$ec_lang['mi_d50_searcy']='Diam. med<br />requdo<br />seg. Searcy';
$ec_lang['mi_hv']='H<sub>v</sub>';
$ec_lang['mi_tau']='Fza. tang.<br />&tau;';
$ec_lang['mi_a']='A';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_notes']='Notas';
$ec_lang['mi_notes_1_term']='Métodos de calcular Q';
$ec_lang['mi_notes_1_def']='Q por sumacão de segmentos estima por bajo la contribucão friccional de segmentos com alto pendiente traversal. Q por sumacão de regiones com n composto estima por alto o efecto da friccão em areas anchas de poca profundidade em o flujo em areas más profundas (canal primario).';
$ec_lang['mi_notes_2_term']='Tamaño mediano de roca';
$ec_lang['mi_notes_2_def']='El tamaño mediano D<sub>50</sub> de acordo com Strickler es o tamaño (por um canal derecho e limpio) implicado por la rugosidade dada. Los otros tamaños D<sub>50</sub> são os requeridos para resistir la erosão de acordo com 1) o condado de Maricopa County, Arizona, USA, e Robinson Rock Chutes, 2) Maynord, Ruff, e Abt (1989), e 3) Searcy (1967)';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Caudal Manning em tuberías';
$ec_lang['mpf_main_title']='Calculadora gratis em linha da fórmula de Manning para caudal em tuberías';
$ec_lang['mpf_main_desc']='Escoamento uniforme em canais a uma específica declividade e profundidade, utilizando a Fórmula de Manning.';
$ec_lang['mpf_spreadheet_notice']='Estrene a versão de esta calculadora em uma hoja de cálculo';
$ec_lang['mpf_spreadheet_link_download']='Descargar hoja de cálculo';
$ec_lang['mpf_spreadheet_link_Google']='Abrir la versão em Google Sheets';
$ec_lang['mpf_spreadheet_view_alh']='Ver lista de hojas de cálculo';
$ec_lang['mpf_pipe_diameter']='Diâmetro da tubulação, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Coeficiente de Manning (rugosidade), n';
$ec_lang['mpf_friction_slope']='Declividade de pressão (possivelmente <a target="_blank" href="../pressureslope.php">?</a> igual à declividade do tubo), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Percentual da seção utilizado (100% ou 1 se for seção plena)';
$ec_lang['mpf_flow']='Vazão, q';
$ec_lang['mpf_velocity']='Velocidade, v';
$ec_lang['mpf_velocity_head']='Pressão exercida pela velocidade, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Área molhada';
$ec_lang['mpf_wetted_perimeter']='Perímetro molhado';
$ec_lang['mpf_hydraulic_radius']='Raio hidráulico';
$ec_lang['mpf_top_width']='Largura, L';
$ec_lang['mpf_froude_number']='Número de Froude, F';
$ec_lang['mpf_shear_stress']='Tensão cisalhante average (força de tração), tau';
$ec_lang['mpf_solve_for_dd0']='Calcular y/d<sub>0</sub> para um Q dado';
$ec_lang['mpf_solve_desc']='Usando D<sub>0</sub>, n e S<sub>0</sub> do formulário da calculadora, encontra o menor y/d<sub>0</sub> para um Q dado.';
$ec_lang['mpf_solve_button']='Calcular';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Pérdida de pressão em uma tubería de acordo com Manning';
$ec_lang['mphl_main_title']='Calculadora gratis em linha da pérdida de altura de pressão em uma tubería de acordo com Manning';
$ec_lang['mphl_main_desc']='La pérdida de pressão em uma tubería lhena a dado caudal';
$ec_lang['mphl_pipe_length']='Longitud da tubería, l';
$ec_lang['mphl_elevation_1']='Altura 1 (down)';
$ec_lang['mphl_pressure_head_1']='Cabecera da pressão 1 (down)';
$ec_lang['mphl_elevation_2']='Altura 2 (up)';
$ec_lang['mphl_pressure_head_2']='Cabecera da pressão 2 (up)';
$ec_lang['mphl_area']='Área, A';
$ec_lang['mphl_total_junction_k']='Coeficiente total de pérdida em as juntas, k';
$ec_lang['mphl_friction_slope']='Pendiente de friccão, s<sub>f</sub>';
$ec_lang['mphl_friction_loss']='Pérdidas por friccão';
$ec_lang['mphl_junction_loss']='Pérdidas em as juntas';
$ec_lang['mphl_total_loss']='Pérdida total';
$ec_lang['mphl_egl_1']='EGL a jusante';
$ec_lang['mphl_egl_2']='EGL a montante';
$ec_lang['mphl_hgl_2']='HGL a montante no tubo (Ver notas)';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapecial de acordo com Manning';
$ec_lang['mtc_main_title']='Calculadora gratis em linha da fórmula de Manning para canal trapecial';
$ec_lang['mtc_main_desc']='Caudal uniforme Manning em um canal trapecial a dado pendiente e profundidad';
$ec_lang['mtc_bottom_width']='Anchura da base';
$ec_lang['mtc_side_slope_1']='Pendiente de lado 1 (horizontal / vertical)';
$ec_lang['mtc_side_slope_2']='Pendiente de lado 2 (horizontal / vertical)';
$ec_lang['mtc_channel_slope']='Pendiente de canal (vertical / horizontal)';
$ec_lang['mtc_flow_depth']='Profundidade de caudal';
$ec_lang['mtc_bend_angle']='Angulo da curva<a target="_blank" href="riprap-bend-angle.png" title="Haz clic para ver imagen">?</a> (para o tamaño de roca)';
$ec_lang['mtc_sgrock']='Gravedade específica da roca (2.65)';
$ec_lang['mtc_d50_in']='Tamanho de roca';
$ec_lang['mtc_d50_strickler']='Tamanho de roca do diseño <a target="_blank" href="javascript:alert(\'La fórmula Strickler relata n com D50 por um canal recto e limpio. Ajuste o valor n para que este tamaño de roca do diseño sea más grande que o tamaño de roca requerido em as siguientes linhas. Depois use tal roca em su diseño.\')">?</a> basado na dada rugosidade Manning';
$ec_lang['mtc_d50_bottom']='Tamanho de roca requerido em o fondo, D50, Maricopa County <a href="javascript:alert(\'Cuando S0 < 2% segum Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% segum Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_z1']='Tamanho de roca requerido em o lado 1, D50, Maricopa County <a href="javascript:alert(\'Cuando S0 < 2% segum Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% segum Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_z2']='Tamanho de roca requerido em o lado 2, D50, Maricopa County <a href="javascript:alert(\'Cuando S0 < 2% segum Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% segum Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_mra']='Tamaño de roca requerido, D50, de acordo com Maynord, Ruff, e Abt (1989)';
$ec_lang['mtc_d50_searcy']='Tamaño de roca requerido, D50, de acordo com Searcy (1967)';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute Design';
$ec_lang['rrc_main_desc']='Planilha de dimensionamento de rampa de pedras Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Vertedero hidráulico sencilho';
$ec_lang['ws_main_title']='Calculadora de caudal em um vertedero hidráulico sencilho';
$ec_lang['ws_main_desc']='Calculadora de caudal em um vertedero hidráulico sencilho';
$ec_lang['ws_weirLength']='Longitud do vertedero, l';
$ec_lang['ws_headWaterHeight']='Altura de cabecera, h';
$ec_lang['ws_weirCoefficient']='Factor para o vertedero hidráulico, Cw';
$ec_lang['ws_notes_heading']='Notas';
$ec_lang['ws_notes_we_term']='Fórmula de um vertedero';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Vertedero hidráulico irregular';
$ec_lang['wi_main_title']='Calculadora gratis em linha para vertedero hidráulico irregular, de profundidade variable';
$ec_lang['wi_main_desc']='Calculadora de caudal para um vertedero irregular de profundidade variable';
$ec_lang['wi_headWaterelevation']='Nivel de cabecera';
$ec_lang['wi_weirPoints']='Puntos do vertedero hidráulico';
$ec_lang['wi_station']='Distancia';
$ec_lang['wi_elevation']='Nivel';
$ec_lang['wi_pondingHeight']='Altura de inundacão';
$ec_lang['wi_incrementalFlow']='Caudal adicional';
$ec_lang['wi_cumulativeFlow']='Caudal total';
$ec_lang['wi_save_and_calculate']='Grabar e calcular';
$ec_lang['wi_notes_we_term']='Equação de Vertedor';
$ec_lang['wi_notes_we_def']='q = se (distancia = 0) entonces 0 o se (slope=0) entoces cw*distancia*d0<sup>1.5</sup> o cw/(2.5*pendiente) * (d0<sup>2.5</sup> - d1<sup>2.5</sup>) donde d1 e d0 são sempre positivos o cero';
// Orifice Flow
$ec_lang['or_main_menu']='Vazão por Orifício';
$ec_lang['or_main_title']='Calculadora gratuita de vazão por orifício';
$ec_lang['or_main_desc']='Vazão por Orifício — Livre ou Submersa';
$ec_lang['or_shape']='Forma da abertura';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Retangular';
$ec_lang['or_diameter']='Diâmetro (circular) ou altura (retangular), D';
$ec_lang['or_width']='Largura, W (somente retangular)';
$ec_lang['or_invert']='Cota da soleira da abertura';
$ec_lang['or_hwe']='Nível d\'água a montante';
$ec_lang['or_twe']='Nível d\'água a jusante';
$ec_lang['or_cd']='Coeficiente de descarga, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Cota do centroide';
$ec_lang['or_head']='Carga efetiva, h';
$ec_lang['or_area']='Área da abertura, A';
$ec_lang['or_flow']='Vazão, Q';
$ec_lang['or_regime']='Verificação do regime de orifício';
$ec_lang['or_regime_valid']='Saída livre — regime de orifício válido ✓';
$ec_lang['or_regime_submerged']='Orifício submerso (TWE acima da soleira) — válido ✓';
$ec_lang['or_regime_warn']='Aviso: nível a montante abaixo da crista — não é regime de orifício';
$ec_lang['or_regime_twe_above_hwe']='Aviso: nível de jusante (TWE) acima do nível de montante (HWE) — verifique as entradas';
$ec_lang['or_notes_1_term']='Equação do orifício';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Saída livre: h = HWE &minus; centroide. Escoamento submerso (TWE acima da soleira): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regime de orifício';
$ec_lang['or_notes_2_def']='As equações de orifício aplicam-se quando o nível a montante está acima da crista da abertura. Quando está abaixo, use uma equação de vertedor.';
$ec_lang['or_notes_3_term']='Coeficiente de descarga';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varia de 0,60 a 0,65 para orifícios de borda viva. Entradas arredondadas ou reentrantes têm valores diferentes. Consulte o <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> ou o Manual de Referência Hidráulica do HEC-RAS.';
$ec_lang['or_notes_4_term']='Submersão';
$ec_lang['or_notes_4_def']='Quando TWE está acima da soleira da abertura, a calculadora aplica automaticamente a equação de orifício submerso com h = HWE &minus; TWE. Quando TWE é igual ou inferior à soleira, assume-se saída livre e h = HWE &minus; centroide.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Tempo de Esvaziamento por Orifício';
$ec_lang['odt_main_title']='Calculadora Gratuita Online de Tempo de Esvaziamento por Orifício — Lagoa, Bacia ou Tanque';
$ec_lang['odt_main_desc']='Tempo de Esvaziamento de Lagoa ou Bacia por Orifício &mdash; Método do Volume Cônico';
$ec_lang['odt_h1_elev']='Cota inicial da superfície da água';
$ec_lang['odt_a1']='Área inicial da lagoa ou bacia, A1';
$ec_lang['odt_h2_elev']='Cota final da superfície da água';
$ec_lang['odt_h_orifice']='Cota do centroide do orifício';
$ec_lang['odt_a0']='Área da lagoa ou bacia na cota do orifício, A0';
$ec_lang['odt_a_ending']='Área final da lagoa, A2 (interpolada)';
$ec_lang['odt_h2_check']='Verificação da cota final';
$ec_lang['odt_h2_ok']='Cota final acima do topo do orifício ✓';
$ec_lang['odt_h2_warn']='Aviso: cota final igual ou abaixo do topo do orifício (centroide + D/2)';
$ec_lang['odt_d']='Diâmetro do orifício (circular) ou altura (retangular), D';
$ec_lang['odt_w']='Largura do orifício, W (somente retangular)';
$ec_lang['odt_t_sec']='Tempo de esvaziamento (segundos)';
$ec_lang['odt_t_min']='Tempo de esvaziamento (minutos)';
$ec_lang['odt_t_hr']='Tempo de esvaziamento (horas)';
$ec_lang['odt_t_day']='Tempo de esvaziamento (dias)';
$ec_lang['odt_notes_1_term']='Fórmula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) fornece o tempo de esvaziamento da carga H até o orifício. Tempo de esvaziamento = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), onde H<sub>1</sub> = cota inicial &minus; cota do orifício, H<sub>2</sub> = cota final &minus; cota do orifício.';
$ec_lang['odt_notes_2_term']='Método';
$ec_lang['odt_notes_2_def']='O método do volume cônico modela a lagoa ou bacia como uma secção cônica entre a área inicial A<sub>1</sub> na superfície inicial da água e a área A<sub>0</sub> na cota do centroide do orifício. A<sub>2</sub>, a área da lagoa na cota final, é interpolada a partir de A<sub>1</sub> e A<sub>0</sub> usando o modelo de secção cônica. O tempo de esvaziamento da cota inicial até a cota final é igual ao tempo total de esvaziamento de H<sub>1</sub> até o orifício menos o tempo restante de H<sub>2</sub> até o orifício.';
$ec_lang['odt_h1']='Carga inicial, H<sub>1</sub> (WSE &minus; centroide)';
$ec_lang['odt_q_max']='Vazão máxima (inicial), Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume esvaziado';
$ec_lang['odt_sketch_start']='Início';
$ec_lang['odt_sketch_end']='Fim';
// Contact us.
$ec_lang['contact_title']='Contacto com HawsEDC';
$ec_lang['contactSendMessage']='Envíe um mensajem a Tom Haws';
$ec_lang['contactYourName']='Su nombre:';
$ec_lang['contactYourEmail']='Su direccão de correo electrónico:';
$ec_lang['contactSubject']='Asunto:';
$ec_lang['contact_message']='Mensajem:';
$ec_lang['contactSpamPrefix']='Five (cinco) plus (y) one (uno) equals (são) ';
$ec_lang['contactSpamPostfix']='(Favor de escreverla em inglés com letras. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Enviar Mensajem';
$ec_lang['menu_brand']='Calculadoras HawsEDC';
$ec_lang['essc_btbw']='Largura de margem a margem';
$ec_lang['essc_mcr']='Raio mínimo de curvatura';
$ec_lang['essc_q']='Vazão, Q';
$ec_lang['hw_hgl_1']='HGL a jusante';
$ec_lang['hw_hgl_2']='HGL a montante';
$ec_lang['mi_d50in']='Tamanho<br />mediano<br />de rocha<br />de revestimento';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_groupPoint']='Ponto';
$ec_lang['mi_groupRegion']='Região';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_n617']='n<br />comp.';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_v617']='v';
$ec_lang['mpf_area_ratio']='Área relativa, a/a0';
$ec_lang['mpf_full_flow']='Vazão a seção plena, Q0';
$ec_lang['mpf_full_flow_ratio']='Razão em relação à seção plena, Q/Q0';
$ec_lang['mpf_note_1']='<p>Notas:</p><dl><dt>Este é o escoamento e a profundidade no interior de um tubo <em>infinitamente longo</em>.</dt><dd>Fazer o escoamento entrar no tubo pode exigir uma profundidade de água significativamente maior. Acrescente pelo menos 1,5 vezes a carga de velocidade para obter a profundidade de água a montante ou <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">veja meu tutorial de 2 minutos</a> sobre cálculos padrão de nível de água em bueiros usando HY-8.</dd>';
$ec_lang['mpf_pipe_area']='Área da tubulação, a0';
$ec_lang['mpf_see_notes']='(Ver notas)';
$ec_lang['mphl_note_1']='<p>Notas:</p><dl><dt>Para uma condição de entrada aberta (bueiro), é necessário verificar condições de controle de entrada.</dt><dd>1. O HGL a montante não pode ser inferior à cota de profundidade normal de escoamento a montante (nem inferior ao tubo!).</dd><dd>2. O nível de água a montante de um bueiro é mais bem representado pelo EGL a montante do que pelo HGL a montante.</dd><dd>3. Veja <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">meu tutorial de 2 minutos</a> para cálculos simples de nível de água em bueiros usando HY-8.</dd>';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_n_bathurst']='n para o tamanho de rocha de projeto segundo Bathurst';
$ec_lang['mtc_n_blodgett']='n para o tamanho de rocha de projeto segundo Blodgett';
$ec_lang['mtc_n_strickler']='n para o tamanho de rocha de projeto segundo Strickler';
$ec_lang['mtc_note_1']='<p>Notas:</p><dl><dt>Iteração automatizada de dimensionamento de rocha e rugosidade</dt><dd>Escolha um botão de opção de rugosidade (BB recomendado) e um botão de opção de tamanho de rocha de projeto (Isbash recomendado). Ajuste a profundidade e o fator de segurança do tamanho de rocha para obter o escoamento desejado com um tamanho de rocha inteiro. Toda vez que qualquer valor de entrada é alterado, o seguinte ciclo de iteração ocorre: 1. A rugosidade é calculada a partir do tamanho de rocha de projeto. 2. O cálculo de rugosidade solicitado é copiado para a rugosidade de entrada. 3. O escoamento do canal e o tamanho de rocha requerido são calculados. 4. O tamanho de rocha de projeto é ajustado. 5. Repete até que o erro no tamanho de rocha de projeto seja muito pequeno.</dd><dt>Calculadora básica (sem iteração)</dt><dd>Digite o valor de rugosidade desejado. Ignore a área de entrada do tamanho de rocha de projeto.</dd></dl>';
$ec_lang['or_velocity']='Velocidade na abertura, v';
