<?php

// ñáéíóú All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']="fracción";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="pies^2";
$ec_lang['u_ft3ps']="pies^3/seg";
$ec_lang['u_fth2o']="pies ca";
$ec_lang['u_ft']="pies";
$ec_lang['u_ftps']="pies/seg.";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% $ec_lang[u_grade]";
$ec_lang['u_grade']="vert./horiz.";
$ec_lang['u_in2']="$ec_lang[u_in]^2";
$ec_lang['u_inh2o']="pulg. ca";
$ec_lang['u_in']="pulg.";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="Mgal/día";
$ec_lang['u_mh2o']="mca";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mmca";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/pie^2";
$ec_lang['u_psi']="lb/pulg^2";
$ec_lang['u_s']="seg";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";

// Page text
// In page order for easiest maintenance.
$ec_lang['menu_brand']='Calculadoras HawsEDC';
$ec_lang['menu_main_list']='Lista de calculadoras';
$ec_lang['menu_main_hydraulics']='Hydraulica';
$ec_lang['menu_main_language']='Idioma';
$ec_lang['template_welcome']='>> Dejad vuestros miedos en la puerta; el amor se habla aquí. Disfrutad tambi&eacute;n <a href="https://hawsedc.com/download.php">las herramientas libres HawsEDC para AutoCAD.</a> <<';
$ec_lang['template_translation_help']='&iquest;Me puede ayudar a traducir esta calculadora a su idioma?  &iquest;Quisiera Ud. poner esta calculadora en su propio sitio web?';
$ec_lang['template_feedback']='Tenga la amabilidad de enviarnos sus comentarios. &iquest;Le fue útil esta calculadora?';
$ec_lang['template_printable_title']='Título Imprimible';
$ec_lang['template_printable_subtitle']='Subtítulo Imprimible';
$ec_lang['index_title']='Calculadoras para ingenieros gratis en línea';
$ec_lang['calc_set_units']='Cambiar sistema de medidas:';
$ec_lang['points_data_help']='(o bien Copiar/Pegar usando el área de datos)';
$ec_lang['points_data_title']='Datos de los puntos<br />(separados por comas o tabulaciones)';
$ec_lang['points_data_copy']='Copiar';
$ec_lang['points_data_paste']='Pegar';
$ec_lang['calc_inputs']='Ingresos';
$ec_lang['calc_results']='Resultados: ';
$ec_lang['view_hide_line']='[Ocultar esta linea]';
$ec_lang['view_printable']='Versión Imprimible (recargar/renover para restaurar)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Pérdida de presión en una tubería según Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculadora gratis en linea de pérdida de presión en una tubería según Darcy-Weisbach';
$ec_lang['dw_main_desc']='Pérdida de presión en una tubería a partir de diámetro, rugosidad, y gasto según Darcy-Weisbach';
$ec_lang['dw_roughness']='Rugosidad absoluto, e';
$ec_lang['dw_kinematic_viscosity']='<span title="1E-6 m^2/sec por agua limpia a la temperatura ambiente">Viscosidad kinemática, v (1E-6)</span>';
$ec_lang['dw_reynolds_number']='Número de Reynolds, Re';
$ec_lang['dw_flow_regime']='Régimen del flujo';
$ec_lang['dw_regime_laminar']='laminar';
$ec_lang['dw_regime_transitional']='transicional';
$ec_lang['dw_regime_turbulent']='turbulente';
$ec_lang['dw_friction_factor_method']='Método del factor de fricción';
$ec_lang['dw_friction_factor']='Factor de fricción, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Pérdida de presión en una tubería según Hazen-Williams';
$ec_lang['hw_main_title']='Calculadora gratis en linea de pérdida de presión en una tubería según Hazen-Williams';
$ec_lang['hw_main_desc']='Calculadora de pérdida de presión en una tubería a partir de diámetro, rugosidad, y gasto según Hazen-Williams';
$ec_lang['hw_roughness']='Coeficiente de Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canal irregular según Manning';
$ec_lang['mi_main_title']='Calculadora gratis en linea de un canal irregular según Manning';
$ec_lang['mi_main_desc']='Calculadora de un canal irregular con flujo uniforme según Manning';
$ec_lang['mi_waterSurfaceElevation']='Altura de la lámina libre';
$ec_lang['mi_q_sum']='Q por sumación de segmentos';
$ec_lang['mi_q_617']='Q por sumación de regiones con n compuesto según Chow 6-17 velocidades iguales';
$ec_lang['mi_q_618']='Q por sumación de regiones con n compuesto según Chow 6-18 equilibrio de fuerzas';
$ec_lang['mi_xSecPoints']='Puntos de la sección traversal';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Alt.';
$ec_lang['mi_q']='Q';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='Div. de<br />regiónes<br />R<sub>h</sub>y Q<br />(Banco)';
$ec_lang['mi_v']='v';
$ec_lang['mi_t']='T';
$ec_lang['mi_f']='f';
$ec_lang['mi_d50_strickler']='Diam. med.<br />de roca<br />impl. por<br />Strickler';
$ec_lang['mi_d50_mc']='Diam. med<br />requdo<br />seg. MC';
$ec_lang['mi_d50_mra']='Diam. med<br />requdo<br />seg. MRA';
$ec_lang['mi_d50_searcy']='Diam. med<br />requdo<br />seg. Searcy';
$ec_lang['mi_hv']='H<sub>v</sub>';
$ec_lang['mi_tau']='Fza. tang.<br />&tau;';
$ec_lang['mi_a']='A';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_notes']='Notas';
$ec_lang['mi_notes_1_term']='Métodos de calcular Q';
$ec_lang['mi_notes_1_def']='Q por sumación de segmentos estima por bajo la contribución friccional de segmentos con alto pendiente traversal. Q por sumación de regiones con n compuesto estima por alto el efecto de la fricción en áreas anchas de poca profundidad en el flujo en áreas más profundas (canal primario).';
$ec_lang['mi_notes_2_term']='Tamaño mediano de roca';
$ec_lang['mi_notes_2_def']='El tamaño mediano D<sub>50</sub> según Strickler es el tamaño (por un canal derecho y limpio) implicado por la rugosidad dada. Los otros tamaños D<sub>50</sub> son los requeridos para resistir la erosión según 1) el condado de Maricopa County, Arizona, USA, y Robinson Rock Chutes, 2) Maynord, Ruff, y Abt (1989), y 3) Searcy (1967)';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Flujo según Manning en tuberías';
$ec_lang['mpf_main_title']='Calculadora gratis en línea de la fórmula de Manning para flujo uniforme en tuberías';
$ec_lang['mpf_main_desc']='Cálculo por Manning de caudal y velocidad de flujo en tuberías a partir de pendiente y sección';
$ec_lang['mpf_spreadheet_notice']='Estrene la versión de esta calculadora en una hoja de cálculo';
$ec_lang['mpf_spreadheet_link_download']='Descargar hoja de cálculo';
$ec_lang['mpf_spreadheet_link_Google']='Abrir la versión en Google Sheets';
$ec_lang['mpf_spreadheet_view_all']='Ver lista de hojas de cálculo';
$ec_lang['mpf_pipe_diameter']='Diámetro de la tubería, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Rugosidad según Manning, n';
$ec_lang['mpf_friction_slope']='Pendiente hidráulica (o quizás <a target="_blank" href="/pressureslope.php">?</a> de la tubería), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Relación de calados, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='Caudal, q';
$ec_lang['mpf_velocity']='Velocidad, v';
$ec_lang['mpf_velocity_head']='Energía cinética, hv';
$ec_lang['mpf_flow_area']='Sección mojada, a';
$ec_lang['mpf_pipe_area']='Sección llena, a<sub>0</sub>';
$ec_lang['mpf_area_ratio']='Relación de secciones, a/a<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='Perímetro mojado, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Radio hidráulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Ancho de lámina libre, T';
$ec_lang['mpf_froude_number']='Número de Froude, F';
$ec_lang['mpf_shear_stress']='Tensión tangencial promedio (fuerza de tracción), tau';
$ec_lang['mpf_full_flow']='Caudal lleno, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='Relación de caudales, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<p>Notes:</p><dl><dt>Este es el caudal (también la profundidad) dentro de una tubería <em>de largo infinito</em>.</dt><dd>El alcanzar que el caudal entre a la tubería puede requerir un cabezal bastante más alto. Agregue por lo menos 1,5 veces la energía cinética al calado o <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">haga los cálculos de cabecera de alcantarilla de una manera estándar utilizando HY-8.</a> </dd>';
$ec_lang['mpf_solve_for_dd0']='Calcular y/d<sub>0</sub> para un Q dado';
$ec_lang['mpf_solve_desc']='Usando D<sub>0</sub>, n y S<sub>0</sub> del formulario de la calculadora, encuentra el menor y/d<sub>0</sub> para un Q dado.';
$ec_lang['mpf_solve_button']='Calcular';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Pérdida de presión en una tubería según Manning';
$ec_lang['mphl_main_title']='Calculadora gratis en línea de la pérdida de altura de presión en una tubería según Manning';
$ec_lang['mphl_main_desc']='La pérdida de presión en una tubería llena a partir de gasto';
$ec_lang['mphl_pipe_length']='Longitud de la tubería, l';
$ec_lang['mphl_area']='Área, A';
$ec_lang['mphl_total_junction_k']='Coeficiente total de pérdida en las juntas, k';
$ec_lang['mphl_friction_slope']='Pendiente de fricción, s<sub>f</sub>';
$ec_lang['mphl_friction_loss']='Pérdidas por fricción';
$ec_lang['mphl_junction_loss']='Pérdidas en las juntas';
$ec_lang['mphl_total_loss']='Pérdida total';
$ec_lang['mphl_egl_1']='EGL aguas abajo';
$ec_lang['mphl_egl_2']='EGL aguas arriba';
$ec_lang['mpf_see_notes']='(Véanse las notas)';
$ec_lang['mphl_hgl_2']='HGL aguas arriba en la tubería ' . $ec_lang['mpf_see_notes'];
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Canal trapecial según Manning';
$ec_lang['mtc_main_title']='Calculadora gratis en línea de la fórmula de Manning para canal trapecial';
$ec_lang['mtc_main_desc']='Flujo uniforme Manning en un canal trapecial a partir de pendiente y profundidad';
$ec_lang['mtc_bottom_width']='Anchura de la base';
$ec_lang['mtc_side_slope_1']='Pendiente de lado 1 (horizontal / vertical)';
$ec_lang['mtc_side_slope_2']='Pendiente de lado 2 (horizontal / vertical)';
$ec_lang['mtc_channel_slope']='Pendiente del canal (vertical / horizontal)';
$ec_lang['mtc_flow_depth']='Calado de la lámina de agua, y';
$ec_lang['mtc_bend_angle']='Angulo de la curva<a href="riprap-bend-angle.png" title="Haz clic para ver imagen">?</a> (para el tamaño de roca)';
$ec_lang['mtc_sgrock']='Gravedad específica de la roca (2.65)';
$ec_lang['mtc_d50_in']='Tamaño de roca';
$ec_lang['mtc_d50_bottom']='Tamaño de roca requerido en el fondo, D<sub>50</sub>, Maricopa County <a href="javascript:alert(\'Cuando S0 < 2% según Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% según Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_z1']='Tamaño de roca requerido en el lado 1, D<sub>50</sub>, Maricopa County <a href="javascript:alert(\'Cuando S0 < 2% según Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% según Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_z2']='Tamaño de roca requerido en el lado 2, D<sub>50</sub>, Maricopa County <a href="javascript:alert(\'Cuando S0 < 2% según Isbash (1936) and Maricopa County, Arizona, US. Cuando S >= 2% según Robinson Rock Chute \')">?</a>';
$ec_lang['mtc_d50_mra']='Tamaño de roca requerido, D<sub>50</sub>, según Maynord, Ruff, y Abt (1989)';
$ec_lang['mtc_d50_searcy']='Tamaño de roca requerido, D<sub>50</sub>, según Searcy (1967)';
$ec_lang['mtc_d50_strickler']='Tamaño de roca del diseño <a target="_blank" href="javascript:alert(\'La fórmula Strickler relata n con D50 por un canal recto y limpio. Ajuste el valor n para que este tamaño de roca del diseño sea más grande que el tamaño de roca requerido en las siguientes lineas. Luego use tal roca en su diseño.\')">?</a> basado en la dada rugosidad Manning';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Vertedero hidráulico sencillo';
$ec_lang['ws_main_title']='Calculadora de gasto en un vertedero hidráulico sencillo';
$ec_lang['ws_main_desc']='Calculadora de gasto en un vertedero hidráulico sencillo';
$ec_lang['ws_weirLength']='Longitud del vertedero, l';
$ec_lang['ws_headWaterHeight']='Altura de cabezal, h';
$ec_lang['ws_weirCoefficient']='Factor para el vertedero hidráulico, Cw';
$ec_lang['ws_notes_heading']='Notas';
$ec_lang['ws_notes_we_term']='Fórmula de un vertedero';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Vertedero hidráulico irregular';
$ec_lang['wi_main_title']='Calculadora gratis en línea para vertedero hidráulico irregular, de profundidad variable';
$ec_lang['wi_main_desc']='Calculadora de gasto para un vertedero irregular de profundidad variable';
$ec_lang['wi_headWaterelevation']='Nivel de cabezal';
$ec_lang['wi_weirPoints']='Puntos del vertedero hidráulico';
$ec_lang['wi_station']='Distancia';
$ec_lang['wi_elevation']='Nivel';
$ec_lang['wi_pondingHeight']='Altura de inundación';
$ec_lang['wi_incrementalFlow']='Gasto adicional';
$ec_lang['wi_cumulativeFlow']='Gasto total';
$ec_lang['wi_save_and_calculate']='Grabar y calcular';
$ec_lang['wi_notes_we_term']='Ecuación de Vertedero';
$ec_lang['wi_notes_we_def']='q = si (distancia = 0) entonces 0 o si (slope=0) entoces cw*distancia*d<sub>0</sub><sup>1.5</sup> o cw/(2.5*pendiente) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) donde d<sub>1</sub> y d<sub>0</sub> son siempre positivos o cero';
// Orifice Flow
$ec_lang['or_main_menu']='Flujo por Orificio';
$ec_lang['or_main_title']='Calculadora gratuita en línea de flujo por orificio';
$ec_lang['or_main_desc']='Flujo por Orificio — Libre o Sumergido';
$ec_lang['or_shape']='Forma de la apertura';
$ec_lang['or_shape_circular']='Circular';
$ec_lang['or_shape_rectangular']='Rectangular';
$ec_lang['or_diameter']='Diámetro (circular) o altura (rectangular), D';
$ec_lang['or_width']='Ancho, W (solo rectangular)';
$ec_lang['or_invert']='Cota de la solera de la apertura';
$ec_lang['or_hwe']='Elevación de la lámina de agua aguas arriba';
$ec_lang['or_twe']='Elevación de la lámina de agua aguas abajo';
$ec_lang['or_cd']='Coeficiente de descarga, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Elevación del centroide';
$ec_lang['or_head']='Carga efectiva, h';
$ec_lang['or_area']='Área de la apertura, A';
$ec_lang['or_flow']='Caudal, Q';
$ec_lang['or_regime']='Verificación del régimen de orificio';
$ec_lang['or_regime_valid']='Salida libre — régimen de orificio válido ✓';
$ec_lang['or_regime_submerged']='Orificio sumergido (TWE sobre la solera) — válido ✓';
$ec_lang['or_regime_warn']='Advertencia: lámina aguas arriba bajo la clave — no es régimen de orificio';
$ec_lang['or_regime_twe_above_hwe']='Advertencia: agua de cola (TWE) sobre agua de cabeza (HWE) — verifique las entradas';
$ec_lang['or_notes_1_term']='Ecuación de orificio';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Salida libre: h = HWE &minus; centroide. Sumergido (TWE sobre la solera): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Régimen de orificio';
$ec_lang['or_notes_2_def']='Las ecuaciones de flujo por orificio aplican cuando la lámina aguas arriba está sobre la clave de la apertura. Cuando está bajo la clave, use una ecuación de vertedero.';
$ec_lang['or_notes_3_term']='Coeficiente de descarga';
$ec_lang['or_notes_3_def']='C<sub>d</sub> es aproximadamente 0,60&ndash;0,65 para orificios de borde agudo. Entradas redondeadas o reentrantes tienen valores diferentes. Consulte <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> o el Manual de Referencia Hidráulica de HEC-RAS.';
$ec_lang['or_notes_4_term']='Sumersión';
$ec_lang['or_notes_4_def']='Cuando TWE está sobre la solera de la apertura, la calculadora aplica automáticamente la ecuación de orificio sumergido con h = HWE &minus; TWE. Cuando TWE es igual o inferior a la solera, se asume salida libre y h = HWE &minus; centroide.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Tiempo de vaciado por orificio';
$ec_lang['odt_main_title']='Calculadora gratuita en línea de tiempo de vaciado por orificio';
$ec_lang['odt_main_desc']='Tiempo de vaciado de estanque por orificio &mdash; Método del volumen cónico';
$ec_lang['odt_h1_elev']='Cota inicial de la lámina de agua';
$ec_lang['odt_a1']='Área inicial del estanque, A1';
$ec_lang['odt_h2_elev']='Cota final de la lámina de agua';
$ec_lang['odt_h_orifice']='Cota del centroide del orificio';
$ec_lang['odt_a0']='Área del estanque a la cota del orificio, A0';
$ec_lang['odt_a_ending']='Área final del estanque, A2 (interpolada)';
$ec_lang['odt_h2_check']='Verificación de cota final';
$ec_lang['odt_h2_ok']='Cota final sobre la cima del orificio ✓';
$ec_lang['odt_h2_warn']='Advertencia: cota final igual o inferior a la cima del orificio (centroide + D/2)';
$ec_lang['odt_d']='Diámetro (circular) o altura (rectangular) del orificio, D';
$ec_lang['odt_w']='Ancho del orificio, W (solo rectangular)';
$ec_lang['odt_t_sec']='Tiempo de vaciado (segundos)';
$ec_lang['odt_t_min']='Tiempo de vaciado (minutos)';
$ec_lang['odt_t_hr']='Tiempo de vaciado (horas)';
$ec_lang['odt_t_day']='Tiempo de vaciado (días)';
$ec_lang['odt_notes_1_term']='Fórmula';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) da el tiempo de vaciado desde la carga H hasta el orificio. Tiempo de vaciado = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), donde H<sub>1</sub> = cota inicial &minus; cota del orificio, H<sub>2</sub> = cota final &minus; cota del orificio.';
$ec_lang['odt_notes_2_term']='Método';
$ec_lang['odt_notes_2_def']='El método del volumen cónico modela el estanque como una sección cónica entre el área inicial A<sub>1</sub> en la lámina de agua inicial y el área A<sub>0</sub> a la cota del centroide del orificio. A<sub>2</sub>, el área del estanque a la cota final, se interpola de A<sub>1</sub> y A<sub>0</sub> usando el modelo de sección cónica. El tiempo de vaciado desde la cota inicial hasta la final es igual al tiempo total de vaciado desde H<sub>1</sub> hasta el orificio menos el tiempo de vaciado restante desde H<sub>2</sub> hasta el orificio.';
$ec_lang['odt_h1']='Carga inicial, H<sub>1</sub> (WSE &minus; centroide)';
$ec_lang['odt_q_max']='Caudal máximo (inicial), Q<sub>max</sub>';
$ec_lang['odt_vol']='Volumen vaciado';
$ec_lang['odt_sketch_start']='Inicio';
$ec_lang['odt_sketch_end']='Fin';
// Contact us.
$ec_lang['contact_title']='Contacto con HawsEDC';
$ec_lang['contactSendMessage']='Envíe un mensaje a Tom Haws';
$ec_lang['contactYourName']='Su nombre:';
$ec_lang['contactYourEmail']='Su dirección de correo electrónico:';
$ec_lang['contactSubject']='Asunto:';
$ec_lang['contact_message']='Mensaje:';
$ec_lang['contactSpamPrefix']='Five (cinco) plus (y) one (uno) equals (son) ';
$ec_lang['contactSpamPostfix']='(Favor de escribirla en inglés con letras. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Enviar Mensaje';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Ancho de orilla a orilla';
$ec_lang['essc_mcr']='Radio mínimo de curvatura';
$ec_lang['essc_q']='Caudal, Q';
// Hazen-Williams HGL
$ec_lang['hw_hgl_1']='HGL aguas abajo';
$ec_lang['hw_hgl_2']='HGL aguas arriba';
// Manning Irregular additional keys
$ec_lang['mi_d50in']='Diam.<br />mediano<br />de la<br />roca';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_groupPoint']='Punto';
$ec_lang['mi_groupRegion']='Región';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_n617']='n<br />compuesto';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_v617']='v';
// Manning Pipe Head Loss note
$ec_lang['mphl_note_1']='<p>Notas:</p><dl><dt>Para una entrada abierta (alcantarilla), es necesario verificar las condiciones de control de entrada.</dt><dd>1. El HGL aguas arriba no puede ser inferior a la cota de flujo a profundidad normal aguas arriba (ni inferior a la tubería).</dd><dd>2. El cabezal de una alcantarilla se representa mejor con el EGL aguas arriba que con el HGL aguas arriba.</dd><dd>3. Véase <a href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">mi tutorial de 2 minutos</a> para cálculos estándar de cabezal en alcantarillas usando HY-8.</dd>';
// Manning Trapezoidal Channel additional keys
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_n_bathurst']='n para el tamaño de roca de diseño según Bathurst';
$ec_lang['mtc_n_blodgett']='n para el tamaño de roca de diseño según Blodgett';
$ec_lang['mtc_n_strickler']='n para el tamaño de roca de diseño según Strickler';
$ec_lang['mtc_note_1']='<p>Notas:</p><dl><dt>Iteración automática para diseño de tamaño y rugosidad de roca</dt><dd>Elija un botón de radio de rugosidad (se recomienda BB) y un botón de radio para el tamaño de roca de diseño (se recomienda Isbash). Ajuste la profundidad y el factor de seguridad del tamaño de roca para obtener el caudal deseado con un tamaño de roca uniforme. Cada vez que cambie cualquier valor de entrada, ocurre el siguiente ciclo de iteración: 1. Se calcula la rugosidad a partir del tamaño de roca de diseño. 2. El cálculo de rugosidad solicitado se copia al campo de rugosidad. 3. Se calculan el caudal del canal y el tamaño de roca requerido. 4. Se ajusta el tamaño de roca de diseño. 5. Se repite hasta que el error en el tamaño de roca de diseño sea muy pequeño.</dd><dt>Calculadora básica (sin iteración)</dt><dd>Ingrese el valor de rugosidad deseado. Ignore el área de entrada del tamaño de roca de diseño.</dd></dl>';
// Orifice Flow additional key
$ec_lang['or_velocity']='Velocidad en la apertura, v';
// Robinson Rock Chute
$ec_lang['rrc_main_desc']='Hoja de cálculo de diseño de canal de roca según Robinson';
$ec_lang['rrc_main_menu']='Canal de roca según Robinson';
