<?php

// All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='အပိုင်းကိန်း';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']='rise/run';
$ec_lang['u_in2']='sq. in.';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/d';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
$ec_lang['u_acft']='ac-ft';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='m^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC တွက်ချက်မှုကိရိယာများ';
$ec_lang['menu_main_list']='တွက်ချက်မှုကိရိယာများ စာရင်း';
$ec_lang['menu_main_hydraulics']='ဟိုက်ဒရောလစ်';
$ec_lang['menu_main_language']='ဘာသာစကား';
$ec_lang['menu_more']='နောက်ထပ်';
$ec_lang['template_welcome']='&gt;&gt; သင့်ကြောက်ရွံ့မှုများကို တံခါးဝတွင် ချန်ထားပါ; ချစ်ခြင်းမေတ္တာသည် ဤနေရာ၌ ကျွန်ုပ်တို့၏ဘာသာစကားဖြစ်သည်။ သင်သည် အရာခပ်သိမ်းကို ဖျက်ဆီးနေသည်မဟုတ်ပါ။ <a target="_blank" href="https://hawsedc.com/download.php">အခမဲ့ HawsEDC AutoCAD ကိရိယာများ</a>ကိုလည်း ခံစားပါ။ &lt;&lt;';
$ec_lang['template_translation_help']='ဤနေရာတွင် ထည့်သွင်းရန် တွက်ချက်မှုကိရိယာတစ်ခုအတွက် မြင်ကွင်းကောင်းတစ်ခု ရှိပါသလား။ ဘာသာပြန်ဆိုမှုများ တိုးတက်စေရန်၊ ပရိုဂရမ်ရေးရန် သို့မဟုတ် ဤတွက်ချက်မှုကိရိယာများကို လက်ခံဆောင်ရွက်ရန် ကူညီနိုင်ပါသလား။  ';
$ec_lang['template_feedback']='ကျေးဇူးပြု၍ သင်၏တန်ဖိုးရှိသောအကြံပြုချက် သို့မဟုတ် ချီးမွမ်းစကားများ ပေးပါ။ ဤအခမဲ့တွက်ချက်မှုကိရိယာသည် သင်၏မျှော်လင့်ချက်များကို အကုန်အလုံး ကျော်လွန်ဆောင်ရွက်နိုင်ခဲ့ပါသလား။';
$ec_lang['template_printable_title']='မှတ်တမ်းတင်ရာ ခေါင်းစဉ်';
$ec_lang['template_printable_subtitle']='မှတ်တမ်းတင်ရာ အမည်ငယ်';
$ec_lang['index_title']='အခမဲ့ အွန်လိုင်း အင်ဂျင်နီယာ တွက်ချက်မှုကိရိယာများ';
$ec_lang['calc_set_units']='ယူနစ်သတ်မှတ်ရန်:';
$ec_lang['points_data_help']='(သို့မဟုတ် ဒေတာနေရာကို အသုံးပြု၍ ကူးယူ/ကူးထည့်ပါ)';
$ec_lang['points_data_title']='အမှတ်ဒေတာ<br />(ကော်မာ သို့မဟုတ် tab ဖြင့် ခွဲ)';
$ec_lang['points_data_copy']='ကူးယူ';
$ec_lang['points_data_paste']='ကူးထည့်';
$ec_lang['calc_inputs']='ထည့်သွင်းချက်များ';
$ec_lang['calc_results']='ရလဒ်များ';
$ec_lang['view_hide_line']='[ဤစာကြောင်း ဝှက်ရန်]';
$ec_lang['view_printable']='မှတ်တမ်းတင်နိုင်သောဗားရှင်း (ပြန်ရယူရန် ပြန်လည်တင်/ရှင်းလင်းပါ)';
$ec_lang['ec_name_label']='ဤတွက်ချက်မှုကိုသိမ်းဆည်းပါ:';
$ec_lang['ec_name_placeholder']='အမည်';
$ec_lang['ec_name_hint']='ထည့်သွင်းချက်များကို URL သို့သိမ်းဆည်းကာ စာမှတ်မုံးခြင်း၊ မှတ်တမ်းများ ပြန်လည်ရယူခြင်းနှင့် မျှဝေခြင်းအတွက်ဖြစ်သည်။';
$ec_lang['ec_name_invalid']='အက္ခရာ၊ ကိန်းဂဏန်း၊ အကွာ၊ – _ . သာ အသုံးပြုပါ။';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Darcy-Weisbach သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['dw_main_title']='အခမဲ့ အွန်လိုင်း Darcy-Weisbach သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['dw_main_desc']='သတ်မှတ်အချင်း၊ ကြမ်းတမ်းမှုနှင့် စီးဆင်းမှုတွင် Darcy-Weisbach သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['dw_roughness']='Darcy-Weisbach ပကတိကြမ်းတမ်းမှု, e';
$ec_lang['dw_kinematic_viscosity']='ကိနမက်တစ် ဗစ်စကော့စিটি, &nu; <span title="1×10⁻⁶ m²/s for clean water at 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['dw_reynolds_number']='Reynolds ကိန်း, Re';
$ec_lang['dw_flow_regime']='စီးဆင်းမှုပုံစံ';
$ec_lang['dw_regime_laminar']='ညင်သာသောစီးဆင်းမှု (laminar)';
$ec_lang['dw_regime_transitional']='အသွင်ကူးပြောင်းမှု (transitional)';
$ec_lang['dw_regime_turbulent']='လှုပ်ရှားသောစီးဆင်းမှု (turbulent)';
$ec_lang['dw_friction_factor_method']='ပွတ်တိုက်မှုဆေးနည်း';
$ec_lang['dw_friction_factor']='ပွတ်တိုက်မှုဆေး, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Hazen-Williams သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['hw_main_title']='အခမဲ့ အွန်လိုင်း Hazen-Williams သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['hw_main_desc']='သတ်မှတ်အချင်း၊ ကြမ်းတမ်းမှုနှင့် စီးဆင်းမှုတွင် Hazen-Williams သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['hw_hgl_1']='မြောက်ဘက် HGL';
$ec_lang['hw_hgl_2']='အပေါ်ဘက် HGL';
$ec_lang['hw_roughness']='Hazen-Williams ကိန်းဂဏန်း, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning မညီမညာ မြောင်းကြောင်း';
$ec_lang['mi_main_title']='အခမဲ့ အွန်လိုင်း Manning မညီမညာ မြောင်းကြောင်း တွက်ချက်မှုကိရိယာ';
$ec_lang['mi_main_desc']='မညီမညာ မြောင်းကြောင်း Manning တစ်သမတ်တည်း စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['mi_waterSurfaceElevation']='ရေမျက်နှာပြင် အမြင့်';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='အဖြတ်ပိုင်းအမှတ်များ';
$ec_lang['mi_groupPoint']='အမှတ်';
$ec_lang['mi_groupSegment']='အပိုင်း';
$ec_lang['mi_groupRegion']='ဇုန်';
$ec_lang['mi_station']='စခန်း';
$ec_lang['mi_elevation']='အမြင့်';
$ec_lang['mi_d50in']='အကာအရံ<br />အလယ်<br />ကျောက်<br />အရွယ်';
$ec_lang['mi_n']='n<br />အပိုင်း<br />အတွက်';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />ဇုန်<br />နယ်နိမိတ်<br />(둑)';
$ec_lang['mi_tau']='ပေါ်ပြင်<br />ညှပ်အား<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='ပေါင်းစပ်<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='မှတ်ချက်များ';
$ec_lang['mi_notes_1_term']='ပေါင်းစပ် n';
$ec_lang['mi_notes_1_def']='ဤတွက်ချက်မှုကိရိယာသည် Chow 1959၊ ၁၃၆ မျက်နှာ၊ ညီမျှခြင်း 6-17 (6-18 မဟုတ်) ကို အသုံးပြု၍ ဇုန်ပေါင်းစပ် n တွက်ချက်ရာတွင် HEC-RAS ကိုးကားစာအုပ်ကို လိုက်နာသည်။';
$ec_lang['mi_notes_2_term']='ကျောက်အကာ';
$ec_lang['mi_notes_2_def']='ကျောက်အကာ ဒီဇိုင်းဆွဲရန် Manning Trapezoidal Channel Calculator ကို အသုံးပြုပါ။ ဤတွက်ချက်မှုကိရိယာသည် သဘာဝအပိုင်းများအတွက် ပိုသင့်တော်သည်။';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning သွတ်ပိုက် စီးဆင်းမှု';
$ec_lang['mpf_main_title']='အခမဲ့ အွန်လိုင်း Manning သွတ်ပိုက် စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['mpf_main_desc']='သတ်မှတ်အစောက်နှင့် နက်ရှိုင်းမှုတွင် Manning ဖော်မြူလာ တစ်သမတ်တည်း သွတ်ပိုက် စီးဆင်းမှု';
$ec_lang['mpf_spreadheet_notice']='ဤတွက်ချက်မှုကိရိယာ၏ spreadsheet ဗားရှင်းကို ကြည့်ပါ';
$ec_lang['mpf_pipe_diameter']='သွတ်ပိုက် အချင်း, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Manning ကြမ်းတမ်းမှု, n';
$ec_lang['mpf_friction_slope']='ဖိအားအစောက် (ပိုက်အစောက်နှင့် <a target="_blank" href="../pressureslope.php">?</a> တူနိုင်), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='နှိုင်းယှဉ်စီးဆင်းမှုနက်, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(မှတ်ချက်များ ကြည့်ပါ)';
$ec_lang['mpf_flow']='စီးဆင်းမှု, Q';
$ec_lang['mpf_velocity']='အမြန်နှုန်း, v';
$ec_lang['mpf_velocity_head']='အမြန်နှုန်းခေါင်း, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='စီးဆင်းမှုနေရာ, a';
$ec_lang['mpf_pipe_area']='သွတ်ပိုက်နေရာ, a0';
$ec_lang['mpf_area_ratio']='နှိုင်းယှဉ်နေရာ, a/a0';
$ec_lang['mpf_wetted_perimeter']='စိုရွှဲသောပတ်လည်, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='ဟိုက်ဒရောလစ်အချင်းဝက်, R<sub>h</sub>';
$ec_lang['mpf_top_width']='အပေါ်ပိုင်းအကျယ်, T';
$ec_lang['mpf_froude_number']='Froude ကိန်း, F';
$ec_lang['mpf_shear_stress']='ပျမ်းမျှညှပ်အား (ဆွဲဆန့်အား), tau';
$ec_lang['mpf_full_flow']='အပြည့်စီးဆင်းမှု, Q0';
$ec_lang['mpf_full_flow_ratio']='အပြည့်စီးဆင်းမှုနှင့် အချိုး, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt><em>အဆုံးမဲ့ရှည်</em>သောသွတ်ပိုက်အတွင်းရှိ စီးဆင်းမှုနှင့် နက်ရှိုင်းမှုဖြစ်သည်။</dt><dd>သွတ်ပိုက်ထဲသို့ စီးဆင်းမှုသွင်းရန် သိသိသာသာ မြင့်မားသော ဦးရေနက်ရှိုင်းမှု လိုအပ်နိုင်သည်။ ဦးရေနက်ရှိုင်းမှုရရန် အမြန်နှုန်းခေါင်းအနည်းဆုံး 1.5 ဆကို ထည့်ပါ သို့မဟုတ် HY-8 ကို အသုံးပြုသည့် စံကြောင်းဖြတ် ဦးရေတွက်ချက်မှုများအတွက် <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ကျွန်ုပ်၏ ၂ မိနစ် သင်ခန်းစာကို ကြည့်ပါ</a>။</dd>';
$ec_lang['mpf_solve_for_dd0']='Q ပေးချက်မှ y/d<sub>0</sub> ဖြေရှင်းရန်';
$ec_lang['mpf_solve_desc']='တွက်ချက်မှုကိရိယာပုံစံမှ D<sub>0</sub>, n, နှင့် S<sub>0</sub> ကို အသုံးပြု၍ သတ်မှတ် Q အတွက် အနိမ့်ဆုံး y/d<sub>0</sub> ကို ရှာဖွေသည်။';
$ec_lang['mpf_solve_button']='ဖြေရှင်းရန်';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Manning သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['mphl_main_title']='အခမဲ့ အွန်လိုင်း Manning သွတ်ပိုက် ခေါင်းဆုံးဆုံးရှုံးမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['mphl_main_desc']='သတ်မှတ်အပြည့်စီးဆင်းမှုတွင် Manning ဖော်မြူလာ ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['mphl_pipe_length']='သွတ်ပိုက်အရှည်, L';
$ec_lang['mphl_area']='နေရာ, A';
$ec_lang['mphl_total_junction_k']='ပေါင်းစပ်ချိတ်ဆက်မှတ်ဆုံးရှုံးမှုကိန်း, k';
$ec_lang['mphl_friction_slope']='ပွတ်တိုက်မှုအစောက်';
$ec_lang['mphl_friction_loss']='ပွတ်တိုက်မှုဆုံးရှုံးမှု, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='ချိတ်ဆက်မှ ဆုံးရှုံးမှု, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='စုစုပေါင်းဆုံးရှုံးမှု, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='မြောက်ဘက် EGL';
$ec_lang['mphl_egl_2']='အပေါ်ဘက် EGL';
$ec_lang['mphl_hgl_2']='သွတ်ပိုက်အတွင်း အပေါ်ဘက် HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>ဖွင့်လှစ်ဝင်ပေါက် (ကြောင်းဖြတ်) အခြေအနေတွင် ဝင်ပေါက်ထိန်းချုပ်မှု အခြေအနေများကို စစ်ဆေးရန် လိုအပ်သည်။</dt><dd>1. အပေါ်ဘက် HGL သည် အပေါ်ဘက် ပုံမှန်နက်ရှိုင်းမှု စီးဆင်းမှုအမြင့် (သို့မဟုတ် သွတ်ပိုက်ထက် နိမ့်) ထက် နိမ့်၍မရပါ။</dd><dd>2. ကြောင်းဖြတ်တစ်ခု၏ ဦးရေသည် အပေါ်ဘက် HGL ထက် အပေါ်ဘက် EGL ဖြင့် ပိုကောင်းစွာ ကိုယ်စားပြုသည်။</dd><dd>3. HY-8 ကို အသုံးပြုသည့် ရိုးရှင်းသောစံကြောင်းဖြတ် ဦးရေတွက်ချက်မှုများအတွက် <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">ကျွန်ုပ်၏ ၂ မိနစ် သင်ခန်းစာကို ကြည့်ပါ</a>။</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Manning Trapezoidal မြောင်းကြောင်း';
$ec_lang['mtc_main_title']='အခမဲ့ အွန်လိုင်း Manning ဖော်မြူလာ Trapezoidal မြောင်းကြောင်း တွက်ချက်မှုကိရိယာ';
$ec_lang['mtc_main_desc']='သတ်မှတ်အစောက်နှင့် နက်ရှိုင်းမှုတွင် Manning ဖော်မြူလာ တစ်သမတ်တည်း Trapezoidal မြောင်းကြောင်း စီးဆင်းမှု';
$ec_lang['mtc_bottom_width']='အောက်ပိုင်းအကျယ်, b';
$ec_lang['mtc_side_slope_1']='ဘေးစောက် ၁ (အလျားဆင့်/ဒေါင်လိုက်)';
$ec_lang['mtc_side_slope_2']='ဘေးစောက် ၂ (အလျားဆင့်/ဒေါင်လိုက်)';
$ec_lang['mtc_channel_slope']='မြောင်းကြောင်းအစောက်, S';
$ec_lang['mtc_flow_depth']='စီးဆင်းမှုနက်ရှိုင်းမှု, y';
$ec_lang['mtc_bend_angle']='ကောက်ကြောင်းထောင့် <a target="_blank" href="riprap-bend-angle.png" title="ပုံကြည့်ရန် နှိပ်ပါ">?</a> (riprap အရွယ်အတွက်)';
$ec_lang['mtc_sgrock']='ကျောက်တုံးအထူးဆွဲငင်အား (2.65)';
$ec_lang['mtc_d50_in']='ဒီဇိုင်းကျောက်တုံးအရွယ်, D50';
$ec_lang['mtc_n_strickler']='Strickler အရ ဒီဇိုင်းကျောက်တုံးအရွယ်အတွက် n';
$ec_lang['mtc_n_blodgett']='Blodgett အရ ဒီဇိုင်းကျောက်တုံးအရွယ်အတွက် n';
$ec_lang['mtc_n_bathurst']='Bathurst အရ ဒီဇိုင်းကျောက်တုံးအရွယ်အတွက် n';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett နှင့် Bathurst နှိုင်းယှဉ်မှု';
$ec_lang['mtc_d50_bottom']='လိုအပ်သောအောက်ပိုင်းထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Isbash & MC) <span title="Isbash (1936) နှင့် Maricopa County, Arizona, US အရ." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='လိုအပ်သောဘေးစောက် ၁ ထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Isbash & MC) <span title="Isbash (1936) နှင့် Maricopa County, Arizona, US အရ." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='လိုအပ်သောဘေးစောက် ၂ ထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Isbash & MC) <span title="Isbash (1936) နှင့် Maricopa County, Arizona, US အရ." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='လိုအပ်သောထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='လိုအပ်သောထောင့်ချောင်းကျောက်တုံးအရွယ်, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>အလိုအလျောက် ကျောက်တုံးအရွယ်နှင့် ကြမ်းတမ်းမှုဒီဇိုင်း ထပ်ခါထပ်ခါတွက်ချက်မှု</dt><dd>ကြမ်းတမ်းမှု ရေဒီယိုခလုတ် (BB အကြံပြု) နှင့် ဒီဇိုင်းကျောက်တုံးအရွယ် ရေဒီယိုခလုတ် (Isbash အကြံပြု) ကိုရွေးချယ်ပါ။ တညီတညာတည်းကျောက်တုံးအရွယ်ဖြင့် သင်လိုချင်သောစီးဆင်းမှုရရန် နက်ရှိုင်းမှုနှင့် ကျောက်တုံးအရွယ်လုံခြုံရေးဆေးကို ချိန်ညှိပါ။ မည်သည့် ထည့်သွင်းချက်တန်ဖိုး ပြောင်းလဲသည့်အခါတိုင်း ောင်လာသောထပ်ခါတလဲလဲအကြိမ်မြောက်ကာလ ဖြစ်ပေါ်သည်: ၁. ဒီဇိုင်းကျောက်တုံးအရွယ်မှ ကြမ်းတမ်းမှုကို တွက်ချက်သည်။ ၂. တောင်းဆိုထားသောကြမ်းတမ်းမှုတွက်ချက်မှုကို ထည့်သွင်းကြမ်းတမ်းမှုသို့ ကူးယူသည်။ ၃. မြောင်းကြောင်းစီးဆင်းမှုနှင့် လိုအပ်သောကျောက်တုံးအရွယ်ကို တွက်ချက်သည်။ ၄. ဒီဇိုင်းကျောက်တုံးအရွယ်ကို ချိန်ညှိသည်။ ၅. ဒီဇိုင်းကျောက်တုံးအရွယ်အမှားငယ်မြဲဖြစ်သည့်အထိ ထပ်ခါတလဲလဲ ဆောင်ရွက်သည်။</dd><dt>အခြေခံတွက်ချက်မှုကိရိယာ (ထပ်ခါတလဲလဲမဟုတ်)</dt><dd>သင်လိုချင်သောကြမ်းတမ်းမှုတန်ဖိုးကို ထည့်ပါ။ ဒီဇိုင်းကျောက်တုံးအရွယ်ထည့်သွင်းနေရာကို လျစ်လျူရှုပါ။</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Robinson Rock Chute';
$ec_lang['rrc_main_desc']='Robinson Rock Chute ဒီဇိုင်း Spreadsheet';
// Weir Flow Simple
$ec_lang['ws_main_menu']='ရိုးရှင်းသော ဆည်တမံ စီးဆင်းမှု';
$ec_lang['ws_main_title']='အခမဲ့ အွန်လိုင်း ရိုးရှင်းသော ကျယ်ပြူးနှင်းစွပ် ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['ws_main_desc']='ရိုးရှင်းသော ကျယ်ပြူးနှင်းစွပ် ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['ws_weirLength']='ဆည်တမံအရှည်, l';
$ec_lang['ws_headWaterHeight']='ဦးရေအမြင့်, h';
$ec_lang['ws_weirCoefficient']='ဆည်တမံကိန်းဂဏန်း, Cw';
$ec_lang['ws_notes_heading']='မှတ်ချက်များ';
$ec_lang['ws_notes_we_term']='ဆည်တမံညီမျှခြင်း';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='မညီမညာ ဆည်တမံ စီးဆင်းမှု';
$ec_lang['wi_main_title']='အခမဲ့ အွန်လိုင်း အပိုင်းပိုင်း ပြောင်းလဲသောနက်ရှိုင်းမှုနှင့် မညီမညာ ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['wi_main_desc']='မညီမညာ ဆည်တမံ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['wi_headWaterelevation']='ဦးရေအမြင့်';
$ec_lang['wi_weirPoints']='ဆည်တမံအမှတ်များ';
$ec_lang['wi_station']='စခန်း<br />(အကွာအဝေး)';
$ec_lang['wi_elevation']='အမြင့်';
$ec_lang['wi_pondingHeight']='ရေဝပ်မှုအမြင့်';
$ec_lang['wi_incrementalFlow']='တိုးမြှင့်စီးဆင်းမှု';
$ec_lang['wi_cumulativeFlow']='စုစုပေါင်းစီးဆင်းမှု';
$ec_lang['wi_save_and_calculate']='သိမ်းဆည်းပြီး တွက်ချက်ရန်';
$ec_lang['wi_notes_we_term']='ဆည်တမံညီမျှခြင်း';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='အပေါက်မှ စီးဆင်းမှု';
$ec_lang['or_main_title']='အခမဲ့ အွန်လိုင်း အပေါက်မှ စီးဆင်းမှု တွက်ချက်မှုကိရိယာ';
$ec_lang['or_main_desc']='အပေါက်မှ စီးဆင်းမှု — လွတ်လပ်သော သို့မဟုတ် နစ်မွန်းသော';
$ec_lang['or_shape']='ဖွင့်လှစ်ပုံသဏ္ဌာန်';
$ec_lang['or_shape_circular']='စက်ဝိုင်းပုံ';
$ec_lang['or_shape_rectangular']='ထောင့်မှန်စတုဂံပုံ';
$ec_lang['or_diameter']='Diameter or height, D <span title="Diameter for circular; height for rectangular" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_width']='Width, W <span title="Rectangular openings only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_invert']='Invert elevation <span title="Bottom of opening" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_hwe']='ဦးရေအမြင့်';
$ec_lang['or_twe']='နောက်ရေအမြင့်';
$ec_lang['or_cd']='ထုတ်လွှတ်မှုကိန်းဂဏန်း, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='ဗဟိုချက်အမြင့်';
$ec_lang['or_head']='ထိရောက်သောခေါင်းဆုံး, h';
$ec_lang['or_area']='ဖွင့်လှစ်နေရာ, A';
$ec_lang['or_flow']='စီးဆင်းမှု, Q';
$ec_lang['or_velocity']='Velocity, v';
$ec_lang['or_regime']='အပေါက်ပုံစံစစ်ဆေးမှု';
$ec_lang['or_regime_valid']='လွတ်လပ်သောကျဆင်းမှု — အပေါက်ပုံစံ မှန်ကန် ✓';
$ec_lang['or_regime_submerged']='နစ်မွန်းသောအပေါက် (TWE သည် invert အပေါ်တွင်) — မှန်ကန် ✓';
$ec_lang['or_regime_warn']='သတိပေးချက်: ဦးရေသည် crown အောက်တွင် — အပေါက်ပုံစံမဟုတ်';
$ec_lang['or_regime_twe_above_hwe']='သတိပေးချက်: နောက်ရေ (TWE) သည် ဦးရေ (HWE) အပေါ်တွင် — ထည့်သွင်းချက်များ စစ်ဆေးပါ';
$ec_lang['or_notes_1_term']='အပေါက်ညီမျှခြင်း';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). လွတ်လပ်သောကျဆင်းမှုအတွက်: h = HWE &minus; ဗဟိုချက်. နစ်မွန်းသောစီးဆင်းမှု (invert အပေါ်တွင် TWE): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='အပေါက်ပုံစံ';
$ec_lang['or_notes_2_def']='ဦးရေမျက်နှာပြင်သည် ဖွင့်လှစ်မှ crown (အပေါ်) အပေါ်တွင်ရှိသောအခါ အပေါက်စီးဆင်းမှုညီမျှခြင်းများ သက်ဆိုင်သည်။ ဦးရေသည် crown အောက်တွင်ရှိသောအခါ ၎င်းအစား ဆည်တမံညီမျှခြင်းကို အသုံးပြုပါ။';
$ec_lang['or_notes_3_term']='ထုတ်လွှတ်မှုကိန်းဂဏန်း';
$ec_lang['or_notes_3_def']='C<sub>d</sub> သည် ချွန်ထက်သောဘောင်ပါ အပေါက်များအတွက် ၀.၆၀&ndash;၀.၆၅ ခန့်ဖြစ်သည်။ ဝိုင်းသော သို့မဟုတ် ပြန်ဝင်သောဝင်ပေါက်များသည် ကွဲပြားသောတန်ဖိုးများ အသုံးပြုသည်။ လမ်းညွှန်မှုအတွက် <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> သို့မဟုတ် HEC-RAS Hydraulic Reference Manual ကို ကြည့်ပါ။';
$ec_lang['or_notes_4_term']='နစ်မွန်းမှု';
$ec_lang['or_notes_4_def']='TWE သည် ဖွင့်လှစ်မှ invert အပေါ်တွင်ရှိသောအခါ ဤတွက်ချက်မှုကိရိယာသည် h = HWE &minus; TWE ကိုအသုံးပြု၍ နစ်မွန်းသောအပေါက်ညီမျှခြင်းကို အလိုအလျောက်သုံးသည်။ TWE သည် invert တွင်ရှိသော သို့မဟုတ် အောက်တွင်ရှိသောအခါ လွတ်လပ်သောကျဆင်းမှုဟု မှတ်ယူပြီး h = HWE &minus; ဗဟိုချက်ဖြစ်သည်။';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='မိုက်ခရိုဟိုက်ဒရို ပါဝါ';
$ec_lang['mhp_main_title']='အခမဲ့ အွန်လိုင်း မိုက်ခရိုဟိုက်ဒရို ပါဝါ တွက်ချက်မှုကိရိယာ';
$ec_lang['mhp_main_desc']='မြစ်ဘေးစီးမိုက်ခရိုဟိုက်ဒရို ပါဝါထုတ်ပိုးတွက်ချက်မှုကိရိယာ';
$ec_lang['mhp_flow']='စီးဆင်းနှုန်း, Q';
$ec_lang['mhp_gross_head']='စုစုပေါင်းခေါင်းဆုံး, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Penstock အချင်း, D';
$ec_lang['mhp_length']='Penstock အရှည်, L';
$ec_lang['mhp_roughness']='သွတ်ပိုက်ကြမ်းတမ်းမှု, e';
$ec_lang['mhp_km']='Minor loss coefficient, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_nu']='Kinematic viscosity, &nu; <span title="1×10⁻⁶ m²/s for clean water near 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['mhp_efficiency']='စက်ရုံထိရောက်မှု, &eta; (0&ndash;1)';
$ec_lang['mhp_velocity']='စီးဆင်းမှုအမြန်နှုန်း, v';
$ec_lang['mhp_vel_check']='အမြန်နှုန်းစစ်ဆေးမှု';
$ec_lang['mhp_f']='ပွတ်တိုက်မှုဆေး, f';
$ec_lang['mhp_hf']='ပွတ်တိုက်မှုခေါင်းဆုံးဆုံးရှုံးမှု, h<sub>f</sub>';
$ec_lang['mhp_hm']='Minor head loss, h<sub>m</sub>';
$ec_lang['mhp_hl']='Penstock စုစုပေါင်းဆုံးရှုံးမှု, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='ခေါင်းဆုံးဆုံးရှုံးမှုစစ်ဆေးမှု';
$ec_lang['mhp_hnet']='အသားတင်ခေါင်းဆုံး, H<sub>net</sub>';
$ec_lang['mhp_power']='ပါဝါထုတ်ပိုး, P';
$ec_lang['mhp_annual_kwh']='၁၀၀% အလားအလာတွင် နှစ်စဉ်စွမ်းအင်';
$ec_lang['mhp_vel_ok']='1–3 m/s — ပစ်မှတ်အတွင်း ✓';
$ec_lang['mhp_vel_low']='1 m/s အောက် — အချင်းလျှော့ချပါ ⚠';
$ec_lang['mhp_vel_high']='3 m/s အပေါ် — အချင်းတိုးချဲ့ပါ ⚠';
$ec_lang['mhp_hl_ok']='၁၀% ပစ်မှတ်အတွင်း ✓';
$ec_lang['mhp_hl_warn']='၁၀% ပစ်မှတ်ကျော်လွန် — ကြီးမားသောပိုက်ကို ထည့်သွင်းစဉ်းစားပါ ⚠';
$ec_lang['mhp_hl_bad']='၂၀% ကျော်လွန် — သွတ်ပိုက် ပြန်လည်အရွယ်တိုင်းပါ';
$ec_lang['mhp_notes_1_term']='ခေါင်းဆုံးဆုံးရှုံးမှု';
$ec_lang['mhp_notes_1_def']='Penstock စုစုပေါင်းဆုံးရှုံးမှု h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, h<sub>f</sub> = f(L/D)(v&sup2;/2g) သည် Darcy-Weisbach ပွတ်တိုက်မှုဆုံးရှုံးမှုဖြစ်ပြီး h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g သည် ဝင်ပေါက်၊ ကောက်ကြောင်းနှင့် ventil များကို ကျုံ့ဆုပ်သည်။ အသားတင်ခေါင်းဆုံး H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='အမြန်နှုန်း';
$ec_lang['mhp_notes_2_def']='1&ndash;3 m/s ကို ပစ်မှတ်ထားပါ။ 1 m/s အောက်သည် စီးဆင်းမှုအတွက် သွတ်ပိုက်ကို အလွန်ကြီးစေသည်; 3 m/s အပေါ်သည် ပွတ်တိုက်မှုဆုံးရှုံးမှုနှင့် ရေပေါက်အချက်ပြ အန္တရာယ်ကို တိုးစေသည်။';
$ec_lang['mhp_notes_3_term']='ခေါင်းဆုံးဆုံးရှုံးမှုပစ်မှတ်';
$ec_lang['mhp_notes_3_def']='စုစုပေါင်းခေါင်းဆုံး၏ ၁၀% အောက်ရှိ Penstock ဆုံးရှုံးမှုများသည် ယေဘုယျ အဆင်ပြေသည်။ သွတ်ပိုက်ကုန်ကျစားရိတ်နှင့် ဆုံးရှုံးသောပါဝါအကြား အကောင်းဆုံးရွေးချယ်မှုသည် တန်ဖိုးမြင့်လျှပ်စစ်နေရာများအတွက် ၄&ndash;၆% ခန့်ကျဆင်းသည်။';
$ec_lang['mhp_notes_4_term']='ချိတ်ဆက်မ (အမှတ်) ဆုံးရှုံးမှုများ k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='ဤဆုံးရှုံးမှုများသည် သွတ်ပိုက်ချိတ်ဆက်မများ၊ ဝင်ပေါက်များ၊ ကောက်ကြောင်းများနှင့် ventil များတွင် ဖြစ်ပေါ်သည် &mdash; &ldquo;အသေး&rdquo; ဟူသောဝေါဟာရသည် သမရိုးကျဖြစ်သော်လည်း လမ်းလွဲသည်; တိုသော penstock တစ်ခုတွင် ပွတ်တိုက်မှုဆုံးရှုံးမှုနှင့် ညီမျှ သို့မဟုတ် ကျော်လွန်နိုင်သည်။ ယေဘုယျ k တန်ဖိုးများ: ချွန်ထက်သောဝင်ပေါက် 0.5, 45&deg; ကောက်ကြောင်းတစ်ခုစီ 0.2&ndash;0.3, gate valve (အပြည့်ဖွင့်) 0.1, butterfly valve 0.2. စုစုပေါင်း k<sub>m</sub> ရရန် ချိတ်ဆက်မများကို ပေါင်းပါ။ ပုသေချက် 1.5 သည် ဝင်ပေါက်တစ်ခုနှင့် ကောက်ကြောင်းနှစ်ခုဟု မှတ်ယူသည်။';
$ec_lang['mhp_notes_5_term']='သွတ်ပိုက်ကြမ်းတမ်းမှု e';
$ec_lang['mhp_notes_5_def']='ယေဘုယျပကတိကြမ်းတမ်းမှု: သံမဏိ (အသစ်) 0.046&nbsp;mm, သံမဏိ (အသုံးပြုပြီး) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, ကွန်ကရစ် 0.3&ndash;3&nbsp;mm. HDPE သည် အသေးစားမိုက်ခရိုဟိုက်ဒရို penstock များအတွက် အများသုံးဖြစ်သည်။';

// Orifice Drain Time
$ec_lang['odt_main_menu']='အပေါက်မှ ရေထုတ်ချိန်';
$ec_lang['odt_main_title']='အခမဲ့ အွန်လိုင်း အပေါက်မှ ရေထုတ်ချိန် တွက်ချက်မှုကိရိယာ — အင်တိုင်း၊ မြောင်းကြောင်း သို့မဟုတ် တိုင်ကီ';
$ec_lang['odt_main_desc']='အင်တိုင်း သို့မဟုတ် မြောင်းကြောင်း အပေါက်ရေထုတ်ချိန် &mdash; ကွာဖြတ်ပမာဏနည်းလမ်း';
$ec_lang['odt_h1_elev']='Starting WSE <span title="Starting water surface elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_a1']='Starting area, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Ending WSE';
$ec_lang['odt_h_orifice']='အပေါက်ဗဟိုချက်အမြင့်';
$ec_lang['odt_a0']='Orifice-level area, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Ending area, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_h2_check']='အဆုံးသတ်အမြင့်စစ်ဆေးမှု';
$ec_lang['odt_h2_ok']='အဆုံးသတ်အမြင့်သည် အပေါက်အထိပ်အပေါ်တွင် ✓';
$ec_lang['odt_h2_warn']='သတိပေးချက်: အဆုံးသတ်အမြင့်သည် အပေါက်အထိပ် (ဗဟိုချက် + D/2) တွင် သို့မဟုတ် အောက်တွင်';
$ec_lang['odt_d']='Orifice D <span title="Diameter (circular) or height (rectangular)" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_w']='Orifice width, W <span title="Rectangular only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_t_sec']='Drain time (s)';
$ec_lang['odt_t_min']='Drain time (min)';
$ec_lang['odt_t_hr']='Drain time (hr)';
$ec_lang['odt_t_day']='Drain time (days)';
$ec_lang['odt_notes_1_term']='ဖော်မြူလာ';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) သည် ခေါင်းဆုံး H မှ အပေါက်သို့ ရေထုတ်ချိန်ကို ပေးသည်။ ရေထုတ်ချိန် = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), H<sub>1</sub> = စတင်အမြင့် &minus; အပေါက်အမြင့်, H<sub>2</sub> = အဆုံးသတ်အမြင့် &minus; အပေါက်အမြင့်.';
$ec_lang['odt_notes_2_term']='နည်းလမ်း';
$ec_lang['odt_notes_2_def']='ကွာဖြတ်ပမာဏနည်းလမ်းသည် အင်တိုင်း သို့မဟုတ် မြောင်းကြောင်းကို ရေမျက်နှာပြင်တွင် စတင်နေရာ A<sub>1</sub> နှင့် အပေါက်ဗဟိုချက်အမြင့်တွင် နေရာ A<sub>0</sub> အကြား ကွာဖြတ်ပိုင်းဟု မော်ဒယ်ပြုသည်။ A<sub>2</sub>၊ အဆုံးသတ်အမြင့်တွင် အင်တိုင်းနေရာ၊ ကွာဖြတ်ပိုင်းမော်ဒယ်ကို အသုံးပြု၍ A<sub>1</sub> နှင့် A<sub>0</sub> မှ ကြားထည့်တွက်ချက်သည်။ စတင်မှ အဆုံးသတ်အမြင့်သို့ ရေထုတ်ချိန်သည် H<sub>1</sub> မှ အပေါက်သို့ စုစုပေါင်းရေထုတ်ချိန်နှင့် H<sub>2</sub> မှ အပေါက်သို့ ကျန်ရှိသောရေထုတ်ချိန် ခြားနားချက်နှင့် ညီသည်။';
$ec_lang['odt_h1']='Starting head, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_q_max']='Max flow, Q<sub>max</sub>';
$ec_lang['odt_vol']='ထုတ်လွှတ်ပမာဏ';
$ec_lang['odt_sketch_start']='စတင်';
$ec_lang['odt_sketch_end']='အဆုံးသတ်';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='ကမ်းနဖူးမှ ကမ်းနဖူးအကျယ်';
$ec_lang['essc_mcr']='အနည်းဆုံးကောက်ကြောင်းအချင်း';
$ec_lang['essc_q']='စီးဆင်းမှု, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='ဆည်မြောင်းရေစီးဆင်းမှုတိုင်းတာ';
$ec_lang['irr_main_title']='အခမဲ့ အွန်လိုင်းဆည်မြောင်းရေစီးဆင်းမှုတိုင်းတာ ကိရိယာများ';
$ec_lang['irr_main_desc']='ဆည်မြောင်းရေစီးဆင်းမှုတိုင်းတာ — Weir နှင့် Orifice';
$ec_lang['contact_title']='HawsEDC ဆက်သွယ်ရန်';
$ec_lang['contactSendMessage']='Tom Haws ထံ မက်ဆေ့ပေးပို့ပါ';
$ec_lang['contactYourName']='သင့်နာမည်:';
$ec_lang['contactYourEmail']='သင့်အီးမေးလ်လိပ်စာ:';
$ec_lang['contactSubject']='အကြောင်းအရာ:';
$ec_lang['contact_message']='မက်ဆေ့:';
$ec_lang['contactSpamPrefix']='ငါးပေါင်း တစ်ညီ';
$ec_lang['contactSpamPostfix']='(ကျေးဇူးပြု၍ စကားလုံးဖြင့် ရေးပါ။ 1=တစ် 2=နှစ် 3=သုံး 4=လေး 5=ငါး 6=ခြောက် 7=ခုနစ် +=ပေါင်း 5+1=6)';
$ec_lang['contactSubmitButton']='မက်ဆေ့တင်ပြရန်';
$ec_lang['contact_success']='ရေးပေးသည့်အချိန်များအတွက် ကျေးဇူးတင်ပါသည်။';

// About
$ec_lang['about_main_menu']='အကြောင်း';
$ec_lang['install_main_menu']='ထည့်သွင်း';
$ec_lang['install_main_title']='EngCalcs ထည့်သွင်းရန်';
$ec_lang['install_main_desc']='အင်တာနက်မရှိဘဲ သုံးရန် သင့်စက်တွင် ထည့်ပါ';
$ec_lang['contact_main_menu']='ဆက်သွယ်ရန်';
$ec_lang['about_main_title']='HawsEDC အင်ဂျင်နီယာ ကိရိယာများ အကြောင်း';
$ec_lang['about_main_desc']='ရည်ရွယ်ချက်၊ ပွင့်လင်းအရင်းအမြစ်နှင့် ပါဝင်ကူညီမှု';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='စက်ပေါက်/ဖြန်းပက် ဆည်မြောင်းရေနှုန်း';
$ec_lang['ds_main_title']='အခမဲ့ Online စက်ပေါက်/ဖြန်းပက် ဆည်မြောင်းရေနှုန်း တွက်ချက်မှု';
$ec_lang['ds_main_desc']='စက်ပေါက် &amp; ဖြန်းပက် ဆည်မြောင်း &mdash; ရေပေးနှုန်း နှင့် တညီတညွတ်တည်းမှု';
$ec_lang['ds_q_avg']='ပျမ်းမျှ emitter စီးဆင်းမှုနှုန်း, q';
$ec_lang['ds_q_min']='အနည်းဆုံး emitter စီးဆင်းမှုနှုန်း, q<sub>min</sub>';
$ec_lang['ds_se']='Emitter spacing, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateral spacing, S<sub>l</sub>';
$ec_lang['ds_n_e']='lateral တစ်ခုတွင် emitter အရေအတွက်, n<sub>e</sub>';
$ec_lang['ds_n_l']='zone တစ်ခုတွင် lateral အရေအတွက်, n<sub>l</sub>';
$ec_lang['ds_d']='ပစ်မှတ် ရေပေးနက်, d';
$ec_lang['ds_a_e']='emitter တစ်ခုလျှင် ဧရိယာ, A<sub>e</sub>';
$ec_lang['ds_pr']='Application rate, PR';
$ec_lang['ds_du']='ဖြန့်ဝေမှု တညီတညွတ်တည်းမှု, DU';
$ec_lang['ds_du_check']='DU အရည်အသွေး စစ်ဆေးခြင်း';
$ec_lang['ds_q_lat']='lateral တစ်ခုစီ စီးဆင်းမှု, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='zone စီးဆင်းမှု, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Runtime (hours)';
$ec_lang['ds_du_excellent']='အလွန်ကောင်း — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='ကောင်း — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='လက်ခံနိုင် — DU ≥ 70%';
$ec_lang['ds_du_poor']='ညံ့ — DU < 70% — ဒီဇိုင်း ပြန်လည်သုံးသပ်ပါ ⚠';
$ec_lang['ds_notes_1_term']='ရေပေးနှုန်း';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>၊ A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> သည် emitter တစ်ခုချင်းဆောင်ရွက်သည့် ဧရိယာဖြစ်သည်။ ရေပေးနှုန်း နည်းလေ မြေကြီးထဲ ရေစိမ့်ဝင်ရန် အချိန်ပိုရလေ &mdash; လေးသော မြေဆီလွှာ သို့မဟုတ် ကန့်လန့်ကွင်းများတွင် အရေးကြီးသည်။';
$ec_lang['ds_notes_2_term']='ဖြန့်ဝေမှု တညီတညွတ်တည်းမှု (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>။ DU 1.0 (100%) ဆိုသည်မှာ emitter အားလုံး တူညီစွာ စီးဆင်းသည်ဟု အဓိပ္ပာယ်ရသည်။ 0.80 အောက် တန်ဖိုးများသည် ရေကောင်းသောနေရာများတွင် ရေဖုန်းကုန်ကာ ပိုသောနေရာများ ကျန်ရစ်သည်။';
$ec_lang['ds_notes_3_term']='လည်ပတ်ချိန်';
$ec_lang['ds_notes_3_def']='လည်ပတ်ချိန် = ပစ်မှတ်နက် &divide; ရေပေးနှုန်း။ ကန့်လန့် သို့မဟုတ် မာကြောသော မြေဆီလွှာများတွင် လည်ပတ်ချိန်ကို ကြားခဏနားပြီး တိုတောင်းသောသံသရာ နှစ်ခု သို့ သုံးခုခွဲပါ။';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='မြောင်းရေစိမ့်မှု';
$ec_lang['cs_main_title']='အခမဲ့ အွန်လိုင်း မြောင်းရေစိမ့်ဆုံးရှုံးမှုနှင့် သယ်ဆောင်မှုထိရောက်နှုန်း တွက်ချက်မှုကိရိယာ';
$ec_lang['cs_main_desc']='မြောင်းရေစိမ့်ဆုံးရှုံးမှု &amp; သယ်ဆောင်မှုထိရောက်နှုန်း &mdash; ဝင်စီးဆင်းမှု-ထွက်စီးဆင်းမှု နည်းလမ်း';
$ec_lang['cs_Q_in']='Inflow, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Outflow, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='ရေစိမ့်ဆုံးရှုံးနှုန်း, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='တိုင်းတာမှု စစ်ဆေးချက်';
$ec_lang['cs_pct_loss']='Fraction lost';
$ec_lang['cs_Ec']='သယ်ဆောင်မှုထိရောက်နှုန်း, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='ထိရောက်နှုန်း အဆင့်';
$ec_lang['cs_Vol_day']='နေ့စဉ် ဆုံးရှုံးသောပမာဏ';
$ec_lang['cs_Vol_year']='နှစ်စဉ် ဆုံးရှုံးသောပမာဏ';
$ec_lang['cs_L']='ရောက်ရှိသောနေရာ အလျား, L';
$ec_lang['cs_wp']='Wetted perimeter, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='Loss per unit length, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Water value';
$ec_lang['cs_lining_cost']='Lining cost';
$ec_lang['cs_Ec_target']='Lining target, E<sub>c,target</sub> <span title="Conveyance efficiency goal after lining; fraction 0&ndash;1" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_lining_area']='Lining area, L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Annual value lost';
$ec_lang['cs_annual_value_recovered']='Annual value recovered';
$ec_lang['cs_lining_total_cost']='Total lining cost';
$ec_lang['cs_payback_years']='Payback period <span title="Simple payback = total lining cost &divide; annual value recovered" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_notes_3_term']='အနားသတ်စြမ်းပြန်ရထားခြင်းကာလ';
$ec_lang['cs_notes_3_def']='ရေ တန်ဖိုးနှင့် အနားသတ်စြမ်းကုန်ကျစားရိတ်ကို တူညီသော ငွေကြေးယူနစ်ဖြင့် ထည့်သွင်းပါ။ အနားသတ်စြမ်းဧရိယာ = ရောက်ရှိသောနေရာအလျား &times; စိုရွှဲသောပတ်လည် &mdash; အတိုင်းအတာထားသော စီးဆင်းမှုနက်ရှိုင်းမှုတွင် မြောင်းခြတ်သုံးမျက်နှာပြင်၏ စိုရွှဲသောပတ်လည် (အောက်ခြေအကျယ်အပြင် ခြေလှမ်းနှစ်ခုလုံး၏ စိုရွှဲသည့် ကြမ်းခင်း)။ နှစ်စဉ်ပြန်လည်ရရှိသည့် တန်ဖိုးသည် အနားသတ်စြမ်းမြောင်းသည် ပစ်မှတ် E<sub>c</sub> ကိုအဆက်မပြတ် ရရှိသည်ဟု မှတ်ယူသည်။ ရုံးကျန်တွင် အနားသတ်စြမ်းများ သို့မဟုတ် အနားသတ်စြမ်းသည် ပစ်မှတ်ထိရောက်နှုန်းသို့မဟုတ်နိမ့်ကျသည်ခြင်းတွင် တကယ့်ပြန်ရထားခြင်းကာလသည် ပိုရှည်ပါလိမ့်မည်။';
$ec_lang['cs_notes_4_term']='ကိုးကားချက်';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, တတိယထုတ်ဝေမှု (2001)။ FAO Irrigation and Drainage Paper 57 (1999)။';
$ec_lang['cs_loss_positive']='Qin > Qout — ရေစိမ့်မှု တွေ့ရှိ ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — တိုင်းတာနိုင်သောဆုံးရှုံးမှု မရှိ';
$ec_lang['cs_loss_negative']='သတိပေးချက်: Qout > Qin — တိုင်းတာမှုများ စစ်ဆေးပါ ⚠';
$ec_lang['cs_Ec_good']='ကောင်း — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='အတော်အသင့် — Ec 60–80%';
$ec_lang['cs_Ec_poor']='ညံ့ — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='နည်းလမ်း';
$ec_lang['cs_notes_1_def']='ဝင်စီးဆင်းမှု-ထွက်စီးဆင်းမှု နည်းလမ်းသည် မြောင်းပိုင်းတွင်း ဦးနှင့်အမြီး ရှိ စီးဆင်းမှုတိုင်းတာ၍ ရေစိမ့်မှုကို ခန့်မှန်းသည်: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>။ သယ်ဆောင်မှုထိရောက်နှုန်း E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>။ နှစ်စဉ်ပမာဏသည် အဆက်မပြတ်ပြည့်စီးဆင်းမှု လုပ်ဆောင်မှုကို မှတ်ယူသည်; ရာသီဥတု သို့မဟုတ် တစ်ပိုင်းတစ်စမြောင်းများတွင် တကယ့်ဆုံးရှုံးမှု ပိုနည်းသည်။';
$ec_lang['cs_notes_2_term']='ထိရောက်နှုန်း အဆင့်သတ်မှတ်ချက်';
$ec_lang['cs_notes_2_def']='ပုံမှန်အတုပြုမထားသော မြေသားမြောင်းများ: E<sub>c</sub> = 60&ndash;80%။ ကောင်းစွာ ထိန်းသိမ်းသောမြေသားမြောင်းများ: 75&ndash;85%။ ကွန်ကရစ်အနားသတ်မြောင်းများ: 90&ndash;98%။ ဝင်စီးဆင်းမှု၏ ၃၀% ကျော် ရေစိမ့်ဆုံးရှုံးမှုများသည် အနားသတ်ရင်းနှီးမြှုပ်နှံမှုကို အကျိုးရှိစေသောအခါများတွင်ဖြစ်သည်။ (USBR, FAO)';

$ec_lang['irr_intro_html']='<p>ဝေါ်နှင့် အပေါက်များသည် ဆည်မြောင်းစနစ်များတွင် ရေစီးဆင်းမှုတိုင်းတာရန် စံပြုနေ့တနေ့သုံး ကိရိယာများဖြစ်သည်။ သင့်အဆောက်အဦနှင့် ကိုက်ညီသော ဂဏန်းတွက်စက်ကို ရွေးချယ်ပါ:</p>';
$ec_lang['irr_card_weir_uniform_head']='ဝေါ် — ကျယ်ဝန်းသောရေကန်ထိပ် (တူညီသောအကျယ်)';
$ec_lang['irr_card_weir_uniform_desc']='ပြောင်းလမ်းဆည်ထိပ်၊ စစ်ဆေးရေးအဆောက်အဦ သို့မဟုတ် ဝေါ်ဘုတ်ပေါ်မှ ရေစီးဆင်းမှုကို တိုင်းတာပါ။ ဝေါ်၏ အရှည်နှင့် ထိပ်ပေါ်ရှိ ရေနက်ကို ထည့်သွင်းပါ။';
$ec_lang['irr_card_weir_irregular_head']='ဝေါ် — ပုံမမှန်သောဆိုင်ခြင်း';
$ec_lang['irr_card_weir_irregular_desc']='ဝေါ်ထိပ်သည် တစ်ခုထဲသောအမြင့်မဟုတ်သောအခါ သုံးပါ — သဘာဝ spillway များ၊ ကျဉ်းချဲ့ပြောင်းလဲသည့် ကျဆင်းမှုဆောက်လုပ်ရေးများ သို့မဟုတ် အပိုင်းများစွာပါသော ထိန်းချုပ်ဆောက်လုပ်ရေးများ။';
$ec_lang['irr_card_orifice_head']='အပေါက် — ရေဦးတံခါး သို့မဟုတ် အပိုင်းပိုက်';
$ec_lang['irr_card_orifice_desc']='ဆလိုင်ဒ်တံခါး၊ ပိုက်ထွက်ပေါက် သို့မဟုတ် culvert ပေါက်ဝမှ ရေစီးဆင်းမှုကို တိုင်းတာပါ။ လွတ်လပ်သော ရေဆင်းနှင့် မြုပ်နစ်ခြင်း (အောက်ဖိအား) နှစ်ခုလုံးကို အော်တိုမက်တစ်ကျ ကိုင်တွယ်သည်။';
$ec_lang['irr_card_canal_head']='မြောင်းဒီဇိုင်း &amp; ခွဲခြမ်းစိတ်ဖြာ';
$ec_lang['irr_card_canal_desc']='Manning\'s ဖော်မြူလာကို အသုံးပြု၍ ဆည်မြောင်းကို ဒီဇိုင်းဆွဲ သို့မဟုတ် စစ်ဆေးပါ။ မြောင်းသစ်များအတွက် Trapezoidal ဂဏန်းတွက်စက်ကို သုံးပါ; ရှိပြီးသား သဘာဝ သို့မဟုတ် တည်ဆောက်ထားသော ဖြတ်ပိုင်းများအတွက် Irregular ဂဏန်းတွက်စက်ကို သုံးပါ။';
$ec_lang['irr_card_drip_head']='ရေစက်ကျ &amp; Sprinkler ဒီဇိုင်း';
$ec_lang['irr_card_drip_desc']='ရေစက်ကျ သို့မဟုတ် sprinkler ဆည်မြောင်းစနစ်အတွက် လျှောက်ထားနှုန်း၊ ဖြန့်ဝေမှုညီမျှမှု၊ ဘေးပိုက်စီးဆင်းမှု၊ ဇုန်စီးဆင်းမှုနှင့် လည်ပတ်ချိန် တွက်ချက်ပါ။ Emitter စီးဆင်းမှု၊ Emitter အကွာအဝေးနှင့် ပန်းတိုင်နက်ကို ထည့်သွင်းပါ။';
$ec_lang['irr_card_seepage_head']='မြောင်းရေစိမ့်မှု &amp; သယ်ဆောင်မှုထိရောက်နှုန်း';
$ec_lang['irr_card_seepage_desc']='ဝင်စီးဆင်းမှုနှင့် ထွက်စီးဆင်းမှုတိုင်းတာချက်များကို အသုံးပြု၍ မြောင်းပိုင်းတွင်းမှ ရေစိမ့်ဆုံးရှုံးမှု ခန့်မှန်းပါ။ သယ်ဆောင်မှုထိရောက်နှုန်းနှင့် နှစ်စဉ်ရေဆုံးရှုံးမှုကို တွက်ချက်ကာ အနားသတ်ရင်းနှီးမြှုပ်နှံမှု ဦးစားပေးမှုတွင် ကူညီပါ။';
$ec_lang['irr_quickref_html']='<h3>မြန်ဆန်သောကိုးကားချက်</h3><dl><dt>ပြောင်းလမ်းဆည် သို့မဟုတ် ထိန်းချုပ်ဆောက်လုပ်ရေး</dt><dd>ဝေါ်ထိပ်ပေါ်ရှိ ရေနက်ကို တိုင်းတာပါ။ တူညီသောထိပ်အတွက် <a href="Weir-Flow-Simple.php">ရိုးရှင်းသောဝေါ်စီးဆင်းမှု</a> ကို သုံးပါ သို့မဟုတ် ဆိုင်ခြင်းမရှိသော ထိပ်အတွက် <a href="Weir-Flow-Irregular.php">ပုံမမှန်ဝေါ်စီးဆင်းမှု</a> ကို သုံးပါ။</dd><dt>ရေဦးတံခါး သို့မဟုတ် ပိုက်ထွက်ပေါက်</dt><dd>အပေါ်ဘက်နှင့် အောက်ဘက် ရေမြင့်ကို တိုင်းတာပါ (လွတ်လပ်ဆင်းသည်ဆိုလျှင် ပိုက်ကြမ်းခင်းမြင့်)။ <a href="Orifice.php">အပေါက်စီးဆင်းမှု</a> ကို သုံးပါ။ စက်ဝိုင်းပိုက်အတွက် D&nbsp;= ပိုက်အချင်း; ထောင့်မှန်တံခါးအတွက် အကျယ် W နှင့် အမြင့် D ထည့်ပါ။</dd><dt>ဆည် သို့မဟုတ် ကန်ကို ဆိုင်းသည့်အချိန်</dt><dd>ကန်ဝ သို့မဟုတ် ဆည်ကို အောက်ဘက်ပေါက်မှ ရေချသည့်အချိန် ခန့်မှန်းရန် <a href="Orifice-Drain-Time.php">အပေါက်ရေချချိန်</a> ကို သုံးပါ — ဆည်မြောင်းသိုလှောင်ထားမှု စီမံကိန်းအတွက် အသုံးဝင်သည်။</dd><dt>နေ့တနေ့ပြင်ပစံနှုန်းများ</dt><dd>ဤနေရာတွင် အသုံးပြုသော ဝေါ်နှင့် အပေါက် စီးဆင်းမှုညီမျှချင်းများသည် ရေတာဝန်ခံများနှင့် ဆည်မြောင်းသက်ဆိုင်ရာများ ပုံမှန်လိုအပ်သော USBR <em>Water Measurement Manual</em> (တတိယ&nbsp;ထုတ်ဝေမှု) ထုံးတမ်းများနှင့် ကိုက်ညီသည်။</dd></dl>';
$ec_lang['about_body_html']='<h3>မစ်ရှင်</h3><p>HawsEDC အင်ဂျင်နီယာ ဂဏန်းတွက်စက်များသည် ကမ္ဘာတစ်ဝန်းရှိ အင်ဂျင်နီယာများနှင့် နေ့တနေ့ပြင်ပကွင်းဆင်းသူများကို ဝန်ဆောင်မှုပေးရန်ရှိသည် — အထူးသဖြင့် ရေအသုံးအနှုန်းနည်းသော၊ အရင်းအမြစ်ကန့်သတ်ထားသော သို့မဟုတ် ဝန်ဆောင်မှုမလုံလောက်သောဒေသများတွင် အလုပ်လုပ်သူများအတွက်ဖြစ်သည်။ ဤကိရိယာများသည် ကျယ်ပြန့်သော လူသားအကျိုးပြုတာဝန်၏ အစိတ်အပိုင်းတစ်ခုဖြစ်သည်: လူတိုင်းကို တတ်နိုင်သမျှ လက်တွေ့ကျကျနှင့် ထိရောက်စွာ ပြောကြားရန် — သူတို့ကို ထာဝရချစ်ကြည်နှစ်သက်ကြောင်းနှင့် တန်ဖိုးထားကြောင်း၊ ကြောက်ရွံ့ဖွယ်ဘာမျှမရှိကြောင်းနှင့် သူတို့သည် အရာအားလုံးကို ပျက်စီးစေမည်မဟုတ်ကြောင်း ပြောကြားရန်ဖြစ်သည်။</p><p>ဂဏန်းတွက်စက်များသည် ယာဉ်ဖြစ်သည်။ ဦးတည်ရာသည် ဝေဒနာမဲ့ကမ္ဘာဖြစ်သည်။</p><h3>Open Source လိုင်စင်</h3><p>ကုဒ်အားလုံးကို <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 သို့မဟုတ် နောက်ပိုင်း</a> အောက်တွင် ထုတ်ပြန်ထားသည် — လွတ်လပ်ခွင့်အဓိပ္ပာယ်ဖြင့် လွတ်လပ်သည်။ တူညီသောစည်းမျဉ်းများအောက်တွင် ကုဒ်ကို အသုံးပြု၊ လေ့လာ၊ ပြောင်းလဲ နှင့် ဖြန့်ဝေနိုင်သည်။</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>Source Code</h3><p>ပြည့်စုံသော source code ကို Bitbucket တွင် အများပြည်သူ ရနိုင်သည်:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>ကုဒ်ကို ကြည့်ရှု၊ ပြဿနာများ တင်ပြ၊ သို့မဟုတ် repository ကို fork ပြုလုပ်နိုင်သည်။</p><h3>ပါဝင်ကမ်းလှမ်းခြင်း</h3><p>Pull requests ကြိုဆိုသည်။ ပါဝင်ကမ်းလှမ်းနည်းများ:</p><ul><li><strong>ဘာသာပြန်ဆိုခြင်း</strong> — ဘာသာစကားတစ်ခုကို တိုးတက်စေ သို့မဟုတ် အသစ်ထည့်ပါ။ သက်ဆိုင်ရာ <code>lib/lang.ec.??.php</code> ဖိုင်ပြောင်းလဲမှုများနှင့်အတူ pull request ဖွင့်ပါ။</li><li><strong>Bug reports</strong> — မည်သည့် ဂဏန်းတွက်စက်စာမျက်နှာတွင်မဆို တုံ့ပြန်ချက်ဖောင်ကို သုံးပါ၊ သို့မဟုတ် Bitbucket တွင် ပြဿနာတင်ပြပါ။</li><li><strong>ဂဏန်းတွက်စက်အသစ်များ</strong> — ကွင်းဆင်းသူများနှင့် ဆည်မြောင်းကျွမ်းကျင်သူများကို ဝန်ဆောင်မှုပေးသော ဟိုက်ဒရောလစ် အင်ဂျင်နီယာ ကိရိယာများအတွက် မြင်ကွင်းများကို အထူးကြိုဆိုသည်။ repository ထဲရှိ developer လမ်းညွှန် <code>CLAUDE.md</code> ကို ကြည့်ပါ။</li><li><strong>Hosting</strong> — ချိတ်ဆက်မှုကန့်သတ်ထားသောဒေသအတွက် ဤဂဏန်းတွက်စက်များကို mirror ပြုလုပ်နိုင်ပါက ကျေးဇူးပြု၍ ဆက်သွယ်ပါ။</li></ul><h3>အင်တာနက်မဲ့ အသုံးပြုခြင်း</h3><p>ဤဂဏန်းတွက်စက်များသည် Progressive Web App (PWA) အဖြစ် လုပ်ဆောင်သည်။ အင်တာနက်ချိတ်ဆက်ထားစဉ် ဂဏန်းတွက်စက် မည်သည့်စာမျက်နှာကိုမဆို ဝင်ရောက်ကြည့်ရှုပါ၊ သင့်ဘရောင်ဇာသည် ဂဏန်းတွက်စက်အားလုံးကို အလိုအလျောက် သိမ်းဆည်းမည်ဖြစ်သည်။ ထိုနောက် ဂဏန်းတွက်စက်အားလုံးသည် အင်တာနက်မဲ့ အသုံးပြုနိုင်သည် — အင်တာနက်မလိုအပ်ပါ။</p><p>Android သို့မဟုတ် iOS တွင် EngCalcs ကို သင့်စက်ပစ္စည်းတွင် အက်ပ်တစ်ခုအဖြစ် ထည့်သွင်းရန် ဘရောင်ဇာ၏ "ပင်မမျက်နှာပြင်တွင် ထည့်ပါ" ရွေးချယ်မှုကို အသုံးပြုပါ။ ကွန်ပျူတာတွင် ဘရောင်ဇာ၏ လိပ်စာဘားတွင် ထည့်သွင်းရေး အိုင်ကွန်ကို ရှာဖွေပါ။</p><p>တစ်ကြိမ်သုံးအတွက် ဂဏန်းတွက်စက်တစ်ခုချင်းစီကို ဘရောင်ဇာ၏ "အမည်ဖြင့် သိမ်းဆည်းပါ&hellip;" မီနူးကို အသုံးပြု၍ သိမ်းဆည်းနိုင်သည်။</p><h3>ဆက်သွယ်ရန်</h3><p>Tom Haws — ဟိုက်ဒရောလစ် အင်ဂျင်နီယာနှင့် ဤဂဏန်းတွက်စက်များ၏ ရေးသားသူ။<br />မည်သည့် ဂဏန်းတွက်စက်စာမျက်နှာတွင်မဆို တုံ့ပြန်ချက်ဖောင်ကို သုံးပါ သို့မဟုတ် <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> တွင် source code ကို ဝင်ရောက်ကြည့်ရှုပါ။</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Rock Chute ဒီဇိုင်း (Robinson)';
$ec_lang['rc_main_title']='အခမဲ့ အွန်လိုင်း Rock Chute ဒီဇိုင်း ဂဏန်းတွက်စက် — Robinson (1998)';
$ec_lang['rc_main_desc']='Rock Chute Riprap အရွယ်ဆုံးဖြတ်ခြင်း &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='ကြောင်းကြမ်းခင်းစောင်းနှုန်း, S<sub>0</sub>';
$ec_lang['rc_qt']='ယူနစ်စီးဆင်းမှုစုစုပေါင်း, q<sub>t</sub> <span title="ကြောင်းဝင်ပေါက်တွင် အကျယ်တစ်ယူနစ်လျှင် စီးဆင်းမှု။ ကြမ်းခင်းအကျယ် B ရှိ မြောင်းတစ်ခုနှင့် စီးဆင်းမှုစုစုပေါင်း Q အတွက် q_t = Q / B ကို အသုံးပြုပါ။" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Riprap အပေါက်နှုန်း, n<sub>p</sub>';
$ec_lang['rc_sg']='ကျောက်အလေးချိန်နှုန်း, sg <span title="ကျောက်ကြမ်း သို့မဟုတ် basalt ပုံမှန် ≈ 2.65။ Robinson စစ်မှန်သောအပိုင်းအခြား: 2.54 မှ 2.82 ။" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='အဆင့်ခွဲ SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="အဆင့်ခွဲ စံသွေဖည်မှု။ တူညီသောကျောက် ≈ 1.25။ Robinson စစ်မှန်သောအပိုင်းအခြား: 1.15 မှ 1.47 ။" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='ဝင်ပေါက်မြောင်းရှိ ပုံမှန်နက်မှုပမာဏ, y<sub>n</sub> <span title="ရေဝပ်မှု (Hp > yn) ကောင်းသည် — အပေါ်စီး၌ ရေကြောင်းနွမ်းမှုကို လျှော့ချသည်။ (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='လိုအပ်သော ကျောက်အလယ်တန်းအရွယ်, D<sub>50</sub> <span title="ညီမျှချင်း 1 (S0 &lt; 0.10) သို့မဟုတ် ညီမျှချင်း 2 (0.10-0.40)။ စစ်မှန်: D50 15-278 mm, S0 0.02-0.40။ အပိုင်းအခြားအပြင်: ခန့်မှန်းတန်ဖိုး။" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='အသုံးပြုသောညီမျှချင်း';
$ec_lang['rc_sg_check']='အလေးချိန်နှုန်း စစ်ဆေးခြင်း';
$ec_lang['rc_SD_check']='အဆင့်ခွဲ SD စစ်ဆေးခြင်း';
$ec_lang['rc_sg_ok']   ='sg စစ်မှန်သောအပိုင်းအခြားတွင်ရှိ (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='သတိပေးချက်: sg < 2.54 — Robinson အပိုင်းအခြားအောက်';
$ec_lang['rc_sg_high'] ='သတိပေးချက်: sg > 2.82 — Robinson အပိုင်းအခြားအထက်';
$ec_lang['rc_SD_ok']   ='SD စစ်မှန်သောအပိုင်းအခြားတွင်ရှိ (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='သတိပေးချက်: SD < 1.15 — Robinson အပိုင်းအခြားအောက်';
$ec_lang['rc_SD_high'] ='သတိပေးချက်: SD > 1.47 — Robinson အပိုင်းအခြားအထက်';
$ec_lang['rc_layer']='ကျောက်အလွှာထူမှုပမာဏ (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='ထိပ်ဆုံး ကွေးမျဉ်းအချင်း (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='ထိပ်ဆုံး ကွေးမျဉ်းအား လျားအလျားပမာဏ';
$ec_lang['rc_apron_length']='ထွက်ပေါက် apron အလျားပမာဏ (15 &times; D<sub>50</sub>) <span title="ကြောင်းကျောက်ကို ဖွဲ့စည်းပုံဆိုင်ရာ ထောက်ပံ့မှုအတွက် လိုအပ်သည်။ &quot;ထွက်ပေါက်လမ်းကြောင်းနှင့် အောက်ဘက်မြောင်းတုတ်ခုခံမှုကြောင့် ဖြစ်ပေါ်သည့် အနည်းဆုံး tailwater သည် ထွက်ပေါက်ရောက်ရှိမှုရှိ riprap ၏ တည်ငြိမ်မှုကို သေချာစေရန် လုံလောက်သည်။&quot; (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='ကြောင်းတွင်း Manning ကြမ်းတမ်းမှုနှုန်း, n';
$ec_lang['rc_Vm']='ကျောက်အလွှာတွင်းရှိ အလျင်, V<sub>m</sub> <span title="qt ၏ ကျောက်အပေါက်များမှ စီးဆင်းသော အပိုင်းအဝေး။ ကျန်ရှိ qs သည် မျက်နှာပြင်ပေါ် စီးဆင်းသည်။ မှုန့်ကျောက်ကြမ်းအတွက် np မူလတန်ဖိုး = 0.45 ။" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='အလွှာတွင်း ယူနစ်စီးဆင်းမှု, q<sub>m</sub>';
$ec_lang['rc_qs']='မျက်နှာပြင် ယူနစ်စီးဆင်းမှု, q<sub>s</sub> (q<sub>t</sub> &minus; q<sub>m</sub>)';
$ec_lang['rc_d']='riprap မျက်နှာပြင်အပေါ် ရေနက်မှုပမာဏ, d';
$ec_lang['rc_Hp']='ဝင်ပေါက် weir ခေါင်းပမာဏ, H<sub>p</sub> <span title="ရေဝပ်မှု (Hp > yn) ကောင်းသည် — အပေါ်စီး၌ ရေကြောင်းနွမ်းမှုကို လျှော့ချသည်။ (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='ဝင်ပေါက်ရေဝပ်မှု စစ်ဆေးခြင်း';
$ec_lang['rc_pond_ok']   ='Hp > yn — အပေါ်စီးတွင် ရေဝပ်မှုရှိ ✓';
$ec_lang['rc_pond_warn'] ='⚠ Hp ≤ yn — ရေဝပ်မှုမရှိ — ဝင်ပေါက်တွင် ရေကြောင်းနွမ်းမှု စစ်ဆေးပါ';
$ec_lang['rc_eq1']='Eq. 1 (S0 < 0.10) — ညင်သာသောစောင်း';
$ec_lang['rc_eq2']='Eq. 2 (0.10 ≤ S0 ≤ 0.40) — ကြမ်းသောစောင်း';
$ec_lang['rc_eq_warn_low']='သတိပေးချက်: S0 < 0.02 — Robinson စစ်ကြည့်သောအပိုင်းအခြားအောက်';
$ec_lang['rc_eq_warn_high']='သတိပေးချက်: S0 > 0.40 — Robinson စစ်ကြည့်သောအပိုင်းအခြားအထက်';
$ec_lang['rc_notes_1_term']='ကျောက်အရွယ်ဆုံးဖြတ်ညီမျှချင်းများ';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) တို့သည် ကြောင်းစောင်းနှင့် ယူနစ်စီးဆင်းမှုကို အခြေခံ၍ D<sub>50</sub> riprap အလယ်တန်းအရွယ်အတွက် ကိုင်ကွယ်ပြုညီမျှချင်းနှစ်ခုကို ရေးဆွဲခဲ့သည်။ ညီမျှချင်း 1 သည် ညင်သာသောစောင်းများအတွက် (S<sub>0</sub> &lt; 0.10) ကျင့်သုံးသည်; ညီမျှချင်း 2 သည် ကြမ်းသောစောင်းများအတွက် (0.10 &le; S<sub>0</sub> &le; 0.40) ကျင့်သုံးသည်။ ညီမျှချင်းနှစ်ခုစလုံးသည် q<sub>t</sub> ကို m&sup2;/s ဖြင့် လိုအပ်ပြီး D<sub>50</sub> ကို mm ဖြင့် ပြန်ပေးသည်။ စစ်ကြည့်ပြီးသောအပိုင်းအခြားမှာ 0.02 &le; S<sub>0</sub> &le; 0.40 ဖြစ်သည်။';
$ec_lang['rc_notes_2_term']='ယူနစ်စီးဆင်းမှု';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> သည် ကြောင်းထိပ်ဆုံးတွင် ယူနစ်စီးဆင်းမှုစုစုပေါင်း (အကျယ်တစ်ယူနစ်လျှင် စီးဆင်းမှုစုစုပေါင်း) ဖြစ်သည်။ ကြမ်းခင်းအကျယ် B ဖြင့် စီးဆင်းမှုစုစုပေါင်း Q ရှိသော မြောင်းတစ်ခုအတွက် q<sub>t</sub> &asymp; Q / B ဟု ခန့်မှန်းပါ၊ သို့မဟုတ် ကြောင်းဝင်ပေါက်ရှိ အရေးကြီးသောနက်မှုပမာဏအခြေအနေမှ တွက်ချက်ပါ။';
$ec_lang['rc_notes_3_term']='ကျောက်အလွှာတွင်း စီးဆင်းမှု';
$ec_lang['rc_notes_3_def']='စီးဆင်းမှုစုစုပေါင်း၏ တစ်စိတ်တစ်ပိုင်းသည် ကျောက် riprap အပေါက်များမှ စီးဆင်းသည် (အလွှာစီးဆင်းမှု q<sub>m</sub>); ကျန်ရှိသည်မှာ ကျောက်မျက်နှာပြင်ပေါ် စီးဆင်းသည် (q<sub>s</sub> = q<sub>t</sub> &minus; q<sub>m</sub>)။ ရေနက်မှု d ကို ကြောင်းကြမ်းတမ်းမှုနှုန်း n ကို အသုံးပြု၍ မျက်နှာပြင်စီးဆင်းမှု q<sub>s</sub> အပေါ် ကျင့်သုံးသည့် Manning&rsquo;s ညီမျှချင်းမှ တွက်ချက်သည်။ မှုန့်ကျောက်ကြမ်းအတွက် မူလ အပေါက်နှုန်း n<sub>p</sub> = 0.45 ပုံမှန်ဖြစ်သည်။';
$ec_lang['rc_notes_5_term']='စစ်မှန်သော ကျောက်အရွယ်အပိုင်းအခြား';
$ec_lang['rc_notes_5_def']='ညီမျှချင်းများကို D<sub>50</sub> အပိုင်းအခြား 15&nbsp;mm မှ 278&nbsp;mm ကို အသုံးပြုကာ ဖွံ့ဖြိုးတိုးတက်ခဲ့သည်။ ဤအပိုင်းအခြားအပြင်ရှိ ရလဒ်များသည် ခန့်မှန်းတန်ဖိုးများဖြစ်ပြီး ထပ်ဆောင်း အင်ဂျင်နီယာဆုံးဖြတ်ချက်ဖြင့် အသုံးပြုသင့်သည်။';
$ec_lang['rc_notes_6_term']='ထွက်ပေါက် Apron အမြင့်';
$ec_lang['rc_notes_6_def']='ထွက်ပေါက်ရောက်ရှိမှုရှိ riprap အထိပ်၏ အမြင့်သည် အောက်ဘက်မြောင်းကြမ်းခင်းအမြင့်တွင် သို့မဟုတ် အောက်တွင် ရှိသင့်သည်။ ပိုမိုမြင့်ပါက ထွက်ပေါက်ကျောက်သည် မတည်ငြိမ်ဖြစ်မည်။';
$ec_lang['rc_notes_7_term']='ဝင်ပေါက်ရေဝပ်မှု စစ်ဆေးခြင်း';
$ec_lang['rc_notes_7_def']='ဝင်ပေါက်မြောင်းရှိ ပုံမှန်နက်မှုပမာဏသည် q<sub>t</sub> ကိုဖြတ်သန်းရန် လိုအပ်သော weir ခေါင်း (H<sub>p</sub>) ထက် နည်းသောအခါ ဝင်ပေါက် apron အပေါ်စီး၌ စီးဆင်းမှုကန့်သတ်မှု သို့မဟုတ် ရေဝပ်မှုဖြစ်ပေါ်သည်။ ဤသည်ယေဘူယျအားဖြင့် လက်ခံနိုင်သည် — ရေဝပ်မှုသည် အလျင်ကို လျှော့ချပြီး အပေါ်စီးရေကြောင်းနွမ်းမှုကို ကာကွယ်သည်။ စစ်ဆေးရန်: ပေးထားသော q<sub>t</sub> နှင့် crest အကျယ်အတွက် H<sub>p</sub> ကိုရှာဖွေရန် weir flow ဂဏန်းတွက်စက်ကို အသုံးပြုပြီး ဝင်ပေါက်မြောင်းပုံမှန်နက်မှုပမာဏနှင့် နှိုင်းယှဉ်ပါ။ H<sub>p</sub> သည် ပုံမှန်နက်မှုပမာဏကျော်ပါက ရေဝပ်မှုဖြစ်ပေါ်မည်။';
$ec_lang['rc_notes_4_term']='ကိုးကားချက်';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://doi.org/10.13031/2013.17230">rock chutes ဒီဇိုင်းဆွဲခြင်း</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. USDA ARS သည် တူညီသောနည်းလမ်းကို အခြေခံ၍ <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel စာရွက်</a> ကိုလည်း ထုတ်ပြန်သည်။';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'ဖီလ်တာ';
$ec_lang['rc_sketch_top_crest_curve'] = 'ထိပ်ဆုံးကောက်ကွေး';
$ec_lang['rc_sketch_outlet_apron']    = 'ထွက်ပေါက်ကြိုပြင်';
$ec_lang['rc_sketch_radius']          = 'အချင်းဝက်';
