<?php

// All missing text declarations will fall back to English.

// واحدها (ترتیب الفبایی)
// برای انتخاب واحد در ماشین‌حساب‌ها لازم است
$ec_lang['u_depthFrac']='کسر';
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/sec";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']='% rise/run';
$ec_lang['u_grade']="rise/run";
$ec_lang['u_in2']="sq. in.";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="sec";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']="kW";
$ec_lang['u_mw']="MW";
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']="hp";

// متن صفحه
// به ترتیب صفحه برای آسان‌ترین نگهداری
// منو و کلی
$ec_lang['menu_brand']='ماشین‌حساب‌های HawsEDC';
$ec_lang['menu_main_list']='فهرست ماشین‌حساب‌ها';
$ec_lang['menu_main_hydraulics']='هیدرولیک';
$ec_lang['menu_main_language']='زبان';
$ec_lang['menu_more']='بیشتر';
$ec_lang['template_welcome']='&gt;&gt; ترس‌هایت را پشت در بگذار؛ اینجا زبان محبت است. تو همه چیز را خراب نمی‌کنی. از <a target="_blank" href="https://hawsedc.com/download.php">ابزارهای رایگان HawsEDC AutoCAD</a> هم لذت ببر. &lt;&lt;';
$ec_lang['template_translation_help']='آیا ایده‌ای عالی برای افزودن یک ماشین‌حساب دارید؟ آیا می‌توانید در بهبود ترجمه‌ها، برنامه‌نویسی، یا میزبانی این ماشین‌حساب‌ها کمک کنید؟  ';
$ec_lang['template_feedback']='لطفاً نظرات ارزشمند خود را برای پیشنهاد یا تعریف با ما در میان بگذارید. آیا این ماشین‌حساب رایگان در همه جهات انتظارات شما را برآورده کرد؟';
$ec_lang['template_printable_title']='عنوان قابل چاپ';
$ec_lang['template_printable_subtitle']='زیرعنوان قابل چاپ';
$ec_lang['index_title']='ماشین‌حساب‌های رایگان مهندسی آنلاین';
$ec_lang['calc_set_units']='تنظیم واحدها:';
$ec_lang['points_data_help']='(یا با استفاده از ناحیه داده کپی/پیست کنید)';
$ec_lang['points_data_title']='داده‌های نقاط<br />(جداشده با کاما یا تب)';
$ec_lang['points_data_copy']='کپی';
$ec_lang['points_data_paste']='پیست';
$ec_lang['calc_inputs']='ورودی‌ها';
$ec_lang['calc_results']='نتایج';
$ec_lang['view_hide_line']='[پنهان کردن این خط]';
$ec_lang['view_printable']='نسخه قابل چاپ (برای بازگشت بارگذاری مجدد کنید)';
$ec_lang['ec_name_label']='این محاسبه را ذخیره کنید:';
$ec_lang['ec_name_placeholder']='نام';
$ec_lang['ec_name_hint']='این داده‌های ورودی را به URL ذخیره می‌کند برای نشانک‌گذاری، بازیابی سابقه و اشتراک';
$ec_lang['ec_name_invalid']='فقط از حروف، ارقام، فاصله، – _ . استفاده کنید';
// Darcy-Weisbach. برای متن مفقود به mphl_ مراجعه کنید.
$ec_lang['dw_main_menu']='افت فشار لوله Darcy-Weisbach';
$ec_lang['dw_main_title']='ماشین‌حساب رایگان آنلاین افت فشار لوله Darcy-Weisbach';
$ec_lang['dw_main_desc']='افت فشار لوله Darcy-Weisbach برای قطر، زبری و دبی مشخص';
$ec_lang['dw_roughness']='زبری مطلق Darcy-Weisbach، e';
$ec_lang['dw_kinematic_viscosity']='ویسکوزیته سینماتیک، ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['dw_reynolds_number']='عدد رینولدز، Re';
$ec_lang['dw_flow_regime']='رژیم جریان';
$ec_lang['dw_regime_laminar']='لامینار';
$ec_lang['dw_regime_transitional']='گذرا';
$ec_lang['dw_regime_turbulent']='آشفته';
$ec_lang['dw_friction_factor_method']='روش ضریب اصطکاک';
$ec_lang['dw_friction_factor']='ضریب اصطکاک، f';
// Hazen-Williams. برای متن مفقود به mphl_ مراجعه کنید.
$ec_lang['hw_main_menu']='افت فشار لوله Hazen-Williams';
$ec_lang['hw_main_title']='ماشین‌حساب رایگان آنلاین افت فشار لوله Hazen-Williams';
$ec_lang['hw_main_desc']='افت فشار لوله Hazen-Williams برای قطر، زبری و دبی مشخص';
$ec_lang['hw_hgl_1']='خط فشار هیدرولیکی پایین‌دست (HGL)';
$ec_lang['hw_hgl_2']='خط فشار هیدرولیکی بالادست (HGL)';
$ec_lang['hw_roughness']='ضریب Hazen-Williams، C';
// Manning Irregular
$ec_lang['mi_menu']='کانال نامنظم Manning';
$ec_lang['mi_main_title']='ماشین‌حساب رایگان آنلاین کانال نامنظم Manning';
$ec_lang['mi_main_desc']='ماشین‌حساب جریان یکنواخت کانال نامنظم با فرمول Manning';
$ec_lang['mi_waterSurfaceElevation']='ارتفاع سطح آب';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='نقاط مقطع عرضی';
$ec_lang['mi_groupPoint']='نقطه';
$ec_lang['mi_groupSegment']='بخش';
$ec_lang['mi_groupRegion']='ناحیه';
$ec_lang['mi_station']='ایستگاه';
$ec_lang['mi_elevation']='ارتفاع';
$ec_lang['mi_d50in']='اندازه<br />متوسط<br />سنگ<br />پوشش';
$ec_lang['mi_n']='n<br />برای<br />بخش';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />مرز<br />ناحیه<br />(کناره)';
$ec_lang['mi_tau']='برش<br />کف<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />مرکب';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='یادداشت‌ها';
$ec_lang['mi_notes_1_term']='n مرکب';
$ec_lang['mi_notes_1_def']='این ماشین‌حساب برای محاسبه n مرکب ناحیه از راهنمای مرجع HEC-RAS پیروی می‌کند و از معادله 6-17 (نه 6-18) Chow 1959، صفحه 136 استفاده می‌کند.';
$ec_lang['mi_notes_2_term']='پوشش سنگی';
$ec_lang['mi_notes_2_def']='برای طراحی پوشش سنگی از ماشین‌حساب کانال ذوزنقه‌ای Manning استفاده کنید. این ماشین‌حساب بیشتر برای مقاطع طبیعی مناسب است.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='جریان لوله Manning';
$ec_lang['mpf_main_title']='ماشین‌حساب رایگان آنلاین جریان لوله Manning';
$ec_lang['mpf_main_desc']='جریان یکنواخت لوله با فرمول Manning برای شیب و عمق مشخص';
$ec_lang['mpf_spreadheet_notice']='نسخه صفحه‌گسترده این ماشین‌حساب را ببینید';
$ec_lang['mpf_pipe_diameter']='قطر لوله، d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='زبری Manning، n';
$ec_lang['mpf_friction_slope']='شیب فشار (احتمالاً <a target="_blank" href="../pressureslope.php">?</a> برابر شیب لوله)، S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='نسبت عمق جریان، y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(به یادداشت‌ها مراجعه کنید)';
$ec_lang['mpf_flow']='دبی، Q';
$ec_lang['mpf_velocity']='سرعت، v';
$ec_lang['mpf_velocity_head']='هد سرعت، h<sub>v</sub>';
$ec_lang['mpf_flow_area']='سطح مقطع جریان، a';
$ec_lang['mpf_pipe_area']='سطح مقطع لوله، a0';
$ec_lang['mpf_area_ratio']='نسبت سطح، a/a0';
$ec_lang['mpf_wetted_perimeter']='محیط تر، P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='شعاع هیدرولیکی، R<sub>h</sub>';
$ec_lang['mpf_top_width']='عرض سطح آب، T';
$ec_lang['mpf_froude_number']='عدد فرود، F';
$ec_lang['mpf_shear_stress']='تنش برشی متوسط (نیروی کششی)، tau';
$ec_lang['mpf_full_flow']='دبی کامل، Q0';
$ec_lang['mpf_full_flow_ratio']='نسبت به دبی کامل، Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>این جریان و عمق داخل یک لوله <em>بی‌نهایت بلند</em> است.</dt><dd>برای هدایت جریان به داخل لوله ممکن است به عمق هد آب بالاتری نیاز باشد. حداقل ۱.۵ برابر هد سرعت را برای به‌دست آوردن عمق هد آب اضافه کنید یا <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">آموزش ۲ دقیقه‌ای من</a> را برای محاسبات استاندارد هد آب کالورت با HY-8 ببینید.</dd>';
$ec_lang['mpf_solve_for_dd0']='محاسبه y/d<sub>0</sub> برای Q مشخص';
$ec_lang['mpf_solve_desc']='با استفاده از D<sub>0</sub>، n و S<sub>0</sub> از فرم ماشین‌حساب، کمترین مقدار y/d<sub>0</sub> را برای Q مشخص پیدا می‌کند.';
$ec_lang['mpf_solve_button']='محاسبه';
// Manning Pipe Head Loss. برای متن مفقود به mpf_ مراجعه کنید.
$ec_lang['mphl_main_menu']='افت هد لوله Manning';
$ec_lang['mphl_main_title']='ماشین‌حساب رایگان آنلاین افت هد لوله Manning';
$ec_lang['mphl_main_desc']='افت هد با فرمول Manning برای جریان کامل مشخص';
$ec_lang['mphl_pipe_length']='طول لوله، L';
$ec_lang['mphl_area']='سطح مقطع، A';
$ec_lang['mphl_total_junction_k']='ضریب کل افت اتصال ترکیبی، k';
$ec_lang['mphl_friction_slope']='شیب اصطکاک';
$ec_lang['mphl_friction_loss']='افت اصطکاک، H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='افت اتصال، H<sub>m</sub>';
$ec_lang['mphl_total_loss']='افت کل، H<sub>l</sub>';
$ec_lang['mphl_egl_1']='خط انرژی پایین‌دست (EGL)';
$ec_lang['mphl_egl_2']='خط انرژی بالادست (EGL)';
$ec_lang['mphl_hgl_2']='خط فشار هیدرولیکی بالادست در لوله ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>برای شرایط ورودی باز (کالورت)، بررسی شرایط کنترل ورودی ضروری است.</dt><dd>۱. HGL بالادست نمی‌تواند پایین‌تر از ارتفاع جریان عمق نرمال بالادست باشد (یا پایین‌تر از لوله!).</dd><dd>۲. هد آب کالورت بهتر است با EGL بالادست نشان داده شود نه HGL بالادست.</dd><dd>۳. برای محاسبات ساده استاندارد هد آب کالورت با HY-8 <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">آموزش ۲ دقیقه‌ای من</a> را ببینید.</dd>';
// Manning Trapezoid. برای متن مفقود به mpf_ مراجعه کنید.
$ec_lang['mtc_menu']='کانال ذوزنقه‌ای Manning';
$ec_lang['mtc_main_title']='ماشین‌حساب رایگان آنلاین کانال ذوزنقه‌ای Manning';
$ec_lang['mtc_main_desc']='جریان یکنواخت کانال ذوزنقه‌ای با فرمول Manning برای شیب و عمق مشخص';
$ec_lang['mtc_bottom_width']='عرض کف، b';
$ec_lang['mtc_side_slope_1']='شیب جانبی ۱ (افقی/عمودی)';
$ec_lang['mtc_side_slope_2']='شیب جانبی ۲ (افقی/عمودی)';
$ec_lang['mtc_channel_slope']='شیب کانال، S';
$ec_lang['mtc_flow_depth']='عمق جریان، y';
$ec_lang['mtc_bend_angle']='زاویه انحنا <a target="_blank" href="riprap-bend-angle.png" title="برای مشاهده تصویر کلیک کنید">?</a> (برای اندازه‌بندی ریپ‌رپ)';
$ec_lang['mtc_sgrock']='چگالی نسبی سنگ (2.65)';
$ec_lang['mtc_d50_in']='اندازه طراحی سنگ، D50';
$ec_lang['mtc_n_strickler']='n برای اندازه طراحی سنگ بر اساس Strickler';
$ec_lang['mtc_n_blodgett']='n برای اندازه طراحی سنگ بر اساس Blodgett';
$ec_lang['mtc_n_bathurst']='n برای اندازه طراحی سنگ بر اساس Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett در برابر Bathurst';
$ec_lang['mtc_d50_bottom']='اندازه سنگ زاویه‌دار مورد نیاز برای کف، D50 (Isbash & MC) <span title="بر اساس Isbash (1936) و شهرستان ماریکوپا، آریزونا، آمریکا." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='اندازه سنگ زاویه‌دار مورد نیاز برای شیب جانبی ۱، D50 (Isbash & MC) <span title="بر اساس Isbash (1936) و شهرستان ماریکوپا، آریزونا، آمریکا." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='اندازه سنگ زاویه‌دار مورد نیاز برای شیب جانبی ۲، D50 (Isbash & MC) <span title="بر اساس Isbash (1936) و شهرستان ماریکوپا، آریزونا، آمریکا." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='اندازه سنگ زاویه‌دار مورد نیاز، D50 (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='اندازه سنگ زاویه‌دار مورد نیاز، D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>تکرار خودکار طراحی اندازه سنگ و زبری</dt><dd>یک دکمه رادیویی زبری (BB توصیه می‌شود) و یک دکمه رادیویی اندازه طراحی سنگ (Isbash توصیه می‌شود) انتخاب کنید. عمق و ضریب ایمنی اندازه سنگ را برای دستیابی به جریان مطلوب با اندازه سنگ مناسب تنظیم دقیق کنید. هر بار که مقدار ورودی تغییر می‌کند، چرخه تکرار زیر اتفاق می‌افتد: ۱. زبری از اندازه طراحی سنگ محاسبه می‌شود. ۲. محاسبه زبری درخواستی به زبری ورودی کپی می‌شود. ۳. جریان کانال و اندازه سنگ مورد نیاز محاسبه می‌شود. ۴. اندازه طراحی سنگ تنظیم می‌شود. ۵. تکرار تا زمانی که خطا در اندازه طراحی سنگ بسیار کوچک شود.</dd><dt>ماشین‌حساب پایه (بدون تکرار)</dt><dd>مقدار زبری دلخواه خود را وارد کنید. ناحیه ورودی اندازه طراحی سنگ را نادیده بگیرید.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='آبشار سنگی Robinson';
$ec_lang['rrc_main_desc']='صفحه‌گسترده طراحی آبشار سنگی Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='جریان سرریز ساده';
$ec_lang['ws_main_title']='ماشین‌حساب رایگان آنلاین جریان سرریز تاج پهن ساده';
$ec_lang['ws_main_desc']='ماشین‌حساب جریان سرریز تاج پهن ساده';
$ec_lang['ws_weirLength']='طول سرریز، l';
$ec_lang['ws_headWaterHeight']='ارتفاع هد آب، h';
$ec_lang['ws_weirCoefficient']='ضریب سرریز، Cw';
$ec_lang['ws_notes_heading']='یادداشت‌ها';
$ec_lang['ws_notes_we_term']='معادله سرریز';
// Weir Flow Irregular. برای متن مفقود به ws_ مراجعه کنید.
$ec_lang['wi_menu']='جریان سرریز نامنظم';
$ec_lang['wi_main_title']='ماشین‌حساب رایگان آنلاین جریان سرریز نامنظم بخش‌بندی‌شده با عمق متغیر';
$ec_lang['wi_main_desc']='ماشین‌حساب جریان سرریز نامنظم';
$ec_lang['wi_headWaterelevation']='ارتفاع هد آب';
$ec_lang['wi_weirPoints']='نقاط سرریز';
$ec_lang['wi_station']='ایستگاه<br />(فاصله)';
$ec_lang['wi_elevation']='ارتفاع';
$ec_lang['wi_pondingHeight']='ارتفاع آب پشت سرریز';
$ec_lang['wi_incrementalFlow']='دبی افزایشی';
$ec_lang['wi_cumulativeFlow']='دبی تجمعی';
$ec_lang['wi_save_and_calculate']='ذخیره و محاسبه';
$ec_lang['wi_notes_we_term']='معادله سرریز';
$ec_lang['wi_notes_we_def']='q = if (length = 0) then 0 else if (slope=0) then cw*length*d<sub>0</sub><sup>1.5</sup> else cw/(2.5*slope) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) where d<sub>1</sub> and d<sub>0</sub> are always positive or zero';
// Orifice Flow
$ec_lang['or_main_menu']='جریان دریچه';
$ec_lang['or_main_title']='ماشین‌حساب رایگان آنلاین جریان دریچه';
$ec_lang['or_main_desc']='جریان دریچه — آزاد یا مستغرق';
$ec_lang['or_shape']='شکل دهانه';
$ec_lang['or_shape_circular']='دایره‌ای';
$ec_lang['or_shape_rectangular']='مستطیلی';
$ec_lang['or_diameter']='قطر یا ارتفاع، D <span title="Diameter for circular; height for rectangular" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_width']='عرض، W <span title="Rectangular openings only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_invert']='ارتفاع کف دهانه <span title="Bottom of opening" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_hwe']='ارتفاع هد آب بالادست';
$ec_lang['or_twe']='ارتفاع هد آب پایین‌دست';
$ec_lang['or_cd']='ضریب تخلیه، C<sub>d</sub>';
$ec_lang['or_centroid_elev']='ارتفاع مرکز ثقل';
$ec_lang['or_head']='هد مؤثر، h';
$ec_lang['or_area']='سطح دهانه، A';
$ec_lang['or_flow']='دبی، Q';
$ec_lang['or_velocity']='سرعت، v';
$ec_lang['or_regime']='بررسی رژیم دریچه';
$ec_lang['or_regime_valid']='خروج آزاد — رژیم دریچه معتبر است ✓';
$ec_lang['or_regime_submerged']='دریچه مستغرق (TWE بالاتر از کف) — معتبر است ✓';
$ec_lang['or_regime_warn']='هشدار: هد آب پایین‌تر از تاج — رژیم دریچه نیست';
$ec_lang['or_regime_twe_above_hwe']='هشدار: هد آب پایین‌دست (TWE) بالاتر از هد آب بالادست (HWE) — ورودی‌ها را بررسی کنید';
$ec_lang['or_notes_1_term']='معادله دریچه';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). برای خروج آزاد: h = HWE &minus; مرکز ثقل. برای جریان مستغرق (TWE بالاتر از کف): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='رژیم دریچه';
$ec_lang['or_notes_2_def']='معادلات جریان دریچه زمانی اعمال می‌شوند که سطح هد آب بالاتر از تاج (بالای) دهانه باشد. وقتی هد آب پایین‌تر از تاج است، به جای آن از معادله سرریز استفاده کنید.';
$ec_lang['or_notes_3_term']='ضریب تخلیه';
$ec_lang['or_notes_3_def']='C<sub>d</sub> برای دریچه‌های لبه تیز در حدود 0.60&ndash;0.65 است. ورودی‌های گرد یا داخل‌برآمده مقادیر متفاوتی دارند. برای راهنمایی به <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> یا راهنمای مرجع هیدرولیک HEC-RAS مراجعه کنید.';
$ec_lang['or_notes_4_term']='استغراق';
$ec_lang['or_notes_4_def']='وقتی TWE بالاتر از کف دهانه است، این ماشین‌حساب به‌طور خودکار معادله دریچه مستغرق را با h = HWE &minus; TWE اعمال می‌کند. وقتی TWE در سطح کف یا پایین‌تر از آن باشد، خروج آزاد فرض می‌شود و h = HWE &minus; مرکز ثقل.';
// Penstock Design
$ec_lang['ps_main_menu']='طراحی لوله پنستاک';
$ec_lang['ps_main_title']='ماشین‌حساب رایگان آنلاین طراحی لوله پنستاک';
$ec_lang['ps_main_desc']='اندازه‌بندی لوله پنستاک میکرو-هیدرو — افت هد، توان و سرعت';
$ec_lang['ps_flow']='دبی، Q';
$ec_lang['ps_gross_head']='هد ناخالص، H<sub>gross</sub>';
$ec_lang['ps_diameter']='قطر لوله پنستاک، D';
$ec_lang['ps_length']='طول لوله پنستاک، L';
$ec_lang['ps_roughness']='زبری لوله، e';
$ec_lang['ps_km']='ضریب افت اتصال، k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['ps_nu']='ویسکوزیته سینماتیک، ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['ps_efficiency']='بازده نیروگاه، &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='سرعت جریان، v';
$ec_lang['ps_vel_check']='بررسی سرعت';
$ec_lang['ps_f']='ضریب اصطکاک، f';
$ec_lang['ps_hf']='افت هد اصطکاک، h<sub>f</sub>';
$ec_lang['ps_hm']='افت هد اتصال، h<sub>m</sub>';
$ec_lang['ps_hl']='افت کل پنستاک، h<sub>L</sub>';
$ec_lang['ps_hl_check']='بررسی افت هد';
$ec_lang['ps_hnet']='هد خالص، H<sub>net</sub>';
$ec_lang['ps_power']='توان خروجی، P';
$ec_lang['ps_annual_kwh']='انرژی سالانه در ظرفیت ۱۰۰٪';
$ec_lang['ps_vel_ok']='1–3 m/s — در محدوده هدف ✓';
$ec_lang['ps_vel_low']='کمتر از 1 m/s — قطر را افزایش دهید ⚠';
$ec_lang['ps_vel_high']='بیشتر از 3 m/s — قطر را کاهش دهید ⚠';
$ec_lang['ps_hl_ok']='در محدوده هدف ۱۰٪ ✓';
$ec_lang['ps_hl_warn']='از هدف ۱۰٪ بیشتر است — لوله بزرگ‌تر را در نظر بگیرید ⚠';
$ec_lang['ps_hl_bad']='از ۲۰٪ بیشتر است — لوله را مجدداً اندازه‌بندی کنید';
$ec_lang['ps_notes_1_term']='افت هد';
$ec_lang['ps_notes_1_def']='افت کل پنستاک h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>، که در آن h<sub>f</sub> = f(L/D)(v&sup2;/2g) افت اصطکاک Darcy-Weisbach است و h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g ورودی‌ها، قوس‌ها و شیرها را پوشش می‌دهد. هد خالص H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='سرعت';
$ec_lang['ps_notes_2_def']='هدف 1&ndash;3 m/s. کمتر از 1 m/s لوله را برای دبی بیش از حد بزرگ می‌کند؛ بیشتر از 3 m/s افت اصطکاک و خطر ضربه قوچ را افزایش می‌دهد.';
$ec_lang['ps_notes_3_term']='هدف افت هد';
$ec_lang['ps_notes_3_def']='افت پنستاک زیر ۱۰٪ هد ناخالص از نظر اقتصادی معمولاً مناسب است. مصالحه بهینه بین هزینه لوله و توان از‌دست‌رفته اغلب برای سایت‌های برق با ارزش بالا در حدود ۴&ndash;۶٪ قرار می‌گیرد.';
$ec_lang['ps_notes_4_term']='افت اتصالات (نقطه‌ای) k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='این افت‌ها در اتصالات لوله، ورودی‌ها، قوس‌ها و شیرها رخ می‌دهند &mdash; اصطلاح &ldquo;جزئی&rdquo; مرسوم است اما گمراه‌کننده است؛ در یک پنستاک کوتاه ممکن است برابر یا بیشتر از افت اصطکاک باشند. مقادیر معمول k: ورودی تیز 0.5، هر قوس 45&deg; از 0.2&ndash;0.3، شیر دروازه‌ای (کاملاً باز) 0.1، شیر پروانه‌ای 0.2. مجموع تمام اتصالات را برای k<sub>m</sub> کل محاسبه کنید. مقدار پیش‌فرض 1.5 یک ورودی و دو قوس را فرض می‌کند.';
$ec_lang['ps_notes_5_term']='زبری لوله e';
$ec_lang['ps_notes_5_def']='زبری مطلق معمول: فولاد (نو) 0.046&nbsp;mm، فولاد (مستعمل) 0.15&nbsp;mm، HDPE 0.003&nbsp;mm، PVC/uPVC 0.0015&nbsp;mm، بتن 0.3&ndash;3&nbsp;mm. HDPE برای پنستاک‌های کوچک میکرو-هیدرو رایج است.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='توان میکرو-هیدرو';
$ec_lang['mhp_main_title']='ماشین‌حساب رایگان آنلاین توان میکرو-هیدرو';
$ec_lang['mhp_main_desc']='ماشین‌حساب توان خروجی میکرو-هیدرو جریان‌رودی';
$ec_lang['mhp_flow']='دبی، Q';
$ec_lang['mhp_gross_head']='هد ناخالص (اختلاف ارتفاع)، H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='افت هد لوله پنستاک، h<sub>L</sub>';
$ec_lang['mhp_efficiency']='بازده نیروگاه، &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='هد خالص، H<sub>net</sub>';
$ec_lang['mhp_power']='توان خروجی، P';
$ec_lang['mhp_annual_kwh']='انرژی سالانه در ظرفیت ۱۰۰٪';
$ec_lang['mhp_notes_1_term']='معادله توان';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>، که در آن &rho; = 1000 kg/m&sup3; (آب شیرین) و g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='هد خالص';
$ec_lang['mhp_notes_2_def']='هد خالص = هد ناخالص &minus; افت هد پنستاک. یک تخمین اولیه رایج h<sub>L</sub> &asymp; ۵٪ از H<sub>gross</sub> است. برای تخمین دقیق‌تر افت پنستاک از <a href="Darcy-Weisbach.php">ماشین‌حساب Darcy-Weisbach</a> استفاده کنید.';
$ec_lang['mhp_notes_3_term']='بازده';
$ec_lang['mhp_notes_3_def']='بازده معمول نیروگاه &eta; برای توربین‌های پلتون و جریان متقاطع رایج در میکرو-هیدرو از 0.70 تا 0.85 است. از 0.75 به عنوان تخمین اولیه محافظه‌کارانه استفاده کنید.';
$ec_lang['mhp_notes_4_term']='انرژی سالانه';
$ec_lang['mhp_notes_4_def']='انرژی سالانه فرض می‌کند عملیات پیوسته با جریان کامل (8760 ساعت در سال). تولید واقعی به دلیل تغییرات فصلی جریان، توقف تعمیرات و ضریب بار کمتر خواهد بود.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='زمان تخلیه دریچه';
$ec_lang['odt_main_title']='ماشین‌حساب رایگان آنلاین زمان تخلیه دریچه — استخر، حوضچه یا مخزن';
$ec_lang['odt_main_desc']='زمان تخلیه دریچه استخر یا حوضچه &mdash; روش حجم مخروطی';
$ec_lang['odt_h1_elev']='ارتفاع سطح آب اولیه <span title="Starting water surface elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_a1']='مساحت اولیه، A<sub>1</sub>';
$ec_lang['odt_h2_elev']='ارتفاع سطح آب نهایی (WSE)';
$ec_lang['odt_h_orifice']='ارتفاع مرکز ثقل دریچه';
$ec_lang['odt_a0']='مساحت سطح دریچه، A<sub>0</sub>';
$ec_lang['odt_a_ending']='مساحت نهایی، A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_h2_check']='بررسی ارتفاع نهایی';
$ec_lang['odt_h2_ok']='ارتفاع نهایی بالاتر از تاج دریچه ✓';
$ec_lang['odt_h2_warn']='هشدار: ارتفاع نهایی در سطح یا پایین‌تر از تاج دریچه (مرکز ثقل + D/2)';
$ec_lang['odt_d']='قطر دریچه D <span title="Diameter (circular) or height (rectangular)" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_w']='عرض دریچه، W <span title="Rectangular only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_t_sec']='زمان تخلیه (s)';
$ec_lang['odt_t_min']='زمان تخلیه (min)';
$ec_lang['odt_t_hr']='زمان تخلیه (hr)';
$ec_lang['odt_t_day']='زمان تخلیه (days)';
$ec_lang['odt_notes_1_term']='فرمول';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) زمان تخلیه از هد H تا دریچه را می‌دهد. زمان تخلیه = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>)، که H<sub>1</sub> = ارتفاع اولیه &minus; ارتفاع دریچه، H<sub>2</sub> = ارتفاع نهایی &minus; ارتفاع دریچه.';
$ec_lang['odt_notes_2_term']='روش';
$ec_lang['odt_notes_2_def']='روش حجم مخروطی استخر یا حوضچه را به صورت یک مقطع مخروطی بین مساحت اولیه A<sub>1</sub> در سطح آب اولیه و مساحت A<sub>0</sub> در ارتفاع مرکز ثقل دریچه مدل می‌کند. A<sub>2</sub>، مساحت استخر در ارتفاع نهایی، از A<sub>1</sub> و A<sub>0</sub> با استفاده از مدل مقطع مخروطی درون‌یابی می‌شود. زمان تخلیه از ارتفاع اولیه تا نهایی برابر است با زمان تخلیه کل از H<sub>1</sub> تا دریچه منهای زمان تخلیه باقی‌مانده از H<sub>2</sub> تا دریچه.';
$ec_lang['odt_h1']='هد اولیه، H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_q_max']='حداکثر دبی، Q<sub>max</sub>';
$ec_lang['odt_vol']='حجم تخلیه‌شده';
$ec_lang['odt_sketch_start']='شروع';
$ec_lang['odt_sketch_end']='پایان';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='عرض از کناره تا کناره';
$ec_lang['essc_mcr']='حداقل شعاع انحنا';
$ec_lang['essc_q']='دبی، Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='اندازه‌گیری جریان آبیاری';
$ec_lang['irr_main_title']='ماشین‌حساب‌های رایگان آنلاین اندازه‌گیری جریان آبیاری';
$ec_lang['irr_main_desc']='اندازه‌گیری جریان آبیاری — سرریزها و دریچه‌ها';
$ec_lang['contact_title']='تماس با HawsEDC';
$ec_lang['contactSendMessage']='پیام برای Tom Haws ارسال کنید';
$ec_lang['contactYourName']='نام شما:';
$ec_lang['contactYourEmail']='آدرس ایمیل شما:';
$ec_lang['contactSubject']='موضوع:';
$ec_lang['contact_message']='پیام:';
$ec_lang['contactSpamPrefix']='پنج به‌علاوه یک برابر است با';
$ec_lang['contactSpamPostfix']='(لطفاً آن را به‌صورت حروف بنویسید. 1=یک 2=دو 3=سه 4=چهار 5=پنج 6=شش 7=هفت +=به‌علاوه 5+1=6)';
$ec_lang['contactSubmitButton']='ارسال پیام';

// About
$ec_lang['about_main_menu']='درباره';
$ec_lang['install_main_menu']='نصب';
$ec_lang['install_main_title']='نصب EngCalcs';
$ec_lang['install_main_desc']='برای استفاده آفلاین به دستگاه خود اضافه کنید';
$ec_lang['contact_main_menu']='تماس';
$ec_lang['about_main_title']='درباره ماشین‌حساب‌های مهندسی HawsEDC';
$ec_lang['about_main_desc']='مأموریت، منبع باز و مشارکت';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='نرخ آبیاری قطره‌ای / بارانی';
$ec_lang['ds_main_title']='ماشین حساب رایگان آنلاین نرخ کاربرد آبیاری قطره‌ای/بارانی';
$ec_lang['ds_main_desc']='آبیاری قطره‌ای و بارانی &mdash; نرخ کاربرد و یکنواختی';
$ec_lang['ds_q_avg']='دبی متوسط قطره‌چکان، q';
$ec_lang['ds_q_min']='دبی حداقل قطره‌چکان، q<sub>min</sub>';
$ec_lang['ds_se']='فاصله قطره‌چکان، S<sub>e</sub>';
$ec_lang['ds_sl']='فاصله جانبی، S<sub>l</sub>';
$ec_lang['ds_n_e']='تعداد قطره‌چکان در هر جانبی، n<sub>e</sub>';
$ec_lang['ds_n_l']='تعداد جانبی در هر بلوک، n<sub>l</sub>';
$ec_lang['ds_d']='عمق کاربرد هدف، d';
$ec_lang['ds_a_e']='مساحت به ازای هر قطره‌چکان، A<sub>e</sub>';
$ec_lang['ds_pr']='نرخ کاربرد، PR';
$ec_lang['ds_du']='یکنواختی توزیع، DU';
$ec_lang['ds_du_check']='بررسی کیفیت DU';
$ec_lang['ds_q_lat']='دبی هر جانبی، Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='دبی بلوک، Q<sub>zone</sub>';
$ec_lang['ds_t_run']='زمان اجرا (hours)';
$ec_lang['ds_du_excellent']='عالی — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='خوب — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='قابل قبول — DU ≥ 70%';
$ec_lang['ds_du_poor']='ضعیف — DU < 70% — طراحی را بازبینی کنید ⚠';
$ec_lang['ds_notes_1_term']='نرخ کاربرد';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>، که در آن A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> مساحت تحت پوشش هر قطره‌چکان است. نرخ کاربرد پایین‌تر زمان بیشتری برای نفوذ آب می‌دهد &mdash; در خاک‌های سنگین یا زمین‌های شیب‌دار مهم است.';
$ec_lang['ds_notes_2_term']='یکنواختی توزیع (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. DU برابر ۱.۰ (۱۰۰٪) یعنی همه قطره‌چکان‌ها جریان یکسانی دارند. مقادیر زیر ۰.۸۰ آب را در نقاط مرطوب هدر می‌دهند و نقاط خشک‌تر باقی می‌گذارند. یکنواختی با نوسانات فشار بیش از حد در امتداد جانبی، فرسودگی قطره‌چکان یا گرفتگی جزئی کاهش می‌یابد.';
$ec_lang['ds_notes_3_term']='زمان اجرا';
$ec_lang['ds_notes_3_def']='زمان اجرا = عمق هدف &divide; نرخ کاربرد. در خاک‌های شیب‌دار یا فشرده، زمان اجرا را به دو یا سه چرخه کوتاه‌تر با دوره‌های استراحت تقسیم کنید تا از رواناب سطحی جلوگیری شود.';

// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='نفوذ کانال';
$ec_lang['cs_main_title']='ماشین‌حساب رایگان آنلاین تلفات نفوذ کانال و راندمان انتقال';
$ec_lang['cs_main_desc']='تلفات نفوذ کانال &amp; راندمان انتقال &mdash; روش دبی ورودی-خروجی';
$ec_lang['cs_Q_in']='دبی ورودی، Q<sub>in</sub>';
$ec_lang['cs_Q_out']='دبی خروجی، Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='نرخ تلفات نفوذ، Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='بررسی اندازه‌گیری';
$ec_lang['cs_pct_loss']='تلفات (درصد)';
$ec_lang['cs_Ec']='راندمان انتقال، E<sub>c</sub>';
$ec_lang['cs_Ec_check']='رتبه‌بندی راندمان';
$ec_lang['cs_Vol_day']='حجم روزانه تلف‌شده';
$ec_lang['cs_Vol_year']='حجم سالانه تلف‌شده';
$ec_lang['cs_L']='طول مسیر، L';
$ec_lang['cs_wp']='محیط تر، P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='تلفات/طول، Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='ارزش آب';
$ec_lang['cs_lining_cost']='هزینه آسترکاری';
$ec_lang['cs_Ec_target']='هدف آستر، E<sub>c,target</sub> <span title="Conveyance efficiency goal after lining; fraction 0&ndash;1" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_lining_area']='سطح آستر، L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='ارزش سالانه تلف‌شده';
$ec_lang['cs_annual_value_recovered']='ارزش سالانه بازیافتی';
$ec_lang['cs_lining_total_cost']='هزینه کل آستر';
$ec_lang['cs_payback_years']='دوره بازگشت <span title="Simple payback = total lining cost &divide; annual value recovered" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — نفوذ شناسایی شد ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — بدون تلفات قابل اندازه‌گیری';
$ec_lang['cs_loss_negative']='هشدار: Qout > Qin — اندازه‌گیری‌ها را بررسی کنید ⚠';
$ec_lang['cs_Ec_good']='خوب — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='متوسط — Ec 60–80%';
$ec_lang['cs_Ec_poor']='ضعیف — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='روش';
$ec_lang['cs_notes_1_def']='روش دبی ورودی-خروجی نفوذ را با اندازه‌گیری جریان در ابتدا و انتهای یک مسیر کانال برآورد می‌کند: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. راندمان انتقال E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. حجم سالانه فرض می‌کند که کانال به طور پیوسته با جریان کامل کار می‌کند؛ تلفات واقعی برای کانال‌های فصلی یا با جریان جزئی کمتر است.';
$ec_lang['cs_notes_2_term']='رتبه‌بندی راندمان';
$ec_lang['cs_notes_2_def']='کانال‌های خاکی بدون آسترمعمول: E<sub>c</sub> = 60&ndash;80%. کانال‌های خاکی نگهداری‌شده: 75&ndash;85%. کانال‌های آسترشده با بتن: 90&ndash;98%. تلفات نفوذ بیش از ۳۰٪ دبی ورودی اغلب سرمایه‌گذاری برای آسترکاری را توجیه می‌کند. (USBR، FAO)';
$ec_lang['cs_notes_3_term']='بازگشت سرمایه آسترکاری';
$ec_lang['cs_notes_3_def']='ارزش آب و هزینه آسترکاری را در هر واحد پول سازگار وارد کنید. سطح آستر = طول مسیر &times; محیط تر — محیط تر مقطع کانال در عمق جریان اندازه‌گیری‌شده است (عرض کف به‌علاوه هر دو شیب تر). ارزش سالانه بازیافتی فرض می‌کند که کانال آسترشده به طور مداوم بازده E<sub>c</sub> هدف را حقق می‌کند. بازگشت سرمایه واقعی برای کانال‌های فصلی یا کانال‌های آبیاری که بازده هدف را دستیافت نمی‌کنند، طولانی‌تر خواهد بود.';
$ec_lang['cs_notes_4_term']='مرجع';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>، ویرایش سوم (2001). FAO Irrigation and Drainage Paper 57 (1999).';

$ec_lang['irr_intro_html']='<p>سرریزها و دریچه‌ها ابزارهای میدانی استاندارد برای اندازه‌گیری جریان آب در سیستم‌های آبیاری هستند. ماشین‌حسابی را انتخاب کنید که با سازه شما مطابقت دارد:</p>';
$ec_lang['irr_card_weir_uniform_head']='سرریز — آستانه عریض (عرض یکنواخت)';
$ec_lang['irr_card_weir_uniform_desc']='جریان روی تاج سد انحرافی، سازه کنترلی یا تخته سرریز را اندازه‌گیری کنید. طول سرریز و عمق آب بالای تاج را وارد کنید.';
$ec_lang['irr_card_weir_irregular_head']='سرریز — پروفیل نامنظم';
$ec_lang['irr_card_weir_irregular_desc']='هنگامی استفاده کنید که تاج سرریز در یک تراز یکنواخت نباشد — سرریزهای طبیعی، سازه‌های افت با عرض متغیر، یا سازه‌های کنترل چند مقطعی.';
$ec_lang['irr_card_orifice_head']='دریچه — دریچه سردهانه یا خروجی لوله';
$ec_lang['irr_card_orifice_desc']='جریان از میان دریچه کشویی، خروجی لوله، یا دهانه آبرو را اندازه‌گیری کنید. به طور خودکار هم جریان آزاد و هم شرایط غرق‌شدگی (فشار پس‌آب) را پردازش می‌کند.';
$ec_lang['irr_card_canal_head']='طراحی &amp; تحلیل کانال';
$ec_lang['irr_card_canal_desc']='کانال آبیاری را با فرمول Manning طراحی یا بررسی کنید. برای کانال‌های جدید از ماشین‌حساب ذوزنقه‌ای و برای مقاطع طبیعی یا مصنوعی موجود از ماشین‌حساب نامنظم استفاده کنید.';
$ec_lang['irr_card_drip_head']='طراحی آبیاری قطره‌ای &amp; بارانی';
$ec_lang['irr_card_drip_desc']='نرخ آبیاری، یکنواختی توزیع، دبی جانبی، دبی منطقه و مدت زمان کارکرد یک سیستم آبیاری قطره‌ای یا بارانی را محاسبه کنید. دبی قطره‌چکان، فاصله قطره‌چکان‌ها و عمق هدف را وارد کنید.';
$ec_lang['irr_card_seepage_head']='نفوذ کانال &amp; راندمان انتقال';
$ec_lang['irr_card_seepage_desc']='تلفات نفوذ از یک مسیر کانال را با استفاده از اندازه‌گیری‌های دبی ورودی و خروجی برآورد کنید. راندمان انتقال و تلفات آب سالانه را محاسبه کنید تا اولویت‌بندی سرمایه‌گذاری برای آسترکاری کمک شود.';
$ec_lang['irr_quickref_html']='<h3>راهنمای سریع</h3><dl><dt>سد انحرافی یا سازه کنترلی</dt><dd>عمق آب بالای تاج سرریز را اندازه بگیرید. برای تاج یکنواخت از <a href="Weir-Flow-Simple.php">سرریز ساده</a> و برای تاج با پروفیل یا پله‌دار از <a href="Weir-Flow-Irregular.php">سرریز نامنظم</a> استفاده کنید.</dd><dt>دریچه سردهانه یا خروجی لوله</dt><dd>تراز آب بالادست و پایین‌دست را اندازه بگیرید (یا تراز کف لوله در صورت جریان آزاد). از <a href="Orifice.php">جریان دریچه</a> استفاده کنید. برای لوله دایره‌ای D&nbsp;= قطر لوله؛ برای دریچه مستطیلی عرض W و ارتفاع D را وارد کنید.</dd><dt>زمان تخلیه مخزن یا استخر</dt><dd>برای برآورد مدت زمان لازم جهت کاهش سطح آب استخر یا مخزن از طریق دریچه کفی از <a href="Orifice-Drain-Time.php">زمان تخلیه دریچه</a> استفاده کنید — مفید برای برنامه‌ریزی ذخیره‌سازی آب آبیاری.</dd><dt>استانداردهای میدانی</dt><dd>معادلات جریان سرریز و دریچه مورد استفاده در اینجا با رویه‌های <em>دستورالعمل اندازه‌گیری آب</em> USBR (ویرایش سوم) مطابقت دارد که معمولاً توسط ناظران آب و شبکه‌های آبیاری الزامی است.</dd></dl>';
$ec_lang['about_body_html']='<h3>مأموریت</h3><p>ماشین‌حساب‌های مهندسی HawsEDC برای خدمت به مهندسان و کارگران میدانی در سراسر جهان وجود دارند — به‌ویژه کسانی که در مناطق کم‌آب، کم‌منابع یا محروم کار می‌کنند. این ابزارها بخشی از یک مأموریت انسان‌دوستانه گسترده‌تر هستند: به هر انسانی به عملی‌ترین و مؤثرترین شکل ممکن بگویند که برای همیشه دوست‌داشتنی و عزیز است، چیزی برای ترسیدن ندارد و همه چیز را خراب نخواهد کرد.</p><p>ماشین‌حساب‌ها وسیله‌اند. مقصد دنیایی عاری از رنج است.</p><h3>پروانه متن‌باز</h3><p>تمام کد تحت <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">پروانه عمومی همگانی GNU نسخه ۳.۰ یا بالاتر</a> منتشر شده — آزاد به معنای واقعی آزادی. می‌توانید کد را با همان شرایط استفاده، مطالعه، تغییر و توزیع مجدد کنید.</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>کد منبع</h3><p>کد منبع کامل به صورت عمومی در Bitbucket در دسترس است:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>می‌توانید کد را مرور کنید، مشکلات را گزارش دهید یا مخزن را فورک کنید.</p><h3>مشارکت</h3><p>درخواست‌های کشش خوش‌آمد هستند. روش‌های مشارکت:</p><ul><li><strong>ترجمه‌ها</strong> — زبانی را بهبود دهید یا اضافه کنید. یک درخواست کشش با تغییرات در فایل <code>lib/lang.ec.??.php</code> مربوطه باز کنید.</li><li><strong>گزارش اشکالات</strong> — از فرم بازخورد در هر صفحه ماشین‌حساب استفاده کنید، یا مشکل را در Bitbucket گزارش دهید.</li><li><strong>ماشین‌حساب‌های جدید</strong> — ایده‌هایی برای ابزارهای مهندسی هیدرولیک که به کارگران میدانی و متخصصان آبیاری خدمت می‌کنند به‌ویژه خوش‌آمد هستند. راهنمای توسعه‌دهنده <code>CLAUDE.md</code> در مخزن را ببینید.</li><li><strong>میزبانی</strong> — اگر می‌توانید این ماشین‌حساب‌ها را برای منطقه‌ای با اتصال محدود آینه‌ای کنید، لطفاً تماس بگیرید.</li></ul><h3>استفاده آفلاین</h3><p>این ماشین‌حساب‌ها به‌عنوان یک برنامه وب پیشرفته (PWA) کار می‌کنند. هنگام اتصال به اینترنت، هر صفحه ماشین‌حساب را بازدید کنید تا مرورگر شما به‌طور خودکار همه ماشین‌حساب‌ها را ذخیره کند. پس از آن، همه ماشین‌حساب‌ها بدون اینترنت کار می‌کنند.</p><p>در Android یا iOS، از گزینه «افزودن به صفحه اصلی» مرورگر خود برای نصب EngCalcs به‌عنوان یک برنامه روی دستگاهتان استفاده کنید. در رایانه رومیزی، آیکون نصب را در نوار آدرس مرورگر خود جستجو کنید.</p><p>همچنین می‌توانید هر ماشین‌حساب را با استفاده از منوی «ذخیره به عنوان&hellip;» مرورگر خود برای استفاده آفلاین یک‌باره ذخیره کنید.</p><h3>تماس</h3><p>Tom Haws — مهندس هیدرولیک و نویسنده این ماشین‌حساب‌ها.<br />از فرم بازخورد در هر صفحه ماشین‌حساب استفاده کنید، یا به کد منبع در <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> دسترسی پیدا کنید.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='طراحی شوت سنگی (Robinson)';
$ec_lang['rc_main_title']='ماشین‌حساب رایگان طراحی شوت سنگی — Robinson (1998)';
$ec_lang['rc_main_desc']='تعیین اندازه ریپ‌رپ شوت سنگی &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='شیب بستر شوت، S<sub>0</sub>';
$ec_lang['rc_qt']='دبی واحد کل، q<sub>t</sub> <span title="جریان به ازای هر واحد عرض در ورودی شوت. برای کانالی با عرض کف B و دبی کل Q، از q_t = Q / B استفاده کنید." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='تخلخل ریپ‌رپ، n<sub>p</sub>';
$ec_lang['rc_sg']='وزن مخصوص سنگ، sg <span title="گرانیت یا بازالت خردشده معمولی ≈ 2.65. محدوده معتبر Robinson: 2.54 تا 2.82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='انحراف دانه‌بندی SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="انحراف معیار دانه‌بندی. سنگ یکنواخت ≈ 1.25. محدوده معتبر Robinson: 1.15 تا 1.47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='عمق نرمال در کانال ورودی، y<sub>n</sub> <span title="تجمع آب (Hp > yn) مطلوب است — فرسایش بالادست را کاهش می‌دهد. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='اندازه میانه سنگ مورد نیاز، D<sub>50</sub> <span title="معادله 1 (S0 &lt; 0.10) یا معادله 2 (0.10-0.40). معتبر: D50 بین 15 تا 278 میلی‌متر، S0 بین 0.02 تا 0.40. خارج از محدوده: مقادیر برون‌یابی." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='معادله به‌کاررفته';
$ec_lang['rc_sg_check']='بررسی وزن مخصوص';
$ec_lang['rc_SD_check']='بررسی انحراف دانه‌بندی SD';
$ec_lang['rc_sg_ok']   ='sg در محدوده معتبر (2.54–2.82) ✓';
$ec_lang['rc_sg_low']  ='هشدار: sg < 2.54 — پایین‌تر از محدوده Robinson';
$ec_lang['rc_sg_high'] ='هشدار: sg > 2.82 — بالاتر از محدوده Robinson';
$ec_lang['rc_SD_ok']   ='SD در محدوده معتبر (1.15–1.47) ✓';
$ec_lang['rc_SD_low']  ='هشدار: SD < 1.15 — پایین‌تر از محدوده Robinson';
$ec_lang['rc_SD_high'] ='هشدار: SD > 1.47 — بالاتر از محدوده Robinson';
$ec_lang['rc_layer']='ضخامت لایه سنگ (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='شعاع منحنی تاج فوقانی (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='طول قوس منحنی تاج فوقانی';
$ec_lang['rc_apron_length']='طول پیش‌بند خروجی (15 &times; D<sub>50</sub>) <span title="برای پشتیبانی سازه‌ای سنگ‌های شوت لازم است. «حداقل آب پشتی که در نتیجه مقاومت کانال خروجی ایجاد می‌شود برای تضمین پایداری ریپ‌رپ در محدوده خروجی کافی است.» (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='ضریب زبری Manning در شوت، n';
$ec_lang['rc_Vm']='سرعت از میان پوشش سنگی، V<sub>m</sub> <span title="بخشی از qt که از خلل‌وفرج سنگ عبور می‌کند. بقیه qs روی سطح جریان می‌یابد. مقدار پیش‌فرض np = 0.45 برای سنگ خردشده زاویه‌دار معمول است." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='دبی واحد از میان پوشش، q<sub>m</sub>';
$ec_lang['rc_qs']='دبی واحد سطحی، q<sub>s</sub> (q<sub>t</sub> &minus; q<sub>m</sub>)';
$ec_lang['rc_d']='عمق جریان بالای سطح ریپ‌رپ، d';
$ec_lang['rc_Hp']='هد آب ورودی، H<sub>p</sub> <span title="تجمع آب (Hp > yn) مطلوب است — فرسایش بالادست را کاهش می‌دهد. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='بررسی تجمع آب در ورودی';
$ec_lang['rc_pond_ok']  ='Hp > yn — تجمع آب در بالادست ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — بدون تجمع آب — ورودی را از نظر فرسایش بررسی کنید';
$ec_lang['rc_eq1']='معادله 1 (S0 < 0.10) — شیب ملایم';
$ec_lang['rc_eq2']='معادله 2 (0.10 ≤ S0 ≤ 0.40) — شیب تند';
$ec_lang['rc_eq_warn_low']='هشدار: S0 < 0.02 — پایین‌تر از محدوده اعتبارسنجی Robinson';
$ec_lang['rc_eq_warn_high']='هشدار: S0 > 0.40 — بالاتر از محدوده اعتبارسنجی Robinson';
$ec_lang['rc_notes_1_term']='معادلات تعیین اندازه سنگ';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) دو معادله تجربی برای اندازه میانه ریپ‌رپ D<sub>50</sub> بر اساس شیب شوت و دبی واحد توسعه دادند. معادله 1 برای شیب‌های ملایم (S<sub>0</sub> &lt; 0.10) اعمال می‌شود؛ معادله 2 برای شیب‌های تند (0.10 &le; S<sub>0</sub> &le; 0.40). هر دو معادله به q<sub>t</sub> بر حسب m&sup2;/s نیاز دارند و D<sub>50</sub> را به میلی‌متر برمی‌گردانند. محدوده معتبر 0.02 &le; S<sub>0</sub> &le; 0.40 است.';
$ec_lang['rc_notes_2_term']='دبی واحد';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> دبی واحد کل در تاج شوت است (دبی کل به ازای هر واحد عرض). برای کانالی با عرض کف B که دبی کل Q را حمل می‌کند، q<sub>t</sub> &asymp; Q / B تقریب زده می‌شود، یا از شرط عمق بحرانی در ورودی شوت محاسبه می‌گردد.';
$ec_lang['rc_notes_3_term']='جریان از میان پوشش سنگی';
$ec_lang['rc_notes_3_def']='بخشی از جریان کل از خلل‌وفرج ریپ‌رپ عبور می‌کند (جریان پوشش q<sub>m</sub>)؛ بقیه روی سطح سنگ جاری می‌شود (q<sub>s</sub> = q<sub>t</sub> &minus; q<sub>m</sub>). عمق جریان d از معادله Manning اعمال‌شده بر جریان سطحی q<sub>s</sub> با استفاده از زبری شوت n محاسبه می‌شود. تخلخل پیش‌فرض n<sub>p</sub> = 0.45 برای سنگ خردشده زاویه‌دار معمول است.';
$ec_lang['rc_notes_5_term']='محدوده معتبر اندازه سنگ';
$ec_lang['rc_notes_5_def']='معادلات با محدوده D<sub>50</sub> از 15&nbsp;میلی‌متر تا 278&nbsp;میلی‌متر توسعه یافته‌اند. نتایج خارج از این محدوده برون‌یابی هستند و باید با قضاوت مهندسی اضافی به‌کار روند.';
$ec_lang['rc_notes_6_term']='تراز پیش‌بند خروجی';
$ec_lang['rc_notes_6_def']='تراز بالای ریپ‌رپ در محدوده خروجی باید برابر یا پایین‌تر از تراز بستر کانال پایین‌دست باشد. اگر بالاتر باشد، سنگ‌های خروجی ناپایدار خواهند بود.';
$ec_lang['rc_notes_7_term']='بررسی تجمع آب در ورودی';
$ec_lang['rc_notes_7_def']='هنگامی که عمق نرمال در کانال ورودی کمتر از هد آب مورد نیاز (H<sub>p</sub>) برای عبور q<sub>t</sub> باشد، جریان محدود یا تجمع آب در بالادست پیش‌بند ورودی رخ می‌دهد. این عموماً قابل قبول است — تجمع آب سرعت را کاهش داده و از فرسایش بالادست جلوگیری می‌کند. برای بررسی: از ماشین‌حساب جریان سرریز برای یافتن H<sub>p</sub> برای q<sub>t</sub> و عرض تاج داده‌شده استفاده کنید و با عمق نرمال کانال ورودی مقایسه کنید. اگر H<sub>p</sub> از عمق نرمال بیشتر شود، تجمع آب رخ خواهد داد.';
$ec_lang['rc_notes_4_term']='مرجع';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://doi.org/10.13031/2013.17230">Design of rock chutes</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. USDA ARS همچنین یک <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">صفحه گسترده Excel</a> بر اساس همین روش منتشر کرده است.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'فیلتر';
$ec_lang['rc_sketch_top_crest_curve'] = 'منحنی تاج';
$ec_lang['rc_sketch_outlet_apron']    = 'پیش‌بند خروجی';
$ec_lang['rc_sketch_radius']          = 'شعاع';
