<?php

// All missing text declarations will fall back to English.

$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
// In page order for easiest maintenance.
$ec_lang['calc_set_units']='Alege unitate masură:';
$ec_lang['calc_results']='Rezultate';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Manning Curgere Conductă';
$ec_lang['mpf_main_title']='Calculator Gratuit Online Manning Curgere Conductă';
$ec_lang['mpf_main_desc']='Formula Manning Curgere Uniformă în Conductă la Pantă și Adâncime Date';
$ec_lang['mpf_pipe_diameter']='Diametru conductă';
$ec_lang['mpf_manningRoughness']='Rugozitate';
$ec_lang['mpf_friction_slope']='Panta (possibly <a target="_blank" href="../pressureslope.php">?</a> equal to pipe slope, S<sub>0</sub> ';
$ec_lang['mpf_depth_ratio']='Procent sau fracţie din conducta plină (100% sau 1 inseamnă plină)';
$ec_lang['mpf_flow']='Debit';
$ec_lang['mpf_velocity']='Viteză';
$ec_lang['mpf_velocity_head']='Presiunea dinamică';
$ec_lang['mpf_flow_area']='Secţiune de curgere';
$ec_lang['mpf_wetted_perimeter']='Perimetrul secţiunii de curgere';
$ec_lang['mpf_hydraulic_radius']='Raza hidraulică';
$ec_lang['mpf_top_width']='Laţimea suprafeţei libere';
$ec_lang['mpf_froude_number']='Numărul Froude';
$ec_lang['mpf_shear_stress']='Efort tangenţial promedio';
$ec_lang['mpf_solve_for_dd0']='Calculează y/d<sub>0</sub> pentru Q dat';
$ec_lang['mpf_solve_desc']='Folosind D<sub>0</sub>, n și S<sub>0</sub> din formularul calculatorului, găsește cel mai mic y/d<sub>0</sub> pentru un Q dat.';
$ec_lang['mpf_solve_button']='Calculează';
// Orifice Flow
$ec_lang['or_main_menu']='Debit prin Orificiu';
$ec_lang['or_main_title']='Calculator gratuit online de debit prin orificiu';
$ec_lang['or_main_desc']='Debit prin Orificiu — Liber sau Înecat';
$ec_lang['or_shape']='Forma deschiderii';
$ec_lang['or_shape_circular']='Circulară';
$ec_lang['or_shape_rectangular']='Dreptunghiulară';
$ec_lang['or_diameter']='Diameter or height, D <span title="Diameter for circular; height for rectangular" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_width']='Width, W <span title="Rectangular openings only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_invert']='Invert elevation <span title="Bottom of opening" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['or_hwe']='Nivelul apei în amonte';
$ec_lang['or_twe']='Nivelul apei în aval';
$ec_lang['or_cd']='Coeficient de debit, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Cota centroidului';
$ec_lang['or_head']='Sarcină efectivă, h';
$ec_lang['or_area']='Aria deschiderii, A';
$ec_lang['or_flow']='Debit, Q';
$ec_lang['or_velocity']='Velocity, v';
$ec_lang['or_regime']='Verificarea regimului de orificiu';
$ec_lang['or_regime_valid']='Curgere liberă — regim de orificiu valid ✓';
$ec_lang['or_regime_submerged']='Orificiu înecat (TWE peste radier) — valid ✓';
$ec_lang['or_regime_warn']='Atenție: nivelul amonte sub cheia arcului — nu este regim de orificiu';
$ec_lang['or_regime_twe_above_hwe']='Atenție: apa din aval (TWE) depășește apa din amonte (HWE) — verificați datele de intrare';
$ec_lang['or_notes_1_term']='Ecuația orificiului';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh). Curgere liberă: h = HWE &minus; centroid. Înecat (TWE peste radier): h = HWE &minus; TWE.';
$ec_lang['or_notes_2_term']='Regimul orificiului';
$ec_lang['or_notes_2_def']='Ecuațiile de debit prin orificiu se aplică atunci când nivelul din amonte este deasupra cheii deschiderii. Când este sub cheie, utilizați o ecuație de deversor.';
$ec_lang['or_notes_3_term']='Coeficient de debit';
$ec_lang['or_notes_3_def']='C<sub>d</sub> variază între 0,60 și 0,65 pentru orificii cu margini ascuțite. Intrările rotunjite sau reintrate au valori diferite. Consultați <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> sau Manualul de Referință Hidraulică HEC-RAS.';
$ec_lang['or_notes_4_term']='Înecare';
$ec_lang['or_notes_4_def']='Când TWE depășește radierul deschiderii, calculatorul aplică automat ecuația orificiului înecat cu h = HWE &minus; TWE. Când TWE este la nivelul sau sub radier, se presupune curgere liberă și h = HWE &minus; centroid.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Timp de Golire prin Orificiu';
$ec_lang['odt_main_title']='Calculator Gratuit Online Timp de Golire prin Orificiu — Iaz, Bazin sau Rezervor';
$ec_lang['odt_main_desc']='Timp de Golire a Iazului sau Bazinului prin Orificiu &mdash; Metoda Volumului Conic';
$ec_lang['odt_h1_elev']='Starting WSE <span title="Starting water surface elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_a1']='Starting area, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Ending WSE';
$ec_lang['odt_h_orifice']='Cota centroidului orificiului';
$ec_lang['odt_a0']='Orifice-level area, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Ending area, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_h2_check']='Verificare cotă finală';
$ec_lang['odt_h2_ok']='Cota finală deasupra vârfului orificiului ✓';
$ec_lang['odt_h2_warn']='Atenție: cota finală la nivelul sau sub vârful orificiului (centroid + D/2)';
$ec_lang['odt_d']='Orifice D <span title="Diameter (circular) or height (rectangular)" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_w']='Orifice width, W <span title="Rectangular only" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_t_sec']='Drain time (s)';
$ec_lang['odt_t_min']='Drain time (min)';
$ec_lang['odt_t_hr']='Drain time (hr)';
$ec_lang['odt_t_day']='Drain time (days)';
$ec_lang['odt_notes_1_term']='Formulă';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) dă timpul de golire de la sarcina H până la orificiu. Timp de golire = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), unde H<sub>1</sub> = cota inițială &minus; cota orificiului, H<sub>2</sub> = cota finală &minus; cota orificiului.';
$ec_lang['odt_notes_2_term']='Metodă';
$ec_lang['odt_notes_2_def']='Metoda volumului conic modelează iazul sau bazinul ca o secțiune conică între aria inițială A<sub>1</sub> la suprafața inițială a apei și aria A<sub>0</sub> la cota centroidului orificiului. A<sub>2</sub>, aria iazului la cota finală, este interpolată din A<sub>1</sub> și A<sub>0</sub> folosind modelul secțiunii conice. Timpul de golire de la cota inițială la cea finală este egal cu timpul total de golire de la H<sub>1</sub> la orificiu minus timpul rămas de golire de la H<sub>2</sub> la orificiu.';
$ec_lang['odt_h1']='Starting head, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['odt_q_max']='Max flow, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volum golit';
$ec_lang['odt_sketch_start']='Start';
$ec_lang['odt_sketch_end']='Sfârșit';

// Units (alphabetical order)
$ec_lang['u_depthFrac']='fracție';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/sec';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% ridicare/drum';
$ec_lang['u_grade']='ridicare/drum';
$ec_lang['u_in2']='in^2';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='in';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='l/s';
$ec_lang['u_m2']='m^2';
$ec_lang['u_m3ps']='m^3/s';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='m H2O';
$ec_lang['u_mld']='Ml/zi';
$ec_lang['u_m']='m';
$ec_lang['u_mm2']='mm^2';
$ec_lang['u_mmh2o']='mm H2O';
$ec_lang['u_mm']='mm';
$ec_lang['u_mps']='m/s';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='sec';
// Menu and General
$ec_lang['menu_brand']='Calculatoare HawsEDC';
$ec_lang['menu_main_list']='Listă de calculatoare';
$ec_lang['menu_main_hydraulics']='Hidraulică';
$ec_lang['menu_main_language']='Limbă';
$ec_lang['menu_more']='Mai mult';
$ec_lang['template_welcome']='&gt;&gt; Lasă temerile la ușă; dragostea se vorbește aici. Nu stricați totul. Bucurați-vă și de <a target="_blank" href="https://hawsedc.com/download.php">instrumentele gratuite HawsEDC AutoCAD</a>. &lt;&lt;';
$ec_lang['template_translation_help']='Aveți o viziune excelentă pentru un calculator de adăugat aici?  Mă puteți ajuta să îmbunătățesc traducerile, să programez sau să găzduiesc aceste calculatoare?  ';
$ec_lang['template_feedback']='Vă rugăm să ne transmiteți sugestiile sau aprecierile dumneavoastră valoroase. Acest calculator gratuit v-a depășit așteptările în orice privință?';
$ec_lang['template_printable_title']='Titlu tipărit';
$ec_lang['template_printable_subtitle']='Subtitlu tipărit';
$ec_lang['index_title']='Calculatoare Inginerești Gratuite Online';
$ec_lang['calc_inputs']='Date de intrare';
$ec_lang['view_hide_line']='[Ascunde această linie]';
$ec_lang['view_printable']='Versiune tipăribilă (reîncărcați/actualizați pentru a restaura)';
$ec_lang['ec_name_label']='Salvați acest calcul:';
$ec_lang['ec_name_placeholder']='Nume';
$ec_lang['ec_name_hint']='Salvează valorile introduse în URL pentru marcaj, recuperare istoric și partajare';
$ec_lang['ec_name_invalid']='Utilizați doar litere, cifre, spații, – _ .';
$ec_lang['points_data_help']='(sau Copiați/Lipiți folosind zona de date)';
$ec_lang['points_data_title']='Date puncte<br />(separate prin virgulă sau tabulație)';
$ec_lang['points_data_copy']='Copiați';
$ec_lang['points_data_paste']='Lipiți';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='Pierdere de Sarcină Conductă Darcy-Weisbach';
$ec_lang['dw_main_title']='Calculator Gratuit Online Pierdere de Sarcină Conductă Darcy-Weisbach';
$ec_lang['dw_main_desc']='Pierdere de Sarcină Conductă Darcy-Weisbach la Diametru, Rugozitate și Debit Date';
$ec_lang['dw_roughness']='Rugozitate absolută Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Vâscozitate cinematică, &nu; <span title="1×10⁻⁶ m²/s for clean water at 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['dw_reynolds_number']='Numărul Reynolds, Re';
$ec_lang['dw_flow_regime']='Regimul de curgere';
$ec_lang['dw_regime_laminar']='curgere laminară';
$ec_lang['dw_regime_transitional']='tranzițional';
$ec_lang['dw_regime_turbulent']='curgere turbulentă';
$ec_lang['dw_friction_factor_method']='Metoda factorului de frecare';
$ec_lang['dw_friction_factor']='Factorul de frecare, f';
// Hazen-Williams
$ec_lang['hw_main_menu']='Pierdere de Sarcină Conductă Hazen-Williams';
$ec_lang['hw_main_title']='Calculator Gratuit Online Pierdere de Sarcină Conductă Hazen-Williams';
$ec_lang['hw_main_desc']='Pierdere de Sarcină Conductă Hazen-Williams la Diametru, Rugozitate și Debit Date';
$ec_lang['hw_hgl_1']='HGL aval';
$ec_lang['hw_hgl_2']='HGL amonte';
$ec_lang['hw_roughness']='Coeficientul Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Manning Canal Neregulat';
$ec_lang['mi_main_title']='Calculator Gratuit Online Manning Canal Neregulat';
$ec_lang['mi_main_desc']='Calculator de Curgere Uniformă Manning Canal Neregulat';
$ec_lang['mi_waterSurfaceElevation']='Cota suprafeței apei';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Puncte secțiune transversală';
$ec_lang['mi_groupPoint']='Punct';
$ec_lang['mi_groupSegment']='Segment';
$ec_lang['mi_groupRegion']='Regiune';
$ec_lang['mi_station']='Stație';
$ec_lang['mi_elevation']='Cotă';
$ec_lang['mi_d50in']='Dimensiune<br />mediană<br />rocă<br />placare';
$ec_lang['mi_n']='n<br />pentru<br />seg-<br />ment';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />limita<br />regiunii<br />(Mal)';
$ec_lang['mi_tau']='Efort<br />tangenț.<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n<br />comp.';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Note';
$ec_lang['mi_notes_1_term']='n compozit';
$ec_lang['mi_notes_1_def']='Acest calculator urmează Manualul de Referință HEC-RAS în calculul n compozit de regiune folosind Chow 1959, pagina 136, ecuația 6-17 (nu 6-18).';
$ec_lang['mi_notes_2_term']='Placare cu rocă';
$ec_lang['mi_notes_2_def']='Folosiți Calculatorul Manning Canal Trapezoidal pentru a proiecta placarea cu rocă. Acest calculator este mai potrivit pentru secțiuni naturale.';
// Manning Pipe Flow additional keys
$ec_lang['mpf_see_notes']='(Consultați notele)';
$ec_lang['mpf_pipe_area']='Aria conductei, a0';
$ec_lang['mpf_area_ratio']='Arie relativă, a/a0';
$ec_lang['mpf_full_flow']='Debit la plin, Q0';
$ec_lang['mpf_full_flow_ratio']='Raport față de debitul la plin, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Acesta este debitul și adâncimea în interiorul unei conducte <em>infinit lungi</em>.</dt><dd>Introducerea debitului în conductă poate necesita o adâncime a apei din amonte semnificativ mai mare. Adăugați cel puțin de 1,5 ori sarcina de viteză pentru a obține adâncimea din amonte sau <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">consultați tutorialul meu de 2 minute</a> pentru calculele standard ale nivelului din amonte ale podețelor folosind HY-8.</dd>';
$ec_lang['mpf_spreadheet_notice']='Consultați versiunea de calcul tabelar a acestui calculator';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='Manning Pierdere de Sarcină Conductă';
$ec_lang['mphl_main_title']='Calculator Gratuit Online Manning Pierdere de Sarcină Conductă';
$ec_lang['mphl_main_desc']='Formula Manning Pierdere de Sarcină la Curgere Plină Dată';
$ec_lang['mphl_pipe_length']='Lungimea conductei, L';
$ec_lang['mphl_area']='Arie, A';
$ec_lang['mphl_total_junction_k']='Coeficient total combinat de pierdere la racorduri, k';
$ec_lang['mphl_friction_slope']='Panta de frecare';
$ec_lang['mphl_friction_loss']='Pierdere prin frecare, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Pierdere la racord, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Pierdere totală, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL aval';
$ec_lang['mphl_egl_2']='EGL amonte';
$ec_lang['mphl_hgl_2']='HGL amonte în conductă ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Pentru o condiție de intrare deschisă (podeț), este necesar să se verifice condițiile de control la intrare.</dt><dd>1. HGL amonte nu poate fi mai jos decât cota de adâncime normală amonte a curgerii (sau sub conductă!).</dd><dd>2. Nivelul apei din amonte al unui podeț este mai bine reprezentat de EGL amonte decât de HGL amonte.</dd><dd>3. Consultați <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">tutorialul meu de 2 minute</a> pentru calculele simple standard ale nivelului din amonte ale podețelor folosind HY-8.</dd>';
// Manning Trapezoid
$ec_lang['mtc_menu']='Manning Canal Trapezoidal';
$ec_lang['mtc_main_title']='Calculator Gratuit Online Formula Manning Canal Trapezoidal';
$ec_lang['mtc_main_desc']='Formula Manning Curgere Uniformă în Canal Trapezoidal la Pantă și Adâncime Date';
$ec_lang['mtc_bottom_width']='Lățimea fundului, b';
$ec_lang['mtc_side_slope_1']='Taluz 1 (orizontal/vertical)';
$ec_lang['mtc_side_slope_2']='Taluz 2 (orizontal/vertical)';
$ec_lang['mtc_channel_slope']='Panta canalului, S';
$ec_lang['mtc_flow_depth']='Adâncimea de curgere, y';
$ec_lang['mtc_bend_angle']='Unghi de curbă <a target="_blank" href="riprap-bend-angle.png" title="Faceți clic pentru imagine">?</a> (pentru dimensionarea riprapului)';
$ec_lang['mtc_sgrock']='Greutatea specifică a rocii (2,65)';
$ec_lang['mtc_d50_in']='Dimensiunea de proiectare a rocii, D50';
$ec_lang['mtc_n_strickler']='n pentru dimensiunea de proiectare a rocii conform Strickler';
$ec_lang['mtc_n_blodgett']='n pentru dimensiunea de proiectare a rocii conform Blodgett';
$ec_lang['mtc_n_bathurst']='n pentru dimensiunea de proiectare a rocii conform Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Dimensiunea necesară a rocii unghiulare de fund, D50 (Isbash & MC) <span title="Conform Isbash (1936) și Comitatul Maricopa, Arizona, SUA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Dimensiunea necesară a rocii unghiulare taluz 1, D50 (Isbash & MC) <span title="Conform Isbash (1936) și Comitatul Maricopa, Arizona, SUA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Dimensiunea necesară a rocii unghiulare taluz 2, D50 (Isbash & MC) <span title="Conform Isbash (1936) și Comitatul Maricopa, Arizona, SUA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Dimensiunea necesară a rocii unghiulare, D50 (Maynord, Ruff și Abt 1989)';
$ec_lang['mtc_d50_searcy']='Dimensiunea necesară a rocii unghiulare, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Iterație automată de dimensionare a rocii și rugozității</dt><dd>Alegeți un buton radio pentru rugozitate (BB recomandat) și un buton radio pentru dimensiunea de proiectare a rocii (Isbash recomandat). Ajustați adâncimea și factorul de siguranță al dimensiunii rocii pentru a obține debitul dorit cu o dimensiune uniformă a rocii. De fiecare dată când modificați orice valoare de intrare, are loc următorul ciclu de iterație: 1. Rugozitatea este calculată din dimensiunea de proiectare a rocii. 2. Calculul rugozității solicitate este copiat la rugozitatea de intrare. 3. Debitul canalului și dimensiunea necesară a rocii sunt calculate. 4. Dimensiunea de proiectare a rocii este ajustată. 5. Repetați până când eroarea din dimensiunea de proiectare a rocii este foarte mică.</dd><dt>Calculator de bază (fără iterație)</dt><dd>Introduceți valoarea dorită de rugozitate. Ignorați zona de intrare a dimensiunii de proiectare a rocii.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Rapide din Rocă Robinson';
$ec_lang['rrc_main_desc']='Foaie de Calcul Proiectare Rapide din Rocă Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Deversor cu Creastă Lată Simplu';
$ec_lang['ws_main_title']='Calculator Gratuit Online Deversor cu Creastă Lată Simplu';
$ec_lang['ws_main_desc']='Calculator Simplu pentru Curgere peste Deversor cu Creastă Lată';
$ec_lang['ws_weirLength']='Lungimea deversorului, l';
$ec_lang['ws_headWaterHeight']='Înălțimea apei amonte, h';
$ec_lang['ws_weirCoefficient']='Coeficientul deversorului, Cw';
$ec_lang['ws_notes_heading']='Note';
$ec_lang['ws_notes_we_term']='Ecuația deversorului';
// Weir Flow Irregular
$ec_lang['wi_menu']='Deversor Neregulat';
$ec_lang['wi_main_title']='Calculator Gratuit Online Deversor Segmentat, Adâncime Variabilă, Neregulat';
$ec_lang['wi_main_desc']='Calculator pentru Curgere peste Deversor Neregulat';
$ec_lang['wi_headWaterelevation']='Cota apei amonte';
$ec_lang['wi_weirPoints']='Puncte deversor';
$ec_lang['wi_station']='Stație<br />(distanță)';
$ec_lang['wi_elevation']='Cotă';
$ec_lang['wi_pondingHeight']='Înălțimea acumulării';
$ec_lang['wi_incrementalFlow']='Debit incremental';
$ec_lang['wi_cumulativeFlow']='Debit cumulat';
$ec_lang['wi_save_and_calculate']='Salvați și Calculați';
$ec_lang['wi_notes_we_term']='Ecuația deversorului';
$ec_lang['wi_notes_we_def']='q = dacă (lungime = 0) atunci 0 altfel dacă (pantă=0) atunci cw*lungime*d<sub>0</sub><sup>1.5</sup> altfel cw/(2.5*pantă) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) unde d<sub>1</sub> și d<sub>0</sub> sunt întotdeauna pozitive sau zero';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Lățimea mal la mal';
$ec_lang['essc_mcr']='Raza minimă de curbură';
$ec_lang['essc_q']='Debit, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Măsurarea Debitului de Irigare';
$ec_lang['irr_main_title']='Calculatoare Online Gratuite pentru Măsurarea Debitului de Irigare';
$ec_lang['irr_main_desc']='Măsurarea Debitului de Irigare — Deversor și Orificii';
$ec_lang['contact_title']='Contact HawsEDC';
$ec_lang['contactSendMessage']='Trimiteți un mesaj lui Tom Haws';
$ec_lang['contactYourName']='Numele dumneavoastră:';
$ec_lang['contactYourEmail']='Adresa dumneavoastră de e-mail:';
$ec_lang['contactSubject']='Subiect:';
$ec_lang['contact_message']='Mesaj:';
$ec_lang['contactSpamPrefix']='Cinci plus unu este egal cu';
$ec_lang['contactSpamPostfix']='(Vă rugăm să scrieți cu litere. 1=unu 2=doi 3=trei 4=patru 5=cinci 6=șase 7=șapte +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Trimiteți Mesajul';
$ec_lang['contact_success']='Mulțumesc că ați luat timp pentru a scrie.';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Hidroenergie';
$ec_lang['mhp_main_title']='Calculator gratuit online de micro-hidroenergie';
$ec_lang['mhp_main_desc']='Calculator de putere pentru micro-hidrocentrale cu derivație fluvială';
$ec_lang['mhp_flow']='Debit, Q';
$ec_lang['mhp_gross_head']='Cădere brută (diferență de nivel), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='Pierderi de sarcină în conducta forțată, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='Randamentul instalației, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='Cădere netă, H<sub>net</sub>';
$ec_lang['mhp_power']='Putere produsă, P';
$ec_lang['mhp_annual_kwh']='Energie anuală la capacitate 100%';
$ec_lang['mhp_notes_1_term']='Ecuația puterii';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, unde &rho; = 1000 kg/m&sup3; (apă dulce) și g = 9,806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='Cădere netă';
$ec_lang['mhp_notes_2_def']='Cădere netă = cădere brută &minus; pierderi de sarcină în conducta forțată. O estimare inițială uzuală este h<sub>L</sub> &asymp; 5% din H<sub>gross</sub>. Utilizați <a href="Darcy-Weisbach.php">calculatorul Darcy-Weisbach</a> pentru estimări mai precise ale pierderilor în conducta forțată.';
$ec_lang['mhp_notes_3_term']='Randament';
$ec_lang['mhp_notes_3_def']='Randamentul tipic al instalației &eta; variază între 0,70 și 0,85 pentru turbinele Pelton și turbinele cu flux încrucișat, frecvente în micro-hidroenergie. Utilizați 0,75 ca estimare inițială prudentă.';
$ec_lang['mhp_notes_4_term']='Energie anuală';
$ec_lang['mhp_notes_4_def']='Energia anuală presupune funcționare continuă la debit maxim (8760 ore/an). Producția reală va fi mai mică din cauza variației sezoniere a debitului, opririlor pentru întreținere și factorului de sarcină.';
// Penstock Design
$ec_lang['ps_main_menu']='Proiectare conductă forțată';
$ec_lang['ps_main_title']='Calculator gratuit online pentru conductă forțată';
$ec_lang['ps_main_desc']='Dimensionarea conductei forțate micro-hidro — Pierderi de sarcină, putere și viteză';
$ec_lang['ps_flow']='Debit, Q';
$ec_lang['ps_gross_head']='Sarcina brută, H<sub>gross</sub>';
$ec_lang['ps_diameter']='Diametrul conductei forțate, D';
$ec_lang['ps_length']='Lungimea conductei forțate, L';
$ec_lang['ps_roughness']='Rugozitatea conductei, e';
$ec_lang['ps_km']='Minor loss coefficient, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['ps_nu']='Kinematic viscosity, &nu; <span title="1×10⁻⁶ m²/s for clean water near 20°C" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['ps_efficiency']='Randamentul centralei, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='Viteza de curgere, v';
$ec_lang['ps_vel_check']='Verificarea vitezei';
$ec_lang['ps_f']='Coeficient de frecare, f';
$ec_lang['ps_hf']='Pierdere de sarcină prin frecare, h<sub>f</sub>';
$ec_lang['ps_hm']='Minor head loss, h<sub>m</sub>';
$ec_lang['ps_hl']='Pierdere totală în conducta forțată, h<sub>L</sub>';
$ec_lang['ps_hl_check']='Verificarea pierderii de sarcină';
$ec_lang['ps_hnet']='Sarcina netă, H<sub>net</sub>';
$ec_lang['ps_power']='Putere produsă, P';
$ec_lang['ps_annual_kwh']='Energie anuală la 100% capacitate';
$ec_lang['ps_vel_ok']='1–3 m/s — în intervalul țintă ✓';
$ec_lang['ps_vel_low']='sub 1 m/s — măriți diametrul ⚠';
$ec_lang['ps_vel_high']='peste 3 m/s — reduceți diametrul ⚠';
$ec_lang['ps_hl_ok']='în limita țintei de 10% ✓';
$ec_lang['ps_hl_warn']='depășește ținta de 10% — luați în calcul o conductă mai mare ⚠';
$ec_lang['ps_hl_bad']='depășește 20% — redimensionați conducta';
$ec_lang['ps_notes_1_term']='Pierdere de sarcină';
$ec_lang['ps_notes_1_def']='Pierderea totală h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, unde h<sub>f</sub> = f(L/D)(v&sup2;/2g) este pierderea prin frecare Darcy-Weisbach, iar h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g acoperă intrarea, coturi și armături. Sarcina netă H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='Viteză';
$ec_lang['ps_notes_2_def']='Țintă 1&ndash;3 m/s. Sub 1 m/s conducta este supradimensionată; peste 3 m/s cresc pierderile prin frecare și riscul de lovitură de berbec.';
$ec_lang['ps_notes_3_term']='Ținta pierderilor de sarcină';
$ec_lang['ps_notes_3_def']='Pierderile în conducta forțată sub 10% din sarcina brută sunt în general economice. Compromisul optim între costul conductei și puterea pierdută se situează adesea în jurul a 4&ndash;6% pentru siturile cu electricitate de mare valoare.';
$ec_lang['ps_notes_4_term']='Pierderi locale k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='Valori tipice: intrare cu margine ascuțită 0.5, fiecare cot de 45&deg; între 0.2&ndash;0.3, robinet cu sertar (complet deschis) 0.1, robinet fluture 0.2. Suma tuturor fitingurilor dă k<sub>m</sub> total. Valoarea implicită 1.5 presupune o intrare și două coturi.';
$ec_lang['ps_notes_5_term']='Rugozitatea conductei e';
$ec_lang['ps_notes_5_def']='Rugozitate absolută tipică: oțel (nou) 0.046&nbsp;mm, oțel (uzat) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, beton 0.3&ndash;3&nbsp;mm. HDPE este des utilizat la conductele forțate micro-hidro de mici dimensiuni.';

// About
$ec_lang['about_main_menu']='Despre';
$ec_lang['install_main_menu']='Instalare';
$ec_lang['install_main_title']='Instalează EngCalcs';
$ec_lang['install_main_desc']='Adaugă pe dispozitiv pentru utilizare offline';
$ec_lang['contact_main_menu']='Contact';
$ec_lang['about_main_title']='Despre calculatoarele de inginerie HawsEDC';
$ec_lang['about_main_desc']='Misiune, sursă deschisă și contribuții';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Rata de aplicare — irigare prin picurare/aspersiune';
$ec_lang['ds_main_title']='Calculator gratuit online al ratei de aplicare la irigarea prin picurare/aspersiune';
$ec_lang['ds_main_desc']='Irigare prin picurare &amp; aspersiune &mdash; rata de aplicare și uniformitate';
$ec_lang['ds_q_avg']='Debitul mediu al emițătorului, q';
$ec_lang['ds_q_min']='Debitul minim al emițătorului, q<sub>min</sub>';
$ec_lang['ds_se']='Emitter spacing, S<sub>e</sub>';
$ec_lang['ds_sl']='Lateral spacing, S<sub>l</sub>';
$ec_lang['ds_n_e']='Emițătoare pe ramură laterală, n<sub>e</sub>';
$ec_lang['ds_n_l']='Ramuri laterale pe zonă, n<sub>l</sub>';
$ec_lang['ds_d']='Adâncimea de udare țintă, d';
$ec_lang['ds_a_e']='Suprafața per emițător, A<sub>e</sub>';
$ec_lang['ds_pr']='Application rate, PR';
$ec_lang['ds_du']='Uniformitatea distribuției, DU';
$ec_lang['ds_du_check']='Verificare calitate DU';
$ec_lang['ds_q_lat']='Debit pe ramură laterală, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Debitul zonei, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Runtime (hours)';
$ec_lang['ds_du_excellent']='Excelent — DU ≥ 90% ✓';
$ec_lang['ds_du_good']='Bun — DU ≥ 80% ✓';
$ec_lang['ds_du_acceptable']='Acceptabil — DU ≥ 70%';
$ec_lang['ds_du_poor']='Slab — DU < 70% — revizuiți proiectul ⚠';
$ec_lang['ds_notes_1_term']='Rata de aplicare';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, unde A<sub>e</sub> = S<sub>e</sub> &times; S<sub>l</sub> este suprafața deservită de fiecare emițător. O rată de aplicare mai mică oferă mai mult timp pentru infiltrare &mdash; importantă pe soluri grele sau câmpuri înclinate.';
$ec_lang['ds_notes_2_term']='Uniformitatea distribuției (DU)';
$ec_lang['ds_notes_2_def']='DU = q<sub>min</sub> / q<sub>avg</sub>. Un DU de 1,0 (100%) înseamnă că toți emițătorii curg identic. Valorile sub 0,80 risipesc apa în zonele bine irigate, lăsând zone mai uscate. Uniformitatea scade cu variații excesive de presiune de-a lungul ramurii laterale, uzura emițătoarelor sau obstrucția parțială.';
$ec_lang['ds_notes_3_term']='Timp de funcționare';
$ec_lang['ds_notes_3_def']='Timp de funcționare = adâncime țintă &divide; rată de aplicare. Pe sol înclinat sau compactat, împărțiți timpul de funcționare în două sau trei cicluri mai scurte cu pauze între ele pentru a evita scurgerea superficială.';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Pierderi prin Infiltrație Canal';
$ec_lang['cs_main_title']='Calculator Online Gratuit pentru Pierderi prin Infiltrație și Eficiența de Transport a Canalului';
$ec_lang['cs_main_desc']='Pierderi prin Infiltrație &amp; Eficiența de Transport a Canalului &mdash; Metoda Influx-Eflux';
$ec_lang['cs_Q_in']='Inflow, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Outflow, Q<sub>out</sub>';
$ec_lang['cs_Q_loss']='Rata de pierderi prin infiltrație, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verificare măsurători';
$ec_lang['cs_pct_loss']='Fraction lost';
$ec_lang['cs_Ec']='Eficiența de transport, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Clasificare eficiență';
$ec_lang['cs_Vol_day']='Volum pierdut zilnic';
$ec_lang['cs_Vol_year']='Volum pierdut anual';
$ec_lang['cs_L']='Lungimea tronsonului, L';
$ec_lang['cs_wp']='Wetted perimeter, P<sub>w</sub>';
$ec_lang['cs_Q_loss_per_L']='Loss per unit length, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Water value';
$ec_lang['cs_lining_cost']='Lining cost';
$ec_lang['cs_Ec_target']='Lining target, E<sub>c,target</sub> <span title="Conveyance efficiency goal after lining; fraction 0&ndash;1" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_lining_area']='Lining area, L &times; P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Annual value lost';
$ec_lang['cs_annual_value_recovered']='Annual value recovered';
$ec_lang['cs_lining_total_cost']='Total lining cost';
$ec_lang['cs_payback_years']='Payback period <span title="Simple payback = total lining cost &divide; annual value recovered" style="cursor:help;color:steelblue;font-size:0.9em">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — infiltrație detectată ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — fără pierderi măsurabile';
$ec_lang['cs_loss_negative']='Atenție: Qout > Qin — verificați măsurătorile ⚠';
$ec_lang['cs_Ec_good']='Bun — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Satisfăcător — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Slab — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Metodă';
$ec_lang['cs_notes_1_def']='Metoda influx-eflux estimează infiltrația prin măsurarea debitului la intrarea și ieșirea unui tronson de canal: Q<sub>loss</sub> = Q<sub>in</sub> &minus; Q<sub>out</sub>. Eficiența de transport E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Volumul anual presupune funcționare continuă la debit maxim; pierderea reală este mai mică pentru canale sezoniere sau cu debit parțial.';
$ec_lang['cs_notes_2_term']='Clasificarea eficienței';
$ec_lang['cs_notes_2_def']='Canale de pământ necăptușite tipice: E<sub>c</sub> = 60&ndash;80%. Canale de pământ bine întreținute: 75&ndash;85%. Canale cu căptușeală din beton: 90&ndash;98%. Pierderi prin infiltrație peste 30% din debitul de intrare justifică adesea o investiție în căptușire. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Rambursare Căptușeală';
$ec_lang['cs_notes_3_def']='Introduceți valoarea apei și costul căptușelii în orice monedă consistentă. Suprafață căptușeală = lungimea tronsonului &times; perimetrul udat &mdash; perimetrul udat al secțiunii transversale a canalului la adâncimea de curgere măsurată (lățimea fundului plus ambii taluzi udați). Valoarea anuală recuperată presupune că canalul căptușit atinge în mod continuu E<sub>c</sub> țintă. Rambursarea reală va fi mai lungă pentru canale sezoniere sau dacă căptușeala nu atinge eficiența țintă.';
$ec_lang['cs_notes_4_term']='Referință';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, ediția a 3-a (2001). FAO Irrigation and Drainage Paper 57 (1999).';

$ec_lang['irr_intro_html']='<p>Deversorele și orificiile sunt instrumentele standard de teren pentru măsurarea debitului de apă în sistemele de irigații. Selectați calculatorul care corespunde structurii dvs.:</p>';
$ec_lang['irr_card_weir_uniform_head']='Deversor — Prag Lat (Lățime Uniformă)';
$ec_lang['irr_card_weir_uniform_desc']='Măsurați debitul peste creasta unui baraj de derivație, a unei structuri de control sau a unei plăci deversoare. Introduceți lungimea deversorului și adâncimea apei deasupra crestei.';
$ec_lang['irr_card_weir_irregular_head']='Deversor — Profil Neregulat';
$ec_lang['irr_card_weir_irregular_desc']='Utilizați când creasta deversorului nu se află la o cotă uniformă — deversor natural, structuri de cădere cu lățime variabilă sau structuri de control cu mai multe secțiuni.';
$ec_lang['irr_card_orifice_head']='Orificiu — Vană de Cap sau Branșament de Conductă';
$ec_lang['irr_card_orifice_desc']='Măsurați debitul printr-o vană glisantă, branșament de conductă sau orificiu de pod-canal. Gestionează automat atât curgerea liberă, cât și condițiile de înec (presiunea apei din aval).';
$ec_lang['irr_card_canal_head']='Proiectarea &amp; Analiza Canalului';
$ec_lang['irr_card_canal_desc']='Proiectați sau verificați un canal de irigații utilizând formula Manning. Folosiți calculatorul Trapezoidal pentru canale noi; calculatorul Neregulat pentru secțiuni naturale sau construite existente.';
$ec_lang['irr_card_drip_head']='Proiectare Picurare &amp; Aspersoare';
$ec_lang['irr_card_drip_desc']='Calculați rata de aplicare, uniformitatea distribuției, debitul lateral, debitul de zonă și durata de funcționare pentru un sistem de irigare prin picurare sau aspersoare. Introduceți debitul emițătorului, distanța dintre emițătoare și adâncimea țintă.';
$ec_lang['irr_card_seepage_head']='Infiltrații Canal &amp; Eficiența de Transport';
$ec_lang['irr_card_seepage_desc']='Estimați pierderile prin infiltrație dintr-un tronson de canal folosind măsurătorile de influx și eflux. Calculați eficiența de transport și volumul anual de apă pierdut pentru a ajuta la prioritizarea investițiilor în căptușire.';
$ec_lang['irr_quickref_html']='<h3>Referință Rapidă</h3><dl><dt>Baraj de derivație sau structură de control</dt><dd>Măsurați adâncimea apei deasupra crestei deversorului. Utilizați <a href="Weir-Flow-Simple.php">Deversor Simplu</a> pentru o creastă uniformă sau <a href="Weir-Flow-Irregular.php">Deversor Neregulat</a> pentru o creastă profilată sau în trepte.</dd><dt>Vană de cap sau branșament de conductă</dt><dd>Măsurați cota apei în amonte și în aval (sau cota radierului dacă curgerea este liberă). Utilizați <a href="Orifice.php">Debit prin Orificiu</a>. Pentru conductă circulară, D&nbsp;= diametrul conductei; pentru vană dreptunghiulară, introduceți lățimea W și înălțimea D.</dd><dt>Timp de golire a unui rezervor sau iaz</dt><dd>Utilizați <a href="Orifice-Drain-Time.php">Timp de Golire prin Orificiu</a> pentru a estima cât durează coborârea nivelului unui iaz sau rezervor printr-un orificiu de fund — util pentru planificarea stocării apei de irigații.</dd><dt>Standarde de teren</dt><dd>Ecuațiile de debit ale deversorului și orificiului utilizate aici corespund procedurilor din USBR <em>Water Measurement Manual</em> (ediția a 3-a), solicitate în mod obișnuit de administratorii de apă și districtele de irigații.</dd></dl>';
$ec_lang['about_body_html']='<h3>Misiune</h3><p>Calculatoarele de Inginerie HawsEDC există pentru a servi ingineri și muncitori de teren din întreaga lume — în special cei care lucrează în regiuni cu deficit de apă, resurse limitate sau insuficient deservite. Aceste instrumente fac parte dintr-o misiune umanitară mai amplă: să spună fiecărui om în cel mai practic și eficient mod posibil că este iubit și prețuit pentru totdeauna, că nu are nimic de care să se teamă și că nu va ruina totul.</p><p>Calculatoarele sunt vehiculul. Destinația este o lume fără suferință.</p><h3>Licență Open Source</h3><p>Tot codul este publicat sub <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 sau mai nou</a> — liber ca în libertate. Puteți utiliza, studia, modifica și redistribui codul în aceleași condiții.</p><p>Copyright &copy; 2009&ndash;2026 Thomas Gail Haws.</p><h3>Cod Sursă</h3><p>Codul sursă complet este disponibil public pe Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Puteți răsfoi codul, semnala probleme sau face fork la depozit acolo.</p><h3>Contribuție</h3><p>Pull request-urile sunt binevenite. Modalități de contribuție:</p><ul><li><strong>Traduceri</strong> — îmbunătățiți sau adăugați o limbă. Deschideți un pull request cu modificări în fișierul <code>lib/lang.ec.??.php</code> relevant.</li><li><strong>Rapoarte de erori</strong> — utilizați formularul de feedback pe orice pagină de calculator sau semnalați o problemă pe Bitbucket.</li><li><strong>Calculatoare noi</strong> — ideile pentru instrumente de inginerie hidraulică care servesc lucrătorilor de teren și practicienilor în irigații sunt deosebit de binevenite. Consultați ghidul pentru dezvoltatori <code>CLAUDE.md</code> din depozit.</li><li><strong>Găzduire</strong> — dacă puteți oglindi aceste calculatoare pentru o regiune cu conectivitate limitată, vă rugăm să ne contactați.</li></ul><h3>Utilizare offline</h3><p>Aceste calculatoare funcționează ca o Aplicație Web Progresivă (PWA). Vizitați orice pagină de calculator în timp ce sunteți conectat la internet, iar browserul dvs. va stoca automat toate calculatoarele în cache. După aceea, toate calculatoarele funcționează offline — nu este necesar internetul.</p><p>Pe Android sau iOS, folosiți opțiunea „Adaugă pe ecranul principal" din browserul dvs. pentru a instala EngCalcs ca aplicație pe dispozitivul dvs. Pe desktop, căutați pictograma de instalare în bara de adrese a browserului.</p><p>Puteți, de asemenea, să salvați orice calculator individual folosind meniul „Salvare ca&hellip;" din browser pentru utilizare offline ocazională.</p><h3>Contact</h3><p>Tom Haws — inginer hidraulic și autorul acestor calculatoare.<br />Folosiți formularul de feedback pe orice pagină de calculator sau accesați codul sursă pe <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Proiectarea Rigolei din Piatră (Robinson)';
$ec_lang['rc_main_title']='Calculator Online Gratuit pentru Proiectarea Rigolei din Piatră — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionarea Pietrei de Protecție a Rigolei &mdash; Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='Panta fundului rigolei, S<sub>0</sub>';
$ec_lang['rc_qt']='Debit unitar total, q<sub>t</sub> <span title="Debitul pe unitate de lățime la intrarea în rigolă. Pentru un canal cu lățimea fundului B și debitul total Q, utilizați q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Porozitatea pietrei de protecție, n<sub>p</sub>';
$ec_lang['rc_sg']='Greutatea specifică a rocii, sg <span title="Granit sau bazalt concasat tipic ≈ 2,65. Interval valid Robinson: 2,54–2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Granulozitate SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Abaterea standard a granulozității. Piatră uniformă ≈ 1,25. Interval valid Robinson: 1,15–1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Adâncimea normală în canalul de intrare, y<sub>n</sub> <span title="Înălțarea (Hp > yn) este benefică — reduce eroziunea în amonte. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Dimensiunea mediană necesară a pietrei, D<sub>50</sub> <span title="Ec. 1 (S0 &lt; 0.10) sau Ec. 2 (0,10–0,40). Valid: D50 15–278 mm, S0 0,02–0,40. În afara intervalului: extrapolat." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Ecuație aplicată';
$ec_lang['rc_sg_check']='Verificare greutate specifică';
$ec_lang['rc_SD_check']='Verificare granulozitate SD';
$ec_lang['rc_sg_ok']   ='sg în intervalul valid (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Avertisment: sg < 2,54 — sub intervalul valid Robinson';
$ec_lang['rc_sg_high'] ='Avertisment: sg > 2,82 — peste intervalul valid Robinson';
$ec_lang['rc_SD_ok']   ='SD în intervalul valid (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Avertisment: SD < 1,15 — sub intervalul valid Robinson';
$ec_lang['rc_SD_high'] ='Avertisment: SD > 1,47 — peste intervalul valid Robinson';
$ec_lang['rc_layer']='Grosimea stratului de piatră (2 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Raza curbei la coronamentul superior (40 &times; D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Lungimea arcului curbei la coronament';
$ec_lang['rc_apron_length']='Lungimea radierului de ieșire (15 &times; D<sub>50</sub>) <span title="Necesară pentru susținerea structurală a pietrei rigolei. „Contrapresiunea minimă rezultată din rezistența tronsoanelor aval este suficientă pentru a asigura stabilitatea pietrei de protecție în zona de ieșire." (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Rugozitatea Manning în rigolă, n';
$ec_lang['rc_Vm']='Viteza prin mantaua de piatră, V<sub>m</sub> <span title="Fracțiunea din qt care curge prin porii pietrei de protecție. Restul qs curge la suprafață. Implicit np = 0,45 pentru piatră concasată cu muchii ascuțite." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Debit unitar prin mantaua de piatră, q<sub>m</sub>';
$ec_lang['rc_qs']='Debit unitar la suprafață, q<sub>s</sub> (q<sub>t</sub> &minus; q<sub>m</sub>)';
$ec_lang['rc_d']='Adâncimea curgerii deasupra suprafeței pietrei, d';
$ec_lang['rc_Hp']='Sarcina hidraulică la intrare, H<sub>p</sub> <span title="Înălțarea (Hp > yn) este benefică — reduce eroziunea în amonte. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Verificare înălțare la intrare';
$ec_lang['rc_pond_ok']  ='Hp > yn — înălțare amonte ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — fără înălțare — verificați intrarea pentru eroziune';
$ec_lang['rc_eq1']='Ec. 1 (S0 < 0,10) — pantă lină';
$ec_lang['rc_eq2']='Ec. 2 (0,10 ≤ S0 ≤ 0,40) — pantă abruptă';
$ec_lang['rc_eq_warn_low']='Avertisment: S0 < 0,02 — sub intervalul de validare Robinson';
$ec_lang['rc_eq_warn_high']='Avertisment: S0 > 0,40 — peste intervalul de validare Robinson';
$ec_lang['rc_notes_1_term']='Ecuații de dimensionare a pietrei';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) au elaborat două ecuații empirice pentru dimensiunea mediană a pietrei de protecție D<sub>50</sub> pe baza pantei rigolei și a debitului unitar. Ecuația 1 se aplică pentru pante line (S<sub>0</sub> &lt; 0,10); Ecuația 2 se aplică pentru pante abrupte (0,10 &le; S<sub>0</sub> &le; 0,40). Ambele ecuații necesită q<sub>t</sub> în m&sup2;/s și returnează D<sub>50</sub> în mm. Intervalul validat este 0,02 &le; S<sub>0</sub> &le; 0,40.';
$ec_lang['rc_notes_2_term']='Debitul unitar';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> este debitul unitar total la coronamentul rigolei (debit total pe unitate de lățime). Pentru un canal cu lățimea fundului B și debitul total Q, se poate aproxima q<sub>t</sub> &asymp; Q / B, sau se poate calcula din condiția adâncimii critice la intrarea în rigolă.';
$ec_lang['rc_notes_3_term']='Curgerea prin mantaua de piatră';
$ec_lang['rc_notes_3_def']='O fracțiune din debitul total se deplasează prin porii pietrei de protecție (debitul prin mantaua q<sub>m</sub>); restul curge la suprafața pietrei (q<sub>s</sub> = q<sub>t</sub> &minus; q<sub>m</sub>). Adâncimea de curgere d se calculează din ecuația lui Manning aplicată debitului de suprafață q<sub>s</sub> cu rugozitatea rigolei n. Porozitatea implicită n<sub>p</sub> = 0,45 este tipică pentru piatra concasată cu muchii ascuțite.';
$ec_lang['rc_notes_5_term']='Intervalul valid al dimensiunii pietrei';
$ec_lang['rc_notes_5_def']='Ecuațiile au fost elaborate pentru un interval D<sub>50</sub> de 15&nbsp;mm până la 278&nbsp;mm. Rezultatele în afara acestui interval sunt extrapolate și trebuie utilizate cu judecată inginerească suplimentară.';
$ec_lang['rc_notes_6_term']='Cota radierului de ieșire';
$ec_lang['rc_notes_6_def']='Cota suprafeței superioare a pietrei de protecție în zona de ieșire trebuie să fie la sau sub cota fundului canalului aval. Dacă este mai ridicată, piatra de protecție de la ieșire va fi instabilă.';
$ec_lang['rc_notes_7_term']='Verificare înălțare la intrare';
$ec_lang['rc_notes_7_def']='Când adâncimea normală în canalul de intrare este mai mică decât sarcina hidraulică (H<sub>p</sub>) necesară pentru a evacua q<sub>t</sub>, apare restricție de debit sau înălțare în amontele radierului de intrare. Aceasta este în general acceptabilă — înălțarea reduce viteza și previne eroziunea în amonte. Verificare: utilizați un calculator de deversor pentru a determina H<sub>p</sub> pentru q<sub>t</sub> și lățimea crestei date, și comparați cu adâncimea normală a canalului de intrare. Dacă H<sub>p</sub> depășește adâncimea normală, va apărea înălțare.';
$ec_lang['rc_notes_4_term']='Referință';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). &ldquo;<a target="_blank" href="https://doi.org/10.13031/2013.17230">Design of rock chutes</a>.&rdquo; <em>Transactions of the ASAE</em>, 41(3), 621&ndash;626. USDA ARS publică, de asemenea, un <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">tabel Excel</a> bazat pe aceeași metodă.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtru';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curbă de creastă';
$ec_lang['rc_sketch_outlet_apron']    = 'Radier de ieșire';
$ec_lang['rc_sketch_radius']          = 'rază';
