<?php

// বাংলা — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="ভগ্নাংশ";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gpm";
$ec_lang['u_gradePercent']="% উচ্চতা/দৈর্ঘ্য";
$ec_lang['u_grade']="উচ্চতা/দৈর্ঘ্য";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/দিন";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="psf";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="সেকেন্ড";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='HawsEDC ক্যালকুলেটর';
$ec_lang['menu_main_list']='ক্যালকুলেটর তালিকা';
$ec_lang['menu_main_hydraulics']='হাইড্রোলিক্স';
$ec_lang['menu_main_language']='ভাষা';
$ec_lang['template_welcome']='&gt;&gt; দরজায় ভয় রেখে আসুন; এখানে ভালোবাসার কথা বলা হয়। <a target="_blank" href="https://hawsedc.com/download.php">বিনামূল্যে HawsEDC AutoCAD টুলগুলো</a>ও উপভোগ করুন। &lt;&lt;';
$ec_lang['template_translation_help']='আপনার কাছে কি এখানে যোগ করার জন্য একটি দারুণ ক্যালকুলেটরের ধারণা আছে?  আপনি কি অনুবাদ উন্নত করতে, প্রোগ্রাম করতে বা এই ক্যালকুলেটরগুলি হোস্ট করতে সাহায্য করতে পারেন?  ';
$ec_lang['template_feedback']='অনুগ্রহ করে আপনার মূল্যবান পরামর্শ বা প্রশংসার কথা জানান। এই বিনামূল্যের ক্যালকুলেটর কি সব দিক থেকে আপনার প্রত্যাশা ছাড়িয়ে গেছে?';
$ec_lang['template_printable_title']='মুদ্রণযোগ্য শিরোনাম';
$ec_lang['template_printable_subtitle']='মুদ্রণযোগ্য উপশিরোনাম';
$ec_lang['index_title']='বিনামূল্যে অনলাইন ইঞ্জিনিয়ারিং ক্যালকুলেটর';
$ec_lang['calc_set_units']='একক নির্ধারণ করুন:';
$ec_lang['points_data_help']='(অথবা ডেটা এলাকা ব্যবহার করে কপি/পেস্ট করুন)';
$ec_lang['points_data_title']='পয়েন্ট ডেটা<br />(কমা বা ট্যাব দ্বারা বিভক্ত)';
$ec_lang['points_data_copy']='কপি';
$ec_lang['points_data_paste']='পেস্ট';
$ec_lang['calc_inputs']='ইনপুট';
$ec_lang['calc_results']='ফলাফল';
$ec_lang['view_hide_line']='[এই লাইনটি লুকান]';
$ec_lang['view_printable']='মুদ্রণযোগ্য সংস্করণ (পুনরুদ্ধারের জন্য পুনরায় লোড করুন)';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='ড্যার্সি-ওয়েইসবাখ পাইপ হেড লস';
$ec_lang['dw_main_title']='বিনামূল্যে অনলাইন ড্যার্সি-ওয়েইসবাখ পাইপ হেড লস ক্যালকুলেটর';
$ec_lang['dw_main_desc']='নির্দিষ্ট ব্যাস, রুক্ষতা ও প্রবাহে ড্যার্সি-ওয়েইসবাখ পাইপ হেড লস';
$ec_lang['dw_roughness']='ড্যার্সি-ওয়েইসবাখ পরম রুক্ষতা, e';
$ec_lang['dw_kinematic_viscosity']='গতিগত সান্দ্রতা, v, m<sup>2</sup>/s এ (কক্ষ তাপমাত্রায় পরিষ্কার পানির জন্য ১E-6)';
$ec_lang['dw_reynolds_number']='রেনোল্ডস সংখ্যা, Re';
$ec_lang['dw_flow_regime']='প্রবাহ ব্যবস্থা';
$ec_lang['dw_regime_laminar']='স্তরীয়';
$ec_lang['dw_regime_transitional']='ক্রান্তিকালীন';
$ec_lang['dw_regime_turbulent']='অশান্ত';
$ec_lang['dw_friction_factor_method']='ঘর্ষণ গুণাঙ্ক পদ্ধতি';
$ec_lang['dw_friction_factor']='ঘর্ষণ গুণাঙ্ক, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='হেজেন-উইলিয়ামস পাইপ হেড লস';
$ec_lang['hw_main_title']='বিনামূল্যে অনলাইন হেজেন-উইলিয়ামস পাইপ হেড লস ক্যালকুলেটর';
$ec_lang['hw_main_desc']='নির্দিষ্ট ব্যাস, রুক্ষতা ও প্রবাহে হেজেন-উইলিয়ামস পাইপ হেড লস';
$ec_lang['hw_hgl_1']='ভাটির HGL';
$ec_lang['hw_hgl_2']='উজানের HGL';
$ec_lang['hw_roughness']='হেজেন-উইলিয়ামস সহগ, C';
// Manning Irregular
$ec_lang['mi_menu']='ম্যানিং অনিয়মিত চ্যানেল';
$ec_lang['mi_main_title']='বিনামূল্যে অনলাইন ম্যানিং অনিয়মিত চ্যানেল ক্যালকুলেটর';
$ec_lang['mi_main_desc']='অনিয়মিত চ্যানেল ম্যানিং অভিন্ন প্রবাহ ক্যালকুলেটর';
$ec_lang['mi_waterSurfaceElevation']='পানির পৃষ্ঠ উচ্চতা';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='প্রস্থচ্ছেদ পয়েন্ট';
$ec_lang['mi_groupPoint']='পয়েন্ট';
$ec_lang['mi_groupSegment']='সেগমেন্ট';
$ec_lang['mi_groupRegion']='অঞ্চল';
$ec_lang['mi_station']='স্টা';
$ec_lang['mi_elevation']='উচ্চতা';
$ec_lang['mi_d50in']='আস্তরণ<br />মধ্যক<br />পাথর<br />আকার';
$ec_lang['mi_n']='n<br />সেগ-<br />মেন্টের<br />জন্য';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />অঞ্চল<br />সীমা<br />(তীর)';
$ec_lang['mi_tau']='তলার<br />শিয়ার<br />&tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='যৌগিক<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='নোট';
$ec_lang['mi_notes_1_term']='যৌগিক n';
$ec_lang['mi_notes_1_def']='এই ক্যালকুলেটর HEC-RAS রেফারেন্স ম্যানুয়াল অনুসরণ করে Chow 1959, পৃষ্ঠা 136, সমীকরণ 6-17 (6-18 নয়) ব্যবহার করে অঞ্চল যৌগিক n গণনা করে।';
$ec_lang['mi_notes_2_term']='পাথর আস্তরণ';
$ec_lang['mi_notes_2_def']='পাথর আস্তরণ ডিজাইন করতে ম্যানিং ট্র্যাপিজোয়েডাল চ্যানেল ক্যালকুলেটর ব্যবহার করুন। এই ক্যালকুলেটর আরও প্রাকৃতিক প্রস্থচ্ছেদের জন্য উপযুক্ত।';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='ম্যানিং পাইপ প্রবাহ';
$ec_lang['mpf_main_title']='বিনামূল্যে অনলাইন ম্যানিং পাইপ প্রবাহ ক্যালকুলেটর';
$ec_lang['mpf_main_desc']='নির্দিষ্ট ঢাল ও গভীরতায় ম্যানিং ফর্মুলা অভিন্ন পাইপ প্রবাহ';
$ec_lang['mpf_spreadheet_notice']='এই ক্যালকুলেটরের স্প্রেডশিট সংস্করণটি দেখুন';
$ec_lang['mpf_pipe_diameter']='পাইপ ব্যাস, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='ম্যানিং রুক্ষতা, n';
$ec_lang['mpf_friction_slope']='চাপ ঢাল (সম্ভবত <a target="_blank" href="../pressureslope.php">?</a> পাইপ ঢালের সমান), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='আপেক্ষিক প্রবাহ গভীরতা, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(নোট দেখুন)';
$ec_lang['mpf_flow']='প্রবাহ, Q';
$ec_lang['mpf_velocity']='বেগ, v';
$ec_lang['mpf_velocity_head']='বেগ হেড, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='প্রবাহ ক্ষেত্রফল, a';
$ec_lang['mpf_pipe_area']='পাইপ ক্ষেত্রফল, a0';
$ec_lang['mpf_area_ratio']='আপেক্ষিক ক্ষেত্রফল, a/a0';
$ec_lang['mpf_wetted_perimeter']='ভেজা পরিধি, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='হাইড্রোলিক ব্যাসার্ধ, R<sub>h</sub>';
$ec_lang['mpf_top_width']='শীর্ষ প্রস্থ, T';
$ec_lang['mpf_froude_number']='ফ্রুড সংখ্যা, F';
$ec_lang['mpf_shear_stress']='গড় শিয়ার চাপ (ট্র্যাকটিভ ফোর্স), tau';
$ec_lang['mpf_full_flow']='পূর্ণ প্রবাহ, Q0';
$ec_lang['mpf_full_flow_ratio']='পূর্ণ প্রবাহের অনুপাত, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>এটি একটি <em>অসীম দীর্ঘ</em> পাইপের মধ্যে প্রবাহ ও গভীরতা।</dt><dd>পাইপে প্রবাহ প্রবেশ করাতে উল্লেখযোগ্যভাবে বেশি আপস্ট্রিম গভীরতার প্রয়োজন হতে পারে। আপস্ট্রিম গভীরতা পেতে বেগ হেডের অন্তত ১.৫ গুণ যোগ করুন অথবা HY-8 ব্যবহার করে স্ট্যান্ডার্ড কালভার্ট হেডওয়াটার গণনার জন্য <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">আমার ২ মিনিটের টিউটোরিয়াল</a> দেখুন।</dd>';
$ec_lang['mpf_solve_for_dd0']='Q দেওয়া y/d<sub>0</sub> খুঁজুন';
$ec_lang['mpf_solve_desc']='ক্যালকুলেটর ফর্ম থেকে D<sub>0</sub>, n, এবং S<sub>0</sub> ব্যবহার করে, নির্দিষ্ট Q-এর জন্য সর্বনিম্ন y/d<sub>0</sub> খুঁজে বের করে।';
$ec_lang['mpf_solve_button']='সমাধান করুন';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='ম্যানিং পাইপ হেড লস';
$ec_lang['mphl_main_title']='বিনামূল্যে অনলাইন ম্যানিং পাইপ হেড লস ক্যালকুলেটর';
$ec_lang['mphl_main_desc']='নির্দিষ্ট পূর্ণ প্রবাহে ম্যানিং ফর্মুলা হেড লস';
$ec_lang['mphl_pipe_length']='পাইপ দৈর্ঘ্য, L';
$ec_lang['mphl_area']='ক্ষেত্রফল, A';
$ec_lang['mphl_total_junction_k']='মোট সম্মিলিত জংশন ক্ষতি সহগ, k';
$ec_lang['mphl_friction_slope']='ঘর্ষণ ঢাল';
$ec_lang['mphl_friction_loss']='ঘর্ষণ ক্ষতি, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='জংশন ক্ষতি, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='মোট ক্ষতি, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='ভাটির EGL';
$ec_lang['mphl_egl_2']='উজানের EGL';
$ec_lang['mphl_hgl_2']='পাইপে উজানের HGL ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>উন্মুক্ত ইনলেট (কালভার্ট) অবস্থার জন্য ইনলেট নিয়ন্ত্রণ পরিস্থিতি পরীক্ষা করা প্রয়োজন।</dt><dd>১. উজানের HGL উজানের স্বাভাবিক গভীরতা প্রবাহ উচ্চতার (বা পাইপের!) চেয়ে কম হতে পারবে না।</dd><dd>২. একটি কালভার্টের হেডওয়াটার উজানের HGL-এর চেয়ে উজানের EGL দ্বারা আরও ভালোভাবে প্রকাশ করা হয়।</dd><dd>৩. HY-8 ব্যবহার করে সহজ স্ট্যান্ডার্ড কালভার্ট হেডওয়াটার গণনার জন্য <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">আমার ২ মিনিটের টিউটোরিয়াল</a> দেখুন।</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='ম্যানিং ট্র্যাপিজোয়েডাল চ্যানেল';
$ec_lang['mtc_main_title']='বিনামূল্যে অনলাইন ম্যানিং ফর্মুলা ট্র্যাপিজোয়েডাল চ্যানেল ক্যালকুলেটর';
$ec_lang['mtc_main_desc']='নির্দিষ্ট ঢাল ও গভীরতায় ম্যানিং ফর্মুলা অভিন্ন ট্র্যাপিজোয়েডাল চ্যানেল প্রবাহ';
$ec_lang['mtc_bottom_width']='তলার প্রস্থ, b';
$ec_lang['mtc_side_slope_1']='পার্শ্ব ঢাল ১ (অনুভূমিক/উল্লম্ব)';
$ec_lang['mtc_side_slope_2']='পার্শ্ব ঢাল ২ (অনুভূমিক/উল্লম্ব)';
$ec_lang['mtc_channel_slope']='চ্যানেল ঢাল, S';
$ec_lang['mtc_flow_depth']='প্রবাহ গভীরতা, y';
$ec_lang['mtc_bend_angle']='বাঁক কোণ <a target="_blank" href="riprap-bend-angle.png" title="চিত্রের জন্য ক্লিক করুন">?</a> (রিপ্র্যাপ আকারের জন্য)';
$ec_lang['mtc_sgrock']='পাথরের আপেক্ষিক গুরুত্ব (2.65)';
$ec_lang['mtc_d50_in']='নকশা পাথর আকার, D50';
$ec_lang['mtc_n_strickler']='স্ট্রিকলার অনুযায়ী নকশা পাথর আকারের জন্য n';
$ec_lang['mtc_n_blodgett']='ব্লডগেট অনুযায়ী নকশা পাথর আকারের জন্য n';
$ec_lang['mtc_n_bathurst']='বাথার্স্ট অনুযায়ী নকশা পাথর আকারের জন্য n';
$ec_lang['mtc_blodgett_v_bathurst']='ব্লডগেট বনাম বাথার্স্ট';
$ec_lang['mtc_d50_bottom']='তলায় প্রয়োজনীয় কোণযুক্ত পাথর আকার, D50 (Isbash এবং MC) <a href="javascript:alert(\'Isbash (1936) এবং Maricopa County, Arizona, US অনুযায়ী।\')">?</a>';
$ec_lang['mtc_d50_z1']='পার্শ্ব ঢাল ১-এ প্রয়োজনীয় কোণযুক্ত পাথর আকার, D50 (Isbash এবং MC) <a href="javascript:alert(\'Isbash (1936) এবং Maricopa County, Arizona, US অনুযায়ী।\')">?</a>';
$ec_lang['mtc_d50_z2']='পার্শ্ব ঢাল ২-এ প্রয়োজনীয় কোণযুক্ত পাথর আকার, D50 (Isbash এবং MC) <a href="javascript:alert(\'Isbash (1936) এবং Maricopa County, Arizona, US অনুযায়ী।\')">?</a>';
$ec_lang['mtc_d50_mra']='প্রয়োজনীয় কোণযুক্ত পাথর আকার, D50 (Maynord, Ruff, এবং Abt 1989)';
$ec_lang['mtc_d50_searcy']='প্রয়োজনীয় কোণযুক্ত পাথর আকার, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>স্বয়ংক্রিয় পাথর আকার ও রুক্ষতা ডিজাইন পুনরাবৃত্তি</dt><dd>একটি রুক্ষতা রেডিও বাটন (BB প্রস্তাবিত) এবং একটি নকশা পাথর আকার রেডিও বাটন (Isbash প্রস্তাবিত) নির্বাচন করুন। একটি সমান পাথর আকারে আপনার কাঙ্ক্ষিত প্রবাহ পেতে গভীরতা ও পাথর আকার নিরাপত্তা গুণক সামঞ্জস্য করুন। প্রতিবার কোনো ইনপুট মান পরিবর্তন করলে নিম্নলিখিত পুনরাবৃত্তি চক্র ঘটে: ১. নকশা পাথর আকার থেকে রুক্ষতা গণনা করা হয়। ২. অনুরোধকৃত রুক্ষতা গণনা ইনপুট রুক্ষতায় কপি করা হয়। ৩. চ্যানেল প্রবাহ ও প্রয়োজনীয় পাথর আকার গণনা করা হয়। ৪. নকশা পাথর আকার সামঞ্জস্য করা হয়। ৫. নকশা পাথর আকারে ত্রুটি খুব ছোট না হওয়া পর্যন্ত পুনরাবৃত্তি।</dd><dt>বেসিক ক্যালকুলেটর (পুনরাবৃত্তি ছাড়া)</dt><dd>আপনার কাঙ্ক্ষিত রুক্ষতা মান লিখুন। নকশা পাথর আকার ইনপুট এলাকা উপেক্ষা করুন।</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='রবিনসন রক চুট';
$ec_lang['rrc_main_desc']='রবিনসন রক চুট ডিজাইন স্প্রেডশিট';
// Weir Flow Simple
$ec_lang['ws_main_menu']='সহজ ওয়্যার বা বাঁধ প্রবাহ';
$ec_lang['ws_main_title']='বিনামূল্যে অনলাইন সহজ বিস্তৃত-ক্রেস্ট ওয়্যার প্রবাহ ক্যালকুলেটর';
$ec_lang['ws_main_desc']='সহজ বিস্তৃত-ক্রেস্ট ওয়্যার বা বাঁধ প্রবাহ ক্যালকুলেটর';
$ec_lang['ws_weirLength']='ওয়্যার দৈর্ঘ্য, l';
$ec_lang['ws_headWaterHeight']='আপস্ট্রিম জলের উচ্চতা, h';
$ec_lang['ws_weirCoefficient']='ওয়্যার সহগ, Cw';
$ec_lang['ws_notes_heading']='নোট';
$ec_lang['ws_notes_we_term']='ওয়্যার সমীকরণ';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='অনিয়মিত ওয়্যার প্রবাহ';
$ec_lang['wi_main_title']='বিনামূল্যে অনলাইন বিভাজিত, পরিবর্তনশীল গভীরতার অনিয়মিত ওয়্যার প্রবাহ ক্যালকুলেটর';
$ec_lang['wi_main_desc']='অনিয়মিত ওয়্যার বা বাঁধ প্রবাহ ক্যালকুলেটর';
$ec_lang['wi_headWaterelevation']='আপস্ট্রিম জলের উচ্চতা';
$ec_lang['wi_weirPoints']='ওয়্যার পয়েন্ট';
$ec_lang['wi_station']='স্টেশন<br />(দূরত্ব)';
$ec_lang['wi_elevation']='উচ্চতা';
$ec_lang['wi_pondingHeight']='পুকুরের উচ্চতা';
$ec_lang['wi_incrementalFlow']='বর্ধিত প্রবাহ';
$ec_lang['wi_cumulativeFlow']='ক্রমবর্ধমান প্রবাহ';
$ec_lang['wi_save_and_calculate']='সংরক্ষণ করুন ও গণনা করুন';
$ec_lang['wi_notes_we_term']='ওয়্যার সমীকরণ';
$ec_lang['wi_notes_we_def']='q = যদি (দৈর্ঘ্য = 0) তাহলে 0 অন্যথায় যদি (ঢাল=0) তাহলে cw*দৈর্ঘ্য*d<sub>0</sub><sup>1.5</sup> অন্যথায় cw/(2.5*ঢাল) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) যেখানে d<sub>1</sub> এবং d<sub>0</sub> সর্বদা শূন্য বা ধনাত্মক';
// Orifice Flow
$ec_lang['or_main_menu']='অরিফিস বা ছিদ্র প্রবাহ';
$ec_lang['or_main_title']='বিনামূল্যে অনলাইন অরিফিস বা ছিদ্র প্রবাহ ক্যালকুলেটর';
$ec_lang['or_main_desc']='অরিফিস বা ছিদ্র প্রবাহ — মুক্ত বা নিমজ্জিত';
$ec_lang['or_shape']='খোলার আকৃতি';
$ec_lang['or_shape_circular']='গোলাকার';
$ec_lang['or_shape_rectangular']='আয়তাকার';
$ec_lang['or_diameter']='ব্যাস (গোলাকার) বা উচ্চতা (আয়তাকার), D';
$ec_lang['or_width']='প্রস্থ, W (শুধুমাত্র আয়তাকার)';
$ec_lang['or_invert']='খোলার ইনভার্ট উচ্চতা (খোলার নিচের অংশ)';
$ec_lang['or_hwe']='আপস্ট্রিম জলের উচ্চতা';
$ec_lang['or_twe']='ডাউনস্ট্রিম জলের উচ্চতা';
$ec_lang['or_cd']='নিঃসরণ সহগ, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='কেন্দ্রচ্যুতি উচ্চতা';
$ec_lang['or_head']='কার্যকর হেড, h';
$ec_lang['or_area']='খোলার ক্ষেত্রফল, A';
$ec_lang['or_flow']='প্রবাহ, Q';
$ec_lang['or_velocity']='খোলায় বেগ, v';
$ec_lang['or_regime']='অরিফিস ব্যবস্থা পরীক্ষা';
$ec_lang['or_regime_valid']='মুক্ত বহির্গমন — অরিফিস ব্যবস্থা বৈধ ✓';
$ec_lang['or_regime_submerged']='নিমজ্জিত অরিফিস (TWE ইনভার্টের উপরে) — বৈধ ✓';
$ec_lang['or_regime_warn']='সতর্কতা: আপস্ট্রিম জল ক্রাউনের নিচে — অরিফিস ব্যবস্থা নয়';
$ec_lang['or_regime_twe_above_hwe']='সতর্কতা: ডাউনস্ট্রিম জল (TWE) আপস্ট্রিম জলের (HWE) উপরে — ইনপুট পরীক্ষা করুন';
$ec_lang['or_notes_1_term']='অরিফিস সমীকরণ';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> &times; A &times; &radic;(2gh)। মুক্ত বহির্গমন: h = HWE &minus; কেন্দ্রচ্যুতি। নিমজ্জিত প্রবাহ (ইনভার্টের উপরে TWE): h = HWE &minus; TWE।';
$ec_lang['or_notes_2_term']='অরিফিস ব্যবস্থা';
$ec_lang['or_notes_2_def']='অরিফিস প্রবাহ সমীকরণ প্রযোজ্য যখন আপস্ট্রিম জলের পৃষ্ঠ খোলার ক্রাউন (শীর্ষ) এর উপরে থাকে। যখন আপস্ট্রিম জল ক্রাউনের নিচে থাকে, তখন ওয়্যার সমীকরণ ব্যবহার করুন।';
$ec_lang['or_notes_3_term']='নিঃসরণ সহগ';
$ec_lang['or_notes_3_def']='তীক্ষ্ণ-প্রান্ত অরিফিসের জন্য C<sub>d</sub> প্রায় 0.60&ndash;0.65 পর্যন্ত। গোলাকার বা পুনঃপ্রবেশী ইনলেট ভিন্ন মান ব্যবহার করে। নির্দেশিকার জন্য <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> বা HEC-RAS হাইড্রোলিক রেফারেন্স ম্যানুয়াল দেখুন।';
$ec_lang['or_notes_4_term']='নিমজ্জন';
$ec_lang['or_notes_4_def']='যখন TWE খোলার ইনভার্টের উপরে থাকে, এই ক্যালকুলেটর স্বয়ংক্রিয়ভাবে h = HWE &minus; TWE ব্যবহার করে নিমজ্জিত অরিফিস সমীকরণ প্রয়োগ করে। যখন TWE ইনভার্টে বা তার নিচে থাকে, মুক্ত বহির্গমন ধরে নেওয়া হয় এবং h = HWE &minus; কেন্দ্রচ্যুতি।';
// Orifice Drain Time
$ec_lang['odt_main_menu']='অরিফিস বা ছিদ্র নিষ্কাশন সময়';
$ec_lang['odt_main_title']='বিনামূল্যে অনলাইন অরিফিস নিষ্কাশন সময় ক্যালকুলেটর — পুকুর, বেসিন বা ট্যাংক';
$ec_lang['odt_main_desc']='পুকুর বা বেসিন অরিফিস নিষ্কাশন সময় &mdash; শঙ্কু আয়তন পদ্ধতি';
$ec_lang['odt_h1_elev']='শুরুর জলের পৃষ্ঠ উচ্চতা';
$ec_lang['odt_a1']='শুরুর পুকুর বা বেসিন ক্ষেত্রফল, A1';
$ec_lang['odt_h2_elev']='শেষ জলের পৃষ্ঠ উচ্চতা';
$ec_lang['odt_h_orifice']='অরিফিস কেন্দ্রচ্যুতি উচ্চতা';
$ec_lang['odt_a0']='অরিফিস উচ্চতায় পুকুর বা বেসিন ক্ষেত্রফল, A0';
$ec_lang['odt_a_ending']='শেষ পুকুর ক্ষেত্রফল, A2 (ইন্টারপোলেটেড)';
$ec_lang['odt_h2_check']='শেষ উচ্চতা পরীক্ষা';
$ec_lang['odt_h2_ok']='শেষ উচ্চতা অরিফিস ক্রাউনের উপরে ✓';
$ec_lang['odt_h2_warn']='সতর্কতা: শেষ উচ্চতা অরিফিস ক্রাউনে বা তার নিচে (কেন্দ্রচ্যুতি + D/2)';
$ec_lang['odt_d']='অরিফিস ব্যাস (গোলাকার) বা উচ্চতা (আয়তাকার), D';
$ec_lang['odt_w']='অরিফিস প্রস্থ, W (শুধুমাত্র আয়তাকার)';
$ec_lang['odt_t_sec']='নিষ্কাশন সময় (সেকেন্ড)';
$ec_lang['odt_t_min']='নিষ্কাশন সময় (মিনিট)';
$ec_lang['odt_t_hr']='নিষ্কাশন সময় (ঘণ্টা)';
$ec_lang['odt_t_day']='নিষ্কাশন সময় (দিন)';
$ec_lang['odt_notes_1_term']='সূত্র';
$ec_lang['odt_notes_1_def']='t = &radic;H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> &radic;(2g)) &times; (2A<sub>x</sub>/5 + 8&radic;(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) হেড H থেকে অরিফিস পর্যন্ত নিষ্কাশন সময় দেয়। নিষ্কাশন সময় = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) &minus; t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), যেখানে H<sub>1</sub> = শুরুর উচ্চতা &minus; অরিফিস উচ্চতা, H<sub>2</sub> = শেষ উচ্চতা &minus; অরিফিস উচ্চতা।';
$ec_lang['odt_notes_2_term']='পদ্ধতি';
$ec_lang['odt_notes_2_def']='শঙ্কু আয়তন পদ্ধতি পুকুর বা বেসিনকে প্রাথমিক জলের পৃষ্ঠে A<sub>1</sub> এবং অরিফিস কেন্দ্রচ্যুতি উচ্চতায় A<sub>0</sub> এর মধ্যে একটি শঙ্কু অংশ হিসাবে মডেল করে। A<sub>2</sub>, শেষ উচ্চতায় পুকুর ক্ষেত্রফল, শঙ্কু অংশ মডেল ব্যবহার করে A<sub>1</sub> এবং A<sub>0</sub> থেকে ইন্টারপোলেট করা হয়। শুরু থেকে শেষ উচ্চতা পর্যন্ত নিষ্কাশন সময় H<sub>1</sub> থেকে অরিফিস পর্যন্ত মোট নিষ্কাশন সময় বিয়োগ H<sub>2</sub> থেকে অরিফিস পর্যন্ত অবশিষ্ট নিষ্কাশন সময়ের সমান।';
$ec_lang['odt_h1']='শুরুর হেড, H<sub>1</sub> (WSE &minus; কেন্দ্রচ্যুতি)';
$ec_lang['odt_q_max']='সর্বোচ্চ (শুরুর) প্রবাহ, Q<sub>max</sub>';
$ec_lang['odt_vol']='নিষ্কাশিত আয়তন';
$ec_lang['odt_sketch_start']='শুরু';
$ec_lang['odt_sketch_end']='শেষ';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='তীর থেকে তীর প্রস্থ';
$ec_lang['essc_mcr']='সর্বনিম্ন বক্ররেখা ব্যাসার্ধ';
$ec_lang['essc_q']='প্রবাহ, Q';
// Contact us.
$ec_lang['contact_title']='HawsEDC যোগাযোগ';
$ec_lang['contactSendMessage']='Tom Haws-কে বার্তা পাঠান';
$ec_lang['contactYourName']='আপনার নাম:';
$ec_lang['contactYourEmail']='আপনার ই-মেইল ঠিকানা:';
$ec_lang['contactSubject']='বিষয়:';
$ec_lang['contact_message']='বার্তা:';
$ec_lang['contactSpamPrefix']='পাঁচ যোগ এক সমান';
$ec_lang['contactSpamPostfix']='(ইংরেজিতে বানান করুন। 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='বার্তা পাঠান';

// Micro-Hydro Power
$ec_lang['mhp_main_menu']='মাইক্রো-হাইড্রো বিদ্যুৎ';
$ec_lang['mhp_main_title']='বিনামূল্যে অনলাইন মাইক্রো-হাইড্রো বিদ্যুৎ ক্যালকুলেটর';
$ec_lang['mhp_main_desc']='রান-অব-রিভার মাইক্রো-হাইড্রো বিদ্যুৎ উৎপাদন ক্যালকুলেটর';
$ec_lang['mhp_flow']='প্রবাহ হার, Q';
$ec_lang['mhp_gross_head']='মোট চাপ শীর্ষ (উচ্চতা পার্থক্য), H<sub>gross</sub>';
$ec_lang['mhp_head_loss']='পেনস্টক চাপ শীর্ষ ক্ষতি, h<sub>L</sub>';
$ec_lang['mhp_efficiency']='প্ল্যান্ট দক্ষতা, &eta; (0&ndash;1)';
$ec_lang['mhp_net_head']='নিট চাপ শীর্ষ, H<sub>net</sub>';
$ec_lang['mhp_power']='বিদ্যুৎ উৎপাদন, P';
$ec_lang['mhp_annual_kwh']='100% ক্ষমতায় বার্ষিক শক্তি';
$ec_lang['mhp_notes_1_term']='বিদ্যুৎ সমীকরণ';
$ec_lang['mhp_notes_1_def']='P = &eta; &times; &rho; &times; g &times; Q &times; H<sub>net</sub>, যেখানে &rho; = 1000 kg/m&sup3; (মিষ্টি পানি) এবং g = 9.806 m/s&sup2;.';
$ec_lang['mhp_notes_2_term']='নিট চাপ শীর্ষ';
$ec_lang['mhp_notes_2_def']='নিট চাপ শীর্ষ = মোট চাপ শীর্ষ &minus; পেনস্টক চাপ শীর্ষ ক্ষতি। একটি সাধারণ প্রাথমিক অনুমান হল h<sub>L</sub> &asymp; H<sub>gross</sub>-এর 5%। আরও সঠিক পেনস্টক ক্ষতির অনুমানের জন্য <a href="Darcy-Weisbach.php">ডার্সি-ওয়েইসবাখ ক্যালকুলেটর</a> ব্যবহার করুন।';
$ec_lang['mhp_notes_3_term']='দক্ষতা';
$ec_lang['mhp_notes_3_def']='মাইক্রো-হাইড্রোতে সাধারণ পেলটন এবং ক্রস-ফ্লো টার্বাইনের জন্য প্ল্যান্ট দক্ষতা &eta; সাধারণত 0.70 থেকে 0.85 পর্যন্ত থাকে। রক্ষণশীল প্রাথমিক অনুমান হিসেবে 0.75 ব্যবহার করুন।';
$ec_lang['mhp_notes_4_term']='বার্ষিক শক্তি';
$ec_lang['mhp_notes_4_def']='বার্ষিক শক্তি ধরে নেয় ক্রমাগত পূর্ণ-প্রবাহ পরিচালনা (8760 ঘন্টা/বছর)। মৌসুমি প্রবাহ পরিবর্তন, রক্ষণাবেক্ষণ বন্ধ এবং লোড ফ্যাক্টরের কারণে প্রকৃত উৎপাদন কম হবে।';
// Penstock Design
$ec_lang['ps_main_menu']='পেনস্টক ডিজাইন';
$ec_lang['ps_main_title']='বিনামূল্যে অনলাইন পেনস্টক ডিজাইন ক্যালকুলেটর';
$ec_lang['ps_main_desc']='মাইক্রো-হাইড্রো পেনস্টক আকার নির্ধারণ — মাথার ক্ষতি, শক্তি এবং বেগ';
$ec_lang['ps_flow']='প্রবাহ হার, Q';
$ec_lang['ps_gross_head']='মোট মাথা, H<sub>gross</sub>';
$ec_lang['ps_diameter']='পেনস্টক ব্যাস, D';
$ec_lang['ps_length']='পেনস্টক দৈর্ঘ্য, L';
$ec_lang['ps_roughness']='পাইপের রুক্ষতা, e';
$ec_lang['ps_km']='গৌণ ক্ষতি সহগ, k<sub>m</sub>';
$ec_lang['ps_nu']='গতিবিজ্ঞান সান্দ্রতা, &nu;, m<sup>2</sup>/s এ (20&deg;C কাছে জলের জন্য 1E-6)';
$ec_lang['ps_efficiency']='প্ল্যান্ট দক্ষতা, &eta; (0&ndash;1)';
$ec_lang['ps_velocity']='প্রবাহ বেগ, v';
$ec_lang['ps_vel_check']='বেগ পরীক্ষা';
$ec_lang['ps_f']='ঘর্ষণ গুণক, f';
$ec_lang['ps_hf']='ঘর্ষণ মাথার ক্ষতি, h<sub>f</sub>';
$ec_lang['ps_hm']='গৌণ মাথার ক্ষতি, h<sub>m</sub>';
$ec_lang['ps_hl']='মোট পেনস্টক ক্ষতি, h<sub>L</sub>';
$ec_lang['ps_hl_check']='মাথার ক্ষতি পরীক্ষা';
$ec_lang['ps_hnet']='নেট মাথা, H<sub>net</sub>';
$ec_lang['ps_power']='শক্তি আউটপুট, P';
$ec_lang['ps_annual_kwh']='100% ক্ষমতায় বার্ষিক শক্তি';
$ec_lang['ps_vel_ok']='1–3 m/s — লক্ষ্যমাত্রার মধ্যে ✓';
$ec_lang['ps_vel_low']='1 m/s এর নিচে — ব্যাস বাড়ান ⚠';
$ec_lang['ps_vel_high']='3 m/s এর উপরে — ব্যাস কমান ⚠';
$ec_lang['ps_hl_ok']='10% লক্ষ্যমাত্রার মধ্যে ✓';
$ec_lang['ps_hl_warn']='10% লক্ষ্যমাত্রা ছাড়িয়েছে — বড় পাইপ বিবেচনা করুন ⚠';
$ec_lang['ps_hl_bad']='20% ছাড়িয়েছে — পাইপ পুনরায় আকার দিন';
$ec_lang['ps_notes_1_term']='মাথার ক্ষতি';
$ec_lang['ps_notes_1_def']='মোট ক্ষতি h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, যেখানে h<sub>f</sub> = f(L/D)(v&sup2;/2g) ডার্সি-ওয়েইসবাক ঘর্ষণ ক্ষতি এবং h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g প্রবেশ, বাঁক এবং ভালভ কভার করে। নেট মাথা H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['ps_notes_2_term']='বেগ';
$ec_lang['ps_notes_2_def']='লক্ষ্য 1&ndash;3 m/s। 1 m/s এর নিচে পাইপ অতিরিক্ত বড়; 3 m/s এর উপরে ঘর্ষণ ক্ষতি এবং জলের হাতুড়ির ঝুঁকি বাড়ে।';
$ec_lang['ps_notes_3_term']='মাথার ক্ষতির লক্ষ্য';
$ec_lang['ps_notes_3_def']='মোট মাথার 10% এর নিচে পেনস্টক ক্ষতি সাধারণত অর্থনৈতিক। পাইপ খরচ এবং হারানো শক্তির মধ্যে সর্বোত্তম ভারসাম্য প্রায়শই উচ্চ-মূল্যের বিদ্যুৎ সাইটের জন্য 4&ndash;6% এর কাছাকাছি।';
$ec_lang['ps_notes_4_term']='গৌণ ক্ষতি k<sub>m</sub>';
$ec_lang['ps_notes_4_def']='সাধারণ মান: তীক্ষ্ণ প্রবেশ 0.5, প্রতিটি 45&deg; বাঁক 0.2&ndash;0.3, গেট ভালভ (সম্পূর্ণ খোলা) 0.1, বাটারফ্লাই ভালভ 0.2। সমস্ত ফিটিং যোগ করে মোট k<sub>m</sub> পাওয়া যায়। ডিফল্ট 1.5 একটি প্রবেশ এবং দুটি বাঁক অনুমান করে।';
$ec_lang['ps_notes_5_term']='পাইপের রুক্ষতা e';
$ec_lang['ps_notes_5_def']='সাধারণ পরম রুক্ষতা: ইস্পাত (নতুন) 0.046&nbsp;mm, ইস্পাত (ব্যবহৃত) 0.15&nbsp;mm, HDPE 0.003&nbsp;mm, PVC/uPVC 0.0015&nbsp;mm, কংক্রিট 0.3&ndash;3&nbsp;mm। HDPE ছোট মাইক্রো-হাইড্রো পেনস্টকের জন্য সাধারণ।';
