<?php

// Кириллица — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="доля";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_ft']="ft";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gал/мин";
$ec_lang['u_gradePercent']="% уклона";
$ec_lang['u_grade']="уклон";
$ec_lang['u_in2']="in^2";
$ec_lang['u_inh2o']="in H2O";
$ec_lang['u_in']="in";
$ec_lang['u_knpcm2']="кН/см^2";
$ec_lang['u_knpm2']="кН/м^2";
$ec_lang['u_kpa']="кПа";
$ec_lang['u_lps']="л/с";
$ec_lang['u_m2']="м^2";
$ec_lang['u_m3ps']="м^3/с";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="м вод.ст.";
$ec_lang['u_mld']="Мл/сут";
$ec_lang['u_m']="м";
$ec_lang['u_mm2']="мм^2";
$ec_lang['u_mmh2o']="мм вод.ст.";
$ec_lang['u_mm']="мм";
$ec_lang['u_mps']="м/с";
$ec_lang['u_npm2']="Н/м^2";
$ec_lang['u_pa']="Па";
$ec_lang['u_psf']="фунт/фут^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="с";
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['u_acft']="акр·фут";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="м^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='Калькуляторы HawsEDC';
$ec_lang['menu_main_list']='Список калькуляторов';
$ec_lang['menu_main_hydraulics']='Гидравлика';
$ec_lang['menu_main_language']='Язык';
$ec_lang['menu_more']='Ещё';
$ec_lang['template_welcome']='>> Оставьте страхи за дверью; здесь говорят на языке любви. Вы не разрушаете всё. Наслаждайтесь также <a target="_blank" href="https://hawsedc.com/download.php">бесплатными инструментами HawsEDC для AutoCAD.</a> <<';
$ec_lang['template_translation_help']='Есть ли у вас отличная идея для калькулятора, который можно добавить сюда?  Можете ли вы помочь мне улучшить переводы, программирование или хостинг этих калькуляторов?  ';
$ec_lang['template_feedback']='Пожалуйста, поделитесь вашими ценными замечаниями или похвалой. Превзошёл ли этот бесплатный калькулятор ваши ожидания?';
$ec_lang['template_printable_title']='Печатный заголовок';
$ec_lang['template_printable_subtitle']='Печатный подзаголовок';
$ec_lang['index_title']='Бесплатные инженерные калькуляторы онлайн';
$ec_lang['calc_set_units']='Установить единицы:';
$ec_lang['calc_defaults']='Значения по умолчанию';
$ec_lang['calc_defaults_confirm']='Reset calculator to factory defaults?';
$ec_lang['points_data_help']='(или Копировать/Вставить через область данных)';
$ec_lang['points_data_title']='Данные точек<br />(разделены запятой или табуляцией)';
$ec_lang['points_data_copy']='Копировать';
$ec_lang['points_data_paste']='Вставить';
$ec_lang['calc_inputs']='Входные данные';
$ec_lang['calc_results']='Результаты';
$ec_lang['view_hide_line']='[Скрыть эту строку]';
$ec_lang['view_printable']='Версия для печати (обновить страницу для восстановления)';
$ec_lang['ec_name_label']='Сохранить этот расчёт:';
$ec_lang['ec_name_placeholder']='Имя';
$ec_lang['ec_name_hint']='Сохраняет входные данные в URL для сохранения в закладках, получения из истории и обмена';
$ec_lang['calc_copy_link']='Copy link';
$ec_lang['calc_copy_link_done']='Copied!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='Потери давления в трубе Дарси-Вейсбах';
$ec_lang['dw_main_title']='Бесплатный онлайн калькулятор потерь давления Дарси-Вейсбах';
$ec_lang['dw_main_desc']='Потери давления в трубе по Дарси-Вейсбах при заданных диаметре, шероховатости и расходе';
$ec_lang['dw_roughness']='Абсолютная шероховатость Дарси-Вейсбах, e';
$ec_lang['dw_kinematic_viscosity']='Кинематическая вязкость, ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Число Рейнольдса, Re';
$ec_lang['dw_flow_regime']='Режим течения';
$ec_lang['dw_regime_laminar']='ламинарный';
$ec_lang['dw_regime_transitional']='переходный';
$ec_lang['dw_regime_turbulent']='турбулентный';
$ec_lang['dw_friction_factor_method']='Метод коэффициента трения';
$ec_lang['dw_friction_factor']='Коэффициент трения, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='Потери давления в трубе Хазен-Уильямс';
$ec_lang['hw_main_title']='Бесплатный онлайн калькулятор потерь давления Хазен-Уильямс';
$ec_lang['hw_main_desc']='Потери давления в трубе по Хазен-Уильямс при заданных диаметре, шероховатости и расходе';
$ec_lang['hw_hgl_1']='ГГЛ ниже по потоку';
$ec_lang['hw_hgl_2']='ГГЛ выше по потоку';
$ec_lang['hw_roughness']='Коэффициент Хазен-Уильямс, C';
// Manning Irregular
$ec_lang['mi_menu']='Неправильное русло Manning';
$ec_lang['mi_main_title']='Бесплатный онлайн калькулятор неправильного русла по Маннингу';
$ec_lang['mi_main_desc']='Калькулятор равномерного течения в неправильном русле по Маннингу';
$ec_lang['mi_waterSurfaceElevation']='Отметка уровня воды';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Точки поперечного сечения';
$ec_lang['mi_groupPoint']='Точка';
$ec_lang['mi_groupSegment']='Сегмент';
$ec_lang['mi_groupRegion']='Зона';
$ec_lang['mi_station']='Пикет';
$ec_lang['mi_elevation']='Отм.';
$ec_lang['mi_d50in']='Средний<br />размер<br />камня<br />крепления';
$ec_lang['mi_n']='n<br />сег-<br />мента';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />граница<br />зоны<br />(Берег)';
$ec_lang['mi_tau']='Дон. кас.<br />напр. τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='Составной<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Примечания';
$ec_lang['mi_notes_1_term']='Составной n';
$ec_lang['mi_notes_1_def']='Этот калькулятор следует справочному руководству HEC-RAS при расчёте составного n зоны по Chow 1959, стр. 136, уравнение 6-17 (не 6-18).';
$ec_lang['mi_notes_2_term']='Каменное крепление';
$ec_lang['mi_notes_2_def']='Для проектирования каменного крепления используйте Калькулятор трапецеидального канала Маннинга. Этот калькулятор больше подходит для природных сечений.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Расход в трубе по Маннингу';
$ec_lang['mpf_main_title']='Бесплатный онлайн калькулятор расхода в трубе по Маннингу';
$ec_lang['mpf_main_desc']='Формула Маннинга для равномерного течения в трубе при заданном уклоне и глубине';
$ec_lang['mpf_spreadheet_notice']='Ознакомьтесь с версией этого калькулятора в виде таблицы';
$ec_lang['mpf_pipe_diameter']='Диаметр трубы, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Коэффициент шероховатости Маннинга, n';
$ec_lang['mpf_friction_slope']='Уклон пьезометрической линии (возможно <a target="_blank" href="../pressureslope.php">?</a> равен уклону трубы), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Относительная глубина наполнения, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(См. примечания)';
$ec_lang['mpf_flow']='Расход, Q';
$ec_lang['mpf_velocity']='Скорость, v';
$ec_lang['mpf_velocity_head']='Скоростной напор, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Площадь живого сечения, a';
$ec_lang['mpf_pipe_area']='Площадь сечения трубы, a0';
$ec_lang['mpf_area_ratio']='Относительная площадь, a/a0';
$ec_lang['mpf_wetted_perimeter']='Смоченный периметр, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Гидравлический радиус, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Ширина по зеркалу воды, T';
$ec_lang['mpf_froude_number']='Число Фруда, F';
$ec_lang['mpf_shear_stress']='Среднее касательное напряжение (влекущая сила), tau';
$ec_lang['mpf_full_flow']='Расход при полном сечении, Q0';
$ec_lang['mpf_full_flow_ratio']='Отношение к полному расходу, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Это расход и глубина внутри <em>бесконечно длинной</em> трубы.</dt><dd>Для подачи расхода в трубу может потребоваться значительно большая высота уровня воды. Добавьте не менее 1,5 скоростного напора к глубине или <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">см. 2-минутное руководство</a> по стандартным расчётам водопропускных труб с помощью HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Найти y/d<sub>0</sub> при заданном Q';
$ec_lang['mpf_solve_desc']='Используя D<sub>0</sub>, n и S<sub>0</sub> из формы, находит наименьшее y/d<sub>0</sub> для заданного Q.';
$ec_lang['mpf_solve_button']='Вычислить';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='Потери напора в трубе по Маннингу';
$ec_lang['mphl_main_title']='Бесплатный онлайн калькулятор потерь напора в трубе по Маннингу';
$ec_lang['mphl_main_desc']='Формула Маннинга потери напора при полном расходе';
$ec_lang['mphl_pipe_length']='Длина трубы, L';
$ec_lang['mphl_area']='Площадь, A';
$ec_lang['mphl_total_junction_k']='Суммарный коэффициент местных потерь, k';
$ec_lang['mphl_friction_slope']='Гидравлический уклон';
$ec_lang['mphl_friction_loss']='Потери на трение, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Местные потери, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Суммарные потери, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='НЭЛ ниже по потоку';
$ec_lang['mphl_egl_2']='НЭЛ выше по потоку';
$ec_lang['mphl_hgl_2']='ГГЛ в трубе выше по потоку ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Для условия открытого входа (водопропускная труба) необходимо проверить условия управления на входе.</dt><dd>1. ГГЛ выше по потоку не может быть ниже отметки нормальной глубины течения выше по потоку (и не ниже самой трубы!).</dd><dd>2. Подпор водопропускной трубы лучше представляется НЭЛ, чем ГГЛ выше по потоку.</dd><dd>3. См. <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">2-минутное руководство</a> по простым стандартным расчётам подпора водопропускных труб с помощью HY-8.</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='Трапецеидальный канал Маннинга';
$ec_lang['mtc_main_title']='Бесплатный онлайн калькулятор трапецеидального канала по Маннингу';
$ec_lang['mtc_main_desc']='Формула Маннинга равномерного течения в трапецеидальном канале при заданном уклоне и глубине';
$ec_lang['mtc_bottom_width']='Ширина дна, b';
$ec_lang['mtc_side_slope_1']='Откос 1, z1 (гориз./верт.)';
$ec_lang['mtc_side_slope_2']='Откос 2, z2 (гориз./верт.)';
$ec_lang['mtc_channel_slope']='Уклон канала, S';
$ec_lang['mtc_flow_depth']='Глубина потока, y';
$ec_lang['mtc_bend_angle']='Угол поворота, β <a target="_blank" href="riprap-bend-angle.png" title="Нажмите для изображения">?</a> (для подбора каменной наброски)';
$ec_lang['mtc_sgrock']='Удельный вес камня, SG (2,65)';
$ec_lang['mtc_d50_in']='Расчётный размер камня, D50';
$ec_lang['mtc_n_strickler']='n для расчётного размера камня по Стриклеру';
$ec_lang['mtc_n_blodgett']='n для расчётного размера камня по Блодгетту';
$ec_lang['mtc_n_bathurst']='n для расчётного размера камня по Батхёрсту';
$ec_lang['mtc_blodgett_v_bathurst']='Блодгетт vs. Батхёрст';
$ec_lang['mtc_d50_bottom']='Требуемый размер угловатого камня на дне, D50 (Isbash & MC) <span title="По Isbash (1936) и Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Требуемый размер угловатого камня откос 1, D50 (Isbash & MC) <span title="По Isbash (1936) и Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Требуемый размер угловатого камня откос 2, D50 (Isbash & MC) <span title="По Isbash (1936) и Maricopa County, Arizona, USA." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Требуемый размер угловатого камня, D50 (Maynord, Ruff и Abt 1989)';
$ec_lang['mtc_d50_searcy']='Требуемый размер угловатого камня, D50 (Searcy 1967)';
$ec_lang['mtc_vel_check']='Проверка скорости';
$ec_lang['mtc_vel_ok']='Скорость приемлема для допущений равномерного течения.';
$ec_lang['mtc_vel_high']='Скорость высокая - проверьте потери в местах перехода, имеющуюся энергию и риск гидравлического удара.';
$ec_lang['mtc_vel_low']='Скорость низкая — риск заиления.';
$ec_lang['mtc_vel_ok_short']='Хорошо';
$ec_lang['mtc_vel_high_short']='Высокая';
$ec_lang['mtc_vel_low_short']='Низкая';
$ec_lang['mtc_note_1']='<dl><dt>Автоматическая итерация подбора камня и шероховатости</dt><dd>Выберите переключатель шероховатости (рекомендуется BB) и переключатель расчётного размера камня (рекомендуется Isbash). Подберите глубину и коэффициент надёжности камня для получения желаемого расхода с равномерным размером камня. При каждом изменении входного значения запускается итерационный цикл: 1. Шероховатость вычисляется из расчётного размера камня. 2. Требуемое значение шероховатости копируется во входную шероховатость. 3. Расход в канале и требуемый размер камня вычисляются. 4. Расчётный размер камня корректируется. 5. Повторять до достижения малой погрешности в расчётном размере камня.</dd><dt>Базовый калькулятор (без итерации)</dt><dd>Введите желаемое значение шероховатости. Игнорируйте поле ввода расчётного размера камня.</dd></dl>';
$ec_lang['mtc_note_2_term']='Проверка скорости';
$ec_lang['mtc_note_2_def']='Высокая скорость означает высокую удельную энергию от имеющегося перепада. Эта энергия может быть быстро потеряна на расширениях, поворотах или препятствиях. Убедитесь, что это приемлемо для данного участка.';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Простой водослив';
$ec_lang['ws_main_title']='Бесплатный онлайн калькулятор широкопорогового водослива';
$ec_lang['ws_main_desc']='Калькулятор расхода через широкопороговый водослив';
$ec_lang['ws_weirLength']='Длина водослива, l';
$ec_lang['ws_headWaterHeight']='Высота напора, h';
$ec_lang['ws_weirCoefficient']='Коэффициент водослива, Cw';
$ec_lang['ws_notes_heading']='Примечания';
$ec_lang['ws_notes_we_term']='Уравнение водослива';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='Водослив сложного профиля';
$ec_lang['wi_main_title']='Бесплатный онлайн калькулятор водослива сложного профиля с переменной глубиной';
$ec_lang['wi_main_desc']='Калькулятор расхода через водослив сложного профиля';
$ec_lang['wi_headWaterelevation']='Отметка верхнего бьефа';
$ec_lang['wi_weirPoints']='Точки водослива';
$ec_lang['wi_station']='Пикет';
$ec_lang['wi_elevation']='Отм.';
$ec_lang['wi_pondingHeight']='Высота подпора';
$ec_lang['wi_incrementalFlow']='Дополнительный расход';
$ec_lang['wi_cumulativeFlow']='Суммарный расход';
$ec_lang['wi_save_and_calculate']='Сохранить и вычислить';
$ec_lang['wi_notes_we_term']='Уравнение водослива';
$ec_lang['wi_notes_we_def']='q = если (длина = 0) то 0, если (уклон=0) то cw*длина*d<sub>0</sub><sup>1.5</sup>, иначе cw/(2.5*уклон) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) где d<sub>1</sub> и d<sub>0</sub> всегда положительные или нулевые';
// Orifice Flow
$ec_lang['or_main_menu']='Расход через отверстие';
$ec_lang['or_main_title']='Бесплатный онлайн калькулятор расхода через отверстие';
$ec_lang['or_main_desc']='Расход через отверстие — свободный или затопленный';
$ec_lang['or_shape']='Форма отверстия';
$ec_lang['or_shape_circular']='Круглое';
$ec_lang['or_shape_rectangular']='Прямоугольное';
$ec_lang['or_diameter']='Диаметр или высота, D <span title="Diameter for circular; height for rectangular" class="ec-tip">?</span>';
$ec_lang['or_width']='Ширина, W <span title="Rectangular openings only" class="ec-tip">?</span>';
$ec_lang['or_invert']='Отметка низа <span title="Bottom of opening" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Отметка верхнего бьефа';
$ec_lang['or_twe']='Отметка нижнего бьефа';
$ec_lang['or_cd']='Коэффициент расхода, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Отметка центроида';
$ec_lang['or_head']='Действующий напор, h';
$ec_lang['or_area']='Площадь отверстия, A';
$ec_lang['or_flow']='Расход, Q';
$ec_lang['or_velocity']='Скорость, v';
$ec_lang['or_regime']='Проверка режима истечения';
$ec_lang['or_regime_valid']='Свободное истечение — режим отверстия действителен ✓';
$ec_lang['or_regime_submerged']='Затопленное отверстие (TWE выше центроида) — действителен ✓';
$ec_lang['or_regime_warn']='Предупреждение: верхний бьеф ниже шелыги — не режим отверстия';
$ec_lang['or_regime_twe_above_hwe']='Предупреждение: нижний бьеф (TWE) выше верхнего (HWE) — проверьте входные данные';
$ec_lang['or_notes_1_term']='Уравнение отверстия';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Свободное: h = HWE − центроид. Затопленное (TWE выше низа): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Режим истечения';
$ec_lang['or_notes_2_def']='Уравнения истечения через отверстие применяются, когда верхний бьеф выше шелыги отверстия. Если ниже — используйте уравнение водослива.';
$ec_lang['or_notes_3_term']='Коэффициент расхода';
$ec_lang['or_notes_3_def']='C<sub>d</sub> составляет примерно 0,60–0,65 для острокромочных отверстий. Скруглённые или заглублённые входы имеют иные значения. См. <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> или Гидравлическое справочное руководство HEC-RAS.';
$ec_lang['or_notes_4_term']='Затопление';
$ec_lang['or_notes_4_def']='Когда TWE выше низа отверстия, калькулятор автоматически применяет уравнение затопленного отверстия с h = HWE − TWE. Когда TWE на уровне низа или ниже — предполагается свободное истечение и h = HWE − центроид.';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Микро-ГЭС';
$ec_lang['mhp_main_title']='Бесплатный онлайн-калькулятор мощности микро-ГЭС';
$ec_lang['mhp_main_desc']='Калькулятор выработки мощности русловой микро-ГЭС';
$ec_lang['mhp_flow']='Расход, Q';
$ec_lang['mhp_gross_head']='Брутто-напор, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Диаметр пенстока, D';
$ec_lang['mhp_length']='Длина пенстока, L';
$ec_lang['mhp_roughness']='Шероховатость трубы, e';
$ec_lang['mhp_km']='Коэффициент местных потерь, k<sub>m</sub> <span title="Sum of all junction and fitting loss coefficients along the penstock" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Кинематическая вязкость, ν <span title="1×10⁻⁶ m²/s for clean water near 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='КПД установки, η (0–1)';
$ec_lang['mhp_velocity']='Скорость потока, v';
$ec_lang['mhp_vel_check']='Проверка скорости';
$ec_lang['mhp_f']='Коэффициент трения, f';
$ec_lang['mhp_hf']='Потери напора на трение, h<sub>f</sub>';
$ec_lang['mhp_hm']='Потери напора, h<sub>m</sub>';
$ec_lang['mhp_hl']='Суммарные потери в пенстоке, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Проверка потерь напора';
$ec_lang['mhp_hnet']='Нетто-напор, H<sub>net</sub>';
$ec_lang['mhp_power']='Выходная мощность, P';
$ec_lang['mhp_annual_kwh']='Годовая выработка при 100% загрузке';
$ec_lang['mhp_vel_ok']='1–3 м/с — в пределах нормы ✓';
$ec_lang['mhp_vel_low']='Скорость низкая - риск заиления и вовлечения воздуха.';
$ec_lang['mhp_vel_high']='Скорость высокая - проверьте потери в местах перехода, имеющуюся энергию и риск гидравлического удара.';
$ec_lang['mhp_vel_ok_short']='Хорошо';
$ec_lang['mhp_vel_high_short']='Высокая';
$ec_lang['mhp_vel_low_short']='Низкая';
$ec_lang['mhp_hl_ok']='в пределах 10% от нормы ✓';
$ec_lang['mhp_hl_warn']='превышает 10% — рассмотрите трубу большего диаметра ⚠';
$ec_lang['mhp_hl_bad']='превышает 20% — пересчитайте трубу';
$ec_lang['mhp_notes_1_term']='Потери напора';
$ec_lang['mhp_notes_1_def']='Суммарные потери h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, где h<sub>f</sub> = f(L/D)(v²/2g) — потери на трение по Дарси–Вейсбаху, а h<sub>m</sub> = k<sub>m</sub>·v²/2g учитывает вход, повороты и задвижки. Нетто-напор H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Скорость';
$ec_lang['mhp_notes_2_def']='Целевая скорость 1–3 м/с. Ниже 1 м/с труба избыточно большая; выше 3 м/с возрастают гидравлические потери и риск гидравлического удара.';
$ec_lang['mhp_notes_3_term']='Допустимые потери напора';
$ec_lang['mhp_notes_3_def']='Потери в пенстоке менее 10% от брутто-напора, как правило, экономически оправданы. Оптимальный компромис между стоимостью трубы и потерянной мощностью обычно составляет 4–6% для объектов с высокой ценностью электроэнергии.';
$ec_lang['mhp_notes_4_term']='Местные потери k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Типичные значения: острый вход 0.5, каждый отвод 45° — 0.2–0.3, задвижка (полностью открыта) 0.1, дисковый затвор 0.2. Сумма всех фитингов даёт суммарный k<sub>m</sub>. Значение по умолчанию 1.5 предполагает один вход и два отвода.';
$ec_lang['mhp_notes_5_term']='Шероховатость трубы e';
$ec_lang['mhp_notes_5_def']='Типичная абсолютная шероховатость: сталь (новая) 0.046 мм, сталь (б/у) 0.15 мм, HDPE 0.003 мм, ПВХ/uPVC 0.0015 мм, бетон 0.3–3 мм. HDPE широко используется в пенстоках малых микро-ГЭС.';
$ec_lang['mhp_notes_6_term']='КПД';
$ec_lang['mhp_notes_6_def']='Типичный КПД установки &eta; составляет от 0,70 до 0,85 для турбин Пелтона и поперечно-осевых турбин, распространённых в малой гидроэнергетике. Используйте 0,75 в качестве консервативной первоначальной оценки.';
$ec_lang['mhp_notes_7_term']='Годовая выработка энергии';
$ec_lang['mhp_notes_7_def']='Годовая выработка рассчитана при непрерывной работе на полном расходе (8760 часов/год). Фактическая выработка будет ниже вследствие сезонных колебаний расхода, простоев на техническое обслуживание и коэффициента нагрузки.';

// Orifice Drain Time
$ec_lang['odt_main_menu']='Время опорожнения через отверстие';
$ec_lang['odt_main_title']='Бесплатный онлайн калькулятор времени опорожнения через отверстие';
$ec_lang['odt_main_desc']='Время опорожнения пруда через отверстие — Метод конического объёма';
$ec_lang['odt_h1_elev']='Начальная отметка УВ <span title="Starting water surface elevation" class="ec-tip">?</span>';
$ec_lang['odt_a1']='Начальная площадь, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Конечная отметка УВ';
$ec_lang['odt_h_orifice']='Отметка центроида отверстия';
$ec_lang['odt_a0']='Площадь на отметке отверстия, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Конечная площадь, A<sub>2</sub> <span title="Interpolated from conic model at ending elevation" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='Проверка конечной отметки';
$ec_lang['odt_h2_ok']='Конечная отметка выше верха отверстия ✓';
$ec_lang['odt_h2_warn']='Предупреждение: конечная отметка на уровне или ниже верха отверстия (центроид + D/2)';
$ec_lang['odt_d']='Диаметр отверстия, D <span title="Diameter (circular) or height (rectangular)" class="ec-tip">?</span>';
$ec_lang['odt_w']='Ширина отверстия, W <span title="Rectangular only" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='Время опорожнения (с)';
$ec_lang['odt_t_min']='Время опорожнения (мин)';
$ec_lang['odt_t_hr']='Время опорожнения (ч)';
$ec_lang['odt_t_day']='Время опорожнения (дн)';
$ec_lang['odt_notes_1_term']='Формула';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) даёт время опорожнения от напора H до отверстия. Время = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), где H<sub>1</sub> = нач. отм. − отм. отв., H<sub>2</sub> = кон. отм. − отм. отв.';
$ec_lang['odt_notes_2_term']='Метод';
$ec_lang['odt_notes_2_def']='Метод конического объёма моделирует пруд как конический раздел между начальной площадью A<sub>1</sub> у начального уровня и площадью A<sub>0</sub> на отметке центроида отверстия. A<sub>2</sub> интерполируется из A<sub>1</sub> и A<sub>0</sub> по конической модели. Время опорожнения от начального до конечного уровня равно полному времени от H<sub>1</sub> до отверстия минус оставшееся время от H<sub>2</sub> до отверстия.';
$ec_lang['odt_h1']='Начальный напор, H<sub>1</sub> <span title="Starting WSE minus orifice centroid elevation" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='Макс расход, Q<sub>max</sub>';
$ec_lang['odt_vol']='Слитый объём';
$ec_lang['odt_sketch_start']='Начало';
$ec_lang['odt_sketch_end']='Конец';
// Erosion Setback and Scour Calc.
$ec_lang['essc_btbw']='Ширина между берегами';
$ec_lang['essc_mcr']='Минимальный радиус кривой';
$ec_lang['essc_q']='Расход, Q';
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='Ирригация';
$ec_lang['irr_main_title']='Бесплатные онлайн-калькуляторы измерения расхода ирригации';
$ec_lang['irr_main_desc']='Измерение расхода ирригации — водосливы и отверстия';
$ec_lang['irr_intro_html']='<p>Водосливы и отверстия — стандартные полевые инструменты для измерения расхода воды в ирригационных системах. Выберите калькулятор, соответствующий вашему сооружению:</p>';
$ec_lang['irr_card_weir_uniform_head']='Водослив — Широкий Порог (Равномерная Ширина)';
$ec_lang['irr_card_weir_uniform_desc']='Измерьте расход воды через гребень водоотводной плотины, регулирующее сооружение или водосливную доску. Введите длину водослива и глубину воды над порогом.';
$ec_lang['irr_card_weir_irregular_head']='Водослив — Нерегулярный Профиль';
$ec_lang['irr_card_weir_irregular_desc']='Используйте, когда гребень водослива не имеет единой равномерной отметки — природные перепады, перепадные сооружения с переменной шириной или многосекционные регулирующие сооружения.';
$ec_lang['irr_card_orifice_head']='Отверстие — Головной Затвор или Трубный Выпуск';
$ec_lang['irr_card_orifice_desc']='Измерьте расход через шандорный затвор, трубный выпуск или отверстие водопропуска. Автоматически обрабатывает как свободное истечение, так и подтопленные условия (подпор с нижнего бьефа).';
$ec_lang['irr_card_canal_head']='Проектирование & Анализ Канала';
$ec_lang['irr_card_canal_desc']='Проектируйте или проверяйте ирригационный канал по формуле Маннинга. Используйте трапецеидальный калькулятор для новых каналов; калькулятор для нерегулярных сечений — для существующих природных или искусственных.';
$ec_lang['irr_card_seepage_head']='Фильтрация из Канала & КПД Водоподачи';
$ec_lang['irr_card_seepage_desc']='Оцените фильтрационные потери из канального участка по измеренным притоку и оттоку. Рассчитайте КПД водоподачи и годовые потери воды для обоснования целесообразности устройства облицовки.';
$ec_lang['irr_quickref_html']='<h3>Краткий Справочник</h3><dl><dt>Водоотводная плотина или регулирующее сооружение</dt><dd>Измерьте глубину воды над гребнем водослива. Используйте <a href="Weir-Flow-Simple.php">Простой Водослив</a> для равномерного гребня или <a href="Weir-Flow-Irregular.php">Нерегулярный Водослив</a> для профилированного или ступенчатого гребня.</dd><dt>Головной затвор или трубный выпуск</dt><dd>Измерьте отметку воды в верхнем и нижнем бьефе (или отметку лотка при свободном истечении). Используйте <a href="Orifice.php">Расход через Отверстие</a>. Для круглой трубы D = диаметр трубы; для прямоугольного затвора введите ширину W и высоту D.</dd><dt>Время опорожнения водохранилища или пруда</dt><dd>Используйте <a href="Orifice-Drain-Time.php">Время Опорожнения через Отверстие</a>, чтобы оценить, сколько времени потребуется для снижения уровня пруда или водохранилища через донное отверстие — полезно для планирования ирригационных накопителей.</dd><dt>Полевые стандарты</dt><dd>Уравнения расхода через водослив и отверстие, используемые здесь, соответствуют процедурам <em>Руководства по Измерению Воды</em> USBR (3-е изд.), которые обычно требуются водохозяйственными службами и ирригационными округами.</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='Расстояние эмиттеров, S<sub>e</sub>';
$ec_lang['ip_sl']='Расстояние рядов, S<sub>l</sub>';
$ec_lang['ip_n_e']='Эмиттеры на латерал, n<sub>e</sub>';
$ec_lang['ip_n_l']='Латералы на зону, n<sub>l</sub>';
$ec_lang['ip_d']='Целевая глубина полива, d';
$ec_lang['ip_a_e']='Площадь на один эмиттер, A<sub>e</sub>';
$ec_lang['ip_pr']='Норма орошения, PR';
$ec_lang['ip_q_lat']='Расход на латерал, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='Расход зоны, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='Время полива (ч)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Фильтрация из Канала';
$ec_lang['cs_main_title']='Бесплатный Онлайн-Калькулятор Потерь на Фильтрацию из Канала и КПД Водоподачи';
$ec_lang['cs_main_desc']='Потери на Фильтрацию из Канала & КПД Водоподачи — Метод Баланса Расходов';
$ec_lang['cs_Q_in']='Приток, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Отток, Q<sub>out</sub>';
$ec_lang['cs_L']='Длина участка, L';
$ec_lang['cs_wp']='Смоченный периметр, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='Расход фильтрационных потерь, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Проверка измерений';
$ec_lang['cs_pct_loss']='Доля потерь';
$ec_lang['cs_Ec']='КПД водоподачи, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Оценка КПД';
$ec_lang['cs_Vol_day']='Суточный объём потерь';
$ec_lang['cs_Vol_year']='Годовой объём потерь';
$ec_lang['cs_Q_loss_per_L']='Потери на единицу длины, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Стоимость воды';
$ec_lang['cs_lining_cost']='Стоимость облицовки';
$ec_lang['cs_Ec_target']='Целевой КПД, E<sub>c,target</sub> <span title="Целевой КПД водоподачи после облицовки; доля 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Площадь облицовки, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Годовая стоимость потерь';
$ec_lang['cs_annual_value_recovered']='Годовая стоимость восстановлена';
$ec_lang['cs_lining_total_cost']='Суммарная стоимость';
$ec_lang['cs_payback_years']='Период окупаемости <span title="Simple payback = total lining cost ÷ annual value recovered" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — фильтрация обнаружена ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — измеримых потерь нет';
$ec_lang['cs_loss_negative']='Предупреждение: Qout > Qin — проверьте измерения ⚠';
$ec_lang['cs_Ec_good']='Хорошо — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Удовлетворительно — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Плохо — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Метод';
$ec_lang['cs_notes_1_def']='Метод баланса расходов оценивает фильтрацию путём измерения расхода у входа и выхода канального участка: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. КПД водоподачи E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Годовой объём рассчитан при непрерывной работе на полном расходе; фактические потери ниже для сезонных или частично загруженных каналов.';
$ec_lang['cs_notes_2_term']='Оценочные показатели КПД';
$ec_lang['cs_notes_2_def']='Типичные незакреплённые земляные каналы: E<sub>c</sub> = 60–80%. Хорошо ухоженные земляные каналы: 75–85%. Каналы с бетонным лотком: 90–98%. Фильтрационные потери свыше 30% от притока, как правило, обосновывают устройство облицовки. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Период окупаемости облицовки';
$ec_lang['cs_notes_3_def']='Введите стоимость воды и стоимость облицовки в любой согласованной валюте. Площадь облицовки = длина участка × смоченный периметр — смоченный периметр поперечного сечения канала на измеренной глубине потока (ширина дна плюс оба смоченных откоса). Годовая восстановленная стоимость предполагает, что облицованный канал достигает целевого E<sub>c</sub> постоянно. Фактический период окупаемости будет больше для сезонных каналов или если облицовка не достигает целевого КПД.';
$ec_lang['cs_notes_4_term']='Источник';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3-е изд. (2001). FAO Irrigation and Drainage Paper 57 (1999).';
// About
$ec_lang['about_main_menu']='О нас';
$ec_lang['install_main_menu']='Установить';
$ec_lang['install_main_title']='Установить EngCalcs';
$ec_lang['install_main_desc']='Добавить на устройство для работы офлайн';
$ec_lang['contact_main_menu']='Контакт';
$ec_lang['about_main_title']='Об инженерных калькуляторах HawsEDC';
$ec_lang['about_main_desc']='Миссия, открытый исходный код и вклад';
$ec_lang['about_body_html']='<h3>Миссия</h3><p>Инженерные Калькуляторы HawsEDC созданы для инженеров и полевых работников по всему миру — особенно тех, кто работает в регионах с дефицитом воды, ограниченными ресурсами или слабым обеспечением. Эти инструменты являются частью более широкой гуманитарной миссии: сказать каждому человеку наиболее практичным и эффективным способом, что он любим и дорог навсегда, что ему нечего бояться и что он не разрушит всё.</p><p>Калькуляторы — это средство. Цель — мир, свободный от страданий.</p><h3>Лицензия с Открытым Исходным Кодом</h3><p>Весь код выпущен под <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Стандартной Общественной Лицензией GNU v3.0 или более поздней версии</a> — свободный как в смысле свободы. Вы можете использовать, изучать, изменять и распространять код на тех же условиях.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Исходный Код</h3><p>Полный исходный код общедоступен на Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Там можно просматривать код, сообщать о проблемах или форкнуть репозиторий.</p><h3>Вклад</h3><p>Pull-запросы приветствуются. Способы участия:</p><ul><li><strong>Переводы</strong> — улучшите или добавьте язык. Откройте pull-запрос с изменениями в соответствующем файле <code>lib/lang.ec.??.php</code>.</li><li><strong>Отчёты об ошибках</strong> — используйте форму обратной связи на любой странице калькулятора или сообщите о проблеме на Bitbucket.</li><li><strong>Новые калькуляторы</strong> — идеи для гидравлических инженерных инструментов для полевых работников и специалистов по орошению особенно приветствуются. См. руководство разработчика <code>CLAUDE.md</code> в репозитории.</li><li><strong>Хостинг</strong> — если вы можете разместить зеркало этих калькуляторов для региона с ограниченным интернетом, пожалуйста, свяжитесь с нами.</li></ul><h3>Работа без интернета</h3><p>Эти калькуляторы работают как прогрессивное веб-приложение (PWA). Откройте любую страницу калькулятора при наличии интернета, и браузер автоматически сохранит все калькуляторы в кэш. После этого все калькуляторы работают офлайн — интернет не нужен.</p><p>На Android или iOS используйте функцию «Добавить на главный экран» в браузере, чтобы установить EngCalcs как приложение на вашем устройстве. На компьютере ищите значок установки в адресной строке браузера.</p><p>Вы также можете сохранить любой отдельный калькулятор через меню «Сохранить как…» в браузере для разового использования офлайн.</p><h3>Контакт</h3><p>Tom Haws — гидравлический инженер и автор этих калькуляторов.<br />Используйте форму обратной связи на любой странице калькулятора или перейдите к исходному коду на <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';
$ec_lang['contact_title']='Контакт HawsEDC';
$ec_lang['contactSendMessage']='Отправить сообщение Tom Haws';
$ec_lang['contactYourName']='Ваше имя:';
$ec_lang['contactYourEmail']='Ваш адрес e-mail:';
$ec_lang['contactSubject']='Тема:';
$ec_lang['contact_message']='Сообщение:';
$ec_lang['contactSpamPrefix']='Пять плюс один равно';
$ec_lang['contactSpamPostfix']='(Пожалуйста, напишите по-английски. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Отправить сообщение';
$ec_lang['contact_success']='Спасибо, что потратили время на письмо.';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='Проектирование Каменного Лотка (Robinson)';
$ec_lang['rc_main_title']='Бесплатный Онлайн-Калькулятор Проектирования Каменного Лотка — Robinson (1998)';
$ec_lang['rc_main_desc']='Подбор Размера Каменной Наброски для Лотка — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Уклон дна лотка, S<sub>0</sub>';
$ec_lang['rc_qt']='Удельный расход, q<sub>t</sub> <span title="Расход на единицу ширины у входа в лоток. Для канала с шириной дна B и полным расходом Q используйте q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Пористость каменной наброски, n<sub>p</sub>';
$ec_lang['rc_sg']='Удельный вес камня, sg <span title="Типичный дроблёный гранит или базальт ≈ 2,65. Диапазон по Robinson: 2,54 до 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Градационное СО SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Стандартное отклонение градационного состава. Однородный камень ≈ 1,25. Диапазон по Robinson: 1,15 до 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Нормальная глубина во входном канале, y<sub>n</sub> <span title="Подпор (Hp > yn) — это хорошо: снижает эрозию выше по течению. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Требуемый медианный размер камня, D<sub>50</sub> <span title="Ур. 1 (S0 < 0,10) или Ур. 2 (0,10–0,40). Действителен: D50 15–278 мм, S0 0,02–0,40. За пределами диапазона: экстраполяция." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Применённое уравнение';
$ec_lang['rc_sg_check']='Проверка удельного веса';
$ec_lang['rc_SD_check']='Проверка градационного СО';
$ec_lang['rc_sg_ok']   ='sg в допустимом диапазоне (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Предупреждение: sg < 2,54 — ниже диапазона Robinson';
$ec_lang['rc_sg_high'] ='Предупреждение: sg > 2,82 — выше диапазона Robinson';
$ec_lang['rc_SD_ok']   ='SD в допустимом диапазоне (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Предупреждение: SD < 1,15 — ниже диапазона Robinson';
$ec_lang['rc_SD_high'] ='Предупреждение: SD > 1,47 — выше диапазона Robinson';
$ec_lang['rc_layer']='Толщина слоя наброски (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Радиус кривой гребня (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Длина дуги кривой гребня';
$ec_lang['rc_apron_length']='Длина выходного порога (15 × D<sub>50</sub>) <span title="Необходима для конструктивной поддержки камня лотка. «Минимальный подпор на выходе, создаваемый нижним бьефом, достаточен для обеспечения устойчивости наброски на выходном участке.» (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Коэффициент шероховатости Маннинга в лотке, n';
$ec_lang['rc_Vm']='Скорость через каменную мантию, V<sub>m</sub> <span title="Часть q_t, протекающая через поры камня. Остаток qs течёт по поверхности. По умолчанию np = 0,45 для угловатого дроблёного камня." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Удельный расход через мантию, q<sub>m</sub>';
$ec_lang['rc_qs']='Поверхностный удельный расход, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Глубина потока над поверхностью наброски, d';
$ec_lang['rc_Hp']='Напор на входном пороге, H<sub>p</sub> <span title="Подпор (Hp > yn) — это хорошо: снижает эрозию выше по течению. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Проверка подпора у входа';
$ec_lang['rc_pond_ok']  ='Hp > yn — подпор выше по течению ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — подпора нет — проверьте вход на эрозию';
$ec_lang['rc_eq1']='Ур. 1 (S0 < 0,10) — пологий уклон';
$ec_lang['rc_eq2']='Ур. 2 (0,10 ≤ S0 ≤ 0,40) — крутой уклон';
$ec_lang['rc_eq_warn_low']='Предупреждение: S0 < 0,02 — ниже диапазона валидации Robinson';
$ec_lang['rc_eq_warn_high']='Предупреждение: S0 > 0,40 — выше диапазона валидации Robinson';
$ec_lang['rc_notes_1_term']='Уравнения подбора размера камня';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) разработали два эмпирических уравнения для медианного размера наброски D<sub>50</sub> на основе уклона лотка и удельного расхода. Уравнение 1 применяется для пологих уклонов (S<sub>0</sub> < 0,10); Уравнение 2 — для крутых уклонов (0,10 ≤ S<sub>0</sub> ≤ 0,40). Оба уравнения требуют q<sub>t</sub> в м²/с и возвращают D<sub>50</sub> в мм. Проверенный диапазон: 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Удельный расход';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> — суммарный удельный расход у гребня лотка (полный расход на единицу ширины). Для канала с шириной дна B и полным расходом Q приближённо q<sub>t</sub> ≈ Q / B, либо вычислите его из условия критической глубины у входа в лоток.';
$ec_lang['rc_notes_3_term']='Фильтрационный поток через каменную мантию';
$ec_lang['rc_notes_3_def']='Часть полного расхода проходит через поры каменной наброски (расход через мантию q<sub>m</sub>); остаток течёт по поверхности камня (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). Глубина потока d вычисляется по уравнению Маннинга для поверхностного расхода q<sub>s</sub> с использованием шероховатости лотка n. Пористость по умолчанию n<sub>p</sub> = 0,45 типична для угловатого дроблёного камня.';
$ec_lang['rc_notes_5_term']='Допустимый диапазон размера камня';
$ec_lang['rc_notes_5_def']='Уравнения разработаны для диапазона D<sub>50</sub> от 15 мм до 278 мм. Результаты за пределами этого диапазона являются экстраполяцией и должны применяться с дополнительной инженерной осторожностью.';
$ec_lang['rc_notes_6_term']='Отметка выходного порога';
$ec_lang['rc_notes_6_def']='Отметка верха наброски на выходном участке должна быть на уровне или ниже отметки дна нижнего канала. Если она выше — выходной камень будет неустойчивым.';
$ec_lang['rc_notes_7_term']='Проверка подпора у входа';
$ec_lang['rc_notes_7_def']='Если нормальная глубина во входном канале меньше напора на пороге (H<sub>p</sub>), требуемого для пропуска q<sub>t</sub>, выше входного порога возникает стеснение потока или подпор. Это, как правило, допустимо — подпор снижает скорость и предотвращает эрозию выше по течению. Для проверки: воспользуйтесь калькулятором водослива, найдите H<sub>p</sub> для заданных q<sub>t</sub> и ширины гребня, затем сравните с нормальной глубиной входного канала. Если H<sub>p</sub> превышает нормальную глубину, подпор возникнет.';
$ec_lang['rc_notes_4_term']='Источник';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS также публикует <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">таблицу Excel</a> на основе того же метода.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Фильтр';
$ec_lang['rc_sketch_top_crest_curve'] = 'Входная кривая';
$ec_lang['rc_sketch_outlet_apron']    = 'Водобойная плита';
$ec_lang['rc_sketch_radius']          = 'радиус';

// Irrigation Pressure. Prefix ip_.
$ec_lang['ip_main_menu']='Давление в ирригации';
$ec_lang['ip_main_title']='Бесплатный онлайн-калькулятор ирригационного давления и однородности распределения';
$ec_lang['ip_main_desc']='Испытание давления трассы и оценка однородности';
$ec_lang['ip_h_supply']='Давление на подаче';
$ec_lang['ip_elev_supply']='Отметка подачи, z<sub>подачи</sub>';
$ec_lang['ip_q_design']='Расход эмиттера по проекту, q<sub>расчётный</sub>';
$ec_lang['ip_h_design']='Давление эмиттера по проекту';
$ec_lang['ip_x']='Показатель разряда эмиттера, x <span title="0.5 for standard non-compensating emitters; near 0 for pressure-compensating emitters" class="ec-tip">?</span>';
$ec_lang['ip_reach_table_title']='Тестовая трасса';
$ec_lang['ip_group_reach']='Участок';
$ec_lang['ip_group_upstream']='Верхний';
$ec_lang['ip_group_downstream']='Нижний';
$ec_lang['ip_group_loss']='Потеря';
$ec_lang['ip_is_lateral']='Лат. <span title="Checked: this reach is a segment of the test lateral, drawn off by individual emitters. Unchecked: this reach is a main, only passing flow along to laterals not on the test path." class="ec-tip">?</span>';
$ec_lang['ip_count']='Эмиттеры <span title="Lateral rows: emitters in this reach only. Main rows: total emitters on laterals OTHER than this one that branch from this reach. For the reach right at the test lateral\'s own takeoff, this also includes any laterals beyond that point along the main, or sharing the same junction (e.g. an opposite-side lateral) — their flow branches from this same reach too." class="ec-tip">?</span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_e']='e <span title="Darcy-Weisbach roughness height" class="ec-tip">?</span>';
$ec_lang['ip_km']='K<sub>m</sub> <span title="Generic minor-loss coefficient for this reach\'s fittings/valves/couplers (≥0.5 suggested minimum)" class="ec-tip">?</span>';
$ec_lang['ip_elev_ds']='Отм. нб. <span title="Downstream-end elevation of this reach. Optional on interior rows (defaults to flat / same as the node above if left blank). Required on the last row: that value is the last emitter\'s elevation, which directly sets the required supply pressure." class="ec-tip">?</span>';
$ec_lang['ip_elev_ds_missing_warn']='Отметка последнего эмиттера (последняя строка) была оставлена пустой и установлена на горизонтальное положение — введите её для получения точного результата ⚠';
$ec_lang['ip_flow']='Расход';
$ec_lang['ip_press']='Давл.';
$ec_lang['ip_v']='V';
$ec_lang['ip_hv']='H<sub>v</sub>';
$ec_lang['ip_hf']='H<sub>f</sub>';
$ec_lang['ip_hm']='H<sub>m</sub>';
$ec_lang['ip_hl']='H<sub>l</sub> <span title="Total reach loss, H_f + H_m" class="ec-tip">?</span>';
$ec_lang['ip_pressure_warn']='Низкое/отрицательное давление — проверьте субатмосферные условия';
$ec_lang['ip_pressure_warn_short']='Низкое ⚠';
$ec_lang['ip_h_far']='Давление последнего эмиттера';
$ec_lang['ip_q_supply']='Расход подачи тестовой трассы, Q<sub>подачи</sub> <span title="Flow entering the modeled test path only, not the whole zone/system — see Q_zone in Application Design below for the system-wide total." class="ec-tip">?</span>';
$ec_lang['ip_q_critical']='Расход последнего эмиттера, q<sub>последний</sub>';
$ec_lang['ip_q_avg_lateral']='Средний расход эмиттера (тестовая латераль), q<sub>ср</sub>';
$ec_lang['ip_dp_avg']='Оцен. &Delta;давление, ср. vs. тестовая латераль <span title="How much higher (or lower) you believe a typical/average lateral runs compared to this test lateral. The test lateral is deliberately the presumed worst case, so its own average is a biased-low stand-in for a field average — left at 0, the uniformity check and application-design numbers below use the test lateral\'s own (likely optimistic) average as-is." class="ec-tip">?</span>';
$ec_lang['ip_q_avg_field']='Оцен. среднее полевое расход эмиттера, q<sub>ср,полевое</sub> <span title="q_avg_lateral re-evaluated at each lateral row\'s pressure plus the entered pressure difference above — an attempt to correct for the test lateral being the presumed worst case, not a representative one. Feeds both the uniformity check and the application-design section below." class="ec-tip">?</span>';
$ec_lang['ip_du_estimate']='Проверка однородности, q<sub>последний</sub>/q<sub>ср,полевое</sub> <span title="Last emitter\'s computed flow divided by the estimated field-average emitter flow — same shape as textbook low-quarter Distribution Uniformity (low-group average ÷ population mean), but from a small modeled sample and a user-estimated correction, not a full-field statistical sample. Values at or above 1 are possible and not a bug: it just means the last emitter isn\'t the low point relative to the estimated field average (e.g. a favorable downhill run, or the &Delta;pressure estimate above is too small)." class="ec-tip">?</span>';
$ec_lang['ip_worst_case_warn']='Давление тестового эмиттера находится на уровне или выше давления подачи — этот путь, вероятно, не является вашей наихудшей латеральью. Проверьте более удалённую или высокофрикционную латераль или профиль отметок, который лучше представляет фактический наихудший случай.';
$ec_lang['ip_q_ratio']='Расход последнего эмиттера vs. расход по проекту, q<sub>последний</sub>/q<sub>расчётный</sub> <span title="A separate check, not a uniformity figure: how far the last emitter runs from the manufacturer\'s rated design flow. Above 1: running above its design point (e.g. from a favorable downhill elevation gain). Below 1: running under design (typical friction-dominated case)." class="ec-tip">?</span>';
$ec_lang['ip_no_solution']='Нет решения: требуемое давление подачи превышает введённое давление подачи. Увеличьте давление подачи, уменьшите спрос или используйте трубу большего диаметра.';
$ec_lang['ip_notes_1_term']='Метод';
$ec_lang['ip_notes_1_def']='Прогнозирует давление в последнем (наиболее удалённом) эмиттере, затем движется вверх по энергетической линии в направлении подачи, участок за участком, добавляя потери на трение и потери местного сопротивления вдоль пути. Отметка и скоростной напор вычисляются в каждом узле для отчёта о действительном давлении там. Прогнозируемое давление на дальнем конце корректируется (методом половинного деления) до совпадения вычисленного требуемого давления подачи с введённым давлением подачи — та же замкнутая задача, решаемая решателем потока труб в калькуляторе Расход в трубе по Маннингу, распространённая на ветвящуюся сеть.';
$ec_lang['ip_notes_2_term']='Магистраль vs. Латеральные участки';
$ec_lang['ip_notes_2_def']='Каждая строка — один участок вдоль единого гидравлически наихудшего пути (тестовая трасса) от подачи до последнего эмиттера. Участок магистрали только пропускает расход на латерали, не входящие в тестовую трассу, поэтому его отбор — простое умножение (расход по проекту × общее количество эмиттеров в участке) — без локальной чувствительности к давлению. Магистраль — общая магистральная труба, поэтому участок прямо у точки ответвления тестовой латерали должен включать не только латерали между его концами, но и любые латерали дальше по магистрали вниз от этого ответвления, или использующие тот же узел (например, латераль с противоположной стороны) — их расход также ветвится из этого же участка, независимо от того, появляются они здесь или нет. Участок латерали — это сегмент самой тестовой латерали: разряд эмиттера вычисляется из действительного локального давления через q = k·H<sup>x</sup>, а потерю на трение снижает фактор F(n) Кристианзена для учёта уменьшения расхода по мере отбора каждым эмиттером в участке.';
$ec_lang['ip_notes_3_term']='Ограничения';
$ec_lang['ip_notes_3_def']='Моделирует одно фиксированное входное давление (без кривой насоса), одну тестовую трассу только (не всё поле), и кривую эмиттера с двумя параметрами (установите показатель близко к 0 для приближения эмиттера с компенсацией давления). Две различные отношения регистрируются и специально разделены: q<sub>последний</sub>/q<sub>ср,полевое</sub> — проверка однородности, по форме похожа на учебниковое низкоквартильное распределение однородности (среднее низкой группы ÷ среднее совокупности), но вычислено из модельных эмиттеров тестовой латерали, скорректировано введённой оценкой &Delta;давления вместо полнопольной статистической выборки — тестовая латераль специально выбирается как предполагаемый наихудший случай, поэтому её сырое, некорректированное среднее значение занижает истинное полевое среднее и делает однородность кажущейся лучше, чем она есть; ввод &Delta;давления существует специально для противодействия этому смещению. Значения на или выше 1 остаются возможны (например, оценка &Delta;давления слишком мала, или благоприятный нисходящий заход). q<sub>последний</sub>/q<sub>расчётный</sub> — отдельная, неоднородная проверка против номинального расхода производителя — полезна для обнаружения переразборки или недоразборки системы в целом, но не замена однородности, поскольку номинальный/расчётный расход не имеет необходимой связи с фактическим средним рабочим давлением системы.';
$ec_lang['ip_notes_4_term']='Источник';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). &ldquo;Irrigation by sprinkling.&rdquo; California Agricultural Experiment Station Bulletin 670. Стандарты ASAE/ASABE для проектирования микроирригации используют тот же многоточечный подход к потерям на трение.';
$ec_lang['ip_notes_5_term']='Проектирование приложения';
$ec_lang['ip_notes_5_def']='Норма орошения и расход системы/зоны используют оценённый среднее полевой расход эмиттера (q<sub>ср,полевое</sub> — собственное среднее тестовой латерали, скорректированное введённой оценкой &Delta;давления), а не предположительную норму: PR = q<sub>ср,полевое</sub> / A<sub>e</sub>, снабжено скорректированным модельным значением. Расстояние и полевые боковые/эмиттерные счётчики — отдельные входы здесь потому, что тестовая трасса моделирует только одну наихудшую ветвь, не каждую латераль в поле.';
$ec_lang['irr_card_pressure_head']='Ирригационное давление и однородность';
$ec_lang['irr_card_pressure_desc']='Модель профиля давления и расхода вдоль ветви магистраль-латераль-эмиттер для оценки однородности распределения на основе действительного давления тестовой трассы, а не просто номинального расхода эмиттера из каталога.';
