<?php

// हिन्दी — All missing text declarations will fall back to English.

// Units (alphabetical order)
// Necessary for calculator units selectors
$ec_lang['u_depthFrac']='भिन्न';
$ec_lang['u_depthPercent']='%';
$ec_lang['u_ft2']='ft^2';
$ec_lang['u_ft3ps']='cfs';
$ec_lang['u_ft']='ft';
$ec_lang['u_fth2o']='ft H2O';
$ec_lang['u_ftps']='ft/से';
$ec_lang['u_gpm']='gpm';
$ec_lang['u_gradePercent']='% चढ़ाव/आधार';
$ec_lang['u_grade']='चढ़ाव/आधार';
$ec_lang['u_in2']='वर्ग इंच';
$ec_lang['u_inh2o']='in H2O';
$ec_lang['u_in']='इंच';
$ec_lang['u_knpcm2']='kN/cm^2';
$ec_lang['u_knpm2']='kN/m^2';
$ec_lang['u_kpa']='kPa';
$ec_lang['u_lps']='ली/से';
$ec_lang['u_m2']='मी^2';
$ec_lang['u_m3ps']='मी^3/से';
$ec_lang['u_mgd']='MGD';
$ec_lang['u_mh2o']='मी जल';
$ec_lang['u_mld']='ML/दिन';
$ec_lang['u_m']='मी';
$ec_lang['u_mm2']='मिमी^2';
$ec_lang['u_mmh2o']='मिमी जल';
$ec_lang['u_mm']='मिमी';
$ec_lang['u_mps']='मी/से';
$ec_lang['u_npm2']='N/m^2';
$ec_lang['u_pa']='Pa';
$ec_lang['u_psf']='psf';
$ec_lang['u_psi']='psi';
$ec_lang['u_s']='सेकंड';
$ec_lang['u_lph']="ली/घंटा";
$ec_lang['u_gph']="गैलन/घंटा";
$ec_lang['u_mmph']="मिमी/घंटा";
$ec_lang['u_inph']="इंच/घंटा";
$ec_lang['u_acft']='एकड़-फुट';
$ec_lang['u_ft3']='ft^3';
$ec_lang['u_m3']='मी^3';
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';

// Page text
// In page order for easiest maintenance.
// Menu and General
$ec_lang['menu_brand']='HawsEDC कैलकुलेटर';
$ec_lang['menu_main_list']='कैलकुलेटर सूची';
$ec_lang['menu_main_hydraulics']='जलगतिकी';
$ec_lang['menu_main_language']='भाषा';
$ec_lang['menu_more']='अधिक';
$ec_lang['template_welcome']='>> दरवाज़े पर अपने डर छोड़ें; यहाँ प्यार हमारी भाषा है। आप सब कुछ बर्बाद नहीं कर रहे। <a target="_blank" href="https://hawsedc.com/download.php">मुफ़्त HawsEDC AutoCAD टूल</a> भी आज़माएँ। <<';
$ec_lang['template_translation_help']='क्या आपके पास यहाँ जोड़ने के लिए किसी कैलकुलेटर का शानदार विचार है? क्या आप अनुवाद सुधारने, प्रोग्राम करने, या इन कैलकुलेटरों को होस्ट करने में मदद कर सकते हैं?  ';
$ec_lang['template_feedback']='कृपया अपने बहुमूल्य सुझाव या प्रशंसा दें। क्या इस मुफ़्त कैलकुलेटर ने हर तरह से आपकी उम्मीदों को पार किया?';
$ec_lang['template_printable_title']='प्रिंट करने योग्य शीर्षक';
$ec_lang['template_printable_subtitle']='प्रिंट करने योग्य उप-शीर्षक';
$ec_lang['index_title']='मुफ़्त ऑनलाइन इंजीनियरिंग कैलकुलेटर';
$ec_lang['calc_set_units']='इकाइयाँ निर्धारित करें:';
$ec_lang['calc_defaults']='डिफ़ॉल्ट मान';
$ec_lang['calc_defaults_confirm']='कैलकुलेटर को मूल डिफ़ॉल्ट मानों पर रीसेट करूँ?';
$ec_lang['points_data_help']='(या डेटा क्षेत्र से कॉपी/पेस्ट करें)';
$ec_lang['points_data_title']='बिंदु डेटा<br />(अल्पविराम या टैब से अलग)';
$ec_lang['points_data_copy']='कॉपी';
$ec_lang['points_data_paste']='पेस्ट';
$ec_lang['calc_inputs']='इनपुट';
$ec_lang['calc_results']='परिणाम';
$ec_lang['view_hide_line']='[यह पंक्ति छुपाएँ]';
$ec_lang['view_printable']='प्रिंट करने योग्य संस्करण (पुनर्स्थापित करने के लिए पुनः लोड करें)';
$ec_lang['ec_name_label']='इस गणना को सहेजें:';
$ec_lang['ec_name_placeholder']='नाम';
$ec_lang['ec_name_hint']='इन इनपुटों को बुकमार्किंग, इतिहास पुनः प्राप्त करने और साझा करने के लिए URL में सहेजता है';
$ec_lang['calc_copy_link']='लिंक कॉपी करें';
$ec_lang['ec_related_calcs']='संबंधित कैलकुलेटर:';
$ec_lang['calc_copy_link_done']='कॉपी किया गया!';
// Darcy-Weisbach. See mphl_ for missing text.
$ec_lang['dw_main_menu']='डार्सी-वाइसबाख पाइप शीर्ष हानि';
$ec_lang['dw_main_title']='मुफ़्त ऑनलाइन डार्सी-वाइसबाख पाइप शीर्ष हानि कैलकुलेटर';
$ec_lang['dw_main_desc']='दिए गए व्यास, खुरदरापन और प्रवाह पर डार्सी-वाइसबाख पाइप शीर्ष हानि';
$ec_lang['dw_roughness']='e';
$ec_lang['dw_roughness_tip']='पाइप की दीवार की निरपेक्ष खुरदरापन ऊँचाई, e। विशिष्ट मान: इस्पात (नया) 0.046 mm, इस्पात (पुराना) 0.15 mm, HDPE 0.003 mm, PVC/uPVC 0.0015 mm, कंक्रीट 0.3–3 mm।';
$ec_lang['dw_kinematic_viscosity']='<span class="ec-help" title="20°C पर स्वच्छ जल के लिए 1×10⁻⁶ मी²/से">गतिक श्यानता, &nu; <span class="ec-tip">?</span></span>';
$ec_lang['dw_kinematic_viscosity_short']='गतिक श्यानता, &nu;';
$ec_lang['dw_kinematic_viscosity_tip']='20°C पर स्वच्छ जल के लिए 1×10⁻⁶ मी²/से';
$ec_lang['dw_reynolds_number']='रेनॉल्ड्स संख्या, Re';
$ec_lang['dw_flow_regime']='प्रवाह व्यवस्था';
$ec_lang['dw_regime_laminar']='स्तरीय';
$ec_lang['dw_regime_transitional']='संक्रमणीय';
$ec_lang['dw_regime_turbulent']='अशांत';
$ec_lang['dw_friction_factor_method']='घर्षण गुणांक विधि';
$ec_lang['dw_friction_factor']='घर्षण गुणांक, f';
// Hazen-Williams. See mphl_ for missing text.
$ec_lang['hw_main_menu']='हेज़न-विलियम्स पाइप शीर्ष हानि';
$ec_lang['hw_main_title']='मुफ़्त ऑनलाइन हेज़न-विलियम्स पाइप शीर्ष हानि कैलकुलेटर';
$ec_lang['hw_main_desc']='दिए गए व्यास, खुरदरापन और प्रवाह पर हेज़न-विलियम्स पाइप शीर्ष हानि';
$ec_lang['hw_hgl_1']='अनुप्रवाह HGL';
$ec_lang['hw_hgl_2']='उर्ध्वप्रवाह HGL';
$ec_lang['hw_roughness']='हेज़न-विलियम्स गुणांक, C';
// Manning Irregular
$ec_lang['mi_menu']='मैनिंग अनियमित-काट नाली';
$ec_lang['mi_main_title']='मुफ़्त ऑनलाइन मैनिंग अनियमित-काट नाली कैलकुलेटर';
$ec_lang['mi_main_desc']='अनियमित-काट नाली मैनिंग एकसमान प्रवाह कैलकुलेटर';
$ec_lang['mi_waterSurfaceElevation']='जल सतह स्तर';
$ec_lang['mi_q_617']='<span class="ec-help" title="मिश्रित प्रवाह, Q, जो Chow 6-17 (समान वेग) के अनुसार प्रत्येक क्षेत्र के लिए मिश्रित n का उपयोग करता है">Q <span class="ec-tip">?</span></span>';
$ec_lang['mi_xSecPoints']='अनुप्रस्थ काट बिंदु';
$ec_lang['mi_groupPoint']='बिंदु';
$ec_lang['mi_groupSegment']='खंड';
$ec_lang['mi_groupRegion']='क्षेत्र';
$ec_lang['mi_station']='चेनेज';
$ec_lang['mi_elevation']='ऊँचाई';
$ec_lang['mi_d50in']='अस्तर मध्यिका चट्टान आकार';
$ec_lang['mi_n']='n';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q क्षेत्र सीमा (तट)';
$ec_lang['mi_tau']='तल अपरूपण &tau;';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='मिश्रित<br />n';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='h<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes_1_term']='मिश्रित n';
$ec_lang['mi_notes_1_def']='यह कैलकुलेटर क्षेत्र मिश्रित n की गणना में Chow 1959, पृष्ठ 136, समीकरण 6-17 (6-18 नहीं) का उपयोग करते हुए HEC-RAS संदर्भ मैनुअल का अनुसरण करता है।';
$ec_lang['mi_notes_2_term']='चट्टान अस्तर';
$ec_lang['mi_notes_2_def']='चट्टान अस्तर डिज़ाइन करने के लिए मैनिंग समलम्बाकार नाली कैलकुलेटर का उपयोग करें। यह कैलकुलेटर प्राकृतिक अनुप्रस्थ काटों के लिए अधिक उपयुक्त है।';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='मैनिंग पाइप प्रवाह';
$ec_lang['mpf_main_title']='मुफ़्त ऑनलाइन मैनिंग पाइप प्रवाह कैलकुलेटर';
$ec_lang['mpf_main_desc']='दिए गए ढलान और गहराई पर मैनिंग सूत्र एकसमान पाइप प्रवाह';
$ec_lang['mpf_spreadheet_notice']='मैनिंग पाइप प्रवाह स्प्रेडशीट';
$ec_lang['mpf_pipe_diameter']='पाइप व्यास, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='मैनिंग खुरदरापन, n';
$ec_lang['mpf_friction_slope']='<a target="_blank" href="../frictionslope.php">घर्षण ढलान, S<sub>f</sub></a><span class="ec-help" title="कभी-कभी पाइप ढलान के बराबर। व्याख्या के लिए लिंक पर जाएं (केवल अंग्रेज़ी में)।"><span class="ec-tip">?</span></span>';
$ec_lang['mpf_depth_ratio']='सापेक्ष प्रवाह गहराई, y/d<sub>0</sub>';
$ec_lang['mpf_flow']='प्रवाह, Q';
$ec_lang['mpf_flow_tip']='प्रवाह और गहराई की गणना एक अनंत लंबे पाइप के लिए की गई है। इतना प्रवाह पाइप में प्रवेश कराने के लिए अधिक शीर्ष जल गहराई की आवश्यकता हो सकती है। विवरण और ट्यूटोरियल वीडियो के लिए नीचे नोट देखें।';
$ec_lang['mpf_velocity']='वेग, v';
$ec_lang['mpf_velocity_head']='<span class="ec-help" title="जल स्तंभ की ऊँचाई के रूप में गतिज ऊर्जा, v&sup2;/2g">वेग शीर्ष, h<sub>v</sub> <span class="ec-tip">?</span></span>';
$ec_lang['mpf_flow_area']='प्रवाह क्षेत्रफल, A';
$ec_lang['mpf_pipe_area']='पाइप क्षेत्रफल, A<sub>0</sub>';
$ec_lang['mpf_area_ratio']='सापेक्ष क्षेत्रफल, A/A<sub>0</sub>';
$ec_lang['mpf_wetted_perimeter']='आर्द्र परिधि, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='हाइड्रोलिक त्रिज्या, R<sub>h</sub>';
$ec_lang['mpf_top_width']='शीर्ष चौड़ाई, T';
$ec_lang['mpf_froude_number']='फ्रूड संख्या, Fr';
$ec_lang['mpf_shear_stress']='औसत अपरूपण प्रतिबल, &tau;';
$ec_lang['mpf_full_flow']='पूर्ण प्रवाह, Q<sub>0</sub>';
$ec_lang['mpf_full_flow_ratio']='पूर्ण प्रवाह से अनुपात, Q/Q<sub>0</sub>';
$ec_lang['mpf_note_1']='<dl><dt>यह एक <em>अनंत लंबे</em> पाइप के अंदर का प्रवाह और गहराई है।</dt><dd>पाइप में प्रवाह प्रवेश कराने के लिए काफी अधिक शीर्ष जल गहराई की आवश्यकता हो सकती है। शीर्ष जल गहराई पाने के लिए वेग शीर्ष का कम से कम 1.5 गुना जोड़ें या HY-8 का उपयोग करके मानक पाइपनाली शीर्ष जल गणना के लिए <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">मेरा 2-मिनट का ट्यूटोरियल</a> देखें।</dd>';
$ec_lang['mpf_solve_for_dd0']='दिए गए Q के लिए y/d<sub>0</sub> हल करें';
$ec_lang['mpf_solve_desc']='कैलकुलेटर फ़ॉर्म से d<sub>0</sub>, n और S<sub>f</sub> का उपयोग करके दिए गए Q के लिए न्यूनतम y/d<sub>0</sub> खोजता है।';
$ec_lang['mpf_solve_button']='हल करें';
$ec_lang['mpf_solver_enter_positive_q']='एक धनात्मक लक्ष्य Q दर्ज करें।';
$ec_lang['mpf_solver_no_solution']='कोई हल नहीं: y/d0 = 93.8% पर Q पाइप की क्षमता से अधिक है (चयनित इकाइयों में Qmax = {qmax})।';
// Manning Pipe Head Loss. See mpf_ for missing text.
$ec_lang['mphl_main_menu']='मैनिंग पाइप शीर्ष हानि';
$ec_lang['mphl_main_title']='मुफ़्त ऑनलाइन मैनिंग पाइप शीर्ष हानि कैलकुलेटर';
$ec_lang['mphl_main_desc']='दिए गए पूर्ण प्रवाह पर मैनिंग सूत्र शीर्ष हानि';
$ec_lang['mphl_pipe_length']='पाइप लंबाई, L';
$ec_lang['mphl_area']='क्षेत्रफल, A';
$ec_lang['mphl_total_junction_k']='मामूली (स्थानीय) हानि गुणांक, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_short']='हानि गुणांक, k<sub>m</sub>';
$ec_lang['mphl_total_junction_k_tip']='मामूली (स्थानीय) हानि गुणांक, k<sub>m</sub>। ये हानियाँ पाइप जंक्शन, प्रवेश, निकास, मोड़ (बेंड), और वाल्वों पर होती हैं — "मामूली" शब्द पारंपरिक है पर भ्रामक है; एक छोटी लाइन में ये घर्षण हानियों के बराबर या उनसे अधिक हो सकती हैं। विशिष्ट k मान: तीक्ष्ण किनारे वाला प्रवेश 0.5, प्रत्येक 45° मोड़ 0.2–0.3, गेट वाल्व (पूर्ण खुला) 0.1, बटरफ्लाई वाल्व 0.2, निकास (जलाशय या वायुमंडल में) 1.0। कुल k<sub>m</sub> के लिए सभी फिटिंगों को जोड़ें। डिफ़ॉल्ट मान 2.0 एक प्रवेश, एक निकास, और दो 45° मोड़ मानकर लिया गया है।';
$ec_lang['mphl_friction_slope']='घर्षण ढलान';
$ec_lang['mphl_friction_loss']='घर्षण हानि, h<sub>f</sub>';
$ec_lang['mphl_junction_loss']='मामूली (स्थानीय) हानि, h<sub>m</sub>';
$ec_lang['mphl_total_loss']='कुल हानि, h<sub>L</sub>';
$ec_lang['mphl_egl_1']='अनुप्रवाह EGL';
$ec_lang['mphl_egl_2']='उर्ध्वप्रवाह EGL';
$ec_lang['mphl_hgl_egl_tip']='पाइप ऊँचा होने पर यह मान्य नहीं हो सकता। नोट्स देखें।';
$ec_lang['mphl_note_1']='<dl><dt>यह कैलकुलेटर पाइप की ऊँचाई को ध्यान में नहीं रखता।</dt><dd>यदि किसी भी बिंदु पर HGL पाइप के शीर्ष से नीचे चली जाए, तो यह गणना मान्य नहीं हो सकती।</dd><dt>खुले इनलेट (पाइपनाली) की स्थिति के लिए, इनलेट नियंत्रण स्थितियों की जाँच आवश्यक है।</dt><dd>1. उर्ध्वप्रवाह HGL उर्ध्वप्रवाह सामान्य गहराई प्रवाह स्तर से ऊपर होनी चाहिए (और पाइप से भी ऊँची!)।</dd><dd>2. पाइपनाली का शीर्ष जल उर्ध्वप्रवाह HGL की तुलना में उर्ध्वप्रवाह EGL द्वारा बेहतर दर्शाया जाता है।</dd><dd>3. HY-8 का उपयोग करके सरल मानक पाइपनाली शीर्ष जल गणना के लिए <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">मेरा 2-मिनट का ट्यूटोरियल</a> देखें।</dd>';
// Manning Trapezoid. See mpf_ for missing text.
$ec_lang['mtc_menu']='मैनिंग समलम्बाकार नाली';
$ec_lang['mtc_main_title']='मुफ़्त ऑनलाइन मैनिंग सूत्र समलम्बाकार नाली कैलकुलेटर';
$ec_lang['mtc_main_desc']='दिए गए ढलान और गहराई पर मैनिंग सूत्र एकसमान समलम्बाकार नाली प्रवाह';
$ec_lang['mtc_bottom_width']='तल चौड़ाई, b';
$ec_lang['mtc_side_slope_1']='पार्श्व ढलान 1, z<sub>1</sub> (क्षैतिज/ऊर्ध्वाधर)';
$ec_lang['mtc_side_slope_2']='पार्श्व ढलान 2, z<sub>2</sub> (क्षैतिज/ऊर्ध्वाधर)';
$ec_lang['mtc_channel_slope']='नाली ढलान, S';
$ec_lang['mtc_flow_depth']='प्रवाह गहराई, y';
$ec_lang['mtc_bend_angle']='<a target="_blank" href="riprap-bend-angle.png">मोड़ कोण, β</a><span class="ec-help" title="चट्टान अस्तर आकार निर्धारण के लिए। चित्र के लिए लिंक पर जाएं।"><span class="ec-tip">?</span></span>';
$ec_lang['mtc_sgrock']='<span class="ec-help" title="पानी की तुलना में घनत्व। कुचली हुई चट्टान के लिए सामान्यतः &asymp; 2.65">चट्टान का विशिष्ट गुरुत्व, sg <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_in']='डिज़ाइन चट्टान आकार, D<sub>50</sub>';
$ec_lang['mtc_n_strickler']='डिज़ाइन चट्टान आकार के लिए n (Strickler विधि)';
$ec_lang['mtc_n_blodgett']='डिज़ाइन चट्टान आकार के लिए n (Blodgett विधि)';
$ec_lang['mtc_n_bathurst']='डिज़ाइन चट्टान आकार के लिए n (Bathurst विधि)';
$ec_lang['mtc_n_pi']='डिज़ाइन चट्टान आकार के लिए n (Phillips & Ingersoll विधि)';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett बनाम Bathurst';
$ec_lang['mtc_pi_range_check']='P&I सीमा जाँच';
$ec_lang['mtc_pi_ok']='d50, P&I सीमा में';
$ec_lang['mtc_pi_ok_tip']='0.28–0.36 ft (Phillips & Ingersoll, 1998)';
$ec_lang['mtc_pi_out_of_range']='सीमा से बाहर';
$ec_lang['mtc_pi_tip']='यह समीकरण जिस 0.28–0.36 ft डेटासेट सीमा से विकसित किया गया था, उससे बाहर एक्सट्रापोलेशन (परिसीमा-बाह्य विस्तार) — इसे केवल एक मोटा जाँच मानें, डिज़ाइन आधार नहीं';
$ec_lang['mtc_d50_bottom']='<span class="ec-help" title="Isbash (1936) और Maricopa County, Arizona, US के अनुसार।">तल के लिए आवश्यक कोणीय चट्टान आकार, D<sub>50</sub> (Isbash और MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z1']='<span class="ec-help" title="Isbash (1936) और Maricopa County, Arizona, US के अनुसार।">पार्श्व ढलान 1 के लिए आवश्यक कोणीय चट्टान आकार, D<sub>50</sub> (Isbash और MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_z2']='<span class="ec-help" title="Isbash (1936) और Maricopa County, Arizona, US के अनुसार।">पार्श्व ढलान 2 के लिए आवश्यक कोणीय चट्टान आकार, D<sub>50</sub> (Isbash और MC) <span class="ec-tip">?</span></span>';
$ec_lang['mtc_d50_mra']='आवश्यक कोणीय चट्टान आकार, D<sub>50</sub> (Maynord, Ruff, and Abt 1989)';
$ec_lang['mtc_d50_searcy']='आवश्यक कोणीय चट्टान आकार, D<sub>50</sub> (Searcy 1967)';
$ec_lang['mtc_vel_ok']='वेग एकसमान-प्रवाह मान्यताओं के लिए उचित है।';
$ec_lang['mtc_vel_low']='वेग कम है; अवसादन का जोखिम।';
$ec_lang['mtc_iteration_tip']='अपने लक्षित प्रवाह के लिए एकसमान चट्टान आकार की ओर स्वचालित पुनरावृत्ति हेतु एक खुरदरापन विकल्प (Blodgett–Bathurst अनुशंसित) और एक चट्टान आकार विकल्प (Isbash अनुशंसित) चुनें। पूरी विधि के लिए नीचे नोट देखें, या पुनरावृत्ति छोड़ने के लिए अपना खुरदरापन मान स्वयं (मार्गदर्शन के लिए लिंक देखें) दर्ज करें और चट्टान आकार को अनदेखा करें।';
$ec_lang['mtc_note_1']='<dl><dt>स्वचालित चट्टान आकार और खुरदरापन डिज़ाइन पुनरावृत्ति</dt><dd>एक खुरदरापन विकल्प चुनें (Blodgett–Bathurst अनुशंसित) और एक डिज़ाइन चट्टान आकार विकल्प चुनें (Isbash अनुशंसित)। एकसमान चट्टान आकार के साथ अपना लक्षित प्रवाह प्राप्त करने के लिए गहराई और चट्टान आकार सुरक्षा कारक को समायोजित करें। जब भी आप कोई इनपुट बदलते हैं, कैलकुलेटर ये चरण दोहराता है: 1. डिज़ाइन चट्टान आकार से खुरदरापन की गणना की जाती है। 2. अनुरोधित खुरदरापन गणना को इनपुट खुरदरापन में कॉपी किया जाता है। 3. नाली प्रवाह और आवश्यक चट्टान आकार की गणना की जाती है। 4. डिज़ाइन चट्टान आकार समायोजित किया जाता है। 5. डिज़ाइन चट्टान आकार में त्रुटि बहुत छोटी होने तक दोहराएँ।</dd><dt>बुनियादी कैलकुलेटर (पुनरावृत्ति रहित)</dt><dd>अपना वांछित खुरदरापन मान दर्ज करें। डिज़ाइन चट्टान आकार इनपुट क्षेत्र को अनदेखा करें।</dd></dl>';
$ec_lang['mtc_note_2_term']='वेग जाँच';
$ec_lang['mtc_note_2_def']='उच्च वेग यह दर्शाता है कि एक बड़ा ऊँचाई ह्रास हुआ जिसने इतनी अधिक विशिष्ट ऊर्जा उत्पन्न की। वह ऊर्जा विस्तारों, मोड़ों या बाधाओं पर शीघ्रता से नष्ट हो सकती है। सत्यापित करें कि यह स्थल के लिए उचित है।';
$ec_lang['mtc_solve_for_y']='Q दिए जाने पर गहराई, y, हल करें';
$ec_lang['mtc_solve_desc']='कैलकुलेटर फ़ॉर्म से b, z<sub>1</sub>, z<sub>2</sub>, S, और n का उपयोग करके, दिए गए Q के लिए गहराई ज्ञात करता है।';
$ec_lang['mtc_solver_no_solution']='इन नाली इनपुट के साथ दिए गए Q के लिए कोई हल नहीं मिला।';
// Weir Flow Simple
$ec_lang['ws_main_menu']='सरल वियर प्रवाह';
$ec_lang['ws_main_title']='मुफ़्त ऑनलाइन सरल चौड़ी-शिखर वियर प्रवाह कैलकुलेटर';
$ec_lang['ws_main_desc']='सरल चौड़ी-शिखर वियर प्रवाह कैलकुलेटर';
$ec_lang['ws_weirLength']='वियर लंबाई, L';
$ec_lang['ws_headWaterHeight']='<span class="ec-help" title="पानी के प्रति इकाई भार की ऊर्जा — जल स्तंभ की एक ऊँचाई, दाब नहीं">शीर्ष, h <span class="ec-tip">?</span></span>';
$ec_lang['ws_weirCoefficient']='वियर गुणांक, C<sub>w</sub>';
$ec_lang['ws_notes_heading']='नोट';
$ec_lang['ws_notes_we_term']='वियर समीकरण';
// Weir Flow Irregular. See ws_ for missing text.
$ec_lang['wi_menu']='अनियमित प्रोफाइल वियर प्रवाह';
$ec_lang['wi_main_title']='मुफ़्त ऑनलाइन खंडित, परिवर्तनशील गहराई, अनियमित प्रोफाइल वियर प्रवाह कैलकुलेटर';
$ec_lang['wi_main_desc']='अनियमित प्रोफाइल वियर प्रवाह कैलकुलेटर';
$ec_lang['wi_weirPoints']='वियर बिंदु';
$ec_lang['wi_pondingHeight']='ताल की ऊँचाई';
$ec_lang['wi_incrementalFlow']='वृद्धिशील प्रवाह';
$ec_lang['wi_cumulativeFlow']='संचित प्रवाह';
$ec_lang['wi_save_and_calculate']='सहेजें और गणना करें';
$ec_lang['wi_notes_we_def']='q = यदि (लंबाई = 0) तो 0 अन्यथा यदि (ढलान=0) तो cw*लंबाई*d<sub>0</sub><sup>1.5</sup> अन्यथा cw/(2.5*ढलान) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) जहाँ d<sub>1</sub> और d<sub>0</sub> सदा शून्य या धनात्मक हैं';
// Orifice Flow
$ec_lang['or_main_menu']='छिद्र प्रवाह';
$ec_lang['or_main_title']='मुफ़्त ऑनलाइन छिद्र प्रवाह कैलकुलेटर';
$ec_lang['or_main_desc']='छिद्र प्रवाह — स्वतंत्र या जलमग्न';
$ec_lang['or_shape']='उद्घाटन आकृति';
$ec_lang['or_shape_circular']='वृत्ताकार';
$ec_lang['or_shape_rectangular']='आयताकार';
$ec_lang['or_diameter']='<span class="ec-help" title="वृत्ताकार के लिए व्यास; आयताकार के लिए ऊँचाई">व्यास या ऊँचाई, D <span class="ec-tip">?</span></span>';
$ec_lang['or_width']='<span class="ec-help" title="केवल आयताकार उद्घाटन">चौड़ाई, W <span class="ec-tip">?</span></span>';
$ec_lang['or_invert']='<span class="ec-help" title="उद्घाटन का तल">इनवर्ट स्तर <span class="ec-tip">?</span></span>';
$ec_lang['or_hwe']='अपस्ट्रीम जल स्तर';
$ec_lang['or_twe']='डाउनस्ट्रीम जल स्तर';
$ec_lang['or_cd']='निर्वहन गुणांक, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='केन्द्रक स्तर';
$ec_lang['or_head']='<span class="ec-help" title="पानी के प्रति इकाई भार की ऊर्जा — जल स्तंभ की एक ऊँचाई, दाब नहीं">प्रभावी शीर्ष, h <span class="ec-tip">?</span></span>';
$ec_lang['or_area']='उद्घाटन क्षेत्रफल, A';
$ec_lang['or_regime']='छिद्र व्यवस्था जाँच';
$ec_lang['or_regime_valid']='स्वतंत्र निकास';
$ec_lang['or_regime_submerged']='जलमग्न छिद्र';
$ec_lang['or_regime_submerged_tip']='TWE केन्द्रक के ऊपर है — छिद्र व्यवस्था अभी भी वैध है';
$ec_lang['or_regime_warn']='छिद्र व्यवस्था से बाहर';
$ec_lang['or_regime_warn_tip']='अपस्ट्रीम जल स्तर उद्घाटन के शिखर से नीचे है';
$ec_lang['or_regime_twe_above_hwe']='इनपुट जाँचें';
$ec_lang['or_regime_twe_above_hwe_tip']='डाउनस्ट्रीम जल (TWE) अपस्ट्रीम जल (HWE) से ऊपर';
$ec_lang['or_notes_1_term']='छिद्र समीकरण';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh)। स्वतंत्र निकास: h = HWE − केन्द्रक। जलमग्न प्रवाह (इनवर्ट के ऊपर TWE): h = HWE − TWE।';
$ec_lang['or_notes_2_term']='छिद्र व्यवस्था';
$ec_lang['or_notes_2_def']='छिद्र प्रवाह समीकरण तब लागू होते हैं जब अपस्ट्रीम जल सतह उद्घाटन के शिखर (ऊपर) से ऊपर हो। जब अपस्ट्रीम जल शिखर से नीचे हो, तो वियर समीकरण का उपयोग करें।';
$ec_lang['or_notes_3_term']='निर्वहन गुणांक';
$ec_lang['or_notes_3_def']='तीखे-किनारे वाले छिद्रों के लिए C<sub>d</sub> लगभग 0.60–0.65 तक होता है। गोलाकार या पुनः-प्रवेशी इनलेट अलग मूल्य उपयोग करते हैं। मार्गदर्शन के लिए <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> या HEC-RAS हाइड्रॉलिक संदर्भ मैनुअल देखें।';
$ec_lang['or_notes_4_term']='जलमग्नता';
$ec_lang['or_notes_4_def']='जब TWE उद्घाटन इनवर्ट के ऊपर हो, तो यह कैलकुलेटर स्वचालित रूप से h = HWE − TWE का उपयोग करके जलमग्न छिद्र समीकरण लागू करता है। जब TWE इनवर्ट पर या उससे नीचे हो, तो स्वतंत्र निकास माना जाता है और h = HWE − केन्द्रक।';
// Micro-Hydro Power
$ec_lang['mhp_main_menu']='माइक्रो-हाइड्रो पावर';
$ec_lang['mhp_main_title']='निःशुल्क ऑनलाइन माइक्रो-हाइड्रो पावर कैलकुलेटर';
$ec_lang['mhp_main_desc']='नदी-प्रवाह माइक्रो-हाइड्रो पावर आउटपुट कैलकुलेटर';
$ec_lang['mhp_gross_head']='सकल हेड, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='<span class="ec-help" title="दबाव नली (आपूर्ति पाइप) का व्यास">दबाव नली व्यास, D <span class="ec-tip">?</span></span>';
$ec_lang['mhp_length']='लंबाई, L';
$ec_lang['mhp_efficiency']='प्लांट दक्षता, &eta; (0&ndash;1)';
$ec_lang['mhp_vel_check']='वेग जाँच';
$ec_lang['mhp_hl_check']='हेड हानि जाँच';
$ec_lang['mhp_hnet']='शुद्ध हेड, H<sub>net</sub>';
$ec_lang['mhp_power']='शक्ति उत्पादन, P';
$ec_lang['mhp_annual_kwh']='100% क्षमता पर वार्षिक ऊर्जा';
$ec_lang['mhp_vel_low']='वेग कम है; अवसादन और वायु-प्रवेश का जोखिम है।';
$ec_lang['mhp_vel_high']='वेग अधिक है; संक्रमण हानियों, उपलब्ध ऊर्जा और वाटर हैमर की जाँच करें।';
$ec_lang['mhp_vel_ok_short']='ठीक';
$ec_lang['mhp_vel_high_short']='अधिक';
$ec_lang['mhp_vel_low_short']='कम';
$ec_lang['mhp_vel_ok_tip']='वेग दबाव नली डिज़ाइन के लिए दक्ष सीमा में है।';
$ec_lang['mhp_hl_ok_tip']='10% लक्ष्य के भीतर — किफ़ायती।';
$ec_lang['mhp_hl_warn_tip']='10% लक्ष्य से अधिक है। बड़े पाइप पर विचार करें।';
$ec_lang['mhp_hl_bad_tip']='20% लक्ष्य से अधिक है। पाइप का आकार बदलें।';
$ec_lang['mhp_notes_1_term']='हेड हानि';
$ec_lang['mhp_notes_1_def']='कुल दबाव नली (आपूर्ति पाइप) हानि h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, जहाँ h<sub>f</sub> = f(L/D)(v&sup2;/2g) डार्सी-वाइसबैक घर्षण हानि है और h<sub>m</sub> = k<sub>m</sub>&middot;v&sup2;/2g प्रवेश, मोड़ और वाल्वों को शामिल करती है। शुद्ध हेड H<sub>net</sub> = H<sub>gross</sub> &minus; h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='वेग';
$ec_lang['mhp_notes_2_def']='जाँचें कि वेग उपलब्ध ड्रॉप और पाइप लागत के लिए उचित है। बहुत कम वेग अत्यधिक बड़े आकार का संकेत हो सकता है; बहुत अधिक वेग घर्षण हानि और वाटर हैमर के जोखिम को बढ़ा सकता है।';
$ec_lang['mhp_notes_3_term']='हेड हानि लक्ष्य';
$ec_lang['mhp_notes_3_def']='सकल हेड के 10% से कम दबाव नली (आपूर्ति पाइप) हानि सामान्यतः किफ़ायती होती है। पाइप लागत और खोई शक्ति के बीच इष्टतम संतुलन प्रायः 4&ndash;6% के आसपास होता है, जहाँ बिजली सबसे मूल्यवान होती है।';
$ec_lang['mhp_notes_6_term']='दक्षता';
$ec_lang['mhp_notes_6_def']='माइक्रो-हाइड्रो में सामान्य Pelton और क्रॉस-फ्लो टर्बाइनों के लिए विशिष्ट प्लांट दक्षता &eta; 0.70 से 0.85 तक होती है। एक रूढ़िवादी प्रारंभिक अनुमान के रूप में 0.75 का उपयोग करें।';
$ec_lang['mhp_notes_7_term']='वार्षिक ऊर्जा';
$ec_lang['mhp_notes_7_def']='वार्षिक ऊर्जा निरंतर पूर्ण-प्रवाह संचालन (8760 घंटे/वर्ष) मानती है। मौसमी प्रवाह भिन्नता, रखरखाव डाउनटाइम और लोड फैक्टर के कारण वास्तविक उत्पादन कम होगा।';

// Orifice Drain Time
$ec_lang['odt_main_menu']='छिद्र निकासी समय';
$ec_lang['odt_main_title']='मुफ़्त ऑनलाइन छिद्र निकासी समय कैलकुलेटर — तालाब, बेसिन या टंकी';
$ec_lang['odt_main_desc']='तालाब या बेसिन छिद्र निकासी समय — शंक्वाकार आयतन विधि';
$ec_lang['odt_h1_elev']='प्रारंभिक जल सतह स्तर';
$ec_lang['odt_a1']='प्रारंभिक क्षेत्रफल, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='अंतिम जल सतह स्तर';
$ec_lang['odt_a0']='छिद्र-स्तर क्षेत्रफल, A<sub>0</sub>';
$ec_lang['odt_a_ending']='<span class="ec-help" title="अंतिम स्तर पर शंक्वाकार मॉडल से प्रक्षेपित">अंतिम क्षेत्रफल, A<sub>2</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_h2_check']='अंतिम स्तर जाँच';
$ec_lang['odt_h2_ok']='अंतिम स्तर छिद्र शिखर के ऊपर';
$ec_lang['odt_h2_warn']='अंतिम स्तर छिद्र शिखर पर या उससे नीचे';
$ec_lang['odt_h2_warn_tip']='छिद्र शिखर = केन्द्रक + D/2';
$ec_lang['odt_d']='<span class="ec-help" title="व्यास (वृत्ताकार) या ऊँचाई (आयताकार)">छिद्र D <span class="ec-tip">?</span></span>';
$ec_lang['odt_w']='<span class="ec-help" title="केवल आयताकार">छिद्र चौड़ाई, W <span class="ec-tip">?</span></span>';
$ec_lang['odt_t_sec']='निकासी समय (से.)';
$ec_lang['odt_t_min']='निकासी समय (मि.)';
$ec_lang['odt_t_hr']='निकासी समय (घं.)';
$ec_lang['odt_t_day']='निकासी समय (दिन)';
$ec_lang['odt_notes_1_term']='सूत्र';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) शीर्ष H से छिद्र तक निकासी समय देता है। निकासी समय = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), जहाँ H<sub>1</sub> = प्रारंभिक स्तर − छिद्र स्तर, H<sub>2</sub> = अंतिम स्तर − छिद्र स्तर।';
$ec_lang['odt_notes_2_term']='विधि';
$ec_lang['odt_notes_2_def']='शंक्वाकार आयतन विधि तालाब या बेसिन को प्रारंभिक जल सतह पर A<sub>1</sub> और छिद्र केन्द्रक स्तर पर A<sub>0</sub> के बीच एक शंक्वाकार खंड के रूप में मॉडल करती है। A<sub>2</sub>, अंतिम स्तर पर तालाब का क्षेत्रफल, शंक्वाकार खंड मॉडल का उपयोग करके A<sub>1</sub> और A<sub>0</sub> से प्रक्षेपित किया जाता है। प्रारंभिक से अंतिम स्तर तक निकासी समय H<sub>1</sub> से छिद्र तक कुल निकासी समय से H<sub>2</sub> से छिद्र तक शेष निकासी समय घटाने के बराबर है।';
$ec_lang['odt_h1']='<span class="ec-help" title="प्रारंभिक जल सतह स्तर घटा छिद्र केन्द्रक स्तर">प्रारंभिक शीर्ष, H<sub>1</sub> <span class="ec-tip">?</span></span>';
$ec_lang['odt_q_max']='अधिकतम प्रवाह, Q<sub>max</sub>';
$ec_lang['odt_vol']='निकाला गया आयतन';
$ec_lang['odt_sketch_start']='प्रारंभ';
$ec_lang['odt_sketch_end']='अंत';
// Erosion Setback and Scour Calc.
// Contact us.

// Irrigation
$ec_lang['irr_main_menu']='सिंचाई';
$ec_lang['irr_main_title']='मुफ़्त ऑनलाइन सिंचाई प्रवाह मापन कैलकुलेटर';
$ec_lang['irr_main_desc']='सिंचाई प्रवाह मापन — वियर और छिद्र';
$ec_lang['irr_intro_html']='<p>वियर और छिद्र सिंचाई प्रणालियों में जल प्रवाह मापने के मानक क्षेत्रीय उपकरण हैं। अपनी संरचना से मेल खाने वाला कैलकुलेटर चुनें:</p>';
$ec_lang['irr_card_weir_uniform_head']='वियर — चौड़ी क्रेस्ट (एकसमान चौड़ाई)';
$ec_lang['irr_card_weir_uniform_desc']='डायवर्जन डैम क्रेस्ट, नियंत्रण संरचना या वियर बोर्ड पर प्रवाह मापें। वियर की लंबाई और क्रेस्ट से ऊपर जल की गहराई दर्ज करें।';
$ec_lang['irr_card_weir_irregular_head']='वियर — अनियमित प्रोफाइल';
$ec_lang['irr_card_weir_irregular_desc']='तब उपयोग करें जब वियर क्रेस्ट एक समान ऊँचाई पर न हो — प्राकृतिक स्पिलवे, परिवर्तनीय चौड़ाई वाले ड्रॉप स्ट्रक्चर, या बहु-खंड नियंत्रण संरचनाएं।';
$ec_lang['irr_card_orifice_head']='छिद्र — हेडगेट या पाइप टर्नआउट';
$ec_lang['irr_card_orifice_desc']='स्लुइस गेट, पाइप टर्नआउट या कल्वर्ट ओपनिंग से प्रवाह मापें। स्वतः ही मुक्त प्रवाह और जलमग्न (डाउनस्ट्रीम जल) दोनों स्थितियों को संभालता है।';
$ec_lang['irr_card_canal_head']='नहर डिज़ाइन और विश्लेषण';
$ec_lang['irr_card_canal_desc']='मैनिंग के सूत्र का उपयोग करके सिंचाई नहर डिज़ाइन करें या जाँचें। नए चैनलों के लिए ट्रेपेज़ॉइडल कैलकुलेटर का उपयोग करें; मौजूदा प्राकृतिक या निर्मित खंडों के लिए अनियमित कैलकुलेटर का उपयोग करें।';
$ec_lang['irr_card_seepage_head']='नहर रिसाव और संवहन दक्षता';
$ec_lang['irr_card_seepage_desc']='अंतर्वाह और बहिर्वाह माप का उपयोग करके नहर खंड से रिसाव हानि का अनुमान लगाएं। संवहन दक्षता और वार्षिक जल हानि की गणना करें ताकि अस्तर निवेश को प्राथमिकता देने में सहायता मिले।';
$ec_lang['irr_quickref_html']='<h3>त्वरित संदर्भ</h3><dl><dt>डायवर्जन डैम या नियंत्रण संरचना</dt><dd>वियर क्रेस्ट के ऊपर जल की गहराई मापें। एकसमान क्रेस्ट के लिए <a href="Weir-Flow-Simple.php">सरल वियर प्रवाह</a> और प्रोफाइल्ड या स्टेप्ड क्रेस्ट के लिए <a href="Weir-Flow-Irregular.php">अनियमित प्रोफाइल वियर प्रवाह</a> उपयोग करें।</dd><dt>हेडगेट या पाइप टर्नआउट</dt><dd>अपस्ट्रीम और डाउनस्ट्रीम जल स्तर मापें (या मुक्त प्रवाह हो तो इनवर्ट ऊँचाई)। <a href="Orifice.php">छिद्र प्रवाह</a> उपयोग करें। वृत्ताकार पाइप के लिए D = पाइप व्यास; आयताकार गेट के लिए चौड़ाई W और ऊँचाई D दर्ज करें।</dd><dt>जलाशय या तालाब खाली होने का समय</dt><dd>तल के छिद्र से तालाब या जलाशय का स्तर कम होने में लगने वाले समय का अनुमान लगाने के लिए <a href="Orifice-Drain-Time.php">छिद्र निकासी समय</a> उपयोग करें — सिंचाई भंडारण योजना के लिए उपयोगी।</dd><dt>क्षेत्रीय मानक</dt><dd>यहाँ उपयोग किए गए वियर और छिद्र प्रवाह समीकरण USBR <em>Water Measurement Manual</em> (तीसरा संस्करण) की प्रक्रियाओं के अनुसार हैं, जो जल प्रबंधकों और सिंचाई जिलों द्वारा सामान्यतः आवश्यक होते हैं।</dd></dl>';
// Drip / Sprinkler Application Rate
$ec_lang['ip_se']='उत्सर्जक अंतराल, S<sub>e</sub>';
$ec_lang['ip_sl']='पार्श्व अंतराल, S<sub>l</sub>';
$ec_lang['ip_n_e']='प्रति पार्श्व उत्सर्जक, n<sub>e</sub>';
$ec_lang['ip_n_l']='प्रति क्षेत्र पार्श्व, n<sub>l</sub>';
$ec_lang['ip_d']='लक्ष्य अनुप्रयोग गहराई, d';
$ec_lang['ip_a_e']='प्रति उत्सर्जक क्षेत्रफल, A<sub>e</sub>';
$ec_lang['ip_pr']='अनुप्रयोग दर, PR';
$ec_lang['ip_q_lat']='प्रति पार्श्व प्रवाह, Q<sub>lat</sub>';
$ec_lang['ip_q_sys']='क्षेत्र प्रवाह, Q<sub>zone</sub>';
$ec_lang['ip_t_run']='चलने का समय (घंटे)';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='नहर रिसाव';
$ec_lang['cs_main_title']='मुफ़्त ऑनलाइन नहर रिसाव हानि और संवहन दक्षता कैलकुलेटर';
$ec_lang['cs_main_desc']='नहर रिसाव हानि और संवहन दक्षता — अंतर्वाह-बहिर्वाह विधि';
$ec_lang['cs_Q_in']='अंतर्वाह, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='बहिर्वाह, Q<sub>out</sub>';
$ec_lang['cs_L']='खंड की लंबाई, L';
$ec_lang['cs_Q_loss']='रिसाव हानि दर, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='माप जाँच';
$ec_lang['cs_pct_loss']='हानि भिन्न';
$ec_lang['cs_Ec']='संवहन दक्षता, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='दक्षता रेटिंग';
$ec_lang['cs_Vol_day']='दैनिक खोया आयतन';
$ec_lang['cs_Vol_year']='वार्षिक खोया आयतन';
$ec_lang['cs_Q_loss_per_L']='हानि प्रति लंबाई, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='जल मूल्य';
$ec_lang['cs_lining_cost']='अस्तर लागत';
$ec_lang['cs_Ec_target']='<span class="ec-help" title="अस्तर के बाद संवहन दक्षता लक्ष्य; भिन्न 0–1">अस्तर लक्ष्य, E<sub>c,target</sub> <span class="ec-tip">?</span></span>';
$ec_lang['cs_lining_area']='अस्तर क्षेत्र, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='वार्षिक खोया मूल्य';
$ec_lang['cs_annual_value_recovered']='वार्षिक वसूल मूल्य';
$ec_lang['cs_lining_total_cost']='कुल अस्तर लागत';
$ec_lang['cs_payback_years']='<span class="ec-help" title="सरल चुकौती = कुल अस्तर लागत ÷ वार्षिक वसूल मूल्य">चुकौती अवधि <span class="ec-tip">?</span></span>';
$ec_lang['cs_loss_positive']='Q<sub>in</sub> > Q<sub>out</sub> — रिसाव पाया गया';
$ec_lang['cs_loss_zero']='Q<sub>in</sub> = Q<sub>out</sub> — कोई मापनीय हानि नहीं';
$ec_lang['cs_loss_negative']='Q<sub>out</sub> > Q<sub>in</sub> — माप जाँचें';
$ec_lang['cs_Ec_good']='अच्छी — E<sub>c</sub> ≥ 80%';
$ec_lang['cs_Ec_fair']='ठीक — E<sub>c</sub> 60–80%';
$ec_lang['cs_Ec_poor']='खराब — E<sub>c</sub> < 60%';
$ec_lang['cs_notes_1_def']='अंतर्वाह-बहिर्वाह विधि नहर खंड के शीर्ष और पुच्छ पर प्रवाह मापकर रिसाव का अनुमान लगाती है: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>। संवहन दक्षता E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>। वार्षिक आयतन निरंतर पूर्ण-प्रवाह संचालन मानता है; मौसमी या आंशिक-प्रवाह नहरों में वास्तविक हानि कम होती है।';
$ec_lang['cs_notes_2_term']='दक्षता रेटिंग';
$ec_lang['cs_notes_2_def']='सामान्य बिना अस्तर की मिट्टी नहरें: E<sub>c</sub> = 60–80%। अच्छी तरह रखरखाव वाली मिट्टी नहरें: 75–85%। कंक्रीट-अस्तर नहरें: 90–98%। अंतर्वाह के 30% से अधिक रिसाव हानि अक्सर अस्तर निवेश को उचित ठहराती है। (USBR, FAO)';
$ec_lang['cs_notes_3_term']='अस्तर चुकौती';
$ec_lang['cs_notes_3_def']='जल मूल्य और अस्तर लागत को किसी भी सुसंगत मुद्रा में दर्ज करें। अस्तर क्षेत्र = खंड की लंबाई × आर्द्र परिधि — मापी गई प्रवाह गहराई पर नहर क्रॉस-सेक्शन की आर्द्र परिधि (तल की चौड़ाई प्लस दोनों आर्द्र ढलानें)। वसूल किया गया वार्षिक मूल्य मानता है कि अस्तर नहर लक्ष्य E<sub>c</sub> को निरंतर प्राप्त करती है। यदि अस्तर लक्ष्य दक्षता तक नहीं पहुँचता या नहरें मौसमी होती हैं, तो वास्तविक चुकौती अवधि अधिक होगी।';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3rd ed. (2001)। FAO Irrigation and Drainage Paper 57 (1999)।';
// About
$ec_lang['about_main_menu']='के बारे में';
$ec_lang['install_main_menu']='इंस्टॉल करें';
$ec_lang['install_main_title']='EngCalcs इंस्टॉल करें';
$ec_lang['install_main_desc']='ऑफ़लाइन उपयोग के लिए अपने डिवाइस में जोड़ें';
$ec_lang['install_intro']='EngCalcs एक प्रोग्रेसिव वेब ऐप (PWA) है। एक बार इंस्टॉल करने के बाद, सभी कैलकुलेटर पूरी तरह ऑफ़लाइन काम करते हैं — इंटरनेट कनेक्शन की ज़रूरत नहीं।';
$ec_lang['install_android_heading']='Android (Chrome)';
$ec_lang['install_android_steps_html']='<li>Chrome में कोई भी कैलकुलेटर पेज खोलें।</li><li>ऊपर नेविगेशन बार में <strong>⬇ इंस्टॉल करें</strong> बटन पर टैप करें, या ब्राउज़र मेनू (⋮) पर टैप करके <strong>होम स्क्रीन पर जोड़ें</strong> चुनें।</li><li>दिखाई देने वाले प्रॉम्प्ट में <strong>इंस्टॉल करें</strong> पर टैप करें।</li><li>EngCalcs आपकी होम स्क्रीन पर दिखेगा और ऑफ़लाइन काम करेगा।</li>';
$ec_lang['install_now_btn']='⬇ अभी इंस्टॉल करें';
$ec_lang['install_prompt_unavailable']='इंस्टॉल प्रॉम्प्ट उपलब्ध नहीं है — इसके बजाय अपने ब्राउज़र मेनू का उपयोग करें।';
$ec_lang['install_ios_heading']='iOS (Safari)';
$ec_lang['install_ios_steps_html']='<li>Safari में कोई भी कैलकुलेटर पेज खोलें।</li><li><strong>Share</strong> बटन (ऊपर की ओर तीर वाला बॉक्स) पर टैप करें।</li><li>नीचे स्क्रॉल करें और <strong>Add to Home Screen</strong> पर टैप करें।</li><li><strong>Add</strong> पर टैप करें। EngCalcs आपकी होम स्क्रीन पर दिखेगा।</li>';
$ec_lang['install_ios_note']='iOS पर, इंस्टॉल करने के लिए हमेशा Share मेनू का उपयोग होता है — कोई स्वचालित इंस्टॉल प्रॉम्प्ट नहीं आता।';
$ec_lang['install_desktop_heading']='डेस्कटॉप (Chrome / Edge)';
$ec_lang['install_desktop_steps_html']='<li>कोई भी कैलकुलेटर पेज खोलें।</li><li>ब्राउज़र के एड्रेस बार में <strong>इंस्टॉल आइकन</strong> (⊕ या कंप्यूटर आइकन) पर क्लिक करें, या ब्राउज़र मेनू खोलकर <strong>Install EngCalcs…</strong> चुनें।</li><li><strong>इंस्टॉल करें</strong> पर क्लिक करें। EngCalcs एक स्वतंत्र ऐप विंडो के रूप में खुलेगा।</li>';
$ec_lang['install_firefox_heading']='Firefox / अन्य ब्राउज़र';
$ec_lang['install_firefox_body']='Firefox डेस्कटॉप पर PWA इंस्टॉल करने का समर्थन नहीं करता। फिर भी आप ब्राउज़र में सभी कैलकुलेटर सामान्य रूप से उपयोग कर सकते हैं — पहली बार खोलने के बाद, पेज ऑफ़लाइन उपयोग के लिए स्वतः कैश हो जाते हैं।';
$ec_lang['install_cached_heading']='क्या-क्या कैश होता है';
$ec_lang['install_cached_body']='जब आप पहली बार EngCalcs इंस्टॉल करते हैं, तो सभी कैलकुलेटर पेज और उनकी सहायक फ़ाइलें (स्क्रिप्ट, स्टाइल) आपके डिवाइस पर अपने आप सहेज ली जाती हैं। इसके बाद, सब कुछ बिना इंटरनेट कनेक्शन के काम करता है। आपकी भाषा का चुनाव आपकी पिछली ऑनलाइन विज़िट से याद रखा जाता है।';
$ec_lang['contact_main_menu']='संपर्क';
$ec_lang['about_main_title']='HawsEDC इंजीनियरिंग कैलकुलेटर के बारे में';
$ec_lang['about_main_desc']='मिशन, ओपन सोर्स और योगदान';
$ec_lang['about_body_html']='<h3>मिशन</h3><p>HawsEDC इंजीनियरिंग कैलकुलेटर दुनिया भर के इंजीनियरों और क्षेत्रीय कार्यकर्ताओं की सेवा के लिए हैं — विशेषकर उन लोगों के लिए जो जल-संकटग्रस्त, संसाधन-सीमित या वंचित क्षेत्रों में काम करते हैं। ये उपकरण एक व्यापक मानवीय मिशन का हिस्सा हैं: हर इंसान को सबसे व्यावहारिक और प्रभावी तरीके से यह बताना कि वे हमेशा के लिए प्यार किए गए और संजोए गए हैं, कि उन्हें डरने की कोई जरूरत नहीं, और वे सब कुछ बर्बाद नहीं करेंगे।</p><p>कैलकुलेटर साधन हैं। गंतव्य एक कष्ट-मुक्त संसार है।</p><h3>ओपन सोर्स लाइसेंस</h3><p>सभी कोड <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License v3.0 या बाद के संस्करण</a> के तहत जारी किया गया है — स्वतंत्रता की भावना में मुक्त। आप कोड को उन्हीं शर्तों के तहत उपयोग, अध्ययन, संशोधन और पुनर्वितरित कर सकते हैं।</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>सोर्स कोड</h3><p>पूरा सोर्स कोड Bitbucket पर सार्वजनिक रूप से उपलब्ध है:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>आप वहाँ कोड ब्राउज़ कर सकते हैं, समस्याएँ दर्ज कर सकते हैं, या रिपॉजिटरी फोर्क कर सकते हैं।</p><h3>योगदान</h3><p>Pull requests स्वागत योग्य हैं। योगदान के तरीके:</p><ul><li><strong>अनुवाद</strong> — किसी भाषा में सुधार करें या नई भाषा जोड़ें। संबंधित <code>lib/lang.ec.??.php</code> फ़ाइल में बदलाव के साथ pull request खोलें।</li><li><strong>बग रिपोर्ट</strong> — किसी भी कैलकुलेटर पेज पर फीडबैक फॉर्म का उपयोग करें, या Bitbucket पर समस्या दर्ज करें।</li><li><strong>नए कैलकुलेटर</strong> — हाइड्रोलिक इंजीनियरिंग टूल के लिए विचार जो क्षेत्रीय कार्यकर्ताओं और सिंचाई पेशेवरों की सेवा करें, विशेष रूप से स्वागत योग्य हैं। रिपॉजिटरी में <code>CLAUDE.md</code> डेवलपर गाइड देखें।</li><li><strong>होस्टिंग</strong> — यदि आप सीमित कनेक्टिविटी वाले क्षेत्र के लिए इन कैलकुलेटरों को मिरर कर सकते हैं, तो कृपया संपर्क करें।</li></ul><h3>ऑफ़लाइन उपयोग</h3><p>ये कैलकुलेटर एक प्रोग्रेसिव वेब ऐप (PWA) के रूप में काम करते हैं। इंटरनेट से जुड़े होने पर किसी भी कैलकुलेटर पेज पर जाएँ, और आपका ब्राउज़र सभी कैलकुलेटरों को स्वचालित रूप से कैश कर लेगा। उसके बाद, सभी कैलकुलेटर ऑफ़लाइन काम करते हैं — इंटरनेट की आवश्यकता नहीं।</p><p>Android या iOS पर, अपने ब्राउज़र की "होम स्क्रीन में जोड़ें" सुविधा का उपयोग करके EngCalcs को अपने डिवाइस पर एक ऐप के रूप में इंस्टॉल करें। डेस्कटॉप पर, अपने ब्राउज़र के एड्रेस बार में इंस्टॉल आइकन देखें।</p><p>आप अपने ब्राउज़र के "इस रूप में सहेजें…" मेनू का उपयोग करके किसी भी कैलकुलेटर को एकल उपयोग के लिए सहेज भी सकते हैं।</p><h3>संपर्क</h3><p>Tom Haws — हाइड्रोलिक इंजीनियर और इन कैलकुलेटरों के लेखक।<br />किसी भी कैलकुलेटर पेज पर फीडबैक फॉर्म का उपयोग करें, या <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a> पर सोर्स कोड देखें।</p>';
$ec_lang['contact_title']='HawsEDC संपर्क';
$ec_lang['contactSendMessage']='Tom Haws को संदेश भेजें';
$ec_lang['contactYourName']='आपका नाम:';
$ec_lang['contactYourEmail']='आपका ई-मेल पता:';
$ec_lang['contactSubject']='विषय:';
$ec_lang['contact_message']='संदेश:';
$ec_lang['contactSpamPrefix']='पाँच जमा एक बराबर';
$ec_lang['contactSpamPostfix']='(कृपया अंग्रेज़ी में लिखें। 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='संदेश भेजें';
$ec_lang['contact_success']='आपका समय लेने के लिए धन्यवाद।';
// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['rc_main_menu']='चट्टानी ढाल संरचना डिज़ाइन (Robinson)';
$ec_lang['rc_main_title']='मुफ्त ऑनलाइन चट्टानी ढाल संरचना डिज़ाइन कैलकुलेटर — Robinson (1998)';
$ec_lang['rc_main_desc']='तीव्र ढाल चैनल चट्टान अस्तर आकार — Robinson, Rice &amp; Kadavy (1998)';
$ec_lang['rc_S0']='तीव्र ढाल चैनल तल ढाल, S<sub>0</sub>';
$ec_lang['rc_qt']='<span class="ec-help" title="तीव्र ढाल चैनल इनलेट पर प्रति इकाई चौड़ाई प्रवाह। तल चौड़ाई B वाले चैनल में कुल प्रवाह Q के लिए, q_t = Q / B उपयोग करें।">कुल इकाई प्रवाह, q<sub>t</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_np']='चट्टान अस्तर सरंध्रता, n<sub>p</sub>';
$ec_lang['rc_sg']='<span class="ec-help" title="पानी की तुलना में घनत्व। सामान्य कुचली ग्रेनाइट या बेसाल्ट के लिए ≈ 2.65। Robinson वैध सीमा: 2.54 से 2.82।">चट्टान आपेक्षिक घनत्व, sg <span class="ec-tip">?</span></span>';
$ec_lang['rc_SD']='<span class="ec-help" title="श्रेणीकरण मानक विचलन। एकसमान चट्टान ≈ 1.25। Robinson वैध सीमा: 1.15 से 1.47।">श्रेणीकरण SD = D<sub>84.1</sub>/D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_yn']='<span class="ec-help" title="ताल बनना (Hp > yn) अच्छा है — अपस्ट्रीम कटाव कम करता है। (USDA)">इनलेट चैनल में सामान्य गहराई, y<sub>n</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_D50']='<span class="ec-help" title="समी. 1 (S0 &lt; 0.10) या समी. 2 (0.10-0.40)। वैध: D50 15-278 mm, S0 0.02-0.40। सीमा के बाहर: बहिर्वेशित।">आवश्यक माध्यिका चट्टान आकार, D<sub>50</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_eq_used']='लागू समीकरण';
$ec_lang['rc_sg_check']='आपेक्षिक घनत्व जाँच';
$ec_lang['rc_SD_check']='श्रेणीकरण SD जाँच';
$ec_lang['rc_sg_ok']='sg वैध सीमा में';
$ec_lang['rc_sg_ok_tip']='2.54–2.82 (Robinson)';
$ec_lang['rc_sg_low']='sg Robinson सीमा से नीचे';
$ec_lang['rc_sg_low_tip']='वैध सीमा: 2.54–2.82';
$ec_lang['rc_sg_high']='sg Robinson सीमा से ऊपर';
$ec_lang['rc_sg_high_tip']='वैध सीमा: 2.54–2.82';
$ec_lang['rc_SD_ok']='SD वैध सीमा में';
$ec_lang['rc_SD_ok_tip']='1.15–1.47 (Robinson)';
$ec_lang['rc_SD_low']='SD Robinson सीमा से नीचे';
$ec_lang['rc_SD_low_tip']='वैध सीमा: 1.15–1.47';
$ec_lang['rc_SD_high']='SD Robinson सीमा से ऊपर';
$ec_lang['rc_SD_high_tip']='वैध सीमा: 1.15–1.47';
$ec_lang['rc_layer']='चट्टान परत मोटाई (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='शीर्ष क्रेस्ट वक्र त्रिज्या (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='शीर्ष क्रेस्ट वक्र चाप लंबाई';
$ec_lang['rc_apron_length']='<span class="ec-help" title="तीव्र ढाल चैनल की चट्टान अस्तर के संरचनात्मक समर्थन के लिए आवश्यक। &quot;निर्गम खंड और अनुप्रवाह चैनल प्रतिरोध के परिणामस्वरूप उत्पन्न न्यूनतम अनुप्रवाह जल निर्गम खंड में चट्टान अस्तर की स्थिरता सुनिश्चित करने के लिए पर्याप्त है।&quot; (Robinson)">निर्गम एप्रन लंबाई (15 × D<sub>50</sub>) <span class="ec-tip">?</span></span>';
$ec_lang['rc_n_chute']='तीव्र ढाल चैनल में Manning खुरदरापन, n';
$ec_lang['rc_Vm']='<span class="ec-help" title="q_t का वह भाग जो चट्टान के छिद्रों से बहता है। शेष q_s सतह पर बहता है। कोणीय कुचली चट्टान के लिए डिफ़ॉल्ट n_p = 0.45।">चट्टान आवरण से गुज़रता वेग, V<sub>m</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_qm']='आवरण से इकाई प्रवाह, q<sub>m</sub>';
$ec_lang['rc_qs']='सतही इकाई प्रवाह, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='चट्टान अस्तर सतह के ऊपर प्रवाह गहराई, d';
$ec_lang['rc_Hp']='<span class="ec-help" title="ताल बनना (Hp > yn) अच्छा है — अपस्ट्रीम कटाव कम करता है। (USDA)">इनलेट वियर शीर्ष, H<sub>p</sub> <span class="ec-tip">?</span></span>';
$ec_lang['rc_ponding_check']='इनलेट पर ताल बनने की जाँच';
$ec_lang['rc_pond_ok']='H<sub>p</sub> > y<sub>n</sub> — अपस्ट्रीम में ताल बनना';
$ec_lang['rc_pond_ok_tip']='तीव्र ढाल चैनल इनलेट के अपस्ट्रीम में ताल बनना अच्छा है; यह अपस्ट्रीम कटाव को कम करता है। (USDA)';
$ec_lang['rc_pond_warn']='H<sub>p</sub> ≤ y<sub>n</sub> — कोई ताल नहीं बनता — इनलेट कटाव की संभावना';
$ec_lang['rc_pond_warn_tip']='तीव्र ढाल चैनल इनलेट के अपस्ट्रीम में कोई ताल नहीं बनता; अपस्ट्रीम कटाव हो सकता है। (USDA)';
$ec_lang['rc_eq1']='समी. 1 (S<sub>0</sub> < 0.10) — सौम्य ढाल';
$ec_lang['rc_eq2']='समी. 2 (0.10 ≤ S<sub>0</sub> ≤ 0.40) — तीव्र ढाल';
$ec_lang['rc_eq_warn_low']='S<sub>0</sub> < 0.02 — Robinson सत्यापन सीमा से नीचे';
$ec_lang['rc_eq_warn_high']='S<sub>0</sub> > 0.40 — Robinson सत्यापन सीमा से ऊपर';
$ec_lang['rc_notes_1_term']='चट्टान साइज़िंग समीकरण';
$ec_lang['rc_notes_1_def']='Robinson, Rice &amp; Kadavy (1998) ने तीव्र ढाल चैनल की ढाल और इकाई प्रवाह के आधार पर माध्यिका चट्टान अस्तर आकार D<sub>50</sub> के लिए दो अनुभवजन्य समीकरण विकसित किए। समीकरण 1 सौम्य ढालों के लिए लागू होता है (S<sub>0</sub> &lt; 0.10); समीकरण 2 तीव्र ढालों के लिए लागू होता है (0.10 &le; S<sub>0</sub> &le; 0.40)। दोनों समीकरणों में q<sub>t</sub> m²/s में आवश्यक है और D<sub>50</sub> mm में प्राप्त होता है। सत्यापित सीमा 0.02 ≤ S<sub>0</sub> ≤ 0.40 है।';
$ec_lang['rc_notes_2_term']='इकाई प्रवाह';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> तीव्र ढाल चैनल क्रेस्ट पर कुल इकाई प्रवाह है (प्रति इकाई चौड़ाई कुल प्रवाह)। तल चौड़ाई B और कुल प्रवाह Q वाले चैनल के लिए, q<sub>t</sub> ≈ Q / B अनुमानित करें, या तीव्र ढाल चैनल इनलेट पर क्रांतिक गहराई की स्थिति से इसकी गणना करें।';
$ec_lang['rc_notes_3_term']='चट्टान आवरण से प्रवाह';
$ec_lang['rc_notes_3_def']='कुल प्रवाह का एक भाग चट्टान अस्तर के छिद्रों से होकर बहता है (आवरण प्रवाह q<sub>m</sub>); शेष भाग चट्टान की सतह के ऊपर बहता है (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>)। प्रवाह गहराई d की गणना तीव्र ढाल चैनल खुरदरापन n का उपयोग करते हुए सतही प्रवाह q<sub>s</sub> पर Manning के समीकरण से की जाती है। कोणीय कुचली चट्टान के लिए डिफ़ॉल्ट सरंध्रता n<sub>p</sub> = 0.45 विशिष्ट है।';
$ec_lang['rc_notes_5_term']='वैध चट्टान आकार सीमा';
$ec_lang['rc_notes_5_def']='समीकरण D<sub>50</sub> की 15 mm से 278 mm की सीमा का उपयोग करके विकसित किए गए थे। इस सीमा के बाहर के परिणाम बहिर्वेशित हैं और इन्हें अतिरिक्त इंजीनियरिंग निर्णय के साथ उपयोग किया जाना चाहिए।';
$ec_lang['rc_notes_6_term']='निर्गम एप्रन ऊँचाई';
$ec_lang['rc_notes_6_def']='निर्गम खंड में चट्टान अस्तर के शीर्ष की ऊँचाई अनुप्रवाह चैनल तल की ऊँचाई पर या उससे नीचे होनी चाहिए। यदि यह अधिक है, तो निर्गम चट्टान अस्थिर होगी।';
$ec_lang['rc_notes_7_def']='जब इनलेट चैनल में सामान्य गहराई q<sub>t</sub> को पारित करने के लिए आवश्यक वियर शीर्ष (H<sub>p</sub>) से कम होती है, तो तीव्र ढाल चैनल इनलेट के अपस्ट्रीम प्रतिबंधित प्रवाह या ताल बनना होता है। यह सामान्यतः स्वीकार्य है — ताल बनना वेग को कम करता है और अपस्ट्रीम कटाव को रोकता है। जाँचने के लिए: दी गई q<sub>t</sub> और क्रेस्ट चौड़ाई के लिए H<sub>p</sub> ज्ञात करने हेतु वियर प्रवाह कैलकुलेटर का उपयोग करें, और इसकी तुलना इनलेट चैनल की सामान्य गहराई से करें। यदि H<sub>p</sub> सामान्य गहराई से अधिक है, तो ताल बनेगा।';
$ec_lang['rc_notes_4_term']='संदर्भ';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., and Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">तीव्र ढाल चैनल चट्टान अस्तर का डिज़ाइन</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. USDA ARS उसी विधि पर आधारित एक <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">Excel स्प्रेडशीट</a> भी प्रकाशित करता है।';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'फ़िल्टर';
$ec_lang['rc_sketch_top_crest_curve'] = 'शीर्ष क्रेस्ट वक्र';
$ec_lang['rc_sketch_outlet_apron']    = 'निर्गम एप्रन';
$ec_lang['rc_sketch_radius']          = 'त्रिज्या';
// Irrigation Pressure. 45 additional keys below (ip_main_menu through ip_notes_5_def)
$ec_lang['ip_main_menu']='सिंचाई दाब';
$ec_lang['ip_main_title']='मुफ़्त ऑनलाइन सिंचाई दाब और वितरण एकरूपता कैलकुलेटर';
$ec_lang['ip_main_desc']='परीक्षण शाखा दाब और एकरूपता अनुमान';
$ec_lang['ip_h_supply']='आपूर्ति दाब';
$ec_lang['ip_elev_supply']='आपूर्ति स्तर, z<sub>supply</sub>';
$ec_lang['ip_q_design']='उत्सर्जक डिज़ाइन प्रवाह, q<sub>design</sub>';
$ec_lang['ip_h_design']='उत्सर्जक डिज़ाइन दाब';
$ec_lang['ip_x']='<span class="ec-help" title="मानक गैर-क्षतिपूरक उत्सर्जकों के लिए 0.5; दाब-क्षतिपूरक उत्सर्जकों के लिए लगभग 0">उत्सर्जक निर्वहन घातांक, x <span class="ec-tip">?</span></span>';
$ec_lang['ip_reach_table_title']='परीक्षण पथ';
$ec_lang['ip_group_reach']='खंड';
$ec_lang['ip_group_upstream']='ऊर्ध्वप्रवाह';
$ec_lang['ip_group_downstream']='अनुप्रवाह';
$ec_lang['ip_group_loss']='हानि';
$ec_lang['ip_is_lateral']='<span class="ec-help" title="चेक किया गया: यह खंड परीक्षण पार्श्व नली का एक खंड है, जिसे व्यक्तिगत उत्सर्जकों द्वारा निकाला जाता है। चेक नहीं किया गया: यह खंड एक मुख्य नली है, केवल परीक्षण पथ पर न होने वाली पार्श्व नलियों को प्रवाह पास करता है।">पार्श्व <span class="ec-tip">?</span></span>';
$ec_lang['ip_count']='<span class="ec-help" title="पार्श्व नली पंक्तियाँ: केवल इस खंड में उत्सर्जक। मुख्य नली पंक्तियाँ: इस खंड से शाखा लेने वाली अन्य पार्श्व नलियों पर कुल उत्सर्जक। परीक्षण पार्श्व नली के अपने निकालने के ठीक स्थान पर खंड के लिए, इसमें मुख्य नली के साथ उस बिंदु के बाद कोई भी पार्श्व नली, या समान जंक्शन साझा करने वाली (उदा. विपरीत-पक्ष की पार्श्व नली) भी शामिल है — उनका प्रवाह भी इसी खंड से शाखा लेता है।">उत्सर्जक <span class="ec-tip">?</span></span>';
$ec_lang['ip_length']='L';
$ec_lang['ip_diameter']='D';
$ec_lang['ip_roughness']='e';
$ec_lang['ip_elev_ds']='<span class="ec-help" title="इस खंड का डाउनस्ट्रीम-छोर स्तर। आंतरिक पंक्तियों में वैकल्पिक (रिक्त छोड़ने पर समतल / ऊपर के नोड के समान डिफ़ॉल्ट)। अंतिम पंक्ति में आवश्यक: वह मान अंतिम उत्सर्जक का स्तर है, जो सीधे आवश्यक आपूर्ति दाब निर्धारित करता है।">DS स्तर <span class="ec-tip">?</span></span>';
$ec_lang['ip_elev_ds_missing_warn']='अंतिम उत्सर्जक स्तर (अंतिम पंक्ति) रिक्त छोड़ दी गई और समतल को डिफ़ॉल्ट दिया गया — सटीक परिणाम के लिए इसे दर्ज करें';
$ec_lang['ip_flow']='प्रवाह';
$ec_lang['ip_press']='दाब';
$ec_lang['ip_hf']='h<sub>f</sub>';
$ec_lang['ip_hm']='h<sub>m</sub>';
$ec_lang['ip_hl']='<span class="ec-help" title="खंड की कुल हानि, h_f + h_m">h<sub>L</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_pressure_warn']='कम/नकारात्मक दाब — अवायुमंडलीय स्थितियों के लिए जाँचें';
$ec_lang['ip_pressure_warn_short']='कम';
$ec_lang['ip_h_far']='अंतिम उत्सर्जक दाब';
$ec_lang['ip_q_supply']='<span class="ec-help" title="केवल मॉडल किए गए परीक्षण पथ में प्रवेश करने वाला प्रवाह — पूरे क्षेत्र/प्रणाली के लिए नीचे अनुप्रयोग डिज़ाइन में Q_zone देखें।">परीक्षण पथ आपूर्ति प्रवाह, Q<sub>supply</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_critical']='अंतिम उत्सर्जक प्रवाह, q<sub>last</sub>';
$ec_lang['ip_q_avg_lateral']='औसत उत्सर्जक प्रवाह (परीक्षण पार्श्व), q<sub>avg</sub>';
$ec_lang['ip_dp_avg']='<span class="ec-help" title="विशिष्ट पार्श्व इस परीक्षण पार्श्व की तुलना में कितने अधिक (या कम) दाब पर चलता है, इसका अनुमान। परीक्षण पार्श्व को जानबूझकर सबसे बुरी स्थिति माना जाता है, इसलिए इसका अपना औसत क्षेत्र औसत का न्यून अनुमान है — 0 पर छोड़ने पर, नीचे एकरूपता जाँच और अनुप्रयोग-डिज़ाइन के आंकड़े परीक्षण पार्श्व के अपने (संभवतः आशावादी) औसत का ज्यों-का-त्यों उपयोग करते हैं।">अनु. ∆दाब, औसत बनाम परीक्षण पार्श्व <span class="ec-tip">?</span></span>';
$ec_lang['ip_q_avg_field']='<span class="ec-help" title="q_avg_lateral का प्रत्येक पार्श्व पंक्ति के दाब पर, ऊपर दर्ज किए गए दाब अंतर सहित, पुनर्मूल्यांकन — परीक्षण पार्श्व के प्रतिनिधि न होकर सबसे बुरी स्थिति माने जाने को सुधारने का प्रयास। यह नीचे एकरूपता जाँच और अनुप्रयोग-डिज़ाइन खंड दोनों को इनपुट करता है।">अनु. क्षेत्र-औसत उत्सर्जक प्रवाह, q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_du_estimate']='<span class="ec-help" title="अंतिम उत्सर्जक का परिकलित प्रवाह, अनुमानित क्षेत्र-औसत उत्सर्जक प्रवाह से विभाजित — यह मानक निम्न-चतुर्थांश वितरण एकरूपता (निम्न-समूह औसत ÷ जनसंख्या माध्य) का सन्निकटन है; लेकिन यह एक पूर्ण-क्षेत्र सांख्यिकीय नमूने के बजाय एक छोटे मॉडल किए गए नमूने और उपयोगकर्ता-अनुमानित सुधार पर आधारित है। 1 पर या उससे ऊपर के मान संभव और मान्य हैं: इनका अर्थ केवल यह है कि अंतिम उत्सर्जक का दाब अनुमानित क्षेत्र औसत पर या उससे ऊपर है, इसलिए न्यूनतम दाब का बिंदु कोई अन्य उत्सर्जक है। ऐसा इसलिए हो सकता है क्योंकि अंतिम उत्सर्जक निचली भूमि पर है या क्योंकि ऊपर का ∆दाब अनुमान बहुत छोटा है।">एकरूपता जाँच, q<sub>last</sub>/q<sub>avg,field</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_worst_case_warn']='परीक्षण उत्सर्जक पर दाब ≥ आपूर्ति दाब है। यह शायद सबसे बुरी स्थिति वाला उत्सर्जक नहीं है, या पाइपों को छोटा किया जा सकता है।';
$ec_lang['ip_q_ratio']='<span class="ec-help" title="यह हमारे मानक एकरूपता माप के सन्निकटन से भिन्न है।">अंतिम उत्सर्जक प्रवाह ÷ डिज़ाइन प्रवाह, q<sub>last</sub>/q<sub>design</sub> <span class="ec-tip">?</span></span>';
$ec_lang['ip_no_solution']='कोई समाधान नहीं: आवश्यक आपूर्ति दाब दर्ज किए गए आपूर्ति दाब से अधिक है। आपूर्ति दाब बढ़ाएँ, माँग कम करें, या एक बड़ी पाइप का उपयोग करें।';
$ec_lang['ip_notes_1_def']='अंतिम (सबसे दूरस्थ) उत्सर्जक पर दाब का अनुमान लगाता है, फिर ऊर्जा ग्रेड लाइन को आपूर्ति की ओर वापस, खंड दर खंड, घर्षण और स्थानीय हानियों को जोड़ते हुए आगे बढ़ाता है। स्तर और वेग शीर्ष को प्रत्येक नोड पर घटाकर वहाँ का वास्तविक दाब रिपोर्ट किया जाता है। अनुमानित दूर-छोर दाब को तब तक समायोजित किया जाता है (समद्विभाजन द्वारा) जब तक कि गणना की गई आवश्यक आपूर्ति दाब दर्ज की गई आपूर्ति दाब से मेल न खाए — यह मैनिंग पाइप प्रवाह कैलकुलेटर के पाइप-प्रवाह समाधानकर्ता द्वारा संबोधित की गई वही बंद-लूप समस्या है, जिसे एक शाखायुक्त नेटवर्क तक विस्तारित किया गया है।';
$ec_lang['ip_notes_2_term']='मुख्य बनाम पार्श्व खंड';
$ec_lang['ip_notes_2_def']='प्रत्येक पंक्ति आपूर्ति से अंतिम उत्सर्जक तक एकल हाइड्रॉलिक रूप से सबसे बुरी पथ (परीक्षण पथ) पर एक खंड है। एक मुख्य खंड केवल परीक्षण पथ पर न होने वाली पार्श्व नलियों को प्रवाह पास करता है, इसलिए इसकी निकासी एक सरल गुणा है (डिज़ाइन प्रवाह × खंड की कुल उत्सर्जक संख्या) — कोई स्थानीय दाब संवेदनशीलता नहीं। मुख्य नली एक साझा ट्रंक पाइप है, इसलिए मुख्य नली के उस खंड में जो परीक्षण पार्श्व नली पर समाप्त होता है, न केवल अपने स्वयं के छोरों के बीच की पार्श्व नलियाँ शामिल होनी चाहिए, बल्कि उस बिंदु से आगे मुख्य नली पर स्थित कोई भी पार्श्व नली, या समान जंक्शन साझा करने वाली (उदा. विपरीत-पक्ष की पार्श्व नली) भी शामिल होनी चाहिए — उनका प्रवाह अलग होने से पहले इसी खंड से होकर गुजरता है, चाहे वे इस तालिका में कहीं भी दिखें या न दिखें। एक पार्श्व खंड स्वयं परीक्षण पार्श्व नली का एक भाग है: उत्सर्जक निर्वहन वास्तविक स्थानीय दाब से q = k·H<sup>x</sup> के माध्यम से परिकलित होता है, और घर्षण हानि को Christiansen के F(n) कारक द्वारा घटाया जाता है ताकि खंड में प्रत्येक उत्सर्जक द्वारा जल निकालने के साथ प्रवाह घटने को ध्यान में रखा जा सके।';
$ec_lang['ip_notes_3_term']='सीमाएँ';
$ec_lang['ip_notes_3_def']='एक निश्चित आपूर्ति दाब (कोई पंप वक्र नहीं), केवल एक परीक्षण पथ (पूरा खेत नहीं), और एक 2-पैरामीटर उत्सर्जक वक्र (दाब-क्षतिपूरक उत्सर्जक का सन्निकटन करने के लिए घातांक को 0 के निकट सेट करें) को मॉडल करता है। दो भिन्न एकरूपता अनुपात रिपोर्ट किए जाते हैं, जिन्हें जानबूझकर अलग रखा गया है: q<sub>last</sub>/q<sub>avg,field</sub> मानक निम्न-चतुर्थांश वितरण एकरूपता (निम्न-समूह औसत ÷ जनसंख्या माध्य) का सन्निकटन है; लेकिन यह मानक पूर्ण-क्षेत्र सांख्यिकीय नमूने के बजाय एक छोटे मॉडल किए गए नमूने और उपयोगकर्ता-अनुमानित सुधार पर आधारित है। साथ ही, परीक्षण पार्श्व को जानबूझकर सबसे बुरी स्थिति माना जाता है, इसलिए इसका कच्चा, असुधारित औसत वास्तविक क्षेत्र औसत को कम आंकेगा और एकरूपता को वास्तविकता से बेहतर दिखाएगा; ∆दाब इनपुट विशेष रूप से इस पूर्वाग्रह का प्रतिकार करने के लिए मौजूद है। एकरूपता के लिए 1 पर या उससे ऊपर के मान अब भी संभव हैं: इनका अर्थ केवल यह है कि अंतिम उत्सर्जक का दाब अनुमानित क्षेत्र औसत पर या उससे ऊपर है, इसलिए न्यूनतम दाब का बिंदु कोई अन्य उत्सर्जक है। ऐसा इसलिए हो सकता है क्योंकि अंतिम उत्सर्जक निचली भूमि पर है या क्योंकि ∆दाब अनुमान बहुत छोटा है। q<sub>last</sub>/q<sub>design</sub> निर्माता के रेटेड प्रवाह के विरुद्ध एक भिन्न, गैर-एकरूपता जाँच है — यह समग्र रूप से अधिक- या कम-दाबित प्रणाली का पता लगाने के लिए उपयोगी है, लेकिन यह एकरूपता संख्या के साथ पढ़ी जाने वाली एक अलग जाँच है, क्योंकि डिज़ाइन/रेटेड प्रवाह का प्रणाली के वास्तविक माध्य परिचालन दाब से कोई आवश्यक संबंध नहीं है।';
$ec_lang['ip_notes_4_def']='Christiansen, J.E. (1942). "Irrigation by sprinkling." California Agricultural Experiment Station Bulletin 670. सूक्ष्म-सिंचाई डिज़ाइन के लिए ASAE/ASABE मानक समान बहु-आउटलेट घर्षण-हानि पद्धति का उपयोग करते हैं।';
$ec_lang['ip_notes_5_term']='अनुप्रयोग डिज़ाइन';
$ec_lang['ip_notes_5_def']='अनुप्रयोग दर और प्रणाली/क्षेत्र प्रवाह अनुमानित क्षेत्र-औसत उत्सर्जक प्रवाह (q<sub>avg,field</sub> — परीक्षण पार्श्व का अपना औसत, दर्ज किए गए ∆दाब अनुमान से सुधारा गया) का उपयोग करते हैं, न कि किसी अनुमानित दर का: PR = q<sub>avg,field</sub> / A<sub>e</sub>, जो सुधारे गए मॉडल किए गए मान से संचालित है। रिक्ति और प्रणाली-व्यापी पार्श्व/उत्सर्जक गणना यहाँ अलग इनपुट हैं क्योंकि परीक्षण पथ केवल एक सबसे बुरी स्थिति वाली शाखा को मॉडल करता है, खेत की हर पार्श्व नली को नहीं।';
$ec_lang['irr_card_pressure_head']='सिंचाई दाब और एकरूपता';
$ec_lang['irr_card_pressure_desc']='वितरण एकरूपता का अनुमान वास्तविक परीक्षण-पथ दाब से लगाने के लिए — केवल कैटलॉग उत्सर्जक प्रवाह दर से नहीं — मुख्य-पार्श्व-उत्सर्जक शाखा के साथ दाब और प्रवाह प्रोफाइल को मॉडल करें।';
