<?php

// àáèéìíòóùú — All missing text declarations will fall back to English.

// Units (alphabetical order)
$ec_lang['u_depthFrac']="frazione";
$ec_lang['u_depthPercent']="%";
$ec_lang['u_ft2']="ft^2";
$ec_lang['u_ft3ps']="cfs";
$ec_lang['u_fth2o']="ft H2O";
$ec_lang['u_ft']="ft";
$ec_lang['u_ftps']="ft/s";
$ec_lang['u_gpm']="gal/min";
$ec_lang['u_gradePercent']="% pendenza";
$ec_lang['u_grade']="pendenza";
$ec_lang['u_in2']="poll^2";
$ec_lang['u_inh2o']="poll H2O";
$ec_lang['u_in']="poll";
$ec_lang['u_knpcm2']="kN/cm^2";
$ec_lang['u_knpm2']="kN/m^2";
$ec_lang['u_kpa']="kPa";
$ec_lang['u_lps']="l/s";
$ec_lang['u_m2']="m^2";
$ec_lang['u_m3ps']="m^3/s";
$ec_lang['u_mgd']="MGD";
$ec_lang['u_mh2o']="m H2O";
$ec_lang['u_mld']="Ml/d";
$ec_lang['u_m']="m";
$ec_lang['u_mm2']="mm^2";
$ec_lang['u_mmh2o']="mm H2O";
$ec_lang['u_mm']="mm";
$ec_lang['u_mps']="m/s";
$ec_lang['u_npm2']="N/m^2";
$ec_lang['u_pa']="Pa";
$ec_lang['u_psf']="lb/ft^2";
$ec_lang['u_psi']="psi";
$ec_lang['u_s']="s";
$ec_lang['u_acft']="ac-ft";
$ec_lang['u_ft3']="ft^3";
$ec_lang['u_m3']="m^3";
$ec_lang['u_kw']='kW';
$ec_lang['u_mw']='MW';
$ec_lang['u_kwh_yr']='kWh/yr';
$ec_lang['u_mwh_yr']='MWh/yr';
$ec_lang['u_hp']='hp';

// Page text
$ec_lang['menu_brand']='Calcolatori HawsEDC';
$ec_lang['menu_main_list']='Elenco calcolatori';
$ec_lang['menu_main_hydraulics']='Idraulica';
$ec_lang['menu_main_language']='Lingua';
$ec_lang['menu_more']='Altro';
$ec_lang['template_welcome']='>> Lasciate le paure alla porta; qui l\'amore è la nostra lingua. Non state rovinando tutto. Godetevi anche gli <a target="_blank" href="https://hawsedc.com/download.php">strumenti gratuiti HawsEDC per AutoCAD.</a> <<';
$ec_lang['template_translation_help']='Hai una grande visione per una calcolatrice da aggiungere qui?  Puoi aiutarmi a migliorare le traduzioni, programmare o ospitare questi calcolatori?  ';
$ec_lang['template_feedback']='Condividi le tue preziose opinioni o suggerimenti. Questo calcolatore gratuito ha superato le tue aspettative in ogni modo?';
$ec_lang['template_printable_title']='Titolo stampabile';
$ec_lang['template_printable_subtitle']='Sottotitolo stampabile';
$ec_lang['index_title']='Calcolatori ingegneristici gratuiti online';
$ec_lang['calc_set_units']='Imposta unità:';
$ec_lang['points_data_help']='(o Copia/Incolla usando l\'area dati)';
$ec_lang['points_data_title']='Dati punti<br />(separati da virgola o tabulazione)';
$ec_lang['points_data_copy']='Copia';
$ec_lang['points_data_paste']='Incolla';
$ec_lang['calc_inputs']='Dati di input';
$ec_lang['calc_results']='Risultati';
$ec_lang['view_hide_line']='[Nascondi questa riga]';
$ec_lang['view_printable']='Versione stampabile (ricaricare per ripristinare)';
$ec_lang['ec_name_label']='Salva questo calcolo:';
$ec_lang['ec_name_placeholder']='Nome';
$ec_lang['ec_name_hint']='Salva questi dati inseriti nell\'URL per segnalibri, recupero della cronologia e condivisione';
// Darcy-Weisbach
$ec_lang['dw_main_menu']='Perdita di carico Darcy-Weisbach';
$ec_lang['dw_main_title']='Calcolatore gratuito online perdita di carico Darcy-Weisbach';
$ec_lang['dw_main_desc']='Perdita di carico in tubazione con Darcy-Weisbach a diametro, scabrezza e portata dati';
$ec_lang['dw_roughness']='Scabrezza assoluta Darcy-Weisbach, e';
$ec_lang['dw_kinematic_viscosity']='Viscosità cinematica, ν <span title="1×10⁻⁶ m²/s for clean water at 20°C" class="ec-tip">?</span>';
$ec_lang['dw_reynolds_number']='Numero di Reynolds, Re';
$ec_lang['dw_flow_regime']='Regime di flusso';
$ec_lang['dw_regime_laminar']='laminare';
$ec_lang['dw_regime_transitional']='di transizione';
$ec_lang['dw_regime_turbulent']='turbolento';
$ec_lang['dw_friction_factor_method']='Metodo del coefficiente di attrito';
$ec_lang['dw_friction_factor']='Coefficiente di attrito, f';
// Hazen-Williams
$ec_lang['hw_main_menu']='Perdita di carico Hazen-Williams';
$ec_lang['hw_main_title']='Calcolatore gratuito online perdita di carico Hazen-Williams';
$ec_lang['hw_main_desc']='Perdita di carico in tubazione con Hazen-Williams a diametro, scabrezza e portata dati';
$ec_lang['hw_hgl_1']='HGL a valle';
$ec_lang['hw_hgl_2']='HGL a monte';
$ec_lang['hw_roughness']='Coefficiente Hazen-Williams, C';
// Manning Irregular
$ec_lang['mi_menu']='Canale irregolare Manning';
$ec_lang['mi_main_title']='Calcolatore gratuito online canale irregolare Manning';
$ec_lang['mi_main_desc']='Calcolatore flusso uniforme canale irregolare con formula di Manning';
$ec_lang['mi_waterSurfaceElevation']='Quota pelo libero';
$ec_lang['mi_q_617']='Q';
$ec_lang['mi_xSecPoints']='Punti sezione trasversale';
$ec_lang['mi_groupPoint']='Punto';
$ec_lang['mi_groupSegment']='Segmento';
$ec_lang['mi_groupRegion']='Regione';
$ec_lang['mi_station']='Dist.';
$ec_lang['mi_elevation']='Quota';
$ec_lang['mi_d50in']='Dim.<br />med.<br />roccia<br />rivestim.';
$ec_lang['mi_n']='n<br />del seg-<br />mento';
$ec_lang['mi_is_bank']='R<sub>h</sub>, Q<br />boundary<br />regione<br />(Sponda)';
$ec_lang['mi_tau']='Tensione<br />di fondo<br />τ';
$ec_lang['mi_t']='T';
$ec_lang['mi_pw']='P<sub>w</sub>';
$ec_lang['mi_a']='A';
$ec_lang['mi_rh']='R<sub>h</sub>';
$ec_lang['mi_n617']='n com-<br />posto';
$ec_lang['mi_v617']='v';
$ec_lang['mi_fr617']='Fr';
$ec_lang['mi_hv617']='H<sub>v</sub>';
$ec_lang['mi_q617']='Q';
$ec_lang['mi_notes']='Note';
$ec_lang['mi_notes_1_term']='n composto';
$ec_lang['mi_notes_1_def']='Questo calcolatore segue il manuale di riferimento HEC-RAS nel calcolo del n composto della regione usando Chow 1959, pagina 136, equazione 6-17 (non 6-18).';
$ec_lang['mi_notes_2_term']='Rivestimento in roccia';
$ec_lang['mi_notes_2_def']='Usare il Calcolatore Canale Trapezoidale Manning per progettare il rivestimento in roccia. Questo calcolatore è più adatto per sezioni naturali.';
// Manning Pipe Flow
$ec_lang['mpf_main_menu']='Portata in tubazione Manning';
$ec_lang['mpf_main_title']='Calcolatore gratuito online portata in tubazione Manning';
$ec_lang['mpf_main_desc']='Formula di Manning per flusso uniforme in tubazione a pendenza e profondità date';
$ec_lang['mpf_spreadheet_notice']='Scopri la versione foglio di calcolo di questo calcolatore';
$ec_lang['mpf_pipe_diameter']='Diametro tubazione, d<sub>0</sub>';
$ec_lang['mpf_manningRoughness']='Scabrezza Manning, n';
$ec_lang['mpf_friction_slope']='Pendente idraulica (possibilmente <a target="_blank" href="../pressureslope.php">?</a> uguale alla pendenza della tubazione), S<sub>0</sub>';
$ec_lang['mpf_depth_ratio']='Rapporto di riempimento, y/d<sub>0</sub>';
$ec_lang['mpf_see_notes']='(Vedi note)';
$ec_lang['mpf_flow']='Portata, Q';
$ec_lang['mpf_velocity']='Velocità, v';
$ec_lang['mpf_velocity_head']='Altezza cinetica, h<sub>v</sub>';
$ec_lang['mpf_flow_area']='Area bagnata, a';
$ec_lang['mpf_pipe_area']='Area totale tubazione, a0';
$ec_lang['mpf_area_ratio']='Rapporto di riempimento area, a/a0';
$ec_lang['mpf_wetted_perimeter']='Perimetro bagnato, P<sub>w</sub>';
$ec_lang['mpf_hydraulic_radius']='Raggio idraulico, R<sub>h</sub>';
$ec_lang['mpf_top_width']='Larghezza pelo libero, T';
$ec_lang['mpf_froude_number']='Numero di Froude, F';
$ec_lang['mpf_shear_stress']='Tensione tangenziale media (forza trattiva), tau';
$ec_lang['mpf_full_flow']='Portata a sezione piena, Q0';
$ec_lang['mpf_full_flow_ratio']='Rapporto alla portata piena, Q/Q0';
$ec_lang['mpf_note_1']='<dl><dt>Questo è il flusso e la profondità all\'interno di una tubazione <em>infinitamente lunga</em>.</dt><dd>L\'immissione del flusso nella tubazione può richiedere un\'altezza idraulica significativamente maggiore. Aggiungere almeno 1,5 volte l\'altezza cinetica per l\'altezza idraulica o <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">vedere il tutorial di 2 minuti</a> per i calcoli standard del livello idraulico nei tombini con HY-8.</dd>';
$ec_lang['mpf_solve_for_dd0']='Calcola y/d<sub>0</sub> dato Q';
$ec_lang['mpf_solve_desc']='Usando D<sub>0</sub>, n, e S<sub>0</sub> dal modulo, trova il minimo y/d<sub>0</sub> per un dato Q.';
$ec_lang['mpf_solve_button']='Calcola';
// Manning Pipe Head Loss
$ec_lang['mphl_main_menu']='Perdita di carico in tubazione Manning';
$ec_lang['mphl_main_title']='Calcolatore gratuito online perdita di carico in tubazione Manning';
$ec_lang['mphl_main_desc']='Formula di Manning perdita di carico a portata piena data';
$ec_lang['mphl_pipe_length']='Lunghezza tubazione, L';
$ec_lang['mphl_area']='Area, A';
$ec_lang['mphl_total_junction_k']='Coefficiente totale perdita di carico ai giunti, k';
$ec_lang['mphl_friction_slope']='Pendente di attrito';
$ec_lang['mphl_friction_loss']='Perdita per attrito, H<sub>f</sub>';
$ec_lang['mphl_junction_loss']='Perdita ai giunti, H<sub>m</sub>';
$ec_lang['mphl_total_loss']='Perdita totale, H<sub>l</sub>';
$ec_lang['mphl_egl_1']='EGL a valle';
$ec_lang['mphl_egl_2']='EGL a monte';
$ec_lang['mphl_hgl_2']='HGL a monte in tubazione ' . $ec_lang['mpf_see_notes'];
$ec_lang['mphl_note_1']='<dl><dt>Per una condizione di imbocco aperto (tombino), è necessario verificare le condizioni di controllo all\'imbocco.</dt><dd>1. L\'HGL a monte non può essere inferiore alla quota di deflusso a profondità normale a monte (o inferiore alla tubazione!).</dd><dd>2. Il livello idraulico di un tombino è meglio rappresentato dall\'EGL a monte che dall\'HGL a monte.</dd><dd>3. <a target="_blank" href="https://www.youtube.com/watch?v=0O1Ezk8SVxU">Vedere il tutorial di 2 minuti</a> per semplici calcoli standard del livello idraulico nei tombini con HY-8.</dd>';
// Manning Trapezoid
$ec_lang['mtc_menu']='Canale trapezoidale Manning';
$ec_lang['mtc_main_title']='Calcolatore gratuito online formula di Manning canale trapezoidale';
$ec_lang['mtc_main_desc']='Flusso uniforme Manning in canale trapezoidale a pendenza e profondità date';
$ec_lang['mtc_bottom_width']='Larghezza di fondo, b';
$ec_lang['mtc_side_slope_1']='Scarpata lato 1 (orizz./vert.)';
$ec_lang['mtc_side_slope_2']='Scarpata lato 2 (orizz./vert.)';
$ec_lang['mtc_channel_slope']='Pendenza canale, S';
$ec_lang['mtc_flow_depth']='Profondità di flusso, y';
$ec_lang['mtc_bend_angle']='Angolo di curva <a target="_blank" href="riprap-bend-angle.png" title="Clicca per immagine">?</a> (per dimensionamento massi)';
$ec_lang['mtc_sgrock']='Peso specifico della roccia (2,65)';
$ec_lang['mtc_d50_in']='Dimensione roccia di progetto, D50';
$ec_lang['mtc_n_strickler']='n per dimensione roccia di progetto secondo Strickler';
$ec_lang['mtc_n_blodgett']='n per dimensione roccia di progetto secondo Blodgett';
$ec_lang['mtc_n_bathurst']='n per dimensione roccia di progetto secondo Bathurst';
$ec_lang['mtc_blodgett_v_bathurst']='Blodgett vs. Bathurst';
$ec_lang['mtc_d50_bottom']='Dimensione roccia angolare richiesta sul fondo, D50 (Isbash & MC) <span title="Secondo Isbash (1936) e Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z1']='Dimensione roccia angolare richiesta scarpata 1, D50 (Isbash & MC) <span title="Secondo Isbash (1936) e Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_z2']='Dimensione roccia angolare richiesta scarpata 2, D50 (Isbash & MC) <span title="Secondo Isbash (1936) e Maricopa County, Arizona, US." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['mtc_d50_mra']='Dimensione roccia angolare richiesta, D50 (Maynord, Ruff, e Abt 1989)';
$ec_lang['mtc_d50_searcy']='Dimensione roccia angolare richiesta, D50 (Searcy 1967)';
$ec_lang['mtc_note_1']='<dl><dt>Iterazione automatica dimensionamento roccia e scabrezza</dt><dd>Scegliere un pulsante radio per la scabrezza (BB raccomandato) e uno per la dimensione roccia di progetto (Isbash raccomandato). Regolare profondità e fattore di sicurezza della roccia per ottenere il flusso desiderato con una dimensione roccia uniforme. Ogni modifica ai dati avvia il ciclo iterativo: 1. La scabrezza viene calcolata dalla dimensione roccia di progetto. 2. La scabrezza richiesta viene copiata nella scabrezza di input. 3. Il flusso nel canale e la dimensione roccia richiesta vengono calcolati. 4. La dimensione roccia di progetto viene aggiornata. 5. Si ripete fino a convergenza.</dd><dt>Calcolatore base (senza iterazione)</dt><dd>Inserire il valore di scabrezza desiderato. Ignorare l\'area di input della dimensione roccia di progetto.</dd></dl>';
// Robinson Rock Chute
$ec_lang['rrc_main_menu']='Scivolo in pietrame di Robinson';
$ec_lang['rrc_main_desc']='Foglio di calcolo per la progettazione di scivoli in pietrame secondo Robinson';
// Weir Flow Simple
$ec_lang['ws_main_menu']='Sfioratore semplice';
$ec_lang['ws_main_title']='Calcolatore gratuito online sfioratore largo a cresta semplice';
$ec_lang['ws_main_desc']='Calcolatore portata sfioratore largo a cresta semplice';
$ec_lang['ws_weirLength']='Lunghezza sfioratore, l';
$ec_lang['ws_headWaterHeight']='Altezza pelo libero a monte, h';
$ec_lang['ws_weirCoefficient']='Coefficiente sfioratore, Cw';
$ec_lang['ws_notes_heading']='Note';
$ec_lang['ws_notes_we_term']='Equazione sfioratore';
// Weir Flow Irregular
$ec_lang['wi_menu']='Sfioratore irregolare';
$ec_lang['wi_main_title']='Calcolatore gratuito online sfioratore irregolare a profondità variabile';
$ec_lang['wi_main_desc']='Calcolatore portata sfioratore irregolare';
$ec_lang['wi_headWaterelevation']='Quota pelo libero a monte';
$ec_lang['wi_weirPoints']='Punti sfioratore';
$ec_lang['wi_station']='Distanza';
$ec_lang['wi_elevation']='Quota';
$ec_lang['wi_pondingHeight']='Altezza di invaso';
$ec_lang['wi_incrementalFlow']='Portata incrementale';
$ec_lang['wi_cumulativeFlow']='Portata cumulativa';
$ec_lang['wi_save_and_calculate']='Salva e calcola';
$ec_lang['wi_notes_we_term']='Equazione sfioratore';
$ec_lang['wi_notes_we_def']='q = se (lunghezza = 0) allora 0 altrimenti se (slope=0) allora cw*lunghezza*d<sub>0</sub><sup>1.5</sup> altrimenti cw/(2.5*pendenza) * (d<sub>0</sub><sup>2.5</sup> - d<sub>1</sub><sup>2.5</sup>) dove d<sub>1</sub> e d<sub>0</sub> sono sempre positivi o zero';
// Orifice Flow
$ec_lang['or_main_menu']='Deflusso a orifizio';
$ec_lang['or_main_title']='Calcolatore gratuito online deflusso a orifizio';
$ec_lang['or_main_desc']='Deflusso a orifizio — libero o sommerso';
$ec_lang['or_shape']='Forma dell\'apertura';
$ec_lang['or_shape_circular']='Circolare';
$ec_lang['or_shape_rectangular']='Rettangolare';
$ec_lang['or_diameter']='Diametro o altezza, D <span title="Diameter for circular; height for rectangular" class="ec-tip">?</span>';
$ec_lang['or_width']='Larghezza, W <span title="Rectangular openings only" class="ec-tip">?</span>';
$ec_lang['or_invert']='Quota di inverto <span title="Parte inferiore dell\'apertura" class="ec-tip">?</span>';
$ec_lang['or_hwe']='Quota pelo libero a monte';
$ec_lang['or_twe']='Quota pelo libero a valle';
$ec_lang['or_cd']='Coefficiente di deflusso, C<sub>d</sub>';
$ec_lang['or_centroid_elev']='Quota centroide';
$ec_lang['or_head']='Carico efficace, h';
$ec_lang['or_area']='Area apertura, A';
$ec_lang['or_flow']='Portata, Q';
$ec_lang['or_velocity']='Velocità, v';
$ec_lang['or_regime']='Verifica regime orifizio';
$ec_lang['or_regime_valid']='Uscita libera — regime orifizio valido ✓';
$ec_lang['or_regime_submerged']='Orifizio sommerso (TWE sopra il centroide) — valido ✓';
$ec_lang['or_regime_warn']='Attenzione: pelo libero a monte sotto la chiave — non è regime orifizio';
$ec_lang['or_regime_twe_above_hwe']='Attenzione: acqua a valle (TWE) sopra acqua a monte (HWE) — verificare i dati';
$ec_lang['or_notes_1_term']='Equazione orifizio';
$ec_lang['or_notes_1_def']='Q = C<sub>d</sub> × A × √(2gh). Uscita libera: h = HWE − centroide. Sommerso (TWE sopra la soletta): h = HWE − TWE.';
$ec_lang['or_notes_2_term']='Regime orifizio';
$ec_lang['or_notes_2_def']='Le equazioni del deflusso a orifizio si applicano quando il pelo libero a monte è sopra la chiave (sommità) dell\'apertura. Quando è sotto la chiave, utilizzare un\'equazione di sfioratore.';
$ec_lang['or_notes_3_term']='Coefficiente di deflusso';
$ec_lang['or_notes_3_def']='C<sub>d</sub> varia da circa 0,60 a 0,65 per orifizi a spigolo vivo. Imbocchi arrotondati o rientranti hanno valori diversi. Vedere <a target="_blank" href="https://www.engineeringtoolbox.com/orifice-nozzle-venture-d_590.html">Engineering Toolbox</a> o il Manuale di Riferimento Idraulico HEC-RAS.';
$ec_lang['or_notes_4_term']='Sommersione';
$ec_lang['or_notes_4_def']='Quando TWE è sopra la soletta dell\'apertura, la calcolatrice applica automaticamente l\'equazione dell\'orifizio sommerso usando h = HWE − TWE. Quando TWE è pari o inferiore alla soletta, si assume uscita libera e h = HWE − centroide.';
// Orifice Drain Time
$ec_lang['odt_main_menu']='Tempo di svuotamento a orifizio';
$ec_lang['odt_main_title']='Calcolatore gratuito online tempo di svuotamento a orifizio';
$ec_lang['odt_main_desc']='Tempo di svuotamento vasca tramite orifizio — Metodo volume conico';
$ec_lang['odt_h1_elev']='Quota pelo libero iniziale <span title="Quota pelo libero iniziale" class="ec-tip">?</span>';
$ec_lang['odt_a1']='Area iniziale, A<sub>1</sub>';
$ec_lang['odt_h2_elev']='Quota pelo libero finale';
$ec_lang['odt_h_orifice']='Quota centroide orifizio';
$ec_lang['odt_a0']='Area alla quota dell\'orifizio, A<sub>0</sub>';
$ec_lang['odt_a_ending']='Area finale, A<sub>2</sub> <span title="Interpolata dal modello conico alla quota finale" class="ec-tip">?</span>';
$ec_lang['odt_h2_check']='Verifica quota finale';
$ec_lang['odt_h2_ok']='Quota finale sopra la sommità dell\'orifizio ✓';
$ec_lang['odt_h2_warn']='Attenzione: quota finale pari o inferiore alla sommità orifizio (centroide + D/2)';
$ec_lang['odt_d']='D orifizio <span title="Diametro (circolare) o altezza (rettangolare)" class="ec-tip">?</span>';
$ec_lang['odt_w']='Larghezza orifizio, W <span title="Solo per rettangolare" class="ec-tip">?</span>';
$ec_lang['odt_t_sec']='Tempo di svuotamento (s)';
$ec_lang['odt_t_min']='Tempo di svuotamento (min)';
$ec_lang['odt_t_hr']='Tempo di svuotamento (h)';
$ec_lang['odt_t_day']='Tempo di svuotamento (giorni)';
$ec_lang['odt_notes_1_term']='Formula';
$ec_lang['odt_notes_1_def']='t = √H<sub>1</sub> / (C<sub>d</sub> A<sub>or</sub> √(2g)) × (2A<sub>x</sub>/5 + 8√(A<sub>x</sub>A<sub>0</sub>)/15 + 16A<sub>0</sub>/15) fornisce il tempo di svuotamento dal carico H all\'orifizio. Tempo di svuotamento = t(H<sub>1</sub>,A<sub>1</sub>,A<sub>0</sub>) − t(H<sub>2</sub>,A<sub>2</sub>,A<sub>0</sub>), dove H<sub>1</sub> = quota iniziale − quota orifizio, H<sub>2</sub> = quota finale − quota orifizio.';
$ec_lang['odt_notes_2_term']='Metodo';
$ec_lang['odt_notes_2_def']='Il metodo del volume conico modella la vasca come sezione conica tra l\'area iniziale A<sub>1</sub> al pelo libero iniziale e l\'area A<sub>0</sub> alla quota del centroide dell\'orifizio. A<sub>2</sub>, l\'area della vasca alla quota finale, è interpolata da A<sub>1</sub> e A<sub>0</sub> usando il modello conico. Il tempo di svuotamento dalla quota iniziale alla finale equivale al tempo totale da H<sub>1</sub> all\'orifizio meno il tempo rimanente da H<sub>2</sub> all\'orifizio.';
$ec_lang['odt_h1']='Carico iniziale, H<sub>1</sub> <span title="Quota pelo libero iniziale meno quota centroide orifizio" class="ec-tip">?</span>';
$ec_lang['odt_q_max']='Portata massima, Q<sub>max</sub>';
$ec_lang['odt_vol']='Volume svuotato';
$ec_lang['odt_sketch_start']='Inizio';
$ec_lang['odt_sketch_end']='Fine';
// Erosion Setback
$ec_lang['essc_btbw']='Larghezza di sponda a sponda';
$ec_lang['essc_mcr']='Raggio minimo di curvatura';
$ec_lang['essc_q']='Portata, Q';
// Contact

// Irrigation
$ec_lang['irr_main_menu']='Misurazione del Flusso di Irrigazione';
$ec_lang['irr_main_title']='Calcolatrici Online Gratuite per la Misurazione del Flusso di Irrigazione';
$ec_lang['irr_main_desc']='Misurazione del Flusso di Irrigazione — Stramazzi e Orifizi';
$ec_lang['contact_title']='Contatti HawsEDC';
$ec_lang['contactSendMessage']='Invia un messaggio a Tom Haws';
$ec_lang['contactYourName']='Nome:';
$ec_lang['contactYourEmail']='Indirizzo e-mail:';
$ec_lang['contactSubject']='Oggetto:';
$ec_lang['contact_message']='Messaggio:';
$ec_lang['contactSpamPrefix']='Cinque più uno è';
$ec_lang['contactSpamPostfix']='(Scrivere in inglese. 1=one 2=two 3=three 4=four 5=five 6=six 7=seven +=plus 5+1=6)';
$ec_lang['contactSubmitButton']='Invia messaggio';
$ec_lang['contact_success']='Grazie per aver dedicato il tempo a scrivere.';


// Micro-Hydro Power
$ec_lang['mhp_main_menu']='Micro-Idroelettrico';
$ec_lang['mhp_main_title']='Calcolatore Gratuito di Potenza Micro-Idroelettrica';
$ec_lang['mhp_main_desc']='Calcolatore di Potenza Micro-Idroelettrica ad Acqua Fluente';
$ec_lang['mhp_flow']='Portata, Q';
$ec_lang['mhp_gross_head']='Altezza lorda, H<sub>gross</sub>';
$ec_lang['mhp_diameter']='Diametro della condotta forzata, D';
$ec_lang['mhp_length']='Lunghezza della condotta forzata, L';
$ec_lang['mhp_roughness']='Rugosità della tubazione, e';
$ec_lang['mhp_km']='Coefficiente di perdita minore, k<sub>m</sub> <span title="Somma di tutti i coefficienti di perdita nei raccordi e negli imbocchi della condotta forzata" class="ec-tip">?</span>';
$ec_lang['mhp_nu']='Viscosità cinematica, ν <span title="1×10⁻⁶ m²/s per acqua pulita a circa 20°C" class="ec-tip">?</span>';
$ec_lang['mhp_efficiency']='Rendimento dell\'impianto, η (0–1)';
$ec_lang['mhp_velocity']='Velocità di flusso, v';
$ec_lang['mhp_vel_check']='Verifica della velocità';
$ec_lang['mhp_f']='Fattore di attrito, f';
$ec_lang['mhp_hf']='Perdita di carico per attrito, h<sub>f</sub>';
$ec_lang['mhp_hm']='Perdita di carico minore, h<sub>m</sub>';
$ec_lang['mhp_hl']='Perdita totale nella condotta forzata, h<sub>L</sub>';
$ec_lang['mhp_hl_check']='Verifica della perdita di carico';
$ec_lang['mhp_hnet']='Altezza netta, H<sub>net</sub>';
$ec_lang['mhp_power']='Potenza prodotta, P';
$ec_lang['mhp_annual_kwh']='Energia annua al 100% di capacità';
$ec_lang['mhp_vel_ok']='1–3 m/s — nell\'intervallo target ✓';
$ec_lang['mhp_vel_low']='Velocità bassa — rischio di sedimentazione e trascinamento d\'aria.';
$ec_lang['mhp_vel_high']='Velocità elevata — rischio di colpo d\'ariete e perdite localizzate.';
$ec_lang['mhp_vel_ok_short']='OK';
$ec_lang['mhp_vel_high_short']='Alto';
$ec_lang['mhp_vel_low_short']='Basso';
$ec_lang['mhp_hl_ok']='entro il target del 10% ✓';
$ec_lang['mhp_hl_warn']='supera il target del 10% — considerare una tubazione più grande ⚠';
$ec_lang['mhp_hl_bad']='supera il 20% — ridimensionare la tubazione';
$ec_lang['mhp_notes_1_term']='Perdita di carico';
$ec_lang['mhp_notes_1_def']='Perdita totale nella condotta forzata h<sub>L</sub> = h<sub>f</sub> + h<sub>m</sub>, dove h<sub>f</sub> = f(L/D)(v²/2g) è la perdita per attrito di Darcy-Weisbach e h<sub>m</sub> = k<sub>m</sub>·v²/2g comprende imbocchi, curve e valvole. Altezza netta H<sub>net</sub> = H<sub>gross</sub> − h<sub>L</sub>.';
$ec_lang['mhp_notes_2_term']='Velocità';
$ec_lang['mhp_notes_2_def']='Obiettivo: 1–3 m/s. Al di sotto di 1 m/s la tubazione risulta sovradimensionata per la portata; al di sopra di 3 m/s aumentano le perdite per attrito e il rischio di colpo d\'ariete.';
$ec_lang['mhp_notes_3_term']='Obiettivo di perdita di carico';
$ec_lang['mhp_notes_3_def']='Perdite nella condotta forzata inferiori al 10% dell\'altezza lorda sono generalmente economiche. Il compromesso ottimale tra costo della tubazione e potenza persa si attesta spesso intorno al 4–6% per i siti ad alta valorizzazione dell\'energia elettrica.';
$ec_lang['mhp_notes_4_term']='Perdite minori k<sub>m</sub>';
$ec_lang['mhp_notes_4_def']='Valori tipici: imbocco con spigolo vivo 0,5, ogni curva a 45° 0,2–0,3, saracinesca (completamente aperta) 0,1, valvola a farfalla 0,2. Sommare tutti i raccordi per ottenere il k<sub>m</sub> totale. Il valore predefinito 1,5 presuppone un imbocco e due curve.';
$ec_lang['mhp_notes_5_term']='Rugosità della tubazione e';
$ec_lang['mhp_notes_5_def']='Rugosità assoluta tipica: acciaio (nuovo) 0,046 mm, acciaio (usato) 0,15 mm, HDPE 0,003 mm, PVC/uPVC 0,0015 mm, calcestruzzo 0,3–3 mm. L\'HDPE è comune nelle condotte forzate di piccoli impianti micro-idroelettrici.';
$ec_lang['mhp_notes_6_term']='Rendimento';
$ec_lang['mhp_notes_6_def']='Il rendimento tipico dell\'impianto η varia da 0,70 a 0,85 per le turbine Pelton e cross-flow comuni negli impianti micro-idroelettrici. Usare 0,75 come stima conservativa iniziale.';
$ec_lang['mhp_notes_7_term']='Energia annua';
$ec_lang['mhp_notes_7_def']='L\'energia annua presuppone un funzionamento continuativo a portata piena (8760 ore/anno). La produzione reale sarà inferiore a causa della variazione stagionale di portata, dei tempi di fermo per manutenzione e del fattore di carico.';

// About
$ec_lang['about_main_menu']='Informazioni';
$ec_lang['install_main_menu']='Installa';
$ec_lang['install_main_title']='Installa EngCalcs';
$ec_lang['install_main_desc']='Aggiungi al tuo dispositivo per l\'uso offline';
$ec_lang['contact_main_menu']='Contatto';
$ec_lang['about_main_title']='Informazioni sui calcolatori HawsEDC';
$ec_lang['about_main_desc']='Missione, open source e contributi';

// Drip / Sprinkler Application Rate
$ec_lang['u_lph']="L/hr";
$ec_lang['u_gph']="gal/hr";
$ec_lang['u_mmph']="mm/hr";
$ec_lang['u_inph']="in/hr";
$ec_lang['ds_main_menu']='Portata di adacquamento — goccia a goccia/irrigatori';
$ec_lang['ds_main_title']='Calcolatore gratuito online della portata di adacquamento per irrigazione a goccia/irrigatori';
$ec_lang['ds_main_desc']='Irrigazione a goccia e a pioggia — portata di adacquamento';
$ec_lang['ds_q_avg']='Portata dell\'erogatore, q';
$ec_lang['ds_se']='Distanza tra erogatori, S<sub>e</sub>';
$ec_lang['ds_sl']='Distanza tra le manichette, S<sub>l</sub>';
$ec_lang['ds_n_e']='Erogatori per manichetta, n<sub>e</sub>';
$ec_lang['ds_n_l']='Manichette per zona, n<sub>l</sub>';
$ec_lang['ds_d']='Profondità di adacquamento obiettivo, d';
$ec_lang['ds_a_e']='Superficie per erogatore, A<sub>e</sub>';
$ec_lang['ds_pr']='Tasso di applicazione, PR';
$ec_lang['ds_q_lat']='Portata per manichetta, Q<sub>lat</sub>';
$ec_lang['ds_q_sys']='Portata di zona, Q<sub>zone</sub>';
$ec_lang['ds_t_run']='Tempo di esercizio (ore)';
$ec_lang['ds_notes_1_term']='Portata di adacquamento';
$ec_lang['ds_notes_1_def']='PR = q / A<sub>e</sub>, dove A<sub>e</sub> = S<sub>e</sub> × S<sub>l</sub> è la superficie servita da ciascun erogatore. Una portata di adacquamento più bassa lascia più tempo all\'infiltrazione — importante su suoli pesanti o campi in pendenza.';
$ec_lang['ds_notes_2_term']='Tempo di irrigazione';
$ec_lang['ds_notes_2_def']='Tempo di irrigazione = profondità obiettivo ÷ portata di adacquamento. Su suoli in pendenza o compatti, suddividere il tempo di irrigazione in due o tre cicli più brevi con pause tra loro per evitare il ruscellamento superficiale.';
// Canal Seepage / Conveyance Efficiency. Prefix cs_.
$ec_lang['cs_main_menu']='Percolazione dal Canale';
$ec_lang['cs_main_title']='Calcolatore Gratuito Online della Perdita per Percolazione e dell\'Efficienza di Convogliamento del Canale';
$ec_lang['cs_main_desc']='Percolazione dal Canale & Efficienza di Convogliamento — Metodo Afflusso-Deflusso';
$ec_lang['cs_Q_in']='Afflusso, Q<sub>in</sub>';
$ec_lang['cs_Q_out']='Deflusso, Q<sub>out</sub>';
$ec_lang['cs_L']='Lunghezza del tratto, L';
$ec_lang['cs_wp']='Perimetro bagnato, P<sub>w</sub>';
$ec_lang['cs_Q_loss']='Portata di perdita per percolazione, Q<sub>loss</sub>';
$ec_lang['cs_loss_check']='Verifica misurazione';
$ec_lang['cs_pct_loss']='Frazione persa';
$ec_lang['cs_Ec']='Efficienza di convogliamento, E<sub>c</sub>';
$ec_lang['cs_Ec_check']='Valutazione dell\'efficienza';
$ec_lang['cs_Vol_day']='Volume giornaliero perso';
$ec_lang['cs_Vol_year']='Volume annuale perso';
$ec_lang['cs_Q_loss_per_L']='Perdita per unità di lunghezza, Q<sub>loss</sub>/L';
$ec_lang['cs_water_value']='Valore dell\'acqua';
$ec_lang['cs_lining_cost']='Costo del rivestimento';
$ec_lang['cs_Ec_target']='Obiettivo di rivestimento, E<sub>c,target</sub> <span title="Obiettivo di efficienza di convogliamento dopo il rivestimento; frazione 0–1" class="ec-tip">?</span>';
$ec_lang['cs_lining_area']='Area di rivestimento, L × P<sub>w</sub>';
$ec_lang['cs_annual_value_lost']='Valore annuo perso';
$ec_lang['cs_annual_value_recovered']='Valore annuo recuperato';
$ec_lang['cs_lining_total_cost']='Costo totale del rivestimento';
$ec_lang['cs_payback_years']='Payback period <span title="Simple payback = total lining cost ÷ annual value recovered" class="ec-tip">?</span>';
$ec_lang['cs_loss_positive']='Qin > Qout — percolazione rilevata ✓';
$ec_lang['cs_loss_zero']='Qin = Qout — nessuna perdita misurabile';
$ec_lang['cs_loss_negative']='Attenzione: Qout > Qin — verificare le misurazioni ⚠';
$ec_lang['cs_Ec_good']='Buona — Ec ≥ 80% ✓';
$ec_lang['cs_Ec_fair']='Discreta — Ec 60–80%';
$ec_lang['cs_Ec_poor']='Scarsa — Ec < 60% ⚠';
$ec_lang['cs_notes_1_term']='Metodo';
$ec_lang['cs_notes_1_def']='Il metodo afflusso-deflusso stima la percolazione misurando la portata all\'inizio e alla fine di un tratto di canale: Q<sub>loss</sub> = Q<sub>in</sub> − Q<sub>out</sub>. L\'efficienza di convogliamento E<sub>c</sub> = Q<sub>out</sub> / Q<sub>in</sub>. Il volume annuale presuppone un funzionamento continuo a piena portata; la perdita effettiva è inferiore per canali stagionali o a portata parziale.';
$ec_lang['cs_notes_2_term']='Valutazioni dell\'efficienza';
$ec_lang['cs_notes_2_def']='Canali in terra non rivestiti tipici: E<sub>c</sub> = 60–80%. Canali in terra ben mantenuti: 75–85%. Canali rivestiti in calcestruzzo: 90–98%. Perdite per percolazione superiori al 30% dell\'afflusso giustificano spesso un investimento nel rivestimento. (USBR, FAO)';
$ec_lang['cs_notes_3_term']='Ammortamento del rivestimento';
$ec_lang['cs_notes_3_def']='Inserire il valore dell\'acqua e il costo del rivestimento in qualsiasi valuta coerente. Area di rivestimento = lunghezza del tratto × perimetro bagnato — il perimetro bagnato della sezione trasversale del canale alla profondità di flusso misurata (larghezza di fondo più entrambe le sponde bagnate). Il valore annuo recuperato presuppone che il canale rivestito raggiunga l\'E<sub>c</sub> obiettivo in modo continuativo. Il tempo di ammortamento effettivo sarà più lungo per canali stagionali o se il rivestimento non raggiunge l\'efficienza obiettivo.';
$ec_lang['cs_notes_4_term']='Riferimento';
$ec_lang['cs_notes_4_def']='USBR <em>Water Measurement Manual</em>, 3a ed. (2001). FAO Irrigation and Drainage Paper 57 (1999).';

$ec_lang['irr_intro_html']='<p>Stramazzi e orifizi sono gli strumenti standard sul campo per misurare il flusso d\'acqua nei sistemi di irrigazione. Seleziona la calcolatrice che corrisponde alla tua struttura:</p>';
$ec_lang['irr_card_weir_uniform_head']='Stramazzo — Soglia Larga (Larghezza Uniforme)';
$ec_lang['irr_card_weir_uniform_desc']='Misura il flusso sulla soglia di una diga di derivazione, struttura di controllo o tavola stramazzi. Inserisci la lunghezza dello stramazzo e la profondità dell\'acqua sopra la soglia.';
$ec_lang['irr_card_weir_irregular_head']='Stramazzo — Profilo Irregolare';
$ec_lang['irr_card_weir_irregular_desc']='Da usare quando la soglia dello stramazzo non ha un\'unica elevazione uniforme — sfioratori naturali, strutture di caduta con larghezza variabile o strutture di controllo a sezioni multiple.';
$ec_lang['irr_card_orifice_head']='Orifizio — Paratoia o Presa Tubazione';
$ec_lang['irr_card_orifice_desc']='Misura il flusso attraverso una paratoia, una presa tubazione o un\'apertura di tombino. Gestisce automaticamente sia la caduta libera sia le condizioni di sommersione (contropressione a valle).';
$ec_lang['irr_card_canal_head']='Progetto & Analisi del Canale';
$ec_lang['irr_card_canal_desc']='Progetta o verifica un canale irriguo usando la formula di Manning. Usa la calcolatrice Trapezoidale per i nuovi canali; la calcolatrice Irregolare per sezioni naturali o costruite esistenti.';
$ec_lang['irr_card_drip_head']='Progetto Goccia a Goccia & Aspersione';
$ec_lang['irr_card_drip_desc']='Calcola il tasso di applicazione, l\'uniformità di distribuzione, il flusso laterale, il flusso di zona e il tempo di esercizio per un sistema di irrigazione a goccia o a pioggia. Inserisci il flusso dell\'emettitore, la spaziatura e la profondità target.';
$ec_lang['irr_card_seepage_head']='Percolazione dal Canale & Efficienza di Convogliamento';
$ec_lang['irr_card_seepage_desc']='Stima la perdita per percolazione da un tratto di canale usando misurazioni di afflusso e deflusso. Calcola l\'efficienza di convogliamento e la perdita d\'acqua annuale per aiutare a stabilire le priorità di rivestimento.';
$ec_lang['irr_quickref_html']='<h3>Riferimento Rapido</h3><dl><dt>Diga di derivazione o struttura di controllo</dt><dd>Misura la profondità dell\'acqua sopra la soglia dello stramazzo. Usa <a href="Weir-Flow-Simple.php">Stramazzo Semplice</a> per una soglia uniforme, o <a href="Weir-Flow-Irregular.php">Stramazzo Irregolare</a> per una soglia profilata o a gradini.</dd><dt>Paratoia o presa tubazione</dt><dd>Misura la quota del pelo libero a monte e a valle (o la quota di fondo se la scarica è libera). Usa <a href="Orifice.php">Flusso per Orifizio</a>. Per una tubazione circolare, D = diametro della tubazione; per una paratoia rettangolare, inserisci la larghezza W e l\'altezza D.</dd><dt>Tempo di svuotamento di serbatoio o laghetto</dt><dd>Usa <a href="Orifice-Drain-Time.php">Tempo di Svuotamento per Orifizio</a> per stimare quanto tempo ci vuole per abbassare il livello di un laghetto o serbatoio attraverso un orifizio sul fondo — utile per la pianificazione dello stoccaggio irriguo.</dd><dt>Standard sul campo</dt><dd>Le equazioni di flusso per stramazzo e orifizio usate qui corrispondono alle procedure del <em>Water Measurement Manual</em> USBR (3a ed.), comunemente richieste da gestori dell\'acqua e distretti irrigui.</dd></dl>';
$ec_lang['about_body_html']='<h3>Missione</h3><p>Le Calcolatrici di Ingegneria HawsEDC esistono per servire ingegneri e operatori sul campo in tutto il mondo — in particolare coloro che lavorano in regioni con scarsità d\'acqua, risorse limitate o poco servite. Questi strumenti fanno parte di una missione umanitaria più ampia: dire a ogni essere umano nel modo più pratico ed efficace possibile che è amato e prezioso per sempre, che non ha nulla da temere e che non rovinerà tutto.</p><p>Le calcolatrici sono il mezzo. La destinazione è un mondo libero dalla sofferenza.</p><h3>Licenza Open Source</h3><p>Tutto il codice è rilasciato sotto la <a target="_blank" href="https://www.gnu.org/licenses/gpl-3.0.html">Licenza Pubblica Generale GNU v3.0 o successiva</a> — libero come nella libertà. Puoi usare, studiare, modificare e ridistribuire il codice secondo gli stessi termini.</p><p>Copyright © 2009–2026 Thomas Gail Haws.</p><h3>Codice Sorgente</h3><p>Il codice sorgente completo è disponibile pubblicamente su Bitbucket:</p><p><a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">bitbucket.org/hawstom/engcalcs</a></p><p>Puoi sfogliare il codice, segnalare problemi o fare un fork del repository lì.</p><h3>Contribuire</h3><p>Le pull request sono benvenute. Modi per contribuire:</p><ul><li><strong>Traduzioni</strong> — migliora o aggiungi una lingua. Apri una pull request con modifiche al file <code>lib/lang.ec.??.php</code> pertinente.</li><li><strong>Segnalazioni di bug</strong> — usa il modulo di feedback su qualsiasi pagina della calcolatrice, o segnala un problema su Bitbucket.</li><li><strong>Nuove calcolatrici</strong> — le idee per strumenti di ingegneria idraulica al servizio di operatori sul campo e professionisti dell\'irrigazione sono particolarmente benvenute. Consulta la guida per sviluppatori <code>CLAUDE.md</code> nel repository.</li><li><strong>Hosting</strong> — se puoi ospitare queste calcolatrici per una regione con connettività limitata, contattaci.</li></ul><h3>Uso offline</h3><p>Questi calcolatori funzionano come un\'App Web Progressiva (PWA). Visita qualsiasi pagina del calcolatore mentre sei connesso a internet e il tuo browser memorizzerà automaticamente tutti i calcolatori nella cache. Dopodiché, tutti i calcolatori funzionano offline — senza necessità di internet.</p><p>Su Android o iOS, usa l\'opzione "Aggiungi alla schermata iniziale" del tuo browser per installare EngCalcs come app sul tuo dispositivo. Su desktop, cerca l\'icona di installazione nella barra degli indirizzi del browser.</p><p>Puoi anche salvare qualsiasi calcolatore individuale usando il menu "Salva con nome…" del tuo browser per un utilizzo offline occasionale.</p><h3>Contatto</h3><p>Tom Haws — ingegnere idraulico e autore di queste calcolatrici.<br />Usa il modulo di feedback su qualsiasi pagina della calcolatrice, o accedi al codice sorgente su <a target="_blank" href="https://bitbucket.org/hawstom/engcalcs">Bitbucket</a>.</p>';

// Rock Chute Design (Robinson, Rice & Kadavy 1998). Prefix rc_.
$ec_lang['u_m2ps']='m^2/s';
$ec_lang['u_ft2ps']='cfs/ft';
$ec_lang['rc_main_menu']='Progetto di Scivolo in Pietrame (Robinson)';
$ec_lang['rc_main_title']='Calcolatrice Gratuita per Progetto di Scivolo in Pietrame — Robinson (1998)';
$ec_lang['rc_main_desc']='Dimensionamento del Pietrame per Scivolo — Robinson, Rice & Kadavy (1998)';
$ec_lang['rc_S0']='Pendenza del fondo dello scivolo, S<sub>0</sub>';
$ec_lang['rc_qt']='Portata specifica totale, q<sub>t</sub> <span title="Portata per unità di larghezza all\'ingresso dello scivolo. Per un canale di larghezza di fondo B con portata totale Q, usare q_t = Q / B." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_np']='Porosità del pietrame, n<sub>p</sub>';
$ec_lang['rc_sg']='Peso specifico relativo della roccia, sg <span title="Granito frantumato o basalto tipico ≈ 2,65. Intervallo valido Robinson: 2,54 a 2,82." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_SD']='Gradazione SD = D<sub>84.1</sub>/D<sub>50</sub> <span title="Deviazione standard granulometrica. Roccia uniforme ≈ 1,25. Intervallo valido Robinson: 1,15 a 1,47." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_yn']='Tirante normale nel canale di ingresso, y<sub>n</sub> <span title="Il rigurgito (Hp > yn) è favorevole — riduce l\'erosione a monte. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_D50']='Dimensione mediana richiesta della roccia, D<sub>50</sub> <span title="Eq. 1 (S0 < 0,10) o Eq. 2 (0,10–0,40). Valido: D50 15–278 mm, S0 0,02–0,40. Fuori intervallo: estrapolato." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_eq_used']='Equazione applicata';
$ec_lang['rc_sg_check']='Verifica del peso specifico relativo';
$ec_lang['rc_SD_check']='Verifica della gradazione SD';
$ec_lang['rc_sg_ok']   ='sg nell\'intervallo valido (2,54–2,82) ✓';
$ec_lang['rc_sg_low']  ='Attenzione: sg < 2,54 — al di sotto dell\'intervallo Robinson';
$ec_lang['rc_sg_high'] ='Attenzione: sg > 2,82 — al di sopra dell\'intervallo Robinson';
$ec_lang['rc_SD_ok']   ='SD nell\'intervallo valido (1,15–1,47) ✓';
$ec_lang['rc_SD_low']  ='Attenzione: SD < 1,15 — al di sotto dell\'intervallo Robinson';
$ec_lang['rc_SD_high'] ='Attenzione: SD > 1,47 — al di sopra dell\'intervallo Robinson';
$ec_lang['rc_layer']='Spessore dello strato di pietrame (2 × D<sub>50</sub>)';
$ec_lang['rc_crest_radius']='Raggio di curvatura in sommità (40 × D<sub>50</sub>)';
$ec_lang['rc_crest_length']='Lunghezza d\'arco in sommità';
$ec_lang['rc_apron_length']='Lunghezza del grembiule di uscita (15 × D<sub>50</sub>) <span title="Necessario per il supporto strutturale della roccia dello scivolo. "Il minimo tirante di valle risultante dal tratto di uscita e dalla resistenza del canale a valle è sufficiente a garantire la stabilità del pietrame nel tratto di uscita." (Robinson)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_n_chute']='Rugosità di Manning nello scivolo, n';
$ec_lang['rc_Vm']='Velocità attraverso il mantello di roccia, V<sub>m</sub> <span title="Frazione di qt che scorre attraverso i pori della roccia. Il resto qs scorre in superficie. np predefinito = 0,45 per roccia frantumata angolare." style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_qm']='Portata specifica nel mantello, q<sub>m</sub>';
$ec_lang['rc_qs']='Portata specifica superficiale, q<sub>s</sub> (q<sub>t</sub> − q<sub>m</sub>)';
$ec_lang['rc_d']='Altezza idrica sopra la superficie del pietrame, d';
$ec_lang['rc_Hp']='Carico al soglio di ingresso, H<sub>p</sub> <span title="Il rigurgito (Hp > yn) è favorevole — riduce l\'erosione a monte. (USDA)" style="cursor:help;color:#06c;font-size:0.9em">?</span>';
$ec_lang['rc_ponding_check']='Verifica del rigurgito all\'imbocco';
$ec_lang['rc_pond_ok']  ='Hp > yn — rigurgito a monte ✓';
$ec_lang['rc_pond_warn']='⚠ Hp ≤ yn — nessun rigurgito — verificare l\'imbocco per erosione';
$ec_lang['rc_eq1']='Eq. 1 (S0 < 0,10) — pendenza dolce';
$ec_lang['rc_eq2']='Eq. 2 (0,10 ≤ S0 ≤ 0,40) — pendenza ripida';
$ec_lang['rc_eq_warn_low']='Attenzione: S0 < 0,02 — al di sotto dell\'intervallo di validazione Robinson';
$ec_lang['rc_eq_warn_high']='Attenzione: S0 > 0,40 — al di sopra dell\'intervallo di validazione Robinson';
$ec_lang['rc_notes_1_term']='Equazioni di dimensionamento della roccia';
$ec_lang['rc_notes_1_def']='Robinson, Rice & Kadavy (1998) hanno sviluppato due equazioni empiriche per la dimensione mediana del pietrame D<sub>50</sub> in funzione della pendenza dello scivolo e della portata specifica. L\'equazione 1 si applica a pendenze dolci (S<sub>0</sub> < 0,10); l\'equazione 2 a pendenze ripide (0,10 ≤ S<sub>0</sub> ≤ 0,40). Entrambe le equazioni richiedono q<sub>t</sub> in m²/s e restituiscono D<sub>50</sub> in mm. L\'intervallo validato è 0,02 ≤ S<sub>0</sub> ≤ 0,40.';
$ec_lang['rc_notes_2_term']='Portata specifica';
$ec_lang['rc_notes_2_def']='q<sub>t</sub> è la portata specifica totale alla sommità dello scivolo (portata totale per unità di larghezza). Per un canale di larghezza di fondo B con portata totale Q, q<sub>t</sub> ≈ Q / B, oppure si calcola dalla condizione di tirante critico all\'ingresso dello scivolo.';
$ec_lang['rc_notes_3_term']='Deflusso attraverso il mantello di roccia';
$ec_lang['rc_notes_3_def']='Una frazione della portata totale scorre attraverso i pori del pietrame (portata di mantello q<sub>m</sub>); il resto scorre sulla superficie della roccia (q<sub>s</sub> = q<sub>t</sub> − q<sub>m</sub>). L\'altezza idrica d è calcolata con l\'equazione di Manning applicata alla portata superficiale q<sub>s</sub> usando la rugosità n dello scivolo. La porosità predefinita n<sub>p</sub> = 0,45 è tipica per roccia frantumata angolare.';
$ec_lang['rc_notes_5_term']='Intervallo valido di dimensione della roccia';
$ec_lang['rc_notes_5_def']='Le equazioni sono state sviluppate per un intervallo D<sub>50</sub> da 15 mm a 278 mm. I risultati al di fuori di questo intervallo sono estrapolati e devono essere utilizzati con ulteriore giudizio ingegneristico.';
$ec_lang['rc_notes_6_term']='Quota della superficie del grembiule di uscita';
$ec_lang['rc_notes_6_def']='La quota della sommità del pietrame nel tratto di uscita deve essere pari o inferiore alla quota del fondo del canale a valle. Se è più alta, la roccia di uscita sarà instabile.';
$ec_lang['rc_notes_7_term']='Verifica del rigurgito all\'ingresso';
$ec_lang['rc_notes_7_def']='Quando il tirante normale nel canale di ingresso è inferiore al carico al soglio (H<sub>p</sub>) necessario per transitare q<sub>t</sub>, si verifica un deflusso limitato o un rigurgito a monte del grembiule di ingresso. Ciò è generalmente accettabile — il rigurgito riduce la velocità e previene l\'erosione a monte. Per verificare: utilizzare una calcolatrice di soglio per trovare H<sub>p</sub> per il q<sub>t</sub> e la larghezza di cresta dati, e confrontarlo con il tirante normale del canale di ingresso. Se H<sub>p</sub> supera il tirante normale, si verificherà rigurgito.';
$ec_lang['rc_notes_4_term']='Riferimento';
$ec_lang['rc_notes_4_def']='Robinson, K.M., Rice, C.E., e Kadavy, K.C. (1998). "<a target="_blank" href="https://www.fs.usda.gov/biology/nsaec/fishxing/fplibrary/Robinson_1998_Design_of_Rock_Chutes.pdf">Design of rock chutes</a>." <em>Transactions of the ASAE</em>, 41(3), 621–626. L\'USDA ARS pubblica anche un <a target="_blank" href="https://data.nal.usda.gov/dataset/rock-chute-design">foglio di calcolo Excel</a> basato sullo stesso metodo.';
// Sketch labels
$ec_lang['rc_sketch_filter']          = 'Filtro';
$ec_lang['rc_sketch_top_crest_curve'] = 'Curva di cresta';
$ec_lang['rc_sketch_outlet_apron']    = 'Platea di uscita';
$ec_lang['rc_sketch_radius']          = 'raggio';
// Manning Trapezoid velocity checks
$ec_lang['mtc_vel_check']='Controllo della velocità';
$ec_lang['mtc_vel_ok']='Velocità ragionevole per le ipotesi di flusso uniforme.';
$ec_lang['mtc_vel_high']='Velocità elevata — verificare le perdite di transizione e l\'energia disponibile.';
$ec_lang['mtc_vel_low']='Velocità bassa — rischio di sedimentazione.';
$ec_lang['mtc_vel_ok_short']='OK';
$ec_lang['mtc_vel_high_short']='Alto';
$ec_lang['mtc_vel_low_short']='Basso';
$ec_lang['mtc_note_2_term']='Controllo della velocità';
$ec_lang['mtc_note_2_def']='Velocità elevata implica elevata energia specifica derivante da una caduta disponibile. Tale energia può dissiparsi rapidamente in corrispondenza di espansioni, curve o ostruzioni. Verificare che ciò sia ragionevole per il sito.';
